NPC refactor
space-wizards/space-station-14 pull request #10122
Opened 2022-07-29 00:44 UTC by metalgearsloth

- Prototypes everywhere
- More ECS
- Better debugging tools

2022-08-23 04:01 UTC, metalgearsloth commented
Just needs the collision avoidance split out and dev docs and then it's good for review (the line count is mostly just the debug map).

2022-08-23 08:33 UTC, moonheart08 approved these changes

2022-08-23 08:55 UTC, moonheart08 requested changes

2022-08-23 08:55 UTC, moonheart08 commented on Resources/Textures/Objects/Weapons/Guns/turrets.rsi/meta.json
> +  },
Missing copyright.

2022-08-23 10:51 UTC, moonheart08 approved these changes

2022-09-01 03:03 UTC, mirrorcult submitted a review, later dismissed
a-ok to merge once engine stuff is figured out

2022-09-01 03:03 UTC, mirrorcult commented on Content.Server/NPC/Pathfinding/IPathfindingGraph.cs
> +}
empty?

2022-09-05 14:28 UTC, merged

2023-06-24 00:04 UTC, Partmedia commented
Clicking the link to the docs in the PR description gives me: "Unauthorized You cannot create the page." Has this moved elsewhere?