Add dizziness as a symptom of bloodloss
space-wizards/space-station-14 pull request #10172
Opened 2022-07-30 19:40 UTC by Elijahrane

## About the PR 
It was suggested by someone in idea guys. Helps with our medical diagnostics goals. The start of the Rane blood mechanics arc.

**Changelog**

:cl: Rane
- add: Bloodloss now makes you dizzy.

2022-07-30 20:40 UTC, AJCM-git requested changes
Server crashes if your blood level reaches 0, also, if you are gonna reuse drunkenness like this you should really rebrand it as dizziness component/system

2022-07-30 20:47 UTC, Elijahrane commented
>Server crashes if your blood level reaches 0,
No?
![image](https://user-images.githubusercontent.com/60792108/181995658-1ce8cc18-43b6-464b-b1be-33a798d51113.png)

>also, if you are gonna reuse drunkenness like this you should really rebrand it as dizziness component/system

It's already reused elsewhere

2022-07-30 21:17 UTC, AJCM-git approved these changes

2022-07-31 02:24 UTC, mirrorcult approved these changes

2022-07-31 02:24 UTC, merged