Nukie win conditions
space-wizards/space-station-14 pull request #10220
Opened 2022-08-01 10:42 UTC by vulppine

## About the PR 

Adds a number of ways that nuclear operatives and the crew can win or fail when the gamemode is nuclear operatives.

These are:

- **Syndicate Major Victory**
  - The nuclear bomb explodes on the station.
- **Syndicate Minor Victory**
  - The crew escapes, but leaves all nukies alive.
  - The crew escapes, and some nukies are alive, but they don't bring the disk with them.
- **Neutral Victory**
  - The nuclear bomb explodes off-station.
- **Crew Minor Victory**
  - The crew escapes, and some nukies are alive, but they manage to secure the disk.
- **Crew Major Victory**
  - All nuclear operatives die.
  - The crew manages to blow up the nuclear operative outpost.

**Changelog**

:cl:
- tweak: Nanotrasen and the Syndicate have provided guidelines to their crews as to how to consider clashes against nuclear operations as successes or failures.

2022-08-01 11:51 UTC, Just-a-Unity-Dev commented
can you add a "Nukies are antag-banned from playing nukies ever again" when the nuke explodes on the syndi base

2022-08-01 11:52 UTC, Just-a-Unity-Dev commented
can you antag-ban the nukies on crew major

2022-08-09 02:10 UTC, GoodWheatley commented
Know it’s a bit late to chime in, but I’d like to see the nuke being delivered to CentCom classified as a “Overwhelming Syndicate Victory” and the crew blowing up the nuke planet a “Overwhelming Crew Victory”.

2022-08-09 02:15 UTC, vulppine commented
> Know it’s a bit late to chime in, but I’d like to see the nuke being delivered to CentCom classified as a “Overwhelming Syndicate Victory” and the crew blowing up the nuke planet a “Overwhelming Crew Victory”.

this actually was the original intent (Syndicate/Crew humiliation victories) but it's more like a little edge case that's not necessarily the goal, but more a fun little 'oh, you can win that way?' message

2022-08-09 03:30 UTC, metalgearsloth requested changes

2022-08-09 03:30 UTC, metalgearsloth commented on Content.Server/Nuke/NukeSystem.cs
> +            });
Transform is already resolved above.

2022-08-09 03:30 UTC, metalgearsloth commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +                    && TryComp(_targetStation, out StationDataComponent? data))
You should just be able to TryComp(_targetStation)

2022-08-09 03:30 UTC, metalgearsloth commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        foreach (var nuke in EntityManager.EntityQuery<NukeComponent>())
```suggestion
        foreach (var nuke in EntityManager.EntityQuery<NukeComponent>(true))
```

2022-08-09 03:30 UTC, metalgearsloth commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +            var nukeTransform = Transform(nuke.Owner);
Just use EntityQuery<NukeComponent, TransformComponent>

2022-08-09 03:30 UTC, metalgearsloth commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +            var diskMapId = Transform(comp.Owner).MapID;
As above i.e. true + EntityQuery<NukeDiskComponent, TransformComponent>

2022-08-13 13:20 UTC, vulppine commented
blocked until #10005 is merged

2022-09-14 02:41 UTC, metalgearsloth approved these changes

2022-09-14 02:42 UTC, merged