active pinpointers finds targets upon map transition
space-wizards/space-station-14 pull request #10241
Opened 2022-08-02 04:32 UTC by JustinTrotter

## About the PR 
Fixes: #10161

Adds a new FTL state called Arrived between Arriving and Cooldown. This is necessary due to a race condition when trying to locate the disk as soon as the map loads. Waiting for the Arrived FTL State (3 seconds) allows for the map to load and for the disk to be findable.

**Screenshots**

**Changelog**

:cl:
- add: Activated pinpointers now automatically target the disk after completing a FTL jump.

2022-08-02 04:36 UTC, metalgearsloth requested changes
This should be done on cooldown and shouldn't need a new specific FTL state because the map has already changed.

You're also resolving IEntityManager in a loop which should not be done, plus IEntityManager is already on systems.

2022-08-02 04:46 UTC, JustinTrotter commented
> This should be done on cooldown and shouldn't need a new specific FTL state because the map has already changed.

I think I see what you mean. I'll set up a cooldown within the Arriving FTL state with the same time frame and remove the FTL state.

> You're also resolving IEntityManager in a loop which should not be done, plus IEntityManager is already on systems.

I see the issue with not resolving it within a loop and will correct that now. But I don't understand what you mean that IEntityManager is already on systems.

2022-08-02 04:49 UTC, mirrorcult commented
entitysystems all already have an `EntityManager` field as well as proxies to the methods on it, in this case `TryComp`

2022-08-02 05:05 UTC, JustinTrotter commented
Looks like I was only experiencing the race condition because I was making the event call at the very beginning the Arriving case. Moving it to the end seems to have given it enough time to load in the disk.

2022-08-02 05:07 UTC, metalgearsloth commented
> Looks like I was only experiencing the race condition because I was making the event call at the very beginning the Arriving case. Moving it to the end seems to have given it enough time to load in the disk.

You just need to wait until the coordinates are set as then the parent has been updated which is lines 278 / 288.

2022-08-05 13:02 UTC, JustinTrotter commented
This is ready btw.

2022-08-08 03:23 UTC, metalgearsloth requested changes

2022-08-08 03:23 UTC, metalgearsloth commented on Content.Server/Pinpointer/ServerPinpointerSystem.cs
> +                if (component != null)
```suggestion
                if (TryComp<PinpointerComponent>(uid, out var component))
```

2022-08-08 04:27 UTC, metalgearsloth approved these changes

2022-08-08 04:27 UTC, merged