Flashes, Expendablelights, and spray bottles will mark as trash when used up
space-wizards/space-station-14 pull request #10430
Opened 2022-08-08 05:49 UTC by jessicamaybe

## About the PR 
title basically. this marks flashes, torches, glowsticks, and spray bottles as trash when used up

flares are still always trash because they're in the starter box and will always just be thrown around

2022-08-13 13:37 UTC, metalgearsloth requested changes

2022-08-13 13:37 UTC, metalgearsloth commented on Content.Server/Flash/FlashSystem.cs
> +                    _tagSystem.AddTag(comp.Owner, "Trash");
EnsureComponent is redundant

2022-08-13 13:37 UTC, metalgearsloth commented on Content.Server/Light/EntitySystems/ExpendableLightSystem.cs
> +                        _tagSystem.AddTag(component.Owner, "Trash");
As above

2022-08-13 13:37 UTC, metalgearsloth commented on Content.Server/Light/EntitySystems/ExpendableLightSystem.cs
> +
```suggestion
```

2022-08-14 05:13 UTC, mirrorcult submitted a review, later dismissed

2022-08-14 05:14 UTC, merged