Voice mask
space-wizards/space-station-14 pull request #10458
Opened 2022-08-09 05:26 UTC by vulppine

## About the PR 

Voice masking. Leverages Identity.Name to use the current identity of the entity speaking in order to get the name to use in a voice message emitted by an entity. Also adds the voice mask - a stealth tool for antagonists that changes their voice to whatever their identity name is, whether it be the generic one generated by IdentitySystem, or their ID card's name.

**Changelog**

:cl:
- add: Voice masking is now possible for mobs that speak.
- add: The Syndicate has found a supplier for voice modification tools, and is now supplying them to their agents. Be aware of who you're speaking to: they might not be who they sound like.

2022-08-11 09:46 UTC, metalgearsloth requested changes

2022-08-11 09:46 UTC, metalgearsloth commented on Content.Server/VoiceMask/VoiceMaskerSystem.cs
> +    public override void Initialize()
Can probably just make this a partial class of VoiceMaskSystem.

2022-08-11 11:00 UTC, vulppine commented
> Would you like to give toggleable feature on syndicate gas mask to merely scramble your voice to Unknown (or something like that), complete with spooky robotic speech sound? That would not hide that you are baddie, but saves you from having to mime out your demands.

right now, just taking off your ID will set the name you speak with to the generic name you have in identity

2022-08-11 11:08 UTC, vulppine commented
actually, having the identity name is probably too revealing sooooooo

2022-08-11 15:20 UTC, vulppine commented
there was some discussion on discord about the state of this feature, so i'll summarize it here:

voice masks (or, voice changers) currently mimic the SS13 functionality of voice changers, but it's not inherently intuitive for newer players, as it requires usage of the ID card currently equipped by the player - so, a proposed change was made that instead allows the player to set their current voice via a dialog

i don't necessarily agree with this, but i also implemented the functionality so that if some consensus is reached, it shouldn't take very long to use the new set of changes

pro and con list, feature wise:

**SS13-style: ID cards as the voice mask name dependency**
- Pros:
  - Cheaper (1 - 2 TC balance because of how difficult it is to change identities)
  - Requires more interaction by the player in order to get an ID card if they forgo the agent card
  - Requires more book-keeping by the player in order to keep a distinct set of identities
- Cons:
  - Not intuitive (requires knowledge that ID card will change the name, but instructions on this are filled in on the uplink description
  - Not realistic (doesn't make sense that the ID card dictates the voice generated by some other non-related item)
  - Requires more book-keeping by the player in order to keep a set of identities (managing ID cards is also annoying)

**Proposed change: Voice mask name is stored in the player/mask**
- Pros:
  - More intuitive - player has gas mask, adjusts name, and uses it
  - More realistic - voice mask generates the player's voice without being dependent on other items
  - No bookkeeping - requires no ID card, so no bookkeeping of ID cards by the player is required
  - Flexible - no ID card requirement means that the player can speak like somebody else while looking (close enough) to somebody else
- Cons:
  - Expensive (3 - 5 TC balance due to its ease of use)
  - Requires less (or zero) interaction by the player to mask a voice (player can just buy gas mask without having to deal with obtaining an ID card to use)
  - Flexible - no ID requirement means that voice names can be changed on a fly, making it less difficult for a player to keep up with identity changes

keep in mind that in SS13, most servers bundle the voice changer as part of a full "chameleon kit", which costs about 2 TC, and includes a full set of chameleon gear - the proposed change above would instead keep it as a separate item from the kit (unless it otherwise is bundled in by another PR)

2022-09-29 01:52 UTC, vulppine commented
> With my proposal about suspicious toolbox mask getting _scrambler_, scope would be cheap identity hiding that does _not_ hide I am bad person when I am in disguise, but saves my primary identity until I slip up somehow all while allowing me to ransom station and such.

this seems like a decent tradeoff, especially since if the role/person you're impersonating usually has something that hides their face to pair with the voice changer (when trying to be stealthy)

2022-09-29 02:11 UTC, metalgearsloth requested changes

2022-09-29 02:20 UTC, metalgearsloth approved these changes

2022-09-29 02:22 UTC, merged