Adds hot potato
space-wizards/space-station-14 pull request #10496
Opened 2022-08-11 00:29 UTC by jessicamaybe

## About the PR 
Adds the hot potato.

The hot potato is a bomb that when armed, cannot be dropped or disposed of. The only way of getting it off of you is by passing it to another player. Thus the game of hot potato begins.

The bomb itself doesn't do too much damage, the hot potato is more about causing some chaos to happen.

Requires #10201
will be draft until new store stuff

:cl:
- add: A new item in the traitor shop! The hot potato. Only available to clowns, mimes, and botanists.

2022-08-14 15:24 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Objects/Weapons/Bombs/hot_potato.yml
> +  id: HotPotato
just make HotPotato parent from HotPotatoFake and add in the explosive components. They share about 80% of the yaml anyways.

2022-08-31 12:07 UTC, mirrorcult requested changes

2022-08-31 12:07 UTC, mirrorcult commented on Content.Server/HotPotato/HotPotatoComponent.cs
> +        /// </summary>
incorrect comment

2022-08-31 12:07 UTC, mirrorcult commented on Content.Server/HotPotato/HotPotatoSystem.cs
> +        component.CooldownEnd = component.LastUseTime + TimeSpan.FromSeconds(component.CooldownTime);
instead of tracking this yourself just use `ItemCooldown` and `UseDelay` which already exist, and check the cooldown on that comp instead

2022-08-31 12:07 UTC, mirrorcult commented on Resources/Locale/en-US/hotpotato/hot-potato.ftl
> +hot-potato-give = {CAPITALIZE(THE($user))} forces { THE($item) } onto {CAPITALIZE(THE($target))}!
```suggestion
hot-potato-give = {CAPITALIZE(THE($user))} forces { THE($item) } onto {THE($target)}!
```

2022-08-31 12:07 UTC, mirrorcult commented on Resources/Locale/en-US/hotpotato/hot-potato.ftl
> +hot-potato-give-fail = You try to force { THE($item) } onto {CAPITALIZE(THE($target))}, but it is unable to attach!
```suggestion
hot-potato-give-fail = You try to force { THE($item) } onto {THE($target)}, but it is unable to attach!
```

2022-08-31 12:07 UTC, mirrorcult commented on Resources/Locale/en-US/hotpotato/hot-potato.ftl
> +hot-potato-give = {CAPITALIZE(THE($user))} forces { THE($item) } onto {CAPITALIZE(THE($target))}!
capitalize capitalizes the first letter of whats passed in, this isnt correct usage

2022-08-31 12:07 UTC, mirrorcult commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 7
this seems like a lot for what is effectively a shitty explosive

2022-08-31 12:07 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Weapons/Bombs/hot_potato.yml
> +      explosionType: DemolitionCharge
isnt this what C4 uses? i would imagine this is an anti-personnel explosive not a breaching charge

2022-08-31 12:08 UTC, mirrorcult commented on Content.Server/HotPotato/HotPotatoComponent.cs
> +        /// </summary>
github fucked me on the review but this is specifically the comment on the sound datafield

2022-10-11 20:07 UTC, closed without merging