Radiation pulse ECS
space-wizards/space-station-14 pull request #10641
Opened 2022-08-16 14:35 UTC by Macoron

## About the PR 
Refactor radiation pulse to ECS. 
- Radiation emission logic moved to `RadiationSourceComponent`
- Visual green circle logic left in `RadiationPulseComponent`
- Radiation pulse now uses `TimedDespawnComponent`.
- Added `PlayOnSpawnComponent` which plays sound when entity is spawned.

I didn't touch much radiation logic, this is just groundwork for any future changes.

2022-08-29 21:52 UTC, EmoGarbage404 approved these changes
lgtm

2022-08-30 05:00 UTC, mirrorcult requested changes

2022-08-30 18:19 UTC, Macoron commented on Content.Server/Audio/Components/PlayOnSpawnComponent.cs
> +}
Didn't know about that system. Looks good, added new component there. Shame that it isn't shared.

2022-08-31 10:24 UTC, mirrorcult approved these changes

2022-08-31 10:24 UTC, merged