Upstream the Guidebook
space-wizards/space-station-14 pull request #10979
Opened 2022-09-02 15:21 UTC by moonheart08

- [ ] Add a button to the HUD to open the guide.
- [ ] Write guide pages for a bunch of things.

**Changelog**
:cl: moony
- add: An in-game guide has been added that'll hopefully ease onboarding for new players.

2022-09-02 15:22 UTC, moonheart08 commented
okay this git history looks dirty but it's also all stuff that got merged upstream so it ultimately contributes nothing.

2022-09-10 04:42 UTC, moonheart08 commented
Undrafting as i'll never be happy with the code behind this unless i rewrite all of richtext

2022-09-14 21:12 UTC, vulppine requested changes
Should the tutorial in `Content.Client/Info/RulesAndInfoWindow.cs` be removed as a result of this? It seems redundant, now.

2022-09-14 22:01 UTC, ElectroJr requested changes
I haven't actually looked at any of the guidebook text, other than making the funny disco monkey dance.

2022-09-14 22:01 UTC, ElectroJr commented on Content.Client/Guidebook/GuidebookWindow.Layout.xaml.cs
> +                return;
Hard-coding a directive to open a specific button, which will probably only ever be used in a single guidebook feels very icky.

Maybe make it a general button to run client-side commands, and create a `openoptions` command (if one doesn't already exist?)

2022-09-17 17:46 UTC, moonheart08 commented on Content.Client/Guidebook/GuidebookWindow.xaml.cs
> +    {
I don't want to write a brand new tree UI element so this is what we've got.

2022-09-17 17:46 UTC, moonheart08 commented on Content.Client/Guidebook/GuidebookWindow.xaml.cs
> +    {
There is no function to do this on the tree UI element.

2022-09-17 19:13 UTC, moonheart08 commented on Content.Client/Guidebook/GuidebookWindow.Layout.xaml.cs
> +                    }*/
tl;dr it does not work right and making it work right requires a parser rewrite.

2022-11-08 20:27 UTC, closed without merging