fix zombie mispredicts
space-wizards/space-station-14 pull request #11043
Opened 2022-09-05 16:37 UTC by EmoGarbage404

## About the PR 
moves a small part of zombie system to shared.
hopefully now they stop mispredicting out the ass and making me want to die.
**Screenshots**

**Changelog**

:cl:
- fix: Zombie move speed should no longer mispredict.

2022-09-05 16:50 UTC, ElectroJr requested changes

2022-09-05 16:50 UTC, ElectroJr commented on Content.Shared/Zombies/SharedZombieSystem.cs
> +public abstract class SharedZombieSystem : EntitySystem
you also need to add a non-abstract empty client-side system that inherits from this in order for it to work.

2022-09-06 03:09 UTC, metalgearsloth commented on Content.Shared/Zombies/SharedZombieSystem.cs
> +}
Does the client ever get zombiecomponent? Looks like it's not networked.

2022-09-07 01:59 UTC, ElectroJr approved these changes

2022-09-07 01:59 UTC, merged