among pequeno
space-wizards/space-station-14 pull request #11115
Opened 2022-09-08 03:11 UTC by EmoGarbage404

## About the PR 
among pequeno
**Screenshots**

![image](https://user-images.githubusercontent.com/98561806/189025575-eb07ac01-4bdf-4f82-b3a3-b440cd6df525.png)

**Changelog**

:cl:
- add: Added a sussy lil friend to the station.

2022-09-08 03:12 UTC, Emisse approved these changes

2022-09-08 03:28 UTC, EmoGarbage404 commented
leaving as DNM until we get the letter from among HQ

2022-09-08 03:48 UTC, Just-a-Unity-Dev approved these changes

2022-09-08 11:53 UTC, Veritius approved these changes

2022-09-10 03:46 UTC, EmoGarbage404 commented
clarified copyright policy for sprites in the rsi

2022-09-10 03:52 UTC, vulppine approved these changes
**AMOUNG** (5.50 credits)

*amoung pequeño* (3.00 credits)

2022-09-10 06:56 UTC, moonheart08 requested changes

2022-09-10 06:56 UTC, moonheart08 commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +  name: among pequeno
Needs to have a static price of three credits.

2022-09-10 06:56 UTC, moonheart08 commented on Resources/Textures/Objects/Fun/toys.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, orb, orb-inhand-left and orb-inhand-right created by Pancake, among-bas
This is wrong, check your ping in shiptest for the correct copyright for the pequeno, and make a new RSI.

2022-09-11 00:08 UTC, moonheart08 approved these changes

2022-09-11 00:08 UTC, merged