starting TC penalties for powerful roles
space-wizards/space-station-14 pull request #11111
Opened 2022-09-08 02:38 UTC by Elijahrane

## About the PR 
Saw people discussing heads as traitor recently, this is good if you want to enable those. Extremely simple implementation, feel free to bikeshed the numbers.

**Changelog**

:cl: Rane
- add: Powerful roles now have difficulty adjustments that make them more balanced antagonists. So, for example, engineers start with 3 less TC.

2022-09-08 02:45 UTC, Elijahrane commented
i removed all the job changes now so the arguments over this pr are smaller in scope

2022-09-08 22:07 UTC, moonheart08 requested changes

2022-09-08 22:07 UTC, moonheart08 commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +            startingBalance -= mind.CurrentJob.Prototype.DifficultyAdjustment;
Clamp this so that if a difficulty adjustment is larger than the actual total balance it just becomes zero.

2022-09-09 07:50 UTC, 0x6273 commented
I think `antagAdvantage` would be a better name for the property.

There are 2 reasons:
- "difficulty" sounds like higher values = higher difficulty, when it's the other way around.
- This makes it clear that's it's for antags and not just how difficult the job is in general.

2022-09-15 19:37 UTC, merged