Add networking cables
space-wizards/space-station-14 pull request #11214
Opened 2022-09-12 05:05 UTC by Illiux

## About the PR 

This adds networking cables to the game. I thought they'd be good as a PR on their own because it turns out there's quite a bit of scattered modifications required to implement a new kind of cable, and they're functional (despite not being useful).

**Screenshots**

![netcable](https://user-images.githubusercontent.com/451390/189576865-ef040edd-7d08-440b-a867-8957d42a0784.png)
![netcable-lit](https://user-images.githubusercontent.com/451390/189576867-58120785-f56b-4cd7-98cd-21b1edcb6577.png)

**Changelog**

:cl: illiux
- add: Networking cables. These can be placed similar to power cables, but are not currently used for anything more.

2022-09-12 05:17 UTC, Just-a-Unity-Dev commented
What does this add to game? This seems like unused content

2022-09-12 05:20 UTC, Just-a-Unity-Dev requested changes

2022-09-12 05:20 UTC, Just-a-Unity-Dev commented on Resources/Prototypes/Entities/Objects/Tools/cable_coils.yml
> +    state: 3
Do you mean `sprite`?

2022-09-12 05:21 UTC, Illiux commented
It doesn't add anything at the moment, but the alternative is bundling it with some later change which makes for a large, hard to review PR. Particularly with how scattered the changes here are, that'd really hurt the readability of whatever other potential PR it got bundled with.

2022-09-12 05:21 UTC, Just-a-Unity-Dev commented on Resources/Prototypes/Entities/Objects/Tools/cable_coils.yml
> +    state: 3
Nevermind, your latest commit (1a3a4649083ad063dc8f0489493ec2955ceaf896) fixed it

2022-09-12 05:24 UTC, Just-a-Unity-Dev commented
I don't see the need for this as we already have device net

2022-09-12 05:49 UTC, Partmedia commented
> It doesn't add anything at the moment, but the alternative is bundling it with some later change which makes for a large, hard to review PR. Particularly with how scattered the changes here are, that'd really hurt the readability of whatever other potential PR it got bundled with.

It would probably be helpful if you gave an example of planned content that uses these cables, and explain why what already exists doesn't cut it.

2022-09-12 05:50 UTC, mirrorcult commented
we aren't going to add stuff based on a hypothetical future feature that we know nothing about. i also personally dislike the concept of having a separate cable entirely for networking--there are already solutions ingame for this (apc devicenet). heavy justification is needed for this

2022-09-12 05:51 UTC, mirrorcult requested changes
see above

2022-09-12 08:34 UTC, juliangiebel commented
I assume those cables are supposed to be used instead of having the wired network use power cables or for a new connection type?
I don't think having even more cables is a good idea. Also wired network currently doesn't use power cables. It only requires the devices to be on the same grid because of performance reasons.

2022-09-12 15:09 UTC, vulppine commented
there is some precedence for these, and it involves a discussion about an implementation about wired device networks as something *technically* more cable bound - this occurred in discord in the development channel (starts around https://discord.com/channels/310555209753690112/310555209753690112/1017982776512888932, where i discuss about the current implementations that use devicenet as the backend)

i think there was a discussion in the past about having a separate cable type for networking, but this solution that we discussed seems somewhat interesting: maybe posting a more collected version of this would be more helpful, and combining this PR with a working implementation would be more advised

2022-09-14 01:28 UTC, Illiux commented
I've written up a high-level design of the wider system I had in mind: https://hackmd.io/@K6FF-6JhTGSCAS672tDDbw/SJhEAh6li

With more consideration I decided that the tradeoffs actually favor using the powernet, so I've managed to eliminate a new cable type from the design. Accordingly, I'm closing this PR.

2022-09-14 01:28 UTC, closed without merging