Rasta hat
space-wizards/space-station-14 pull request #11269
Opened 2022-09-14 15:43 UTC by ChilbroBaggins

I had some goofy stuff I was messing around with. I wanted to clear it all out though before updating my master. So, if you think it's fun merge it. 
![Screenshot 2022-08-15 101528](https://user-images.githubusercontent.com/107660393/190200967-ee295eee-6418-4f1f-b2e0-0afa24322884.jpg)
![Screenshot 2022-08-15 101521](https://user-images.githubusercontent.com/107660393/190200974-5c3a6259-9abf-4cf4-8d58-d2f115881db2.jpg)
![Screenshot 2022-08-15 101516](https://user-images.githubusercontent.com/107660393/190200983-7b388323-de22-4900-88a3-30fb7ab7a358.jpg)

2022-09-15 14:00 UTC, EmoGarbage404 requested changes
Probably shouldn't add content that has no way of being acquired in game.

2022-09-15 14:29 UTC, mirrorcult requested changes
see above

2022-09-15 14:30 UTC, mirrorcult commented on Resources/Prototypes/Entities/Clothing/Head/hats.yml
> +- type: entity
a

2022-09-15 14:59 UTC, ChilbroBaggins commented
OK, added to the Clothesmate and Autodrobe.

2022-09-16 14:40 UTC, mirrorcult approved these changes

2022-09-16 14:40 UTC, merged