Cleanup and re-parenting of wallmount/door electronics
space-wizards/space-station-14 pull request #11397
Opened 2022-09-18 15:54 UTC by corentt

closes #11155

2022-09-21 10:49 UTC, metalgearsloth requested changes

2022-09-21 10:49 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Devices/Electronics/base_electronics.yml
> +      state: generic
This needs to be netsync false

2022-09-21 20:34 UTC, corentt commented on Resources/Prototypes/Entities/Objects/Devices/Electronics/base_electronics.yml
> +      state: generic
done

2022-09-22 15:57 UTC, metalgearsloth approved these changes

2022-09-22 15:57 UTC, merged