janitor wall closet.
space-wizards/space-station-14 pull request #11409
Opened 2022-09-19 06:36 UTC by moonheart08

## About the PR
it's like a janitor closet but for walls

2022-09-19 06:39 UTC, theashtronaut commented on Resources/Prototypes/Entities/Structures/Storage/Closets/wall_lockers.yml
> +  description: It's a storage unit for janitorial clothes and gear.
```suggestion
  description: It's a storage unit for janitorial supplies.
```
it doesn't have any clothes in it :p

2022-10-09 19:50 UTC, mirrorcult commented
i feel like the fill should just inherit from the custodial closet so we dont get cases where people forget to update both

2022-10-09 19:52 UTC, EmoGarbage404 commented
> i feel like the fill should just inherit from the custodial closet so we dont get cases where people forget to update both

The closets cant inherit from each other because they will then inherit anchorable and other stuff that will break it. Perhaps either make storage fills prototypes or make abstract entities?

2022-10-24 08:14 UTC, ShadowCommander commented
The StorageFill can be moved to a separate entity and use prototype composition on both the locker and wall closet.

2022-10-24 08:15 UTC, ShadowCommander requested changes
The StorageFill can be moved to a separate entity and use prototype composition on both the locker and wall closet.

2022-10-24 08:18 UTC, mirrorcult commented
oh yeah that exists now

2022-11-08 20:27 UTC, closed without merging