adds a source uid to most damage & mobstate events
space-wizards/space-station-14 pull request #11559
Opened 2022-09-27 16:46 UTC by PaulRitter

note: whenever possible, i used the uid of the actual user, instead of the tool/weapon

this should be very useful for admintooling, as well as gamemodes where you actually wanna figure out who just killed a player for points etc

2022-09-28 11:23 UTC, rolfero approved these changes

2022-09-28 22:37 UTC, vulppine requested changes

2022-09-28 22:37 UTC, vulppine commented on Content.Shared/MobState/EntitySystems/SharedMobStateSystem.cs
> +        public void UpdateState(MobStateComponent component, FixedPoint2 damage, EntityUid? origin = null)
should probably pass down the origin from the DamageChangedEvent listener (see line 178)

2022-09-28 22:37 UTC, vulppine commented on Content.Shared/MobState/MobStateChangedEvent.cs
> +            DamageState currentMobState, EntityUid? origin)
```suggestion
            DamageState currentMobState, 
            EntityUid? origin)
```

2022-10-01 01:49 UTC, metalgearsloth submitted a review, later dismissed
There's an empty MeleeWeaponSystem

2022-10-03 22:42 UTC, vulppine approved these changes

2022-10-08 10:15 UTC, merged