Biomass Reclaimer cleanup
space-wizards/space-station-14 pull request #11551
Opened 2022-09-27 13:11 UTC by 0x6273

#11545 got merged while I was reviewing it. This PR addresses my review comments, plus some other minor changes.

- Document all the properties.
- Data fields for how much the part ratings affect speed/yield, instead of hardcoded values.
- The timers now count down instead of up (gets rid of `Accumulator` field).
- Make `BloodReagent` nullable.
- Make `CurrentExpectedYield` uint instead of float.
- More `ViewVariables` attributes and made some existing ones RW.
- Decouple speed and yield so they no longer affect the other, instead both are based on mass.
- Change formula for yield to be the same as for speed: multiplier^(partRating-1)

2022-09-27 13:16 UTC, metalgearsloth commented on Content.Server/Medical/BiomassReclaimer/BiomassReclaimerComponent.cs
> +        public float YieldPerUnitMass = default!;
You don't need to null suppress primitive types.

2022-09-27 13:56 UTC, 0x6273 commented on Content.Server/Medical/BiomassReclaimer/BiomassReclaimerSystem.cs
> +                Logger.Error("Somehow tried to extract biomass from {0}, which has no physics component.", toProcess);
So I should do something like this instead?
```csharp
PhysicsComponent? physics = null;
if (!Resolve(toProcess, ref physics))
    return;
```

2022-10-01 16:35 UTC, vulppine requested changes

2022-10-01 16:35 UTC, vulppine commented on Content.Server/Medical/BiomassReclaimer/BiomassReclaimerSystem.cs
> +            PhysicsComponent? physics = null;
just place this in the function parameters (most of SS14 does that if the function isn't a registered event listener)

2022-10-02 17:47 UTC, vulppine approved these changes

2022-10-02 17:47 UTC, vulppine commented on Content.Server/Medical/BiomassReclaimer/BiomassReclaimerSystem.cs
>              EntityManager.QueueDeleteEntity(toProcess);
```suggestion
            QueueDel(toProcess);
```

2022-10-04 01:55 UTC, mirrorcult approved these changes

2022-10-04 01:55 UTC, merged