Medibot recipe now requires medkit to be empty
space-wizards/space-station-14 pull request #11604
Opened 2022-09-29 13:38 UTC by GoodWheatley

## About the PR 

Took a stab at fixing #10852 and added the ContainerEmpty condition to the medibot recipe.

**Changelog**

:cl:
- fix: You can no longer delete items by crafting medibots

2022-09-29 13:44 UTC, 0x6273 commented on Resources/Prototypes/Recipes/Crafting/Graphs/bots/medibot.yml
> +        doAfter: 2
```suggestion
        doAfter: 2
```

2022-09-29 13:55 UTC, GoodWheatley commented
The tests keep failing :(

2022-09-29 14:30 UTC, Just-a-Unity-Dev requested changes
You have an extra space

2022-09-29 14:31 UTC, Just-a-Unity-Dev commented
Ignore my previous comment

2022-09-29 14:31 UTC, GoodWheatley commented
> Ignore my previous comment

no problem

2022-09-29 14:32 UTC, Just-a-Unity-Dev commented
GitHub doublesended my comment, great

2022-09-29 15:43 UTC, GoodWheatley commented
wait that wasn't supposed to be pushed fuck

2022-09-29 21:13 UTC, rolfero commented
Your tabs seem to be off - its important to have the correct amount of tabs to "place" the condition correctly. It should be under the specific edge. Perhaps double check https://docs.spacestation14.io/en/content/construction/index and see if you can get it working.

2022-09-29 22:45 UTC, Mervill commented
This does not fix the problem, for reasons I discussed in the original issue. Testing this change using a standard filled medkit (`MedkitFilled`) still creates the medibot.

2022-09-30 01:23 UTC, GoodWheatley commented
> This does not fix the problem, for reasons I discussed in the original issue. Testing this change using a standard filled medkit (`MedkitFilled`) still creates the medibot.

I would fix the underlying problem if I could, but I still have no idea how to do it. If somebody makes a PR that fixes the underlying issue I'll close this.

2022-09-30 01:40 UTC, EmoGarbage404 commented on Resources/Prototypes/Recipes/Crafting/Graphs/bots/medibot.yml
> +        container: "medkit"
pretty sure this needs to be `storagebase`.

2022-09-30 17:17 UTC, GoodWheatley commented
@Zumorica ready for review

2022-10-01 16:48 UTC, vulppine submitted a review, later dismissed

2022-10-01 22:02 UTC, Mervill requested changes
This condition is an `IGraphCondition` which is not evaluated when 'crafting' something (vs constructing something which does check `IGraphCondition`). So this change does not fix the issue.

Unfortunately this problem can't be solved with a simple data change. What really needs to happen is crafting needs to be rewritten to not use graphs (#11374). Which is a much bigger job.

2022-10-02 02:42 UTC, GoodWheatley commented
In light of Mervill's comment, going to close this since it ultimately won't solve the problem.

2022-10-02 02:42 UTC, closed without merging

2022-11-30 23:12 UTC, veliebm commented
Good try @GoodWheatley :)