biomass reclaimer suicide
space-wizards/space-station-14 pull request #11649
Opened 2022-10-02 01:46 UTC by EmoGarbage404

## About the PR 
funny goes CHUNKCHUNKCHKCHKCHUNKBRRRRR
**Screenshots**

**Changelog**

:cl:
- add: You can now suicide into biomass reclaimers.

2022-10-02 01:47 UTC, mirrorcult commented
based

2022-10-02 02:50 UTC, Kromabae commented
No video D:

2022-10-02 02:54 UTC, EmoGarbage404 commented
> No video D:

You kill yourself and then the machine go brchunkchunkchucnknkrbrrrr

2022-10-04 01:50 UTC, mirrorcult requested changes

2022-10-04 01:50 UTC, mirrorcult commented on Content.Server/Medical/BiomassReclaimer/BiomassReclaimerSystem.cs
> +
should really only set handled after it actually processes

2022-10-04 11:08 UTC, merged