Bad 2 Da Bone [Skeleton Tweaks]
space-wizards/space-station-14 pull request #11669
Opened 2022-10-03 02:07 UTC by EmoGarbage404

## About the PR 
retools skeletons to be less weak and more of an antag-adjacent thing.
restores the broken skull behavior but not the rebuilding thing (as it was lame and buggy)
makes a few ghost roles for use in events.
**Screenshots**

**Changelog**

:cl:
- tweaks: The sounds of spooky bones rattle on...

2022-10-13 22:49 UTC, moonheart08 approved these changes

2022-10-13 22:49 UTC, moonheart08 commented on Resources/Prototypes/Datasets/Names/skeleton_first.yml
> +  - Boner
boner johnson

2022-10-15 21:37 UTC, mirrorcult requested changes

2022-10-15 21:37 UTC, mirrorcult commented on Content.Server/Mind/Components/TransferMindOnGibComponent.cs
> +public sealed class TransferMindOnGibComponent : Component
i swear this alreaday exists/existed

2022-10-15 21:37 UTC, mirrorcult commented on Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
> +    bloodReagent: Milk
SO based

2022-10-15 21:37 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Vehicles/buckleable.yml
> +  name: Skeleton Motorcycle
```suggestion
  name: skeleton motorcycle
```

2022-10-15 21:37 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Vehicles/buckleable.yml
> +              - VehicleKey
any key? shouldnt it use its own key / not ATV stuff

2022-10-15 21:59 UTC, mirrorcult approved these changes

2022-10-15 22:06 UTC, merged