Price of food depends on its nutritional capacity
space-wizards/space-station-14 pull request #11752
Opened 2022-10-07 12:49 UTC by corentt

## About the PR

It creates a SolutionPrice component that is added to food prototypes (only FoodBase and inherited entity for now). This allow to calculate a price based on their reagents.

The reagent prototype now have a PricePerUnit datafield that is used is the calculation.
Right now only Nutriment, Vitamin and Protein got a price.

This can easily be extended to drinks and chemicals.

fixes #11464

**Changelog**

:cl:
- add: the price of food now depends on its nutritional capacity

2022-10-16 05:36 UTC, metalgearsloth commented
Kinda weird having SolutionPrice considering the same reagent in one container or another changes its price.

2022-10-16 19:02 UTC, corentt commented
> Kinda weird having SolutionPrice considering the same reagent in one container or another changes its price. 

You mean I should remove that component and calculate the price on every SolutionContainer ?

2022-10-30 06:59 UTC, metalgearsloth commented
> > Kinda weird having SolutionPrice considering the same reagent in one container or another changes its price.
> 
> You mean I should remove that component and calculate the price on every SolutionContainer ?

yes, it seems like it's too prone to data entry bugs where contributors forget about it.

2022-11-15 11:34 UTC, metalgearsloth requested changes

2022-11-15 11:34 UTC, metalgearsloth commented on Content.Server/Cargo/Systems/PricingSystem.cs
> +        {
```suggestion
        foreach (var solution in component.Solutions.Values)
        {
```

2022-11-15 11:34 UTC, metalgearsloth commented on Content.Server/Cargo/Systems/PricingSystem.cs
> +            foreach(var reagent in solution.Contents)
```suggestion
            foreach (var reagent in solution.Contents)
```

Unnecessary when you're just iterating over it.

2022-11-15 11:51 UTC, metalgearsloth approved these changes

2022-11-15 11:51 UTC, merged