Add announcement wrap to department radio messages for non-player sources (salvage magnet)
space-wizards/space-station-14 pull request #11912
Opened 2022-10-14 04:11 UTC by HoofedEar

## About the PR 
The salvage magnet no longer "says" anything. This PR provides a way to define a radio message as an announcement, so that the message is a lot cleaner looking over the radio.
This also accounts for the requested change in #10001 (if-else)

**Screenshots**

![image](https://user-images.githubusercontent.com/1261392/195759985-60b69249-715f-4f63-a71f-2c058fdba61e.png)

**Changelog**

:cl:
- tweak: Salvage magnet can no longer speak

2022-10-14 04:33 UTC, Just-a-Unity-Dev commented
Maybe instead of flat out removing the "says", how about use "beeps" instead?

2022-10-14 22:37 UTC, HoofedEar commented
> Maybe instead of flat out removing the "says", how about use "beeps" instead?

Even with "beeps" it still looks a bit messy since it would say "Salvage magnet beeps:" so it would be _named_ Salvage magnet which is very odd and confusing. Maybe if the magnet was possessed by a player? But this is just to non-sentient interactions

2022-10-15 21:29 UTC, mirrorcult requested changes

2022-10-15 21:29 UTC, mirrorcult commented on Content.Server/Headset/HeadsetComponent.cs
> +            if (!Channels.Contains(channel.ID) || !Owner.TryGetContainerMan(out var containerMan))
use `ContainerSystem` methods for this thru `_entMan.System<ContainerSystem>`

2022-10-16 19:36 UTC, ElectroJr commented
I'm currently scrapping IListen and IRadio, which will probably conflict with this pretty heavily.

2022-10-17 16:26 UTC, HoofedEar commented
Marked as draft until #11980 is complete. Changes should be easy enough

2022-12-22 21:07 UTC, HoofedEar commented
Gonna remake this after Crimbo

2022-12-22 21:07 UTC, closed without merging