Brig timers
space-wizards/space-station-14 pull request #12006
Opened 2022-10-17 22:38 UTC by rolfero

## About the PR 
Adds a brig timer.

The signal timer component allows an entity to be used as a signal timer, sending a signal when a timer triggers.
The textscreen component draws text in the world - for example, the signal timer label or the countdown.

The textscreen component can quite easily be used as it is as an escape shuttle timer, a round time clock, or other thing.

Want to add a brig timer to cells? First make sure that it's reasonable for prisoners to be released from their cells without supervision. Then add a brig timer to a nearby wall, set the label to Cell1/Cell2/whatever, and link it to the windoors using a multitool.

It should be linked like this:
Timer Start -> Close
Timer Trigger -> Open & Hold

**Screenshots**

https://user-images.githubusercontent.com/45628623/196296187-58f22718-badc-49b7-8cd6-de5eee811331.mp4

**Changelog**

:cl:
- add: Brig timers can now be added to maps.

2022-10-17 22:50 UTC, rolfero commented
leaving this here as well
![cursed](https://user-images.githubusercontent.com/45628623/196298133-d479a507-d9e9-4de4-9234-b0eac601091a.png)

2022-10-17 23:05 UTC, moonheart08 commented
while the text screen is very cursed it's currently the correct way to do it so consider this my approval of that idea in particular

2022-10-17 23:07 UTC, EmoGarbage404 commented
> leaving this here as well ![cursed](https://user-images.githubusercontent.com/45628623/196298133-d479a507-d9e9-4de4-9234-b0eac601091a.png)

i'm just happy to be included 
(the implementation is conceptually fine)

2022-10-17 23:18 UTC, rolfero commented
forgot to look at tests before opening PR, will look at fixing failed test tomorrow

2022-11-08 03:25 UTC, metalgearsloth commented on Content.Server/MachineLinking/System/SignalTimerSystem.cs
> +                    continue;
Use an active component for this stuff please.

2022-11-15 11:48 UTC, metalgearsloth requested changes

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Client/MachineLinking/UI/SignalTimerBoundUserInterface.cs
> +        }
Redundant? Just use the dependency directly.

2022-11-15 11:48 UTC, metalgearsloth commented on Resources/Textures/Structures/Wallmounts/textscreen.rsi/meta.json
> +  "copyright": "brainfood",
Needs a license, also should really be their entire discord handle and specify as such.

2022-11-15 11:48 UTC, metalgearsloth commented on Resources/Textures/Effects/text.rsi/meta.json
> +  "copyright": "Github @Rolfero",
License.

2022-11-15 11:48 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Structures/Wallmounts/timer.yml
> +    canCollide: false
Unnecessary?

2022-11-15 11:48 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Structures/Wallmounts/timer.yml
> +    state: on
```suggestion
  - type: Sprite
    sprite: Structures/Wallmounts/switch.rsi
    netsync: false
    state: on
```

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Shared/TextScreen/TextScreenVisuals.cs
> +    public enum TextScreenMode
```suggestion
    public enum TextScreenMode : byte
```

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Shared/TextScreen/TextScreenVisuals.cs
> +    public enum TextScreenVisuals
```suggestion
    public enum TextScreenVisuals : byte
```

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Server/MachineLinking/System/SignalTimerSystem.cs
> +            }
Shouldn't this be handled by yaml

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Server/MachineLinking/System/SignalTimerSystem.cs
> +            if (_ui.TryGetUi(component.Owner, SignalTimerUiKey.Key, out var bui))
```suggestion
            if (_ui.TryGetUi(uid, SignalTimerUiKey.Key, out var bui))
```

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Server/MachineLinking/System/SignalTimerSystem.cs
> +                                HasComp<ActiveSignalTimerComponent>(uid),
You RemComp the component but then HasComp it after.

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Server/MachineLinking/System/SignalTimerSystem.cs
> +            }
Should be passing around AppearanceComponent? because SetData is doing a resolve internally each time.

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Shared/MachineLinking/SharedSignalTimerComponent.cs
> +    public enum SignalTimerUiKey
```suggestion
    public enum SignalTimerUiKey : byte
```

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Server/MachineLinking/Components/SignalTimerComponent.cs
> +        public AudioParams SoundParams = AudioParams.Default.WithVolume(-2f);
VV readwrite for all but user.

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Client/TextScreen/TextScreenVisualsComponent.cs
> +        public const float PixelSize = 0.03125f;
Just use EyeManager.PixelsPerMeter.

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Client/TextScreen/TextScreenSystem.cs
> +                {
This should be an active component.

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Client/TextScreen/TextScreenSystem.cs
> +            PrepareLayerStatesToDraw(component, sprite);
Shouldn't you just UpdateText at the end?

2022-11-15 11:48 UTC, metalgearsloth commented on Content.Client/MachineLinking/UI/SignalTimerWindow.xaml.cs
> +                if (_owner.GetCurrentTime() < _triggerTime.Value)
See above

2022-12-14 10:36 UTC, CaptainSqrBeard commented
dead?

2022-12-14 10:48 UTC, rolfero commented
> dead?

I plan om returning as soon as i can to this, but im currently busy with uhhh lets call it strikes and uprisings

2023-01-10 13:06 UTC, closed without merging