Allow gas filters to not filter gases.
space-wizards/space-station-14 pull request #12051
Opened 2022-10-19 15:04 UTC by Vordenburg

## About the PR 

This PR allows gas filters to go back to their initial state of not filtering any gas by adding the "none" option to the top of the list of gases to filter. Previously, if you set a gas filter to filter some gas, you would be unable to allow all gases to pass through again, which meant the atmospheric technician had to choose some gas like tritium as a workaround. It's a minor quality of life improvement.

**Screenshots**

**Changelog**

:cl:
- add: Allowed gas filters to be reset to filter no gases.

2022-10-20 01:30 UTC, ShadowCommander requested changes
Minor formatting change. Otherwise looks good.

2022-10-20 01:30 UTC, ShadowCommander commented on Content.Client/Atmos/UI/GasFilterBoundUserInterface.cs
> +            } else {
```suggestion
            }
            else
            {
```

2022-10-22 21:55 UTC, mirrorcult requested changes

2022-10-22 21:55 UTC, mirrorcult commented on Content.Client/Atmos/UI/GasFilterBoundUserInterface.cs
> +            }
why does this need a separate network message? just make the `Gas` in `GasFilterSelectGasMessage` nullable

2022-11-04 01:27 UTC, merged