eldritch mask
space-wizards/space-station-14 pull request #12174
Opened 2022-10-23 22:13 UTC by brainfood1183

An eldritch "squiddy" mask, perfect for any librarian or would be cultist.

![Untitled-85](https://user-images.githubusercontent.com/113240905/197420548-9c1f3532-39ba-4c28-8150-ce49c04df169.jpg)

2022-11-02 16:54 UTC, rolfero approved these changes

2022-11-08 20:35 UTC, moonheart08 requested changes
Add it to the maintenance loot pool.

2022-11-09 04:12 UTC, brainfood1183 commented
> Add it to the maintenance loot pool.

added it to the maintenance fluff pool.

2022-11-16 14:47 UTC, mirrorcult approved these changes

2022-11-16 14:48 UTC, merged