combat cuffing
space-wizards/space-station-14 pull request #12500
Opened 2022-11-09 04:14 UTC by JustinTrotter

## About the PR 
Fixes #12439

I'm not 100% sold on this one. It works fine but there's still issues with you throwing the cuffs in the trash, putting it in the plant, or placing it on the table. These all things happen in non-combat mode anyway so it wouldn't really hurt gameplay more than it does already. It's a net-win at least.

**Screenshots**

**Changelog**

:cl:
- tweak: You can cuff people while in combat.

2022-11-09 04:31 UTC, moonheart08 commented
conflict speedrun

2022-11-09 05:14 UTC, JustinTrotter commented
Don't merge. I broke Fire Extinguishers I think

2022-11-13 06:23 UTC, metalgearsloth requested changes

2022-11-13 06:23 UTC, metalgearsloth commented on Content.Shared/Item/ItemComponent.cs
> +    [DataField("ignoreCombat")]
This is extra scuffed, why can't cuffing / melee logic just handle this.

2022-11-15 07:20 UTC, closed without merging