Job description
space-wizards/space-station-14 pull request #12510
Opened 2022-11-09 11:27 UTC by S1ss3l

## About the PR 
Added job description in english ! I already made a PR (#12275) for the first commit but I don't know how to remove it from my branch. I guess it should be fine since the changes are identical.

:cl:
- add: You should now see a description when hovering over job title.

2022-11-14 19:55 UTC, keronshb reviewed
Left a review, it's all spelling and some formatting.

2022-11-14 20:48 UTC, S1ss3l commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-assistant = An engineer in training, help the engineer fix the station and try to learn atmos !
The localization for the name use the same scheme, should I change it too ? (it's job-name-assistant)

2022-11-14 20:51 UTC, S1ss3l commented
I'm happy that the only thing to change are typo (english not being my main language yada yada yada). I'll wrap this all up in a commit soon, thanks for the feedback!

2022-11-14 21:00 UTC, keronshb commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-assistant = An engineer in training, help the engineer fix the station and try to learn atmos !
Oh yeah I see that now. That should be renamed to job-name-technical-assistant too, considering assistant.yml is passenger.

2022-11-14 21:01 UTC, keronshb commented
> I'm happy that the only thing to change are typo (english not being my main language yada yada yada). I'll wrap this all up in a commit soon, thanks for the feedback!

Yep no problem, glad to help!

2022-12-06 23:22 UTC, mirrorcult requested changes
these descriptions still have a lot of typos and I just don't like them overall, you should really do a second pass/get someone else to do these

2022-12-06 23:22 UTC, mirrorcult commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-security = Enforce space law, cuff troublemaker and bring them to brigg, be fair and try not to get hated by half the station.
```suggestion
job-description-security = Enforce the law, cuff troublemakers and bring them to the brig, be fair and try not to get hated by half the station.
```

2022-12-06 23:22 UTC, mirrorcult commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-detective = Investigate crime. Free innocent falsly condamned and incriminate real criminal (and vice-versa).
```suggestion
job-description-detective = Investigate crime. Free innocent falsly condamned and incriminate real criminal (and vice-versa).
```
this just needs to be completely rewritten, it doesn't make any sense

2022-12-06 23:22 UTC, mirrorcult commented on Resources/Locale/en-US/job/job-description.ftl
> +job-description-warden = Manage the armory and prisoneer. Prevent the prisoners from being forgotten in their cells.
```suggestion
job-description-warden = Manage the armory and brig. Prevent the prisoners from being forgotten in their cells.
```

2022-12-23 23:36 UTC, closed without merging