Rename Kahlua to Coffee Liqueur
space-wizards/space-station-14 pull request #12525
Opened 2022-11-10 03:34 UTC by Mervill

## About the PR 

Closes #10486

Copyright infringement is bad m'kay

**Changelog**

:cl:
- tweak: Kahlua renamed Coffee Liqueur due to copyright

2022-11-10 03:43 UTC, moonheart08 commented
Removed CL, gonna merg.

2022-11-10 06:33 UTC, wrexbe commented on Resources/Locale/en-US/reagents/meta/consumable/drink/alcohol.ftl
> +reagent-desc-coffeeliqueur = A widely known, Mexican coffee-flavoured liqueur.
Make the history game related

2022-11-10 06:34 UTC, wrexbe requested changes

2022-11-10 06:34 UTC, wrexbe commented on Resources/Locale/en-US/reagents/meta/consumable/drink/alcohol.ftl
> +reagent-desc-coffeeliqueur = A widely known, Mexican coffee-flavoured liqueur.
Make the history game related

2022-11-10 06:34 UTC, wrexbe commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
>    description: A widely known, Mexican coffee-flavoured liqueur. In production since 1936, HONK.
Make the history game related, instead of the trademarked products history

2022-11-10 20:21 UTC, wrexbe approved these changes

2022-11-16 20:59 UTC, mirrorcult approved these changes

2022-11-16 20:59 UTC, merged