zombie claw animation fix
space-wizards/space-station-14 pull request #12537
Opened 2022-11-10 20:45 UTC by EmoGarbage404

## About the PR 
it was a fist (at least on the client) so i just added the animations and range to the component state
should also fix some of the weird zombie bugs
**Screenshots**

**Changelog**

:cl:
- fix: Fixed weird zombie attack animations.

2022-11-10 22:22 UTC, metalgearsloth requested changes

2022-11-10 22:22 UTC, metalgearsloth commented on Content.Server/Zombies/ZombifyOnDeathSystem.cs
> +            Dirty(target);
Does this really need to be a full entity dirty? Much more efficient to just get the comps you touched.

2022-11-10 22:45 UTC, metalgearsloth approved these changes

2022-11-19 16:06 UTC, mirrorcult approved these changes

2022-11-19 16:07 UTC, merged