Complete #5177
space-wizards/space-station-14 pull request #12724
Opened 2022-11-22 17:53 UTC by Vordenburg

## About the PR 

#5177 only added the DumpCanister behavior for plasma canisters. This PR reduces repetition in the YAML files by handling the spawning of the specific broken canister in the system and moves the DumpCanister behavior to the base gas canister instead.

Resolves #4832

**Screenshots**

**Changelog**

:cl:
- fix: All gas canisters now dump their contents when destroyed.

2022-11-23 03:16 UTC, Mervill requested changes
Can you chage
```
- type: entity
  parent: BaseStructure
  id: GasCanisterBrokenBase
```
to
```
- type: entity
  parent: BaseStructureDynamic
  id: GasCanisterBrokenBase
```
and add
```
- type: Recyclable
```
to the same entity

2022-11-23 08:29 UTC, metalgearsloth commented on Content.Server/Atmos/Piping/Unary/Components/GasCanisterComponent.cs
> +        public string BrokenCanister { get; set; } = "GasCanisterBrokenBase";
Shouldn't destructible be handling this.

2022-11-23 08:31 UTC, metalgearsloth commented on Content.Server/Atmos/Piping/Unary/Components/GasCanisterComponent.cs
> -        [DataField("accessDeniedSound")]
This is already done implicitly by the type serializer

2022-11-23 08:33 UTC, metalgearsloth submitted a review, later dismissed
I don't see a reason to move destructible onto entities when it will be more subject to bugs and code quality issues over time.

If you want to reduce repetition in yaml then update the datafields to specify inheritance.

2022-11-23 18:43 UTC, Vordenburg commented
> I don't see a reason to move destructible onto entities when it will be more subject to bugs and code quality issues over time.

The Destructible component was already on all of these entities. Is there some better way to handle this behavior of dumping the gas canister's contents and spawning a broken variant than using the Destructible component?

> If you want to reduce repetition in yaml then update the datafields to specify inheritance.

Can you show me what you mean by using the datafields to specify inheritance, such as an example of this being done elsewhere?

The Destructible component was removed from every descendant of GasCanister in order to have a unified specification on the parent, GasCanister, with a field on the GasCanister component itself specifying which broken variant to spawn, instead of having that information needing to be put onto Destructible components on every child with the necessarily duplicated destructible thresholds and et cetera.

2022-12-04 23:38 UTC, metalgearsloth commented
> Can you show me what you mean by using the datafields to specify inheritance, such as an example of this being done elsewhere?

https://github.com/space-wizards/RobustToolbox/blob/master/Robust.Shared/Prototypes/IPrototype.cs#L44

> Is there some better way to handle this behavior of dumping the gas canister's contents and spawning a broken variant than using the Destructible component?

No, so destructible should handle it.

2022-12-20 02:45 UTC, Ygg01 commented
Issue was solved by another PR.

2022-12-20 21:34 UTC, Vordenburg commented
> Issue was solved by another PR.

Which PR? If it has been merged, I am still able to break open nitrous oxide canisters and be unaffected.

2022-12-20 22:27 UTC, mirrorcult commented
@Ygg01 this was not resolved in another pr

2022-12-21 05:08 UTC, EmoGarbage404 commented
if the issue was that only the plasma canister had the DumpCanister effect, why not just add it to all of the canisters? I get that it's going to be some yaml bloat, but it's only a few lines and could probably be generalized to all atmos containers, if needed.

2022-12-21 06:24 UTC, Vordenburg commented
> if the issue was that only the plasma canister had the DumpCanister effect, why not just add it to all of the canisters? I get that it's going to be some yaml bloat, but it's only a few lines and could probably be generalized to all atmos containers, if needed.

I wasn't aware at the time of writing this PR that this would be the preferred way to solve this problem, so I can change it to that instead. My original submission did generalize the end-result behavior but did not use Destructible.

2023-01-01 06:21 UTC, mirrorcult approved these changes

2023-01-01 06:21 UTC, merged