Basic fixes for the Syndicate Reinforcement Teleporter
space-wizards/space-station-14 pull request #12770
Opened 2022-11-27 01:51 UTC by Mervill

## About the PR 

I ran outta motivation on this one. I did some basic fixes but there's still some longer-term problems with the Syndicate Reinforcement Teleporter that need to be addressed.

![reinforcement](https://user-images.githubusercontent.com/6798456/204115600-a0db02c0-a3cb-4671-a635-1ac5c1cdffda.gif)

**Changelog**

:cl:
- fix: The Syndicate Reinforcement Teleporter creates a real syndicate member complete with objectives and codewords.
- fix: The Syndicate Reinforcement Teleporter creates a syndicate member of any race instead of just humans.

2022-11-27 02:13 UTC, ZeroDayDaemon commented
Do they get the objectives of who uses it?

2022-11-27 02:14 UTC, Mervill commented
no they get random new objectives like a fresh traitor. making the objectives smarter is definitely a good idea but not in the cards for me at the moment

2022-11-27 04:31 UTC, Elijahrane commented
so you could theoretically buy a reinforcement and the reinforcement gets an objective to kill you?

2022-11-27 04:34 UTC, EmoGarbage404 commented
> so you could theoretically buy a reinforcement and the reinforcement gets an objective to kill you?

Incredibly based and funny.

2022-11-27 05:49 UTC, Mervill commented
are traitors not excluded from the list of possible kill traitors?

2022-11-27 05:58 UTC, mirrorcult commented
> are traitors not excluded from the list of possible kill targets?

no, and they shouldnt be excluded, really

2022-11-27 15:22 UTC, GoodWheatley commented
I said this in ideamen and I’ll say it here again, I really don’t like the idea of the Reinforcement Teleporter creating an entirely new traitor. Most of the value of the item was that you had a partner to help complete your objectives, and this change invalidates this value. And keep in mind that this is also nukie-purchaseable, which could lead to some weird conflicts where the reinforcement is told to kill a nukie.

Other changes look good though!

2022-11-27 16:02 UTC, HoidC commented
Wasn't the point of this for nuclear operatives, not traitors? And if it is for traitors, why does it create another traitor with different objectives?

2022-12-02 12:25 UTC, ZeroDayDaemon commented
Ideally this would copy the objectives of the user if they are an antag (that way works for both nukies and non nukies) and if a non antag uses it, it should spawn an antag with fresh objectives (to prevent any sane person from using it, also if it refused on non antags it would become a validhunters dream)

2022-12-02 12:32 UTC, GoodWheatley commented
After thinking about this for a while, the traitor teleporter and nukie teleporter should be separate items. Right now buying a nukie reinforcement means you’ll have to buy a hardsuit for them, which only adds to the cost. They should come equipped with standard nukie gear, and the only way I can see that work is if the teleporters are separate items each spawning in their own unique role.

2022-12-02 18:42 UTC, Elijahrane commented
just give them the 'keep other traitor alive' objective with the user as the target

2022-12-03 03:20 UTC, GoodWheatley commented
> just give them the 'keep other traitor alive' objective and the 'ensure other traitor achieves at least half their objectives' objective with the user as the target

what if the traitor has the die objective?

2022-12-03 03:34 UTC, mirrorcult commented
then it's very funny and they shouldn't have bought a reinforcement

2022-12-03 05:10 UTC, Mervill commented
The Objectives thing is a real issue but...
- Funny
- To do that fix properly, I think, needs a new toolbox feature (specifically system-bound data, ask me about it later)
- I am not going to be pushing any more changes to this in a short term, the holidays are coming up and Dwarf Fortress comes out on Tuesday

2023-01-07 14:41 UTC, AJCM-git requested changes

2023-01-07 14:41 UTC, AJCM-git commented on Content.Server/Ghost/Roles/Components/GhostRoleTraitorReinforcementComponent.cs
> +    public sealed class GhostRoleTraitorReinforcementComponent : GhostRoleComponent
Please dont expand E/C code like this, i know GhostTakeoverAvailableComponent does this but that thing is incredibly old. If you want to do this, ECSing GhostRoleComponent is a requirement

2023-01-12 03:18 UTC, AJCM-git commented
closing this as it would require a conversion of E/C code elsewhere and its been inactive. Do reopen once you have time

2023-01-12 03:18 UTC, closed without merging