Split Kitchen supply crate into Dinnerware and Bar Supply crates
space-wizards/space-station-14 pull request #12800
Opened 2022-11-29 02:40 UTC by Cheackraze

## About the PR 
This splits the Kitchen Supply crate into Kitchen Supply, Kitchen Dinner ware, and Bartender Supply crates.  Plates, Knife, Bowl, and Skewers were removed from the kitchen supply crate and added to a Kitchen Dinnerware crate. Also adds Pie Tins, Drinking Glasses, Forks and Spoons to the Dinnerware crate.  The Kitchen Supply crate gets 1 more egg carton, 2 more rice bags, and 1 more universal enzyme bottle to make up the money difference. The Kitchen Dinnerware Crate has 4x of each utensil, except forks and spoons, only 2 each

Also adds the bar supply crate costing 750, with 5x drinking glasses, 5x shot glasses, 2x shakers, and 2 of each: Orange Juice, Tomato Juice, Lime Juice, Soda Water Can, Water Bottle, and Milk Cream Carton

**Changelog**

:cl: checkraze
- add: Added Dinnerware crate and Bar Supply crate
- tweak: Moved some items from the Kitchen Supply crate to the Dinnerware Crate

2022-12-06 23:32 UTC, mirrorcult requested changes

2022-12-06 23:32 UTC, mirrorcult commented on Resources/Prototypes/Catalog/Cargo/cargo_food.yml
> +  cost: 1000
this + the old kitchen crate should probably be reduced in price now that its split (maybe 1000 for the old crate and 500 for this) since they have comparatively less

2022-12-07 00:53 UTC, Cheackraze commented on Resources/Prototypes/Catalog/Cargo/cargo_food.yml
> +  cost: 1000
sounds good to me but I'll double check the contents to make sure I don't introduce a perfectly balanced crate with no exploits (infinite money glitch edition)

2022-12-07 01:13 UTC, Cheackraze commented on Resources/Prototypes/Catalog/Cargo/cargo_food.yml
> +  cost: 1000
the supply crate was worth just under 500 and the dinnerware was worth just over 500 so I made them both worth 750

2023-01-07 14:56 UTC, AJCM-git approved these changes
just merge master and rerun tests

2023-01-08 01:54 UTC, AJCM-git approved these changes

2023-01-14 18:37 UTC, merged