Prize limit for Arcades
space-wizards/space-station-14 pull request #12855
Opened 2022-12-03 23:12 UTC by Jackrost

This PR limit prizes for Space Villain arcade. All arcades on maps (static and spawner) were changed. No more arcade abuse

**Screenshots**

**Changelog**

:cl:
- tweak: Space Villain arcade prizes now limited

2022-12-03 23:15 UTC, EmoGarbage404 requested changes
you probably don't need to have filled and non-filled variants.

2022-12-03 23:15 UTC, EmoGarbage404 commented on Content.Server/Arcade/Components/SpaceVillainArcadeComponent.cs
> +                entityManager.SpawnEntity(_random.Pick(_possibleRewards), entityManager.GetComponent<TransformComponent>(Owner).MapPosition);
```suggestion
                _entityManager.SpawnEntity(_random.Pick(_possibleRewards), entityManager.GetComponent<TransformComponent>(Owner).MapPosition);
```

2022-12-03 23:15 UTC, EmoGarbage404 commented on Content.Server/Arcade/Components/SpaceVillainArcadeComponent.cs
> +                var entityManager = IoCManager.Resolve<IEntityManager>();
```suggestion
```

2022-12-03 23:15 UTC, EmoGarbage404 commented on Content.Server/Arcade/Components/SpaceVillainArcadeComponent.cs
> +        private int _rewardAmount;
just make this public

2022-12-03 23:28 UTC, Jackrost commented
> you probably don't need to have filled and non-filled variants.
But who fill them? Mapers? Big amount arcades created with spawners also.

2022-12-03 23:32 UTC, Jackrost commented on Content.Server/Arcade/Components/SpaceVillainArcadeComponent.cs
> +                entityManager.SpawnEntity(_random.Pick(_possibleRewards), entityManager.GetComponent<TransformComponent>(Owner).MapPosition);
done

2022-12-03 23:32 UTC, Jackrost commented on Content.Server/Arcade/Components/SpaceVillainArcadeComponent.cs
> +                var entityManager = IoCManager.Resolve<IEntityManager>();
done

2022-12-03 23:32 UTC, Jackrost commented on Content.Server/Arcade/Components/SpaceVillainArcadeComponent.cs
> +        private int _rewardAmount;
done

2022-12-03 23:52 UTC, Jackrost commented
The main problem that construction doesn't allow me to set prize amount after completion. It's some sort of workaround

2023-01-02 02:49 UTC, Jackrost commented
Fix it. Now number of prizes are randomised

2023-01-03 14:00 UTC, Jackrost commented
It's don't conflict now, but you need to manually check and swap arcades to new ones if they exist

2023-01-13 20:19 UTC, AJCM-git requested changes
You can fix origin with git CLI with these commands
`git checkout arcade-limitation`
`git checkout master Resources/Maps/origin.yml`
Do a commit, then merge latest master to this branch and finally make sure that there arent any new `SpaceVillainArcade` in any of the maps

2023-01-13 20:19 UTC, AJCM-git commented on Content.Server/Arcade/Components/SpaceVillainArcadeComponent.cs
> +                _entityManager.SpawnEntity(_random.Pick(_possibleRewards), _entityManager.GetComponent<TransformComponent>(Owner).MapPosition);
use entity coordinates (`<TransformComponent>(Owner).Coordinates` )

2023-01-15 00:50 UTC, AJCM-git approved these changes

2023-01-15 00:52 UTC, merged