Add logging for hacking
space-wizards/space-station-14 pull request #12861
Opened 2022-12-04 04:00 UTC by Chief-Engineer

Wire pulses, cuts, and mends get logged with the wire type and color.

2022-12-05 04:39 UTC, metalgearsloth requested changes

2022-12-05 04:39 UTC, metalgearsloth commented on Content.Server/Wires/BaseWireAction.cs
> +
[Dependency] just means when IoCManager.InjectDependencies is run it will get injected so it's unnecessary if you're resolving elsewhere.

2022-12-05 04:39 UTC, metalgearsloth commented on Content.Server/Wires/BaseWireAction.cs
> +        _adminLogger.Add(LogType.Action, LogImpact.Medium, $"{EntityManager.ToPrettyString(user):player} cut {wire.Color.Name()} {GetType().Name.Replace("WireAction", "")} in {EntityManager.ToPrettyS
There's no requirement for inheritors to use _text so you can't use it in the base class. You'd have to add it as a property to baseWireAction.

2022-12-21 03:57 UTC, vulppine reviewed
i don't think that Text has to necessarily be implemented on every single wire action, as it seems that it's only used to internally identify a wire in the logs (it's probably more legible to read the non WireAction part of the class name, instead of the shortened one that a user sees in the UI): the text variable in those wires is meant for the general user to see when they open up the UI

2022-12-23 20:39 UTC, vulppine commented
> 
> It should be falling back to what you're describing if _text isn't set. I tried to figure out a way to not need to override the Text property in every wire action but wasn't able to, it would use the value of BaseWireAction instead. My thinking with using the _text field instead of the class name whenever possible is:
> 

actually, if what you mean you get 'Base' as a name, i just tested this PR locally and removed the Text implementation from one of the wires and got the correctly trimmed name

> There's less reliance on consistency in class names. For example: AirAlarmPanicWire, AtmosMonitorDeviceNetWire

but this is definitely a concern: i don't think that having it just be the full name of the wire action would be a bad idea either though (save for making logs a bit longer as a result), but it is dependent on the wire implementer actually ensuring that their class name makes sense to the wire action in question

however, you make a good point where just using the user-facing wire's label may be more friendlier to people who don't actually know what the classes themselves do: in either case, this PR seems fine, and if you want to go forward with just using the wire label in the panel, that's fine with me imo

2022-12-25 03:12 UTC, vulppine commented
> > actually, if what you mean you get 'Base' as a name, i just tested this PR locally and removed the Text implementation from one of the wires and got the correctly trimmed name
> 
> What I meant here is that I wasn't able to figure out a way to use the user-facing wire label without modifying each implementation of `BaseToggleWireAction` to include
> 
> ```
>     protected override string Text
>     {
>         get => _text;
>         set => _text = value;
>     }
> ```
> 
> Since it's exactly the same bit of code, ideally there'd be a way to not include it in every single class, but I'm not familiar enough with C# to know how to do that or if it's even possible.

ah, i see: right now labels are optional due to how it’s implemented, and i think making labels required for logging purposes may slightly be out of scope (i.e., what if some wire in the future had empty text/no visible label for its corresponding light), so at the moment this is fine - the alternative, of course, is having those notably long log lines for every wire action that was activated on some entity

2022-12-26 21:44 UTC, vulppine approved these changes
imo i think just putting the direct class name as the log label fallback would be nicer in case you don't have a wire that follows the 'WireAction' name pattern, but this seems fine enough imo

2023-01-15 21:14 UTC, merged