Make phones functional
space-wizards/space-station-14 pull request #12892
Opened 2022-12-05 13:55 UTC by Chief-Engineer

## About the PR 

Modifies prayer system to allow it to be used for other similar functions. Adds this functionality to the red phone and to the banana phone.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, or this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The red phone can now be used to leave a message for Central Command
- tweak: The banana phone can now be used to leave a message for the Honkmother

2022-12-05 15:07 UTC, moonheart08 requested changes

2022-12-05 15:07 UTC, moonheart08 commented on Content.Server/Prayer/PrayableComponent.cs
> +        public string SentMessage = "Your message has been sent to the gods...";
Localization.

2022-12-05 15:07 UTC, moonheart08 commented on Content.Server/Prayer/PrayableComponent.cs
> +        public string NotifiactionPrefix = "PRAYER";
Localization.

2022-12-05 15:07 UTC, moonheart08 commented on Content.Server/Prayer/PrayableComponent.cs
> +        public string Verb = "Pray";
Localization.

2023-01-16 07:57 UTC, ZoldorfTheWizard commented
@Chief-Engineer is this still a valid pr with #13321 close to completion?

2023-01-17 18:34 UTC, ZoldorfTheWizard approved these changes

2023-01-17 18:35 UTC, ZoldorfTheWizard approved these changes

2023-01-17 18:42 UTC, merged