Multithreaded Conveyor Belts
space-wizards/space-station-14 pull request #12929
Opened 2022-12-08 13:41 UTC by keronshb

## About the PR 

Currently in draft

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame
- [ ] This PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

2022-12-08 19:25 UTC, Partmedia commented
Per the discussion on Discord, before you start serious work on this, I would encourage you to profile the conveyor system to identify what the actual bottleneck is. You may find that the current bottleneck is not parallelizable, or that threading overhead might be greater than the performance gains.

2022-12-13 02:11 UTC, metalgearsloth requested changes
Looks like it's not predicted yet?

2022-12-13 14:20 UTC, keronshb commented on OBOBOBOB
> +   update-git-for-windows
buh.,. I'm really not sure how this got here.

2022-12-13 14:28 UTC, keronshb commented on Content.Shared/Power/Events/PowerChangedEvent.cs
> +[Serializable, NetSerializable]
Wasn't sure if it needed it for prediction purposes since it's in shared now.

2022-12-15 01:58 UTC, metalgearsloth requested changes

2022-12-15 01:58 UTC, metalgearsloth commented on Content.Shared/Power/Events/PowerChangedEvent.cs
> +}
Move this back to server and revert the namespace changes plz.

2022-12-15 01:58 UTC, metalgearsloth commented on Content.Shared/Physics/Controllers/SharedConveyorController.cs
> +{
Because this is abstract client is never going to run this code, only server which inherits this.

2022-12-15 01:58 UTC, metalgearsloth commented on Content.Shared/Conveyor/ConveyorComponent.cs
> +
Network.

2022-12-15 01:58 UTC, metalgearsloth commented on Content.Shared/Conveyor/ActiveConveyorComponent.cs
> -[RegisterComponent]
I don't think this one needs networking.

2022-12-15 01:58 UTC, metalgearsloth commented on Content.Server/Physics/Controllers/ConveyorController.cs
> +    [Dependency] private readonly SharedAppearanceSystem _appearance = default!;
A bunch of these are duplicated from sharedconveyorcontroller.

2023-02-13 12:20 UTC, metalgearsloth approved these changes

2023-02-13 12:20 UTC, merged