Fix in-game voting
space-wizards/space-station-14 pull request #12932
Opened 2022-12-08 19:18 UTC by Partmedia

## About the PR 
A regression introduced after the UI refactor caused the vote-casting window to not appear when the client was in-game.

*This fix was sponsored by Mining Station 14.*

**Steps To Reproduce**
Enter the game as a ghost or player, call a vote. You hear the "ding" but no vote window shows up.

**Media**
![2022-12-08_11-05](https://user-images.githubusercontent.com/3229565/206546771-a074dacb-38c8-46a9-a71d-2926d5d0d956.png)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame
- [ ] This PR does not require an ingame showcase

**Changelog**
:cl: notafet
- fix: Votes can once again be cast in-game

2022-12-08 20:51 UTC, moonheart08 requested changes
This fix is an ugly hack.

Add a new UI widget to the different states/screens that votes should be put in, and set the popup container to it when switching between states.

2022-12-08 21:30 UTC, Partmedia commented
While I agree that your suggested fix would be better, I also think that this fix is better than no fix. Besides, there is precedent for this type of fix (see 85866ea).

2022-12-09 00:12 UTC, mirrorcult commented
this fix isn't ideal but it's certainly not ugly and it's better than nothing, imo just add a comment that this should be removed in favor of a proper popup eventually

2022-12-09 00:13 UTC, mirrorcult commented
also the restart vote cvar should be reenabled

2022-12-09 00:13 UTC, mirrorcult commented
also the restart vote cvar should be reenabled

2022-12-09 07:03 UTC, moonheart08 commented
I don't really want to budge on this considering adding UI elements to each state for the vote container isn't very hard.

2022-12-09 19:15 UTC, Partmedia commented
I've added a comment about the "hack" and re-enabled vote restart by default, as requested.

We're all volunteers, and I'm not presently interested in adding and testing per-state vote containers. I investigated and fixed making votes functional again, and thought upstream might find the fix useful.

2022-12-19 01:12 UTC, DrSmugleaf approved these changes

2022-12-19 01:13 UTC, merged