Printable drills and constructable thrusters
space-wizards/space-station-14 pull request #12943
Opened 2022-12-09 03:41 UTC by EmoGarbage404

## About the PR 
adds lathe recipes and techs for both the mining drill and the power drill (since it happened to have a recipe)
Also adds recipes for thruster and gyroscope circuitboards, making them constructable.
**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame
- [ ] This PR does not require an ingame showcase

![image](https://user-images.githubusercontent.com/98561806/206618899-e31e74e7-5053-4909-b72c-1f079d87de32.png)
![image](https://user-images.githubusercontent.com/98561806/206619041-3d96a984-6c9c-48a5-9ec7-02180f77a4cc.png)
![image](https://user-images.githubusercontent.com/98561806/206619056-b121940d-20bc-4b83-9749-cab3d73ca500.png)

**Changelog**

:cl:
- add: Mining drills and power drills can now be printed at the protolathe.
- add: Thrusters and Gyroscopes can be built and upgraded.

2022-12-09 09:27 UTC, S1ss3l commented
Gyroscope make sense but aint it weird that the thruster is made with a cricuitboard ?

2022-12-18 08:46 UTC, deltanedas requested changes

2022-12-18 08:46 UTC, deltanedas commented on Content.Server/Shuttles/Systems/ThrusterSystem.cs
> +            SubscribeLocalEvent<ThrusterComponent, RefreshPartsEvent>(OnRefrehParts);
typo OnRefrehParts

2022-12-18 08:46 UTC, deltanedas commented on Content.Server/Shuttles/Systems/ThrusterSystem.cs
> +        private void OnRefrehParts(EntityUid uid, ThrusterComponent component, RefreshPartsEvent args)
typo OnRefrehParts

2022-12-18 23:34 UTC, deltanedas approved these changes
please merge please merge please merge please merge

2022-12-19 04:38 UTC, merged