Allow direct transfer between specific BallisticAmmoProviders.
space-wizards/space-station-14 pull request #12964
Opened 2022-12-10 21:04 UTC by Vordenburg

## About the PR 

No longer will you have to cycle rounds on the floor and pick them up one by one to load a magazine.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame
- [ ] This PR does not require an ingame showcase

https://user-images.githubusercontent.com/114301317/206875044-f72c6002-610f-4e39-a972-aa368441ff80.webm

**Changelog**

:cl:
- add: You can now transfer ammunition between magazines and boxes by clicking on one with the other.

2022-12-10 22:52 UTC, metalgearsloth requested changes

2022-12-10 22:52 UTC, metalgearsloth commented on Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs
> +        Audio.PlayPredicted(targetComponent.SoundInsert, args.Target.Value, args.User);
Just use the takeammoevent.

2022-12-20 19:44 UTC, Vordenburg commented on Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs
> +        Audio.PlayPredicted(targetComponent.SoundInsert, args.Target.Value, args.User);
Done.

2023-01-20 16:08 UTC, mirrorcult approved these changes

2023-01-20 16:08 UTC, merged