Goodbye Microwave, Hello Hot Plates!
space-wizards/space-station-14 pull request #13061
Opened 2022-12-18 01:46 UTC by EmoGarbage404

## About the PR 
adds a hot plate to be used in various chemistry endeavors 
just put a beaker on it and wowee it heats it up slowly could you ever fathom that.
also includes a little upgrade in case you're feeling spicy.
**Media**

![image](https://user-images.githubusercontent.com/98561806/208273148-9ee5770a-0676-4a72-a86c-6d76bbc0b133.png)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added hot plates for heating up beakers. No longer are chemists bound to the humble microwave.

2022-12-18 08:21 UTC, deltanedas commented
No longer need to search for a microwave to cook meth, very good
I also hope this will lead to more reactions that use heat since a rarely made stimulant being the only pseudo realistic reaction is silly

2022-12-20 04:13 UTC, moonheart08 requested changes

2022-12-20 04:13 UTC, moonheart08 commented on Content.Server/Chemistry/EntitySystems/SolutionHeaterSystem.cs
> +            heater.NextHeat = _timing.CurTime + TimeSpan.FromSeconds(1);
instead of this

2022-12-20 04:13 UTC, moonheart08 commented on Content.Server/Chemistry/EntitySystems/SolutionHeaterSystem.cs
> +                _solution.AddThermalEnergy(solution.Owner, s, heater.HeatPerSecond * heater.HeatMultiplier);
multiply this by frametime and just update every tick.

2022-12-20 04:44 UTC, moonheart08 approved these changes

2022-12-21 14:45 UTC, mirrorcult requested changes

2022-12-21 14:45 UTC, mirrorcult commented on Content.Server/Chemistry/EntitySystems/SolutionHeaterSystem.cs
> +                continue;
create an `ActiveSolutionHeaterComponent` instead of an `Enabled` bool

2022-12-25 01:59 UTC, merged