Adds radiation damage to nuclear bombs
space-wizards/space-station-14 pull request #13074
Opened 2022-12-18 20:28 UTC by TemporalOroboros

## About the PR 
Makes the nuclear bomb explosion also deal radiation damage.

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The nuclear bomb now deals radiation damage in addition to the normal explosion damage.

2022-12-19 05:10 UTC, Just-a-Unity-Dev commented
I feel as it should also use the RadiationSystem to radiate the affected areas

2022-12-19 07:39 UTC, metalgearsloth commented
> I feel as it should also use the RadiationSystem to radiate the affected areas

Does radiation even work off grid.

2022-12-19 07:45 UTC, metalgearsloth requested changes

2022-12-19 07:45 UTC, metalgearsloth commented on Resources/Prototypes/explosion.yml
> +  fireStates: 3
Does this really need a new damage type? This adds overhead to the explosion tiles for something that is supposed to destroy everything in range anyway.

2022-12-19 09:26 UTC, Macoron commented
> > I feel as it should also use the RadiationSystem to radiate the affected areas
> 
> Does radiation even work off grid.

It does. You could spawn a big radiation source, with insane radiation intensity to feel nuke explosion zone. 

Though I'm not sure why would you do that if round will end in one minute and everything in radius supposed to be dead anyway.

2023-01-02 19:05 UTC, EmoGarbage404 reviewed
feels like unnecessary overhead considering that a nuke triggers a round end. Besides that, just doing radiation damage isn't really interesting enough to warrant the overhead from a new explosion type. If you're going to do anything, do radioactive fallout, but then consider that adding that is kinda pointless given that you're irradiating a pile of space debris.

2023-01-04 20:25 UTC, ElectroJr commented
It seems like sloth emo and me are all of the opinion that this is unnecessary and will just contribute to worse nuke/explosion performance, so closing this.

2023-01-04 20:25 UTC, closed without merging