Electro Gloves in syndicate uplink
space-wizards/space-station-14 pull request #13128
Opened 2022-12-21 05:12 UTC by LedinecMing

## About the PR 

https://user-images.githubusercontent.com/63245550/208825706-790661dd-cc0c-4bb1-9e23-cf92ca0ed54b.mp4

![image](https://user-images.githubusercontent.com/63245550/208825738-cdf777a1-7109-4cfd-a0c2-acc63f733926.png)

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added electrogloves in syndicate uplink, with a slot for powercell, cost 6 TC and work as a stun baton.

2022-12-21 05:26 UTC, Emisse commented
who hurt you

2022-12-21 05:37 UTC, asperger-sind commented
Imho the gloves should be more expensive, disguised stuns and all, 8 TC is probably the go-to.
Ninja gloves could also have the stun capability, as SS13 Ninjas (at least on /tg/) could do zappy things with their gloves.

2022-12-21 05:48 UTC, metalgearsloth requested changes

2022-12-21 05:48 UTC, metalgearsloth commented on Content.Server/Stunnable/Systems/ElectroGlovesSystem.cs
> +        }
Unused?

2022-12-21 05:48 UTC, metalgearsloth commented on Content.Server/Stunnable/Components/ElectroGlovesComponent.cs
> +}
Copy-pasting code is generally a bad idea. This should be networked + using file-scoped namespaces but because you copied stun batons it isn't.

2022-12-23 06:11 UTC, LedinecMing commented
@metalgearsloth you meant file organization like this?

2022-12-23 06:23 UTC, moonheart08 commented
im ngl i think this is a horrible idea

2023-01-20 15:59 UTC, mirrorcult commented
im not super convinced this will be good for the game, is there more justification for it?

2023-01-22 15:51 UTC, closed without merging