add a test for jobs with setPreference: false
space-wizards/space-station-14 pull request #13182
Opened 2022-12-25 04:48 UTC by EmoGarbage404

## About the PR 

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl no fun

2022-12-25 05:23 UTC, moonheart08 commented on Content.IntegrationTests/Tests/Station/StationJobsTest.cs
> +                }
....what.
this just takes the map and then does nothing with it

2023-01-04 12:11 UTC, DrSmugleaf approved these changes

2023-01-09 13:41 UTC, metalgearsloth requested changes
Did you mean to delete dart

2023-01-10 21:37 UTC, EmoGarbage404 commented
> Did you mean to delete dart

moony told me to

2023-01-27 04:31 UTC, AJCM-git commented
merge master and see if the test still works

2023-01-28 17:39 UTC, merged