Add nymph and dionea seeds
space-wizards/space-station-14 pull request #13227
Opened 2022-12-29 08:04 UTC by Marya-The-Slime

## About the PR 

**Media**
![Скриншот 27 12 22_10 35 14](https://user-images.githubusercontent.com/96390365/209921604-a75d2976-08d6-4a06-a1cd-d55a230cb512.jpg)
![Скриншот 27 12 22_10 35 46](https://user-images.githubusercontent.com/96390365/209921610-255e8623-1c83-4632-9f23-a161da261e9c.jpg)
![Скриншот 27 12 22_10 38 32](https://user-images.githubusercontent.com/96390365/209921613-b2a4c7a3-3463-4ab4-b9dd-2cf916b1048c.jpg)
![Скриншот 27 12 22_10 34 52](https://user-images.githubusercontent.com/96390365/209921616-50fc322c-ceb8-4817-be88-d3b354cea073.jpg)

- [ I have added screenshots/videos to this PR showcasing its changes ingame, ]
**Changelog**
:cl: Marya
- add: Added nymphs
- add: Added dionea spores
- add: dionea spores to Exotic Botany crate in cargo

2023-01-01 06:14 UTC, mirrorcult commented
what exactly is the purpose of these?

2023-01-02 03:07 UTC, Jackrost commented
> what exactly is the purpose of these?

In SS13 botanics can create mobs for ghosts with those seeds

2023-01-02 18:59 UTC, EmoGarbage404 requested changes
sorry for nitpicking your pr to death, otherwise it looks fine.

2023-01-02 18:59 UTC, EmoGarbage404 commented on Resources/Textures/Mobs/Animals/nymph.rsi/meta.json
> +    "license": "#DionaNotAWood",
if these are from bay, then you need to use the license that used on bay. A look on the repo says that the assets are licensed under the `CC-BY-SA-3.0` license.

2023-01-02 18:59 UTC, EmoGarbage404 commented on Resources/Textures/Objects/Specific/Hydroponics/nymph_seed.rsi/meta.json
> +  "license": "#DionaNotAWood",
same as before

2023-01-02 18:59 UTC, EmoGarbage404 commented on Resources/Textures/Objects/Specific/Hydroponics/nymph_seed.rsi/meta.json
> +  "copyright": "Taken from baystation12",
link to the repo, please

2023-01-02 18:59 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Objects/Specific/Hydroponics/nymph_seed.yml
> +  production: 3
The maturation value should be higher and the production and yield values should be lower. As it stands, you can make an absurd amount of ghost roles using these.

2023-01-02 18:59 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Objects/Specific/Hydroponics/nymph_seed.yml
> +- type: seed
this doesn't need to be it's own file. Put the seed entity with the other ones and the seed prototype with the rest of the seed prototypes.

2023-01-02 18:59 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Mobs/NPCs/nymph.yml
> +    - CannotSuicide
the `CannotSuicide` tag isn't really necessary here.

2023-01-02 18:59 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Mobs/NPCs/nymph.yml
> +  name: Nymph
nitpick but please structure your yaml according to the [conventions](https://docs.spacestation14.io/en/getting-started/conventions).
![image](https://user-images.githubusercontent.com/98561806/210269869-93fed4de-f207-4534-8abb-c91a3bf5f41a.png)

2023-01-02 18:59 UTC, EmoGarbage404 commented on Resources/Locale/en-US/npc/nymph.ftl
> +ent-MobNymph = Nymph
we don't localize entity names on the main branch.

2023-01-02 18:59 UTC, EmoGarbage404 commented on Resources/Locale/en-US/seeds/nymph_seed.ftl
> +ent-NymphSeed = packet of dionea spores
same here.

2023-01-02 18:59 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Objects/Specific/Hydroponics/nymph_seed.yml
> +  name: pack of dionea spores
calling these "dionae spores" isn't really accurate considering they, besides their appearance, currently have 0 relations to diona besides what other servers implement. Consider just changing it to "nymph seeds/spores"

2023-01-20 15:56 UTC, mirrorcult commented
needs reviews addressed

2023-02-02 01:55 UTC, closed without merging