Grenade Penguin 2: The Reckoning
space-wizards/space-station-14 pull request #13278
Opened 2023-01-01 23:30 UTC by EmoGarbage404

## About the PR 
cheaper, an actually reasonable speed, and no longer attack the user. DId i mention they explode on crit?
**Media**

https://user-images.githubusercontent.com/98561806/210187412-383b4195-9477-4772-bb34-e0a5a471258c.mp4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Grenade penguins no longer attack syndicate agents.
- tweak: Grenade penguins are now only 5 TC and explode on death. You can still trigger them manually, if you'd like.

2023-01-01 23:38 UTC, mirrorcult requested changes

2023-01-01 23:38 UTC, mirrorcult commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +        return;
hello

2023-01-02 00:59 UTC, EmoGarbage404 commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +        return;
FUCK

2023-01-02 01:18 UTC, mirrorcult approved these changes

2023-01-02 01:18 UTC, merged