Spiders buff
space-wizards/space-station-14 pull request #13294
Opened 2023-01-02 20:48 UTC by Jackrost

This PR direct to change spiders and make them more big threat:
*) damage and HP were buffed. They now deal little poison damage.
*) No slipping!
*) can now pull stuff (items and crited people)
*) spiders can spawn webs that slowdown enemies and preys.

This PR conflict with another PR #13292

**Media**
![image](https://user-images.githubusercontent.com/1917927/210276990-c434ff2d-76ad-4717-a670-9a13fa135ea0.png)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame

:cl: Jack Rost
- tweak:  spiders have more damage and hp now, no slipping and can pull stuff around
- add: spider net. Spiders now can spawn net that slowdown anyone expect spiders

2023-01-07 05:04 UTC, AJCM-git requested changes

2023-01-07 05:04 UTC, AJCM-git commented on Resources/Locale/en-US/actions/actions/spider.ftl
> +spider-web-action-description = Spawns web that slow your prey down.
Spawns **a** web that **slows***

2023-01-07 19:04 UTC, Jackrost commented on Content.Server/Spider/SpiderSystem.cs
> +                        EntityManager.SpawnEntity("SpiderWeb", transform.Coordinates);
> use proxy method Spawn() and dont use prototypes ids like this, either move it to the component or use a tag. 

Do you mean create var in component as Datafield? What a type of this var need to be - string?

2023-01-08 01:50 UTC, Jackrost commented on Content.Client/Spider/SpiderVisualsSystem.cs
> +    public sealed class SpiderVisualsSystem : VisualizerSystem<SpiderWebVisualsComponent>
How can I do that if sprite name is generating? Generic visualizers expect me to put true/false as data as shown on exapmle
![image](https://user-images.githubusercontent.com/1917927/211177142-1a6c921f-899b-48ef-9031-b8aef822a59a.png)

2023-01-08 14:05 UTC, AJCM-git commented on Content.Server/Spider/SpiderSystem.cs
> +                        EntityManager.SpawnEntity("SpiderWeb", transform.Coordinates);
Yeah, a data field like
```
        [DataField("prototype", customTypeSerializer: typeof(PrototypeIdSerializer<EntityPrototype>))]
        public string Prototype = "proto";
```

2023-01-08 20:58 UTC, closed without merging