Add prevent suicide to minds and add tag control commands
space-wizards/space-station-14 pull request #13307
Opened 2023-01-03 12:27 UTC by Chief-Engineer

## About the PR 
Adds options to prevent suicide for minds and ~~mind components~~ adds commands to edit tags ingame.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-01-03 14:33 UTC, Elijahrane commented
Isn't there already a CannotSuicide tag? Look at mice

2023-01-20 16:16 UTC, mirrorcult requested changes

2023-01-20 16:16 UTC, mirrorcult commented on Content.Server/Administration/Commands/TagCommands.cs
> +        public override string Help => "Usage: removetag <entity uid> <tag>";
completions would be really nice

2023-01-20 16:16 UTC, mirrorcult commented on Content.Server/Administration/Commands/TagCommands.cs
> +        public override string Help => "Usage: removetag <entity uid> <tag>";
with the current tagcomp tags for removetag, and `CompletionHelper.PrototypeIDs<TagPrototype>()` for addtag

2023-02-02 01:59 UTC, metalgearsloth requested changes

2023-02-02 01:59 UTC, metalgearsloth commented on Content.Server/Administration/Commands/TagCommands.cs
> +
This needs localizing.

2023-02-02 01:59 UTC, metalgearsloth commented on Content.Server/Administration/Commands/TagCommands.cs
> +                shell.WriteError($@"Could not add {args[1]} to {entityUid}.");
Same herre, also why the @

2023-02-02 01:59 UTC, metalgearsloth commented on Content.Server/Administration/Commands/TagCommands.cs
> +        }
As above

2023-02-02 01:59 UTC, metalgearsloth commented on Content.Server/Mind/MindSystem.cs
> +    }
Shouldn't this be its own component.

2023-02-17 00:35 UTC, DrSmugleaf approved these changes

2023-02-17 00:36 UTC, merged