Clean up the JobRequirements
space-wizards/space-station-14 pull request #13374
Opened 2023-01-08 14:45 UTC by 778b

## About the PR 

Closes https://github.com/space-wizards/space-station-14/issues/13348

**Changelog**

- Just clean up the JobRequirements

2023-01-08 21:53 UTC, AJCM-git requested changes

2023-01-08 21:53 UTC, AJCM-git commented on Content.Shared/Roles/JobRequirements.cs
> +        /// Should the condition be inverted?.
use     `/// <inheritdoc/>`

2023-01-08 21:53 UTC, AJCM-git commented on Content.Shared/Roles/JobRequirements.cs
> +        /// Should the condition be inverted?.
same

2023-01-08 21:53 UTC, AJCM-git commented on Content.Shared/Roles/JobRequirements.cs
> +        /// Should the condition be inverted?.
Be more concrete than this, declare what is the purpose of the condition being inverted

2023-01-10 11:46 UTC, metalgearsloth approved these changes

2023-01-10 11:46 UTC, metalgearsloth commented on Content.Shared/Roles/JobRequirements.cs
> +        /// and it allow pick if condition was false.
```suggestion
        /// If true, requirement will return false if playtime above the specified time.
```

2023-01-10 12:44 UTC, merged