Locksystem cleanup
space-wizards/space-station-14 pull request #13409
Opened 2023-01-10 01:23 UTC by Cheackraze

## About the PR 
cleans up some obsolete code in LockSystem
**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

-cleans up some obsolete code in LockSystem

2023-01-10 02:13 UTC, metalgearsloth requested changes

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
> +                _appearanceSystem.SetData(lockComp.Owner, StorageVisuals.CanLock, true, appearance);
```suggestion
                _appearanceSystem.SetData(uid, StorageVisuals.CanLock, true, appearance);
```

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
> +            _sharedPopupSystem.PopupEntity(Loc.GetString("lock-comp-do-lock-success", ("entityName", EntityManager.GetComponent<MetaDataComponent>(lockComp.Owner).EntityName)), lockComp.Owner, user);
```suggestion
            _sharedPopupSystem.PopupEntity(Loc.GetString("lock-comp-do-lock-success", ("entityName", EntityManager.GetComponent<MetaDataComponent>(uid).EntityName)), uid, user);
```

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
> +                _audio.PlayPvs(_audio.GetSound(lockComp.LockSound), lockComp.Owner, AudioParams.Default.WithVolume(-5));
```suggestion
                _audio.PlayPvs(_audio.GetSound(lockComp.LockSound), uid, AudioParams.Default.WithVolume(-5));
```

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
> +                    _audio.PlayPvs(_audio.GetSound(component.UnlockSound), component.Owner, AudioParams.Default.WithVolume(-5));
```suggestion
                    _audio.PlayPvs(_audio.GetSound(component.UnlockSound), uid, AudioParams.Default.WithVolume(-5));
```

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
> +                    _appearanceSystem.SetData(component.Owner, StorageVisuals.Locked, false, appearanceComp);
```suggestion
                    _appearanceSystem.SetData(uid, StorageVisuals.Locked, false, appearanceComp);
```

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
>                  {
Can you remove the == true while you're here as well?

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
> +                _appearanceSystem.SetData(lockComp.Owner, StorageVisuals.Locked, false, appearanceComp);
```suggestion
                _appearanceSystem.SetData(uid, StorageVisuals.Locked, false, appearanceComp);
```

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
> +                _audio.PlayPvs(_audio.GetSound(lockComp.UnlockSound), lockComp.Owner, AudioParams.Default.WithVolume(-5));
```suggestion
                _audio.PlayPvs(_audio.GetSound(lockComp.UnlockSound), uid, AudioParams.Default.WithVolume(-5));
```

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
> +                _sharedPopupSystem.PopupEntity(Loc.GetString("lock-comp-do-unlock-success", ("entityName", EntityManager.GetComponent<MetaDataComponent>(lockComp.Owner).EntityName)), lockComp.Owner,
```suggestion
                _sharedPopupSystem.PopupEntity(Loc.GetString("lock-comp-do-unlock-success", ("entityName", EntityManager.GetComponent<MetaDataComponent>(lockComp.Owner).EntityName)), uid, user.Value);
```

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
> +                _appearanceSystem.SetData(lockComp.Owner, StorageVisuals.Locked, true, appearanceComp);
```suggestion
                _appearanceSystem.SetData(uid, StorageVisuals.Locked, true, appearanceComp);
```

2023-01-10 02:13 UTC, metalgearsloth commented on Content.Server/Lock/LockSystem.cs
>              if (EntityManager.TryGetComponent(lockComp.Owner, out AppearanceComponent? appearanceComp))
```suggestion
            if (EntityManager.TryGetComponent(uid, out AppearanceComponent? appearanceComp))
```

2023-01-10 02:36 UTC, metalgearsloth approved these changes

2023-01-17 22:39 UTC, EmoGarbage404 commented
was this intentional? it looks like you just accidentally deleted your branch?

2023-01-17 22:43 UTC, Cheackraze commented
ye was clearing out old branches, whoops

2023-01-18 00:09 UTC, merged