Fix magboot action duplication
space-wizards/space-station-14 pull request #13467
Opened 2023-01-14 11:38 UTC by Theomund

## About the PR

This pull request resolves #13408, which described an issue where magnetic boots would duplicate their actions twice upon being equipped. After some debugging, I found out that the `OnGetActions` handler function was being called by the client and the server at the same time, causing the duplication to occur. I resolved the issue by moving the handler to the server's `MagbootsSystem` class.

**Media**

![Screenshot from 2023-01-14 06-29-10](https://user-images.githubusercontent.com/34360334/212469927-8ccbcb1b-2fb3-4f2e-b157-75b03612226d.png)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Magnetic boots no longer duplicate their item action when being equipped.

2023-01-14 11:45 UTC, metalgearsloth requested changes
Removing prediction is just working around it rather than fixing it.

2023-01-14 11:53 UTC, Theomund commented
> Removing prediction is just working around it rather than fixing it.

I will look into addressing that, and I will revert my current changes.

2023-01-14 12:11 UTC, closed without merging

2023-01-15 00:45 UTC, ElectroJr commented
FYI Fixing this properly is probably going to be somewhat difficult and either require patching around shitty action networking or just reworking it altogether

2023-01-23 20:14 UTC, 778b commented
I think it must be look like ToggleableClothingSystem 
![image](https://user-images.githubusercontent.com/33431126/214139933-d742d45a-0c4e-4829-972d-a8227edf7859.png)
Because now it looking worst 
![image](https://user-images.githubusercontent.com/33431126/214140035-840af0bc-0074-4d79-ad19-ae1064281cf6.png)
Maybe we will need to create new component for clothes for add action when it equipped? Because it will be very fine architecture improvement