Hide Aghosts from players
space-wizards/space-station-14 pull request #13594
Opened 2023-01-19 02:40 UTC by Mirino97

## About the PR

Simple command to hide aghosts from normal ghosts for administration privacy (and to help in metacomm cases as well)

**Media**

Video's too big to embbed, so here goes link.

In the left screen, you'll see me toggle between "admin vision" and "player vision" by changing the visibility mask. 
7 is "admin vision", 3 is "player vision".

When I toggle aghost hide from the right window, the ghost disappears in the left window when the left window is in "player vision" but still shows up in "admin vision".
https://streamable.com/y8tr3x

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Mirino
- add: Aghosts can now hide from other ghosts with the command toggleaghost.

2023-01-23 00:40 UTC, metalgearsloth requested changes
Using a component would be better as the command could just toggle a bool and would also handle cleanup for you.

2023-01-23 00:40 UTC, metalgearsloth commented on Content.Server/Administration/Commands/AGhost.cs
> +        [Dependency] private readonly EntityManager _entMan = default!;
You duplicated the dependency.

2023-01-23 00:40 UTC, metalgearsloth commented on Content.Server/Administration/Commands/ToggleAghostCommand.cs
> +    public string Description => "Shows or hides your aghost from other players";
localisation

2023-01-23 00:40 UTC, metalgearsloth commented on Content.Server/Administration/Commands/ToggleAghostCommand.cs
> +            shell.WriteLine("You can only toggle ghost visibility on a client.");
writeerror

2023-01-23 00:40 UTC, metalgearsloth commented on Content.Server/Administration/Commands/ToggleAghostCommand.cs
> +        var entityManager = IoCManager.Resolve<IEntityManager>();
Use a dependency

2023-01-23 00:40 UTC, metalgearsloth commented on Content.Server/Administration/Commands/ToggleAghostCommand.cs
> +        var _visibilitySystem = entityManager.EntitySysManager.GetEntitySystem<VisibilitySystem>();
This should check whether they are an aghost as compared to a regular ghost tbh, also local variables shouldn't be prefixed with _.

2023-01-23 00:40 UTC, metalgearsloth commented on Content.Server/Administration/Commands/AGhost.cs
> +                eyeComponent.VisibilityMask = (uint) VisibilityFlags.Ghost | (uint) VisibilityFlags.Aghost + 1;
Is this ever cleaned up? If someone goes back to a regular ghost it'll still have aghost, also you should use the enum for Normal rather than 1.

2023-02-07 20:59 UTC, AJCM-git commented
@Mirino97 you coming back to this?

2023-02-07 21:37 UTC, Mirino97 commented
Yes. Currently on the throes of trying to fix my Pc, then getting ready to move and buying a new Pc, but I will. You can pick it up tho, if you're interested.

Enviado do Yahoo Mail no Android 
 
  Em ter., 7 7e fev. 7e 2023 às 17:59, ***@***.***> escreveu:   


@Mirino97 you coming back to this?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-02-07 21:40 UTC, EmoGarbage404 commented
> Yes. Currently on the throes of trying to fix my Pc, then getting ready to move and buying a new Pc, but I will. You can pick it up tho, if you're interested.
> 
> Enviado do Yahoo Mail no Android 
>  
>   Em ter., 7 7e fev. 7e 2023 às 17:59, ***@***.***> escreveu:   
> 
> 
> @Mirino97 you coming back to this?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>   
> 

Enviado do Yahoo mail no Android

2023-02-07 21:43 UTC, GoodWheatley commented
> > Yes. Currently on the throes of trying to fix my Pc, then getting ready to move and buying a new Pc, but I will. You can pick it up tho, if you're interested.
> > Enviado do Yahoo Mail no Android
> > Em ter., 7 7e fev. 7e 2023 às 17:59, _**@**_.***> escreveu:
> > @Mirino97 you coming back to this?
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> Enviado do Yahoo mail no Android

You are receiving this because you were mentioned.Message ID: @.***>

2023-02-28 13:16 UTC, closed without merging