Add GHOST GANG!
space-wizards/space-station-14 pull request #13734
Opened 2023-01-26 17:09 UTC by Chief-Engineer

## About the PR

- Adds ghost plushie, a rare and special plushie
- Adds revenant plushie, a type of ghost plushie
- Revenants drop ectoplasm on death

Ghost plushies are very floaty, will move on their own, and can be made to orbit you. Ectoplasm can be used with a ghost plushie to create a revenant plushie.

**Media**

![ogU7eTMzLt](https://user-images.githubusercontent.com/119664036/214901740-d359df92-77e3-4cb3-b5de-e1a76a8bd46b.gif)
![image](https://user-images.githubusercontent.com/119664036/214901895-79863917-832b-4a02-9bd9-b6f5a43cb0b5.png)
![image](https://user-images.githubusercontent.com/119664036/214901985-b4d647ed-ae69-47bf-a7a1-b3940087ecfa.png)
![image](https://user-images.githubusercontent.com/119664036/214902138-9c8fc96f-eb48-4e61-9425-8400fff6341b.png)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Revenants now drop ectoplasm when they die.

2023-01-26 17:13 UTC, Visne commented
> add: Huge update!

Don't do this.

2023-01-26 18:11 UTC, moonheart08 commented
> > add: Huge update!
> 
> Don't do this.

Edited this out of the description (Reminder to triagers: You can edit issues and PRs)

2023-01-26 18:13 UTC, EmoGarbage404 commented
I feel like these should use new sprites rather than reusing old ones. Especially the ghost ones.

2023-01-27 00:33 UTC, EmoGarbage404 commented
> @EmoGarbage404 Why? They're meant to look exactly like ghosts and revenants.

personally, these sprites don't even look remotely like plushies. I get the idea of wanting to have a "gotcha" type of thing, but i don't really feel like that's very necessary. It's not like it's going to fool people past a single solitary instant.

the ghost "plush" being transparent is also equally weird. you can keep all the neat effects for the plushes, just make some new sprites that actually look like plushes.

2023-01-27 02:50 UTC, Visne commented
I feel like if the ghost plushie is rare enough then it using the same sprite is fine. It's definitely more fun that way, and players don't see the ghost while alive anyways, so it's not confusing or anything. That it doesn't look like a conventional real-life plushie is irrelevant in my opinion.

I'm a bit less certain about the revenant plushie using the same sprite though.

2023-01-28 03:54 UTC, CaptainSqrBeard commented
Maybe rename it into a toy instead if plushie? That can explain transparency I think

2023-01-28 03:59 UTC, metalgearsloth requested changes
These code changes look very suss as well. This should also have dedicated sprites.

2023-01-28 03:59 UTC, metalgearsloth commented on Content.Shared/Revenant/Components/RevenantComponent.cs
> +    public string SpawnOnDeathPrototype = "Ectoplasm";
Isn't there already a component for this?

2023-01-28 03:59 UTC, metalgearsloth commented on Content.Shared/Follower/FollowerSystem.cs
>          }
Does this cause issues on grid deletions / round restarts?

2023-01-28 03:59 UTC, metalgearsloth commented on Content.Shared/Construction/Steps/PrototypeConstructionGraphStep.cs
> +    }
This is very hacky and prototypes should not be used in this way.

2023-01-28 03:59 UTC, metalgearsloth commented on Content.Shared/Follower/FollowerSystem.cs
> +    }
This looks sussy?

2023-01-28 03:59 UTC, metalgearsloth commented on Content.Shared/Construction/Steps/ConstructionGraphStepTypeSerializer.cs
> +            }
As per the graph step this really shouldn't exist, prototypes should just be for spawning and not be used as some authority on what an entity is.

2023-01-28 03:59 UTC, metalgearsloth commented on Content.Server/Revenant/EntitySystems/RevenantSystem.cs
> +            Spawn(component.SpawnOnDeathPrototype, Transform(uid).Coordinates);
remove

2023-01-28 03:59 UTC, metalgearsloth commented on Content.Server/Physics/Controllers/RandomWalkController.cs
> +            ||  EntityManager.HasComponent<FollowerComponent>(randomWalk.Owner))
This should just be an event at this point?

2023-01-28 04:22 UTC, metalgearsloth commented on Content.Shared/Revenant/Components/RevenantComponent.cs
> +    public string SpawnOnDeathPrototype = "Ectoplasm";
Doesn't destructible handle "spawnondeath" stuff?

2023-01-28 04:45 UTC, metalgearsloth commented
> What's the point of having exact duplicate sprites?

It shouldn't, it should have toy variants like all the others.

2023-01-28 11:22 UTC, Visne commented
Changing the ghost sprite kinda ruins the whole gimmick.

2023-01-28 11:25 UTC, metalgearsloth commented on Content.Shared/Revenant/Components/RevenantComponent.cs
> +    public string SpawnOnDeathPrototype = "Ectoplasm";
Revenants have damageable?

2023-01-28 11:36 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +    - type: TileFrictionModifier
These stats make it especially janky because the pickup + following both mispredict a lot.

2023-04-22 08:08 UTC, metalgearsloth commented on Content.Shared/Follower/FollowerSystem.cs
>          }
StopFollowingEntity is called on grid deletions.

2023-04-22 08:17 UTC, metalgearsloth commented on Content.Shared/Follower/FollowerSystem.cs
> +        _containerSystem.AttachParentToContainerOrGrid(xform);  // In case it is an item in an inventory
This immediately gets bulldozed by the setparent.

2023-04-22 08:19 UTC, metalgearsloth commented on Content.Shared/Follower/FollowerSystem.cs
>          }
I'm just going to remove it and let callers handle it as it stops the cleanup events being raised which will cause other issues if anyone relies on those events.

2023-04-22 08:25 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +    - type: TileFrictionModifier
Do you have the fakelag disabled locally? It should be on by default.

2023-04-22 08:29 UTC, metalgearsloth commented
Still needs:
- Placing the plushie mispredicts.
- Throwing is a bit jank by being fully dynamic as it just travels almost indefinitely.
- Sprite visibility desyncs as soon as you place it down and pick it up.

2023-05-28 09:21 UTC, metalgearsloth approved these changes

2023-05-28 09:21 UTC, merged