Personal AIs can now access the crew manifest
space-wizards/space-station-14 pull request #13740
Opened 2023-01-27 01:53 UTC by JustinTrotter

## About the PR

Set up a new action for pAIs to view the crew manifest. Should only apply to the station that they are currently on and only if the CCvars are set to allow unsecure crew manifest viewing.

**Media**

![screenshot_pai_crew_manifest](https://user-images.githubusercontent.com/8183999/214993355-0c61b6bc-4e48-49d7-9db2-bc0307a466ea.png)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Personal AIs can now access the crew manifest

2023-01-27 01:57 UTC, JustinTrotter commented
If/when this gets merged. I'll add something similar for ghosts.

2023-01-27 04:26 UTC, AJCM-git commented
Cant you use a `IntrinsicUiComponent`?

2023-01-28 09:01 UTC, metalgearsloth requested changes

2023-01-28 09:01 UTC, metalgearsloth commented on Content.Server/CrewManifest/CrewManifestSystem.cs
> +        if (owningStation == null || actor == null || actor.PlayerSession is not IPlayerSession sessionCast)
You shouldn't copy-paste code between methods like this as any bugfixes need to be copy-pasted assuming whoever fixes them sees them both. They should both be calling the same method.

2023-02-28 13:18 UTC, AJCM-git commented
@JustinTrotter you coming back to this?

2023-02-28 14:51 UTC, closed without merging