Dame Dane Guy Outfit
space-wizards/space-station-14 pull request #13787
Opened 2023-01-29 20:11 UTC by Alekshhh

## About the PR
Adds Kazuma Kiryu's outfit from the Yakuza series. Includes shoes, outfit and coat. Can be found in the autodrobe.

**Media**

![image](https://user-images.githubusercontent.com/44923899/215353120-ef538b01-c009-479f-ad6b-036687455d6e.png)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Aleksh
- add: Added Dame Dane clothing set. EEYIKES!

2023-01-30 14:10 UTC, brainfood1183 commented
you have two entities with the same id. Clothinguniformjumpsuitsdamedane is given to both the jumpsuit and jumpskirt. you should change the id of the jumpskirt to clothinguniformjumpskirtdamedane. Then you would likely have to add that id to the clothingvend.

2023-02-11 02:29 UTC, AJCM-git requested changes

2023-02-11 02:29 UTC, AJCM-git commented on Resources/Textures/Clothing/OuterClothing/Coats/damedanecoat.rsi/meta.json
> +  "copyright": "Created by Alekshhh, original design by SEGA",
```suggestion
  "copyright": "Made by Alekshhh (Github) for SS14, inspired by Kazuma Kiryu outfit",
```

2023-02-11 02:29 UTC, AJCM-git commented on Resources/Textures/Clothing/Shoes/Misc/damedaneshoes.rsi/meta.json
> +  "copyright": "Created by Alekshhh, original design by SEGA",
```suggestion
  "copyright": "Made by Alekshhh (Github) for SS14, inspired by Kazuma Kiryu outfit",
```

2023-02-11 02:29 UTC, AJCM-git commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/damedaneoutfit.rsi/meta.json
> +  "copyright": "Created by Alekshhh, original design by SEGA",
```suggestion
  "copyright": "Made by Alekshhh (Github) for SS14, inspired by Kazuma Kiryu outfit",
```

2023-02-11 03:13 UTC, AJCM-git approved these changes

2023-02-11 03:14 UTC, merged