Rigged boxing gloves
space-wizards/space-station-14 pull request #13847
Opened 2023-02-01 23:51 UTC by GoodWheatley

## About the PR

This PR adds a new Passenger & Boxer-exclusive item, Rigged Boxing Gloves. These gloves have covertly installed weights inside them, causing them to do significant Blunt and Stamina damage per punch. However, the added weight also reduces how fast you can punch with the gloves. I believe this is a better way to implement a disguised stun than the Electro Gloves PR because a) it takes 4 hits to stun someone instead of two, b) the boxing gloves sprite is must much visible than yellow gloves, and c) only one job on the station can reliably have this, unless somebody got lucky with a surplus.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Rigged Boxing Gloves are now available in the uplink for 5 TC, if you're a Passenger or Boxer.

2023-02-01 23:52 UTC, EmoGarbage404 commented
kinda just tangentially related, but boxer is currently unused as Lighthouse was the last map to implement it and no one has added it to their map since (as far as I know).

2023-02-01 23:54 UTC, metalgearsloth commented
If this is unused there's no point merging it

2023-02-01 23:55 UTC, EmoGarbage404 commented
> If this is unused there's no point merging it

it's available for passengers, which is kinda fine I guess.

2023-02-01 23:57 UTC, metalgearsloth commented
Are boxing gloves mapped on every station? Seeing someone walking around with em would be highly suss if they were syndie items.

2023-02-01 23:58 UTC, EmoGarbage404 commented
boxing gloves are pretty common, yeah.

2023-02-02 00:02 UTC, GoodWheatley commented
> kinda just tangentially related, but boxer is currently unused as Lighthouse was the last map to implement it and no one has added it to their map since (as far as I know).

future proofing in case a new map adds it back

2023-02-03 08:51 UTC, deltanedas commented
reasons for tiders to wear boxing gloves
- easily accessible way of hiding fingerprints, if det actually does anything
- can stun with punches very good against flukies

2023-02-28 19:58 UTC, AJCM-git requested changes
this may conflict with #13935 design-wise

2023-02-28 19:58 UTC, AJCM-git commented on Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
> +    - type: FingerprintMask
Just inherit ClothingHandsGlovesBoxingBlue and get rid of this

2023-03-01 14:15 UTC, GoodWheatley commented
> this may conflict with #13935 design-wise

The title for that is incorrect, the author changed the PR to just remove the combat bonus outright.

2023-03-27 10:52 UTC, deltanedas requested changes

2023-03-27 10:52 UTC, deltanedas commented on Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
> +  description: Blue gloves for competitive boxing. Feels like they're heavier than usual...
the only way to validcheck should be the boxer being suspiciously robust not walk up, strip, shift click gloves

2023-03-27 10:52 UTC, deltanedas commented on Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
> +        Blunt: 8
damage too since its an extra click

2023-04-19 03:12 UTC, AJCM-git commented
@GoodWheatley you coming back to this?

2023-04-19 11:09 UTC, GoodWheatley commented
> @GoodWheatley you coming back to this?

It’s ready to merge

2023-04-19 19:43 UTC, AJCM-git commented
> > @GoodWheatley you coming back to this?
> 
> It’s ready to merge

Then merge master to see if tests passes and resolve delta's reviews

2023-04-22 23:08 UTC, merged