Resolves GravityGeneratorVisualizer is Obsolete
space-wizards/space-station-14 pull request #13885
Opened 2023-02-03 07:42 UTC by TemporalOroboros

## About the PR

Splits the GravityGeneratorVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-02-03 07:44 UTC, metalgearsloth requested changes
Just use the gravitygeneratorcomponent

2023-02-03 08:01 UTC, TemporalOroboros commented
> Just use the gravitygeneratorcomponent

Do you want me to make a client version of SharedGravityGeneratorComponent or move the sprite map to shared (and therefor the server)?

2023-02-03 08:04 UTC, metalgearsloth commented
The status should be on shared; using a separate comp state for it would also potentially mean removing appearancecomponent.

2023-02-15 20:10 UTC, AJCM-git requested changes

2023-02-15 20:10 UTC, AJCM-git commented on Content.Client/Gravity/GravitySystem.cs
> +    }
i dont think this is necessary

2023-02-15 20:10 UTC, AJCM-git commented on Content.Shared/Gravity/SharedGravityGeneratorComponent.cs
> +        [DataField("coreActivatedState")]
VV

2023-03-25 05:47 UTC, TemporalOroboros commented on Content.Client/Gravity/GravitySystem.cs
> +    }
Turns out it wasn't.

2023-03-25 05:47 UTC, TemporalOroboros commented on Content.Shared/Gravity/SharedGravityGeneratorComponent.cs
> +        [DataField("coreActivatedState")]
Done.

2023-03-25 05:48 UTC, TemporalOroboros commented
@DrSmugleaf 
Pushing commits isn't reopening the PR. Please reopen it at your convenience.

2023-03-31 05:04 UTC, metalgearsloth approved these changes

2023-03-31 05:04 UTC, merged