Resolves MedicalScannerVisualizer is Obsolete
space-wizards/space-station-14 pull request #13893
Opened 2023-02-03 07:52 UTC by TemporalOroboros

## About the PR

Splits the MedicalScannerVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-02-03 21:57 UTC, AJCM-git requested changes

2023-02-03 21:57 UTC, AJCM-git commented on Content.Client/MedicalScanner/MedicalScannerVisualizerComponent.cs
> +public sealed class MedicalScannerVisualizerComponent : Component
move to MedicalScannerComponent

2023-02-03 21:57 UTC, AJCM-git commented on Content.Client/MedicalScanner/MedicalScannerVisualizerSystem.cs
> +        if(!AppearanceSystem.TryGetData(uid, MedicalScannerVisuals.Status, out MedicalScannerStatus status, args.Component))
generic

2023-02-03 21:57 UTC, AJCM-git commented on Content.Client/MedicalScanner/MedicalScannerVisualizerComponent.cs
> +public sealed class MedicalScannerVisualizerComponent : Component
move to MedicalScannerComponent

2023-02-03 21:57 UTC, AJCM-git commented on Content.Client/MedicalScanner/MedicalScannerVisualizerSystem.cs
> +            case Yellow: return "occupied";
unhardcode

2023-02-03 21:57 UTC, AJCM-git commented on Content.Client/MedicalScanner/MedicalScannerVisualizerSystem.cs
> +            case Yellow: return "maint_unlit";
same

2023-02-15 22:26 UTC, AJCM-git requested changes

2023-02-15 22:26 UTC, AJCM-git commented on Content.Client/MedicalScanner/MedicalScannerComponent.cs
> +    // TODO: ECS DragDrop
merge fail?

2023-02-15 22:26 UTC, AJCM-git commented on Content.Client/MedicalScanner/MedicalScannerComponent.cs
> +public sealed class MedicalScannerComponent : SharedMedicalScannerComponent
access

2023-02-15 22:26 UTC, AJCM-git commented on Content.Client/MedicalScanner/MedicalScannerComponent.cs
> +    public readonly Dictionary<MedicalScannerStatus, string> TerminalStateStatusMap = new()
VV, datafield

2023-02-15 22:26 UTC, AJCM-git commented on Content.Client/MedicalScanner/MedicalScannerSystem.cs
> +        if(!AppearanceSystem.TryGetData<MedicalScannerStatus>(uid, MedicalScannerVisuals.Status, out var status, args.Component))
newline

2023-03-06 18:13 UTC, DrSmugleaf commented
Reopen when you come back to this.

2023-03-25 07:01 UTC, TemporalOroboros commented on Content.Client/MedicalScanner/MedicalScannerComponent.cs
> +    // TODO: ECS DragDrop
Should be fixed now.

2023-03-25 07:01 UTC, TemporalOroboros commented on Content.Client/MedicalScanner/MedicalScannerComponent.cs
> +public sealed class MedicalScannerComponent : SharedMedicalScannerComponent
Done.

2023-03-25 07:02 UTC, TemporalOroboros commented on Content.Client/MedicalScanner/MedicalScannerComponent.cs
> +    public readonly Dictionary<MedicalScannerStatus, string> TerminalStateStatusMap = new()
Done.

2023-03-25 22:05 UTC, TemporalOroboros commented
@DrSmugleaf 
Commits tested and pushed, reopen at your leisure.

2023-03-25 22:05 UTC, TemporalOroboros commented on Content.Client/MedicalScanner/MedicalScannerSystem.cs
> +        if(!AppearanceSystem.TryGetData<MedicalScannerStatus>(uid, MedicalScannerVisuals.Status, out var status, args.Component))
Done.

2023-03-26 19:25 UTC, AJCM-git approved these changes

2023-03-26 19:26 UTC, merged