Resolves ParticleAcceleratorPartVisualizer is Obsolete
space-wizards/space-station-14 pull request #13897
Opened 2023-02-03 07:52 UTC by TemporalOroboros

## About the PR

Splits the ParticleAcceleratorPartVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-02-15 18:29 UTC, AJCM-git requested changes

2023-02-15 18:29 UTC, AJCM-git commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerComponent.cs
> +public sealed class ParticleAcceleratorPartVisualizerComponent : Component
visuals

2023-02-15 18:29 UTC, AJCM-git commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerComponent.cs
> +    public static readonly Dictionary<ParticleAcceleratorVisualState, string> StatesSuffixes = new()
VV

2023-02-15 18:29 UTC, AJCM-git commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerSystem.cs
> +        SubscribeLocalEvent<ParticleAcceleratorPartVisualizerComponent, ComponentInit>(OnInit);
oncomponentinit

2023-02-15 18:29 UTC, AJCM-git commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerSystem.cs
> +    }
i dont think this is necessary

2023-02-15 18:29 UTC, AJCM-git commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerSystem.cs
> +        if (!AppearanceSystem.TryGetData(uid, ParticleAcceleratorVisuals.VisualState, out ParticleAcceleratorVisualState state, args.Component))
generic

2023-03-06 18:13 UTC, DrSmugleaf commented
Reopen when you come back to this.

2023-03-25 22:21 UTC, TemporalOroboros commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerSystem.cs
> +    }
Alright.

2023-03-25 23:17 UTC, TemporalOroboros commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerComponent.cs
> +public sealed class ParticleAcceleratorPartVisualizerComponent : Component
Done

2023-03-25 23:17 UTC, TemporalOroboros commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerSystem.cs
> +        if (!AppearanceSystem.TryGetData(uid, ParticleAcceleratorVisuals.VisualState, out ParticleAcceleratorVisualState state, args.Component))
Done

2023-03-25 23:19 UTC, TemporalOroboros commented
@DrSmugleaf 
Commits tested and pushed, reopen at your leisure.

2023-03-25 23:19 UTC, TemporalOroboros commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerSystem.cs
> +        SubscribeLocalEvent<ParticleAcceleratorPartVisualizerComponent, ComponentInit>(OnInit);
Removed as unnecessary.

2023-03-26 15:11 UTC, AJCM-git requested changes

2023-03-26 15:12 UTC, AJCM-git commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerComponent.cs
> +    public static readonly Dictionary<ParticleAcceleratorVisualState, string> StatesSuffixes = new()
dont make this static

2023-04-07 03:34 UTC, TemporalOroboros commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerSystem.cs
> +    }
Point.

2023-04-07 03:34 UTC, TemporalOroboros commented on Content.Client/ParticleAccelerator/ParticleAcceleratorPartVisualizerComponent.cs
> +    public static readonly Dictionary<ParticleAcceleratorVisualState, string> StatesSuffixes = new()
Alright.

2023-04-22 09:39 UTC, merged