Resolve PoweredLightVisualizer is Obsolete
space-wizards/space-station-14 pull request #13891
Opened 2023-02-03 07:51 UTC by TemporalOroboros

## About the PR

Splits the PoweredLightVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-02-03 21:50 UTC, AJCM-git requested changes

2023-02-03 21:50 UTC, AJCM-git commented on Content.Client/Light/Visualizers/PoweredLightVisualizerComponent.cs
> +    [DataField("blinkingSound")] public SoundSpecifier? BlinkingSound = default;
separate the attribute from the field (also VV)

2023-02-03 21:50 UTC, AJCM-git commented on Content.Client/Light/Visualizers/PoweredLightVisualizerComponent.cs
> +    public Action<string>? BlinkingCallback;
VV?

2023-02-03 21:50 UTC, AJCM-git commented on Content.Client/Light/Visualizers/PoweredLightVisualizerSystem.cs
> +public sealed class PoweredLightVisualizerComponent : Component
oops

2023-02-03 21:50 UTC, AJCM-git commented on Content.Client/Light/Visualizers/PoweredLightVisualizerSystem.cs
> +        if (!AppearanceSystem.TryGetData(uid, PoweredLightVisuals.BulbState, out PoweredLightState state, args.Component))
generic, newline

2023-02-03 21:50 UTC, AJCM-git commented on Content.Client/Light/Visualizers/PoweredLightVisualizerSystem.cs
> +        }
unhardcode

2023-02-03 21:50 UTC, AJCM-git commented on Content.Client/Light/Visualizers/PoweredLightVisualizerSystem.cs
> +                    args.Sprite!.LayerSetState(PoweredLightLayers.Base, "on");
i dont think the null forgiving operator here matters

2023-02-03 21:50 UTC, AJCM-git commented on Content.Client/Light/Visualizers/PoweredLightVisualizerSystem.cs
> +    }
move the key to the component, i dont thunk `ToggleBlinkingAnimation` needs `AppearanceChangeEvent` as an argument, make `OnAnimationCompleted` use `ToggleBlinkingAnimation`

2023-02-11 10:31 UTC, TemporalOroboros commented on Content.Client/Light/Visualizers/PoweredLightVisualizerComponent.cs
> +    public Action<string>? BlinkingCallback;
Removed

2023-02-16 04:10 UTC, AJCM-git approved these changes

2023-02-16 04:10 UTC, merged