Resolves ThrusterVisualizer is Obsolete
space-wizards/space-station-14 pull request #13904
Opened 2023-02-03 07:55 UTC by TemporalOroboros

## About the PR

Splits the ThrusterVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-02-03 17:09 UTC, ElectroJr commented on Content.Client/Shuttles/ThrusterVisualizerSystem.cs
> +                    {
use the actual out value

2023-02-15 22:13 UTC, AJCM-git requested changes
this has a bug where when you turn a thruster off the propulsion animation starts

2023-02-15 22:13 UTC, AJCM-git commented on Content.Client/Shuttles/ThrusterVisualizerSystem.cs
> +        if(!AppearanceSystem.TryGetData<bool>(uid, ThrusterVisualState.State, out var state, args.Component))
newline

2023-02-15 22:13 UTC, AJCM-git commented on Content.Client/Shuttles/ThrusterVisualsComponent.cs
> +public sealed class ThrusterVisualsComponent : Component {}
access

2023-03-06 18:13 UTC, DrSmugleaf commented
Reopen when you come back to this.

2023-05-07 09:04 UTC, TemporalOroboros commented on Content.Client/Shuttles/ThrusterVisualizerSystem.cs
> +        if(!AppearanceSystem.TryGetData<bool>(uid, ThrusterVisualState.State, out var state, args.Component))
Merged into upper if statement.

2023-05-07 09:04 UTC, TemporalOroboros commented on Content.Client/Shuttles/ThrusterVisualsComponent.cs
> +public sealed class ThrusterVisualsComponent : Component {}
Done

2023-05-07 09:54 UTC, TemporalOroboros commented
@DrSmugleaf 
Commits tested and pushed.

2023-05-07 13:37 UTC, merged