Resolves BagOpenCloseVisualizer is Obsolete
space-wizards/space-station-14 pull request #13909
Opened 2023-02-03 07:56 UTC by TemporalOroboros

## About the PR

Splits the BagOpenCloseVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-02-14 03:40 UTC, AJCM-git requested changes
pretty sure this can be a gen vis, leaving these just in case

2023-02-14 03:40 UTC, AJCM-git commented on Content.Client/Storage/Visualizers/BagOpenCloseVisualizerComponent.cs
> +public sealed class BagOpenCloseVisualizerComponent : Component
move to ClientStorageComponent (cursed E/C oldcode, brace your eyes)

2023-02-14 03:40 UTC, AJCM-git commented on Content.Client/Storage/Visualizers/BagOpenCloseVisualizerSystem.cs
> +public sealed class BagOpenCloseVisualizerSystem : VisualizerSystem<BagOpenCloseVisualizerComponent>
StorageSystem

2023-02-14 03:40 UTC, AJCM-git commented on Content.Client/Storage/Visualizers/BagOpenCloseVisualizerSystem.cs
> +    }
pretty sure everything here is useless and you just have to double check that layers are mapped correctly in the prototypes with this component before removing this

2023-02-14 03:40 UTC, AJCM-git commented on Content.Client/Storage/Visualizers/BagOpenCloseVisualizerComponent.cs
> +    public const string OpenIconLayer = "openIcon";
cursed

2023-02-14 03:40 UTC, AJCM-git commented on Content.Client/Storage/Visualizers/BagOpenCloseVisualizerSystem.cs
> +        }
this can be reduced to 
`                args.Sprite.LayerSetVisible(BagOpenCloseVisualizerComponent.OpenIconLayer, bagState);`

2023-03-06 18:14 UTC, DrSmugleaf commented
Reopen when you come back to this.

2023-04-20 07:29 UTC, TemporalOroboros commented
Converted to a generic visualizer. Commits tested and pushed.
@DrSmugleaf Reopen whenever is convenient.

2023-04-22 09:23 UTC, metalgearsloth commented
This PR is extremely cooked.

2023-04-22 09:23 UTC, closed without merging

2023-05-13 23:42 UTC, TemporalOroboros commented
@metalgearsloth 
Cookedness should be fixed and I've made it into a generic visualizer.
Please reopen whenever is most convenient.

2023-05-14 00:05 UTC, AJCM-git commented
i think you force pushed to the repo before opening the pr which apparently makes it impossible to reopen??

2023-05-14 01:29 UTC, TemporalOroboros commented
Opened a new version over here. #16399