Resolves FoldableVisualizer is Obsolete
space-wizards/space-station-14 pull request #13913
Opened 2023-02-03 07:56 UTC by TemporalOroboros

## About the PR

Splits the FoldableVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-02-03 22:39 UTC, AJCM-git requested changes
Generic visualizer (make a FoldableBase prototype or something with it)

2023-02-04 03:27 UTC, TemporalOroboros commented
> Generic visualizer (make a FoldableBase prototype or something with it)

Conflicts with a generic visualizer that's already on one of the entities. Should I just copy-paste from the base prototype?

2023-02-04 03:46 UTC, AJCM-git commented
> Conflicts with a generic visualizer that's already on one of the entities. Should I just copy-paste from the base prototype?

yeah, just add the same logic to the overwriting visualizer (make a comment like "foldable enums" or smt")

2023-02-04 04:29 UTC, TemporalOroboros commented
> > Conflicts with a generic visualizer that's already on one of the entities. Should I just copy-paste from the base prototype?
> 
> yeah, just add the same logic to the overwriting visualizer (make a comment like "foldable enums" or smt")

Turns out all of the uses had different base states so I had to copypasta for all of them.

2023-02-04 15:56 UTC, AJCM-git commented on Resources/Prototypes/Entities/Structures/Furniture/rollerbeds.yml
> +  parents: BaseItem
oop

2023-02-04 21:34 UTC, AJCM-git requested changes
Delete FoldableVisualLayers enum since its no longer used in code, dynamically generate it  in the prototype instead, also i think you can reduce boilerplate if you make another mapped layer in the sprite with a folded state that is invisible, then you can inherit the visualizer since it sets visibility and not state, for example
```yml
  - type: Sprite
    layers:
    - state: bag
      map: ["unfoldedLayer"] # dynamically generated
    - state: bag_folded 
      map: ["foldedLayer"] # dynamically generated
      visible: false
  - type: GenericVisualizer
    visuals:
      enum.FoldedVisuals.State:
        unfoldedLayer:
          True: {visible: false}
          False: {state: true}
        foldedLayer:
          True: {visible: true}
          False: {state: false}
```
(obviously you would have to copypaste for the ones that overwrite the visualizer but eh)

2023-02-04 22:18 UTC, AJCM-git requested changes
make a BaseFoldable prototype or something with the gen vis and inherit that whenever possible (reminder that the syntax for multiple parents is `parent: [foobar, barfoo]`

2023-02-04 22:28 UTC, AJCM-git commented on Resources/Prototypes/Entities/Structures/Furniture/rollerbeds.yml
>        key: emergency_rollerbed
oops

2023-02-05 00:17 UTC, AJCM-git requested changes
even if an entity has multiple parents you still have to use `parent` as singular (also try running the game before pushing, many of these you can catch yourself when running)

2023-02-05 00:17 UTC, AJCM-git commented on Resources/Prototypes/Entities/Objects/Specific/Medical/morgue.yml
> +  parents: [BaseFoldable]
if you are using a single parent then declare it normally

2023-02-06 14:44 UTC, AJCM-git approved these changes

2023-02-06 19:53 UTC, merged