Resolves TimerTriggerVisualizer is Obsolete
space-wizards/space-station-14 pull request #13912
Opened 2023-02-03 07:56 UTC by TemporalOroboros

## About the PR

Splits the TimerTriggerVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-02-14 03:28 UTC, AJCM-git requested changes

2023-02-14 03:28 UTC, AJCM-git commented on Content.Client/Trigger/TimerTriggerVisualizerSystem.cs
> +        if(!TryComp<AnimationPlayerComponent>(uid, out var animPlayer))
newline

2023-02-14 03:28 UTC, AJCM-git commented on Content.Client/Trigger/TimerTriggerVisualizerSystem.cs
> +        }
single object initializer, unhardcode

2023-02-14 03:28 UTC, AJCM-git commented on Content.Client/Trigger/TimerTriggerVisualizerSystem.cs
> +        SubscribeLocalEvent<TimerTriggerVisualizerComponent, ComponentInit>(OnInit);
OnComponentInit

2023-02-14 03:28 UTC, AJCM-git commented on Content.Client/Trigger/TimerTriggerVisualizerSystem.cs
> +        if(!TryComp<AnimationPlayerComponent>(uid, out var animPlayer))
newline

2023-02-14 03:28 UTC, AJCM-git commented on Content.Client/Trigger/TimerTriggerVisualizerSystem.cs
> +        if (!AppearanceSystem.TryGetData(uid, TriggerVisuals.VisualState, out TriggerVisualState state, args.Component))
generic

2023-02-14 03:28 UTC, AJCM-git commented on Content.Client/Trigger/TimerTriggerVisualizerSystem.cs
> +                args.Sprite.LayerSetState(0, "icon");
unhardcode

2023-02-14 03:28 UTC, AJCM-git commented on Content.Client/Trigger/TimerTriggerVisualizerComponent.cs
> +public sealed class TimerTriggerVisualizerComponent : Component
rename to visuals

2023-02-14 03:28 UTC, AJCM-git commented on Content.Server/Entry/IgnoredComponents.cs
> +            "TimerTriggerVisualizer",
remove

2023-02-14 03:28 UTC, AJCM-git commented on Content.Client/Trigger/TimerTriggerVisualizerComponent.cs
> +    [DataField("countdown_sound")]
camelCase, vv

2023-03-06 18:14 UTC, DrSmugleaf commented
Reopen when you come back to this.

2023-05-13 19:43 UTC, TemporalOroboros commented
@DrSmugleaf 
Commits tested and pushed, please reopen whenever is most convenient.

2023-05-13 21:18 UTC, AJCM-git approved these changes

2023-05-13 21:18 UTC, merged