Resolves GenericEnumVisualizer is Obsolete
space-wizards/space-station-14 pull request #13914
Opened 2023-02-03 07:56 UTC by TemporalOroboros

## About the PR

Splits the GenericEnumVisualizer into a component/system pair.

### TODO:
- [ ] Testing

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-02-13 23:27 UTC, AJCM-git requested changes
remove GenericEnumVisualizer and replace its usages with a gen vis

2023-03-06 18:14 UTC, DrSmugleaf commented
Reopen when you come back to this.

2023-05-14 01:25 UTC, TemporalOroboros commented
@DrSmugleaf 
Commits tested and pushed. It should be good to go whenever is convenient for you.

2023-05-15 04:38 UTC, AJCM-git requested changes

2023-05-15 04:38 UTC, AJCM-git commented on Resources/Prototypes/Entities/Structures/meat_spike.yml
> +        base:
this has no base mapped

2023-05-15 04:38 UTC, AJCM-git commented on Resources/Prototypes/Entities/Objects/Fun/pai.yml
> +      map: ["base"]
is this used?

2023-05-15 18:19 UTC, TemporalOroboros commented on Resources/Prototypes/Entities/Objects/Fun/pai.yml
> +      map: ["base"]
No.

2023-05-15 18:55 UTC, merged