Salvage magnet shows cooldown time on Examine (revived)
space-wizards/space-station-14 pull request #14007
Opened 2023-02-09 17:33 UTC by deltanedas

## About the PR
revival of #13214

**Media**
working with current master, on Aspid (:rocket:)
![magnet](https://user-images.githubusercontent.com/39013340/217892494-d5baad95-183e-49e0-a98d-09a4c5689c3b.png)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Errant
- tweak: Salvage magnet shows remaining cooldown time when examined.)

2023-02-10 23:02 UTC, AJCM-git requested changes
Why not use the `SalvageMagnetComponent` `CooldownTime` instead of these checks?

2023-02-11 14:53 UTC, deltanedas commented
isn't CooldownTime the time it takes to cool down, not how much time is left

2023-02-22 07:08 UTC, deltanedas commented
@AJCM-git a

2023-03-03 16:25 UTC, DrSmugleaf approved these changes

2023-03-03 16:25 UTC, merged