Make counters climbable
space-wizards/space-station-14 pull request #14085
Opened 2023-02-13 04:43 UTC by EmoGarbage404

## About the PR

cleans up the prototypes because of parenting issues.
makes them properly vault able

the justification is that being able to hide behind counters and not deal with people climbing over is really boring and unintuitive.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: You can now climb on counters.

2023-02-13 10:47 UTC, deltanedas commented
*HoP chuckles*
HoP says: "I'm in danger"

2023-02-13 11:37 UTC, metalgearsloth requested changes

2023-02-13 11:37 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Structures/Furniture/Tables/base_structuretables.yml
> +    netsync: false
TableBase is netsync false you spud

2023-02-13 11:37 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Structures/Furniture/Tables/tables.yml
> +    base: state_
Dupe

2023-02-13 11:37 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Structures/Furniture/Tables/tables.yml
> +    base: state_
Dupe

2023-02-14 18:31 UTC, DrSmugleaf approved these changes

2023-02-14 23:07 UTC, metalgearsloth approved these changes

2023-02-14 23:08 UTC, merged