implant locale + priority tweaks
space-wizards/space-station-14 pull request #14149
Opened 2023-02-17 10:42 UTC by deltanedas

## About the PR
moves implant actions to the bottom of the ui, tweaks their names

**Media**

microbomb implant before changes, breaks combat mode muscle memory with potentially *explosive* consequences
![101505](https://user-images.githubusercontent.com/39013340/219622232-8ee1b1cb-a26d-420b-9c77-801e20213ca4.png)

they go at the bottom now

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

2023-02-17 19:47 UTC, deltanedas commented
dont think ci is my fault :tm:

2023-02-24 01:00 UTC, keronshb requested changes
Just some small value tweaks otherwise it's good to go.

2023-02-24 01:00 UTC, keronshb commented on Resources/Prototypes/Actions/types.yml
> +  priority: -22
```suggestion
  priority: -10
```

Same as above.

2023-02-24 07:05 UTC, deltanedas commented on Resources/Prototypes/Actions/types.yml
> +  priority: -20
ill just make them all -20 since -10 might put them inbetween other actions (ninja ones at least)

2023-02-24 23:19 UTC, keronshb approved these changes

2023-02-24 23:20 UTC, keronshb commented on Resources/Prototypes/Actions/types.yml
> +  priority: -20
Fair enough.

2023-02-24 23:20 UTC, merged