uichange Fix Grinder
space-wizards/space-station-14 pull request #14234
Opened 2023-02-23 02:39 UTC by DEATHB4DEFEAT

## About the PR

**Media**

![image](https://user-images.githubusercontent.com/77995199/220809716-88a2d167-b59b-414e-a002-92f20aefda7d.png)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: DEATHB4DEFEAT
- fix: Fixed grinder UI being too small.

2023-02-26 03:29 UTC, jamessimo commented
Shouldn't there be some margin bottom around the large eject buttons and the list box under it? Looks strange touching. I dont mind larger buttons bu they may be a little too large.

2023-02-26 03:30 UTC, DEATHB4DEFEAT commented
> Shouldn't there be some margin bottom around the large eject buttons and the list box under it?

there should be

2023-03-23 04:10 UTC, AJCM-git requested changes
what jamessimo said

2023-03-25 14:50 UTC, AJCM-git approved these changes

2023-03-25 14:51 UTC, merged