Feature/store chat size
space-wizards/space-station-14 pull request #14299
Opened 2023-02-27 01:59 UTC by vulppine

## About the PR

Adds the ability for a user set chat size to be stored into the configuration file, so when the game is started up again, the last set chat size is restored. This is per screen type (i.e., default and separated style screen layouts have their own separate stored chat sizes)

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Chat size storage. Now you don't have to resize the chat constantly every time you start up the game!

2023-02-27 02:00 UTC, Emisse commented
thank you my child old chat usable finally

2023-02-27 02:50 UTC, DrSmugleaf commented
Make the default not a 50/50 split I beg you

2023-02-27 05:22 UTC, vulppine commented
> Make the default not a 50/50 split I beg you

ok

![image](https://user-images.githubusercontent.com/76629141/221480877-5e412612-a04d-4783-a14c-12622ac74f56.png)

2023-03-02 19:16 UTC, DrSmugleaf requested changes

2023-03-05 02:56 UTC, vulppine commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("ui.separated_chat_size", "0.6,0", CVar.CLIENTONLY | CVar.ARCHIVE);
this should be a good enough size for a 720p screen (which seems to be the default size for SS14 unmaximized)

2023-03-06 19:06 UTC, DrSmugleaf approved these changes

2023-03-06 19:06 UTC, merged