Add EmoteOnDamage comp/system for zombies
space-wizards/space-station-14 pull request #14371
Opened 2023-03-03 15:05 UTC by 0x6273

Gets rid of `ActiveZombieComponent`, adds new `EmoteOnDamageComponent` and system that does the same thing but more reusable.

It's similar to AutoEmote but I decided not to support per-emote chance and cooldown values on this one to keep it simple.

Also, this fixes a bug where if a mob becomes a zombie some other way than changing mobstate to critical (such as admin antag ctrl, or the "turn into zombie" action) they would not get all of the zombie behavior.

2023-03-03 15:13 UTC, EmoGarbage404 commented
Do the emotes still play on damage if the entity is incapacitated?

2023-03-03 15:32 UTC, 0x6273 commented
> Do the emotes still play on damage if the entity is incapacitated?

I don't think I've changed anything related to this. They should play only when mobstate is `MobState.Alive`.

2023-03-04 16:48 UTC, brainfood1183 commented
we need a system that handles infection on damage like how zombies infect crew and turn them into zombies so we can apply this to other forms of infection from "conversion" monsters.

2023-03-06 03:37 UTC, AJCM-git requested changes
looks good (a video in the pr body would be appreciated)

2023-03-06 03:37 UTC, AJCM-git commented on Content.Server/Chat/Systems/EmoteOnDamageSystem.cs
> +        _chatSystem.TryEmoteWithoutChat(uid, emote);
make WithoutChat opt-out with a field in the component

2023-03-07 02:41 UTC, AJCM-git commented on Content.Server/Chat/EmoteOnDamageComponent.cs
> +    public bool HiddenFromChatWindow = false;
arent these the same or am i missing something? (also dont forget the video in the pr body)

2023-03-14 21:40 UTC, AJCM-git commented
@0x6273 you coming back to this?

2023-03-15 10:07 UTC, 0x6273 commented
> @0x6273 you coming back to this?

It's ready for review/merge. There's no video because it doesn't change anything that's visible to players.

2023-03-23 14:52 UTC, merged