Cuffable/Handcuff ECS
space-wizards/space-station-14 pull request #14382
Opened 2023-03-04 03:52 UTC by EmoGarbage404

## About the PR

- predicted
- ECS
- cleanup
- makes the brain tingle
- i tested it bro trust me

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl no fun

2023-03-06 23:44 UTC, metalgearsloth requested changes
Access attribute + VVAccess.ReadWrite (gottem)

2023-03-07 00:17 UTC, AJCM-git requested changes
just some details (formatting and nesting in SharedCuffableSystem.cs look a lil uggo sometimes tho but its fine)

2023-03-07 00:17 UTC, AJCM-git commented on Content.Shared/Cuffs/SharedCuffableSystem.cs
> +                // TODO these pop-ups need third-person variants (i.e. {$user} is cuffing {$target}!
do this

2023-03-07 00:17 UTC, AJCM-git commented on Content.Shared/Cuffs/SharedCuffableSystem.cs
> +            // TODO these messages really need third-party variants. I.e., "{$user} starts cuffing {$target}!"
same

2023-03-13 01:07 UTC, AJCM-git commented
merge master

2023-03-13 20:41 UTC, AJCM-git commented
linter error

2023-03-13 23:34 UTC, AJCM-git approved these changes

2023-03-13 23:34 UTC, merged