Add telecommunication server
space-wizards/space-station-14 pull request #14415
Opened 2023-03-05 11:17 UTC by Slava0135

## About the PR

**Media**

![Peek 2023-03-05 14-13](https://user-images.githubusercontent.com/40753025/222957158-313e0685-ebd7-423d-93ac-1c9cf5039c3f.gif)

**Changelog**

:cl:
- add: added telecommunication server. You can put encryption keys there. In the future will be necessary to transmit radio messages.

2023-03-05 11:27 UTC, Just-a-Unity-Dev commented
Please implement the structure before the system so that mappers have time to map the server rather than players yelling "WAAA NO RADIO MAPPER SUCKS" in #general

2023-03-05 11:32 UTC, Slava0135 commented
> Please implement the structure before the system so that mappers have time to map the server rather than players yelling "WAAA NO RADIO MAPPER SUCKS" in #general

yes, it's only a structure (plus board, construction and research). System will be introduced later.

2023-03-05 11:36 UTC, Slava0135 commented
don't know why it can't find the prototype, also it doesn't show up in circuit imprinter

2023-03-05 11:46 UTC, Just-a-Unity-Dev commented
oh fuck my blindass thought you implemented the system already lmao mb

2023-03-05 12:07 UTC, brainfood1183 commented
How many of these will need to be mapped is it just one?

2023-03-05 12:10 UTC, Slava0135 commented
> How many of these will need to be mapped is it just one?

Up to you, 1 server with only command key is enough but you can also put them in each department with related keys (though there is no key for command channel only, need to add?)

2023-03-05 12:39 UTC, brainfood1183 commented
> ?

I was asking becausew i have a telecoms room on my map but i guess i cannot directly replace the old servers with these new ones since they wont actually be active on first release. I guess i will place them in their departments and can later move them to the telecoms room once the system is implemented.

2023-03-05 12:42 UTC, QuietlyWhisper commented
> > ?
> 
> I was asking becausew i have a telecoms room on my map but i guess i cannot directly replace the old servers with these new ones since they wont actually be active on first release. I guess i will place them in their departments and can later move them to the telecoms room once the system is implemented.

It's a single server that handles all communications, although you can choose to have several servers with different access instead!

2023-03-05 13:01 UTC, Slava0135 commented
hm, test is failing saying: `Prototype TelecomServer modifies component on spawn: ContainerContainer. Modified fields: containers`, need help

2023-03-05 13:04 UTC, Just-a-Unity-Dev commented
your `containers` field is being modified to contain a container

2023-03-05 13:06 UTC, QuietlyWhisper commented
I'll also drop the doc in here so anyone seeing this gets an idea of what's going on...
[https://docs.google.com/document/d/1CyinGKcQF9sDS9t7_C00z_a2LhGlvedN9tXe8J1lRDo/edit](url)

2023-03-05 14:08 UTC, AJCM-git requested changes

2023-03-05 14:08 UTC, AJCM-git commented on Resources/Prototypes/Entities/Structures/Machines/telecomms.yml
> +      key_slots: !type:Container
![image](https://user-images.githubusercontent.com/60196617/222965140-75ac798a-0d2d-48cc-9be5-7ef47c9eda34.png)
test fails cuz of overwritten containers

2023-03-05 14:08 UTC, AJCM-git commented on Resources/Textures/Structures/Machines/telecomms.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/a7df6036f04f386ac660bcc84c332a0b2ff5ed1a",
i wont require you to but it would be helpful to link the dmi file you took this from at that commit instead

2023-03-05 16:25 UTC, deltanedas commented
nukies hitting telecomms new meta

2023-03-05 16:27 UTC, Slava0135 commented
> nukies hitting telecomms new meta

Telecom server also should be mapped on nukie ship, or how else syndicate channel will work?

2023-03-05 16:36 UTC, deltanedas commented
if there are no nukies, how will it work

2023-03-05 16:40 UTC, Slava0135 commented
> if there are no nukies, how will it work

Syndies breaking into comms and inserting key (or just steal the server lol), or building your own (as it's cheap), maybe add miniserver with invisibility and single key slot, that you can install somewhere distant.

2023-03-05 17:05 UTC, deltanedas commented
massive amount of effort when:
- currently nobody uses traitor key since it only has 1 channel
- that would mean someone has to buy 2
- breaking into telecomms makes you instantly valid

2023-03-05 19:19 UTC, QuietlyWhisper commented
@deltanedas @Slava0135 Centcom and Syndicate channels are unaffected by radio server; see doc

2023-03-06 06:58 UTC, Slava0135 commented
i will put encryption key changes to separate PR

2023-03-06 21:11 UTC, AJCM-git approved these changes
Holy shit BaseMachinePowered inheritors need to share more components, the boilerplate is insane

2023-03-06 21:11 UTC, merged