Fix slime hair translucent
space-wizards/space-station-14 pull request #14478
Opened 2023-03-07 08:52 UTC by CaptainSqrBeard

## About the PR

fixes #14430

Slime hair is now translucent as it was before
(slime mains don't kill me)

**Media**
![cultist_slime](https://user-images.githubusercontent.com/56765288/223371365-93cecbc1-5c8e-464c-a599-5326d30ecadf.png)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- fix: Fixed slime hair was not translucent

2023-03-07 09:05 UTC, Just-a-Unity-Dev commented
based

2023-03-11 03:57 UTC, vulppine requested changes

2023-03-11 03:57 UTC, vulppine commented on Content.Shared/Humanoid/Markings/MarkingManager.cs
> +        public bool MustMatchSkin(out float alpha, string species, HumanoidVisualLayers layer, IPrototypeManager? prototypeManager = null)
put the out var before the prototype manager parameter here

2023-03-11 17:17 UTC, CaptainSqrBeard commented
fixed

2023-03-11 21:02 UTC, vulppine approved these changes

2023-03-11 21:04 UTC, merged