Blind (permanent, temporary or blindfolded) players no longer get flashed
space-wizards/space-station-14 pull request #14487
Opened 2023-03-07 16:01 UTC by Naive817

## About the PR

As the title shows, blind people no longer get flashed.
IDK whether my way of doing it is stupid, please review.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://user-images.githubusercontent.com/31364560/223477518-3ee241d6-16fd-492e-a753-c8330ade23f4.mp4

**Changelog**

:cl: furontier
- tweak: Flashes can no longer affect blind (permanent, temporary or blindfolded) players.

2023-03-11 06:24 UTC, metalgearsloth requested changes

2023-03-11 06:24 UTC, metalgearsloth commented on Content.Server/Flash/FlashSystem.cs
> +                args.Cancel();
Shouldn't need to check Running.

2023-03-11 06:24 UTC, metalgearsloth commented on Content.Server/Flash/FlashSystem.cs
> +                args.Cancel();
Same here.

2023-03-12 00:39 UTC, Naive817 commented on Content.Server/Flash/FlashSystem.cs
> +                args.Cancel();
yes it's not necessary, removed this

2023-03-13 04:03 UTC, merged