make balance of hunger rate
space-wizards/space-station-14 pull request #14595
Opened 2023-03-11 18:48 UTC by pofitlo

Change baseDecayRate from 0.5 to 0.25 (mouse will starve twice as long)
reason: too hight hunger rate make useless to eat food

## About the PR

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:

- tweak: Changed Decay rate!

2023-03-12 02:04 UTC, deltanedas commented
I would have changelog be `Mice take twice as long to starve.` since it didnt mention mice or what decaying was

2023-03-12 23:39 UTC, mirrorcult commented
mice are supposed to have to eat often. makes more sense to reduce their total hunger so they have to eat less food to be satiated, if thats not already how it is

2023-03-12 23:39 UTC, mirrorcult requested changes
^

2023-03-14 09:51 UTC, deltanedas commented
\>be mouse
\>spawn in starving
\>pull up to kitchen, inhale 50 times my body mass in 3 seconds
\>full belly so good!
\>1 min later
\>hungy

2023-03-14 22:04 UTC, AJCM-git commented
linter fail

2023-03-23 16:48 UTC, AJCM-git commented
@pofitlo You coming back to this?

2023-04-01 08:07 UTC, pofitlo commented
@AJCM-git i dont think so. *sigh*

2023-04-01 08:07 UTC, closed without merging