More DoAfter Changes
space-wizards/space-station-14 pull request #14609
Opened 2023-03-12 17:54 UTC by ElectroJr

## About the PR
This PR started off as just changes required to network DoAfter events so that they could be properly predicted but it has since ballooned somewhat into its own refacto. This includes a few of the changes listed in #14403.

## Changes:

### Networking & map saving related
- DoAfters should now properly support saving to yaml.
- The optional `Func<bool>` checks have been obsoleted and replaced with a serializable attempt-events.
- The Cancellation tokens / sources have largely been removed. DoAfters should be cancelled via `DoAfterSystem.Cancel()`.
- `DoAfterEvent<MyData>` has been replaced with inheritance (`MyDoAfterEvent : DoAfterEvent`). Required to make the events net & yaml serializable
- DoAfterEvents must now be specified in shared code. This restricts DoAfters a bit when working with server-side systems, but it greatly simplifies the networking logic.
- DoAfterEvents now need to implement a `Clone()` method.
  - Required for Client-side prediction, but it adds a bunch of boilerplate and I hate it.
  - Alternative would be to just trust that all DoAfterEvent's are immutable, but that will inevitably lead to bugs getting past reviews, leading to difficult to diagnose networking / prediction bugs.
  - If theres some other way like via fancy analyzer, send help.

### DoAfterArgs
- `DoAfterEventArgs` has been renamed to `DoAfterArgs`. They are the arguments/options that specify how the DoAfter behaves and aren't really related to the event that will get raised when the DoAfter has finished.
- I thought about combining them with the `DoAfter` itself, as mentioned in #14403. and TODO comments, but decided against it.
- The `BreakOnStun` option has been generalized to `RequireCanInteract` and now defaults to true
  - If there are specific DoAfters that should still be performable while stunned but now while otherwise incapacitated I guess this can be re-added?
- The various `RaiseOnX` bools have been replaced with a single `EntityUid EventTarget` option.

### Duplicate Blocking & Cancellation
DoAfterArgs now has options to support automatic blocking and cancellation of duplicates (fixes #6124).
- Reduced boilerplate and prevents the various bugs relating to DoAfters becoming blocked/unusable.
- The `BlockDuplicate` option prevents a duplicate DoAfter from being created. This defaults to true.
- The `CancelDuplicate` option will cancel any duplicates when trying to add a new DoAfter. This defaults to true.
- The `DuplicateCondition` flags can be used to configure what DoAfters are considered duplicates. 
  - Default behaviour is that they are duplicates if they have the same target, tool, and raise the same type of DoAfterEvent.
  - A DoAfter being performed by another player will never be considered a duplicate.
  - E.g., it is now trivial to make it so that force feeding someone a burger is mutually exclusive with trying to place it in their hands.

### Misc

DoAfterEvent is now abstract, and each system/doafter should have its own event. This fixes various bugs where systems would attempt to handle DoAfters that were started by other systems.

DoAfter related Constriction & Tool code has also changed quite a bit to simply them. Just like DoAfters, they no longer have separate success & fail events.

## TODO
- [ ] Move more `DoAfterEvent`s to shared code. Currently server-side events will just error
- [ ] Pausing
- [ ] Test map saving.
- [ ] Test (mis)p)redicted DoAfters
- [ ] Test DoAfters.
  - I've only tested eating & stripping. It is very likely that various DoAFterArgs bugs got in, especially while converting the `RaiseOnX` bools to the event target uids.)
- [ ] #14606 
- [ ] #14607 
- [ ] #14576 
- [ ] #14530 
- [ ] #14427 
- [ ] #14368
- [ ] Add Changelog

2023-03-16 23:12 UTC, ElectroJr commented on Content.Shared/DoAfter/Events.cs
> +// Really these should all go into their respective shared namespaces whenever those systems get properly predicted.
I'll probably fix this before marking the draft as ready, but its just such tedious work.

2023-04-02 06:10 UTC, keronshb requested changes
Only one issue so far, otherwise this is good to go.

2023-04-02 06:10 UTC, keronshb commented on Content.Server/Mech/Systems/MechSystem.cs
> +    private void OnRemoveBattery(EntityUid uid, MechComponent component, RemoveBatteryEvent args)
If you try removing a battery with a crowbar it just deletes the battery.

2023-04-03 01:13 UTC, keronshb approved these changes

2023-04-03 01:13 UTC, merged