Lone Ops
space-wizards/space-station-14 pull request #14647
Opened 2023-03-14 04:03 UTC by Scribbles0

## About the PR

draft pr because it isn't finished yet (might need #14025 or more work on nuke code paper stuff, currently does not give nuke code to lone operatives)

Adds a station event that spawns a lone nuclear operative sent to destroy the station. May only appear after 55 minutes have passed. Can appear on any gamemode.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Demonstration of loneop spawning, what happens if the loneop dies, and what happens if the nuke is detonated.

https://user-images.githubusercontent.com/91828755/224890084-67b8fce5-e6f3-4d04-974e-56235b7bf306.mp4

**Changelog**

:cl:
- add: Lone nuclear operatives have recently started attacking stations. Make sure to watch out for them on long and extended shifts.

2023-03-14 08:23 UTC, deltanedas requested changes

2023-03-14 08:23 UTC, deltanedas commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        if (_nukeopsRuleConfig.SpawnOutpost == false)
use `!_nukeopsRuleConfig.SpawnOutpost`

2023-03-14 16:44 UTC, Cheackraze commented
A shuttle gives them a peaceful place where they can prepare and buy things and hide the stuff like bags and toolboxes, and also allows them to have some odds and ends mapped for them, like how regular nukies get on their shuttle/base.  It let's them actually plan.  If they just randomly spawn on the station in a blood red it is much more difficult to actually find a hiding place to purchase your gear and plan without being discovered, and the shuttle has IFF console and turrets to prevent the crew from finding or using it.  It is much better executed with a shuttle than without.

2023-03-14 16:52 UTC, EmoGarbage404 requested changes

2023-03-14 16:52 UTC, EmoGarbage404 commented on Content.Server/StationEvents/Events/LoneOpsSpawn.cs
> +            return;
```
if (!_prototypeManager.TryIndex<GameRulePrototype>("Nukeops", out var ruleProto)
    return;
```
Also the nukeops string should be a const variable on the system (gamerule refactor when i get off my ass).

2023-03-14 16:52 UTC, EmoGarbage404 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +    public void OnLoneOpsSpawn()
Name this something else, because this name implies its an event handler, which it isn't.

2023-03-14 16:53 UTC, EmoGarbage404 commented
Having a shuttle feels pretty essential.

This is kinda an annoying scope thing, so feel free to ignore, but maybe only make the shuttle spawn once someone has spawned in as the lone op?

2023-03-14 16:59 UTC, Cheackraze commented
> Having a shuttle feels pretty essential.
> 
> This is kinda an annoying scope thing, so feel free to ignore, but maybe only make the shuttle spawn once someone has spawned in as the lone op?

Not sure how that would work exactly unless you want them to spawn onto like, the nukie planet.  Ghost role spawner has to be on a grid somewhere, and you'd hope the shuttle or whatever is initialized and has air beforehand lol

2023-03-14 17:00 UTC, EmoGarbage404 commented
Like i said, pointless ideaguys-ing.

On a more relevant note, the pr looks good.

2023-03-14 21:37 UTC, Emisse commented
looks good but id like a test merge when its ready so we can test on live for bugs

2023-04-09 17:37 UTC, Scribbles0 commented
@moonheart08 can you review please (if/when you have time)?
anyone else who'd like to is also welcome to add feedback

2023-04-09 21:56 UTC, Emisse commented
cant speak for the code but ill test this locally when im home and see if i can suss out any bugs

2023-04-17 06:00 UTC, merged

2023-04-17 06:32 UTC, DogZeroX commented
This is not marked as antag in admin panel