adds mech drill
space-wizards/space-station-14 pull request #14646
Opened 2023-03-14 03:23 UTC by Naive817

## About the PR

Adds mech drill that can be installed on ripley to mine rocks
It cant be used on other things or as a melee weapon as for now

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added mech drill

2023-03-14 04:10 UTC, EmoGarbage404 commented
needs a screenshot/video of it being tested

2023-03-14 04:45 UTC, Naive817 commented
> needs a screenshot/video of it being tested

video is added, went lazy when I made the PR

2023-03-25 23:07 UTC, mirrorcult requested changes
the interaction with `GatheringTool` here seems really weird? technically two doafters would try to happen at once since mech drill tries to start its own, when really all you need with this interaction is something like:

- before gathering doafters, raise an event to see if it should go through--mechdrill handles it and cancels if not enough energy or etc mech related checks. if it should go through it starts playing the audio
- after doafter (which gets raised by gatherable), do all the usual logic you already have there

2023-03-25 23:07 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Specific/Mech/mecha_equipment.yml
> +  name: Mecha drill
```suggestion
  name: mecha drill
```

2023-03-25 23:07 UTC, mirrorcult commented on Content.Server/Mech/Equipment/Components/MechDrillComponent.cs
> +}
```suggestion
[RegisterComponent]
public sealed class MechDrillComponent : Component
{
    /// <summary>
    /// The change in energy after each drill.
    /// </summary>
    [DataField("drillEnergyDelta")]
    public float DrillEnergyDelta = -30;

    /// <summary>
    /// How long does it take to drill something?
    /// </summary>
    [DataField("drillDelay")]
    public float DrillDelay = 0.25f;

    /// <summary>
    /// The sound played when a mech is drilling something
    /// </summary>
    [DataField("drillSound")]
    public SoundSpecifier DrillSound = new SoundPathSpecifier("/Audio/Mecha/sound_mecha_hydraulic.ogg");

    public IPlayingAudioStream? AudioStream;
}
```

conventions

2023-03-25 23:07 UTC, mirrorcult commented on Content.Server/Mech/Equipment/EntitySystems/MechDrillSystem.cs
> +    private void OnMechdrill(EntityUid uid, MechDrillComponent component, DoAfterEvent args)
```suggestion
    private void OnMechDrill(EntityUid uid, MechDrillComponent component, DoAfterEvent args)
```

2023-03-25 23:07 UTC, mirrorcult commented on Content.Server/Mech/Equipment/EntitySystems/MechDrillSystem.cs
> +            BreakOnUserMove = true
set `RaiseOnTarget` and `RaiseOnUser` = false in the doafter args

2023-03-25 23:07 UTC, mirrorcult commented on Content.Server/Mech/Equipment/EntitySystems/MechDrillSystem.cs
> +        component.AudioStream = _audio.PlayPvs(component.drillSound, uid);
sound could stand to be a little quieter imo, judging from the video

2023-03-27 12:27 UTC, Naive817 commented
> the interaction with `GatheringTool` here seems really weird? technically two doafters would try to happen at once since mech drill tries to start its own, when really all you need with this interaction is something like:
> 
> * before gathering doafters, raise an event to see if it should go through--mechdrill handles it and cancels if not enough energy or etc mech related checks. if it should go through it starts playing the audio
> * after doafter (which gets raised by gatherable), do all the usual logic you already have there

`GatherableSystem` subscribed to `InteractUsingEvent`, which is raised when a target entity is interacted with by a user while holding an object in their hand.
mech systems used `InteractNoHandEvent`, which is cursed according to remarks

2023-03-27 12:27 UTC, Naive817 commented
> the interaction with `GatheringTool` here seems really weird? technically two doafters would try to happen at once since mech drill tries to start its own, when really all you need with this interaction is something like:
> 
> * before gathering doafters, raise an event to see if it should go through--mechdrill handles it and cancels if not enough energy or etc mech related checks. if it should go through it starts playing the audio
> * after doafter (which gets raised by gatherable), do all the usual logic you already have there

`GatherableSystem` subscribed to `InteractUsingEvent`, which is raised when a target entity is interacted with by a user while holding an object in their hand.
mech systems used `InteractNoHandEvent`, which is cursed according to remarks

2023-03-27 12:27 UTC, Naive817 commented
> the interaction with `GatheringTool` here seems really weird? technically two doafters would try to happen at once since mech drill tries to start its own, when really all you need with this interaction is something like:
> 
> * before gathering doafters, raise an event to see if it should go through--mechdrill handles it and cancels if not enough energy or etc mech related checks. if it should go through it starts playing the audio
> * after doafter (which gets raised by gatherable), do all the usual logic you already have there

`GatherableSystem` subscribed to `InteractUsingEvent`, which is raised when a target entity is interacted with by a user while holding an object in their hand.
mech systems used `InteractNoHandEvent`, which is cursed according to remarks

2023-04-29 06:44 UTC, metalgearsloth requested changes
I'm skeptical of making mech copies of code just for basic interactions, especially when it's not being predicted.

Is there any strong reason why this isn't just using gatherable?

2023-04-29 06:44 UTC, metalgearsloth commented on Content.Server/Mech/Equipment/Components/MechDrillComponent.cs
> +/// </summary>
Looks like you copied this from mechgrabber.

2023-04-29 06:45 UTC, metalgearsloth commented on Content.Server/Mech/Equipment/Components/MechDrillComponent.cs
> +    public IPlayingAudioStream? AudioStream;
Delay needs to be 1 minimum, 0.25 means the do_after doesn't even show.

2023-05-06 04:18 UTC, metalgearsloth commented
@Naive817 Are you coming back to this.

2023-05-08 16:18 UTC, PilgrimViis commented
> @Naive817 Are you coming back to this.

I did the same feature for an unofficial server. If you want guys, I could pick up this task and create a new PR in this repo. You can check out a video of how I've implemented it here. https://github.com/Workbench-Team/space-station-14/pull/161/files

2023-05-12 16:13 UTC, AJCM-git commented
> > @Naive817 Are you coming back to this.
> 
> I did the same feature for an unofficial server. If you want guys, I could pick up this task and create a new PR in this repo. You can check out a video of how I've implemented it here. [Workbench-Team/space-station-14#161 (files)](https://github.com/Workbench-Team/space-station-14/pull/161/files)

Push your changes to this PR and we will review that if you want to contribute this feature, opening a new one for changes is not advised (worst case you can force pusH)

2023-05-14 01:27 UTC, AJCM-git commented
> > @Naive817 Are you coming back to this.
> 
> I did the same feature for an unofficial server. If you want guys, I could pick up this task and create a new PR in this repo. You can check out a video of how I've implemented it here. [Workbench-Team/space-station-14#161 (files)](https://github.com/Workbench-Team/space-station-14/pull/161/files)

Yeah, you can take it (unless @Naive817 says otherwise

2023-05-15 04:16 UTC, closed without merging