Adding purple berets for R&D
space-wizards/space-station-14 pull request #14702
Opened 2023-03-16 07:48 UTC by lzk228

:cl:
- add: purple berets!
- ![Screenshot_20230316_094543](https://user-images.githubusercontent.com/124214523/225549061-b23fa3e1-b46b-44a4-a854-1c0ff66e945b.png)
![Screenshot_20230316_094557](https://user-images.githubusercontent.com/124214523/225549067-28abc142-620f-4a78-a05d-52f7f2e0ab62.png)
![Screenshot_20230316_094606](https://user-images.githubusercontent.com/124214523/225549069-3b125e5b-81b1-4e93-ba25-7c1e83bb0b30.png)

2023-03-16 14:51 UTC, DogZeroX commented
Make sure the add: says "add: Added purple berets for science!" or something like that.

2023-03-16 18:59 UTC, Flareguy commented
Why is the beret a different color from the regular science purple?

2023-03-19 23:42 UTC, potato1234x commented
imo this would be better in rd's locker

2023-03-19 23:52 UTC, deltanedas commented
yeah to go in line with ce/cmo/hos/warden(?) berets

2023-03-23 17:42 UTC, AJCM-git requested changes

2023-03-23 17:42 UTC, AJCM-git commented on Resources/Textures/Clothing/Head/Hats/beret_rnd.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e",
you need to specify whatever changes you made to the sprite here

2023-04-01 00:35 UTC, lzk228 commented
I'd rather make a new PR

2023-04-01 00:35 UTC, closed without merging