Cryo pods crutchy fix
space-wizards/space-station-14 pull request #14745
Opened 2023-03-20 01:06 UTC by BELNAKBU

## About the PR

Just a little bit crutchy fix of cryo pods make them work somehow

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Cryo pods now works. somehow

2023-03-23 01:33 UTC, vulppine requested changes
the changelog is too vague, please change it to something that actually references what you add/fix in this PR

2023-03-23 01:33 UTC, vulppine commented on Content.Server/Medical/CryoPodSystem.cs
> +                    return;
unneeded

2023-03-23 01:33 UTC, vulppine commented on Content.Shared/Medical/Cryogenics/SharedCryoPodSystem.cs
> +    protected void AddInsertOtherVerb(EntityUid uid, SharedCryoPodComponent cryoPodComponent, GetVerbsEvent<InteractionVerb> args)
while this technically works, this doesn't match the 'drag-drop' interaction pattern that SS14 (especially other medical entities) have - i'd say that this should be changed to match that, instead

2023-03-23 01:33 UTC, vulppine commented on Content.Shared/Medical/Cryogenics/SharedCryoPodSystem.cs
> +            AlternativeVerb verb = new();
do `var` as the type, and add the type in the constructor/`new()` statement instead

2023-03-23 01:33 UTC, vulppine commented on Content.Shared/Medical/Cryogenics/SharedCryoPodSystem.cs
> +    public bool IsOccupied(SharedCryoPodComponent scannerComponent)
does this have to be public?

2023-03-23 01:33 UTC, vulppine commented on Content.Shared/Medical/Cryogenics/SharedCryoPodSystem.cs
> +    public bool CanCryoPodInsert(EntityUid uid, EntityUid target, SharedCryoPodComponent? component = null)
does this have to be public?

2023-03-23 02:52 UTC, vulppine commented on Content.Server/Medical/CryoPodSystem.cs
> +                    return;
(by this, i meant the return statement)

2023-04-19 10:08 UTC, metalgearsloth commented
Re-open if you come back to it.

2023-04-19 10:08 UTC, closed without merging