JobInfo and HealthBar for security and medical huds, like SS13
space-wizards/space-station-14 pull request #14751
Opened 2023-03-20 13:02 UTC by DocNITE

## About the PR
   Added huds for security and medical glasses huds. (and security sunglasses too)
 At can be show: Job icon from character. Health bar and his status.
(There is exists some parts from SimpleStation and Nyanotrasen, what i rework for myself)

**Media**
![image](https://user-images.githubusercontent.com/69177241/226346420-beba10e1-0e63-4b21-b52e-c3d977986d7d.png)
![image](https://user-images.githubusercontent.com/69177241/226346468-10e681d5-02c1-4685-b892-6d58cc80bb03.png)
![image](https://user-images.githubusercontent.com/69177241/226346546-401f483e-3ea7-4d7a-b2e8-74ff946ea90d.png)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added show job icon feature for secruity hud and security sunglasses
- add: Added health bar and status for medical hud.

2023-03-20 13:11 UTC, metalgearsloth commented
1. This pr needs splitting
2. If you're porting their code are you willing to make the necessary review changes.
3. Job status should be a generic system and not hardcoded. Same with health.

2023-03-20 18:31 UTC, Elijahrane commented
The reason I didn't upstream them is due to https://github.com/space-wizards/space-station-14/issues/13738

Although the health bar overlay in isolation in better than the ancient one that exists up here imo, even if it's only ported for admin use

2023-03-21 05:04 UTC, DocNITE commented
> The reason I didn't upstream medical huds is due to #13738
> 
> SecHuds are from a different codebase so no comment on those
> 
> Although the health bar overlay in isolation in better than the ancient one that exists up here imo, even if it's only ported for admin use. I don't know where the status additions come from; did you write those?

You mean SecHud or something? It's from two overlays - ShowJobInfo and ShomHealthBar. So, ClothingGrantingSystem can run 8 components in currently time. I make that screenshot from another server, where my huds is used. It's a `advanced hud`, what grants two components. So, advanced hud can show two overlays

2023-03-21 06:05 UTC, randy10122 commented
gahhhhh someone figured it out before i did. my life is over

2023-03-21 06:07 UTC, DocNITE commented
> gahhhhh someone figured it out before i did. my life is over

nono, wait. You can show me youre code :D But i need contact with you

2023-03-21 10:33 UTC, randy10122 commented
ohalso minor adjustment id make is medhuds not showing job status - just for a game balance thing mostly

2023-03-22 04:10 UTC, potato1234x commented
finally, no more med scanner spam

2023-03-25 03:05 UTC, vulppine requested changes

2023-03-25 03:05 UTC, vulppine commented on Content.Shared/Clothing/EntitySystems/ClothingGrantingSystem.cs
> +// from SimpleStation 14
license? i think adding that codebase's license up here would make sense since this was directly copied over

2023-04-09 21:05 UTC, SonicHDC commented
I don't think it's necessary to add a position display for the sunglasses. This is illogical and deprives the visor of its uniqueness. And also the bartender has the same glasses.

2023-04-11 00:11 UTC, metalgearsloth requested changes

2023-04-11 00:11 UTC, metalgearsloth commented on Content.Client/EntityJobInfo/EntityJobInfoOverlay.cs
> +    public EntityJobInfoOverlay(IEntityManager entManager, IPrototypeManager protoManager, InventorySystem inventorySystem)
This is still hardcoded for jobs when it should be generic for status indicators and in a separate PR.

2023-04-11 00:12 UTC, metalgearsloth commented
@DocNITE are you coming back to this

2023-04-12 01:07 UTC, closed without merging