Material Reclaimer
space-wizards/space-station-14 pull request #14969
Opened 2023-03-30 00:11 UTC by EmoGarbage404

## About the PR

Adds the material reclaimer: a machine capable of converting the junk you have lying around into raw materials.
Simply insert the stuff, give it a second to chug, and watch materials and chemicals pop out.

chemicals can acquired by clicking on the reclaimer with a container of some kind (akin to a fuel tank)

TODO
- [ ] tests for the hellscape that is PhysicalCompositionComponent

- [ ] giving like 75% of entities some kind of composition.

**Media**

soon:tm:
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the material reclaimer. Insert junk you don't want to grind it up into its raw material form.

2023-03-30 00:30 UTC, Elijahrane commented
isn't this what the recycler is supposed to do

2023-03-30 18:01 UTC, EmoGarbage404 commented
> isn't this what the recycler is supposed to do

I imagine the material reclaimer as a low-throughput system that has a high return yield.
The recycler can be quicker, but have a more limited yield in return.

I don't plan on making the changes to the recycler in this pr, but I've modified this system to allow for it to be adapted for the recycler (as i envisioned it) in the future.

2023-03-30 20:17 UTC, EmoGarbage404 commented
Also, open letter to all, does this need a guide entry? If so, what general category should it be listed under?

2023-03-30 20:43 UTC, deltanedas commented
i think its fairly self explanatory, may as well make a protolathe guide at that point (dont)

2023-03-30 20:44 UTC, EmoGarbage404 commented
> i think its fairly self explanatory, may as well make a protolathe guide at that point (dont)

funnily enough, the protolathe has a small guide in the science section.

2023-03-31 00:36 UTC, EmoGarbage404 commented
Ready for review

2023-03-31 05:53 UTC, mirrorcult commented
i think im still kind of confused on why this and the recycler are separate systems, i think that will end up being confusing

2023-03-31 12:00 UTC, EmoGarbage404 commented
> i think im still kind of confused on why this and the recycler are separate systems, i think that will end up being confusing

I felt that it was important to give players options. In situations where material balance is important and you need to scavenge, you may feel incentivized to carefully shift through trash to find items that give a decent return. Otherwise, if you simply need to destroy trash, you can simply funnel it through a recycler to get rid of it quicker for a much smaller return (or at least that's my intent).

I do plan on merging the two systems; i just wanted to split up the pr since it got big fairly quickly.

I think giving players the option off efficiency vs. returns is enough to justify two similar machines. This one also collects chemicals from reclaimed objects, which can be easily collected.

2023-04-04 22:19 UTC, EmoGarbage404 commented
Converted recycling to use the same system as the reclaimer. 
Hopefully the relationship between the two machines is more clear now.

2023-04-09 23:55 UTC, moonheart08 requested changes

2023-04-09 23:55 UTC, moonheart08 commented on Content.Client/Materials/MaterialReclaimerSystem.cs
> +public sealed class MaterialReclaimerSystem : SharedMaterialReclaimerSystem
```suggestion
/// <inheritdoc/>
public sealed class MaterialReclaimerSystem : SharedMaterialReclaimerSystem
```

2023-04-09 23:55 UTC, moonheart08 commented on Content.Server/Materials/MaterialReclaimerSystem.cs
> +public sealed class MaterialReclaimerSystem : SharedMaterialReclaimerSystem
```suggestion
/// <inheritdoc/>
public sealed class MaterialReclaimerSystem : SharedMaterialReclaimerSystem
```

2023-04-09 23:55 UTC, moonheart08 commented on Content.Server/Materials/MaterialReclaimerSystem.cs
> +    public override bool TryFinishProcessItem(EntityUid uid, MaterialReclaimerComponent? component = null, ActiveMaterialReclaimerComponent? active = null)
```suggestion
    /// <inheritdoc/>
    public override bool TryFinishProcessItem(EntityUid uid, MaterialReclaimerComponent? component = null, ActiveMaterialReclaimerComponent? active = null)
```

2023-04-09 23:55 UTC, moonheart08 commented on Content.Server/Materials/MaterialReclaimerSystem.cs
> +    public override void Reclaim(EntityUid uid,
```suggestion
    /// <inheritdoc/>
    public override void Reclaim(EntityUid uid,
```

2023-04-09 23:55 UTC, moonheart08 commented on Content.Shared/Materials/ActiveMaterialReclaimerComponent.cs
> +public sealed class ActiveMaterialReclaimerComponent : Component
where doc comments

2023-04-09 23:55 UTC, moonheart08 commented on Content.Shared/Materials/MaterialReclaimerComponent.cs
> +public sealed class MaterialReclaimerComponent : Component
so this does what? (doc comments)

2023-04-09 23:55 UTC, moonheart08 commented on Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
> +public abstract class SharedMaterialReclaimerSystem : EntitySystem
doc comments

2023-04-09 23:55 UTC, moonheart08 commented on Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
> +    public bool TryStartProcessItem(EntityUid uid, EntityUid item, MaterialReclaimerComponent? component = null, EntityUid? user = null)
dock comment

2023-04-09 23:55 UTC, moonheart08 commented on Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
> +    public virtual bool TryFinishProcessItem(EntityUid uid, MaterialReclaimerComponent? component = null, ActiveMaterialReclaimerComponent? active = null)
dooc commemntwert

2023-04-09 23:55 UTC, moonheart08 commented on Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
> +    public virtual void Reclaim(EntityUid uid,
doc comment

2023-04-09 23:55 UTC, moonheart08 commented on Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
> +    public void SetReclaimerEnabled(EntityUid uid, bool enabled, MaterialReclaimerComponent? component = null)
d o c comment

2023-04-09 23:55 UTC, moonheart08 commented on Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
> +    public bool CanStart(EntityUid uid, MaterialReclaimerComponent component)
a smidge of doc comment

2023-04-09 23:55 UTC, moonheart08 commented on Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
> +    public bool CanGib(EntityUid uid, EntityUid victim, MaterialReclaimerComponent component)
dock comment

2023-04-09 23:55 UTC, moonheart08 commented on Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
> +    public override void Update(float frameTime)
```suggestion
    /// <inheritdoc/>
    public override void Update(float frameTime)
```

2023-04-10 04:37 UTC, moonheart08 approved these changes

2023-04-10 04:38 UTC, merged