Chemical Wiki Descriptions, Recipe Tweaks & Effect Tweaks
space-wizards/space-station-14 pull request #15016
Opened 2023-03-31 14:15 UTC by Alekshhh

## About the PR
o Changes almost all wordings in the chemical wiki section to have up-to-date, consistent and relevant information.
o Tweaked chemical recipes, namely:
- All plasma catalysts were reduced from 5u to 1u
- Epinephrine no longer requires diethylamine anymore, creates 5u epinephrine
- Dexalin requires 2u hydrogen,1u oxygen, 1u plasma catalyst, creates 3u dexalin
- Lexorin requires 1u heartbreaker toxin, 1u fluorine, 1u plasma, creates 3u lexorin
- Ultravasculine requires 1u dylovene, 1u sodium, 1u plasma catalyst
- Sigynate requires 1u iodine, 1u kelotane, 1u sugar, creates 3u sigynate
- Phenol requires 1u oxygen, 1u hydrogen, 1u carbon
- Diphenymethylamine requires 1u ethyloxyephedrine, 1u phenol, 1u sodium carbonate, makes 3u diphenylmethylamine
- Ammonia reaction creates 3u instead of 4u
- Sodium carbonate no longer requires ammonia, creates 3u sodium carbonate

o  Tweaked chemical effects, namely:
- Bicaridine no longer causes drunkness
- Dermaline no longer causes drunkness on slight overdose
- Nocturine no longer causes poison damage on overdose (60u to deal 2 poison per second are you real)
- Sigynate cures 2 caustic a second instead of 6

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: The chemical page of the wiki has been heavily reworded, and a few chemicals had their recipes tweaked and effects changed a little

2023-03-31 15:48 UTC, Interrobang01 commented
Great PR. This has been needed for a while now, thank you. I don't have anything negative to comment on, everything here is good.

...fantastic licoxide description btw

2023-03-31 16:07 UTC, Alekshhh commented
if anyone has suggestions for desc recipes or effects lemme know since I already have it open

2023-04-14 11:20 UTC, deltanedas requested changes

2023-04-14 11:20 UTC, deltanedas commented on Resources/Locale/en-US/reagents/meta/medicine.ftl
> +reagent-desc-dexalin-plus = Used in treatment of extreme cases of oxygen deprivation and bloodloss. Flushes lexorin out the blood stream.
out of

2023-04-14 11:20 UTC, deltanedas commented on Resources/Locale/en-US/reagents/meta/medicine.ftl
> +reagent-desc-dylovene = A broad spectrum anti-toxin, which treats toxin damage in the blood stream. Overdosing will cause vomiting, dizzyness and pain.
broad-spectrum was correct

2023-04-14 11:20 UTC, deltanedas commented on Resources/Locale/en-US/reagents/meta/medicine.ftl
> +reagent-desc-epinephrine = An effective stabilizing chemical used to keep a critical person from dieing to asphyxiation while patching up minor damage during crit. Flushes lexorin out the blood strea
dying

2023-04-14 11:20 UTC, deltanedas commented on Resources/Locale/en-US/reagents/meta/medicine.ftl
> +reagent-desc-inaprovaline = Inaprovaline is a synaptic stimulant and cardiostimulant, commonly used to treat asphyxiation damage caused during critical states and reduce bleeding. Used in many advanc
medicines

2023-04-14 11:20 UTC, deltanedas commented on Resources/Locale/en-US/reagents/meta/medicine.ftl
> +reagent-desc-leporazine = A chemical used to stabilize body temperature and rapidly cure cold damage. Great for unprotected EVA travel, but prevents use of cryogenic tubes.
extra vehicular activities travel pro

2023-04-14 22:12 UTC, mirrorcult commented
> 
> o Tweaked chemical effects, namely:
> 
>     * Bicaridine no longer causes drunkness
> 
>     * Dermaline no longer causes drunkness on slight overdose

keep both of these

2023-04-24 20:32 UTC, AJCM-git commented
@Alekshhh You coming back to this? (also you committed the engine)

2023-04-24 20:42 UTC, Alekshhh commented
FUCK

2023-04-28 07:10 UTC, Alekshhh commented
I'll prob just make a new one with only the wiki tweaks and recipe tweaks

2023-04-28 07:10 UTC, closed without merging