Machines update
space-wizards/space-station-14 pull request #15196
Opened 2023-04-07 10:38 UTC by SonicHDC

## About the PR

Updates autolathe and uniform printer.

**Media**

![image](https://user-images.githubusercontent.com/100022571/230594287-2ab588ae-a5fd-4a13-8aa9-b1ea1f80d361.png)

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: SonicDC
- add: Added three more directions for autolathe!
- fix: Fixed incorrect rotation of the uniform printer!

2023-04-07 12:51 UTC, Flareguy commented
While these sprites are good, they're pretty hard to read as an autolathe. I'm not really sure if this is a good idea, but if you want to continue it, I would definitely add some extra stuff on the rotational sprites so that it's more recognizable.

2023-04-07 22:28 UTC, SonicHDC commented
Well, I added a light bulb on top to show power. No more ideas yet.

2023-04-09 02:25 UTC, potato1234x commented
isnt the discount dans meant to be poorly sprited?

2023-04-14 11:43 UTC, deltanedas requested changes

2023-04-14 11:43 UTC, deltanedas commented on Resources/Textures/Structures/Machines/VendingMachines/discount.rsi/meta.json
> +  "copyright": "Redesigned by SonicDC#9046",
you still need to include vg copyright if modified

2023-04-14 11:43 UTC, deltanedas commented on Resources/Textures/Structures/Machines/VendingMachines/discount.rsi/meta.json
> +		  0.4,
sus indent

2023-04-14 11:43 UTC, deltanedas commented on Resources/Textures/Structures/Machines/autolathe.rsi/meta.json
> +	  "directions": 4
indent for every directions line is sus

2023-04-16 06:17 UTC, SonicHDC commented on Resources/Textures/Structures/Machines/VendingMachines/discount.rsi/meta.json
> +		  0.4,
Whats sus?

2023-04-22 06:28 UTC, closed without merging