Multiline paper edit
space-wizards/space-station-14 pull request #15216
Opened 2023-04-08 11:01 UTC by Morb0

## About the PR

Use new TextEdit for Papers.
Make some hacks because lack of events.
And rebind newline key function to Shift + Enter (most default thing?)

**Media**

https://user-images.githubusercontent.com/14136326/230717501-e032214b-2e8f-43e8-9cde-2571be079065.mp4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Support multiline text edit for papers

2023-04-09 02:27 UTC, mirrorcult requested changes
paper should definitely use this but not sure about comms console / admin announcements -- people could spam newlines into them which might be annoying? (although realistically thats an admin issue and really easy to deal with)

2023-04-09 02:27 UTC, mirrorcult commented on Content.Client/Administration/UI/AdminAnnounceWindow.xaml.cs
> +
this class has `ILocalizationManager` already injected (`_localization`)

2023-04-11 02:30 UTC, vulppine commented
> paper should definitely use this but not sure about comms console / admin announcements -- people could spam newlines into them which might be annoying? (although realistically thats an admin issue and really easy to deal with)

could also filter newlines into spaces or limit the amount of newlines in an announcement

2023-04-11 02:38 UTC, mirrorcult commented
yeah i'd probably limit the number of newlines

2023-04-11 19:20 UTC, Morb0 commented
> yeah i'd probably limit the number of newlines

Done, only 2 newlines [1984]

2023-04-14 01:12 UTC, DrSmugleaf requested changes

2023-04-14 01:12 UTC, DrSmugleaf commented on Content.Client/Communications/UI/CommunicationsConsoleBoundUserInterface.cs
> +            // No more than 2 newlines, other replaced to spaces
This should be checked on the server as well, when it receives the CommunicationsConsoleAnnounceMessage (same for the 256 char limit)

2023-04-14 19:57 UTC, DrSmugleaf approved these changes

2023-04-14 19:57 UTC, merged