uplink ringtone code + minor cleanup
space-wizards/space-station-14 pull request #15277
Opened 2023-04-10 14:31 UTC by deltanedas

## About the PR
removed the tator-only toggle uplink button from pda settings
tators are told their ringtone code for uplink
they can enter it or guess the 625 combinations to open uplink ui (no #s)

also did some very small cleanup of related files imports

**Media**

https://user-images.githubusercontent.com/39013340/230923187-66476a7d-1979-45f0-8211-1ad6ed5cde52.mp4

- [X] I have added a video to this PR showcasing its changes ingame

**Changelog**
:cl:
- add: The Syndicate has added a ringtone code lock to uplinks. Operatives are told the code when they are briefed. Set your ringtone to the code to open your uplink!

2023-04-10 15:11 UTC, AJCM-git commented
The way this should probably work is by adding/removing the uplink button from the PDA BUI imo (also some UX QOL stuff might be needed now that the code is very important, like adding it to the character menu, automatically opening the character menu when you are selected as traitor and coloring codewords/code in red or smt in the chat)

2023-04-10 18:08 UTC, deltanedas commented
locking/unlocking would be cool however
1. the old bui code for uplink is horrible

but ill try

2023-04-10 18:51 UTC, deltanedas commented
other stuff:

>  automatically opening the character menu when you are selected as traitor
good thing to have and sounds easy, i will try to do it

> coloring codewords/code in red or smt in the chat

im split on this:
- for good players this makes it incredibly easy to find traitors since you dont need to always remember to check for codewords
- but i shouldnt need to deeply analyze chat 24/7 as a traitor, leave that for bozos that realise a tator tried a codeword on them, they dont have the special brain implants or whatever

2023-04-10 19:04 UTC, deltanedas commented
@AJCM-git so uh is there an existing thing for telling the client to open a window or should i make an event specifically for opening character info then handle it on client

2023-04-10 19:35 UTC, AJCM-git commented
> other stuff:
> 
> > automatically opening the character menu when you are selected as traitor
> 
> good thing to have and sounds easy, i will try to do it
> 
> > coloring codewords/code in red or smt in the chat
> 
> im split on this:
> 
>     * for good players this makes it incredibly easy to find traitors since you dont need to always remember to check for codewords
> 
>     * but i shouldnt need to deeply analyze chat 24/7 as a traitor, leave that for bozos that realise a tator tried a codeword on them, they dont have the special brain implants or whatever
> 
>     * at that point you may as well put a traitor icon next to your sprite so it saves you having to say a highlighted codeword in bar

i meant highlighting the ones that appear in the chat the first time informing you what they are, but if you manage to highlight the ones in the chat that would be a cool bonus


> @AJCM-git so uh is there an existing thing for telling the client to open a window or should i make an event specifically for opening character info then handle it on client

I think UISystem has a method for it

2023-04-11 00:37 UTC, mirrorcult approved these changes

2023-04-11 00:37 UTC, mirrorcult commented on Content.Server/PDA/Ringer/RingerSystem.cs
> +                Logger.Info($"{ToPrettyString(user):player} opened uplink {ToPrettyString(uid):uplink}");
no need loggy

2023-04-12 08:00 UTC, deltanedas commented
@mirrorcult so should i change it to be lock rather than open or is it ok

2023-04-12 08:47 UTC, mirrorcult commented
the way it works now is fine

2023-04-12 20:29 UTC, crazybrain23 commented
Does this mean you can't steal TC from another syndicates PDA without knowing the code?

2023-04-12 20:50 UTC, Emisse commented
might be a good time to start thinking of implementing customized uplinks like ss13; implant with less tc, pen uplink, etc

2023-04-12 22:26 UTC, deltanedas commented
> Does this mean you can't steal TC from another syndicates PDA without knowing the code?

correct. you either need to:
- brute force it like a caveman
- brute force it with macro and get bwoinked
- hope bozo left code as ringtone
- get bozo to tell you the code somehow
this is much nicer than previously just rob ssds pda then check uplink + loot the 20tc

> might be a good time to start thinking of implementing customized uplinks like ss13; implant with less tc, pen uplink, etc

i dont think these would have any code in common with pda uplink stuff:
- implant likely an action that toggles ui on your entity
- pen likely toggles ui on itself when clicked (should probably change to writing password on paper thats pretty easily checked)
- headset (since frequency isnt real i guess whispering passwoed into it)

only code theyd share here is trycomp actor and store toggleui

2023-04-23 18:36 UTC, keronshb commented
This will come in handy when the mind refactor is in place so we can store codes there.

2023-04-23 18:46 UTC, keronshb requested changes
![image](https://user-images.githubusercontent.com/54602815/233858669-9adb3d91-472f-47cc-9377-542e76f46bb0.png)

There's a bug when you're making someone a traitor from the context menu. The codewords aren't appearing and it shows the attempted color changing code.

2023-04-23 18:46 UTC, keronshb commented on Resources/Locale/en-US/game-ticking/game-presets/preset-traitor.ftl
> +    [color=red]{$codewords}[/color].
You can't change color like this here

2023-04-23 19:17 UTC, deltanedas commented
oh boy i wonder what broke it now

2023-04-23 19:18 UTC, deltanedas commented on Resources/Locale/en-US/game-ticking/game-presets/preset-traitor.ftl
> +    [color=red]{$codewords}[/color].
is that not how you do it

2023-04-23 19:47 UTC, keronshb commented on Resources/Locale/en-US/game-ticking/game-presets/preset-traitor.ftl
> +    [color=red]{$codewords}[/color].
I don't think you can do it in general.

2023-04-23 19:49 UTC, deltanedas commented on Resources/Locale/en-US/game-ticking/game-presets/preset-traitor.ftl
> +    [color=red]{$codewords}[/color].
guess ill remove

2023-04-23 20:02 UTC, deltanedas commented
![20:56:07](https://user-images.githubusercontent.com/39013340/233862793-f95bf03b-ca4f-45cf-898a-f95409d2d7a3.png)

i dont know why but removing color tag also fixed codewords

2023-04-23 21:00 UTC, keronshb approved these changes
Tested and works fine now.

2023-04-23 21:00 UTC, merged

2023-04-24 13:09 UTC, GoodWheatley commented
I’d normally just ask this on Discord but you don’t have an account, so this seems like the next best method. Is everyone able to use an unlocked uplink, or are traitors still the only ones who can see the button?

2023-04-24 13:11 UTC, mirrorcult commented
read the PR description, its not traitor-only anymore