Rebindable menu + move menu to default F10
space-wizards/space-station-14 pull request #15287
Opened 2023-04-10 21:00 UTC by Skyedra

## About the PR
- Steam users have F12 bound to screenshot, so they would prefer F12 not be bound to anything
- It's now possible to bind the menu key yourself via the UI (allows users to put it back on ESC if they want to)

**Media**

https://user-images.githubusercontent.com/22365940/230997367-e5e69ec3-37eb-429e-b3f6-8ae451aab549.mp4
(In the middle of the test video I forgot F6/F7 are already bound to things :P )

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Ability to bind the menu toggle key directly in the UI
- tweak: Default menu toggle moved from F12 to F10

2023-04-10 21:01 UTC, moonheart08 commented
F11 is bound to the game's builtin screenshot feature.

2023-04-10 21:03 UTC, Skyedra commented
> F11 is bound to the game's builtin screenshot feature.

Are you sure?

![image](https://user-images.githubusercontent.com/22365940/230998454-97c9b33c-9bc4-4538-a96e-e24b57de635f.png)

2023-04-10 21:18 UTC, deltanedas commented
f11 is fullscreen bruh

2023-04-10 21:22 UTC, Skyedra commented
> f11 is fullscreen bruh

f11 doesn't trigger fullscreen for me?

2023-04-10 22:42 UTC, deltanedas commented
on most linux wms

2023-04-10 22:44 UTC, Skyedra commented
> on most linux wms

I'm actually running on linux (Ubuntu KDE) and don't have this behavior.  A window manager binding to a common function key seems very weird (usually they'd require the meta/super key also be pressed).

2023-04-10 23:20 UTC, deltanedas commented
my bad i just have that as my config and am so used to it

2023-04-10 23:21 UTC, Skyedra commented
> my bad i just have that as my config and am so used to it

All good, I moved it to f10 any way as people pointed out a lot of games have f11 as fullscreen.  We don't support that yet anyway, but one day we might so... f10!

2023-04-11 00:23 UTC, vulppine requested changes
one thing i noticed while checking this out is that the escape menu is still titled 'Esc Menu' - since this is no longer specifically the 'Esc' menu, can you change the locale string so it reflects this in this PR?

2023-04-11 00:23 UTC, vulppine commented on Resources/Locale/en-US/escape-menu/ui/options-menu.ftl
> +ui-options-function-show-escape-menu = Toggle menu
this is a little vague

2023-04-11 03:40 UTC, merged