Brig Timers
space-wizards/space-station-14 pull request #15285
Opened 2023-04-10 19:50 UTC by EmoGarbage404

## About the PR

straight up revival of #12006 
quite literally just addressed reviews.

**Media**

https://user-images.githubusercontent.com/45628623/196296187-58f22718-badc-49b7-8cd6-de5eee811331.mp4
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Rolfero, EmoGarbage404
- add: Added brig timers for security. Use these to automate the sentence tracking of your prisoners. You can even hook them up to automatically open doors!

2023-04-10 20:30 UTC, deltanedas commented
would anyone be against me making 1-3 of these buildable and if not then like wallmount gen with steel + wire + board

2023-04-10 20:33 UTC, deltanedas commented
> > would anyone be against me making 1-3 of these buildable and if not then like wallmount gen with steel + wire + board
> 
> Considering they can open doors, they probably would need changes to properly respect access, etc.

doesnt linking *anything* to doors require access in the first place? i assume the brig timer just exists 1. for name/desc and 2. so only sec can use them and not have tiders running in freeing everyone

so if you are concerned about something making a timer for a bridge door, they need bridge access in the first place so its a non-issue

2023-04-10 23:18 UTC, deltanedas commented on Resources/Prototypes/Entities/Structures/Wallmounts/timer.yml
> +    access: [["Brig"]]
this should be sec access so lawyers cant just free their buddies using the timer

2023-04-11 02:04 UTC, vulppine requested changes

2023-04-11 02:05 UTC, vulppine commented
i feel like the TextScreen stuff server-side could be its own system, instead of being tied to signal timers

2023-04-11 03:43 UTC, EmoGarbage404 commented
> i feel like the TextScreen stuff server-side could be its own system, instead of being tied to signal timers

TextScreen is entirely on the client. You just set it by setting appearance data. It's not inherently tied to signal timers

2023-04-11 04:16 UTC, vulppine commented
> > i feel like the TextScreen stuff server-side could be its own system, instead of being tied to signal timers
> 
> TextScreen is entirely on the client. You just set it by setting appearance data. It's not inherently tied to signal timers

yeah, threw me off a bit to see a seemingly unrelated appearance change in the timer - i would’ve just made a system containing the appearance system method calls so that there’s a more central place for changing the properties of text screen visuals

2023-04-12 00:20 UTC, EmoGarbage404 commented on Content.Server/MachineLinking/System/SignalTimerSystem.cs
> +        if (!_interaction.InRangeUnobstructed(mob, uid))
no, because this is for validating clientside messages, not serverside interact events

2023-04-12 00:23 UTC, EmoGarbage404 commented on Content.Client/TextScreen/TextScreenVisualsComponent.cs
> +    public const float PixelSize = 1f / EyeManager.PixelsPerMeter;
start believing

2023-04-12 01:49 UTC, vulppine requested changes

2023-04-17 20:23 UTC, EmoGarbage404 commented
@vulppine the button doesn't add more delay: it's only a start and stop. I don't know if you still want the changes, as I think it functions fine as-is. Your call.

2023-04-18 02:48 UTC, vulppine commented
> @vulppine the button doesn't add more delay: it's only a start and stop. I don't know if you still want the changes, as I think it functions fine as-is. Your call.

oh yeah, in that case that’s fine: i must’ve looked at the demo video wrong earlier, haha

2023-04-19 06:02 UTC, vulppine approved these changes
i think it's fine, unless there's an issue with using sprites for text

2023-04-19 07:47 UTC, merged