Server-side light level system
space-wizards/space-station-14 pull request #15417
Opened 2023-04-14 21:54 UTC by EmoGarbage404

## About the PR

Adds a system for calculating how much "light" is in a certain position on the map.
is based on a pretty rudimentary estimation using pointlightcomponents
Perhaps not all that efficient; i really don't know.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl no fun

2023-04-14 22:07 UTC, mirrorcult commented
would be nice to have a clientside overlay for this to see how good of an estimate it is

2023-04-14 22:08 UTC, mirrorcult requested changes

2023-04-14 22:08 UTC, mirrorcult commented on Content.Shared/Light/LightLevelSystem.cs
> +        foreach (var (light, xform) in EntityQuery<SharedPointLightComponent, TransformComponent>(true))
surely there are enough lights on the map that doing an entitylookup is faster than a query + distance check

2023-04-15 01:18 UTC, EmoGarbage404 commented
to the shed

2023-04-16 21:18 UTC, EmoGarbage404 commented
just going to close this considering how large the change in scope will be

2023-04-16 21:18 UTC, closed without merging