Medical guidebook entries
space-wizards/space-station-14 pull request #15432
Opened 2023-04-15 20:41 UTC by MagnusCrowe

## About the PR

This PR adds several guidebook entries to help players understand the mechanics behind the medical profession, with helpful coloring and even pictures!

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: MagnusCrowe
- add: Added guidebook entries for Medical

2023-04-15 23:42 UTC, moonheart08 commented
@MagnusCrowe The hard part of the chemistry guidebook is already done in one of my PRs, #14060. What needs done still is wiring up the backend to the frontend ui of the guidebook.

2023-04-16 06:57 UTC, moonheart08 commented
Also the usual headsup: If you take my work, please use git merge to incorporate it, not copy paste.

2023-04-16 08:32 UTC, MagnusCrowe commented
> Also the usual headsup: If you take my work, please use git merge to incorporate it, not copy paste.

It won't be part of this pull request but if I am the one to write the Chem guide, I'll do that.

2023-05-01 07:10 UTC, MagnusCrowe commented
Any chance of a review?

2023-05-06 11:52 UTC, metalgearsloth requested changes
Cloneable not clonable IMO. Docs also need spellcheck run over them.

2023-05-06 11:52 UTC, metalgearsloth commented on Resources/Prototypes/Guidebook/medical.yml
> +  text: "/Server Info/Guidebook/Medical/CloningAndMorgue.xml"
Please alphabetise these, at the very least with the child entries.

2023-05-06 11:52 UTC, metalgearsloth commented on Resources/Prototypes/Guidebook/shiftandcrew.yml
>    - Science
Same here please keep it alphabetical and not just inserting it on top.

2023-05-06 11:52 UTC, metalgearsloth commented on Resources/Server Info/Guidebook/Medical/CloningAndMorgue.xml
> +- [color=Red]Their soul has departed.[/color]
```suggestion
If the corpse has an examination message like the one below, they ARE still cloneable, but their "soul" (read: player) is not present.
- [color=Red]Their soul has departed.[/color]
```

2023-05-06 11:52 UTC, metalgearsloth commented on Resources/Server Info/Guidebook/Medical/CloningAndMorgue.xml
> +This biomass reclamation process usually occures in advance.  You will want to reclaim biomass from any corpse that is unclonable.  The reclaimer is reletively slow and often times you will find your
```suggestion
This biomass reclamation process usually occurs in advance.  You will want to reclaim biomass from any corpse that is uncloneable.  The reclaimer is relatively slow and often times you will find your clone room looking more like a corpse pile.  Reclaim early and often.
```

2023-05-06 11:52 UTC, metalgearsloth commented on Resources/Server Info/Guidebook/Medical/DiagnosisAndTreatment/CryoMedicine.xml
> +Once your patient is healed, you may eject them from the pod and begin the process of warming them up.  While in the pod, their body temperature will get very low, but the pod protects them.  Once th
```suggestion
Once your patient is healed, you may eject them from the pod and begin the process of warming them up.  While in the pod, their body temperature will get very low, but the pod protects them.  Once they leave the pod, they will still be cold but no longer be protected by the pod.  To warm them up quickly the application of a low dose of [color=#ff7db5]Leporazine[/color] is recommended.  If no [color=#ff7db5]Leporazine[/color] is on hand, you may need to rely on a winter jacket and scarf.
```

2023-05-06 11:52 UTC, metalgearsloth commented on Resources/Server Info/Guidebook/Medical/DiagnosisAndTreatment/Damage/Toxin.xml
> +All of the cures to toxin damage target the [color=DeepSkyBlue]damage types[/color], not the entire [color=Gold]damage group[/color] .  This means that radiation and poison will have completely diffe
```suggestion
All of the cures to toxin damage target the [color=DeepSkyBlue]damage types[/color], not the entire [color=Gold]damage group[/color].  This means that radiation and poison will have completely different treatments.
```

2023-05-06 11:52 UTC, metalgearsloth commented on Resources/Server Info/Guidebook/Medical/DiagnosisAndTreatment/Diagnosis.xml
> +</Document>
Remove

2023-05-06 11:52 UTC, metalgearsloth commented on Resources/Server Info/Guidebook/Medical/DiagnosisAndTreatment/Viruses.xml
> +</Document>
Diseases are gonna get removed until they get refactored so remove.

2023-05-06 11:52 UTC, metalgearsloth commented on Resources/Server Info/Guidebook/Medical/Medical.xml
> +</Box>
As above.

2023-05-06 11:52 UTC, metalgearsloth commented on Resources/Server Info/Guidebook/Medical/Medical.xml
> +</Box>
I think generally listing these is a bad idea as they're liable to change a lot.

2023-05-06 17:55 UTC, MagnusCrowe commented
Thank you for all the feedback.  I will work on it.

2023-08-08 20:41 UTC, AJCM-git commented
re-open once you come back

2023-08-08 20:41 UTC, closed without merging