Improving the sound for security boots
space-wizards/space-station-14 pull request #15508
Opened 2023-04-18 14:46 UTC by Klaypexx

## About the PR
- Changing sound to jackboots (add sound heavystep1.ogg, heavystep2.ogg,heavystep3.ogg ,heavystep4.ogg). 
- Tweaked the sound for combat boots so it doesn't sound so loud.

**Media**

https://user-images.githubusercontent.com/68664576/232811864-605b1055-622d-46eb-be45-374bcbb856a9.mov

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Klaypexx
- tweak: Jackboots sound changed to unique 
- tweak: The sound for combat boots has become more pleasant to hear

2023-04-23 02:35 UTC, EmoGarbage404 requested changes
The sound for the combat boots in this pr is a copyrighted Half Life 2 sound effect and cannot be used. Please change it.

2023-04-23 18:00 UTC, keronshb approved these changes
> The sound for the combat boots in this pr is a copyrighted Half Life 2 sound effect and cannot be used. Please change it.

~~Please address these changes before this PR can be merged.~~

Oops hit the wrong button here ignore this approval.

2023-04-23 18:00 UTC, keronshb requested changes
> The sound for the combat boots in this pr is a copyrighted Half Life 2 sound effect and cannot be used. Please change it.

Please address these changes before this PR can be merged.

2023-04-25 14:16 UTC, Klaypexx commented on Resources/Audio/Effects/Footsteps/sources.txt
> +heavystep1.ogg, heavystep2.ogg, heavystep3.ogg, heavystep4.ogg are taken from https://mp3crown.org/downloadmp3/oeh0x71lkbx_heavy-footstep-sound-effect-hd-hq.html
> > The sound for the combat boots in this pr is a copyrighted Half Life 2 sound effect and cannot be used. Please change it.
> 
> Please address these changes before this PR can be merged.

Okay, no problem

2023-04-25 14:22 UTC, Klaypexx commented
> > The sound for the combat boots in this pr is a copyrighted Half Life 2 sound effect and cannot be used. Please change it.
> 
> ~Please address these changes before this PR can be merged.~
> 
> Oops hit the wrong button here ignore this approval.

Heavystep1-4 i completely download from youtube (https://m.youtube.com/watch?v=xbkl17x0heo) , the author under the video wrote that the sound, I quote « Feel free to use, i altered the sound of this youtubers sound effect to make it sound more heavy and intense. Enjoy!»

As for combat boots, I will try to find a license for it or find a more suitable sound.

2023-04-28 07:47 UTC, closed without merging