Resolving issue: "Armor isn't predicted #15273"
space-wizards/space-station-14 pull request #15518
Opened 2023-04-18 23:30 UTC by zhoan1

## About the PR

Armor mitigation should be properly when attacking self. Changes made via moving ArmorComponent.cs to a new folder in Shared and adding a new file called ArmorDamageSystem in that same folder.

Tested via process in "Armor isn't predicted #15273"
1. attacked self without armor: dead in 9 hits
2. attacked self with armor: dead in 14 hits
3. attacked a non-self identical entity wearing the same armor: dead in 14 hits

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added new folder Armor under Content.Shared, new file ArmorDamageSystem.cs
- remove: Removed duplicate code from ArmorSystem.cs that is now present in ArmorDamageSystem.cs
- tweak: Changed location and namespace of ArmorComponent.cs to belong to Content.shared now.
- fix: Fixed armor mitigation not counting when attacking self

2023-04-18 23:35 UTC, DogZeroX commented
Only put player-facing changelogs.

2023-04-19 10:04 UTC, metalgearsloth requested changes

2023-04-19 10:04 UTC, metalgearsloth commented on Content.Shared/Armor/ArmorDamageSystem.cs
> +}
1. Please use file-scoped namespaces
2. The server system should be inheriting this
3. You should move the examine here
4. ArmorComponent isn't actually networked

2023-04-29 07:00 UTC, metalgearsloth commented
Re-open when you come back to this.

2023-04-29 07:00 UTC, closed without merging