Species-blocking system for specific jobs
space-wizards/space-station-14 pull request #15536
Opened 2023-04-19 14:49 UTC by noverd

## About the PR

In this PR, I added a species-blocking system for specific jobs. This can be useful for blocking aliens from the positions of captain or head. To do this, a new field called "allowSpecies" has been added to the Job prototype. It takes a list of allowed strings. If a player tries to enter a task with a prohibited species, the system will try to find a character in the preferences with a suitable Species. If it doesn't find one, it will create a new character with the allowed species.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Species-blocking system for specific jobs

2023-04-19 14:56 UTC, noverd commented
> > This can be useful for blocking aliens from the positions of captain or head
> 
> jester-that-helps would like to have a word with you
My discord is CodTenAlt#9052

2023-04-19 14:59 UTC, GoodWheatley commented
Why are you trying to codify speciesism

2023-04-19 15:01 UTC, mirrorcult commented
cause some servers will want this functionality?

2023-04-19 15:01 UTC, metalgearsloth requested changes

2023-04-19 15:02 UTC, noverd commented
> Why are you trying to codify speciesism

No discrimination, I just don't think there will be HoS dion in reality

2023-04-19 15:04 UTC, GoodWheatley commented
> > Why are you trying to codify speciesism
> 
> No discrimination, I just don't think there will be HoS dion in reality

Didn’t notice that this is just adding the functionality, sorry. Good PR

2023-04-20 11:14 UTC, noverd commented on Content.Server/GameTicking/GameTicker.Spawning.cs
> +            }
OK

2023-04-21 18:08 UTC, Myakot commented
Finally. Space-station-14 will reach it's perfect state - xenophobia.

2023-04-22 19:27 UTC, closed without merging

2023-04-23 12:09 UTC, noverd commented
In the future, when I do this, I will do a PR