make timers constructable and deconstructable
space-wizards/space-station-14 pull request #15571
Opened 2023-04-20 08:18 UTC by deltanedas

## About the PR
similar recipe to wallmount gens
- 5 steel 2 lv and a board
- for screen and brig timers, some glass as well
- screwdrive

**Media**
soon

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added construction for signal timer, screen timer and brig timer.

2023-04-28 08:58 UTC, deltanedas commented
@EmoGarbage404 any issues with this or is it good

2023-04-29 09:33 UTC, metalgearsloth requested changes

2023-04-29 09:33 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Structures/Wallmounts/timer.yml
> +  - type: Fixtures
Remove.

2023-04-29 20:41 UTC, EmoGarbage404 approved these changes
Looks fine at a glance. Assuming it works in game, gtg

2023-05-01 22:58 UTC, deltanedas commented
@EmoGarbage404 j

2023-05-06 11:14 UTC, metalgearsloth approved these changes

2023-05-06 11:15 UTC, merged