Blindness refactor
space-wizards/space-station-14 pull request #15705
Opened 2023-04-23 19:05 UTC by ElectroJr

- Removes blindness source tracking in favour of just raising cancellable events.
- Same goes for vision modifying/protecting clothing
- Use auto comp states.
- I have no idea what was going on with BlurryVision

2023-04-23 19:10 UTC, ElectroJr commented on Content.Server/Chemistry/ReagentEffects/ChemHealEyeDamage.cs
>                  return;
I'm not sure what this is meant to do? Is it supposed to be a quantized reaction?

2023-04-24 00:09 UTC, metalgearsloth requested changes
also VVreadwrite for most of the fields.

2023-04-24 00:09 UTC, metalgearsloth commented on Content.Shared/Eye/Blinding/Components/RequiresEyeProtectionComponent.cs
> +public sealed class RequiresEyeProtectionComponent : Component
Networked

2023-04-29 05:19 UTC, metalgearsloth approved these changes

2023-04-29 05:32 UTC, merged