Convert ReinforcedWallVisualizer to ECS
space-wizards/space-station-14 pull request #15735
Opened 2023-04-24 10:51 UTC by Bixkitts

part of #8995

2023-04-24 10:53 UTC, mirrorcult approved these changes

2023-04-24 21:47 UTC, AJCM-git requested changes
Build fail, test your changes.
Also we have something called generic visualizers that i *think* can be used for this, they are handled by the `GenericVisualizerSystem` if you want to look at the internals and you can see examples of how to use them by searching `type: GenericVisualizer` in the prototypes.

2023-04-25 22:33 UTC, Bixkitts commented
Now it builds.
Will look at `GenericVisualizerSystem` and see how/if I can reasonably apply it to this and more of these
small refactors.

2023-04-27 00:14 UTC, vulppine requested changes
generic visualizer may be the nicer solution here, but i'm leaving these review comments so you have a better idea of what the code style is for SS14

2023-04-27 00:14 UTC, vulppine commented on Content.Client/Wall/ReinforcedWallVisualizerSystem.cs
> +{
filescoped namespace

2023-04-27 00:14 UTC, vulppine commented on Content.Client/Wall/ReinforcedWallVisualsComponent.cs
> +public sealed class ReinforcedWallVisualsComponent : Component
you need to add `[RegisterComponent]` as an attribute here - that might be why your tests are failing

2023-04-27 00:14 UTC, vulppine commented on Content.Client/Wall/ReinforcedWallVisualizerSystem.cs
> +            object index = sprite.LayerMapReserveBlank(ReinforcedWallVisualsComponent.ReinforcedWallVisualLayers.Deconstruction);
`var` instead of type

2023-04-27 00:14 UTC, vulppine commented on Content.Client/Wall/ReinforcedWallVisualizerSystem.cs
> +            int stage = (int)deconStage;
`var` instead of type

2023-04-29 18:10 UTC, Bixkitts commented
Reading the docs+source and trying to wrap my head around yaml-AppearanceChangeEvent-AppearanceData-components-enums and the sprite layers and states system.

2023-04-29 19:08 UTC, Bixkitts commented
Figured it out (mostly). 
Appears to work in game.
I'll start doing this to other Visualizers where I can.
Should be ready to merge unless I messed up!

2023-05-01 19:39 UTC, AJCM-git approved these changes

2023-05-01 19:39 UTC, merged