Fixes zipties spawning multiple entities on removal
space-wizards/space-station-14 pull request #15761
Opened 2023-04-25 00:28 UTC by Menshin

The handcuff system is now handling the broken cuffs spawning server-side, fixes #15730 .

Also fixed the popups misprediction when beginning to uncuff someone and added PVS wide popup feedback as it was already the case for cuffing.

## About the PR

**Media**

- [X] This PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Despite clowns complains, Nanotrasen have recalled all magic zipties that spawned myriads of themselves on removal and replaced them with plain ones.
- tweak: Starting to uncuff someone (or self) now gives a popup feedback to observers around.

2023-04-29 11:30 UTC, metalgearsloth requested changes

2023-04-29 11:50 UTC, Menshin commented on Content.Shared/Cuffs/SharedCuffableSystem.cs
> +            }
Indeed, no reason for these to be server-side, i'm fixing that.

2023-05-02 10:14 UTC, metalgearsloth approved these changes

2023-05-02 10:14 UTC, merged

2023-10-19 13:06 UTC, lilazero commented
Tested. Doesn't fix it. Still spawns multiple zipties on the floor #21088