Botany stuff
space-wizards/space-station-14 pull request #15793
Opened 2023-04-25 18:15 UTC by ThunderBear2006

## About the PR

Added a new system where plants may transmutate into whole new plant species.

The way this happens is through a new plant gene: TRA(nsmution), TRA is three integer values
that can mutate like other plant genetics (e.g. plant yield).

When a plant's TRA value matches one of its transmutations TRA values it transmutes into that plant,
Plant transmutations are defined in their seed prototype, meaning a lemon plant won't turn into an apple tree (unless you add that transmutation).

Added new plants that can only be acquired through plant transmutation:

Cannabis can turn into: 
Rainbow cannabis, grinds into THC, Space drugs and mind breaker toxin

Banana tree can turn into:
Pink banana tree: produces pink bananas that can be ground or juiced into a new chemical: Laughtex (more on that later)

Lemon plant can turn into:
Hell Lemon: Has a very short fuse that triggers a tiny but powerful explosion, can either go off by being used or at random

Poppy can turn into:
Clown flower: works like a spray bottle but with a higher velocity, only holds 10 units

Fly Amanita can turn into:
Shroominal Pod: Produces a Shroomkin (mushroom chicken) that lays Shreggs (shroom eggs), Shreggs are like normal eggs but contain a significant amount of blood and some space drugs in them

Shroominal Pod can turn into:
Shroomanoid Pod: Produces a Shrooman (mushroom man), a new ghost role, Shroomen can only wear a belt, a backpack, gloves, neck garments, mask, glasses and ear pieces. Shroomen talk with an elegant accent (like if you read a thesaurus as a pass time).

Shroomen are very weak to fire, weak to slash, blunt and shock, but take very little asphyxiation damage and cold damage and take half poison damage. Bare handed attacks deal 2 brute and 6 poison, so great if the station is spaced but bad in a fight

Laughtex: A new toxin that makes the subject laugh uncontrollably (I swear I've typed this sentence so many damn times) but slowly suffocates them, deals 3 units of airloss scaled by quantity, same effects if touched but only 1 unit of airloss scaled by quantity.

TRA-05: Chemical that increments plant TRA values in the positive by one unit when metabolized at the cost of using 10 units of water and nutriment

TRA-91: Like TRA-05 but decrements TRA, costs the plant half the nutriment and water

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

All plants and their produce:
![image](https://user-images.githubusercontent.com/100388962/234354470-09b82aa5-3cda-4a7d-97ba-4418964f3c09.png)

Laughtex Effects:
https://user-images.githubusercontent.com/100388962/234360766-557e2f09-eca9-4b63-93ee-1fa9fb1855d5.mp4

Fully decked out shrooman:
![image](https://user-images.githubusercontent.com/100388962/234361877-b5535b87-879e-4fe1-affb-2247533be425.png)
![image](https://user-images.githubusercontent.com/100388962/234361943-be99cac6-2b16-437c-b791-b029b60c04ce.png)
![image](https://user-images.githubusercontent.com/100388962/234361977-49986230-ce95-44e6-a843-a4de27431af2.png)

Shrooman inventory slots:
![image](https://user-images.githubusercontent.com/100388962/234362088-46b4c404-123b-4128-8938-b4486dc85931.png)

Hell Lemon in use:
https://user-images.githubusercontent.com/100388962/234363426-af82de19-45b6-4659-9010-560a7d4cfcad.mp4

**Changelog**

:cl: ThunderBear#9834
- add: The egg heads over at Centcom have discovered a new element to plant genetics, they're calling it the TRA Sequence and plants with the correct TRA Sequence have been documented to transmute into new plant species! Centcom has advised all botanists and scientists to experiment with this new genetic element in hopes of discovering new plant species!
- add: Added Laughtex, a chemical reagent that causes the subject to laugh uncontrollably during metabolization or touch, causes airloss damage and comes from pink bananas!
- add: Added TRA-05 and TRA-91, two new chemical reagents that can increment or decrement (respectively) a plant's TRA sequence during metabolization

2023-04-25 18:47 UTC, ThunderBear2006 commented
Tiny note: If anyone reviews this requesting a change please @me on the discord server

2023-04-25 23:06 UTC, potato1234x commented
missed opportunity to call the hell lemons combustible lemons

2023-04-25 23:28 UTC, metalgearsloth commented
> Shroominal Pod
What's wrong with pod people?

Additionally I'm hesitant to add even more botany values when the seedprototype needs a refactor and none of it is exposed to players still.

2023-04-26 00:39 UTC, ThunderBear2006 commented
> missed opportunity to call the hell lemons combustible lemons

I thought it would line up with the quote better

2023-04-26 00:45 UTC, ThunderBear2006 commented
> > Shroominal Pod
> > What's wrong with pod people?
> 
> Additionally I'm hesitant to add even more botany values when the seedprototype needs a refactor and none of it is exposed to players still.

That is a shame, I'm not sure what I could do for the seed prototype but I maybe I could merge my PR with the plant analyzer PR if thats possible?

2023-04-26 00:50 UTC, ThunderBear2006 commented
> > > Shroominal Pod
> > > What's wrong with pod people?
> > 
> > 
> > Additionally I'm hesitant to add even more botany values when the seedprototype needs a refactor and none of it is exposed to players still.
> 
> That is a shame, I'm not sure what I could do for the seed prototype but I maybe I could merge my PR with the plant analyzer PR if thats possible?

Also I didn't make pod people because we already have plant people, the Diona. I thought maybe a different approach could be taken while achieving a similar result

2023-04-26 01:56 UTC, vulppine requested changes
there's a lot of formatting issues, please make sure that your bracing adheres to this style:

```cs
blockStatement
{
  // lines go here
}
```

i've attached a few review comments to some code, but generally you'll need to go over your changed files and fix this up

2023-04-26 01:56 UTC, vulppine commented on Content.Server/Botany/Systems/BotanySystem.Seed.cs
> +    public EntityUid SpawnSeedPacket(SeedData seedData, EntityCoordinates coords, EntityUid user, bool sampled = false)
unused parameter

2023-04-26 01:56 UTC, vulppine commented on Content.Server/Chemistry/ReagentEffects/PlantMetabolism/PlantShiftTRA.cs
> +namespace Content.Server.Chemistry.ReagentEffects.PlantMetabolism
this needs to be a filescoped namespace

2023-04-26 01:56 UTC, vulppine commented on Content.Server/Explosion/Components/TriggerRandomlyComponent.cs
> +namespace Content.Server.Explosion.Components
this needs to be a filescoped namespace

2023-04-26 01:56 UTC, vulppine commented on Content.Server/Explosion/EntitySystems/TriggerSystem.cs
> +        private void UpdateRandom(float frameTime){
fix the braces here

2023-04-26 01:56 UTC, vulppine commented on Content.Server/Explosion/EntitySystems/TriggerSystem.cs
> +            foreach (var random in EntityQuery<TriggerRandomlyComponent>()){
fix the braces here

2023-04-26 01:56 UTC, vulppine commented on Content.Shared/Botany/TransmutationPrototype.cs
> +    [DataField("plantPrototype")] public string prototype = "";
```suggestion
    [DataField("plantPrototype")] public string Prototype = "";
```

2023-04-26 01:56 UTC, vulppine commented on Content.Server/Botany/Systems/PlantHolderSystem.cs
> +            foreach(var tra_proto in seedData.PlantTransmutations){
variable needs to be `camelCase`, so:

```suggestion
            foreach (var traProto in seedData.PlantTransmutations)
            {
```

2023-04-26 01:57 UTC, vulppine commented
> > > > Shroominal Pod
> > > > What's wrong with pod people?
> > > 
> > > 
> > > Additionally I'm hesitant to add even more botany values when the seedprototype needs a refactor and none of it is exposed to players still.
> > 
> > 
> > That is a shame, I'm not sure what I could do for the seed prototype but I maybe I could merge my PR with the plant analyzer PR if thats possible?
> 
> Also I didn't make pod people because we already have plant people, the Diona. I thought maybe a different approach could be taken while achieving a similar result

diona in SS13 *are* the pod people (at least in some implementations of SS13), so i think that you should consider making it so that the pods spawn them instead

2023-04-26 02:20 UTC, ThunderBear2006 commented
> diona in SS13 _are_ the pod people (at least in some implementations of SS13), so i think that you should consider making it so that the pods spawn them instead

I would have done that but I thought it would've been better if the humanoid that was spawned wouldn't be as good as a round start species, otherwise you'd just be able to respawn once the botanist whips up a batch of them, at least with the current implementation there are downsides.

Either way with @metalgearsloth and others not wanting to add more stuff to botany until it is refactored makes me think its not worth the time to make changes to this PR unless there is a solution that makes everyone happy

2023-04-26 02:23 UTC, vulppine commented
> > diona in SS13 _are_ the pod people (at least in some implementations of SS13), so i think that you should consider making it so that the pods spawn them instead
> 
> I would have done that but I thought it would've been better if the humanoid that was spawned wouldn't be as good as a round start species, otherwise you'd just be able to respawn once the botanist whips up a batch of them, at least with the current implementation there are downsides.
> 
> Either way with @metalgearsloth and others not wanting to add more stuff to botany until it is refactored makes me think its not worth the time to make changes to this PR unless there is a solution that makes everyone happy

yeah, that was the intention: however, diona also have a 'growth stage' post-harvest where they're a nymph and have to harvest blood samples in order to grow into a full humanoid - the growth stage is essentially the same as a monkey - doing something like this might be out of scope and would be a lot more to review for this PR, and i'm not sure if we need *more* species at the moment either

2023-05-18 02:27 UTC, ThunderBear2006 commented
Closing because botany needs a rework to both have better gameplay and to not be a code abomination

2023-05-18 02:27 UTC, closed without merging

2024-02-07 15:56 UTC, Carmell0 commented
For the love of GOD add an industrial reagent grinder, litteraly just a blender with inf capacity and a chem master to put reagents in. This would be SO MUCH BETTER for botany

2024-02-07 16:02 UTC, Aisu9 commented
> For the love of GOD add an industrial reagent grinder, litteraly just a blender with inf capacity and a chem master to put reagents in. This would be SO MUCH BETTER for botany

just build a material reclaimer, it grinds stuff instantly and with no material inefficiency

2025-01-09 23:42 UTC, Qwazori commented
Since the botany refactoring is already partially implemented and already well underway, I think it's worth resuming this pull request