new unbeelivable jelly candies
space-wizards/space-station-14 pull request #15844
Opened 2023-04-27 12:16 UTC by Tunguso4ka

## About the PR

Adds Shalena Bjilka (Шалена Бджілка or Crazy Bee) jelly candies to the Discount Den. 

**Media**

![зображення](https://user-images.githubusercontent.com/71643624/234857945-6303f57a-dcb1-4e84-ad5c-700032993ac4.png)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Tunguso4ka
- add: new unbeelivable jelly candies flooded the Discount Den assortment

2023-04-27 12:22 UTC, deltanedas requested changes

2023-04-27 12:22 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
> +  name: Shalena Bjilka
should be `shalena bjilka`

2023-04-27 12:22 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
> +  name: empty Shalena Bjilka
same

2023-04-27 12:30 UTC, Tunguso4ka commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
> +  name: Shalena Bjilka
done.

2023-04-27 12:30 UTC, Tunguso4ka commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
> +  name: empty Shalena Bjilka
done.

2023-04-27 12:39 UTC, lapatison commented
Excuse me, but isn't that a registered trademark?
https://www.roshen.com/ro/en/products/boxed-sweets/crazy-bee-frutty

2023-04-27 13:07 UTC, Tunguso4ka commented
> Excuse me, but isn't that a registered trademark? https://www.roshen.com/ro/en/products/boxed-sweets/crazy-bee-frutty

i forgor. Will rename ma candies.

2023-04-29 04:08 UTC, metalgearsloth commented
The other food contents are generic but this just seems to be a specific real world food analogue being added? I'm not seeing a strong need to add this.

2023-04-30 07:51 UTC, moonheart08 commented
For those downvoting this PR solely because of political reasons i.e. the fact this is Ukranian: Your opinion has been discarded.

However, we're not adding niche regional foods at this time, and also just removed one, so this cannot be added either.

2023-04-30 07:51 UTC, closed without merging