Added uranium glass and uranium window
space-wizards/space-station-14 pull request #15869
Opened 2023-04-28 16:28 UTC by AsikKEsel

## About the PR

Aded uranium glass, uranium window, reinforced uranium glass, reinforced uranium window

**Media**

![UraniumGlassUpdate](https://user-images.githubusercontent.com/115815982/235202499-55107247-b0f1-4669-99c4-81dd507dc089.png)

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added uranium glass and uranium window. Don't worry, scientists reduce radioactive emissions by 97.4% with RadAbsorb

2023-04-28 16:32 UTC, deltanedas requested changes

2023-04-28 16:32 UTC, deltanedas commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +  description: Clear and very tougher, with a RadAbsorb.
Clear and much tougher than regular glass, with added RadAbsorb (patent pending) to protect you from deadly radiation.

2023-04-28 16:32 UTC, deltanedas commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +  description: Clear and very tougher, with a RadAbsorb.
ditto

2023-04-28 16:33 UTC, deltanedas commented
has this been added to ore processor recipes, its really handy for making lots of glass sheets

2023-04-29 05:34 UTC, metalgearsloth requested changes
Arbitrage needs fixing hence the test failure.

2023-04-29 05:34 UTC, metalgearsloth commented on Resources/Textures/Structures/Windows/reinforced_uranium_window.rsi/meta.json
> +    "copyright": "made by AsikKEsel",
Isn't there existing sprites in ss13 to use instead? Also these are derivatives but don't credit the original source.

2023-05-06 04:47 UTC, metalgearsloth approved these changes

2023-05-06 04:47 UTC, merged