Attach paper to closets and lockers
space-wizards/space-station-14 pull request #15864
Opened 2023-04-28 07:02 UTC by lzk228

## About the PR

You can attach papers to lockers and closets like to crates

**Media**

![image](https://user-images.githubusercontent.com/124214523/235304247-591019bc-405a-4454-8d51-bd18b7bb84b8.png)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: lzk
- tweak: Paper can be attached to closets and lockers

2023-04-29 11:58 UTC, metalgearsloth commented
Screenshots?

2023-04-29 13:09 UTC, lzk228 commented
> Screenshots?

done

2023-04-29 17:44 UTC, metalgearsloth commented
Tests need fixing.

2023-05-01 02:09 UTC, Emisse commented
might be nice to have this visually displayed, same with cargo crates

2023-05-01 19:04 UTC, AJCM-git requested changes
fix test (extra points if you make it visually display the papers in the locker sprite but i wont require you to)

2023-05-10 05:24 UTC, lzk228 commented
it's too hard to make visually display papers

2023-05-12 15:31 UTC, AJCM-git commented
merge master

2023-05-14 01:04 UTC, AJCM-git requested changes
Test fail due to an inheritance error, search `LockerWallMedicalDoctorFilled` and replace its prototype with this and it should run correctly:
```yml
- type: entity
  parent: LockerWallMedical
  id: LockerWallMedicalDoctorFilled
  name: medical doctor's wall locker
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: HandheldHealthAnalyzer
        prob: 0.6
      - id: ClothingHandsGlovesLatex
      - id: ClothingHeadsetMedical
     # - id: ClothingEyesHudMedical #Removed until working properly
      - id: ClothingBeltMedical
      - id: ClothingHeadHatSurgcapGreen
        prob: 0.1
        orGroup: Surgcaps
      - id: ClothingHeadHatSurgcapPurple
        prob: 0.05
        orGroup: Surgcaps
      - id: ClothingHeadHatSurgcapBlue
        prob: 0.90
        orGroup: Surgcaps
      - id: UniformScrubsColorBlue
        prob: 0.5
        orGroup: Surgshrubs
      - id: UniformScrubsColorGreen
        prob: 0.1
        orGroup: Surgshrubs
      - id: UniformScrubsColorPurple
        prob: 0.05
        orGroup: Surgshrubs
      - id: NitrousOxideTankFilled
        prob: 0.3
      - id: ClothingMaskSterile
  ```

2023-05-14 01:04 UTC, AJCM-git requested changes
a

2023-05-14 19:02 UTC, merged