Hot potato on fire
space-wizards/space-station-14 pull request #16017
Opened 2023-05-02 15:00 UTC by Slava0135

## About the PR

Makes hot potato deal heat damage while you holding it

**Media**

**Changelog**

:cl:
- add: hot potato now deals damage while you are holding it

2023-05-02 16:34 UTC, Slava0135 commented
added burn sound effect
https://user-images.githubusercontent.com/40753025/235728649-b05ea01d-1ffe-4d20-984e-6e4d8bee86c7.mp4

2023-05-03 05:41 UTC, metalgearsloth requested changes

2023-05-03 05:41 UTC, metalgearsloth commented on Content.Server/HotPotato/HotPotatoSystem.cs
> +    }
This should be its own component for holding an item doing damage, also it's not a good idea to spam damage events every tick, just tick every second or something.

2023-05-05 13:43 UTC, metalgearsloth requested changes
Damage is predicted so should be able to put this in shared and network it too I think.

2023-05-05 13:43 UTC, metalgearsloth commented on Content.Server/Damage/Components/DamageOnHoldingComponent.cs
> +    public TimeSpan NextDamage = TimeSpan.Zero;
TimeOffsetSerializer + datafield.

2023-05-05 13:43 UTC, metalgearsloth commented on Content.Server/Damage/Systems/DamageOnHoldingSystem.cs
> +                component.NextDamage = _timing.CurTime + TimeSpan.FromSeconds(component.Interval);
Set this on enabled.

2023-05-05 13:43 UTC, metalgearsloth commented on Content.Server/Damage/Systems/DamageOnHoldingSystem.cs
> +    }
This should be a resolve that takes in the component instead.

2023-05-06 10:30 UTC, metalgearsloth approved these changes

2023-05-06 10:30 UTC, merged