Make mop bucket destructible
space-wizards/space-station-14 pull request #16124
Opened 2023-05-05 15:54 UTC by notquitehadouken

## About the PR

Fixes #16122 
Mop buckets now break and have half the health of a trolley

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Mop buckets are no longer indestructible

2023-05-05 16:17 UTC, Slava0135 commented
> hope you can make these somehow otherwise jani gonna have no buckets

bananium mop buckets

2023-05-05 16:17 UTC, Slava0135 commented
you can actually order buckets from cargo

2023-05-05 17:52 UTC, mirrorcult commented
this should spill contents on destruction

2023-05-05 18:41 UTC, notquitehadouken commented
> What about making cardboard boxes destructible too?

:stare:

2023-05-05 21:40 UTC, keronshb commented
> What about making cardboard boxes destructible too?

They are, just not for syndies.

2023-05-06 01:07 UTC, metalgearsloth requested changes

2023-05-06 01:07 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
> +          - !type:EmptyAllContainersBehaviour
This doesn't do anything as it doesn't have containers.

2023-05-06 06:33 UTC, Myakot commented
> 

![image](https://user-images.githubusercontent.com/30875116/236607047-f4648b33-f799-4453-91a7-03b4a041327c.png)
No they are not destructible by bullets. First thind I tried doing with new ice anomaly was either blocking it's projectiles with mop buckets or boxes, boxes are larger and easier to use.
Sorry for off-topping.

2023-05-06 19:24 UTC, notquitehadouken commented
alright i'll make a less horrible solution

2023-05-06 19:24 UTC, closed without merging