Chemical Wiki Descriptions, Recipe Tweaks & Effect Tweaks (2)
space-wizards/space-station-14 pull request #16157
Opened 2023-05-06 08:58 UTC by Alekshhh

## About the PR
o Changes almost all wordings in the chemical wiki section to have up-to-date, consistent and relevant information.
o Tweaked chemical recipes, namely:

- All plasma catalysts were reduced from 5u to 1u
- Epinephrine no longer requires diethylamine, creates 5u epinephrine
- Dexalin requires 2u hydrogen,1u oxygen, 1u plasma catalyst, creates 3u dexalin
- Lexorin requires 1u heartbreaker toxin, 1u fluorine, 1u plasma, creates 3u lexorin
- Ultravasculine requires 1u dylovene, 1u sodium, 1u plasma catalyst
- Sigynate requires 1u iodine, 1u kelotane, 1u sugar, creates 3u sigynate
- Phenol requires 1u oxygen, 1u hydrogen, 1u carbon
- Diphenymethylamine requires 1u ethyloxyephedrine, 1u phenol, 1u sodium carbonate, makes 3u diphenylmethylamine
- Ammonia reaction creates 3u instead of 4u
- Sodium carbonate no longer requires ammonia, creates 3u sodium carbonate

o Tweaked chemical effects, namely:

- Nocturine no longer causes poison damage on overdose (60u to deal 2 poison per second are you real)
- Sigynate cures 2 caustic a second instead of 6

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Alekshhh
- tweak: The chemical page of the wiki has been heavily reworded, and a few chemicals had their recipes tweaked and effects changed a little

2023-05-12 16:10 UTC, AJCM-git requested changes

2023-05-12 16:10 UTC, AJCM-git commented on Resources/Locale/en-US/reagents/meta/toxins.ftl
> +reagent-desc-unstable-mutagen = A concoction of irradiated chemicals that are prone to rapid mutation within plants - dionas being the exception. Use with caution.
weird wording `chemicals that are prone to rapid mutation within plants`

2023-06-05 11:15 UTC, metalgearsloth commented
@Alekshhh are you coming back to this.

2023-06-15 22:05 UTC, AJCM-git commented
re-open when you come back to this

2023-06-16 03:46 UTC, metalgearsloth commented
> re-open when you come back to this

I agreed to work on it in exchange for laser raptor.

2023-07-31 06:03 UTC, merged

2023-07-31 19:08 UTC, Aisu9 commented
was it needed to make chemistry no longer needing Botanist help to heal caustic damage efficiently?
Derma now trivialise burn healing
Hyro and Dylo both heal poison and radiation damage
Not a single medicine alleviate bloodloss damage
Epinephrine only work on critical patient
And for the best, Occuline deals eye damage instead of healing eye damage

2023-07-31 19:13 UTC, Aisu9 commented
Doxarubixadone is still a waste of cryoxadone with how easy you can synthetise phalanximine

2023-07-31 19:41 UTC, LankLTE commented
I don’t see why this needs to be made? Updating guidebook descriptions is fine, but then it also makes a bunch of seemingly random Chem changes with no explanation as to why. Sigynate in particular was super underused as-is and I don’t see why Dexalin needs to be harder to make.

2023-08-01 16:25 UTC, hord-brayden commented
This wasn't a great one, seemed pretty random to alter reagents to make some recipes easier and others harder.

I'm unsure if this was intentional, but lexorin was possible to make (albeit very diluted) without a chemmaster4000 or Chen dispenser by anyone given they find a few common ingredients- now with Florine, lexorin is now effectively ONLY for chemists.