Make Reactions conserve thermal energy
space-wizards/space-station-14 pull request #16190
Opened 2023-05-06 22:35 UTC by ElectroJr

Currently reacting 5 sodium & 5 chlorine will just reset the solution temperature back to room temperature. This PR changes around the order of the reaction processing so that products are added to a solution before reaction effects are triggered. It also Ensures that thermal energy is conserved when creating products & consuming reagents. Reagent effects that change thermal energy (i.e., exo/endo-thermic reactions) get processed after this and should still work.

This might have unintended side effects somewhere. E.g., when a reaction destroys reagents & reduces the overall heat capacity, the temperature of the remaining reagents would now be significantly larger.

:cl:
- tweak: Chemical reactions should now conserve thermal energy.

2023-05-06 22:36 UTC, ElectroJr commented on Content.Shared/Chemistry/Reaction/ChemicalReactionSystem.cs
> -            }
This implicitly assumed that the properties/contents of the solution haven't changed, which isn't generally true.

2023-05-07 03:09 UTC, metalgearsloth requested changes

2023-05-07 03:09 UTC, metalgearsloth commented on Content.Shared/Chemistry/Reaction/ChemicalReactionSystem.cs
>                          $"Reaction effect {effect.GetType().Name:effect} of reaction ${reaction.ID:reaction} applied on entity {ToPrettyString(entity):entity} at {Transform(entity).Coordinates:coordi
Should this be using the above coordinates?

2023-05-13 03:10 UTC, metalgearsloth approved these changes

2023-05-13 03:10 UTC, merged