Crew monitoring server board
space-wizards/space-station-14 pull request #16191
Opened 2023-05-06 23:06 UTC by Nimfar11

## About the PR

Now if the crew monitoring server is destroyed or unavailable, the RND will be able to build it.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: Nimfar11

- add: Adds the ability to examine and print the crew monitoring server board.

2023-05-07 00:25 UTC, keronshb commented
This needs discussion. There's already powergaming issues with handheld crew monitors, and freely being able to print the computer boards adds to that.

2023-05-07 00:38 UTC, Nimfar11 commented
It is already possible to print consoles and portable crew monitoring consoles. This board, gives the ability to restore the monitoring work if the server was destroyed or it is not on the map at all. It would be strange not to use the basic mechanics.

2023-05-07 03:49 UTC, metalgearsloth commented
> This needs discussion. There's already powergaming issues with handheld crew monitors, and freely being able to print the computer boards adds to that.

I think we should just move the handheld crew monitor later and slot this in instead potentially?

2023-05-07 05:23 UTC, keronshb commented
> > This needs discussion. There's already powergaming issues with handheld crew monitors, and freely being able to print the computer boards adds to that.
> 
> I think we should just move the handheld crew monitor later and slot this in instead potentially?

I was thinking instead of allowing it to be printed, a spare could be in tech storage and/or more spares could be ordered from cargo as needed.

2023-05-07 06:34 UTC, lzk228 commented
you should add gold and maybe plasma to recipe

2023-05-07 11:14 UTC, Nimfar11 commented
> Wait portable crew monitors can be printed and they're not just limited by vendor??

No, they can print by learning the technology you need for the console and as I suggested for the server. Only there it seems to need gold. So if anything to limit, then the cost of the most handheld crew monitor.

> you should add gold and maybe plasma to recipe

Definitely not for the server, I think it is worth making more expensive for rare resources itself handheld monitor.

2023-05-08 01:38 UTC, keronshb requested changes
I talked it over, we feel that the board should be put into cargo instead. It helps control it more over printing. The crew monitoring console will also be moved in a separate PR.

There should also be a spare mapped onto each map in tech storage as well, if it isn't there already. No need to do it for this PR though.

2023-05-08 01:38 UTC, keronshb commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - CrewMonitoringServerMachineCircuitboard
Please add this to cargo as an option to buy instead.

2023-05-08 05:49 UTC, closed without merging