Stop puddles and soap from blocking doors
space-wizards/space-station-14 pull request #16258
Opened 2023-05-08 20:51 UTC by DawBla

## About the PR

Stops puddles and soap from blocking doors
Fixes #16167, #15253

**Media**

https://user-images.githubusercontent.com/46636558/236931309-cf709052-712e-4f44-b977-42d120aae8ce.mp4

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Mumohan
- fix: Airlocks are no longer scared of puddles and soap. They should now close properly.

2023-05-08 20:52 UTC, EmoGarbage404 commented
does this not allow doors to close over objects like walls, tables, and barricades?

2023-05-08 20:57 UTC, DawBla commented
> does this not allow doors to close over objects like walls, tables, and barricades?


https://user-images.githubusercontent.com/46636558/236933435-2c62c230-0240-45f0-87cc-cab8f71c2e8e.mp4

Looks like it works fine

2023-05-08 21:08 UTC, keronshb requested changes
Double check to see if you can slip on soap and also see if you can still block using shields in the middle of doorways without it closing on you.

2023-05-08 21:19 UTC, DawBla commented
> Double check to see if you can slip on soap and also see if you can still block using shields in the middle of doorways without it closing on you.


https://user-images.githubusercontent.com/46636558/236937558-a5453aef-627f-4fba-ba6c-c7f83ffe94e3.mp4

Yeah it works

2023-05-08 21:28 UTC, keronshb approved these changes
looks good to me

2023-05-08 21:28 UTC, DawBla commented
I know this solution is not perfect, if I understand it correctly, right now the doors get stopped by for example puddles because doors gets stopped by stuff that's intersecting their AABB by more than 20% to not crush it if the safety is on
Since doors AABB is 0.98x0.98=0.9604 and for example banana peels AABB is 0.4x0.4=0.16
Banana peel passes the check 0.16/0.9604<0.2
but Soap or Puddle has AABB 0.8x0.6=0.48 and 0.8x0.8=0.64 respectively and fails the <0.2 check

I tried fixing it using that, but I couldn't get it to work without creating too much spaghetti

Only weird behavior with this solution I've observed is that dead bodies stop blocking doors
But this happens because they toggle the PhysicsComponent.CanCollide from true on living/crit players to false on dead players
Not sure if that was the behavior before puddles broke doors, but it seems like it was intended and was bugged?


https://user-images.githubusercontent.com/46636558/236939134-7c6ad838-48c9-43ba-a54e-95729bc30be8.mp4

2023-05-08 23:43 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Specific/Janitorial/soap.yml
> +        hard: false
Won't soap go through walls?

2023-05-09 07:33 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Specific/Janitorial/soap.yml
> +        hard: false
Okay I checked and it does so the soap solution needs rethinking.

2023-05-09 15:18 UTC, metalgearsloth requested changes

2023-05-09 15:18 UTC, metalgearsloth commented on Content.Shared/Doors/Systems/SharedDoorSystem.cs
> +                continue;
Please use the enums and just cast it to an int.

2023-05-09 23:54 UTC, metalgearsloth commented on Content.Shared/Doors/Systems/SharedDoorSystem.cs
> +
This is still extremely mid but I'll fix it later.

2023-05-09 23:54 UTC, metalgearsloth approved these changes

2023-05-09 23:54 UTC, merged