Allow PKA to gather
space-wizards/space-station-14 pull request #16250
Opened 2023-05-08 14:19 UTC by metalgearsloth

No whitelist or anything as afaik it's only rocks and trees so.

https://user-images.githubusercontent.com/31366439/236848483-830e3559-1967-4208-a79f-e0c503912875.mp4

:cl:
- add: PKA bullets can now destroy gatherable materials such as rocks or trees.

2023-05-08 19:50 UTC, brainfood1183 commented
wont this make drills obsolete?

2023-05-09 01:01 UTC, deltanedas commented
yeah it should probably be a pka module/whatever its called in the future but that doesnt exist so

2023-05-09 01:02 UTC, metalgearsloth commented
> wont this make drills obsolete?

if it does then drills need a buff as they work like this in 13.

2023-05-10 19:44 UTC, DrSmugleaf approved these changes

2023-05-10 19:47 UTC, DrSmugleaf requested changes

2023-05-10 19:47 UTC, DrSmugleaf commented on Content.Server/Gatherable/GatherableSystem.cs
> +                if (!_tagSystem.HasTag(uid, tag))
Shouldn't this be a different uid passed into this method? uid is the equivalent of args.Args.Used before, not args.Args.Target.Value which is what this is now.

2023-05-11 13:19 UTC, merged