Monkeys are no longer ghost roles
space-wizards/space-station-14 pull request #16363
Opened 2023-05-12 16:44 UTC by GoodWheatley

## About the PR

This right now is effectively a free respawn for players, and no amount of clumsy is going to change that. If you want a sentient monkey, give it cognizine.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- remove: Regular monkeys are no longer available for ghosts to control.

2023-05-12 16:48 UTC, deltanedas commented
not to mention on lrp the amount of shitters taking it as a free self antag role

2023-05-12 20:33 UTC, KaiShibaa commented
History has repeated itself

2023-05-12 20:59 UTC, GoodWheatley commented
PR updated

2023-05-13 03:07 UTC, metalgearsloth commented
Shouldn't you just map fewer monkeys or nerf them? Probability ghost roles are cringe.

2023-05-13 05:45 UTC, Emisse commented
i love monky

2023-05-16 10:04 UTC, 0x6273 requested changes

2023-05-16 10:04 UTC, 0x6273 commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +      path: /Audio/Animals/monkey_scream.ogg
You messed up formatting. Revert this line the way it was.

2023-05-19 07:00 UTC, metalgearsloth commented
fuck it

2023-05-19 07:00 UTC, merged