Add tether gun
space-wizards/space-station-14 pull request #16430
Opened 2023-05-14 14:07 UTC by metalgearsloth

Off-brand gravity gun.

https://github.com/space-wizards/space-station-14/assets/31366439/245fb4f9-d137-4728-910a-011b11afb324

Still needs a lot of polishing but it generally works atm.

:cl:
- add: Added a tether gun for science.

2023-05-14 14:09 UTC, deltanedas commented
does this attach to portals

2023-05-14 14:12 UTC, metalgearsloth commented
> does this attach to portals

No. Only dynamic or anchored bodies if admin (portals are static but not anchored).

2023-05-14 14:14 UTC, deltanedas requested changes

2023-05-14 14:14 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml
> +  description: Manipulates gravity around object to fling them at high velocities.
objects

2023-05-14 14:14 UTC, deltanedas commented on Resources/Textures/Objects/Weapons/Guns/Launchers/tether_gun.rsi/meta.json
> +	"version": 1,
this files indent looks hyper sus

2023-05-17 13:37 UTC, metalgearsloth commented
beaby for bebiew

2023-05-17 14:09 UTC, EmoGarbage404 commented
Add it to RND, coward

2023-05-17 14:32 UTC, OttoMaticode commented
A fellow shipbreaker, I see

2023-05-17 18:08 UTC, crazybrain23 commented
> 

At the very least, add it to the recipes but with no unlock, make it a tech disk gamble only.

2023-05-17 18:19 UTC, EmoGarbage404 commented
> At the very least, add it to the recipes but with no unlock, make it a tech disk gamble only.

Nah just chuck it in T2 experimental

2023-05-17 19:23 UTC, Emisse approved these changes

2023-05-18 01:36 UTC, merged