[Sprites] guitar back and some resprites
space-wizards/space-station-14 pull request #16611
Opened 2023-05-19 14:16 UTC by lzk228

## About the PR

welding masks icon repsrites
acoustic guitar backpack sprite
health analyzer icon resprite
fixed guitar inhand sprites

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: lzk
- tweak: Changed sprites

2023-05-28 03:29 UTC, OctoRocket commented
It is missing screenshots

2023-05-28 06:57 UTC, metalgearsloth requested changes

2023-05-28 06:57 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        - GasAnalyzer
These are components

2023-05-28 07:41 UTC, lzk228 commented
shit... branches somehow merged together

2023-05-30 17:43 UTC, AJCM-git submitted a review, later dismissed
Update the copyright in the ones you modified

2023-05-30 22:39 UTC, lzk228 commented
health analyzer meta was not updated in #16125, so i dont think that should be updated here

2023-06-15 11:55 UTC, merged