Dewarns access
space-wizards/space-station-14 pull request #16666
Opened 2023-05-21 08:52 UTC by TemporalOroboros

## About the PR

Fixes all warnings in the Access module.
Also fixes a bunch of component.Owner accesses because I had to ECS BUIs to get all of them.
Requires <https://github.com/space-wizards/RobustToolbox/pull/4079#issue-1718421710>
Not a draft only because I need to run tests to figure out what broke and this is faster than repeatedly crashing the debugger.

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

2023-07-19 05:34 UTC, TemporalOroboros commented on Content.Server/Administration/Systems/AdminVerbSystem.Tools.cs
> +#pragma warning disable CA1069
I had to disable a lot of "independent asserts should be grouped in an 'Assert.Multiple'" warnings when I went through the unit tests. (The linter didn't recognise that wrapping an assert around a TryGetComp and having it immediately followed by an assert on the resulting component made them interdependent.) In this case the comments claim that they have the same value for a reason and I haven't looked hard enough to dispute that.

2023-07-19 05:34 UTC, TemporalOroboros commented on Content.Server/Administration/Systems/AdminVerbSystem.Tools.cs
> +        newMix.SetMoles(gasType, (1000.0f * mixSize) / (Atmospherics.R * Atmospherics.T20C)); // Fill the tank to 1000KPA. // TODO: Sort out linter warnings.
The warning this refers to is specific to vscode. For some reason it lints for "excessive parentheses". It wants me to get rid of the parentheses in the numerator, but that's probably less clear.

2023-07-19 05:35 UTC, TemporalOroboros commented on Content.Server/Administration/Systems/AdminVerbSystem.Tools.cs
> +        newMix.SetMoles(gasType, (1000.0f * mixSize) / (Atmospherics.R * Atmospherics.T20C)); // Fill the tank to 1000KPA. // TODO: Sort out linter warnings.
I could probably poke around the .vscode file and disable it everywhere, but that should probably be its own thing.

2023-07-19 06:14 UTC, TemporalOroboros commented on Content.Server/Administration/Systems/AdminVerbSystem.Tools.cs
> +#pragma warning disable CA1069
InvokeVerb has always used the name so I don't know why these are separate.

2023-07-23 04:19 UTC, metalgearsloth requested changes

2023-07-23 04:19 UTC, metalgearsloth commented on Content.Shared/Access/Systems/AccessReaderSystem.cs
> +
EntitySystems already have these now.

2023-07-23 04:19 UTC, metalgearsloth commented on Content.Shared/Access/Systems/AccessReaderSystem.cs
>          }
This should just be a test instead of doing it at runtime.

2023-07-23 04:19 UTC, metalgearsloth approved these changes

2023-07-23 04:19 UTC, merged