Makes ghetto chemistry possible
space-wizards/space-station-14 pull request #16679
Opened 2023-05-21 21:55 UTC by Wissensbegierde

## About the PR

closes:https://github.com/space-wizards/space-station-14/issues/15905

- [x] You can use Welders to heat reagents inside of beakers

https://github.com/space-wizards/space-station-14/assets/120598766/fc88ba5e-d19f-4332-94e2-1c51942e0cd0

- [x] You can use Fire Extinguishers to cool reagents inside of beakers

https://github.com/space-wizards/space-station-14/assets/120598766/f9cc530d-de7b-4042-a1cb-0a299f6440f7

- [ ] You can use mortar and pestle to grind items into reagents

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Ghetto Chemistry is possible now

2023-05-21 22:23 UTC, 0x6273 commented
> You can use mortar and pestle to grind items into reagents

That should be a separate PR.

2023-05-22 03:48 UTC, moonheart08 commented
> > You can use mortar and pestle to grind items into reagents
> 
> That should be a separate PR.

nah its fine

2023-05-27 12:15 UTC, Wissensbegierde commented
> > > You can use mortar and pestle to grind items into reagents
> > 
> > 
> > That should be a separate PR.
> 
> nah its fine

I think imma do it on a later PR after all

2023-05-27 13:53 UTC, 0x6273 commented
This has lots of formatting issues. No newlines between functions, too many newlines, and wrong indentation in some places.

2023-05-27 18:49 UTC, Wissensbegierde commented
> 

I forgot to use Jetbrainer

2023-05-28 16:30 UTC, Wissensbegierde commented
> This has lots of formatting issues. No newlines between functions, too many newlines, and wrong indentation in some places.

its done, anything else missing

2023-05-28 17:57 UTC, Wissensbegierde commented on Content.Server/Extinguisher/Systems/CoolableSystem.cs
> +namespace Content.Server.Extinguisher.Systems
> Use file-scoped namespace for new files

ok done

2023-06-03 19:18 UTC, mirrorcult commented
extinguisher/welder interactions need to be more discoverable, ideally examine text on the items themselves

2023-06-04 13:44 UTC, Wissensbegierde commented
> extinguisher/welder interactions need to be more discoverable, ideally examine text on the items themselves

ok done
![grafik](https://github.com/space-wizards/space-station-14/assets/120598766/7b0eb5c6-2cd1-4b18-ad00-5ccec4723637)

2023-06-04 13:50 UTC, lzk228 commented
so many text

2023-06-04 15:04 UTC, Wissensbegierde commented
> extinguisher/welder interactions need to be more discoverable, ideally examine text on the items themselves

nevermind i put the messages on the item themselves

![grafik](https://github.com/space-wizards/space-station-14/assets/120598766/44f5fa17-21f0-42ab-a7e3-51d619e5cf62)


![grafik](https://github.com/space-wizards/space-station-14/assets/120598766/de5b6d1e-51c0-4df6-8137-abf2ac660552)

2023-06-09 01:18 UTC, 0x6273 reviewed
I don't think extinguisher should have a doafter. It should work by using it normally and either cool or heat the beaker based on the temperature of the solution in the extinguisher.

2023-06-09 01:21 UTC, 0x6273 commented on Content.Server/Extinguisher/Components/CoolableComponent.cs
> +///     Allows users to weld/unweld doors, crates and lockers.
Also the summary of the comp you copy-pasted this from should probably be updated now that it's also used for heating beakers.

2023-06-09 21:24 UTC, Wissensbegierde commented
> 

I would need the opinion of a maintainer

2023-06-09 21:25 UTC, Wissensbegierde commented
> I don't think extinguisher should have a doafter. It should work by using it normally and either cool or heat the beaker based on the temperature of the solution in the extinguisher.

I would need the opinion of a maintainer

2023-06-16 00:13 UTC, AJCM-git commented
> > I don't think extinguisher should have a doafter. It should work by using it normally and either cool or heat the beaker based on the temperature of the solution in the extinguisher.
> 
> I would need the opinion of a maintainer

I think the do after is fine to keep it consistent with the welder

2023-06-18 21:56 UTC, Wissensbegierde commented on Content.Server/Tools/ToolSystem.Welder.cs
> +            if(args.Target != null)
done

2023-06-18 21:56 UTC, Wissensbegierde commented on Content.Server/Extinguisher/Components/CoolableComponent.cs
> +///     Allows users to weld/unweld doors, crates and lockers.
done

2023-06-18 21:57 UTC, Wissensbegierde commented on Content.Server/Chemistry/EntitySystems/SolutionContainerSystem.cs
> +    #region GhettoChemistry
done

2023-06-18 21:58 UTC, Wissensbegierde commented on Content.Server/Chemistry/EntitySystems/SolutionContainerSystem.cs
> +    #region GhettoChemistry
> Could this go in its own system instead of adding to SolutionContainerSystem?

done

2023-06-26 23:54 UTC, AJCM-git requested changes
There is a lot of copy pasted code from welders, the proper way to implement this would be to add a new "Cooling" `ToolQuality` prototype and rename the "Welding" one to "Heating" (or merge both into one, im not sure on this yet). Then make a new "TemperatureChanger" component/system (name due to change) that subscribes to the ToolDoAfterEvent use AddThermalEnergy there, then finally add that component (and tool component (with the proper fields set)) to the fire extinguisher (obviously add it to the welder too and remove duplicated code). Do ask any question (either here or in discord)

2023-07-15 03:24 UTC, AJCM-git commented
@Wissensbegierde You coming back to this?

2023-07-15 06:31 UTC, deltanedas commented
dibs if abandoned :trollface:

2023-07-16 07:19 UTC, Wissensbegierde commented
> @Wissensbegierde You coming back to this?

I am on it

2023-07-22 16:48 UTC, keronshb commented
@Wissensbegierde  Fix conflicts and any remaining reviews and I'll review this weekend if it's done, otherwise sometime 1st week of August.

2023-08-01 01:08 UTC, Caelumrobocop commented
ill do it
ghetto chem coming to a town near you

2023-08-10 19:01 UTC, AJCM-git commented
re-open once you come back to this

2023-08-10 19:01 UTC, closed without merging