Make ghost role Accept dialog much friendlier
space-wizards/space-station-14 pull request #16797
Opened 2023-05-25 02:59 UTC by tom-leys

## About the PR
- Automatically shift to same-named ghost role if the old one goes away
- If you fail to land the role, the next one (with same rules) does not require another dialog
- 
**Media**

https://github.com/space-wizards/space-station-14/assets/5285589/9e25d977-7a20-40a1-819e-7bf2d1ce96e9

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: As a ghost, it's easier to pick a ghost role. The rules dialog auto-finds any role for you with the same name. If it can't, "Accept for next role" will skip the dialog for any next role you pick with the same rules.

2023-06-15 11:05 UTC, metalgearsloth requested changes

2023-06-15 11:05 UTC, metalgearsloth commented on Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRoleRulesWindow.xaml.cs
> +                    : "ghost-roles-window-request-role-button-timer";
pascalCase please.

2023-06-15 11:05 UTC, metalgearsloth commented on Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRoleRulesWindow.xaml.cs
> +                RequestButton.Text = Loc.GetString(button_str);
.

2023-06-15 11:05 UTC, metalgearsloth commented on Resources/Locale/en-US/ghost/ghost-gui.ftl
> +ghost-roles-window-request-role-button-timer-gone = Agree for next ({$time}s)
This should specify that it is a random ghost role being picked.

2023-06-15 11:05 UTC, metalgearsloth commented on Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRolesEui.cs
>              }
This needs to disclose when failure occurs as someone might mash the button if it takes more than a second due to ping or the ghost role legitimately being taken already.

2023-07-22 01:00 UTC, tom-leys commented
Feel free to reuse my code if you want to contribute with it yourself.

2023-07-22 01:00 UTC, closed without merging