Chemistry goggles
space-wizards/space-station-14 pull request #16835
Opened 2023-05-26 19:43 UTC by icesickleone

## About the PR

"Science" goggles from /tg/, tells you exactly what and how much of each reagent is inside a container.

**Media**

![image](https://github.com/space-wizards/space-station-14/assets/132941221/5c4301a2-f09f-40c1-83cb-22ab7a4ebd06)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: NT has finally provided chemists with proper eye-protection - goggles that can scan the reagents inside any container!

2023-05-26 19:46 UTC, GoodWheatley commented
This feels like it should be a RD/science thing rather than chemist equipment

2023-05-26 19:47 UTC, mirrorcult commented
this should be in an examine menu and not tacked on to the base examine

2023-05-26 19:50 UTC, GoodWheatley commented
> this should be in an examine menu and not tacked on to the base examine

Don’t agree with this, having to click on those buttons is super clunky.

2023-05-26 19:50 UTC, mirrorcult commented
ok too bad

2023-05-26 19:50 UTC, GoodWheatley commented
> ok too bad

:despair:

2023-05-26 20:00 UTC, asperger-sind commented
> ok too bad

it really is clunky clicking on the examine buttons, also base examine makes me happy when i look at the colors

2023-05-26 20:04 UTC, mirrorcult commented
an examine menu would also have colors

2023-06-02 01:06 UTC, ElectroJr requested changes
I agree that it should be a detailed examine verb, examining things with solutions already dumps a bunch of text into the examine box.

2023-06-02 01:06 UTC, ElectroJr commented on Content.Server/Chemistry/EntitySystems/SolutionContainerSystem.cs
> +        }
Raise an event directed at the entity, instead of checking for a specific component in a specific slot.

2023-06-28 03:17 UTC, AJCM-git commented
@icesickleone you coming back to this?

2023-07-16 13:19 UTC, closed without merging