Soap holoprojector for clown
space-wizards/space-station-14 pull request #16927
Opened 2023-05-29 08:42 UTC by lzk228

## About the PR

add holoprojector for clown, that create soap projections

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added new holoprojector for clown!

2023-05-29 08:59 UTC, ficcialfaint commented
The copyright field in `meta.json`s should be either a commit link or a permalink.
Also something weird with your tabulation in meta's

2023-05-31 08:20 UTC, Kit0vras commented on Resources/Prototypes/Entities/Structures/Holographic/projections.yml
it's just a projection without any functionality, so it doesn't make sense.
add slippery and fixtures (to make slippery work)

2023-05-31 08:23 UTC, Kit0vras commented
> it will also be good if you add at least a small screenshot or video for clarity of the added

2023-05-31 08:53 UTC, lzk228 commented
> it will also be good if you add at least a small screenshot or video for clarity of the added

Unfortunately, i cant

2023-06-02 15:17 UTC, brainfood1183 commented
Looks good, how will the clown get their hands on the holosoap? Is it to be added to theatre? random loot in maints or research based?

2023-06-02 15:32 UTC, lzk228 commented
> Looks good, how will the clown get their hands on the holosoap? Is it to be added to theatre? random loot in maints or research based?

i changed clown startgear

2023-06-02 15:36 UTC, EmoGarbage404 commented
honestly the clown gear slide is real. They now start with a horn, laughter machine, and an infinite soap machine. Some of it should be shoved in a vendor, crate, or sci unlock.

2023-06-02 16:30 UTC, brainfood1183 commented
> honestly the clown gear slide is real. They now start with a horn, laughter machine, and an infinite soap machine. Some of it should be shoved in a vendor, crate, or sci unlock.

I have a toy box crate pr that pjb approved for merging. It adds a toybox and some new toys. I guess the recorder could be moved to it.

2023-06-02 19:03 UTC, deltanedas commented
would actually be very powerful for cleaning blood of clothes wsci

2023-06-16 00:08 UTC, AJCM-git requested changes
Move this to a tech or something, also this needs a new "RemovePreviousProjection" bool datafield to HolosignProjectorComponent that removes the previous projection that is false by default, then set it to true for this for.

2023-06-16 05:09 UTC, lzk228 commented
omg

2023-06-16 05:09 UTC, closed without merging