add an event to prevent gun shooting
space-wizards/space-station-14 pull request #17104
Opened 2023-06-03 21:57 UTC by deltanedas

## About the PR
sloth silently removed GunsDisabled tag when adding crusher (sabotaging ninja!!!!??!) so this adds it back in a better form
this pr adds ShotAttemptedEvent which can be cancelled if you dont want a gun to and makes crusher's cooldown thing use this event

crusher and glaive still work as expected

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

2023-06-04 10:49 UTC, metalgearsloth requested changes

2023-06-04 10:49 UTC, metalgearsloth commented on Content.Shared/Weapons/Ranged/Events/ShotAttemptedEvent.cs
> +public sealed class ShotAttemptedEvent : CancellableEntityEventArgs
raised by ref + record struct fam.

2023-06-04 11:52 UTC, deltanedas commented on Content.Shared/Weapons/Ranged/Events/ShotAttemptedEvent.cs
> +public sealed class ShotAttemptedEvent : CancellableEntityEventArgs
then cant inherit cancellable, make custom field?

2023-06-08 02:15 UTC, metalgearsloth approved these changes

2023-06-08 02:15 UTC, merged