Disposal routing
space-wizards/space-station-14 pull request #1710
Opened 2020-08-16 11:46 UTC by juliangiebel

I added a disposal router and tagger.

The tagger adds a tag to the `DisposalHolderComponent` when it flows through and the router compares those tags to it's own and if at least one of them match it routes the holder to the side.

Disposable Mailing [#1662] could be done by making a device that's a mix of the pipe tagger and the bin.

This can later be expanded by, for example, adding a pipe that adds tags depending on the entities being transported in the disposal holder.

This is my first time adding a component or doing stuff with the user interface.

2020-08-18 13:00 UTC, DrSmugleaf commented on Content.Server/GameObjects/Components/Disposal/DisposalRouterComponent.cs
> +            _userInterface.OnReceiveMessage += OnUiReceiveMessage;
`.CloseAll()` needs to be called on `_userInterface` in this component's OnRemove method.

2020-08-18 13:02 UTC, DrSmugleaf commented on Content.Server/GameObjects/Components/Disposal/DisposalTaggerComponent.cs
> +            _userInterface.OnReceiveMessage += OnUiReceiveMessage;
`.CloseAll()` needs to be called on `_userInterface` in this component's `OnRemove` method.

2020-08-18 13:02 UTC, DrSmugleaf commented on Content.Server/GameObjects/Components/Disposal/DisposalTaggerComponent.cs
> +                    _localizationManager.GetString("You have no hands."));
You can use the static ´Loc´ here as well instead of _localizationManager and remove the dependency.

2020-08-18 13:03 UTC, DrSmugleaf commented on Content.Shared/GameObjects/Components/Disposal/SharedDisposalRouterComponent.cs
> +            public readonly string Tags = "";
This should probably have a length limit imposed on it to prevent the user from inputting a giant regex string.

2020-08-19 10:06 UTC, DrSmugleaf requested changes

2020-08-19 10:06 UTC, DrSmugleaf commented on Content.Server/GameObjects/Components/Disposal/DisposalRouterComponent.cs
> +            _userInterface.CloseAll();
OnRemove is a special case and `base.OnRemove()` must be called at the end of the overriding method.

```suggestion
            _userInterface.CloseAll();
            base.OnRemove();
```

2020-08-19 13:44 UTC, DrSmugleaf approved these changes

2020-08-19 13:50 UTC, merged

2020-08-19 14:05 UTC, PJB3005 commented on Content.Client/GameObjects/Components/Disposal/DisposalRouterWindow.cs
> +                            (TagInput = new LineEdit {SizeFlagsHorizontal = SizeFlags.Expand, CustomMinimumSize = (320, 0),
I feel the need to point out that hitting enter in this `LineEdit` should probably confirm. And also there's no feedback for when you confirm AFAICT?

2020-08-19 14:05 UTC, PJB3005 commented on Content.Client/GameObjects/Components/Disposal/DisposalTaggerWindow.cs
> +            _tagRegex = new Regex("^[a-zA-Z0-9 ]*$", RegexOptions.Compiled);
Again, `private static readonly` this.

2020-08-19 14:06 UTC, PJB3005 commented on Content.Server/GameObjects/Components/Disposal/DisposalRouterComponent.cs
> +                foreach (var tag in msg.Tags.Split(',', StringSplitOptions.RemoveEmptyEntries))
Oh also you're only verifying that these tags sent from the client are indeed valid which is very bad.

2020-08-19 14:38 UTC, DrSmugleaf commented on Content.Shared/GameObjects/Components/Disposal/SharedDisposalTaggerComponent.cs
> +            public readonly string Tag = "";
This also needs a character limit.