make mice not eat uranium and pills
space-wizards/space-station-14 pull request #17110
Opened 2023-06-04 00:43 UTC by deltanedas

## About the PR
fixes #16149 by adding BadFood marker component and gives it to uranium and pill items
ai will ignore food with BadFood

afaik no ore is edible so ore wasnt an issue, material sheets (uranium) were

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- fix: CentCom's Ministry Of Knowledge has trained station mice to stop eating uranium.

2023-06-04 00:56 UTC, malchanceux commented
Mice squad pulling up to salvage to eat the entire shift's supply of bananium:

2023-06-04 15:22 UTC, GoodWheatley commented
Mice eating pills is funny leave that in

2023-06-04 15:24 UTC, deltanedas commented
downside of that is you can do mouse genocide by putting radium 20u pills at every mouse spawn so they instantly suicide

2023-06-04 15:24 UTC, metalgearsloth commented
Just remove food from bananium and uranium tbh.

Sometimes mice are used to deter chemistry from entityspam so might need to talk about that one.

2023-06-04 15:25 UTC, GoodWheatley commented
> downside of that is you can do mouse genocide by putting radium 20u pills at every mouse spawn so they instantly suicide

I’m 70% sure that spawncamping mice like that breaks powergaming/metagaming rules

2023-06-04 15:34 UTC, Equivocateur commented
> Just remove food from bananium

Its called bananium for a reason

2023-06-04 23:58 UTC, SentryPrimies commented
literally 1984

2023-06-05 00:26 UTC, deltanedas commented
> Sometimes mice are used to deter chemistry from entityspam so might need to talk about that one.

would suffix: Admeme mouse that ignores BadFood be ok for this fun activity

2023-06-07 14:27 UTC, metalgearsloth commented
> > Sometimes mice are used to deter chemistry from entityspam so might need to talk about that one.
> 
> would suffix: Admeme mouse that ignores BadFood be ok for this fun activity

uhhhh sure though the pills one I'm still suss on.

2023-06-07 15:44 UTC, deltanedas commented
@metalgearsloth admeme mouse that ignores bad food added, also despawns after a minute so you dont need to clean them up manually

2023-06-07 19:39 UTC, mirrorcult requested changes

2023-06-07 19:39 UTC, mirrorcult commented on Content.Server/NPC/Systems/NPCUtilitySystem.cs
> +        var avoidBadFood = HasComp<IgnoreBadFoodComponent>(owner);
this dont build

2023-06-15 12:34 UTC, metalgearsloth approved these changes

2023-06-15 12:34 UTC, metalgearsloth commented on Content.Server/Nutrition/Components/IgnoreBadFoodComponent.cs
> +/// This component allows ai mobs to eat food with BadFoodComponent.
```suggestion
/// This component allows NPC mobs to eat food with BadFoodComponent.
```

2023-06-15 12:35 UTC, merged