Improve paper stamping experience
space-wizards/space-station-14 pull request #17135
Opened 2023-06-05 10:49 UTC by eoineoineoin

## About the PR

Improves the UIs for paper with stamps. Stamps are more visually interesting; each paper will lay out the stamps slightly differently and overlaps them, which is more akin to real-world bureaucracy, although does hurt legibility if a paper has been stamped many times - not sure if this is really a concern, as stamp names also show up in the item description.

Stamps themselves can now define an ink colour to customize how they appear in the UI. I based this color off the stamp sprite, but made some modifications to ones which were too low-contrast with most paper. Stamps also have some procedural noise, to make them more stamp-like.

https://github.com/space-wizards/space-station-14/assets/1676295/bf3739b9-9426-445a-bd17-2846fcb47fe3

The text in stamps now rescales to fit the allowed space, which was previously causing overflow with long stamp names.

https://github.com/space-wizards/space-station-14/assets/1676295/91630b9d-7764-4e19-b232-c25702152c10

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Cripes
- tweak: Stamps have been refilled with new ink.

2023-06-07 14:26 UTC, metalgearsloth requested changes

2023-06-07 14:26 UTC, metalgearsloth commented on Content.Client/Paper/UI/StampLabel.xaml.cs
> +            handle.UseShader(null);
Transform too.

2023-06-07 14:26 UTC, metalgearsloth commented on Content.Client/Paper/UI/StampWidget.xaml.cs
> +        }
This formatting, it hurts. Just use =>

2023-06-07 14:26 UTC, metalgearsloth commented on Content.Client/Paper/UI/StampWidget.xaml.cs
> +            var prototypes = IoCManager.Resolve<IPrototypeManager>();
Get IPrototypeManager in the constructor rather than resolving it every draw.

2023-06-07 14:26 UTC, metalgearsloth commented on Content.Client/Paper/UI/StampWidget.xaml.cs
> +            handle.UseShader(null);
Same here on transform.

2023-06-07 14:26 UTC, metalgearsloth commented on Content.Shared/Paper/StampComponent.cs
> +        public Color StampedColor { get; set; } = Color.FromHex("#BB3232"); // StyleNano.DangerousRedFore
```suggestion
        public Color StampedColor = Color.FromHex("#BB3232"); // StyleNano.DangerousRedFore
```

2023-07-16 13:25 UTC, metalgearsloth commented
@eoineoineoin conflicts need resolving.

2023-08-01 14:19 UTC, Slava0135 commented
![Screenshot_2023-08-01_17-11-14](https://github.com/space-wizards/space-station-14/assets/40753025/7350181a-38e4-4706-9626-087ef92bf8a7)
you can't change stamp color when using admin fax? you can select the stamp but it does nothing i guess

2023-08-03 17:02 UTC, eoineoineoin commented
Have added a colour selector to the admin fax window:
![2023-08-03_17-55](https://github.com/space-wizards/space-station-14/assets/1676295/f03104a6-bcce-4a9c-b5fe-32b8e24abe60)

2023-08-03 17:03 UTC, Slava0135 commented
> Have added a colour selector to the admin fax window: ![2023-08-03_17-55](https://user-images.githubusercontent.com/1676295/258183857-f03104a6-bcce-4a9c-b5fe-32b8e24abe60.png)

cool but stamp icon does nothing?

2023-08-03 17:18 UTC, eoineoineoin commented
It does. It changes the display of the paper:

![2023-08-03_18-16](https://github.com/space-wizards/space-station-14/assets/1676295/c6a52b05-2a7a-49fc-927b-7bcb2c5939a5)

(That functionality was already there; I didn't touch it in this PR)

2023-08-03 17:19 UTC, Slava0135 commented
ah i see now

2023-08-04 03:20 UTC, metalgearsloth commented
Fix tests

2023-08-06 12:36 UTC, eoineoineoin commented
I've fixed the test, but needed to modify a map which had a serialized stamp with the old data layout (without colour info for the stamp); is there something I should do to version old data automatically?

2023-08-10 22:59 UTC, AJCM-git requested changes
file scope your namespaces and this is pretty much done

2023-08-10 22:59 UTC, AJCM-git commented on Content.Server/Paper/PaperSystem.cs
fyi you can use `THE` ftl function instead of calling identity here

2023-08-13 18:16 UTC, AJCM-git approved these changes

2023-08-13 18:28 UTC, merged