only show flavor above 0.1u
space-wizards/space-station-14 pull request #17169
Opened 2023-06-06 21:53 UTC by deltanedas

## About the PR
if a pill has say 0.01u carbon you could taste it
this pr fixes and only lets you taste it if its above 0.1u in the solution being ingested

**Media**
less than 0.1u sugar
![22:53:01](https://github.com/space-wizards/space-station-14/assets/39013340/ff4eb028-8693-46f6-8391-0ededa0986ba)
does not taste sweet!
![22:53:07](https://github.com/space-wizards/space-station-14/assets/39013340/fbf57fab-8bbd-446b-aef0-7e3f4a731081)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

2023-06-06 21:55 UTC, EmoGarbage404 commented
Can this be configurable so that certain flavors have a higher or lower threshold for being noticed? Something like oil should be immediately tasted whereas some other flavors might be more subtle.

2023-06-06 22:03 UTC, deltanedas commented
ok ill add thing to reagent prototype

2023-06-07 01:58 UTC, metalgearsloth requested changes

2023-06-07 01:58 UTC, metalgearsloth commented on Content.Server/Nutrition/EntitySystems/FlavorProfileSystem.cs
>          flavors.UnionWith(flavorProfile.Flavors);
Can you pass the hashset into the ctor or is that just lists? At a minimum should initialize the capacity. to flavorProfile.Flavors.Count.

2023-06-07 01:58 UTC, metalgearsloth commented on Content.Shared/Chemistry/Reagent/ReagentPrototype.cs
> +        public float FlavorMinimum = 0.1f;
Should this be fixedpoint2?

2023-06-07 03:03 UTC, deltanedas commented on Content.Shared/Chemistry/Reagent/ReagentPrototype.cs
> +        public float FlavorMinimum = 0.1f;
probably

2023-06-07 04:29 UTC, metalgearsloth approved these changes

2023-06-07 04:29 UTC, merged