Core: NEW station map
space-wizards/space-station-14 pull request #17269
Opened 2023-06-11 10:28 UTC by UbaserB

## About the PR

Nanotrasen has introduced a new station into the ranks! Core is a 40-70 medium population map featuring a singularity in the center along with an off-branching arrivals area and a singular solar panel array.

**Station-exclusive jobs include:**
- Boxer
- Zookeeper
- Reporter

The evacuation shuttle used here is Rod, which is on another unapproved PR right now where the map Marathon needs to be tweaked by Emisse.

**P.S.** Before merging I would like a considerable amount of playtesting and player feedback from not just maintainers.
(these are the main points to be covered)
- singularity
- job spawns
- power
- firelocks and spacing
- fax
- air alarms/sensors
- atmos
- cameras
- telecommunications
- disposals
- artifact room
- warp points as ghost

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![Core-0](https://github.com/space-wizards/space-station-14/assets/134914314/cd0faa26-1648-40ea-a5c5-b335e2d15d80)

**Changelog**

:cl: Ubaser
- add: Nanotrasen has hired a group of architects to change up their selection with the introduction of the new space station, Core!

2023-06-11 10:33 UTC, forgotmyotheraccount commented
What happens when Arrivals runs out of EVA suits?

2023-06-11 10:35 UTC, UbaserB commented
> What happens when Arrivals runs out of EVA suits?

i might add a small disposals section for people so they can return the suits to arrivals. Otherwise, just run through space you'll live :)

2023-06-11 10:59 UTC, lzk228 commented
goofy ahh arrivals

2023-06-11 15:20 UTC, deltanedas commented
the singulo window grilles arent shocked so singuloose will be ridiculously easy

2023-06-11 16:28 UTC, Cheackraze commented
A few things from a very brief look over:

That arrivals is unique but isn't going to work.  New players especially will be confused and punished by the forced spacewalk, etc.
The solar array is massive and boring, should split it into multiples and make them more interesting
Serious lack of maints: med and sci especially have none, and the maints that do exist are straight, narrow, and empty
Station specific jobs: these are *station specific*, meaning intended for their specific stations.

Looks like you've put in a good effort for it though so I can do a more in depth review when it's ready

2023-06-11 16:33 UTC, EmoGarbage404 commented
this map has next to 0 maintenance of any kind, which is a major problem.

also, check is right about arrivals. neat concept, but you're really throwing new players to the wolves. Many people aren't going to be able to go spacewalk to the main station a few minutes after joining.

2023-06-11 16:46 UTC, Cheackraze commented
Also if you're including a custom evac shuttle, you should include the render of that as well since it will also need to be reviewed

2023-06-11 20:10 UTC, Emisse commented
reviewed minor things on discord, will do a more in depth design review later today or tomorrow after work
check cartography threads

2023-06-12 01:18 UTC, potato1234x commented
no robotics?

2023-06-12 01:56 UTC, Yousifb26 commented
Along with non electrified grills it doesn’t have plasma glass or shutters so you WILL die if you stay too long in maints with a singulose active. I suggest plasma glass to add a cool effect of being able to see a singulose from maints

2023-06-12 04:40 UTC, UbaserB commented
> Along with non electrified grills it doesn’t have plasma glass or shutters so you WILL die if you stay too long in maints with a singulose active. I suggest plasma glass to keep the cool effect of being able to see a singulose from maints

this is actually on purpose, i added a set of glass, plasma sheets and rods so that engineering can do it themselves :)

2023-06-12 04:44 UTC, UbaserB commented
> Also if you're including a custom evac shuttle, you should include the render of that as well since it will also need to be reviewed

i have a separate PR that should be accepted soon

2023-06-13 16:44 UTC, Cheackraze commented
> > Along with non electrified grills it doesn’t have plasma glass or shutters so you WILL die if you stay too long in maints with a singulose active. I suggest plasma glass to keep the cool effect of being able to see a singulose from maints
> 
> this is actually on purpose, i added a set of glass, plasma sheets and rods so that engineering can do it themselves :)

Radiation in its current implementation is really overly punishing, particularly since it is functionally undetectable unless you are an engineer.  It is incredibly frustrating for players who die to something they are not aware is even happening or not aware of what to do etc.  If radiation was better conveyed to players through like green glowy stuff or in some other way this wouldn't be an issue, but as it stands, you're just going to end up killing 1/4 of the crew every shift and the victims will probably not be very happy about it

2023-06-13 22:47 UTC, UbaserB commented
> > > Along with non electrified grills it doesn’t have plasma glass or shutters so you WILL die if you stay too long in maints with a singulose active. I suggest plasma glass to keep the cool effect of being able to see a singulose from maints
> > 
> > 
> > this is actually on purpose, i added a set of glass, plasma sheets and rods so that engineering can do it themselves :)
> 
> Radiation in its current implementation is really overly punishing, particularly since it is functionally undetectable unless you are an engineer. It is incredibly frustrating for players who die to something they are not aware is even happening or not aware of what to do etc. If radiation was better conveyed to players through like green glowy stuff or in some other way this wouldn't be an issue, but as it stands, you're just going to end up killing 1/4 of the crew every shift and the victims will probably not be very happy about it

Hm yeah that makes a lot of sense… i might add signs or something similar to warn anyone passing through

2023-07-12 22:37 UTC, UbaserB commented
Im having a stroke and the ghost conflict is not going away

2023-07-15 11:53 UTC, UbaserB commented
im confused i think i did something wrong

2023-07-15 11:53 UTC, UbaserB commented
i was simply trying to update my map guh

2023-07-15 11:54 UTC, UbaserB commented
i was simply trying to update my map, but im going to just reopen it real quickly

2023-07-15 11:57 UTC, UbaserB commented
i was simply trying to update the thing, still new to github. Reopening now

2023-07-18 23:12 UTC, Emisse requested changes

2023-07-18 23:12 UTC, Emisse commented on Resources/Prototypes/Maps/core.yml
> +            SecurityOfficer: [ 4, 6 ]
```suggestion
            SecurityOfficer: [ 4, 4 ]
```

2023-07-18 23:12 UTC, Emisse commented on Resources/Prototypes/Maps/core.yml
> +            StationEngineer: [ 3, 5 ]
```suggestion
            StationEngineer: [ 4, 4 ]
```

2023-07-18 23:12 UTC, Emisse commented on Resources/Prototypes/Maps/core.yml
> +            Mime: [ 1, 2 ]
```suggestion
            Mime: [ 1, 1 ]
```

2023-07-18 23:12 UTC, Emisse commented on Resources/Prototypes/Maps/core.yml
> +            Janitor: [ 1, 2 ]
```suggestion
            Janitor: [ 2, 2 ]
```

2023-07-18 23:12 UTC, Emisse commented on Resources/Prototypes/Maps/core.yml
> +            CargoTechnician: [ 2, 4 ]
```suggestion
            CargoTechnician: [ 3, 3 ]
```

2023-07-18 23:12 UTC, Emisse commented on Resources/Prototypes/Maps/core.yml
> +  minPlayers: 40
```suggestion
  minPlayers: 30
```

2023-07-18 23:12 UTC, Emisse commented on Resources/Prototypes/Maps/core.yml
> +  maxPlayers: 70
```suggestion
  maxPlayers: 60
```

2023-07-18 23:12 UTC, Emisse commented on Resources/Prototypes/Maps/core.yml
> +            AtmosphericTechnician: [ 3, 3 ]
```suggestion
            AtmosphericTechnician: [ 2, 2 ]
```

2023-07-18 23:12 UTC, Emisse commented on Resources/Prototypes/Maps/core.yml
> +            SalvageSpecialist: [ 3, 4 ]
```suggestion
            SalvageSpecialist: [ 3, 3 ]
```

2023-07-18 23:12 UTC, Emisse commented on Resources/Prototypes/Maps/core.yml
> +            Chaplain: [ 1, 2 ]
```suggestion
            Chaplain: [ 1, 1 ]
```

2023-07-19 06:11 UTC, Emisse approved these changes

2023-07-19 07:23 UTC, merged