use parts crates for rewards
space-wizards/space-station-14 pull request #17374
Opened 2023-06-16 07:52 UTC by deltanedas

## About the PR
fixes #17372

todo: ui

**Media**
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: When taking a mission you can now see what its rewards will be.

2023-06-16 10:58 UTC, metalgearsloth requested changes
Dump the loot bit.

2023-06-16 11:00 UTC, metalgearsloth requested changes

2023-06-16 11:00 UTC, metalgearsloth commented on Content.Server/Salvage/Expeditions/SalvageExpeditionComponent.cs
> +    public List<string> Rewards = default!;
Datafield + customtypeserializer.

2023-06-16 11:01 UTC, deltanedas commented
dump it entirely or in ui only

2023-06-16 11:02 UTC, metalgearsloth commented
both if possible

2023-06-16 22:52 UTC, deltanedas commented
i think the rest of the stuff in C.Sh.Procedural.Loot is needed for ores so i left it in

2023-06-17 02:00 UTC, metalgearsloth approved these changes

2023-06-17 02:00 UTC, merged