add command to let admins send custom cargo orders
space-wizards/space-station-14 pull request #17379
Opened 2023-06-16 15:33 UTC by Chief-Engineer

## About the PR

Lets admins add custom cargo orders. As implemented, the order item is teleported onto the shuttle when it is delivered so it needs to be staged somewhere safe, like an admin testing area.

**Media**

![image](https://github.com/space-wizards/space-station-14/assets/119664036/8ba29cdb-0d78-47b1-add6-69f9a0611a29)
![image](https://github.com/space-wizards/space-station-14/assets/119664036/d32173ce-7491-47ec-8b71-6b0995906b50)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Admins can now send custom cargo orders.

2023-06-24 12:05 UTC, metalgearsloth commented on Content.Shared/Cargo/CargoOrderData.cs
> +
Adding a bunch of special-casing around this seems kinda weird to me.

2023-06-25 11:02 UTC, metalgearsloth commented on Content.Shared/Cargo/CargoOrderData.cs
> +
I think that's probably better yeah.

2023-08-10 20:51 UTC, AJCM-git requested changes
Looks mostly good

2023-08-10 20:51 UTC, AJCM-git commented on Content.Client/Cargo/UI/CargoConsoleMenu.xaml.cs
As far as i can tell the only difference between the null and not null parts of the main part of this are the `Icon` field, cant you use a ternary operator or something to make this a lot cleaner (or make the command always send a default icon or something)?

2023-08-10 20:51 UTC, AJCM-git commented on Content.Client/Cargo/UI/CargoShuttleMenu.xaml.cs
same

2023-08-10 20:51 UTC, AJCM-git commented on Content.Server/Administration/Commands/Station/AddCustomCargoOrder.cs
> +public sealed class AddCustomCargoOrder : LocalizedCommands
can you update this to the new `ToolshedCommand` API

2023-08-10 20:51 UTC, AJCM-git commented on Content.Server/Administration/Logs/Converters/CargoOrderDataStringRepresentationConverter.cs
> +            writer.WriteNumber("entityUid", value.EntityUid.Value.GetHashCode()); // How do I make this use EntityUidConverter.cs instead?
make a WriteEntityUid method? (if thats the problem, idk if thats your actual issue here)

2023-08-10 20:51 UTC, AJCM-git commented on Content.Shared/Cargo/Orders/CargoOrderDataEntity.cs
filescoped namespace

2023-08-16 01:39 UTC, moonheart08 commented
@Chief-Engineer i hate to do this to you but needs rewritten to use toolshed if you ever come back to it.

2023-08-16 01:39 UTC, closed without merging