Status Icons
space-wizards/space-station-14 pull request #17529
Opened 2023-06-21 15:06 UTC by EmoGarbage404

## About the PR

Sorry, sammy sonic rider.

Adds an implementation for status icons, little icons that display on characters to inform people of various stuff about them.
Usages range from antag identifiers to sechud to medhud to whatever the hell you could envision.

This PR includes the basis for a zombie icon but I'm waiting on Electro's faction system before I actually implement it.
For now, this is just a code-side implementation.

Courtesy to RamZ for the zombie icon.

**Media**

![image](https://github.com/space-wizards/space-station-14/assets/98561806/c25209ee-8b1c-4ce4-bccf-ce3cf1a51c91)
sprite size-based cutoffs (it stops rendering past a certain point) (debug and using incorrect icon ordering)

![image](https://github.com/space-wizards/space-station-14/assets/98561806/8ede2374-6b49-483d-8400-6ccf6bb35cd5)
multiple icons

![image](https://github.com/space-wizards/space-station-14/assets/98561806/ff2fdfcb-e06a-4e5a-a152-abee3d8a5235)
working on non-standard sprite sizes (offset)

![image](https://github.com/space-wizards/space-station-14/assets/98561806/eaa61aac-2009-4bbc-92bc-3442f344cb4f)
zombies

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl no fun

2023-06-21 15:10 UTC, Cheackraze commented
Could you make the system disable-able by cvar?

2023-06-21 15:16 UTC, EmoGarbage404 commented
> Could you make the system disable-able by cvar?

sure.

2023-06-21 15:18 UTC, Cheackraze commented
> > Could you make the system disable-able by cvar?
> 
> sure.

Thanks! A lot of people find the icons visually distracting and powergamey so im certain that they will eventually want a way to disable this easily.

2023-06-21 15:19 UTC, Cheackraze commented
Probably both. Clients for individual player preferences and server for balance reasons.

2023-06-21 15:20 UTC, AJCM-git commented
> should the option be for individual clients or for servers as a whole? Maybe have both?

Sounds a little pointless for individual clients as an option as that would just make the game more difficult for them individually, would be better off as an trait in that case

2023-06-21 15:32 UTC, EmoGarbage404 commented
implemented 2 cvars:
- local_status_icons_enabled: clientside cvar for toggling status icons. could be a menu option in the future or something
- global_status_icons_enabled: server configuration for whether or not status icons should render.

2023-06-26 01:10 UTC, metalgearsloth requested changes

2023-06-26 02:01 UTC, EmoGarbage404 commented on Content.Shared/StatusIcon/Components/StatusIconComponent.cs
> +}
can't do access because shared comp and clientside-only system

2023-06-27 19:38 UTC, EmoGarbage404 commented
added access and addressed all review. Should be gtg.

2023-06-28 00:28 UTC, AJCM-git approved these changes

2023-06-28 00:31 UTC, merged