Procgen asteroids for salvage magnet
space-wizards/space-station-14 pull request #17547
Opened 2023-06-22 04:00 UTC by EmoGarbage404

## About the PR

Uses moony's ~~incomprehensible~~ very epic system to add procgen asteroids for salvage.
The asteroids have a 60% chance to spawn in place of a conventional salvage map.

Additionally cleans up salvagesystem (not all the way)
Adjusts the salvage spawning algorithm to actually offset it from the magnet
reduces the range to compensate for this offset.
Adjusts the salvage algorithm to pick the map/asteroid first *then* pick the location.

**Media**

![image](https://github.com/space-wizards/space-station-14/assets/98561806/65299369-4f9f-43cd-93ba-636c8334eaa7)
![image](https://github.com/space-wizards/space-station-14/assets/98561806/e3eccb4f-e30e-426a-a0a2-1cd6be9c7f60)
![image](https://github.com/space-wizards/space-station-14/assets/98561806/06e1d85f-f508-4a3c-ac03-15b1d1473d84)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The salvage magnet can now pull in randomly generated asteroids stuffed with ores.
- fix: Salvages are much less likely to fail to be pulled in.

2023-06-22 04:09 UTC, metalgearsloth commented
Would be nice if these were a lot bigger and less dense.

2023-06-22 04:11 UTC, EmoGarbage404 commented
> Would be nice if these were a lot bigger and less dense.

![image](https://github.com/space-wizards/space-station-14/assets/98561806/eb3b12c9-71e3-4016-8a3d-e056043373bc)

i have it generating larger ones.

having them be less dense is fine but if there's no ore they're kinda uninteresting. I'll try increasing standard rock up to like 40% and see how that looks.

2023-06-22 04:18 UTC, EmoGarbage404 commented
![image](https://github.com/space-wizards/space-station-14/assets/98561806/01cb06fa-2ee6-4aba-965c-e61ea5582142)
![image](https://github.com/space-wizards/space-station-14/assets/98561806/25e0d80b-8f7d-48b8-86ab-eb1a643aa40e)
![image](https://github.com/space-wizards/space-station-14/assets/98561806/bf00f87e-eacf-493a-8a9c-4657f29aa1b9)
![image](https://github.com/space-wizards/space-station-14/assets/98561806/00d7dc6d-53c9-478a-9453-5060f38c85e4)
@metalgearsloth bigger shapes, less dense

2023-06-22 04:20 UTC, metalgearsloth commented
Should be at least like 30x30 with hollow bits but maybe I'm alone in feeling that they're tiny af.

2023-06-25 17:35 UTC, moonheart08 requested changes

2023-06-25 17:35 UTC, moonheart08 commented on Content.Server/Salvage/SalvageSystem.cs
> +                RaiseLocalEvent(ent, new LocalStructureLoadedEvent());
sus amogus
just make LocalityLoaderSystem always load the object if there is no world controller.

2023-06-25 17:50 UTC, moonheart08 approved these changes

2023-06-25 17:50 UTC, merged