digital ian cartridge game
space-wizards/space-station-14 pull request #17553
Opened 2023-06-22 13:14 UTC by laok233

## About the PR

added digital ian cartridge game :tm:  (it's cool i guess)
note: i've also planned a hunger system, but it is delayed (lack of time and skill issue) and it is a week a way just like surgery.

**Media**

https://github.com/space-wizards/space-station-14/assets/72604018/1df36725-4e1a-49a0-b9bb-29b95d00a194

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: end
- add: Nanotrasen has rewarded HoP a game cartridge in honor of his contribution to the station.

2023-06-22 13:22 UTC, Equivocateur commented
Ideal coping mechanism when the actual corgo got sent to the chef for free bicaridine

2023-06-22 21:32 UTC, 0x6273 requested changes
You need to fix your editor so it does not do this:
![image](https://github.com/space-wizards/space-station-14/assets/48867431/9a22c4e6-5c73-484f-b269-7848e42f547a)

2023-06-22 21:32 UTC, 0x6273 commented on Content.Client/CartridgeLoader/Cartridges/DigitalIanUi.cs
> +    private void SendDigitalIanMessage(DigitalIanUiAction action, BoundUserInterface userInterface)
```suggestion
    }
    
    private void SendDigitalIanMessage(DigitalIanUiAction action, BoundUserInterface userInterface)
```

2023-06-22 21:32 UTC, 0x6273 commented on Content.Server/CartridgeLoader/Cartridges/DigitalIanCartridgeComponent.cs
> +}
```suggestion
    [DataField("soundPet")]
    public SoundSpecifier SoundPet = new SoundPathSpecifier("/Audio/Animals/small_dog_bark_happy.ogg");
}
```

2023-06-22 21:48 UTC, 0x6273 commented on Content.Server/CartridgeLoader/Cartridges/DigitalIanCartridgeSystem.cs
> +public sealed class DigitalIanCartridgeSystem : EntitySystem
```suggestion
namespace Content.Server.CartridgeLoader.Cartridges;

public sealed class DigitalIanCartridgeSystem : EntitySystem
```

2023-06-22 22:19 UTC, Kromabae commented
ian tamagotchi moments

2023-06-23 07:50 UTC, laok233 commented
> You need to fix your editor so it does not do this: ![image](https://user-images.githubusercontent.com/48867431/248064311-9a22c4e6-5c73-484f-b269-7848e42f547a.png)

What does that mean?
No trailing blank line?
And how do i fix it.

2023-06-23 08:07 UTC, 0x6273 commented
> What does that mean? No trailing blank line? And how do i fix it.

It means that the last line doesn't have a linebreak (\n) character at the end. Most editors should fix this automatically.

2023-06-29 20:21 UTC, AJCM-git requested changes

2023-06-29 20:21 UTC, AJCM-git commented on Content.Client/CartridgeLoader/Cartridges/DigitalIanUiFragment.xaml.cs
> +        Icon.SetFromSpriteSpecifier(new SpriteSpecifier.Rsi(new("Mobs/Pets/corgi.rsi"), "ian"));
unhardcode this, make it a EntityPrototype datafield in the component

2023-06-29 20:21 UTC, AJCM-git commented on Content.Client/CartridgeLoader/Cartridges/DigitalIanUiFragment.xaml
> +    </BoxContainer> -->
This is way too simple, at least add hunger (could just add HungerComponent to the embedded entity and then make a control showcasing the hunger), also rebrand mentions of "Ian" to "Mascot" to make this more generic

2023-06-29 21:24 UTC, laok233 commented
well i guess it is better to close this pr and reopen it when i have time to do things.

2023-06-29 21:24 UTC, closed without merging