Adds a chameleon EVA suit to the uplink
space-wizards/space-station-14 pull request #17647
Opened 2023-06-25 19:32 UTC by Arendian

## About the PR

This PR adds a chameleon EVA suit and helmet to the uplink.
The suit has the exact same stats as the normal syndicate EVA(no armor, 20% slowdown) the helmet also has no armor value.
The bundle contains the following:
Chameleon EVA helmet
Chameleon EVA suit
Chameleon gas mask
Double emergency oxygen tank

**Media**

![image](https://github.com/space-wizards/space-station-14/assets/137322659/2938806f-c922-451a-938b-a18df2488aa5)
![image](https://github.com/space-wizards/space-station-14/assets/137322659/590e2278-10e7-405c-a2d7-f23668b9c7a7)
![image](https://github.com/space-wizards/space-station-14/assets/137322659/4843a05e-8a70-4563-a184-a8535b44dba8)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dygon
- add: Syndicate researchers have finally found a way to fit their chameleon technology into an EVA suit. The chameleon EVA bundle is now available in the uplink.

2023-06-25 19:48 UTC, 0x6273 commented
Seems kinda overpowered for just 6 TC. Also, the code has formatting issues in some places.

2023-06-25 20:05 UTC, Arendian commented
> Seems kinda overpowered for just 6 TC. Also, the code has formatting issues in some places.

The normal suit is 2 tc so I thought 4 tc for a the chameleon ability sounded acceptable, the normal chameleon clothing is only 6 tc too and contains way more stuff. What price do you think is more representable for it's function? 8tc?(same price as bloodred)

2023-06-25 20:41 UTC, deltanedas commented
8 tc can get you an emag, and thus a real hardsuit
why pretend to be cap in space with chameleon eva when you can just get the real thing, it will probably be left in the storage anyway

2023-06-25 20:46 UTC, Arendian commented
> 8 tc can get you an emag, and thus a real hardsuit
> why pretend to be cap in space with chameleon eva when you can just get the real thing, it will probably be left in the storage anyway

This suit would make nuclear operatives infiltrating a lot more viable since you have no timeframe where you are in your bloodred when entering the station. Also the current chameleon does not have the option to imitate any hardsuit at all, so this one would make it possible to infiltrate engineering and blowing the ame for example or turning off grav without looking too suspicious. Or switch yourself to a security hardsuit and walk around undercover during an assault without worrying about the spacing of your nuclear operative colleagues.

2023-06-25 20:48 UTC, KaiShibaa commented
I feel like chameleon should just be tied to suits or regular clothing and not actual EVA protection suit (or adding chameleon to everything). If the point of it is to be stealthy you can kinda already do that with the normal chameleon gear wearing Captain's hardsuit for instance and faking that you're wearing it (by not going into space) 

If you space an area as a nukie, I think you've already lost the element of stealth seeing that people already know you're onboard.

2023-06-25 20:58 UTC, 0x6273 reviewed
> The normal suit is 2 tc so I thought 4 tc for a the chameleon ability sounded acceptable, the normal chameleon clothing is only 6 tc too and contains way more stuff. What price do you think is more representable for it's function? 8tc? (same price as bloodred) It would make this the suit for a stealth mission while a bloodred would be for a loud one.

Yeah 8 is probably fine. It can always be tuned later.

2023-06-25 20:58 UTC, 0x6273 commented on Content.Shared/Clothing/EntitySystems/SharedChameleonClothingSystem.cs
> +    public bool IsValidEVATarget(EntityPrototype proto, SlotFlags chameleonSlot = SlotFlags.NONE)
```suggestion
    }
    
    public bool IsValidEVATarget(EntityPrototype proto, SlotFlags chameleonSlot = SlotFlags.NONE)
```

2023-06-25 20:58 UTC, Arendian commented
> I feel like chameleon should just be tied to suits or regular clothing and not actual EVA protection suit (or adding chameleon to everything). If the point of it is to be stealthy you can kinda already do that with the normal chameleon gear wearing Captain's hardsuit for instance and faking that you're wearing it (by not going into space). You can already do the things you've used as an example with the normal chameleon suit.
> 
> If you space an area as a nukie, I think you've already lost the element of stealth seeing that people already know you're onboard.

The current chameleon gear is unable to disguise as hardsuits(except rd one), only softsuits.
![image](https://github.com/space-wizards/space-station-14/assets/137322659/fc5e0e6a-7af6-473a-b095-7f613d072ebf)


And if you space the area in disguise people would just shout "an engineer just exploded x area" instead of "nukies just exploded x area"

2023-06-26 02:55 UTC, Myakot commented
8 tc is way too expensive. Don't forget this suit's parent is default syndie eva. This suit **doesn't** protect you in open space and the cold temperatures will get to you.
also rip slimes with oxy tanks in bundles, as always.

2023-06-26 03:07 UTC, KaiShibaa commented
> 8 tc is way too expensive. Don't forget this suit's parent is default syndie eva. This suit **doesn't** protect you in open space and the cold temperatures will get to you. also rip slimes with oxy tanks in bundles, as always.

You're probably thinking of the emergency suits. Syndie EVA does protect you from space.

Price is higher because it literally allows you to change the look of the suit on a whim. If it were the same price as the regular Syndie EVA bundle, this would just be better to grab than that.

2023-06-28 00:54 UTC, AJCM-git requested changes
This unnecessarily repeats a lot of code, you need to add a new EntityWhitelist datafield to the chamaleon component and tweak the methods to support it

2023-06-28 02:09 UTC, Emisse commented
personally not a fan of space proof chameleon suit

2023-06-30 01:24 UTC, crazybrain23 requested changes
~~Ironically, you've missed the EVA suit (it's in the `softsuits.yml`)~~
I might be wrong here, I have no idea how you did it without tags?

2023-08-08 20:45 UTC, AJCM-git commented
re-open if you come back to this

2023-08-08 20:45 UTC, closed without merging