broodmother or a huge spider
space-wizards/space-station-14 pull request #17795
Opened 2023-07-02 21:50 UTC by kxvvv

## About the PR

for your evaluation. does it have a chance?
PR adds a large spider, its servants, and a spider egg.

later I will sort everything into the right folders. (originally created as a prototype)

if you think this has a chance, I need edits in the balance, etc.

**Media**

SCREENSHOOTS:
![image](https://github.com/space-wizards/space-station-14/assets/136233650/a5fa6822-b0c8-437a-af90-cca73a25452c) ![image](https://github.com/space-wizards/space-station-14/assets/136233650/1671af42-6d29-4d49-97ba-f9fef0846e5b)![image](https://github.com/space-wizards/space-station-14/assets/136233650/a004df60-7d2c-47a3-82cf-3b07b0171a17)

![image](https://github.com/space-wizards/space-station-14/assets/136233650/4bcbf343-92c6-4fc0-affa-82661277b330)

![image](https://github.com/space-wizards/space-station-14/assets/136233650/f2d6c0ac-f3b5-4cdf-aaec-a7b5e1be92ac)

![image](https://github.com/space-wizards/space-station-14/assets/136233650/01b43787-5fb2-4ffb-bac1-07d7aae35851)
![image](https://github.com/space-wizards/space-station-14/assets/136233650/5b438baa-6e05-4ddd-b782-4fcd069205c2)

![image](https://github.com/space-wizards/space-station-14/assets/136233650/df8fe8f5-528c-403b-beef-ad12c0d1d02d)

VIDEO:
https://youtu.be/ADPFHvafm0c

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: A huge spider queen has been spotted at NT stations!

2023-07-02 21:58 UTC, Aisu9 commented
what the hell are those damages, Broodmother deal 47 damage per bite (35 pierce/12 poison) and the servant deal 18 (12 piercing and 8 poison)

2023-07-02 22:05 UTC, LankLTE commented
Just for reference, the Space Dragon does 30 damage a hit. I wouldn’t go any higher than that- the Xeno Queen’s 20 may be a good reference point.

2023-07-02 22:05 UTC, kxvvv commented
> what the hell are those damages, Broodmother deal 47 damage per bite (35 pierce/12 poison) and the servant deal 18 (12 piercing and 8 poison)

That's what I'm talking about, I need balance tips

2023-07-02 23:53 UTC, Nimfar11 commented
It's worth correcting the translation at brood servant.

2023-07-03 07:52 UTC, GeneralGaws commented
Maybe that spider should be megafauna? But its great pr

2023-07-03 11:33 UTC, kxvvv commented
> It's worth correcting the translation at brood servant.

for example?

2023-07-03 11:36 UTC, deltanedas commented
holy shit kill it with fire

2023-07-06 03:49 UTC, metalgearsloth requested changes

2023-07-06 03:49 UTC, metalgearsloth commented on Content.Shared/Movement/Components/SlowContactsComponent.cs
> +
Do not hardcode in specific entities like this as it breaks composition.

If you want it whitelisted then use an entity whitelist.

2023-07-06 03:49 UTC, metalgearsloth commented on Content.Shared/Movement/Systems/SlowContactsSystem.cs
> +            }
As above do not hardcode in specific entities.

2023-07-06 03:49 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Mobs/NPCs/broodmother.yml
> +        Base: dead
unused, please remove.

2023-07-06 03:49 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Mobs/NPCs/broodmother.yml
> +      750: 0.8
Why does it go down then up?

2023-07-06 03:49 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Mobs/NPCs/broodmother.yml
> +    eggLayCooldownMax: 99999999
Don't add hacks if you want an infinite cooldown.

2023-07-13 10:25 UTC, JoeHammad1844 commented
god damn that bitch is fast

2023-08-05 02:34 UTC, metalgearsloth commented
Is this still draft?

2023-08-05 05:31 UTC, kxvvv commented
> Is this still draft?

yes, need fix something in her skill

2023-09-04 16:47 UTC, LankLTE commented
@kxvvv Will you be coming back to this?

2023-10-02 23:40 UTC, metalgearsloth commented
> > @kxvvv Will you be coming back to this?
> 
> it's done i need review🧐

Your tests are failing.

2023-10-08 22:41 UTC, kxvvv commented
too many code updates came out during your "mega very fast" review, I'm too lazy to redo it ._.

2023-10-08 22:41 UTC, closed without merging