Fix content.integration tests warnings
space-wizards/space-station-14 pull request #17817
Opened 2023-07-04 15:01 UTC by TemporalOroboros

## About the PR

- Fixes most of the warnings in the Content.IntegrationTests module.
- Does not fix CreateGrid related warnings as that would require engine work.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-07-04 23:13 UTC, TemporalOroboros reviewed
Broke some tests. Will fix them soon.

2023-07-04 23:13 UTC, TemporalOroboros commented on Content.IntegrationTests/Tests/Minds/MindTests.ReconnectTests.cs
> +            Assert.That(mind.OwnedEntity, Is.Not.Null);
Should be Is.Null

2023-07-04 23:13 UTC, TemporalOroboros commented on Content.IntegrationTests/Tests/Minds/MindTests.ReconnectTests.cs
> +            Assert.That(mind.CurrentEntity, Is.EqualTo(visiting));
Probably don't need two of the same test?

2023-07-04 23:13 UTC, TemporalOroboros commented on Content.IntegrationTests/Tests/Minds/MindTests.ReconnectTests.cs
> +            Assert.That(!entMan.Deleted(visiting), Is.False);
Both of the checks here shouldn't have the !s. That's what the Is.False s are for.

2023-07-04 23:13 UTC, TemporalOroboros commented on Content.IntegrationTests/Tests/Networking/SimplePredictReconcileTest.cs
>                      Assert.That(clientSystem.EventTriggerList,
Somehow got here as False, True, True, True. Fix.

2023-07-05 00:11 UTC, TemporalOroboros commented on Content.IntegrationTests/Tests/Networking/SimplePredictReconcileTest.cs
>                      Assert.That(clientSystem.EventTriggerList,
Might be fixed by dirtying the comp after handling state.

2023-07-05 00:37 UTC, TemporalOroboros commented on Content.IntegrationTests/Tests/Networking/SimplePredictReconcileTest.cs
>                      Assert.That(clientSystem.EventTriggerList,
Did not fix it. Not sure what's wrong here.

2023-07-05 04:34 UTC, TemporalOroboros commented on Content.IntegrationTests/Tests/Networking/SimplePredictReconcileTest.cs
>                      Assert.That(clientSystem.EventTriggerList,
Looks like the component state isn't being reset during prediction? I don't know why that's happening.

2023-07-06 01:24 UTC, TemporalOroboros commented
Should be good to go. About half of the lines added are two new mispredict reconciliation tests. They're for the source gen and ECS based versions.

2023-07-06 03:44 UTC, metalgearsloth requested changes

2023-07-06 03:44 UTC, metalgearsloth commented on Content.IntegrationTests/PoolManager.cs
>              IoCManager.Register<InteractionSystemTests.TestInteractionSystem>();
Just do the resolve once and re-use it.

2023-07-06 03:44 UTC, metalgearsloth commented on Content.IntegrationTests/PoolManager.cs
>                      IoCManager.Resolve<IComponentFactory>()
Same here.

2023-07-06 03:44 UTC, metalgearsloth commented on Content.IntegrationTests/PoolManager.cs
> +                .First((ent) => entityManager.GetComponent<MapGridComponent>(ent) == mapData.MapGrid);
Better to leave the warning in place than this.

2023-07-06 03:44 UTC, metalgearsloth commented on Content.IntegrationTests/PoolManager.cs
> +#pragma warning restore
Should just disable the specific warning rather than all of them.

2023-07-06 04:54 UTC, metalgearsloth approved these changes

2023-07-06 04:54 UTC, merged