Allow map renderer to render maps from a path, and fix some entities not being rotated
space-wizards/space-station-14 pull request #17829
Opened 2023-07-05 07:35 UTC by DebugOk

## About the PR
This makes the map renderer be able to take paths to render, instead of requiring a station prototype. However to do so I had to make a cvar that'll create a dummy map and station prototype if a map is loaded without one, which I'm not sure is the best solution, but I had no other ideas. Marking it as a draft for now in case someone has a better suggestion for how to do this

Additionally, I also fixed the issue where rotations weren't getting applied properly, because why not.

**Media**
Before fixed rotations

![image](https://github.com/space-wizards/space-station-14/assets/49997488/62de2682-3370-4c5d-b6ad-cd6beb03662c)

After
![dart-0](https://github.com/space-wizards/space-station-14/assets/49997488/0c3f9239-536f-471d-8e03-f1da38e9a56d)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
Real?

2023-07-07 00:03 UTC, metalgearsloth commented
Map renderer should always just take a path as it's significantly more useful than taking gamemap prototypes tbh.

2023-07-07 10:10 UTC, DebugOk commented
> Map renderer should always just take a path as it's significantly more useful than taking gamemap prototypes tbh.

Probably, but its likely done like that because the server uses a map prototype for loading it properly

2023-07-10 03:02 UTC, Emisse approved these changes

2023-08-10 19:00 UTC, AJCM-git requested changes

2023-08-15 07:26 UTC, DebugOk commented on Content.MapRenderer/Program.cs
Sorry, didn't seem to get notifications for any of this. Will do

2023-08-28 18:34 UTC, DebugOk commented
I found a potential solution that only requires changing maprenderer code, but I'm having an issue where it doesn't seem to be spawning any entities. Does MapLoaderSystem not work properly in a test pair?

2023-08-28 20:51 UTC, DebugOk commented
> I found a potential solution that only requires changing maprenderer code, but I'm having an issue where it doesn't seem to be spawning any entities. Does MapLoaderSystem not work properly in a test pair?

Nevermind, seems to be an issue caused by the empty map I was using lacking some random component

2023-08-28 20:59 UTC, juliangiebel commented
The map renderer can already take map filenames using the -f option.

2023-09-04 20:52 UTC, DebugOk commented
For the record, I'm still working on this, I'm just trying to figure stuff out

2023-09-17 08:54 UTC, lzk228 commented
feature idea: render with subfloor toggled on

2023-10-19 20:16 UTC, DebugOk commented
I've been working on other stuff recently that has taken my attention away from this, feel free to reuse the code I already implemented for rotations for whatever, but for now, I'll have to work on this at a later date.

2023-10-19 20:16 UTC, closed without merging