Adding sounds to stamps
space-wizards/space-station-14 pull request #17834
Opened 2023-07-05 15:47 UTC by Lomcastar

## About the PR
Now it is more pleasant to put stamps.
Almost all stamps have the sound of a hand stamp.
But the DENIED and APPROVED stamps have an automatic stamp sound, which in my opinion sounds more pleasant.

**Media**

https://github.com/space-wizards/space-station-14/assets/129697969/c4fd8ec8-0b9b-485b-bc0b-e05ce7a204be

- [x] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**
:cl:
- add: Added stamp sounds.

2023-07-05 17:33 UTC, mirrorcult requested changes

2023-07-05 17:33 UTC, mirrorcult commented on Content.Shared/Paper/StampComponent.cs
> +        public string Sound = string.Empty;
use a `SoundSpecifier`, not a string path

2023-07-05 17:36 UTC, mirrorcult commented on Resources/Audio/Items/Stamp/thick_stamp_nosub.ogg
unused sound? whats the diff between sub vs nosub

2023-07-05 17:37 UTC, Lomcastar commented on Resources/Audio/Items/Stamp/thick_stamp_nosub.ogg
very little difference in sound

2023-07-05 17:37 UTC, Lomcastar commented on Resources/Audio/Items/Stamp/thick_stamp_nosub.ogg
is it better to remove it if it is not used?

2023-07-05 17:44 UTC, mirrorcult commented on Resources/Audio/Items/Stamp/thick_stamp_nosub.ogg
no reason to keep it if its basically the same sound

2023-07-05 18:38 UTC, Lomcastar commented
hmmmmmmmm... ok...

2023-07-05 21:22 UTC, CaptainSqrBeard commented
Make clown stamp honk and mime stamp silent 😄

2023-07-06 00:28 UTC, Lomcastar commented
@CaptainSqrBeard The idea is good but.
The seal of the mime is the base for all other seals.
A clown needs a special sound. Something between a stamp and a HONK.

2023-07-07 02:53 UTC, Emisse commented
thunk

2023-07-07 02:53 UTC, merged