Calling ERT via the communication console.
space-wizards/space-station-14 pull request #17851
Opened 2023-07-06 07:27 UTC by VigersRay

## About the PR

Made it possible to call the OBR through the communication console with the verification of certain conditions. Perhaps this needs further improvement, in particular, the issue of calling the OBR during nuclear operatives and the ability to turn it off through swaras, as well as the ability to cancel the OBR called by the admins, is open.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![image](https://github.com/space-wizards/space-station-14/assets/60344369/0817d9b9-ff98-40c7-809a-dfb40fd18d03)
![image](https://github.com/space-wizards/space-station-14/assets/60344369/91e9d8de-5558-44e5-9b8d-285dbd2dc283)

https://github.com/space-wizards/space-station-14/assets/60344369/f1399777-2df9-4d1c-860d-b28e957f9cd9

**Changelog**

:cl: VgiersRay
- add: Nanotranzen made it possible for stations to request ERT via the communications console.

2023-07-06 08:20 UTC, Dynexust commented
Good idea, however I feel as if the admins should be able to approve manually whether to send an ERT or not.

2023-07-06 08:38 UTC, Maksim22848 commented
the idea is really good, but there will be a big problem that the players will just shitspawn them

2023-07-06 08:53 UTC, VigersRay commented
> the idea is really good, but there will be a big problem that the players will just shitspawn them

There are requirements for each type and fallback between calls, so I don't think that's a problem.

2023-07-06 09:25 UTC, ficcialfaint commented
why’s it 14k lines

2023-07-06 09:30 UTC, VigersRay commented
> why’s it 14k lines

shuttles...

2023-07-06 09:31 UTC, GeneralGaws commented
> why’s it 14k lines 

 Shuttles for every type of ert squad, cburn shuttle, med shuttle etc

2023-07-06 09:32 UTC, ficcialfaint commented
i see mb

2023-07-06 09:36 UTC, noverd commented
Good.

2023-07-06 10:51 UTC, PuroSlavKing commented on Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml
> +    back: ClothingBackpackClownFilled
"ClothingBackpackERTClown"?

2023-07-06 11:27 UTC, Just-a-Unity-Dev commented
this should be a cvar i can see some servers wanting it while others not

2023-07-06 11:28 UTC, Just-a-Unity-Dev commented
also i find ERT to be unnecessary cause command will literally just call ERT for everything don't tell me they won't

2023-07-06 12:22 UTC, VigersRay commented on Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml
> +    back: ClothingBackpackClownFilled
is real?

2023-07-06 12:23 UTC, VigersRay commented
> this should be a cvar i can see some servers wanting it while others not

In general, it is easy to make a cvar, but the call button itself will remain in both cases.

2023-07-06 12:24 UTC, VigersRay commented
> also i find ERT to be unnecessary cause command will literally just call ERT for everything don't tell me they won't

In most cases, ERT will be automatically rejected.

2023-07-06 17:20 UTC, VigersRay commented
> Yeah a system, where an admin should always be in control here I think is best. Basically you could put a request in at the console, and the admin would have to approve it. If not approved, you could get a centcomm message like, "Sorry all our Ert teams are busy at the moment leave a message at the beep."

Actually the whole idea is to allow the crew to receive ERT without administrators. Perhaps there are always admins on the servers of the wizards, but on certain servers there is a problem with this, the admins are either too lazy to spawn the return shuttle and roles every time, or they simply do not exist on the server in most cases. I just heard that the call to ERT in cc13 also happens automatically without the participation of admins.

2023-07-06 17:53 UTC, KaiShibaa commented
Personally, ERT should be admin only. People are going to end up abusing this for every single little thing. ERT should also not be an answer to everything.

 I don't think calling admins lazy is a good idea either.

2023-07-06 18:01 UTC, CloneTrooperSimp commented
Interesting idea.
We hope it won't get abused by players, but that is... expecting too much I'd say...

2023-07-06 18:03 UTC, Nairodian commented
Admins _should_ probably have some button to prevent calling it, in case of events and such. But if there's a system in place to require two or more command votes, admin denial and accepting may not be required.

2023-07-06 18:12 UTC, Geekyhobo commented
As a non 13 player I didn't think about the head vote thing, that I think is the winner, especially with the increased amount of hours to play command roles, I believe that the heads can make the right call.

2023-07-06 18:30 UTC, VigersRay commented
> 

On the server where I have already uploaded this, oddly enough they do not abuse it, even during the attack of nuclear operatives, no one called the ERT having only 5 sats in the state. I think this only applies to LRP servers. While again, there are fixed requirements for sending an ERT , these can be increased by making the ability to call an ERT via the console very rare, such as 80% dead crew, or 80% zombies on a station.

2023-07-06 18:30 UTC, VigersRay commented
> Personally, ERT should be admin only. People are going to end up abusing this for every single little thing. ERT should also not be an answer to everything.
> 
> I don't think calling admins lazy is a good idea either.

On the server where I have already uploaded this, oddly enough they do not abuse it, even during the attack of nuclear operatives, no one called the ERT having only 5 sats in the state. I think this only applies to LRP servers. While again, there are fixed requirements for sending an ERT , these can be increased by making the ability to call an ERT via the console very rare, such as 80% dead crew, or 80% zombies on a station.

2023-07-06 18:40 UTC, lzk228 commented
player abusing, player gets banned, isnt it?

2023-07-06 23:57 UTC, metalgearsloth commented
We ended up disabling early launches entirely as our playerbase abused it constantly so I would put money on this being abused.

2023-07-07 00:05 UTC, VigersRay commented
> We ended up disabling early launches entirely as our playerbase abused it constantly so I would put money on this being abused.

Perhaps if there was the same system for early launch as in expeditions (checking if all the utilizers have returned), this problem would not exist. It would be possible to check conditionally if 80-90% of the LIVE crew came on board, then an early launch can be made.

2023-07-09 19:06 UTC, Peptide90 commented
> player abusing, player gets banned, isnt it?

Relying on admin intervention is the last step in the process. If you can engineer it out do that first.

I'm used to SS13 where you need two head swipes in like 5 seconds. Same thing exists for shuttle calling there too. Also +1 for allowing admins to block all requests.

2023-07-09 19:55 UTC, deltanedas commented
if admins are online this should be a thing that requires admin approval to spawn, with an option in adminbus or something to disable entirely since average lizard shitter will call it after stubbing his toe and might mess with events as previously stated

with no admins the coded checks should help but ultimately it would be a burden to deal with reports of abusing it

2023-07-11 08:54 UTC, JoeHammad1844 commented
what are the requirements for ERT to be called? and please send images of all the shuttles

2023-08-21 04:55 UTC, metalgearsloth commented
Swipes need coding

2023-08-29 23:55 UTC, AJCM-git requested changes
Heads swipes as described by PJB are necessary

2023-08-30 06:08 UTC, closed without merging