[VM] SyndieDrobe
space-wizards/space-station-14 pull request #17885
Opened 2023-07-07 21:27 UTC by PuroSlavKing

**Animation:**

https://github.com/space-wizards/space-station-14/assets/103608145/da2251b0-ab20-4162-bd52-78b26ed4814b

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: PuroSlavKing
- add: Added SyndieDrobe!

2023-07-07 21:41 UTC, deltanedas requested changes

2023-07-07 21:41 UTC, deltanedas commented on Resources/Locale/en-US/advertisements/vending/syndiedrobe.yml
> +advertisement-syndiedrobe-6 = Death of NT!
of -> to

2023-07-07 21:42 UTC, PuroSlavKing commented on Resources/Locale/en-US/advertisements/vending/syndiedrobe.yml
> +advertisement-syndiedrobe-6 = Death of NT!
> of -> to

done

2023-07-08 21:19 UTC, CaptainSqrBeard commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/syndiedrobe.yml
> +    ClothingHeadHatTacticalMaidHeadband: 5
please don't

2023-07-08 21:20 UTC, PuroSlavKing commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/syndiedrobe.yml
> +    ClothingHeadHatTacticalMaidHeadband: 5
😈

2023-07-09 19:19 UTC, merged