Nukes role restrictions
space-wizards/space-station-14 pull request #17929
Opened 2023-07-10 13:08 UTC by VigersRay

## About the PR

If you don't know how to turn on the harm mod, you don't play nukers.
The leader must play 5 hours in command and sec department, he must be able to lead and fight. 
Medic must play 5 hours in the medical department, he must be able to heal.
A standard nuker should also play 5 hours in sec department. 
And to know the general aspects of the game, all hes need to play 25 hours.

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: VigersRay
- tweak: The syndicate began to recruit more experienced people into the ranks of nuclear operatives.

2023-07-10 16:09 UTC, crazybrain23 requested changes

2023-07-10 17:56 UTC, Geekyhobo commented
Personally I think this is going too far, the whole reason that #17888 was merged was because it would allow more people to paly nukie. I get that its frustrating, especially as a nukie, when your commander or teammates seem like they have never seen a gun before in their life. But its not fair to people just to gatekeep a fun and enjoyable role. Plus this technically makes it rarer for people to get the roles. Example being, if there is only 2 people that have the requirements to be the commander on a server they will get the role, unless your are able to also ignore those role time requirements. Also in the same line of thinking, if there is no one with the capability of filling the nukie roles, does that mean that a nukie round can never start? 

Idk that was a bit of a rant but I mean it as constructive criticism. I think this could be a good idea, just need to be fleshed out a bit more than just putting role timers on it.

2023-07-10 18:12 UTC, HoidC commented
> Personally I think this is going too far, the whole reason that #17888 was merged was because it would allow more people to paly nukie. I get that its frustrating, especially as a nukie, when your commander or teammates seem like they have never seen a gun before in their life. But its not fair to people just to gatekeep a fun and enjoyable role. Plus this technically makes it rarer for people to get the roles. Example being, if there is only 2 people that have the requirements to be the commander on a server they will get the role, unless your are able to also ignore those role time requirements. Also in the same line of thinking, if there is no one with the capability of filling the nukie roles, does that mean that a nukie round can never start?
> 
> Idk that was a bit of a rant but I mean it as constructive criticism. I think this could be a good idea, just need to be fleshed out a bit more than just putting role timers on it.

the command timers are a bit much but this role absolutely needs a playtime limiter for how difficult it is 

there's been multiple instances that i've personally witnessed of players having their first round be a nuke op round which is going to suck for them and everyone else around them - they're inevitably going to be yelled at by their own team and laughed at in OOC chat when they die, and they're also thrown into the most complex role in the game

roles that are difficult have role timers so that players can learn them before they play them and this shouldn't be different

2023-07-10 18:16 UTC, deltanedas commented
i think:
- commander should require a few hours as operative
- operative needs salvage time
- theyre still low times

2023-07-10 18:58 UTC, LankLTE commented
> i think:
> 
>     * commander should require a few hours as operative
> 
>     * operative needs salvage time
> 
>     * theyre still low times

I agree commander should be operative time, but afaik that's not tracked so it'd need to be worked on.
Why should operative need salvage time..? They're not even remotely related roles. Simple playtime requirement should be enough for salvage.
The times are somewhat short (and nukie needing 5 hours of command for whatever reason is odd)- personally like 50 hours to get nukie should be the max though. It's a very unique role and the truth is you'll never be able to get rid of new players being nukie entire, just lower it.

2023-07-10 20:38 UTC, GoodWheatley commented
Commander requiring operative time would suck because of how low the chances of rolling nukie are. Likewise, I don’t think that requiring command and sec time is going to guarantee that new nukies know how their mechanics work; you can have command shifts which don’t teach you anything relevant to being a nukie commander and sec shifts where you never shoot a gun. I think just having a flat 30 hour requirement would work the best.

2023-07-10 20:45 UTC, deltanedas commented
whereas salv is surviving in space, killing dragons, healing yourself in battle, etc

2023-07-10 20:49 UTC, GoodWheatley commented
> whereas salv is surviving in space, killing dragons, healing yourself in battle, etc

Or it’s just flying back and forth and looting magnet debris for the shift. And with how competitive getting the salvage tech job roundstart is already, requiring salvage playtime just means that only salvage mains will get to play nukies for potentially a month.

2023-07-10 20:50 UTC, deltanedas commented
that means more sosa ops which is good

2023-07-10 20:51 UTC, GoodWheatley commented
> that means more sosa ops which is good

How is letting a single player have a vastly higher chance to roll antags good for the game

2023-07-10 20:59 UTC, LankLTE commented
> Commander requiring operative time would suck because of how low the chances of rolling nukie are. Likewise, I don’t think that requiring command and sec time is going to guarantee that new nukies know how their mechanics work; you can have command shifts which don’t teach you anything relevant to being a nukie commander and sec shifts where you never shoot a gun. I think just having a flat 30 hour requirement would work the best.

It requiring operative time may suck, but it's a good thing. I think like, literally half an hour would be fine, just to ensure that you _have_ played nukie at some point in the past and don't have people playing their first nukie game on commander. 
Everything else I agree with

2023-07-10 22:34 UTC, deltanedas commented
yeah im not saying 10 hours nukie requirement for commander, that would be simply impossible

2023-07-10 22:35 UTC, Emisse commented
commander should be like 1 hour since thats 1-2 nukie missions and thats enough time to be acquainted with it

2023-07-11 00:56 UTC, crazybrain23 commented
> commander should be like 1 hour since thats 1-2 nukie missions and thats enough time to be acquainted with it

If operative roletimers were based on time, there would be an incentive to waste time as nukies so you can unlock commander. Would be better to track number of times as operative?

2023-07-11 01:46 UTC, deltanedas commented
then youd be incentivised to group suicide to get a new round quicker, which is much worse

2023-07-11 08:41 UTC, JoeHammad1844 commented
how about some hours as security aswell?
1 hour as salv and 1 hour as sec sounds reasonable to me

2023-08-04 03:23 UTC, metalgearsloth commented
> For the nukie requirements, I think it'd be good if commander, maybe even agent, had a requirement for having played as nukie before, but it'd need to be really short to make sure it's actually reasonable to unlock. Like emisse said, 1-2 rounds is probably fine most of the time, it'd probably be enough to ensure that the commander can give some guidance to the team. 

Just make it like 10-15 minutes so there's no dramas about getting it after a round.

2023-08-22 00:34 UTC, deltanedas commented
merg

2023-08-23 03:57 UTC, JoeHammad1844 commented
add some hos playtime to commander and CMO gameplay to agent

2023-08-23 09:02 UTC, crazybrain23 commented on Resources/Prototypes/Roles/Antags/nukeops.yml
> +    time: 18000 # 5h
Second point is that you gave the regular nukies a command playtime requirement but the commander doesn't have the command playtime requirement.

2023-08-31 02:03 UTC, metalgearsloth commented
@VigersRay if you're going to work on your PRs ping us on discord.

2023-08-31 02:03 UTC, closed without merging

2023-09-07 15:28 UTC, Geekyhobo commented
@VigersRay Is it alright If I try and revive this PR? Wanna make this happen

2023-09-07 15:29 UTC, Geekyhobo commented
and #17928

2023-09-07 15:44 UTC, Morb0 commented
> @VigersRay Is it alright If I try and revive this PR? Wanna make this happen

You can, just add him as an author

2023-09-07 16:08 UTC, deltanedas commented
revive it address reviews and in cl do
`:cl: VigersRay, Geekyhobo`

2023-09-07 23:20 UTC, crazybrain23 commented
> @VigersRay Is it alright If I try and revive this PR? Wanna make this happen

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

If you run `git fetch upstream pull/17929/head:nukeops_role_restrictions` you'll have a local copy of this PR that you can make changes to. It keeps their commit history and makes a co-authored PR.

2023-09-07 23:22 UTC, deltanedas commented
bruh real every time i want to compile or ~~steal~~ revive someone pr i add their fork as a remote :trollface:

2023-09-13 16:39 UTC, deltanedas commented
ok @Geekyhobo you took too long this is my pr now

2023-09-13 17:26 UTC, Geekyhobo commented
@deltanedas Go for it, I dont really have the time due to school.