Species job blacklist
space-wizards/space-station-14 pull request #17930
Opened 2023-07-10 13:25 UTC by VigersRay

## About the PR

Adds the ability to restrict species from holding certain roles. Dione who can become security is stupid, no?

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![image](https://github.com/space-wizards/space-station-14/assets/60344369/5cd50ae0-df96-4524-b63f-db2f0c9ccb46)

**Changelog**

2023-07-10 13:30 UTC, metalgearsloth commented on Content.Client/LateJoin/LateJoinGui.cs
> +using NFluidsynth;
Wrong logs.

2023-07-10 14:27 UTC, Aisu9 commented
i mean it does make sense... but what about speciesism being illegal(and banable) in this version of Nanotrasen/in SS14

2023-07-10 14:32 UTC, LankLTE commented
> i mean it does make sense... but what about speciesism being illegal/outlawed(and banable) in this version of Nanotrasen/in SS14

This is for downstream (and disabled by default I believe). Won't be used in WizDen

2023-07-10 14:35 UTC, VigersRay commented
> > i mean it does make sense... but what about speciesism being illegal/outlawed(and banable) in this version of Nanotrasen/in SS14
> 
> This is for downstream (and disabled by default I believe). Won't be used in WizDen

quite right

2023-07-10 14:51 UTC, KasianenkoViacheslavMiki commented
Sorry, what I write in this conversation and so not a contributor. But how I think and wrote EmoGarbage404 is better in a Job's prototype. But not as Job Requirement, but as a different component. For example how I created a similar feature.
https://github.com/KasianenkoViacheslavMiki/space-station-14/commit/21977197fc71702f444c905095d15727e63b3457 
So you can simply configure in Job's prototype which species must be banned for this job, which is more logical.

2023-07-10 15:10 UTC, VigersRay commented
> Sorry, what I write in this conversation and so not a contributor. But how I think and wrote EmoGarbage404 is better in a Job's prototype. But not as Job Requirement, but as a different component. For example how I created a similar feature.
> https://github.com/KasianenkoViacheslavMiki/space-station-14/commit/21977197fc71702f444c905095d15727e63b3457 
> So you can simply configure in Job's prototype which species must be banned for this job, which is more logical. 

Well, yes, this is the best option, I was just too lazy to specify a ban for the species for 20 roles in my build, so I decided that it would be easier to specify them in the species component

2023-07-12 19:56 UTC, Emisse commented
i dont think putting this on the species is a good option, having it be a blacklist on the job prototype would be a lot better and save you headache in the future

2023-07-12 22:14 UTC, VigersRay commented
> i dont think putting this on the species is a good option, having it be a blacklist on the job prototype would be a lot better and save you headache in the future

Yeah, it's probably better that way, I'll move it there when I have free time.

2023-07-12 22:14 UTC, VigersRay commented
> i dont think putting this on the species is a good option, having it be a blacklist on the job prototype would be a lot better and save you headache in the future

Yeah, it's probably better that way, I'll move it there when I have free time.

2023-07-14 05:08 UTC, VigersRay commented
> > Diona who can become security is stupid, no?
> 
> On upstream diona can harm, so it's not stupid.

This was just an example, in the code I did not apply restrictions for any of the races, each individual build will decide for itself which restrictions need to be applied.

2023-07-16 13:10 UTC, metalgearsloth requested changes
As emisse said this should be a jobrequirement.

2023-08-04 02:57 UTC, metalgearsloth commented
@VigersRay are you coming back to this

2023-08-31 02:02 UTC, closed without merging