Pipe painter
space-wizards/space-station-14 pull request #17965
Opened 2023-07-11 20:19 UTC by lzk228

## About the PR

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

2023-07-11 20:28 UTC, BRINGit34 commented
This is so rad

2023-07-18 23:03 UTC, potato1234x commented
ok but what if it could paint everything 😳

2023-07-20 22:05 UTC, ficcialfaint requested changes
What’s the point of just taking someone’s work from another fork, not ensuring it works, not running it on the local server, not trying to fix any issues?

2023-07-26 12:21 UTC, c4llv07e commented
> What’s the point of just taking someone’s work from another fork, not ensuring it works, not running it on the local server, not trying to fix any issues?

I think it was working two weeks ago and it just broke after BoundUserInterface refactoring.

2023-07-26 12:23 UTC, c4llv07e commented on Content.Client/PipePainter/PipePainterBoundUserInterface.cs
> +    public PipePainterBoundUserInterface(ClientUserInterfaceComponent owner, Enum uiKey) : base(owner, uiKey)
```suggestion
    public PipePainterBoundUserInterface(EntityUid owner, Enum uiKey) : base(owner, uiKey)
```

Now EntityUid is required as the owner.

2023-07-26 12:24 UTC, c4llv07e commented on Content.Server/PipePainter/PipePainterSystem.cs
> +        component.Owner.GetUIOrNull(PipePainterUiKey.Key)?.Open(actor.PlayerSession);
```suggestion
        _userInterfaceSystem.TryOpen(uid, PipePainterUiKey.Key, actor.PlayerSession);
```

This should work (I tested).

2023-07-26 17:09 UTC, lzk228 commented
works right

2023-07-26 20:31 UTC, Vaaankas commented
Shouldnt it be the same item with the airlock painter?

2023-07-26 22:58 UTC, potato1234x commented
> Shouldnt it be the same item with the airlock painter?

merge them into the omnipainter

2023-07-26 23:00 UTC, AJCM-git requested changes
> Shouldnt it be the same item with the airlock painter?

yeah they should

2023-07-26 23:18 UTC, lzk228 commented
bruh

2023-07-29 14:32 UTC, ficcialfaint commented
> > What’s the point of just taking someone’s work from another fork, not ensuring it works, not running it on the local server, not trying to fix any issues?
> 
> 
> 
> I think it was working two weeks ago and it just broke after BoundUserInterface refactoring.

anyways, it'd never happen if they at least ensured it worked and copied the latest version from that codebase, had to test it locally first

2023-08-10 20:58 UTC, AJCM-git commented
@lzk228 are you coming back to this?

2023-08-10 21:18 UTC, lzk228 commented
nah bruh

2023-08-10 21:20 UTC, closed without merging