Fix DNA scrambler ending nukie rounds early
space-wizards/space-station-14 pull request #18153
Opened 2023-07-19 18:20 UTC by Arendian

## About the PR

resolves #18145 
This PR gives the scrambled entities the NukeOperatice component.
Apparently entities in a paused map don't count as alive, so the DNA scrambled entities need the NukeOperative component.
This prevents the game thinking all nukies are dead the moment it checks for alive operatives when one of them gets killed.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Dygon
- fix: DNA scrambled nuclear operatives now count as alive for the end of round check.

2023-07-19 20:44 UTC, deltanedas commented
good solution will remove the scrambled prototype so imo this is a fine bandaid considering it can end nukie rounds early

2023-07-19 20:50 UTC, Arendian commented
I can probably just remove the scrambled prototype and make it turn someone into MobHumanNukeOp since only the name is currently different.

2023-07-19 20:56 UTC, PrPleGoo commented
shouldn't they also still be a syndie faction member?

2023-07-19 21:03 UTC, PrPleGoo commented
I feel like the polymorph method is the real issue here. Components should be whitelisted for getting moved over to the new entity.

2023-07-19 21:04 UTC, EmoGarbage404 commented
why is it even polymorphing an entity instead of just randomizing the appearance? It's like one function call to do so.

2023-07-19 21:04 UTC, PrPleGoo commented on Resources/Prototypes/Entities/Mobs/Player/human.yml
> +    - type: NukeOperative
Fix the polymorph method or fix the implant.

2023-07-19 21:05 UTC, PrPleGoo commented
> why is it even polymorphing an entity instead of just randomizing the appearance? It's like one function call to do so.

A wizzard polymorphing a nukeops into a chicken and back should not cause the same issue I think.

2023-07-19 22:01 UTC, Arendian commented
> A wizzard polymorphing a nukeops into a chicken and back should not cause the same issue I think.

Nuclear operatives can safely all polymorph without the round ending, the issue is that whenever an operator dies the game starts a check to see if it was the last operative. If it can't find any entity in an unpaused map with the NukeOperative component it will end the round. The original bodies with the NukeOperative component are placed in a paused map upon polymorphing  so they won't be seen by the check.
This PR is a bandaid to at least remove the big issue of rounds ending too early while I try to rework it. 
Another option is temporarily disabling the ability to buy the implant for nukies.

2023-08-10 19:37 UTC, AJCM-git requested changes
The actual fix is to just make the implant call `HumanoidAppearanceSystem.LoadProfile` (using a profile from `HumanoidCharacterProfile.RandomWithSpecies`) instead of using polymorphing (fixing polymorph roles has to do with moving em to the mind, but thats another thing), if thats not doable then just remove the implant for now

2023-08-13 16:56 UTC, closed without merging