allow richtext on papers + edit premade documents
space-wizards/space-station-14 pull request #18154
Opened 2023-07-19 18:51 UTC by onoira

## About the PR

let players markup their fancy papers _and_ edit existing ones (character sheet, books, …). it is not possible to edit existing documents today. includes a guidebook entry ('Writing').

should be checked for regressions to https://github.com/space-wizards/space-station-14/pull/17786 (_i didn't see any_)

Known issues:

- [x] `KeybindTag` is still usable for some reason
- [x] `ColorTag` doesn't work on paper
- [x] ~~markup-only changes sometimes aren't saved (but you can temporarily change the text as a workaround)~~ (can't reliably reproduce)

Depends on https://github.com/space-wizards/RobustToolbox/pull/4187

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, ~~**or** this PR does not require an ingame showcase~~

![image](https://github.com/space-wizards/space-station-14/assets/73342011/a835bac3-9c96-4c94-82ff-94495d778701)
![image](https://github.com/space-wizards/space-station-14/assets/73342011/78e1313f-026c-4324-8b1e-951f3c93edd3)
![image](https://github.com/space-wizards/space-station-14/assets/73342011/33c9433d-4303-4ec2-8a09-1f08ab9c3276)

**Changelog**

:cl:
- fix: Nanotrasen no longer uses disappearing ink for official books and documents. These can now be modified.
- add: New pen technology enables stylish ways of writing. See the guidebook for more info.

2023-07-19 19:26 UTC, mirrorcult commented
test fail is erroneous

2023-07-21 08:19 UTC, juliangiebel requested changes
> caveats: (I don't consider any of these blockers)
>
> KeybindTag is still usable for some reason.
> ColorTag doesn't work on paper.
> markup-only changes sometimes aren't saved, but you can temporarily change the text as a workaround.

Those should be fixed before merging this PR imo.

The color not working might be because of the style that gets applied to paper `RichTextLabel`
```cs
  Element<RichTextLabel>().Class("PaperWrittenText")
      .Prop(Label.StylePropertyFont, notoSans12)
      .Prop(Control.StylePropertyModulateSelf, Color.FromHex("#111111")),
```

2023-07-23 14:21 UTC, moonheart08 commented
> > caveats: (I don't consider any of these blockers)
> > KeybindTag is still usable for some reason.
> > ColorTag doesn't work on paper.
> > markup-only changes sometimes aren't saved, but you can temporarily change the text as a workaround.
> 
> Those should be fixed before merging this PR imo.
> 
> The color not working might be because of the style that gets applied to paper `RichTextLabel`
> 
> ```cs
>   Element<RichTextLabel>().Class("PaperWrittenText")
>       .Prop(Label.StylePropertyFont, notoSans12)
>       .Prop(Control.StylePropertyModulateSelf, Color.FromHex("#111111")),
> ```

Agreeing with Julian, especially as more markup gets added for use in guides/etc. Last thing we need is for players to be able to insert UI elements like links when those are introduced.

2023-07-27 08:56 UTC, juliangiebel approved these changes
Looks good to me 👍

2023-08-13 03:05 UTC, metalgearsloth commented on Content.Server/Paper/PaperSystem.cs
> +                paperComp.Content = args.Text;
Server should be validating the text, no?

2023-08-22 11:50 UTC, merged