[Tweak] Pen are wearable on ear
space-wizards/space-station-14 pull request #18386
Opened 2023-07-27 23:48 UTC by lzk228

## About the PR

Requires #18384 

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Spessmens learned to put the pen behind their ear.

2023-07-28 00:23 UTC, UbaserB commented
I have a questions. Are other pens like cybersun pens and explosive/hypo allowed to be placed on the ear?

2023-07-29 13:25 UTC, ficcialfaint requested changes

2023-07-29 13:25 UTC, ficcialfaint commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
> +    - earr
```suggestion
    slots:
    - ears
```

2023-07-29 17:42 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
> +    - earr
read pr desc pls

2023-07-29 19:14 UTC, ficcialfaint commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
> +    - earr
eh aight

2023-08-02 13:53 UTC, closed without merging