Emaggable protolathe
space-wizards/space-station-14 pull request #18456
Opened 2023-07-30 14:00 UTC by ubis1

## About the PR

Now you can emag protolathe to get access to craft some things from the armory research tab. However, to get the access to this things, you still need to research the technolgy. 

List of protolathe emaggable recipes:
      - ExplosivePayload
      - WeaponLaserCarbine
      - WeaponAdvancedLaser
      - WeaponLaserCannon
      - WeaponXrayCannon
      - WeaponTaser
      
**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

sry for shitquality  (of vid and code) :(

https://github.com/space-wizards/space-station-14/assets/140386474/63490cb7-9df8-47a8-adad-cec0fee2025a

**Changelog**

Syndicate agents has reported that their EMAGs are now able to interact with protolathe, giving the access to some recipes from armory tech tab.

:cl:
- add: Added the posibility to be emagged to lathes; added the list of emaggable recipies to protolathe

2023-07-30 14:17 UTC, ficcialfaint commented
the CL seems to have logical and grammar mistakes, perhaps making it `Lathes can be emagged now; emaggable recipes list has been added for protolathes`

2023-07-30 14:34 UTC, EmoGarbage404 requested changes

2023-07-30 14:34 UTC, EmoGarbage404 commented on Content.Server/Lathe/LatheSystem.cs
> +            SubscribeLocalEvent<LatheComponent, GotEmaggedEvent>(OnEmagged);
handle this in `SharedLatheSystem`: the reason you have to do the popup yourself is because of prediction issues due to being server-side.

2023-07-30 14:34 UTC, EmoGarbage404 commented on Content.Server/Lathe/LatheSystem.cs
> +            _audio.PlayPvs(component.EmaggedSound, uid);
A few things:
- no need to check for being powered. As far as i can tell, most EMAG functions don't require that.
- You don't need to add the EmaggedComponent yourself
- The popup will get played correctly if this event is handled in the shared system

2023-07-30 14:34 UTC, EmoGarbage404 commented on Resources/Locale/en-US/lathe/components/lathe-component.ftl
> +lathe-component-got-emmaged = Something zaps inside the machine
like i said, you can remove this because EmagSystem handles this already when used properly.

2023-07-30 14:34 UTC, EmoGarbage404 commented on Content.Shared/Lathe/LatheComponent.cs
> +        public readonly List<string> EmagRecipes = new();
This should be a separate component, something like `EmagLatheRecipesComponent`.

Then you can define dynamic and static recipes on that component and just subscribe to `LatheGetRecipesEvent`. That way, you could have both static recipes and ones that only unlock when you also research the required technology.

2023-07-30 14:34 UTC, EmoGarbage404 commented on Content.Server/Lathe/LatheSystem.cs
> +                    continue;
this condition should just be checked outside of the loop with a return statement.

2023-08-04 02:34 UTC, EmoGarbage404 commented on Content.Shared/Lathe/SharedLatheSystem.cs
> +    }
this should be a subscription on the EmagLatheRecipesComponent, as emagged a regular lathe with no extra recipes shouldn't do anything.

2023-08-05 08:40 UTC, JoeHammad1844 commented
could you make the autolathe emaggable and make it dispense ammo?

2023-08-05 09:26 UTC, metalgearsloth requested changes

2023-08-05 09:26 UTC, metalgearsloth commented on Content.Shared/Lathe/LatheComponent.cs
> +
Separate file please, also none of the recipes are networked (use AutoNetworkedField / AutoGenerateComponentState is probably easiest).

2023-08-05 09:26 UTC, metalgearsloth commented on Content.Server/Lathe/LatheSystem.cs
> +            {
Just invert the if and you can reduce the indentation.

2023-08-05 21:06 UTC, EmoGarbage404 approved these changes

2023-08-07 14:20 UTC, metalgearsloth approved these changes

2023-08-07 14:21 UTC, merged