[ADD] Melee weapon - Chainsaw
space-wizards/space-station-14 pull request #18538
Opened 2023-08-01 18:33 UTC by NULL882

## About the PR

New kind of homemade weapon !

Now you can create a new weapon (exclusively for self-defense, honestly) with which no one will stop you.

**Media**

![image](https://github.com/space-wizards/space-station-14/assets/104377798/eaab4eba-bc6a-4ba2-9a80-7f1ce26b4240)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Makeshift chainsaw and standart chainsaw.
- add: Standart chainsaw added to Uplink for 14 TC.

2023-08-01 19:17 UTC, Just-a-Unity-Dev commented
gchainsaw.rsi isn't green on the inhands

2023-08-01 19:19 UTC, deltanedas commented
- standard not standart
- makeshift insanely cheap you can take apart a few tables sand make a chainsaw

2023-08-01 19:24 UTC, deltanedas requested changes

2023-08-01 19:24 UTC, deltanedas commented on Content.Server/Chainsaw/Systems/ChainsawSystem.cs
> +            SoundSystem.Play(comp.ActiveSound.GetSound(), playerFilter, comp.Owner, AudioHelpers.WithVariation(0.5f));
SoundSystem deprecated

2023-08-01 19:24 UTC, deltanedas commented on Content.Server/Chainsaw/Systems/ChainsawSystem.cs
> +            if (EntityManager.TryGetComponent<AppearanceComponent>(comp.Owner, out var appearance) &&
TryComp

2023-08-01 19:24 UTC, deltanedas commented on Content.Server/Chainsaw/Systems/ChainsawSystem.cs
> +            comp.Activated = false;
this might need dirty not sure

2023-08-01 19:24 UTC, deltanedas commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 14
this is nearly same price as dsword with no reflection, even if 33 damage

2023-08-01 19:24 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/chainsaw.yml
> +  - type: Chainsaw
this seems to be duping wielded logic

2023-08-01 19:25 UTC, NULL882 commented
> Is the recipe only 3 plasteel and 5 cable? That seems way too easy for a melee weapon that strong.

any suggestions about crafting?

2023-08-01 19:47 UTC, Emisse commented
we have another chainsaw pr up currently i was thinking of not having it be obtainable outside of chaplain uplink/salvage or expedition rewards

2023-08-02 12:29 UTC, ficcialfaint commented
Changelogs should include a verb:
❌ - add: A cool item
✅ - add: Added a cool item

2023-08-05 04:34 UTC, metalgearsloth commented
First come first served https://github.com/space-wizards/space-station-14/pull/17743

2023-08-05 04:34 UTC, closed without merging