Printable oxy tanks
space-wizards/space-station-14 pull request #18706
Opened 2023-08-05 14:09 UTC by JoeHammad1844

ive been sitting on this so longa ton of stuff has been added that just arent in this yml so I will need to manually add them

## About the PR

adds emergency, extended emergency and double emergency oxygen tanks to the autolathe

by the way ive been sitting on the code for this so long that a bunch of stuff thats been added isnt in the YML yet so i need to quickly manually re add them

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: JoeHammad
- add: The dark secrets of creating oxygen tanks has been revealed to the cargo department

2023-08-05 14:11 UTC, deltanedas commented
theres no reason to print smaller ones when its just a few steel more for the vastly superior option
also cl is wrong sci hss an autolathe and sometimes engi

2023-08-05 14:12 UTC, deltanedas requested changes

2023-08-05 14:12 UTC, deltanedas commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> -      - ModularReceiver
i before e except after c

2023-08-05 14:17 UTC, deltanedas commented
also webedit ops :trollface:

2023-08-05 14:17 UTC, JoeHammad1844 commented
what the fuck is an editweb

2023-08-05 14:20 UTC, JoeHammad1844 commented
![image](https://github.com/space-wizards/space-station-14/assets/130668733/a4d36879-7524-462d-af38-eafec26a16f6)
hermm

2023-08-05 14:22 UTC, JoeHammad1844 commented
null value ops

2023-08-05 14:22 UTC, JoeHammad1844 commented
ss14 version of john howard: captain goes for a space walk and disappears

2023-08-05 14:25 UTC, metalgearsloth commented
> ss14 version of john howard: captain goes for a space walk and disappears

Are you thinking of Harold Holt?

2023-08-05 14:26 UTC, deltanedas commented
((gaming refren)

2023-08-05 14:29 UTC, JoeHammad1844 commented
yeah probably

2023-08-05 14:31 UTC, JoeHammad1844 commented
![image](https://github.com/space-wizards/space-station-14/assets/130668733/67ce02d0-8c4e-4273-9ea1-56032bedd99e)
zamn okay, what does this mean?

2023-08-05 14:44 UTC, deltanedas commented
ignore

2023-08-05 14:46 UTC, JoeHammad1844 commented
Odd

2023-08-05 15:03 UTC, UbaserB commented
> theres no reason to print smaller ones when its just a few steel more for the vastly superior option
> also cl is wrong sci hss an autolathe and sometimes engi

you forgot about spiders

2023-08-05 15:05 UTC, deltanedas commented
yes and spiders will print double emergency tanks theres no reason to print smaller ones

2023-08-05 15:14 UTC, JoeHammad1844 commented
you're probably right but it just feels wrong not to, you know? someone might just like one aesthetically, I get your point, but I also don't see a reason why not to include it

2023-08-05 16:34 UTC, KaiShibaa commented
People would powergame and only grab the double emergency ones because it makes the other two redundant.

There's a reason they're rarely mapped.

2023-08-05 21:00 UTC, EmoGarbage404 commented
it seems weird that all of these are directly available at any autolathe.

Even if a tank has double capacity, it should have a cost that is greater than double since it has the added advantage of only taking up a single inventory slot.

Additionally, I think printing these is very bloat-y considering the autolathe is already full of random shit and oxygen tanks are extremely plentiful.

quite frankly, this just looks like your other prs trying to give salvage double extended emergency tanks but in another set of clothes.

2023-08-06 00:31 UTC, JoeHammad1844 commented
not entirely
you can just go down to atmos and ask for a bigger oxygen tank and get it for free, they might even fill it up more for you.
the ones that you can print start empty but you could just find oxygen tanks in maints, assuming cargo didn't already steal them all

also, I was trying to give salv the single extended tank not the double extended tank

2023-08-06 05:11 UTC, EmoGarbage404 commented
Considering these items are direct upgrades, they should not be available roundstart in an easily accessible / replenishable manner.

We've additionally rejected several other PRs which sought to similarly make these items more easily acquired.

Due to the combined benefits of having a significantly higher capacity while simultaneously fitting in a pocket, these should not be common or able to produced in any way.

closing this.

2023-08-06 05:11 UTC, closed without merging