Updated taxibot.png
space-wizards/space-station-14 pull request #18837
Opened 2023-08-07 20:12 UTC by Diebeck

## About the PR

Updates the taxibot textures to be newer and fancier.

**Media**

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Updated Taxibot sprites

2023-08-07 21:42 UTC, Emisse commented
update the meta.json to include that you tweaked the sprites

2023-08-08 12:58 UTC, Diebeck commented
Ive done it now, anything else to do?

2023-08-08 20:08 UTC, Flareguy commented
Please add images showing this sprite in-game.

2023-08-08 20:10 UTC, ficcialfaint requested changes

2023-08-08 20:10 UTC, ficcialfaint commented on Resources/Textures/Mobs/Silicon/Bots/taxibot.rsi/meta.json
> +  "copyright": "taxibot drawn by Diebeck",
```suggestion
  "copyright": "taxibot drawn by FillerVK, modified by Diebeck",
```

2023-08-09 06:58 UTC, FillerVK commented
It looks good, but there are a few comments.
- Could you please make this "eye" the way it was before, it just doesn't fit in with the rest of the bots.
- TaxiBot looks like a jeep from the side, not a small taxi robot
- I don't think it's cool that you made it more "square"
- Maybe reduce the headlights and leave the taxi markings?

Thank you if you do this!

2023-08-31 01:15 UTC, EmoGarbage404 commented
@Diebeck is this pr still being worked on?

2023-09-03 03:25 UTC, AJCM-git commented
re-open once you come back

2023-09-03 03:25 UTC, closed without merging