light refactor and nuke spinny light
space-wizards/space-station-14 pull request #18869
Opened 2023-08-08 10:56 UTC by deltanedas

## About the PR
- in C.Sh.Light renamed Component to Components WHO DID THIS AND WHY
- general .Owner refactor and what not
- move emergency light spinning into its own component, RotatingLightComponent
- nuke has a spinny light when armed

fixes #18861

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Armed nuclear bombs now have warning lights. Set off a nuke and watch the light spin!!!

2023-08-08 11:03 UTC, PJB3005 commented
> nuke has a spinny light when armed

Can you also make it so that the nuke has different sprite states for "armed" and "about to blow"? I know it does in SS13.

2023-08-08 11:04 UTC, deltanedas commented
i will try steal sprite then add an appearance thing for it

2023-08-08 11:23 UTC, dmnct commented
At some point we will probably want to add other types of animated lights, like blinking, pulsating etc
Will we then create a different system and component for every kind of different light animations we could think of, (potentioally ending with something having 3-4 different LightComponents for it to both rotate and flicker and change color over time) or should we just maybe go ahead of that and call this AnimatedLightSystem and Component?

2023-08-08 11:24 UTC, deltanedas commented
well blinking lights is part of a different light animation thing right, flashlight and flares use it

2023-08-08 11:32 UTC, deltanedas commented
also at the very least i have currently unhardcoded the speed but i think putting the animation itself in prototypes would be annoying

2023-08-08 20:51 UTC, PJB3005 commented on Content.Server/Nuke/NukeSystem.cs
> +        _transform.SetCoordinates(uid, nukeXform, nukeXform.Coordinates.SnapToGrid());
The better fix is this:
![image](https://github.com/space-wizards/space-station-14/assets/8107459/9f340e2c-a986-4a37-b458-b90a90044a63)

I ran into this while trying out the nuke myself just now. Not your code.

2023-08-08 21:10 UTC, Partmedia requested changes
This superfluous namespace change from `using Content.Shared.Light.Component` to `using Content.Shared.Light.Components` will likely cause unnecessary pain for forks.

2023-08-08 21:20 UTC, deltanedas commented on Content.Server/Nuke/NukeSystem.cs
> +        _transform.SetCoordinates(uid, nukeXform, nukeXform.Coordinates.SnapToGrid());
using your troll then

2023-08-08 21:21 UTC, deltanedas commented
it causes pain for upstream on its own and will forever unless its changed may as well do it now than never

2023-08-08 21:53 UTC, rbertoche commented
how does an s causes pain?
also please stop calling changes that break public APIs refactors
it's simply a misnomer, if well named stuff is taken in consideration

2023-08-09 05:07 UTC, JoeHammad1844 commented
rotate the light source from flashlights by 90 degrees so that it lines up with the source on the sprite, but that may be out of scope

2023-08-10 01:12 UTC, metalgearsloth commented
> This superfluous namespace change from Content.Shared.Light.Component to Content.Shared.Light.Components will likely cause unnecessary pain for forks.

Both the client and server sides suffix with s so I imagine someone forking the game right now would appreciate consistency over legacy.

2023-08-19 18:28 UTC, Partmedia commented
As discussed at the 2023-08-19 maintainer meeting, please split up the namespace and refactoring changes into a separate PR, and add detailed information for #codebase-changes. Keep the actual content/feature changes in this PR.

2023-08-19 19:31 UTC, closed without merging