Revert "[Trait] Wheelchair bound"
space-wizards/space-station-14 pull request #18882
Opened 2023-08-08 15:51 UTC by QuietlyWhisper

Reverts space-wizards/space-station-14#18785
related to #18874

Currently being abused to bypass stuns. Should be remerged when that vehicle system is fixed imo

2023-08-08 15:57 UTC, Equivocateur commented on Resources/Prototypes/Traits/disabilities.yml
> -- type: trait
Ya could've just commented this block out

2023-08-08 16:37 UTC, EmoGarbage404 commented
Just disable the trait and leave in all the code

2023-08-08 18:09 UTC, Partmedia requested changes
Yes, please just disable the trait.

2023-08-09 00:28 UTC, QuietlyWhisper commented
Going to open a new pr to do it properly

2023-08-09 00:28 UTC, closed without merging