Make wielding precede cycling in event subs
space-wizards/space-station-14 pull request #18915
Opened 2023-08-09 14:31 UTC by Vordenburg

[gun-in-hand.webm](https://github.com/space-wizards/space-station-14/assets/114301317/e5724c7e-b23b-482e-8a3f-7feefcb443ea)

Resolves #17077

2023-08-13 07:11 UTC, metalgearsloth requested changes

2023-08-13 07:11 UTC, metalgearsloth commented on Content.Shared/Wieldable/WieldableSystem.cs
> +    public bool AttemptWield(EntityUid used, WieldableComponent component, EntityUid user)
Should be TryWield instead.

2023-08-13 07:11 UTC, metalgearsloth commented on Content.Shared/Wieldable/WieldableSystem.cs
> +    public bool AttemptUnwield(EntityUid used, WieldableComponent component, EntityUid user)
As above.

2023-08-14 00:05 UTC, AJCM-git approved these changes

2023-08-14 22:45 UTC, merged