move hot plate item placement stuff into its own system
space-wizards/space-station-14 pull request #18923
Opened 2023-08-09 19:20 UTC by deltanedas

## About the PR
can be used for plates or something in the future

**Media**
hotplate still work trust
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

2023-08-10 00:44 UTC, Partmedia commented
- Please justify the YAML-breaking change by giving examples of future systems that could conceivably use the item placement system.
- Or, allow the old solution heater system datafields to still work by making the solution heater component inherit from the new item placement system.
- Please include a video demonstrating the tests done to make sure that the hot plate still works.

2023-08-10 00:52 UTC, keronshb requested changes
I agree please make a video.

Also I also feel like while yes generalizing something is good because it makes it less tightly coupled, there should be a reason for this change. A reason being another mechanic that's going to use it added with this PR.

2023-08-10 02:51 UTC, 0x6273 commented
Could this work for the artifact scanner also?

> Or, allow the old solution heater component datafields to still work by making the solution heater component inherit from the new item placement component.

That's dumb, don't do this.

2023-08-10 03:33 UTC, metalgearsloth commented on Content.Shared/Placeable/ItemPlacerComponent.cs
> +[RegisterComponent]
networked too

2023-08-10 05:11 UTC, deltanedas commented
i want to eventually use this for pro plates, could also work for artifacts

2023-08-15 20:39 UTC, 0x6273 commented
Calling this `ItemPlacerComponent` is maybe not ideal since it works with any entity and not just items.

2023-08-15 22:59 UTC, deltanedas commented
i dont like the name overall but im not good with naming things
it integrates with PlaceableSurface tho which is for items

2023-08-16 23:46 UTC, mirrorcult requested changes
why not entirely merge `ItemPlacer` with `PlaceableSurface`?

2023-08-16 23:46 UTC, mirrorcult commented
code looks fine besides that though

2023-08-17 03:59 UTC, deltanedas commented
doesnt make sense to track placed items for inert things like tables that are still placeable but have no logic

2023-08-20 00:36 UTC, mirrorcult commented
fair enough i suppose

2023-08-20 00:36 UTC, mirrorcult approved these changes

2023-08-20 00:37 UTC, merged