Content update for NetEntities
space-wizards/space-station-14 pull request #18935
Opened 2023-08-10 03:17 UTC by metalgearsloth

Requires https://github.com/space-wizards/RobustToolbox/pull/4252

Adding helper methods to EntityManager to make conversion easy too.

2023-08-28 20:12 UTC, ElectroJr requested changes
Only a partial review (100/486). I left comments on any comp states that should get updated to somehow handle unknown entities. Some of those comp states might work fine as is, but its probably safer to still update them and set good examples. E.g., the rider comp state implies that the rider is a child of the vehicle, so the vehicle should never be an unknown entity.

2023-08-28 20:12 UTC, ElectroJr commented on Content.Client/Vehicle/VehicleSystem.cs
> +        var entity = GetEntity(state.Entity);
Needs to handle unknown net ids

2023-09-02 19:30 UTC, ElectroJr commented on Content.Server/Anomaly/AnomalySystem.Commands.cs
> +        if (!NetEntity.TryParse(args[0], out var uidNet) || !TryGetEntity(uidNet, out var uid))
Possibly worth adding a helper method for this?

2023-09-02 19:35 UTC, ElectroJr commented on Content.Server/Atmos/EntitySystems/GasTileOverlaySystem.cs
> +                ev.UpdatedChunks[GetNetEntity(grid)] = dataToSend;
you already have netGrid here

2023-09-02 19:54 UTC, ElectroJr commented on Content.Shared/DoAfter/SharedDoAfterSystem.cs
> +        }
Weh

2023-09-06 09:03 UTC, metalgearsloth commented on Content.Shared/DoAfter/SharedDoAfterSystem.cs
> +        }
debugging be like

2023-09-10 23:42 UTC, ElectroJr approved these changes

2023-09-10 23:42 UTC, merged