Add ability to burn papers +Flammable tweaks.
space-wizards/space-station-14 pull request #18955
Opened 2023-08-10 11:28 UTC by mhamsterr

Let it burn! Revival of #10373 
Most of the code was done by [JustinTrotter](https://github.com/JustinTrotter) in his pr and then modified by me (JustinTrotter, please leave a comment here / find me on discord if you want me to close this pr / change something). 

## About the PR

+ Now you can specify if entity should ignite because of contact with isHot entities.
+ Now you can specify the amount of firestacks that will be applied to entity when ignited.
+ Now you can specify if entity will lose it's firestacks because of interaction with other entities.

+ Papers can now burn to ash.
  + But fire cannot spread between them or any other items next to them

**Media**

https://github.com/space-wizards/space-station-14/assets/81412348/b5aae678-9aa3-4a62-8345-044aa61a022f

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: JustinTrotter & mhamster
- tweak: Added ability to burn paper to get ash. Very useful.

2023-08-10 11:30 UTC, metalgearsloth submitted a review, later dismissed

2023-08-10 12:16 UTC, mhamsterr commented on Content.Server/Atmos/Components/FlammableComponent.cs
>      }
Like that in last commit? (i am at very low level at c# actually, sorry)

2023-08-14 01:05 UTC, AJCM-git requested changes

2023-08-14 07:44 UTC, Emisse approved these changes

2023-08-14 13:04 UTC, UbaserB commented
walking over it should set you on fire

2023-08-14 13:22 UTC, mhamsterr commented
> walking over it should set you on fire

sounds fair. will try to implement it before merge (if it is planned soon)

2023-08-14 15:19 UTC, mhamsterr commented
> > walking over it should set you on fire
> 
> sounds fair. will try to implement it before merge (if it is planned soon) (and will do another pr if i don't make it on time)

actually nevermind, will do it in a separate pr

2023-08-14 19:42 UTC, AJCM-git approved these changes

2023-08-14 19:45 UTC, merged