Speed boots and their research
space-wizards/space-station-14 pull request #19013
Opened 2023-08-12 09:38 UTC by FillerVK

## About the PR

- New Speed Boots have been added. 
- Added new research to produce them.
- Their production will cost:
   -  1000 steel
   -    700 plastic

- Added clown Speed Boots, as well as their crafting, they can be made:
    -   One clown shoes
    -   One speed boots

**Media**

https://github.com/space-wizards/space-station-14/assets/130583174/bb650d3e-da2a-4e69-8710-16005aec0c16

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

2023-08-12 09:54 UTC, lzk228 reviewed
most bruh pr after #15948

2023-08-12 09:54 UTC, lzk228 commented on Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
> +    sprite: Clothing/Shoes/Boots/laceups.rs
```suggestion
    sprite: Clothing/Shoes/Boots/laceups.rsi
```

2023-08-12 10:24 UTC, Errant-4 commented on Resources/Prototypes/Entities/Clothing/Shoes/speedboots.yml
> +  parent: ClothingShoesBaseButcherable
THIS is the real crime here

2023-08-12 10:48 UTC, Tunguso4ka commented
should be tier 3 research and a little bit slower imo.

2023-08-12 11:22 UTC, FillerVK commented
> should be tier 3 research and a little bit slower imo.

I have already moved them to tier 3 and also made them slower🙂

2023-08-12 11:32 UTC, Errant-4 commented on Resources/Prototypes/Entities/Clothing/Shoes/speedboots.yml
> +  id: ClothingShoesSpeedBootsClown
Why are you not deriving this from ClothingShoesSpeedBoots, and only specifying the two or so differences?

2023-08-12 12:49 UTC, FillerVK commented on Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
> +      - id: ClothingShoesSpeedBoots
Because I remove MagBoots of blinding

2023-08-12 12:49 UTC, FillerVK commented on Resources/Prototypes/Entities/Clothing/Shoes/magboots.yml
> -
Why do we need them if we have Speed Boots now?

2023-08-12 13:56 UTC, EmoGarbage404 requested changes

2023-08-12 13:56 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Clothing/Shoes/magboots.yml
> -    price: 3000
keep these or else you're going to break maps and downstreams. Eventually these should have the blinding effect added back, which will help them be separate.

2023-08-12 13:56 UTC, EmoGarbage404 commented on Resources/Prototypes/Recipes/Construction/clothing.yml
> +  description: Modified SpeedBoots specifically for the clown. Now the officers will never catch up with you!
```suggestion
  description: Modified speed boots specifically for the clown. Now the officers will never catch up with you!
```

2023-08-12 13:56 UTC, EmoGarbage404 commented on Resources/Prototypes/Research/experimental.yml
> +  tier: 3
no point that a 10% speed boost should be tier 3. Experimental already has too many t3 techs already

2023-08-12 13:56 UTC, EmoGarbage404 commented on Resources/Prototypes/Research/experimental.yml
> +  cost: 15000
```suggestion
  cost: 7500
```
really steep for one item

2023-08-12 16:15 UTC, LankLTE commented
Experimental already has two T3s, it doesn’t need more. I’d move it to a different tech tree.

2023-08-13 07:21 UTC, Emisse commented
ok these are gonna need to use battery charge for their speed up ability, speed is probably the most important combat stat in the game at the moment and this is the only way i can think to balance this

2023-08-13 23:30 UTC, AJCM-git requested changes
Make them use batteries

2023-08-16 20:18 UTC, DrSmugleaf commented
> most bruh pr after #15948

@lzk228 Next time you post a pointless and abrasive message like this on the repo you are getting repo banned.

2023-08-16 20:31 UTC, NakataRin commented
Maybe tweak its cost a bit? It seems extremely cheap for such a powerful type of buff as movement speed. 
I'm not saying to boost to cost 100k steel, but maybe some "rare" resources like uranium?

2023-08-17 07:14 UTC, FillerVK commented
> Maybe tweak its cost a bit? It seems extremely cheap for such a powerful type of buff as movement speed. I'm not saying to boost it to cost 100k steel, but maybe some "rare" resources like uranium?

Yes, it's a good idea, I'm also thinking of moving it to tier 3 of industrial technologies.

2023-08-31 01:27 UTC, metalgearsloth requested changes

2023-08-31 01:27 UTC, metalgearsloth commented on Resources/Prototypes/tags.yml
> +
This should go before ClothMade due to alphabetical.

2023-08-31 01:27 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Clothing/Shoes/speedboots.yml
> +    enabled: true
Make it take power, should just need PowerCellDrawComponent + PowerCellComponent (I think I made a parent you can use for this) and a generic component for it.

2023-09-23 02:31 UTC, AJCM-git commented
@FillerVK you coming back to this?

2023-09-26 14:05 UTC, FillerVK commented
> @FillerVK you coming back to this?

Yeah, I'm going to get back to it, I'm just a little busy right now.

2023-09-26 15:21 UTC, Yousifb26 commented
Imo these need the mag boot quality removed, these completely trivialize advanced mag boots and possibly even add increased stun time to slips (if that’s possible) as well to the aforementioned batteries (the increased slip for logic and balance(again if that’s even a thing that can be done)) but just my opinion if there get merged

2023-10-17 13:06 UTC, metalgearsloth commented
Re-open if you come back to this.

2023-10-17 13:06 UTC, closed without merging