Dead mobs can no longer shoot guns
space-wizards/space-station-14 pull request #19020
Opened 2023-08-12 17:03 UTC by Errant-4

## About the PR

RIP, gundead

**Media**
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Central Command wishes to assure all employees that recent sightings of dead crewmembers firing their weapons were completely fictional.

2023-08-12 18:40 UTC, metalgearsloth requested changes

2023-08-12 18:40 UTC, metalgearsloth commented on Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
> +
This should be under AttemptShoot so it works for NPCs as well, not just the network event handler.

2023-08-13 23:33 UTC, AJCM-git approved these changes

2023-08-14 19:32 UTC, Errant-4 commented
I think the "awaiting changes" tag was added by accident? It was removed and then added back on the same line

2023-08-16 19:00 UTC, Partmedia submitted a review, later dismissed
Thank you for your fix.

2023-08-16 19:00 UTC, Partmedia commented on Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
> +            _mobState.IsIncapacitated(user))
It would probably catch more edge cases if this call was replaced with ActionBlockerSystem's `CanUseHeldEntity`.

2023-08-21 18:27 UTC, merged