removing the health analyzer from medics' pda
space-wizards/space-station-14 pull request #19180
Opened 2023-08-15 18:28 UTC by Verslebas

## About the PR

It's not logical that the pda has a health analyzer, it devalues the regular analyzer because the analyzer in the pda even doesn't require a battery.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Verslebas
- remove: Health analyzer from medics' pda

2023-08-15 18:36 UTC, LankLTE commented
1984
In all seriousness I would advise either making this a cartridge or putting a medium battery in the health analyzer. At the moment they run out of power quite fast, and do serve a purpose in being usable by anyone who isn’t a doctor. If medbay is relying on them they shouldn’t be running out of power 24/7 esp. since not all medbays have battery chargers

2023-08-15 18:41 UTC, Verslebas commented
> 1984
> In all seriousness I would advise either making this a cartridge or putting a medium battery in the health analyzer. At the moment they run out of power quite fast, and do serve a purpose in being usable by anyone who isn’t a doctor. If medbay is relying on them they shouldn’t be running out of power 24/7 esp. since not all medbays have battery chargers

I can replace the battery, it is a good idea, I also don't like that analyzers run out of battery quickly, but a medical scanner in pda is weird

2023-08-15 19:15 UTC, EmoGarbage404 commented
> If medbay is relying on them they shouldn’t be running out of power 24/7 esp. since not all medbays have battery chargers

sounds like a reason for them to get better batteries and for mappers to map in chargers.
just because something is the status quo doesn't mean it should be maintained.

2023-08-15 19:43 UTC, Aisu9 commented
> > If medbay is relying on them they shouldn’t be running out of power 24/7 esp. since not all medbays have battery chargers
> 
> sounds like a reason for them to get better batteries and for mappers to map in chargers. just because something is the status quo doesn't mean it should be maintained.

Because mappers had no reason to map charger? what about the defibrillators that were map without chargers in medbay?

2023-08-15 19:49 UTC, LankLTE commented
> sounds like a reason for them to get better batteries and for mappers to map in chargers. just because something is the status quo doesn't mean it should be maintained.

You can literally find medium capacity batteries in the super readily-available flashlights spread across the station. I’m only suggesting health scanners start with one because it’s simple to replace but sort of screws over people who don’t know they can / should. There has also been a reason (defibs) for chargers to be mapped for months and they still aren’t on a few stations

2023-08-15 20:39 UTC, Verslebas commented
write it like that?

> If this does go forward, please revise your Changelog entry according to the Changelog guidelines: https://docs.spacestation14.io/en/getting-started/pr-guideline#changelog

2023-08-15 20:58 UTC, Emisse commented
can you change health analyzer back to small battery, incentivizes people actually going and getting better batteries + most maps have medbays with rechargers

2023-08-15 22:16 UTC, chromiumboy commented
I think this change should be made, but only once we have a stronger system in place for diagnosing patients via other means

2023-08-16 00:34 UTC, Verslebas commented
> can you change health analyzer back to small battery, incentivizes people actually going and getting better batteries + most maps have medbays with rechargers

Sure

2023-08-16 06:17 UTC, JoeHammad1844 commented
> can you change health analyzer back to small battery, incentivizes people actually going and getting better batteries + most maps have medbays with rechargers

imagine getting shot and there are no medics in medbay because theyre all out getting batteries.

this will also skyrocket the demand for flashlights and science can't print medium capacity batteries without gold (but to be fair they can print ten with one bar)

even if they do they're probably all going to go towards borgs and not the crew

2023-08-16 07:06 UTC, Emisse requested changes

2023-08-16 07:06 UTC, Emisse commented on Resources/Prototypes/Entities/Objects/Specific/Medical/healthanalyzer.yml
> -  parent: [ HandheldHealthAnalyzerUnpowered, PowerCellSlotSmallItem]
keep this small

2023-08-16 07:16 UTC, SonicHDC commented
Maybe better adding something new before removing what's exist?

2023-08-17 03:51 UTC, JoeHammad1844 commented
![image](https://github.com/space-wizards/space-station-14/assets/130668733/4a7dade5-3c8b-4127-abdb-e8432eb6d33b)
I feel we should listen to the audience here. and if you dont, add a health analyzer to every doctors backpacks

2023-09-11 04:28 UTC, Partmedia commented
I think most of the feedback suggests that people would really prefer the PDA scanners to stay. For better or worse, the health analyzers are pretty essential to what MED does because of the lack of other obvious signs of problems. Maybe we can revisit this when there are better ways to diagnose patients.

2023-10-02 20:34 UTC, Partmedia commented
Closing per the previous comment. Please re-open if more discussion is needed on this.

2023-10-02 20:34 UTC, closed without merging