Stunbatons hit only first person when thrown
space-wizards/space-station-14 pull request #19209
Opened 2023-08-16 11:37 UTC by kalane15

## About the PR

Fixed stunnig all mobs in a line when thrown
Closes #19124.
**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Stunbatons hit only first person when thrown

2023-08-17 21:44 UTC, deltanedas commented
why close bowling is awful

2023-08-22 11:20 UTC, metalgearsloth requested changes
Better to just make the entity land after ThrowDoHitEvent is handled instead of this.

2023-08-22 15:30 UTC, kalane15 commented
This should affect all throwable items or stunbatons only? I'm not sure about it.

2023-08-30 02:09 UTC, metalgearsloth commented
> Should this affect all throwable items or stunbatons only? I'm not sure about it.

All of them.

2023-08-30 02:11 UTC, metalgearsloth requested changes

2023-08-30 02:11 UTC, metalgearsloth commented on Content.Shared/Damage/Systems/StaminaSystem.cs
>      }
Add a field to ThrowDoHitEvent on whether the entity should land.

2023-08-30 02:11 UTC, metalgearsloth commented on Content.Shared/Damage/Systems/StaminaSystem.cs
> +        return TakeStaminaDamage(target, component.Damage, staminaComp, uid, sound: component.Sound);
You're resolving staminacomponent twice which is unnecessary, just pass it into the method as it's far cheaper.

Also call it TryCollide instead if you're changing the return type.

2023-09-07 03:36 UTC, metalgearsloth requested changes

2023-09-07 03:36 UTC, metalgearsloth commented on Content.Shared/Throwing/ThrownItemSystem.cs
> +            RaiseLocalEvent(thrown, new ThrowDoHitEvent(thrown, target, component, true), true);
LandAfterHit is an unnecessary field.

2023-09-07 03:36 UTC, metalgearsloth commented on Content.Shared/Damage/Systems/StaminaSystem.cs
> -
If someone's crit they shouldn't be taking more stamina damage so this should stay.

2023-09-07 03:36 UTC, metalgearsloth commented on Content.Shared/Damage/Systems/StaminaSystem.cs
>          return true;
Caller should be handling sound, not stamina system.

2023-09-07 03:36 UTC, metalgearsloth commented on Content.Shared/Damage/Systems/StaminaSystem.cs
> +    }
Stamina shouldn't be tied to mob component.

2023-10-16 11:25 UTC, metalgearsloth commented
@kalane15 are you still working on this

2023-10-16 11:27 UTC, kalane15 commented
unfortunately no

2023-10-16 18:17 UTC, closed without merging