Edit labels behaiviour
space-wizards/space-station-14 pull request #19278
Opened 2023-08-18 09:54 UTC by Fahasor

## About the PR

This PR is a prolongation of #19082
Now labels text don't shown in name of entity (but they still shown in description, it already coded by someone)
Labels don't shown in name field, but they shown in vendomates.
Also some small fixes like adding suffix to jugs and making label text lowercase.

**Media**

https://github.com/space-wizards/space-station-14/assets/70820551/73ab51dc-ecec-4dea-926b-347472b08fbd

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Special medical check of Nanotrasen workers find out that they all have small eye disease. Now labels don't shown in name of objects.

2023-08-18 10:53 UTC, juliangiebel commented
Please don't close and open a new PR because you forgot to commit something. You can use your original one https://github.com/space-wizards/space-station-14/pull/19276

Also change the CL

2023-08-27 19:41 UTC, Fahasor commented
So, i tried resolve merge conflict, but can't reproduce it on my local branch. Merge just goes by a normal way. Branches is up to date with SS14 original repository.

2023-08-28 04:40 UTC, Fahasor commented
Hah, this is not so hard, it just auto merged, but i was confused because git does not show merge conflict to me, but github shows it (shit, this now does not looks like good PR, because it have already merged commit)

2023-08-28 04:41 UTC, Fahasor commented
Is there something bad with CL, then give me feedback please, i think it's normal now

2023-09-15 02:12 UTC, EmoGarbage404 commented on Content.Server/Labels/Label/LabelSystem.cs
> -                _metaData.SetEntityName(uid, label.OriginalName, metadata);
this removes the functionality of the labels changing the name of the entity, which i feel should be preserved

2023-09-15 22:40 UTC, AJCM-git requested changes
Sorry i took so long, but now i have time to deal with this one. Everything but the one review i have is perfect

2023-09-15 22:40 UTC, AJCM-git commented on Content.Server/Labels/Label/LabelSystem.cs
yeah dont remove changing the entity name, if you *really* want to get rid of OriginalName, what you could do is scanning for the CurrentLabel in the name string and removing only that when deleting a label, but that may be very scuffed/unreadable, idk

2023-10-25 13:23 UTC, metalgearsloth commented
Re-open if you come back to this, it looks like something went funky with your merge.

2023-10-25 13:23 UTC, closed without merging