Get rid of CuffSystem, make CuffableComponent update its hand count properly
space-wizards/space-station-14 pull request #1927
Opened 2020-08-26 22:01 UTC by nuke-makes-games

2020-08-26 22:01 UTC, Zumorica approved these changes

2020-08-27 07:56 UTC, RemieRichards commented on Content.Server/GameObjects/Components/GUI/HandsComponent.cs
> +            if (Owner.TryGetComponent<CuffableComponent>(out var cuffable))
😬 big yikes on this

Should probably just be a component message, that `CuffableComponent` can then listen to.

Check out the `EventBus`.

2020-08-27 07:57 UTC, RemieRichards requested changes
Use a component message (see other comment)

2020-08-27 08:08 UTC, RemieRichards commented on Content.Server/GameObjects/Components/GUI/HandsComponent.cs
> +            if (Owner.TryGetComponent<CuffableComponent>(out var cuffable))
Something like:
```cs
    public class HandCountChangedEvent : EntitySystemMessage
    {
        public HandCountChangedEvent()
        {
        }
    }
```

You'd have this here (the line of this comment) in `RemoveHand()`:
```cs
Owner.EntityManager.EventBus.RaiseEvent(EventSource.Local, new HandCountChangedEvent());
```

And anything that cares about this (e.g. `CuffableComponent`) would do:
```cs
Owner.EntityManager.EventBus.SubscribeEvent<HandCountChangedEvent>(EventSource.Local, this, HandleHandCountChange);

...

private void HandleHandCountChange(HandCountChangedEventmessage)
{
	if (message.Entity != Owner)
	    return;
        ... //Do something now you know about the change
}

```

2020-08-27 13:07 UTC, RemieRichards approved these changes
Nice!

2020-08-27 14:33 UTC, DrSmugleaf approved these changes

2020-08-27 14:33 UTC, merged