send popup message to chat
space-wizards/space-station-14 pull request #19364
Opened 2023-08-20 17:30 UTC by onoira

## About the PR

display popup messages in the chat

## Why / Balance

in accordance with the information redundancy principle from the accessibility guidelines:
<https://hackmd.io/PIF3dxZkRS27hIyJM58xLw#Text>

the popup itself still provides an animated alert in the play area, but can also be read later or grab the player's attention if they're looking away from the play area, _that is_ at the chat.

## Technical details

adds a `notice` command that writes a client-side message to the `Visual` ('Actions') channel. `Visual` is filtered out by default.

originally I tried sending this only when the popup target was the player, but this excluded things like _burning your hand_ or _getting injected with a needle_ that seem important. rather than enforce or expect an important popup to always centre on the player character, this assumes that any popup is something intended to be read.

this PR is not concerned with the style or consistency of popup messages; only that they get duplicated to the chat.

yes, I see the deprecation warning on `IConsoleCommand`, but I don't know what to do with that information.
yes, this allows people to talk to themselves in the chat window. I don't know if that's good  or bad.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, ~~**or** this PR does not require an ingame showcase~~

![image](https://github.com/space-wizards/space-station-14/assets/73342011/6ec7e10e-8b76-4f15-b5a7-4f65aaab657a)

<details>
<summary>chat filter</summary>

![image](https://github.com/space-wizards/space-station-14/assets/73342011/3cceabae-8726-4cc3-8435-790b27019526)

</details>

## Breaking changes

n/a

## Changelog

no cl?

2023-08-20 17:36 UTC, lzk228 commented
really like it, but maybe apply some text formatting?

2023-08-20 18:14 UTC, ike709 commented
I think this is chatlog bloat and I'd like a setting to disable it.

2023-08-20 18:14 UTC, mirrorcult commented
this should be opt-in. chat-channel thats disabled by default i think

2023-10-16 20:37 UTC, lzk228 commented
> ready for review

can you update the media please?

2023-10-17 05:47 UTC, metalgearsloth requested changes
I don't understand why we need to roundtrip to server for a local chat message.

2023-10-17 05:47 UTC, metalgearsloth commented on Content.Server/Chat/Commands/NoticeCommand.cs
> +}
Please update to code standards:
1. localisation
2. file-scoped namespace
3. public
4. Use dependencies not resolve.

2023-10-17 05:47 UTC, metalgearsloth commented on Content.Client/Popups/PopupSystem.cs
>          }
How does this work with replays.

2023-10-24 06:24 UTC, metalgearsloth commented on Content.Server/Chat/Commands/NoticeCommand.cs
> +}
Make it a public class not internal please.

2023-10-24 06:26 UTC, metalgearsloth commented on Content.Server/Chat/Commands/NoticeCommand.cs
> +        }
Still needs localising please, everything the client can see needs to be localised.

2023-10-24 06:27 UTC, metalgearsloth commented
> > I don't understand why we need to roundtrip to server for a local chat message.
> 
> popup system is clientside; chat system is serverside. we only want the popups the player can see, so we're only treating the popups that should be drawn.

Actually think I'm a dumbass so please ignore, will check ingame later.

2023-11-25 21:31 UTC, Arteben commented
Is this pull request still relevant?

2023-12-11 12:01 UTC, nok-ko commented
> > Is this pull request still relevant?
> 
> yeah, but i can't presently work on it. i may continue in a few weeks.

Do you still intend to work on this? I would be interested in taking it over if you’re too busy.

2023-12-16 03:38 UTC, nok-ko commented
> > Do you still intend to work on this? I would be interested in taking it over if you’re too busy.
> 
> i plan to work on it this weekend, but if you'd prefer to do it for any reason: i'd be okay handing it off.

In that case, go ahead. I might lurk in the code reviews. :)

2024-01-20 05:01 UTC, metalgearsloth commented
Re-open if you come back to it.

2024-01-20 05:01 UTC, closed without merging