Dropping stops examination
space-wizards/space-station-14 pull request #19398
Opened 2023-08-21 14:40 UTC by kalane15

## About the PR

Title.
## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Dropping item stops its examination

2023-08-21 18:18 UTC, EmoGarbage404 requested changes
does this not stop all examination when you drop an item?

The issue outlines that it should only close the window if you drop the item you are examining.

2023-08-21 18:18 UTC, EmoGarbage404 commented on Content.Client/Examine/ExamineSystem.cs
> +                return;
use iplayermanager to check that the person dropping the item is the local player.

2023-08-21 20:14 UTC, kalane15 commented
you're right, seems fixed now

2023-08-22 04:27 UTC, DrSmugleaf approved these changes

2023-08-22 04:28 UTC, merged