Roboticists
space-wizards/space-station-14 pull request #19400
Opened 2023-08-21 16:23 UTC by KingFroozy

## About the PR

Roboticists coming to the game, introducing their own Job, Bags, PDAs and ID cards, Airlocks, Lockers, and access.
Job Spawn is included, I put my own character there as a reference :3

Roboticists of coure have a job description, as well as all their important stuff. Also the science department's description was slightly changed due to addition of roboticists

I also changed the Robodrobe's and Robotech's deluxe access to  Robotics, and Robodrobe was slightly resprited to match the Robotics style, also adjusted it's inventory to match the Roboticist's clothes.

Roboticists, Research Director, Head of Personnel, and everyone with AA access have access to robotics.

Robotics airlock are: Standard, Standard locked, Glass, Glass locked, Maintenance locked, and secure windoor locked. These airlocks are available to be chosen in spray painter's UI.
Robotics access is visible in the ID card computer and access configurator.

Their lockers contain: A pair of robohands gloves, gasmask, a coat, a headset, a welding mask and a filled utility belt.
Robotics wardrobe's inventory was changed to match the Roboticist's clothes

WARNING: Roboticists are not mapped on any station yet! Any assistance with mapping would be very welcome.

## Why / Balance

Only two (2) roboticists are available to play at the station (As I believe, it should be), because their job isn't that important, but not that useless to have only one roboticist.

Robotics lockers contain a welding mask and a filled utility belt due to many mechs and cyborgs require having a welder and a bunch of tools to complete them.
Roboticist's starter bags contain a standard survival box in it.

To play as roboticist, you have to play in the science department for at least 6 hours.

## Technical details

Content.Shared / Access / components / IdCardComputerComponent.cs was changed to make the robotics access appear in the ID card computer's UI

## Media

![Снимок экрана 2023-08-21 183235](https://github.com/space-wizards/space-station-14/assets/140668342/5f3a22b7-078a-4ad1-a2eb-0b2e763ebde7)

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2023-08-21 16:27 UTC, deltanedas requested changes

2023-08-21 16:27 UTC, deltanedas commented on Resources/Locale/en-US/job/department-desc.ftl
> +department-Science-description = Research new technologies, dangerous artifacts, and build robots.
, and
should be
and

2023-08-21 16:27 UTC, deltanedas commented
also why should senior researcher not have it, senior engi has atmos and senior phys has chem

2023-08-21 16:32 UTC, KingFroozy commented
> also why should senior researcher not have it, senior engi has atmos and senior phys has chem

I changed the thing, since roboticists aren't playable yet. They have to be mapped to require to play as them for the other roles, else it would be impossible to play as Senior Researcher or RD

2023-08-21 16:41 UTC, deltanedas commented
as in access to the doors, not a playtime required

2023-08-21 16:48 UTC, KingFroozy commented
> as in access to the doors, not a playtime requirement

Oh, wait, you're right

2023-08-21 18:46 UTC, EmoGarbage404 commented
Calling a veto on a robotics job.

Quite plainly, robotics is so integrated into the general of science that it doesn't make sense to section it off from the standard job. Separating what few robotics mechanics we have into a separate job when that very same job is forced to do regular scientist work 90% of the time seems rather pointless.

Furthermore, unlike something like atmospherics or chemistry, where there are higher stakes and greater complexity, robotics isn't really something that warrants being more selective with who can interact with it. If anything, this is simply preventing people from engaging with interesting and fun mechanics.

I don't really see a reason to add this job into the game and you haven't really justified it in your PR description either.

Closing this pr.

2023-08-21 19:27 UTC, EmoGarbage404 commented
Reopening just to get some second opinions.

you're still free to add the clothes and such into the robodrobe.

2023-08-21 19:58 UTC, deltanedas commented
giving borg panels robotics access reader might make it important enough, since then you need to kill a roboticist or emag it twice, neither are ideal for tators

2023-08-21 19:59 UTC, HoidC commented
I want to say Roboticists would be a good role if robots and modules were cheaper but as it is, they don’t really get much until later into the round. Silver isn’t mapped into all vaults and can only be obtained through Salvage, of which isn’t always (ever) reliable, and borgs need a LOT of steel to make until you get the machine upgraded.

If there was more early round bot content maybe roboticist would be good but until then I personally don’t see the point

2023-08-21 20:00 UTC, deltanedas commented
1. make vims and hamtr
2. salv died and got replaced by pros so silver is on the menu
3. hampter helps make borgs

2023-08-21 20:02 UTC, HoidC commented
> * make vims and hamtr
> * salv died and got replaced by pros so silver is on the menu
> * hampter helps make borgs

deltanedas be comprehensible challenge (impossible difficulty)[gone wrong]{gone professional}

2023-08-21 21:12 UTC, Nimfar11 commented
Theoretically, a roboticist could be a useful role, but the problem is that there's nowhere to use it right now. The Borg is in its infancy and doesn't have half of what it was designed for, including the AI itself. Robotics has nothing to do yet. I rather think that this role is premature. Later, perhaps, but now it seems too early.

2023-08-21 22:26 UTC, Endecc commented
I agree with the feedback of how Cyborgs, and as a whole Robotics, are still very young. Unless some argument could be made if you also consider a roundstart Borg, but even then that would amount to "Babysit this 1 robot until you can make more in 20 minutes."

I want to say I would love this role, it was one of my favorites when I was very active in SS13. But there really isn't much for it to do in the current state of Robotics.

I think it's worth holding onto as a role for later, though. Integrating the clothing vendor and the outfits for Scientists who want to play the part, I also think is a great idea. But it's just not fun enough for players to be locked in that robotics lab. Not quite yet.

2023-08-21 22:27 UTC, UbaserB commented
In the first place, to balance the job and borging i feel creating the basic borgs should be available (no modules, or maybe one or two basic types) roundstart. If this were to happen there could also be a seperate robotics research tree which slowly lets you unlock the different types and modules, for example janitor bots at first, and then engineer borgs at the end. This would allow robotics to keep working throughout the whole round, and scientists to actually have a job (for a while at least).

2023-08-22 01:00 UTC, potato1234x commented
i like this, however the drobe sprite change looks a bit out of place on a normal map

2023-08-23 00:44 UTC, potato1234x commented
i'd definitely make the color scheme purple and black like the robodrobe

2023-08-26 22:35 UTC, basyachok commented
i was a roboticist main when i was playing ss13.
yep, this pr is completely pointless at the current time, it will also cause more conflicts and harm to the RND rather than bring something useful, imo we don't actually have the robotics at all.
i can't imagine a roboticist gameplay without being able to build a lethal mecha

too early

2023-08-30 06:06 UTC, metalgearsloth requested changes
Ideally this just becomes a loadout for scientists as there's no reaosn to have it as an entirely separate role as robotics doesn't need its own access.

Atmos and chem there's at least a highly volatile department that needs access-gating.

2023-09-22 08:14 UTC, Froozigiusz commented
I think that for the roboticist to work, simple robots would need to get a refactor alongside maintenance drone (an intermediate level robot alongside pAI?). Right now many robotic projects are found within the construction menu, which funny thing, cyborgs can also create them (and drones in the lathe, if they have tool module active). Drones being in the lathe is also incredibly confusing for a robot that it is.
Maybe a roboticist shuld be more of a shepperd, controlling the flow of all types of robots on the station. Having access to the status computer would also allow to disable some simpler robots and hamper bigger ones, and maybe even having access to the compiler/binary radio channel.

2023-10-13 16:47 UTC, closed without merging

2023-10-13 20:30 UTC, Hmeister-fake commented
I think it's too early to add robo. At the moment science is basically 4 things, research, anomalys, artifacts and robotics. Removing one of these for a seperate job with very minimal content that still relys on science researching robo modules seems silly. When the medical refactor is done this would be great to PR with Robo surgery because then there would be a good reason for it to be a seperate job, since you would need surgery experience and science experience to play it.