Security Jetpacks In Suit Storage
space-wizards/space-station-14 pull request #19438
Opened 2023-08-23 07:08 UTC by Alekshhh

## About the PR
Security and warden suit storages come with a jetpack

## Why / Balance
Stations don't supply security with jetpacks. This simple fix makes sure sec is actually space ready incase someone is doing laps around the station with a gun. Also, HOS has one of their own, so why not their lackeys too? You can call this a mapper issue, but I'm not bugging every mapper to add jetpacks to sec.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:Alekshhh
- add: Added jetpacks to security suit storages

2023-08-23 15:01 UTC, NancokPS2 commented
This is a bit power creep-y no? All of sec just having the tools to catch up with any antag with a jetpack (which are not trivial to obtain) is a bit much.  
Sec isn't supposed to be on par with all threats, they are just security guards and some stuff WILL give them a hard time.      

Without mentioning that someone running laps around the station is not really a threat more than it is an annoyance. Their job is to protect the inside of the station, not patrol outside. And HoS can already deal with this IF it ever happens.
    
I think it would be better if it was a cargo purchase or at most there was a single non-HoS jetpack in the armory for emergencies of some kind.   

Warden certainly doesn't need a jetpack since he is meant to stay and guard sec (his hardsuit is in case of atmos issues, not to chase people outside), and if he has to cover for a lack of seccies+HoS and chase someone outside, he can ask for the appropiate gear somewhere else (buy some from cargo, get one from the EVA room, ask HoS or Cap for theirs, etc)

2023-08-23 16:24 UTC, Alekshhh commented
I agree with warden not needing a jetpack
stations however have an average of two suit storages for sec, only maybe two having four, so just having on average two spare jets isn't going to kill some kind of dynamic. space battles are not uncommon, given how many roles have some form of space protection, so the jetpacks are there for teams to take out lingering threats out of the station that can harm the inside of the station.

2023-08-23 18:12 UTC, NancokPS2 commented
QM suit is because he handles shuttles  
RD is for dealing with artifacts   
Cap is because cap gets everything  
  
Only HoS is given one for space combat, altho i agree that 2 per station is not really an issue

2023-08-27 02:14 UTC, Partmedia commented
I think more than just the HoS should be prepared to go on space battles, but I also don't think every officer should have a jetpack. As you mention, each station has far fewer hardsuit storage units than the number of officers.

To verify the last point, I went through all the maps and counted the suit storage units:

| Map       | Sec Suit Storage Units |
|-----------|----------------------- |
| Core      | 2                      |
| Barrantry | 1                      |
| Aspid     | 3                      |
| Box       | 3                      |
| Kettle    | 4                      |
| Meta      | 2                      |
| Packed    | 2                      |
| Fland     | 2                      |
| Cluster   | 2                      |
| Omega     | 1                      |
| Saltern   | 2                      |
| Origin    | 2                      |

And so I think this PR is fine once you remove it from the warden. And of course, I would recommend for Kettle to have less security hardsuit storage units.

2023-08-27 02:15 UTC, Partmedia requested changes

2023-08-27 02:15 UTC, Partmedia commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +      - id: JetpackSecurityFilled
Please remove this

2023-08-27 02:15 UTC, Partmedia commented on Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
>          - id: NitrogenTankFilled
Why isn't nitrogen being removed?

2023-08-27 02:15 UTC, Partmedia commented on Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
>          - id: NitrogenTankFilled
Same here.

2023-09-20 07:58 UTC, closed without merging