Shuttle timers
space-wizards/space-station-14 pull request #19471
Opened 2023-08-24 03:38 UTC by graevy

## About the PR

- fixed an oversight with TextScreenVisuals that caused it to display e.g. 1m60s
- created the `ShuttleTimer` prototype, which should automatically sync with parent shuttles when placed on them
- created `RemoteShuttleTimer` prototypes `EvacShuttleTimer` and `ArrivalsShuttleTimer` which should automatically sync with their respective shuttles, as well as track per-map ETA, when placed anywhere outside of them
- to avoid strict inheritance, duplicated much of the `SignalTimer` code into `Content.Server/TextScreen`. with a maintainer's blessing I would like to deduplicate signaltimer screens into textscreen composites

## Why / Balance

Implements [this feature](https://github.com/space-wizards/space-station-14/issues/18249) requested by @Emisse 

## Technical details

Shuttles on creation now `EnsureComp<ShuttleTimerComponent>`, which contains hashset<entityuid>s `LocalScreens` and `RemoteScreens`. When a shuttle is created, any shuttletimers on it are added to `LocalScreens`, and `AllEntityQuery<RemoteShuttleTimerComponent>` filters from every placed remote timer (sorry; I couldn't come up with a better way to avoid local variable capture) using a bitmask to populate `RemoteScreens`. `ShuttleTimerComponent` is on both the timers and the shuttles; `RemoteShuttleTimerComponent` is only on the timers at the moment. Whenever a remote is created, it queries all shuttles to be added to their remotescreen hashset via the same bitmask.

There are some extra `ShuttleTimerEvent`s in the `ArrivalsSystem`, `RoundEndSystem`, `EmergencyShuttleSystem`, and `EmergencyShuttleSystem.Console` to handle timers at the start and end of each round, as well as useful timings specific to those systems (e.g. the emergency shuttle timers display the time until server restart after the round ends)

## Media

[I screencapped the timers I placed on maps here](https://mega.nz/file/KTAA1S7a#NGri9Jt9azpC3uFjYDp3-OH2C6QV46M_fGRlMwIiKfI), but removed them from the mapfiles after for mappers to place.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Added shuttle timer prototypes and associated logic.

2023-08-24 13:55 UTC, JoeHammad1844 commented
video wont play for me

2023-08-24 21:13 UTC, graevy commented
> video wont play for me

can you download it?

2023-08-25 06:51 UTC, JoeHammad1844 commented
> can you download it?

didn't work

2023-08-25 08:35 UTC, graevy commented
> > can you download it?
> 
> didn't work

okay i just transcoded the shit out of it. it was x265

https://github.com/space-wizards/space-station-14/assets/51971268/2dec263c-58ea-4d43-b530-028082481957

2023-08-25 08:39 UTC, graevy commented
> > can you download it?
> 
> didn't work

https://github.com/space-wizards/space-station-14/assets/51971268/686422d3-e50b-426e-822a-36a7cdfa076f

compressed the shit out of it

2023-08-25 09:00 UTC, JoeHammad1844 commented
nice

2023-08-27 08:36 UTC, metalgearsloth requested changes
Most of your systems and events need documenting as it's not clear when for example "TextScreenTextEvent" is raised.

Also this should be using device networks rather than its own separate pairing system.

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/Shuttles/Systems/ArrivalsSystem.cs
> +    public float Docked;
Remove, data needs to be on components.

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/TextScreen/Systems/TextScreenSystem.cs
> +    }
Is this supposed to be MapInit?

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/TextScreen/Systems/TextScreenSystem.cs
> +    }
Just put the code in the update method.

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/TextScreen/Systems/TextScreenSystem.cs
> +public sealed class TextScreenSystem : EntitySystem
Systems need to be documented as this isn't intuitive.

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/TextScreen/Components/ActiveTextScreenTimerComponent.cs
> +}
Remove

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/Shuttles/Systems/ShuttleTimerSystem.cs
> +        }
Just add it to engine, also I don't think the event should have a struct constraint.

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/Shuttles/Systems/ShuttleSystem.cs
> +        EntityManager.EnsureComponent<ShuttleTimerComponent>(ev.EntityUid);
Asteroids don't need shuttle timers.

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/Shuttles/Systems/ShuttleTimerSystem.cs
> +
This isn't documented and I'm kinda suss this needs to exist.

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/Shuttles/Components/ShuttleTimerComponent.cs
> +
These need to be datafields (though really it should be using device networks).

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/Shuttles/Components/RemoteShuttleTimerComponent.cs
> +    }
Remove

2023-08-27 08:36 UTC, metalgearsloth commented on Content.Server/Shuttles/Components/EmergencyShuttleComponent.cs
> +{
Document

2023-10-30 10:37 UTC, graevy commented
hi @metalgearsloth, i took a break and came back and addressed your feedback. it is much cleaner. i submitted [this pr](https://github.com/space-wizards/space-station-14/pull/21327) to help achieve a subnet pattern [here](https://github.com/space-wizards/space-station-14/blob/89a49440831aab3c50e72a9fb7dd7148362811f1/Content.Server/Shuttles/Systems/ShuttleTimerSystem.cs#L32)

- all pairing is done with device networks
- subnets for each timer proto (e.g. arrivals on terminal vs on station vs on shuttle) are still achieved by comparing `MapUid`s, but this time only in the network event handler
- `ShuttleTimer` and `TextScreenTimer` components/systems/events are now the only additions (outside of the protos)
- i added the timers to the shuttles/terminal/devmap in spots i thought worked. i wasn't sure if that was a good idea

i'm gonna go to sleep and figure out this awful commit history tomorrow.

2023-10-31 12:00 UTC, UbaserB commented
yeah its a bit weird it uses the brig timer sprite rn tbh

2023-10-31 22:40 UTC, graevy commented
alright, i'll grab another texture and graft the textscreensystem onto it as best i can

2023-11-01 10:09 UTC, graevy commented
alright @BolloTea @UbaserB how do we feel about the sprites now:

![dotnet_oS6RuPBu1D](https://github.com/space-wizards/space-station-14/assets/51971268/252f0adb-23c7-4035-b517-6f0b45fc1d49)

2023-11-01 11:29 UTC, UbaserB commented
![Uploading IMG_0959.png…]()

2023-11-01 15:02 UTC, BolloTea commented
Looks much better.  But, can I ask you one small selfish request?  Wouldn't it be too difficult to make a small abbreviated inscription on the screen itself (time until arrival and a separate time before departure of the shuttle)?

2023-11-01 20:53 UTC, graevy commented
@BolloTea "ETA"/"ETD" in a row above the timer?

2023-11-26 01:30 UTC, graevy commented
completely refactored the client `TextScreenSystem` to:
- split the text/timer state behavior between `TextScreenVisualsComponent` and `TextScreenTimerComponent`
- use a `string?[]` instead of a `string` for text, to accommodate multiple text rows
- center rendered text per-row

did a minor `signaltimersystem` refactor to accommodate this

removed the server textscreensystem and events; using the appearance system instead

generalized `shuttletimers` into `screens` so they can extend to the hallway screens from ss13

added the screens to the arrivals/emergency shuttles, and the terminal/centcomm/dev maps

renamed `textscreen` (the brig timer sprites) to `signalscreen` to make the distinction clearer

documented all the new methods and added an overview to the refactored textscreensystem

2023-12-04 07:39 UTC, metalgearsloth requested changes

2023-12-04 07:39 UTC, metalgearsloth commented on Content.Server/Shuttles/Systems/ShuttleTimerSystem.cs
> +{
file-scoped namespaces please.

2023-12-04 07:39 UTC, metalgearsloth commented on Content.Server/Shuttles/Systems/ShuttleTimerSystem.cs
> +        }
This method feels weird but I can't articular how to make it better so it's fine as is.

2023-12-04 07:39 UTC, metalgearsloth commented on Content.Server/Shuttles/Systems/ShuttleTimerSystem.cs
> +            var targetGrid = _stationSystem.GetLargestGrid(Comp<StationDataComponent>(station));
You already have the query here just add StationDataComponent as another generic.

2023-12-04 07:39 UTC, metalgearsloth commented on Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
> +                AllEntityQuery<StationCentcommComponent>().MoveNext(out var centcomm);
Just dump this on a method instead IMO, like "GetCentcomm" or something so at least we only have 1 spot to update if we have to change it.

2023-12-19 22:30 UTC, metalgearsloth approved these changes

2023-12-19 22:30 UTC, merged