Meleespeech Action, Holoparasite Meleespeech
space-wizards/space-station-14 pull request #19504
Opened 2023-08-24 23:38 UTC by HerCoyote23

Previous PR got stuck in git bash mistake hell. 
## About the PR

Makes the MeleeSpeech component have an action to configure your battlecry.
Adds MeleeSpeech to Holoparasites.

Be advised that this is my first foray into actions and I was very much figuring out how they work over this PR. It's likely a bit flawed in implementation.
## Why / Balance

## Technical details

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: The Syndicate's Holoparasite have taken to yelling catchphrases as they fight.

2023-08-25 02:49 UTC, metalgearsloth requested changes
99% there I think just some minor stuff gj.

2023-08-25 02:49 UTC, metalgearsloth commented on Content.Shared/Speech/Components/MeleeSpeechComponent.cs
> +[RegisterComponent, NetworkedComponent]
newline

2023-08-25 02:49 UTC, metalgearsloth commented on Content.Shared/Speech/Components/MeleeSpeechComponent.cs
> +    /// <summary>
newline

2023-08-25 02:49 UTC, metalgearsloth commented on Content.Shared/Speech/Components/MeleeSpeechComponent.cs
> +    /// <summary>
newline

2023-08-25 02:49 UTC, metalgearsloth commented on Content.Server/Speech/EntitySystems/MeleeSpeechSystem.cs
> +        Dirty(meleeSpeechComp);
```suggestion
        Dirty(uid, meleeSpeechComp);
```

2023-08-25 04:38 UTC, HerCoyote23 commented
Think Holoclowns should have meleespeech as well? Atm they inherit it from Guardian, don't know if it's quite thematically fitting.

2023-08-25 06:58 UTC, VektorZ1 commented
The holoclowns should make a honk sound when struck :trollface:

2023-08-26 21:25 UTC, keronshb approved these changes

2023-08-26 21:26 UTC, merged