Volume and pressure pump
space-wizards/space-station-14 pull request #1955
Opened 2020-08-29 02:25 UTC by collinlunn

Replacements for DebugPumpComponent. 

Pressure pump brings outlet to a target pressure. Speed is controlled by pumping a fraction of the needed amount.

Volume pump transfers a flat amount of volume.

UI & sprites not included.

2020-08-29 11:41 UTC, DrSmugleaf approved these changes

2020-08-30 10:38 UTC, Zumorica requested changes

2020-08-30 10:38 UTC, Zumorica commented on Content.Server/GameObjects/Components/Atmos/Piping/Pumps/VolumePumpComponent.cs
> +            outletGas.Merge(transferingGas);
Why don't you use `inletGas.RemoveRatio` here instead? To get the ratio you would divide the transfer rate by the total volume of the inlet gas. That way you can avoid creating a new gas mixture for the sole purpose of calculating the moles to be removed from the inlet.

2020-08-31 00:10 UTC, Zumorica commented on Content.Server/GameObjects/Components/Atmos/GridAtmosphereComponent.cs
> +            while (_currentRunPipeNetDevice.Count > 0)
Oops

2020-08-31 00:12 UTC, Zumorica approved these changes

2020-08-31 00:13 UTC, merged