Tail wagging
space-wizards/space-station-14 pull request #19573
Opened 2023-08-27 04:40 UTC by Morb0

## About the PR

Simple action-based implementation of tail wagging for reptilians

## Why / Balance

## Technical details

- Not use emote system, because it not supports custom system behavior, don't have convenient panel and don't have conditions to make toggable emote
- Use simple `Animated` prefix to get animated marking, looks okay while tails is marking
- Support multiple tail markings animation

## Media

https://github.com/space-wizards/space-station-14/assets/14136326/0739a7f6-6688-4871-86f0-b91d42e72107

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: The lizards have gained control of their tail wagging

2023-08-27 04:41 UTC, LankLTE commented
Don’t have an issue with the feature but something about this feels so cursed

2023-08-27 04:41 UTC, DogZeroX commented
The path to the texture says "corvax"

2023-08-27 04:45 UTC, LankLTE commented
> The path to the texture says "corvax"

The system / component are also in a corvax folder and use it in their namespace

2023-08-27 04:47 UTC, Morb0 commented
> > The path to the texture says "corvax"
> 
> The system / component are also in a corvax folder and use it in their namespace

Fixed

2023-08-27 06:11 UTC, metalgearsloth requested changes
This should be using generic emoting rather than specifically being just for wagging.

2023-08-27 11:14 UTC, UbaserB commented
I like the side view, but not the front view animation.

2023-08-27 18:47 UTC, NancokPS2 commented
Would any other race get a similar treatment?  
It feels very odd because every mob is basically a static static image, yet now reptilians get an animation solely for their tails.  
This is pretty good, but it is really out of place atm.

2023-08-27 19:44 UTC, DogZeroX commented
I don't think all races need wagging, if anything when you animate it.

2023-08-27 21:54 UTC, VasilisThePikachu commented
This is the best thing to be created ever since sliced bread, though I have to agree having it as an action is a bit weird. Better for it to just be an emote (like "wags tail" etc)

2023-09-11 11:06 UTC, DrSmugleaf requested changes

2023-09-11 18:26 UTC, Eden077 commented
Liznerds rise up

2023-09-11 18:31 UTC, LankLTE submitted a review, later dismissed
This needs to be handled via emotes, not a sidebar action.

2023-09-11 18:31 UTC, LankLTE commented on Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/reptilian.yml
This needs to not be in a Corvax folder.

2023-09-11 18:41 UTC, LankLTE commented
I also think the animation looks really odd, too smooth and out of place. I’d get the opinions of an art director on that though as it isn’t my strong suit.

2023-09-11 18:47 UTC, Morb0 commented
> This needs to be handled via emotes, not a sidebar action.

I got permit to not reinventing emote system for tails.
https://discord.com/channels/310555209753690112/560845886263918612/1150679877582856233

2023-09-11 20:26 UTC, LankLTE commented
> I got permit to not reinventing emote system for tails.

She had misunderstood and thought the alternative was using the emote wheel PR (that I believe is now closed). After further discussion we agree this should be implemented via chat emotes.

2023-09-12 06:37 UTC, moonheart08 requested changes
The spritework is awful, needs redone by an animator who understands what weight is. As of now the animation is extremely stiff.

2023-10-20 10:22 UTC, SonicHDC commented
![Downloadedpng](https://github.com/space-wizards/space-station-14/assets/100022571/6afe06e0-7a20-4658-91b9-a521985ac6f3)
Я полагаю, что как чёрные кормашки или мелкие вставки подойдёт.
Или же сам цвет вставок сделать тусклей/светлей.

2023-10-20 10:24 UTC, SonicHDC commented
Multitabs PRs answers. XD

2023-11-20 11:41 UTC, SonicHDC commented
When?

2024-01-04 02:17 UTC, metalgearsloth commented
@Morb0 add prediction and I'll merge

2024-01-06 08:23 UTC, UbaserB commented
You will need to include this tail marking for wagging now #23551

2024-01-14 07:51 UTC, metalgearsloth approved these changes

2024-01-14 07:52 UTC, merged

2024-01-14 10:48 UTC, Hmeister-fake commented
I am so happy

2024-01-14 10:50 UTC, SonicHDC commented
Yey!

2024-01-15 01:06 UTC, Aexxie commented
hell yeah now I dont need to do it myself