Add cane/wheelchair crate
space-wizards/space-station-14 pull request #19625
Opened 2023-08-29 06:40 UTC by Kezu02

## About the PR
I added two crates: the blind support crate and wheelchair crate. Both cost 300 spesos.

## Why / Balance
Blind/wheelchair players will inevitably get their things lost/taken. There wasn't any way to get more.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: NanoTrasen has begun producing spare canes and wheelchairs for our disabled crew. Order them from Cargo!

2023-08-29 15:20 UTC, brainfood1183 commented
we likely could do with a wheelchair spawner as well so wheelchair could be mapped in medical

2023-08-30 00:34 UTC, Aisu9 commented
what about crafting them in lathes

2023-08-30 00:42 UTC, lzk228 commented on Resources/Prototypes/Catalog/Cargo/cargo_emergency.yml
> +  - type: cargoProduct
```suggestion
- type: cargoProduct
```

2023-09-02 15:26 UTC, QuietlyWhisper commented
resolves #19753

2023-09-04 04:51 UTC, mirrorcult commented
please do not use github webedits to make PRs, and include screenshots of this working as expected in game

2023-09-04 04:51 UTC, mirrorcult requested changes
above

2023-09-23 18:36 UTC, LankLTE commented
Superseded by #19811 . Feel free to re-open if you wish.

2023-09-23 18:36 UTC, closed without merging