Boxes (and sterile mask)
space-wizards/space-station-14 pull request #1964
Opened 2020-08-30 10:22 UTC by SweptWasTaken

Just more bloat content. I'm not making empty variants for these boxes like the crates or lockers.

Added 
- donkpocket box 
- buncha boxes for stuff
- sterile mask

I made sure to organize things neatly yada yada.

I'm gonna tie this into #1835 so this will be completed before that.

2020-09-01 06:49 UTC, SweptWasTaken commented
Added "filled" versions of the backpacks for spawning start gear.

2020-09-02 23:13 UTC, DrSmugleaf requested changes
LGTM except for one rsi's attribution missing a commit id.

2020-09-02 23:13 UTC, DrSmugleaf commented on Resources/Textures/Clothing/Masks/mask_sterile.rsi/meta.json
> +    "copyright": "Taken from https://github.com/tgstation",
Missing a commit id here.

2020-09-03 21:12 UTC, SweptWasTaken commented
Ready

2020-09-03 21:13 UTC, DrSmugleaf approved these changes

2020-09-03 21:13 UTC, merged