Decorative Flags
space-wizards/space-station-14 pull request #19670
Opened 2023-08-30 22:15 UTC by SaveliyM360

## About the PR
I added flags to the game. It's a nice addition to the decor, and also allows servers to add their own faction and country lore flags, thanks to the existing blank flag base (hello from Baystation), such as Transsolar Federation, Space Wizard Federation, Moges State, Arachnid Empire... I think you get the idea.

## Why / Balance
I wrote above, and it's also not cool that there are banners in the game, but there are no flags.

## Technical details
They can be breaked just like posters. But unfortunately, they are available so far only in sandbox mode for mapping. Maybe in the future I will add them to the station maps (I hope it won't break anything).

How to create your flag based on a blank flag sprite: Take the blank flag sprite, create a new layer under it, and set the blending mode to "multiple" on the blank flag layer. Before that, I recommend to select and cut on a new layer the sprites of "nails", which are located on the upper edges of the flag, and look like a "plus".

## Media

![flags](https://github.com/space-wizards/space-station-14/assets/142160914/10013798-fc30-45a3-b22a-c467023f0cc5)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

- add: Added decorative wall flags, including the NT and Syndicate flags.

2023-08-30 22:24 UTC, lzk228 commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/flags.yml
> +  description: "Smells bloody. Fuck NT!"
that's a bad word

2023-08-30 22:55 UTC, deltanedas commented
real

2023-08-31 00:41 UTC, CatMagic1 commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/flags.yml
> +  description: "Smells bloody. Fuck NT!"
merge blocked

2023-08-31 00:50 UTC, Emisse commented on Resources/Textures/Structures/Wallmounts/flags.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/d0d81185f09ca30d3b0856d476544240dba0de53, drawed by Saveliy360",
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/d0d81185f09ca30d3b0856d476544240dba0de53, drawn by Saveliy360",
```

2023-08-31 01:07 UTC, ficcialfaint commented on Resources/Textures/Structures/Wallmounts/flags.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/d0d81185f09ca30d3b0856d476544240dba0de53, drawn by Saveliy360",
doesn't seem too clear: what exactly was drawn by you and what was taken from /tg/

2023-08-31 01:07 UTC, ficcialfaint commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/flags.yml
Can it spawn a destructed version of the flag as posters do?

2023-08-31 10:35 UTC, JoeHammad1844 commented
you forgot to mention you also added the french flag

2023-09-04 23:49 UTC, mirrorcult requested changes
the solid color flags can very easily use a grayscale layer that has its color specified in the sprite component instead, rather than duplicating so many images like this. the other ones are fine to be unique. (maybe even just try setting color on the gray solid color flag and see how it looks?)

"handy flag" reads kind of weird to me? ive never heard them called that before in english, i would call them "handheld flags"

2023-09-04 23:49 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Misc/handy_flags.yml
> +  description: "Just black handy flag"
description is incorrect

2023-09-04 23:49 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Misc/handy_flags.yml
> +  description: "Holding it in your hands, show these carp that you're not kidding."
```suggestion
  id: PirateHandyFlag
  name: pirate handy flag
  description: Hold it in your hands to show these carp that you're not kidding.
```
descs dont need quotation marks around them + dont capitalize pirate imo
descriptions for most of these read pretty weirdly imo but ill just point them out as i go

2023-09-04 23:49 UTC, mirrorcult commented on Resources/Textures/Structures/Wallmounts/flags.rsi/meta.json
> +	{
lots of mixed tabs & spaces in this file, please only use spaces

2023-09-04 23:49 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Misc/handy_flags.yml
> +  description: "Be gay do crime handy flag"
```suggestion
  name: LGBTQ handy flag
  description: "The be gay do crime handy flag."
```

all flag descs here need periods at the end of them, the solid color flags mostly

also think this desc reads better like this, same for the wallmount flag

2023-09-04 23:49 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Misc/handy_flags.yml
> +  description: "Just black handy flag"
```suggestion
  id: BlackHandyFlag
  name: black handy flag
  description: Just a black handy flag.
```

same for all the other color flags, not going to review them separately

2023-09-05 00:43 UTC, SaveliyM360 commented
> Ok, I think I fixed all the typos in the files, and renamed all the handy things to handheld. About grayscale mechanics for the flags, I don't really understand it. When I creating colored flags, I focused on the color variety of bedspreads, because I thought that five flags would be too few.
If you mean to remove the colored flags, then I will.

2023-09-05 00:45 UTC, mirrorcult commented
you can just have one grayscaled sprite for the flags, and then color them dynamically in YAML by changing the `color:` field in spritecomponent

2023-09-05 00:55 UTC, SaveliyM360 commented
> you can just have one grayscaled sprite for the flags, and then color them dynamically in YAML by changing the `color:` field in spritecomponent

Oh, i got it. Well, in fact, this role is performed by the blank flag.

2023-09-05 01:03 UTC, SaveliyM360 commented
Okay, now all coloured flags are removed.

2023-09-12 21:54 UTC, SaveliyM360 commented
I replaced the picture, due to the removal of colored flags.

2023-12-04 06:14 UTC, metalgearsloth requested changes
"Drawn by" not "drawed by" please, also faint's review.

2023-12-04 06:27 UTC, merged