Hurt Command
space-wizards/space-station-14 pull request #1967
Opened 2020-08-30 19:11 UTC by exp111

2020-08-31 22:31 UTC, Zumorica reviewed
Maybe make this take in an entity uid to be hurt instead and default to the player entity if the user passes "_" or something?

2020-09-02 12:59 UTC, DrSmugleaf requested changes

2020-09-02 12:59 UTC, DrSmugleaf commented on Content.Server/Body/BodyCommands.cs
> +            var entityUid = player.AttachedEntityUid.HasValue ? player.AttachedEntityUid.Value : EntityUid.Invalid;
`player` can be null here.

2020-09-02 12:59 UTC, DrSmugleaf commented on Content.Server/Body/BodyCommands.cs
> +            var ent = IoCManager.Resolve<IEntityManager>().GetEntity(entityUid);
This will throw if the entity doesn't exist, despite what the doc for IEntityManager says. Use TryGetEntity instead.

2020-09-02 20:20 UTC, DrSmugleaf requested changes

2020-09-02 20:20 UTC, DrSmugleaf commented on Content.Server/Body/BodyCommands.cs
> +            }
You could move all of this to the end of the method and do a normal `if damageclass parse, else if damagetype parse, else error message`.

2020-09-02 20:55 UTC, DrSmugleaf approved these changes

2020-09-02 21:00 UTC, merged