Animated status icons
space-wizards/space-station-14 pull request #19691
Opened 2023-08-31 10:39 UTC by Morb0

## About the PR

Adds support for animated RSI states

## Why / Balance

## Technical details

## Media

![pog](https://github.com/space-wizards/space-station-14/assets/14136326/04adbcd3-4b22-4a29-874f-89e249a393c3)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2023-08-31 10:44 UTC, lzk228 requested changes
what about add `sprite: [path]` to `JobIcon` and remove it from all other

2023-08-31 10:48 UTC, Morb0 commented
> what about add `sprite: [path]` to `JobIcon` and remove it from all other

Nope, seems it require full sprite defenition
`Reading Content.Shared.StatusIcon.StatusIconPrototype(JobIconBotanist) threw the following exception: Robust.Shared.Serialization.InvalidMappingException: Expected sprite-node`

2023-08-31 11:04 UTC, metalgearsloth requested changes

2023-08-31 11:04 UTC, metalgearsloth commented on Content.Client/StatusIcon/StatusIconOverlay.cs
> +                        throw new NotImplementedException();
Considering this code is shared with gastileoverlay it should be on a common system for handling it.

2023-09-04 17:08 UTC, ps3moira commented
it looks visually jarring and annoying to look at

2023-09-04 17:12 UTC, Morb0 commented
> it looks visually jarring and annoying to look at

sad

2023-09-21 22:49 UTC, AJCM-git commented
@Morb0 you coming back to this?

2023-11-06 03:24 UTC, closed without merging