gib hitchhikers on ftl
space-wizards/space-station-14 pull request #19793
Opened 2023-09-03 17:58 UTC by deltanedas

## About the PR
if you are on lattice or space when ftl starts or ends you will get gibbed

fixes #18441

## Why / Balance
see issue

## Technical details
checks tile under every mob to see if it should get gibbed

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- tweak: A fracture in bluespace is now causing spacemen that hitchhike on shuttles to be gibbed on FTL. Keep legs inside the vehicle at all times.

2023-09-03 18:04 UTC, LankLTE commented
This could also lead to people being gibbed after shuttle bombing, which isn't ideal

2023-09-03 18:06 UTC, deltanedas commented
1. having to define what lattice is inside the shuttle as opposed to inside seems like hell, cant check atmos since its spaced
2. they kinda would fly out the top/bottom...
3. shuttle bombings cant be repaired so they are typically cordoned off by pros, reducing chance of someone standing on a lattice inside before getting to centcom

2023-09-03 18:09 UTC, Equivocateur commented
> This could also lead to people being gibbed after shuttle bombing, which isn't ideal

https://youtu.be/S6v252cYhp0?si=Zw2FdfFPnapN2AHg&t=90 but in reverse, makes sense in or outside the shuttle during ftl either way.

2023-09-03 18:11 UTC, deltanedas commented
real

2023-09-03 19:16 UTC, CaptainSqrBeard commented
People will just bring a steel sheet to place on lattice. That's probably not the solution

2023-09-03 19:17 UTC, deltanedas commented
you cant do that

2023-09-03 19:23 UTC, CaptainSqrBeard commented
> you cant do that

what stops me from doing that?

2023-09-03 19:23 UTC, coolmankid12345 commented
It literally doesn't work

2023-09-03 19:28 UTC, HoidC commented
ok hear me out but there’s two solutions to this 

1. Zones (I’m sent to hell for uttering this word)
2. Making shuttle tiles bomb proof so people don’t get instagibbed by minibombs, also reduces the ridiculous power of the end round shuttle bomb

2023-09-03 19:28 UTC, deltanedas commented
for whatever reason adding tiles to lattice is counted as building for evac

2023-09-04 00:10 UTC, UbaserB commented
zones sound fine honestly. Atmos markers already exist, so id image it’d be similar.

2023-09-04 06:24 UTC, CaptainSqrBeard commented
I didn't know that you can't build tiles on shuttle. But as it doesn't check containers I can build a crate and hide inside 🤔

2023-09-04 06:38 UTC, deltanedas commented
yes its unfortunate but not sure how i would fix it

2023-09-04 10:01 UTC, JoeHammad1844 commented
thing is that  escape pods dont count for the escape to centcom alive syndie objective, so if you go loud you just wont be able to complete th objective because sec will catch you

2023-09-04 10:03 UTC, metalgearsloth requested changes

2023-09-04 10:03 UTC, metalgearsloth commented on Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
> +        var xformQuery = GetEntityQuery<TransformComponent>();
Chuck it on the system.

2023-09-04 10:33 UTC, deltanedas commented
> so if you go loud you just wont be able to complete th objective because sec will catch you

hiding on thruster is cowardice
if you want to go load bomb the shittle and be the only one left

2023-09-04 14:16 UTC, metalgearsloth approved these changes

2023-09-04 14:16 UTC, merged

2023-09-05 06:03 UTC, JoeHammad1844 commented
> hiding on thruster is cowardice if you want to go loud bomb the shittle and be the only one left

no TC left :sad: