UseDelay + rad cleanup
space-wizards/space-station-14 pull request #19817
Opened 2023-09-04 14:09 UTC by metalgearsloth

I just wanted to fix some things from rad collector PR and ended up doing a mild rework of UseDelay to make more sense.

2023-09-04 16:47 UTC, Partmedia commented
This would be easier to review if the UseDelay and rad cleanup were separate. The rad cleanup part looks fine, but I have not tested this in game. How much of the changed stuff was tested in game?

2023-11-10 12:25 UTC, AJCM-git requested changes
Since you already have to merge master may as well apply new standards

2023-11-10 12:25 UTC, AJCM-git commented on Content.Server/Singularity/Components/RadiationCollectorComponent.cs
Make these use the new default names

2023-11-10 12:25 UTC, AJCM-git commented on Content.Shared/Timing/UseDelayComponent.cs
same

2024-01-03 02:31 UTC, AJCM-git commented
superseded by  #22502

2024-01-03 02:31 UTC, closed without merging