Guardians (Holo and holoclown) have syndicate faction ai
space-wizards/space-station-14 pull request #19816
Opened 2023-09-04 13:45 UTC by QuietlyWhisper

## About the PR

Removed the player requirement, the ghost takeover still works.
Players can summon their guardians without requiring someone to be playing it (This is useful for lowpop and low death count)
Players will still see the notification when a soul takes over the holo
When the holo is ghosted, it returns to AI control
Non syndicate cannot use uplink guardians; they will attack anyone that isn't a syndicate (Crew members shouldnt be using contraband that is likely loyal to the syndicate)

## Why / Balance

Guardians can be an entire waste of telecrystals when they rely on ghosts that may or may not exist. This removes the gambling aspect. 
Should encourage more guardian usage by syndicate agents when they are guaranteed to get usage out of it.
Allows usage on lowpop where ghosts and ghosts willing to play the role are scarce.

## Technical details

Added the syndicate faction and AI components to the uplink guardians.
Removed the check for player control, so the guardian may always be summoned.

## Media

(discord links to the ss14 server, videos are too large for github)
https://discord.com/channels/310555209753690112/675078881425752124/1148247722260963349
https://discord.com/channels/310555209753690112/675078881425752124/1148249548393816064
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Whisper
- add: Guardians (holo, holoclown) have AI control before a ghost takes over the role, and after a player ghosts from it.
- tweak: Guardians can be summoned without a player in the role.

2023-09-04 14:08 UTC, deltanedas commented
would be cool to see if the salvager ai compound for taking weapons could be used for holoclown to make its ai more useful

2023-09-04 16:13 UTC, QuietlyWhisper commented
> would be cool to see if the salvager ai compound for taking weapons could be used for holoclown to make its ai more useful

it's included. Though clowns aren't very good with guns :)

2023-09-04 16:19 UTC, deltanedas commented
:trollface:

2023-09-05 06:13 UTC, JoeHammad1844 commented
I was banned from the discord, please link youtube videos

2023-09-07 03:16 UTC, EmoGarbage404 requested changes

2023-09-07 03:16 UTC, EmoGarbage404 commented on Content.Server/Guardian/GuardianSystem.cs
> +        /*private bool CanRelease(EntityUid guardian)
remove commented out code

2023-09-07 03:16 UTC, EmoGarbage404 commented on Content.Server/Guardian/GuardianSystem.cs
> +            /*if (!CanRelease(guardian))
here too

2023-09-11 14:35 UTC, QuietlyWhisper commented
should I be worried robust is in the changed files tab for some reason?

2023-09-11 15:23 UTC, deltanedas commented
yes
`git checkout upstream/master RobustToolbox` and commit it (either that or reset i forget which)

2023-09-13 23:22 UTC, DrSmugleaf submitted a review, later dismissed

2023-09-14 03:51 UTC, DrSmugleaf approved these changes

2023-09-14 03:51 UTC, merged