Add moth plushie
space-wizards/space-station-14 pull request #19842
Opened 2023-09-05 08:02 UTC by Fromoriss

About the PR
This will add moth plushie in plushie crate.

 Why / Balance
I forget it yesterday..

 Technical details
Only makes plushie crate (can be ordered in cargo) with moth plushie.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
No cl

2023-09-05 08:11 UTC, Fromoriss commented
Ok, somebody already makes it, with arcades..

2023-09-05 08:22 UTC, deltanedas commented
reopen that pr doesnt add the plushie itself

2023-09-05 08:24 UTC, Fromoriss commented
> reopen that pr doesnt add the plushie itself

There is another PR, that add plushie both to crate and arcade.

2023-09-05 08:26 UTC, deltanedas commented
yes but it depends on this

2023-09-05 17:43 UTC, Partmedia commented
Could you please clarify the license for this moth plushie sprite, or where you got it from?

2023-09-05 17:52 UTC, LankLTE commented
> Could you please clarify the license for this moth plushie sprite, or where you got it from?

It’s taken from /tg/, I had assumed the commit at the top of the toys.rsi meta would cover it

2023-09-05 17:53 UTC, Partmedia commented
> > Could you please clarify the license for this moth plushie sprite, or where you got it from?
> 
> It’s taken from /tg/, I had assumed the commit at the top of the toys.rsi meta would cover it

It does, I wanted to double check that this is actually from the same source.

2023-09-05 18:00 UTC, lzk228 requested changes
merge master into your branch

2023-09-05 18:09 UTC, Partmedia commented
> merge master into your branch

This is not necessary (and in fact, confuses the diff). This is sometimes useful for large changes to expose new test failures due to changes in master, but this is not applicable here.

2023-09-05 19:24 UTC, Fromoriss commented
Okay, now it's already existing, but last commits make it possible to order with a plushie crate and meta.json is updated with note, that moth plushie from /tg/

2023-09-06 10:18 UTC, lzk228 commented
@Fromoriss you added commits to your branch, that already was merged to wizard/master, so that because diff has "new" moth plushie, you should merge master in your branch now

2023-09-06 10:21 UTC, lzk228 commented on Resources/Textures/Objects/Fun/toys.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, orb, orb-inhand-left and orb-inhand-right created by Pancake, plushie_d
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, orb, orb-inhand-left and orb-inhand-right created by Pancake, plushie_diona and plushie_diona1 created by discord user Deos#5630, toy-mouse-equipped-HELMET is a resprited 1-equipped-HELMET in mouse.rsi by PuroSlavKing (Github), plushie_xeno by LinkUyx#6557, plushie_hampter by RenLou#4333, beachball taken from https://github.com/ss220-space/Paradise/commit/662c08272acd7be79531550919f56f846726eabb, beachb-inhand by ;3#1161, moth plushie taken from tgstation by Fromoriss",
```

2023-09-06 17:05 UTC, closed without merging

2023-09-08 03:46 UTC, UbaserB commented
why is it deleted this makes me so sad

2023-09-08 05:58 UTC, Just-a-Unity-Dev commented
closed for some reason, im assuming they accidentally deleted the branch

2023-09-08 09:23 UTC, lzk228 commented
> why is it deleted this makes me so sad

#19828

2023-09-08 09:30 UTC, Just-a-Unity-Dev commented
forgetf