Emagged Borg Sound Effect
space-wizards/space-station-14 pull request #19858
Opened 2023-09-05 22:00 UTC by ps3moira

## About the PR

- Emagged Borgs now play a Sound Effect

## Media

**Changelog**
:cl:
- add: Emagging borgs now plays a sound effect.

2023-09-05 22:34 UTC, ficcialfaint requested changes
Test your changes locally before opening a PR

2023-09-05 22:34 UTC, ficcialfaint commented on Resources/Audio/Ambience/Antag/attributions.yml
> + - files: ["emag_borg.ogg"]
```suggestion

- files: ["emag_borg.ogg"]
```

2023-09-05 22:34 UTC, ficcialfaint commented on Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
> +      path: /Audio/Ambience/Antag/emag_borg.ogg
There is no such datafield in `EmagSiliconLaw`

2023-09-05 23:47 UTC, EmoGarbage404 commented
this PR doesn't do anything? You need to actually implement the logic for playing the sound.

2023-09-07 18:40 UTC, Partmedia commented
It looks like the logic is still missing, not to mention there are YAML lint problems. If you need help, please contact us in [#howdoicode on Discord](https://discord.com/channels/310555209753690112/560845886263918612).

2023-09-07 19:31 UTC, deltanedas commented
the video isnt even from ingame bruh

2023-09-08 11:20 UTC, potato1234x commented
you gotta actually write code for this you know. also sound is way too long

2023-09-08 21:24 UTC, deltanedas commented on Content.Server/Silicons/Laws/SiliconLawSystem.cs
> +    [Dependency] private readonly SharedAudioSystem _audioSystem = default!;
just adding a dependency doesnt make it play anything...

2023-11-03 22:21 UTC, closed without merging