Russian revolver
space-wizards/space-station-14 pull request #19978
Opened 2023-09-10 11:57 UTC by MACMAN2003

## About the PR

Adds in a joke revolver "gun" that is incapable of being used in combat, but is instead used to play Russian Roulette. It can only be used by the player holding it, and is only capable of harming the player holding it.

## Why / Balance

It'd make for some hilarious additions to the spess guy funny moments compilations. As for balance, I'm pretty sure it'd just add a few more patients to medbay each round.

## Technical details

I don't know if I can explain the technical details because I barely understand them myself lol.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/20659419/3b96960a-ae10-4643-a616-5db3e483bf1e

## Breaking changes

Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.Revolver.Cycle() was changed from private to public, and a new method "RussianizeRevolver" was added into it.

**Changelog**

:cl:
- add: Added a revolver to the Barkeep's booze locker that can be used to play Russian Roulette.

2023-09-10 12:25 UTC, lzk228 commented
#8524 :trollface:

2023-09-10 16:17 UTC, Equivocateur commented
> #8524 :trollface:

Not a real gun per se, and it has unique functionality.

2023-09-10 17:19 UTC, Errant-4 commented
It's kind of weird conceptually to introduce a gun that looks like a gun, but arbitrarily can only be used on yourself

2023-09-10 17:45 UTC, deltanedas commented
it should be possible to use any gun on yourself, in the ideal world

2023-09-10 18:14 UTC, Equivocateur commented
> it should be possible to use any gun on yourself, in the ideal world

/suicide with gun in hand if gun has a bullet in chamber

2023-09-10 18:52 UTC, BRINGit34 commented
Maybe it should be like one of those cartoon guns where the barrel is pointing the wrong way. Just to make it more clear

2023-09-10 19:15 UTC, BolloTea commented
Finally some normal bar entertainment 🤡

2023-09-10 19:17 UTC, BolloTea commented
All that remains is to make a reverse pistol for the antagonist clown

2023-09-10 20:27 UTC, Partmedia commented
It would be better if this were not a separate weapon, but rather a change that allowed the normal revolver to target yourself. I also don't like the culturally insensitive use of "Russian revolver" and "Russianize", because this sounds like an insult to a whole cultural group.

2023-09-10 20:31 UTC, BolloTea commented
> It would be better if this were not a separate weapon, but rather a change that allowed the normal revolver to target yourself. I also don't like the culturally insensitive use of "Russian revolver" and "Russianize", because this sounds like an insult to a whole cultural group.

Excuse me, but do you have any ideas on what to call a revolver for playing "Russian Roulette"?  Besides, there is nothing offensive in this.

2023-09-10 20:48 UTC, MACMAN2003 commented
> It would be better if this were not a separate weapon, but rather a change that allowed the normal revolver to target yourself. I also don't like the culturally insensitive use of "Russian revolver" and "Russianize", because this sounds like an insult to a whole cultural group.
Do you have any suggestions for alternative names for the gun and/or the "Russianize" method?

2023-09-10 21:21 UTC, LankLTE commented
Don't really see how the names are culturally insensitive (any more than Russian Roulette itself would be, which to my knowledge isn't). That said I do agree that having this as its' own revolver seems kind of weird, especially when the revolver looks like a normal gun instead of a cartoony one with the barrel turned around (which would at least warrant looking funny)

2023-09-10 21:56 UTC, LankLTE commented
I forgot that this was for the bar- that'd obviously make it difficult to implement as a normal revolver without giving the barkeep their own revolver, which would cause other issues. It's still preferred that this isn't its' own gun, so some other solution would be appreciated if you could find one.
Also, the method name should be changed. Something like MakeRoulette could work better

2023-09-10 22:02 UTC, BolloTea commented
The cartoon version with the barrel upside down is not appropriate.  Yes, it wouldn't be bad if every weapon could have a suicide function.  But a separate revolver for playing roulette is the best solution not to be a full-fledged weapon.  This is just a way to test your nerves of steel with friends, after a friendly drinking session in a bar, or as an emergency way to exit the game.

2023-09-10 22:05 UTC, Partmedia commented
Maybe you could investigate adding a component field to the `GunComponent` that would allow the shooter to shoot themselves, setting this to false by default.

2023-09-10 22:06 UTC, forgotmyotheraccount commented
> > it should be possible to use any gun on yourself, in the ideal world
> 
> /suicide with gun in hand if gun has a bullet in chamber

This is the clear answer. Introducing a new weapon called the "russian revolver" that can only be used on yourself seems silly, no matter what angle you look at it from.

Ideally someone who inputs /suicide while also holding a firearm should have the trigger pulled, and if it's got a lethal round in the chamber it should discharge and kill. If not, it fails. There should be other contextual /suicide methods, like slitting your throat with blades. As it stands /suicide is just a ragequit when it could be a legitimate RP option.

2023-09-10 22:10 UTC, Hmeister-fake commented
My one tidbit is the ammo, cause if it comes with real 45. ammo then a fella with an actual revolver can use it but for real. Maybe make it kill you the same way with any ammo type and fill it with practice rounds?

2023-09-10 22:13 UTC, AJCM-git commented
I think adding the functionality to "shuffle" the chamber/ammo of any gun with a verb, and then allowing clicking on yourself (with a do_after of course), /suicide, or both to kill you if there is a bullet in the chamber would make a decent implementation for russian roullete.

2023-09-10 22:14 UTC, forgotmyotheraccount commented
> My one tidbit is the ammo, cause if it comes with real 45. ammo then a fella with an actual revolver can use it but for real. Maybe make it kill you the same way with any ammo type and fill it with practice rounds?

Even blanks can kill you IRL. Practice rounds could put you into crit rather than killing.

2023-09-10 22:21 UTC, BolloTea commented
> > > it should be possible to use any gun on yourself, in the ideal world
> > 
> > 
> > /suicide with gun in hand if gun has a bullet in chamber
> 
> This is the clear answer. Introducing a new weapon called the "russian revolver" that can only be used on yourself seems silly, no matter what angle you look at it from.
> 
I bet that if you indicate in the description that this revolver is intended exclusively for playing roulette, then many questions and misunderstandings will go away by themselves.  But regarding suicide, you can do things differently.  Give a short delay to the rest of the weapon before shooting yourself, so that you can cancel the action if it is accidental or just collect your thoughts.  And the roulette revolver itself has the possibility of instant suicide, because you have already consciously taken a step towards this game.

2023-09-10 22:30 UTC, BolloTea commented
Simply, the essence of this pr is not only to add suicide, but also to add an inferior weapon to the bartender, aimed at the entertainment of the station crew)

2023-09-10 22:32 UTC, BolloTea commented
Хочу отметить что ЛЕГАЛЬНОГО, а для того чтобы игроки лучше запомнили его, то для этого стоит добавить отдельную текстуру

2023-09-10 22:40 UTC, UbaserB commented
Hello, i’m the one who designed the idea of this concept based on ss13’s russian revolvers. As it stands, it is not meant to be a form of suicide as despite the fact it can kill you because /suicide currently works far too well for that. The reason why there is this specific revolver is primarily because from my experience playing russian roulette is way too funny and if it doesn’t right out kill you there isn’t that comedy factor in play. I don’t mind changing changing a few things to specify that its meant to be for the game, and i dont believe the bullet is an issue either since the only other revolvers in the game are the detective’s, syndicate’s and the deckard (if i remember correctly). About another point, i understand that “accidentally killing yourself” is an issue as its an instakill; and i was thinking that requiring harm mode to be active could be a solution for that. We just didnt know how to go about coding it and thought it wasnt exactly necessary so we left it out.

2023-09-10 22:44 UTC, UbaserB commented
> Simply, the essence of this pr is not only to add suicide, but also to add an inferior weapon to the bartender, aimed at the entertainment of the station crew)
> I want to note that it is LEGAL, and in order for players to remember it better, it is worth adding a separate texture for this!
> I'm done, sorry.

i copied the inspector sprites, did a rehue and changed some minor details since i thought it would fit better into the game’s style. Should i resprite it entirely then?

2023-09-10 22:49 UTC, UbaserB commented
> I forgot that this was for the bar- that'd obviously make it difficult to implement as a normal revolver without giving the barkeep their own revolver, which would cause other issues. It's still preferred that this isn't its' own gun, so some other solution would be appreciated if you could find one.
> Also, the method name should be changed. Something like MakeRoulette could work better

Just clearing it up, its not technically a gun. Its a joke item, similar to soap or space glue. It simply looks like a revolver and (partially) acts like one.

2023-09-10 22:59 UTC, asperger-sind commented
> Just clearing it up, its not technically a gun. Its a joke item, similar to soap or space glue. It simply looks like a revolver and (partially) acts like one.

Soap and glue both have legitimate gameplay appliances, this PR adds an item that has exclusively one purely esoteric feature.

2023-09-10 23:02 UTC, UbaserB commented
> > Just clearing it up, its not technically a gun. Its a joke item, similar to soap or space glue. It simply looks like a revolver and (partially) acts like one.
> 
> Soap and glue both have legitimate gameplay appliances, this PR adds an item that has exclusively one purely esoteric feature.

soap can only slip people, in 13 they can be used to clean but that purpose currently isnt in 14. Glue, maybe in one crafting recipe like i think improv shotgun uses it surre, but most of the time clown uses it for annoying people by applying it onto objects and it has no other purpose.

2023-09-10 23:05 UTC, RedNiloc commented
I think having something like this in the game would be fun. I think it should be a syndi items, or just a clown item.

2023-09-10 23:07 UTC, asperger-sind commented
My 2c on the matter (devi asked for takes on the pr in the discord)

The sprite should be a normal revolver with a curved barrel facing towards the user, the name should also be changed to "Russian Roulette Revolver" rather than just staying as "Russian Revolver" because that (along with the current sprites) can be interpreted as a "normal" *Russian* revolver, also change the method name to "make roulette" as Lank suggested.

Ideally all guns would be able to shoot the user but that's probably out of scope, even if that gets coded the barkeep still could have a Russian roulette revolver because its the big silly

Overall good PR, I don't see a reason to not have this in-game.

2023-09-10 23:34 UTC, MaloTV commented
Finally an easy way to kill myself (that fucking mouse AHHHHHHHH)

2023-09-11 01:33 UTC, Maksim22848 commented
> It would be better if this were not a separate weapon, but rather a change that allowed the normal revolver to target yourself. I also don't like the culturally insensitive use of "Russian revolver" and "Russianize", because this sounds like an insult to a whole cultural group.

Нас такое никак не оскорбляет, мы наоборот сами посмеёмся над этим лол

2023-09-11 05:05 UTC, ficcialfaint requested changes

2023-09-11 05:17 UTC, ficcialfaint requested changes

2023-09-11 05:17 UTC, ficcialfaint commented on Resources/Prototypes/Entities/Objects/Fun/russian_revolver.yml
> +      path: /Audio/Weapons/Guns/MagIn/revolver_magin.ogg
you don't need to write the default values in the prototype
```suggestion
    chambers: [ True, True, True, True, True, True ]
    ammoSlots: [ null, null, null, null, null, null ]
```

2023-09-11 05:23 UTC, MACMAN2003 commented on Content.Server/RussianRevolver/RussianRevolverComponent.cs
> +public sealed partial class RussianRevolverComponent : Component
what does an access attribute do

2023-09-11 05:30 UTC, metalgearsloth requested changes
This should just be an action to shoot a gun at yourself as we already have spins. If you really want add a separate action that runs the suicide command rather than just shooting yourself.

2023-09-11 05:36 UTC, MACMAN2003 commented on Content.Server/RussianRevolver/RussianRevolverComponent.cs
> +public sealed partial class RussianRevolverComponent : Component
i added one but i'm not sure i added it correctly

2023-09-11 06:17 UTC, UbaserB commented
> This should just be an action to shoot a gun at yourself as we already have spins. If you really want add a separate action that runs the suicide command rather than just shooting yourself.

by action, do you mean the left sidebar thing?

2023-09-11 06:47 UTC, UbaserB commented
nevermind i think i know

2023-09-11 07:51 UTC, MACMAN2003 commented
found a bug, the bullets that are inserted into the revolver don't get set as shot

2023-09-11 08:30 UTC, BolloTea commented
The curved trunk is certainly comical, but it would be more suitable for a clown and not a bartender.  So, a curved trunk is a big stupidity that should not be added.  I think many will agree with this

2023-09-11 08:38 UTC, BolloTea commented
>About another point, i understand that “accidentally killing yourself” is an issue as its an instakill; and i was thinking that requiring harm mode to be active could be a solution for that. We just didnt know how to go about coding it and thought it wasnt exactly necessary so we left it out.

Sorry, translation difficulties.  I meant the delay for other weapons, and not specifically for the Russian revolver.  Sorry if I misled you.  Nevertheless, your pr is what many have been waiting for, especially old like me.  So, thank you very much for your work.
Удачи🤠

2023-09-11 08:55 UTC, BolloTea commented
> My 2c on the matter (devi asked for takes on the pr in the discord)
> 
> The sprite should be a normal revolver with a curved barrel facing towards the user, the name should also be changed to "Russian Roulette Revolver" rather than just staying as "Russian Revolver" because that (along with the current sprites) can be interpreted as a "normal" _Russian_ revolver, also change the method name to "make roulette" as Lank suggested.
> 
> Ideally all guns would be able to shoot the user but that's probably out of scope, even if that gets coded the barkeep still could have a Russian roulette revolver because its the big silly
> 
> Overall good PR, I don't see a reason to not have this in-game.

And to avoid confusion, you need to make a correct description, and not change the name

2023-09-11 09:14 UTC, MACMAN2003 commented on Content.Server/RussianRevolver/RussianRevolverComponent.cs
> +public sealed partial class RussianRevolverComponent : Component
i figured out what i was doing wrong and fixed it

2023-09-11 10:06 UTC, UbaserB commented
> > My 2c on the matter (devi asked for takes on the pr in the discord)
> > The sprite should be a normal revolver with a curved barrel facing towards the user, the name should also be changed to "Russian Roulette Revolver" rather than just staying as "Russian Revolver" because that (along with the current sprites) can be interpreted as a "normal" _Russian_ revolver, also change the method name to "make roulette" as Lank suggested.
> > Ideally all guns would be able to shoot the user but that's probably out of scope, even if that gets coded the barkeep still could have a Russian roulette revolver because its the big silly
> > Overall good PR, I don't see a reason to not have this in-game.
> 
> And to avoid confusion, you need to make a correct description, and not change the name

we also did this

2023-09-11 21:51 UTC, VektorZ1 commented
Would be many times cooler to add the ability to point any revolver at yourself for a game of Russian roulette.

2023-09-11 21:53 UTC, Emisse commented
you should just be able to shoot yourself with a gun

2023-09-11 22:19 UTC, deltanedas commented
actions are bloat and would be annoying, imo it should be when you click yourself with a gun it makes a popup saying you place the barrel in your mouth and close your eyes, then when its up inflict 2x or whatever damage because its going right into your brain

2023-09-11 22:59 UTC, MACMAN2003 commented
i love waking up to a merge conflict
how do i fix that

2023-09-11 23:19 UTC, UbaserB commented
> you should just be able to shoot yourself with a gun

An issue with letting this happen means that the average person wouldnt be able to play russian revolver. You’re not allowed to carry a gun on your person unless you are security or the bartender, and this is simply meant to be a friendly game of russian roulette. However, i suppose it wouldn’t be hard to add an additional feature of using /suicide command while holding a gun to kill yourself with certainty.

2023-09-25 13:33 UTC, UbaserB commented
> This should just be an action to shoot a gun at yourself as we already have spins. If you really want add a separate action that runs the suicide command rather than just shooting yourself.

After trying to figure out how to implement this, we came to the realisation that not only should this change be done in a separate PR, but it is way out of scope for what we are trying to implement. Currently as it stands though, there is no issue with the current code and functions normally ingame.

2023-09-25 13:41 UTC, metalgearsloth requested changes
From discord:
no new guns
shouldn't "roulettify"
shouldn't be its own component
should just use an action
it also shouldn't be a 98.5% chance of spawning inside the booze locker

2023-09-25 13:46 UTC, MACMAN2003 commented
it's not a real gun, it's a toy.
as for switching it to an action, i have no idea how to implement that.

2023-10-06 06:42 UTC, Partmedia commented
I'm going to go ahead and close this, because to address the reviewer comments this would require a bit of a rework. Please feel free to open a new PR for this once it is ready.

2023-10-06 06:42 UTC, closed without merging