Add gas tanks throw damage
space-wizards/space-station-14 pull request #20035
Opened 2023-09-11 15:01 UTC by Slava0135

## About the PR

## Why / Balance

:trollface: 

## Technical details

* Renamed `IThrown.cs` to `ThrownEvent.cs`.

## Media

[Peek 2023-09-11 17-51.webm](https://github.com/space-wizards/space-station-14/assets/40753025/3aa7f1a2-3d92-4399-b67c-65f5b15de66f)

## Breaking changes

* `ThrownEvent` `user` field is now nullable.

**Changelog**

:cl:
- tweak: Gas tanks now deal damage when thrown. Be sure to hold them when opening valve... or not.

2023-09-11 15:14 UTC, deltanedas requested changes

2023-09-11 15:14 UTC, deltanedas commented on Content.Shared/Throwing/ThrownEvent.cs
> +public sealed class ThrownEvent : HandledEntityEventArgs
this should not parent handled event since:
- nothing actually handles it
- throwing system never checks ev.Handled

2023-09-11 15:14 UTC, deltanedas commented on Content.Shared/Throwing/ThrownEvent.cs
> +///     Raised when throwing the entity in your hands.
raised on what?

2023-09-11 15:55 UTC, deltanedas commented on Content.Shared/Throwing/ThrownItemSystem.cs
> +        private void ThrowItem(EntityUid uid, ThrownItemComponent component, ref ThrownEvent @event)
just leave it as args like everything else @event is ugly

2023-09-14 03:48 UTC, Partmedia commented
It seems a little strange to me that "damage target on thrown" is being singled out for gas tanks and not other entities, too. Why specifically gas tanks?

2023-09-14 12:43 UTC, Slava0135 commented
> It seems a little strange to me that "damage target on thrown" is being singled out for gas tanks and not other entities, too. Why specifically gas tanks?



> It seems a little strange to me that "damage target on thrown" is being singled out for gas tanks and not other entities, too. Why specifically gas tanks?

We could add this to some more dangerous items like crowbars or knives. With gas tanks I thought it would be funny because they can fly in random directions causing some havoc.

2023-09-30 21:46 UTC, mirrorcult commented
overall i think adding thrown damage to more things is good i would be in favor of adding it to a lot of other should-really-be-damaging entities. im especially ok w it on this because of the gas tank valve spinny

2023-10-05 17:55 UTC, iacore commented
Blunt Damage should scale with item mass. Also sharp stuff should have more damage.

2023-12-04 06:32 UTC, merged