Disable faxes in preparation phase of nukeops war
space-wizards/space-station-14 pull request #20031
Opened 2023-09-11 13:42 UTC by Morb0

## About the PR

Steel allow sending for emagged faxes (like Syndie)

## Why / Balance

Stop sending ERT requests!!1!
**MAN UP AND DEAL WITH IT**

## Technical details

- Adds `SendFaxAttemptEvent` cancellable event before sending fax

## Media

![fax](https://github.com/space-wizards/space-station-14/assets/14136326/d3798811-a136-4b7a-868b-ef03073fab52)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: After nukeops declaration of war, fax communication is suppressed

2023-09-11 13:57 UTC, deltanedas requested changes

2023-09-11 14:45 UTC, Morb0 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        ev.Reason = Loc.GetString("war-ops-fax-unavailable");
It seems more logical to me and I made it so that if the reason is an empty string then the popup will not appear

2023-09-11 14:46 UTC, Morb0 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +    private void OnSendFaxAttempt(ref SendFaxAttemptEvent ev)
Yeah, I missed it. Added blocking for all faxes that are not on the outpost grid.

2023-09-11 15:14 UTC, deltanedas commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +        ev.Reason = Loc.GetString("war-ops-fax-unavailable");
oh fair

2023-09-12 06:56 UTC, JoeHammad1844 commented
could be used to metagame when nukies can arrive

2023-09-14 03:49 UTC, Partmedia commented
I don't think this makes sense in game. Why shouldn't you be able to send faxes (that CentCom is going to ignore anyway)? This seems like it adds unnecessary dependencies between disparate systems for little IC or gameplay value.

2023-09-14 04:43 UTC, deltanedas commented
why shouldnt you be able to ftl? same reason

2023-09-14 04:48 UTC, Partmedia commented
> why shouldnt you be able to ftl? same reason

FTL is not restricted; the station's ability to call the emergency shuttle is, to prevent the round ending before the nukies arrive. This serves a specific gameplay purpose. Please give me a specific gameplay reason all faxes should suddenly stop working.

2023-09-14 05:07 UTC, Morb0 commented
> Why shouldn't you be able to send faxes (that CentCom is going to ignore anyway)?

Logically, if Centcom got the fax they shouldn't ignore the nuclear threat to the station.

2023-09-14 06:28 UTC, Partmedia commented
> Logically, if Centcom got the fax they shouldn't ignore the nuclear threat to the station.

CentCom is supposed to be able to hear announcements sent through the communications console. Logically, if the captain announces "nukies," then CentCom shouldn't ignore the nuclear threat to the station.

2023-09-14 06:35 UTC, Morb0 commented
> > Logically, if Centcom got the fax they shouldn't ignore the nuclear threat to the station.
> 
> CentCom is supposed to be able to hear announcements sent through the communications console. Logically, if the captain announces "nukies," then CentCom shouldn't ignore the nuclear threat to the station.

Announcements from communication console is voice-based station-wide only, while long-range bluespace faxes are what you need to communicate with CentCom.

2023-09-14 06:41 UTC, Partmedia commented
> Announcements from communication console is voice-based station-wide only, while long-range bluespace faxes are what you need to communicate with CentCom.

1. I don't think this matters. I don't think it makes sense for faxes to be blacked out. It's not like the admins are going to always send help, and it's not like faxes being broken will stop admins from sending help if they really wanted to. There are tons of IC reasons CentCom might not send help: they're too far, busy, etc. I still don't see an in-game purpose for this proposed feature.

2. Since when? Discord search is not great, but here is [an example from #stories that clearly shows the expectation that a communication console is for communicating with CentCom](https://discord.com/channels/310555209753690112/903965207091642429/989107329817526292).

2023-09-14 11:45 UTC, Morb0 commented
> > Announcements from communication console is voice-based station-wide only, while long-range bluespace faxes are what you need to communicate with CentCom.
> 
> 1. I don't think this matters. I don't think it makes sense for faxes to be blacked out. It's not like the admins are going to always send help, and it's not like faxes being broken will stop admins from sending help if they really wanted to. There are tons of IC reasons CentCom might not send help: they're too far, busy, etc. I still don't see an in-game purpose for this proposed feature.
> 2. Since when? Discord search is not great, but here is [an example from #stories that clearly shows the expectation that a communication console is for communicating with CentCom](https://discord.com/channels/310555209753690112/903965207091642429/989107329817526292).

1. I think it's matters. Operatives would suppress any station communications before such a major operation, preventing the station from calling for help.

2. Description of console. `A computer used to make station wide announcements, set the appropriate alert level, and call the emergency shuttle.`

2023-09-15 17:48 UTC, Partmedia commented
I've opted not to merge this for now.

- There is no IC reason to disallow on-station faxes being sent when nukies are coming.
- CentComs (admins) are free to ignore faxes. Further, if this is a roleplay problem, you can just consider a "no response" equivalent to "your message got jammed." If this is a problem on a different server, you can of course remove the CentCom fax.
- As it stands, merging this introduces an unnecessary interdependence between the fax system and the nukeops game rule.

2023-09-15 17:48 UTC, closed without merging