Chaplain Hoodie change
space-wizards/space-station-14 pull request #20096
Opened 2023-09-13 04:05 UTC by peptron1

## About the PR
I made the chaplain hoodie have its hood built in, and toggleable just like winter coats. Also a few tiny changes to names.

## Why / Balance
Literally just because I want to start contributing, and this seemed like a pretty easy thing to poke at.
Specifically, the PR addresses *part* of this issue: https://github.com/space-wizards/space-station-14/issues/20070

## Technical details
I made a new base for misc clothing that has a toggle, similar to winter coats. I was going to add this to more than just the chaplain hoodie but I do not want to sprite hoods for the grey and black hoodies.

**Changelog**

:cl:
- tweak: The chaplain hoodie now comes with its hood as an action, similar to winter coats

2023-09-13 04:09 UTC, DrSmugleaf approved these changes

2023-09-13 08:30 UTC, lzk228 requested changes
remove hood from chaplain vending machin

2023-09-13 08:30 UTC, lzk228 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
> +  noSpawn: True
```suggestion
  abstract: True
```

2023-09-13 14:18 UTC, KaiShibaa commented
Honestly the hood looks better with the Jensen coat than the hoodie itself imo. Bit sad this will remove it

2023-09-13 18:09 UTC, QuietlyWhisper commented
> Honestly the hood looks better with the Jensen coat than the hoodie itself imo. Bit sad this will remove it

it's just as easy to add it to the coats if you really want to have it

2023-09-14 22:28 UTC, peptron1 commented
so I agree that the hood looks good with the Jensen coat:
![image](https://github.com/space-wizards/space-station-14/assets/57651027/7ba851d0-3a72-4402-9bcc-81dc7a9281f2)
![image](https://github.com/space-wizards/space-station-14/assets/57651027/53ed46db-bff6-465b-9384-4f3e5084cb77)

but it's still the chaplain hoodie, and has that name and description, I assume it would be good to change it somehow so that the jensen coat doesnt just randomly have a chaplain hoodie attached to it?

2023-09-17 15:23 UTC, QuietlyWhisper commented
> so I agree that the hood looks good with the Jensen coat: ![image](https://user-images.githubusercontent.com/57651027/268125041-7ba851d0-3a72-4402-9bcc-81dc7a9281f2.png) ![image](https://user-images.githubusercontent.com/57651027/268125056-53ed46db-bff6-465b-9384-4f3e5084cb77.png)
> 
> but it's still the chaplain hoodie, and has that name and description, I assume it would be good to change it somehow so that the jensen coat doesnt just randomly have a chaplain hoodie attached to it?

you could make a new prototype that inherits from the chaplain hoodie and just change the name I guess

2023-09-18 01:10 UTC, merged