Tweak - Mechs can now open locked doors if the pilot has access to that door.
space-wizards/space-station-14 pull request #20185
Opened 2023-09-14 23:44 UTC by Simyon264

## About the PR

Doors will now check for a pilot when a mech attempts to open a door by bumping it. When a pilot is found, the pilots access is used.

## Why / Balance

The Ripley is pretty much useless in its current form. Getting in and out only to open a door takes a long time and having someone else do it for you gets boring real fast. Even worse when no one is around. This PR changes it so that doors check for pilots in mechs and it will use their access instead. 

Also see [this discord post](https://canary.discord.com/channels/310555209753690112/1150113194388496474)

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/63975668/d920f192-0e98-4a2e-abed-8dd4b379a5fa

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- tweak: Mechs can now open locked doors if the pilot has access to that door.

2023-09-14 23:47 UTC, EmoGarbage404 commented
The has access event should already be handling this?

2023-09-14 23:57 UTC, Simyon264 commented
It does not.

https://github.com/space-wizards/space-station-14/assets/63975668/f5c1fb55-355e-4d00-8957-53de38feac57

2023-09-15 00:07 UTC, EmoGarbage404 commented
The function OnGetAdditionalAccess in SharedMechSystem is what handled this in the past. That method should be fixed since it's more generally applicable to all access-related items.

2023-09-15 00:09 UTC, Simyon264 commented
Alright. Will update this tomorrow. Marking this as a draft for the time being.

2023-10-02 18:17 UTC, ElectroJr requested changes
Don't just do if-has-component checks like this. Instead have the mech redirect the get-access event to the pilot or whatever it was that OnGetAdditionalAccess was doing before it broke.

2023-10-05 03:22 UTC, EmoGarbage404 commented
Superceded by #20737

2023-10-05 03:22 UTC, closed without merging