Headsets
space-wizards/space-station-14 pull request #2023
Opened 2020-09-04 20:54 UTC by DrSmugleaf

Supersedes #1598

2020-09-05 11:02 UTC, DrSmugleaf commented
Reviews addressed

2020-09-05 12:24 UTC, exp111 reviewed
The mime is missing a headset as starting gear (apparently the service headset?).
Also they currently don't work, but you know that

2020-09-05 12:24 UTC, exp111 commented on Resources/Prototypes/Entities/Clothing/Earpieces/ears.yml
> +  description: The radio to keep up to date in real time with fun onboard station activities
I think descriptions are inherited

2020-09-05 12:24 UTC, exp111 commented on Resources/Prototypes/Entities/Clothing/Earpieces/ears.yml
> +  description:
Most of the headsets have no description. Is this a future junior job?

2020-09-06 05:42 UTC, metalgearsloth commented on Content.Server/GameObjects/Components/HandheldRadioComponent.cs
> +                : "The radio is now off.");
This should also be localised.

2020-09-10 09:53 UTC, exp111 reviewed
Couldn't test the handheld radio
![grafik](https://user-images.githubusercontent.com/17885980/92714112-10a4d480-f35c-11ea-8361-75825f6f6996.png)

```cs
[ERRO] go.comp.sprite: Unable to load RSI '/Textures/Objects/Devices/communication.rsi'. Trace:
SixLabors.ImageSharp.UnknownImageFormatException: Image cannot be loaded. Available decoders:
 - GIF : GifDecoder
 - TGA : TgaDecoder
 - JPEG : JpegDecoder
 - PNG : PngDecoder
 - BMP : BmpDecoder

   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Stream stream)
   at Robust.Client.ResourceManagement.RSIResource.Load(IResourceCache cache, ResourcePath path) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\ResourceManagement\ResourceTypes\RSIResource.cs:line 86
   at Robust.Client.ResourceManagement.ResourceCache.GetResource[T](ResourcePath path, Boolean useFallback) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\ResourceManagement\ResourceCache.cs:line 36
   at Robust.Client.GameObjects.SpriteComponent.ExposeData(ObjectSerializer serializer) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Renderable\SpriteComponent.cs:line 1072
[ERRO] go.comp.sprite: Layer has no RSI to load states from.cannot use 'state' property. Prototype: 'handrad'
[ERRO] root: Exception while loading resource Robust.Client.ResourceManagement.RSIResource at '/Textures/Objects/Devices/communication.rsi', no fallback available
```

2020-09-10 09:53 UTC, exp111 commented on Content.Server/Chat/ChatManager.cs
> +                message = message.Substring(1);
Maybe trim the start of the string? Many people will write "; hello" or ";hello" and we probably don't want the space there.

2020-09-10 09:53 UTC, exp111 commented on Content.Server/GameObjects/Components/HeadsetComponent.cs
> +                msg.MessageWrap = Loc.GetString("[{0}] {1} says, {{0}}", channel, source.Name);
![grafik](https://user-images.githubusercontent.com/17885980/92713833-bd328680-f35b-11ea-93c0-86229789f908.png)
Add the quotes

2020-09-10 09:53 UTC, exp111 commented on Content.Server/GameObjects/Components/HeadsetComponent.cs
> +                _netManager.ServerSendMessage(msg, playerChannel);
The player itself doesn't get the message, which would be nice as a confirmation "yes you really did send the msg on the radio"

2020-09-10 10:31 UTC, DrSmugleaf commented
Reviews addressed.

2020-10-07 00:00 UTC, ShadowCommander requested changes
It'd be nice for IActivate to be implemented on the HandheldRadioComponent, so that people don't have to pick it up to turn it on/off.

Later on multiple channels need to be implemented so that `:e` and `:q` work for specifying which preset frequency.
GUI for changing the frequency. (Usually on the handheld radio. Sometimes on the headset depending on codebase.)
Examine tooltip to see available radio prefixes.

2020-10-07 11:09 UTC, DrSmugleaf commented on Content.Server/Interfaces/IListen.cs
> +        void Broadcast(string message, IEntity speaker);
Done, they are both called CanListen and Listen now.

2020-10-07 11:10 UTC, DrSmugleaf commented
> It'd be nice for IActivate to be implemented on the HandheldRadioComponent, so that people don't have to pick it up to turn it on/off.
> 
> Later on multiple channels need to be implemented so that `:e` and `:q` work for specifying which preset frequency.
> GUI for changing the frequency. (Usually on the handheld radio. Sometimes on the headset depending on codebase.)
> Examine tooltip to see available radio prefixes.

All done except for the multiple prefixes and GUI. Should I do those in this pr as well?

2020-10-07 11:56 UTC, ShadowCommander approved these changes

2020-10-07 11:57 UTC, ShadowCommander commented
Should be fine like this. Channels, GUI, and examine can be added in a separate PR.

2020-10-07 12:02 UTC, merged