Make mice great again
space-wizards/space-station-14 pull request #20252
Opened 2023-09-16 12:15 UTC by BadRyuner

## About the PR

Added the ability for mice to disarm mousetraps. 

## Why / Balance
The chances of disarming may not be very balanced, but it's better than nothing. 

Players surround the entire kitchen with mousetraps. This completely kills the gameplay for the mouse. This PR gives a small chance for mouse players to sneak in there and bring CHAOS.

## Technical details
Added Verb for the mousetrap. When activated it randomly either kills the mouse, disarms the mousetrap and damages the mouse (a quarter of the mousetrap damage), or just disarms the mousetrap.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

[example.webm](https://github.com/space-wizards/space-station-14/assets/54708336/c744633b-364e-4711-b901-56b1558b9c84)

## Breaking changes

**Changelog**

- add: Mice can disarm a mousetrap

2023-09-16 12:16 UTC, deltanedas commented
mousetraps in the video look disarmed already...

2023-09-16 12:32 UTC, UbaserB commented
great idea

2023-09-16 20:41 UTC, Partmedia commented
> Players surround the entire kitchen with mousetraps. This completely kills the gameplay for the mouse.

I don't think so; they can go find food elsewhere. The only reason players surround the entire kitchen with mousetraps is if mice are being excessively egregious.

2023-09-16 20:47 UTC, deltanedas commented
yeah i very rarely see chefs mine the kitchen, severe lack of pros

2023-09-16 21:50 UTC, forgotmyotheraccount commented
The high rate of failure seems fair, I don't see an issue with it. Maybe add a doafter to prevent lucky players from blitzing through a mined kitchen in seconds.

2023-09-18 01:52 UTC, metalgearsloth requested changes

2023-09-19 12:51 UTC, metalgearsloth commented on Content.Server/Mousetrap/MousetrapSystem.cs
> +                if (_random.Prob(MathF.Min(0.99f, 0.15f * component.Difficulty))) // Chance to die
Don't use a dummy min statement, just check the value.

Also having a random chance to die makes this feature nearly pointless when they can just go around the mousetrap 99% of the time.

2023-09-19 12:51 UTC, metalgearsloth requested changes
Forgot to mention but this should also be added to shared and predicted.

2023-09-21 04:49 UTC, closed without merging