ADDS THE LOUD MOUTH TRAIT
space-wizards/space-station-14 pull request #20288
Opened 2023-09-17 13:41 UTC by Raitononai

## About the PR

ADDS A NEW TRAIT THAT MAKES YOU YELL ALL THE TIME. 
IT MAKES YOU ALWAYS SPEAK IN CAPS AND APPENDS "!!" TO EVERYTHING WITH A 20% CHANCE TO MAKE YOU VOCALISE YOUR RAGE. RAAAAAARGH.

## Why / Balance

ITS FUNNY AND I'M ANGRY, GRAAAAAAH!

## Technical details

ITS JUST ACCENT CODE BUT IT CAPITALISES EVERYTHING AND APPENDS "!!" ITS NOT THAT CONFUSING.
ADDS "LoudSystem" AND "LoudAccentComponent". YOU COULD USE THEM ON SOMETHING LIKE A FUNNY DRINK OR CHEM EFFECT IF YOU WANT, JUST LIKE OTHER ACCENT COMPONENTS.

## Media

https://github.com/space-wizards/space-station-14/assets/136900466/cea3d43d-bd63-4c18-826f-6fa28b14962c

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added the new 'Loud Mouth' trait, it's now possible to really express your emotions. Permanently.

2023-09-17 17:34 UTC, Equivocateur commented
Dr ANIMAL rp

2023-09-17 17:50 UTC, Tunguso4ka commented
:trollface:

2023-09-17 18:57 UTC, deltanedas commented
make it invert case so if you use caps it turns into lowercase
like that time we made a rage cage but called it calm cage and were screaming about GET ROBUST AT THE calm cage TODAY!!!!

2023-09-17 19:17 UTC, Raitononai commented
I like this idea, i'll do it tomorrow

2023-09-19 15:59 UTC, ficcialfaint requested changes

2023-09-19 15:59 UTC, ficcialfaint commented on Content.Server/Speech/EntitySystems/LoudSystem.cs
> +        var msg = message;
```suggestion
    {
        var msg = message;
```

2023-09-19 15:59 UTC, ficcialfaint commented on Content.Server/Speech/EntitySystems/LoudSystem.cs
> +        return msg;
The comment says `Apply random suffix to var if random chance succeeds`, but apparently it's vice versa, isn't it? Also the if-statement should probably be inverted and there are some odd blank lines which should be removed.
```suggestion
        if (!_random.Prob(component.YellChance))
            return msg;

        var pick = _random.Pick(component.YellSuffixes);

        msg = msg + " " + Loc.GetString(pick);
        return msg;
```

2023-09-20 08:44 UTC, Raitononai commented
I decided against invert case cause its a bit confusing when you type in full caps and get lower case, with the trait that's meant to make you yell.

2023-09-20 08:54 UTC, ficcialfaint requested changes

2023-09-20 08:54 UTC, ficcialfaint commented on RobustToolbox
Your PR shouldn’t modify any of the submodules

2023-09-20 15:48 UTC, Raitononai commented
How the fuck did i manage to do this

2023-09-20 15:52 UTC, GoodWheatley commented
> How the fuck did i manage to do this

Try updating the submodule on your local branch

2023-09-20 17:17 UTC, Raitononai commented
i'm just gonna close this and re-make the PR since it's just faster for me to do that

2023-09-20 17:17 UTC, closed without merging