Make latejoining not hardcoded to presets
space-wizards/space-station-14 pull request #2028
Opened 2020-09-05 21:47 UTC by DTanxxx

Made `DisallowLateJoin` a get&set property in GamePreset with a default value of false.

2020-09-06 10:31 UTC, Zumorica requested changes
Changing this to a property in the presets will do nothing.
You need to add an admin command that changes `DisallowLateJoin` in the GameTicker and afterwards calls `UpdateLateJoinStatus()`

2020-09-06 10:31 UTC, Zumorica commented on Content.Server/GameTicking/GamePreset.cs
> +        public virtual bool DisallowLateJoin { get; set; } = false;
Revert this change

2020-09-06 10:31 UTC, Zumorica commented on Content.Server/GameTicking/GamePresets/PresetSuspicion.cs
> +        public override bool DisallowLateJoin { get; set; } = true;
Also revert this

2020-09-06 20:39 UTC, DTanxxx commented
Hi Zumorica,
By adding an 'admin command', does that mean adding an IClientCommand to GameTickerCommands.cs?

2020-09-06 21:10 UTC, Zumorica commented
> Hi Zumorica,
> By adding an 'admin command', does that mean adding an IClientCommand to GameTickerCommands.cs?

Pretty much!

2020-09-06 21:13 UTC, Zumorica commented on Content.Server/GameTicking/GameTickerCommands.cs
> +        public string Description => "";
This should have a description saying what this command does

2020-09-06 21:13 UTC, Zumorica commented on Content.Server/GameTicking/GameTickerCommands.cs
> +        public string Help => "";
This should tell you the arguments you need to pass to the command

2020-09-06 21:13 UTC, Zumorica commented on Content.Server/GameTicking/GameTickerCommands.cs
> +            ticker.ToggleDisallowLateJoin(bool.Parse(args[0]));
You should only execute the command if you actually have the arguments (check the length of the args array and return if it's not enough)

2020-09-07 10:33 UTC, Zumorica approved these changes

2020-09-07 10:33 UTC, merged