Lizard "Rework"
space-wizards/space-station-14 pull request #20328
Opened 2023-09-19 05:02 UTC by LankLTE

## About the PR

Part of my Species Reworks, this gives lizards the ability to pull without hands, a diet restriction (Meat, Fruit, and Pills), and removes their random damage modifiers while toning up / down their notable ones to reasonable levels. Additionally normalizes their specific heat, removes their extra cold damage taken, and removes their random walking speed increase. 

## Why / Balance

To make lizards more unique as a species and remove their random damage modifiers, as discussed in [this](https://hackmd.io/-CnGYVtPQ2CHOJFp_ZYclA) design doc. 
This does outright disallow them from eating any other food (akin to moths). I'm not a *huge* fan of this implementation, but there is literally no way to do this otherwise that doesn't involve outright rewriting how food works. 

## Technical details

Any food I could find that was a fruit / meat has been tagged appropriately. This shouldn't break anything but it's possible (likely) I've missed a few, which can be fixed later. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Lank
- tweak: Reptilians have received a minor rework. Notable features include a diet restriction to only meat, fruit and pills, and the ability to pull objects using their tail.

2023-09-19 06:19 UTC, BolloTea commented
Why didn’t you like the cold?

2023-09-19 06:20 UTC, LankLTE commented
> Why didn’t you like the cold?

They still take cold damage sooner, they just don't take more. I don't know why I laid it out like that, I'd honestly be fine changing that back.

2023-09-19 06:20 UTC, Emisse approved these changes

2023-09-19 06:20 UTC, Emisse commented
i approve the stat changes n shit idk if this is the sane way to do the food but for now fuck it w/e

2023-09-19 06:21 UTC, LankLTE commented
Will fix test fails tomorrow

2023-09-19 06:22 UTC, BolloTea commented
> > Why didn’t you like the cold?
> 
> They still take cold damage sooner, they just don't take more. I don't know why I laid it out like that, I'd honestly be fine changing that back.

Thanks for the clarification, otherwise it sounded a little strange)

2023-09-19 06:33 UTC, LankLTE commented
> Will fix test fails tomorrow

I lied I'm doing it right now. 

> Thanks for the clarification, otherwise it sounded a little strange)

No problem. I also remember now that the point of it was to make emergency suits not completely unusable. You'll still die a lot faster, but not like, 3x as fast like you would before.

2023-09-19 06:45 UTC, UbaserB commented
i dont like the fact lizards cant eat pills please thats the only thing i wish for to be changed, considering my most important and main character is a lizard (im begging you)

2023-09-19 06:59 UTC, LankLTE commented
> i dont like the fact lizards cant eat pills please thats the only thing i wish for to be changed, considering my most important and main character is a lizard (im begging you)

I don't know if I made it clear enough but when I said "meat, fruit and pills" I mean that's *all* they can eat- so they can already eat pills still.

2023-09-19 10:09 UTC, VasilisThePikachu commented
I still really don't like the diet restrictions here, at least outright disallowing it. Would be better for the future to do a rework of food at this point since this just kinda sounds like a temporary "fix" that will just stick around in the end.

2023-09-19 10:42 UTC, UbaserB commented
> > i dont like the fact lizards cant eat pills please thats the only thing i wish for to be changed, considering my most important and main character is a lizard (im begging you)
> 
> I don't know if I made it clear enough but when I said "meat, fruit and pills" I mean that's _all_ they can eat- so they can already eat pills still.

oh ok lol

2023-09-19 21:20 UTC, IProduceWidgets commented
Lizards are already poisoned by chocolate, would it make sense to extend that as a food limitation rather than simply stopping them from eating altogether?

2023-09-19 21:26 UTC, VasilisThePikachu commented
> Lizards are already poisoned by chocolate, would it make sense to extend that as a food limitation rather than simply stopping them from eating altogether?

Thats kinda part of the "food rework" they were talking about. With the way food is coded right now its kinda hard. Plus making it toxic sounds kinda worse tbh. In 13 they can eat everything but stuff like grain or something like that gave you a mood debuff. We wont have moods here anytime soon... soooo

2023-09-19 21:31 UTC, LankLTE commented
Also, I think poisoning them is sort of unintuitive for new players because, at least with how it’s currently implemented for things like chocolate, people would just go to eat something they could as any other race then suddenly start dying. That seems weird when we have the ability to stop them from eating them anyways.

2023-09-19 22:02 UTC, Hmeister-fake commented
Maybe if the cold damage modifier was replaced by something more unique like being getting cold over time (cold blooded and all, don't generate heat) and being unable to gain heat without a space pen or other drugs, warm clothing, or maybe make it so that when they get hugged they get a little warmer

2023-09-20 02:33 UTC, JoeHammad1844 commented
why did you reduce their heat damage so much?

2023-09-20 02:35 UTC, LankLTE commented
> why did you reduce their heat damage so much?

They used to have fairly good resistances which were removed, and this current resistances set mirrors moths (0.7 cold and 1.3 heat). I know heat is more relevant in combat, but given cold is the more common type environmentally I feel it'll balance out (and it's really easy to fix if it doesn't)

2023-09-20 02:39 UTC, JoeHammad1844 commented
that makes sense but 30% resistance still feels a like little too much, although you'll mostly only encounter it when getting shot with a laser, but a lizard wearing a sec vest will, if my math isnt wrong, add up to 60% resistance, which is just as good as an elite hardsuit and 90% with an elite hardsuit

2023-09-20 02:41 UTC, LankLTE commented
> a lizard wearing a sec vest will, if my math isnt wrong, add up to 60% resistance, which is just as good as an elite hardsuit and 90% with an elite hardsuit

Your math is wrong. Not only does that not check out additively (sec vest is 20% heat resist), damage modifiers in this game are multiplicative, so a lizard with a sec vest comes out to about 45% resistance

2023-09-20 02:52 UTC, JoeHammad1844 commented
so 30% multiplied by 20%

2023-09-20 02:54 UTC, LankLTE commented
> so 30% multiplied by 20%

The damage coefficients are multiplied, not the resistance percentages. 0.7 (species) * 0.8 (vest) to get 0.56 (44% resistance)

2023-09-20 04:30 UTC, LankLTE commented
Tests work locally- fairly certain test fail is erroneous.

2023-09-24 16:19 UTC, LankLTE commented
Don't mind that, I'm just an idiot.

2023-09-24 23:43 UTC, crazybrain23 requested changes
Nearly every time you added a tag, you've overridden the previously inherited tags by not including them, which is causing the test errors (among other bugs).

2023-09-24 23:44 UTC, LankLTE commented
> Nearly every time you added a tag, you've overridden the previously inherited tags by not including them, which is causing the test errors (among other bugs).

I had just hoped there weren't any. Damnit.

2023-09-24 23:45 UTC, crazybrain23 commented
> > Nearly every time you added a tag, you've overridden the previously inherited tags by not including them, which is causing the test errors (among other bugs).
> 
> I had just hoped there weren't any. Damnit.

Pizza and bread are the two I checked, but there's probably more.

2023-09-25 04:06 UTC, LankLTE commented
holt shit it works

2023-09-25 07:34 UTC, crazybrain23 commented
> Pizza and bread are the two I checked, but there's probably more.

Pie and soup also need fixing.

2023-09-27 01:14 UTC, LankLTE commented
> Pie and soup also need fixing.

fixed 👍

2023-09-30 20:11 UTC, LankLTE commented
Think the tags are all fixed / it's good

2023-10-06 19:30 UTC, Partmedia commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +    - DoorBumpOpener
Why was this added here?

2023-10-06 19:33 UTC, LankLTE commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +    - DoorBumpOpener
Probably an accident.

2023-10-06 19:34 UTC, LankLTE commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +    - DoorBumpOpener
Have removed it now, sorry

2023-10-06 21:17 UTC, Partmedia approved these changes

2023-10-06 21:19 UTC, merged