Syndies can buy zombie bundle
space-wizards/space-station-14 pull request #20358
Opened 2023-09-20 06:21 UTC by JoeHammad1844

## About the PR

the syndicate zombie bundle can now be purchased by traitors and can spawn in the surplus bundle
## Why / Balance

it requires two syndicates to collaborate, doesn't come with a hypo and the hypopen is 6TC so you'll need a third traitor to buy it so youll be stuck with a slow injection and it likely wont be purchased anyway because it wont really help you with your injections

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: JoeHammad
- tweak: Traitors can now buy the syndicate zombie bundle.
- tweak: The syndicate zombie bundle can now come in surplus crates.

2023-09-20 07:08 UTC, LankLTE commented
Not a huge fan of thi. Syndies have a lot of tools to pull off a zombie bundle, namely inherent stealth, that nukies don’t. Nobody is suspicious about a doctor injecting someone, for example, but then when the patient turns they could easily infect all of medbay. 
Zombies are also easily a round ending threat, and this is fine with nukies because they’re already roundending, but 2 syndies being able to conspire to effectively end the round by adding another major antag isn’t a great idea imho.

I’ll still leave it open for discussion and other opinions in case I’m alone here.

2023-09-20 07:31 UTC, KompaniLinge commented
If this gets implemented, 40tc seems far too little, especially seeing how much of a trump card it is. Minimum 41 tc, 50 ideal. 
If we want something so round ending as zombies to be implemented for normal syndies, it needs to be something that takes more then just 2 guys.

2023-09-20 07:37 UTC, JoeHammad1844 commented
alright, ill increase it to 45

2023-09-20 07:38 UTC, KompaniLinge commented
> alright, ill increase it to 45

45 only for synds, right? It should remain at 40 for nukies.

2023-09-20 07:40 UTC, JoeHammad1844 commented
yep, 40 for nukies but 45 for syndies, so you either need 3 guys or 2 and to butcher renault without using TC, which is is hard

2023-09-20 08:50 UTC, QuietlyWhisper commented
It sounded like a cool concept to have many syndicates betray or decide together to buy a zombie kit, but then it occured to me it really doesnt help anyone and simply ends the round-

2023-09-20 11:57 UTC, JoeHammad1844 commented
thats sortof the point, most people wont go for it because they want to do their objectives, and finding two other people to do the same would be hard. this will be picked rarely and likely would not succeed anyway because most zombie rounds ive seen dont have zombies dominate, even with like 5 initial infected, and they can turn at will.

a doctor with romerol injecting people saying its medicine wouldn't be very different to a doctor turning in medbay and biting crit people, except the traitor gets to leave. come to think of it it would be a good distraction to have so you can do your objectives while everyone is focused on the zombies

2023-09-20 12:50 UTC, Equivocateur requested changes
Should be moved to final objective when a traitor has fully greentexted.

2023-09-21 03:56 UTC, JoeHammad1844 commented
is that even in the game yet?

2023-09-21 05:48 UTC, LankLTE commented
The zombie bundle is intentionally locked behind nukies as zombies can very easily end a round, but nukies already do so. Giving one syndie the ability to effectively force a round end by getting lucky with a super surplus is not something we’re interested in having.

2023-09-21 05:48 UTC, closed without merging