Power monitors for distributors
space-wizards/space-station-14 pull request #20395
Opened 2023-09-21 18:12 UTC by chromiumboy

## About the PR

- Added UIs to the SMES and substation. These UIs display the battery charge, current power load, and the quality of the external power supply. It also displays all of the device's sources and loads in a scrollable window
- The external power description includes a new state - 'stable'. Appears when power supply and power demand are roughly equal (within 10% of each other)
- The power monitoring console and APC have also been given a face lift
- SMES, substations and APCs all list their assigned name at the top of their respective UIs
- Duplicated UI code has been removed and is handled by a common system

This PR closes #2878

## Why / Balance

This PR adds missing UI elements to the SMES and substation. The addition of source/load monitoring to these devices will also assist in diagnosing issues in the local power net, which is difficult at present

The power monitor console will continue to serve a role in the game by allowing players to check the status of all SMES and substations on a cable network simultaneously, to get an overview picture of what's going on with the primary storage and distribution system (for further diagnosis, the player would then go to the problematic machine). It will also continue to allow players to monitor the stations primary power status from other places, such as the CE office and bridge

## Technical details

The code for power monitoring has been generalised and is now handled on the server by 'PowerMonitoringSystem' and 'PowerMonitoringComponent'. Client side UI handling for this system (e.g., drawing the charge bars, querying the external power status, updating the lists of sources and loads) have been centralized into the client 'PowerMonitoringSystem'. Messages between the server and client for these systems are contained in 'SharedPowerMonitoringComponent'

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![smes_sources](https://github.com/space-wizards/space-station-14/assets/50505512/416ac4e2-e00a-4195-910f-9981d5a4ef8d)![smes_loads](https://github.com/space-wizards/space-station-14/assets/50505512/58665248-b440-4362-83c9-d560388a4066)

![substation_sources](https://github.com/space-wizards/space-station-14/assets/50505512/0314fcb2-17d0-44d4-b835-05afb85a425b)![substation_loads](https://github.com/space-wizards/space-station-14/assets/50505512/8ee10c90-5ebf-4d34-a49c-f0fc11782b14)

![powermonitor_sources](https://github.com/space-wizards/space-station-14/assets/50505512/c917b687-0958-468c-a3e3-2d8cad8b3aa5)![powermonitor_loads](https://github.com/space-wizards/space-station-14/assets/50505512/4e034401-cf2f-4153-9240-72d99c5a019c)

## Breaking changes

- 'PowerMonitoringConsoleComponent' has been removed and replaced with the more generalised 'PowerMonitoringComponent'
- 'SharedPowerMonitoringConsoleComponent' has been removed and replaced with the more generalised 'SharedPowerMonitoringComponent'
- 'HasAccess' has been removed from 'ApcComponent' (a client-side access check has been added to ApcMenu.xaml.cs in its place)
- 'ApcExternalPowerState' has been replaced with the more generalised 'ExternalPowerState' 
- 'LastExternalState' has been moved from 'ApcComponent' to 'NetworkBatteryComponent'

**Changelog**

- add: UIs have been added for the SMES and substation

2023-09-21 22:06 UTC, Partmedia commented
In "Breaking changes", please add specific instructions for a fork to port over code. If your replacements are drop-in replacements, say that. If other changes (e.g. method names, argument order, etc.) changes, provide a one to one mapping of old functions to new.

2023-09-21 22:26 UTC, deltanedas commented
also changelog needs :cl:

2023-09-22 15:11 UTC, AJCM-git commented on Content.Client/Power/PowerMonitoring/PowerMonitoringSystem.cs
> +public sealed class PowerMonitoringSystem : EntitySystem
This is super not allowed, system methods shouldnt ever care about UI controls, move these to the window or make a UI controller if necessary

2023-09-22 15:16 UTC, AJCM-git commented on Content.Server/Power/Components/PowerMonitoringComponent.cs
> +public sealed partial class PowerMonitoringComponent : Component, ISerializationHooks
Serialization hooks are deprecated, please dont use them

2023-09-22 15:28 UTC, AJCM-git commented on Content.Server/Power/EntitySystems/PowerMonitoringSystem.cs
> +        Resolve(uid, ref netBattery, false);
Either make this a check or use trycomp

2023-09-22 15:30 UTC, AJCM-git commented on Content.Server/Power/EntitySystems/PowerMonitoringSystem.cs
> +        foreach (PowerSupplierComponent powerSupplier in netQ.Suppliers)
Use var (same for the other loops)

2023-09-22 15:32 UTC, AJCM-git commented on Content.Server/Power/EntitySystems/PowerMonitoringSystem.cs
> +        PowerNetworkBatteryComponent? battery = null;
Dont use resolves like this, trycomp exists

2023-09-22 15:34 UTC, AJCM-git requested changes
.

2023-09-23 17:18 UTC, chromiumboy commented
> .

Cheers for the review, I wasn't expecting one so quickly! :)

2023-09-27 18:01 UTC, chromiumboy commented
Just FYI, this PR is on hold while I work on improving the power monitoring console itself

2023-10-06 03:16 UTC, Partmedia commented
I think these changes are fine, if you'd like to un-draft them and have them in-game as an interim before we get improved power monitors.

2023-12-27 05:27 UTC, AJCM-git commented
@chromiumboy you coming back to this?

2023-12-27 08:08 UTC, chromiumboy commented
> @chromiumboy you coming back to this?

Not at the moment, and this will need a rethink and major refactoring now that the power monitoring console PR has been merged. So I'll close this for now

2023-12-27 08:08 UTC, closed without merging