fire extinguisher go brrrrrr
space-wizards/space-station-14 pull request #20479
Opened 2023-09-24 23:06 UTC by EmoGarbage404

## About the PR

- buffs fire extinguishers to 10 bursts instead of 4
- makes fire extinguishers launch the player farther.

## Why / Balance

fire extinguishers are fairly underpowered as mobility tools. This makes them a lot better as a tool for moving around.

## Media

https://github.com/space-wizards/space-station-14/assets/98561806/3393de52-d951-4a16-8a79-ddb6cab987b9

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Fire extinguishers now use less fluid per burst and launch the user farther in low-gravity.

2023-09-24 23:41 UTC, AJCM-git requested changes

2023-09-24 23:41 UTC, AJCM-git commented on Content.Server/Fluids/Components/SprayComponent.cs
> +    [ViewVariables(VVAccess.ReadWrite), DataField,]
Typo

2023-09-24 23:41 UTC, AJCM-git commented on Content.Server/Fluids/Components/SprayComponent.cs
>  using Content.Server.Fluids.EntitySystems;
May as well get rid of properties

2023-09-25 00:52 UTC, CatMagic1 commented
As seen in WALL-E

2023-09-25 01:33 UTC, AJCM-git approved these changes

2023-09-25 01:33 UTC, merged