Necropolis and mine walls
space-wizards/space-station-14 pull request #20578
Opened 2023-09-28 16:48 UTC by NULL882

## About the PR

For https://github.com/space-wizards/space-station-14/issues/14226

Just walls for some lavaland structures.

## Why / Balance

This walls need for https://github.com/space-wizards/space-station-14/issues/14226, lavaland wall assets.

## Technical details

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![image](https://github.com/space-wizards/space-station-14/assets/104377798/0d53e9ef-625f-4476-878e-f9197d6b48c6)
![image](https://github.com/space-wizards/space-station-14/assets/104377798/65f64164-df68-4977-befb-c1dbcd3c296b)

## Breaking changes

**Changelog**

:cl: NULL882
- add: Added necropolis wall.
- add: Added Mine Wall.
- add: Added Sings for Mine Wall

2023-09-28 16:50 UTC, mirrorcult requested changes
all the actual stuff looks good

2023-09-28 16:50 UTC, mirrorcult commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/signs.yml
> +  description: A sign, survivals is written on it.
```suggestion
  description: A sign. "Survival" is written on it.
```

2023-09-28 16:50 UTC, mirrorcult commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/signs.yml
> +  description: A sign, mine is written on it.
```suggestion
  description: A sign. "Mine" is written on it.
```

2023-09-28 16:54 UTC, NULL882 commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/signs.yml
> +  description: A sign, mine is written on it.
Done.

2023-09-28 16:54 UTC, NULL882 commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/signs.yml
> +  description: A sign, survivals is written on it.
Done.

2023-09-28 17:07 UTC, mirrorcult approved these changes

2023-09-28 17:07 UTC, merged

2023-09-29 00:31 UTC, Carolyn3114 commented
wait, how's there a watcher there?

2023-09-29 00:32 UTC, mirrorcult commented
we have watchers

2023-09-29 00:32 UTC, Carolyn3114 commented
must be new