Syndicate Bombs were Intended to Be CanCollide
space-wizards/space-station-14 pull request #20573
Opened 2023-09-28 15:02 UTC by gusxyz

## About the PR
Discussed with rain they were meant to be can collide. 
Its intended to spawn it unanchored, it wont get you stuck now

## Media
 ![gif](https://i.imgur.com/ihMFi9U.gif)
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-09-28 15:16 UTC, Just-a-Unity-Dev commented
you forgot `ed`

2023-09-28 15:21 UTC, gusxyz commented
> you forgot `ed`

💀

2023-09-28 23:09 UTC, metalgearsloth commented
Why is this static but not anchored?

2023-09-29 00:29 UTC, gusxyz commented
its dynamic and removed noRot

2023-09-29 20:59 UTC, Partmedia commented
This kind of behaves weirdly when it's noRot but still allowed to rotate, e.g. taking this and pushing it into a wall causes to rotate, with no way to rotate it back.

![image](https://github.com/space-wizards/space-station-14/assets/3229565/cac9323a-0a4c-4a1a-b3e7-dd22e7194d26)

2023-10-01 00:23 UTC, gusxyz commented
added rotatable tag

2023-10-06 03:20 UTC, Partmedia requested changes
Sorry for the delay on this. Please see the review comments.

2023-10-06 03:20 UTC, Partmedia commented on Resources/Prototypes/Entities/Structures/Machines/bombs.yml
> +      bodyType: Dynamic
This duplicates what's already in `BaseStructureDynamic`.

2023-10-06 03:20 UTC, Partmedia commented on Resources/Prototypes/Entities/Structures/Machines/bombs.yml
>      - type: Transform
This also duplicates what's already in `BaseStructureDynamic`.

2023-10-06 06:18 UTC, Partmedia commented
Now the bomb doesn't snap itself to a cardinal direction when it anchors itself, but I'm fine with this.
![image](https://github.com/space-wizards/space-station-14/assets/3229565/40dd24ac-d556-4be4-b0bc-41c12c641dff)

2023-10-06 06:21 UTC, Partmedia commented
What's weird is that when you anchor it with a wrench, it snaps correctly, but it doesn't snap when you begin the countdown, hmm...

2023-10-06 06:29 UTC, Partmedia commented
The bug is that `TryStartCountdown` uses `_transform.AnchorEntity()` instead of going through AnchorableSystem's `OnAnchorComplete()` which handles the cardinal direction snapping. Since this is not your bug, I'm going to go ahead and merge this. @Just-a-Unity-Dev

2023-10-06 06:29 UTC, Partmedia approved these changes

2023-10-06 06:29 UTC, merged

2023-10-06 07:48 UTC, Just-a-Unity-Dev commented
> The bug is that `TryStartCountdown` uses `_transform.AnchorEntity()` instead of going through AnchorableSystem's `OnAnchorComplete()` which handles the cardinal direction snapping. Since this is not your bug, I'm going to go ahead and merge this. @Just-a-Unity-Dev 

a

https://github.com/space-wizards/space-station-14/assets/67359748/9313edf8-5626-4052-b7fd-59634d7b508e

I'll try to fix it within this week, but I've hit a motivation block