Inventory-like GUI for stripping. (draft)
space-wizards/space-station-14 pull request #2060
Opened 2020-09-10 21:19 UTC by sentient-ai

Apparently calls to ItemSlotButton.OnPressed with left/right clicks send 2 calls back to back. Middle's don't.
Double calls break shit with null-shenaniganry when you try to shove nonexistent things on peoples bodies.

Have not figured out hands/cuffs, or even the sprites to fill the GUI. Plagiarism only gets me so far.

All negative input on this monstrosity appreciated.

2020-09-14 22:40 UTC, sentient-ai commented
https://streamable.com/w4hxgp

okay. fixed the weird double-call interaction, hands work, sprites work.
i'm pretty happy with it now.
just accepting that uncuffing oughta be done from the right click menu, unless there's more reworks to be had.

2020-09-20 23:21 UTC, Zumorica requested changes
Read my review. I'd personally recommend you handle hands separately from other slots.

2020-09-20 23:21 UTC, Zumorica commented on Content.Shared/GameObjects/Components/Inventory/EquipmentSlotDefinitions.cs
> +            RHAND,
This is WAY too hardcoded... Currently you can add hands to any humans with a simple command, so it'd be best if you didn't hardcode slots like this, and instead handled multiple hands sanely.

2020-10-26 18:08 UTC, Zumorica commented
@sentient-ai is it fine if I take over this and finish it myself?

2020-12-22 06:34 UTC, SweptWasTaken commented
Please finish this PR.

2020-12-22 19:27 UTC, sentient-ai commented
I completely missed the comment by Zum two months ago. Really got stuck on finding a way to get the extra hands / handcuffs working and dropped off the face of the earth, sorry.

2020-12-22 19:28 UTC, Zumorica commented
I can take it off your hands if you want me to, your call

2020-12-22 19:29 UTC, sentient-ai commented
Please do, don't feel qualified to do it justice at the moment. If I keep contributing I'll stick to lower level stuff.

2021-01-06 23:47 UTC, SweptWasTaken commented
> 
> 
> I can take it off your hands if you want me to, your call

15 days and no pulse, closing.

2021-01-06 23:47 UTC, closed without merging