disposal tube refactor
space-wizards/space-station-14 pull request #20801
Opened 2023-10-07 02:24 UTC by deltanedas

## About the PR
you can count the rings on disposals code to see how old it is
this refactors the tube related code

## Why / Balance
i will be adding new disposal piece soon so time to clean up this mess

## Technical details
- general cleanup of tube/tagger/router code
- no virtual transit/junction component tagger and router are now separated from them
- sound params are on the sounds instead of hardcoded
- router event overriding is better
- make shared ui stuff less evil
- move router and tagger code into their own systems

## Media
router with matching tag
![01:20:48](https://github.com/space-wizards/space-station-14/assets/39013340/1cfa1017-eed1-4d2d-90d6-24b68d4603a8)

router without matching tag
![01:21:00](https://github.com/space-wizards/space-station-14/assets/39013340/e6ecab84-5e0f-4795-b84f-c4891c46a420)

junction still work yep
![01:22:01](https://github.com/space-wizards/space-station-14/assets/39013340/670f0d00-5317-4db8-9b16-b1cc4b73d572)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
`SharedDisposalRouterComponent` removed and is now just the ui code in `DisposalRouterUi.cs`
`SharedDisposalTaggerComponent` removed and is now just the ui code in `DisposalTaggerUi.cs`
anything that has `DisposalRouterComponent` now also needs `DisposalJunctionComponent`
anything that has `DisposalTaggerComponent` now also needs `DisposalTransitComponent`

most likely nobodys made their own disposals pieces yet but who knows...

**Changelog**
no cl no fun

2023-10-07 10:59 UTC, brainfood1183 commented
Any chance u could fix the disposal unit sprite layers? it uses a layer called charging that isnt listed in the proto (must be in the component or something). If you try to create a new unit it will keep blinking back to the disposal_charging layer. Only way i found to fix this is to add a new unit sprites in a separate folder and you need to name the charging layer disposal_charging.

2023-11-15 05:48 UTC, metalgearsloth commented
pro

2023-11-15 05:49 UTC, metalgearsloth requested changes
Apparently I started a review at some point.

2023-11-15 05:49 UTC, metalgearsloth commented on Content.Server/Disposal/Tube/Systems/DisposalTaggerSystem.cs
> +    }
Same here.

2023-11-15 06:00 UTC, deltanedas commented
bruh i thought i deleted this :trollface:

2023-11-15 06:00 UTC, closed without merging