A return to foam (foam rework)
space-wizards/space-station-14 pull request #20831
Opened 2023-10-08 04:25 UTC by EmoGarbage404

## About the PR

Adds back in the ability for foam/smoke to transfer reagents, but with a few changes:
- Smoke/foam no longer transfers the entire volume of the solution in a second, instead transferring a percentage based on the duration of the foam. In layman's terms: standing in foam/smoke should never give an individual more u of a solution than was originally present.
- Modified the spreading to be more even and less horrifically jank.
- Fixed the foam dissolving animation. Also fixed when it would mispredict at the end and play multiple times.
- Adjusted the vent foam event to be less completely insane. 200u per foam??? 

Fixes #20830 20732

## Why / Balance

chem smoke/foam is fun and it should be back

## Media

https://github.com/space-wizards/space-station-14/assets/98561806/141a220e-cae4-4e10-a721-fc583c9b9266

video of updated spreading code + animation fix

https://github.com/space-wizards/space-station-14/assets/98561806/18e6f9b2-d6ad-48c6-8614-0242d9f41936

video of the solution transfer changes.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

renamed SmokeSystem.Start to SmokeSystem.StartSmoke + added new parameters. These were required anyway so this is just streamlining the function.

SmokeComponent is now in shared.

**Changelog**

:cl:
- add: Foam and smoke can now transfer chemicals when inhaled. Wear internals to avoid this.
- fix: Fixed foam dissolution animation.

2023-10-08 04:27 UTC, deltanedas commented
ipecac pax foam my beloved

2023-10-09 01:00 UTC, brainfood1183 commented
this include foam artifact effects?

2023-10-09 07:28 UTC, Myakot commented
Dissolution animation looks much better, thanks!

2023-10-16 06:07 UTC, metalgearsloth requested changes

2023-10-16 06:07 UTC, metalgearsloth commented on Content.Server/Fluids/EntitySystems/SmokeSystem.cs
> +        var smokeAffected = EnsureComp<SmokeAffectedComponent>(args.OtherEntity);
AddComp as you already checked it.

2023-10-16 06:07 UTC, metalgearsloth commented on Content.Server/Fluids/EntitySystems/SmokeSystem.cs
> +            return;
Use EntityQuery<T> for this + onendcollide

2023-10-16 06:07 UTC, metalgearsloth commented on Content.Shared/Chemistry/Components/SmokeAffectedComponent.cs
> +public sealed partial class SmokeAffectedComponent : Component
NetworkedComponent prolly.

2023-10-27 02:52 UTC, metalgearsloth approved these changes

2023-10-27 02:52 UTC, merged