blue blood now requires copper instead of iron to cure bloodloss
space-wizards/space-station-14 pull request #20863
Opened 2023-10-09 15:33 UTC by brainfood1183

Blue blooded creatures such as spiders and crabs now require copper to stop bloodloss instead of iron. (giving them iron tablets will poison them).

Added - new tag CopperBlood (add to mobs with blue blood to make them require copper for bloodloss).
Renamed - spider blood to hemocyanin blood ( not just for spiders).
Changed - crabs now have blue blood.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2023-10-09 17:50 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
> +    bloodReagent: CopperBlood # would be cool if they had to drink copper instead of iron but that might just be more bloat to deal with.
:trollface: it would be cool indeed

2023-10-09 18:05 UTC, brainfood1183 commented on Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
> +    bloodReagent: CopperBlood # would be cool if they had to drink copper instead of iron but that might just be more bloat to deal with.
its in ss13 so it will be so :)

2023-10-10 01:34 UTC, mirrorcult requested changes
i'd prefer for a new reagent condition to get added that just checks for blood reagent rather than doing it indirectly through tags and `HasTag`

2023-10-11 21:30 UTC, brainfood1183 commented
> i'd prefer for a new reagent condition to get added that just checks for blood reagent rather than doing it indirectly through tags and `HasTag`

Might be out of my league but i will give it a go :)

2023-10-17 17:32 UTC, brainfood1183 commented
> i'd prefer for a new reagent condition to get added that just checks for blood reagent rather than doing it indirectly through tags and `HasTag`

created a new metabolizer type and modified the arachnid heart to metabolize iron and copper differently then applied this new heart to all hemocyanin animals as well.

2023-10-31 20:41 UTC, mirrorcult approved these changes

2023-10-31 20:41 UTC, merged