Preliminary scrubber buff
space-wizards/space-station-14 pull request #20946
Opened 2023-10-12 12:41 UTC by BasedUser

## About the PR
Scrubbers have been buffed from 200 L/s to 12500 L/s. This value shouldn't be final (i.e. gas leaks possibly not being a problem), but it's a decent start.
Although, I think that the value should be anywhere from 1000L/s to 4000L/s for single scrubbers - 1000L/s because of 5 would-be scrubber layers and 4000L/s to mostly preserve atmos setups.
This PR can be closed freely should a more complete atmos balance rework happen.

## Why / Balance
Response to #20917.

## Technical details
Air alarm presets have been changed. Scrubbers have a higher `maxTransferRate` defined in their prototype.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: router
- tweak: Scrubbers have been buffed to 12500L/s to account for slow radiators. This change is temporary, more balance feedback is needed for a proper scrubber balance level.

2023-10-12 13:05 UTC, GoodWheatley commented
This value would make scrubbers 62 times stronger than their previous value, even stronger than if you were abusing the stacking bug in the first place. How on earth is this value reasonable?

2023-10-12 18:30 UTC, Partmedia requested changes
This isn't a problem with your changes but rather the old code, but I think `GasVentScrubberData` should store a float `VolumeRate` between 0-1 that represents the transfer rate normalized to the component's MaxTransferRate. Would you be able to PR that in a separate PR, such that this balance change becomes a 1-line YAML change? That would make it easier to make future balancing changes as needed.

I'm also thinking that a buff to only scrubbers doesn't work well, because then you'll just get backing up of whatever is connected next. I think a global bump up in `Atmospherics.MaxTransferRate` might be more appropriate.

2023-10-12 18:33 UTC, deltanedas commented
even with 32 stacked scrubbers the scrubbers are the bottleneck, pumps are much faster

2023-10-12 18:42 UTC, deltanedas commented
ok more pro idea what if plasteel scrubber that scrubs faster intended for gas production instead of station usage

2023-10-12 18:46 UTC, Partmedia commented
> ok more pro idea what if plasteel scrubber that scrubs faster intended for gas production instead of station usage

That would make some more sense, yes.

2023-10-12 18:48 UTC, Partmedia commented
You know, it's perfectly possible to make tritium using passive vents in the chamber and a big bank of filters. I don't know why people insist that scrubbers are absolutely necessary.

An alternative to plasteel scrubbers is to lean into machine upgrades to upgrade scrubbers.

2023-10-12 19:00 UTC, deltanedas commented
the best designs use 32x scrubbers and not filters + passive vents

2023-10-12 19:08 UTC, moonheart08 commented
2500.
Not 4000, 2500.

2023-10-12 19:26 UTC, Ilya246 commented
> You know, it's perfectly possible to make tritium using passive vents in the chamber and a big bank of filters. I don't know why people insist that scrubbers are absolutely necessary.
> 
> An alternative to plasteel scrubbers is to lean into machine upgrades to upgrade scrubbers.

using passive vents has terrible efficiency and i don't think it's better than even unstackable scrubbers right now

2023-10-13 01:08 UTC, BasedUser commented
> The number to use is 2500. Not 4000, 2500.

valid

2023-12-11 20:28 UTC, Partmedia commented
I'm closing this since everything is going to be buffed soon in https://github.com/space-wizards/space-station-14/pull/21954. Thanks for your initial contribution.

2023-12-11 20:28 UTC, closed without merging