Adds auto-population to the cookbook
space-wizards/space-station-14 pull request #20978
Opened 2023-10-14 00:28 UTC by nmajask

## About the PR

Adds auto-population for food items into the cookbook, as well as produce in the botany guidebook and medical items with microwave recipes in the chemistry guidebook. This is my first time doing something big in C# and working with the UI code, so the code quality is very low and if I could get feedback on it that would be amazing.

The food item embed contain an image of the food, the food's description, all of the recipes that result in it, and all of the recipes that require it. The only recipes that work are microwave recipes and reactions that spawn entities.

I'm not the best when it comes to knowing about food, so please give feedback on the categorization.

## Why / Balance

Currently, the only way to learn recipes is by looking it up in the wiki which is outdated or going through the code which can be annoying to do. This makes it easier for chefs to know what they can even cook, and also shows them what things can be used for.

## Technical details

So a lot of this has low code quality as I'm new to C# and xaml. One of the main issues is the fact that reaction effects which is what spawns items are held server side, so I had to graft another list to the system that handles chem effects. Information being stored server side is one of the main issues i have encountered. I would like to combine foods with their sliced versions, but the slice-able food comp is held server side. I want to add reagent grinding to the guidebook for chem, but the info for that is held server side. I want to add what the foods taste like to the description, but that is held server side. We would probably just need a generic system to get information for the guidebook to the client but that is beyond me at the moment.

As for the UI, I made some changes to avoid redundant code. Reagent recipes have been split of into a new reaction embed to allow for me to use them for food item recipes. Reactions also now show solid products and show units when the reaction is quantized to show that you need exact amounts. Microwave recipes are also a new embed type similar to the reaction embed, and they show the time needed for it to cook. For the food embed, it doesn't have to be given a food to embed, it can be given any entity. It automatically lists any reactions or microwave recipes that produce it, and any microwave recipes that require it. There is also a cookbook group embed that lists all the foods of a specific category similar to the reagent groups. To add an entity to the group, you need to give it a CookbookDocumentation comp and a catagory.

I've tried to avoid messing with the reagent embeds where possible to avoid bloat in the PR, though there are a couple things that kind of creep out of the scope of the PR like removing the extra unused bun prototype and making some of the formatting of some of the yml documents more consistent. I also haven't done the best job of splitting stuff into different commits because I was still learning.

## Media

![image](https://github.com/space-wizards/space-station-14/assets/14363906/55c92297-2db3-4bc8-ab2b-87a8cc93b4ab)
The embed

![image](https://github.com/space-wizards/space-station-14/assets/14363906/d7a8554d-acce-45f7-8081-3978a69f1c12)
This is what hell looks like
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The guidebook for cooking recipes now automatically updates and has a new format

2023-10-14 00:29 UTC, deltanedas commented
i dont think Or is needed since theyre separate recipes, not multiple recipes for the same thing

2023-10-14 00:32 UTC, nmajask commented
> i dont think Or is needed since theyre separate recipes, not multiple recipes for the same thing

Its mostly to visually separate the recipes, but it does do a bad job at that anyways. I would use the list thing that the crew monitor uses but I couldnt get that to work.

2023-10-18 18:36 UTC, nmajask commented
PR is ready for review, just need feedback on the implementation and where to categorize foods.

2023-10-22 20:21 UTC, daerSeebaer commented
Your current version is failing in the integration tests. I don't know exactly what they do, but the error was thrown in a file called "GuideEntryPrototypeTests.cs" so I guess that is an error related to this PR. Please look into this and maybe ask someone with more knowledge about the test pipeline what the Error means.

2023-10-22 20:22 UTC, daerSeebaer requested changes

2023-10-22 22:37 UTC, nmajask commented on .vscode/settings.json
> +    "git-blame.gitWebUrl": ""
Im using VSC to code and it constantly makes this change, forgot to not push it in one of the commits

2023-10-22 22:37 UTC, nmajask commented on Content.Client/Guidebook/Controls/GuideCookbookGroupEmbed.xaml
> +    <BoxContainer Name="CatagoryContainer" Orientation="Vertical"/>
I cant spell for shit, thanks for pointing that out. Should be fixed in the latest commit.

2024-01-29 04:03 UTC, metalgearsloth requested changes

2024-01-29 04:03 UTC, metalgearsloth commented on Content.Client/Guidebook/Controls/GuideMicrowaveRecipeEmbed.xaml.cs
> +}
Please document your code.

2024-01-29 04:03 UTC, metalgearsloth commented on Content.Client/Guidebook/Controls/GuideReactionEmbed.xaml.cs
> +    }
As above "u" is not a clear variable name and the code is unnecessarily hard to read.

2024-01-29 04:03 UTC, metalgearsloth commented on Content.Server/Chemistry/EntitySystems/ChemistryGuideDataSystem.cs
> +        var changeset = new ReagentGuideChangeset(new Dictionary<string, ReagentGuideEntry>(), new HashSet<string>(), new Dictionary<string, Dictionary<string, uint>>(), new HashSet<string>());
If these are just being initialized to default values there's no point having them in the ctor.

2024-01-29 04:03 UTC, metalgearsloth commented on Content.Server/Chemistry/EntitySystems/ChemistryGuideDataSystem.cs
> +                ReactionRegistry[proto.ID].Add(effect.Entity, effect.Number);
Use GetOrNew.

2024-01-29 04:03 UTC, metalgearsloth commented on Content.Server/Chemistry/EntitySystems/ChemistryGuideDataSystem.cs
> +        var sendEv = new ReagentGuideRegistryChangedEvent(new ReagentGuideChangeset(ReagentRegistry, new HashSet<string>(), ReactionRegistry, new HashSet<string>()));
As above.

2024-01-29 04:03 UTC, metalgearsloth commented on Content.Server/Chemistry/EntitySystems/ChemistryGuideDataSystem.cs
As above.

2024-01-29 04:03 UTC, metalgearsloth commented on Content.Shared/Kitchen/Components/CookbookDocumentationComponent.cs
> +}
Category needs to be a prototype so it gets properly validated, datafield strings are obsolete, and this needs networking + access attribute.

2024-02-29 22:54 UTC, metalgearsloth commented
Re-open if you come back to it.

2024-02-29 22:54 UTC, closed without merging