Added a penguin plushie!
space-wizards/space-station-14 pull request #21097
Opened 2023-10-19 00:48 UTC by CMDR-Piboy314

## About the PR

Added a new penguin plushie entity, and put it in the space villain arcade and the plushie crate.

## Why / Balance

It's cute!

## Technical details

No C# changes in this PR.

## Media

https://github.com/space-wizards/space-station-14/assets/92357316/f4c24d6c-8100-47e4-95ee-78e21f922b66

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None.

**Changelog**

:cl:
- add: Added a penguin plushie!

2023-10-19 01:00 UTC, CatMagic1 commented
powercreep

2023-10-19 01:01 UTC, UbaserB commented
oh my god it looks so dumb i love it

2023-10-19 01:50 UTC, potato1234x commented
linux penguin?

2023-10-19 01:50 UTC, asperger-sind commented
> linux penguin?

the description "i use arch btw!"implies that

2023-10-19 02:42 UTC, deltanedas commented
sorry void better

2023-10-19 05:22 UTC, JoeHammad1844 commented
traitor grenade penguin plushie :trollface:

2023-10-19 22:45 UTC, lzk228 commented
![plushie_linux-export](https://github.com/space-wizards/space-station-14/assets/124214523/96b226c5-15df-4e61-b646-94ea0e80c8ba)
![plushie_linux_02-export](https://github.com/space-wizards/space-station-14/assets/124214523/28ccd654-8f4a-4140-bc59-95621ff41258)
here, you can use one of those
(by netwy)

2023-10-19 23:08 UTC, CMDR-Piboy314 commented
Epic! I'll switch out the sprite and edit the :cl: in a bit!

2023-10-20 14:11 UTC, CMDR-Piboy314 commented
Sprite switched out, netwy added to :cl:, tested, checks... mostly successful- the error seems unrelated to my PR, as it's ``System.InvalidOperationException : Called Delete on an entity already being deleted. Entity: HandcuffsDummy (2948, HandcuffsDummy)``, no conflicts. Ready for merge!

2023-10-20 15:07 UTC, lzk228 requested changes

2023-10-20 15:07 UTC, lzk228 commented on Resources/Textures/Objects/Fun/toys.rsi/meta.json
you also should update copyright

2023-10-20 15:24 UTC, CMDR-Piboy314 commented on Resources/Textures/Objects/Fun/toys.rsi/meta.json
done

2023-10-22 11:45 UTC, CMDR-Piboy314 commented
Anything more I need to do to get this merged?

2023-10-22 12:57 UTC, lzk228 commented
> Anything more I need to do to get this merged?

patience. a lot of it

2023-11-04 05:07 UTC, mirrorcult approved these changes

2023-11-04 05:07 UTC, merged