User accessible playtime
space-wizards/space-station-14 pull request #21242
Opened 2023-10-25 17:06 UTC by Titian3

## About the PR
I have made a Stats window in the character selection menu so people can check how much play time they have in total and per role.

## Why / Balance
Because 10 people asked me to check their play time which is only available via admin command and that was enough for me to say this is bullshit and make it. 
It is also generating 5-10 aHelps a day mainly with people wanting to apply to Salamander.

## Technical details
All client side changes, reusing some existing methods that relate to the role selection and time quota to retrieve the time data. Pretty sure that is only loading up once on connection based on some testing with the new window so it shouldn't be making a bunch of db calls.

## Media
Accessed via the customization menu:
<img width="955" alt="image" src="https://github.com/space-wizards/space-station-14/assets/47093363/866a1058-cd35-4b14-92f2-b56b865ab28d">
Simple window with a table.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/0c27dfba-43c8-4366-9363-84593d521c5a)
Even sorts the table!
![image](https://github.com/space-wizards/space-station-14/assets/47093363/dca11f27-0e13-43d6-bd9c-b532a0abebce)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None, all new UI and functions.

**Changelog**

:cl: Repo
- add: Stats menu on Character setup for total and role playtime.

2023-10-25 17:48 UTC, lzk228 commented
i think in Role Type should be job-name string
and question: Hrs and Min in playtime can be localised?

2023-10-25 17:49 UTC, lzk228 commented
and why overall shows twice?

2023-10-25 17:55 UTC, QuietlyWhisper commented
@metalgearsloth is this kinda what you wanted out of #20517?

2023-10-25 18:08 UTC, Titian3 commented
> i think in Role Type should be job-name string and question: Hrs and Min in playtime can be localised?

I tried not to touch the serverside to keep it simple so its only bringing back those Job names, ill have a look if maybe i can map them back to the jobname string

The Hrs and Min is localized:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/3f3bd1c9-e394-4370-977a-92217c4c8b23)

2023-10-25 18:11 UTC, Titian3 commented
> and why overall shows twice?

The overview one and the one in the table?
Mainly ease of viewing for the overview up the top as that was the core issue i was trying to solve. I guess its not really necessary to have it in the table too.

2023-10-25 19:26 UTC, Titian3 commented
@lzk228 Updated it to be a bit cleaner now, its using the localized job names now too.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/1f06c8ad-387c-4049-9c60-d4f7bd48c3de)

2023-10-25 20:36 UTC, UbaserB commented
Great idea, love the stats button. Only issue is the UI page, it feels really clunky and unorganised. Firstly i feel the role type and role time should be seperated or highlighted some, along with the [XX]Hrs:[XX]Min to be “[XX] Hrs      [XX] Min” or something along those lines. The start of “[XX] Min” in that case would be consistent down the board of all jobs in the y-axis. Man i love UI design lol.

2023-10-26 04:51 UTC, Titian3 commented
> Great idea, love the stats button. Only issue is the UI page, it feels really clunky and unorganised. Firstly i feel the role type and role time should be seperated or highlighted some, along with the [XX]Hrs:[XX]Min to be “[XX] Hrs [XX] Min” or something along those lines. The start of “[XX] Min” in that case would be consistent down the board of all jobs in the y-axis. Man i love UI design lol.

Like this?
![image](https://github.com/space-wizards/space-station-14/assets/47093363/766cca2d-8969-45ef-9788-6b88f07a8bf9)
Yeah UI stuff has been struggle every time I make a small change even this one, its like 30min to test its working right and rendering correctly...

2023-10-26 04:52 UTC, metalgearsloth commented
Add some margins / thickness to it and it'll look a lot better.

2023-10-26 04:54 UTC, Titian3 commented
> Add some margins / thickness to it and it'll look a lot better.

I have a 10 all round margin on the main window, its a bit clearer on that last screen cap. 
Did you mean thicker for that, or margins on the table bit?

2023-10-26 04:55 UTC, metalgearsloth commented
Mainly between each label and its parent container, I'm mainly looking at the left edge here.

2023-10-26 04:56 UTC, ficcialfaint commented
Agree with the UI comments above. I'd separate the table's headers (*Role Type* (also why can't it just be *Role* and *Time*?) and *Role Time*). Also I'm pretty sure there is a method (assume in (Content)LocalizationManager) that localizes and generates a pretty time string as the way it is currently displayed is meh

2023-10-26 05:50 UTC, Titian3 commented
> Mainly between each label and its parent container, I'm mainly looking at the left edge here.

Ok more margins on the child labels in the table:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/d2672b5f-4bb9-4579-a419-1ee9b46bc390)

> Agree with the UI comments above. I'd separate the table's headers (_Role Type_ (also why can't it just be _Role_ and _Time_?) and _Role Time_). Also I'm pretty sure there is a method (assume in (Content)LocalizationManager) that localizes and generates a pretty time string because the way it is currently displayed is meh

I've Simplified the headers names, this is all localized so can be set to whatever makes sense on that side.
The sperate the table's headers you mentioned was the Horizontal separator between the header and the table rows I think, that's in there now. 
I specifically used just Hours and minutes because the output from the server/db it is some timespan that is just pain to read. days:hours:minutes:seconds DD:HH:MM:SS. 
No one wants to do some 24x calculation every time they want to know hours in a game. Generally speaking stats for games I've only ever seen in hours, Eg steam tracker is in hours not days and seconds.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/5a2741d2-df41-428d-9ec5-083a4dd4a3c0)
But if you know the particular time localization i'm happy to check it out to see if it does a better job, I put the RU style hrs and min in this screen cap as a ref with just changing the loc string.

2023-10-26 06:00 UTC, lzk228 commented
> Ok more margins on the child labels in the table: ![image](https://user-images.githubusercontent.com/47093363/278222888-d2672b5f-4bb9-4579-a419-1ee9b46bc390.png)

tgat one is great, and good readable

2023-10-26 17:06 UTC, notquitehadouken commented
delicious :trollface: 
no more having to annoy admins in ahelp for them to tell me my time hasn't changed since i last played

2023-10-26 21:38 UTC, UbaserB commented
Question, is this overall playtime or playtime for that specific character? If the former, i would be interested in being able to see how many hours or what i have played more with those characters :)

2023-10-26 21:39 UTC, LankLTE commented
I might be wrong but I don’t think per-character playtime is actually tracked at all

2023-10-28 05:44 UTC, metalgearsloth requested changes

2023-10-28 05:44 UTC, metalgearsloth commented on Content.Client/Info/PlaytimeStats/PlaytimeStatsWindow.cs
> +    }
Sorting by regex parsing is kinda dirty, would be better to just make a private control with the timespan data stored on it instead and use that.

2023-10-28 05:44 UTC, metalgearsloth commented on Content.Client/Info/PlaytimeStats/PlaytimeStatsWindow.cs
> +        {
Don't add the try-catch.

2023-10-28 05:44 UTC, metalgearsloth commented on Content.Client/Info/PlaytimeStats/PlaytimeStatsWindow.cs
> +            {
You could just make it IEnumerable and avoid allocating the entire dictionary instead.

2023-10-28 08:33 UTC, Titian3 commented
> Question, is this overall playtime or playtime for that specific character? If the former, i would be interested in being able to see how many hours or what i have played more with those characters :)

Total user playtime, all stats are user based.

2023-10-28 10:19 UTC, Titian3 commented
@metalgearsloth I maybe should have put all those change requests in separate commits but they are all done now. Thank you for taking some time to review 😊

2023-10-28 10:31 UTC, Titian3 commented
> I might be wrong but I don’t think per-character playtime is actually tracked at all

I'm going to explicitly mention it is for the user in the window title in the UI, players will probably have the same question for is it user vs character if we are asking it already.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/ab4c9bee-a474-4c7c-9e18-bb87a018acc3)

2023-10-28 12:01 UTC, metalgearsloth approved these changes

2023-10-28 12:01 UTC, merged