Storage Standardization [Take 2]
space-wizards/space-station-14 pull request #21270
Opened 2023-10-27 01:53 UTC by EmoGarbage404

## About the PR

Standardizes items to a 99% more sane system.

Sizes are now an enum (Tiny, Small, Normal, Large, Huge, Ginormous) which determine what kinds of containers an item can fit in. For example, large items can't fit in small containers. Sizes also have a numerical value which can be seen in the value (though this is pending to change in the future) which mimics the existing system.

This also comes with an additional lever, called "slots." **SLOTS ARE ONLY USED BY BELTS IN THE CURRENT DESIGN.** Slots simply specify a max number of items that can fit and ignores cumulative item sizes.

Naturally, a lot of values have been tweaked so balance might be fucky. This can all be changed rather trivially so don't sweat it too hard, capiche?

## Why / Balance

The purely numerical storage system had two main issues:

**Thresholds**
A lot of the values were built around numerical size thresholds that corresponded to in-game containers. These include:
- size 12: pockets
- size 100: backpacks
- size 120: duffels
- size 9999 (yes this was in the game fml): BoH

By using these standardized enum values instead of numbers, these items can more directly reflect the actual thresholds they're balanced around while simplifying the amount of numbers being juggled around.

**Cumulative Sizes**
10 size 1 items vs. 1 size 10 item. It's just not the same. Containers were not able to handle storing many smaller items without additionally storing larger ones than intended, barring you go through the pain of adding whitelists to it. The simple fact is that this makes balancing small containers like pill bottles very garbage.

Max item sizes can block this unwanted behavior, for example, by restricting Large items from being placed in toolbelts or Small items from being placed in matchboxes. This will allow coders more ways to make multipurpose and dynamic storage options (epical!)

## Technical details

**ItemComponent**
Size - Enum representing a different rough estimate of size.

**StorageComponent**
MaxTotalWeight - replacement for capacity, integer. Required for all storage unless they use slots.
MaxSlots - optional: alternative system that dictates a max number of items that can be placed
MaxItemSize - optional: the max size item that can be inserted into this storage. If null, it will be generated using an appropriate default value.

## Media

![image](https://github.com/space-wizards/space-station-14/assets/98561806/110d84b4-aca3-48f9-8886-573d81089ec1)
![image](https://github.com/space-wizards/space-station-14/assets/98561806/9449f586-21e2-49e3-9966-8f8e6712d276)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Same shit as #21212

**Changelog**

:cl:
- add: Storage containers can now block large items from being inserted into them, regardless of the space available.
- add: Belts now function on a slot based storage system rather than a volume based one.
- tweak: Standardized item sizes into regular categories.

2023-10-27 02:07 UTC, mirrorcult commented
much more based

2023-10-27 02:08 UTC, EmoGarbage404 commented
> much more based

one may say i encountered a brief lapse in based-ed-ness

2023-10-27 02:30 UTC, LankLTE commented
I think this is better, but I'm still not a huge fan of allowing nested containers to give you more storage. If I'm going over this correctly, boxes weigh 4 and can hold 12, so you're still encouraging people to fill their backpacks with boxes to hold more stuff. Making "normal" items weigh 6 / hold 6 would essentially fix this while also being closer to the current storage system (one normal item of 30 weighing 6x a tiny item of 5), instead of making normal items significantly easier to carry in large amounts while also encouraging nested storage again (maybe even further, since you have more slots to put other stuff in excluding your nested storage).

2023-10-27 02:55 UTC, QuietlyWhisper commented
> I think this is better, but I'm still not a huge fan of allowing nested containers to give you more storage. If I'm going over this correctly, boxes weigh 4 and can hold 12, so you're still encouraging people to fill their backpacks with boxes to hold more stuff. Making "normal" items weigh 6 / hold 6 would essentially fix this while also being closer to the current storage system (one normal item of 30 weighing 6x a tiny item of 5), instead of making normal items significantly easier to carry in large amounts while also encouraging nested storage again (maybe even further, since you have more slots to put other stuff in excluding your nested storage).

I think the intention is to give sub-storage entities value and use, by allowing them to carry more items. However this is better done with whitelisted items like pill canisters, which can be sized to be tiny/small but hold a lot of specific contents, rather than the bullshittery we saw with boxes in the discord forum...

It only gets stupid when you can fit multiple storage expansions into your bag that have no content restrictions it seems-

2023-10-27 02:56 UTC, UbaserB commented
> I think this is better, but I'm still not a huge fan of allowing nested containers to give you more storage. If I'm going over this correctly, boxes weigh 4 and can hold 12, so you're still encouraging people to fill their backpacks with boxes to hold more stuff. Making "normal" items weigh 6 / hold 6 would essentially fix this while also being closer to the current storage system (one normal item of 30 weighing 6x a tiny item of 5), instead of making normal items significantly easier to carry in large amounts while also encouraging nested storage again (maybe even further, since you have more slots to put other stuff in excluding your nested storage).

i dont think encouraging boxes is a particularly bad thing. I mean for one, why would carrying 8837438 pills NOT in canisters make sense?

2023-10-27 03:30 UTC, JoeHammad1844 commented
I like this change, less hidden values are also nice, but what does a backpack with a medkit inside look like?

2023-10-27 06:44 UTC, JoeHammad1844 commented
> I think this is better, but I'm still not a huge fan of allowing nested containers to give you more storage. If I'm going over this correctly, boxes weigh 4 and can hold 12

the tradeoff is that you cant store normal sized items

2023-10-27 08:24 UTC, BasedUser commented
Not particularly a fan, since this also breaks all forks' prototypes. However, many of the considerations from the storage discussion thread have been taken in.

2023-10-27 10:04 UTC, BasedUser commented
From my limited playtesting (and intent to bring ss13 balance when the dust settles), I'd love to see an "arbitrage whitelist" be added, allowing you to put otherwise large (but not volume-exhausting) items in select containers (i.e. mops IN backpacks, if that were to be an intended feature).

Otherwise, LGTM.

> 7 stun batons in a belt is a valid state with this system.

You can hold 4 on /tg/, and that's with the security belt nerf.

2023-10-27 12:02 UTC, CatMagic1 commented
much better 👍

but also c4 matchboxes????
no more c4 matchboxes :(

2023-10-27 12:50 UTC, JoeHammad1844 commented
what do stacks look like?

2023-10-28 04:42 UTC, JoeHammad1844 commented
what just got merged that made this conflict

2023-10-31 03:14 UTC, mirrorcult requested changes

2023-10-31 03:14 UTC, mirrorcult commented on Content.Shared/Item/SharedItemSystem.cs
> +    public const int ItemSizeWeightGinormous = 48;
should this not just be the values of the enum

2023-10-31 03:49 UTC, mirrorcult approved these changes

2023-10-31 03:55 UTC, merged