Pipe dispenser
space-wizards/space-station-14 pull request #2153
Opened 2020-09-29 20:36 UTC by juliangiebel

Problems for future PRs:
Atmos pipes and need icons and an anchorable + pullable component

2020-10-16 20:37 UTC, exp111 requested changes
Crash while dispensing a pipe
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Nachricht = Specified argument was out of the range of valid values. (Parameter 'pipeDirection')
  Quelle = Content.Shared
  Stapelüberwachung:
   at Content.Shared.GameObjects.Components.Atmos.PipeDirectionHelpers.PipeDirectionToPipeShape(PipeDirection pipeDirection) in D:\Visual Studio\Github\ss14\review-space-station-14\Content.Shared\GameObjects\Components\Atmos\SharedPipeComponent.cs:line 144
   at Content.Client.GameObjects.Components.Atmos.PipeVisualizer.GetPipeBaseStateId(PipeVisualState pipeVisualState) in D:\Visual Studio\Github\ss14\review-space-station-14\Content.Client\GameObjects\Components\Atmos\PipeVisualizer.cs:line 35
   at Content.Client.GameObjects.Components.Atmos.PipeVisualizer.OnChangeData(AppearanceComponent component) in D:\Visual Studio\Github\ss14\review-space-station-14\Content.Client\GameObjects\Components\Atmos\PipeVisualizer.cs:line 28
   at Robust.Client.GameObjects.EntitySystems.AppearanceSystem.UpdateComponent(AppearanceComponent component) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\AppearanceSystem.cs:line 30
   at Robust.Client.GameObjects.EntitySystems.AppearanceSystem.FrameUpdate(Single frameTime) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\AppearanceSystem.cs:line 14
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 259
   at Robust.Shared.GameObjects.EntityManager.FrameUpdate(Single frameTime) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 111
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 290
   at Robust.Client.GameController.<MainLoop>b__65_3(Object sender, FrameEventArgs args) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 108
   at Robust.Shared.Timing.GameLoop.Run() in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 242
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 113
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 59
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35
   at Robust.Client.ContentStart.Start(String[] args) in D:\Visual Studio\Github\ss14\review-space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in D:\Visual Studio\Github\ss14\review-space-station-14\Content.Client\Program.cs:line 9

```
pipeDirection was South

2020-10-16 20:37 UTC, exp111 commented on Content.Client/GameObjects/Components/PipeDispenser/PipeDispenserMenu.cs
> +                    if (prototype.Name.ToLowerInvariant().Contains(_searchBar.Text.Trim().ToLowerInvariant()))
Just save the _searchBar.Text.Trim() into a var?

2020-10-16 20:37 UTC, exp111 commented on Content.Client/GameObjects/Components/PipeDispenser/PipeDispenserMenu.cs
> +                _shownItems.Add(prototype);
I'd just use a `else` here instead of using continue

2020-10-16 20:37 UTC, exp111 commented on Content.Client/GameObjects/Components/PipeDispenser/PipeDispenserMenu.cs
> +                    if (prototype.Name.ToLowerInvariant().Contains(_searchBar.Text.Trim().ToLowerInvariant()))
You can call Contains with a param to ignore case

2020-10-16 20:37 UTC, exp111 commented on Content.Client/GameObjects/Components/PipeDispenser/PipeDispenserVisualizer.cs
> +                    ActivateState(sprite,  "screen");
```suggestion
                    ActivateState(sprite, "screen");
```

2020-10-16 20:37 UTC, exp111 commented on Content.Client/GameObjects/Components/PipeDispenser/PipeDispenserVisualizer.cs
> +                    ActivateState(sprite,  "screen");
```suggestion
                    ActivateState(sprite, "screen");
```

2020-10-16 20:37 UTC, exp111 commented on Resources/Prototypes/Entities/Constructible/Power/pipe_dispenser.yml
> +  name: "pipe dispenser"
i don't think you need the quotes

2020-10-16 20:37 UTC, exp111 commented on Content.Server/GameObjects/Components/PipeDispenserComponent.cs
> +        public void OnBreak(BreakageEventArgs eventArgs)
I think you should disable all buttons on the client/close the menu if the dispenser breaks/has no power

2020-10-16 20:37 UTC, exp111 commented on Content.Client/GameObjects/Components/PipeDispenser/PipeDispenserVisualizer.cs
> +            ActivateState(sprite, "off");
You should probably load those states from the yaml

2020-10-16 20:37 UTC, exp111 commented on Content.Client/GameObjects/Components/PipeDispenser/PipeDispenserVisualizer.cs
> +            _baseStates = new Dictionary<string, bool>
I also don't like this whole saving if the states exist. Just do a LayerMap.TryGetValue if they are asked

2020-10-16 20:37 UTC, exp111 commented on Content.Client/GameObjects/Components/PipeDispenser/PipeDispenserVisualizer.cs
> +        private Dictionary<string, Animation> _animations = new Dictionary<string, Animation>();
readonly

2020-11-04 22:19 UTC, juliangiebel commented on Content.Client/GameObjects/Components/PipeDispenser/PipeDispenserBoundUserInterface.cs
> +            if(!disposing) { return; }
Resolved in upcoming commit

2020-12-22 06:44 UTC, SweptWasTaken commented
Too stale. Lemme know if you're continuing work.

2020-12-22 06:44 UTC, closed without merging