Makes syndicate stealth effective even against players wearing sechud or any hud
space-wizards/space-station-14 pull request #21621
Opened 2023-11-12 21:21 UTC by rbertoche

## About the PR

This makes stealth effective against all huds.

## Why / Balance

It was annoying ninjas could easily be seen by people wearing sec huds or beer goggles.

## Technical details

It creates a new bool member HasStealthComponent in GetStatusIconsEvent which is used to
pass that state, exactly how InContainer was being done, instead of spreading HasComponent tests all round.

It also hides AFK marker when on stealth, making it harder for players to find it before an admin gets to make a ghost role for it or something in case the ninja player suddenly disconnects

## Media

![image](https://github.com/space-wizards/space-station-14/assets/472878/708df0e8-1386-47a0-92a1-ea64168318cb)

## Breaking changes

**Changelog**

:cl: rber
- tweak: Syndicate stealth tech now has electronic countermeasures and is effective against NT augmented reality devices

2023-11-12 21:27 UTC, UbaserB commented
Shouldn’t it also hide beer glasses/onion goggle UI? A new meta could occur of security wearing beer glasses to spot ninjas lol.

2023-11-12 21:30 UTC, rbertoche commented
It hides against those too!

2023-11-12 21:30 UTC, rbertoche commented
Beer google screenshot was a "before" screenshot, but it should effect all huds currently in the game

2023-11-12 23:09 UTC, GoodWheatley commented
Isn’t there a PR already up for this? @deltanedas

2023-11-13 04:09 UTC, deltanedas commented
unless something broke it or it didnt get merged this shouldnt be a problem?

2023-11-13 04:21 UTC, deltanedas commented
#21009 pro wasnt merged

2023-11-13 06:22 UTC, rbertoche commented
Isn't it a bit of an overkill to add a whole new event just to fix this? This patch is way smaller plus by not creating and raising a whole new event inside a while loop it's probably measurably faster

2023-11-13 07:13 UTC, deltanedas commented
benchmark it :trollface:

also InContainer HasStealthComponent this is why you use an event so it scales much better you dont need to update every overlay every time you have some kind of invisibility

2023-11-13 09:01 UTC, rbertoche commented
Don't be greedy deltanedas! :P
Draw iterates over whatever AllEntityQueryEnumerator encompasses regardless of it having changed or not, having two calls of methods that do pretty much the same thing one right after the other (in your case GetStatusIcons and IsVisible) can't possibly be faster than having just one of the calls but allocating one bool more for the event on that call
Besides if for any reason people decide there's a certain overlay which should show anyway, then it's not hardcoded that every status icon thing gets hidden along with stealth (such as HR/Rev)

2023-11-13 09:03 UTC, deltanedas commented
only scenario in which overlays should still show is maybe if you thermal goggles or something, t3 xray sechud would be unbalanced

2023-11-13 09:04 UTC, rbertoche commented
except for head revs and revs, but I did not test if yours would hide that

2023-11-13 09:04 UTC, rbertoche commented
it's also kinda a rare case anyway

2023-11-13 09:04 UTC, deltanedas commented
revs should still not be able to see if a rev is invisible or in a crate it doesnt make any sense

2023-11-13 09:05 UTC, rbertoche commented
I did not change anything with InContainer, only stealth, this only affects entities with stealth

2023-11-13 09:09 UTC, deltanedas commented
still wouldnt make sense for revs to be able to recognize invisible revs

2023-11-14 20:51 UTC, rbertoche commented
If that is the case, it's very easy to make it so by changing [this line](https://github.com/space-wizards/space-station-14/blob/f8ab1614564765a6ee5a515b8a075b200685a5d1/Content.Client/Overlays/ShowSyndicateIconsSystem.cs#L21) exactly how the other IconsSystems where changed, it's very easy to change this in any of them in one way or another

2023-11-22 21:35 UTC, rbertoche commented
any news on this one?

2024-01-09 03:28 UTC, AJCM-git requested changes
I think a better implementation would be to make each use-case of the visibility a datafield in the `StatusIconData` and then do the checks in the necessary `GetStatusIconEvent` subscription, this would make it so each status icon can opt in or out in certain visibility option as needed. For example, if you want to make the SSD indicator show inside containers but not on stealth (example, dont do this), then you would add two datafields bool to StatusIconData (`showInsideContainers` and `showOnStealth` or something like that) and then do the necessary checks in `SSDIndicatorSystem.OnGetStatusIcon` (kinda working off memory about how status icons work so there may be something wrong here but i think i articulated the idea well enough)
Of course, you would need to also move the `GetIconStatusEvent.InContainer` field to the prototype.
Gonna leave this same review in  #21009, so y'all can decide who will implement this.

2024-01-12 20:25 UTC, rbertoche commented
Cool, thanks for requesting changes regardless of it being an old PR. I hope to get time to fix it but can't be sure.

2024-04-04 23:05 UTC, VasilisThePikachu commented
Is this still being worked on?

2024-05-19 18:10 UTC, GroggleG commented
Good god I want to see some activity on this, Id do it if I had the time/skill to.

2024-05-25 05:17 UTC, AJCM-git commented
Superceded by  #28270

2024-05-25 05:17 UTC, closed without merging