Fix robusted dionas not being recoverable
space-wizards/space-station-14 pull request #21636
Opened 2023-11-13 16:04 UTC by luringens

## About the PR
Diona that have robusted themselves into a tree now drop their items before polymorphing, and can be recovered by chopping down the tree.

## Why / Balance
The polymorph definition for this set `revertOnDeath: true`, but trees do not have a `mobState` that can die so that never worked. Further, this sends all items carried by the diona (including the nuke disk if they are holding it) into the ether leaving them unrecoverable.

## Technical details
- `PolymorphSystem` subscribes to `DamageThresholdReached` to detect imminent destruction and revert the polymorph on destruction if `revertOnDeath` is true. I figured this makes sense since destruction and death are about analogous here. There is a comment on `DamageThresholdReached` that says it's not being used anywhere else, but this is as good a first use as any I suppose.
- To avoid diona immediately turning into a tree again, allowing them to be chopped repeatedly for infinite wood, this adds a configurable cooldown to polymorphs that defaults to zero. For TreeMorph this is set to 160 seconds, enough for 80u of robust harvest to be processed out of their bodies.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![image](https://github.com/space-wizards/space-station-14/assets/8277780/aeef384b-8620-4329-93db-8b7b3656df8b)

## Breaking changes
N/A

**Changelog**

:cl:
- tweak: Diona now drop their items when robusted into a tree.
- fix: Diona can be cut free from their robust tree-form.

2023-11-13 16:14 UTC, LordEclipse commented
> There is one issue with this fix. Because polymorphing basically sends the chem system into stasis, the remaining solution is not processed or consumed. This means if there was 10u more robust harvest in system than required to polymorph, being cut free makes the diona process .5u of it and then polymorph again. This means it's trivial to get infinite wood from this, and is just a pain in general for the affected diona. Ideally, polymorphing would consume the 80u of robust harvest that it took to hit that limit, but I'm not sure if there's any simple way to do that with the current system without adding an ugly special-case in the revert-code. One way to resolve this is to just give up on reverting the Diona and just let them die as before, as dropping the inventory already resolves the most abusable part of current behaviour. Any suggestions on how best to resolve this is welcome.

They could receive a cooldown/immunity to being turned into a tree after being cut free instead.

2023-12-17 03:51 UTC, mirrorcult requested changes

2023-12-17 03:51 UTC, mirrorcult commented on Content.Server/Polymorph/Systems/PolymorphSystem.cs
> +        private void OnDamageThresholdReached(EntityUid uid, PolymorphedEntityComponent comp, DamageThresholdReached args)
wont this trigger on every threshold change even if it doesnt destroy the entity? this should subscribe to `DestructionEventArgs` instead

2023-12-17 03:51 UTC, mirrorcult commented on Content.Server/Polymorph/Components/PolymorphableComponent.cs
> +        [ViewVariables(VVAccess.ReadOnly)]
```suggestion
        /// <summary>
        /// Timestamp for when the most recent polymorph ended.
        /// </summary>
        [ViewVariables(VVAccess.ReadOnly)]
```

2023-12-17 03:51 UTC, mirrorcult commented on Content.Shared/Polymorph/PolymorphPrototype.cs
> +        public TimeSpan Cooldown = TimeSpan.Zero;
```suggestion
        /// <summary>
        /// The amount of time that should pass after this polymorph has ended, before a new one
        /// can occur.
        /// </summary>
        [DataField("cooldown", serverOnly: true)]
        [ViewVariables(VVAccess.ReadWrite)]
        public TimeSpan Cooldown = TimeSpan.Zero;
```

2024-01-04 13:10 UTC, merged