Change opossum sprites | Add new pet poppy the safty opossum
space-wizards/space-station-14 pull request #21672
Opened 2023-11-15 19:16 UTC by VasilisThePikachu

## About the PR

Changes the opossum sprites to ones from baystation (it was the only ones i could fine and i cant sprite)

Also adds poppy, a safety opossum! Would go great as an engineering pet. (they dont have a pet right? only atmos does)

Since I know a bunch of people love Morty and his iconic sprite. I kept him in as an admin spawn

## Why / Balance

Old sprites were only 2 directional and were not really in match of the art style. Neither are these really in the right art style but its better then what we have right now

## Technical details

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Poppy
![image](https://github.com/space-wizards/space-station-14/assets/34938708/228110f9-2734-4810-a221-ef8bdecb6693)
![image](https://github.com/space-wizards/space-station-14/assets/34938708/cee684bb-7808-4e95-a621-0f6458bcdb54)

Morty/Possums
![image](https://github.com/space-wizards/space-station-14/assets/34938708/99369585-9f6e-47a1-945e-ac7daa223955)
![image](https://github.com/space-wizards/space-station-14/assets/34938708/1116ba95-924e-4450-a782-97802e8feb9e)

## Breaking changes

**Changelog**

:cl: Vasilis
- add: Added Poppy the Safty Opposum!
- tweak: Opossums have received some new sprites. Old sprites are still available to be spawned in.

2023-11-15 20:28 UTC, CatMagic1 commented
buh morty be mortying why he no mortying no more

2023-11-15 22:17 UTC, UbaserB commented
nooo morty no longer morty :(

2023-11-16 21:22 UTC, Emisse commented
morty killed

2023-11-29 17:04 UTC, DrSmugleaf requested changes

2023-11-29 17:04 UTC, DrSmugleaf commented on Resources/Textures/Mobs/Animals/possum.rsi/meta.json
> +  "copyright": "New sprites taken from Baystation12 at https://github.com/Baystation12/Baystation12/blob/c7442716b52ce4edeef5eaf5d2fc7c57a08a3f01/icons/mob/simple_animal/possum.dmi, old sprites taken
This should be a separate .rsi instead of mixing licenses in the copyright field like this

2023-12-16 14:34 UTC, merged

2023-12-16 14:35 UTC, UbaserB commented
NOOOOOOOOOO morty

2023-12-16 14:36 UTC, Blackern5000 commented
MORTY NOOOOOOOOOOOOOOOOOOOO

2023-12-16 14:41 UTC, VasilisThePikachu commented
Oh no ..... I can already see the assassin's coming to my house

2023-12-16 15:23 UTC, MACMAN2003 commented
it's mortyover