Refactor NPCRetaliationSystem::Update to fix crash caused by Debug Assertion
space-wizards/space-station-14 pull request #21785
Opened 2023-11-19 13:02 UTC by Chronophylos

## About the PR
I refactored the `Update` function in the `NPCRetaliationSystem` to prevent a crash caused by Debug Assertion.
fixes #21702 

## Technical details

I eliminate the queue by combining the two foreach loops and remove the check for entity termination, as it only results in deaggroing the entity twice without altering anything else.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Resolved a crash issue occurring in debug builds when a retaliating NPC dies.

2023-11-19 13:20 UTC, lzk228 commented
they'll kill you for webedit

2023-11-19 13:23 UTC, Chronophylos commented
what do you mean?

2023-11-19 20:32 UTC, Partmedia commented
> what do you mean?

Web edits (edits made through the Github web editor) are [not allowed by policy](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#testing).

You signed your commits using your GPG key, which shows up on Github as "Verified", which people assume come from web editing. So you are free to ignore them :)

2023-11-19 20:38 UTC, EmoGarbage404 requested changes

2023-11-19 20:38 UTC, EmoGarbage404 commented on Content.Server/NPC/Systems/NPCRetaliationSystem.cs
> -                    _deAggroQueue.Add(ent);
You need to still remove terminating / deleted entities or else they'll throw errors when we try and access data on them. Just remove passing in the MetaData component and keep everything else the same.

2023-11-20 13:44 UTC, Chronophylos commented
@Partmedia Thank you for elaborating :). Verifying my commits has been a habit for years.

2023-12-02 16:59 UTC, EmoGarbage404 approved these changes

2023-12-02 17:00 UTC, EmoGarbage404 commented
I opted to remove the changelog in accordance with the significance guidelines.

2023-12-02 17:00 UTC, merged