Cat cake. A small update.
space-wizards/space-station-14 pull request #21805
Opened 2023-11-20 12:05 UTC by Nyranu

## About the PR
This small PR will allow you to put a cakecat on your head, as well as add sprites holding it in your hand and on your head. I think it will add more cute mini elements, and will also be a great reward for cooking it.

## Why / Balance
I have sometimes seen questions of this type in looc: “Why can't you put it on your head like a moth” 

## Media
![Screenshot_225](https://github.com/space-wizards/space-station-14/assets/139381125/d39e71d2-19aa-45ef-ae29-6a7f09c92b1c)
![Screenshot_224](https://github.com/space-wizards/space-station-14/assets/139381125/547fd101-9a35-429a-9263-d5c74c293ae9)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: The ability to put a cakecat on your head.
- add: Sprites holding it in  hands, on  head.

2023-11-20 12:57 UTC, lzk228 requested changes
since cak moved to new .rsi, remove states from old folder

2023-11-20 12:57 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +    equippedPrefix: 0
for what prefix if it's only one cak in folder

2023-11-20 12:57 UTC, lzk228 commented on Resources/Textures/Mobs/Pets/cakecat.rsi/meta.json
> +  "copyright": "Update by Nyranu. The original PR from TheShuEd",
you should put here copyright from `Resources/Textures/Mobs/Pets/cat.rsi/meta.json` and new copyright for inhand and equipped states

2023-11-20 12:58 UTC, lzk228 commented
read [pr guidelines](https://docs.spacestation14.io/en/getting-started/pr-guideline) and fix your cl

2023-11-20 14:29 UTC, lzk228 requested changes

2023-11-20 14:29 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +    inhandVisuals:
can be changed to `heldPrefix: cak`

2023-11-20 23:29 UTC, lzk228 approved these changes
not sure about copyright but seems good to me

2023-11-22 03:51 UTC, LankLTE commented
> maybe make the cl more in-universe? maybe:
> 
> "Extended monitoring of feline pastroid specimens has led to the caks becoming more comfortable with researchers, allowing for crew to hold them and wear them on their heads."

Do not do this. The changelog should probably be removed outright as it's fairly minor (per the [pull request guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#writing-an-effective-changelog))

2023-11-22 04:33 UTC, Emisse commented
cl is fine rn

2023-11-23 00:41 UTC, merged