localize damage type in armor examine description
space-wizards/space-station-14 pull request #21807
Opened 2023-11-20 16:05 UTC by Chronophylos

## About the PR
I added localization for damage types in the armor examine description.

## Why / Balance
fix #21652 

## Technical details
The damage type is localized separately and then inserted as parameter in the final string.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- fix: Included missing damage type localization for armor examination.

2023-11-22 19:25 UTC, ficcialfaint commented on Resources/Locale/en-US/armor/armor-examine.ftl
> +armor-damage-type-slash = Slashing
perhaps just leave it "Slash"?

2023-12-02 16:49 UTC, EmoGarbage404 requested changes

2023-12-02 16:49 UTC, EmoGarbage404 commented on Resources/Locale/en-US/armor/armor-examine.ftl
> +armor-damage-type-caustic = Caustic
you're missing strings for bloodloss, asphyxiation, cellular, cold, poison, shock, and structural.

2023-12-04 12:39 UTC, lzk228 commented
since it concerns only to localisation possibilities, i dont think cl should be included

2023-12-04 12:57 UTC, merged