Two variations of human scars
space-wizards/space-station-14 pull request #21895
Opened 2023-11-25 11:07 UTC by UbaserB

## About the PR

Weren't enough markings for humans and since there are tattoos; why not scars? However with the limited pixel range it was difficult to figure out anything so i just made two types; one left and one right (they look exactly the same). Right now they can be colored any color but ideally something that doesn't look horrendous lol anything further is out of the scope of this PR right now.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![image](https://github.com/space-wizards/space-station-14/assets/134914314/429f9a55-3738-4fb1-9d3d-7a9d9914af74)

## Breaking changes

**Changelog**

:cl: Ubaser
- add: Added two eye scars markings for humans and dwarves.

2023-11-27 05:32 UTC, EmoGarbage404 commented
i feel like you can just make the sprite a transparent black color and then make the marking skin-colored. That would basically just look like a scar without allowing it to be RGB hell.

2023-11-27 05:44 UTC, UbaserB commented
> i feel like you can just make the sprite a transparent black color and then make the marking skin-colored. That would basically just look like a scar without allowing it to be RGB hell.

makes sense, i did try to do something similar but failed; ill try again.

2023-11-27 05:45 UTC, NeviNovat commented
BUT I LIKE RGB HELL!

Honestly scars can look different depending on the damage and type of damage it was done to make them, some scar can remain deep red while some go pink and others white. Black may be used to indicate deep scars that leave a noticeable shadow.

2023-11-27 05:46 UTC, EmoGarbage404 commented
> Honestly scars can look different depending on the damage and type of damage it was done to make them, some scar can remain deep red while some go pink and others white. Black may be used to indicate deep scars that leave a noticeable shadow.

then write a skin tone validator. letting people make their scars bright neon pink is dumb and looks awful.

2023-11-27 06:04 UTC, NeviNovat commented
> > Honestly scars can look different depending on the damage and type of damage it was done to make them, some scar can remain deep red while some go pink and others white. Black may be used to indicate deep scars that leave a noticeable shadow.
> 
> then write a skin tone validator. letting people make their scars bright neon pink is dumb and looks awful.

Fair point. That might be the best solution to! I wish I could code it, don't know where to start. One problem is  that while I know to code somewhat, there is so much code to go over just to understand one basic thing.

I like the RGB option still since I like more player freedoms. But I have no problems with restrictions, especially if proven that a freedom is "abused" continuously.

2023-11-28 05:38 UTC, UbaserB commented
> i feel like you can just make the sprite a transparent black color and then make the marking skin-colored. That would basically just look like a scar without allowing it to be RGB hell.

i tried my best, the fallback is on pure white but it doesnt work. If i change the type or remove it, then the marking doesnt work at all. Not sure this is solvable without coding, sorry!

2023-12-11 03:11 UTC, mirrorcult requested changes

2023-12-11 03:11 UTC, mirrorcult commented on Resources/Locale/en-US/markings/scars.ftl
> +marking-ScarEyeLeft-eyescarleft = Back Tattoo (Left)
whys it say back tattoo

2023-12-11 07:31 UTC, UbaserB commented on Resources/Locale/en-US/markings/scars.ftl
> +marking-ScarEyeLeft-eyescarleft = Back Tattoo (Left)
lol let me fix that

2023-12-11 09:18 UTC, merged