Added Rim station take 2
space-wizards/space-station-14 pull request #21926
Opened 2023-11-27 20:21 UTC by Starbuckss14

## About the PR

Added Rim station a small ish map for 60 players. My map has lots of nice hiding spots and areas for roleplay.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- add: Added Rim station
- fix: Fixed the issue from the last PR
![Screenshot (13)](https://github.com/space-wizards/space-station-14/assets/145926356/4a0875c8-6915-432d-8b0c-74e294fd922c)
![Screenshot (14)](https://github.com/space-wizards/space-station-14/assets/145926356/0f1b7b5e-0bf9-4d3f-a39a-c00e3983133e)
![Screenshot (15)](https://github.com/space-wizards/space-station-14/assets/145926356/7be5a134-302e-452d-99d7-3f90496869e2)
![Screenshot (16)](https://github.com/space-wizards/space-station-14/assets/145926356/d7391f7a-982f-4918-95b6-f8c09365e1c7)
![Screenshot (17)](https://github.com/space-wizards/space-station-14/assets/145926356/5cea3acd-0c49-43a4-b4c8-aa1681805fad)
![Screenshot (18)](https://github.com/space-wizards/space-station-14/assets/145926356/ecd196a6-189d-427d-8e02-c8aca3cc93df)
![Screenshot (19)](https://github.com/space-wizards/space-station-14/assets/145926356/f736a052-e5d4-44c3-9e75-f1f6e35f074c)

2023-11-27 20:47 UTC, lzk228 commented
remove fix part from cl

2023-11-27 20:49 UTC, lzk228 requested changes
you have some commits that don't supposed to be here

2023-11-27 21:31 UTC, lzk228 commented
i think you really should read some docs about using github, and then do prs

2023-11-27 22:29 UTC, Starbuckss14 commented
> remove fix part from cl

Fixed

2023-11-27 22:30 UTC, Starbuckss14 commented
> you have some commits that don't supposed to be here

Ya I fixed that reverting the edits I made by mistake from before. The files being added are the map and prototype

2023-11-27 22:32 UTC, Starbuckss14 commented
> i think you really should read some docs about using github, and then do prs

The map and prototype file are included, I don't see the issue. I am not a computer science major

2023-11-28 04:39 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Fun/skub.yml
> -    delay: 2.0
pro

2023-11-28 10:49 UTC, lzk228 requested changes
got it?

2023-11-28 10:49 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Fun/skub.yml
> +    delay: 2
that shouldn't be in this pr

2023-11-28 10:49 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +    delay: 1
+

2023-11-28 10:49 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Specific/Janitorial/soap.yml
> +    paralyzeTime: 3.5
+

2023-11-28 10:49 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
> +  description: A very loud & dangerous sword with a beam made of pure, concentrated plasma. Make those without the highground suffer. Cuts through unarmored targets like butter.
+

2023-11-28 10:49 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
>      wideAnimationRotation: -135
+

2023-11-28 17:43 UTC, Starbuckss14 commented on Resources/Prototypes/Entities/Objects/Fun/skub.yml
> -    delay: 2.0
> pro

Based proskub moment

2023-11-28 17:46 UTC, Starbuckss14 commented
> Your random changes, found [here](https://github.com/space-wizards/space-station-14/pull/21926/commits/966e76e27e323984ad2da69a3b873ffe80c15546), should be atomized (Moved) to a separate PR if you wish for them to be added, though it seems like these changes are "change for change sake", but that is an entirely seperate discussion. To my understanding you seem to be using github desktop, you can revert commits to your branch, if need be, relatively easily by:
> 
> 1. Navigating to your history tab for your respective branch, in this case `Starbuckss14:master`.
> 2. Finding the respective commit(s) that have caused this issue.
> 3. Right clicking and pressing `Revert Changes In Commit`
> 4. You will then have to push your revert(s) to origin (your primary branch you are working on.)
>    ![T4CKxOVrI6](https://private-user-images.githubusercontent.com/91865152/286126846-8af15467-6acd-4b28-b6e3-b3140a9fe63b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTM2MDIsIm5iZiI6MTcwMTE5MzMwMiwicGF0aCI6Ii85MTg2NTE1Mi8yODYxMjY4NDYtOGFmMTU0NjctNmFjZC00YjI4LWI2ZTMtYjMxNDBhOWZlNjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE3NDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NGUzOTJkOGY2ZjY0NzlmNjkxZWVjMDgzZTA2MWJiM2NmYzI3NGQ4MWM3ODUyZjZhOGFiNjI3M2Q4YTUwMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a31yZy0jvwHihmvAUnIC5PykxQ25javVoOqyvxILYL8)
> 
> In the future, I suggest creating a new branch on github desktop for any projects you may be undertaking. Currently you are pushing any and all changes to your personal repository to this PR. Create a branch with you relevant map files, and then PR that.

Ok Thank you so much for your help! This fixed the issue! Very based as one might say!

2023-11-28 17:49 UTC, Starbuckss14 commented
I am happy to report that I have fixed the issue! special thanks to PursuitInAshes!

2023-11-28 17:57 UTC, lzk228 reviewed
i personally don't like that here is 2 mimes, 2 clowns, 2 musicians and 2 paramedics for ONLY 60 PLAYERS

about map, in some places too much decals in some too less

2023-12-21 01:35 UTC, closed without merging

2023-12-21 01:35 UTC, Starbuckss14 commented
This PR is getting closed! The map Rim will remain on my pc if I come back to it or if anyone wants to take over the project. I switched work to my new asteroid map "Phobos." Below are some teasers!
![Screenshot (25)](https://github.com/space-wizards/space-station-14/assets/145926356/c369f35f-0676-44df-98fb-f5a293af149c)
![Screenshot (26)](https://github.com/space-wizards/space-station-14/assets/145926356/274ca630-5705-459c-b1ac-12d54a14fc1b)
![Screenshot (27)](https://github.com/space-wizards/space-station-14/assets/145926356/8939867a-94b0-42c0-a443-4dbc8b8a62d0)