Animals obey conservation of matter unless they are undead
space-wizards/space-station-14 pull request #21922
Opened 2023-11-27 14:36 UTC by Sirionaut

## About the PR
Somewhat addresses #21726 & #18927

- Animals only produce if their hunger level is at least **okay** (before it was **peckish**)
- They now also consume extra nutrients when doing that (before it was only chickens)
- Hungerless animals (zombies) still produce endlessly, eggLayer code implied that was on purpose and I love it, so I expanded it
- Zombification removes reproductive abilities
- Refactored a bit
 
does NOT include:
- shared animal metabolism update thing

## Why / Balance
Animals should obey the 1st law of thermodynamics, unless they are zombies.

I like the idea of zombie animals still producing food, it allows for FUN when someone lets loose the zombified food supply.

eggLayer: One every 60-120 seconds for 60 hunger (unchanged)
udder: 25 every 60 seconds for 10 hunger
wool: 25 every 60 seconds for 10 hunger

While testing, I noticed that zombie animals can procreate with healthy ones.
Zombies should reproduce via biting, not traditional biology.

## Technical details

- ZombieSystem.Transform.cs removes reproductive components
- Animalsystems now check _mobState.IsDead(uid) 
- Consumes nutrients when producing (if the entity has hunger)
- changed udders to use base.update(frameTime) instead of counting frames like before. (I guessed this is the newer and better way to do it?)

## Media

- [X] this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:

- fix: Animals now obey conservation of matter (unless they are undead).

2023-11-28 14:02 UTC, Sirionaut commented
last updates is me trying to implement what was written in 
https://github.com/space-wizards/space-station-14/discussions/21113 &
https://github.com/space-wizards/space-station-14/discussions/20585

2023-11-28 14:14 UTC, deltanedas requested changes

2023-11-28 14:14 UTC, deltanedas commented on Content.Server/Animals/Components/EggLayerComponent.cs
>      public string EggLayAction = "ActionAnimalLayEgg";
EntProtoId

2023-11-29 10:46 UTC, deltanedas commented on Content.Server/Animals/Components/EggLayerComponent.cs
>      public string EggLayAction = "ActionAnimalLayEgg";
if you remove the serializer it wont catch invalid ids
EntProtoId does this automatically while string needs the type serializer

2023-12-11 03:19 UTC, mirrorcult approved these changes
lovely PR!!

2023-12-11 03:19 UTC, mirrorcult commented
going to modify the changelog here, since i think its not clear enough what the PR changes

2023-12-11 03:20 UTC, merged