Fire Extinguisher action "Toggle Safety"
space-wizards/space-station-14 pull request #21942
Opened 2023-11-28 08:50 UTC by alwinnocom

![image](https://github.com/space-wizards/space-station-14/assets/63136288/f3b01d95-9515-4da2-8c9b-64749682f6a3)
![image](https://github.com/space-wizards/space-station-14/assets/63136288/efa893e7-989a-4653-8aaf-51f56db3cf0a)

2023-11-28 08:58 UTC, Slava0135 commented
pro tip: don't use master for PRs - make a separate branch so you don't have to reset it and can work on several PRs at the same time

2023-11-28 08:58 UTC, deltanedas requested changes

2023-11-28 08:58 UTC, deltanedas commented on Content.Server/Extinguisher/FireExtinguisherComponent.cs
> +    public string ToggleAction = "ActionToggleSafety";
replace with 
```
[DataField]
public EntProtoId ToggleAction = "ActionToggleSafety";`
```

2023-11-28 08:58 UTC, deltanedas commented on Content.Server/Extinguisher/FireExtinguisherComponent.cs
> +    [DataField("toggleActionEntity")] public EntityUid? ToggleActionEntity;
just `[DataField]`

2023-11-28 08:58 UTC, deltanedas commented on Content.Server/Extinguisher/FireExtinguisherSystem.cs
> -
bruh

2023-11-28 08:58 UTC, deltanedas commented on Content.Server/Extinguisher/FireExtinguisherSystem.cs
> +        /// <summary>
put xmldoc on the method itself not subscribing
also this has no reason to be documented the code is very simple

2023-11-28 08:58 UTC, deltanedas commented on Content.Server/Extinguisher/FireExtinguisherSystem.cs
> +            /// <summary>
regular comment not xmldoc

2023-11-28 08:58 UTC, deltanedas commented on Content.Server/Extinguisher/FireExtinguisherSystem.cs
> +    /// </summary>
as above xmldoc unneeded its self explanatory

2023-11-28 08:58 UTC, deltanedas commented on Content.Server/Extinguisher/FireExtinguisherSystem.cs
> +    public void ToggleSafety(EntityUid uid,
user is never used just remove it

2023-11-28 08:58 UTC, deltanedas commented on Content.Server/Extinguisher/FireExtinguisherSystem.cs
> +        // Change the sprite from Off to On or On to Off via SharedActionSystem.cs & ActionUIController.cs StartTargeting()
comment not needed probably

2023-11-28 08:59 UTC, Slava0135 commented on Content.Server/Extinguisher/FireExtinguisherSystem.cs
> -
:trollface:

2023-11-29 01:36 UTC, alwinnocom commented on Content.Server/Extinguisher/FireExtinguisherSystem.cs
> -
my bad it was an accident

2023-11-29 02:21 UTC, EmoGarbage404 commented
does this even need to be an action? toggling it inhand is literally just pressing "z," last I checked. This just seems like action bloat.

2023-11-29 21:27 UTC, closed without merging