Add water cups to water coolers
space-wizards/space-station-14 pull request #22073
Opened 2023-12-02 01:21 UTC by tgrkzus

## About the PR

Added water cup dispensing to water coolers

As well as added examine on Bins (e.g. a paper bin) to say how many items are left.
And added an alt interact on bin interaction as a fallback to restocking items in bins.
Also to simplify things I make Water cups now default to empty, which is more sensible to me, why would a station have random water cups sitting around for hours? Minor nerf I guess to some maps?

Another note is you can technically put other cups in the bin, if you want. Which is a bit odd, but better than adding a random tag for just a paper cup I think.

## Why / Balance

Water coolers without cups are kinda useless in a lot of maps, other than as a random water tank.
The sprite has a paper cups on the side so I guess this was intended at some point.

## Technical details

- Reuses the same bin component as Paper Bin
- Use alt verbs to construct a fallback on bin interaction for restocking

## Media

Water cooler examine
<img width="329" alt="watercooler" src="https://github.com/space-wizards/space-station-14/assets/7283010/6f433664-8ab6-441b-94b4-535568c08e5b">

And demo of the usage.
https://github.com/space-wizards/space-station-14/assets/7283010/4232839d-daf8-4b0b-a3f2-b9e55ec20882

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Paper cups are now available at water coolers.

2023-12-02 01:38 UTC, Partmedia commented on Resources/Locale/en-US/prototypes/entities/structures/storage/tanks/tanks.ftl
> +    .desc = Seems like a good place to stand and waste time. It has a stock of paper cups on the side
Missing trailing period

2023-12-02 01:42 UTC, Partmedia commented
Thank you for your contribution. I think this change is very welcome. I'm going to give this an in-game test in a bit and double check things work.

Please take a look at the test failure (which doesn't look like a false positive). If you have questions about what it means, please let us know.

2023-12-03 01:49 UTC, EmoGarbage404 requested changes

2023-12-03 01:49 UTC, EmoGarbage404 commented on Content.Shared/Storage/EntitySystems/BinSystem.cs
> +        args.PushText(Loc.GetString("bin-component-on-examine-text", ("count", component.Items.Count)));
this locale string isn't in the files you've committed. did you forgor?

2023-12-03 01:49 UTC, EmoGarbage404 commented on Content.Shared/Storage/EntitySystems/BinSystem.cs
> +            OnAfterInteractUsing(uid, component, new AfterInteractUsingEvent(args.User, (EntityUid) args.Using, args.Target, EntityCoordinates.Invalid, canReach));
you should really just make a private function with this code and call it in both. constructing a new event here is really strange.

2023-12-05 21:47 UTC, merged