Kobold Monkey
space-wizards/space-station-14 pull request #22108
Opened 2023-12-03 02:08 UTC by UbaserB

## About the PR

As per this message by Flare, i decided to add kobold monkeys to the game. Kind of like normal monkeys, you can buy them in cubes from cargo and they act similarly. The biggest difference is that while they have a lot less health, they move much faster (i havent balanced movement speed yet) and do more damage than a normal reptilian. When they become sentient, they can speak like normal humans. If possible, i would like to implement an accent for the kobolds.

![image](https://github.com/space-wizards/space-station-14/assets/134914314/9ed9d6ca-6c3c-4115-a0e6-220524e525dc)

I haven't implemented a mob like this before and may have made some mistakes in the yamls so please tell me if i did.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Can't post image yet, will when error is fixed.

## Breaking changes

I tried fixing this error by making sure those two prototypes dont have any mistakes but i legitimately don't know what's wrong.

![image](https://github.com/space-wizards/space-station-14/assets/134914314/3b7e5a16-4e2c-4857-86c8-f36af268dde9)

**Changelog**

:cl: Ubaser
- add: You can now purchase kobolds from cargo as an alternative to monkeys!

2023-12-03 02:11 UTC, metalgearsloth submitted a review, later dismissed

2023-12-03 02:13 UTC, UbaserB commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
>  - type: entity
i have no idea how to do that, i thought you had to list every component

2023-12-03 02:25 UTC, UbaserB commented
> These needed to be shaded in the same way as lizards, they currently appear to use many less colors then them.

ok yea kinda forgot about that

2023-12-04 23:38 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
>  - type: entity
That would be better, anything that's just wholesale copying the yaml over as it quickly makes it unmaintainable.

2023-12-11 16:00 UTC, Kadeo64 commented
can't wait to make an army of kobolds to overthrow the captain

2023-12-25 16:35 UTC, BYONDFuckery commented
Pay them each one (1) shiny coin from the vault per shift

2023-12-25 16:37 UTC, BYONDFuckery commented
Also make them revvable (with a rare chance to be sentient like monkeys) so you CAN make a kobold army to overthrow the captain


(This might fuck up balancing because SOMEONE is gonna play Emag Kobold and order 20 crates of Kobold Cubes i bet)

2023-12-25 16:39 UTC, Errant-4 commented
Not gonna lie, "purchase kobolds" just sounds wrong

2023-12-25 17:04 UTC, Errant-4 requested changes
The kobolds still speak monkey accent. 

Also can you please merge the main branch because this version of RT will no longer compile on systems so can't be tested

2023-12-28 05:32 UTC, merged