Anesthesia Real
space-wizards/space-station-14 pull request #22140
Opened 2023-12-05 00:40 UTC by IProduceWidgets

## About the PR

Implanters now require the target is asleep to remove an implant.
Also some minor bugfix for nitrous and freezon status effects. They now correctly persist on continued use.

## Why / Balance

Require extra effort for implant checking.

## Technical details

Adds a do after option to require the target is asleep.

## Media

![anesthesia](https://github.com/space-wizards/space-station-14/assets/107586145/6d9a657f-dafe-4269-b9fa-bf948a5e6957)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Implant removal now requires anesthesia!

2023-12-05 02:14 UTC, Nairodian commented
If it's going to require sleeping, I'd decrease the length of the do-after just to be less of a pain in the ass.

2023-12-05 04:53 UTC, notquitehadouken commented
surgery update????????

2023-12-05 07:43 UTC, Holinka4ever commented
Just interesting, how it will work on humanoids that are dead, cause there are contorversal things like:

1)If removing implant from a dead person is not possible without being a patient alive+sleep state, it will be non-logical as hell.

2)if removing implant from a dead person is possible, it will just encourage sec to kill a target, that it will give a frustration to antag/non-antag patient.

2023-12-05 10:52 UTC, Hmeister-real commented
>2)if removing implant from a dead person is possible, it will just encourage sec to kill a target, that it will give a frustration to antag/non-antag patient.

I doubt sec will start killing people who are AoS on sight just to check for implants, if they do that isn't a powergaming issue it's an admin issue. Unless they are a confirmed syndie and it's lrp, then I can see that happening.

2023-12-05 14:33 UTC, Anzarot121 commented
a person can simply turn it off using the sign on the right.

2023-12-05 16:43 UTC, IProduceWidgets commented
> 1)If removing implant from a dead person is not possible without being a patient alive+sleep state, it will be non-logical as hell.

Right now it requires the sleeping component, which you lose when you die. I'm not going to make it work on dead people, as someone else is currently working on consciousness states and it would overlap a bit too much.

> a person can simply turn it off using the sign on the right.

I'm not 100% what you mean, but if you mean players can wake themselves up, this PR also stops that from working with nitrous oxide. (It also is prevented by chloral and nocturine, but in a small enough time span that its probably not useful here unless you have a second person administering it throughout the removal -- maybe once IV bags are added that would work.)

You do however have the option to go to sleep to have your implant removed, if for some reason you wanted that. Nitrous just allows for forced sleeping.

2023-12-05 16:49 UTC, IProduceWidgets commented
I decreased the draw time to 30s from 60s since the time difference is made up and more by the other doafters needed from stripping / internals etc.

2023-12-05 21:42 UTC, Emisse commented
Id like Kerons thoughts on this before proceeding

2023-12-07 01:37 UTC, Geekyhobo commented
I think this can be meta gamed by just clicking on someone with an implanter when they are not asleep, and getting the message that they can't removed the implant i think its a cool feature but it might be more logical to wait til surgery is a thing before we merge this. I think it would work well and be pretty cool if the only way to remove or check for an implanter is when they are undergoing surgery, also as i was writing this i realized you should just have it say the patent must be asleep to perform this action. just don't say the work implanter because it might make people have a bias to check for an implant because the wording leads them to believe the implant regardless of the person having it or not.

2023-12-07 07:01 UTC, IProduceWidgets commented
> I think this can be meta gamed by just clicking on someone with an implanter when they are not asleep, and getting the message that they can't removed the implant i think its a cool feature but it might be more logical to wait til surgery is a thing before we merge this.

Nah, it always fails if they are asleep, and otherwise follows the current logic of nothing happening if they do not have an implant once the doafter completes.

I'll change the popup text. I was unsure of how to word it, and was more focused on avoiding the identity system.

2023-12-07 12:49 UTC, IProduceWidgets commented
Test fail is erroneous

2023-12-08 23:53 UTC, Anzarot121 commented
Found another problem. Slime people don't sleep from nitric oxide.

2023-12-09 00:49 UTC, Aisu9 commented
> Found another problem. Slime people don't sleep from nitric oxide.

another use for hydrochloric hydrate

2023-12-12 04:37 UTC, keronshb commented
> Id like Kerons thoughts on this before proceeding

I don't know if I like the change or not.

The extremely long timer for removal was originally there as a placeholder until surgery was in.

If this helps as an extra step I don't see the harm but I don't exactly like it either.

2023-12-14 11:44 UTC, Simyon264 commented
I like this change. It adds a bit of RP possibilities.

2023-12-15 09:43 UTC, Emisse commented
goncflicts

2023-12-27 00:41 UTC, IProduceWidgets commented
I fixed the conflict, it was just someone fixing nitrous in another PR the same way I did here.

I have no good answer to the slime issue though. I also don't know how surgery will handle that either though, so...

2023-12-27 02:15 UTC, K-Dynamic commented
> I fixed the conflict, it was just someone fixing nitrous in another PR the same way I did here.
> 
> I have no good answer to the slime issue though. I also don't know how surgery will handle that either though, so...

Guess the surgeon will just have to operate on slime patients while they're awake (i.e. make this pr's implant removers work on awake slimes)

That or:
- use chloral hydrate
- wait for nocturine recipe to be added as part of chem rework

2024-01-01 05:55 UTC, deltanedas commented
nocturine recipe currently requires a toxin kit or an emag, both are ideally out of reach of rule abiding goodsec

2024-01-03 05:32 UTC, IProduceWidgets commented
I made it work on slimes that are awake, the solution isn't elegant though because its not generalized for the doafter and instead just special cases the slime species in the implanter system. 

Its the best I can come up with though.

2024-01-20 05:32 UTC, metalgearsloth requested changes
Use spaces not tabs please, mixing it is hell and will immediately get diffed by anyone else who touches the file.

![image](https://github.com/space-wizards/space-station-14/assets/31366439/c3fa0d1f-f548-48f9-a13e-a802fa7961df)

2024-01-28 00:03 UTC, IProduceWidgets commented
I refuse to believe that removing tabs caused that test fail.

2024-02-01 08:39 UTC, metalgearsloth requested changes

2024-02-01 08:39 UTC, metalgearsloth commented on Content.Server/Implants/ImplanterSystem.cs
>      }
1. Don't mix tabs and spaces.
2. Don't hardcode this for species, use a component if yo ureally want it.
3. Please don't inline your ifs like this it makes the formatting a mess.

2024-02-01 08:39 UTC, metalgearsloth commented on Content.Shared/DoAfter/DoAfterArgs.cs
Datafield strings are obsolete.

2024-02-01 08:39 UTC, metalgearsloth commented on Resources/Prototypes/Reagents/gases.yml
> +        refresh: true
You can't just say it's milliseconds and have it work, this is deserialized as seconds.

2024-04-01 02:38 UTC, metalgearsloth commented
Re-open if you come back to it.

2024-04-01 02:38 UTC, closed without merging