Change names for syndi reinforcements
space-wizards/space-station-14 pull request #22193
Opened 2023-12-06 21:33 UTC by lzk228

## About the PR

Changes reinforcements names to random default human male names

## Why / Balance

- for MRP
- its hard to stealth with name like "AMERICA" or "Punch McBeef"

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- tweak: Syndicate reinforcements now have default human male names.

2023-12-06 22:42 UTC, lzk228 commented
> ideally it would be a cvar, funny names are epic for lrp

is it hard to do?

2023-12-07 03:33 UTC, JoeHammad1844 commented
fun fact: the deathcommando.yml was actually meant for death squad names

2023-12-07 03:33 UTC, JoeHammad1844 commented
> i don't see why this really is an issue. syndie reinforcements can't really stealth to begin with considering they're not on the crew manifest. the only thing this deals with is the intentional fact that they're meant to stick out pretty bad.

secoff PDAs actually dont get access to the crew manifest (they do, but they are dumb)

2023-12-07 03:34 UTC, JoeHammad1844 commented
maybe nuclear operative reinforcements should get funny names, infact there should be a difference between syndicate and nuclear reinforcements so they can have different loadouts. currently they both use the same 'barratry' loadout

2023-12-07 13:38 UTC, notquitehadouken commented
> > i don't see why this really is an issue. syndie reinforcements can't really stealth to begin with considering they're not on the crew manifest. the only thing this deals with is the intentional fact that they're meant to stick out pretty bad.
>
> secoff PDAs actually dont get access to the crew manifest (they do, but they are dumb)

"there's this bug so i don't have to do anything"

2023-12-12 07:54 UTC, ps3moira commented
I see no issue with this and like mentioned before, syndicate reinforcement agents are not really supposed to be stealth, they're supposed to be the guy to take eyes of you or at the very least help you with whatever.

2023-12-25 01:09 UTC, LankLTE requested changes
I feel this should either be a cvar or not implemented at all- for LRP reinforcements really aren't a stealth option and I don't feel changing the names are necessary there.

2023-12-25 02:20 UTC, lzk228 commented
dunno how to actually code cvars so

2023-12-25 02:20 UTC, closed without merging