Combat nitrile gloves
space-wizards/space-station-14 pull request #22275
Opened 2023-12-09 21:25 UTC by Stanislav4ix

## About the PR
Combat nitrile gloves are a special development of the Syndicate for their medics. They are sterile and most importantly combative. They will protect you from burns, electric shock and just make you look stylish.

## Why / Balance
This was added primarily for RP.

https://github.com/space-wizards/space-station-14/assets/124695665/5a2f736d-18a1-4ed2-ba81-01b5a35276c2

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
Added combat nitrile gloves for nuke medics. Now they appear with them.

2023-12-09 21:32 UTC, JoeHammad1844 commented
this is cool, when its added, these should increase the speed of using medical, like regular nitriles should

2023-12-09 21:33 UTC, JoeHammad1844 commented
also, your changelog is broken, it should look like this

:cl: Stanislav4ix
- add: blah blah

2023-12-10 00:40 UTC, Doru991 requested changes

2023-12-10 00:40 UTC, Doru991 commented on Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
> +    fiberMaterial: insulative
```suggestion
    fiberMaterial: fibers-insulative
```
You got this word wrong, which is why the tests aren't happy

2023-12-10 11:33 UTC, closed without merging