Added new plushie toy!
space-wizards/space-station-14 pull request #22456
Opened 2023-12-13 17:03 UTC by Stanislav4ix

## About the PR

## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Stanislav4ix
- add: 

https://github.com/space-wizards/space-station-14/assets/124695665/3b296aeb-7a53-47ff-9380-fb0d6c119307

Added new toy! Meet "Plushie bubble"!

2023-12-13 17:07 UTC, deltanedas commented
minifauna plushie when

2023-12-13 17:10 UTC, Stanislav4ix commented
> minifauna plushie when

But I didn't even think about that, thanks for the idea bro :)

2023-12-13 18:19 UTC, Errant-4 commented
Either add some changelog text or remove the blank entry

2023-12-13 20:04 UTC, Stanislav4ix commented
> Either add some changelog text or remove the blank entry

Changelog isn't blank

2023-12-13 20:08 UTC, deltanedas commented
videos arent put in changelog
your cl is `add:`

2023-12-13 22:14 UTC, Stanislav4ix commented
> <!-- Please read these guidelines before opening your PR: https://docs.spacestation14.io/en/getting-started/pr-guideline -->
> <!-- The text between the arrows are comments - they will not be visible on your PR. -->
> 
> ## About the PR
> Added new plushie toy just for fun. You can scale it and do something fun :)
> 
> ## Why / Balance
> Because we need more toys!!
> 
> ## Technical details
> Nothing special.
> 
> ## Media
> <!-- 
> PRs which make ingame changes (adding clothing, items, new features, etc) are required to have media attached that showcase the changes.
> Small fixes/refactors are exempt.
> Any media may be used in SS14 progress reports, with clear credit given.
> 
> If you're unsure whether your PR will require media, ask a maintainer.
> 
> Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
> -->
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame
> https://github.com/space-wizards/space-station-14/assets/124695665/3b296aeb-7a53-47ff-9380-fb0d6c119307
> 
> **Changelog**
> :cl: Stanislav4ix
> - add:  Added new toy! Meet "Plushie bubble"!
> 
> <!--
> Make sure to take this Changelog template out of the comment block in order for it to show up.
> :cl:
> - add: Added fun!
> - remove: Removed fun!
> - tweak: Changed fun!
> - fix: Fixed fun!
> -->
>

2023-12-13 22:16 UTC, Stanislav4ix commented
> <!-- Please read these guidelines before opening your PR: https://docs.spacestation14.io/en/getting-started/pr-guideline -->
> <!-- The text between the arrows are comments - they will not be visible on your PR. -->
> 
> ## About the PR
> Added new plushie toy just for fun. You can scale it and do something fun :)
> 
> ## Why / Balance
> Because we need more toys!!
> 
> ## Technical details
> Nothing special.
> 
> ## Media
> <!-- 
> PRs which make ingame changes (adding clothing, items, new features, etc) are required to have media attached that showcase the changes.
> Small fixes/refactors are exempt.
> Any media may be used in SS14 progress reports, with clear credit given.
> 
> If you're unsure whether your PR will require media, ask a maintainer.
> 
> Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
> -->
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> **Changelog**
> :cl: Stanislav4ix
> - add: 
> 
> https://github.com/space-wizards/space-station-14/assets/124695665/3b296aeb-7a53-47ff-9380-fb0d6c119307
> 
> **Changelog**
> :cl: Stanislav4ix
> - add: Added new toy! Meet "Plushie bubble"!
> 
> <!--
> Make sure to take this Changelog template out of the comment block in order for it to show up.
> :cl:
> - add: Added fun!
> - remove: Removed fun!
> - tweak: Changed fun!
> - fix: Fixed fun!
> -->
>

2023-12-13 22:16 UTC, Stanislav4ix commented
> <!-- Please read these guidelines before opening your PR: https://docs.spacestation14.io/en/getting-started/pr-guideline -->
> <!-- The text between the arrows are comments - they will not be visible on your PR. -->
> 
> ## About the PR
> Added new plushie toy just for fun. You can scale it and do something fun :)
> 
> ## Why / Balance
> Because we need more toys!!
> 
> ## Technical details
> Nothing special.
> 
> ## Media
> <!-- 
> PRs which make ingame changes (adding clothing, items, new features, etc) are required to have media attached that showcase the changes.
> Small fixes/refactors are exempt.
> Any media may be used in SS14 progress reports, with clear credit given.
> 
> If you're unsure whether your PR will require media, ask a maintainer.
> 
> Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
> -->
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> **Changelog**
> :cl: Stanislav4ix
> - add: 
> 
> https://github.com/space-wizards/space-station-14/assets/124695665/3b296aeb-7a53-47ff-9380-fb0d6c119307
> 
> **Changelog**
> :cl: Stanislav4ix
> - add: Added new toy! Meet "Plushie bubble"!
> 
> <!--
> Make sure to take this Changelog template out of the comment block in order for it to show up.
> :cl:
> - add: Added fun!
> - remove: Removed fun!
> - tweak: Changed fun!
> - fix: Fixed fun!
> -->
>

2023-12-13 22:20 UTC, Stanislav4ix commented
> videos arent put in changelog
> your cl is `add:`

Thanks, I fixed it

2023-12-13 23:24 UTC, Errant-4 commented
Dragon Roar might be a risky sound effect to make this spammable
I don't know about sprite copyright but should that part not be updated in meta.json ?

2023-12-13 23:45 UTC, deltanedas commented
give it long cooldown like nuke toy

2023-12-14 11:24 UTC, Stanislav4ix commented
> give it long cooldown like nuke toy

I did it, now cooldown is 30 seconds

2023-12-14 18:46 UTC, Errant-4 commented
Only the in-hand use is restricted, it can be thrown for continuous roaring. Also, when it hits a wall it plays both a squeak and a roar

2023-12-14 19:34 UTC, ficcialfaint requested changes

2023-12-14 19:34 UTC, ficcialfaint commented on Resources/Textures/Objects/Fun/toys.rsi/meta.json
Add info in `copyright` field about where you took the sprite form

2023-12-25 00:53 UTC, LankLTE commented
@Stanislav4ix Are you coming back to this?

2023-12-25 01:28 UTC, LankLTE commented
This could probably serve to be made obtainable somewhere- the arcade cabinet rewards or the plushie crate are usual spots. That said I don't believe it's necessary.

2024-01-07 20:31 UTC, TheShuEd commented
looks like you can't get that toy anywhere. Is this planned, or did you forget to add her ways to get it?

2024-02-01 14:13 UTC, metalgearsloth commented
Re-open if you come back to it.

2024-02-01 14:13 UTC, closed without merging