Fix mob pull issue
space-wizards/space-station-14 pull request #22485
Opened 2023-12-14 13:36 UTC by Anzarot121

## About the PR

Once again allows creatures that inherit from simplemob(hamster, slime, spider, etc) to pull items.
## Why / Balance

fix issue https://github.com/space-wizards/space-station-14/issues/22465
## Technical details

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None
**Changelog**
:cl:
- fix: Mobs can now pull things

2023-12-14 13:38 UTC, EmoGarbage404 commented
I feel like this really shouldnt be on simplemob. Entities should just add this as needed because every mob being able to drag can be highly problematic.

2023-12-14 13:39 UTC, metalgearsloth commented
Wasn't the point to stop them pulling and breaking / stealing things?

2023-12-14 13:40 UTC, Anzarot121 commented
> I feel like this really shouldnt be on simplemob. Entities should just add this as needed because every mob being able to drag can be highly problematic.

Well, this is how it was before the PR that nerfed mothroaches.

2023-12-14 13:42 UTC, Anzarot121 commented
> Wasn't the point to stop them pulling and breaking / stealing things?

Only mothroaches. But for some reason the author of that PR forbade all creatures that inherit from simplemob from doing this. I added a line of code that saves his changes but again allows everyone else to drag things along.

2023-12-14 14:03 UTC, Errant-4 requested changes

2023-12-14 14:12 UTC, Errant-4 commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
>  - type: entity
That's almost right, but it starts with `- type: entity` , so what you have done is, you visually dislodged the end of the mothroach codeblock. Observe where the indentation changes

2023-12-14 14:49 UTC, Anzarot121 commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
>  - type: entity
done

2023-12-14 18:25 UTC, Errant-4 reviewed
Looks good  in regards to what the original concept of the PR was. I would clarify the changelog entry a bit, and end it with a "."

Now the question is, do you want to call it a day and leave it like this, which would be fair. Or consider emogarbage's suggestion, which I will admit is probably a better idea in the long run. Slightly awkward, because it involves doing the very first approach you tried to do, and I told you not to do

2023-12-14 20:31 UTC, Anzarot121 commented
> Looks good in regards to what the original concept of the PR was. I would clarify the changelog entry a bit, and end it with a "."
> 
> Now the question is, do you want to call it a day and leave it like this, which would be fair. Or consider emogarbage's suggestion, which I will admit is probably a better idea in the long run.

I believe that for my first PR, what I have now will be enough. I spent 4 hours on this, perhaps Emo’s proposal needs to be implemented separately from this PR.

2023-12-14 20:50 UTC, Anzarot121 commented
I also think there needs to be a discussion about which existing mobs should retain the ability to pull things, which should be added this ability, and which should be removed.

2023-12-16 09:32 UTC, Anzarot121 commented
So?

2023-12-19 14:57 UTC, OctoRocket commented
This would certainly nice to have back.

2023-12-25 11:28 UTC, metalgearsloth commented
> > Wasn't the point to stop them pulling and breaking / stealing things?
> 
> Only mothroaches. But for some reason the author of that PR forbade all creatures that inherit from simplemob from doing this. I added a line of code that saves his changes but again allows everyone else to drag things along.

Mothroaches are a symptom of the problem, hamsters or whatever billion simplemobs there are being able to do it is still an issue.

2023-12-26 02:12 UTC, OctoRocket commented
What was the original issue with moth roaches being able to pull things anyways?

2024-01-19 17:18 UTC, gardspirito commented
Updates?

2024-01-24 03:31 UTC, metalgearsloth commented
> What was the original issue with mothroaches being able to pull things anyways?

Mobs that can go under doors pulling things.

2024-01-24 11:56 UTC, K-Dynamic commented
> Mobs that can go under doors pulling things.

I thought items don't slide under doors even when pulled

Mobs can pull items through plastic flaps though

2024-02-02 00:05 UTC, metalgearsloth commented
People asking for updates when the original request is still pending.

2024-02-02 13:14 UTC, Anzarot121 commented
Oh okay. Well. @EmoGarbage404, Do you have a rough list of mobs or groups of mobs that should be allowed to pull?

2024-02-03 01:25 UTC, merged