Add unoccluded check for pointing arrows
space-wizards/space-station-14 pull request #2253
Opened 2020-10-14 20:30 UTC by DrSmugleaf

Fixes https://github.com/space-wizards/space-station-14/issues/1485

However InRangeUnoccluded believes walls don't occlude for some reason.

2020-10-28 13:01 UTC, DrSmugleaf commented
Ready for review.

2020-10-29 09:48 UTC, metalgearsloth requested changes
I can't point at walls, literally unplayable.

Would be nice to have some kind of combined check that's usable for pointing + context / verbs.

2020-11-02 11:01 UTC, DrSmugleaf commented
> I can't point at walls, literally unplayable.
> 
> Would be nice to have some kind of combined check that's usable for pointing + context / verbs.

Fixed by https://github.com/space-wizards/space-station-14/pull/2420, unless you are trying to point through a corner.

2020-11-03 10:24 UTC, metalgearsloth approved these changes

2020-11-03 10:25 UTC, merged