Added carp chair!
space-wizards/space-station-14 pull request #22781
Opened 2023-12-20 18:47 UTC by Stanislav4ix

## About the PR
I added a carp chair for true aristocrats. :trollface:

## Why / Balance
We need more chairs! And seriously, for better RP or events.

## Technical details
It's made of carp skin, SOOOO EXPENSIVE.

## Media
![image](https://github.com/space-wizards/space-station-14/assets/124695665/392b4e2f-7400-4fe7-a36d-c9a05471ba44)
![image](https://github.com/space-wizards/space-station-14/assets/124695665/a66a5873-b525-4609-a02f-560f6e1ea775)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Stanislav4ix
- add: Added carp chair!

2023-12-20 19:00 UTC, Ilya246 commented
what do we get next? a carp-et?

2023-12-20 20:21 UTC, lzk228 commented
> what do we get next? a carp-et?

a carp pet :trollface:

2023-12-20 21:39 UTC, deltanedas requested changes

2023-12-20 21:39 UTC, deltanedas commented on Resources/Prototypes/Entities/Structures/Furniture/chairs.yml
> +  - type: Rotatable
are these 2 necessary id think theyre inherited

2023-12-20 21:39 UTC, deltanedas commented on Resources/Prototypes/Entities/Structures/Furniture/chairs.yml
> +    node: chairCarp
you have to actually make the construction graph

2023-12-20 23:28 UTC, Emisse commented
this should probably be converted to the sheet meister system as like carp leather or something

2023-12-21 00:11 UTC, JoeHammad1844 commented
we need carp scales to drop from butchered carp (for crafting these and the carp suit)

2023-12-21 00:20 UTC, deltanedas commented
and carp teeth to make statue now that expeds dont use faction structures :trollface:

2023-12-25 00:02 UTC, ficcialfaint requested changes

2023-12-25 00:02 UTC, ficcialfaint commented on Resources/Textures/Structures/Furniture/chairs.rsi/meta.json
> +      "directions": 4
copyright field

2024-01-16 23:17 UTC, TheShuEd commented
Are you planning to finish your pr?

2024-01-16 23:42 UTC, Stanislav4ix commented
> Are you planning to finish your pr?

Yes, just I'm "green", it's difficult for me

2024-01-16 23:47 UTC, TheShuEd commented
If you have any questions, feel free to ask me here or on discord @eshhhed

2024-02-01 11:15 UTC, metalgearsloth commented
Ping if you come back to this.

2024-02-01 11:15 UTC, closed without merging