Adds sound to both Smoke Grenades and Teargas Grenades
space-wizards/space-station-14 pull request #22866
Opened 2023-12-22 22:36 UTC by Hmeister-fake

## About the PR
Adds sound to both smoke grenades and teargas grenades

## Why / Balance
They lacked it beforehand, now they shouldnt.

## Technical details
I am not a coder, this is just a hacky copy and paste job of @deltanedas code from [#22855] with some assumptions being made, but the sound is original. First ever PR, this will hopefully work as intended.

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

- tweak: Smoke grenades and Teargas grenades now have sound.

2023-12-22 22:41 UTC, deltanedas commented
add to attributions.yml in effects too

2023-12-22 22:53 UTC, deltanedas requested changes
sound is paid access and has no easily visible license ultra sus

2023-12-22 22:53 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Weapons/Throwable/grenades.yml
> +    - type: TimerTriggerVisuals
unindent

2023-12-22 22:53 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Weapons/Throwable/grenades.yml
> +      path: /Audio/Effects/Smoke-grenade.ogg
delete

2023-12-22 23:01 UTC, Hmeister-fake commented
> sound is paid access and has no easily visible license ultra sus

i just downloaded it and then used it with a custom sound, so it should be fine.

2023-12-24 06:16 UTC, metalgearsloth commented
> > sound is paid access and has no easily visible license ultra sus
> 
> i just downloaded it and then used it with a custom sound, so it should be fine.

The project hasn't paid for the sound though?

2023-12-24 07:18 UTC, deathride58 commented
![image](https://github.com/space-wizards/space-station-14/assets/6356337/195779b2-f6c2-4e60-aa67-d6e0443b4fa7)

The sound's license ((seen here)[https://www.pond5.com/legal/license]) is fairly clear that this use is a *hard* no, considering there's no way to have a sound in the repo without allowing raw access in the process.

2023-12-24 07:29 UTC, Emisse commented
change the sound effect to something we can use

2023-12-24 11:14 UTC, Hmeister-fake commented
New sound is now completely copyright free, all good.

2023-12-24 15:20 UTC, merged

2024-01-03 22:36 UTC, EmoGarbage404 commented
@Hmeister-fake the sound effect you used is not licensed to be used in this project due to the stipulation on hosting content on other websites.

![image](https://github.com/space-wizards/space-station-14/assets/98561806/8ed72846-832d-4157-95ff-6822b6cff462)

Additionally, the copyright you supplied in the attribution is incorrect. In the future, make sure you verify the actual license for audio being used and that it is suitable for the project.

Thank you.

2024-01-03 23:10 UTC, Hmeister-fake commented
> Additionally, the copyright you supplied in the attribution is incorrect. In the future, make sure you verify the actual license for audio being used and that it is suitable for the project.

It shouldn't be? The actual smoke effect is taken from an unlicensed sound I already had that doesn't actually have a licence I know of (I don't remember what it's from but not a website) but the grenade click is however from a free licence thing. Should I change the effect to be pre-existing from ss13, should I create the noise myself or do you have any suggestions on what I should do.

2024-01-04 03:46 UTC, deltanedas commented
not having a license doesnt mean CC0-1.0 it means all rights reserved