pac
space-wizards/space-station-14 pull request #22932
Opened 2023-12-24 23:40 UTC by TheShuEd

## About the PR

add pacified to thief 

## Why / Balance

:(

:cl:
- tweak: Thiefs now cant hurt anyone, they are pacific.

2023-12-24 23:44 UTC, deltanedas commented
pacifist :trollface: pacific is an ocean

2023-12-24 23:46 UTC, deltanedas requested changes

2023-12-24 23:46 UTC, deltanedas commented on Content.Server/GameTicking/Rules/ThiefRuleSystem.cs
> +
EnsureComp<PacifiedComponent>(mind.OwnedEntity.Value);

2023-12-24 23:48 UTC, Hmeister-fake commented
Please do not merge this, you shouldnt remove the ability to defend youself from an antag role

2023-12-24 23:49 UTC, Hmeister-fake commented
> Please do not merge this, you shouldnt remove the ability to defend youself from an antag role

Just make them have a check that fails the missions if they kill someone or reach a damage freshhold

2023-12-24 23:55 UTC, ficcialfaint commented on Content.Server/GameTicking/Rules/Components/ThiefRuleComponent.cs
> +    public bool PacifistThiefs = true;
```suggestion
    /// Add a Pacified comp to thieves
    /// </summary>
    public bool PacifistThieves = true;
```

2023-12-24 23:55 UTC, ficcialfaint commented on Content.Server/GameTicking/Rules/ThiefRuleSystem.cs
> +            MakeThief(thief, component.PacifistThiefs);
```suggestion
            MakeThief(thief, component.PacifistThieves);
```

2023-12-24 23:57 UTC, LankLTE commented
Have discussed it in the other PR, but I feel this is a really poor way to stop the antag from attacking people. Rather than discouraging combat, you're outright disallowing it.

2023-12-24 23:57 UTC, deltanedas commented on Content.Server/GameTicking/Rules/Components/ThiefRuleComponent.cs
> +    public bool PacifistThiefs = true;
Pacify too :trollface:

2023-12-25 00:02 UTC, PokkeTigrex commented
My main issue with thieves being pacified over following the rule of no violence/murder is their inability to defend themselves from even the most basic mobs, as well as late round antags like zombies that has the goal to kill everyone, including the thief who needs to survive as well. It also completely rules out breaking in by breaking structures with melee. 
Imagine rolling thief as a salvage, and being unable to do your job because you can't breaks some rocks.

2023-12-25 00:13 UTC, LookyPadooky commented
not only is this just kinda whack, but very rarely does anyone ever use the pacifisim trait so if you became a thief most people would just know by the fact that you literally could not throw a punch for your life. maybe call off all thief objectives if the thief directly kills a crewmate? or something like that idk

2023-12-25 00:17 UTC, mirrorcult commented
my thoughts from discord but i feel very strongly this is a positive change

![image](https://github.com/space-wizards/space-station-14/assets/19853115/fbb21590-04b5-4190-87e2-90ccc466a4a4)

![image](https://github.com/space-wizards/space-station-14/assets/19853115/b15e651e-e579-4372-be0e-bf5c12755e51)

2023-12-25 00:20 UTC, mirrorcult commented
the point about rolling salv as a pacifist is valid though. there will probably have to be a proper solution there, maybe just disallowing salv thief

for the record im of the opinion that pacifist trait in general is more fun when the restrictions are fairly obvious and possible to work around--imo it should only block melee attacks and firing guns, pretty much everything else should be allowed

2023-12-25 00:25 UTC, LankLTE commented
There's also a possibility sec metagames this by telling prisoners arrested for stealing shit to punch them since if can't punch, then valid. Just banning an role from getting antag because the (kind of arbitrary) restriction it enforces conflicts with that role kind of seems to me like you shouldn't be putting that restriction on it in the first place. 

As a whole if you're going to give them pacifist but then change it to "be possible to work around", you might as well just give them an "inverse objective" to not damage people or kill people too much otherwise they fail which still gives them wiggle room while not making them completely unable to defend themselves from any threat at all.

2023-12-25 00:26 UTC, Emisse commented
that doesnt work because random crew mates can be pacifist too

2023-12-25 00:27 UTC, LankLTE commented
> that doesnt work because random crew mates can be pacifist too

yeah but it's fairly unlikely, especially in the context of them stealing shit. I doubt the kind of sec who would metagame that are actually gonna be stopped by "well what if I just took the pacifist trait"

2023-12-25 00:31 UTC, Aisu9 commented
mmmmh.... tasty tasty explosive mix in beakers or chemical grenades, i love pacifism

2023-12-25 00:36 UTC, PokkeTigrex commented
Stealing the hypospray (which is very easy with free thieving gloves), or getting the sleep loadout can immediately be weaponized by pacifist thieves to do easy murder. Which is encouraged by forcing this and laxing the rules about non-violence, bypassing the whole point of pacifism.

2023-12-25 03:42 UTC, merged

2023-12-25 20:09 UTC, Carmell0 commented
This is a twmporary solution, right? Like honestly, there has to be something better. Just make it so the theif does zero damage to humans, or that they only do stun damage.

2023-12-25 22:42 UTC, Rainbeon commented
This made dual-antagging Thief-Head Rev very bad for rounds and non-functional for the HR player #22983

2023-12-25 22:46 UTC, deltanedas commented
along with not being able to mine, not being able to defend yourself against shitters or ai mobs, sec perma metagaming

this should be reverted

2023-12-25 22:50 UTC, Aisu9 commented
> along with not being able to mine, not being able to defend yourself against shitters or ai mobs, sec perma metagaming
> 
> this should be reverted

can't you just... use your pickaxe/drill and doafter the blocks? it's slower but still work

2023-12-25 22:51 UTC, deltanedas commented
99% sure that was removed
and doafter = thief metagaming

2023-12-25 23:01 UTC, mirrorcult commented
making some changes to how pacifist works tomorrow that should alleviate pretty much all issues while keeping the core idea

2023-12-25 23:02 UTC, deltanedas commented
that will affect downstream, deltav uses pacifism to prevent end of round grief

2023-12-25 23:03 UTC, mirrorcult commented
it shouldnt affect that much at all

2023-12-25 23:24 UTC, LankLTE commented
I feel like current pacifist, as a trait, is honestly fine. Changing how pacifist works itself is probably worse than just making some other way of the thief not attack people.

2023-12-26 00:55 UTC, Hmeister-fake commented
[#22963] exists for a reason, merge it until a better solution for thief is found.

2023-12-26 00:59 UTC, EmoGarbage404 commented
> [#22963] exists for a reason, merge it until a better solution for thief is found.

literally just wait a day for the proper solution to be coded. the intent behind the pacifism has been explained thoroughly to you in the discord. you don't need to plug your closed PR because you don't like the design.

2023-12-26 01:05 UTC, Hmeister-fake commented
> > [#22963] exists for a reason, merge it until a better solution for thief is found.
> 
> literally just wait a day for the proper solution to be coded. the intent behind the pacifism has been explained thoroughly to you in the discord. you don't need to plug your closed PR because you don't like the design.

It's causing more issues than before due to the new mixed-antag thing. This is quite literally forcing head-revs who also have thief on for example to be pacified and ruining entire shifts. It's just causing more issues than even I thought it would when it first got merged, and its not *just me* not liking the design, im speaking for a lot of people. [#22983] [#22984] and the whole discord discussion with a lot of people disliking it matter, you can't just decide what is best for the game yourselves when there are clear issues.

2023-12-26 01:06 UTC, mirrorcult commented
it's Christmas dip shit I already told you I'm fixing it tomorrow

2023-12-26 01:09 UTC, Hmeister-fake commented
> it's Christmas dip shit I already told you I'm fixing it tomorrow

Unrelated but fair, forgot timezone wise Americans are in the middle of Christmas cheer rn

2023-12-26 01:14 UTC, mirrorcult commented
it's not unrelated it's you can wait a single fuckin day of a feature being mildly broken in like 10% of cases

2023-12-27 07:54 UTC, mirrorcult commented
https://github.com/space-wizards/space-station-14/pull/23037