Change id insertion sound
space-wizards/space-station-14 pull request #23007
Opened 2023-12-26 14:46 UTC by dakamakat

## About the PR

Id card / cartrige  insert sound changing

## Why / Balance

Change previous usage of weapon mag  / UX

## Technical details

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

tweak: new id insert sound added

https://github.com/space-wizards/space-station-14/assets/52600490/8b8b4187-614d-443d-ad5e-964173c02bee

2023-12-26 15:18 UTC, UbaserB commented
based

2023-12-26 15:19 UTC, EmoGarbage404 commented
so long batrfile_magin.ogg

2023-12-26 15:20 UTC, EmoGarbage404 requested changes
add an entry to attributions.yml in the Audio/Machines folder for your new sound effect.

2023-12-28 03:34 UTC, EmoGarbage404 approved these changes

2023-12-28 03:34 UTC, merged