Rename Goldschläger to Gildlager
space-wizards/space-station-14 pull request #23223
Opened 2023-12-30 12:46 UTC by UbaserB

## About the PR

Resolves #10500.

2023-12-30 16:59 UTC, EmoGarbage404 requested changes
needs migration.yml entries for `DrinkGoldschlagerBottleFull` and `DrinkGoldschlagerGlass`

2023-12-31 01:55 UTC, Hmeister-fake commented
Can it keep the ä? It makes it look more unique

2023-12-31 02:11 UTC, UbaserB commented
> Can it keep the ä? It makes it look more unique

it doesnt actually have an ä ingame

2024-01-05 01:00 UTC, Emisse commented
conflict

2024-01-05 01:09 UTC, UbaserB commented
> conflict

shut up i cant fix it!! This PR might as well be closed since literally no one can help me

2024-01-05 01:16 UTC, IamVelcroboy commented
I just want to know if you even considered Goldschlonger at all....

2024-01-05 01:27 UTC, GreyMario commented
> I just want to know if you even considered Goldschlonger at all....

dick joke ban he

2024-01-06 14:22 UTC, metalgearsloth commented on Resources/migration.yml
> +Goldschlager: Gildlager
Needs to be an entity prototype.

2024-01-06 15:34 UTC, merged