allow users to click a button ingame and in lobby to view round-end-s…
space-wizards/space-station-14 pull request #23310
Opened 2024-01-01 02:32 UTC by Cyber-Finn

## About the PR
I added functionality for players to view the Round-End Summary again, after closing it.
Can be done in-game, after round end, and from the lobby.

## Why / Balance
No balance changes made.
This change was made after I spotted a few complaints (and had some myself) about not being able to pull up the round-end summary after closing it. No balance changes made, it's simply a button click that displays the UI again.

## Technical details
I'm simply storing the data from the round end summary, then showing the form again once the user clicks a button.

## Media
Here are 2 videos of the feature in action:
Part 1 shows the new option in the escape menu when the round ends:
https://github.com/space-wizards/space-station-14/assets/146375585/3dd87dab-5b52-4a50-bd55-9eaea4ce17d1

Part 2 shows the new button on the Lobby screen, when the player is returned to the lobby:
https://github.com/space-wizards/space-station-14/assets/146375585/1dce70fb-f8f7-4612-8f7d-f6c628eb1c9b

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
No breaking changes

**Changelog**
Added functionality for players to view the Round-End Summary again, after closing it. Can be done in-game after the round ends, and from the Lobby screen. Note that the EscapeUI button is visible throughout the game, but wont do anything until the round ends. I'm unable to hide it at will, as I was advised to change the way that I did it previously (Where I used the same EscapeUI object to access the same instance of the window that was being displayed when the user pressed ESC).

:cl:
- add: Added functionality for users to see the Round-End-Summary again, after closing it. Press F10 to see the option after round-end (While in-game, between restart). The option will also appear on Lobby screen, above the OOC chat.

2024-01-02 07:52 UTC, Dragonjspider commented
I don't like that in the Esc menu it's right next to quit, but other than that, it's really nice to see this finally getting in

2024-01-05 05:11 UTC, mirrorcult commented
im not a super big fan of how huge the button is in the lobby but its probably mostly fine

2024-01-05 05:13 UTC, EmoGarbage404 commented
Could 100% be an action tbh

2024-01-05 05:13 UTC, mirrorcult requested changes
how does this work with the entities in the roundend menu when you go into the lobby? seems like it would error?

also for the lobby button i'd maybe rename it to just "Round-End Summary" or "Last Round Summary" to keep it shorter

2024-01-05 05:13 UTC, mirrorcult commented on Content.Client/GameTicking/Managers/ClientGameTicker.cs
> +        private static RoundEndMessageEvent _backedUpRoundEndMessage = default!;
uh, just make it nullable instead of null suppressing?

2024-01-05 05:13 UTC, mirrorcult commented on Content.Client/GameTicking/Managers/ClientGameTicker.cs
> +        private static RoundEndMessageEvent _backedUpRoundEndMessage = default!;
and why does it need to be static? just store it on the instance?

2024-01-29 04:29 UTC, closed without merging

2024-01-29 04:29 UTC, metalgearsloth commented
Ping if you come back to this.

2024-03-31 03:23 UTC, Terraspark4941 commented
> Could 100% be an action tbh

considering this is stale, i want to reopen this as my own PR with action-buttons instead of a menu button, just like in TG/station13