NoDrink component
space-wizards/space-station-14 pull request #23356
Opened 2024-01-02 06:00 UTC by DenisShvalov

## About the PR
Added NoDrinkComponent and few change in DrinkSystem

## Why / Balance
If you want to make someone drinkless

## Media

https://github.com/space-wizards/space-station-14/assets/115770678/a8c4b041-b218-4d39-a060-e7f670a972de

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Component that prevent someone from drinking

2024-01-02 06:02 UTC, UbaserB commented
remove the CL, this isnt a playerfacing change

2024-01-02 06:05 UTC, DenisShvalov commented
> remove the CL, this isnt a playerfacing change

Removed

2024-01-02 08:15 UTC, Anzarot121 commented
This should be added to the skeleton. At the moment, they cannot drink, but their attempts still remove substances from the vessels.

2024-01-02 15:31 UTC, Cyber-Finn commented
silly question, but skeles drink milk to heal, right? Wouldnt this impact their ability to heal - if applied to them as-is (that is, removing the ability to drink anything at all)?

2024-01-02 15:55 UTC, DenisShvalov commented
> silly question, but skeles drink milk to heal, right? Wouldnt this impact their ability to heal - if applied to them as-is (that is, removing the ability to drink anything at all)?

Skeleton can't drink milk, he heals by spilling milk on them

2024-01-02 17:04 UTC, Cyber-Finn commented
> > silly question, but skeles drink milk to heal, right? Wouldnt this impact their ability to heal - if applied to them as-is (that is, removing the ability to drink anything at all)?
> 
> Skeleton can't drink milk, he heals by spilling milk on them

copy, thanks for answering! 😄

2024-02-22 03:03 UTC, AJCM-git requested changes

2024-02-22 03:03 UTC, AJCM-git commented on Content.Server/Nutrition/Components/NoDrinkComponent.cs
> +/// This component marks entity, that can't drink anything
Why cant you just remove the drink component from the entities that need this?

2024-03-17 11:41 UTC, closed without merging