Localize admin menu(atmos, objects)
space-wizards/space-station-14 pull request #23373
Opened 2024-01-02 13:03 UTC by MetalSage

## About the PR

Added localization for the admin menu, it is now fully localized. I guess.
- Localized atmos tab and windows that open from this tab
- Localized objects tab

**Changelog**

no cl no fun

2024-01-02 13:07 UTC, ficcialfaint requested changes

2024-01-02 13:07 UTC, ficcialfaint commented on Content.Client/Administration/UI/Tabs/ObjectsTab/ObjectsTab.xaml.cs
> +            ObjectTypeOptions.AddItem(_localization.GetString($"admin-ui-objects-tab-selection-{Enum.GetName((ObjectsTabSelection)type)}")!);
make the enum string lowercase

2024-01-02 13:47 UTC, ficcialfaint requested changes
the following needs to be localized as well:
- Reason in `AdminTab
/PlayerActionsWindow.xaml`
- `AdminTab
/TeleportWindow.xaml`
- `AdminbusTab
/LoadBlueprintsWindow.xaml`
- Player count in `PlayerTab
/PlayerTab.xaml`
- `RoundTab.xaml`

2024-03-01 02:51 UTC, AJCM-git commented
@MetalSage Are you coming back to this?

2024-04-14 05:36 UTC, closed without merging