Admin chat relay + kill of MoMMI OOC relay for good
space-wizards/space-station-14 pull request #23458
Opened 2024-01-03 17:46 UTC by Simyon264

## About the PR
Adds CVars for admin chat relay and integrates a Discord bot into the server. Also kills of MoMMI OOC relay.

## Why / Balance
Resolves #20144. Also MoMMI is being phased out.

## Technical details
Adds `discord.net` as a NuGet package to `Content.Server`. This is used in `DiscordLink.cs` to host a discord bot which will handle all bot interaction. 

## Media

![image](https://github.com/space-wizards/space-station-14/assets/63975668/97b9a1e4-4f81-4e0d-9941-e6856a3a75a3)
![image](https://github.com/space-wizards/space-station-14/assets/63975668/8028d1d0-7eab-4537-92db-81dbbc7a8932)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Removes IMoMMILink, which means existing servers will have to set up the OOC relay again. Should be pretty much a drop in replacement. 
There are 3 CVars needed for the OOC bridge:
`discord.token`: Your Discord bot token.
`discord.guild_id`: The guild ID for the channel.
`discord.relay_channel_id`: The channel ID for the OOC relay.

2024-01-03 18:03 UTC, VasilisThePikachu requested changes
Lil nitpicks

2024-01-07 18:48 UTC, VasilisThePikachu reviewed
I don't see the commit where you added this. But the "!status" screenshot example conflicts with redbots (Sussy baka bot on discord) status command. 

I think the fix here is to just make the prefix customizable.

Also ensure it does not do anything if its ran outside a forum channel if you have not already.

2024-01-08 07:25 UTC, Simyon264 commented
> Also ensure it does not do anything if its ran outside a forum channel if you have not already.

It ignores the command when ran outside of the Ahelp relay forum channel.

2024-01-13 14:28 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink.cs
> +        Client = new DiscordSocketClient(new DiscordSocketConfig()
This should absolutely not be constructed from `PostInject()`. This should be from some initialize call, and only if a token is specified.

2024-01-13 14:29 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink.cs
> +        }
Your problem is that you're calling this from `PostInject()`.

2024-01-13 14:31 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink.cs
> +        Debug.Assert(Client.LoginState == LoginState.LoggedOut);
```suggestion
        DebugTools.Assert(Client != null);
        DebugTools.Assert(Client.LoginState == LoginState.LoggedOut);
```

2024-01-13 14:31 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink.cs
> +                _sawmill.Fatal(FormatLog(msg));
Please provide a separate sawmill for relaying messages created by Discord.Net. Something like `discord.link.log`.

2024-01-13 14:33 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink.cs
> +        Client.GetGuild(ulong.Parse(_guildId))
This `ulong` should be parsed when the CVar is read from the config.

2024-01-13 14:36 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink.cs
> +        switch (msg.Severity)
Use `_sawmill.Log` as it allows you to pass the log level as a parameter, then use a switch expression to translate the log levels.

2024-01-13 14:37 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink.cs
> +            _sawmill.Warning("No Discord token specified, not connecting.");
This should not be a warning case, it is a totally valid use for game servers to not have the Discord integration configured.

2024-01-13 14:38 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink.cs
> +        await Task.Delay(-1); // Following discord.net guide, idk what im doiung help
You don't need to do this, the game server will keep the process running.

2024-01-13 14:39 UTC, PJB3005 commented on Content.Shared/CCVar/CCVars.cs
> +        /// </summary>
This entire file needs better comments indicating that these various CVars you added are linked and need each other to be configured.

2024-01-13 14:40 UTC, PJB3005 commented on Content.Shared/CCVar/CCVars.cs
> +        ///     Prefix for the Discord bot.
Indicate that this is a prefix for all the _commands_.

2024-01-26 16:16 UTC, IProduceWidgets commented
Ideally players should not see that the admin is not in game.

2024-01-29 20:28 UTC, Peptide90 commented
> Ideally players should not see that the admin is not in game.

People admin checking is as old as time and an ahelp will do it. They'll find a way, but yeah if it's easy enough to hide sure.

2024-01-30 00:04 UTC, Simyon264 commented
Whoops forgot to show it in the screenshot! Admins who reply using the ahelp relay are marked yellow and have a little symbol in front of their name.

2024-02-01 08:35 UTC, metalgearsloth commented
@Simyon264 is this still being worked on.

2024-02-01 11:10 UTC, Simyon264 commented
Yes. I have been taking a short break for about a week now.

2024-02-10 12:59 UTC, Simyon264 commented
> Ideally players should not see that the admin is not in game.

I added a CVar to hide that the message was sent from discord, but the Relay uses your discord username, which means it's easy to check if it was sent from discord by just matching the ingame username from the discord username (Also Discord usernames are all lowercase).

2024-02-10 14:01 UTC, Simyon264 commented
Test fails seems unrelated.

2024-03-28 21:37 UTC, ShadowCommander requested changes

2024-03-28 21:37 UTC, ShadowCommander commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("admin.ahelp_relay_channel_id", string.Empty, CVar.SERVERONLY);
Mention Discord so that it's clearer what these are for.

2024-03-28 21:37 UTC, ShadowCommander commented on Content.Shared/CCVar/CCVars.cs
> +        /// The channel that OOC messages are sent to.
Add Discord mention

2024-03-28 21:37 UTC, ShadowCommander commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("admin.ahelp_relay_show_discord", true, CVar.SERVERONLY);
```suggestion
        ///     If this is true, the ahelp relay shows that the response was from Discord. If this is false, all messages an admin sends will be shown as if the admin was ingame.
        /// </summary>
        public static readonly CVarDef<bool> AdminAhelpRelayShowDiscord =
            CVarDef.Create("admin.ahelp_relay_show_discord", true, CVar.SERVERONLY);
```

2024-03-29 13:36 UTC, Simyon264 commented
Reviews done.

2024-04-11 17:51 UTC, ShadowCommander approved these changes
Looks good, though I haven't done a super in depth review.

2024-04-11 20:41 UTC, Simyon264 commented
Don't worry, PJB will do a nuclear bomb shell of a review and I'm ready for it.

2024-05-08 21:49 UTC, PJB3005 requested changes
Try again

2024-05-08 21:49 UTC, PJB3005 commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +using Discord.WebSocket;
There should be no references to Discord.Net in this file.

In fact, ideally there wouldn't even be references to *Discord* in this file. There should be a separate manager in charge of bridging bwoinks to Discord. You'd have:
* `BwoinkSystem` (this shouldn't be a system but that's not your fault)
* `DiscordLink`
* `DiscordBwoinkLink`
* `DiscordChatLink`

2024-05-08 21:49 UTC, PJB3005 commented on Content.Server/Chat/Managers/ChatManager.cs
> +        private void MessageReceived(SocketMessage arg)
This functionality shouldn't be in chat manager.

2024-05-08 21:49 UTC, PJB3005 commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +        private static string EscapeMarkdown(string text)
Does Discord.Net not have functionality for this?

2024-05-08 21:49 UTC, PJB3005 commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +            var job = "No entity attached";
These need to be localized strings

2024-05-08 21:49 UTC, PJB3005 commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +                await relay.SendMessageAsync($"Use `{_discord.BotPrefix}status` to regenerate the status embed as seen above. `-` in the beginning of a message will be cause the message to not be rel
Localized string

2024-06-19 15:07 UTC, metalgearsloth commented
derelict.

2024-06-19 16:49 UTC, Simyon264 commented
I will come back to this once #28639 is merged as it touches the BwoinkSystem as well.

2024-08-02 02:32 UTC, Simyon264 commented
I am quite short on time in the following days (mainly because of my upcoming birthday). I will reopen this once I find the time.

2024-08-02 02:32 UTC, closed without merging

2024-09-25 20:21 UTC, AwareFoxy commented
> I am quite short on time in the following days (mainly because of my upcoming birthday). I will reopen this once I find the time.

hi, can I take care of this if you don't want to go back to it

2024-09-26 07:05 UTC, Simyon264 commented
> > I am quite short on time in the following days (mainly because of my upcoming birthday). I will reopen this once I find the time.
> 
> hi, can I take care of this if you don't want to go back to it

I now have the time and will soon atomize this PR into two distinct issues.
1: The ahelp relay
2: The ooc relay.

I will first do the ooc relay as that is much simpler and integrates a bot into Content.

2024-11-13 21:04 UTC, JIPDawg commented
Guten tag, 

give pl0x.

Auf Wiedersehn.