Slimes now don't rot (?)
space-wizards/space-station-14 pull request #23452
Opened 2024-01-03 16:55 UTC by Hmeister-fake

## About the PR
 Slimes now shouldn't rot.

## Why / Balance
 As they were before the recent change to rotting, slimes had very little to work with and this at least gave them an upperhand comparable to Arachnid pockets and Reptilian tail grabbing. Without not rotting, slimes where just squishier and easier to kill rainbow urist mchands who OD faster from meds and i guess have funny blood?

## Technical details
 Added one line of code, someone please check if it's placed in the right area.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
 Literally one line of code

**Changelog**
 🆑 Hmeister

- tweak: Slimes don't Rot again.

2024-01-03 18:32 UTC, EmoGarbage404 commented
Please test your changes before you make PRs

2024-01-03 22:08 UTC, Hmeister-fake commented
> Please test your changes before you make PRs

can't, dev enivornment is bugged and i cant figure out how to fix it

2024-01-03 22:24 UTC, Kadeo64 commented
imo "slimes don't rot" seems like a bandaid change for slimes as a species when they could really use actual unique abilities, like [23425] attempts to do.

2024-01-03 22:33 UTC, Hmeister-fake commented
> imo "slimes don't rot" seems like a bandaid change for slimes as a species when they could really use actual unique abilities, like [23425] attempts to do.

Yes, but untill then they shouldn't be almost objectively worse than Diona (lmao)

2024-01-03 22:33 UTC, Hmeister-fake commented
> Please test your changes before you make PRs

it should work however, got help from a maintainer to confirm it.

2024-01-03 23:48 UTC, Nairodian commented
Okay to properly explain why this isn't going to work. `noRot` is actually short form for no rotation, it's used for sprites that shouldn't rotate. You're looking for the component `- type: Perishable`. Please keep in mind if you're going to remove it from slimes, you're going to have to remove the perishable component from the base mob, and re-add it to every species except slimes.

2024-01-04 00:32 UTC, Just-a-Unity-Dev commented
probably shouldn't make a bandaid when the proper PR is just a few days away - this will probably conflict with my pr too

2024-01-04 00:36 UTC, DrMelon requested changes

2024-01-04 00:36 UTC, DrMelon commented on Resources/Prototypes/Entities/Mobs/Species/slime.yml
> +  noRot: true
See: https://github.com/space-wizards/space-station-14/pull/23452#issuecomment-1876120863

2024-01-04 01:07 UTC, closed without merging