Dice Bombs (draft)
space-wizards/space-station-14 pull request #23475
Opened 2024-01-03 22:49 UTC by lzk228

## About the PR

Add dice bombs as a librarian traitor uplink item.
It waits value seconds after roll and KABLOOM!

I need help with balance, because i dont know what numbers i should put in Explosive component in dice prototypes.

## Why / Balance

Cool idea.

## Technical details

Files changed

## Media

Just a demo

https://github.com/space-wizards/space-station-14/assets/124214523/f8481f1e-3a38-4f97-a589-f73aed0f87fc

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Dice bombs added to the librarian uplink.

2024-01-03 23:44 UTC, Aisu9 commented
please make the dice gain damage depending on the timer

2024-01-03 23:55 UTC, lzk228 commented
> please make the dice gain damage depending on the timer

i would, but if i do, it will be afwul maybe idk
explosion values need very fine tuning so

2024-01-04 00:31 UTC, Just-a-Unity-Dev commented
the higher the roll = the higher the severity imo like dnd

2024-01-04 00:35 UTC, GoodWheatley commented
> the higher the roll = the higher the severity imo like dnd

rolling a nat 1 should instagib you

2024-01-04 01:49 UTC, K-Dynamic commented
Nat(max) -1: syndie bomb explosion
Nat(max): singulo/tesla

Make dice available to clown too

2024-01-04 02:18 UTC, LookyPadooky commented
I agree that rolling a 20 on the d20 should do something insane, it probably won't happen often either because you

1. have to play librarian (one of the least popular jobs)
2. roll syndicate
3. win a one in twenty chance after spending your well earned syndicate bucks on a really risky gimmick item

so please make it have like a syndie bomb tier explosion.......... it would be really funny, plus people would have 20 seconds to react and try to get the bomb somewhere safe anyway so i think it would be funny

2024-01-04 19:31 UTC, lzk228 commented
Updated pr info.
Only left is to put them into uplink.

2024-01-04 19:50 UTC, Dutch-VanDerLinde commented
> Nat(max) -1: syndie bomb explosion Nat(max): singulo/tesla
> 
> Make dice available to clown too

clown already has so much job specific stuff and librarian gets nothing

2024-01-09 07:36 UTC, lzk228 commented
Ready for review!

2024-01-09 14:02 UTC, lzk228 commented
https://github.com/space-wizards/space-station-14/assets/124214523/222ac989-433d-4e12-a167-d4d4e3d0ee16

now on critical failure will be critical failure popup

2024-01-13 04:59 UTC, BreadyToad commented
> 2024-01-09_14-59-06.mp4 
> now on critical failure will be critical failure popup

Why 2 is considered a critical failure though? Isn't it supposed to be only a nat 1?

2024-01-13 05:00 UTC, K-Dynamic commented
For real the clown and mime should also get access to these since they're associated with toys too

2024-01-13 05:03 UTC, BreadyToad commented
> For real the clown and mime should also get access to these since they're associated with toys too

Clown and mime already have job specific items, plus dice are much more commonly associated with tabletop games which are much more structured and suited for the librarian than for chaotic duo (plus my boy librarian needs at least something unique to him)

2024-01-13 06:00 UTC, K-Dynamic commented
Offtopic but give the syndie librarian:
- bluespace book
- flying book enemy (will either bite or shoot laser)
- fake monkey cubes but in form of figures

2024-01-13 10:52 UTC, lzk228 commented
> > 2024-01-09_14-59-06.mp4
> > now on critical failure will be critical failure popup
> 
> Why 2 is considered a critical failure though? Isn't it supposed to be only a nat 1?

idk, i just coded and it become like this

2024-01-16 23:42 UTC, lzk228 commented
Updated PR info. Now will be big boom if 20 dropped.

2024-01-16 23:55 UTC, K-Dynamic commented
based

2024-01-17 11:09 UTC, TheShuEd requested changes
I like the unique content for the librarian, but I'm not sure if it makes sense to give that content to greytides in the same way

2024-01-17 11:09 UTC, TheShuEd commented on Content.Server/Dice/DiceSystem.cs
> +        if (die.DiceBomb && !TryComp<ExplodeOnTriggerComponent>(uid, out var explodeTrigger)) // True only on first roll, so cannot be activated twice
I think DiceBomb should be a separate system, not built into an existing DiceSystem. Just make the events you need and subscribe to them in a separate file.

2024-01-17 11:09 UTC, TheShuEd commented on Content.Shared/Dice/DiceComponent.cs
> +    [DataField("diceBomb")]
Also please, separate component

Dice roll logic and explosive dice logic should not be mixed in the same component and system, as they do completely different things.

2024-01-17 21:17 UTC, lzk228 commented
@TheShuEd ive tried and i cant do it separate system and component.
if i do it in server it cant use events
if i do it in shared it cannot change explosion component because its in server

2024-01-17 22:58 UTC, TheShuEd commented
Hmm, then I suggest waiting for more experienced programmers to review

2024-03-04 03:00 UTC, AJCM-git commented
I really like this idea for traitor librarians but will close since the requested changes couldn't be fulfilled, feel free to reopen if you find a way.

2024-03-04 03:00 UTC, closed without merging

2024-03-04 06:39 UTC, lzk228 commented
@AJCM-git i already answered to review and i think someone of expeirenced coders should make other review

2024-03-04 13:11 UTC, AJCM-git commented
> @AJCM-git i already answered to review and i think someone of expeirenced coders should make other review

I mean if you end up finding someone to help you out then you can reopen no problem

2024-03-04 13:32 UTC, Mangohydra commented
rolling a 1 should stun you for 7 seconds (same as the omega soap)