Refinement of mercenary items
space-wizards/space-station-14 pull request #23616
Opened 2024-01-06 12:41 UTC by Jackal298

## About the PR

The sprites have been changed and the mercenary's backpack and overalls have been modified.
The mercenary's overalls now have sencers
The mercenary's backpack has become a little more spacious; according to its characteristics, it is slightly better than a regular backpack in terms of capacity, but it will lose to item bags
## Why / Balance

## Technical details

## Media

![Ячейки](https://github.com/space-wizards/space-station-14/assets/129199891/5494c59b-7851-4730-af5a-0030b5384b8d)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-01-06 12:48 UTC, UbaserB commented
I liked the old stripe on the top for the gloves

2024-01-06 12:56 UTC, Jackal298 commented
> I liked the old stripe on the top for the gloves

I wanted to make fingerless gloves and combat gloves similar to each other, when crafting fingerless gloves using combat gloves, it looked strange from a design point of view

2024-01-07 01:57 UTC, Jezithyr requested changes

2024-01-07 01:57 UTC, Jezithyr commented on Resources/Textures/Clothing/Hands/Gloves/mercfingerless.rsi/icon.png
Fingerless gloves should have a different sprite from the battle gloves (that have fingers)

2024-01-07 05:33 UTC, Jackal298 commented on Resources/Textures/Clothing/Hands/Gloves/mercfingerless.rsi/icon.png
> Fingerless gloves should have a different sprite from the battle gloves (that have fingers)

The sprites of fingerless gloves are cut off as is the case with regular black and fingerless gloves, I checked and there are finger pixels there

2024-01-07 05:35 UTC, Jackal298 commented on Resources/Textures/Clothing/Hands/Gloves/mercfingerless.rsi/icon.png
> Fingerless gloves should have a different sprite from the battle gloves (that have fingers)

I made them similar so that when converting combat gloves into fingerless ones they would have the same design

2024-01-07 06:09 UTC, Jackal298 commented on Resources/Textures/Clothing/Hands/Gloves/mercfingerless.rsi/icon.png
> Fingerless gloves should have a different sprite from the battle gloves (that have fingers)

![Untitled 12-25-2023 04-12-48 рпр](https://github.com/space-wizards/space-station-14/assets/129199891/50b1721f-6961-47d0-b4a5-0f3a821ddbb4)

This is what the fingerless gloves look like on the player model sprite

2024-01-07 07:43 UTC, Jackal298 commented on Resources/Textures/Clothing/Hands/Gloves/mercfingerless.rsi/icon.png
> Fingerless gloves should have a different sprite from the battle gloves (that have fingers)

The fingerless gloves sprite icon is also cut off and it is different from combat gloves

2024-01-08 20:33 UTC, Jackal298 commented
![image](https://github.com/space-wizards/space-station-14/assets/129199891/e237219d-3f3f-4862-ba56-eed289ae861e)

2024-01-09 00:36 UTC, LankLTE requested changes
The mercenary bag should not just have more storage than a normal bag, as that just encourages people to learn where they’re mapped and hunt them out roundstart for stronger gear. It should share stats with the normal backpack or duffel bag.

2024-01-09 05:58 UTC, Jackal298 commented
> The mercenary bag should not just have more storage than a normal bag, as that just encourages people to learn where they’re mapped and hunt them out roundstart for stronger gear. It should share stats with the normal backpack or duffel bag.

![Размер](https://github.com/space-wizards/space-station-14/assets/129199891/d15081a9-2279-49da-ab7a-85f56ca75d05)

Left duffel bag, Right Merc backpack

2024-01-09 09:34 UTC, Jackal298 commented
> The mercenary bag should not just have more storage than a normal bag, as that just encourages people to learn where they’re mapped and hunt them out roundstart for stronger gear. It should share stats with the normal backpack or duffel bag.

Now, in terms of capacity, this is a regular backpack,

2024-01-09 09:57 UTC, Jackal298 commented
Please know, I realized that my work was drowned in other PRs and since they just didn’t answer my question, I will close this PR and do everything right so that my work is properly merged

2024-01-09 09:57 UTC, closed without merging