Better whitelists
space-wizards/space-station-14 pull request #23985
Opened 2024-01-12 20:52 UTC by Simyon264

## About the PR

Adds a way for easier whitelists. 
## Why / Balance

Resolves #19606.
## Technical details

TBD
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
TBD
## Breaking changes

TBD

2024-01-16 12:04 UTC, Simyon264 commented on Content.Server.Database/Model.cs
> +    }
I am still a bit unsure... What do you exactly mean with "generic user lists"?

2024-02-01 11:33 UTC, metalgearsloth commented
@Simyon264 you working on this famalams.

2024-02-01 18:26 UTC, Simyon264 commented
Yes. I am still working on it.

2024-03-02 23:52 UTC, Simyon264 commented
FYI, I am still working on it.

2024-03-18 04:34 UTC, PJB3005 requested changes

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server.Database/Model.cs
> +    public class Blacklist
Doc comment explain what this table means.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/WhitelistPrototype.cs
> +public sealed class PlayerConnectionWhitelistPrototype : IPrototype
I need a doc comment explaining what these prototypes are and what they are used for (e.g. reference to CVar).

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/WhitelistCondition.cs
> +public abstract partial class WhitelistCondition
I need a doc comment explaining what these conditions are and how they are used (reference to prototype).

2024-03-18 04:34 UTC, PJB3005 commented on Resources/Prototypes/whitelists.yml
> +﻿- type: PlayerConnectionWhitelist
Separate the MRP template into another file and rename it so that it's clear that it's wizden-specific policy that downstreams may not want to use.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                foreach (var whitelistString in whitelistStringList.Split(','))
Do all this string splitting and figuring out the prototypes ahead of time with an OnValueChanged.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                        _sawmill.Warning($"Whitelist prototype {whitelistString} does not exist.");
This should be an error, not a warning.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                        continue;
You should block connecting entirely due to misconfiguration if this error occurs, as a configuration error may open a security hole in the server.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                    var whitelist = whitelists.FirstOrDefault(w => w.ID == whitelistString);
Don't do this. Just use `IPrototypeManager.Index<>`

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/WhitelistPrototype.cs
> +    public static async Task<(bool isWhitelisted, string? denyMessage)> IsWhitelisted(this PlayerConnectionWhitelistPrototype prototype, NetUserData data, ISawmill sawmill)
Why is all this logic implemented as an extension method instead of in the only system that calls this?

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/BlacklistCommands.cs
> +        var loc = IoCManager.Resolve<IPlayerLocator>();
Pull these dependencies in via `[Dependency]`.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/BlacklistCommands.cs
> +        var name = string.Join(' ', args).Trim();
Do not do this. Raise an error if more than one argument was provided.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/Conditions/ConditionAlwaysDeny.cs
> +public sealed partial class ConditionAlwaysDeny : WhitelistCondition
I need doc comments for all of these.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/BlacklistCommands.cs
> +        if (data != null)
Swap this if around for an early return.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Shared/CCVar/CCVars.cs
> +        public static readonly CVarDef<string> WhitelistPrototype =
This CVar is named incorrectly. If it's `whitelist.prototypeList`, it should be `WhitelistPrototypeList`.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("whitelist.prototypeList", "basicWhitelist", CVar.SERVERONLY);
```suggestion
            CVarDef.Create("whitelist.prototype_list", "basicWhitelist", CVar.SERVERONLY);
```

CVar naming convention is pascal case

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/BlacklistCommands.cs
> +        var loc = IoCManager.Resolve<IPlayerLocator>();
Pull these dependencies in via `[Dependency]`.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/BlacklistCommands.cs
> +        var name = string.Join(' ', args).Trim();
Do not do this. Raise an error if more than one argument was provided.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/Conditions/ConditionManualWhitelist.cs
> +        var db = IoCManager.Resolve<IServerDbManager>();
Do not pull in `IServerDbManager` via `IoCManager`. Move all the testing logic over to `ConnectionManager` to get rid of this OOP crap.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/Conditions/ConditionNotes.cs
> +            var note = await db.GetAdminNote(remark.Id);
This is incredibly slow. Hell this code isn't even correct? Why aren't you just using the note information returned by `GetAllAdminRemarks`?

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/WhitelistCondition.cs
> +    public abstract Task<(bool sucess, string denyReason)> Condition(NetUserData data);
It's `success`, not `sucess`.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/WhitelistPrototype.cs
> +                sawmill.Debug($"User {data.UserName} passed whitelist condition {condition.GetType().Name}");
These logs should be `Verbose`, not `Debug`.

2024-03-18 04:34 UTC, PJB3005 commented on Resources/Prototypes/whitelists.yml
> +      range: 14 # 14 Days
You are going to need a way to be able to re-use the notes when evaluating these 3 conditions. You're not getting away with calling `GetAllAdminRemarks` **three** times per connection attempt.

2024-03-18 04:34 UTC, PJB3005 commented on Content.Server.Database/Model.cs
> +    }
Nah this is fine for now.

2024-03-18 04:35 UTC, PJB3005 commented on Content.Server/Connection/Whitelist/Conditions/ConditionNotes.cs
> +        var remarks = await db.GetAllAdminRemarks(data.UserId.UserId);
Yes, this includes role and server bans.

2024-06-07 20:42 UTC, PJB3005 requested changes

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                if (allWhitelists.FirstOrDefault(p => p.ID == id) is { } prototype)
Do not do this. Use `prototypeManager.TryIndex()` to retrieve the prototype by ID.

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                    _whitelists = Array.Empty<PlayerConnectionWhitelistPrototype>();
You are still causing the whitelist system to fail closed (people can connect) on misconfiguration. This should not be a thing.

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                switch (condition.GetType())
You can just type switch on the object directly instead of using `GetType()`.

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                    case { } t when t == typeof(ConditionNotesDateRange):
These complex objects need to be handled in their own separate functions.

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +        private async Task<List<IAdminRemarksRecord>> GetAdminRemarks(NetUserId userId)
You are never cleaning out this cache. It should be an object that is allocated in `IsWhitelisted` and not stored on the manager itself.

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +        public async Task<(bool isWhitelisted, string? denyMessage)> IsWhitelisted(PlayerConnectionWhitelistPrototype whitelist, NetUserData data, ISawmill sawmill)
This code is large enough to warrant pulling out into a partial.

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                        remarks = remarks.Where(x => x.CreatedAt > DateTime.Now.AddDays(-conditionNotes.Range)).ToList();
This isn't a major deal to me, but it's always poor form to run `DateTime.Now` in a loop like this as you'll have to re-fetch the system time every loop. And subtract the date range too.

Also do this with UTC instead. I'm not sure it matters but it cannot hurt to be sure.

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                        }
Half this logic is LINQ, the other half isn't. Why can't you just put it all in a single loop with various `continue` blocks for filtering?

You also do not need to bother with the `remarksCopy.Remove()` stuff, if you organize the code well then you can just have a match break the loop with `matched = true;` at the end of it.

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                        var overallPlaytime = await _db.GetPlayTimes(data.UserId);
You need to cache this DB result.

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                        var playtime = await _db.GetPlayTimes(data.UserId);
You need to cache this DB result.

2024-06-07 20:42 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +                        }
Same concerns with this code being half LINQ half not. Also isn't this copy pasted?

2024-07-06 10:24 UTC, Simyon264 commented
> A long term goal would be to allow arbitrary lists to be made so that servers can create as many manual lists as they want for whatever purpose they have, potentially even using those lists for other things unrelated to connections. Having conditions work as being list membership now will prevent having to make changes in the future that either break YAML configs or require workarounds.

Something like this? @Chief-Engineer 
```yaml
  - !type:ConditionMembership
    list: whitelist # Which list the player needs to be a part of
    requiredMembershipTime: 120 # Must be a member for 2 hours
    action: Allow
  - !type:ConditionAlwaysMatch
    action: Deny # Not a member, deny connection
```

2024-08-27 15:24 UTC, PJB3005 reviewed
I'll fix these issues myself real quick.

2024-08-27 15:24 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.Whitelist.cs
> +        Dictionary<NetUserId, List<PlayTime>> cachePlaytime = new();
Why are you storing this keyed on user ID if this function only runs for a single user at once?

2024-08-27 15:24 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.Whitelist.cs
> +    private async Task<bool> CheckConditionNotesDateRange(ConditionNotesDateRange conditionNotes, List<IAdminRemarksRecord> remarks)
These don't need to be async

2024-08-27 15:24 UTC, PJB3005 commented on Content.Server/Connection/ConnectionManager.cs
> +            }
Screwed up merge xd

2024-08-27 15:32 UTC, PJB3005 approved these changes

2024-08-27 16:01 UTC, merged