decelerator nerf and projectile fix
space-wizards/space-station-14 pull request #24032
Opened 2024-01-13 16:03 UTC by Arendian

## About the PR

resolves #23956 
Nerfs the particle decelerator's projectile damage and lifetime, it now also belongs to the "Energy" type and can be reflected by reflective entities.

Fixes some projectile collision stuff that made it so bullet grenade projectiles were able to penetrate walls.
The reason this is in this PR is because the decelerator projectile had a component value that it shouldn't have, because I named it wrongly when I added it with the bullet grenades.

## Why / Balance

The damage was way too high for tool that isn't even supposed to be a weapon, that shoots wall penetrating projectiles with a range of around 75 tiles.
Damage lowered from 25 to 10 and projectile lifetime reduced from 3 to 0.6 seconds, the lowered lifetime should still allow it to be used on singularities, because it's still a range of around 15 tiles.
The projectile has been made reflective so energy shields and swords can reflect it.

## Technical details

Added a new component value that decides if a projectile is able to deal damage after colliding.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The particle decelerator's projectile now deals less damage and can be reflected by objects that reflect energy projectiles.
- fix: Bullet grenade projectiles no longer penetrate walls.

2024-01-13 17:20 UTC, TheShuEd commented on Content.Shared/Projectiles/ProjectileComponent.cs
>      public string? ImpactEffect;
You can also change string to EntProtoId to fit the modern format

2024-01-13 17:20 UTC, TheShuEd commented on Content.Shared/Projectiles/ProjectileComponent.cs
> +    [DataField] public SoundSpecifier? SoundHit;
please use line breaks so that the entire file is in the same style

2024-01-14 05:22 UTC, metalgearsloth requested changes

2024-01-14 05:22 UTC, metalgearsloth commented on Content.Shared/Projectiles/ProjectileComponent.cs
> +
This shouldn't be on projectilecomponent, use collision layers or absolute worst case another component if you want this behaviour as projectilecomponent doesn't need to become a god component.

2024-01-14 05:22 UTC, metalgearsloth commented on Content.Shared/Projectiles/ProjectileComponent.cs
> +    public bool DamageAfterCollide = false;
Same here.

2024-01-14 05:23 UTC, metalgearsloth commented on Content.Server/Projectiles/ProjectileSystem.cs
>          }
This control flow is also messy and shouldn't be on projectilecomponent as it's bloating it too much.

2024-01-14 21:42 UTC, Arendian commented
I moved the check for projectiles penetrating to an event and made a new CanPenetrateComponent.

2024-01-14 23:38 UTC, mirrorcult approved these changes

2024-01-14 23:39 UTC, merged