Medical glasses
space-wizards/space-station-14 pull request #24101
Opened 2024-01-15 06:30 UTC by DenisShvalov

## About the PR
Added medical glasses - medical hud in form of glasses

## Why / Balance
I like glasses
Also, added medical hud and glasses craft in medical techfab

## Media

https://github.com/space-wizards/space-station-14/assets/115770678/447c1e18-4849-48f2-b2eb-b7e390d5e673

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![image](https://github.com/space-wizards/space-station-14/assets/115770678/ebe0ab44-2f1f-4be0-8bb4-86e210569647)

**Changelog**

:cl:
- add: Medical glasses - another form of medical hud
- tweak: Added medical glasses and hud recipe in medical techfab

2024-01-15 06:33 UTC, EmoGarbage404 commented
ngl leading with the reskin and not with the fact that you're adding recipes to the techfab is a mood

2024-01-15 07:50 UTC, TheShuEd requested changes

2024-01-15 07:50 UTC, TheShuEd commented on Resources/Prototypes/Recipes/Lathes/medical.yml
> +    Steel: 400
if it's just a reskin they should have the same material cost

2024-01-15 07:50 UTC, TheShuEd commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +  - type: ShowHealthIcons
just inherit from the existing medical visor, and don't add duplicate components

2024-01-15 10:15 UTC, TheShuEd commented
I'm still not sure if we need to add resprites to techfab.  therefore not an approval, but simply a cancellation of the request

2024-01-17 11:26 UTC, TheShuEd commented
how about this suggestion. Make these glasses look expensive and make them a one-of-a-kind in a medical vending machine. Also add them to the thief's stealing tasks, he has just a shortage of unique items to steal in the science and medical departments.

2024-03-04 02:09 UTC, AJCM-git commented
Re-skins like this shouldnt be added without lathes properly handling them (the ui should have a submenu or something to change the sprite to an alternative and have the same recipe or something), if you or someone ends up doing that feel free to reopen

2024-03-04 02:09 UTC, closed without merging