Add a way for bulk abstracting prototypes
space-wizards/space-station-14 pull request #24140
Opened 2024-01-16 01:58 UTC by EmoGarbage404

## About the PR

Adds a new file, ignoredPrototypes.yml
Files and directories in this file will be read and have all of their contained prototypes be made abstract.

This is a very simple way for servers to bulk exclude prototypes they don't want (clothes, construction recipes, etc) while creating minimal conflicts by minimizing the amount of places that have to be modified. Instead of getting conflicts for a bunch of different clothing items when you remove them, you can only remove the places they appear and sidestep other issues. This also allows maps to be easily ignored for tests while not having to deal with resolving conflicts that may arise from deleting the file itself.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

no cl no fun

2024-01-16 02:33 UTC, metalgearsloth requested changes

2024-01-16 02:33 UTC, metalgearsloth commented on Content.Shared/Entry/EntryPoint.cs
> +        private const string IgnoreFile = "/ignoredPrototypes.yml";
ResPath.

2024-01-16 07:55 UTC, metalgearsloth approved these changes

2024-01-16 08:24 UTC, DrSmugleaf approved these changes
It feels like this should probably support multiple files or at least have the one file be settable through a CVar, but I suppose that is only a problem for downstreams of downstreams.

2024-01-16 12:31 UTC, EmoGarbage404 commented
If i were to add multi-file support, how would you like it to be done? Just a readonly list in Entry Point?

2024-01-16 20:21 UTC, DrSmugleaf commented
> If i were to add multi-file support, how would you like it to be done? Just a readonly list in Entry Point?

Could do any .yml files in a directory like the changelog does

2024-01-17 04:53 UTC, EmoGarbage404 commented
@DrSmugleaf added and tested multi-file support. Now, any file inside of the IgnoredPrototypes directory will be read, rather than just a single file.

2024-01-17 05:39 UTC, mirrorcult approved these changes

2024-01-17 05:39 UTC, merged