Add more variety to vendor thank you and advertisement messages
space-wizards/space-station-14 pull request #24219
Opened 2024-01-18 08:09 UTC by UbaserB

## About the PR

Partially fixes #23803 by adding more thank you messages, however i have not added any new thank you messages to vendors that don't already have unique messages.

2024-01-18 16:01 UTC, FairlySadPanda reviewed
Did a quick SPAG pass (spelling/punctuation/grammar) and caught a few things. Avoided rewording anything except in two instances where the sentence was a bit unclear

2024-01-19 03:00 UTC, UbaserB commented
> FYI, you worded the comment of PR using "[...] resolves #issuenumber" and github doesn't care that there was a "partially" preceding that. It will automatically mark that issue as resolved upon merging this PR.
> 
> Not sure if that was desired or not, since "partially resolves ≠ resolves". Just pointing it out.

im gonna rename resolves then

2024-01-19 03:12 UTC, UbaserB commented
Fixed.

2024-01-19 04:27 UTC, Partmedia requested changes
Thanks for your contribution. Please take a look at the review comments and avoid changing so much indentation.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Locale/en-US/advertisements/vending/coffee.ftl
> +advertisement-coffee-14 = Hot beverages! come get yours now!
Capitalization

2024-01-19 04:27 UTC, Partmedia commented on Resources/Locale/en-US/advertisements/vending/games.ftl
> +advertisement-goodcleanfun-9 = Fun times forever!
You can swap 8 and 9 to reduce the diff and make it easier for translators.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/ammo.yml
It is not necessary to re-indent everything.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/boozeomat.yml
It is not necessary to re-indent everything.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/cigs.yml
It is not necessary to re-indent everything.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/clothesmate.yml
It is not necessary to re-indent everything.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/cola.yml
It is not necessary to re-indent everything.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/curadrobe.yml
It is not necessary to re-indent everything.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/discount.yml
It is not necessary to re-indent everything.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/games.yml
It is not necessary to re-indent everything.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/happyhonk.yml
It is not necessary to re-indent everything.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/magivend.yml
It is not necessary to re-indent everything.

2024-01-19 04:27 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/smartfridge.yml
It is not necessary to re-indent everything.

2024-01-19 04:46 UTC, UbaserB commented
Review addressed.

2024-01-21 14:06 UTC, Partmedia requested changes
There's still some unnecessary re-indentation. You can see these yourself by inspecting the diff.

2024-01-21 14:06 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/condiments.yml
Unnecessary re-indentation

2024-01-21 14:06 UTC, Partmedia commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/curadrobe.yml
Unnecessary re-indentation

2024-01-21 14:56 UTC, UbaserB commented
> There's still some unnecessary re-indentation. You can see these yourself by inspecting the diff.

ohhhh yeah i kind of forgot lol let me fix them all up

2024-01-27 04:23 UTC, UbaserB commented
I made sure to triple check it this time so it should be all good

2024-01-27 06:46 UTC, Partmedia approved these changes

2024-01-27 06:46 UTC, merged

2024-01-27 06:46 UTC, Partmedia commented
Thank you for your contribution!