add support clothing equip/unequip doafters
space-wizards/space-station-14 pull request #24389
Opened 2024-01-22 02:03 UTC by EmoGarbage404

## About the PR

not for upstream, just a nice balance stick that people talk about a lot

## Media

https://github.com/space-wizards/space-station-14/assets/98561806/09d73c02-04db-495b-952a-ef26bd8f741c

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

2024-01-22 02:06 UTC, metalgearsloth requested changes

2024-01-22 02:06 UTC, metalgearsloth commented on Content.Shared/Inventory/InventorySystem.Equip.cs
> +                _doAfter.TryStartDoAfter(args);
I thought starting do_afters in prediction was supported.

2024-01-22 02:06 UTC, metalgearsloth commented on Content.Shared/Inventory/InventorySystem.Equip.cs
> +        {
HasFlag allocates and sucks, use bitmask check.

2024-01-22 02:06 UTC, metalgearsloth commented on Content.Shared/Inventory/InventorySystem.Equip.cs
> +
As above.

2024-01-22 02:15 UTC, UbaserB commented
i know you said not for upstream... but can you make it upstream?

2024-01-22 02:33 UTC, EmoGarbage404 commented
> i know you said not for upstream... but can you make it upstream?

someone is free to add it but uhh. i'm not fighting that fight today.

2024-01-22 02:34 UTC, Emisse commented
bout to add hardsuit equip doafter and have someone physically show up at my house this time

2024-01-28 10:48 UTC, metalgearsloth approved these changes

2024-01-28 10:48 UTC, merged