Fix aHelp relay to detect AFK Admins
space-wizards/space-station-14 pull request #24482
Opened 2024-01-24 09:44 UTC by Titian3

## About the PR
Gave Admins a separate 5min AFK timer and if someone send an aHelp and they are AFK it will send in the relay as a SOS instead of looking like the admin has seen it. Thank you @nikthechampiongr for this better idea than to kick everyone 😄

## Why / Balance
I have made this be cause I went AFK for several rounds and a bunch of aHelps were missed but to the relay they looked ok.

## Technical details
Add admin detection condition to the afk detection and update the bwoink system discord relay message to take in to account if the admin is AFK or not.

## Media
Admin online/Not AFK
![image](https://github.com/space-wizards/space-station-14/assets/47093363/d1101f1f-07d2-4d61-acd2-2c4c923fbc2d)

Admin online/AFK detected
![image](https://github.com/space-wizards/space-station-14/assets/47093363/cebfa6ba-6c96-4b03-961f-04a1af7cf143)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
NA

**Changelog**

:cl: Repo
- tweak: AFK admins will trigger the SOS in aHelp relay.

2024-01-24 09:45 UTC, Titian3 commented
If someone could tell me how to make this only show on the admin changelog you will get 100 points.

2024-01-24 09:55 UTC, Pangogie commented
Should do 10min. We do a lot of AFKing sometimes until we hear the bwoink.

2024-01-24 09:55 UTC, Pangogie commented
I hit the wrong button. :)

2024-01-24 10:57 UTC, nikthechampiongr commented
> If someone could tell me how to make this only show on the admin changelog you will get 100 points.

I would like my 100 points please.

🆑 Repo

ADMIN:
- tweak: AFK admins will trigger the SOS in aHelp relay.

2024-01-24 11:01 UTC, Titian3 commented
> I hit the wrong button. :)

10min now.

2024-01-24 11:03 UTC, nikthechampiongr commented
@Titian3 Looking at the usages of GetTargetAdmins, it is also used to notify online admins for new ahelps. Did you test what afk admins see or hear when an ahelp is made while they are afk? A lot of admins have the game minimized and wait for the bwoink sound.

2024-01-24 11:14 UTC, nikthechampiongr requested changes
The changes to the GetTargetAdmins function make all ahelps completely invisible to afk admins. Maybe you should have a separate function for this?

2024-01-24 11:24 UTC, Titian3 commented
> The changes to the GetTargetAdmins function make all ahelps completely invisible to afk admins. Maybe you should have a separate function for this?

Yes you are right, when I first tested it, I think I saw the red aHelp from the first message, making the new function and testing now. 
🙏Thank you! 200 points have been deposited in your account!

2024-01-24 11:34 UTC, Titian3 commented
> The changes to the GetTargetAdmins function make all ahelps completely invisible to afk admins. Maybe you should have a separate function for this?

Re-tested, all looks working right now.

![image](https://github.com/space-wizards/space-station-14/assets/47093363/523cf53e-1e0f-4bc2-9c02-1038c8a64022)

![image](https://github.com/space-wizards/space-station-14/assets/47093363/ee8e6d2f-2fbc-4302-a176-71f70bb593e7)

![image](https://github.com/space-wizards/space-station-14/assets/47093363/53e5cf02-912c-47a4-bda9-e452a2a69065)

2024-01-24 12:22 UTC, nikthechampiongr requested changes
The GetTargetAdmins function is still used for determining the color of the message in discord. This means that it will appear green but the messages of the player will have SOS next to them. Are you sure this is intended?

2024-01-24 12:34 UTC, nikthechampiongr approved these changes
Looks good to me. Although the list with the active admins is never used and all the points where the function is called it just grabs the number of things in the list. I don't think that's an issue tho. Good luck with the actual maintainers.

2024-02-01 13:03 UTC, metalgearsloth commented on Content.Shared/CCVar/CCVars.cs
> +        /// How long a admin client can go without any input before being considered AFK.
```suggestion
        /// How long an admin client can go without any input before being considered AFK.
```

2024-02-01 13:03 UTC, merged