New uplink item - Secret Storage Crate.
space-wizards/space-station-14 pull request #24667
Opened 2024-01-28 15:54 UTC by marboww

## About the PR
This PR adds a stealth box-like crate to the uplink in the Utilities category.

## Why / Balance
This innovation in the game will perfectly allow traitors to conveniently hide their things in an invisible crate (or hide in case of danger) for 2 TK. However, it will not replace the stealth box; The syndicate's symbols attract too many eyes.

## Technical details
PR takes the syndicate box as a base and adds two stealth-related components to it.

## Media

https://github.com/space-wizards/space-station-14/assets/152051971/1fcc6eca-6b27-4410-80ab-be648272e830

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### P.S

I am sorry for my English

**Changelog**

- tweak: Price change (from 4 to 2 TC)

2024-01-28 16:35 UTC, icekot8 commented
I don't see the point. You can just as easily use a stealth box, but it's 1 TC more expensive, and the box lets entities through while the secret crate doesn't.
I don't find your arguments convincing.

2024-01-28 16:39 UTC, Lomovar commented
make it foldable :trollface:

2024-01-28 17:07 UTC, marboww commented
> I don't see the point. You can just as easily use a stealth box, but it's 1 TC more expensive, and the box lets entities through while the secret crate doesn't. I don't find your arguments convincing.

In such cases, I can do it cheaper, for example the same 2 TC. Because crates have many disadvantages: syndicate symbolism, etc.  Well, this is my first PR, there are also some mistakes.

2024-01-28 21:03 UTC, deltanedas commented
storage implant is 1 more tc and has no non meta counters

2024-01-29 01:43 UTC, marboww commented
ok I'll change the price now

2024-01-29 02:34 UTC, marboww commented
> I don't see the point. You can just as easily use a stealth box, but it's 1 TC more expensive, and the box lets entities through while the secret crate doesn't. I don't find your arguments convincing.

2024-01-29 02:36 UTC, marboww commented
oh damn what have I done...

2024-01-29 04:05 UTC, metalgearsloth commented
I don't think this fits, there should be a risk to traitors storing their stuff in maints and this bypasses most of it with an expensive shader.

2024-01-29 04:11 UTC, deltanedas commented
no risk just hide it all in toilets

2024-01-29 04:20 UTC, marboww commented
> I don't think this fits, there should be a risk to traitors storing their stuff in maints and this bypasses most of it with an expensive shader.

There is still a risk. A person can simply stumble upon an invisible space that does not allow him to pass, and he can calmly open it, call security or scientists.

2024-01-29 04:23 UTC, marboww commented
you spend your TK if you want to hide something with a slightly increased chance that it won’t be found, and for only a small price.

2024-01-29 07:02 UTC, lzk228 requested changes
change id to something nore obvious, like `CrateSyndicateStealth`
also since this, i dont think it needs new name and desc, so just add `suffix: Stealth`

2024-01-29 07:02 UTC, lzk228 commented on Resources/Prototypes/Catalog/Fills/Crates/syndicate.yml
> +
move just to crates, not filled versions

2024-01-29 07:47 UTC, marboww commented
> change id to something nore obvious, like `CrateSyndicateStealth`
> also since this, i dont think it needs new name and desc, so just add `suffix: Stealth`

ok

2024-01-29 08:34 UTC, marboww commented
hmm, I forgot about the thief, I’d better close PR

2024-01-29 08:34 UTC, closed without merging