Chameleon PDA's
space-wizards/space-station-14 pull request #24786
Opened 2024-01-31 22:44 UTC by Rainfey

## About the PR
Added a chameleon PDA to the chameleon kit

## Why / Balance
Last major equippable item that was missing from the chameleon kit

## Technical details
Required adding a handler for PDA's snowflake method of storing their appearance (field on the PDAComponent)

## Media
![Screenshot 2024-01-30 165959](https://github.com/space-wizards/space-station-14/assets/11758391/f33a4acd-c64b-453b-a5e4-b7f41c0231de)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Due to ID cards and PDA's sharing a slot, the chameleon feature on Agent ID cards had to be removed.
Otherwise you could chameleon a PDA to look like an ID card, and vice versa.

![Screenshot 2024-01-30 144021](https://github.com/space-wizards/space-station-14/assets/11758391/10393636-339f-4166-a6a8-3c4c09fb750f)

**Changelog**
:cl:
- add: Chameleon PDA
- remove: Chameleon Agent ID Card

2024-02-01 00:16 UTC, potato1234x commented
the agent id chameleon should probably be fixed instead of removed, knowing the maintainers they probably wont merge until fixed

2024-02-01 13:44 UTC, Rainfey commented
Well i wanted to avoid it - but i would also prefer having both chameleon ID and PDA.
Drafting until i rewrite things to support that.
Probably going to add an EntityWhitelist to each chameleon item.

2024-03-14 22:52 UTC, metalgearsloth requested changes

2024-03-14 22:52 UTC, metalgearsloth commented on Content.Client/Clothing/Systems/ChameleonClothingSystem.cs
> +            prototype = Proto.Index(component.Default.Value);
TryIndex

2024-03-14 22:52 UTC, metalgearsloth commented on Content.Shared/Clothing/Components/ChameleonClothingComponent.cs
> +    public ChameleonBoundUserInterfaceState(SlotFlags slot, EntProtoId? selectedId, EntityWhitelist? whitelist)
You can just network it in the component and not need it in the BUI state at all.

2024-03-14 22:52 UTC, metalgearsloth commented on Content.Shared/Clothing/EntitySystems/SharedChameleonClothingSystem.cs
> +
TryIndex

2024-03-14 22:52 UTC, metalgearsloth commented on Content.Shared/PDA/SharedPdaSystem.cs
> +
This looks unused and it's also undocumented.

2024-03-14 22:52 UTC, metalgearsloth commented on Content.Shared/Clothing/EntitySystems/SharedChameleonClothingSystem.cs
> +
Why not valuelist if you're just going to return a slow ienumerable anyway?

2024-03-14 22:52 UTC, metalgearsloth commented on Content.Shared/Whitelist/EntityWhitelist.cs
> +        {
You never use the factory.

2024-05-10 15:50 UTC, Emisse commented
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

2024-05-10 15:50 UTC, closed without merging