Drag changes
space-wizards/space-station-14 pull request #2487
Opened 2020-11-03 09:56 UTC by metalgearsloth

* Higlights only show near cursor which seems nicer than highlighting the whole screen.
* Don't highlight un-droppable entities.
* Disables interaction outlines while dragging so they're not overlaying over each other.
* Fixes https://github.com/space-wizards/space-station-14/issues/2311

I moved a bunch of stuff to shared so the client has a better if when a drag's valid. It won't be 100% perfect as not all of it's predicted but it should fix the range issues.

2021-01-05 09:40 UTC, metalgearsloth commented
Should be good for a review again

2021-01-07 00:01 UTC, metalgearsloth commented
Merging in a week if no objections

2021-01-09 11:14 UTC, PaulRitter requested changes
only looked at this in the web reviewer, didn't checkout code locally

2021-01-09 11:14 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Disposal/DisposalUnitComponent.cs
>          public bool CanInsert(IEntity entity)
```suggestion
        public override bool CanInsert(IEntity entity)
```

2021-01-09 11:14 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Disposal/DisposalUnitComponent.cs
> +using Content.Shared.GameObjects.Components.Disposal;
```suggestion
using Content.Shared.GameObjects.Components.Disposal;
```
duplicate

2021-01-11 11:14 UTC, merged