Fix pressing shift while held triggering escape
space-wizards/space-station-14 pull request #24878
Opened 2024-02-02 21:37 UTC by Tayrtahn

## About the PR

Pressing shift while being held (as a small mob) will no longer cause you to attempt to escape from the person holding you.

## Why / Balance

Fixes #24847

## Technical details

Same bug as #22998 and #24387, and the same fix.
If this shows up again, I swear I'll actually bother to make a helper method.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: You can now press shift while being held as a small mob without accidentally trying to escape.

2024-02-02 23:28 UTC, Tayrtahn commented
Yeah, I've wondered about that too.

And CL removed.

2024-02-03 00:52 UTC, metalgearsloth requested changes

2024-02-03 00:52 UTC, metalgearsloth commented on Content.Server/Resist/EscapeInventorySystem.cs
> +
Just add a bool property on moveinputevent as this point and return this.

2024-02-03 02:14 UTC, metalgearsloth approved these changes

2024-02-03 02:14 UTC, merged