Reintroduce starvation damage with a cap.
space-wizards/space-station-14 pull request #24929
Opened 2024-02-03 22:54 UTC by dffdff2423

## About the PR

Re-add starvation damage, but with a capped value. 

## Why / Balance

Many players just ignore eating with the removal of starvation damage. Starvation damage will force players to start eating because it will be far more noticeable. This re-adds it, while not murdering SSD players.

## Technical details

Add a new field to the Hunger component that contains maximum values for damage. Then, only apply damage if the current damage is less than the cap. 

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: aquif
- tweak: Re-add starvation damage. Starvation damage now has a cap that cannot be exceeded.

2024-02-04 00:04 UTC, Golinth commented
starvation causing a massive slowdown is already punishment enough, why do we need damage on top of that?

2024-02-04 00:55 UTC, K-Dynamic commented
Starving should make chems metabolise slower instead of dealing damage :trollface:

2024-02-04 03:06 UTC, dffdff2423 commented
> starvation causing a massive slowdown is already punishment enough, why do we need damage on top of that?

The slowdown is not really enough. If you are playing anything other than security/antag the slowdown is not that big of a deal.

2024-02-04 03:07 UTC, dffdff2423 commented
> Starving should make chems metabolise slower instead of dealing damage :trollface:

The reason why I went with damage is because it provides something that is an obvious issue that the player needs to deal with. In addition, making chems metabolise slower would make medical really annoying to play.

2024-02-04 13:24 UTC, JoeTheJanitor commented
> Starving should make chems metabolise slower instead of dealing damage :trollface:

Me calmly walking to medical after getting hypo’d with lexorin because i didnt eat for a while

2024-02-04 20:34 UTC, EmoGarbage404 requested changes
I think this PR fails to address some key concerns regarding hunger balancing.
1) vomiting drains hunger far too quickly
2) regaining hunger is slow and unresponsive. many food items seem underwhelming in terms of hunger restoration
3) Hunger thresholds are generally too wide, making it difficult to exit the lowest threshold if you've completely exhausted your stomach.

2024-02-04 21:06 UTC, dffdff2423 commented
> 1. vomiting drains hunger far too quickly
I agree that is probably the case. Do you think that a number change would suffice (I would say 1/2 the values they currently are)?

> 2. regaining hunger is slow and unresponsive. many food items seem underwhelming in terms of hunger restoration

I would disagree that food tends to seem underwhelming.  Most of the time they work exactly how I would expect them to work. 

What we could do to make them more responsive is delay starvation damage by a few seconds every time Hunger is increased.

> 3. Hunger thresholds are generally too wide, making it difficult to exit the lowest threshold if you've completely exhausted your stomach.

What if we just reduced the threshold for starving?

2024-02-04 22:14 UTC, deltanedas commented
game theory what if spessmen had intestines so vomiting didnt make them hungry just very upset for a moment

2024-02-04 22:21 UTC, UbaserB commented
> game theory what if spessmen had intestines so vomiting didnt make them hungry just very upset for a moment

Simply just make vomiting vomit up any *currently injested* chemicals and food, but not actually remove their hunger that has already entered their body. As it currently is, its like their vomiting up their muscles and fat making them hungry… which is a medical issue in the real world and very dangerous.

2024-02-04 22:31 UTC, deltanedas commented
it would also make ipecac a medicine rather than nukie validhunting chem

2024-02-05 03:20 UTC, dffdff2423 commented
> Simply just make vomiting vomit up any _currently injested_ chemicals and food, but not actually remove their hunger that has already entered their body. As it currently is, its like their vomiting up their muscles and fat making them hungry… which is a medical issue in the real world and very dangerous.

From the looks of things, making vomit not damage hunger at all would be a very easy (but breaking) change. I think that is a better solution to what I proposed.

2024-02-27 01:06 UTC, dffdff2423 commented
I am going to close this for the time being because there are other things that I would rather spend my coding time on. If someone else wants to take this PR and fix the issues above: feel free to do so.

2024-02-27 01:06 UTC, closed without merging