WIP StepOnComponents
space-wizards/space-station-14 pull request #2496
Opened 2020-11-04 20:13 UTC by Ygg01

My WIP work on StepOnComponent

2020-11-06 12:16 UTC, Zumorica approved these changes

2020-11-10 08:52 UTC, metalgearsloth requested changes
Remove CatwalkComponent as well (it's in 2 places) plz.

2020-11-10 09:31 UTC, Ygg01 commented
> Remove CatwalkComponent as well (it's in 2 places) plz.

Will do. Does SS14 work on MacOS? I'm away from my regular dev computer.

2020-11-22 13:56 UTC, metalgearsloth approved these changes

2020-11-22 14:02 UTC, merged

2020-11-24 13:58 UTC, Ygg01 commented
@metalgearsloth do those changes still need to be applied. I'm at my home computer.