Fix cryostorage removing minds of players who have entered ghost role
space-wizards/space-station-14 pull request #24991
Opened 2024-02-06 09:36 UTC by c4llv07e

## About the PR
Fixes a bug where cryo removes the mind from a new role if the player entered cryostorage, ghosted out and picked a ghost role before cryo finishes.

## Technical details
Right now it just checks if the player with the `CryostorageContainedComponent` is actually stored in the specified cryostorage. It could remove any mind contained in cryostorge, but I can't garantie that it won't cause more bugs.

## Media
I don't think there should be any media there. I can record the bug itself, but I think it is clear from the description.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: c4llv07e
- fix: Cryo won't remove you from the new body if you chose a new ghost role before cryo deleted your old body.

2024-02-06 09:45 UTC, lzk228 commented
#24223

2024-02-06 16:20 UTC, EmoGarbage404 requested changes

2024-02-06 16:20 UTC, EmoGarbage404 commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +            if (containedComp.Cryostorage == null ||
Should this not be checking that the mind's attached entity is the cryostored entity? Im not sure this check would actually fix the issue. The body still needs to get removed, but the mind just needs to not detach.

2024-02-28 22:08 UTC, EmoGarbage404 approved these changes

2024-02-28 22:09 UTC, merged