Predict two-way levers
space-wizards/space-station-14 pull request #25043
Opened 2024-02-08 06:42 UTC by metalgearsloth

Annoys me the rare occasions I touch cargo. Doesn't predict the signal but at least the lever responds immediately.

2024-02-10 08:37 UTC, Jezithyr commented
LGTM I don't see any non-nitpick issues with this. Might be worth using Entity\<T?\> next time instead of the old EntityUid, Comp? way of implementing the resolve pattern.

2024-02-10 09:05 UTC, 0x6273 requested changes
There are "unnecessary `using` directives" warnings in some files after you moved stuff to shared namespace.

2024-02-10 23:38 UTC, Jezithyr commented on Content.Shared/DeviceLinking/SharedDeviceLinkSystem.cs
> +        DeviceLinkSourceComponent? sourceComponent = null)
That's not really long enough to warrant switching it to a list imo.

2024-02-11 03:10 UTC, metalgearsloth commented
> There are "unnecessary `using` directives" warnings in some files after you moved stuff to shared namespace.

IDE warnings are way down the list compared to compiler warnings and deleting tends to attract more merge conflicts.

2024-02-11 03:19 UTC, merged