2024 02 08 nuke disk cryogenic pinpointer fixes
space-wizards/space-station-14 pull request #25069
Opened 2024-02-08 23:34 UTC by Krunklehorn

## About the PR

Currently, `CryostorageSystem` sends mobs to a paused map while keeping track of their equipment. This breaks pinpointer interactions during nukies, as the nuclear authentication disk is technically off-map when inside of a cryogenic storage unit.

## Why / Balance

#25055

## Technical details

- Adds `BeforeEnterCryostorageEvent`, `AfterExitCryostorageEvent` and `SpecialRespawnEvent` for `PinpointerSystem` to react to
- Removes duplicate `SetTarget` method from `PinpointerSystem`

When a pinpointer target enters cryostorage, it begins tracking the cryogenic storage unit itself. Once a target is removed, it will switch to it instead.

When a pinpointer target is destroyed and respawned, the pinpointer will automatically track the new entity.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Krunk
- fix: Pinpointers continue to track objectives after they enter or exit cryogenic storage units.
- fix: Pinpointers continue to track special respawn objectives after they are respawned.

2024-02-08 23:40 UTC, metalgearsloth commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +
Just recursively iterate children rather than adding several codepaths for hands or whatever else.

2024-02-08 23:40 UTC, metalgearsloth commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +}
All new events must be structs.

2024-03-31 05:36 UTC, metalgearsloth commented
@Krunklehorn is this better off just using polymorph as otherwise we'll get problems with anything else that shunts to another map.

2024-03-31 20:19 UTC, Krunklehorn commented
@metalgearsloth How about this? Systems still handle the parenting/unparenting, but now paused map storage is a common system which can at least mark entities and raise an event on arrival/departure.

2024-04-29 03:44 UTC, mirrorcult requested changes

2024-04-29 03:44 UTC, mirrorcult commented on Content.Server/Polymorph/Systems/PolymorphSystem.cs
> +            _transform.SetParent(uid, targetTransformComp, PausedMapStorage.PausedMap.Value);
why does this need to be two calls and you have to remember to call `BeforeEnter` and `AfterExit`, shouldnt the methods on `PausedMapStorage` just be like `InsertIntoPausedStorage` and `RemoveFromPausedStorage`

2024-04-29 03:44 UTC, mirrorcult commented on Content.Server/Pinpointer/PinpointerSystem.cs
> +        SubscribeLocalEvent<SpecialRespawnEvent>(OnSpecialRespawn);
this running on every broadcast seems bad, feels like pinpointer targets should get some marker component so these can be directed subscriptions

2024-05-28 23:17 UTC, AJCM-git commented
@Krunklehorn you coming back to this?

2024-05-29 00:12 UTC, Krunklehorn commented
No, someone else can pick it up from here.

2024-06-19 15:05 UTC, closed without merging