Add MIDI track names to the channel window
space-wizards/space-station-14 pull request #25117
Opened 2024-02-11 03:02 UTC by FairlySadPanda

## About the PR
Add any MIDI track names in a loaded MIDI file to the channels window, so if your MIDI is competent it will tell you what your channels are for. Or not. The internet MIDI landscape is ancient and strange.

## Why / Balance
It sucked to not know what MIDI channels were.

## Technical details
This is not currently replicated as I have no idea how you'd do that; there's no replicated data that says someone is actually playing music, as far as I can see, as it's all done via firing MidiEvents around.

It turned out that the way that Fluidsynth is loaded is just by throwing a byte array at it, which meant there's no way of querying MIDI files being loaded for their text events. As such I did the mature senior software engineer thing of Googling to see if someone had written a MIDI loader that could do this.

The Midi file is from https://github.com/davidluzgouveia/midi-parser and is licensed under MIT. Other than deleting a few non-sandboxed things I've not changed it. Like most ideomatic C# code it throws, so I've protected us from the awfulness of the `throw` keyword with a try-catch surrounding the dirty code. 

This is a dirty hack of a PR and I'm happy to be pointed at how to do this more nicely.

## Media
![image](https://github.com/space-wizards/space-station-14/assets/732532/d82aaaa7-f427-4345-a2b4-bf2525bdb191)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: You can now see any channel names of a MIDI file you've loaded whilst playing.

2024-02-11 03:04 UTC, FairlySadPanda commented on Content.Client/Instruments/InstrumentComponent.cs
> +    public List<string> TrackNames = new();
Would love a way of making this list networked somewhere so band mates can be told what channels are what, meaning they can play along on appropriate channels

2024-02-11 03:07 UTC, FairlySadPanda commented
Realistically networking song details properly would be just a big QOL feature. This at least allows the lead player to tell other players what channels to play, but the ideal would be to hide empty channels entirely from the list for both player and band mates.

2024-02-21 13:09 UTC, metalgearsloth requested changes
MidiLoader looks like it should be on engine (also needs adding to Libraries.yml when updated).

2024-02-21 13:09 UTC, metalgearsloth commented on Content.Client/Instruments/MidiLoader.cs
> +
As above also looks like this should be readonly.

2024-02-21 13:09 UTC, metalgearsloth commented on Content.Client/Instruments/MidiLoader.cs
> +}
record struct.

2024-03-04 17:29 UTC, closed without merging

2024-06-01 23:29 UTC, affonsoamendola commented
So, I really want this issue to go forward, so I'm offering to try and finish it off, but I have a problem with your implementation, if I understood correctly you chose to use the Track Names from the midi files right?

Why not use the values on the program change event defining what instrument is going to be played on each channel? Thats always a simple pair of numbers, instrument and bank, that can be dictionaried into an instrument string following the General MIDI Standards, and I do think that information is always available even from Ancient MIDIs, (even though some of them might just set the channels to all piano, bank 0 instrument 0 as default)

I have a lot of midis to test here, some very old, and I noticed several of them either dont have Track Names, or have weird conventions on how to name and abbreviate stuff.

For example, this one has an Untitled Track, 2 tracks named Synth, etc

![image](https://github.com/space-wizards/space-station-14/assets/35969464/0ab29589-09a9-4d0d-b213-e6ac85361423)

While checking via the channels tab on this software (Which I assume is reading what instrument that channel is setup for) you can see a much more descriptive string on whats there

![image](https://github.com/space-wizards/space-station-14/assets/35969464/ec4b0e34-be85-483b-a846-c94855798b25)

Also, correct me if I'm wrong, but from a quick look around the code I have the impression that Robust just completely ignores Tracks and just plays everything by channels, i.e. playing a note only if that channel is not filtered, so the Track information could be incorrect if they arent in the exact same order as the channels, as tracks can play notes on any channels they want, even multiple

This would probably also be an issue and maybe even justify opening a new issue on changing the Channel Filter popup to a Track Filter popup, but honestly I'd kind of be against that, that would definitely be better as you could filter entire sections of songs, like string ensembles of multiple channels of different string instruments but heres what the Track list for my I Dream of Jeannie MIDI looks like in the end

![image](https://github.com/space-wizards/space-station-14/assets/35969464/5791cfd9-002e-4933-a7b4-5ad97598725a)

Theres so much crap in the Track Names of old MIDIs, should we even try to filter out that information?

I'd rather stay with the clean instrument and bank numbers from the program change event

What do you guys think? Can we reopen this, I really want this functionality in the game, it annoys me to no end having to open up a midi editor to see whats in the channels I'm playing and since the Instruments on the game all have a number value that defines what instrument it is (I think its even named program), we could highlight channels that match the instrument on hand, making it easier to see what channel should be being played with a certain instrument

Thank you

2024-06-02 20:05 UTC, FairlySadPanda commented
Awesome write-up! I should totally use instrument information instead!

The implementation was as it was because I hacked it in without knowing much about MIDI. This sort of information will be invaluable if I revisit it. Given I was using a sidecar to parse MIDI files... it might need some more consensus from maintainers. IDK.

2024-06-02 20:55 UTC, affonsoamendola commented
I did an attempt at something similar to what you've done but using the Program Change event information and without using the little loader you used

There is somewhat of a problem here with what I did, apparently the MIDI system just fires events for stuff like setting up what is GOING to be played in the renderer. I.e. the Grand Piano game instrument has its Midi Renderer set up as all channels (except 9, the percussion channel, that works differently) and uses a IgnoreProgramChangeEvents bool to prevent other unwanted MIDI events from changing the current MidiRenderer channel setup to another instrument (You dont want the Grand Piano in-game to suddenly start spewing jazz guitar sounds if theres a rogue program change event in the middle of the file that you werent expecting).

So what I did was: on the MidiRenderer I added two variables for every channel, one for its current bank, and one for its current program (Instrument/patch are other names documentation uses for it) and added a line in the MidiEventHandler function to set those values only when an program change event happens and the DisableProgramChangeEvents is set to TRUE, and it actually works.

But it is still a bit of a nasty hack, I couldnt figure out a way to ONLY populate those variables with the ProgramChangeEvents we really want (The ones at the beginning of the file, setting up the channels), in this setup, a rogue one in the middle of the file would end up changing what the channel list name would be.

![image](https://github.com/space-wizards/space-station-14/assets/35969464/b78db061-a79d-4a36-a8f3-7abf00e560e5)

As you can see, theres several Accoustic Grand Piano channels, most of them are just empty channels, we also should find out a way to hide those empty channels, but I dont know how to "step" through the MIDI file events in FluidSynth to check which channels actually have stuff, and Channel 9 works a bit differently, so it almost always shows up as Accoustic Grand Piano, that one will also need to be thought out, the percussion channel doesnt work very well with the current setup, as its instruments are coded in the notes of channel 9.

Also no clue on how to make this work with the band setup, maybe theres a way to change the place where the current channel names is stored from the MidiRenderer to a Shared ActiveInstrument as suggested earlier, but I have no idea how that shared stuff works, this is my first time messing around with SS14 code