Alert levels
space-wizards/space-station-14 pull request #25137
Opened 2024-02-11 22:14 UTC by OliverOtter

## About the PR

Adds 5 new alert levels that admins can use. They can be used for RP/event reasons, and work similar to the Gamma/Epsilon alert, being unable to be changed by crew.
## Why / Balance

Can be used for rp purposes, and for the future. Ex: Code Lima can be auto called if cults where in game, and where making the nar'sie summoning rune.
## Technical details
NA

## Media

![image](https://github.com/space-wizards/space-station-14/assets/153337321/23e66171-9df5-4581-98d8-5f1cddad9df9)
![image](https://github.com/space-wizards/space-station-14/assets/153337321/3a96c1c6-6616-4f98-a42b-ba8de8af3dcf)
![image](https://github.com/space-wizards/space-station-14/assets/153337321/12562a5d-54ca-4065-82f9-ffc6d942c140)
![image](https://github.com/space-wizards/space-station-14/assets/153337321/5c823036-8a90-4a02-bc55-908a78099fb0)
![image](https://github.com/space-wizards/space-station-14/assets/153337321/08c783d0-b50c-47cd-976d-dcc0c0236fd5)

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A
**Changelog**

no cl no fun

2024-02-11 23:00 UTC, lzk228 commented
nuuuh

2024-02-11 23:04 UTC, UbaserB commented
I feel like this is a bit too many presets. Maybe 1 or two sure, but this feels like bloat since admins can manually set up their own iirc

2024-02-11 23:06 UTC, mirrorcult commented
these all seem extremely way too situational and memey to be actual prototypes in the game and not just uploaded

2024-02-11 23:08 UTC, UbaserB commented
> these all seem extremely way too situational and memey to be actual prototypes in the game and not just uploaded

i would probably keep alert navy though, events with visitors are fairly common.

2024-02-11 23:58 UTC, lzk228 commented
> these all seem extremely way too situational and memey to be actual prototypes in the game and not just uploaded

they cant even be uploaded since name hardcoded #21525 :trollface:

2024-02-12 07:37 UTC, Clostyandr commented
The last two is cringe. Other is OK, but call it normal i can't.

2024-02-12 10:50 UTC, IProduceWidgets commented
> > these all seem extremely way too situational and memey to be actual prototypes in the game and not just uploaded
> 
> i would probably keep alert navy though, events with visitors are fairly common.

But why would a visitor require an alert level that changes the alarm colors and such? 

Many of these feel like a way to have recolored announcements, which would just be a nice feature in itself.

2024-02-14 22:29 UTC, Veritius requested changes

2024-02-14 22:29 UTC, Veritius commented on Resources/Locale/en-US/alert-levels/alert-levels.ftl
> +alert-level-beige-announcement = Central Command has seen the shit going on the station, and is just dissapointed in everyone on board. Everyone is required to feel shame.
Spelling:
```suggestion
alert-level-beige-announcement = Central Command has seen the shit going on the station, and is just disappointed in everyone on board. Everyone is required to feel shame.
```

Funnier:
```suggestion
alert-level-beige-announcement = Central Command has seen the shit going on the station, and is just disappointed in everyone on board. Everyone is contractually obligated to feel shame.
```

2024-02-14 22:29 UTC, Veritius commented on Resources/Locale/en-US/alert-levels/alert-levels.ftl
> +alert-level-cyan-instructions = Time paradox detected.
These aren't instructions.

2024-02-14 22:29 UTC, Veritius commented on Resources/Locale/en-US/alert-levels/alert-levels.ftl
> +alert-level-lima-announcement = Central Command has ordered the Lima security level on the station. There is currently a supernatural or eldritch level abnormallity to the station. All staff on board
```suggestion
alert-level-lima-announcement = Central Command has ordered the Lima security level on the station. There is currently a supernatural or eldritch level abnormality to the station. All staff on board is investigate and eliminate the abnormality.
```

2024-04-28 09:22 UTC, metalgearsloth commented
what mirror said nutria

2024-04-28 09:22 UTC, closed without merging