fishops nerf real
space-wizards/space-station-14 pull request #25148
Opened 2024-02-12 09:47 UTC by deltanedas

## About the PR
made rehydratables inherit forensic fibers + dna + prints when hydrated

fibers and dna makes sense prints are a stretch but magic forensic analyser thingy whatever

## Why / Balance
"your honour they have no evidence" in fishops trial no longer works
det with 10 separate fish scans that all have your prints on them:

now you have to cover fingerprints like normal or butcher all the fish to avoid being sentenced

## Technical details
moved rehydrating to shared for future stuff, also fixed the rehydrate popup because did you know it used to have one

## Media
![100208](https://github.com/space-wizards/space-station-14/assets/39013340/a71c0915-6f2c-4e60-ade8-d0d0f4306e44)

![100240](https://github.com/space-wizards/space-station-14/assets/39013340/c6edad77-d3e9-4d42-9df9-4b5d20aa6a81)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
rehydrating is in shared so if you use `GotRehydratedEvent` import `Content.Shared.Chemistry.Components;` (instead of) server components.

**Changelog**
:cl:
- tweak: Rehydrated mobs (carp) now keep their forensics data from their cube/plushie form.

2024-02-12 10:06 UTC, IProduceWidgets commented
In b4 petting doesn't work unless you take your gloves off PR ![image](https://github.com/space-wizards/space-station-14/assets/107586145/17312192-32e5-4bd4-a486-ac7760ef9919)

2024-02-12 11:54 UTC, deltanedas commented
test fail fake

2024-02-16 19:44 UTC, deltanedas commented
merg

2024-02-16 23:43 UTC, metalgearsloth requested changes

2024-02-16 23:43 UTC, metalgearsloth commented on Content.Server/Forensics/Systems/ForensicsSystem.cs
> +
Just add a method for this.

2024-02-25 17:23 UTC, deltanedas commented
@metalgearsloth merg

2024-03-05 03:13 UTC, metalgearsloth approved these changes

2024-03-05 03:13 UTC, merged