WebP lobby images
space-wizards/space-station-14 pull request #25184
Opened 2024-02-13 16:13 UTC by PJB3005

## About the PR
Lobby images are now WebP, saving significant file size at the cost of little image quality loss.

## Why / Balance
Reduces folder from 10 MB to 2.5 MB.

## Technical details
Engine supports WebP already ez PR.

2024-02-13 16:15 UTC, deltanedas commented
webp my beloved

2024-02-13 16:29 UTC, VasilisThePikachu requested changes
Should probably specify to use either 99% quality or 100% to people making lobby pr's [PutLobbyScreensHere.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Textures/LobbyScreens/PutLobbyScreensHere.txt)

2024-02-13 16:35 UTC, VasilisThePikachu approved these changes

2024-02-14 14:31 UTC, notquitehadouken commented
no 7.5 megabyte space save left behind

2024-02-14 22:25 UTC, Veritius approved these changes

2024-02-16 23:55 UTC, mirrorcult approved these changes

2024-02-16 23:55 UTC, merged