PDA Pen Holder
space-wizards/space-station-14 pull request #2519
Opened 2020-11-07 17:51 UTC by exp111

2020-11-07 18:10 UTC, metalgearsloth requested changes

2020-11-07 18:10 UTC, metalgearsloth commented on Content.Server/GameObjects/Components/PDA/PDAComponent.cs
> +        [ViewVariables] private string _startingPen = default!;
Should be nullable

2020-11-07 18:10 UTC, metalgearsloth commented on Content.Server/GameObjects/Components/PDA/PDAComponent.cs
> +                eventArgs.User.GetComponent<HandsComponent>().PutInHand(swap.GetComponent<ItemComponent>());
50/50 on it being dependent upon hands but it's fine for now.

2020-11-07 18:35 UTC, exp111 commented on Content.Server/GameObjects/Components/PDA/PDAComponent.cs
> +        [ViewVariables] private Container _penSlot = default!;
Yes the problem is that the swap code is kinda shit.

2020-11-08 01:57 UTC, metalgearsloth approved these changes
LGTM though having a button for it in the UI would be nice like the ID (either a TODO or implementing it is fine).

2020-11-08 12:43 UTC, metalgearsloth approved these changes

2020-11-08 12:43 UTC, merged