Add new stairs
space-wizards/space-station-14 pull request #25212
Opened 2024-02-14 06:32 UTC by Ko4ergaPunk

## About the PR
We have three colors of steel tiles, but only one stairs. Trouble.
Also remove the shades so you can connect the stairs

## Why / Balance
Mappers say thanks for that.

## Media

![newStairs](https://github.com/space-wizards/space-station-14/assets/62609550/6435bb6e-2bff-40ce-8d9e-2a431b34c19b)
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2024-02-14 06:33 UTC, UbaserB commented
very fair

2024-02-14 09:45 UTC, Flareguy requested changes
Restore ``stairs_steel,`` ``stairs_white,`` and ``stairs_dark`` to their original versions with shading.
We had stairs that were sprited exactly like these before, and they had major problems with indicating directionality.

If there's any way to do stairs without any lightsource, it's probably what you've done with stage stairs. Their trims help indicate directionality.

2024-02-16 11:49 UTC, Flareguy commented
Okay, after some discussion on discord, we've decided stairs should use iconsmooth to fix the tiling issues, since without the shading they look kind of bad. Keep in mind that you'll probably need iconsmooth to be fixed for directional sprites, though.

Likewise, I would probably fully revert the stairs sprites or leave it to another PR since they do genuinely help convey directionality 
IMO. The side state sucks, but the north one works fairly well in my opinion.

2024-02-16 20:32 UTC, Flareguy approved these changes

2024-02-21 06:28 UTC, merged