Added Evidence Markers for the Detective!
space-wizards/space-station-14 pull request #25255
Opened 2024-02-15 03:54 UTC by Moomoobeef

## About the PR
The detective now starts with a box of evidence markers in their locker. These yellow numbered markers are useful for marking the elements of a crime scene.

## Why / Balance
An immersive way to make a crime scene look like a crime scene, and might make it more obvious to would be janitors that this is not the place to clean.

## Media
![2024-02-14_19-44](https://github.com/space-wizards/space-station-14/assets/62638182/ec5856f0-60db-48a4-a829-d24343629f45)
![2024-02-14_19-42](https://github.com/space-wizards/space-station-14/assets/62638182/2cffe196-99a1-4f88-a435-31b861eabaef)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Detectives are now supplied with a box of evidence markers, useful for marking evidence at a crime scene.

2024-02-16 18:49 UTC, EmoGarbage404 requested changes
the sprites for these are a bit large.

For the icons, they could probably just be shrunk a tiny bit so that the edge of the face is a bit tighter around the number. The inhands can definitely be smaller. The current size looks more like a wet floor sign.

2024-02-16 18:49 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Objects/Specific/Security/evidence-marker.yml
> +  - type: Item
remove this dummy `Item` definition from all the prototypes

2024-02-16 18:49 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Objects/Specific/Security/evidence-marker.yml
> +  name: first evidence marker
might make more sense to just have their names be `evidence marker` since it's already kinda clear what the number is. just a thought.

2024-02-17 00:22 UTC, Moomoobeef commented
:+1: sure I can make those changes in a bit.
I just got home so I'm gonna eat first but in a few hours I should have it ready to be reviewed again.

2024-02-17 01:53 UTC, K-Dynamic commented
Maybe let the detective renumber the markers by letting them change evidence marker sprites

2024-02-17 05:43 UTC, Moomoobeef commented
![image](https://github.com/space-wizards/space-station-14/assets/62638182/f021255e-3740-4425-bfec-3f42fdadf24a)
new sprites, they're smaller.

2024-02-17 20:49 UTC, EmoGarbage404 approved these changes

2024-02-17 20:49 UTC, merged