randomized sexless species now have epicene gender by default
space-wizards/space-station-14 pull request #25282
Opened 2024-02-15 20:21 UTC by Dutch-VanDerLinde

## About the PR
title

## Why / Balance
good for sexless species
if you randomize everything in the character editor it'll use female pronouns by default if you get a sexless species

## Technical details
when completely randomizing a character -

how it worked before:
if sex was male, give male pronouns, otherwise give female
this resulted in sexless species being given female pronouns by default

how it works now:
pronouns are they/them by default
if sex is male, give male pronouns
if sex is female, give female pronouns

## Media
![image](https://github.com/space-wizards/space-station-14/assets/45323883/0eae3a3b-bb5c-42ca-9118-646c5f961c49)
randomized sexless character has they/them pronouns by default
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-02-15 21:09 UTC, Brandon-Huu approved these changes

2024-02-15 21:49 UTC, PolterTzi commented
While we're at it, why not just make it completely random?

2024-02-15 22:40 UTC, 0x6273 requested changes

2024-02-15 22:40 UTC, 0x6273 commented on Content.Shared/Preferences/HumanoidCharacterProfile.cs
> +            }
This should be a switch expression (`var gender = sex switch {..}`)

2024-02-16 04:22 UTC, Clostyandr commented
Huh? I thought this game without any politics...

2024-02-16 04:24 UTC, mirrorcult commented
> Huh? I thought this game without any politics...

![hog](https://github.com/space-wizards/space-station-14/assets/19853115/cf897d21-1650-4c62-b110-c821d5fe77e9)

2024-02-16 04:32 UTC, PolterTzi commented
> Huh? I thought this game without any politics...

I should be surprised by the utter mess of mental gymnastics and whatever else that must've led you to developing the thoughts that would lead to making such a comment.

2024-02-16 04:41 UTC, metalgearsloth approved these changes

2024-02-16 05:16 UTC, Brandon-Huu commented
> Huh? I thought this game without any politics...

Politics is when fixing bugs

2024-02-19 22:38 UTC, merged