Plushies can now have pAIs stuffed into them to make your companion even better!
space-wizards/space-station-14 pull request #25306
Opened 2024-02-16 05:49 UTC by Moomoobeef

## About the PR
I added a slot to plushies which can contain pAIs and only pAIs.

## Why / Balance
I thought it would be really neat.

## Media
![2024-02-15_21-43](https://github.com/space-wizards/space-station-14/assets/62638182/5c0d895c-0681-4180-b433-cc47b3de8e61)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Plushies now have some space inside where you can insert a pAI, for the ultimate companion.

2024-02-16 05:49 UTC, UbaserB commented
best change ever

2024-02-16 06:00 UTC, marboww commented
does this also apply to the PAI syndicate? If yes, then this is a funny disguise

2024-02-16 06:01 UTC, marboww commented
this is a funny disguise for the PAI syndicate

2024-02-16 06:07 UTC, Moomoobeef commented
it does apply the the syndicate pAI

2024-02-16 06:29 UTC, Dragonjspider commented
Finally, a true companion :)

2024-02-16 08:26 UTC, Moomoobeef commented
so I have no idea why the check failed. Need some help with that

2024-02-16 08:34 UTC, deltanedas commented
add a container for it too

2024-02-16 09:10 UTC, 0x6273 commented
I think it should just have a 2x1 inventory, so you can hide other small items like c4 also. And maybe require a sharp item to access it.

2024-02-16 18:45 UTC, EmoGarbage404 commented
i feel like this would be better if you had to cut it open or something, like was suggested. Every plushie having a slot in the verb menu that is only used for PAIs is kinda strange. It should definitely be expanded to fit any small item.

2024-02-17 00:23 UTC, Moomoobeef commented
alright then, I'll have to see _how_ I can make it where you have to cut it. And then I can change it to just have like a 2x1 storage or something.

2024-02-17 01:18 UTC, ViceEmargo commented
I agree that it would be interested if you had to interact with the plushie with a sharp object first, and I also believe it should be a general small storage space as opposed to only allowing pAIs, but this is a fantastic use case plushie-storage.

2024-02-17 08:12 UTC, deltanedas commented
additionally make it so when inserting a mind container it transfers mind to the plushie :trollface:

2024-02-17 08:13 UTC, Hanzdegloker commented
> additionally make it so when inserting a mind container it transfers mind to the plushie :trollface:

Just stuck a plushie that can only Weh!

2024-02-18 10:14 UTC, Veritius commented
> i feel like this would be better if you had to cut it open or something, like was suggested. Every plushie having a slot in the verb menu that is only used for PAIs is kinda strange. It should definitely be expanded to fit any small item.

hand a lizard plushie with a remote explosive grenade to a lizard

2024-02-18 12:14 UTC, TheShuEd requested changes

2024-02-18 12:14 UTC, TheShuEd commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +  - type: ItemSlots
you need to add ContainerContainer component

test fail is real
![image](https://github.com/space-wizards/space-station-14/assets/96445749/da0459ee-0cd7-4374-9e85-a0c6bfa878e8)

2024-02-19 02:43 UTC, Moomoobeef commented
So I agree with emo on how it _should_ work, but I honestly don't know how to do that. It's beyond the scope of what I know how to do right now. So if someone else wants to figure it out or if someone wants to try and help me out with it I'd love that but for now I'm just at a standstill.

2024-02-19 02:54 UTC, UbaserB commented
> So I agree with emo on how it _should_ work, but I honestly don't know how to do that. It's beyond the scope of what I know how to do right now. So if someone else wants to figure it out or if someone wants to try and help me out with it I'd love that but for now I'm just at a standstill.

using any sharp object (similar to “butcher”) will start a doafter where the entity now *shows* storage. This storage will be 2x3 and cannot hold any objects (blacklist) that hold a tag determining if they are “sharp” or not. You can then close it up again (not sure how yet, probably add a new entity like a sowing needle or something. Maybe more simply just an action.) This then preserves the item inside the object as it is still a container but you cannot open it up.

This is my idea anyway.

2024-02-19 03:48 UTC, Moomoobeef commented
it's not that I don't know how to do it in _concept_, but rather that I can't understand the code. I thought I knew C# and I did spend some time learning it but any time I look at the code in this project it's like reading hieroglyphs, and I'm not sure where or how to start getting it.

2024-02-20 00:30 UTC, TheShuEd requested changes
Now toys are food for Nianes, and you need to make sure that the items sewn inside will not be lost when the toy is eaten

2024-02-20 03:15 UTC, marboww commented
> So I agree with emo on how it _should_ work, but I honestly don't know how to do that. It's beyond the scope of what I know how to do right now. So if someone else wants to figure it out or if someone wants to try and help me out with it I'd love that but for now I'm just at a standstill.
> 
> Edit: when I posted this comment my github hadn't refreshed and I completely missed TheShuEd's review, it's not that I meant to ignore it or anything. I could make that change but thinking about it I really think it would make more sense if it worked more in the way emo proposed.

Emo probably assumes that it is enough to make a 1x2 storage space where you can store any kind of things. And since I've done the moth eating, I can do something to help.

2024-03-12 10:10 UTC, UbaserB commented
Are you going to figure out how to code it or..?

2024-05-04 14:47 UTC, beck-thompson commented
Hey! If ya can't finish this I'd love to do it myself. Let me know if your still working on it!

2024-05-06 23:18 UTC, Moomoobeef commented
You are welcome to finish it because I just don't have time for this before the feature freeze, been very busy with life stuff so. I can't figure out how to close the PR on my phone so until I get on my computer just pretend it's closed :P

2024-05-07 00:53 UTC, closed without merging