Make Camera Monitor Great Again
space-wizards/space-station-14 pull request #25358
Opened 2024-02-17 23:02 UTC by VigersRay

## About the PR

I don’t know why it was necessary to make the cameras the way they are now, the need to connect to each server, not a user-friendly interface, and also a terrible artificial delay as if the transmission was taking place via 1st generation Bluetooth. In short, I did this thing a long time ago, but then I broke the game with it, then I killed it. Now, after the crew monitoring rework, I tried it again and it works much better.

## Why / Balance

This will allow people to start using cameras (previously only masochists and people with a mania for spying on the captain did this)

## Technical details

This is a terrible shitcode and copy-paste, I will understand if you close it.
![shitcode](https://github.com/space-wizards/space-station-14/assets/60344369/a5806d55-3a8e-432f-af2c-6d63e0713676)

## Media

![image](https://github.com/space-wizards/space-station-14/assets/60344369/262d3eeb-d516-4e64-88e2-f668fc4c12bf)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: VigersRay
- tweak: Improved camera monitoring.

2024-02-18 01:51 UTC, chromiumboy commented
I like the concept, but yeah, the execution needs some work. Namely, don't copy paste the crew monitor UI code. Like you have the coordinates listed for the camera but they aren't needed in this context... Making the nav map UI visually distinct from the other monitors would be nice. Like changing up the colors and markers for the cameras for example

Also why do we still need to manually refresh subnets and cameras, this functionality can just be automated

2024-02-18 06:02 UTC, Baptr0b0t commented
The UI map was exactly what I needed for my AI PR, hope to see it merged soon.
https://github.com/space-wizards/docs/pull/162
https://github.com/space-wizards/space-station-14/pull/25267

2024-02-18 18:47 UTC, VigersRay commented
> I like the concept, but yeah, the execution needs some work. Namely, don't copy paste the crew monitor UI code. Like you have the coordinates listed for the camera but they aren't needed in this context... Making the nav map UI visually distinct from the other monitors would be nice. Like changing up the colors and markers for the cameras for example
> 
> Also why do we still need to manually refresh subnets and cameras, this functionality can just be automated

After the PR, I thought about camera colors by department and removing subnet update buttons. In general, you can add automatic detection of all cameras and subnets every 10 seconds, I think this will not be too much of a burden. The only thing is that you first need to update the subnets, wait until the network emission works, and then update the cameras.

2024-02-19 17:42 UTC, ficcialfaint requested changes

2024-02-19 17:42 UTC, ficcialfaint commented on Content.Client/SurveillanceCamera/UI/SurveillanceCameraMonitorBoundUi.cs
> +        _surveillanceCameraMonitorSystem = _entManager.EntitySysManager.GetEntitySystem<SurveillanceCameraMonitorSystem>();
you have `EntMan` and `EntMan.System<T>`

2024-02-19 17:42 UTC, ficcialfaint commented on Content.Client/SurveillanceCamera/UI/SurveillanceCameraNavMapControl.cs
> +
localization

2024-02-19 17:42 UTC, ficcialfaint commented on Content.Server/SurveillanceCamera/Systems/SurveillanceCameraMonitorSystem.cs
> +    // }
don't comment out, delete instead

2024-02-19 17:42 UTC, ficcialfaint commented on Resources/Locale/en-US/surveillance-camera/surveillance-camera-ui.ftl
> +surveillance-camera-monitor-ui-flavor-left = Dont check captain bathroom
```suggestion
surveillance-camera-monitor-ui-flavor-left = Don't check captain bathroom
```

2024-03-13 21:57 UTC, Strol20 commented
Is this pr active?

2024-03-26 04:04 UTC, metalgearsloth commented
Re-open if you come back to it.

2024-03-26 04:04 UTC, closed without merging