Cleaner Grenade
space-wizards/space-station-14 pull request #25444
Opened 2024-02-21 14:47 UTC by DenisShvalov

Added Cleaner Grenade

## About the PR
Added Cleaner Grenades that creates foam of space cleaner of activate
- Added 2 grenades in janitor belt on spawn
- Added 2 grenades in custodial closet
- Added 2 grenades in janitorial supplies crate

## Why / Balance
Big puddles of space lube 💀 

## Media

https://github.com/space-wizards/space-station-14/assets/115770678/99fe98e1-c8fa-49d4-8658-a73519887606

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- add: Added Cleaner Grenades that will help janitors in their work

2024-02-21 18:45 UTC, 0x6273 commented
You can already make these with modular grenade chem payload.

2024-02-21 18:45 UTC, DenisShvalov commented
> I think it'd be cooler if you crafted them from like soap and cloth or something. Since buying a whole supply crate for 2 grenades is a bit wasteful and the kitchen can make soap, more interaction is always better.

This grenade can by created by chemist with 50 fluoro, 50 water and 30 space cleaner. Craft with soap and cloth is to op in my sight

2024-02-22 05:15 UTC, Golinth commented
I support this. As a nukie, or syndie chemist, I tend to always pack a lube foam grenade or two, and this will certainly help prevent how OP that strategy is.

2024-03-01 01:18 UTC, metalgearsloth requested changes
Remove it from the locker as it's not essential to the job.

2024-03-04 08:56 UTC, DenisShvalov commented
> Remove it from the locker as it's not essential to the job.

Why not? Janitors can fast clean large puddles with them, so they will use them often.
I decided to add them to lockers, because in ss13 you can find them in jani lockers

2024-03-04 09:10 UTC, Catdere commented
> > Remove it from the locker as it's not essential to the job.
> 
> Why not? Janitors can fast clean large puddles with them, so they will use them often. I decided to add them to lockers, because in ss13 you can find them in jani lockers

I agree with this, As having a few cleaner grenades in your locker can help keep the station clean until sci can hit you with a better mod

2024-03-17 11:48 UTC, metalgearsloth commented
> > Remove it from the locker as it's not essential to the job.
> 
> Why not? Janitors can fast clean large puddles with them, so they will use them often. I decided to add them to lockers, because in ss13 you can find them in jani lockers

The locker is so someone can take that role if they change their job; the grenade is not essential to the job.

2024-03-17 12:15 UTC, metalgearsloth requested changes
In case my comment wasn't clear put it on a vendor or equivalent, lockers are supposed to be barebones and not just a mess of sometimes roundstart stuff sometimes not.

2024-03-17 12:15 UTC, metalgearsloth commented on Resources/Prototypes/Catalog/Fills/Items/belt.yml
>        - id: FlashlightLantern
Why isn't this using amount.

2024-03-18 16:02 UTC, DenisShvalov commented
Removed from jani locker, added box of them that you can buy in cargo with jani items

2024-03-25 06:46 UTC, metalgearsloth approved these changes

2024-03-25 06:46 UTC, merged