Implanter Fabricator
space-wizards/space-station-14 pull request #25520
Opened 2024-02-24 17:11 UTC by TheShuEd

## About the PR
Adds a new Lathe that allows for the production of various implants. This automaton can be Emagged to gain access to some not-so-strong implants.

Removed the ability to buy fun implants via cargo.

added 2 new implants: 
- Smoke Cloud Implant (the only way to get it is by emagging a new lathe)
- Protokinetic implant - allow to rarely shoot ptk projectiles from hand

## Why / Balance
Implants are a rather interesting mechanic that is very underutilized

I think we also need useful implants for the crews. Adding this to the medical machine would increase the variety of gameplay of the medical department.

## Technical details
no c#

## Media
![image](https://github.com/space-wizards/space-station-14/assets/96445749/e0a7e9ec-239a-4fbf-8383-f62d505e9cb1)

https://github.com/space-wizards/space-station-14/assets/96445749/e8bb0d08-4097-4a25-88ff-bacee42b45e3

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added new ImpLathe. Lathe to fabricating implanters.
- add: New Protokinetic and smoke cloud implanters added.

2024-02-24 17:17 UTC, TheShuEd commented
I wanted to make biochem cooler, but you nuke it

2024-02-24 17:47 UTC, metalgearsloth commented
I think inventory is interesting and nuking it for powergaming implants doesn't seem good and just creeps them even harder. The only reason nukies / sec have implants is important to bypass inventory but there's no reason a random clown needs to be able to teleport at will.

2024-02-24 17:48 UTC, deltanedas commented
> there's no reason a random clown needs to be able to teleport at will.

thats emag only

2024-02-24 17:49 UTC, metalgearsloth commented
> > there's no reason a random clown needs to be able to teleport at will.
> 
> thats emag only

It's still forcing implant removal as a mechanic and bypassing the entire reason it even exists for nukies.

2024-02-24 18:08 UTC, Aisu9 commented
why emag card need to gain more value again?

2024-02-24 21:11 UTC, Kadeo64 commented
I don't think PKA implant being random is a good idea, it should probably just have a long cooldown (15 seconds maybe)

2024-02-25 07:25 UTC, keronshb requested changes

2024-02-25 07:25 UTC, keronshb commented on Resources/Prototypes/Recipes/Lathes/implants.yml
> +
These shouldn't be printable, even by emag. It's huge powercreep and they're meant to be bought via uplink.

2024-02-25 07:25 UTC, keronshb commented on Resources/Prototypes/Recipes/Lathes/implants.yml
> +    Plasma: 50
Mindshields should not be printable.

2024-03-13 21:27 UTC, closed without merging

2024-03-13 22:20 UTC, Hmeister-real commented
o7