Disables the random sentience event
space-wizards/space-station-14 pull request #25542
Opened 2024-02-25 05:06 UTC by Flareguy

## About the PR
Disables the RandomSentience event. This only comments out the yaml responsible for the event, and does not remove any associated code.

## Why / Balance
This event only really ends up accomplishing two things the vast majority of the time: clogging up the ghost role menu & removing a possible spawn chance for any other events.
These roles are not fun to play as or to roleplay as, and are very rarely taken as a result. I would be willing to bet that very few people want to sit around all round to play as an immobile hydroponics tray that most people won't even realize is sentient.

The event *is* inherintly kind of funny, but that's all it really has going for it. You'll probably get significantly more engaging roleplay by playing as a pAI.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
- remove: Removed the random sentience event.

2024-02-25 05:10 UTC, Ilya246 commented
i think it would be better to just change what it can make sentient, remove vending machines from the pool so it gets more of the fun stuff like bots and animals

2024-02-25 05:14 UTC, Flareguy commented
> i think it would be better to just change what it can make sentient, remove vending machines from the pool so it gets more of the fun stuff like bots and animals

I didn't even know it COULD make those sentient. Is there any code that determine what it can make sentient specifically?

2024-02-25 05:15 UTC, Ilya246 commented
> > i think it would be better to just change what it can make sentient, remove vending machines from the pool so it gets more of the fun stuff like bots and animals
> 
> I didn't even know it COULD make those sentient. Is there any code that determine what it can make sentient specifically?

it's a tag, iirc RandomSentienceTarget or something, may be wrong

2024-02-25 05:52 UTC, potato1234x commented
yeah, the vending machines need to go, every time ive seen them be sentient they just get ignored or brought to the shuttle as a shittier pai

2024-02-25 06:10 UTC, LeIronGoat commented
> > i think it would be better to just change what it can make sentient, remove vending machines from the pool so it gets more of the fun stuff like bots and animals
> 
> I didn't even know it COULD make those sentient. Is there any code that determine what it can make sentient specifically?

Yeah, very rarely I see a cleanbot become sentient. Could be fun to still have those rarely. Its not an incredibly engaging role, but its a little something here and there.

I assume this also removes the chance where it occasionally also includes corgis/slimes, but thats probably fine since we can just cog those pretty easily usually.

2024-02-25 06:47 UTC, K-Dynamic commented
Supposedly medibits and cleanbots can't become sentient due to a bug or something, so maybe change that

2024-02-25 08:22 UTC, FungiFellow commented
Instead of removing the event altogether just remove hydroponics trays from the list as they can already gain sentience through botany.

2024-02-25 08:30 UTC, mirrorcult commented
yeah imo just tighten the list of what can actually be targeted so its only actually interesting stuff

2024-02-25 08:30 UTC, mirrorcult requested changes
above

2024-02-25 09:31 UTC, jessicamaybe commented
I feel like half the time I see this event trigger it's just the vending machines on the centcom map, removing those from the rotation would be good.

I think would also be funny to see stuff like the nuclear bomb or the captains laser gun be able to gain sentience

2024-02-26 21:22 UTC, Ghagliiarghii commented
I've seen a funny sentient vending machine a time or two, I would instead weight it so they're much rarer and so you see sentient pets / robots (cleanbot, medibot, etc.) a lot more often.

2024-02-26 22:27 UTC, tutoumi commented
if you make sentient cleanbot, PLEASE make it able to have a knife like in tg. Not to attack directly but to cut minorly and stun (much less than the honkbot would) those who run on it

2024-03-17 11:41 UTC, metalgearsloth commented
Re-open if you come back to it.

2024-03-17 11:41 UTC, closed without merging