Fix running showatmos twice not disabling the atmos overlay
space-wizards/space-station-14 pull request #2557
Opened 2020-11-14 23:27 UTC by DrSmugleaf

Fixes #2546

2020-11-15 03:29 UTC, metalgearsloth requested changes
Probably needs a master merge now as well.

2020-11-15 03:29 UTC, metalgearsloth commented on Content.Server/GameObjects/EntitySystems/Atmos/AtmosDebugOverlaySystem.cs
> +        [Dependency] private readonly IEntityManager _entityManager = default!;
EntityManager

2020-11-15 10:27 UTC, DrSmugleaf commented on Content.Server/GameObjects/EntitySystems/Atmos/AtmosDebugOverlaySystem.cs
> +        [Dependency] private readonly IEntityManager _entityManager = default!;
Fixed.

2020-11-18 07:17 UTC, metalgearsloth approved these changes

2020-11-18 07:18 UTC, merged