Improve hurt command feedback and usability
space-wizards/space-station-14 pull request #2559
Opened 2020-11-14 23:27 UTC by DrSmugleaf

2020-11-15 03:26 UTC, metalgearsloth requested changes

2020-11-15 03:26 UTC, metalgearsloth commented on Content.Server/Commands/HurtCommand.cs
> +                msg += string.Join('|', types);
StringBuilder

2020-11-15 03:26 UTC, metalgearsloth commented on Content.Server/Commands/HurtCommand.cs
> +                    }
Spanish moment. Suss on this.

2020-11-15 10:20 UTC, DrSmugleaf commented on Content.Server/Commands/HurtCommand.cs
> +                msg += string.Join('|', types);
Done.

2020-11-15 10:21 UTC, DrSmugleaf commented on Content.Server/Commands/HurtCommand.cs
> +                    }
I don't know what you méan sir

2020-11-15 10:24 UTC, DrSmugleaf commented
Reviews addressed.

2020-11-27 07:18 UTC, metalgearsloth approved these changes

2020-11-27 07:18 UTC, merged