Chore/more typos
space-wizards/space-station-14 pull request #25628
Opened 2024-02-27 00:50 UTC by Brandon-Huu

## About the PR

Removed multiple instances of programmer spelling

## Why / Balance

Some of the typos were user facing and made up look bad. stupid dog.

## Technical details

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-02-27 04:54 UTC, Brandon-Huu commented
NOOO

2024-02-27 05:35 UTC, Ilya246 commented
this is a massive breaking change and will break most downstreams

2024-02-27 05:54 UTC, metalgearsloth requested changes
Datafields should be using the string-less version, rest looked okay. The only actual change downstreams should need to do is the ambient music update for interruptible if they have their own and git should handle the rest.

2024-02-27 08:24 UTC, Ilya246 commented on Content.Client/CloningConsole/UI/CloningConsoleWindow.xaml.cs
> +                        case ClonerStatus.OccupantMetaPhysical:
"metaphysical" is one word, no?

2024-03-03 17:18 UTC, Brandon-Huu commented
wtf

2024-03-03 17:18 UTC, closed without merging