Shader Dev Window & Other Stuff
space-wizards/space-station-14 pull request #2572
Opened 2020-11-16 20:47 UTC by GlassEclipse

Continues https://github.com/space-wizards/space-station-14/pull/1194
Requires https://github.com/space-wizards/RobustToolbox/pull/1407

2020-11-23 03:57 UTC, metalgearsloth requested changes

2020-11-23 03:57 UTC, metalgearsloth commented on Content.Client/Commands/GuiShaderDevCommand.cs
> +        public string Command => "shaderDevWindow";
I prefer all lowercase but that's just me

2020-11-23 03:57 UTC, metalgearsloth commented on Content.Client/Commands/GuiShaderDevCommand.cs
> +                 */
Remove?

2020-11-23 03:57 UTC, metalgearsloth commented on Content.Client/Commands/GuiShaderDevCommand.cs
> +                }
I get Shader prototype has no source exceptions when I try using this even when I checked out the engine PR. Probably need to handle those?

2020-11-23 03:57 UTC, metalgearsloth commented on Content.Client/Development/SimpleShaderDevWindow.cs
> +                    new Label {Text = "Foreground Color: "},
Localise here + elsewhere.

2020-11-23 03:57 UTC, metalgearsloth commented on Content.Client/Development/SimpleShaderDevWindow.cs
> +            Title = "Shader Dev: " + (ShaderName != null ? ("'" + ShaderName + "'") : "NULL");
Localise, also this seems ugly, maybe null coalesce or something instead?

2021-01-14 08:18 UTC, metalgearsloth commented
You coming back to this glass?

2021-02-06 23:04 UTC, SweptWasTaken commented
> 
> 
> You coming back to this glass?

Guess not. Closing.

2021-02-06 23:04 UTC, closed without merging