Dionae now bleed sap, and this can be used to make syrup.
space-wizards/space-station-14 pull request #25748
Opened 2024-03-01 15:44 UTC by Blackern5000

## About the PR
I switched the water in their blood for a new sap reagent, makes more sense for a tree.
This sap can be boiled to make syrup, a very sweet and helpful substance for feeding the crew or making sticky traps. Put it on pancakes, inject it into starving people, or toss it on the floor while running from sec.
People **_definitely_** won't make nymph sap factories in the freezer!
Sap can also be centrifuged into water and sugar for chemistry.

Syrup restores double the average amount of hunger and slows you by 55% when walking through it.

Sap restores below average hunger and thirst.
Boiling sap makes a cloud of water vapor and syrup at a 12:1 ratio of sap to syrup

## Why / Balance
Trees aren't full of water, they're full of sap. Which may be mostly water, but is still a different substance.
Also water is slippery and having slippery blood is annoying for enemies at best and gets you/your friends killed at worst.

## Media

https://github.com/space-wizards/space-station-14/assets/140123969/9fdabd88-a365-48d8-9f3e-0f07058641c1

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added sap
- add: Added syrup, it can be made by boiling sap.
- tweak: Dionae now bleed sap instead of water

2024-03-01 21:27 UTC, mirrorcult commented
40:1 is pretty crazy i'd maybe make it 10:1

2024-03-30 02:45 UTC, LankLTE requested changes
I do think the slippery blood is not a bad thing, but this does probably make more sense and have funnier gameplay with the nymph sap farm. The ratio needs to be much less though or literally nobody will bother- I'd say anything higher than 10:1 or 15:1 is unreasonable.

2024-03-30 02:45 UTC, LankLTE commented on Resources/Prototypes/Recipes/Reactions/single_reagent.yml
> +    Syrup: 0.03 #40:1 ratio based on real syrup production
Being realistic probably doesn't make for good gameplay- imho make this higher or nobody will bother.

2024-04-05 21:04 UTC, LankLTE commented on Resources/Prototypes/Recipes/Reactions/single_reagent.yml
> +    Syrup: 0.03 #40:1 ratio based on real syrup production
Honestly I don't think the nerfs to slowdown, hunger, and such were necessary but w/e

2024-04-05 21:05 UTC, LankLTE approved these changes

2024-04-05 21:06 UTC, merged

2024-04-06 00:56 UTC, baddiePRO commented
wake up babe, diona sap just got merged