Species Guidebook Infobutton
space-wizards/space-station-14 pull request #25844
Opened 2024-03-04 22:07 UTC by Errant-4

## About the PR
Wouldn't it be great if we had Species info in the Guidebook?
Wouldn't it be even better if this was available in the character editor? Now there will be an info button next to the species selection dropdown, complete with hover tooltip. Pressing the button opens the relevant Guidebook page and also loads the other species pages, so the player can click check them all without having to change species in the character editor.

This is currently in draft because the integration/functionality is done but the actual Guidebook pages are mostly... rough

... also it turns out the Guidebook looks _awful_ when opened over the profile editor, due to being the same color and not having any visible borders. Is that something I also need to fix? Or can I declare that Somebody Else's Problem?

## Media
![Screenshot from 2024-03-04 22-21-36](https://github.com/space-wizards/space-station-14/assets/35878406/9259f2e3-273f-4fc3-bc26-3376f7807f2e)

![Screenshot from 2024-03-04 22-11-16](https://github.com/space-wizards/space-station-14/assets/35878406/021ddb9c-c64a-4aa4-a827-04d9527fcdd7)

![Screenshot from 2024-03-04 22-11-34](https://github.com/space-wizards/space-station-14/assets/35878406/90953fbc-d264-4908-ad20-ace690a296c0)

![Screenshot from 2024-03-04 22-12-08](https://github.com/space-wizards/space-station-14/assets/35878406/b52e9c05-141c-4078-9ec6-d34318c5d35b)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Errant
- add: Species info is now available in the Guidebook and in the character editor.

2024-03-05 04:47 UTC, Cojoke-dot commented
This would be nice, but I think the bullet point for the stats is not a great idea

2024-03-05 09:44 UTC, Errant-4 commented
Info icon was made smaller, and is no longer displayed for species that don't have a guidebook page

![image](https://github.com/space-wizards/space-station-14/assets/35878406/3c12f582-2dde-4f75-b738-8499f6968a4a)

2024-03-05 20:29 UTC, LankLTE commented
Gonna give a few nitpicks about stuff that should be in the guidebook page, but past that good addition (and honestly overdue)

2024-03-05 20:40 UTC, LankLTE requested changes
Took a quick look. Mostly minor things but ideally anything gameplay affecting should be logged here, both for players & so they're actually written down somewhere.

2024-03-05 20:40 UTC, LankLTE commented on Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
Generally don't make unrelated changes like this. Fine since it's minor, but for the future avoid this.

2024-03-05 20:40 UTC, LankLTE commented on Resources/ServerInfo/Guidebook/Mobs/Arachnid.xml
Arachnids suffocate 1.5x faster and have blue blood (needs copper to heal).

2024-03-05 20:40 UTC, LankLTE commented on Resources/ServerInfo/Guidebook/Mobs/Moth.xml
Insect blood is worth mentioning. Currently not regenerated by copper, iron, or anything of the sort afaik.

2024-03-05 20:40 UTC, LankLTE commented on Resources/ServerInfo/Guidebook/Mobs/Reptilian.xml
Should mention their diet restriction (can only eat foods with meat and fruit).

2024-03-05 20:40 UTC, LankLTE commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  They take [color=#1e90ff]30% less Blunt damage and 20% less Slash damage[/color]; but [color=#ffa500]50% more Heat damage, 20% more Shock damage, and they easily catch on fire.[/color]
I'd explicitly say that high heat damage can ignite them as that's fairly unique.

2024-03-05 20:40 UTC, LankLTE commented on Resources/ServerInfo/Guidebook/Mobs/SlimePerson.xml
Slimes suffocate a lot slower (about 20% of the normal speed), take more brute damage in space, and are hurt by water.

2024-03-05 20:44 UTC, Errant-4 commented on Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
I did not see that as an unrelated change, but rather fixing some obsolete pieces in a file I happened to already touch as part of my PR. I thought that's something to actively aspire to. Am I mistaken?

2024-03-05 20:48 UTC, LankLTE commented on Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
PR guidelines say that fixes should be in a separate PR- but given this isn't breaking anything nor does it make it more difficult to review, it's probably fine.

2024-03-11 03:00 UTC, LankLTE approved these changes

2024-03-11 03:01 UTC, merged

2024-03-11 04:19 UTC, metalgearsloth commented on Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
> +
There's some weird code in this pr but I'll just fix it in my loadouts pr.