Recipe books
space-wizards/space-station-14 pull request #25865
Opened 2024-03-05 17:15 UTC by TheShuEd

## About the PR
adds a system of forgotten recipes. To craft such things, you must first study a special book that unlocks these recipes.

- [x] storing learned recipes in the mind
- [x] a system that lets you learn new recipes
- [x] a system that prevents you from crafting unlearned items.
- [ ] a system that hides recipes from the player that he has not yet studied
- [ ] a small portion of content in the form of new crafting recipes, and books that teach these recipes.

## Why / Balance
PR as part of the system for the future librarian rework
https://github.com/space-wizards/docs/pull/173

## Media

https://github.com/space-wizards/space-station-14/assets/96445749/3d5b9ab9-2e95-4c00-90e9-57e70b253bf0

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
later
:cl:
- add: Added fun!

2024-03-05 21:05 UTC, notquitehadouken commented
tiders when they can't craft 8000 bats roundstart:

2024-03-05 23:47 UTC, K-Dynamic commented
Time to raid the library like it's Project Zomboid :trollface:

2024-03-06 01:01 UTC, Hanzdegloker commented
love this, but I fear books being stolen or hoarded, perhaps a printing press machine that is librarian locked that can print copies for a price? A cheap price but a price. late join librarian could mean a RANSACKED library so yeah, also book loaning and just filling up spares would be nice using the press.

2024-03-06 01:07 UTC, TheShuEd commented
I think that all libraries will have to be rebuilt, perhaps blocking half of the bookcases behind librarian access.  So he can have more personal space to work with books

2024-03-06 01:51 UTC, K-Dynamic commented
> love this, but I fear books being stolen or hoarded, perhaps a printing press machine that is librarian locked that can print copies for a price? A cheap price but a price. late join librarian could mean a RANSACKED library so yeah, also book loaning and just filling up spares would be nice using the press.

Let librarians print books maybe

2024-03-06 01:53 UTC, TheShuEd commented
Sound like a real work for librarian! Hit book thiefs, keep the library is clean, and give people recipes

2024-03-06 03:26 UTC, thymol-blue commented
Does this work for construction as well (e.g need to read a book to build a girder)? Also can we make the book consumable somehow? This would be fantastic for downstream!

2024-03-06 04:40 UTC, Hanzdegloker commented
this kinda open pandora's box of, imagine role starting knowledge like, Engineers round start can make walls and grilles but nobody outside of engie can unless they learn it from the library.

2024-03-06 05:52 UTC, thymol-blue commented
Not for SS14 that would be a slippery slope indeed but it would be nice for downstream which is exactly what you described. In CM-13 only certain roles can build stuff (e.g only ComTechs and engineers can build barricades and set up APCs) but your average marine can't.

I was thinking of a way to do this in CM-14 when bam this PR showed up! It is cool if you don't get to it though, just would be nice to have the options and flexibility if you ever get to it. Sorry for sort of derailing this.

2024-03-06 14:29 UTC, Tayrtahn requested changes
Just a few typos and a comment tweak.

2024-03-06 14:29 UTC, Tayrtahn commented on Content.Client/Construction/ConstructionSystem.cs
> +        public bool IsUserRecipeLeared(EntityUid user, string recipe)
```suggestion
        public bool IsUserRecipeLearned(EntityUid user, string recipe)
```

2024-03-06 14:29 UTC, Tayrtahn commented on Content.Shared/Mind/SharedRecipesUnlockSystem.cs
> +                Text = Loc.GetString("paper-recipe-learning-verb-text", ("item",_proto.Index(item).Name)),
```suggestion
                Text = Loc.GetString("paper-recipe-learning-verb-text", ("item", _proto.Index(item).Name)),
```

2024-03-06 14:29 UTC, Tayrtahn commented on Content.Shared/Mind/SharedRecipesUnlockSystem.cs
> +    public bool IsMindRecipeLeared(EntityUid mind, string recipe, MindLearnedRecipesComponent? comp = null)
```suggestion
    public bool IsMindRecipeLearned(EntityUid mind, string recipe, MindLearnedRecipesComponent? comp = null)
```

2024-03-06 14:29 UTC, Tayrtahn commented on Content.Shared/Mind/SharedRecipesUnlockSystem.cs
> +    public bool IsUserRecipeLeared(EntityUid user, string recipe, MindLearnedRecipesComponent? comp = null)
```suggestion
    public bool IsUserRecipeLearned(EntityUid user, string recipe, MindLearnedRecipesComponent? comp = null)
```

2024-03-06 14:29 UTC, Tayrtahn commented on Content.Shared/Mind/SharedRecipesUnlockSystem.cs
> +        return IsMindRecipeLeared(mind.Value, recipe);
```suggestion
        return IsMindRecipeLearned(mind.Value, recipe);
```

2024-03-06 14:29 UTC, Tayrtahn commented on Content.Shared/Paper/PaperRecipeTeacher.cs
> +    public LocId PopupText = "paper-recipe-leaning-start";
```suggestion
    public LocId PopupText = "paper-recipe-learning-start";
```

2024-03-06 14:29 UTC, Tayrtahn commented on Resources/Locale/en-US/paper/paper-recipe-learning.ftl
> +paper-recipe-leaning-start = You immerse yourself in the reading, learning how to create a {$item}.
```suggestion
paper-recipe-learning-start = You immerse yourself in the reading, learning how to create a {$item}.
```

2024-03-06 14:29 UTC, Tayrtahn commented on Content.Client/Construction/ConstructionSystem.cs
> +            return _recipeUnlock.IsUserRecipeLeared(user, recipe);
```suggestion
            return _recipeUnlock.IsUserRecipeLearned(user, recipe);
```

2024-03-06 14:29 UTC, Tayrtahn commented on Content.Server/Construction/ConstructionSystem.Initial.cs
> +            if (constructionPrototype.NeedLearn && !_recipeUnlock.IsUserRecipeLeared(user, constructionPrototype.ID))
```suggestion
            if (constructionPrototype.NeedLearn && !_recipeUnlock.IsUserRecipeLearned(user, constructionPrototype.ID))
```

2024-03-06 14:29 UTC, Tayrtahn commented on Content.Server/Construction/ConstructionSystem.Initial.cs
> +            if (constructionPrototype.NeedLearn && !_recipeUnlock.IsUserRecipeLeared(user, constructionPrototype.ID))
```suggestion
            if (constructionPrototype.NeedLearn && !_recipeUnlock.IsUserRecipeLearned(user, constructionPrototype.ID))
```

2024-03-06 14:29 UTC, Tayrtahn commented on Content.Shared/Construction/Prototypes/ConstructionPrototype.cs
> +    /// Should the player learn the crafting of this item?
```suggestion
    /// Does the player need to learn the recipe to be able to craft this item?
```

2024-03-06 17:13 UTC, keronshb commented
> this kinda open pandora's box of, imagine role starting knowledge like, Engineers round start can make walls and grilles but nobody outside of engie can unless they learn it from the library.

I would imagine this isn't the use case.  All current crafts wouldn't be included (weapons, walls, etc). The same would go for most future crafts. This is more for specific cases - like an improved maint shotgun or maybe antagonist exclusive construction.

2024-03-06 19:35 UTC, baddiePRO commented
> love this, but I fear books being stolen or hoarded, perhaps a printing press machine that is librarian locked that can print copies for a price? A cheap price but a price. late join librarian could mean a RANSACKED library so yeah, also book loaning and just filling up spares would be nice using the press.

give all library books a GPS tracker, and librarian gets a computer to track down any book with a tracker in it?

2024-03-08 00:47 UTC, TheShuEd commented
![image](https://github.com/space-wizards/space-station-14/assets/96445749/88397c9b-20f9-4025-adea-8c837c4864b0)

2024-03-08 01:52 UTC, Tayrtahn reviewed
For the record, "crumbs" is a somewhat odd word choice (generally associated with food), but I actually kinda like it, since the weirdness fits with the mysticism of these items.

2024-03-08 01:52 UTC, Tayrtahn commented on Resources/Prototypes/Recipes/Construction/forgotten.yml
> +  description: Crumbs of unknown energies will keep you from electricy.
```suggestion
  description: Crumbs of unknown energies will protect you from electricity.
```

2024-03-08 01:52 UTC, Tayrtahn commented on Resources/Prototypes/Recipes/Construction/forgotten.yml
> +  description: Crumbs of unknown energies will keep you from the poisons.
```suggestion
  description: Crumbs of unknown energies will protect you from poison.
```

2024-03-08 01:52 UTC, Tayrtahn commented on Resources/Prototypes/Recipes/Construction/forgotten.yml
> +  description: Crumbs of unknown energies will keep you out of the cosmic cold.
```suggestion
  description: Crumbs of unknown energies will protect you from the cosmic cold.
```

2024-03-08 01:52 UTC, Tayrtahn commented on Resources/Prototypes/Recipes/Construction/forgotten.yml
> +  description: Crumbs of unknown energies will keep you out of the fire.
```suggestion
  description: Crumbs of unknown energies will protect you from fire.
```

2024-03-08 01:52 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Clothing/Neck/amulets.yml
> +  description: Crumbs of unknown energies will keep you from electricy.
```suggestion
  description: Crumbs of unknown energies will protect you from electricity.
```

2024-03-08 01:52 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Clothing/Neck/amulets.yml
> +  description: Crumbs of unknown energies will keep you from the poisons.
```suggestion
  description: Crumbs of unknown energies will protect you from poison.
```

2024-03-08 01:52 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Clothing/Neck/amulets.yml
> +  description: Crumbs of unknown energies will keep you out of the cosmic cold.
```suggestion
  description: Crumbs of unknown energies will protect you from the cosmic cold.
```

2024-03-08 01:52 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Clothing/Neck/amulets.yml
> +  description: Crumbs of unknown energies will keep you out of the fire.
```suggestion
  description: Crumbs of unknown energies will protect you from fire.
```

2024-04-06 09:04 UTC, TheShuEd commented
maybe later

2024-04-06 09:04 UTC, closed without merging