Add a handy security radio
space-wizards/space-station-14 pull request #25913
Opened 2024-03-07 18:20 UTC by Ramlik

## About the PR
I've always wanted to have a handy security radio in game and I thought it would be cool to have one in game.

## Why / Balance
This could help security guards in game for communication and give a good opportunity to all humanoid antagonists to listen all the talks of security through it. 

## Technical details
This walkie talkie works the same way as handheld one, but this one has recolored sprite and uses security channel.

## Media
https://youtu.be/VQOLiTQAmKc?si=IoeRN4mHT9vDIcIG

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes
Unless the prototype and/or sprites won't be loaded in game everything should work fine. Everything is tested on local server.

**Changelog**
:cl:

2024-03-07 18:48 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Devices/securityradio.yml
dont create a new file, just put that radio next to the existing one

2024-03-07 18:49 UTC, lzk228 requested changes
more requests
- use default radio as a parent
- make a new .rsi file and make the same png names in both files, so you shouldnt change them in sec radio (theyll inherit from parent)

2024-03-07 19:43 UTC, Brandon-Huu commented
So just a more annoying chat that can't be sabotaged?

2024-03-07 19:59 UTC, Hanzdegloker commented
> So just a more annoying chat that can't be sabotaged?

I mean, yeah

2024-03-07 20:39 UTC, UbaserB commented
i feel like the sprite needs improving, its too shiny

2024-03-08 05:48 UTC, Krunklehorn commented
Why is this security specific? Why not just change handheld radios to take encryption keys?

2024-03-08 17:34 UTC, IProduceWidgets commented
I think it would be better to make handheld radios have changeable frequencies, but iirc there was a PR for that which got mothballed.

2024-03-13 08:41 UTC, metalgearsloth requested changes

2024-03-13 08:41 UTC, metalgearsloth commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
>        - id: FlashlightSeclite
Put it in the vendor it's not essential for sec role.

2024-04-27 13:27 UTC, metalgearsloth approved these changes

2024-04-27 13:27 UTC, merged