Implement vital chef's hat functionality
space-wizards/space-station-14 pull request #25950
Opened 2024-03-09 21:34 UTC by Tayrtahn

![chefhat](https://github.com/space-wizards/space-station-14/assets/85356/33a4fb54-c46b-4148-a857-eff5c4ec5d84)

## About the PR

If you put a player-controlled mouse or hamster into a chef's hat and wear it, the mouse/hamster will be able to control your movement. Obviously.

The wearer does still have control as well, and movement prediction is disabled on the wearing character, so have fun trying to coordinate movement!

## Why / Balance

I noticed that the chef's hat has an inventory that fits a single tiny item, and that mice are tiny items. I tried it and was disappointed to see that this wasn't already a feature. So now it is.

## Technical details

Adds PilotedClothingComponent, which is uses InputRelay to set up a connection from the pilot to the wearer. The connection is shut down if the clothing is unequipped or the pilot leaves the clothing's storage. Both the wearer and the pilot are able to steer the character.

Adds PilotedByClothingComponent to the wearer while the connection is active. This just disables physics prediction for the wearer. Trust me, it feels awful with prediction on. The delay from having it unpredicted adds to the effect anyway.

Adds a tag "ChefPilot" and gives it to mice and hamsters. PilotedClothingSystem uses a whitelist to validate that this tag is on a potential pilot.

## Media

https://github.com/space-wizards/space-station-14/assets/85356/f59d5905-057a-4e17-a220-7ae773c9b040

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Mice and hamsters inside chef's hats can now steer the hat's wearer.

2024-03-09 22:02 UTC, Cojoke-dot commented
This pr... this is a perfect idea...

2024-03-10 00:56 UTC, TheShuEd commented
sounds like a rather complex mechanic that is very narrowly applicable and not reusable.  Does your implementation support possible future antagonists like a brain worm or possession as a mechanic for controlling other entities?  Or is it strictly fixed to the conditions of clothing slots

2024-03-10 01:08 UTC, ike709 commented
> sounds like a rather complex mechanic that is very narrowly applicable and not reusable. 

You have described... Space Station 13

2024-03-10 02:05 UTC, Tayrtahn commented
> sounds like a rather complex mechanic that is very narrowly applicable and not reusable.  Does your implementation support possible future antagonists like a brain worm or possession as a mechanic for controlling other entities?  Or is it strictly fixed to the conditions of clothing slots

The way it's implemented, it is limited to the "pilot" being inside a clothing item and the clothing item being worn by the person being controlled.

But the reusable system already existed with the InputRelay system, which is used for transferring control from pilots to mechs. This just bridges a couple of gaps to reuse that functionality for this specific case.

It would definitely be possible to implement a brain worm with InputRelay in a way pretty similar to this (and I might look into that), but I think the differences are significant enough to deserve separate implementations.

2024-03-10 04:10 UTC, slarticodefast commented
This idea is amazing. Could you add cockroaches and mothroaches to the pilots as well?

2024-03-10 04:57 UTC, beck-thompson commented
Vital PR

2024-03-10 21:37 UTC, Tayrtahn commented
> Could you add cockroaches and mothroaches to the pilots as well?

I'm going to keep it limited to rodents for now, but I encourage you or anyone else to submit a follow-up PR for that change if this gets merged.

2024-03-11 03:34 UTC, Plykiya commented
mothroaches as hats should let them pilot people as well

2024-03-11 09:41 UTC, Hmeister-real commented
> On a side note, if anyone adds a larger chef's hat that can fit a raccoon, they'll have my support instantly

Rat king sized chef hat :godo:

2024-03-11 13:00 UTC, asperger-sind commented
Speaking of the prediction, wouldn't this affect players with high ping more than those with less ping? Iirc devbuild has simulated delay of around 185ms so this perhaps didn't come up during testing.

2024-03-25 08:12 UTC, metalgearsloth requested changes
I wonder if this would be better served as a generic vehicle system to relay movement inputs instead of having:
- jetpacks
- pilotedclothing
- shuttle
- vehicle 2.0 + cardboard box + mechs.

Specifically by splitting the component into one for being a vehicle and another for being a vehicle able to be piloted via clothing?

2024-03-25 08:12 UTC, metalgearsloth commented on Content.Shared/Clothing/EntitySystems/PilotedClothingSystem.cs
> +            return;
HasFlag allocates on debug just manually do a bitmask check.

2024-03-25 08:12 UTC, metalgearsloth commented on Content.Shared/Clothing/Components/PilotedClothingComponent.cs
> +    /// <summary>
Just remove it if it doesn't work.

2024-03-25 18:54 UTC, Tayrtahn commented on Content.Shared/Clothing/Components/PilotedClothingComponent.cs
> +
Huh, didn't know sourcegen could do that. Neat.

2024-03-26 18:12 UTC, Tayrtahn commented
> I wonder if this would be better served as a generic vehicle system to relay movement inputs instead of having:
> 
> * jetpacks
> * pilotedclothing
> * shuttle
> * vehicle 2.0 + cardboard box + mechs.
> 
> Specifically by splitting the component into one for being a vehicle and another for being a vehicle able to be piloted via clothing?

You're just trying to dupe me into doing the vehicle refactor, aren't you? 😛 

You make a good point though; all those systems probably could be combined. I can look into doing that, but for now I've just fixed the specific issues you pointed out.

2024-05-10 15:53 UTC, Emisse commented
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

2024-06-14 00:48 UTC, GroggleG commented
The completion and merge of this PR is vital to my mental health

2024-06-15 18:02 UTC, Kadeo64 commented
holy shit SSD people can now be used for something useful

2024-06-18 10:59 UTC, metalgearsloth commented
The lack of prediction is pretty bad but I don't think there's an easy way around having 2 players control the same mob so.

2024-06-18 10:59 UTC, metalgearsloth approved these changes

2024-06-18 10:59 UTC, merged

2024-07-30 05:15 UTC, justdie12 commented
Uploading 2024-07-30 08-12-23.mp4…

2024-07-30 05:16 UTC, justdie12 commented
Uploading 2024-07-30 08-12-23.mp4…

2024-07-30 05:26 UTC, justdie12 commented
Uploading 2024-07-30 08-12-23_compressed.mp4…

2024-07-30 05:30 UTC, justdie12 commented
https://drive.google.com/file/d/1NKXE98TCdvA54PwMnsqiG5EBZmyfXvPm/view?usp=sharing
watch video, i cant upload it here.

2024-07-30 05:35 UTC, Cojoke-dot commented
> https://drive.google.com/file/d/1NKXE98TCdvA54PwMnsqiG5EBZmyfXvPm/view?usp=sharing watch video, i cant upload it here.

That is a known bug
#29288

2024-07-30 06:05 UTC, justdie12 commented
> > https://drive.google.com/file/d/1NKXE98TCdvA54PwMnsqiG5EBZmyfXvPm/view?usp=sharing watch video, i cant upload it here.
> 
> That is a known bug #29288

what about ghost movement? maybe just use a bit of RIPLEY code?

2024-07-30 06:19 UTC, Cojoke-dot commented
> what about ghost movement?

I don't think that's a bug and if it was it would not get fixed, its kinda funny and an admin would have to cause it anyway.

2024-07-30 06:31 UTC, justdie12 commented
> > what about ghost movement?
> 
> I don't think that's a bug and if it was it would not get fixed, its kinda funny and an admin would have to cause it anyway.

i think what author need to use RIPLEY code instead, cuz' now its so laggy tbh
and he needs to add hands and other interface to mouse, in Ratatouille Remi can control hands and oher stuff

2024-07-30 06:33 UTC, Cojoke-dot commented
> i think what author need to use RIPLEY code instead, cuz' now its so laggy tbh and he needs to add hands and other interface to mouse, in Ratatouille Remi can control hands and oher stuff

It's using the RIPLEY code, it feels laggy because predictions are turned off so it does not look like your player is teleporting constantly. I agree about that hands but... wyci 🙃