chili/chilly peppers sprite alignment fix & minor refactorization
space-wizards/space-station-14 pull request #25971
Opened 2024-03-10 17:03 UTC by Gyrandola

## About the PR

Chilly pepper sprite was way off-centered, turns out the normal chili sprite wasn't perfectly aligned as well.
Refactored the names and IDs to make it clear they're both peppers.

## Why / Balance

Fixes #25019.
New naming is clearer.

## Technical details

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![Screenshot 2024-03-10 171917](https://github.com/space-wizards/space-station-14/assets/62253058/85a53d6c-9d74-41ed-83cc-29b601696d87)

## Breaking changes

**Changelog**

:cl:
- fix: Pepper sprites are now properly centered!

2024-03-10 22:40 UTC, potato1234x commented
name change is kinda unnecessary its pretty obvious theyre peppers

2024-03-10 22:42 UTC, Luxzhv commented
> name change is kinda unnecessary its pretty obvious theyre peppers

Better to just have it, to also be ready for Bell Peppers and Pepper corns whenever someone gets around to it.

2024-03-10 22:59 UTC, Tayrtahn commented
I've seen "chili" in the files and assumed it was the stew, so I agree that the change is good.

2024-03-13 03:50 UTC, EmoGarbage404 requested changes

2024-03-13 03:50 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
> +  id: FoodChiliPepper
you need to add entries to migrations.yml for both of these prototypes.

2024-04-20 02:06 UTC, merged