Working flashlight for hard hats
space-wizards/space-station-14 pull request #2599
Opened 2020-11-21 11:25 UTC by Macoron

![hard-hats](https://user-images.githubusercontent.com/6161335/99876031-31fc2980-2c05-11eb-80b8-1f77cfff7308.gif)
Continue #2362

Now hard hats have working flashlight. It use same component as original flashlight. 
Add verb to toggle off/on flashlight.

Moved hard hats sprites names to "off-on" prefix. Also add enabled light effect for some sprites.
Now ClothingEquippedPrefix will update players sprite when changed.

2020-11-22 03:38 UTC, metalgearsloth requested changes

2020-11-22 03:38 UTC, metalgearsloth commented on Content.Client/GameObjects/Components/Clothing/ClothingComponent.cs
> +                _clothingEquippedPrefix = value;
```suggestion
                if (_clothingEquippedPrefix == value)
                    return;

                _clothingEquippedPrefix = value;
```

2020-11-22 03:38 UTC, metalgearsloth commented on Content.Client/GameObjects/Components/Clothing/ClothingComponent.cs
> +            }
```suggestion
            get => _clothingEquippedPrefix;
```

2020-11-22 03:38 UTC, metalgearsloth commented on Content.Client/GameObjects/Components/HUD/Inventory/ClientInventoryComponent.cs
> +        }
Would be better to have the file marked as nullable and return a null slot instead IMO.

```suggestion
        public bool TryFindItemSlots(IEntity item, [NotNullWhen(true)] out Slots? slots)
        {
            slots = null;
        
            foreach (var (slot, entity) in _slots)
            {
                if (entity == item)
                {
                    slots = slot;
                    return true;
                }
            }

            return false;
        }
```

2020-11-22 08:10 UTC, Macoron commented
Fixed merge conflicts with latest master and also added suggested changes.
Ready for review.

2020-11-23 03:17 UTC, merged

2020-11-24 05:01 UTC, SweptWasTaken commented
Good PR :)