Adds new "Short-Sighted" trait!
space-wizards/space-station-14 pull request #26037
Opened 2024-03-12 10:47 UTC by Moomoobeef

## About the PR
There is now a trait for short-sightedness. Your vision is severely degraded compared to normal vision, however it is not considered legally blind, and glasses do help your condition considerably!

Welding will still damage your eyesight further, and oculine can be used to recover additional damage back to where you started, you cannot however cure your eyes completely no matter how many carrots you eat.

With this trait you start with glasses, similar to how blindness starts you with a cane. I'm still open to input on whether you should start with glasses or not, as glasses _are_ pretty easy to find.

## Why / Balance
I thought it would be cool. And for those who liked roleplaying as disabled persons, you now have yet another way to do so without crippling yourself quite as much.

## Technical details

BlindableComponent and BlindableSystem now have MinDamage, which works exactly the same as MaxDamage but the opposite.
Setting MinDamage is done through a call to BlindableSystem, and in order to avoid repeating ourselves, updating blindness is now handled by its own method which is called by both AdjustEyeDamage and SetMinDamage.

I'd like to thank ShadowCommander who was indispensable during the coding process, and informed me of some useful resources as well.

## Media
With glasses:
![2024-03-12_03-11](https://github.com/space-wizards/space-station-14/assets/62638182/30199cc2-a837-46ec-9975-a7f378cb2835)

Without:
![2024-03-12_03-11_1](https://github.com/space-wizards/space-station-14/assets/62638182/b0bea800-237d-497b-8490-f13da5b206f4)

There are 9 levels of blindness, the blindness trait sets level 9, this is level 4. I did consider making it 3 instead, I'd like input on whether it should be 4 or 3.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
I don't _think_ this should break anything, BlindableSystem was changed quite a bit, however all calls should behave exactly the same as before, and everything worked in testing. That said I also am not particularly knowledgeable.

**Changelog**
:cl:
- add: CentCom has now started hiring crew who are short-sighted.

2024-03-12 10:49 UTC, UbaserB commented
Does the character have a custom description? Like with blindness and how their eyes are glassy.

2024-03-12 10:49 UTC, Moomoobeef commented
No, I took that out as you can't really tell that someone is short-sighted from looking at them...

2024-03-12 10:50 UTC, UbaserB commented
> No, I took that out as you can't really tell that someone is short-sighted from looking at them...

you could say their eyes scatter or they cant focus well **when the glasses are not equipped**

2024-03-12 10:51 UTC, Moomoobeef commented
I suppose. If folks really want I can look into implementing that tomorrow morning.

2024-03-12 11:48 UTC, Tayrtahn commented
What would make this really fun for me would be if glasses almost completely corrected for this, but were breakable and took damage when the wearer did. Maybe they could even fall off if the wearer gets hit hard enough. So you're basically fine until suddenly you're stumbling around looking for them like Velma.

That sounds like a separate PR though.

2024-03-12 15:44 UTC, DoutorWhite commented
The effect looks a little more like astigmatism, but it's very good.

2024-03-12 18:31 UTC, deathride58 reviewed
The blindness trait should probably be made to use the PoorVisionComponent (or alternatively, the blindness trait's system should be made to make use of the new MinDamage variable)

2024-03-13 21:43 UTC, pigeonpeas commented
> > No, I took that out as you can't really tell that someone is short-sighted from looking at them...
> 
> you could say their eyes scatter or they cant focus well **when the glasses are not equipped**

you could say they are squinting! i usually squint a lot when i don't have my glasses..

2024-03-17 05:20 UTC, Moomoobeef commented
I completely forgot about this PR, I seem to do that a lot. I'm gonna try and work on the feedback I've been given and have another commit out probably tomorrow. If I go another 2/3 days without anything please message me on discord because chances are if that happens that I forgot again.

2024-03-17 06:08 UTC, Nopey commented
> add: CentCom has now started hiring crew who are short-sighted.

The changelog would benefit from being more direct, and OOC; perhaps something like:
> add: Added new "Short-Sighted" trait, which impedes your vision.

Reference: https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#writing-an-effective-changelog

2024-03-25 07:44 UTC, Moomoobeef commented
changed PermanentBlindnessSystem to use the new MinDamage like you suggested, making the system much simpler. I considered making it where there's some examine text when you examine someone short-sighted who is not wearing glasses but imo that doesn't really make sense, you wouldn't be able to tell someone is short-sighted by looking at them. Plus I couldn't actually figure out how to implement it so that you only see that _when they aren't wearing glasses._

2024-03-25 13:22 UTC, metalgearsloth submitted a review, later dismissed

2024-03-25 13:22 UTC, metalgearsloth commented on Content.Shared/Traits/Assorted/PermanentPoorVisionSystem.cs
> +    [Dependency] private readonly IEntityManager _entityManager = default!;
This is already a dependency on systems.

2024-03-25 13:22 UTC, metalgearsloth commented on Content.Shared/Eye/Blinding/Components/BlindableComponent.cs
>      public const int MaxDamage = 9;
Same here

2024-03-25 13:22 UTC, metalgearsloth commented on Content.Shared/Eye/Blinding/Systems/BlindableSystem.cs
>  }
There's no reason to make UpdateEyeDamge public, additionally setting the min / max should be clamping it and not just clamping if the max changes.

2024-03-25 13:22 UTC, metalgearsloth commented on Content.Shared/Eye/Blinding/Components/BlindableComponent.cs
> +
VVRW is redundant.

2024-03-25 13:22 UTC, metalgearsloth commented on Content.Shared/Traits/Assorted/PermanentBlindnessSystem.cs
> +        _blinding.SetMinDamage(new Entity<BlindableComponent?>(blindness.Owner, blindable), maxMagnitudeInt);
This should be done on mapinit not compstartup as it will break with save/load.

2024-03-25 13:22 UTC, metalgearsloth commented on Content.Shared/Traits/Assorted/PermanentPoorVisionComponent.cs
> +
MinDamage shouldn't be a field on both components, choose 1 to use.

2024-03-25 13:22 UTC, metalgearsloth commented on Content.Shared/Traits/Assorted/PermanentPoorVisionSystem.cs
> +}
Same here.

2024-04-29 04:02 UTC, mirrorcult commented
are you planning to come back to this?

2024-04-29 05:22 UTC, Moomoobeef commented
I legitimately forgot about it. I also have had a lot going on in the last few weeks, but I'll try to finish it up soon.

2024-05-03 03:47 UTC, Moomoobeef commented
I forgot again. shoot me
anyway I actually opened vscode this time (wow) and I'm gonna work on it now

2024-05-05 18:10 UTC, Moomoobeef commented
ba-bam

2024-05-08 00:26 UTC, mirrorcult requested changes

2024-05-08 00:26 UTC, mirrorcult commented on Content.Shared/Eye/Blinding/Components/BlindableComponent.cs
> +
why isnt this a datafield

2024-05-08 00:26 UTC, mirrorcult commented on Content.Shared/Traits/Assorted/PermanentPoorVisionSystem.cs
> +
```suggestion
```

2024-05-08 19:26 UTC, Moomoobeef commented
I don't know why the build check failed when it didn't before, as far as I can tell there's nothing wrong with the changes I made, but evidently there is...

2024-05-09 06:29 UTC, mirrorcult commented
test is just heisenbug

2024-05-09 06:31 UTC, mirrorcult requested changes

2024-05-09 06:31 UTC, mirrorcult commented on Content.Shared/Traits/Assorted/PermanentPoorVisionSystem.cs
> +}
is this not literally identical to `PermanentBlindness` but just with a different minimum damage value, why not merge those two components and just change the value in a datafield

2024-05-09 06:31 UTC, mirrorcult commented
will get to this tomorrow if review not done since its fairly simple

2024-05-09 22:32 UTC, Moomoobeef commented
I've made modifications so that permanentBlindness handles both blindness and short-sightedness traits, I'm just waiting on some help for one little problem and then I'll commit it.

2024-05-10 01:40 UTC, mirrorcult approved these changes

2024-05-10 01:40 UTC, merged