Fix recycled containers deleting items inside them
space-wizards/space-station-14 pull request #26045
Opened 2024-03-12 16:16 UTC by SlamBamActionman

## About the PR

Right now you can delete any item that fits in a survival box by placing it inside of one and then recycling the box in a Recycler/Material Reclaimer. This PR fixes this by dumping out any item inside containers.

- For Reclaimers,  any recyclable items inside the container get placed on top of the Reclaimer.
- For Recyclers, any recyclable items inside the container get recursively recycled as well.

## Why / Balance

I doubt it's intended behavior to be able to effectively delete any item that fits in a box. Also ensures a recycled box provides the correct amount of material as its contents also get recycled.

## Technical details

When trying to recycle, once all checks are passed it iterates through the object's containers if it has any and dumps out any items onto the machine doing the recycling.

## Media

![image](https://github.com/space-wizards/space-station-14/assets/83650252/9e95b099-ab95-449d-b5a1-25b80afda8cd)
The result of recycling a survival box in a Recycler/Reclaimer.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Containers no longer delete the items inside when recycled.

2024-03-12 16:48 UTC, HelpTheSteak commented
How am I gonna destroy all my contraband after I complete my objectives as thief now

2024-03-12 18:01 UTC, SlamBamActionman commented
> How am I gonna destroy all my contraband after I complete my objectives as thief now

Ngl I've done the same. It just feels like a kinda jank and unintended way to get rid of evidence, plus it provides little to no interesting gameplay for either side.

2024-03-12 18:06 UTC, deltanedas commented
> How am I gonna destroy all my contraband after I complete my objectives as thief now

tell the chaplain you found 4 among pequeno and you must personally incinerate them

2024-03-13 16:41 UTC, HelpTheSteak commented
> How am I gonna destroy all my contraband after I complete my objectives as thief now

But anyway I think this is actually a good change since det has more evidence to check now (unless they cremated it)

2024-03-15 02:51 UTC, ElectroJr requested changes

2024-03-15 02:51 UTC, ElectroJr commented on Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
> +                var containedEntites = cont.ContainedEntities.ToArray();
This shouldn't iterate over all containers, it has to be opt-in. Not all containers are there to store physical entities that can be dropped. E.g., "Actions" in the actions hotbar are also entities in containers.

Instead, this should behave more like entity destruction/breaking. I.e., raise an event, then let the storage & entity-storage systems handle that event.

2024-03-17 10:35 UTC, SlamBamActionman commented
This is the first time I'm making something new for the event system so let me know if there's something iffy with the implementation. Behavior seems to be replicated and working fine though.

2024-03-18 13:33 UTC, metalgearsloth commented on Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
> +        RaiseLocalEvent(item, ref reclaimedEvent);
use xformsystem, these methods do a bunch of resolves internally that are slow and not thread-safe.

2024-03-19 02:36 UTC, merged