metal pipe sound when body falls
space-wizards/space-station-14 pull request #26078
Opened 2024-03-13 12:10 UTC by Slava0135

## About the PR

## Why / Balance

## Technical details

## Media

https://github.com/space-wizards/space-station-14/assets/40753025/9a068857-3617-4f6d-8b85-f2c653b243d1

## Breaking changes

**Changelog**

2024-03-13 13:24 UTC, FairlySadPanda commented on Resources/Audio/Effects/attributions.yml
> +  source: "https://www.youtube.com/watch?v=iDLmYZ5HqgM"
It's a stock sound from prior to 1993 with unknown provenance. I wanted to add it in as a round restart sfx :(

2024-03-13 16:45 UTC, Slava0135 commented
https://youtu.be/cEf_hfDgIBo?si=FHrS7O-FbzyM3Tgg
Real source is unknown but according to this, it appeared in many games before it became popular in 2020. I think we are safe to use this (at least for april 1). Any thoughts?

2024-03-17 13:35 UTC, metalgearsloth requested changes
1. That video doesn't even have a license nor is it the original source.
2. I doubt we can use this.

2024-03-18 20:26 UTC, PJB3005 commented
Re-open when you can find the original sound CD from the 90s this came from lol.

2024-03-18 20:26 UTC, closed without merging

2024-03-24 11:38 UTC, Slava0135 commented
i think i found source for it

![image](https://github.com/space-wizards/space-station-14/assets/40753025/0dffbe39-366a-4f24-a125-906de6405ae8)

https://soundeffects.fandom.com/wiki/Sound_Ideas,_METAL,_DROP_-_METAL,_DROP_METAL_POLE:_LOUD_DROP_AND_BOUNCE_02

on their site it says its Roalty Free, though you need to buy it???
![image](https://github.com/space-wizards/space-station-14/assets/40753025/ed12c51a-5303-492e-90f2-4341d8ec987f)
https://www.sound-ideas.com/Product/198/L2-Sound-Effects-Library-by-Frank-Serafine

2024-03-24 11:44 UTC, Slava0135 commented
it was modified though (by Jixaw), they uploaded it on their second channel (without license though)
https://www.youtube.com/watch?v=kPWv44v0b04
![image](https://github.com/space-wizards/space-station-14/assets/40753025/fb8f76ca-86c3-4678-a821-92652e5f950f)

i wouldn't merge this into master, but for april 1st, i think its fine, if we just put link to this video (and i actually use audio file from there)

2024-03-24 11:52 UTC, Slava0135 commented
this though https://www.sound-ideas.com/Page/Sound-Ideas-End-User-License
![image](https://github.com/space-wizards/space-station-14/assets/40753025/921c1073-fd92-4544-bd96-cef152548c1b)

2024-03-24 11:57 UTC, Slava0135 commented
Assuming original sound comes from Sound Ideas, you need to buy license, so we are not allowed to use it.

I think they just don't care about videos
![image](https://github.com/space-wizards/space-station-14/assets/40753025/f422d3e1-f0be-4525-958a-bb7db45ca600)