Strobes added
space-wizards/space-station-14 pull request #26083
Opened 2024-03-13 15:18 UTC by Ko4ergaPunk

## About the PR
Added strobes. Example of use in the media.
Can be connected to a button. There is a type that makes sounds.

## Why / Balance
You can build a disco. That's not enough?

## Media

![ezgif-2-b7cacc41b3](https://github.com/space-wizards/space-station-14/assets/62609550/2e534bed-6dcf-4a1d-8556-2d717b1cdef8)

https://github.com/space-wizards/space-station-14/assets/62609550/0891a7b9-fe19-4d74-908b-9102b46e0d67

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Ko4erga
- add: Strobes added WEE-OOO-WEE-OOO!

2024-03-13 17:09 UTC, deathride58 requested changes
strobe.ogg needs attribution info in the attributions.yml

2024-03-13 17:11 UTC, CatMagic1 commented
oh epic

2024-03-13 22:42 UTC, potato1234x commented
make it spin faster and change colors :trollface:

2024-03-14 08:17 UTC, Ko4ergaPunk commented
> strobe.ogg needs attribution info in the attributions.yml

That's just policesiren, but modified

2024-03-14 11:47 UTC, Ko4ergaPunk commented
New ones. Only vanilla sounds, but modified


https://github.com/space-wizards/space-station-14/assets/62609550/a3175472-8d80-4d86-92c5-9fef5cbbb2b8

2024-03-14 22:12 UTC, Ko4ergaPunk reviewed
done

2024-03-18 14:50 UTC, metalgearsloth submitted a review, later dismissed

2024-03-18 14:50 UTC, metalgearsloth commented on Resources/Audio/Effects/Lightning/attributions.yml
> +  copyright: "Piotr Zaczek (blukotek) on freesound.org. Modified by Ko4erga"
strobeadmin still needs crediting.

2024-03-18 16:36 UTC, Ko4ergaPunk reviewed
Well, I don't know who made that sound. I take it from /Audio/Misc/adminlarm.ogg and made it more faster and cycled. Author is not listed in attributions

2024-03-22 07:15 UTC, metalgearsloth commented on Resources/Audio/Effects/Lightning/attributions.yml
> +  copyright: "Piotr Zaczek (blukotek) on freesound.org. Modified by Ko4erga"
You can't add new sounds with attribution, you need to find the original source or otherwise credit it properly.

2024-03-24 07:20 UTC, superjj18 commented
A way to change it's color would be wonderful, and could also be applied to the lights in the station according to the alert level

2024-04-07 15:37 UTC, Peptide90 commented
Grateful for this, will be good for airlocks and stuff but what happened to lightBehavior? Do we not use those anymore? Just seems odd to add another component specific to this when it should probably be a function of that.

2024-04-07 18:50 UTC, MACMAN2003 commented
it'd be nice to have the ability to change its color/spin speed

2024-04-10 18:27 UTC, Ko4ergaPunk commented
![merge](https://github.com/space-wizards/space-station-14/assets/62609550/137b6d1a-b184-4721-b112-ad0257e83d45)
I deleted /Audio/Misc/adminlarm.ogg

2024-04-12 07:58 UTC, TheShuEd approved these changes

2024-04-12 08:02 UTC, merged

2024-04-12 08:33 UTC, Peptide90 commented
Guess it was discussed on discord about why this wasn't a lightbehaviour?