New seats
space-wizards/space-station-14 pull request #26109
Opened 2024-03-14 09:33 UTC by JustArt1m

## About the PR
Adds sofas and bag chairs in 8 colors and 8 new comfy chair colors.

## Why / Balance
Just for a greater variety of decor.

## Media
![NewChairsUpdate](https://github.com/space-wizards/space-station-14/assets/123451459/097d1ee1-a266-450a-9db4-32c9eb9c5bbc)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Just_Art
- add: Added sofas of 8 colors!
- add: Added padded stools of 8 colors!
- add: Added comfy chairs of 8 colors!
- add: Added crafts for sofas, padded stools and comfy chairs!

2024-03-14 11:11 UTC, TheShuEd requested changes
first of all, I think these sprites are much worse than the one proposed here: #24123
![image](https://github.com/space-wizards/space-station-14/assets/96445749/a9bec28a-5b93-48b6-bdd0-38759d698fec)

Secondly, the problem of automatic sofa smoothing is not solved here either. The variant when corner, end and middle elements of the sofa are different entities is not accepted. They should automatically match each other depending on the turn and the neighbors. Like stairs in minecraft.

2024-03-14 12:28 UTC, ShadowCommander requested changes

2024-03-14 12:28 UTC, ShadowCommander commented on Resources/Prototypes/Entities/Structures/Furniture/chairs.yml
> +    node: blackChairComfy
Please use sprite layer variants instead of creating one sprite for each color. You can look at screwdrivers for how color layers work.

2024-03-14 15:58 UTC, Kit0vras commented
dont do a hubbabubbalion sprites. Just do a Grey scale sprites, (like crystals) and then paint they in prototype (like crystals)
after that, you can change the color to whatever you want right in the prototype by changing one line.

2024-03-15 10:22 UTC, TheShuEd requested changes

2024-03-15 10:22 UTC, TheShuEd commented on Resources/Textures/Structures/Furniture/chairs.rsi/comfy-overlay-greyscale.png
sprite is not used. If it were, the front and back views are blank

2024-03-15 10:22 UTC, TheShuEd commented on Resources/Textures/Structures/Furniture/chairs.rsi/pufi-overlay-greyscale.png
sprite is not used. If it were, the front and back views are blank

2024-03-15 10:22 UTC, TheShuEd commented on Resources/Textures/Structures/Furniture/chairs.rsi/comfy-greyscale.png
it's worth it to remove the sprite of the existing light-green seats, and make them the same way through repainting them in light green.

2024-03-15 10:22 UTC, TheShuEd commented on Resources/Textures/Structures/Furniture/chairs.rsi/pufi-greyscale.png
still look bad

2024-03-15 10:49 UTC, JustArt1m commented on Resources/Textures/Structures/Furniture/chairs.rsi/comfy-greyscale.png
What do you mean? There is no light green seat sprite in the game.

2024-03-15 11:27 UTC, TheShuEd commented on Resources/Textures/Structures/Furniture/chairs.rsi/comfy-greyscale.png
Bruh, i mean this sprite:
https://github.com/space-wizards/space-station-14/blob/10e099b01a34f94accc7809c2697959a6758efe7/Resources/Textures/Structures/Furniture/chairs.rsi/comfy.png

2024-03-15 22:31 UTC, Ko4ergaPunk commented
> The variant when corner, end and middle elements of the sofa are different entities is not accepted

Why fences don't have auto connect? 
![image](https://github.com/space-wizards/space-station-14/assets/62609550/ba6d183d-e59c-490a-8057-50cc4142f003)
We'll be waiting for nEw FeAtUrEs while missing out cool things.

2024-03-15 22:56 UTC, TheShuEd commented
ask Sloth, he first request this feature

2024-03-16 14:28 UTC, IProduceWidgets commented
Honestly, it does seem desirable for the chain link fences. Figuring out if I have the correct corner when placing those is pain every time.

2024-04-04 13:24 UTC, IamVelcroboy commented
Can you include random spawners too, please?

2024-05-10 15:54 UTC, Emisse commented
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

2024-05-10 15:54 UTC, closed without merging