Added a mist reaction
space-wizards/space-station-14 pull request #26111
Opened 2024-03-14 10:28 UTC by PolterTzi

## About the PR

Adds a mist reaction - equivalent to smoke, but doesn't obstruct vision and has a much more transparent sprite.
The recipe is 1:1:1 Sodium, Water and Sugar, but that's honestly just kinda arbitrary, absolutely open to changing that.

## Why / Balance

The intent is to enable chemical grenades that are able to infuse people with chems without otherwise impeding gameplay - Either for funny purposes, medical application or somewhat more stealthy poisonings.

## Media

https://github.com/space-wizards/space-station-14/assets/62557990/0ad7dbf1-8cc7-4369-bfbd-9806158ee56d

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Mixing Sugar, Sodium and Water now creates a transparent chemical mist.

2024-03-14 16:43 UTC, TheShuEd commented
Atmos refactor is here :trollface:

2024-03-14 20:34 UTC, UbaserB commented
If the chem injection is on the same scale as foam/fog, and THIS easy to craft, i feel like that is unbalanced and there is no reason to use either one. I would either increase the recipe or reduce the effects.

2024-03-15 03:10 UTC, PolterTzi commented
> If the chem injection is on the same scale as foam/fog, and THIS easy to craft, i feel like that is unbalanced and there is no reason to use either one. I would either increase the difficulty of the recipe or reduce the effects.

If your goal is solely to inject chems, it is meant to be a better option than either.
The two still would have their uses, since sometimes you still do want to cover up sightlines or slip people or apply the chem to the floor.

Maybe it's too hard to notice with the current sprite, I can see why that would be an issue. That could be tweaked.
And I'm more intent to trying to add this as a viable option than this exact recipe, so, yeah, it could be tweaked.

2024-03-15 03:14 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Effects/chemistry_effects.yml
> +  noSpawn: true
This field is obsolete.

2024-03-15 03:14 UTC, metalgearsloth requested changes
Isn't this just easy to craft smoke / foam

2024-03-15 03:36 UTC, PolterTzi commented
> Isn't this just easy to craft smoke / foam

I wanted something that would achieve a similar effect to smoke without making everyone affected effectively blind.
I don't think it's that much easier to make than smoke, but if the current recipe is unbalanced, it can be made a bit harder.

2024-03-15 03:36 UTC, PolterTzi commented on Resources/Prototypes/Entities/Effects/chemistry_effects.yml
> +  noSpawn: true
I assume you mean noSpawn?

2024-03-20 08:14 UTC, Jezithyr commented
Reopened since the repoban was in error. (The ban was made due to a misunderstood reference to the stonewall riots in an april fools PR)

2024-04-15 22:40 UTC, Dueu commented
My proposal for balancing: Space Aerosol Reagent.
Recipe: 3 Oil, 2 Hydrogen, 4 Flourine, Catalyst: Silver OR Vestine = 9 Space Aerosol
This locks it behind asking cargo for silver or being a chemist agent and keep vestine to make space aerosol.
Then it would be a reaction 1 water to 1 space aerosol plus the reagents to turn into mist.

2024-04-29 03:55 UTC, mirrorcult commented
this is overly confusing in its role when placed alongside foam and smoke, hard to notice and i dont understand why there necessarily needs to be a reagent like smoke that doesnt obscure vision

2024-04-29 03:55 UTC, closed without merging