Backpacks
space-wizards/space-station-14 pull request #26187
Opened 2024-03-16 19:45 UTC by 21Melkuu

## About the PR

Add new explosion-proof backpack in aplink for 2 tk
## Why / Balance

Mobility for nuke ops is an important part. At the moment the ops cannot take explosives with him, and medicine with him in a regular gray  backpack due to the lack of explosion protection. To solve this problem and add a little variability I propose this backpack

## Media

![2](https://github.com/space-wizards/space-station-14/assets/79728504/774cd238-9f49-4dff-aac7-6e5da63328c2)
![1](https://github.com/space-wizards/space-station-14/assets/79728504/9eff8fc2-b16a-4d10-bc80-5a32d2f9d0d1)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: 21Melkuu
- add: Add new explosion-proof backpack in aplink.

2024-03-16 19:46 UTC, Dutch-VanDerLinde commented
i think this should go in the wearables category rather than pointless, its not exactly pointless

2024-03-16 19:47 UTC, Dutch-VanDerLinde commented
also instead of an uplink purchase, what about adding it to the SyndieDrobe since the nukies get that on the planet

2024-03-16 19:52 UTC, 21Melkuu commented
> also instead of an uplink purchase, what about adding it to the SyndieDrobe since the nukies get that on the planet

I still think that a backpack like this has its advantages, so it should be price.

2024-03-16 19:53 UTC, 21Melkuu commented
> i think this should go in the wearables category rather than pointless, its not exactly pointless

you're probably right

2024-03-16 20:27 UTC, kerisargit commented
Please, I beg you, Satchel too. It’s just beautiful on the medic, you can lay everything out neatly

2024-03-16 21:02 UTC, 21Melkuu commented
> Please, I beg you, Satchel too. It’s just beautiful on the medic, you can lay everything out neatly

if approves this PR I make satchel

2024-03-16 21:51 UTC, Golinth commented
> Please, I beg you, Satchel too. It’s just beautiful on the medic, you can lay everything out neatly

I take the satchel from the clothesmate anyway, so please god add the satchel too.

2024-03-17 02:19 UTC, metalgearsloth requested changes

2024-03-17 02:19 UTC, metalgearsloth commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    - UplinkWearables
```suggestion
  categories:
    - UplinkWearables
```

Please use an IDE so your yaml gets trimmed properly.

2024-03-17 02:19 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
> +  description:
```suggestion
  description:
```

2024-03-17 02:21 UTC, metalgearsloth commented
Please make your PR names descriptive in future.

2024-03-17 02:21 UTC, metalgearsloth approved these changes

2024-03-17 02:21 UTC, merged