Added Yip Yip the kobold bartender
space-wizards/space-station-14 pull request #26265
Opened 2024-03-19 18:06 UTC by PolterTzi

## About the PR

Adds a kobold equivalent for Pun Pun.

## Why / Balance

WEH

## Media

![image](https://github.com/space-wizards/space-station-14/assets/62557990/b43c7092-5c5b-4b55-bdc3-eb81549847dc)
![image](https://github.com/space-wizards/space-station-14/assets/62557990/8fdb644a-0045-454e-91fd-a3182a4b1272)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: A kobold might show up in Pun Pun's place.

2024-03-19 18:12 UTC, Simyon264 commented
FYI: There is a freeze on new pets.
> New pets. While fluff is nice we have enough cargo-obtainable fluff animals and department mascots, to add new animals they must have something interesting like new AI behaviors or spawn in proc gen maps.

See #8524 for more info. This PR may be closed any time by a maintaner.

2024-03-19 18:12 UTC, Errant-4 commented
At this point it might make sense to create a second parent for the bartender animals to inherit the common components without having to redefine them every time

2024-03-19 18:14 UTC, VasilisThePikachu commented
> FYI: There is a freeze on new pets.
> 
> > New pets. While fluff is nice we have enough cargo-obtainable fluff animals and department mascots, to add new animals they must have something interesting like new AI behaviors or spawn in proc gen maps.
> 
> See #8524 for more info. This PR may be closed any time by a maintaner.

It wont be closed but not merged any time soon.

2024-03-19 18:18 UTC, PolterTzi commented
Ah, darn.
Oh well.

2024-03-19 18:20 UTC, VasilisThePikachu requested changes
Though I will leave one review

2024-03-19 18:20 UTC, VasilisThePikachu commented on Resources/Prototypes/Entities/Markers/Spawners/mobs.yml
>    id: SpawnMobMonkeyPunpun
I would suggest you rename this as well and add a migration to change the old id to the new one

https://github.com/space-wizards/space-station-14/blob/master/Resources/migration.yml

2024-03-19 18:32 UTC, TheShuEd commented
I think it's fine and doesn't really fall under the freeze, since it's not adding a new ghost role, but randomizing the appearance of an existing one.

2024-03-19 18:36 UTC, VasilisThePikachu commented
> I think it's fine and doesn't really fall under the freeze, since it's not adding a new ghost role, but randomizing the appearance of an existing one.

>New pets. While fluff is nice we have enough cargo-obtainable fluff animals and **department mascots**, to add new animals they must have something interesting like new AI behaviors or spawn in proc gen maps.

I would call this a new department mascot. And it does not add anything interesting

2024-03-19 18:36 UTC, Carmell0 commented
Suggestions:
 The name “nup nup” or “nip nip” would be funnier
Splash text saying “engage in a rivalry with pun pun”
Sometimes pun and yip spawn together. Sometimes both are at the bar, or maybe make it so yip spawns in the maints bar.

2024-03-19 21:44 UTC, CatMagic1 commented
I would argue that this is cool and yall are using TOO much logic to decide on funny lizard bartender

2024-03-19 21:46 UTC, UbaserB commented
> Suggestions:
> The name “nup nup” or “nip nip” would be funnier
> Splash text saying “engage in a rivalry with pun pun”
> Sometimes pun and yip spawn together. Sometimes both are at the bar, or maybe make it so yip spawns in the maints bar.

i agree with this

2024-03-19 22:53 UTC, Hmeister-real commented
no explanation, just closed? This is a sad day

2024-03-19 22:55 UTC, VasilisThePikachu commented
> no explanation, just closed? This is a sad day

they got repo banned

2024-03-19 23:12 UTC, Hmeister-real commented
> > no explanation, just closed? This is a sad day
> 
> they got repo banned

oh... what for?

2024-03-19 23:22 UTC, FairlySadPanda commented
ok hear me out 
![image](https://github.com/space-wizards/space-station-14/assets/732532/bf4b8008-b3af-45bf-b159-698fc90c865b)

2024-03-20 00:53 UTC, deltanedas commented
> ok hear me out 
> ![image](https://github.com/space-wizards/space-station-14/assets/732532/bf4b8008-b3af-45bf-b159-698fc90c865b)
> 

april 1 pun pun replacement

2024-03-20 05:35 UTC, Xman0613 commented
> > no explanation, just closed? This is a sad day
> 
> they got repo banned

wait why did they get repo banned?

2024-03-20 08:01 UTC, Jezithyr commented
Reopened since the repoban was in error. (The ban was made due to a misunderstood reference to the stonewall riots in an april fools PR)

2024-03-20 08:17 UTC, gitjubx commented
> > > no explanation, just closed? This is a sad day
> > 
> > 
> > they got repo banned
> 
> wait why did they get repo banned?

he censort the LGBTQ capes and made a joke about it beeing funny to censoring it or such...then wiggled himself out so like punch then apologize and everything is fine!

2024-03-20 08:23 UTC, PolterTzi commented
> > > > no explanation, just closed? This is a sad day
> > > 
> > > 
> > > they got repo banned
> > 
> > 
> > wait why did they get repo banned?
> 
> he censort the LGBTQ capes and made a joke about it beeing funny to censoring it or such...then wiggled himself out so like punch then apologize and everything is fine!

I censored them in the media preview of the april fools PR that was meant to add them to riot gear (since "pride was a riot" and all that).
I very much did not intend to censor them in game.
The censorship was admittedly not a good idea and that's on me.

2024-03-30 03:22 UTC, metalgearsloth commented
https://github.com/space-wizards/space-station-14/pull/25982 is a better approach to this.

2024-03-30 03:22 UTC, closed without merging

2024-03-30 08:03 UTC, PolterTzi commented
I don't really agree that it's strictly better, but there's little point in me arguing when it's still frozen anyway.