New Decor
space-wizards/space-station-14 pull request #26291
Opened 2024-03-20 15:22 UTC by JustArt1m

## About the PR
Several new decorative elements: floor lamps with random head color and blinds. Also a new hat: torchere. Floor lamps and blinds have crafts.

## Why / Balance
To make the station more cozy.

## M
![NewDecor](https://github.com/space-wizards/space-station-14/assets/123451459/2308bafc-0c49-4193-ab0f-c45631507eeb)
edia

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Just_Art
- add: Added floor lamps!
- add: Added wooden and metal blinds!
- add: Added crafts for floor lamps and blinds!
- add: Added torchere hat!

2024-03-20 15:30 UTC, Hmeister-real commented
i wish the lamp heads color changed the lights color

2024-03-20 18:00 UTC, JustArt1m commented
> Not to nitpick too much, but I feel like the venetian blinds should be plastic, no?
> 
> Also, do they close?
> 
> Lamps look great btw.

The blinds are closing. Plastic ones would look almost the same as metal ones.

2024-03-20 20:15 UTC, Tayrtahn approved these changes

2024-03-20 20:50 UTC, Tayrtahn reviewed
Deconstruction graph needs fixing (not sure how that works).

Also, "torchere" is a pretty obscure word (if it even is one in English?).

2024-03-21 05:28 UTC, JustArt1m commented
> Deconstruction graph needs fixing (not sure how that works).
> 
> Also, "torchere" is a pretty obscure word (if it even is one in English?).

Maybe I made a mistake, do you understand the word torchiere? If not, I'll replace it...

I checked, the deconstruction graph is working properly, what is the error?

2024-03-21 05:53 UTC, UbaserB commented
> > Deconstruction graph needs fixing (not sure how that works).
> > Also, "torchere" is a pretty obscure word (if it even is one in English?).
> 
> Maybe I made a mistake, do you understand the word torchiere? If not, I'll replace it...
> 
> I checked, the deconstruction graph is working properly, what is the error?

replace torchiere i dont think many people know what the word means

2024-03-25 00:50 UTC, brainfood1183 commented
The worn lamp shade has the wrong directional sprite, looks like a goon style sprite which is more over head as opposed to perfectly straight on like the current ss14 sprites.

2024-04-04 13:29 UTC, IamVelcroboy commented
Will you include a random spawner for the lamps too, please?

2024-04-06 07:35 UTC, JustArt1m commented
> Will you include a random spawner for the lamps too, please?

The lamp color is random by default, no random spawner is required

2024-04-06 08:19 UTC, IamVelcroboy commented
> > Will you include a random spawner for the lamps too, please?
> 
> The floor lamp color is random by default, no random spawner is required

Ooo fancy 👍

2024-04-06 13:35 UTC, Tayrtahn requested changes

2024-04-06 13:35 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Structures/Doors/blinds.yml
> +    node: frameWood
I believe you'll need to set deconstructionTarget on each of these to the appropriate base construction node.

2024-04-06 13:35 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Structures/Doors/blinds.yml
> +    node: startWoodBlinds
Here too

2024-04-06 13:35 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Structures/Doors/blinds.yml
> +    node: frameMetal
Here too

2024-04-06 13:35 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Structures/Doors/blinds.yml
> +    node: startMetalBlinds
Here too

2024-04-22 00:39 UTC, EmoGarbage404 requested changes
the worn lampshade is at the wrong perspective. I also think the blinds could be redone to more closely remember actual blinds. they look a lot like stairs.

2024-04-29 04:20 UTC, mirrorcult commented
are you coming back to this?

2024-05-10 16:02 UTC, closed without merging

2024-05-10 16:02 UTC, Emisse commented
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.