Broadcast Radio + Microphone
space-wizards/space-station-14 pull request #26345
Opened 2024-03-22 20:03 UTC by noctyrnal

## About the PR

Adds a radio, which broadcasts messages sent from the Broadcast Microphone, akin to an actual radio, letting stations have their own radio shows and hosts. Ideally should be mapped in for reporters.

## Why / Balance

Gives more variety to reporters, and adds more decorative / "lively" aspects to places e.g a radio in the bar.

## Technical details

N/A

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![image](https://github.com/space-wizards/space-station-14/assets/99278536/cbe9b279-d079-4741-870a-4b75f89c04e0)

https://github.com/space-wizards/space-station-14/assets/99278536/69caf560-6889-4db7-b9ce-61b04471ff0c

## Breaking changes

N/A

**Changelog**

- add: Added the Radio and Broadcast microphone. Host your own radio shows today!

2024-03-22 20:07 UTC, lzk228 requested changes
they should be obtainable

2024-03-22 20:27 UTC, Hmeister-fake commented
> they should be obtainable

arent these made for an upcoming role though? don't think they should be obtainable till the role for them is done

2024-03-22 20:31 UTC, noctyrnal commented
> > they should be obtainable
> 
> arent these made for an upcoming role though? don't think they should be obtainable till the role for them is done

They've been made for reporters, though also as RP tools for any radio hosts / self-proclaimed radio hosts in the future. Made them craftable too, so people can decorate their spaces with it easier, and means mappers dont have to map in 500 for full radio host gaming.

You can now craft them with 3 Steel and 2 LV cables.

2024-03-22 20:42 UTC, Dutch-VanDerLinde commented
changelog broken you need 🆑

2024-03-22 20:45 UTC, noctyrnal commented
> changelog broken you need 🆑

Fixed on both PRs

2024-03-22 21:44 UTC, FairlySadPanda commented
Chatfactor warning, I'll need to eyeball this code (similar to how I had to fuck with handheld radios) during the content refactor.

2024-03-23 01:57 UTC, UbaserB commented
The microphone sprite looks weird. The top looks like a grater and there's already a microphone sprite in the game so maybe you can tweak that one.

2024-03-23 12:46 UTC, SoulFN commented
I think microphone should be in the reporter's backpack at the roundstart.

2024-03-23 17:10 UTC, noctyrnal commented
> Chatfactor warning, I'll need to eyeball this code (similar to how I had to fuck with handheld radios) during the content refactor.

I can use the original microphone sprite, though my issue was that people would confuse it with the microphone instrument.

2024-03-23 17:10 UTC, noctyrnal commented
> I think microphone should be in the reporter's backpack at the roundstart.

I'll just put it in their pockets.

2024-03-24 00:19 UTC, UbaserB commented
> > Chatfactor warning, I'll need to eyeball this code (similar to how I had to fuck with handheld radios) during the content refactor.
> 
> I can use the original microphone sprite, though my issue was that people would confuse it with the microphone instrument.

which is why i said you should tweak the original microphone sprite

2024-03-24 00:19 UTC, EmoGarbage404 commented
just combine them

2024-03-24 19:58 UTC, 2013HORSEMEATSCANDAL commented
if you can you should see if there's a way to make music go through these mics as well, so radio hosts can play music.

2024-03-25 01:21 UTC, Partmedia reviewed
I've highlighted a few nitpicks on the changes.

The microphone sprite in the PR description looks comically large; I don't know if you had a chance to change this yet.

2024-03-25 01:21 UTC, Partmedia commented on Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
Please revert this no-op change to this file.

2024-03-25 01:21 UTC, Partmedia commented on Resources/Textures/Objects/Devices/communication.rsi/meta.json
> +	  {
Please fix the whitespace here.

2024-04-02 08:46 UTC, Peptide90 commented
> if you can you should see if there's a way to make music go through these mics as well, so radio hosts can play music.

Probably out of scope for this PR but took me a second to realise you meant MIDIs not actual music.

Detecting a midi in range of the microphone then broadcasting it would be good. At a reduced volume / range and with a radio / static effect over the top to really capture that retro futurism. Probably not the place to discuss it but just thought I'd add my two cents.

2024-04-14 10:11 UTC, closed without merging