pai expansion cards
space-wizards/space-station-14 pull request #26344
Opened 2024-03-22 19:50 UTC by deltanedas

## About the PR
lets some circuit boards be installed into pais to let them do more things

currently its just power monitoring computer

## Why / Balance
requires https://github.com/space-wizards/docs/pull/183

## Technical details
added new `PAIExpansionSlot` and `PAIExpansionCard` components, uses componentregistry gaming and requires engine pr

currently power monitor needs to be anchored to list power devices so that doesnt work yet

## Media
![18:27:54](https://github.com/space-wizards/space-station-14/assets/39013340/4d548edf-68da-49df-9852-1c0c41e69ba8)

![19:49:03](https://github.com/space-wizards/space-station-14/assets/39013340/4c1c0dc0-814e-4a34-9928-32d2b311257c)

![19:49:37](https://github.com/space-wizards/space-station-14/assets/39013340/9b65dfff-804b-44e5-b380-0812db939eba)

![19:50:06](https://github.com/space-wizards/space-station-14/assets/39013340/ee2e0f19-033e-46fa-bd88-201d12aca86f)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Certain computer boards can be inserted into pAIs to give them extra features, examine them to see if they are allowed.

2024-03-22 20:05 UTC, lzk228 commented on Resources/Textures/Interface/Actions/pai-expansions.rsi/power_monitor.png
maybe we can combine that with aghost actions icons?

2024-03-22 22:15 UTC, superjj18 commented
I do very much love this change.  I had a similar idea, however the only difference was that instead of expansion slots, its connected to the unique command PDAs, and give access once the Pai is inserted.

2024-03-22 22:18 UTC, deltanedas commented on Resources/Textures/Interface/Actions/pai-expansions.rsi/power_monitor.png
pro idea give aghost expansion slots :trollface:

2024-03-23 01:58 UTC, UbaserB commented
Is this going to be obtained through research?

2024-03-23 02:19 UTC, deltanedas commented
no theyre just computer circuitboards you put in the pai

2024-03-23 02:26 UTC, UbaserB commented
> no theyre just computer circuitboards you put in the pai

yea but like how do you get them

2024-03-23 02:27 UTC, Dutch-VanDerLinde commented
> > no theyre just computer circuitboards you put in the pai
> 
> yea but like how do you get them

they're just normal circuit boards for any normal computer

2024-03-23 02:32 UTC, UbaserB commented
> > > no theyre just computer circuitboards you put in the pai
> > 
> > 
> > yea but like how do you get them
> 
> they're just normal circuit boards for any normal computer

wait im dumb

2024-03-23 02:41 UTC, superjj18 commented
> > > no theyre just computer circuitboards you put in the pai
> > 
> > 
> > yea but like how do you get them
> 
> they're just normal circuit boards for any normal computer

big thing here would be balancing, as not every single person should be able to get a pai with access to say a crew monitor for instance.

2024-03-23 03:25 UTC, deltanedas commented
they need a crew monitor to begin with, they can always just drag around a computer/ the parts for it wherever they go. the real power is having another player keep track of it and not yourself

2024-03-23 17:21 UTC, chromiumboy commented
I think you'll have trouble getting this PR accepted, as your converting consoles into portable versions of themselves, and this has been vetoed in the past

2024-03-23 19:59 UTC, lzk228 commented
> I think you'll have trouble getting this PR accepted, as your converting consoles into portable versions of themselves, and this has been vetoed in the past

but you cant see it directly, pai will tell you about the maps and etc

2024-03-23 20:00 UTC, lzk228 requested changes

2024-03-23 20:00 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Fun/pai.yml
> +        name: Expansion Slot
loc string

2024-03-23 21:52 UTC, chromiumboy commented
> > I think you'll have trouble getting this PR accepted, as your converting consoles into portable versions of themselves, and this has been vetoed in the past
> 
> but you cant see it directly, pai will tell you about the maps and etc

Ah I see. Hmm, OK, that seems better then

2024-03-25 16:58 UTC, mbreton101 commented
This has a lot of potential with helping all departments making their job a little easier, it would also allow for Pai's to get less bord. here's some examples why this could be cool:
Allows Paramedics to get notifications of suit sensors on the move, without needing the handheld
Allows Security officer to set people to arrest easier
Allows Cargo to order delivery's anywhere 
Allows Science to research artifacts using a Pai potentially allowing more roleplay, or monitor/adjusting science's technology's

This could also potently give syndicate Pai a unique benefits over normal Pai's. Either having multiple expansion slots allowing syndicates to monitor multiple departments or potentially allowing them to access security records or approving orders without the proper access.

I think in order to allow the change of Cargo/security computer's, their should be an ID slot that you can put in the Pai, to give them access to change restricted terminals. I don't think they ID needs to be stuck in the Pai, just in an out.

Lastly my experimental idea would allow a Pai to change access of crew members, granted they get an ID computer installed, and have given the Pai proper HoP/Captain access. This would allow the HoP to not be completely bounded to their office, allowing for more unique playstyles. I personally believe this will not majorly benefits an-tag's, because an an-tag would both need to get an ID computer circuit and HoP/Captain access; and if an an-tag already has those items they practically they already have all access

2024-03-29 16:25 UTC, SoulFN commented
What about inserting encryption keys into PAI?

2024-03-29 16:53 UTC, Golinth commented
> I think in order to allow the change of Cargo/security computer's, their should be an ID slot that you can put in the Pai, to give them access to change restricted terminals. I don't think they ID needs to be stuck in the Pai, just in an out.

instead, why not have pAIs inherit the access of the PDA they’re inserted in?

2024-03-29 16:54 UTC, deltanedas commented
pai yelling on common that owner is being killed by john smith the tator

2024-03-29 17:06 UTC, HoidC commented
> pai yelling on common that owner is being killed by john smith the tator

let them read but not send on radio

2024-04-06 21:59 UTC, SoulFN commented
Can you also add PAI anomaly scanner and gas analyser functionality, but only PAI can see information?

2024-04-30 15:30 UTC, deltanedas commented
> Can you also add PAI anomaly scanner and gas analyser functionality, but only PAI can see information?

they arent boards so wouldnt make sense to insert them, and theres no cognitive load on having an anomaly scanner open 24/7 so it doesn't serve much purpose to have a pai look at the funny numbers for the shift compared to something more interesting like a crew monitor

2024-05-06 21:37 UTC, Agustron24 commented
Syndicate pai should be able to crack doors, like them beging able to pulse cables of doors.

Also make pai have sake game on them

2024-05-06 21:37 UTC, Agustron24 commented
*snake

2024-05-10 16:02 UTC, Emisse commented
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

2024-06-14 00:27 UTC, deltanedas commented
open

2024-06-14 01:13 UTC, deltanedas commented
how does it have different engine on actions than i have locally

2024-06-16 01:29 UTC, deltanedas commented
@AJCM-git do you know why its using wrong engine code just for this pr

2024-06-16 01:40 UTC, AJCM-git commented
> @AJCM-git do you know why its using wrong engine code just for this pr

How do you even run into things like this (pretty sure when it merges master with your required pr, it autoresolves the conflicts by adding another `SetUi` with a repeated signature in the runner version of the engine)

![image](https://github.com/space-wizards/space-station-14/assets/60196617/7d5c372c-9d0c-4b09-a28d-305fe79e5c1f)

2024-06-16 01:42 UTC, IProduceWidgets commented
> criminal records, which is read-only unless you emag it (new thief meta to lay low)
By chance did you check if the ninja obj is impacted by this?

2024-06-16 01:44 UTC, deltanedas commented
> By chance did you check if the ninja obj is impacted by this?

you need the console board to make a pai a criminal records console so no real reason to not allow hacking it

2024-06-16 01:47 UTC, deltanedas commented
OH pr body was trolling it real

2024-06-25 04:29 UTC, metalgearsloth commented
This seems like significant powercreep for PAIs by being able to see everyone with a crew monitor, and also power monitoring is incredibly expensive so in no universe should they have this.

2024-06-25 11:06 UTC, deltanedas commented
do you have any suggestions besides criminal records then

2024-06-25 14:33 UTC, keronshb commented
> do you have any suggestions besides criminal records then

PAIs should really be nothing more than a glorified talking radio that can change their holographic shape, and even then I have doubts for that because they've ruined intrigue rounds in SS13 because of the fact they're hidden sentient pocket radios.

2024-06-25 16:46 UTC, deltanedas commented
well the design doc was merged :trollface:

2024-06-25 16:58 UTC, deltanedas commented
@metalgearsloth no funny ones now

2024-07-10 01:40 UTC, Djungelskog2 commented
This partially feels like a more convoluted attempt to add more PDA cartridges to the game, also I take issue with the lathe and announcement ones because if in missing something they can be both easily obtained and abused, they can all be obtained from things like tech vaults or science and can be used to constantly recall the shuttle, spam announcements, store absurd amounts of mats or make anything anywhere you go

2024-07-10 01:45 UTC, Djungelskog2 commented
I would rather have PDA cartridges locked behind something like science rather than the exact same functionality with the liability of a player behind it. I like the idea of it being a personal assistant with an alternative functionality rather than an upgraded or new functionality (think hacking doors in 13, or adding holograms to make it more flavourful and interactive)

2024-07-10 14:55 UTC, Baptr0b0t commented
> This partially feels like a more convoluted attempt to add more PDA cartridges to the game, also I take issue with the lathe and announcement ones because if in missing something they can be both easily obtained and abused, they can all be obtained from things like tech vaults or science and can be used to constantly recall the shuttle, spam announcements, store absurd amounts of mats or make anything anywhere you go

it's true, however it's not necessarily easy to obtain and it's not that different from creating a computer

2024-07-28 23:26 UTC, superjj18 commented
I still think these additional abilities should be connected to the Command PDAs for balance reasons.  Makes command members with pais slightly better and limits the amount of pais with abilities to characters that arguably should have them.

(Also can be stolen and used by syndie pais if the command member is killed)

2024-08-18 22:44 UTC, Emisse commented
i think it might be better to allow pai to interact with anything installed in your pda

2024-10-29 10:22 UTC, Jezithyr commented
> well the design doc was merged
The design proposal was reverted as its approval did not take into account the discussions or balance/powercreep issues.

> i think it might be better to allow pai to interact with anything installed in your pda
This is a far better solution and doesn't add additional maintenance of a separate upgrade system. Plus it's far more balanced since the PAI can only do what a player would otherwise do themselves on their PDA, instead of having additional functionality which would need to be balanced and maintained (which adds more risks of creating bugs/exploits).

2024-10-29 10:47 UTC, closed without merging

2024-10-29 14:04 UTC, superjj18 commented
> i think it might be better to allow pai to interact with anything installed in your pda

If PDA messaging gets added this honestly would be pretty cool