Optimize a bunch of distance comparisons
space-wizards/space-station-14 pull request #26395
Opened 2024-03-24 18:18 UTC by Tayrtahn

## About the PR

Replaced a bunch of distance comparisons with more optimized versions.

## Why / Balance

Faster code.

## Technical details

A bunch of places in the code did range checks or other distance comparisons by calculating a vector length. Vector lengths is relatively expensive to calculate though, as they require finding a square root. If the actual length isn't needed (only a comparison to another value), it's cheaper to just compare the square distances instead.

This PR replaces many instances of `if (someVector.Length() > someValue)` with `if (someVector.LengthSquared() > someValue * someValue)`, eliminating a square root calculation. In some instances, the actual length was needed later in the code so it couldn't be eliminated, so the square root calculation was instead delayed until after some conditional checks were passed, so that it won't be wasted when the method returns early.
i.e:
```C#
var length = someVector.Length();
if (length > someValue)
   return;
SomeMethodThatNeedsLength(length, foo);
```
becomes
```C#
var lengthSquared = someVector.LengthSquared();
if (lengthSquared > someValue * someValue)
   return;
SomeMethodThatNeedsLength(MathF.Sqrt(lengthSquared), foo);
```

## Media

Code
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-03-24 18:23 UTC, PJB3005 reviewed
Honestly just looking at this diff I'd rather see a helper method made for this.

2024-03-24 18:26 UTC, Tayrtahn commented
> Honestly just looking at this diff I'd rather see a helper method made for this.

That's a good call and now I'm annoyed that I didn't do it that way in the first place. Will change!

2024-03-25 16:06 UTC, moonheart08 requested changes
I think we'd be better off if you didn't change systems that did anything more complex with length than a comparison.

This is ultimately a micro-optimization that won't even show up in profiling, and you often mis-apply the optimization.

(This isn't meant to be mean, sorry. More of noting how actually useful this change is, which isn't very.)

2024-03-25 16:06 UTC, moonheart08 commented on Content.Server/Fluids/EntitySystems/SpraySystem.cs
> +            var vaporPos = userMapPos.Offset(diff.IsShorterThan(1) ? quarter : threeQuarters);
This does the length calculation twice (minus sqrt), which is slower than doing it once with the square root. I think you over-estimate how expensive square root is.

2024-03-25 16:06 UTC, moonheart08 commented on Content.Server/Pinpointer/PinpointerSystem.cs
> +        else if (vec.IsShorterThanOrEqualTo(pinpointer.MediumDistance))
This is slower than what we had before. You overestimate how expensive sqrt is vs `x^2 + y^2`

For a rough approximation, the cost of the sqrt is that of the two squaring operations (not the addition). It's very minor and only adds up in hot loops.

2024-03-25 16:06 UTC, moonheart08 commented on Content.Server/Singularity/EntitySystems/SingularityAttractorSystem.cs
> +            biasBy = Vector2.Normalize(biasBy) * (attractor.BaseRange / biasBy.Length());
Slower than before.

2024-03-25 16:06 UTC, moonheart08 commented on Content.Server/SurveillanceCamera/Systems/SurveillanceCameraMicrophoneSystem.cs
> +                    ev.Recipients.TryAdd(actor.PlayerSession, new ICChatRecipientData(diff.Length(), false, true));
Slower than before.

2024-03-25 16:06 UTC, moonheart08 commented on Content.Shared/Damage/Systems/DamageOnHighSpeedImpactSystem.cs
> +        var damageScale = component.SpeedDamageFactor * args.OurBody.LinearVelocity.Length() / component.MinimumSpeed;
Slower than before.

2024-03-25 16:06 UTC, moonheart08 commented on Content.Shared/Friction/TileFrictionController.cs
> +                    control = velocity.IsShorterThan(_stopSpeed) ? _stopSpeed : speed;
Slower than before.

2024-03-25 16:06 UTC, moonheart08 commented on Content.Shared/Movement/Systems/SharedMoverController.cs
> +
Slower than before.

2024-03-25 16:22 UTC, Tayrtahn commented on Content.Client/Interaction/DragDropHelper.cs
> +                }
Sorry, Visual Studio Code got worked up about it. I'll put it back.

2024-03-25 16:30 UTC, Tayrtahn commented
> I think we'd be better off if you didn't change systems that did anything more complex with length than a comparison.
> 
> This is ultimately a micro-optimization that won't even show up in profiling, and you often mis-apply the optimization.
> 
> (This isn't meant to be mean, sorry. More of noting how actually useful this change is, which isn't very.)

No worries, I appreciate the feedback! It seems like I did indeed overestimate the cost of square roots - some quick research suggests that this change can have a significant impact in Unity (which is probably where I picked it up) but a pretty minimal effect outside of that specific environment.

I'll scale this back to just the most obvious use cases.

2024-03-25 16:59 UTC, moonheart08 commented
As I feel it'd be useful to you:
[Here is a distance comparison in sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgDkBXfGKASzFwBuGjWIBmJqQYBhBgG8aDJUwnAIEADYMAsgAoAajDAZoUhGgaHjphgE8AlPMXKXxAOwMELADIwAdgDmGAAWuo4AfHY+/kGh9sLULgC+zkriDGqaDGwGRiZQZhZW+VIOTokuyu6e0YEhAMoAjhzYsAAmYQyRtrWxTS3tYQnJNElAA=).

Let's assume the user has a ten year old Intel Broadwell microarchitecture processor, the instruction used for the sqrt operation is VSQRTPS and has a throughput of 1 every 14 clocks if uncontested. This is fine on it's own, pretty slow relative to LengthSquared (a single DPPS, or dot product operation, which can dispatch every other clock on the same processor)
In a hot loop, this optimization *would matter, possibly a lot*.

However, the estimate I gave is with the knowledge that most of these examples are in branch heavy, AVS-unit light code, which on an OoO/speculative processor like Broadwell (or newer architectures) means most of our time is going to be spent doing other things. So it's better to do the entire task once (compute length outright) or distribute the task (compute the dot product, then square root it later), but *never* do it more than once, as that opens room for actual pipeline contention instead of just waiting.

On newer processors (say, a modern Zen 4 one), the sqrt is even cheaper (10 clocks, none of which impede other instructions from running unless both ports 0 and 1 are occupied, which is guaranteed if we just computed the dot product of two vectors.), but we're still just juggling individual clocks here when the CPU is probably busy doing something more useful and working ahead while it computes the length.

2024-03-25 16:59 UTC, moonheart08 commented
I got the referenced instruction latencies from https://agner.org/optimize/, check the instruction table.

2024-03-25 19:17 UTC, moonheart08 commented
> > Measuring something being +-100 cycles faster/slower isn't possible.
> 
> Just repeat the benchmark enough times in series to exaggerate the difference. +- 100 cycles may be indistinguishable, but times a million nets something.

The difference immediately gets thrown out a window by OS process scheduling and CPU system action scheduling (modern processors can steal a core back from the OS to run system code in some circumstances)

2024-03-25 19:31 UTC, Tayrtahn commented
The reasoning for it being slower makes sense to me. I'm going to revert the more complicated changes that delay the square root and just keep the ones that always remove.

2024-03-25 20:21 UTC, PJB3005 commented
The savings, while real, will not amount to anything compared to the logic that surrounds 99% of the changes in this PR. Yes, I know that without needing to set up a whole micro benchmark. It's for that reason that doing any complex modifications is not worth spending the energy on, and definitely not worth the risk of messing up and introducing a bug.

2024-03-25 21:50 UTC, Tayrtahn commented
So I've changed it so it's basically* all one-liner changes using helper methods, which I think are at least as readable as the originals.

Are those worth keeping, or is this PR dead?

*there are also two loops that look for the shortest distance in a collection, but I can remove those too if they make the code harder to follow.

2024-04-01 06:38 UTC, metalgearsloth commented
See above on "the optimisation is so small the risk of bugs outweighs any benefit", sorry.

2024-04-01 06:38 UTC, closed without merging