Add Polymorph Proto Id to Polymorph Actions
space-wizards/space-station-14 pull request #26419
Opened 2024-03-24 23:42 UTC by keronshb

Adds poly proto ids to polymorph action event and checks for proto id when performing

## About the PR

Polymorph Actions will now also accept polymorph proto ids, in the scenario you need to make a custom polymorph action for a  store.

## Why / Balance

Needed for Wizard individual personal polymorphs.

## Technical details

Polymorph Actions Prototypes are now nullable and a datafield was added for prototype ids.

On polymorph action pressed, the system checks if the action has a prototype already. And if it doesn't, then it checks if it has a prototype Id and then polymorphs accordingly.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Polymorph Action Event's Prototype is made nullable and has a new field for Polymorph Prototype Ids called ProtoId.

Polymorph System's OnPolymorphAcitonEvent checks first if the prototype is null, and if that's null then it checks for a prototype id. If either is found it will then polymorph the action caller.

2024-03-25 06:26 UTC, metalgearsloth requested changes

2024-03-25 06:26 UTC, metalgearsloth commented on Content.Server/Polymorph/Systems/PolymorphSystem.cs
>      }
Just use TryIndex on prototypemanager.

2024-03-25 06:26 UTC, metalgearsloth commented on Content.Shared/Polymorph/PolymorphActions.cs
> +
Just remove this and index when needed.

2024-03-29 02:43 UTC, keronshb commented on Content.Server/Polymorph/Systems/PolymorphSystem.cs
>      }
Changes done

2024-03-29 02:44 UTC, keronshb commented on Content.Shared/Polymorph/PolymorphActions.cs
> +
Changes complete

2024-03-29 06:41 UTC, metalgearsloth approved these changes

2024-03-29 06:41 UTC, merged