Added master volume slider in audio options
space-wizards/space-station-14 pull request #2642
Opened 2020-11-29 15:40 UTC by ManelNavola

- There is now a slider for changing the master volume
- The slider goes from 0% to 100% in 1% increments, being 0% setting the volume to 0.0f and 100% setting it to 1.0f

Requires space-wizards/RobustToolbox#1427
Fixes #2614

2020-12-01 13:56 UTC, metalgearsloth requested changes

2020-12-01 13:56 UTC, metalgearsloth commented on Content.Client/UserInterface/AudioSource.cs
> +}
Unused?

2020-12-01 13:56 UTC, metalgearsloth commented on Content.Client/UserInterface/OptionsMenu.Audio.cs
> +                MasterVolumeLabel.Text = string.Format("{0:0}%", MasterVolumeSlider.Value);
Localize

2020-12-01 13:56 UTC, metalgearsloth commented on Content.Client/UserInterface/OptionsMenu.Audio.cs
> +                MasterVolumeLabel.Text = string.Format("{0:0}%", MasterVolumeSlider.Value);
Localize

2020-12-01 13:56 UTC, metalgearsloth commented on Content.Client/UserInterface/OptionsMenu.Audio.cs
> +                MasterVolumeSlider.OnValueChanged += OnMasterVolumeSliderChanged;
Will need to unsubscribe from these as the control is remade every time the round is restarted.

2020-12-02 08:04 UTC, ManelNavola commented on Content.Client/UserInterface/AudioSource.cs
> +}
No clue what this was doing here

2020-12-02 13:12 UTC, metalgearsloth commented on Content.Client/UserInterface/OptionsMenu.Audio.cs
> +                base.Dispose(disposing);
In case you haven't just doublecheck it works with round restarts, otherwise LGTM

2020-12-02 13:12 UTC, metalgearsloth approved these changes

2020-12-05 20:14 UTC, merged