Fix 'Hypopen shouldn't display solution examine text'
space-wizards/space-station-14 pull request #26453
Opened 2024-03-26 17:36 UTC by drteaspoon420

## About the PR

Fixes #26439

## Technical details

~~I removed the ExaminableSolution component of the solution.~~
ExaminableSolution now has 'hidden' datafield. That, if true, requires entity to be held by examinee to display any indication of chemicals.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: DrTeaspoon
- fix: Hypopen no longer shows chemical contents when examined, when not held by the examinee.

2024-03-26 17:38 UTC, Dutch-VanDerLinde commented
maybe make the little status that says volume (0/10) when you're holding it also not appear

2024-03-26 17:51 UTC, PJB3005 commented
Showing volume content is fine, showing the description isn't.

2024-03-26 18:55 UTC, drteaspoon420 commented
So new UI component just when item is in hand?

2024-03-27 09:59 UTC, deltanedas requested changes

2024-03-27 09:59 UTC, deltanedas commented on Content.Shared/Chemistry/Components/SolutionManager/ExaminableSolutionComponent.cs
> +    [DataField("hidden"), ViewVariables(VVAccess.ReadWrite)]
replace this line with just `[DataField]`

2024-03-27 09:59 UTC, deltanedas commented on Content.Shared/Chemistry/EntitySystems/SharedSolutionContainerSystem.cs
> +        //Check if examinable solution requires you to hold the item in hand.
instead of copy pasting this comment put it on CanSeeHiddenSolution

2024-03-27 09:59 UTC, deltanedas commented on Content.Shared/Chemistry/EntitySystems/SharedSolutionContainerSystem.cs
> +        if (hands == null)
use TryComp return value

2024-03-27 09:59 UTC, deltanedas commented on Content.Shared/Chemistry/EntitySystems/SharedSolutionContainerSystem.cs
> +        return found;
just return it directly no need to assign

2024-03-30 06:16 UTC, ShadowCommander requested changes

2024-03-30 06:16 UTC, ShadowCommander commented on Content.Shared/Chemistry/Components/SolutionManager/ExaminableSolutionComponent.cs
> +    public bool Hidden = false;
Maybe rename to HeldOnly for clarity?

2024-03-30 11:05 UTC, drteaspoon420 commented on Content.Shared/Chemistry/Components/SolutionManager/ExaminableSolutionComponent.cs
> +    public bool Hidden = false;
Done! Much Better

2024-03-30 17:53 UTC, drteaspoon420 reviewed
Done

2024-03-31 04:59 UTC, merged