Mr Nanotrasen, a new admeme spawn
space-wizards/space-station-14 pull request #26459
Opened 2024-03-26 20:55 UTC by noctyrnal

## About the PR

Based of emisse's insane lore drop, admins can now spawn Mr Nanotrasen, a space dragon with a new sprite, a PDA and Centcomm certified plated teeth. When he is killed, he can be butchered to drop 300K Spesos (Nanotrasen's profit)

## Why / Balance

Funny PR

## Technical details

N/A

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![f54daf5aede5a8c90a05c5464d53f58c](https://github.com/space-wizards/space-station-14/assets/99278536/e7a565bf-c168-42d8-84a1-9d3f0f211968)

## Breaking changes

N/A

**Changelog**

:cl:
- add: Adds a new admeme spawn, Mr Nanotrasen the space dragon.

2024-03-26 20:56 UTC, UbaserB commented
Why is he not white

2024-03-26 20:57 UTC, noctyrnal commented
> Why is he not white

he can be any colour :)

2024-03-26 21:33 UTC, UbaserB commented
> > Why is he not white
> 
> he can be any colour :)

he needs to be white specifically because thats whats stated in the lore

2024-03-27 02:25 UTC, deltanedas commented
racism in the ss14 /!\\

2024-03-27 02:27 UTC, UbaserB commented
> racism in the ss14 /!\

https://discord.com/channels/310555209753690112/675078881425752124/1222101235327565864

2024-03-27 02:40 UTC, Flareguy reviewed
The tie should really probably not be on the unshaded layer, it looks pretty weird here.

2024-03-27 02:48 UTC, noctyrnal commented
> The tie should really probably not be on the unshaded layer, it looks pretty weird here.

issue is is that if i put it on the shaded layer then it fucks with the random colouring of the dragon, making the tie look bad. I can remove the random colouring if the unshaded tie is too much of a putoff though.

2024-03-27 05:09 UTC, Flareguy commented
> > The tie should really probably not be on the unshaded layer, it looks pretty weird here.
> 
> issue is is that if i put it on the shaded layer then it fucks with the random colouring of the dragon, making the tie look bad. I can remove the random colouring if the unshaded tie is too much of a putoff though.

You can just make another layer that doesn't get colored, no?
You should probably remove the random coloring anyways, though, since he's supposed to be white.

2024-03-27 05:10 UTC, noctyrnal commented
> > > The tie should really probably not be on the unshaded layer, it looks pretty weird here.
> > 
> > 
> > issue is is that if i put it on the shaded layer then it fucks with the random colouring of the dragon, making the tie look bad. I can remove the random colouring if the unshaded tie is too much of a putoff though.
> 
> You can just make another layer that doesn't get colored, no? You should probably remove the random coloring anyways, though, since he's supposed to be white.

ill just take the colouring away, saves me work.

2024-03-27 10:29 UTC, lzk228 commented
> > > Why is he not white
> > 
> > 
> > he can be any colour :)
> 
> he needs to be white specifically because thats whats stated in the lore

lmao, since when game depends on lore?

2024-03-27 10:30 UTC, UbaserB commented
> > > > Why is he not white
> > > 
> > > 
> > > he can be any colour :)
> > 
> > 
> > he needs to be white specifically because thats whats stated in the lore
> 
> lmao, since when game depends on lore?

since they said it was lore :clueless:

2024-03-29 01:41 UTC, Moomoobeef commented
NT only makes 300k?

2024-03-29 01:42 UTC, noctyrnal commented
> NT only makes 300k?

they gambled the rest of it away to get thronglers

2024-03-31 02:55 UTC, metalgearsloth requested changes
Don't copy-paste existing sprites for admemes.

2024-03-31 02:55 UTC, metalgearsloth commented on Resources/Prototypes/InventoryTemplates/mr_nanotrasen_inventory_template.yml
> +      displayName: ID
Why's it in its own yml + please follow yaml styleguide for naming prototypes.

2024-03-31 02:55 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Mobs/Player/dragon.yml
> +      shader: unshaded
Supposed to be white.

2024-04-14 10:11 UTC, closed without merging