Makes secglasses roundstart
space-wizards/space-station-14 pull request #26487
Opened 2024-03-28 01:50 UTC by Flareguy

## About the PR
Replaces all instances of sunglasses & sechud in security lockers & job fills with secglasses.
Removes the research for secglasses since it is now pointless. To make them obtainable past roundstart, you can now craft secglasses by-hand using a sechud + glasses + some cable coil.

## Why / Balance
This has been discussed a few times before in the past, and the conclusion I've come to is that the tradeoff of sechud / glasses isn't really a very meaningful or interesting one. Making the person using the HUD unable to use flashes or flashbangs doesn't really do anything other then giving them slightly less options.
This is also pretty bad when you factor in that the sechud is pretty important QOL for a security officer. This ends up nerfing criminal records in a kind of unsavory way.

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Security glasses have been moved from research to roundstart gear. All officers now start with them instead of sunglasses by default.
- add: You can now craft security glasses.

2024-03-28 01:55 UTC, Emisse commented
i approve but yaml fail

2024-03-28 02:04 UTC, Hanzdegloker commented
I just ask, sunglasses will be good flash protection and possible conversion protection and is obtainable outside of security. I want what happen to sechuds? what niche do they now fill if you get the full on upgrade off the rip when it comes to sec. Personally I would continue to use the sec hud out of looks but besides that, what role can the sec hud fill now?

2024-03-28 02:22 UTC, Flareguy commented
> I just ask, sunglasses will be good flash protection and possible conversion protection and is obtainable outside of security. I want what happen to sechuds? what niche do they now fill if you get the full on upgrade off the rip when it comes to sec. Personally I would continue to use the sec hud out of looks but besides that, what role can the sec hud fill now?

If SS13 is to go off of, presumably none, outside of being the "base hud type" used in specific situations where that is warranted (like crafting.) It's not great, but in the current state of the sechud & sunglasses, there's really not much of a solution to this AFAIK.
There is at least the sec/med hud, which should help it feel a little less weird since you can't keep the flash protection if you're using that.

2024-03-28 11:30 UTC, K-Dynamic commented
> I just ask, sunglasses will be good flash protection and possible conversion protection and is obtainable outside of security. I want what happen to sechuds? what niche do they now fill if you get the full on upgrade off the rip when it comes to sec. Personally I would continue to use the sec hud out of looks but besides that, what role can the sec hud fill now?

Maybe give them to sec auxiliary staff who you don't 100% trust with flash protection (i.e. lawyers) or you run out of secglasses

2024-03-28 15:26 UTC, IProduceWidgets commented
I'm not 1000% sure, but I think your test fail is the construction graph.

2024-03-29 01:11 UTC, EmoGarbage404 requested changes

2024-03-29 01:11 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +    graph: GlassesSecHUD
needs to specify the node for the graph.
```suggestion
    graph: GlassesSecHUD
    node: glassesSec
```

there's your fail

2024-03-29 02:39 UTC, SpeltIncorrectyl commented
I am very onboard with this, sechud cannot be used because the risk of being flashed is too great. Especially considering the time you really need to use sechud is the same time your enemies have flashes.

2024-03-29 13:01 UTC, notquitehadouken commented
this is how it is like in /tg/ and i must say it is much better than locking them behind research

(also they look cool so hooray)

2024-03-30 06:18 UTC, Brandon-Huu commented
How does this affect the secmed hud

2024-03-30 06:53 UTC, Flareguy commented
> How does this affect the secmed hud

It doesn't touch anything relating to the hud itself. You can still print sechuds in the armory / get them from boxes.

2024-03-31 03:00 UTC, EmoGarbage404 approved these changes

2024-03-31 03:00 UTC, merged