Fix capitalization for pirates and rats
space-wizards/space-station-14 pull request #26644
Opened 2024-04-01 06:07 UTC by Vermidia

## About the PR

When rats and pirates speak in all caps, the first letter of their messages will now no longer be converted to lowercase. Along with this, if their message was in all caps, words added to their sentences will also be in all caps

## Why / Balance

Let the pirates scream YARGH.

## Technical details

LINQ

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/32827189/7a838717-351e-4d39-9ba1-25e32ae59367

## Breaking changes

**Changelog**

:cl:
- fix: Pirate Accent and Mobster accent will respect capitalization better now

2024-04-01 06:34 UTC, metalgearsloth requested changes
Why doesn't the accent just handle the casing of the original characters instead of only handling ALL CAPS or no caps.

2024-04-01 07:00 UTC, Vermidia commented
Tried to make it a little smarter by checking only the first and last words and changing caps based on that.

2024-04-12 07:02 UTC, ShadowCommander requested changes

2024-04-17 10:04 UTC, metalgearsloth approved these changes

2024-04-17 10:04 UTC, merged