Working vendors
space-wizards/space-station-14 pull request #2665
Opened 2020-12-01 20:22 UTC by DmitriyRubetskoy

Changed the chocolate dispenser machine so it actually dispenses sweets

2020-12-01 20:24 UTC, SweptWasTaken commented
Your title should be more descriptive than this. There's a lot of vending machines in the game, and "working" could mean anything.

2020-12-01 20:26 UTC, SweptWasTaken requested changes

2020-12-01 20:26 UTC, SweptWasTaken commented on Resources/Prototypes/Catalog/VendingMachines/snack.yml
> -  description: A vending machine containing snacks.
Why did you remove the description?

2020-12-03 23:30 UTC, PJB3005 requested changes
Your IDE absolutely butchered all the project files. Please clear all that stuff out of your PR.

2020-12-04 07:10 UTC, DmitriyRubetskoy commented
I will make another pull request with proper name and files

2020-12-04 07:10 UTC, closed without merging