Crates - 3rd times a charm
space-wizards/space-station-14 pull request #2669
Opened 2020-12-02 07:36 UTC by SweptWasTaken

3rd and hopefully final PR for this. Been a PR in some form or another since April.

A lot of the stuff for the actual crates isn't implemented yet, so I either didn't include them or commented them out. I took most of them from tgstation's current code.

- [ ] Changed plasma crate to phoron
- [ ] Fix crate icons
- [ ] Add the rest of the crates
- [ ] Make it so you can weld crates shut
- [ ] Make it so you can anchor crates
- [ ] Add tgcrates content
- [ ] Add secure crates that can be "locked" (Access levels for secure storage will be in a different PR)
- [ ] Add crates to cargo console

Will close #553 and old sprites will be added to the rsi-dump.

2020-12-02 08:58 UTC, metalgearsloth approved these changes
Fix build

2020-12-02 08:58 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +
highly approve

2020-12-02 08:58 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Constructible/Storage/Crates/Filled/crate_science.yml
> +# Bro what do I PUT here
idk lol

2020-12-02 09:30 UTC, ike709 commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +
`It's` should be `Its` though.

2020-12-05 14:26 UTC, Zumorica requested changes

2020-12-05 14:26 UTC, Zumorica commented on Resources/Prototypes/Entities/Constructible/Power/cargo_console.yml
> +      -
oops?
```suggestion
```

2020-12-05 14:26 UTC, Zumorica commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +  description: It's smug aura compells you to perform surgery with a slightly higher degree of skill.
```suggestion
  description: Its smug aura compells you to perform surgery with a slightly higher degree of skill.
```

2020-12-05 14:56 UTC, Zumorica commented
I fixed everything wrong with this PR, I'm merging this.
Needs more work but that can be done in the future, and this is already a good starting point anyway.

2020-12-05 14:59 UTC, merged