Added Jukebox
space-wizards/space-station-14 pull request #26736
Opened 2024-04-05 02:28 UTC by metalgearsloth

Resurrected from inverted's original PR which died due to requiring audio rework which is now done.

Draft so I can fix a bunch of stuff and check it works. Requires https://github.com/space-wizards/RobustToolbox/pull/5024

:cl: iNV3RT3D & metalgearsloth
- add: Added a jukebox.

2024-04-15 15:01 UTC, ps3moira commented
[https://www.youtube.com/watch?v=u8Ou884gD_w](url) bar's gonna be groovy

2024-04-17 06:43 UTC, DrSmugleaf requested changes

2024-04-17 06:43 UTC, DrSmugleaf commented on Content.Client/Audio/Jukebox/JukeboxBoundUserInterface.cs
> +        // TODO: Need a way to sub to compstates as otherwise this can fail in some situations.
Can't you subscribe to the after handle auto comp state event for this?

2024-04-17 06:43 UTC, DrSmugleaf commented on Content.Shared/Audio/Jukebox/JukeboxUi.cs
> +    public ProtoId<JukeboxPrototype>? SelectedSong;
These are already on the jukebox component, can the client UI use the values from that instead?

2024-04-17 09:27 UTC, merged

2024-04-17 09:41 UTC, K-Dynamic commented
Now we just need a dj table to create ear-destroying nightcore mixes with added cowbells