Tippy, the helpful hint clown!
space-wizards/space-station-14 pull request #26767
Opened 2024-04-06 08:39 UTC by SlamBamActionman

## About the PR

This PR adds Tippy the clown, a humorous command that allows admins to broadcast messages to players via a clown walking onto the screen. It's possible to customize the Tippy tip to target a specific player, and set Tippy's sprite to look like any entity.

Tippy has a 1% chance to spawn instead of a normal chat gameplay tip.

`/clippy <player uid | broadcast> <message> [entity prototype] [speak time] [animate time] [waddle]` is an admin command to spawn Tippy.
`/tip` is an admin command to generate a random chat gameplay tip.

## Why / Balance

Tippy is a charming little fella and adds a bit of levity. Mostly an admeme thing, but when he (rarely) randomly appears it'll be a fun time for all.

## Technical details

This PR utilizes the code from #26112 with some minor cleanup to remove April's Fools functionality.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl, lots of fun!

2024-04-06 08:41 UTC, SlamBamActionman commented
There is a minor visual bug where the speech bubble appears for one frame in the wrong location before being repositioned and I filled with text. It's not very noticable but it's there, so if anyone can suggest a fix I'm all ears.

2024-04-06 09:10 UTC, Simyon264 requested changes
tippy👍

2024-04-06 09:10 UTC, Simyon264 commented on Content.Client/Tips/ClippyUIController.cs
> +            shell.WriteLine("usage: clippy <message> [entity prototype] [speak time] [animate time] [waddle]");
Localization.

2024-04-06 09:10 UTC, Simyon264 commented on Content.Client/Tips/ClippyUIController.cs
> +                shell.WriteError($"Unknown prototype: {ev.Proto}");
Localization

2024-04-06 09:10 UTC, Simyon264 commented on Content.Server/Tips/TipsSystem.cs
> +        _conHost.RegisterCommand("clippy", "Broadcast a message as Tippy the clown", "clippy <player Uid | broadcast> <message> [entity prototype] [speak time] [slide time] [waddle]", SendClippy);
Localization as well as using `LocalizedCommands` instead of `RegisterCommand`.

2024-04-06 09:10 UTC, Simyon264 commented on Content.Server/Tips/TipsSystem.cs
> +        _conHost.RegisterCommand("tip", "Spawn a random game tip", "tip", SendTip);
Localization here too and `LocalizedCommands`

2024-04-06 09:10 UTC, Simyon264 commented on Content.Server/Tips/TipsSystem.cs
> +                "usage: clippy <player Uid | broadcast> <message> [entity prototype] [speak time] [slide time] [waddle]");
Localization here as well.

2024-04-06 09:10 UTC, Simyon264 commented on Content.Server/Tips/TipsSystem.cs
> +                shell.WriteError($"Could not find player {args[0]}");
Here too.

2024-04-06 09:10 UTC, Simyon264 commented on Content.Server/Tips/TipsSystem.cs
> +                shell.WriteError($"Unknown prototype: {args[2]}");
Also here.

2024-04-06 09:10 UTC, Simyon264 commented on Content.Client/Tips/ClippyUIController.cs
> +        _conHost.RegisterCommand("local_clippy", ClippyCommand);
Unsure on this one, but having the command in a different file using `LocalizedCommands` is more clear.

2024-04-06 14:18 UTC, VasilisThePikachu requested changes

2024-04-06 14:18 UTC, VasilisThePikachu commented on Content.Client/Tips/ClippyUIController.cs
> +            shell.WriteLine("usage: clippy <message> [entity prototype] [speak time] [animate time] [waddle]");
Change the command to "tippy" instead. Also, ensure it has auto-complete (shows suggestions in the console)

2024-04-06 18:35 UTC, beck-thompson commented
Could you show a video? Sounds super fun 😆

2024-04-08 20:47 UTC, SlamBamActionman commented
- All references to Clippy have been removed
- Localization strings have been added
- Command has autocomplete and targeting a specific player is now easier
- local_clippy has been removed (didn't really serve much of a point)

I didn't change it from RegisterCommand into LocalizedCommand since it'd require changing the inheritance; let me know if it's a hard requirement. Also, video is up in the description.

2024-04-08 20:57 UTC, SlamBamActionman commented
Test fail appears unrelated to PR.

2024-04-09 01:36 UTC, brainfood1183 commented
Now admins can make Jonky The Cluwne

2024-04-15 13:33 UTC, dvir001 commented
1% is a lot for this.
This should be a 1 to 10000 or even 100000

2024-04-15 18:09 UTC, superjj18 commented
> 1% is a lot for this. This should be a 1 to 10000 or even 100000

That’s insane, you may as well just not add it at all

We must calculate how many tips per day per server, and from that we can extrapolate tippy’s per day.

2024-04-15 18:16 UTC, beck-thompson commented
1% might be a little much but you can easily just change it to like .5% or .25%. 1 / 100000 is so small you might as well remove it!

2024-04-15 22:34 UTC, SlamBamActionman commented
Unless a maintainer chimes in with a percentage, this can just be merged and admins are free to adjust it as necessary. It's a CCVar so editing the value isn't particularly difficult.

2024-04-29 04:28 UTC, mirrorcult commented
1% is fine lol its just tippy

2024-04-29 04:28 UTC, mirrorcult approved these changes

2024-04-29 04:38 UTC, merged