Maints Exit Sign
space-wizards/space-station-14 pull request #26831
Opened 2024-04-08 20:15 UTC by brainfood1183

Adds a new diretional exit sign for maints areas which should point to the nearest none departmental airlock.

![untitled-411](https://github.com/space-wizards/space-station-14/assets/113240905/4110af50-1868-4b97-8c0a-ed3787604f67)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Directional Exit signs for maints!

2024-04-08 20:55 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/signs.yml
> +  description: A direction sign, pointing which way to the exit.
```suggestion
  description: A directional sign pointing toward the nearest exit.
```

2024-04-08 23:41 UTC, Tayrtahn approved these changes

2024-04-08 23:47 UTC, Tayrtahn requested changes
Didn't catch this before, but I think it would be better to call this "exit" instead of "maints", for the id, file name, etc.

2024-04-09 00:11 UTC, baddiePRO commented
is there any way you could make them glow in the dark too?

2024-04-09 01:32 UTC, brainfood1183 commented
![untitled-412](https://github.com/space-wizards/space-station-14/assets/113240905/191e718b-f47a-42ec-aba2-0fd45faee9b2)

now glows in dark

2024-04-09 01:35 UTC, Tayrtahn approved these changes

2024-04-09 01:38 UTC, Flareguy commented
Due to how wallmounts work, this is going to display on *every side* of a wall, and likely end up being very confusing. This is an interesting idea, but I don't think it can work right now.

2024-04-09 01:42 UTC, K-Dynamic commented
Surely we could have some blinking lights on the ground/tile leading to a door

2024-04-09 04:26 UTC, UbaserB commented
the glow seems a bit strong

2024-04-09 06:56 UTC, SlamBamActionman commented
I support the idea, but perhaps it'd be better to implement it like this:

- Exit signs are mounted on the side of the wall, very similar to lamp tubes.
- Instead of just shining they instead illuminate the surroundings with a small 1-2 tile green glow.

That way they become more diagetic and add to the dark maints atmosphere. Might need a sprite adjustment to work on the side of the wall though.

2024-04-09 13:47 UTC, brainfood1183 commented
> I support the idea, but perhaps it'd be better to implement it like this:
> 
>     * Exit signs are mounted on the side of the wall, very similar to lamp tubes.
> 
>     * Instead of just shining they instead illuminate the surroundings with a small 1-2 tile green glow.
> 
> 
> That way they become more diagetic and add to the dark maints atmosphere. Might need a sprite adjustment to work on the side of the wall though.

i think this is an interesting idea, kinda like how the janitorial signs work. I will have a think about it.

2024-04-09 16:50 UTC, IProduceWidgets commented
> Due to how wallmounts work, this is going to display on _every side_ of a wall, and likely end up being very confusing. This is an interesting idea, but I don't think it can work right now.

This can *maybe* be resolved with careful mapping, but yeah its a bit of a weird spot since we don't want lots of doubled walls.

2024-04-10 00:46 UTC, brainfood1183 commented
> > Due to how wallmounts work, this is going to display on _every side_ of a wall, and likely end up being very confusing. This is an interesting idea, but I don't think it can work right now.
> 
> This can _maybe_ be resolved with careful mapping, but yeah its a bit of a weird spot since we don't want lots of doubled walls.

Yea currently its best to place signs on T sections of walls to avoid the sign appearing in rooms it shouldn't. Not great lets be honest but it is a problem for all signs and not just this sign i guess.

2024-04-21 18:06 UTC, Golinth commented
> > I support the idea, but perhaps it'd be better to implement it like this:
> > ```
> > * Exit signs are mounted on the side of the wall, very similar to lamp tubes.
> > 
> > * Instead of just shining they instead illuminate the surroundings with a small 1-2 tile green glow.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That way they become more diagetic and add to the dark maints atmosphere. Might need a sprite adjustment to work on the side of the wall though.
> 
> i think this is an interesting idea, kinda like how the janitorial signs work. I will have a think about it.

That’s exactly how I was envisioning this. A glowing exit sign, could even use the same green bulb as the janitorial sign

2024-04-23 11:31 UTC, merged