You can now see paper on crates (with color!)
space-wizards/space-station-14 pull request #26834
Opened 2024-04-08 22:22 UTC by Vermidia

## About the PR

Paper is now visible on the sprites of crates, including color. (Other branch got a bit cooked).
Currently in 3 flavors: Paper, Bounty Paper, and the Captains Lavender Paper

## Why / Balance

Easier to see when something's been attached to a crate.
Closes #26820

## Technical details

See #26828, I implemented pretty much all of that, just changing the paperlabeltype to a string for easy of adding of more paper types without changing code

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![Lookatallthesenotes](https://github.com/space-wizards/space-station-14/assets/32827189/c07ea354-1c42-49c3-9a7b-b00cae4b70b0)

## Breaking changes

**Changelog**

:cl:
- add: You can now see paper attached on crates

2024-04-08 22:54 UTC, deltanedas requested changes

2024-04-08 22:54 UTC, deltanedas commented on Content.Server/Labels/Label/LabelSystem.cs
> +            UpdateAppearance((uid, component, null));
dont need null for optional ones so just (uid, component)

2024-04-08 22:54 UTC, deltanedas commented on Content.Server/Labels/Label/LabelSystem.cs
> +            UpdateAppearance((uid, label, null));
.

2024-04-08 22:54 UTC, deltanedas commented on Content.Shared/Labels/Components/PaperLabelTypeComponent.cs
> +    [DataField("paperType")]
replace with just `[DataField]` it autogenerates yaml name from c# name

2024-04-08 22:54 UTC, deltanedas commented on Resources/Textures/Structures/Storage/Crates/labels.rsi/meta.json
> +    ]
indent trolled use 2 spaces not 4

2024-04-08 22:54 UTC, deltanedas commented on Resources/Textures/Structures/Storage/Crates/toybox.rsi/meta.json
> +    "version": 1,
untroll indent

2024-04-09 06:54 UTC, Vermidia commented
I realized that while I did make the paper attachable, bounties and invoices still shared a color. So invoices are blueish now (can definitely change if it's too saturated/unfitting.

2024-04-09 22:19 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Structures/Storage/Crates/crates.yml
> +      offset: "0.0,0.03"
```suggestion
      offset: "0.0,0.03125"
```

needs to be multiples of the pixel size (1 / 32)

2024-04-09 22:19 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Structures/Storage/Crates/crates.yml
> +      offset: "0.0,0.03"
```suggestion
      offset: "0.0,0.03125"
```

here too

2024-04-14 03:39 UTC, merged