Replace the machete and laser in the borg weapons module with an e-dagger and recharging cobra
space-wizards/space-station-14 pull request #26947
Opened 2024-04-14 09:50 UTC by Blackern5000

## About the PR
Replaces the weapons in the syndicate borg weapon's module with
An energy dagger, just an energy dagger.
A recharging cobra called the "Rinkhal" (A type of cobra) that generates one bullet every four seconds and holds up to 10 at a time.

## Why / Balance
Syndies don't get lasers, they use ballistics and energy melees.

## Media

https://github.com/space-wizards/space-station-14/assets/140123969/bc3ae891-fce7-44c4-971d-46e8469fe88e
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: The syndicate agent's cyborg weapons module now uses syndicate weaponry rather than NT weaponry.

2024-04-14 10:05 UTC, SoulFN commented
Lol, i wanted to do the same thing

2024-04-14 13:42 UTC, Dutch-VanDerLinde commented
what about a viper instead

2024-04-14 14:01 UTC, SoulFN commented
> what about a viper instead

Cobra is silent and doesn't leave a bullet casing

2024-04-14 14:34 UTC, SoulFN commented
Maybe, you whould replace e-sword with e-pen?

2024-04-15 00:55 UTC, SoulFN commented
> You still need to spend 8 tc to hijack the borg, so it's actually 13 tc to do this. 18 if you have two borgs though.

But you still have emag, not only borgs

2024-04-16 23:55 UTC, Everturning commented
machetes and advanced lasers are barely used ingame, also poses the question of "how can it make these caseless bullets inside its chassis". 
"syndie borgs" you say, but those are specially built for it. this is just a hijacked borg with no space for it. even saying it's the module is iffy.

2024-04-18 05:53 UTC, SoulFN commented
> machetes and advanced lasers are barely used ingame, also poses the question of "how can it make these caseless bullets inside its chassis". "syndie borgs" you say, but those are specially built for it. this is just a hijacked borg with no space for it. even saying it's the module is iffy.

As i remember, you can put L6-SAW module into regular borg, why he can produce bullets to L6-SAW, but can't produce ammo to cobra?

2024-04-18 05:59 UTC, SoulFN commented
Engi borgs can also produce infinite resources (RCD), producing pistol ammo makes sense

2024-04-18 06:01 UTC, superjj18 commented
> "how can it make these caseless bullets inside its chassis"


How do we get so many bullets in them? Like this! Plus, we fire the whole bullet. That's 65% more bullet per bullet. This is the same technology we've been using on robots for decades. Scares the hell out of them. :trollface:

2024-04-18 06:22 UTC, K-Dynamic commented
Can we just agree on 'bluespace magic' or something, otherwise we'll be arguing about physical and energy limitations of borgs for a while rather than balancing

2024-04-18 07:34 UTC, deltanedas commented
if you are going to argue that infinite cobra is op see infinite l6 which is broken

2024-05-08 11:52 UTC, thebadman4662 commented
Yes, death to borg legions with lasers!

2024-05-10 15:59 UTC, Emisse commented
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

2024-07-04 01:19 UTC, Plykiya commented
Apparently this PR is needed because people are (reportedly) giving their nukie borgs lasers...?

2024-07-04 01:28 UTC, metalgearsloth requested changes
Make it not silenced as it sounds too goofy.

2024-07-12 13:46 UTC, Tayrtahn commented
This will need to be updated to work with the changes to item toggle introduced by #28039

2024-07-12 14:05 UTC, deltanedas requested changes

2024-07-12 14:05 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
> +  parent: EnergySword # I don't just parent it to energy dagger because then it would be able to write on paper.
just give it an edagger, being able to write on paper isnt much when the borg can just talk anyway

2024-07-17 08:31 UTC, IProduceWidgets commented
Do held items still drop when borgs are gibbed? If so this will run into the problem the l6 module has where it drops for crew to use.

2024-07-17 08:41 UTC, Plykiya commented
> Do held items still drop when borgs are gibbed? If so this will run into the problem the l6 module has where it drops for crew to use.

the L6 "spawns" but attempting to interact with it does nothing, it's like a weird cursed item parented to the module

2024-07-18 16:08 UTC, Golinth commented
Can you still cryo Borgs to access their held item?  Same issue as above, if the crew gets their hands on this it could be pretty wild

2024-07-18 23:42 UTC, deltanedas commented
cryoing borgs just deletes items you take out, no exploit here

also borgs just shouldnt be allowed in cryo

2024-07-20 03:12 UTC, metalgearsloth requested changes

2024-07-20 03:12 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
> +    startingCharge: 1000
Are you using cartridges because you actually want it to use cartridges or because you don't know how to make it shoot bullets directly?

2024-07-21 07:04 UTC, metalgearsloth approved these changes

2024-07-21 07:04 UTC, merged