Allow the Command & Super door remotes to use the access of their user again.
space-wizards/space-station-14 pull request #26996
Opened 2024-04-16 11:54 UTC by BramvanZijp

## About the PR
The Command & Super door remote return to their old behaviour of using the access of the remote + the access of the user.

## Why / Balance
This was removed because it made remotes too OP, however now the captains door remote cannot edit most doors while it should be able to. So then somebody made a PR to give caps remote AA, but this was rejected due to making the captain have 2 AA items to loot. This solution takes the best from each, allowing the captain to use his remote alongside his access, meaning he can bolt or emergency access any door so long as he also has his AA ID.

## Technical details
Added a datafield to the DoorRemote component which is false by default, but true for the Command & Super Remotes.
The code now checks for the access of Args.Used (the remote itself) if the field is false, like it does right now, while checking the access of Args.User (the person using the remote, who has the access of the remote due to holding it but also the access of any potential IDs.) if the field is true, which it only is for the command & super remotes (unless the component is changed in VV.)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: BramvanZijp
- tweak: The Command Door Remote can now effect doors that the user (but not the remote) has access to again.

2024-04-16 11:59 UTC, VasilisThePikachu requested changes

2024-04-16 11:59 UTC, VasilisThePikachu commented on Resources/Prototypes/Entities/Objects/Devices/door_remote.yml
> +    ExtendedByID: true
Lowercase e otherwise this will drop a silent error and not work (there's already a PR to fix this)

2024-04-16 12:17 UTC, VasilisThePikachu approved these changes
Approving the *CODE* side of things

2024-04-16 13:19 UTC, BramvanZijp commented
> change for the better, for example, currently HoP remote does not allow to bolt command doors, which is kind of counter-intuitive.

As a note, this is only for the COMMAND Door Remote (The one the captain has.)

2024-04-17 00:46 UTC, Brandon-Huu commented
> Approving the _CODE_ side of things
> 
> I want a bit of discussion with others before we merge.

The door remotes have been so useless, I thought they were just bugged. 
Weird to see that this was somehow an intentional change.

2024-04-17 07:56 UTC, Golinth commented
While I personally wish every door remote would work like this, I 100% agree that this should go through for the Command remote at the very least. I've had multiple instances where I as captain can not get into a department or room, because another head has bolted them. As the person "in control" of the station, the captain should always be able to access anywhere he wants, and a QM bolting off cargo with no ability to change that without sitting and waiting for an engi to hack into them for you actively goes against that view

2024-04-18 01:16 UTC, EmoGarbage404 commented
The general maint consensus is to deny this PR.

Allowing the Captain--and by extent any antagonists who steal both his ID and remote at the same time--to effectively bolt off any door with extremely limited counterplay is a balance issue. For antagonists, it makes it trivial for the captain to retreat anywhere and hard block anyone attempting to chase them. For regular crew, an antagonist can basically lock you in a closet if they get ahold of the remote.

Furthermore, this reduces the amount of autonomy that Heads have over their own departments, as the captain can trivially undo any of the measures they put into place. This doesn't reflect the kind of dynamic that is wanted between Heads and the Captain.

Thank you for your contribution. I'm closing this PR. Feel free to make more contributions in the future.

2024-04-18 01:16 UTC, closed without merging

2024-04-18 01:32 UTC, Golinth commented
> Allowing the Captain--and by extent any antagonists who steal both his ID and remote at the same time--to effectively bolt off any door with extremely limited counterplay is a balance issue. 

This is already the case with the current door remote system, arguably more so. If an antagonist gets ahold of, say for example, the medical door remote, there is already 0 counter play to locking down the entire department. 

> For antagonists, it makes it trivial for the captain to retreat anywhere and hard block anyone attempting to chase them. For regular crew, an antagonist can basically lock you in a closet if they get ahold of the remote.

Again, for both of these, it’s trivial for the captain (or any other head and therefor antagonists) to do the same thing. For doors with no access (such as the glass ones in hallways, or doors made with the RCD) the any remote remote works to bolt to stop chasers, or to trap people.

> Furthermore, this reduces the amount of autonomy that Heads have over their own departments, as the captain can trivially undo any of the measures they put into place. This doesn't reflect the kind of dynamic that is wanted between Heads and the Captain.

This is what I don’t get the most. Am I reading this right in that the captain should not be in control of what happens in departments? If the captain does not stand above heads, and can veto their decisions, what’s the point of a captain in a first place? Have every important decision be done by a vote of heads, not a figurehead that is being relegated to basically be “carry the nuke codes” and nothing else.

2024-04-18 01:50 UTC, PJB3005 commented
I get the feeling we should just remove the ability for the door remote to bolt doors instead.

2025-02-26 13:31 UTC, BramvanZijp commented
I feel like this should/could be revisited now that the AI is in, since this is counterplay to the ai, and the ai is counterplay to this.

2025-02-26 13:49 UTC, BramvanZijp commented
Have pushed an update to this to my origin branch, waiting to hear if we can re-open this PR or if I gotta make a new one.

2025-02-26 16:18 UTC, VasilisThePikachu commented
> Have pushed an update to this to my origin branch, waiting to hear if we can re-open this PR or if I gotta make a new one.

Make a new one