Removes Chaplain
space-wizards/space-station-14 pull request #2699
Opened 2020-12-04 08:54 UTC by SweptWasTaken

Left in the chaplain's clothes and the sprites for the stuff I removed as there's no harm in leaving them there.

Luckily he was never mapped in anyone so no map changes are needed.

2020-12-04 10:40 UTC, PJB3005 requested changes
Just comment it all out instead of straight up removing it.

2020-12-04 14:26 UTC, moonheart08 commented
My map work has chaplain mapped- please just comment it out so we can put it back later.

2020-12-05 05:44 UTC, SweptWasTaken commented
Applied reviews.

2020-12-07 23:23 UTC, Zumorica approved these changes

2020-12-07 23:23 UTC, merged