Add medical gloves to medical loadouts
space-wizards/space-station-14 pull request #27029
Opened 2024-04-16 22:40 UTC by Vermidia

## About the PR

Adds latex and nitrile gloves to loadouts for all medical roles excluding psychologist and interns

## Why / Balance

Make yourself look even more qualified at roundstart.

## Technical details

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![drip](https://github.com/space-wizards/space-station-14/assets/32827189/163f076c-6b37-431f-be10-73d1f16b3f7e)

## Breaking changes

**Changelog**

:cl:
- add: Most medical roles now can choose to start with nitrile or latex gloves in their loadout

2024-04-17 05:20 UTC, Golinth commented
while you're at it, can you add the nurse hat as well?

2024-04-17 06:58 UTC, Vermidia commented
Done

2024-04-17 07:19 UTC, mirrorcult requested changes

2024-04-17 07:19 UTC, mirrorcult commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - GlovesNitrile
why arent these just one `loadoutGroup` called like `DoctorGloves` that all of the jobs have instead of it being duplicated 4 times

2024-04-18 23:47 UTC, Dutch-VanDerLinde commented
#27045 got merged so remove the LatexGloves prototype, since science already covers

2024-04-18 23:49 UTC, Vermidia commented
Have done so

2024-04-20 06:22 UTC, merged