Ghost command now releases artifact ghost role
space-wizards/space-station-14 pull request #27066
Opened 2024-04-17 20:55 UTC by osjarw

## About the PR
If someone picks the sentient artifact ghost role and starts to regret it, they can now `/ghost` and let someone else take the role.

## Why / Balance
Before this PR, the sentient artifact ghost role couldn't be released 

## Technical details
`CanReturn` is set to true because the artifact doesn't have a mobstate, so `IsCharacterDeadPhysically` returns true. Because of this, `/ghost` doesn't release the role.
I added an if clause that sets `CanReturn` to false when the artifact/player/mind has the `ArtifactComponent`, which implies that this is a sentient artifact ghost role.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Before:
The role can't be selected after the artifact has ghosted

https://github.com/space-wizards/space-station-14/assets/62134478/2ea6b33d-1dac-4b52-b29e-c6ce1cc5b1b2

After:
The role can now be selected after the artifact has ghosted

https://github.com/space-wizards/space-station-14/assets/62134478/1d67ad6a-d529-42a9-b6d1-ca4bc6fc17ae

## Breaking changes

**Changelog**

:cl:
- fix: Ghost command now frees up sentient artifact ghost role

2024-04-18 00:24 UTC, metalgearsloth commented on Content.Server/GameTicking/GameTicker.GamePreset.cs
> +
Artifacts shouldn't be hardcoded into ghost code as it just becomes a big mess for forks, probably put in a bool on the component instead or use an event.

2024-05-29 00:35 UTC, AJCM-git commented
@osjarw you coming back to this?

2024-05-29 09:59 UTC, osjarw commented
I can take a look at this again later today.

2024-06-08 16:24 UTC, osjarw commented
Working on this currently, managed to hack together a new way to solve this issue, implemented with events. 
Currently I just need to figure out how to solve the merge conflict properly and just push it.

2024-06-09 16:36 UTC, Mirino97 commented
Reopened by contributor's request

2024-06-09 16:37 UTC, osjarw commented
Hopefully this is an acceptable way of fixing this.. 
I guess that I could also just go and figure out the "proper" way of doing this ghost stuff without just re-calling OnGhostAttempt. 
Anyways also tested this code, it seems to be working and it didn't seem to break anything, like ghosting while in crit or when playing as a mouse. 

Also sorry for taking this long in submitting this code, been a bit busier than expected these past few weeks.

2024-06-09 16:58 UTC, osjarw commented
It looks like that test is failing on the code I submitted, I guess I'll try to figure out how to make it run properly, without failing that test...

2024-06-10 16:54 UTC, osjarw commented
While this PR is in a "mergeable" state, I think it should actually handle the ghost attempt. 
Currently it just calls `OnGhostAttempt` again, and now that I've taken a closer look at it, it isn't really something that should be done. The logging happens twice, and there's a tiny bit of recursion, which isn't really ideal. 

I guess I could just yank out the important bits from `OnGhostAttempt`, but that would cause an annoying amount of code duplication, and git blame wouldn't look as beautiful as it does now..

Actually I guess I'll just go with the recursion route, I'll just set `viaCommand` to false to stop the logging from happening twice, and actually do some null-checks instead of just assuming that the ones that are already done apply to my code.

2024-06-14 01:13 UTC, metalgearsloth commented
It's still failing tests.

2024-06-16 19:33 UTC, osjarw commented
Finally got around to implementing what I wrote in my last comment..

The `DeleteAllThenGhost` test shouldn't be failing anymore, used to fail because one of the nullables was null and I assumed it to already be checked... 
TIL that TryComp can be called with a nullable, in which case it does the handling, so switched to using that. 

Also the admin logs aren't duplicated like I thought in my last comment, apparently I fixed that already.

2024-06-16 19:41 UTC, osjarw commented
This should close #28081

2024-06-16 22:00 UTC, AJCM-git commented
Isnt this already handled by the `GhostRoleComponent.ReregisterOnGhost` field? prob should just fix that if its somehow broken

2024-06-17 03:32 UTC, AJCM-git requested changes
What i said before, forgot to leave it as a review

2024-08-08 10:53 UTC, closed without merging