RD hardsuit reflect chance + description change
space-wizards/space-station-14 pull request #27105
Opened 2024-04-18 21:58 UTC by Hmeister-real

## About the PR
Changes the hardsuit to have a 55% chance to reflect energy, and also minorly increases it's stats.

## Why / Balance
With the recent (major) RD hardsuit nerf in #27094, I think it needs a buff, as the comments said further down in that PR. 

## Technical details
Stat changes and reflect

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Hmeister
- tweak: RD's hardsuit now reflects energy and is a little more protected

2024-04-18 22:06 UTC, Hmeister-real commented
i have genuinely no clue how two checks failed, it is literally such a minor change. If someone has any idea how to fix it please let me know

2024-04-18 22:07 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +           - Energy
indentation is fucked

2024-04-18 22:32 UTC, Hmeister-real commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +           - Energy
👍

2024-04-18 23:57 UTC, EmoGarbage404 requested changes
I don't see why the RD suit, which is already extremely armored and resistant against explosions, needs to have higher amounts of combat-focused armor as well as reflective properties that almost solely impact laser combat.

It's already an extremely powerful bombsuit. I don't think there's really a reason for it to be much more.

2024-04-19 04:45 UTC, ps3moira commented
power creeping the mysta hardsuit lol

2024-04-19 05:37 UTC, Hmeister-real commented
> I don't see why the RD suit, which is already extremely armored and resistant against explosions, needs to have higher amounts of combat-focused armor as well as reflective properties that almost solely impact laser combat.

well the whole reason for it's experimental nature was the fact it was very portable and mobile, but with that removed it needs something unique to replace that. Any suggestions on another feature that would be better then?

2024-04-19 05:58 UTC, deltanedas commented
maybe shitty ninja cloak that wears off after 5s with a big cooldown

2024-04-19 06:26 UTC, K-Dynamic commented
Yeah what's up with this rd suit powercreep going on since the size increase

Just make it 3x3 or 2x4 storage, no need to make rd stronk

2024-04-19 07:16 UTC, Hmeister-real commented
> maybe shitty ninja cloak that wears off after 5s with a big cooldown

Cloak is a syndie thing, don't think it would suit too well

> Just make it 3x3 or 2x4 storage, no need to make rd stronk

Im not touching the size since EmoGarbage merged #27094 with so little discussion. I assume that its a maintainer change and we have no choice in the matter :(

2024-04-19 09:06 UTC, BolloTea commented
What if we gave the suit itself internal blast-proof storage of about 3x4 or 4x3?  This will make it more acceptable and not too op.  Yes, this is a small detail, but quite pleasant.  You can also make a built-in anomaly analyzer or a switchable node analyzer (sorry if I wrote the name wrong).  Still, this is primarily a scientific suit, not a combat one.

2024-04-19 09:13 UTC, K-Dynamic commented
> What if we gave the suit itself internal blast-proof storage of about 3x4 or 4x3? This will make it more acceptable and not too op. Yes, this is a small detail, but quite pleasant. You can also make a built-in anomaly analyzer or a switchable node analyzer (sorry if I wrote the name wrong). Still, this is primarily a scientific suit, not a combat one.

I wouldn't be against this when we get hardsuit abilities some day

2024-04-19 09:38 UTC, Hmeister-real commented
> What if we gave the suit itself internal blast-proof storage of about 3x4 or 4x3? This will make it more acceptable and not too op. Yes, this is a small detail, but quite pleasant. You can also make a built-in anomaly analyzer or a switchable node analyzer (sorry if I wrote the name wrong). Still, this is primarily a scientific suit, not a combat one.

I maybe could try at the storage idea but it would be very basic and just turn the suit into a bag too, but the built-in stuff is out of scope for this, it would be better for a PR adding suit abilities specifically

2024-04-19 09:58 UTC, Hmeister-real commented
no clue why it failed, need help

2024-04-19 10:31 UTC, BolloTea commented
By the suit's abilities, we mean switching modes, such as with the blood-red suit on the TG, where it has two modes?

2024-04-19 14:04 UTC, GoodWheatley commented
Just remove the objective at this point

2024-04-19 14:23 UTC, HelpTheSteak commented
Either remove the objective or unnerf the suit because the hardsuit is now the second hardest objective in the game

2024-04-19 14:42 UTC, DummeHytteOst commented
> Either remove the objective or unnerf the suit because the hardsuit is now the second hardest objective in the game

the objective did have its difficulty increased since its become harder to get, so you likely wont have it with other high difficulty objectives. 

and as i commected here https://github.com/space-wizards/space-station-14/pull/27094#issuecomment-2066721381 i don't think the RD suit needs a buff, as it is incredibly good at what its supposed to be used for.

2024-04-19 15:06 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +  - 0,0,3,2
```suggestion
    grid:
    - 0,0,3,2
```

2024-04-19 15:10 UTC, Tayrtahn commented
> > Either remove the objective or unnerf the suit because the hardsuit is now the second hardest objective in the game
> 
> the objective did have its difficulty increased since its become harder to get, so you likely wont have it with other high difficulty objectives. 
> 
> and as i commected here https://github.com/space-wizards/space-station-14/pull/27094#issuecomment-2066721381 i don't think the RD suit needs a buff, as it is incredibly good at what its supposed to be used for.

I agree with your linked comment. Having some drawbacks also makes it more likely that the RD will take it off and leave it in its locker like you said, which makes it more interesting as a steal objective. If the RD is always wearing it, it's effectively a kill objective.

2024-04-20 03:08 UTC, Partmedia commented
Regrettably I'm opting to close this PR. As many commenters here have already pointed out, I feel that the RD hardsuit is already sufficiently strong that it does not need a "general buff" in response to a size increase in #27094. The size increase was made for the sole purpose of making this a sufficiently challenging steal objective and this "buff" feels like too much.

2024-04-20 03:08 UTC, closed without merging