22182 cigarette pack is too big inside
space-wizards/space-station-14 pull request #27311
Opened 2024-04-25 10:16 UTC by iztokbajcar

## About the PR

I made cigarettes the only allowed item inside cigarette packs.

## Why / Balance

It was done to prevent players from abusing the cig packs as a storage space for things that don't actually belong there.
Related issue: #22182

## Technical details

In `Resources/Prototypes/Entities/Objects/Consumables/Smokeables/Cigarettes/packs.yaml`, the `Cigarette` tag was whitelisted in the Storage components of the `CigPackBase` and `CigPackMixedBase` entities.

## Media

Before (a chocolate bar can be seen in the packet's inventory):
![Screenshot_20240425_120007](https://github.com/space-wizards/space-station-14/assets/50874197/9790a220-6dca-41c3-b4b1-36c6fb777314)

After (I cannot place a chocolate bar inside):
![Screenshot_20240425_121256](https://github.com/space-wizards/space-station-14/assets/50874197/6b15d45f-fc1c-4893-a223-0469f7d0e137)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Cigarette packs can now only store cigarettes.

2024-04-25 12:22 UTC, ElPidor commented
It is necessary to find a new way to store ammunition, and not completely destroy this method, since the use of a cigarette pack is effective due to its size and complexity of use, given the lack of alternatives. It may be worth increasing the weight of the cartridges or finding another storage method that does not lead to “abuse”
in 2 words
Skill issue

2024-04-25 13:51 UTC, Hanzdegloker commented
Damn, I really liked putting my lighter in the thing for safe keeping

2024-04-25 13:53 UTC, keronshb requested changes
Cig Packs are designed to allow more than just cigarettes. If you had some bullets or pills it's completely fine to put into a cigarette pack for safe keeping.

2024-04-25 14:23 UTC, BellwetherLogic commented
Considering that cigs are functionally cosmetic anyway (except for Interdyne Herbals) it feels kinda weird to disallow a small container from holding a lot of little things that aren't also cigs. If you're going to add a whitelist to it I think anything that's tiny and cylindrical should be able to take advantage of the TARDIS-like nature of the humble cig pack... which includes bullets anyway. 

Now, if you wanted to exclude things like syringes, flares, breath masks, etc, I could understand that. (Please don't, I like having somewhere to put all the 1x1 shit that comes in my survival box and makes storage a pain to manage.) But at the very least, lighters should absolutely be whitelisted for this even if an only-smoking-related whitelist gets applied to cig packs.

2024-04-25 14:35 UTC, K-Dynamic commented
Or maybe make cigarette packs act like ammo and swab dispensers?

2024-04-25 15:35 UTC, Hanzdegloker commented
> Or maybe make cigarette packs act like ammo and swab dispensers?

Absolutely not, I want to be able to PICK which cigs I smoke. Dan's soaked smokes foreva

also custom made cigs with like meth from chem

2024-04-25 17:36 UTC, ps3moira commented
I think it'd be fine to allow things cigarette shaped to fit inside. Like a pen or crayon.

2024-04-25 20:02 UTC, ike709 commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +        - Cigarette
They're supposed to hold lighters as well.

2024-04-30 11:46 UTC, metalgearsloth requested changes
Agree with keron here.

If you're going to add a big whitelist to it what's the point of the whitelist...?

2024-05-10 23:55 UTC, EmoGarbage404 commented
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

2024-05-10 23:55 UTC, closed without merging