Add maximum volume to ChemMaster buffer
space-wizards/space-station-14 pull request #27317
Opened 2024-04-25 20:46 UTC by Partmedia

## About the PR
Add a maximum volume to the ChemMaster buffer and make transferring solutions respect the maximum volume. The initial proposed volume limit is 300u.

## Why / Balance
No solution container should have an infinite capacity. That the ChemMaster has an infinite buffer capacity has led to unreasonable meta-strategies that:

- Discourages making pills and bottles, which is the point of the chem master, to be a glorified chemical holding tank
- Discourages using the actual mechanics that are designed to separate chemicals, including electrolysis and centrifuging (https://github.com/space-wizards/space-station-14/pull/22517)
- Having one chemist hoarding all of the round-start base chemicals in their own buffer

The infinite buffer is a [placeholder mechanic](https://discord.com/channels/310555209753690112/675078881425752124/1196275816254930944) that isn't supposed to be there.

300u is an arbitrary limit that is designed to be larger than buckets and the largest obtainable beaker, but small enough to discourage ChemMaster-storing from coming back. Well-justified arguments for a different proposed volume limit welcome.

## Media

https://github.com/space-wizards/space-station-14/assets/3229565/f2426d37-eb35-4fd7-913d-34e2ecb20129

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**

:cl: notafet
- tweak: ChemMasters now have a limited buffer capacity.

2024-04-25 21:14 UTC, deltanedas commented
this kills nukie chem since thats 1 and a half jugs, unusable

2024-04-25 21:20 UTC, beck-thompson commented
> Discourages making pills and bottles, which is the point of the chem master, to be a glorified chemical holding tank

Unless I'm misunderstanding (could easily be the case) I feel like this should really be solved by having a separate buffer for pills rather than just nerffing the chemmaster. Feels like it just "solves" the solution by the chemmaster not being used which is kind of silly. (Your other points are fair though)

2024-04-25 21:22 UTC, thebadman4662 commented
Limited buffer would discourage me even more frankly, at 300u it could let antags have way easier time making pill bombs but at higher it could possibly make it even harder than it is now if chemmasters have to be specialized, and trust me, pill specialization will be very low on that list for non-antags.

Bottles are already very strong, usually they are not used because doctors do not care to be better at their job or medbay simply have no glass. If you take both bottle and vial boxes, its only enough for a single chemist to bottle med and even then they will want few extra bottles for some niche meds. There are some epi bottles too but I would not drain them all into jug and deny them from fellow coworkers.

It would discourage using electrolyze as much because you will need to bother cargo for all the buckets to store recycling products should buffers be too low. Electrolyze is in pretty great spot frankly but atmos pretty much never have any idea how to work with chemists and latter will have to ask captain for access or let them in and set the pipes in LRP. If MRP atmos are clueless you are just boned because you can't work on pipes.

Centrifuge is underused because its terribly bad, 3/10 input compared to electrolyze with large beakers(BSBs make it 3/100, good luck beating THAT should salvs have presents) and take like 3-4 time to complete while only working with vials that are expensive and can't be printed in medbay should they get destroyed. I also do not recall any centrifuge interaction worth doing that electrolysis won't have covered. Right now its best disassembled so you can construct another electrolysis or cryo pod.

So the real question is, how low will be buffer set to punish farming resources with centrifuge and if it will be enough to force chemists into different chemmaster/discarding resources. Keep in mind some maps have as little as single chemmaster so it can be annoying real fast if you have shitsci denying you more of them there.

Low buffer = Chemists will have loads and loads of buckets from harvesting resources everywhere just to function.
Medium buffer = Mix of low and possibly having to get more chemmasters, infighting who gets to work where.
Large buffer = Buffer is added but single chemist can work on single buffer whole shift, nothing really changes except you will want extra chemmasters for mass harvesting electrolyze.

2024-04-25 21:31 UTC, QuietlyWhisper commented
> Limited buffer would discourage...

A lot of these issues would be resolved by providing more materials to medbay and their medical techfab, which can print many bottles and whatnot, and the items that are missing could simply be added.

2024-04-25 21:35 UTC, QuietlyWhisper commented
I do think we'll also need to revisit the chemmaster using material to create pills and bottles, there's already been a pr that gave pills a material cost, and it's very likely you could just reuse that, but with glass, to allow bottles to be created at the station, rather than needing to keep placing a new bottle inside the machine or filling bottles by hand.

2024-04-25 21:40 UTC, thebadman4662 commented
> > this kills nukie chem since thats 1 and a half jugs, unusable
> 
> make a valid chemmaster that has 2000 unit storage

Let it be emag interaction too 😄

2024-04-25 22:15 UTC, thebadman4662 commented
> > * Discourages using the actual mechanics that are designed to separate chemicals, including electrolysis and centrifuging ([Electrolysis and Centrifuge #22517](https://github.com/space-wizards/space-station-14/pull/22517))
> 
> i'm pretty sure that neither the electrolysis or centrifuge can separate chemicals. a workaround to this would be to add a separatory funnel or something

I meant it in sense of using it as much, electrolysis gives you industrial amounts of reagents but then you need loads and loads of buchets/jugs to store them should you want to keep harvesting and buffer is small. 

Plastic production with small buffer will truly be hellish if you do not have BSB.

2024-04-25 22:18 UTC, mirrorcult commented
good change this needed to happen forever ago but now is as good a time as any

2024-04-25 22:32 UTC, QuietlyWhisper commented
> I meant it in sense of using it as much, electrolysis gives you industrial amounts of reagents but then you need loads and loads of buckets/jugs to store them should you want to keep harvesting and buffer is small.
> 
> Plastic production with small buffer will truly be hellish if you do not have BSB.

You should elaborate on this more, because maybe it's not so bad to nerf both these productions too if they're that impressive

2024-04-25 22:32 UTC, Brandon-Huu commented
> this kills nukie chem since thats 1 and a half jugs, unusable

A real chemists doesn't use machines

2024-04-25 22:33 UTC, Brandon-Huu commented
Honestly just remove the machines. Doing chemistry with just jugs and beakers is faster and less annoying.

2024-04-25 22:52 UTC, keronshb requested changes
Since Nukies also have their own variant, this should be balanced around both or make a separate machine for nukies with a higher capacity.

300 seems also a little low. It's a static machine so arguably it should be equal or greater than a bluespace beaker.

2024-04-25 22:54 UTC, Partmedia commented
> Since Nukies also have their own variant, this should be balanced around both or make a separate machine for nukies with a higher capacity.
> 
> 300 seems also a little low. It's a static machine so arguably it should be equal or greater than a bluespace beaker.

Could you suggest a number that you feel would be balanced for both?

2024-04-25 23:29 UTC, thebadman4662 commented
BSBs are 1000 and it should be plenty for both crew and nukies... I suppose chemist on Reach will need to maintain condenser/electrolyze locker from now but it won't be sadistic to newbie chemists.

2024-04-25 23:33 UTC, Brandon-Huu commented
The UI might want to show the buffer limit, like it shows the limit for containers.

2024-04-25 23:47 UTC, keronshb commented
> Could you suggest a number that you feel would be balanced for both?

1000 should be fine, to match a bluespace beaker.

2024-04-26 00:10 UTC, Kromabae commented
why do nukies need a bigger buffer?

2024-04-26 00:30 UTC, EpicJoston commented
Chemmasters being able to hold infinite buffer is breaking the balance of the game how? I'm sorry to be blunt, but if you want pills and bottles to be used in med more then make them more accessible or easier to use.

Bottles aren't being used because its annoying to get enough for all the doctors, which is why people use the accessible jugs.

Pills aren't being made because its annoying to dedicate a whole Chemmaster just to the production of pills.

If these options want to see more use then make them more accessible. Let Chemmasters have a second buffer to make pills. Give med more roundstart bottles. Don't make what is currently being used less accessible, because you're going to kill the fun of the game that way.

Over in the Science department, mechanics are being tweaked to make the department more accessible and more rewarding. Recently, Anomalies got a huge overhaul to make their point gain worth the risk, and now Artifacts have their best upgrade available round start. This makes science more accessible and Scientists have more fun as they spend less time doing tedious tasks to get to the good parts of Sci.

Balance changes should make things more fun. I do not see how any Chemist is going to have more fun with this change, and can only see how it becomes more annoying and frustrating.

Instead, buff Bottle accessibility and add easier Chemmaster pill making functionality, and we'll likely see both being used more often without nerfing anything.

2024-04-26 01:27 UTC, Brandon-Huu commented
> why do nukies need a bigger buffer?

because they suck at chem

2024-04-26 01:30 UTC, PJB3005 commented
Half these problems people have with "bottles suck" "pills suck" are because the relevant feature isn't correctly implemented in SS14 and/or the UI for it is hot fucking garbage.

You want to fix the chem master being an infinite chemistry buffer? Make it so the alternative is as least as good as it is in SS13 instead of forcing people to juts suffer.

2024-04-26 01:31 UTC, PJB3005 commented
Bottles shouldn't even cost glass because that just makes inventory management harder and it's another dumb "wow I didn't get materials I guess I can't do my job" pinch that does not balance the game in any way. In SS13 they're just magic free

2024-04-26 01:38 UTC, thebadman4662 commented
> Bottles shouldn't even cost glass because that just makes inventory management harder and it's another dumb "wow I didn't get materials I guess I can't do my job" pinch that does not balance the game in any way. In SS13 they're just magic free

Free bottles?! Damn those Nanotrasen budget cuts on the 14th are driving me crazy now.

2024-04-26 01:38 UTC, Partmedia commented
> Bottles shouldn't even cost glass because that just makes inventory management harder and it's another dumb "wow I didn't get materials I guess I can't do my job" pinch that does not balance the game in any way. In SS13 they're just magic free

I don't disagree but someone else merged that in https://github.com/space-wizards/space-station-14/pull/11207 and I'm not going to revert that here.

> You want to fix the chem master being an infinite chemistry buffer? Make it so the alternative is as least as good as it is in SS13 instead of forcing people to juts suffer.

This is sort of a "when someone codes this" (or rather, when someone reverts this) issue.

2024-04-26 01:59 UTC, Rainbeon commented
I do not see how this change achieves any of the 3 bulleted problems listed.

>Discourages making pills and bottles, which is the point of the chem master, to be a glorified chemical holding tank

The ChemMaster buffer being large is not at all why pills and bottles are not made. You will not see any more pills or bottles after this change as you would before it.

>Discourages using the actual mechanics that are designed to separate chemicals, including electrolysis and centrifuging 

They do not perform the same function at all, I am not even sure what point you are making here? The ChemMaster buffer has zero relation to the usage of electrolysis and centrifuging. These are machines that provide unique interactions to turn reagents into other reagents.

>Having one chemist hoarding all of the round-start base chemicals in their own buffer

I have not seen this happen at all, it is not a "meta" strategy, it's really bad to do, actually. Aluminum and Iodine tend to get dumped here and are the only base chemicals this consistently happens for (and that's because it gives you extra empty jugs and these reagents are entirely useless).

I am not really convinced this change has any positive impact whatsoever, given the listed ones do not seem to be actually correlated at all, and just seems to be adding an extra point of frustration to Chemist gameplay for not much reason. Overall agree with PJB's assessment.

2024-04-26 02:21 UTC, keronshb requested changes
The 1000 max volume is better, but after reading the comments and thinking over things the actual fix would be to improve the systems instead of just making a bandaid fix and adding to tech debt, while simultaneously making the experience worse for people while they're forced to wait for something new.

Is this so game breaking at the moment that this _needs_ to be merged?

2024-04-26 06:27 UTC, thebadman4662 commented
> for example, the infinite buffer is being cited as a reason that #27304 cannot work

Infinite buffer and having to use buckets or middleman container do not really affect eachother much other than chemists having to go for more buckets or discard chems like iodine/aluminium/nitrogen/sodium/fluorine so they can have more jugs to pour meds into.

Most jugs you take out and dump into buffer will be used to store meds made from reagents you just dumped, with some water stealing some of that space as drawing from sinks does not give you any extra containers and cryo meds use dexalin which expands in size by 50% on creation.

> I feel that for any chemist who isn't power-gaming, 1000u is "practically infinite". Ultimately though, I'll leave this as a PM/wizard decision. Feel free to merge/close as you see fit.

While I agree 1k+ is enough to basically make all medical needs, even if not at same pace as before nerf, is using sink, condenser and electrolyzer really powergaming? I thought its part of chemist job to keep medbay supplied and harvest reagents so it can continue to be supplied with least strain on other departments if possible.

2024-04-26 09:45 UTC, CastalBW commented
I Kind of see the point to limiting the chemmaster but at the same time, we need better ways to store chems other then leaving jugs on the floor first, I know we have lockers on some maps, but having to look through a list full of jugs of possibly unlabelled chems, would not be fun and would make learning chem even worse.

2024-04-26 10:02 UTC, slarticodefast commented
> (for example, the infinite buffer is being cited as a reason that https://github.com/space-wizards/space-station-14/pull/27304 cannot work)

Since I am the one who suggested limiting the buffer in that PR I would like to clarify my statement:

>Alternative suggestion to make pills more viable:
>
>- Allow the chemmaster to select reagents from the buffer when making pills/filling bottles
>- Allow more than one pill bottle to be inserted, so you can make more than 10 pills at a time
>- Limit the buffer to something reasonable like 1000u

I think these changes should be made at the same time so that chemistry does not become unneccesarily tedious in the meantime. However, the buffer definitely should get limited at some point. My personal opinion is that using jugs, bottles and pills should be all equally viable and easy to use from an UI-perspective. The choice is then up to the player and we would see more variation of playstyles instead of one meta strategy.

2024-04-26 10:28 UTC, 0x6273 requested changes
The current and max volume should be shown in the UI, like they are for the container slot.

2024-04-26 13:57 UTC, keronshb commented
> If you have a design doc that explains what "the actual fix would be to improve the systems" looks like, that could help.

Take a look on how it's implemented in SS13, hop on a private server or play a live game. 

Now it may be implemented different per server, try a few different ones out, TG, Citadel, VG, etc. See what works, what doesn't.

Also PJB's comment summarizes it.

2024-04-26 14:49 UTC, thebadman4662 commented
Bottle production is simply taking a jug of medicine and pouring it in. Praise bottlemed.

Pill production been pain since limted chems start even more than usually, only map with enough chemmasters was Barratry because there was only a single chem dispenser. I would love dedicated pillmaker, yes.

2024-04-26 15:13 UTC, IProduceWidgets commented
My well adjusted argument is for a common factor of 180 and 100, of which the only sensible ones without getting egregious are 900 (my preferred) or 1800.

The reason for this is 90u is the common mix size for most base meds including bicard, inaprov, derma, and dylo. 180u is the size of a fully filled pill canister at 20u*9 = 180u, and 100u is the size of large beaker.

2024-04-26 15:17 UTC, IProduceWidgets commented
> Bottles shouldn't even cost glass because that just makes inventory management harder and it's another dumb "wow I didn't get materials I guess I can't do my job" pinch that does not balance the game in any way. In SS13 they're just magic free

They would need to also not drop shards or you have an infinite glass machine.

2024-04-26 15:53 UTC, PJB3005 commented
Limiting the volume of the chem master to 1k doesn't even change anything. You want to really fix the powercreep? Make it so it isn't a stasis beaker.

*Ahem*

I've thought about this topic for the past hour again and here are my thoughts on the whole matter.

## Currently

People use the chem master for kinda three purposes:

**Lazy, unorganized buffer of fucking-whatever-anything:** I have some shit in my beaker I don't care about, transfer it into the buffer. Never have to worry again.

**Chem dispenser 2:** Some reagents like Benzene are common to need for other chemical reactions, so you end up needing to mass-produce these. Hell, a competent chemistry lab has the hotplate running immediately at round start, just so they can use various chemicals later immediately. These are then accessed later in the same way the regular chem dispenser's buttons are.

**I need an extra jug:** In our current meta where medicine is provided to doctors in the form of jugs, chemistry does not start with enough jugs round start to provide all the chemicals they should. So they need more jugs. This is achieved by just dumping a jug directly into the chem master so you can empty it and use it for something else, without even losing the reagent because the chem master has infinite buffer. Trust me though, if it didn't people would just start flushing some useless jugs down the drain instead.

So how can we divy up these real, necessary use cases without telling chemists "lol fuck you", as this PR does? I have some ideas:

## Improvements

**Fix the smart fridge:** The smart fridge in SS14 is basically not implemented at all. In SS13 it allows you to store and index bulk amounts of pills, bottles, and so on. This is great. 

**Fix bottle production:** Bottles should be free and infinite so you can use them as cold storage for garbage you don't care about (what even was the ash for when you produce insuzine?) Then dump them into the smart fridge for cold-storage access later. 

**Chem dispenser upgrade:** Make chem dispensers start out with like 10 slots of free jugs that can be transferred into by chem masters. The idea here is that you get a "transfer to chem dispenser" button right in your chem master, so you can dump stuff like the aforementioned benzene into the chem dispenser. This allows the chem dispenser to replace the use cases of second-stage reagents storage.

**Maybe add the ability to transfer directly into a jug or other container:** Another idea I had is that you can have an "out-only" slot in the chem master that can fit jugs. So you can transfer from a beaker into a jug, inside the chem master UI.

**Make the UI not dogshit:** Seriously this UI needs work, especially to make the last point work.

By the way, it should probably be noted that in SS13 you can upgrade the chem master's internal buffer. On TG the default size is only 100 units, but it can be upgraded to 600 with bluespace beakers.

2024-04-26 16:58 UTC, thebadman4662 commented
> **Chem dispenser 2:** Some reagents like Benzene are common to need for other chemical reactions, so you end up needing to mass-produce these. Hell, a competent chemistry lab has the hotplate running immediately at round start, just so they can use various chemicals later immediately. These are then accessed later in the same way the regular chem dispenser's buttons are.

There is another layer to this as chem dispensers will cool down your beakers preventing you from hotmixing, though I think beaker needs to be empty for it to happen? I jug/masterchem so much I frankly would have to check if mixes coold own to... Either way, using the dispenser slows down your production a lot if you require heat to make many hot mixes in a row.

2024-04-26 23:15 UTC, deltanedas commented
> chem dispensers will cool down your beakers

this is false

2024-04-26 23:26 UTC, thebadman4662 commented
> > chem dispensers will cool down your beakers
> 
> this is false

Actually, it is correct. Any amount of any chem will reset temperature if container is empty, it will dillute it otherwise.

![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/21f0a3e3-d019-4e36-afbd-0661c95ce706)
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/7dd97c6f-22c8-4f8d-9242-9a411f82492e)
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/dfe87f2c-efb0-4dbd-b62d-2835dab65526)

2024-04-26 23:44 UTC, deltanedas commented
thats a bug it should use the source solution temperature if adding to an empty container

2024-04-26 23:51 UTC, osjarw commented
> thats a bug it should use the source solution temperature if adding to an empty container

Just tested this, the beaker temperature is set to the solution's temperature. 
Tested this by heating up the jug before trying to reset the beaker temperature. Now it's "reset" to the same temperature as the solution inside the jug

2024-04-27 02:07 UTC, QuietlyWhisper commented on Resources/Prototypes/Entities/Structures/Machines/chem_master.yml
>      unlimited: true
```suggestion
    unlimited: false
```
Does this need to be changed to false?
![image](https://github.com/space-wizards/space-station-14/assets/121047731/83c444ed-0a71-48de-81da-e259a4492154)

2024-04-28 09:29 UTC, EpicJoston commented
If we're going to make a change as drastic as this, the system that replaces it needs to be just as good or better to use. We can't just make a change that will make people hate playing the role because "now its balanced". A role being fun and feeling good to play should always take priority, even if its at the cost of things being imbalanced for it. I'm just going to parrot PJB's comment, incentivize people to use pills and bottles instead of removing what's currently available.

However, we need to keep med as is until new med gets finalized, because everything we know about how med works is going to change fundamentally. Changes like this and the syringes not working on jugs just seem like screwing chem and med players over for no good reason.

2024-04-28 09:39 UTC, metalgearsloth commented
See PJB's comment that we should work on the problem not the symptoms.

2024-04-28 09:39 UTC, closed without merging