action refactor proper ecs edition
space-wizards/space-station-14 pull request #27422
Opened 2024-04-28 02:41 UTC by deltanedas

## About the PR
nuked BaseActionComponent, theres now ActionComponent InstantActionComponent TargetActionComponent EntityTargetActionComponent WorldTargetActionComponent

instead of casting component to do things it uses events

made diona gib inherit BaseSuicideAction

## Why / Balance
no evil component inheritance, actually using events and different components

i see a lot of new players gib themselves on accident as diona since they dont know Gib yourself! gibs yourself

## Technical details
read the yml :trollface:

added a few base actions, notable now **every action inherits from BaseAction** so when entity categories are a thing *hopefully* thatll make it really easy to categorize them similar to objectives.

## Media
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
- all action related components are now in Content.Shared.Actions
- BaseActionComponent and BaseTargetActionComponent are removed, they use proper ecs instead of inheritance now
- ActionComponent has access so you need to use ActionsSystem to modify it instead of setting things directly
- use `_actions.SetEvent` instead of (previously, casting the base action component) setting the component Event field directly

**Changelog**
:cl:
- tweak: Diona WGib yourself!" action now has a suicide warning like microbombs.

2024-04-28 03:06 UTC, keronshb commented
This should wait for and be tested with [22568]

Im just going to finish that one now and then start on any extra spells after.

2024-08-08 19:19 UTC, deltanedas commented
draft until mapping state is fixed and doesnt need mapping_actions

2025-04-17 10:16 UTC, deltanedas commented
i could fix them if anyone cared to review

2025-04-17 10:20 UTC, metalgearsloth commented
> i could fix them if anyone cared to review

If you did middleware style events so we could fix every event being hardcoded otherwise eh half of actions needs a cleaver.

2025-04-17 10:22 UTC, deltanedas commented
still infinitely better than what we have now

2025-04-17 10:23 UTC, metalgearsloth commented
I'd review it but can't guarantee 2nd review lol.

2025-04-17 10:31 UTC, metalgearsloth commented
Ping me in a month bitch.

2025-04-18 00:21 UTC, deltanedas commented on Resources/Prototypes/Magic/mindswap_spell.yml
> +      requireAll: true
notice how it didnt have requireAll before so wizards could mindswap into ANY mind container, even pais and shit

2025-05-02 20:59 UTC, keronshb commented
If I'm reading this right, does this just mean there's separate Action Comp, but also there's separate action comps on top of the base action comp?

2025-05-02 21:04 UTC, deltanedas commented
there is no component inheritance anymore

2025-05-02 21:20 UTC, keronshb commented
> there is no component inheritance anymore

Nah I get that but I see you add like:
  - type: Action
    useDelay: 0
    itemIconStyle: BigAction
    sound: !type:SoundPathSpecifier
      path: /Audio/Magic/staff_animation.ogg
    icon:
      sprite: Objects/Magic/magicactions.rsi
      state: spell_default
  - type: EntityTargetAction
  - ....

So an ActionComp and a separate EntityTargetActionComp.
In theory doesn't this add the same amount of overhead?

2025-05-03 14:50 UTC, deltanedas commented
correct the current implementation doesnt have much overhead removal its more code quality
in the future though moving stuff like use delay into its own component (perhaps call it UseDelayComponent who knows) would be much simpler as it isnt duplicated across multiple inherited components

2025-05-03 21:55 UTC, keronshb commented
> correct the current implementation doesnt have much overhead removal its more code quality in the future though moving stuff like use delay into its own component (perhaps call it UseDelayComponent who knows) would be much simpler as it isnt duplicated across multiple inherited components

That's probably fine then. I've brought this up to maints since it's going to be a rather large undertaking to review and test.
Very likely that, if we decide to merge this, it'll line up after an update so it has a full 2 weeks on Vulture to test.

Since you're also working on actions, how well do you think this new system you set up would handle:
- Multiple events
- Different targeting logic
  - For ex) You may have a "main" targeting logic like instant or world target, and then a sub targeting system where you would:
  - Instant + Sub Targeting Logic to target all on screen
  - World + Sub targeting logic to make Custom Shape to target tiles (like a 3x3 square or like how Force Wall does a 1x3)
  - Instant + All on screen + custom shape under them

Think this would work as a mix and match of components? I was thinking more in the lines of prototypes, but I'm trying to pick more brains about this since I plan on working on another refactor right after this.

2025-05-03 22:22 UTC, deltanedas commented
multiple events would be changing SetEvent to SetEvents and passing a list instead of a single event, easy to do
the action executing code already had event removed from the params so no more changes to anything using it like NPCs needed, they are already event-count agnostic

what would need changing is how targets are specified, right now only entity-targets can be changed by event handling. would need to flesh it out more to have coords as well

the targeting client code is still very hardcoded and would need an overhaul to not be specific to certain components

2025-05-14 16:42 UTC, keronshb commented
@deltanedas Fix conflicts. We're going to put this on a test merge branch and see how it goes.

2025-05-14 16:54 UTC, deltanedas commented
test branch aka vulture :trollface:

2025-05-18 12:22 UTC, metalgearsloth commented
Thanks for keeping it open will try and push it through in the next week.

2025-05-18 15:55 UTC, keronshb commented
> Thanks for keeping it open will try and push it through in the next week.

The plan is we're going to push it to its own test branch that will be pushed to vulture so it has some proper time to test.

2025-05-18 23:52 UTC, keronshb commented
> ALSO FIXED BEING ABLE TO MINDSWAP WITH **ANY** MINDCONTAINER ENTITY, INCLUDING PAI/AI/SENTIENT GUN

This was intended IIRC. At least for PAI & AI.

2025-05-24 15:07 UTC, keronshb commented
@deltanedas  see about fixing the conflicts so we can merge today/tomorrow

2025-05-24 16:21 UTC, deltanedas commented
i already have a separate pr fixing all the maps

2025-05-24 20:42 UTC, keronshb commented
> i already have a separate pr fixing all the maps

Merged

2025-05-26 15:35 UTC, deltanedas commented
you have a button for that too but yeah

2025-05-26 16:37 UTC, keronshb commented
Merging, seeing how this goes.

2025-05-26 16:37 UTC, keronshb approved these changes

2025-05-28 13:08 UTC, DrSmugleaf approved these changes
Looks fine other than 2 nitpicks thanks for finishing the work splitting up action data

2025-05-28 18:32 UTC, keronshb commented on Content.Shared/RatKing/SharedRatKingSystem.cs
> +        var actions = new Entity<ActionsComponent>(uid, comp);
```suggestion
        var actions = new Entity<ActionsComponent?>(uid, comp);
```

2025-05-28 18:33 UTC, keronshb requested changes
That & fix conflict and we can merg :trollface:

2025-05-28 19:52 UTC, merged

2025-05-28 19:52 UTC, ScarKy0 commented
Hopefully vulture doesnt blow up

2025-05-29 05:51 UTC, Pronana commented
Hey I have some questions about resolving some merge conflicts that came up as a result of this PR, is there a good way I can contact you that isn't github?

@deltanedas

2025-05-29 13:49 UTC, deltanedas commented
use matrix if you want @deltanedas:kde.org