Remake gasp popup to emote
space-wizards/space-station-14 pull request #27736
Opened 2024-05-06 19:14 UTC by lzk228

## About the PR

Remake gasp from popup to emote
Add sound to gasp and deathgasp

Resolves #18194 
Remake of #23278 

## Why / Balance

Good

## Technical details

Some datafield was renamed from popup to emote

## Media

https://github.com/space-wizards/space-station-14/assets/124214523/4c037e0e-6ad2-437d-90ce-a11b24ce0ef9

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Gasp and deathgasp emotes now have a sound.

2024-05-06 20:12 UTC, FairlySadPanda commented
Was going to go "oh, this should cover both dimorphisms and also should be rigged in as a emote so people can gasp for RP reasons" but you've already gone it 👏

2024-05-06 20:46 UTC, AJCM-git requested changes

2024-05-06 20:46 UTC, AJCM-git commented on Content.Server/Body/Components/RespiratorComponent.cs
> +        [DataField("gaspEmote", customTypeSerializer:typeof(PrototypeIdSerializer<EmotePrototype>))]
use protoid

2024-05-06 20:46 UTC, AJCM-git commented on Resources/Audio/Effects/Gasp/attributions.yml
> +  source: "https://github.com/tgstation/tgstation"
the source must be a permalink to the file (or folder in this case) containing the sounds

2024-05-28 23:56 UTC, AJCM-git approved these changes

2024-05-28 23:56 UTC, merged