Bartender Drip DLC
space-wizards/space-station-14 pull request #27767
Opened 2024-05-07 07:45 UTC by Golinth

## About the PR

Added some amazing bartender drip made by sunnysmiles11 (Lena Milize) on discord, added the new clothes to loadouts, and some new senior bartender drip as well (As explained by Lena, experienced bartenders IRL wear black clothes). The timegate can be removed if it is a point of contention.

## Why / Balance

Additional bartender drip. Shouldn't affect game balance, as it is drip. With the dark uniform, the crew can expect the bartender to be experienced at their job, and may feel comfortable ordering more advanced drinks. Starting bartenders will also 

## Technical details

Purely YML and sprite changes.

## Media

![image](https://github.com/space-wizards/space-station-14/assets/22528949/d2ce82d2-12ea-459d-84b3-274aa1d006e1)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added new bartender drip!

2024-05-07 07:46 UTC, lzk228 commented
wouldnt be better to make bowtie a separate item?

2024-05-07 07:48 UTC, skypatrol21 commented
Much-needed diversity to an underappreciated role this addition would help add a little variety to one of the most RP heavy roles in the game. Up and tell this point, bartender drip has been pretty limited. This would be a refreshing update.

2024-05-07 07:52 UTC, UbaserB commented
I LOVE TIME-GATES!
Honestly, I feel like we need more time-gates for all sorts of roles, even if it's not "senior". It helps with the immersion and gives you goals to work towards. Always appreciate that.

2024-05-07 07:58 UTC, Golinth commented
> wouldnt be better to make bowtie a separate item?

Probably yes, but that would add a little bit more work than I wanted on this PR, and I was hoping to get this merged right before the content freeze takes place. After the content freeze I'm 100% open to adding some new bowtie options as an alternative to neckties.

2024-05-08 01:54 UTC, EmoGarbage404 commented
i don't really see a point in adding playtime gating to these

2024-05-08 01:57 UTC, metalgearsloth requested changes

2024-05-08 01:57 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +
Why can't we just use recolouring for this? Seems unnecessarily copy-pasted together.

2024-05-08 01:57 UTC, Golinth commented
> i don't really see a point in adding playtime gating to these

Only the dark color scheme gets the playtime gate, and the reasoning behind it was that IRL, experienced bartenders do wear darker colors.

2024-05-08 01:58 UTC, Golinth commented
Mobile GitHub moment. I’ll start working on the review.

2024-05-10 23:45 UTC, EmoGarbage404 commented
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

2024-05-10 23:45 UTC, closed without merging