Shotgun spread refactor
space-wizards/space-station-14 pull request #27773
Opened 2024-05-07 16:32 UTC by RiceMar1244

## About the PR

Makes the code for firing a spread of projectiles use a new component instead of the CartridgeAmmoComponent.

## Why / Balance

I noticed multiple people had tried to introduce energy spread weapons to the game in the past but they were rejected on the basis of spread code.
Previously only shotgun cartridges could define projectile spreads. With this refactor, now things like energy weapons will be able to fire spreads.

## Technical details

I added a new component, ProjectileSpreadComponent. The new component now holds the projectile count and spread data that was previously in the CartridgeAmmoComponent, as well as an additional entity prototype field. In the GunSystem, the code for spawning the original bullet uses the switch case's preferred method (spawning the bullet from the cartridge prototype for CartridgeAmmoComponent and just launching the projectile it already has for AmmoComponent) but uses the ProjectileSpreadComponent to launch the rest of the spread.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Nothing breaks as a result of the changes.

**Changelog**

No CL!

2024-05-16 14:00 UTC, RiceMar1244 commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
> +
Oh no, thanks for the catch. If I remember correctly, I think the code was complaining about a potentially null value, so I thought id check it at the very start. Ill look into this.

2024-06-18 13:45 UTC, metalgearsloth commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
> +
This is slightly too copy-paste with the above for my taste and needs combining please.

2024-06-18 13:46 UTC, metalgearsloth requested changes

2024-06-18 13:46 UTC, metalgearsloth commented on Content.Shared/Projectiles/ProjectileSpreadComponent.cs
> +    [ViewVariables(VVAccess.ReadWrite), DataField("count")]
Needs updating to modern code standards i.e.
- Needs to actually be networked.
- EntityPrototype serializer was long deprecated and replaced by entprotoid.
- Datafield strings are unnecessary.
- VVRW is implicit on datafields now.

2024-06-18 16:08 UTC, RiceMar1244 commented
Alrighty, Ill see what I can do. Thanks for the feedback!

2024-07-21 04:17 UTC, metalgearsloth commented
Re-open if you come back to it.

2024-07-21 20:32 UTC, RiceMar1244 commented
Thanks for closing it up for me Sloth. I was hoping Id feel like coming back to it but i dont think I will right now. I think I just really want to work on something of my own right now. Cheers!

2024-08-03 13:26 UTC, merged