Traitor objective issuers
space-wizards/space-station-14 pull request #27855
Opened 2024-05-09 18:47 UTC by whateverusername0

## About the PR

Traitors now know who hired them.

## Why / Balance

Spicing up the briefing text, looks nice imo. Can also be used for RP if anyone cares.

## Technical details

GenerateBriefing now takes objectiveIssuer argument, which if null will be defaulted to "The Syndicate"

## Media

new briefing text
![image](https://github.com/space-wizards/space-station-14/assets/113782077/b1d60914-ec59-453e-a25e-f1481a42eb2e)

if we don't have an employer
![image](https://github.com/space-wizards/space-station-14/assets/113782077/1d6af62f-3857-45ec-ad7f-fe094921d3e4)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: 
- tweak: Traitors now know their employers.

2024-05-09 18:49 UTC, Dutch-VanDerLinde commented
very epic

2024-05-09 19:21 UTC, mirrorcult commented
should read more like `You are a traitor sent by (corporation) on behalf of The Syndicate.` imo

2024-05-09 20:44 UTC, Brandon-Huu commented
Having traitor in the description is kinda weird.

2024-05-09 20:48 UTC, Dutch-VanDerLinde commented
> Having traitor in the description is kinda weird.

well they're traitors are they not?

2024-05-09 21:04 UTC, Hrosts commented
> Having traitor in the description is kinda weird.

Doubling on the weirdness thing, though it's not a huge issue.
I think it would be better to separate these into 2 sentences:

> You are a traitor.
CyberSun Industries could use your assistance.

Or something of this sort.

2024-05-09 22:37 UTC, Brandon-Huu commented
> > Having traitor in the description is kinda weird.
> 
> well they're traitors are they not?

Traitor would imply that they were working for NT(or whoever) then joined the syndicate.

2024-05-10 00:55 UTC, mirrorcult commented
> > > Having traitor in the description is kinda weird.
> > 
> > 
> > well they're traitors are they not?
> 
> Traitor would imply that they were working for NT(or whoever) then joined the syndicate.

the antag is literally called traitor, take it up with whoever added it to ss13 15 years ago or whatever

2024-05-10 01:32 UTC, Brandon-Huu commented
> the antag is literally called traitor, take it up with whoever added it to ss13 15 years ago or whatever

Yeah that's its OC name not IC

2024-05-10 01:33 UTC, mirrorcult commented
'syndicate agent' as before sounds cleaner than 'traitor' regardless so i guess it doesnt matter

2024-05-10 01:33 UTC, Dutch-VanDerLinde commented
> > the antag is literally called traitor, take it up with whoever added it to ss13 15 years ago or whatever
> 
> Yeah that's its OC name not IC

not really they literally are traitors

2024-05-10 01:33 UTC, mirrorcult requested changes

2024-05-10 01:33 UTC, mirrorcult commented on Resources/Locale/en-US/game-ticking/game-presets/preset-traitor.ftl
> +    You are a traitor sent from {$corporation}.
```suggestion
    You are an agent sent by {$corporation} on behalf of The Syndicate.
```

2024-05-10 02:00 UTC, mirrorcult approved these changes

2024-05-10 02:01 UTC, merged