Adds Support for Guidebook Buttons in UIs
space-wizards/space-station-14 pull request #27891
Opened 2024-05-10 18:38 UTC by ike709

## About the PR
`FancyWindow` UIs can now specify a guidebook entry prototype ID. If one is set, a help button is added to the UI header next to the close button to open the guidebook.

Since this is just a straight QoL buff I assume it's kosher for the freeze.

## Media
Right now the sprite is just the verb icon but downscaled, which doesn't look the best. Better sprite coming when you draw it.

https://streamable.com/16hyb9

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: UIs can now link to a Guidebook entry via a help button in the top right corner.
- add: Added the help button to the reagent dispenser UI.

2024-05-10 19:31 UTC, moonheart08 requested changes
Aside from it furthering the StyleNano problem, lgtm. just fix that and this should be good.

2024-05-10 19:32 UTC, moonheart08 commented on Content.Client/Stylesheets/StyleBase.cs
> +                    }),
An example using the first rule:
```cs
    Element<TextureButton>().Class(FancyWindow.StyleClassWindowHelpButton)
        .Prop(TextureButton.StylePropertyTexture, textureHelpButton)
        .Prop(Control.StylePropertyModulateSelf, Color.FromHex("#4B596A"))
```

2024-05-10 21:48 UTC, moonheart08 approved these changes

2024-05-11 02:21 UTC, merged

2024-05-11 02:32 UTC, ike709 commented on Content.Client/Chemistry/UI/ReagentDispenserBoundUserInterface.cs
> +                HelpGuidebookIds = EntMan.GetComponent<GuideHelpComponent>(Owner).Guides
For people looking to add this functionality to other PRs, this is literally the only code change needed to add the guidebook to a UI as long as the entity has `GuideHelpComponent` already.