Animal flavor text
space-wizards/space-station-14 pull request #2796
Opened 2020-12-21 07:53 UTC by DmitriyRubetskoy

Hopefully witty enough, and aren't too long.

2020-12-21 08:00 UTC, SweptWasTaken commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +  description: Their lives are constant pain due to their inner-body knees
Period.

2020-12-21 08:02 UTC, DmitriyRubetskoy commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +  description: Nice to have, but you can't build a civilization on foundation of honey alone
It is a reference to the https://www.youtube.com/watch?v=JEYh5WACqEk&t=518s on 9:04

2020-12-21 08:10 UTC, Injazz commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +  description: Despite popular misconseptions, is not actually made of butter
I don't feel "popular misconceptions" is appropriate wording.
Use either _"popular beliefs"_, or_"common misconceptions"_.
Also there is a typo in "miscon**s**eptions"

2020-12-21 09:24 UTC, Injazz requested changes

2020-12-21 09:26 UTC, Injazz commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +  description: A folk legend goes around that his claw snaps spacemen out of existance over distasteful remarks. Be polite and tolerant for your own safety.
existence*

2020-12-21 10:58 UTC, DmitriyRubetskoy commented
Damn I need to spellcheck when writing large amounts of text, this is embarrassing

2020-12-21 11:00 UTC, Zumorica requested changes

2020-12-27 10:26 UTC, SweptWasTaken approved these changes

2020-12-27 10:27 UTC, SweptWasTaken commented
Didn't cringe at any of the descriptions and I think the changes made were constructive. 

Ready for a merge imo.

2020-12-27 16:57 UTC, DmitriyRubetskoy commented
Yeah probably good for a merge

2020-12-27 16:59 UTC, Zumorica approved these changes

2020-12-29 20:51 UTC, DmitriyRubetskoy commented
Please merge?..

2020-12-30 00:52 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +  description: Nice to have, but you can't build a civilization on foundation of honey alone.
```suggestion
  description: Nice to have, but you can't build a civilization on a foundation of honey alone.
```

The actual quote.

2020-12-30 11:07 UTC, metalgearsloth approved these changes

2021-01-01 17:26 UTC, SweptWasTaken commented
Merge me.

2021-01-01 17:27 UTC, Zumorica approved these changes

2021-01-01 17:27 UTC, merged