Accent trait limit
space-wizards/space-station-14 pull request #28046
Opened 2024-05-15 09:07 UTC by TheShuEd

## About the PR
updated traits code, removed obsolete constructs. Traits are now divided into categories, where you can customize how many traits you can take in a category.

Also added Italian and cowboy accent traits.

## Why / Balance
5 accents on one character makes speech horribly unintelligible.

## Media
![image](https://github.com/space-wizards/space-station-14/assets/96445749/bc00453a-5ac2-4e39-9b6d-640bee444c23)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added italian and cowboy accents
- tweak: You can now choose only 1 accent per character

2024-05-15 09:27 UTC, lzk228 commented
resolves #20501

2024-05-17 09:17 UTC, TheShuEd commented
![image](https://github.com/space-wizards/space-station-14/assets/96445749/fd0c033f-8ba5-4f2d-8485-d11d1cb4494e)

2024-05-17 09:29 UTC, TheShuEd commented
wait im fixing some bugs

2024-05-17 10:20 UTC, TheShuEd commented
Frontal Lisp is now worth 2 points

2024-05-17 10:36 UTC, Tornado-Technology commented on Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
> +            var categories = _prototypeManager.EnumeratePrototypes<TraitCategoryPrototype>().OrderBy(t => Loc.GetString(t.Name)).ToList();
Scary Linq

2024-05-17 10:47 UTC, TheShuEd commented on Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
> +            var categories = _prototypeManager.EnumeratePrototypes<TraitCategoryPrototype>().OrderBy(t => Loc.GetString(t.Name)).ToList();
![image](https://github.com/space-wizards/space-station-14/assets/96445749/17c21271-37fa-46f6-8dc7-ad0162d53730)
there was a scary linq here before me.

2024-05-18 16:25 UTC, EmoGarbage404 requested changes
currently there seems to be an issue if a trait doesn't end up in a category. I'd say make it so either:
1. there's a test that errors if a trait isn't in any category
2. trait prototypes have the category themselves, instead of larger lists (This is better for adding new categories and traits in the future i think)
3. Add some kind of 'default' category that always shows up in the UI.

other than that it looks good

2024-05-19 23:01 UTC, Emisse commented
agree with emo, needs to automatically add it to the category. we have a lot of stuff we need to consolidate to not be hardcoded into lists and i dont feel comfortable merging something that adds another one

2024-05-27 09:39 UTC, TheShuEd commented
now the category prototype does not contain the trait prototypes themselves:
```yml
- type: traitCategory
  id: Disabilities
  name: trait-category-disabilities

- type: traitCategory
  id: SpeechTraits
  name: trait-category-speech
  maxTraitPoints: 2
  ```
but the category is written inside the trait itself. If no category is specified, the trait will be displayed in the UI above all categories, without a category header.
```yml
- type: trait
  id: ItalianAccent
  name: trait-italian-name
  description: trait-italian-desc
  category: SpeechTraits
  cost: 1
  components:
    - type: ReplacementAccent
      accent: italian

- type: trait
  id: Liar
  name: trait-liar-name
  description: trait-liar-desc
  category: SpeechTraits
  cost: 1
  components:
    - type: ReplacementAccent
      accent: liar
```

2024-06-03 18:47 UTC, merged