Fix ItemSlotsSystem modifying uninitialized entities
space-wizards/space-station-14 pull request #28221
Opened 2024-05-23 12:48 UTC by DrSmugleaf

## About the PR
## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2024-05-24 04:03 UTC, AJCM-git approved these changes

2024-05-24 04:28 UTC, ElectroJr requested changes
IMO this shouldn't be changed. If this is because things are failing the `PrototypeSaveTest`, they should be and the correct fix is that the prototypes should already have specified the containers. Aside from that, I'm not sure why it would even need changing, it ensures you don't get NREs when using `TryGetSlot()` on a pre mapinit entity.

2024-05-25 09:28 UTC, DrSmugleaf commented
> IMO this shouldn't be changed. If this is because things are failing the `PrototypeSaveTest`, they should be and the correct fix is that the prototypes should already have specified the containers. Aside from that, I'm not sure why it would even need changing, it ensures you don't get NREs when using `TryGetSlot()` on a pre mapinit entity.

Are there cases of actually modifying the item slots pre map init? At that point it sounds like it should just return false if the container is null. Having components that require you to change another component in a specific way is annoying, but if that's a supported use-case and it's not an option to make TryGetSlot return null when the container is null then this should be closed.

2024-05-25 09:39 UTC, DrSmugleaf commented
Figured it out on discord https://discord.com/channels/310555209753690112/770682801607278632/1243858779401883689

2024-05-25 09:39 UTC, closed without merging