make cargo balance ui updating its own component
space-wizards/space-station-14 pull request #28295
Opened 2024-05-26 04:35 UTC by deltanedas

## About the PR
title

## Why / Balance
need this downstream

## Technical details
- added new `BankClientComponent` that gets queried to update ui for any bank related console
- cargo ordering console handles its BankBalanceUpdatedEvent instead of being hardcoded to update ui
- all cargo ordering console entities now have BankClient

## Media
it work
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
`CargoOrderConsoleComponent` now needs `BankClientComponent` for UI to update the same

**Changelog**
no cl no fun

2024-05-26 19:15 UTC, EmoGarbage404 commented
just a thought: would it not be better to have this network the balance on the local entity so that uis could just use the component info instead of having to do it through clunky ui states

2024-05-26 20:17 UTC, deltanedas commented
cargo ordering console specifically uses the station to get the catalog so its not entirely useless. wouldnt hurt to add though

2024-05-26 21:22 UTC, ShadowCommander requested changes

2024-06-11 16:21 UTC, deltanedas commented
merg

2024-07-13 06:10 UTC, metalgearsloth commented
okay for now ig.

2024-07-13 06:11 UTC, merged