Update rules
space-wizards/space-station-14 pull request #28452
Opened 2024-05-31 20:36 UTC by Chief-Engineer

## About the PR

~~Redirects rules to the wiki instead of having them in-game. Plan is to self merge when the rule rewrite goes into effect (within the next 1-2 days I think)~~

~~Feel free to suggest any wording or formatting changes. Ideally the link would be an actual link but afaik that's not supported.~~

## Why / Balance

No one likes that there are two versions of the rules in two different places, it was like this because it became impossible to mirror the rules that are on the wiki into the game. Instead of telling players to read the wiki rules and then giving them a list of rules that are not the wiki rules, this just tells them to read the wiki rules and attempts to convince them to while also making it clear that these are WizDen servers and that there are roleplay rules.

## Technical details

Many characters were meticulously replaced with much fewer characters. Each new character was typed by hand using artisanal typing techniques on a traditional keyboard layout. The keystrokes traveled down metallic highways surrounded by insulation designed to both keep them on their path and free of corruption. Arriving at their destination, they were bundled together and escorted by military grade encryption across the world to where they are now. Their digital form ensures that, unlike analog  keystrokes, they are as pure as when they were created.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-05-31 20:39 UTC, EmoGarbage404 commented
so glad to see the rules are gone. I will have fun self-antaging once this is merged. Thank you!

2024-05-31 20:44 UTC, lzk228 commented
some players can have bad pc and even couldnt open game and browser in the same time to read the rules, so its better to keep it in, maybe in another way

2024-05-31 20:45 UTC, mirrorcult commented
yeah i dont know that im fully happy with this

2024-05-31 20:46 UTC, mirrorcult commented
not having it be available ingame is a huge amount of friction

2024-05-31 21:07 UTC, moonheart08 commented
This is kind of a bad idea, especially friction wise. The ingame rules are **necessary** for onboarding, and any extra friction in the onboarding process beyond the existing massive friction the rules impose will reduce player join rates even further.

A proper approach would be to instead autogenerate the wiki rules from the ingame rules, likely by just writing a tool to parse guidebook doc markup (in-engine?) and convert that to styled HTML for rehosting on the wiki, website, or wherever else.

2024-05-31 21:11 UTC, PJB3005 requested changes
Absolutely not. These should be in-game. If the problem is that the wiki rules go out of sync, remove the wiki rules.

2024-05-31 21:13 UTC, moonheart08 commented
So here's what I'd do:
- Port the rules screen to use the guidebook document system, if it doesn't already.
- Implement tables into that, likely just needs to support square, plain tables with a header to start with.
- Use the integration test frame tooling to write a guidebook-to-html conversion system, by constructing a document and then walking its control tree to produce HTML elements with styling information attached. This is the Hard Part and I can provide guidance for all of this.

Is this a lot of work? yeah. yeah it is.

but I don't think removing the ingame rules is an option.

2024-05-31 21:34 UTC, PJB3005 commented
Then modify the rules some more so they fit.

2024-05-31 22:00 UTC, mirrorcult commented
ideal solution is to just have table support and keep it ingame, @EmoGarbage404 is working on it

2024-05-31 22:12 UTC, moonheart08 commented
> > Then modify the rules some more so they fit.
> 
> I spent weeks writing this draft after people complained endlessly about the last version, which I think also took the person who wrote it weeks to write, for a year without being willing to write a proposal themselves. If someone doesn't like the current or proposed rules they need to write and get a proposal passed themselves

This doesn't justify the nuclear option.

2024-05-31 22:13 UTC, EmoGarbage404 commented
can everyone get off each other's throats i am literally halfway through adding table support to the guidebook

2024-06-01 13:39 UTC, engineer-pearl commented
If there's disagreement here about showing the laws in the book, what about a wording like "The in-game rules page is undergoing some major changes. You can still view the current rules at [color=#a4885c]https://wiki.ss14.io/wiki/Server_Rules[/color]"

This wording still allows ChiefEngineer to handle a rewrite quickly, but indicates that the situation is not permanent (which may make it feel less like "the nuclear option").

2024-06-01 13:41 UTC, moonheart08 commented
> If there's disagreement here about showing the laws in the book, what about a wording like "The in-game rules page is undergoing some major changes. You can still view the current rules at [color=#a4885c][https://wiki.ss14.io/wiki/Server_Rules[/color]](https://wiki.ss14.io/wiki/Server_Rules%5B/color%5D)"
> 
> This wording still allows ChiefEngineer to handle a rewrite quickly, but indicates that the situation is not permanent (which may make it feel less like "the nuclear option").

This game is about to have a major audience in some days, now's not the time for 'temporary' (fixed three months later). It can be out of sync for a bit.

2024-06-01 14:17 UTC, Tayrtahn commented
While not needed for this, it would also probably be good to get an actual hyperlink rich text tag for possible future use.

2024-06-02 04:39 UTC, mirrorcult commented
tables PR is merged, this can be updated

2024-06-02 19:47 UTC, moonheart08 commented
Not sure anyone's said this yet so here's a big "Thank you" for keeping the rules in-game.

2024-06-05 22:45 UTC, EmoGarbage404 commented on Resources/Prototypes/Guidebook/ss14.yml
> +  - Rules
i'd say remove this since we already have a tab that lets you read the ingame rules

2024-06-05 22:59 UTC, EmoGarbage404 commented on Resources/ServerInfo/Guidebook/ServerRules/WizDenRules.xml
> +</Document>
this isn't needed since we can just choose which one to show based on the server config

2024-06-05 23:59 UTC, AJCM-git approved these changes

2024-06-05 23:59 UTC, merged