Welding masks restrict vision
space-wizards/space-station-14 pull request #28519
Opened 2024-06-02 13:56 UTC by MACMAN2003

## About the PR

Made welding masks (not the welding gas masks) restrict your vision.
## Why / Balance

it's realistic and it gives a use to the flipped up welding mask sprites. As for game balance, it's pretty much a nerf, it blinds you completely when it's down and does not protect you when it's up.
## Technical details

I don't really understand the code enough to summarize it but I'll try my best.
I moved the flash immunity component from server to shared, so that the welding mask can actually toggle it
The welding mask component stores an invalid entity UID until it is worn then it stores the UID of the wearer until unequipped. Whenever the welding mask component receives a "folded event" it effectively toggles all the fancy things that come with a welding mask.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/20659419/f5dd4a05-d8fb-4f5f-820a-d686b69bd7a0

## Breaking changes

**Changelog**

🆑 
- tweak: Welding masks can be folded up and will blind wearers when folded down.

2024-06-02 14:04 UTC, ninruB commented
Aren't these basically just blindfolds now? Blindfolds too fully blind you while giving you flashres.
SS13 restricted weldermask vision to like a 6x6 square around the character which is much more reasonable than complete blindness.

2024-06-02 14:05 UTC, EmoGarbage404 commented
Yeah this should be it's own vision effect separate from blindness. It shouldnt have grayscale either.

2024-06-02 14:06 UTC, ninruB commented
>It shouldnt have grayscale either.

Pretty sure SS13 greyscaled and/or dithered the screen when the weldermask is on, might be misremembering though.

2024-06-02 14:21 UTC, Hmeister-real commented
give it a cone of vision, like 4 tiles wide and as long as normal vision, but make everything outside of that visible, but not descernable if you know what i mean, like in some ss13 servers wearing a helmet blocks your vision from behind but only viewing objects vision.

2024-06-02 14:56 UTC, deltanedas commented
it should block blue light or something because thats near UV which its meant to block
also cone would be good

2024-06-02 16:17 UTC, Ghagliiarghii commented
way too restrictive of vision currently

2024-06-02 16:46 UTC, Brandon-Huu commented
This is an amazing change. Welding mask are supposed to be for welding.
Currently they are only used against revs and malf borgs.
Keep up the great work!

2024-06-03 03:26 UTC, Ghagliiarghii commented
> it should block blue light or something because thats near UV which its meant to block also cone would be good

A lowpass filter on the colors (sch that greens look faded and blues look greyscale but reds look normal) and increasing the view size to be a bit larger would improve this. 
I would like personally a 3-7 tile (would need to test to see what feels right) diameter circle of vision and an additional cone of vision in front of you similar to the seclight lit area (a bit longer than the normal blue flashlight found in emergency toolboxes and elsewhere)

2024-06-03 03:27 UTC, Ghagliiarghii commented
I would also greatly appreciate the quality of life of being able to flip it up on your head, if nothing else just to be able to eat without juggling this mask item.

2024-06-03 04:33 UTC, Partmedia commented
I like this change because it provides an incentive for the player to not be wearing the welding mask all the time. I think it would be better if you used a different shader (or slightly increased the radius) and made the tint a color closer to what you would expect from a welding mask. Unfortunately this is also affected by the feature freeze.

2024-06-05 16:06 UTC, MACMAN2003 commented
![image](https://github.com/space-wizards/space-station-14/assets/20659419/e04c8f29-24b8-403e-a56c-07ec95c93001)
best i can do to increase vision range is the breaking bad mexico filter

2024-06-05 17:11 UTC, ninruB commented
RESULT NOT SATISFACTORY. CAUSE: `<TARGET NOT MET>`
`<MACBOY2003>`,
YOU WILL BE DEPORTED TO THE `<SHADER MINES>` COLONY FOR `<WELDERMASK CODE>` RESTRUCTURING UNTIL RESULTS IMPROVE AND MATCH `<TARGET RESULTS>`.

2024-06-13 22:33 UTC, MACMAN2003 commented
now that the freeze is over..... could this be reopened so i could get more feedback

2024-06-14 03:59 UTC, MACMAN2003 commented
![image](https://github.com/space-wizards/space-station-14/assets/20659419/883a7954-55cb-4896-8e03-9a42821e5b31)
the shader mines are a confusing and horrible place

2024-06-14 06:52 UTC, MACMAN2003 commented
all checks have passed! it works perfectly! (as long as no one presses the tilde key)

2024-06-19 15:02 UTC, metalgearsloth requested changes
All new code must use file-scoped namespaces.

2024-06-19 15:02 UTC, metalgearsloth commented on Content.Client/Eye/Blinding/WeldingVisionSystem.cs
> +        }
Why is one on Init and one on Shutdown? You're using 2 different lifestages for this instead of Startup or Remove.

2024-06-19 15:02 UTC, metalgearsloth commented on Content.Shared/Clothing/Components/MaskComponent.cs
> +
Code must be documented.

2024-06-19 15:02 UTC, metalgearsloth commented on Content.Shared/Clothing/ClothingEvents.cs
> +
Same here on documenting your code.

2024-06-19 15:02 UTC, metalgearsloth commented on Content.Shared/Clothing/Components/WeldingMaskComponent.cs
> +}
This is very hardcoded and needs to be split out or use existing code, not just making an entire component for 1 specific entity.

Also none of it is documented.

2024-06-19 15:02 UTC, metalgearsloth commented on Content.Shared/Clothing/EntitySystems/WeldingMaskSystem.cs
> +}
There's no reason this can't just extend itemtoggle.

2024-06-19 15:02 UTC, metalgearsloth commented on Content.Shared/Eye/Blinding/Components/BlindfoldComponent.cs
>  }
As above this is not documented.

2024-06-19 15:02 UTC, metalgearsloth commented on Content.Shared/Eye/Blinding/Components/WeldingVisionComponent.cs
> +}
As above.

2024-06-19 15:02 UTC, metalgearsloth commented on Content.Shared/Eye/Blinding/Systems/BlindfoldSystem.cs
> +    }
As above.

2024-06-19 15:02 UTC, metalgearsloth commented on Content.Shared/Flash/Components/FlashImmunityComponent.cs
>  public sealed partial class FlashImmunityComponent : Component
Do not remove access attributes just to bypass access.

2024-07-02 05:21 UTC, ps3moira commented
Finally! I always thought it was kinda cheap and easy to be immune to flashes and welding damage, so this is huge

2024-07-22 17:16 UTC, Brandon-Huu commented
No update in a month. It is so joever

2024-07-27 18:28 UTC, MACMAN2003 commented
drafting this cause fixing it will take _a very long time_

2024-08-14 11:58 UTC, closed without merging

2024-08-14 11:58 UTC, metalgearsloth commented
Re-open if you come back to it.