"I'm Weh-cellent" Cap
space-wizards/space-station-14 pull request #28573
Opened 2024-06-04 00:42 UTC by UBlueberry

## About the PR

Added one new hat, the "Wehcellent cap".

## Media

![image](https://github.com/space-wizards/space-station-14/assets/161545003/a1153775-f588-4fac-a09f-d50df6ed0a44)
![image](https://github.com/space-wizards/space-station-14/assets/161545003/0ae0f157-5539-4704-b8ae-fa0a6f30f91c)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2024-06-04 00:43 UTC, metalgearsloth commented
Closed due to feature freeze May 10th-June 14th. Comment to have it reopen after this.

2024-06-04 00:49 UTC, UBlueberry commented
oh i forgot my bad

2024-10-29 15:16 UTC, UBlueberry commented
wouldn't it be cool if

2025-03-16 00:06 UTC, UBlueberry commented
_UBlueberry wehs!_

2025-03-16 00:07 UTC, ArtisticRoomba commented
if you want i can totally abuse my triage permissions to re-open this :godo:

2025-03-16 00:08 UTC, FairlySadPanda commented
weh-n you code it

2025-03-16 00:08 UTC, ArtisticRoomba commented on Resources/Textures/Clothing/Head/Hats/wehcellentcap.rsi/meta.json
new json file needs to be 4-spaced, if reopening

2025-03-16 00:27 UTC, Djungelskog2 commented
have its only method of obtaining be eating 10 weh plushies in 5 mins

2025-03-16 15:44 UTC, UBlueberry commented on Resources/Textures/Clothing/Head/Hats/wehcellentcap.rsi/meta.json
idk what that means but i would like it reopened

2025-03-16 17:17 UTC, ArtisticRoomba commented
I've been stopped...

2025-03-16 17:18 UTC, ArtisticRoomba commented on Resources/Textures/Clothing/Head/Hats/wehcellentcap.rsi/meta.json
Right now your indentation is 2-spaced, you'll want to increase this spacing to 4 spaced.

2025-03-16 17:29 UTC, Boaz1111 commented
reopened

2025-03-19 21:09 UTC, UBlueberry commented
funny story: i need to set up my dev environment again cause i messed everything up
so this might take a while.

2025-03-19 21:49 UTC, UBlueberry commented on Resources/Textures/Clothing/Head/Hats/wehcellentcap.rsi/meta.json
hopefully i fixed it

2025-03-19 22:07 UTC, ArtisticRoomba requested changes

2025-03-19 22:07 UTC, ArtisticRoomba commented on Resources/Textures/Clothing/Head/Hats/wehcellentcap.rsi/meta.json
> +    "copyright": "Created by UBlueberry for Space Station 14",
```suggestion
    "copyright": "Created by UBlueberry (GitHub) for Space Station 14",
```

2025-03-19 22:12 UTC, UBlueberry commented
tested it in vis studio - still works
apologies for all the corrections - it's been a long while and i don't know all the new conventions n stuff

2025-03-19 22:42 UTC, ArtisticRoomba approved these changes
LG2M

2025-03-29 11:59 UTC, SlamBamActionman approved these changes
This is gonna need a PR to add the hat into the game somehow (Clothesmate? Maints loot?) but as-is? A wehcellent cap!

2025-03-29 11:59 UTC, merged