Make Projectiles not Hit a Variety of Station Objects Unless Clicked on
space-wizards/space-station-14 pull request #28571
Opened 2024-06-04 00:16 UTC by Cojoke-dot

## About the PR

Makes a variety of objects around the station not be able to be hit by projectiles unless targeted by the player. The objects include:
- Computers
- Circuit imprinter
- Fax
- Reagent grinder
- Portable Generators
- Electrolyzer
- Centrifuge
- Disposal chutes
- Booze, Soda, and Chem Dispensers
- Microwave
- Gas Condenser
- Vaccine Machines
- Filing cabinets
- Large Instruments

## Why / Balance

A lot of objects around the map feel like they should be able to be shot over but also should have the option of being destroyed by guns(mostly the stuff that can go on tables). I put some of the shorter machines and all of the instruments in here too.
## Technical details

Adds the RequireProjectileTarget component to the objects listed

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: A variety of objects around the station now need to be clicked on in order for bullets to hit them.

2024-06-04 00:22 UTC, metalgearsloth commented on Content.Shared/Damage/Components/RequireProjectileTargetComponent.cs
> +}
Didn't we just get a PR with this?

2024-06-04 01:53 UTC, Cojoke-dot commented
yeah, just needed the merge, thats all gone now

2024-06-04 02:29 UTC, Cojoke-dot commented
Adding the hydroponics tray and wood fences

2024-06-04 13:31 UTC, Lamrr commented on Resources/Prototypes/Entities/Structures/Storage/filing_cabinets.yml
> +  - type: RequireProjectileTarget
Filing cabinets, or at least the tall cabinets, should probably be able to be used as cover.

2024-06-04 13:43 UTC, AJCM-git requested changes
Add em to the grinders and rechargers as well (a good way to get a sense of what may need this is searching for `drawdepth: SmallObjects ` that can be anchored and using some logic of "can you hide behind this?"). Also remember to double check the children of your prototypes to make sure nothing weird is going on.

A better way to do this btw, would be adding the component to a new SmallConstructibleMachine prototype and make those that have ConstructibleMachine inherit that where it makes sense, same logic applies to the other base prototypes (unless all of their children *are* ""small"")

2024-06-05 00:09 UTC, Cojoke-dot commented
> Add em to the grinders...
Reagent grinders?

2024-06-05 01:03 UTC, AJCM-git commented
> > Add em to the grinders...
> 
> Reagent grinders?

yeah

2024-06-05 02:09 UTC, AJCM-git commented on Resources/Prototypes/Entities/Structures/Walls/fence_wood.yml
why change to machine layer?

2024-06-05 20:24 UTC, AJCM-git requested changes
you havent answered my last comment

2024-06-05 20:33 UTC, Cojoke-dot commented
> you havent answered my last comment

oh... uh... MachineLayer has the layers that were on the fence before + BulletImpassable and Opaque. Is there a different way I should do this?

2024-06-05 20:38 UTC, AJCM-git commented
> > you havent answered my last comment
> 
> oh... uh... MachineLayer has the layers that were on the fence before + BulletImpassable and Opaque. Is there a different way I should do this?

MachineLayer is given with the assumption that something is a machine, that way if someone wants to change how the layer works they dont have to double check that everything it affects is indeed a machine, so either just add those or add a new layer

2024-06-05 20:40 UTC, Cojoke-dot commented
ok, got it, I'll change that

2024-06-05 20:47 UTC, AJCM-git approved these changes

2024-06-05 20:47 UTC, merged