Convert rules to use guidebook parsing
space-wizards/space-station-14 pull request #28647
Opened 2024-06-05 22:55 UTC by EmoGarbage404

## About the PR

`.txt` stinky `.xml` glorious

changes the rules windows to use guidebook parsing.
changes the cvar to now use a guidebook prototype.
its very cool works great

needs #28452

## Media

![image](https://github.com/space-wizards/space-station-14/assets/98561806/fdc3afa6-e9d2-4e04-a53a-f658f61c67f4)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

2024-06-05 23:17 UTC, AJCM-git requested changes
Holy moly jank like this is why UiControllers were made (tho i dont think this predates them so wtf?)

2024-06-05 23:17 UTC, AJCM-git commented on Content.Client/Info/InfoSystem.cs
> +    public ProtoId<GuideEntryPrototype> Rules = "SS!4";
a

2024-06-05 23:17 UTC, AJCM-git commented on Content.Client/Info/RulesControl.xaml
> +﻿<BoxContainer xmlns="https://spacestation14.io" Orientation="Vertical" HorizontalExpand="True" VerticalExpand="True" Access="Public">
not your fault but public access with no name

2024-06-05 23:17 UTC, AJCM-git commented on Content.Client/Info/RulesManager.cs
> +        return _prototypeManager.Index(_sysMan.GetEntitySystem<InfoSystem>().Rules);
Yeah, i see the reason of the TODO now (its prob something else but this SUCKS)

2024-06-05 23:17 UTC, AJCM-git commented on Content.Client/Info/InfoSystem.cs
>      }
can you subscribe to this in the UIController instead?

2024-06-05 23:51 UTC, EmoGarbage404 commented
now configured to use the prototypes from the rules PR

2024-06-06 07:10 UTC, AJCM-git approved these changes

2024-06-06 07:11 UTC, merged