add notification for dependent wearables being dropped
space-wizards/space-station-14 pull request #28722
Opened 2024-06-08 02:13 UTC by justinbrick

## About the PR

added a notification for dependent wearables being dropped when the parent clothing is removed (i.e. PDA dropped when jumpsuit removed)

## Why / Balance

in relation to issue #28604, this gives a notification when the PDA is dropped. this also doubles purpose in giving a notification if any dependent wearables are dropped as well, 

## Technical details

this adds a single locale string & an additional check inside the unequip system of the inventory.

## Media

https://github.com/space-wizards/space-station-14/assets/49499807/242afe19-fdde-4e31-bc07-db4241939e66

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl:
- tweak: added a popup to notify when extra items are removed from your inventory while unequipping something

2024-06-08 02:26 UTC, justinbrick commented
One thing to note is that the popup will likely still happen multiple times if there is multiple items dropped recursively.  a996847 tries to mitigate that, but doesn't guarantee it. i'm not sure if that can be fixed without changing the method signature (at the top of my head)

2024-06-08 02:58 UTC, Tayrtahn requested changes

2024-06-08 02:58 UTC, Tayrtahn commented on Content.Shared/Inventory/InventorySystem.Equip.cs
> +            _popup.PopupPredicted(Loc.GetString("inventory-component-dropped-from-unequip"), target, target);
```suggestion
            _popup.PopupClient(Loc.GetString("inventory-component-dropped-from-unequip"), target, target);
```
PopupPredicted will show to everyone, PopupClient will show only to the specific player.

2024-06-08 08:08 UTC, lzk228 commented
attached video doesnt load for me

2024-06-08 16:02 UTC, justinbrick commented
> attached video doesnt load for me

I had a feeling that might be the case for some people. It's also not playing on discord for me, but it does play here. 
Give this one a shot, see if it works. If not, I might have to re-install OBS or try looking at my settings.

https://github.com/space-wizards/space-station-14/assets/49499807/0dda4b4e-0a8c-49cd-8d8d-35569cb1d064

2024-06-08 16:29 UTC, lzk228 commented
is it possible to actually display the dropped item(s)?

2024-06-08 17:24 UTC, deltanedas commented
(the first video is hevc and some browsers cant play it for some reason)

2024-06-08 18:29 UTC, justinbrick commented
> is it possible to actually display the dropped item(s)?

It is possible, but I don't think it's a very good idea, since you can drop multiple items at once - might cause a massive wall of text.

2024-06-08 19:33 UTC, lzk228 commented
> > is it possible to actually display the dropped item(s)?
> 
> It is possible, but I don't think it's a very good idea, since you can drop multiple items at once - might cause a massive wall of text.

then would be good to just add plural version `You dropped items!`

2024-06-08 20:33 UTC, Tayrtahn commented
> then would be good to just add plural version `You dropped items!`

Implementation note: to do this properly, just pass the number of items as an argument when using Loc.GetString and handle picking the right text on the Fluent side.

2024-06-10 00:54 UTC, Tayrtahn commented on Content.Shared/Inventory/InventorySystem.Equip.cs
> +            _popup.PopupClient(Loc.GetString("inventory-component-dropped-from-unequip", ("items", itemsDropped)), target, target);
I recommend using `itemsDropped - 1` to make the localization more straightforward.

2024-10-31 10:53 UTC, SlamBamActionman commented
Closed due to no response from PR author; has been continued in #33078.

2024-10-31 10:53 UTC, closed without merging