Buffs the particle decelerator
space-wizards/space-station-14 pull request #28747
Opened 2024-06-08 17:43 UTC by Flareguy

## About the PR
Buffs the particle decelerator to be 10x stronger (-10 energy to -100 energy.)
A single particle decelerator can now roughly shrink the singularity by 1 stage, or almost 1 stage.

## Why / Balance
-10 singularity energy is ridiculously terrible - you'd need a team of 10+ people to even put a dent in a low level singularity. This should make particle decelerators actually usable for situations outside of admin-spawned ERTs.

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
- tweak: Particle decelerators are now 10 times stronger.

2024-06-08 19:45 UTC, Brandon-Huu commented
>  A single particle decelerator can now roughly shrink the singularity by 1 stage, or almost 1 stage.
That's awful.

one person shouldn't have that much power

2024-06-08 21:02 UTC, EmoGarbage404 commented
I know it shouldnt be impossible, but decels are 3 a piece in cargo and have 20 shots.
This current iteration feels extremely strong, especially for early stage singulos, where a single person with a decel can disable a singulo from outside of engineering in just a few seconds

2024-06-08 21:06 UTC, Flareguy commented
Nerfed it down to -65 SinguloFood. This is probably a bit of a lowball and, from what I saw, was able to get a level 6 singulo down to either level 3 or level 4 with 3 people's worth of firerate & ammo simulated.

I don't remember how it fared with 1 player, but it was not very well.

2024-06-15 11:34 UTC, ShadowCommander approved these changes

2024-07-06 18:56 UTC, osjarw commented
How does this work with tesla? 
IIRC, tesla handles singulofood differently, that is, it varies between -100 and 100, hitting 100 sets it back to 0 while spawning a small energy ball, and if decelerators get it to -100, the tesla dies.
So with singulofood -65, you can kill the tesla in anywhere between 2-4 shots if the tesla isn't actively consuming stuff.

2024-07-08 12:25 UTC, ShadowCommander commented
One suggestion that was brought up is to make the particle decelerator percentage based so that it can still kill level 5 and level 6 singularities without seemingly instakilling level 3 and below singularities.

2024-07-09 12:28 UTC, Ilya246 commented
why not just have it deal flat *and* percentage damage together so it works well against high-health singularities but can still kill low-health ones fast

2024-07-10 19:13 UTC, wafehling commented
We need this change so badly. Half, possibly more of rounds (In the last couple weeks, in my personal accounting) now end from singuloose/tesloose, and it's rare that anyone tries to counter-play them. I've seen people try several times, and I've never seen the particle decels succeed once against them, even with several dedicated users trying.

2024-08-15 08:22 UTC, slarticodefast requested changes

2024-08-15 08:22 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +      fireCost: 500
remove fireCost to stop the yaml linter complaining. This is a part of ProjectileBatteryAmmoProvider and not changed anyways.
```suggestion
```

2024-08-15 08:22 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +      fireCost: 500
```suggestion
```

2024-08-15 08:22 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +    - type: Gun
Please fix the indentation for the components. Do the same with the WeaponParticleDecelerator, it is wrong there, too.

2024-09-09 10:22 UTC, TheShuEd commented
do you plan to continue your work?

2024-09-09 10:43 UTC, TheShuEd commented
summarizing internal discussions: damage should be a percentage, not flat. A different implementation is required. Given that the PR is outdated, reviews are not fixed, and checks are not passed, we are closing the PR

2024-09-09 10:43 UTC, closed without merging