Plays rustle sound when inserting or opening a backpack.
space-wizards/space-station-14 pull request #2890
Opened 2021-01-02 07:54 UTC by SweptWasTaken

Doesn't proc when you can't insert something.

2021-01-02 10:52 UTC, Zumorica requested changes

2021-01-02 10:52 UTC, Zumorica commented on Content.Server/GameObjects/Components/Items/Storage/ServerStorageComponent.cs
> +                var file = _random.Pick(soundCollection.PickFiles);
Instead of doing this manually, use `AudioHelpers.GetRandomFileFromSoundCollection()`

2021-01-02 10:52 UTC, Zumorica commented on Content.Server/GameObjects/Components/Items/Storage/ServerStorageComponent.cs
> +        public string _soundCollectionName = "storageRustle";
Why isn't this serialized? And it should probably default to no sound collection, in my opinion

2021-01-02 22:41 UTC, SweptWasTaken commented
@Zumorica Is this better?

2021-01-03 01:02 UTC, SweptWasTaken commented
Working now, applied the suggestions you gave in vc.

2021-01-03 01:06 UTC, bobbahbrown commented on Content.Server/GameObjects/Components/Items/Storage/ServerStorageComponent.cs
> +        protected void PlaySoundCollection(string? name)
```suggestion

        protected void PlaySoundCollection(string? name)
```

2021-01-05 05:34 UTC, metalgearsloth approved these changes

2021-01-05 05:34 UTC, merged

2021-01-05 18:36 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Interactable/ToolComponent.cs
> +using System;
why tho