Make SSD character fall asleep
space-wizards/space-station-14 pull request #28902
Opened 2024-06-12 19:48 UTC by lzk228

## About the PR

If entity is SSD, it got asleep with force (cannot be awaked)
When entity no longer SSD, it can be awaked
Fixes #21906 

## Why / Balance

Cool

## Technical details

no

## Media

https://github.com/space-wizards/space-station-14/assets/124214523/2568d015-849c-456e-858a-547c0bb6ef3a

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: SSD character now will fall asleep until they are no longer SSD.

2024-06-12 20:12 UTC, lzk228 commented
test are failing because of changes, im powerless here

2024-06-13 01:29 UTC, Tayrtahn commented
> test are failing because of changes, im powerless here

Add a check to make sure the entity isn't terminating before adding the component.

2024-06-13 01:50 UTC, ps3moira commented
Only downside is if the server sucks and you're disconnected your character drops whatever they're holding when they go to sleep, but this is awesome!

2024-06-13 02:27 UTC, VigersRay commented
Omg, he is died

2024-06-13 17:33 UTC, Tayrtahn commented on Content.Shared/SSDIndicator/SSDIndicatorSystem.cs
> +        EnsureComp<ForcedSleepingComponent>(uid);
```suggestion
        if (!TerminatingOrDeleted(uid))
            EnsureComp<ForcedSleepingComponent>(uid);
```

2024-06-13 18:33 UTC, Partmedia commented
Thanks for the PR. Per the discussion on the original "Show SSD Indicator" CVar (I can link those if you can't find them), this behavior should probably also be controlled by the same CVar, i.e. not fall asleep if the CVar is disabled.

2024-06-13 19:49 UTC, lzk228 commented
> Thanks for the PR. Per the discussion on the original "Show SSD Indicator" CVar (I can link those if you can't find them), this behavior should probably also be controlled by the same CVar, i.e. not fall asleep if the CVar is disabled.

Tried to add check for the cvar but on ghost i got
```
[ERRO] con: localhost@JoeGenero: ExecuteError - ghost :
Robust.Shared.Configuration.InvalidConfigurationException: Trying to get unregistered variable 'ic.show_ssd_indicator'
```
for server and
```
[INFO] CON: > ghost
[INFO] CON: There was an error while executing the command: Robust.Shared.Configuration.InvalidConfigurationException: Trying to get unregistered variable 'ic.show_ssd_indicator'
```
for client

2024-06-15 11:17 UTC, Anzarot121 commented
revenant buff real

2024-07-27 16:25 UTC, ps3moira commented
is this still being worked on?

2024-07-27 16:51 UTC, lzk228 commented
> is this still being worked on?

its working, i just wait for the issue to be resolved, because i have no clue how to resolve it and as Tayrtahn said its not my problem, i just add the code that cause the issue to happen

2024-08-02 05:55 UTC, metalgearsloth requested changes
Needs cvar for servers that may want it + the fact it has ingame implications due to revenant.

2024-08-18 09:48 UTC, SlamBamActionman commented
Hello! The PR was put up to a maintainer vote which concluded with the following result: Merge, but with changes.

Maintainers think it's a neat idea, but that immediately falling asleep would be too punishing. This is due to the existence of revenants, who can kill a character who is sleeping, and also an antag DCing and finding themselves asleep even upon an immediate reconnect. 

The PR has maintainer approval if there is a timer before the sleep happens. This delay should be controlled by a cvar so that it's easily adjustable on a server-to-server basis.

An exact time wasn't settled upon but there were suggestions ranging from 10 to 20 minutes.

2024-08-18 10:03 UTC, Cojoke-dot commented
> The PR has maintainer approval if there is a timer before the sleep happens. This delay should be controlled by a cvar so that it's easily adjustable on a server-to-server basis.
> 
> An exact time wasn't settled upon but there were suggestions ranging from 10 to 20 minutes.

OOooOoo, It would be nice to have the ability to identify if people have been SSD for a while and they should be moved to cryo. One of my biggest fears of putting a yellow text SSD person in cryo is that they just DC'ed and had been gone for only a few minutes. This also means not dropping and breaking everything in your hand if you happen to lose connection while walking with a jug of chems or something.

2024-08-18 10:07 UTC, lzk228 commented
> An exact time wasn't settled upon but there were suggestions ranging from 10 to 20 minutes.

wow, it looks pretty long, i'll do 10 for now, someone else can change it later

2024-08-19 21:50 UTC, lzk228 commented
i've looked into it a little, and it's too complicated for me right now
closing, maybe will come back later
if anyone wants to take it, you are welcome

2024-08-19 21:50 UTC, closed without merging