Adds jetpacks to the game
space-wizards/space-station-14 pull request #2893
Opened 2021-01-02 19:58 UTC by lzimann

The PR also includes a way of relaying movement input to equipped items, this is done by an Action on the ItemComponent `OnInventoryRelayMove`, the function will be the same as implementing the `IRelayMoveInput` interface, thanks to @RemieRichards  on the idea and implementation for the input relay.

Opening the PR as a draft because the space movement part of the jetpack is still not working very well, hopefully with the PR a proper solution can be figured out.

2021-01-04 08:07 UTC, metalgearsloth commented
What's the issue with space movement?

I see some other stuff that could be optimised a lot but I'll leave it for later.

2021-01-04 08:32 UTC, SweptWasTaken approved these changes

2021-01-04 08:33 UTC, SweptWasTaken commented
Unfortunately I cannot suggest these. However I have gone ahead and converted all the meta.jsons in this PR to standard and properly licensed them. I've also fixed a couple of bugs with them such as inhands being the wrong color and for some reason mining inhands in the improvised jetpacks rsi. Whatever, here's the ZIP.

[Jetpacks.zip](https://github.com/space-wizards/space-station-14/files/5763704/Jetpacks.zip)

2021-01-08 22:55 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Jetpack/JetpackComponent.cs
> +                _gasTank?.RemoveAirVolume(VolumeUsage);
this should try to output the gasmix into the tile below

2021-01-29 10:36 UTC, PaulRitter requested changes
i'd like to see nullability being used in everything you add in this pr

2021-02-13 14:36 UTC, Peptide90 commented
For reference #878 is the corresponding issue so it can be closed off when this PR is done.

2021-02-20 19:12 UTC, lzimann commented
The movement part is still not great, putting this on hold until physics refactor.

2021-02-20 19:12 UTC, closed without merging