Makes EventRole Ids properly set ID names.
space-wizards/space-station-14 pull request #28958
Opened 2024-06-13 22:54 UTC by Vermidia

## About the PR

Event roles like ERT or shuttle roles now have their ids set their name on the card.

## Why / Balance

So you know who the card belonged to, and so it shows up when opening the PDA.

## Technical details

New component: ID bind that activates on loadout equip/when added to an entity
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/space-wizards/space-station-14/assets/32827189/822e8441-4d92-41ab-b544-261ea5bde279

## Breaking changes

No?
**Changelog**

no cl just flavor

2024-06-13 23:13 UTC, Dutch-VanDerLinde commented
why does  the moth have hte identity Felana Leander when the id card is Specialist Chameleon

2024-06-13 23:17 UTC, Vermidia commented
Weirdness because randomizeName isn't set to false on ERT/CBURN meaning they have their name randomized twice, which I should probably fix here.

2024-06-15 04:23 UTC, Vermidia commented
Moved the system to server, and changed it to activate on mind added (Couldn't find a way to make sure it only activates after it applies the name and everything except that)

2024-08-11 02:34 UTC, metalgearsloth submitted a review, later dismissed

2024-08-11 02:34 UTC, metalgearsloth commented on Content.Server/Access/Systems/IdBindSystem.cs
> +        EntityManager.RemoveComponent(ent, ent.Comp);
You should not be touching components in the eventbus as this will break.

2024-08-11 02:34 UTC, metalgearsloth commented on Content.Server/Access/Components/IdBindComponent.cs
> +
```suggestion
namespace Content.Server.Access.Components;

/// <summary>
/// Makes it so when starting gear loads up, the name on a PDA/Id (if present) is changed to the character's name.
/// </summary>
[RegisterComponent]
public sealed partial class IdBindComponent : Component
{
    /// <summary>
    /// If true, also tries to get the PDA and set the owner to the entity
    /// </summary>
    [DataField]
    public bool BindPdaOwner = true;
}
```

2024-11-04 16:16 UTC, slarticodefast requested changes
Sorry for the long wait with the review. We are really backlogged at the moment.

2024-11-04 16:16 UTC, slarticodefast commented on Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
> -  randomizeName: false
wouldn't this randomize the name twice?

2024-11-04 16:16 UTC, slarticodefast commented on Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
> +  randomizeName: false
this should already be inherited from EventHumanoidMindShielded

2025-04-21 18:25 UTC, merged

2025-04-21 18:35 UTC, slarticodefast commented
Oh, ancient PR finally merged. Now that I look at it again, shouldn't this change it on map init rather than when a mind is added?

2025-04-22 19:26 UTC, Vermidia commented
This is very old but the reason it does not is because it would result in the PDA/ID getting the first name generated instead of the final name.