Fix the ability to shoot out of crates
space-wizards/space-station-14 pull request #28961
Opened 2024-06-14 00:28 UTC by Cojoke-dot

## About the PR

bug
## Why / Balance

You could shoot out of crates while inside of them, making you unable to get hit by projectiles unless the crate was clicked on
## Technical details

adds a check to make sure that the shooter is not inside of said inventory whenever canceling collisions
## Media

https://github.com/space-wizards/space-station-14/assets/83733158/60448ffb-21ac-4f20-940a-6a17d0848a06

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: You can no longer shoot out of crates with guns

2024-06-14 00:32 UTC, AJCM-git requested changes

2024-06-14 00:32 UTC, AJCM-git commented on Content.Shared/Damage/Systems/RequireProjectileTargetSystem.cs
> +            if (CompOrNull<InsideEntityStorageComponent>(shooter)?.Storage != ent.Owner)
use ContainerSystem.IsEntityOrParentInContainer

2024-06-14 01:50 UTC, AJCM-git requested changes
Please test things before requesting reviews

2024-06-14 03:31 UTC, AJCM-git commented
> > Please test things before requesting reviews
> 
> Sorry about that
> 
> uh... here is a bug with how it works right now, I'm not sure how to fix it when using ContainerSystem.IsEntityOrParentInContainer. Its a minuscule bug that people are not going to see, but I will note its existence.
> 2024-06-13.21-59-12.mp4

You are right its minuscule because idk whats wrong in that video

2024-06-14 04:33 UTC, Cojoke-dot commented
> You are right its minuscule because idk whats wrong in that video

The bullet hit the fax machine after I got in the crate (the second time) when I should have not hit. It just checks if the shooter is in a container, it does not differentiate the container and everything else.

2024-06-16 23:11 UTC, AJCM-git submitted a review, later dismissed
you still have a pending review from sloth

2024-06-23 02:15 UTC, metalgearsloth requested changes
I haven't checked this out locally but I'm not really sure why this needs to also use RequireProjectileTarget changes to just add container checks?

2024-06-30 22:50 UTC, Cojoke-dot commented
> I haven't checked this out locally but I'm not really sure why this needs to also use RequireProjectileTarget changes to just add container checks?

Is it not more efficient to never cancel it rather than the same checks for passover on the container too and cancel the PreventCollide? I may just not understand what your saying...

2024-07-11 01:56 UTC, metalgearsloth requested changes

2024-07-11 01:56 UTC, metalgearsloth commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
> +                                    }
This indentation is cooked.

2024-07-11 05:14 UTC, merged