EMP Grenade actually sabotages power
space-wizards/space-station-14 pull request #28984
Opened 2024-06-14 12:03 UTC by WarMechanic

## About the PR

EMP has been changed to target APC-powered-devices (most electrical devices) as well as batteries to disable them. This means EMP can interfere with autolathes, airlocks, atmos devices, substations and SMES. The power draw of a single EMP grenade now cuts out a substation, and the disabling effect prevents further recharge until it subsides.

EMP duration now also stacks, which creates a novel way to quietly black out the station by attacking engineering SMES with 3 EMP grenades (5tc EMP bundle) to black out the station for 3 minutes.

## Why / Balance

EMP at 2tc has a relatively low value-proposition when compared to C4 which is also 2tc. While EMP can probably black out one (or two if you're lucky) APCs and can be used as a defensive option against Stun/Lasers. C4 can be used to cut wires, substations, SMES, generators, doors, reinforced walls, people and the list probably continues.

New EMP can be used to soft-bomb station power in an explosion that isn't globally alarming (salv boom). Targeting the captain's office directly may let you crowbar in and steal the locker but it leaves ephemeral evidence in the form of everything electrical shimmering blue. Opting to bomb substations blacks out a wider area, providing several degrees of separation from your target. That is to say, new EMP grenade favours map knowledge and rewards better stealth.

## Technical details

This PR changes `C.S/Power/EntitySystems/PowerReceiverSystem` to read EmpPulseEvent and turn off APC devices. Unfortunately, I couldn't find a way to disable `C.S/Power/Components/PowerNetworkBatteryComponent` using the event system so I simply TryComp and change it in `C.S/.../EmpSystem` itself.
EMP Grenade had its power drain changed in YAML

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

tweak: EMP Grenades can now disable any electrical device.

2024-06-14 12:04 UTC, WarMechanic commented
As a quick note: due to `EmpSystem` now disabling machines there are a few obsolete specific interactions in `EmpSystem` which include: making vendors eject items randomly (???) and turning off cameras (they are turned off anyway). Should these be removed?

2024-06-14 14:38 UTC, Dutch-VanDerLinde commented
changelog is broken

2024-06-16 04:25 UTC, WarMechanic commented
im currently investigating an issue in that apc visuals don't update until after you inspect it

2024-06-16 13:53 UTC, WarMechanic commented
should emp disable energy sword and derivatives for consistency? i think i can also do that here

2024-06-16 17:29 UTC, WarMechanic commented
small refactor of how the power cell charger back-end works, it should be functionally the same in-game but the battery and charger can now communicate properly which was used to update the charger's state

2024-06-17 07:04 UTC, WarMechanic commented
emp now correctly calculates power drain from gravity generators, and emp grenades are capable of instantly silencing gravity generators which is something that c4 can't do

might make for some solid nukie tactics in the future

2024-06-17 07:09 UTC, WarMechanic commented
i could fix this https://github.com/space-wizards/space-station-14/issues/29116 now but would that be stretching the bounds of this PR?

2024-06-17 10:01 UTC, WarMechanic commented
alright after some strenuous testing i think emp interactions with everything should be good to go

2024-06-17 10:02 UTC, WarMechanic commented
i wanted to make emp affect energy sword too but that would require very specific overrides on the generic toggle system which is shit, it would be easier to make energy sword take power which i think would be pretty cool

2024-06-17 10:07 UTC, WarMechanic commented
also whoever is reviewing this:
i do use the obsolete `someComponent.Owner` in my code simply because i wasn't sure how to handle it another way, if you want to save some time reviewing a suggested change will get me started on the rest

2024-06-17 11:52 UTC, K-Dynamic commented
> i wanted to make emp affect energy sword too but that would require very specific overrides on the generic toggle system which is shit, it would be easier to make energy sword take power which i think would be pretty cool

I don't recommend this considering syndies/nukies use EMPs and it would be annoying, especially as eswords are a bit weak currently

2024-06-17 12:07 UTC, WarMechanic commented
i'm considering expanding nanotrasen use of emp tech, perhaps through research. one thing im considering is an emp slug that can be utilised for door breaching, anti-silicon or in this case a countermeasure to syndicate energy weapons

i don't think esword emp vulnerability is a door that necessarily needs to be closed, but i can always revisit it downstream if its unwanted

2024-06-17 16:52 UTC, patrickkelly0 commented on Content.Server/Power/EntitySystems/ChargerSystem.cs
this is really flipping cool

2024-06-17 16:52 UTC, patrickkelly0 commented on Content.Server/Power/EntitySystems/ChargerSystem.cs
+rep

2024-06-18 00:27 UTC, Boaz1111 commented
> i'm considering expanding nanotrasen use of emp tech, perhaps through research. one thing im considering is an emp slug that can be utilised for door breaching, anti-silicon or in this case a countermeasure to syndicate energy weapons
> 
> 
> 
> i don't think esword emp vulnerability is a door that necessarily needs to be closed, but i can always revisit it downstream if its unwanted

As far as NT EMP tech, ion rifle should coming in relatively soon

2024-07-27 12:51 UTC, metalgearsloth requested changes

2024-07-27 12:51 UTC, metalgearsloth commented on Content.Server/Gravity/GravityGeneratorSystem.cs
> +                return;
Just trycomp this is pointless

2024-07-27 12:51 UTC, metalgearsloth commented on Content.Server/Emp/EmpSystem.cs
> +            if (disabled.DisabledUntil == TimeSpan.Zero)
Just make it null

2024-07-27 12:51 UTC, metalgearsloth commented on Content.Server/Power/EntitySystems/BatterySystem.cs
> +        }
Generic is pointless here afaik.

2024-07-27 12:51 UTC, metalgearsloth commented on Content.Server/Power/EntitySystems/BatterySystem.cs
> +
Use the other version of trycomp here.

2024-07-27 12:51 UTC, metalgearsloth commented on Content.Server/Power/EntitySystems/BatterySystem.cs
> +
RemComp doesn't exception if it doesn't exist, just remcomp.

2024-07-27 12:51 UTC, metalgearsloth commented on Content.Server/Power/EntitySystems/ChargerSystem.cs
> +            RemComp<ChargingComponent>(target);
Same here.

2024-08-24 01:12 UTC, slarticodefast commented
Are you coming back to this?

2024-08-31 01:17 UTC, slarticodefast commented
If you plan to continue working on this, please write a comment here and I will reopen the PR for you.

2024-08-31 01:17 UTC, closed without merging