PipeNetDeviceComponent refactor
space-wizards/space-station-14 pull request #2912
Opened 2021-01-04 03:20 UTC by collinlunn

Pumps, vents, and such no longer inherit from PipeNetDeviceComponent, they are their own components.

Should make it easier to add UI, since you can put in a shared component for pumps/etc. 

Also other code quality improvements.

2021-01-06 11:59 UTC, Zumorica requested changes
Instead of using `Owner.EnsureComponent`, try using `Owner.EnsureComponentWarn`! That way it'll print a warning if the entity *was* missing the component in question, which is honestly preferred to silently fixing it.

2021-01-06 11:59 UTC, Zumorica commented on Content.Server/GameObjects/Components/Atmos/Piping/PipeNetDeviceComponent.cs
> +            SendMessage(message);
Creating the same empty message per pipe net device every update tick is expensive. Try caching the empty message and sending it over and over as needed, or use interfaces to update the rest of components instead.

2021-01-06 11:59 UTC, Zumorica commented on Content.Server/GameObjects/Components/Atmos/Piping/Pumps/BasePumpComponent.cs
>              if (_inletPipe == null | _outletPipe == null)
```suggestion
            if (_inletPipe == null || _outletPipe == null)
```

2021-01-07 01:52 UTC, metalgearsloth requested changes

2021-01-07 01:52 UTC, metalgearsloth commented on Content.Server/GameObjects/Components/Atmos/Piping/GasCanisterPortComponent.cs
> +                    }
Should return if connected if you want to replicate the old behavior.

2021-01-07 06:33 UTC, metalgearsloth approved these changes

2021-01-07 06:35 UTC, metalgearsloth approved these changes

2021-01-07 06:37 UTC, merged