Hidden loadout groups
space-wizards/space-station-14 pull request #29170
Opened 2024-06-18 17:46 UTC by Errant-4

## About the PR
Makes it possible to hide a loadout group. This is useful for groups where all choices are decided by the game automatically, and adding optional choices into the group is not feasible for desirable whatever reason. There is then no reason to display this loadout group to the player at all. (Such as survival boxes)

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2024-06-18 20:35 UTC, deltanedas requested changes

2024-06-18 20:35 UTC, deltanedas commented on Content.Client/Lobby/UI/Loadouts/LoadoutWindow.xaml.cs
> +            if (groupProto.Hidden == true)
remove == true its already a bool

2024-06-18 20:35 UTC, deltanedas commented on Content.Shared/Preferences/Loadouts/LoadoutGroupPrototype.cs
> +    public bool Hidden = false;
remove = false thats the default

2024-06-18 23:22 UTC, Errant-4 commented on Content.Client/Lobby/UI/Loadouts/LoadoutWindow.xaml.cs
> +            if (groupProto.Hidden == true)
Fixed

2024-06-18 23:22 UTC, Errant-4 commented on Content.Shared/Preferences/Loadouts/LoadoutGroupPrototype.cs
> +    public bool Hidden = false;
Fixed

2024-06-19 00:26 UTC, metalgearsloth approved these changes
Something weird is that someone can just export and import their character to edit it anyway but I guess that's a host issue?

2024-06-19 00:26 UTC, merged

2024-06-19 04:49 UTC, Errant-4 commented
> Something weird is that someone can just export and import their character to edit it anyway but I guess that's a host issue?

Huh, I guess that's something to keep in mind. But in the loadout group where I wanted this, every option not blocked by species filters is force-Selected , so it's fine if the player actually presses options in it. It makes no difference