more consistent CentComm naming
space-wizards/space-station-14 pull request #29217
Opened 2024-06-19 19:35 UTC by strO0pwafel

## About the PR
this pr changes a lot of the public-facing instances of "centcom" to"centcomm"

## Why / Balance
i wanted to start learning git and this seemed like an easy first pr. 

**Changelog**
:cl: 
- fix: Fixed inconsistent naming of CentComm.

2024-06-19 19:59 UTC, PJB3005 commented
CentCom is the correct spelling though.

2024-06-19 20:00 UTC, strO0pwafel commented
https://github.com/space-wizards/space-station-14/pull/21108#issuecomment-1771962208 i got it from here

2024-06-19 20:09 UTC, 0x6273 commented
I think we should go with "CentComn" instead. An n is kinda like half of an m, so it's a good compromise that everyone will surely be happy with.

2024-06-19 21:45 UTC, PJB3005 commented
https://en.wikipedia.org/wiki/United_States_Central_Command

2024-06-20 02:16 UTC, HolySSSS commented
We in command are saving up cents with 1 letter shorter name, think about the budget!

2024-06-20 15:26 UTC, ps3moira commented
Why would CentCom have a second M?

2024-06-22 07:14 UTC, IProduceWidgets commented
Everyone hush, I'm trying to talk on the centercom.

2024-07-25 23:33 UTC, Plykiya requested changes
at might as well as make the capitalization consistent as well

2024-07-25 23:33 UTC, Plykiya commented on Resources/Locale/en-US/cargo/bounties.ftl
> +bounty-description-trash = Recently a group of janitors have run out of trash to clean up, without any trash Centcomm wants to fire them to cut costs. Send a shipment of trash to keep them employed,
CentComm

2024-07-25 23:33 UTC, Plykiya commented on Resources/Prototypes/Entities/Clothing/Head/hoods.yml
> +  name: Centcomm winter coat hood
CentComm

2024-07-25 23:33 UTC, Plykiya commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
> +    jobTitle: Centcomm Agent
CentComm

2024-07-25 23:33 UTC, Plykiya commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
> +    jobTitle: Centcomm Quarantine Officer
CentComm

2024-07-25 23:33 UTC, Plykiya commented on Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
> +  description: A one-of-a-kind vending machine for all your centcomm aesthetic needs!
CentComm

2024-07-25 23:33 UTC, Plykiya commented on Resources/Prototypes/Objectives/traitor.yml
> +  name: Escape to centcomm alive and unrestrained.
CentComm

2024-07-25 23:33 UTC, Plykiya commented on Resources/Prototypes/Objectives/thief.yml
> +  name: Escape to centcomm alive and unrestrained.
CentComm

2024-07-25 23:33 UTC, Plykiya commented on Resources/Prototypes/Objectives/traitor.yml
> +  description: Do it however you like, just make sure they don't make it to centcomm.
CentComm....

2024-08-08 10:03 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Clothing/Head/hoods.yml
> +  name: Centcomm winter coat hood
```suggestion
  name: CentComm winter coat hood
```

2024-08-08 10:04 UTC, merged

2024-08-08 10:19 UTC, Plykiya commented
wtf actually merged, that's crazy