Muffins
space-wizards/space-station-14 pull request #29318
Opened 2024-06-21 21:32 UTC by RumiTiger

## About the PR
I added a chocolate and banana muffin to the game. I also resprited the cherry and berry muffins.
I added recipes for almost all the muffins.

## Why / Balance
I really don't understand why there were muffins in the game, but no way to make them.

## Media
![muffins](https://github.com/space-wizards/space-station-14/assets/154005209/63983536-5f58-4c31-aefd-422e3d038ca2)
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
**Changelog**
:cl:
- add: A chocolate and banana muffin has been added to the game!
- tweak: Now you can make a regular, chocolate, banana, and berry muffin!

2024-06-22 09:34 UTC, TheShuEd commented
webedit ops is real

2024-08-25 15:35 UTC, slarticodefast commented
The test fail seems to be real. One of the problem is that the meta.json has the state cherry-muffin twice. If you get it fixed I can have a look at the PR.

2024-08-29 02:48 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
> +#    Sugar: 10
You can uncomment this now that cherries are merged :)

2024-09-01 20:52 UTC, slarticodefast requested changes
Ok, tested it in-game and everything works great. Found two more minor things that need to be adjusted. I will ask the art directors for approval of the sprites next.

2024-09-01 20:52 UTC, slarticodefast commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/dinnerware.yml
> +    FoodPlateMuffinTin: 5
Put it below the FoodPlateTin. The objects show up in the machine in the order they are defined here, so they should be ordered by category.

2024-09-01 20:52 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/misc.yml
> +    - Banana
```suggestion
```
Remove the banana tag. That one is used for a cargo bounty and we don't want the muffins to fullfill it.

2024-09-12 12:43 UTC, UbaserB requested changes
Could you make the cherry and chocolate cupcakes match the shading of the normal muffin, (with minor hue-shifting not just pure black/white) alongside making them more desaturated? If you wanted to, you could alternatively take aspects from the original cherry muffin sprite and put it onto the normal muffin for consistency.

2024-09-16 13:31 UTC, RumiTiger commented
> Could you make the cherry and chocolate cupcakes match the shading of the normal muffin, (with minor hue-shifting not just pure black/white) alongside making them more desaturated? If you wanted to, you could alternatively take aspects from the original cherry muffin sprite and put it onto the normal muffin for consistency.

Like this?
![Muffins](https://github.com/user-attachments/assets/aa9e5adc-d5f8-4fc1-af87-27dc1842668f)

2024-09-16 16:25 UTC, slarticodefast commented
>Also in the future, please avoid web edits so we can make sure all changes have been properly tested.

Like I asked before, please avoid webedits and push changes to your remote branch using git instead for the following reasons:
- webedits are more susceptible to errors since you may forget to upload a file or submit a wrong one
- we cannot ensure the changes have been locally tested by the author like they should be
- each single commit causes the integration tests to be re-run and there is a total computation limit

Please refer to our documentation to learn how to use git and an IDE:
[Git for the SS14 Developer](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html)
[Setting up a Development Environment](https://docs.spacestation14.com/en/general-development/setup/setting-up-a-development-environment.html)

>Like this?

I will ask the art directors for approval.

2024-10-26 11:52 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Lathes/cooking.yml
> +    Steel: 50
Move this above FoodKebabSkewer so it is below the FoodPlateTin recipe.
You will also need to add this to lathe.yml so the recipe can be used.
Reminder: No web edits, please test your changes in-game.

2024-10-30 12:37 UTC, slarticodefast approved these changes
Looks good to me.
The sprites have been art director approved.

2024-11-01 02:06 UTC, deathride58 commented
Can confirm that the reviewing art director has given their approval, but did not state such in the PR. Dismissing their requested changes and merging

2024-11-01 02:06 UTC, deathride58 approved these changes

2024-11-01 02:06 UTC, merged