fix(uplink): Show all items in debug uplink
space-wizards/space-station-14 pull request #29313
Opened 2024-06-21 19:15 UTC by Brandon-Huu

## About the PR

Made it so the debug uplink has access to all listings.

## Why / Balance

Fixes #28499

## Technical details

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![image](https://github.com/space-wizards/space-station-14/assets/103440971/7e238638-52ea-4f16-8831-fb6c8bc3d14a)

## Breaking changes

**Changelog**

2024-06-21 19:15 UTC, Brandon-Huu commented
Probably a better way to do this?

2024-06-30 03:52 UTC, metalgearsloth requested changes

2024-06-30 03:52 UTC, metalgearsloth commented on Content.Shared/Store/Components/StoreComponent.cs
> +
Might be better to just make listings nullable and default to all instead of having a bool that invalidates another entire field?

2024-07-06 01:04 UTC, Brandon-Huu commented
Closed until I finish my PHD. Thesis

2024-07-06 01:04 UTC, closed without merging