reclaimer-lobby-art
space-wizards/space-station-14 pull request #29343
Opened 2024-06-22 13:31 UTC by GetOutMarutak

## About the PR

## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

![reclaimer lobby nuke](https://github.com/space-wizards/space-station-14/assets/169447831/8ff9d9a8-fd2a-44c8-b0cf-99a3cc744875)
![reclaimer lobby ice](https://github.com/space-wizards/space-station-14/assets/169447831/065ed17b-0e04-4e44-b871-9f5c8526b180)

2024-06-22 14:37 UTC, dffdff2423 commented
You need to include the copyright info in attributions.yml

2024-06-24 03:17 UTC, Flareguy requested changes
There should only be one lobby art added here. These are both too similar to eachother.
I would suggest keeping the nuke one, but the ice one would probably be fine too.

2024-06-24 12:53 UTC, Flareguy approved these changes

2024-06-25 00:21 UTC, VasilisThePikachu requested changes
Create a ``reclaimer-lobby-nuke.webp.yml`` and enable filtering. Like the rest of the lobby images.

also i think just "reclaimer-nuke" is a better name

2024-06-25 13:28 UTC, merged