GasFilterComponent
space-wizards/space-station-14 pull request #2935
Opened 2021-01-06 22:51 UTC by collinlunn

2021-01-09 12:33 UTC, PaulRitter requested changes
cannot evaluate the atmos parts since i haven't worked with that yet, otherwise just some nitpicks

2021-01-09 12:33 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Atmos/Piping/GasFilterComponent.cs
> +            Owner.TryGetComponent(out _appearance);
use componentdependencies here

2021-01-09 12:33 UTC, PaulRitter commented on Content.Shared/Atmos/Atmospherics.cs
> +    [Serializable, NetSerializable]
why is this needed?

2021-01-09 22:12 UTC, collinlunn commented on Content.Shared/Atmos/Atmospherics.cs
> +    [Serializable, NetSerializable]
Needed for Gas types to be used by VV

2021-01-09 22:14 UTC, PaulRitter commented on Content.Shared/Atmos/Atmospherics.cs
> +    [Serializable, NetSerializable]
ah, makes sense

2021-01-13 22:15 UTC, PaulRitter approved these changes

2021-01-13 22:15 UTC, merged