tweak(votes): Zombies count towards restart votes
space-wizards/space-station-14 pull request #29362
Opened 2024-06-22 23:16 UTC by Brandon-Huu

## About the PR

Made zombies count towards the minimum "ghost player" requirement to initiate a restart vote.

## Why / Balance

We have all had those zombie rounds with 4 crew left alive and not being able to restart.

## Technical details

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-06-29 05:38 UTC, metalgearsloth requested changes

2024-06-29 05:38 UTC, metalgearsloth commented on Content.Server/Voting/Managers/VoteManager.DefaultVotes.cs
>                      ghostCount++;
Coupling this tightly is terrible for forks who do not use zombies, use the eventbus as it's why we have it.

2024-07-06 01:03 UTC, Brandon-Huu commented
Closed until I finish my PHD. Thesis

2024-07-26 19:03 UTC, Brandon-Huu commented
Finished my thesis

2024-07-29 20:32 UTC, Brandon-Huu commented
I've thought of a more same way of doing this while sitting in the parking lot of an underfunded community college after a day of being in between life and death.

2024-08-23 21:48 UTC, IProduceWidgets requested changes

2024-08-23 21:48 UTC, IProduceWidgets commented on Content.Server/Ghost/GhostSystem.cs
> +            args.DeadPlayers += 1;
This will count aghost

2025-04-09 21:40 UTC, closed without merging

2025-04-09 21:40 UTC, slarticodefast commented
Closing this since it had requested changes and a merge conflict for several months.
If you are coming back to it, leave a comment and I will re-open.