Hallucinations
space-wizards/space-station-14 pull request #29385
Opened 2024-06-23 16:45 UTC by FaDeOkno

## About the PR

This PR adds real working hallucinations to the game.

## Why / Balance

Just, eh.. It's kinda strange to call SeeingRainbows effect as a hallucinations so I decided to make real ones.

## Technical details

So, basicly the system uses random VisibilityFlags so other people can not see hallucinations of others. That's pretty simple.
Also hallucinations entities spawns near humanoids, including the hallucinating person.
There also is a new prototype that contains details of hallucinations, so you can just make your ents and a pack that contains them to use.

## Media

https://github.com/space-wizards/space-station-14/assets/143940725/715c4b91-6a86-4eed-9bfb-3ae455ddc8f2

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

2024-06-23 16:47 UTC, metalgearsloth commented
Needs a significant amount of reviewing as currently this will tank server performance.

2024-06-23 16:55 UTC, FaDeOkno commented
I'd like to make it better, but not sure how yet

2024-06-24 00:15 UTC, IProduceWidgets commented
Is there any reason for this to be doing anything on server except for ensuring the component?

2024-06-24 00:42 UTC, deltanedas commented
client cant do ai

2024-06-24 02:16 UTC, FaDeOkno commented
> Is there any reason for this to be doing anything on server except for ensuring the component? Seems like basically all of it should be on client since the stuff only displays to a single client.

Entities now are mobs so I don't think so
But maybe there is a way...

2024-07-20 03:28 UTC, metalgearsloth requested changes
Also needs file-scoped namespaces.

2024-07-20 03:28 UTC, metalgearsloth commented on Content.Server/Hallucinations/HallucinationsSystem.cs
> +}
All of this needs to be clientside. Adding another visibility layer which will have a significant impact on PVS is absolutely not worth it.

EntityManager is also a dependency on systems you do not need to get it again.

2024-07-20 03:28 UTC, metalgearsloth commented on Content.Shared/Hallucinations/HallucinationsPrototype.cs
> +    /// <summary>
Datafield strings are obsolete please remove them.

2024-07-20 03:28 UTC, metalgearsloth commented on Content.Shared/Hallucinations/HallucinationsComponent.cs
> +    [DataField, ViewVariables(VVAccess.ReadWrite)]
This needs to be networked, TimeOffsetSerializer doesn't handle pausing on its own but we have a sourcegen version for that now, and datafield + VVRW is pointless.

2024-07-30 19:50 UTC, bruhmogus commented
this idea is funny as fuck ngl

2024-09-19 08:03 UTC, closed without merging