Fixed strapped med patients standing to talk and gasp
space-wizards/space-station-14 pull request #29520
Opened 2024-06-27 20:13 UTC by ArkiveDev

## About the PR

Fixed the bug where characters strapped onto a bed would visually stand to talk or gasp. 
## Why / Balance

Fixes #29427
It was visually jarring to see strapped patients quickly rotate between standing and laying with their dying breaths
## Technical details

The RotationVisualizerSystem defaults to vertical in the absence of a RotationState component. Buckling didn't set the RotationState because it relied on a call to the StandingStateSystem, but cancelled the DownAttemptEvent the StandingStateSystem raised, causing the StandingStateSystem to exit the down() function before it could set the RotationState. I removed the event handler (all it did was set the event to cancelled) so now the StandingStateSystem sets RotationState as it runs the rest of the down() function.  
I'm not sure why the buckleSystem canceled the DownAttemptEvent, but I haven't seen any unexpected behavior in my testing
## Media

![image](https://github.com/space-wizards/space-station-14/assets/95712736/d8223edd-f119-4d6a-b52d-3116c2ba263a)
![image](https://github.com/space-wizards/space-station-14/assets/95712736/bf8a9a6e-bac0-44a9-a3ff-5fe2aad7dfcf)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Strapped medical patients no longer dramatically stand up to gasp for air.

2024-06-27 23:26 UTC, Brandon-Huu commented
Did you test anything else besides the medbed?

2024-06-27 23:28 UTC, Brandon-Huu commented
The failed tests are not a bug, you are failing the buckling test

>  Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed BuckleUnbuckleCooldownRangeTest [58 ms]
  Error Message:
     Assert.That(standingState.Down(human), Is.False)
  Expected: False
  But was:  True

2024-06-28 04:53 UTC, metalgearsloth requested changes
Does this break someone getting put into crit when buckled in a chair?

2024-06-28 17:53 UTC, ArkiveDev commented
I had successfully tested talking, emoting, involuntary gasping, dragging, and (un)buckling self and others on the bed, medical bed, and chair before creating the PR.
Unfortunately it does look like this change breaks entering crit while buckled to a chair. The crit character remains upright until unbuckled. 
I'll need to try a different approach.

2024-06-28 17:58 UTC, GoodWheatley commented
> The crit character remains upright until unbuckled.

I’m pretty sure this is intended behavior, I’ve always seen it work like this before the bug was introduced.

2024-06-28 19:08 UTC, Brandon-Huu commented
> Unfortunately it does look like this change breaks entering crit while buckled to a chair.
Yeah, isn't that normal?

2024-06-29 03:18 UTC, Plykiya commented
do we just.... change the test...?

2024-07-02 10:12 UTC, Plykiya commented
fixed by https://github.com/space-wizards/space-station-14/pull/29653

2024-07-02 18:30 UTC, closed without merging