Guidebook UI close for items
space-wizards/space-station-14 pull request #29540
Opened 2024-06-28 16:56 UTC by Rorkh

## About the PR

fixes #29459 

## Why / Balance

QoL

## Technical details
I removed ToggleGuidebook method in GuidebookUIController class and embedded it's logic into OpenGuidebook method.
I suppose it was meant to be so because it's summary is "Opens or closes the guidebook" while old code only opened it.

## Media

https://github.com/space-wizards/space-station-14/assets/78957156/e9e1fc30-72b3-41f4-bd57-beca03a586cc
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Activating guidebook book with opened guidebook UI now closes it

2024-06-28 17:17 UTC, ShadowCommander requested changes
Can you make it keep this functionality? 

https://github.com/space-wizards/space-station-14/assets/10494922/0f423ab8-d648-4cff-87d0-42c99b70ed57

2024-06-28 18:51 UTC, Rorkh commented
> Can you make it keep this functionality?
> Content.Client_1uHbeBSFDm.mp4

I'll try. I'll take a look soon

2024-06-28 21:45 UTC, Rorkh commented
> Can you make it keep this functionality?
> Content.Client_1uHbeBSFDm.mp4

Done

2024-06-29 03:32 UTC, metalgearsloth requested changes

2024-06-29 03:32 UTC, metalgearsloth commented on Content.Client/UserInterface/Systems/Guidebook/GuidebookUIController.cs
> +        bool closeIfShown = true)
Much better API design to keep this on a separate method instead of making toggle functionality something done via passing args.

2025-01-21 08:20 UTC, closed without merging