Update water.yml
space-wizards/space-station-14 pull request #29596
Opened 2024-06-30 01:13 UTC by justdie12

https://github.com/space-wizards/space-station-14/assets/125140938/e9b2e08e-d05a-4528-a3f7-4dd00ad1585e

Water should put out the fire. That's why now the water tiles are extinguishing you.

## About the PR

## Why / Balance
bruh i burn in water

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-06-30 03:27 UTC, metalgearsloth requested changes
This should use https://github.com/space-wizards/space-station-14/pull/28168 instead

2024-06-30 06:25 UTC, lzk228 commented
fixes #21532

2024-06-30 10:22 UTC, justdie12 commented
> This should use #28168 instead

![image](https://github.com/space-wizards/space-station-14/assets/125140938/46c7f63b-c951-48fc-8c2e-4fe31155917b) 
![image](https://github.com/space-wizards/space-station-14/assets/125140938/c97200d8-5e9f-479b-8f87-3f25a45d63ee)

kinda... ummm... not working. Am I stupid?

2024-07-21 17:56 UTC, Emisse approved these changes

2024-07-22 02:53 UTC, merged