Dynamic Radial Menus
space-wizards/space-station-14 pull request #29678
Opened 2024-07-03 05:55 UTC by Rinary1

## About the PR

fix icons at radial menu, dynamic changes radius

## Why / Balance

If in radial menu has a lot of icons, it becomes impossible to use it

## Technical details

Added private void class "UpdateRadius" his update radius of radial menu, adds 5f every 1 icon.

## Media

![image](https://github.com/space-sunrise/space-station-14/assets/72972221/a6ef9bec-2639-4247-9fe9-f5036c2a8e38)
![image](https://github.com/space-sunrise/space-station-14/assets/72972221/c38af8a7-6fcb-4982-9e11-4948a6c92400)
![image](https://github.com/space-sunrise/space-station-14/assets/72972221/4b7ee876-5f39-42c5-95a6-e8d9d0aa5205)
![image](https://github.com/space-sunrise/space-station-14/assets/72972221/b28454dd-db75-4356-ba8d-2828d54ef5fd)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Rinary
 - fix: Fixed Radial Menus

2024-07-03 05:56 UTC, metalgearsloth requested changes

2024-07-03 05:56 UTC, metalgearsloth commented on Content.Client/UserInterface/Controls/RadialContainer.cs
You're getting the child count twice and iterating the entire collection, you should be passing this into the method.

You should also document this code.

2024-07-04 01:24 UTC, metalgearsloth commented on Content.Client/UserInterface/Controls/RadialContainer.cs
>          var children = ReserveSpaceForHiddenChildren ? Children : Children.Where(x => x.Visible);
```suggestion
		
        var children = ReserveSpaceForHiddenChildren ? Children : Children.Where(x => x.Visible);
```

2024-07-04 01:24 UTC, metalgearsloth commented on Content.Client/UserInterface/Controls/RadialContainer.cs
> +		Radius = baseRadius + (childCount * radiusIncrement);
```suggestion
		
		// Add padding from the center at higher child counts so they don't overlap.
		Radius = baseRadius + (childCount * radiusIncrement);
```

2024-07-04 01:25 UTC, metalgearsloth approved these changes

2024-07-04 01:25 UTC, merged

2024-07-04 23:41 UTC, SabatonShip commented
Woah! Thanx alot!