Adds a Dinky Start Sticker for security officers
space-wizards/space-station-14 pull request #29767
Opened 2024-07-06 14:47 UTC by PoorMansDreams

## About the PR

Wonkly golden star sticker for security officers with 100+ hours
## Why / Balance

## Technical details

## Media

![image](https://github.com/space-wizards/space-station-14/assets/150595537/89b1a88f-47bc-46d6-ae4d-63f15aa96c5a)
![image](https://github.com/space-wizards/space-station-14/assets/150595537/c4b89dba-2eb3-46dd-90bd-4e6f002a4afb)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added Star sticker for Secoffs

2024-07-07 09:00 UTC, Hrosts commented
Should it have a separate categoty for itself? Seems it would fit nicely with the trinkets

2024-07-07 14:07 UTC, Plykiya commented
> Should it have a separate categoty for itself? Seems it would fit nicely with the trinkets

trinket slots kinda make sense

we have enough badges, medals, etc to make it work

2024-07-07 19:59 UTC, PoorMansDreams commented
![image](https://github.com/space-wizards/space-station-14/assets/150595537/451e5336-c601-43a7-944f-f10cd591627c)
:godo:

2024-07-07 20:01 UTC, PoorMansDreams commented
> Should it have a separate categoty for itself? Seems it would fit nicely with the trinkets

I couldn't find a way to have it only be sec only if it were in trinkets

2024-07-07 22:14 UTC, Skarletto commented
urgent and desperately needed ⭐ :trollface:

2024-07-08 01:11 UTC, XxSWAG-MASTER-OVERLORDxX commented
this actually rases another issue, the dets vest has a badge on it, maybe that could also be its own neck slot item?

2024-08-11 23:43 UTC, UbaserB requested changes

2024-08-11 23:43 UTC, UbaserB commented on Resources/Prototypes/Entities/Objects/Misc/dinkystar.yml
> +    - type: EmbeddableProjectile
Please remove `EmbeddableProjectile`

2024-08-12 04:01 UTC, PoorMansDreams commented on Resources/Prototypes/Entities/Objects/Misc/dinkystar.yml
> +    - type: EmbeddableProjectile
it is gone

2024-08-12 04:05 UTC, UbaserB approved these changes

2024-08-15 01:50 UTC, merged