Vox displacement updates
space-wizards/space-station-14 pull request #29824
Opened 2024-07-08 13:26 UTC by Flareguy

## About the PR
Adds displacement maps for vox on gloves, eyewear, & back sprites. They should actually align to the sprite now.

Also fixes some minor vox sprite errors on labcoats + adds some new species-specific vox sprites that were easy to add.

## Why / Balance
Having items actually look like they fit on the character is good I think

## Media
![Content Client_mbx6h8keQT](https://github.com/space-wizards/space-station-14/assets/78941145/2942454f-2b0c-47a8-9742-b533ccfe3796)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
- tweak: Added vox displacement maps for glasses, gloves, and back items. They should display correctly now.

2024-07-08 13:38 UTC, lzk228 commented
tail should be completely new part of body

2024-07-16 22:51 UTC, TheShuEd approved these changes

2024-07-16 22:52 UTC, TheShuEd requested changes
Missclick, still need copy displacement to dummy

2024-07-17 07:32 UTC, TheShuEd approved these changes

2024-07-17 07:43 UTC, merged