Prevent Dragon Body from Despawning + Make Dragon Unrevivable
space-wizards/space-station-14 pull request #29842
Opened 2024-07-09 08:30 UTC by Cojoke-dot

## About the PR

Dragon is now unrevivable and the Dragons dead body will no longer despawn after a period
## Why / Balance

#29836, make Dragon unrevivable because there is nobody that should be reviving a dragon...
## Technical details

`RiftAccumulator` now only counts up when `RiftAccumulatorActive` is true, which only becomes false when the dragon dies
## Media

https://github.com/space-wizards/space-station-14/assets/83733158/057d433a-80d9-42d6-a1ec-336b35b49acb

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Dead Space Dragons no long despawn

2024-07-09 09:49 UTC, Cojoke-dot commented
That feels like it's just going to end badly for everyone still. If someone somehow got a dragon body(which would be full of crew bodies) and revived it, the dragon would just end up killing said person or dying quickly due to low health. The main purpose of the PR is to prevent dragons already killed from despawning with all the bodies they ate. If someone defibs the dragon into a crit state and it vanishes while they are healing it, it's not going to be fun for the antag that spent their time trying to revive them or all the people that got eaten by the dragon.

2024-07-09 10:11 UTC, deltanedas commented
being revived should reset the timer or remove the rift part, so the revived dragon is a safe pet

2024-07-09 13:54 UTC, metalgearsloth requested changes

2024-07-09 13:54 UTC, metalgearsloth commented on Content.Server/Dragon/DragonSystem.cs
> -            comp.RiftAccumulator += frameTime;
Isn't it just easier to just... not accumulate these if the dragon is dead?

2024-07-09 13:54 UTC, metalgearsloth commented on Content.Server/Dragon/Components/DragonComponent.cs
> +
Please update this to use modern standards as VVRW is unnecessary and datafield strings are obsolete though realistically this needs removing.

2024-07-09 16:48 UTC, Brandon-Huu commented
> make Dragon unrevivable because there is nobody that should be reviving a dragon...
Carp suit

2024-07-09 17:55 UTC, Cojoke-dot commented
> Carp suit

Carp suit just gives you an AI team, player-driven carp and dragon are still going to eat you alive.

2024-07-09 17:59 UTC, Cojoke-dot commented
> being revived should reset the timer or remove the rift part, so the revived dragon is a safe pet

They are still full of bodies… the main purpose of the pr is to make it so you don't lose those players due to a bug. Maybe in another pr though, there would need to be a system to get the people out without destroying the dragon body.

2024-07-09 18:05 UTC, Errant-4 commented
Okay hold on, a though just occured to me. Is it possible to harvest ichor from a dead dragon? If yes, is there a limit to the amount you can get? Or did we just create Medical's newest resource asset

2024-07-09 18:08 UTC, Cojoke-dot commented
> Okay hold on, a though just occured to me. Is it possible to harvest ichor from a dead dragon? If yes, is there a limit to the amount you can get? Or did we just create Medical's newest resource asset

No, so how Ichor is created is that it's just added when a dragon eats someone. The issue with harvesting it is that a dragon metabolizes at an insanely high rate, do it only ends up in their blood for about 5 seconds.

2024-07-09 19:03 UTC, deltanedas commented
> Carp suit just gives you an AI team, player-driven carp and dragon are still going to eat you alive.

roleplaying game when people roleplay:

2024-07-10 01:35 UTC, HelpTheSteak commented
You could also just alter the code for pacifist to player carps and dragons but only make it apply to carp suit wearers (I don't know if this is possible tbh)

2024-07-10 01:41 UTC, Cojoke-dot commented
> You could also just alter the code for pacifist to player carps and dragons but only make it apply to carp suit wearers (I don't know if this is possible tbh)

I'm going to do that anyways so the dragon and carps don't FF so much, but not in this pr 🙃

2024-07-18 21:50 UTC, IProduceWidgets commented
Does unrevivable prevent it becoming a zombie? Because zombie dragon is pretty peak.

2024-07-18 21:52 UTC, Cojoke-dot commented
> Does unrevivable prevent it becoming a zombie? Because zombie dragon is pretty peak.

I don't think so, humans don't become zombies when unrevivable. I'm not in a place to test it right now.

2024-07-18 21:53 UTC, IProduceWidgets commented
I can just add the comp and vv and check. One moment.

2024-07-18 23:36 UTC, deltanedas commented
> I'm going to do that anyways so the dragon and carps don't FF so much, but not in this pr 🙃

zombies have code for preventing ff for zombies, could be change to work with factions then have zombies use zombie faction and this use dragon faction

2024-07-21 07:57 UTC, Emisse approved these changes

2024-07-21 10:46 UTC, metalgearsloth commented
Dragon code stinky but this is fine I suppose.

2024-07-21 10:46 UTC, metalgearsloth approved these changes

2024-07-21 10:46 UTC, merged