Banjo can now be worn on your back
space-wizards/space-station-14 pull request #29931
Opened 2024-07-11 22:21 UTC by z9ctn4fn

## About the PR
You can now wear the banjo on your back.

## Why / Balance
#29616

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: You can now wear the banjo on your back and suit storage slots.
- add: Banjo sprites on your back added. They suck.

2024-07-11 22:29 UTC, z9ctn4fn commented
Ah shoot
Forgot about that

2024-07-11 23:53 UTC, deathride58 requested changes

2024-07-11 23:53 UTC, deathride58 commented on Resources/Textures/Objects/Fun/Instruments/banjo.rsi/meta.json
> +      }
Y'need commas
```suggestion
      },
      {
        "name": "equipped-SUITSTORAGE"
        "directions": 4
      },
```

2024-07-12 01:20 UTC, z9ctn4fn commented on Resources/Textures/Objects/Fun/Instruments/banjo.rsi/meta.json
> +      }
i fixed it

2024-07-12 02:18 UTC, deathride58 requested changes

2024-07-12 02:18 UTC, deathride58 commented on Resources/Textures/Objects/Fun/Instruments/banjo.rsi/meta.json
> +        "comment": "lol i made these shitty sprites in like 2 minutes -archangel"
This `comment` field is not defined within the [RSI spec](https://docs.spacestation14.com/en/specifications/robust-station-image.html); additional credits should be added to the copyright field at the root of the json object

2024-07-12 02:18 UTC, deathride58 commented on Resources/Textures/Objects/Fun/Instruments/banjo.rsi/meta.json
> +
This extra line needs removal

2024-07-12 02:35 UTC, Tayrtahn commented on Resources/Textures/Objects/Fun/Instruments/banjo.rsi/meta.json
> +        "copyright": "lol i made these shitty sprites in like 2 minutes -archangel"
Not like that either. Add it to the copyright field on line 8

2024-08-11 16:01 UTC, UbaserB reviewed
The banjo sprites need to be improved, mainly in consistency and form, look at the original sprites for reference.

2024-09-28 22:13 UTC, slarticodefast commented
Are you coming back to this?

2024-10-05 22:16 UTC, slarticodefast commented
If you come back to this, leave a comment and I will re-open the PR.

2024-10-05 22:16 UTC, closed without merging

2024-10-15 01:54 UTC, z9ctn4fn commented
I will not be coming back to this.

On Sat, Oct 5, 2024 at 2:16 PM slarticodefast ***@***.***>
wrote:

> If you come back to this, leave a comment and I will re-open the PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/space-wizards/space-station-14/pull/29931#issuecomment-2395212131>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYFNF75I7PJCEE4RRLMM56DZ2BQMNAVCNFSM6AAAAABKX2KBUSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGIYTEMJTGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>