Adds character eye customization #2946
space-wizards/space-station-14 pull request #2995
Opened 2021-01-13 13:21 UTC by Rember

Fixes #2946
This adds a set of color bars in the character customization screen that lets you adjust the eye colors of your character.

There's still a handful of problems:
* The bars don't fit on the default window size, so you'll have to lengthen your window to see them.
* The bars don't stretch out, in order to customize the colors right now you have to use the number input next to the bars.
* All of these functionalities for eye colors were pretty much copy-pasted from hair color code (with some deletions that seemed irrelevant), so there's probably a whole mess of redundant or plain wrong code, I'm not really experienced with C# so apologies for that.

Please leave feedback or help if you can!

2021-01-13 13:35 UTC, Rockdtben commented on Content.Client/UserInterface/HumanoidProfileEditor.cs
> +                    panel.SizeFlagsHorizontal = SizeFlags.None;
`panel.SizeFlagsHorizontal = SizeFlags.None;`

should be 

`panel.SizeFlagsHorizontal = SizeFlags.FillExpand;`

Like PJB said.

2021-01-13 17:30 UTC, PaulRitter requested changes
solid pr :+1:

2021-01-13 17:30 UTC, PaulRitter commented on Content.Shared/GameObjects/Components/SharedMagicMirrorComponent.cs
> +        }
you can pull latest master & just use the color struct here

2021-01-13 17:30 UTC, PaulRitter commented on Content.Client/GameObjects/Components/MagicMirrorBoundUserInterface.cs
> +    }
might as well use xaml to create a new control but i wont force you :P

2021-02-04 12:43 UTC, metalgearsloth commented
@Rember were you coming back to this?

2021-02-04 16:56 UTC, Rember commented
> 
> 
> @Rember were you coming back to this?

I got caught up in a lot of stuff lately, but I do want to come back to it (if it hasn't run too far behind master). I'll see if I can get back on it around this time tomorrow, then I'll be looking for help in #howdoicode. Feel free to ping me in case you want to help out with this.

2021-02-09 08:47 UTC, metalgearsloth commented
No worries I'll leave it up, was just checking if it was derelict.

2021-02-22 22:26 UTC, SweptWasTaken commented
> 
> 
> > @Rember were you coming back to this?
> 
> I got caught up in a lot of stuff lately, but I do want to come back to it (if it hasn't run too far behind master). I'll see if I can get back on it around this time tomorrow, then I'll be looking for help in #howdoicode. Feel free to ping me in case you want to help out with this.

No progress in 14 days, closing.

2021-02-22 22:26 UTC, closed without merging