SmartEquip now Pulls the Gun Rather than the Magazine
space-wizards/space-station-14 pull request #29986
Opened 2024-07-13 06:36 UTC by Cojoke-dot

## About the PR

When storing a gun on your backslot or beltslot, when using Smart-Equip it takes out the gun rather than the magazine of the weapon.
## Why / Balance

It does not make much sense to me to pull the magazine of a weapon on your belt rather than the weapon itself...
## Technical details

Check if the item being pulled from does not have the gun component before trying to take an item out of the `ItemSlotsComponent`
## Media

https://github.com/user-attachments/assets/5dcc7e43-a366-4804-a6be-2ec713b05a60

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Smart-Equip now takes the gun out of the slot rather than the weapon's magazine.

2024-07-13 06:56 UTC, lzk228 commented
does it also works with lantern in belt slot?

2024-07-13 06:57 UTC, lzk228 commented on Content.Shared/Interaction/SmartEquipSystem.cs
> +            !HasComp<GunComponent>(slotItem))
oh it doesnt...

2024-07-13 08:03 UTC, Cojoke-dot commented
ok... is there anything else that is like that? Don't want batteries or mags drawn from a smart-Equip... I don't know what else is like that

2024-07-13 11:43 UTC, metalgearsloth requested changes

2024-07-13 11:43 UTC, metalgearsloth commented on Content.Shared/Interaction/SmartEquipSystem.cs
> +            !HasComp<GunComponent>(slotItem))
Guns shouldn't be hardcoded into smartequip. It should be adjusted to be a global behavior pulling the item itself if you want it.

2024-07-14 01:03 UTC, Cojoke-dot commented on Content.Shared/Interaction/SmartEquipSystem.cs
> +            !HasComp<GunComponent>(slotItem))
Now it does 👍

2025-04-15 22:35 UTC, metalgearsloth commented
Okay playing around with this it does not seem to do as described, the item just doesn't move so something's changed since then and needs re-implementing.

2025-04-15 22:35 UTC, closed without merging