Grab intent
space-wizards/space-station-14 pull request #30011
Opened 2024-07-13 18:30 UTC by FaDeOkno

## About the PR

This PR adds Grab (Yellow intent system) into the game. You can grab someone softly, hardly and start choking them. Also you can throw grabbed entity.

## Why / Balance

Grab is a core mechanic in SS13, so I've decided to move it in SS14

## Technical details

The main system was made in the PullingSystem.cs. It checks when you are trying to pull someone, and if you have combat mode on, changes GrabStage to higher. Also it checks if you are in combat mode and moving grabbed entity when VirtualItem deletes. If you are, you will throw grabbed entity
Also there is MartialArts category added, just because I'm planning to make Mart. Arts after (or if) this PR is accepted.

## Media

https://youtu.be/E_pl2XdckM4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

PullMovingComponent was moved to Content.Shared.Movement.Pulling.Components

**Changelog**

2024-07-13 18:35 UTC, SebaenSah commented
Yes please! I can't wait to forget and accidentally start choking the secoffs!

2024-07-13 18:36 UTC, Plykiya commented
You have localized popup messages but you don't use them at all?

2024-07-13 18:38 UTC, Plykiya commented on Resources/Locale/en-US/pulling/popups.ftl
You have localized popup messages but you don't use them at all?

2024-07-13 18:39 UTC, FaDeOkno commented on Resources/Locale/en-US/pulling/popups.ftl
I do use them. In video are no popups only because it was made before adding them

2024-07-13 18:40 UTC, Plykiya commented on Resources/Locale/en-US/pulling/popups.ftl
looking through the code that got pushed at the moment, I don't see a single use of popups though?

2024-07-13 18:41 UTC, FaDeOkno commented
Uh... Whats wrong with Test Packaging test?..

2024-07-13 18:43 UTC, FaDeOkno commented on Resources/Locale/en-US/pulling/popups.ftl
`            _popup.PopupEntity(Loc.GetString("popup-grab-" + puller.Comp.GrabStage.ToString().ToLower() + "-target", ("puller", Identity.Entity(puller, EntityManager))), pullable, pullable, popupType);
            _popup.PopupEntity(Loc.GetString("popup-grab-" + puller.Comp.GrabStage.ToString().ToLower() + "-self", ("target", Identity.Entity(pullable, EntityManager))), pullable, puller, PopupType.Medium);
            _popup.PopupEntity(Loc.GetString("popup-grab-" + puller.Comp.GrabStage.ToString().ToLower() + "-others", ("target", Identity.Entity(pullable, EntityManager)), ("puller", Identity.Entity(puller, EntityManager))), pullable, othersFilter, true, popupType);`

2024-07-13 18:44 UTC, FaDeOkno commented on Resources/Locale/en-US/pulling/popups.ftl
Oh thats not how i wanted it to look like
Anyways there are popup using in PullingSystem

2024-07-13 18:44 UTC, Plykiya commented
Not sure if this would be a blocker for the PR but a doc exists for Grapple Systems which was approved but not merged. https://github.com/space-wizards/docs/pull/213

It'd be nice if a maintainer could weigh on in that.

2024-07-13 18:45 UTC, FaDeOkno commented on Resources/Locale/en-US/pulling/popups.ftl
Lines 680, 681, 682, 697 and 705

2024-07-13 18:45 UTC, Plykiya commented on Resources/Locale/en-US/pulling/popups.ftl
ah, my bad, the file was hidden. Yeah, okay. Looks good.

2024-07-13 18:46 UTC, FaDeOkno commented
Oh, okay

2024-07-13 19:00 UTC, Errant-4 commented
I tried it and I have some UX and maybe design observations:

Reptilians can grab without using hands at all levels, including apparently choking other players hands-free with their tail. They should probably use hands for the higher tier grabs like others?

When Player1 releases Player2, Player2 gets a popup saying "You are trying to escape" rather than telling them that Player1 released them

When a  player tries to escape a grab, there is no proper communication from the game about what's happening, is this actually taking some time? Did it succeed did it fail?

The grabbing player is also not notified in any way about attempted and succesful escapes

There does not seem to be a way for the Grabbing player to reduce the level of the grab (ie stop choking the target)

The PULLED and PULLING alert icons should display the current grab level

2024-07-13 19:07 UTC, FaDeOkno commented
> Reptilians can grab without using hands at all levels, including apparently choking other players hands-free with their tail. They should probably use hands for the higher tier grabs like others?
Im not sure about it

> When Player1 releases Player2, Player2 gets a popup saying "You are trying to escape" rather than telling them that Player1 released them
oh. will fix that rn

> When a player tries to escape a grab, there is no proper communication from the game about what's happening, is this actually taking some time? Did it succeed did it fail?
There are no popup showing that you're trying to escape?
You have random chance to escape, but also there are 1 second delay for avoiding too fast clicks

> The grabbing player is also not notified in any way about attempted and succesful escapes
Would be fixed

> There does not seem to be a way for the Grabbing player to reduce the level of the grab (ie stop choking the target)
Maybe it would be good to be able to lower the level by dropping virtualitem and clicking on the alert while in combat mode

> The PULLED and PULLING alert icons should display the current grab level
I don't have such icons yet. I can draw them to display the type, but it probably will be awful

2024-07-13 19:24 UTC, bruhmogus commented
OH DEAR GOD NO INTENTS *fucking dies*

2024-07-13 19:27 UTC, ninruB commented
> OH DEAR GOD NO INTENTS _fucking dies_

Whats so bad about intents? I personally like them and we did have a dedicated disarm intent action a while ago.

2024-07-13 19:29 UTC, Errant-4 commented
> OH DEAR GOD NO INTENTS _fucking dies_

Ah yeah that's a somewhat fair point, the title should probably be changed given that **no literal intents are actually involved** (which is good)

2024-07-13 19:50 UTC, TheDoctor1977 commented
> Whats so bad about intents? I personally like them and we did have a dedicated disarm intent action a while ago.

I personally just find them to be unnecessarily clunky for things that could be done contextually (in the same way that we killed disarm intent by just making it right click)

2024-07-13 19:52 UTC, bruhmogus commented
> > Whats so bad about intents? I personally like them and we did have a dedicated disarm intent action a while ago.
> 
> I personally just find them to be unnecessarily clunky for things that could be done contextually (in the same way that we killed disarm intent by just making it right click to disarm)

we could also make it so that trying to ctrl click on someone you're already pulling increases the grab level, so like one click to soft, two clicks to hard, three to fucking murderise

2024-07-13 19:53 UTC, lzk228 commented
should be an animation when you trying to grab (like punch/push animation)

2024-07-13 19:59 UTC, FaDeOkno commented
> > > Whats so bad about intents? I personally like them and we did have a dedicated disarm intent action a while ago.
> > 
> > 
> > I personally just find them to be unnecessarily clunky for things that could be done contextually (in the same way that we killed disarm intent by just making it right click to disarm)
> 
> we could also make it so that trying to ctrl click on someone you're already pulling increases the grab level, so like one click to soft, two clicks to hard, three to fucking murderise

But that's definetly how it works here

2024-07-13 20:46 UTC, bruhmogus commented
> > > > Whats so bad about intents? I personally like them and we did have a dedicated disarm intent action a while ago.
> > > 
> > > 
> > > I personally just find them to be unnecessarily clunky for things that could be done contextually (in the same way that we killed disarm intent by just making it right click to disarm)
> > 
> > 
> > we could also make it so that trying to ctrl click on someone you're already pulling increases the grab level, so like one click to soft, two clicks to hard, three to fucking murderise
> 
> But that's literally how it works here

i didnt read any of that i just saw intent and had an allergic reaction

2024-07-13 21:23 UTC, FaDeOkno commented
> > > > > Whats so bad about intents? I personally like them and we did have a dedicated disarm intent action a while ago.
> > > > 
> > > > 
> > > > I personally just find them to be unnecessarily clunky for things that could be done contextually (in the same way that we killed disarm intent by just making it right click to disarm)
> > > 
> > > 
> > > we could also make it so that trying to ctrl click on someone you're already pulling increases the grab level, so like one click to soft, two clicks to hard, three to fucking murderise
> > 
> > 
> > But that's literally how it works here
> 
> i didnt read any of that i just saw intent and had an allergic reaction

lol

2024-07-13 21:27 UTC, FaDeOkno commented
> Edit Also, while obviously you can't fully describe a change this big in the changelog, you can definitely do better than "Added grab system". Consider that many players have never played Space Station 13, what does this tell them about what this is and how to use it? nothing

uh
i can try 
maybe.

2024-07-13 21:34 UTC, FaDeOkno commented
virtual items are cursed

2024-07-13 22:17 UTC, FaDeOkno commented
![image](https://github.com/user-attachments/assets/19790dad-c7c8-4022-9098-a5662a49f715)
I guess this looks pretty ok for the alert

2024-07-14 09:28 UTC, deepdarkdepths commented
How do you throw people using this?

2024-07-14 10:48 UTC, slarticodefast commented
> should be an animation when you trying to grab

I agree that this needs better visual cues or people will start choking each other by accident without noticing.

There should also be popups for all stages for the grabber, the grabbed person and third persons (at least if the animation does not show this clearly).
"You are being grabbed by Urist McHands"
"You grab Urist McScales"
"Urist McHands grabs Urist McScales"

"Urist McHands starts choking you"
"You start choking Urist McScales"
"Urist McHands starts choking Urist McScales"

Especially throwing ist not visually distinct from pulling. Maybe throwing someone should rotate his sprite like it does for objects?

If I am a security officer watching a fight I should be able to see if they are just pulling each other or choking/throwing to be able to decide if I need to step in.

2024-07-14 11:24 UTC, FaDeOkno commented
> > should be an animation when you trying to grab
> 
> I agree that this needs better visual cues or people will start choking each other by accident without noticing.
> 
> There should also be popups for all stages for the grabber, the grabbed person and third persons (at least if the animation does not show this clearly). "You are being grabbed by Urist McHands" "You grab Urist McScales" "Urist McHands grabs Urist McScales"
> 
> "Urist McHands starts choking you" "You start choking Urist McScales" "Urist McHands starts choking Urist McScales"
> 
> Especially throwing ist not visually distinct from pulling. Maybe throwing someone should rotate his sprite like it does for objects?
> 
> If I am a security officer watching a fight I should be able to see if they are just pulling each other or choking/throwing to be able to decide if I need to step in.

There are these popups. Video has first version of grab so it doesnt have them.

I'm currently trying to rewrite throwing because its awfully made. But rotating thrown person will be looking... Not really good

2024-07-14 18:41 UTC, FaDeOkno commented
Not properly tested yet

2024-07-14 21:45 UTC, FaDeOkno commented
I think I should make this PR draft until it will be really finished

2024-07-14 23:45 UTC, FaDeOkno commented
Now it looks like a finished system. I thought it would take more time.

Virtual Items are not disappearing to lower the stage anymore
Throwing now works by directional Ctrl+Q
P o p u p s for grabbing added
Alerts updated (not sucks I hope)

2024-07-14 23:49 UTC, FaDeOkno commented
_i havent even touched any .yml's excluding alerts wth._

2024-07-14 23:52 UTC, FaDeOkno commented
my bad

2024-07-14 23:52 UTC, mirrorcult commented
im a fan of this as a basic implementation for this system, there is a grappling doc i'd like to get to eventually which was mentioned above but this should be totally fine to have right now, we can just iron out that stuff later. will get to a proper review later

2024-07-15 07:40 UTC, Verbalase commented
![cc8](https://github.com/user-attachments/assets/e0ffe304-295e-468c-8418-ce5c7528ba89)

actually would be perfect

2024-07-15 16:53 UTC, Anderery commented
_Just waiting now.._

2024-07-15 19:02 UTC, Errant-4 commented
I don't know if I'm doing something wrong, but it doesn't actually seem to work anymore? Trying to pull a mob a second time now just ends the pull

2024-07-15 19:12 UTC, FaDeOkno commented
> ~I don't know if I'm doing something wrong, but it doesn't actually seem to work anymore? Trying to pull a mob a second time now just ends the pull~ Ignore me, I forgot combat mode...

![Evade_Pyro](https://github.com/user-attachments/assets/511ce484-2e56-4006-ba04-faa735fcf125)

2024-07-15 19:15 UTC, Errant-4 commented
I did find an actual UI issue, though. If your second hand is not empty when you try to choke the pulled mob, the click will _end the pull completely_ rather than tell you that it failed to choke and maintain a hard grab

2024-07-15 19:17 UTC, FaDeOkno commented
Uh thats strange. I thought it was fixed

2024-07-15 19:18 UTC, FaDeOkno commented
Oh I see. Thats because it returns false after popup

2024-07-15 19:24 UTC, FaDeOkno commented
You can try it now

2024-07-15 19:33 UTC, Errant-4 commented
> You can try it now

Nothing seems to have changed

2024-07-15 19:34 UTC, FaDeOkno commented
Thats strange. You tried to rebuild?

2024-07-15 19:40 UTC, FaDeOkno commented
lemme check again...

2024-07-15 19:45 UTC, FaDeOkno commented
hm

2024-07-15 19:46 UTC, FaDeOkno commented
oh dang I found it
wait a sec

2024-07-15 19:47 UTC, Errant-4 commented
Cough test your fixes

2024-07-17 03:01 UTC, ps3moira commented
there should probably be a cooldown for each escape attempt so people can't just autoclicker/keybind out of being grabbed.

2024-07-17 10:13 UTC, FaDeOkno commented
> there should probably be a cooldown for each escape attempt so people can't just autoclicker/keybind out of being grabbed.

There is

2024-07-18 04:06 UTC, Catdere commented
I think the grab intent actions are greatly beneficial to the game and is a step for opening the doors for more complex maneuvers such as CQC.

2024-07-18 18:14 UTC, FaDeOkno commented
Well
Now this is not only grab PR

2024-07-18 18:55 UTC, lzk228 commented
such thing should has guidebook section, but i think it can be done in another pr

2024-07-18 19:37 UTC, Catdere commented
> such thing should has guidebook section, but i think it can be done in another pr

I have a much better idea. why not after learning CQC either with a book or spawning is as a chef, it tells you "The Basics of CQC"
also having combos would be helpful in a guidebook

2024-07-18 20:04 UTC, FaDeOkno commented
Oh this really worked

2024-07-18 22:36 UTC, Catdere commented
CQC? so you think you're a real big boss huh? I think the price of CQC manuals should be quite high something like 12 TC

2024-07-18 22:41 UTC, Catdere commented
> CQC? so you think you're a real big boss huh? I think the price of CQC manuals should be quite high something like 12 TC

Ive chosen this random price due to the power, CQC is a weapon implant that cant be removed nor can anyone tell you have it until you use it.

2024-07-18 23:15 UTC, mirrorcult commented
CQC should really be in a different PR

2024-07-18 23:16 UTC, metalgearsloth requested changes
1. Needs a design doc.
2. I would recommend splitting the PR out if you want to get it through review faster.
3. Please read through https://docs.spacestation14.com/en/general-development/codebase-info/conventions.html

2024-07-18 23:16 UTC, FaDeOkno commented
> > CQC? so you think you're a real big boss huh? I think the price of CQC manuals should be quite high something like 12 TC
> 
> Ive chosen this random price due to the power, CQC is a weapon implant that cant be removed nor can anyone tell you have it until you use it.

Sounds pretty fair

2024-07-19 04:34 UTC, Yebok24 commented
> OH DEAR GOD NO INTENTS _fucking dies_

You already have a combat mode like on TG, what's wrong with also having a grab system like on TG?

2024-07-19 12:36 UTC, FaDeOkno commented
> 2. I would recommend splitting the PR out if you want to get it through review faster.

Is it necessary?

> 3. Please read through https://docs.spacestation14.com/en/general-development/codebase-info/conventions.html

Okay, I'll structure my files soon

2024-07-19 13:27 UTC, EmoGarbage404 commented
Yeah please move all the CQC stuff out as it'll make reviewing significantly easier

2024-07-19 14:15 UTC, FaDeOkno commented
> Yeah please move all the CQC stuff out as it'll make reviewing significantly easier

okay

2024-07-19 14:42 UTC, FaDeOkno commented
what
why
It exsists.
![image](https://github.com/user-attachments/assets/8fd3fdf2-7eac-49a7-a969-e37676a76570)

2024-07-19 14:43 UTC, deltanedas commented
its private not protected

2024-07-19 14:46 UTC, FaDeOkno commented
> its private not protected

I've never had such problem without making it protected. And checks are not finding it for some reason

2024-07-22 19:04 UTC, M1and1B commented
Heh, good job, my friend

2024-07-27 21:32 UTC, FaDeOkno commented
> 1. Needs a design doc.

Well I've made a small doc, but there are no any reaction to it yet

2024-07-29 18:34 UTC, FaDeOkno commented
_Waiting._

2024-07-30 11:40 UTC, deepdarkdepths commented
Give me grab or give me death

2024-08-02 03:36 UTC, Tornado-Technology commented
Okay all shit with netPredict fixed, xd
Link: https://github.com/Tornado-Technology/space-station-14/tree/grab-intent

2024-08-02 03:37 UTC, Tornado-Technology commented
> Okay all shit with netPredict fixed, xd Link: https://github.com/Tornado-Technology/space-station-14/tree/grab-intent

I really changed only one system and two components, but I don't give a fuck, just like I don't give a fuck about creating client systems for the sake of popups. 

@FaDeOkno you can take my solution

2024-08-02 03:39 UTC, Tornado-Technology commented
> 1. Needs a design doc.
> 2. I would recommend splitting the PR out if you want to get it through review faster.
> 3. Please read through https://docs.spacestation14.com/en/general-development/codebase-info/conventions.html

I'll ping you since the author didn't provide a link to his docs: https://github.com/space-wizards/docs/pull/261

2024-08-02 03:43 UTC, Tornado-Technology requested changes
It's best not to make changes to code you haven't gotten into

2024-08-02 03:43 UTC, Tornado-Technology commented on Content.Server/Movement/Components/PullMovingComponent.cs
>      public EntityCoordinates MovingTo;
Better be uset `NetCoordinates`

2024-08-02 03:43 UTC, Tornado-Technology commented on Content.Shared/Teleportation/Systems/SharedPortalSystem.cs
> +using System.Linq;
I think u dont need linq for this

2024-08-02 03:43 UTC, Tornado-Technology commented on Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
> -
Pls remove shit

2024-08-02 03:43 UTC, Tornado-Technology commented on Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
> +
Pls remove shit

2024-08-02 04:17 UTC, FaDeOkno commented on Content.Shared/Teleportation/Systems/SharedPortalSystem.cs
> +using System.Linq;
I didnt touch this line

2024-08-02 07:23 UTC, Pumkin69 commented
Instead of doing a full RNG % system to break out of grabs i recommend making it a short do-after that is uninterruptible and making it similar to how league of legends does crit chance and doing a markov chain to do RNG instead of just a straight % chance. This would make it so its not just lottery on if you get out in the first try or the 20th (or at least it will help a lot). This will be hard to code i assume but i have no fucking clue i just think its a better system than full RNG cause its not fun imo to just gamble on stuff like shoves for example it feels skilless and unfun.

2024-10-10 05:30 UTC, LevitatingTree commented
seems really interesting, but would boxers/wrestlers get any sort of martial arts as well?

2024-10-16 17:16 UTC, ps3moira commented
Bump

2024-10-23 01:03 UTC, GroggleG commented
Bump x2

2024-11-18 03:06 UTC, deepdarkdepths commented
Maintainer discussion purgatory

2024-12-03 03:42 UTC, DinoWattz commented
> Maintainer discussion purgatory

I wouldn't wish that on my worst enemies..

2024-12-03 03:44 UTC, Pumkin69 commented
just a week away

2024-12-09 19:43 UTC, FaDeOkno commented
e




design doc is still not accepted

2024-12-09 19:43 UTC, FaDeOkno commented
💀

2024-12-27 08:54 UTC, Pumkin69 commented
ah i love maintainer hell so much!!!

2025-02-18 12:18 UTC, loksill commented on Content.Server/Alert/Click/StopPulling.cs
what is IAlertClick (12,47)

2025-02-18 17:02 UTC, FaDeOkno commented on Content.Server/Alert/Click/StopPulling.cs
that's an old thing
I guess, i should already close this PR

2025-02-22 19:15 UTC, loksill commented on Content.Server/Alert/Click/StopPulling.cs
I want to push this PR to another repository. But I can't because of this fucking class.

2025-02-22 19:16 UTC, loksill commented on Content.Server/Alert/Click/StopPulling.cs
where did this file come from, it is not in the original build

2025-02-23 14:01 UTC, FaDeOkno commented on Content.Server/Alert/Click/StopPulling.cs
Then you have to replace this class with alert event

2025-03-08 08:30 UTC, loksill commented on Content.Server/Alert/Click/StopPulling.cs
Couldn't this have been done right away?

2025-03-10 02:24 UTC, metalgearsloth requested changes

2025-03-10 02:24 UTC, metalgearsloth commented on Content.Shared/Movement/Pulling/Components/PullerComponent.cs
> +    };
Grabbing needs to be its own component + system, even if grabbing can cause pulling they're still handling 2 different things.

2025-03-10 02:24 UTC, metalgearsloth commented on Content.Shared/Movement/Pulling/Components/PullableComponent.cs
>  }
Same here don't mix components into god components, keep them separate.

2025-03-10 02:24 UTC, metalgearsloth commented on Content.Shared/MartialArts/Systems/GrabThrownSystem.cs
> +
Predict it properly please, ask on discord if you need help.

If anything you might need to run it on client so it looks correct from their POV and have it tell the server.

2025-03-10 02:24 UTC, metalgearsloth commented on Content.Shared/MartialArts/Systems/GrabThrownSystem.cs
> +
HasComp is pointless, also you should be using the deferred comp changes in the eventbus.

2025-03-10 02:24 UTC, metalgearsloth commented on Content.Shared/MartialArts/Components/GrabThrownComponent.cs
> +}
Please document your code, also these need datafields.

2025-03-10 02:24 UTC, metalgearsloth commented on Content.Shared/Hands/EntitySystems/SharedHandsSystem.Interactions.cs
> +        }
Virtual items shouldn't be baked in here either, just call trydrop on it and let virtualitemsystem handle it.

2025-03-10 02:24 UTC, metalgearsloth commented on Content.Server/Implants/SubdermalImplantSystem.cs
> +            _pullingSystem.TryStopPull(ent, pull, ignoreGrab: true);
As below.

2025-03-10 02:24 UTC, metalgearsloth commented on Content.Shared/Administration/SharedAdminFrozenSystem.cs
> +            _pulling.TryStopPull(uid, pullable, ignoreGrab: true);
As below.

2025-03-10 02:24 UTC, metalgearsloth commented on Content.Server/Hands/Systems/HandsSystem.cs
> +
As below no virtual baking in. Copy-pasting code is also terrible for maintainability because if someone fixes a bug or refactors they won't realise there's 4 other spots they need to update.

2025-03-10 02:24 UTC, metalgearsloth commented on Content.Server/Body/Systems/RespiratorSystem.cs
> +
CanBreathe if anything should be an event and grab should not be infecting other systems.

2025-04-15 22:26 UTC, metalgearsloth commented
Re-open if you come back to it.

2025-04-15 22:26 UTC, closed without merging