Replace GetGridUid() with transformSystem.GetGrid()
space-wizards/space-station-14 pull request #30031
Opened 2024-07-14 05:13 UTC by Plykiya

## About the PR

Title

## Why / Balance

Project 0 warnings

## Technical details

Pretty uneventful drop-in replace

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

beep boop

2024-07-14 05:25 UTC, Plykiya commented
suffering

2024-07-14 05:35 UTC, Plykiya commented
![image](https://github.com/user-attachments/assets/2cf48184-9810-433a-9694-477b52f98592)
wait a minute, all the tests passed locally

2024-07-14 05:49 UTC, Plykiya commented
![image](https://github.com/user-attachments/assets/23faaf54-4a0b-45cd-8783-8190647c3528)

strange, the tests all pass locally.

2024-07-14 05:50 UTC, Winkarst-cpu commented
ubuntu-latest is broken.

2024-07-14 06:11 UTC, Plykiya commented
![image](https://github.com/user-attachments/assets/82b227af-9c8f-4019-b464-144018ed5431)
![image](https://github.com/user-attachments/assets/c9e6c69b-f998-48f6-951f-e1cc2d2b20cd)

maaan, I don't know

2024-07-14 06:13 UTC, Winkarst-cpu commented
Just say that failed check is not related to the PR.

2024-07-14 07:10 UTC, Plykiya commented
> Just say that failed check is not related to the PR.

![image](https://github.com/user-attachments/assets/c66154ea-9eff-4288-bcb0-0ca14faf8656)

yeah alright

2024-07-14 18:30 UTC, Plykiya commented
I'll just leave those two random test fails for someone else to deal with in another PR 👍

2024-07-14 21:22 UTC, Winkarst-cpu commented
> I'll just leave those two random test fails from PathfindingSystem.Grid and PuddleSystem for someone else to deal with in another PR 👍

All checks have passed 😄

2024-08-08 09:54 UTC, metalgearsloth requested changes

2024-08-08 09:54 UTC, metalgearsloth commented on Content.Server/Administration/Commands/WarpCommand.cs
Re-use system plz.

2024-08-08 09:54 UTC, metalgearsloth commented on Content.Server/Administration/Commands/WarpCommand.cs
>                  xform.AttachToGridOrMap();
Same here also attachtogridormap also bad.

2024-08-16 00:43 UTC, closed without merging