Diamond Hoe
space-wizards/space-station-14 pull request #30069
Opened 2024-07-15 14:39 UTC by Yeah-I-listening-Hollywood-undead

## About the PR
Added Diamond Hoe for very successful gardeners

## Why / Balance

This will not affect the game balance in any way, since this hoe does not differ from the standard one in anything other than its appearance. That make the reference to minecraft.
## Technical details

At the moment, crafting this hoe causes the server to explode. I do not know how to fix it, I hope you will help
## Media

![Screenshot_1058](https://github.com/user-attachments/assets/c5439d28-4396-409c-b5d7-a81b7e911222)

- [✔] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

A diamond hoe has been added. You can make it out of two diamonds and two sticks. And extremely upset their fellow miners who risked their lives for these diamonds.

2024-07-15 14:41 UTC, UbaserB commented on Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
> +  name: Diamond hoe
make it lowercase

2024-07-15 14:45 UTC, TheShuEd requested changes

2024-07-15 14:53 UTC, TheShuEd commented
let the unit tests do their job.

2024-07-15 15:04 UTC, lzk228 commented
also your cl is broken, should be 
```
:cl:
- tweak: text
- add: text
```

2024-07-15 15:09 UTC, TheShuEd commented on Resources/Prototypes/Recipes/Crafting/Graphs/improvised/diamond_hoe.yml
> +      - material: MaterialDiamond
```suggestion
      - material: RawDiamond
```

2024-07-15 15:42 UTC, regenpower commented
this is why i live for this game

2024-07-15 16:45 UTC, BombasterDS commented
RawDiamonds is now stackable thing, try use Diamonds instead in craft recipe

2024-07-15 16:46 UTC, BombasterDS commented
Actually, I think it's better not to be craftable, but a loadout equipment for longtime botany players (like janitor's golden plunger)

2024-07-15 16:49 UTC, BombasterDS commented on Resources/Prototypes/Recipes/Crafting/Graphs/improvised/diamond_hoe.yml
> +      - material: RawDiamond
Try use Diamond instead of RawDiamond

2024-07-15 17:46 UTC, SlamBamActionman commented
Can we at least make it colored the same as the diamond item, to make it more cohesive and less of a blatant Minecraft reference than what it already is?

2024-07-16 14:44 UTC, BombasterDS commented
You need to add ConstructionComponent to it, as failed test says

2024-07-16 14:51 UTC, Yeah-I-listening-Hollywood-undead commented
> You need to add ConstructionComponent to it, as failed test says

I don't see  ConstructionComponent in any YML prototypes

2024-07-16 15:13 UTC, BombasterDS commented
> > You need to add ConstructionComponent to it, as failed test says
> 
> I don't see ConstructionComponent in any YML prototypes

Add
- type: Construction
  graph: DiamondHoe
  node: DiamondHoe (actually, nodes must be named lowercased, so it's better to call node "hoe" there and in construction graph)

2024-07-16 15:17 UTC, BombasterDS commented on Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
> +
- type: Construction
     graph: DiamondHoe
     node: hoe

2024-07-16 15:24 UTC, BombasterDS commented
> > You need to add ConstructionComponent to it, as failed test says
> 
> I don't see ConstructionComponent in any YML prototypes

In YAML Component is skipping, so just search Construction

2024-07-16 15:45 UTC, Tayrtahn commented on Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
> +    sprite: Objects/Tools/Hydroponics/diamondhoe.rsi
This somehow got duplicated

2024-07-16 15:47 UTC, BombasterDS commented
And you better call nodes with lowercases. For example, you have DiamondHoe graph and DiamondHoe node. Better just call node hoe

2024-08-23 01:01 UTC, slarticodefast commented
Are you coming back to this? If you need help fixing the errors, feel free to ping me on discord (Slartibartfast).

2024-08-30 01:05 UTC, slarticodefast commented
If you plan to continue working on this, please write a comment and I will re-open the PR for you.

2024-08-30 01:05 UTC, closed without merging

2024-09-28 09:05 UTC, Yeah-I-listening-Hollywood-undead commented
> If you plan to continue working on this, please write a comment and I will re-open the PR for you.

Yes, I do. Everyone forget this PR and i think. Somewhere in the discord it was decided that this was not necessary

2024-09-28 10:38 UTC, slarticodefast commented
The repository that submitted this pull request has been deleted, so I am unable to re-open it. Could you either restore it or make a new PR?

> Everyone forget this PR and i think. Somewhere in the discord it was decided that this was not necessary

There hasn't been an internal maintainer discussion thread for this yet, so I don't think such a decision has been made.
Personally I don't see a reason against including this, it's a fun little gimmick. You would have to address the reviews though.

2024-09-29 11:08 UTC, Yeah-I-listening-Hollywood-undead commented
> There hasn't been an internal maintainer discussion thread for this yet, so I don't think such a decision has been made.
> Personally I don't see a reason against including this, it's a fun little gimmick. You would have to address the reviews and fix the test fails though before this can be merged.

Undersand. I am made new PR