DummyWireComponent
space-wizards/space-station-14 pull request #3011
Opened 2021-01-16 20:40 UTC by collinlunn

Spawns fake cosmetic wires under machines so that real wires appear to tile to the machine.

2021-01-17 02:52 UTC, metalgearsloth requested changes

2021-01-17 02:52 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Constructible/Power/wires.yml
> +    state: hvcable_4
Are these iconcomponents needed?

2021-01-17 02:52 UTC, metalgearsloth commented on Content.Server/GameObjects/Components/Power/DummyWireComponent.cs
> +    public class DummyWireComponent : Component, IMapInit
Component should be client-side if possible IMO.

2021-01-17 13:38 UTC, PaulRitter requested changes
since all the dummywirecomponent does is spawn a prototype underneath the entity, i'd argue on maybe naming it a bit more generic, maybe SpawnPrototypeComponent

2021-01-17 13:38 UTC, PaulRitter commented on Content.Client/GameObjects/Components/Power/DummyWireComponent.cs
> +            serializer.DataField(ref _dummyWireProtos, "prototype", new List<string> { "HVDummyWire" });
if its a list i'd call it prototypes
```suggestion
            serializer.DataField(ref _dummyWireProtos, "prototypes", new List<string> { "HVDummyWire" });
```

2021-01-18 10:50 UTC, metalgearsloth approved these changes

2021-01-18 10:51 UTC, merged