Toilet
space-wizards/space-station-14 pull request #3012
Opened 2021-01-16 23:46 UTC by Macoron

## About the PR
Adds toilet. Things that you can do with it:

- [x] You can seat on toilet (sick!)
- [x] You can raise and lower toilet seat
- [x] You can unanchor toilet and run around with it
- [x] You can deconstruct toilet using welding tool to get some metal
- [x] Toilets are reagent containers with decent amount of toxic water
- [x] Using crowbar you can open cistern lid and stash something
- [x] You can swirlie yourself

I used almost same stash mechanic from potted plant. Added new SecretStash component that used both in toilet cistern and potted plant.

P.S. Inspired by: https://www.youtube.com/watch?v=hHqAvzGyy30

2021-01-16 23:49 UTC, SweptWasTaken commented
Why is the toilet water toxic by default?

Also, add a complex digestion system, a robust plumbing network and... AND....

2021-01-16 23:56 UTC, ike709 commented
@SweptWasTaken Assistants don't flush.

2021-01-17 00:27 UTC, PJB3005 commented
> You can swirlie yourself

But can you swirlie other people?

2021-01-17 02:25 UTC, komunre commented
I like this idea. Maybe it will be good for Roleplay.

2021-01-17 08:06 UTC, Macoron commented
> Why is the toilet water toxic by default?

Pee poo water bad

> But can you swirlie other people?

Nope, until grab will be implemented. 

> Also, washing sinks when?

Maybe in next PR

2021-01-17 08:18 UTC, mirrorcult commented
> > But can you swirlie other people?
> 
> Nope, until grab will be implemented.

could just use click+drag plus a do_after

2021-01-17 08:20 UTC, Macoron commented
> > > But can you swirlie other people?
> > 
> > 
> > Nope, until grab will be implemented.
> 
> could just use click+drag plus a do_after

This will buckle someone

2021-01-17 08:21 UTC, mirrorcult commented
> 
> 
> > > > But can you swirlie other people?
> > > 
> > > 
> > > Nope, until grab will be implemented.
> > 
> > 
> > could just use click+drag plus a do_after
> 
> This will buckle someone

sad but I'm glad i can experience the gritty realism of buckling someone to a toilet

2021-01-17 13:25 UTC, PaulRitter reviewed
cannot stash any prying tools, currently fine imo since we dont really have intents rn

really nice to see these wellwritten content prs, a nice way to show off how easy it really is to implement new features :D

2021-01-17 13:25 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Watercloset/ToiletComponent.cs
> +            IsSeatUp = random.NextDouble() > 0.5f;
could just do random.Prob

2021-01-17 13:25 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Watercloset/ToiletComponent.cs
> +                    message.AddMarkup(Loc.GetString("There is [color=darkgreen]someting[/color] inside cistern!"));
`someting` in the aaaiiiir tonight
```suggestion
                    message.AddMarkup(Loc.GetString("There is [color=darkgreen]something[/color] inside cistern!"));
```

2021-01-17 13:25 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Watercloset/ToiletComponent.cs
> +                var selfMessage = Loc.GetString("You bashes themselves with {0:theName}!", Owner);
```suggestion
                var selfMessage = Loc.GetString("You bashes yourself with {0:theName}!", Owner);
```

2021-01-17 13:25 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Watercloset/ToiletComponent.cs
> +                var selfMessage = Loc.GetString("You stick your head into {0:theName} and flushes it!", Owner);
```suggestion
                var selfMessage = Loc.GetString("You stick your head into {0:theName} and flush it!", Owner);
```

2021-01-17 13:26 UTC, PaulRitter requested changes
used wrong reviewkind, see above review for actual review

2021-01-17 20:11 UTC, Macoron commented
@PaulRitter all issues should be resolved

2021-01-17 20:36 UTC, mirrorcult commented on Content.Server/GameObjects/Components/Watercloset/ToiletComponent.cs
> +                var selfMessage = Loc.GetString("You bashes yourself with {0:theName}!", Owner);
You bash yourself!

2021-01-18 11:51 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Watercloset/ToiletComponent.cs
> +        [ViewVariables] private SecretStashComponent _secretStash = default!;
imo its fine

2021-01-18 12:29 UTC, Macoron commented on Content.Server/GameObjects/Components/Watercloset/ToiletComponent.cs
> +        }
Are you seriously want to create custom appearance class for a toilet?

2021-01-18 19:41 UTC, Macoron commented on Content.Server/GameObjects/Components/Watercloset/ToiletComponent.cs
> +        [ViewVariables] private SecretStashComponent _secretStash = default!;
Agree. Don't want to overengineer it with null checks. 
90% of the component doesn't make any sense if you can't hide something inside cistern.

2021-01-18 20:09 UTC, Macoron commented on Content.Server/GameObjects/Components/Watercloset/ToiletComponent.cs
> +        }
Prying sound will play anyway (by using crowbar). Added amazing toilet seat sound.

2021-01-19 05:26 UTC, metalgearsloth commented on Content.Server/GameObjects/Components/Watercloset/ToiletComponent.cs
> +        }
https://discord.com/channels/310555209753690112/770682801607278632/790229194319462430

2021-01-19 13:43 UTC, Macoron commented
Added toilet visualizer and awesome seat sound. Wow

2021-01-20 07:02 UTC, metalgearsloth approved these changes

2021-01-20 07:02 UTC, merged

2021-01-20 07:02 UTC, metalgearsloth commented
Game is complete.