Further slippery object tweaks
space-wizards/space-station-14 pull request #30131
Opened 2024-07-17 17:59 UTC by ninruB

## About the PR

This PR seeks to address common feedback regarding the recent slippery object time standardization-nerf PR, and hopes to finetune the values suggested in it for more entertaining and balanced play.

Clown PDA now stuns for 3 seconds as opposed to the default (1.5).

Banana peels now stun for 1 second (prev: 1.5) and launch with a coefficient of 2 (prev: 1.5).

Minana peels now serve as an upgrade to banana peels and stun for 1.5 seconds with a launch coefficient of 2.5.

Bananium peels now serve as the final upgrade in the aforementioned chain and stun for 2 seconds and launch with a coefficient of 3.

Syndicate soap had it's launch coefficient reduced to 1 from 3 to make it more combat viable.

Omega soap had it's stats reversed (3/5 instead of 5/3) to make it less combat viable but better for thieves and more entertaining.
## Why / Balance

See commit description details and the above section.
## Technical details

Webedit, I can't run a devenv let alone build the game or test values right now due to hardware issues.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None(?)

**Changelog**

:cl: BurninDreamer
- tweak: Slip stun duration and launch coefficients have been further tweaked.

2024-07-17 20:41 UTC, slarticodefast commented
I agree that slip items should have different levels of "quality" and the banana adjustments are good for that. However I feel like the omega soap should stay at 5s stun time. With a 3.5 second doafter for cuffing this change would make the slip stun impossible. We should keep that possibility for at least one (rare) slipping object. Especially pacifist thieves use it as an alternative to combat.

2024-07-17 23:45 UTC, metalgearsloth requested changes
All PRs need to be tested ingame, additionally I would also ask that this PR also have a video ingame please.

2024-07-18 02:34 UTC, ninruB commented
> All PRs need to be tested ingame, additionally I would also ask that this PR also have a video ingame please.

I literally can't do this on my current PC and I'm certainly not getting an upgrade any time soon.
If either is strictly mandatory I'd have to ask a reviewer to do that instead.

2024-07-18 03:02 UTC, thebadman4662 commented
I feel syndie soap should be possible to slipcuff at ~5s stun. It makes you valid, its syndicate item. If 1TC feels too low for reusable stealth kill potential, perhaps it could be increased? THat said bolas already exist and from that you are just one stun prod away from murdering anyone alone, even if its tad more dangerous to attacker.

Nerf was mainly against Sel Fantagos(Fucking banana peels being guaranteed kills), no? Feels weird antags got nerfed as well.

Other than that slips seem okay, tiders can't just murder anyone for free because a common slip guarantees slipcuff kills. Sure secoff can still slip with disabler/stun baton only to get stunned with it but touching that would very much nerf interfering/defending syndicates so at some point admins have to step in to ban assholes.

2024-07-18 03:29 UTC, ninruB commented
> However I feel like the omega soap should stay at 5s stun time. With a 3.5 second doafter for cuffing this change would make the slip stun cuff impossible.

> I feel syndie soap should be possible to slipcuff at ~5s stun. 

If I'm not mistaken, in both cases a slipcuff is still possible because stuns halve the amount of time required to cuff someone.

> It [syndie soap] makes you valid, its a syndicate item. If 1TC feels too low for reusable stealth kill potential, perhaps it [stun duration] could be increased?

While I think it could be 4-5 seconds of stun as opposed to 3, I also think it might be a bit too oppressive in combat with competent use, I also think that exploring an even more different alternative with no launch coefficient at all and instead some damage on slip could be interesting if the middle ground isn't settled upon.

2024-07-18 03:44 UTC, thebadman4662 commented
> While I think it could be 4-5 seconds of stun as opposed to 3, I also think it might be a bit too oppressive in combat with competent use, I also think that exploring an even more different alternative with no launch coefficient at all and instead some damage on slip could be interesting if the middle ground isn't settled upon.

Stam stun is 6s and sec have roughly half that time to cuff someone assuming they are not high on stims/meth/epi which either makes cuffing impossible or very tight. At 3 you basically have to be on top of someone already ready + they need to be "kind of afk" and let you cuff them. Then there is part where syndie might not be playing with 10 ping so little bit of grace period if form of longer stun is needed for some players.

2024-07-18 08:00 UTC, slarticodefast commented
>At 3 you basically have to be on top of someone already ready 

The [liltenhead video on the slip nerf](https://www.youtube.com/watch?v=uCaMk4A5Q8M) shows how close the timing on this has to be for it to work.
I agree that this should not be something only possible for low ping players as it would give them a significant advantage.

2024-07-18 08:19 UTC, ninruB commented
Alright this is agreeable, you get around 600ms to react and get a slipcuff off in the worst-case scenario, I propose a stun duration of 4.5 on both soaps to put this at 2~ seconds instead.

Now, two questions, is 4.5 desired and agreeable and should it be bundled with no launch coefficient and damage on step for syndicate soap? Or should a middle ground be reached with 3.5/4 seconds instead?

2024-07-18 08:27 UTC, slarticodefast commented
A launch coefficient of 0 would probably give you more time for cuffing as you will know where your opponent will land making it easier to aim, meaning it actually buffs the soap. 4.5s sounds good to me, but I can do some in-game testing later.

2024-07-18 10:34 UTC, slarticodefast commented
> Could someone explain why we're so insistent on slip-cuffing for traitors?

>slip nerfs was meant to curb a particular playstyle and focus back more on combat.

It creates entertaining "abduction" roleplay scenarios and gives traitors a non-lethal way of accomplishing their goals. The alternatives are nocturine or just gunning down your target, both of which have less player interaction. Making the balance force you towards combat is bad for a roleplay game and pushes it towards being a combat simulator.

The slip cuff method also has the drawback that the target can still call for help after being cuffed or walk over the soap to avoid it, so it should be cheaper than other methods. The syndie soap price should probably be increased again if it gets buffed. But I totally agree that it should not be available to every tider with a banana peel and slipping was definitely overpowered before the nerf.

And again, if we don't want slip cuffing in general we should balance it in a way makes it impossible for all players. While having a low ping will always give you an advantage, having an entire combat option depend on it is bad balancing in my opinion.

2024-07-18 12:26 UTC, Djungelskog2 commented
Correct me if I'm wrong but aren't there still options such as using beanbags, stunbatons, makeshift stunbatons, chemicals or simply reviving them after criting them for those scenarios? It also means you have to put thought and preparation into them rather than using a bit of maints gear you can find just about anywhere to do the exact same thing over and over again

2024-07-18 12:38 UTC, slarticodefast commented
There is an open PR making stun batons unable to be used by thieves or other pacifists as this was intended according to maintainers. If you crit someone to take their stuff you probably will just hide them in maints intead of healing them.

2024-07-18 12:43 UTC, Djungelskog2 commented
Then use the chemicals, slips were cheap, easy to obtain and almost impossible to avoid unless your metagaming every person holding a slippable object in your vicinity. Not to mention how unfun it is when it occurs

2024-07-18 12:58 UTC, SlamBamActionman commented
> Correct me if I'm wrong but aren't there still options such as using beanbags, stunbatons, makeshift stunbatons, chemicals or simply reviving them after criting them for those scenarios? It also means you have to put thought and preparation into them rather than using a bit of maints gear you can find just about anywhere to do the exact same thing over and over again

I think that this raises a good point; players have a lot of ways stun 'n' cuff each other, it's just that the Syndie soap has previously been a fairly punishing way to achieve it. Plus it's reusable and, well, the 1 TC cost is _very_ good value. Keeping the Syndie soap purely as a slipping option better matches its cost.

If you're a Passenger/Boxer you have access to the Rigged Boxing Gloves for 4 TC; stuns in 2 seconds, is (relatively) silent, deals 30 damage and you get a proper stun duration. Nocturine + Hypopen is the strongest stun at 12 TC, but if you're crafty you can get around the Nocturine cost by scrounging chemicals from maints pills and mushrooms. Hell, some food and cigarettes have Licoxide in them.

If those options aren't enough, put Omega Soap in the uplink at a high (4 TC?) cost. That's on par with other lethal options and makes it an investment without eliminating the playstyle.

2024-07-18 13:04 UTC, thebadman4662 commented
Adding omega soap to uplink would make it syndicate contraband by admin ruling as main way would be buying it from there, right now crew can argue how much its of a weapon and sec does not have to consifcate it on sight due to lack of syndicate contraband branding, do we really want to make lives of thieves even harder?

2024-07-18 17:33 UTC, ninruB commented
> This seems contradictory, coefficient of 5 launches you far away and is more entertaining than being stamcrit for 5 seconds.

This is a misunderstanding, it was 5 stun and 3 coefficient and is now 5 coefficient and 3 stun, no contradiction here.

2024-08-12 00:41 UTC, UbaserB commented
Maintainers have decided that the current slip times feel fine for balance and that it goes against the intent of #27879 by changing a bunch of the values.

2024-08-12 00:41 UTC, closed without merging