Localization of encryption keys
space-wizards/space-station-14 pull request #30172
Opened 2024-07-19 15:22 UTC by chavonadelal

## About the PR

Localization of encryption keys
## Why / Balance

## Technical details

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: to4no_fix

2024-07-19 15:41 UTC, TheShuEd requested changes
Procedural generation of localization keys like here is a very awkward thing to support. It is better to put LocId field in the communication channel prototype and use it directly

2024-07-19 16:43 UTC, chavonadelal commented
> Procedural generation of localization keys like here is a very awkward thing to support. It is better to put LocId field in the communication channel prototype and use it directly

@TheShuEd If I understood you correctly and you suggest putting the localization key directly into the ID of the communication channel, then this does not seem possible. Errors appear.
![image](https://github.com/user-attachments/assets/ef8e984e-00cd-455f-873d-6284dae8e625)

2024-07-19 18:45 UTC, TheShuEd commented
Yep, you need change DataField type, and adapt code for it

2024-07-19 18:46 UTC, TheShuEd commented
Wait, no, dont toich Id filed

2024-07-19 18:46 UTC, TheShuEd commented
Just... Just use name field?

2024-07-19 19:11 UTC, chavonadelal commented
> Just... Just use name field?

@TheShuEd I don't think this will work since the default channel is taken from the prototype of the encryption key where the default channel ID is specified. As I understand it.
![image](https://github.com/user-attachments/assets/9a8041b9-2c9d-4ae9-951f-93be7ce20cbf)

2024-07-19 22:29 UTC, Tayrtahn requested changes
Building localized string IDs from prototype IDs like this is pretty janky. RadioChannelPrototype actually has a LocalizedName field; just use that.

My suggestions are untested, but I think they should work.

Also do what Ed said and change RadioChannelPrototype.Name from string to LocId.

2024-07-19 22:29 UTC, Tayrtahn commented on Content.Shared/Radio/EntitySystems/EncryptionKeySystem.cs
> +                ("channel", Loc.GetString($"chat-radio-{defaultChannel.ToString().ToLower()}")),
```suggestion
                ("channel", proto.LocalizedName),
```

2024-07-19 22:29 UTC, Tayrtahn commented on Content.Shared/Radio/EntitySystems/EncryptionKeySystem.cs
> +                ("channel", Loc.GetString($"chat-radio-{defaultChannel.ToString().ToLower()}")),
```suggestion
                ("channel", proto.LocalizedName),
```

2024-07-20 14:03 UTC, chavonadelal commented
> Building localized string IDs from prototype IDs like this is pretty janky. RadioChannelPrototype actually has a LocalizedName field; just use that.
> 
> My suggestions are untested, but I think they should work.
> 
> Also do what Ed said and change RadioChannelPrototype.Name from string to LocId.

I did what you asked 😄

2024-07-20 14:13 UTC, TheShuEd approved these changes

2024-07-20 14:17 UTC, Tayrtahn approved these changes
Looks good to me. I'm going to assume you've tested it and it works.

2024-07-20 14:19 UTC, chavonadelal commented
> Looks good to me. I'm going to assume you've tested it and it works.

Yes, the required text appears, I didn’t notice any errors.

2024-07-20 16:14 UTC, merged