Implement a playerpanel
space-wizards/space-station-14 pull request #30238
Opened 2024-07-21 20:09 UTC by nikthechampiongr

## About the PR

This PR implements a player panel which provides general information and actions for a player.

PR will be drafted pending feedback from adminbus, however it could be merged immediately in its current state. Should this be merged immediately, then keep in mind more features likely need to be implemented and the ui may need to look a little better.

## Why / Balance

It is a convenience feature that allows admins to access important information about a player in 1 place as well as perform quick actions.

## Technical details

The playerpanel is a bui. Upon opening it, it will receive info the admin can access and display the appropriate information and enable the appropriate buttons.

Most buttons implement their functionality by running commands with the target player's guid.

The exceptions to this:
- The kick button which can only work with a username
- The toggle freeze button which sends a message to the server for the freeze to be performed.

The whitelist commands were also altered to also receive a guid.

Also a small quirk, the whitelist toggle will function immediately without expecting a message from the server. This is because we already know the user is able to use the command, and even if for some reason a player is whitelisted/dewhitelisted before we press the button the command that is executed will have no effect.

## Media

![image](https://github.com/user-attachments/assets/bef99254-bf4e-45ff-aa6f-e3cda9388211)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: 
ADMIN:

- add: The player panel has now been added and can be invoked with the playerpanel command. It will display general information on the selected player, as well as allow for general actions to be performed on them.

2024-07-24 13:11 UTC, nikthechampiongr commented
Well feedback round over, should be ready.

2024-07-24 13:48 UTC, nikthechampiongr commented
Heisentest my beloved

2024-07-24 14:07 UTC, nikthechampiongr commented
Rolebans cause me suffering.

2024-08-05 08:25 UTC, metalgearsloth requested changes
Rest looks okay just EUIs being a PITA to write.

2024-08-05 08:25 UTC, metalgearsloth commented on Content.Client/Administration/UI/PlayerPanel/PlayerPanel.xaml
> +           <controls:ConfirmButton Name="WhitelistToggle" Text="False" Visible="False"></controls:ConfirmButton>
Local plx.

2024-08-05 08:25 UTC, metalgearsloth commented on Content.Server/Administration/Commands/PlayerPanelCommand.cs
> +            return CompletionResult.FromHintOptions(options, "<PlayerIndex>");
localise.

2024-08-09 05:33 UTC, metalgearsloth approved these changes

2024-08-09 05:33 UTC, merged