Reflective vest needs to be held in hand to work
space-wizards/space-station-14 pull request #30246
Opened 2024-07-22 08:14 UTC by Plykiya

## About the PR

Added a SlotFlags field on ReflectComponent so that anything with the component, if the SlotFlag is set to anything besides None, has to be equipped in that indicated slot to work.

## Why / Balance

People were holding their reflective vests in their hand and using it as an infinite health shield

## Technical details

I already explained it!

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Uploading 2024-07-22 01-11-18.mp4…

## Breaking changes

not breaking

**Changelog**

:cl:
- tweak: Reflective vests now need to be equipped to receive its benefits.

2024-07-30 14:00 UTC, EmoGarbage404 requested changes

2024-07-30 14:00 UTC, EmoGarbage404 commented on Content.Shared/Weapons/Reflect/ReflectComponent.cs
> +public sealed partial class ReflectComponent : Component, IClothingSlots
i would say just remove the interface and give the variable a more descriptive name.

2024-07-30 14:00 UTC, EmoGarbage404 commented on Content.Shared/Weapons/Reflect/ReflectComponent.cs
> +    public SlotFlags Slots { get; set; } = SlotFlags.NONE;
using NONE for the default is kinda strange and i think itd be more logical if it was nullable and then null was the value for "this isn't tied to a slot"

2024-07-30 17:44 UTC, Plykiya commented on Content.Shared/Weapons/Reflect/ReflectSystem.cs
> +            !_inventorySystem.TryGetInventoryEntity<ReflectComponent>((user, inventoryComp), out _))
TryGetInventoryEntity only retrieves entities with the component that are in their proper slot but only if the IClothingSlot interface is implemented, which is why I can't get rid of it or make it nullable guahh

2024-09-19 00:00 UTC, metalgearsloth commented
@Plykiya is this still getting worked on

2024-09-19 00:01 UTC, Plykiya commented
> @Plykiya is this still getting worked on

depends, if I have to make it not use the interface then I probably won't continue it, if I just have to migrate the duplicate code into a function I can do that

2024-11-13 09:02 UTC, closed without merging