Cleans up Hydroponics content.
space-wizards/space-station-14 pull request #3025
Opened 2021-01-19 08:17 UTC by SweptWasTaken

## About the PR 

Hydroponics content is very dirty and disorganized. I am cleaning it up.

= Putting stuff where it should be
= Adding stuff like inhands and updating some sprites
= Getting YAML and rsis up to standard

2021-01-26 20:13 UTC, SweptWasTaken commented
This is ready.

2021-01-29 10:28 UTC, PaulRitter requested changes

2021-01-29 10:28 UTC, PaulRitter commented on Resources/Textures/Clothing/Shoes/Boots/jackboots.rsi/desktop.ini
> +jackboots.png=@jackboots.png,0
google drive moment

2021-02-09 21:58 UTC, SweptWasTaken commented
Fixed the one review and updated it from the last hydroponics PR.

2021-02-17 12:19 UTC, PaulRitter approved these changes

2021-02-17 12:59 UTC, metalgearsloth commented
Do not research

2021-02-17 12:59 UTC, merged

2021-02-17 17:28 UTC, Visne commented
Pretty sure this messed up the spade texture.