Add camera bug
space-wizards/space-station-14 pull request #30250
Opened 2024-07-22 16:37 UTC by pofitlo-Git

## About the PR

Adding a new item to the syndicate's uplink - the camera bug. a handheld device that allows you to view cameras, thereby allowing you to plan your actions much better or use them for tracking, ambushes, etc.
## Media

![image](https://github.com/user-attachments/assets/b295a521-cdcf-4ed7-92c7-febad5591bb7)
![image](https://github.com/user-attachments/assets/de241e13-9448-459b-bbc4-b908097672e4)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

🆑
- add: Added Camera Bug in syndicate uplink that cost 2 TC and allow you watch all cameras on station

2024-07-22 17:29 UTC, Brandon-Huu commented
Does the device come out of the box with the ability to monitor the cameras?
If so, I do not think it should. The syndicate should have to manually connect it to a camera router(server) to get access to the network.

2024-07-22 17:57 UTC, deltanedas commented
if you are going to break into ai sat or wherever the routers are you can just as easily make a camera monitor yourself (which is a t1 civ btw)

2024-07-22 18:20 UTC, Brandon-Huu commented
> if you are going to break into ai sat or wherever the routers are you can just as easily make a camera monitor yourself (which is a t1 civ btw)

How will this function on rounds with multiple stations?
How will this affect nukies?

2024-07-22 18:22 UTC, TheShuEd commented
I would suggest doing things a little differently. Add 3 hidden cameras, like a small item that needs to be manually placed in the plants, or slipped into a bag, and a monitor that allows you to keep an eye specifically on such cameras.

2024-07-22 18:24 UTC, pofitlo-Git commented
> I would suggest doing things a little differently. Add 3 hidden cameras, like a small item that needs to be manually placed in the plants, or slipped into a bag, and a monitor that allows you to keep an eye specifically on such cameras.

in future. now just this. because its critically important for tactic game

2024-09-15 21:37 UTC, slarticodefast commented
Hey, sorry for the wait on the review, we are currently quite backlogged. I opened an internal maintainer disscussion for the item balance. The code looks good on the first view and I can give it an in-game test when you fix the merge conflict.

Quick question: Did you make the item sprite yourself or did you port it from SS13? We had people misunderstand the copyright field in the meta file before, so I just want to make sure we don't violate any licenses by accident.

2024-09-15 21:41 UTC, pofitlo-Git commented
> Hey, sorry for the wait on the review, we are currently quite backlogged. I opened an internal maintainer disscussion for the item balance. The code looks good on the first view and I can give it an in-game test when you fix the merge conflict.
> 
> Quick question: Did you make the item sprite yourself or did you port it from SS13? We had people misunderstand the copyright field in the meta file before, so I just want to make sure we don't violate any licenses by accident.

it's my sprite and i think that i can improve this a little )

2024-09-18 21:00 UTC, slarticodefast requested changes
Hey, I brought it up for maintainer dicussion and could you make it 3 TC and add a power cell to it for balance? Look at the handheld crew monitor to see how that is done. Inheriting from BaseHandheldComputer might be all you need to do.

2024-09-26 12:48 UTC, pofitlo-Git commented
> Hey, I brought it up for maintainer dicussion and could you make it 3 TC and add a power cell to it for balance? Look at the handheld crew monitor to see how that is done. Inheriting from BaseHandheldComputer might be all you need to do.

I can't make it chargeable because it should be realised into the SurveillanceCameraMonitorSystem. and I literally don't sure that I should touch it considering the consequences that may be

2024-09-30 02:26 UTC, slarticodefast requested changes
I tried it out myself and it seems like SurveillanceCameraMonitorBoundUserInterface causes some problems when combined with a power cell. I guess we can include it as it is for now and adjust the balance later if necessary.
Could you fix the merge conflict and address two minor nitpicks? Should be good to merge then.

2024-09-30 02:26 UTC, slarticodefast commented on Resources/Locale/en-US/store/uplink-catalog.ftl
> +uplink-cameraBug-desc = A portable device that allows you to view the station's cameras
```suggestion
uplink-cameraBug-desc = A portable device that allows you to view the station's cameras.
```

2024-09-30 02:26 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/camera_bug.yml
> +  description: personal camera viewing device
Can you give it a proper item description for the examine window?
For example `An illegal syndicate device that allows you to hack into the station's camera network.`

2024-09-30 13:23 UTC, pofitlo-Git commented
> I tried it out myself and it seems like SurveillanceCameraMonitorBoundUserInterface causes some problems when combined with a power cell. I guess we can include it as it is for now and adjust the balance later if necessary. Could you fix the merge conflict and address two minor nitpicks? Should be good to merge then.

I think that It's done

2024-09-30 13:54 UTC, Boaz1111 commented
@slarticodefast shouldn't this also have the name be lowercase? not entirely sure, so I won't leave a review

2024-09-30 14:08 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/camera_bug.yml
> +  name: Camera bug
```suggestion
  name: camera bug
```

2024-09-30 22:12 UTC, slarticodefast commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 3
```suggestion
    Telecrystal: 4
```

2024-09-30 22:13 UTC, slarticodefast approved these changes

2024-09-30 22:14 UTC, slarticodefast commented
I asked the other maintainers and we decided to increase the price to 4TC since it does not need a power cell now. I adjusted that number for you and will merge as soon as the tests are done. Thank you for your contribution!

2024-09-30 22:24 UTC, merged

2024-10-02 11:15 UTC, deltanedas commented
tc shouldnt be relevant to powercells since you can get them all over maints and in many vendors + make microreactors anyway