Update vending_machines.yml
space-wizards/space-station-14 pull request #30277
Opened 2024-07-23 14:23 UTC by justdie12

## About the PR

## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-07-23 14:24 UTC, justdie12 commented
#19088 solved

2024-07-23 14:41 UTC, lzk228 commented
please name your PR correctly, you can write short about changes and then describe them fully in pr description
also you can type `resolve #19088` and the issue will be autoclosed if this pr get merged

2024-07-23 14:50 UTC, justdie12 commented
> please name your PR correctly, you can write short about changes and then describe them fully in pr description also you can type `resolve #19088` and the issue will be autoclosed if this pr get merged

srry dont know

2024-07-23 14:51 UTC, justdie12 commented
resolve #19088

2024-07-23 14:57 UTC, lzk228 commented
> resolve #19088

i meant you should write it in your pr description

2024-07-23 15:02 UTC, VasilisThePikachu requested changes
Please explain why this pr is good for the game and add a changelog

2024-08-26 15:11 UTC, UbaserB requested changes

2024-08-26 15:11 UTC, UbaserB commented on Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
> -    ejectDelay: 0.6
Please change it to 1.9 instead of removing it

2024-09-30 02:50 UTC, slarticodefast commented
A 2 second delay for the nanomed would feel very frustrating if you need several items. We had a maintainer discussion about this and would you request you to instead reduce the delays of other vending machines to be more consistent. Keep in mind the long vending sound for machines like the coffe vendor, so they don't overlap.

2024-09-30 05:05 UTC, UbaserB commented on Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
> -    ejectDelay: 0.6
scratch this lol

2024-10-13 05:13 UTC, UbaserB commented
You coming back to this?

2024-10-28 00:18 UTC, closed without merging