Microvawe  Recepies  and Egg interaction´s Fix
space-wizards/space-station-14 pull request #30294
Opened 2024-07-23 21:06 UTC by Katzenminer

## About the PR
I  have  changed almost all Recepies That used only  Solid Eggs as in `FoodEgg` to now accept the Reagent `Egg`, making it possible to use either whole eggs,  or raw egg  in a  container. I have also the addresed the issue that Came with it that Whole Eggs in the brownie Recepie always  survive the cooking  effectivly cloning them.

## Why / Balance
It is very inconvinent for chef´s wehn cooking to be forced to use a  whole  a egg,  and also it makes no sense to  force  them to in many recepies. 
This Commit came to be regarding the  issue:#30259

## Technical details
I Have Added Two  Foreach loops to the  `SubtractContents `Methode inside MircowaveSystems.cs. The first  foreach loop check for Containers  that have the type Food and if they are empty, If that is the case they get added to a Stack Called `entsToRemove `. 
The  second foreach loop removes  each item in the Stack.

## Media
This media  below  is me  going through every  recepie making sure it doesnt duplicate the eggs.

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/user-attachments/assets/7b9fec00-047e-4945-b678-5a0a3f177159

**Changelog**
:cl:
- add: Added a Recepie for Boiled Egg.
- remove: Removed Eggs being Cooked as A Chemical Reaction by Heat.
- tweak: Changed All Recepies Except:Burgers and Boiled Eggs  to  now use Raw egg, so a whole egg or  a cracked Egg into a beaker works.
- fix: Fixed Eggs Not  disapearing after Microwaving with them sometimes.

2024-07-23 21:54 UTC, beck-thompson commented
LETS GOOOOOOO! Good job on the PR 🫡

2024-07-23 22:22 UTC, Katzenminer commented
Egghell  is real.🫠

2024-07-24 06:20 UTC, IProduceWidgets commented
> This Commit came to be regarding the issue:https://github.com/space-wizards/space-station-14/issues/30259

if you add this line to your PR description it will automatically close the issue when your PR is merged.
> fixes #30259

2024-09-02 16:10 UTC, beck-thompson commented
Merge conflict hell

2024-09-03 16:16 UTC, Plykiya requested changes
the code itself is simple and fine, there's just formatting issues and some unexplained things

2024-09-03 16:16 UTC, Plykiya commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +                    continue;
please add a newline after the continue

2024-09-03 16:16 UTC, Plykiya commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +                    continue;
newline after the continue

2024-09-03 16:16 UTC, Plykiya commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +                }
newline after the foreach

2024-09-03 16:16 UTC, Plykiya commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +                    continue;
newline after the continue

2024-09-03 16:16 UTC, Plykiya commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +
unnecessary blank lines

2024-09-03 16:16 UTC, Plykiya commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +                        continue;
newline after the continue

2024-09-03 16:16 UTC, Plykiya commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +                if (TryComp<FoodComponent>(entToRemove, out var foodComp))
newline before and after the if statement

2024-09-03 16:16 UTC, Plykiya commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +        private void Spawn(List<EntProtoId> trash, EntityCoordinates coordinates)
what's the point of this spawn function? there's no comment on it

2024-12-04 10:49 UTC, Katzenminer commented
Accidentaly removed the branch whilst cleaning up others.

2025-02-24 12:29 UTC, slarticodefast requested changes

2025-02-24 12:29 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Construction/Graphs/food/egg.yml
> -    entity: FoodEggBoiled
In the changelog you say that you added a recipe for boiled egg, but I don't see that anywhere, only the construction graph step here has been removed, which means `FoodEggBoiled` is now unobtainable.
Also it is now a little weird because eggs now directly explode when heated up without the boiled step in between.

2025-02-24 12:29 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Consumable/Food/egg.yml
> +  #   node: boiled
Don't comment this out,if it is not needed anymore delete it.
But like mentioned in the other comment, `FoodEggBoiled` are now only obtainable by directly spawning them, and they are no longer part of the construction graph at all, meaning they cannot explode either, whereas unboiled eggs can.

2025-02-24 12:29 UTC, slarticodefast commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
>          }
What is this for?

2025-02-24 12:29 UTC, slarticodefast commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +            foreach (var item in component.Storage.ContainedEntities)
This whole extra loop feels a little jank. Some thoughts:
- It can probably be combined with the first loop instead of iterating a second time. The current solution just adds to the existing spaghetti code.
- Is a Stack better than a list here? Not sure what is better for performance, but we don't need the LIFO property here since we only loop over it. You don't even need to modify the Stack in each step with `Pop()`, you can just use a foreach loop.
- Tying it to foodComponent is kinda hardcoding the solution to food items, but not other containers. Maybe a whole different approach would be better, where any closed container (like eggs, but also bottles, other food items etc) would not be allowed to add reagents to the recipe. It would make sense that you have to break the eggs first before using them in a recipe. That way you can also keep the boiled egg construction graph, because that only affects whole eggs.

2025-02-24 17:37 UTC, closed without merging

2025-02-24 17:37 UTC, Katzenminer commented
Fixed by #35459, thank you @slarticodefast for you help and elegantly resolving the issue.