Allow ai to understand if its handcuffed.
space-wizards/space-station-14 pull request #30402
Opened 2024-07-27 06:47 UTC by IProduceWidgets

maybe useful at #30066
partially fixes #27460
partially fixes #28006

## About the PR

Allows Ai to understand if its handcuffed by checking this precondition.

@osjarw useful?

## Why / Balance

Can be used to avoid ai constantly trying to do stuff it cant do because of handcuffs, when it should instead do something else, such as run away.

## Technical details

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl

2024-07-27 06:59 UTC, IProduceWidgets commented
dufuq are these test fails

2024-07-27 07:19 UTC, IProduceWidgets commented
What are these flake ass tests even...

2024-07-28 04:09 UTC, metalgearsloth requested changes

2024-07-28 04:09 UTC, metalgearsloth commented on Content.Shared/Cuffs/SharedCuffableSystem.cs
> +
```suggestion

            if (requireFullyCuffed && hands.Count > cuffable.CuffedHandCount)
                return false;

```

2024-07-28 04:09 UTC, metalgearsloth commented on Content.Shared/Cuffs/SharedCuffableSystem.cs
> +        {
Doc summary please, also Entity<CuffableComponent>

2024-08-02 07:07 UTC, metalgearsloth approved these changes

2024-08-02 07:07 UTC, merged