Meteors now leave behind a bit of ore
space-wizards/space-station-14 pull request #30419
Opened 2024-07-28 00:13 UTC by Plykiya

## About the PR

Made meteors leave behind ore after the explosion

## Why / Balance

idk, an admin told me to do it

## Technical details

- Created WeightedSpawnEntityBehavior that takes a WeightedRandomEntityPrototype and spawns a number of entities between a min and max, at a random offset from the final position of the entity.
- Spawning can be delayed if, for example, the entity has an explosive behavior that would destroy your newly spawned entity. If this happens, a temporary entity is created to act as a spawner.
- Created a spawn table of possible asteroid ores that the meteors will now leave behind
- Arbitrarily chose values that seemed appropriate for the size of the meteors

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**KABOOM**
https://www.youtube.com/watch?v=tgqEwkIMV7o

## Breaking changes

**Changelog**

:cl:
- add: Meteors now leave behind asteroid rocks on impact.

2024-07-28 05:25 UTC, UbaserB commented
This is actually very cool, woah..

2024-07-28 05:38 UTC, beck-thompson commented
Maybe salvage will finally stay on station!

2024-07-31 08:12 UTC, metalgearsloth requested changes

2024-07-31 08:12 UTC, metalgearsloth commented on Content.Server/Destructible/Thresholds/Behaviors/WeightedSpawnEntityBehavior.cs
> +    public string WeightedSpawn = string.Empty;
Please use the new standards for this i.e. ProtoId

2024-07-31 08:12 UTC, metalgearsloth commented on Content.Server/Destructible/Thresholds/Behaviors/WeightedSpawnEntityBehavior.cs
> +public sealed partial class WeightedSpawnEntityBehavior : IThresholdBehavior
Needs documenting.

2024-07-31 08:12 UTC, metalgearsloth commented on Content.Server/Destructible/Thresholds/Behaviors/WeightedSpawnEntityBehavior.cs
> +                var spawner = system.EntityManager.SpawnEntity("TemporaryEntityForTimedDespawnSpawners", position.Offset(GetRandomVector()));
Please use ProtoId so this doesn't cause runtime exceptions and gets validated by CI.

2024-07-31 21:56 UTC, Plykiya commented
TryStopNukeOpsFromConstantlyFailing my NEMESIS

2024-08-01 02:55 UTC, merged