Pipe visualizers
space-wizards/space-station-14 pull request #3042
Opened 2021-01-27 06:12 UTC by collinlunn

Pipes now look disconnected, then connect when pipes are placed that connect to them. The base pipe sprite looks disconnected, then PipeConnectorVisualizer layers over a small sprite that covers up the disconnected part of the pipe.

Also, you can set a PipeNode to an arbitrary PipeDirection and the sprite will update correctly.

2021-02-04 09:25 UTC, metalgearsloth requested changes
Maybe something for next pr but some stuff (e.g. vents and scrubbers) are triggering EnsureComponentWarn for PipeNetDeviceComponent.

2021-02-04 09:25 UTC, metalgearsloth commented on Content.Client/GameObjects/Components/Atmos/Piping/PipeVisualizer.cs
> +                }
Same here.

2021-02-05 18:34 UTC, collinlunn commented on Content.Client/GameObjects/Components/Atmos/Piping/PipeConnectorVisualizer.cs
> +                }
The specific exception, `FileNotFoundException`, seems to violate the sandbox. Not sure how to handle that.

2021-02-09 07:05 UTC, metalgearsloth commented on Content.Client/GameObjects/Components/Atmos/Piping/PipeConnectorVisualizer.cs
> +                }
Does TryGetResource instead?

2021-02-23 02:18 UTC, metalgearsloth approved these changes

2021-02-23 02:18 UTC, merged