Allow for respawn verb to be used on offline players. Also minor  rewrite on respawn command
space-wizards/space-station-14 pull request #30433
Opened 2024-07-29 00:21 UTC by nikthechampiongr

## About the PR

This command makes the respawn verb to be used on disconnected players.

Also localizes the respawn command and allows for it to accept userids.

## Why / Balance

admin qol

## Technical details

respawn command rewritten so that it can accept userids, was localized, and now uses [Dependency] where possible.

respawn verb is now available on disconnected players.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:

ADMIN:

- fix: Respawn verb is now available on players even after they are disconnected.
- tweak: Respawn command now also accepts user ids

2024-07-29 12:19 UTC, nikthechampiongr commented
I am expanding the scope of this pr to most verbs as most of them appear to be actually possible without an actor component. Long live CE.

2024-07-29 13:13 UTC, nikthechampiongr commented
Currently proceeding with just erase and respawn not needing an actor component as they are the only ones which are possible and make sense.

2024-07-29 13:15 UTC, nikthechampiongr commented
nevermind one moment

2024-07-30 02:12 UTC, metalgearsloth requested changes

2024-07-30 02:12 UTC, metalgearsloth commented on Content.Server/Administration/Commands/EraseCommand.cs
> +            shell.WriteLine(Loc.GetString("cmd-erase-player-not-found"));
```suggestion
        {
            shell.WriteError(Loc.GetString("cmd-erase-player-not-found"));
```

2024-07-30 02:12 UTC, metalgearsloth commented on Content.Server/Administration/Commands/EraseCommand.cs
> +        }
Pretty sure pjb added a thing to inject these in some engine PR.

2024-07-30 02:12 UTC, metalgearsloth commented on Content.Server/Administration/Commands/EraseCommand.cs
> +        return CompletionResult.FromHintOptions(options, "<PlayerIndex>");
Localise maybe?

2024-07-30 02:12 UTC, metalgearsloth commented on Content.Server/GameTicking/Commands/RespawnCommand.cs
> +
As above.

2024-07-30 02:12 UTC, metalgearsloth commented on Content.Server/GameTicking/Commands/RespawnCommand.cs
WriteErrors in here too just can't highlight it all coz github things.

2024-08-31 11:38 UTC, metalgearsloth approved these changes

2024-08-31 11:38 UTC, merged