Random hunger at roundstart is now controlled by adjustable amounts.
space-wizards/space-station-14 pull request #30481
Opened 2024-07-30 04:23 UTC by Blackern5000

## About the PR
The random hungerComponent and thirstComponent in newly spawned entities is now controlled by two adjustable numbers separate from the hunger thresholds, and can be made to be a specific number instead.

## Why / Balance
Some mobs, such as mice, already use this functionality, however it has been nonfunctional. It also seems helpful for in the future if say, someone wanted to make rat king have a specific variation for it's starting hunger, or something similar.
![image](https://github.com/user-attachments/assets/d91ade7b-ed33-49ad-b703-027253260ea3)
The mouse hungerComponent uses currentHunger, which was not able to be set manually with the previous version

## Technical details
hungerComponent and thirstComponent now have two new variables which act as the minimum and maximum for random hunger. These numbers default to 110 min/150 max and 310 min/449 max for hunger and thirst respectively, and can be specified in the prototype or modified before mapinit. If a prototype has a specified currentHunger equal to or above 0 (defaults to -1 to allow this), it will entirely skip the random hunger variation and just use that number instead.

## Media
![image](https://github.com/user-attachments/assets/a221e09a-3413-4d8c-9ec7-cca88c4d9205)

![image](https://github.com/user-attachments/assets/0b7909ae-66ec-4508-9a1c-cec468ac67e9)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Some entities may have extremely high or extremely low starting hunger with the default variation, cockroaches come to mind, but I think they're parented to mice so I'm not sure.

**Changelog**
I don't think this needs a changelog

2024-07-30 04:53 UTC, EmoGarbage404 requested changes

2024-07-30 04:53 UTC, EmoGarbage404 commented on Content.Shared/Nutrition/Components/HungerComponent.cs
> +    [DataField("hungerMin"), ViewVariables(VVAccess.ReadWrite)]
```suggestion
    [DataField]
```
do this for all datafields

2024-07-30 04:53 UTC, EmoGarbage404 commented on Content.Shared/Nutrition/EntitySystems/ThirstSystem.cs
>          }
this really should use the thresholds or else any modification to them is going to require also updating these values for parity.

2024-07-30 04:53 UTC, EmoGarbage404 commented on Content.Shared/Nutrition/Components/ThirstComponent.cs
> +    /// </summary>
for both of these, you need to copy the comment and use "min" or "max" when applicable. summary comments are per-variable and dont make sense when written like this.

2024-08-01 04:44 UTC, ps3moira commented
somewhat out of this scope but would this be applicable to all crew who join the server/spawn in having random chances of hunger levels?

2024-12-19 06:23 UTC, closed without merging