Add keybinds for rotating and flipping objects
space-wizards/space-station-14 pull request #30540
Opened 2024-08-01 00:39 UTC by slarticodefast

## About the PR
Adds keybinds for rotating and flipping objects. Previously this was only accessible via the context menu.

## Why / Balance
It was really frustrating to use and took way too much time if you were moving atmos devices.

## Technical details
Works exactly the same as with the verbs.
I also fixed a few bugs:
- the flip verb no longer shows up when out of range
- the popups for anchored rotatable entities are actually used now

## Media
![Screenshot (215)](https://github.com/user-attachments/assets/32710985-f8e9-4527-9393-b4e5a8f46528)

(video is a little laggy because I did this on my notebook)

https://github.com/user-attachments/assets/9b9b71fe-81aa-430f-b7b6-d24cf12dcf78

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
none

**Changelog**
:cl:
- add: Added new keybindings for rotating and flipping objects. The defaults are R for clockwise, Shift+R for counterclockwise and F for flipping.

2024-08-08 03:15 UTC, metalgearsloth requested changes
I know the old code isn't predicted but at least make the new code predicted plz.

2024-08-08 08:27 UTC, slarticodefast commented
> make the new code predicted plz

For rotating this should be possible, but flipping deletes and spawns a new entity. I thought we cannot predict that? Maybe I can find a way to reuse the old one. Also I should probably add a small cooldown to both.

2024-08-13 13:36 UTC, metalgearsloth commented
> > make the new code predicted plz
> 
> For rotating this should be possible, but flipping deletes and spawns a new entity. I thought we cannot predict that? Maybe I can find a way to reuse the old one. Also I should probably add a small cooldown to both.

guess it's fine for now.

2024-08-13 13:36 UTC, metalgearsloth approved these changes

2024-08-13 13:36 UTC, merged