Adds energy bola
space-wizards/space-station-14 pull request #30576
Opened 2024-08-02 16:05 UTC by SpeltIncorrectyl

## About the PR
Energy bola is a tool available to security. It is like a normal bola except it disintegrates when removed, sort of like zipties.

## Why / Balance
The energy bola has identical stats to the normal bola, except it takes up half the inventory space (2 slots vs 4 slots of the bola) and is single use.
There are 2 energy bolas in every security officer locker, 2 in each in HoS locker and Warden locker, 8 in the sectech, and they can be manufactured at the secfab for 3 plastic each.

## Technical details
Added new property to EnsaringCompnent, DestroyOnRemove. When something with this set to true is removed from the victim, it is deleted instead of being placed into someone's hand.

## Media

https://github.com/user-attachments/assets/428a9487-372b-41e0-8cfd-2e25e72616dd

## Requirements

- [ X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
* Potential breaking change, new property DestroyOnRemove added to EnsnaringComponent, defaults to false which performs original behaviour.

**Changelog**
:cl:
- add: Added energy bolas to the security department's arsenal. They are half the size and are single use.

2024-08-09 02:42 UTC, slarticodefast requested changes
Very minor cleanup needed, but looks good to me code-wise. From a balancing perspective I will put it up for discussion with the other maintainers.

2024-08-09 02:42 UTC, slarticodefast commented on Content.Shared/Ensnaring/Components/EnsnaringComponent.cs
> +    [DataField]
```suggestion
    [DataField]
```
ReadWrite is the default now, so you don't need this attribute. You can also remove it from the other datafields above. Change them to `[DataField]` as well. The name gets autoconverted to camelCase, but old files still do this manually. And add a summary to your new datafield.

2024-08-09 10:44 UTC, slarticodefast approved these changes

2024-08-09 18:19 UTC, whateverusername0 commented
i love ebola, merge now

2024-08-11 19:08 UTC, SpeltIncorrectyl commented
guh
another merge conflict!?

2024-08-13 12:49 UTC, slarticodefast commented
I had a balance discussion with the other maintainers. Conceptually this addition has our approval, but we think in in its current form it might be a very powerful weapon, in particular due to the self-deletion. We would ask you to make the following adjustments:
- Make its size 2x2, the same as the normal bola.
- Make it unlockable by science research instead of it being available for mass production at round start.
- Remove the energy bolas from the lockers so that its round start availability is reduced. Keeping a few in the sec vend is fine.
- Reduce the breakoutTime to something like 1-2 seconds (and adjust the freeTime accordingly).
- Add comments in the yml code stating that it is balanced around its self deleting ability and low availability (so future balance PRs will know our reasoning on that).

2024-08-13 16:29 UTC, SpeltIncorrectyl commented
> I had a balance discussion with the other maintainers. Conceptually this addition has our approval, but we think in in its current form it might be a very powerful weapon, in particular due to the self-deletion. We would ask you to make the following adjustments:
> 
>     * Make its size 2x2, the same as the normal bola.
> 
>     * Make it unlockable by science research instead of it being available for mass production at round start.
> 
>     * Remove the energy bolas from the lockers so that its round start availability is reduced. Keeping a few in the sec vend is fine.
> 
>     * Reduce the breakoutTime to something like 1-2 seconds (and adjust the freeTime accordingly).
> 
>     * Add comments in the yml code stating that it is balanced around its self deleting ability and low availability (so future balance PRs will know our reasoning on that).

If it just didn't have self-deletion could it keep its size and availability?

2024-08-13 16:33 UTC, UbaserB commented
that'd pretty much be normal bolas at that point lol

2024-08-13 16:37 UTC, slarticodefast commented
> that'd pretty much be normal bolas at that point lol

Yeah, this pretty much. There was no opposition to sec having bolas in general though.

2024-08-13 16:45 UTC, SpeltIncorrectyl commented
> > that'd pretty much be normal bolas at that point lol
> 
> Yeah, this pretty much. There was no opposition to sec having bolas in general though.

Could energy bola be a smaller cheaper bola for sec?

2024-08-14 21:29 UTC, SpeltIncorrectyl commented
I've done the changes that Keron said to in design-discussion on the discord.
* 2x2 size in inventory to match normal bola
* 5000 point tier 1 arsenal research to make them in the secfab
* no self deletion

2024-08-14 22:17 UTC, slarticodefast requested changes

2024-08-14 22:17 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Weapons/Throwable/bola.yml
> +    size: Normal
```suggestion
```
This part is not needed since it is inherited from BaseBola

2024-08-17 13:06 UTC, chavonadelal commented
I think you shouldn't separate this out as a separate technology. You should put it in the technology special means or counteraction to riots (I think that's what it's called). Otherwise it's very cool!

2024-08-17 13:10 UTC, chavonadelal requested changes
I think you shouldn't separate this out as a separate technology. You should put it in the technology special means or counteraction to riots (I think that's what it's called). Otherwise it's very cool!

2024-08-20 16:39 UTC, slarticodefast commented
Hey, we had a discussion and vote among the maintainers on if and how the energy bola should be merged. The poll options and results were:
- Merge as it is, the same as the normal bola, but with heat damage (1)
- Change it to be self-deleting again, then merge (3)
- Give it an alternative ability, different from self-deletion (0)
- Close the PR (1)

Since the required 75% approval was not reached, the next step according to the [maintainer policy](https://docs.spacestation14.com/en/staff/maintainer-policy.html) will be further discussion about possible adjustments before a second poll can be made. If you have any suggestions for this, feel free to tell us either here or in the #design-discussion channel on Discord. The main points made in the previous discussion were the following:
- The energy bola should have different stats/properties than the normal bola, enough to warrant it being its own item
- The self-deletion property was extremely powerful in SS13, raising concerns for our combat balance.
- In all cases the round start availability should be greatly reduced. With two in each locker and 8 in the sec vend on a map like Marathon you would have 28 in total. That is way more than you would ever need and makes the research and printing completely unnecessary. I would suggest only keeping a few in the sec vend.
- The inventory size should be the same as the normal bola, since you should not be able to carry dozens of it with you.
- The energy bola should not be its own research, but be part of an existing tech, for example riot control.
- One maintainer voiced concerns about the item sprite, but did not take part in the poll.

2024-09-07 20:13 UTC, SpeltIncorrectyl commented
Is this pr still under review?

2024-09-07 20:27 UTC, Plykiya commented
> Is this pr still under review?

the wall of text you received was your review, make the changes they asked for and it'll be aporoved

2024-09-07 22:18 UTC, slarticodefast commented
> the wall of text you received in the previous message was your review, make the changes they asked for and it'll be re-reviewed

Yeah, this. When some adjustments are made we can do a second poll among maintainers, but we are currently unsure ourselves about how to best balance this item while keeping it unique. Suggestions are welcome.

2024-09-14 18:00 UTC, closed without merging

2024-09-14 18:01 UTC, SpeltIncorrectyl commented
I didn't know how to make it a unique item without self-deletion or a different size.