New head of security weapon:Energy Shotgun
space-wizards/space-station-14 pull request #30643
Opened 2024-08-04 13:22 UTC by Boaz1111

## About the PR

I added an experimental energy shotgun with three fire modes:
Wide fire(lethal)
Narrow fire(lethal)
Disabler(non lethal)

## Why / Balance

Was speaking with flare about this, the HoS really needed a unique weapon instead of a bland SMG that can be obtained in other ways. This will hopefully cause more playstyle variety for HoS. The weapon is also high risk, and a steal objective for syndies. My original idea was to add the X-01 from SS13, but flare showed me this shotgun and I instantly loved it. 
## Technical details

## Media

https://github.com/space-wizards/space-station-14/assets/149967078/16865e2d-72fa-4177-9eab-0300981c4f09

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: The HoS has been given a new experimental weapon:An energy shotgun with multiple fire modes. This experimental tech is highly wanted by the syndicate, and agents will try to steal it.
- remove: Removed the Head of Security's Emergency Orders

2024-08-04 14:44 UTC, Brandon-Huu commented
Put the emergency code change into a separate PR.

2024-08-04 14:44 UTC, Hanzdegloker commented
Love the idea and versatility aspect but I am unsure if it will be very useful against nukies vs just grabbin like a rifle or shotgun due to the lack of reloading capabilities for prolonged encounters. Against traitors and general HoS duties seems fine and fit though. Hell zombies better watch out.

2024-08-04 14:46 UTC, Boaz1111 commented
> Put the emergency code change into a separate PR.

Emo explicitly told me to put it in the same PR.
![image](https://github.com/user-attachments/assets/23f1d44f-610a-4168-8fd1-2c99dccc1068)

2024-08-04 14:46 UTC, Boaz1111 commented
> Love the idea and versatility aspect but I am unsure if it will be very useful against nukies vs just grabbin like a rifle or shotgun due to the lack of reloading capabilities for prolonged encounters. Against traitors and general HoS duties seems fine and fit though. Hell zombies better watch out.

We'll see as time goes on I suppose.

2024-08-04 14:47 UTC, Brandon-Huu commented
> > Put the emergency code change into a separate PR.
> 
> Emo explicitly told me to put it in the same PR. ![image](https://private-user-images.githubusercontent.com/149967078/354909506-23f1d44f-610a-4168-8fd1-2c99dccc1068.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3ODMwNzMsIm5iZiI6MTcyMjc4Mjc3MywicGF0aCI6Ii8xNDk5NjcwNzgvMzU0OTA5NTA2LTIzZjFkNDRmLTYxMGEtNDE2OC04ZmQxLTJjOTlkY2NjMTA2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxNDQ2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGIyMGM3MmM4ZjYzNjBmMGI4N2RlOTIyYzE5MTIzOWM3MTcxN2E1NzU2MzJhMDc4MjM5ZmU2MDM2NGM1ZDg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ltOdwEWXpPW58n6HEqqmV2tpUTdq-32hLDq6JfN9y_4)

Emo hasn't read the pull request guidelines? 🤨

2024-08-04 15:49 UTC, PrivateJoe09 commented
> Well for Traitors, the shotgun and majority of HoS's weapons will get disabled with one EMP use.... that leaves him with his knife and mk, which in most cases will not be enough to kill someone.

Adding that if it has to be wielded means no riot shields, which is a significant drawback. One of the strengths of the WT is its reliability, unlike an EMPable shotgun. I would really like to keep the WT; otherwise, it’s hard to see this as a security buff. It's similar to how the HoS from TG has both the X-01 and the Compact Shotgun.

2024-08-04 15:54 UTC, Brandon-Huu commented
> > Well for Traitors, the shotgun and majority of HoS's weapons will get disabled with one EMP use.... that leaves him with his knife and mk, which in most cases will not be enough to kill someone.
> 
> Adding that if it has to be wielded means no riot shields, which is a significant drawback. One of the strengths of the WT is its reliability, unlike an EMPable shotgun. I would really like to keep the WT; otherwise, it’s hard to see this as a security buff. It's similar to how the HoS from TG has both the X-01 and the Compact Shotgun.

Where in the PR does it say the WT was removed?

2024-08-04 16:02 UTC, Boaz1111 commented
> > > Well for Traitors, the shotgun and majority of HoS's weapons will get disabled with one EMP use.... that leaves him with his knife and mk, which in most cases will not be enough to kill someone.
> > 
> > 
> > Adding that if it has to be wielded means no riot shields, which is a significant drawback. One of the strengths of the WT is its reliability, unlike an EMPable shotgun. I would really like to keep the WT; otherwise, it’s hard to see this as a security buff. It's similar to how the HoS from TG has both the X-01 and the Compact Shotgun.
> 
> Where in the PR does it say the WT was removed?

it will be from his office

2024-08-04 16:11 UTC, NakataRin commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  description: An one of a kind prototype energy weapon using various shotgun configurations. The possibility for both lethal, and non-lethal shots makes this a versatile weapon.
Some flavor text changes I'd like to offer:

I think that looks better

```suggestion
  description: A one-of-a-kind prototype energy weapon that uses various shotgun configurations. It offers the possibility of both lethal and non-lethal shots, making it a versatile weapon.
```
This version is closer to yours, just fixes some typos here and there
```suggestion
  description: A one-of-a-kind prototype energy weapon that uses various shotgun configurations. The possibility of both lethal and non-lethal shots makes it a versatile weapon.
```

2024-08-04 16:24 UTC, Boaz1111 commented
appreciated.

2024-08-04 22:21 UTC, Cojoke-dot commented
> Well for Traitors, the shotgun and majority of HoS's weapons will get disabled with one EMP use.... that leaves him with his knife and mk, which in most cases will not be enough to kill someone.

I mean... that's what happens with every other secoff right? All you gotta do is dodge the emp, ez

2024-08-04 22:36 UTC, Reese1243 commented
> > Well for Traitors, the shotgun and majority of HoS's weapons will get disabled with one EMP use.... that leaves him with his knife and mk, which in most cases will not be enough to kill someone.
> 
> I mean... that's what happens with every other secoff right? All you gotta do is dodge the emp, ez

I was gonna mention this. it is the same situation if either a secoff or HoS gets EMP'd. both lose their stuns and both would have to rely on the pistol, knife, or seclite (depending on the situation of course but this is assuming they didnt get stuff from the armory)

2024-08-04 23:09 UTC, Cojoke-dot commented
Uh... It's 5 shots in the shotgun till you need to reload right? It takes 7 shots consecutively of the disabler smg bolts to take someone out, so uh... 3 hits with with 2-3 pellets on each shot. I don't see much reason to use this over a normal disabler or a stun baton.
- baton, 20 charged, 3 to stun (~ 6.66 stuns), melee range
- disabler, 10 charges, 4 to stun (~ 2.5 stuns)
- disabler smg, 25 charges, 7 to stun (~3.5 stuns)
- shotgun, 5 charges (shared with your lethal mode), 3 to stun ( 1.9 stuns with all triple hits)

Maybe 20 stam per non-lethals shot? Instead of a 2-2-3, you can hit a 2-3 or a 2-2-1? It should be better than other sec gear options correct? It knocks the shotgun up to a 2.6 stun possible and gives it much more flexibility. It gives it some kind of advantage over the other options HoS has for disabling people.

Uh... for the lethal maybe put one more bullet in the wide shot? Hitting all your shots from a regular lethal round deal 60 🤷‍♂️

Finally... GUAH!!! YOU CAN'T PUT IT IN YOUR BACK SLOT!!! 😞

2024-08-04 23:18 UTC, Boaz1111 commented
> Finally... GUAH!!! YOU CAN'T PUT IT IN YOUR BACK SLOT!!! 😞 

You literally can though? Have you tested it?

2024-08-04 23:21 UTC, Cojoke-dot commented
> > Finally... GUAH!!! YOU CAN'T PUT IT IN YOUR BACK SLOT!!! 😞
> 
> You literally can though? Have you tested it?

oh... lol, I had the disabler yml pulled up on my screen when I was writing that, got a little mixed up

2024-08-04 23:38 UTC, Doc-Michael commented
Is it just me or do the five shots seem very low, especially for a Special head item, Krammer has 4, Enforcer has 7 and they are easily reloadable, wouldn't 8 or 10 that it originally had be better? missing your shots will be heavly punishing due to the low capacity, where fighting two people requires you to hit all your shots with majority if not all the bolts. In nukies like a previous comment stated its not a practical gun,  and even in traitors im starting to question its practical use being underepowered where a krammer can output more damage than the Energy Shotgun, and if its not practical to use, what stops a HoS from leaving it in armoury in favour of other weapons in the safes?

2024-08-04 23:40 UTC, PrivateJoe09 commented
> Is it just me or do the five shots seem very low, especially for a Special head item, Krammer has 4, Enforcer has 7 and they are easily reloadable, wouldn't 8 or 10 that it originally had be better? missing your shots will be heavly punishing due to the low capacity, where fighting two people requires you to hit all your shots with majority if not all the bolts. In nukies like a previous comment stated its not a practical gun, and even in traitors im starting to question its practical use being underepowered where a krammer can output more damage than the Energy Shotgun, and if its not practical to use, what stops a HoS from leaving it in armoury in favour of other weapons in the safes?

or just make it reload itself

2024-08-05 00:42 UTC, Boaz1111 commented
> Is it just me or do the five shots seem very low, especially for a Special head item, Krammer has 4, Enforcer has 7 and they are easily reloadable, wouldn't 8 or 10 that it originally had be better? missing your shots will be heavly punishing due to the low capacity, where fighting two people requires you to hit all your shots with majority if not all the bolts. In nukies like a previous comment stated its not a practical gun,  and even in traitors im starting to question its practical use being underepowered where a krammer can output more damage than the Energy Shotgun, and if its not practical to use, what stops a HoS from leaving it in armoury in favour of other weapons in the safes?

In traitors it's certainly not underpowered due to the prevalence of webvests

2024-08-05 20:13 UTC, Boaz1111 commented
Yeah I'll fix that

2024-08-05 20:31 UTC, keronshb commented
I still feel like this should go to the Warden and then either the Multiphase or the Big Iron should go to the HoS.

2024-08-05 22:51 UTC, Pumkin69 commented
i think it should auto recharge like caps laser pistol but be 2x5 so you have to have a duffel or backpack or carry it on your back. The current implementation is a hard nerf to HoS if you remove the wt550. However making it recharge would be good.

2024-08-08 00:05 UTC, EdenTheLiznerd commented
> i think it should auto recharge like caps laser pistol but be 2x5 so you have to have a duffel or backpack or carry it on your back. The current implementation is a hard nerf to HoS if you remove the wt550. However making it recharge would be good.

I'm not exactly comfortable with making satchels users suffer for using the cooler bag, Just make it take up an entire side of the satchel.

2024-08-08 11:05 UTC, Boaz1111 commented
> Many players who play as Security and a handful of HoS mains (rare find) believe that if the shotgun were to replace the WT, it would be a significant downgrade. I strongly oppose this change. The shotgun might be a "cool" weapon, but it's not better than a mere Kammer. At most, it can deal 50 heat damage from close range, totaling a disappointing 250 damage with a full magazine. Plus, you need to return to sec to recharge it, which is a hassle.
> 
> For comparison, the "bland SMG" can deal up to 480 piercing damage per magazine. You get three magazines, and it takes around 1.2 seconds to crit an unarmored human with only seven shots, leaving them bleeding as well.
> 
> Heat damage is also a joke. Incendiary bullets for the WT deals 14 heat and 2 blunt damage. Claiming the shotgun is good because it can deal with webvests limits its usefulness to "it can kill webvests, so it's good enough." However, it can't even crit an elite hardsuit, even with perfect hits from all five shots in a full magazine. You'll likely get EMPed before you can do that, making it situational. The WT can still crit a webvest with 21 shots, even if the web is their counter.
> 
> The only advantage the shotgun has over the WT is that it's a simple disabler. However, the disabler SMG already fulfills this role for traitors rounds. Additionally, no sane tot player would choose getting a webvest if they were tasked with obtaining the shotgun. Antagonists already have superior close-range weapons, like the hypopen, which can instantly send you to sleep, or the esword, which you are not winning against with a shotgun.
> 
> To sum it all up, I don't think this weapon is anywhere near capable of replacing the WT or being useful for a competent HoS player, even as a stun gun. Who would choose using a shot from a 5-ammo shotgun over a disabler? It’s outmatched by most guns in the armory. Either make it stronger or beg the mappers to keep the WT.

made it a 2x4, gave it 7 shots, gave it a recharge

2024-08-08 19:40 UTC, PrivateJoe09 commented
> made it a 2x4, gave it 7 shots, gave it a recharge

this is much better, thanks.

2024-08-08 23:47 UTC, keronshb requested changes
> I still feel like this should go to the Warden and then either the Multiphase or the Big Iron should go to the HoS.

Reiterating this. I'd still feel way more comfortable giving this to the Warden and then introducing the Big Iron & a nerfed Revolver for the HoS.

Big Iron is also known as the MWS-01 - https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14353

2024-08-09 04:23 UTC, Boaz1111 commented
Why's that?

2024-08-09 15:53 UTC, keronshb commented
> Why's that?

The Warden gets easier home defense with an Energy Shotgun or for riot control. Especially if they also get a ballistic shotgun.

MWS-01 is a better version of the Multiphase. Higher skill ceiling and more rewarding. Also easier transport due to item size.

2024-08-09 16:55 UTC, Doc-Michael commented
> > Why's that?
> 
> The Warden gets easier home defense with an Energy Shotgun or for riot control. Especially if they also get a ballistic shotgun.
> 
> MWS-01 is a better version of the Multiphase. Higher skill ceiling and more rewarding. Also easier transport due to item size.

I'd say that the Energy Shotgun is a much better option of us at its current standing, having original content is much better than copying over what other people already have, its a nice new concept which has potential, and its being balanced well enough where its not going to be over/underpowered, its larger size blocks it from being stored in a storage implanter thus providing a bigger challenge for any Syndicate agent trying to steal it.

Warden having a special items is probably outside of this PR's talking point and shouldn't be mentioned, there was a discussion on the Official Discord about which special HoS gun people preferred, and not once anyone mentioned the MWS-01, and don't get me wrong but the Big Iron seems like a balancing nightmare, as well as a coding one.

2024-08-09 19:39 UTC, keronshb commented
> I'd say that the Energy Shotgun is a much better option of us at its current standing, having original content is much better than copying over what other people already have,

This is irrelevant and it's nothing new. It exists in SS13 as either technology shells to put into regular shotguns or the Warden exclusive energy shotgun.

2024-08-10 09:32 UTC, Boaz1111 commented
Right, Keron, one more question, as far as like... balancing and stuff is concerned, what is the issue with giving this to the HoS? Leaving the Warden out of the scenario for now. Like, anything I could change?

2024-08-11 23:44 UTC, keronshb commented
> Right, Keron, one more question, as far as like... balancing and stuff is concerned, what is the issue with giving this to the HoS? Leaving the Warden out of the scenario for now. Like, anything I could change?

It's multiphase but shotgun. Having a regular shotgun that can swap between some lasers and disablers is extremely good to have in one package. These are better off to be delegated to technology shells, which it would require a different ammo type to fire these kind of projectiles.

In contrast, the Particle Defender (laser and disabler energy shotgun) was a "pump and use" weapon with a recharge rate.

2024-08-12 00:24 UTC, Boaz1111 commented
well, but like, what makes it:
Good for ward to have
Bad for HoS to have

2024-08-12 00:24 UTC, Boaz1111 commented
is it too good for the HoS?

2024-08-15 23:05 UTC, Pumkin69 commented
I'd rather the hos have the energy shotgun. Also this replaces the emergency orders which do literally nothing and give the HoS and actually interesting head item. I highly disagree with the sentiment of warden getting this instead.

2024-08-18 20:48 UTC, Boaz1111 commented
ALT DESIGN:
Cell Driven Energy Shotgun
Instead of an internal battery, this design proposes special power cells for the energy shotgun.
These power cells would hold 3-5 shots
Pros:
-More playstyle variance.
If the Head of Security wanted to focus on disabling hostiles instead of killing them, they could take more disabler cells.
-Certain about what mode is selected.
You know what cell you put in. Could also be adressed with visualisers.
-Higher skill ceiling.
This change would allow for more tactical play. See point 1.
-New unlocks for research.
In order to make the shotgun as customisable as a normal shotgun, it could be able to unlock more modes as sci researches things. Think a radiation mode, an incendiary mode, etc. 

Cons:
-Difficult to balance.
The cells are proposed to be 2x2, idea might change. If a head of security can carry many cells, they can be extremely versatile. Needs to be looked at if we go with this idea
-Harder to use. 
While higher skill ceiling might be an upside, this weapon could also be frustrating for newish heads of security. 

Overall I think it's a good idea, but needs maintainer discussion.

2024-08-18 20:49 UTC, Boaz1111 commented
To add on, the normal types would be converted into cells, the head of security would spawn with 2-3 of each, and they will be available to be made at the secfab.

2024-08-19 03:57 UTC, Emisse commented
seems fine to me fix goncflicts

2024-08-19 10:07 UTC, Boaz1111 commented
got it

2024-08-19 10:49 UTC, Boaz1111 commented
need to unscrungle this shit

2024-08-19 11:14 UTC, merged