split temperature protection into heating and cooling
space-wizards/space-station-14 pull request #30662
Opened 2024-08-05 03:12 UTC by EmoGarbage404

## About the PR

Allows temperature protection component to specify separate coefficients based on whether or not the player is warming up or cooling down.

adjusts some items (firesuits and winter clothing) to have more reasonable temperature protections for the different directions.

## Why / Balance

There's a lot of times where balancing insulation equally between heating and cooling has adverse effects. Especially for specialty temperature  protection (cold prot, heat prot) having the coefficient applied equally makes them incredibly strong and generally useful.

splitting it up like this lets us have more control over how we apply the modifiers and thus better balance firesuits and other items.

## Media

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Firesuits are now worse at keeping in heat and winter clothes make you get warmer quicker.

2024-08-11 23:01 UTC, slarticodefast requested changes
Ok, from a physics perspective the conductivity *should* always be the same in both directions. I tried thinking of ways this can be abused, but could not come up with anything. From a gameplay perspective this change is great.

2024-08-12 00:09 UTC, EmoGarbage404 commented
> Ok, from a physics perspective the conductivity should always be the same in both directions

i be hating on the laws of physics. they cramp my ephemeral style.

2024-08-12 00:15 UTC, EmoGarbage404 commented on Content.Server/Temperature/Components/TemperatureProtectionComponent.cs
> +    ///     How much to multiply temperature deltas by when cooling down
i dont really think it's worth having breaking changes there for something that really doesn't matter in the grand scheme of things. generally it's better not to unnecessarily rename classes and variables.

2024-08-12 01:06 UTC, slarticodefast commented on Content.Server/Temperature/Components/TemperatureProtectionComponent.cs
> +    ///     How much to multiply temperature deltas by when cooling down
They are both only used for this single thing, so it should be fine to rename them. Not really necessary, but makes it much more unsterstandable in my opinion

2024-08-12 01:09 UTC, slarticodefast approved these changes
The test fail is a heisentest, I had that one fail randomly a few times before.

2024-09-07 05:37 UTC, merged