fix(Creampies): Made it so identities are respected when creaming or being creamed
space-wizards/space-station-14 pull request #30684
Opened 2024-08-05 21:16 UTC by Brandon-Huu

## About the PR

Uuuh, Not sure. I made it so uuuhh. Identity is respected.

## Why / Balance

Resolves #18540
Resolves #30676

## Technical details

## Media

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-08-05 21:18 UTC, Brandon-Huu commented
Code kinda shit IMO

2024-08-05 21:18 UTC, Brandon-Huu commented
Might fix

2024-08-05 21:24 UTC, Brandon-Huu commented
https://github.com/space-wizards/space-station-14/blob/f7d8b4e7d469c03f4adab33307af4a44e44b0319/Content.Server/Flash/FlashSystem.cs#L139-L143

No idea if I'm supposed to use Identity() or not.

2024-08-06 14:50 UTC, EmoGarbage404 requested changes

2024-08-06 14:50 UTC, EmoGarbage404 commented on Content.Server/Nutrition/EntitySystems/CreamPieSystem.cs
> +            _popup.PopupEntity(Loc.GetString("cream-pied-component-on-hit-by-unknown-message-others", ("owner", args.Target)), uid, otherPlayers, false);
the "owner" param on this isn't passing in an identity.

2024-08-06 14:50 UTC, EmoGarbage404 commented on Resources/Locale/en-US/nutrition/components/cream-pied-component.ftl
> +cream-pied-component-on-hit-by-unkown-message =  You have been creamed!
"unkown"

2024-08-06 15:20 UTC, Brandon-Huu commented
Gyaat

2024-08-06 15:22 UTC, closed without merging

2024-08-06 15:24 UTC, Brandon-Huu commented
Mistakes where made