hallway screen nuke timer support, and recall bugfix refactor
space-wizards/space-station-14 pull request #30713
Opened 2024-08-06 21:31 UTC by graevy

redoing #29831 because I 4am-pushed an entire fork sync into the old one which requested review from every maintainer. also I didn't commit some signaltimersystem changes

## About the PR

Added nuke timer tracking to the hallway screens (fixes #25771).

Pretty sure this fixes #28644 in the refactor. I thought I squashed it in original testing but you know how it goes. It came up again in the nested timer case and I duct-taped a solution.

We had a brief [discussion](https://discord.com/channels/310555209753690112/310555209753690112/1259983505987862538) in the development chat about how to deal with confusion over the broadcast button, so I edited the text box default text to be a little more helpful, pictured below.

## Technical details

- All instances of `Shuttle Timer` or `TextScreenVisuals` etc have just been replaced with `Screen` to reflect the feature creep
- Rather than directly tweaking the screen text or color or timer etc. through the appearancesystem, I pass the entirety of an intended screen display as a `ScreenUpdate`. this greatly simplifies serverside logic, so there's ~60 fewer lines of code
- A screen stores `ScreenUpdate`s in a `SortedDictionary` of `ScreenPriority : ScreenUpdate`s. (`ScreenPriority` is a bytemask). The screen displays the highest priority update (if it exists).
- The clientside handling unwraps `ScreenUpdate` more easily than the batch edits, but there's still some cruft for a later PR:
    - I didn't bother adding a server -> client surface in `ScreenSystem` (still using `AppearanceSystem`) which still requires the server to delete timers by setting them to e.g. `TimeSpan.Zero`, and makes the clientside unpacking a little awkward.
    - I'm passing screen `NetEntity` maps to the client even though it doesn't use them

## Media

![dotnet_4v1G7McpaV](https://github.com/space-wizards/space-station-14/assets/51971268/f2d97878-ea18-43fe-81d6-9066af63058a)

![image](https://github.com/space-wizards/space-station-14/assets/51971268/b73bc672-59e2-429a-8028-fc9fc0c25c91)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: hallway screens now display the nuke countdown timer
- fix: recalling the shuttle should no longer display "ETA" without a timer

2024-08-06 21:56 UTC, graevy commented
guessing from discord that `TestGhostOnDelete` is pervasively failing. i'll push dummy commits later

2024-08-26 22:10 UTC, graevy commented
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

._.

2024-08-27 13:11 UTC, metalgearsloth requested changes

2024-08-27 13:11 UTC, metalgearsloth commented on Content.Shared/Screen/ScreenVisuals.cs
> +
You should make these explicit numbers.

2025-01-19 08:17 UTC, Emisse commented
needs to not change map files in this pr

2025-04-23 00:11 UTC, closed without merging

2025-04-23 00:11 UTC, MilonPL commented
I will be closing this PR as stale, if you ever come back to this, please open a new PR.