New Tins
space-wizards/space-station-14 pull request #30742
Opened 2024-08-07 15:31 UTC by kmr9000

## About the PR

Added 7 new tins, recipes for making them and empty tin can for cooking them in the microwave. After eating a canned food, the label must be removed from it, after which the jar can be reused to make other canned food. Empty jars are also added to dinnerware and recipe added to lath. See screenshot. 

**added tins:**
1. tinned tomatoes
2. tinned chanterelles
3. tinned pineapple
4. tinned corn
5. tinned chili
6. tinned condensed milk
7. tinned mice

## Why / Balance

It makes the chef gameplay more interesting. Since the recipe is not simple, it won't affect the balance.

## Media

![2024-08-07_00-01-13](https://github.com/user-attachments/assets/63e330a6-4259-4554-8ccd-3634f63d0887)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

Players can now find or create 7 new kinds of tins using empty tins from dinnerware. Empty tins can also be created in the lath.

:cl: mr_09
- add: 7 types of new tins: tinned tomatoes, tinned chanterelles, tinned pineapple, tinned corn, tinned chili, tinned condensed milk, and tinned mice.
- add: Empty tin used to cook tins.
- add: Recipes for cooking tins.
- add: Tins Loot Spawner.
- tweak: Empty tin recipe added to autolathe.
- tweak: Empty tin added to dinnerware.

2024-08-07 18:36 UTC, IProduceWidgets commented
The microwave recipe doesn't make much sense lmao.

2024-08-07 18:42 UTC, EmoGarbage404 commented
tinned mouse is diabolical i approve wholeheartedly

2024-08-07 18:48 UTC, lzk228 commented
about your CL, combine three first like in
`add: Added 7 types of new tins: tinned tomatoes, tinned chanterelles, tinned pineapple, tinned corn, tinned chili, tinned condensed milk, and tinned mice, which chef can make.`
tin spawner is not player-facing so can be removed, and two last can also be combined
`add: Empty tin added to Dinnerware and autolathe.`

2024-08-07 18:49 UTC, lzk228 commented
i also think the sprites could be combined in one rsi and use layering, but maintainers will decide this

2024-08-07 19:06 UTC, kmr9000 commented
> about your CL, combine three first like in `add: Added 7 types of new tins: tinned tomatoes, tinned chanterelles, tinned pineapple, tinned corn, tinned chili, tinned condensed milk, and tinned mice, which chef can make.` tin spawner is not player-facing so can be removed, and two last can also be combined `add: Empty tin added to Dinnerware and autolathe.`

Okay, thanks

2024-08-08 07:10 UTC, Hrosts commented
> tinned condensed milk

Sguschonka!

2024-08-08 22:32 UTC, saga3152 commented
> > tinned condensed milk
> 
> Sguschonka!

You should ve able to make varyenaya(boiled) sguschonka by microwaving it.

2024-08-11 09:19 UTC, UbaserB commented
test fail real, please fix

2024-08-11 09:31 UTC, UbaserB requested changes
The sprites need to have less strong contrast and dithering in regards to the shading.

2024-08-29 03:19 UTC, UbaserB commented
Are you coming back to this?

2024-08-29 03:59 UTC, Golinth commented
> tinned mice

speed merg immediately

2024-08-29 19:13 UTC, EthanQix commented
A couple mistakes I've noticed : 
- Description for empty tin is wrong
- Pineapple tin has the Vegetable tag instead of Fruit
- Condensed milk tin has the Vegetable tag
- Mouse meat tin doesn't have the Meat tag

2025-03-21 08:40 UTC, closed without merging