ApcNet updating fix
space-wizards/space-station-14 pull request #3078
Opened 2021-02-04 04:14 UTC by collinlunn

Closes #3056

Moves updating of ApcNets to a grid component, since there is no individual component that guarantees the existence of an ApcNet that I can do an EntityQuery for.

TODO: Ensure ApcNets always stop getting updated after removal.

2021-02-04 04:55 UTC, metalgearsloth requested changes
1 minor thing and 1 nullable. Rest LGTM.

2021-02-04 04:55 UTC, metalgearsloth commented on Content.IntegrationTests/Tests/PowerTest.cs
>                  var grid = mapMan.CreateGrid(new MapId(1));
```suggestion
                var grid = mapMan.CreateGrid(mapId);
```

2021-02-04 04:55 UTC, metalgearsloth commented on Content.IntegrationTests/Tests/PowerTest.cs
> +using System.Threading.Tasks;
```suggestion
#nullable enable
using System.Threading.Tasks;
```

2021-02-04 09:43 UTC, collinlunn commented
Will take some time to fix the test to be compatible with nullable.

2021-02-04 10:42 UTC, PaulRitter requested changes
you have nullability errors

2021-02-04 12:25 UTC, metalgearsloth commented
If it's painful to fix the test just out of scope it.

2021-02-04 13:36 UTC, Zumorica commented
Any reason this is a grid component instead of an entity system? This seems like it'd make creating "proper" new grids with power support more difficult

2021-02-04 19:23 UTC, collinlunn commented
Fixing nullability on the power test is big enough to be its own PR, undoing that for now.

2021-02-04 19:39 UTC, collinlunn commented
> Any reason this is a grid component instead of an entity system? This seems like it'd make creating "proper" new grids with power support more difficult

@Zumorica 
I could make the entity system maintain the set of ApcNets to update, but I'm not sure how I'd efficiently check which ApcNets are paused other than checking if each ApcNet's associated grid is paused every frame. If that's not a problem, I could move it to the entity system though.

2021-02-04 19:45 UTC, Zumorica commented
Hmm, it is true that making this a grid component elegantly solves the paused grid problem. I *guess* newly created APCs could ensure that there's a GridPower component on the grid they're on...

2021-02-05 06:48 UTC, metalgearsloth commented
> 
> 
> > Any reason this is a grid component instead of an entity system? This seems like it'd make creating "proper" new grids with power support more difficult
> 
> @Zumorica
> I could make the entity system maintain the set of ApcNets to update, but I'm not sure how I'd efficiently check which ApcNets are paused other than checking if each ApcNet's associated grid is paused every frame. If that's not a problem, I could move it to the entity system though.

You could check if the APC itself is paused during the uniqueApcNet update though checking it at a grid-level is faster.

2021-02-05 12:43 UTC, Zumorica commented
Maybe APC nets could store which grid ID they belong to? That'd allow you to check if the grid is paused before updating, I guess.

2021-02-05 18:01 UTC, collinlunn commented
> Maybe APC nets could store which grid ID they belong to? That'd allow you to check if the grid is paused before updating, I guess.

I could have an entity system maintain a set of all ApcNets, and do that. I just wasn't sure if it was efficient to check GridPaused so often, but that might be negilgible?

2021-02-12 11:36 UTC, Zumorica commented
> > Maybe APC nets could store which grid ID they belong to? That'd allow you to check if the grid is paused before updating, I guess.
> 
> I could have an entity system maintain a set of all ApcNets, and do that. I just wasn't sure if it was efficient to check GridPaused so often, but that might be negilgible?

Sounds good imo.

2021-02-14 22:00 UTC, collinlunn commented
I've updated this to follow the feedback, the grid component has been replaced with each ApcNet adding itself to an EntitySystem.

2021-02-17 13:44 UTC, metalgearsloth approved these changes

2021-02-17 13:44 UTC, metalgearsloth commented on Content.Server/GameObjects/EntitySystems/ApcNetSystem.cs
> +                if (gridId != null && !_pauseManager.IsGridPaused((GridId) gridId))
```suggestion
                if (gridId != null && !_pauseManager.IsGridPaused(gridId.Value))
```

2021-02-17 13:51 UTC, merged