Radio sound
space-wizards/space-station-14 pull request #30780
Opened 2024-08-08 12:47 UTC by Morb0

## About the PR

Now talking into radio and hearing radio messages produces a sound
Now only for headsets
Reference: [#85115](https://github.com/tgstation/tgstation/pull/85115)

## Why / Balance

Don't miss radio messages, greater immersion

## Technical details

## Media

https://github.com/user-attachments/assets/9c4901bc-32af-4d25-acc5-d1e0805f2f1a

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Hearing and talking into the radio now produces a sound

2024-08-08 12:51 UTC, Djungelskog2 commented
I'm sorry but I think the current sounds are fine, it sounds super disruptive and hearing it constantly would be like nails against a chalkboard.

2024-08-08 12:51 UTC, UbaserB commented
The sound's a little jarring, but I absolutely adore the idea.

2024-08-08 12:53 UTC, metalgearsloth commented on Content.Server/Radio/EntitySystems/HeadsetSystem.cs
> +
Does this add a global override or just the property?

2024-08-08 12:53 UTC, Djungelskog2 commented
Additionally I thing I noticed about 13 radio is how it's physically slower to type into and is less active for that, ss14 radio is far more intuitive and faster (for better or for worse), the SFX shouldn't carry the same weight

2024-08-08 16:22 UTC, bruhmogus commented
maybe we should use a more staticy version of the speech sound instead? the current noises should be saved for handhelds maybe

2024-08-08 16:39 UTC, Unbelievable-Salmon commented
This is extremely useful from an accessibility standpoint and would make my life ten times better with my vision severely limited as it is, so I ask this is greatly considered.

2024-08-08 16:57 UTC, themias commented
I like the idea! Perhaps there could be an option under Audio settings to toggle it for those who might not enjoy it.

2024-08-08 19:59 UTC, Hrosts commented
Having it togglable per-channel would be nice

2024-08-08 23:27 UTC, forgotmyotheraccount commented
Maybe radios could have a menu which lets you toggle which channels produce sound? Not a bad feature, but it'd be unbearable to get pinged for every common message you receive on a high pop server.

2024-08-09 23:35 UTC, lizelive commented
1. use per dept sound so you can tell what you are hearing. An easy standard you could use is https://en.wikipedia.org/wiki/DTMF
2. have per channel mute (including common)

2024-08-29 02:06 UTC, UbaserB requested changes
After internal discussion, we've decided that there should be a toggle per channel and the sound itself needs to be changed so that it's less jarring.

2024-09-12 11:55 UTC, UbaserB commented
You coming back to this?

2024-09-17 12:14 UTC, GroggleG commented
Played with this on TG, it was quite literally the most obnoxious thing that was merged in recent years (ignoring the wallening). in anywhere above 20 people it was really fucking annoying.

2024-09-17 14:00 UTC, superjj18 commented
> Played with this on TG, it was quite literally the most obnoxious thing that was merged in recent years (ignoring the wallening). in anywhere above 20 people it was really fucking annoying.

Can you not simply turn it off in the settings?

2024-09-17 21:16 UTC, GroggleG commented
given the fact that most people did I think that should be the default :feelsgood: 

> > Played with this on TG, it was quite literally the most obnoxious thing that was merged in recent years (ignoring the wallening). in anywhere above 20 people it was really fucking annoying.
> 
> Can you not simply turn it off in the settings?

2024-09-27 07:46 UTC, Snorkcom commented
nice spam, make the sound mute then

2024-09-27 23:07 UTC, superjj18 commented
> given the fact that most people did I think that should be the default :feelsgood: 
> 
> 
> 
> > > Played with this on TG, it was quite literally the most obnoxious thing that was merged in recent years (ignoring the wallening). in anywhere above 20 people it was really fucking annoying.
> 
> > 
> 
> > Can you not simply turn it off in the settings?
> 
> 
> 
> 

Not to be that guy but what analytics are you referring to in order to come to the conclusion that "most people did"

2024-09-28 06:09 UTC, UbaserB commented
Please ask if you want this PR to be reopened.

2024-09-28 06:09 UTC, closed without merging