Add diamond mining drills, buff regular mining drills
space-wizards/space-station-14 pull request #30814
Opened 2024-08-09 09:23 UTC by Blackern5000

## About the PR
Adds diamond mining drills, a T2 tech item which can be printed by science using diamonds. It is currently the only recipe to use diamonds. Also moves grappling tech to salvage T1, and makes diamonds worth 2k each instead of 500.
Also moves some prototypes around to better categorized files
- Pickaxes and drills are now found in mining.yml
- Drill recipes are now found in salvage.yml

## Why / Balance
Emo told me to do it
![image](https://github.com/user-attachments/assets/3a9134da-2a87-4378-b426-aeeedb3d7a9d)

For awhile now, drills have been outclassed by roundstart pickaxes due to the fact that you can instantly break 3 rocks every wideswing, and it took drills 3 hits to break one single rock. I've buffed them to break rocks in 2 hits, and hit 4 times a second. Diamond drills are simply regular drills with doubled damage, so they break rocks in one hit and hit 4 times a second, easily outclassing pickaxes.

As for the research changes, Emo told me to do it.
![image](https://github.com/user-attachments/assets/db606617-c67b-454c-96b7-b96fd57f240e)
It just makes more sense to lock higher level stuff behind higher level tech.

As for the diamond price change, Emo told me to do it in this pr instead of making it a separate one..

## Media

https://github.com/user-attachments/assets/23c0c821-44da-4159-be43-13ec2e467b44

![image](https://github.com/user-attachments/assets/536c3779-d682-4e62-9a55-37ccefec2a32)
## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added diamond-tipped mining drills, a science printed item found under T2 industrial.
- tweak: Standard mining drills now attack faster and break rocks in two hits.
- tweak: Moved ore bags of holding to T2 industrial tech.
- tweak: Grappling guns are now researched with Salvage Equipment.
- tweak: Diamonds are now worth 2,000 spesos each.

2024-08-09 09:50 UTC, lzk228 commented
diamond pickaxe soon?

2024-08-10 15:23 UTC, EmoGarbage404 approved these changes

2024-08-10 15:23 UTC, EmoGarbage404 commented on Resources/Prototypes/Reagents/Materials/materials.yml
> +  price: 2.5 # This should probably be a lot more but I'll leave that to a different pr
```suggestion
  price: 10 
```
live dangerously, lad

2024-08-10 20:37 UTC, IProduceWidgets commented
How would you feel about re-balancing the pickaxe to be a little slower and the shovel to be a little faster at mining?
Right now the pickaxe is fast enough there's not much reason to use a drill, and the shovel is so slow youd rather die than use it.

2024-08-11 17:19 UTC, EmoGarbage404 commented on Resources/Prototypes/Reagents/Materials/materials.yml
> +  price: 2.5 # This should probably be a lot more but I'll leave that to a different pr
live dangerously

2024-08-12 00:19 UTC, UbaserB requested changes
The outline on the diamond drillhead should be a bit darker, the inside grooves are fine though.

2024-08-12 01:40 UTC, UbaserB approved these changes

2024-08-12 01:49 UTC, merged