Return Long2 and Long3 hairstyles
space-wizards/space-station-14 pull request #30963
Opened 2024-08-13 06:14 UTC by JustArt1m

## About the PR
Return long2 and long3 hairstyles as classic.

Once upon a time, these hairstyles were resprited and completely lost their concept. I think it is necessary to return the old versions as classic ones.

## Why / Balance
Just for more customization. 

## Media

Classic Long 2
![Screenshot 2024-08-13 090333](https://github.com/user-attachments/assets/35a224bf-3d5e-4f31-bc83-531c5d6226fc)
![Screenshot 2024-08-13 090345](https://github.com/user-attachments/assets/a6b0f8b7-b2d5-411f-90b8-0f7e90ccae49)
![Screenshot 2024-08-13 090341](https://github.com/user-attachments/assets/fdb552cd-f260-40d3-9ade-353fdd63f55b)
![Screenshot 2024-08-13 090337](https://github.com/user-attachments/assets/703bfbba-cdd5-49df-937b-58b2e2256c2d)

Classic Long 3
![Screenshot 2024-08-13 090559](https://github.com/user-attachments/assets/74eabeeb-9c11-4f02-9df3-8808b16c15f6)
![Screenshot 2024-08-13 090611](https://github.com/user-attachments/assets/a8396956-19d1-4174-9daa-a331ef15304f)
![Screenshot 2024-08-13 090606](https://github.com/user-attachments/assets/b3e3e2f2-fd99-4327-8b1f-0dd6ef1d435f)
![Screenshot 2024-08-13 090603](https://github.com/user-attachments/assets/6ac2c4d7-30a7-49dd-adc8-c0d2bc19d0b5)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Just_Art
- add: Added Classic Long 2 and Classic Long 3 hairstyles!

2024-08-13 06:38 UTC, JustArt1m commented
> please update the copyright information for this hair

How exactly? These hairstyles were originally from https://github.com/tgstation/tgstation/blob/05ec94e46349c35e29ca91e5e97d0c88ae26ad44/icons/mob/species/human/human_face.dmi

2024-09-03 07:39 UTC, UbaserB requested changes

2024-09-03 07:39 UTC, UbaserB commented on Resources/Locale/en-US/accessories/human-hair.ftl
> +marking-HumanHairClassicLong2 = Classic Long Hair 2
Needs to be in alphabetical order

2024-09-03 08:20 UTC, UbaserB approved these changes

2024-09-03 08:29 UTC, merged