Namespace cleanup around Mind Roles
space-wizards/space-station-14 pull request #30965
Opened 2024-08-13 09:12 UTC by Errant-4

## About the PR
File-scoping namespaces, including in some large systems, that I'm touching in a work-in-progress PR around Mind Roles. 
No functional changes to the contents, this is just to make the actual later changes easier to review

## Media

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2024-08-13 09:21 UTC, 0x6273 commented
Can't you just make the namespace changes in the same PR but in a separate commit?

2024-08-13 14:15 UTC, Errant-4 commented
> Can't you just make the namespace changes in the same PR but in a separate commit?

That's what I have been doing until now, but I was told that's not the silver bullet I thought it was

2024-08-15 18:12 UTC, VasilisThePikachu requested changes

2024-08-15 18:12 UTC, VasilisThePikachu commented on Content.Server/Chat/Managers/ChatManager.cs
> +        _mommiLink.SendOOCMessage(player.Name, message.Replace("@", "\\@").Replace("<", "\\<").Replace("/", "\\/")); // @ and < are both problematic for discord due to pinging. / is sanitized solely
```suggestion
        _mommiLink.SendOOCMessage(player.Name, message.Replace("@", "\\@").Replace("<", "\\<").Replace("/", "\\/")); // @ and < are both problematic for discord due to pinging. / is sanitized solely to kneecap links to murder embeds via blunt force
```

2024-08-15 18:26 UTC, VasilisThePikachu approved these changes

2024-08-15 18:26 UTC, merged