Add a popup when someone else throws something
space-wizards/space-station-14 pull request #31080
Opened 2024-08-16 08:51 UTC by DrSmugleaf

## About the PR
## Media
![image](https://github.com/user-attachments/assets/31841c67-b6d9-4e88-ad5c-95a8cd9ab09f)

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2024-08-16 09:54 UTC, SlamBamActionman commented
Not sure I like this. It makes it harder to stealthily chuck bombs into rooms, throw explosive pens and makes the throwing knives even less appealing since you can track the thrower via the text pop-up. 

I could see this being useful for a downstream like RMC where throwing-capable characters are meant to all be on the same team, but for upstream it conflicts with the stealth aspect of certain roles.

2024-08-16 10:16 UTC, Pumkin69 commented
This PR does NOT seem like a good idea to merge into upstream.

2024-08-16 10:37 UTC, ElPidor commented
BAD + SKILL ISSUE + DO NOT MERGE 
secoff dont care about throwing stuff like why non antag need to throw something? 
antag need to throw because have some things that are need to be thrown -> secoff see popup auga neuron activity -> stanbatoning 
its good as it is

2024-08-16 11:56 UTC, Dutch-VanDerLinde requested changes
this should use the identity of the entity who threw the item, believe this pop up will bypass identity

2024-08-16 14:43 UTC, EmoGarbage404 requested changes

2024-08-16 14:43 UTC, EmoGarbage404 commented on Content.Shared/Throwing/ThrowingSystem.cs
> +        var popup = Loc.GetString("throwing-user-threw-others", ("user", user), ("thrown", uid));
need to use Identity.Entity() in `Content.Shared.IdentityManagement` for the user and uid so that it respects all the junk correctly.

2024-08-16 14:43 UTC, EmoGarbage404 commented on Content.Shared/Throwing/ThrowingSystem.cs
> +        _popup.PopupEntity(popup, user.Value, Filter.PvsExcept(user.Value), true, PopupType.SmallCaution);
i'd probably say do a normal white popup instead of the scary red ones?

2024-08-16 20:57 UTC, ps3moira commented
This kinda kills any stealth if giant red text outs you

2024-08-21 10:10 UTC, DrSmugleaf commented
i never expected this amount of powergamer malding over a basic feature that 13 has always had for very good reason
up to you i don't care what upstream does or does not merge though

2024-08-21 11:07 UTC, SlamBamActionman commented
> i never expected this amount of powergamer malding over a basic feature that 13 has always had for very good reason up to you i don't care what upstream does or does not merge though

Please state the "very good reason" in the PR's "Why/Balance" section then (the one that was not included, in conflict with the Pull Request Guidelines), otherwise we are going to have to evaluate the feature based on what is being shown in relation to SS14's gameplay.

2024-08-21 12:03 UTC, Dutch-VanDerLinde commented
why / balance : someone CHUCKING a whole ass bomb at someone stealthily is stupid

2024-08-21 14:57 UTC, ps3moira commented
It's a good feature from SS13. There will eventually be more pop ups for actions so you can tell if someone's hitting someone, throwing something, reading or anything like that as it's kinda hard to tell at a certain points of the game what is happening. This is the starting point of that and should be welcomed

2024-08-21 20:30 UTC, SlamBamActionman commented
Can't hide by throwing in/from the dark:
![image](https://github.com/user-attachments/assets/a172611b-d872-4dc0-891d-98b6ac1782bb)
![image](https://github.com/user-attachments/assets/09cb30c3-1180-474b-a344-08dbdf1da7ca)

Disappearing into the crowd is no longer a strategy:
![image](https://github.com/user-attachments/assets/6f2ab83b-6693-437b-a035-a900d8af7b26)

Text lingers after exiting FoV, so you can't throw it at someone unexpecting and then run away:
![image](https://github.com/user-attachments/assets/ca235e04-a0ef-42b6-9560-eee4b262e9bd)

2024-08-21 21:02 UTC, BolloTea commented
Epilepsy is the beginning.  If there is a pop-up window for every little thing, then your brain will simply explode trying to process all the information that pops up literally for a second and disappears forever.  At 13, at least it was in the chat, where you could pick up tons of text at any time and find what you need (plus there is a word search).  Here it’s done crookedly, poorly, and my God, seeing a pop-up window from any sneeze is annoying to say the least

2024-08-21 21:09 UTC, BolloTea commented
> It's a good feature from SS13. There will eventually be more pop ups for actions so you can tell if someone's hitting someone, throwing something
>
Please - no.  The game already has a damage indicator to show that someone is hitting someone.  Extra information will be too overloading and unnecessary
Or do as in 13 - in the chat

2024-08-21 22:09 UTC, ps3moira commented
> > It's a good feature from SS13. There will eventually be more pop ups for actions so you can tell if someone's hitting someone, throwing something
> 
> Please - no. The game already has a damage indicator to show that someone is hitting someone. Extra information will be too overloading and unnecessary Or do as in 13 - in the chat

A version of this that shows who throws or does what but in chat does seem better. I wonder if it's CCVar or easy to change to do this

2024-09-02 12:11 UTC, SlamBamActionman commented
Hello! The PR was put up to a maintainer vote which concluded with the following result: Do Not Merge.

The reasons given were the following:
- Concerns about the stealth aspect of the game.
- Want to avoid too many pop-ups as it could lead to visual clutter and make people filter out pop-ups.

As such, this PR will be closed. Thank you for your contribution!

2024-09-02 12:11 UTC, closed without merging