Feature/crackable pai
space-wizards/space-station-14 pull request #31164
Opened 2024-08-18 17:01 UTC by Brahex

## About the PR

pAI's can now take damage! They are very sturdy, that is, unless you drop them. When the damage threshold is reached its screen cracks, its name is scrambled, and it starts talking a little funny. Oh, also, you can repair it through welding.

## Why / Balance

I really wanted that feeling of dropping your phone in SS14. Since a pAI cannot be fully destroyed, this has no impact on game balance.

## Technical details

Created a GlitchAccentComponent.

The pAI component now keeps track of whether it is cracked or not and adds/removes the GlitchAccent, adds/removes the cracked screen overlay, and changes its name and description respectively.

## Media

![tmp](https://github.com/user-attachments/assets/273e1b1d-5f21-451a-b35b-a565801ec956)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None as far as I'm aware.

**Changelog**

:cl:
- add: A pAi can now take damage. It takes the most damage when dropped or thrown.
- add: When damaged, a pAi's screen will crack, its name will scramble, and its voice will become glitched.
- add: A pAi can now be repaired through welding.

2024-08-18 17:03 UTC, beck-thompson commented
Such a fun idea!

2024-08-18 21:32 UTC, ElPidor commented
should pai get damage when its baked in microwave?

2024-08-18 22:16 UTC, Golinth commented
I feel like this makes it too easy to scramble the name. Usually to scramble the name you need to microwave it, either by finding one or breaking into the kitchen and you risk completely destroying it

2024-08-19 06:26 UTC, Brahex commented
> I feel like this makes it too easy to scramble the name. Usually to scramble the name you need to microwave it, either by finding one or breaking into the kitchen and you risk completely destroying it

Before I make any changes to this, how do we all feel about this mechanic in general? I myself have some questions about motivating a player to undertake an action that has a 50% chance to round remove their ally (in the case of a nukie trying to hide their name on a syndicate pAI). This sounds rather harsh on the player being round removed.

How things currently work in this PR: It is now possible to hide ones name on a pAI without negative consequences. However, it is now also possible for crew to repair said pAI to figure out the name of the last owner.

2024-08-26 08:59 UTC, Moomoobeef commented
I forgot I had already made damaged pAI sprites a few months back and never used them for anything. Glad to see this idea being put into an actual PR though (you got further than I did lol)

2024-09-10 09:21 UTC, SlamBamActionman commented
Hello! This PR has gone through a maintainer vote with the following result: Merge, but with changes.

Consensus is that the name obfuscation is too trivial to reverse, and its functionality already exists in another system (microwaving). We'd like to see the name scrambling removed from this PR.
We'd also like to see microwaving pAIs have a reduced risk of destroying the pAI (current value is too high) but that shouldn't be a blocker for this PR and can be made into a separate GitHub issue.

Once the name scrambling is removed, we're comfortable merging the PR.

2024-10-13 13:09 UTC, Brahex commented
If anyone knows how to merge master into this branch without leading to updated submodule errors and build errors about missing .csproj files, let me know.

2025-04-26 01:27 UTC, MilonPL requested changes

2025-04-26 01:27 UTC, MilonPL commented on Content.Server/Speech/EntitySystems/GlitchAccentSystem.cs
Take a look at [DamagedSiliconAccentSystem](https://github.com/space-wizards/space-station-14/blob/master/Content.Server/Speech/EntitySystems/DamagedSiliconAccentSystem.cs). Could probably use that instead.

2025-04-26 01:27 UTC, MilonPL commented on Content.Server/PAI/PAISystem.cs
> +        }
This should just use the ExamineEvent in Shared.

2025-04-26 01:27 UTC, MilonPL commented on Content.Server/PAI/PAISystem.cs
> +    private void OnCracked(EntityUid uid, PAIComponent comp, BreakageEventArgs args)
Use the Entity<T> pattern and sub by-ref

2025-04-26 01:27 UTC, MilonPL commented on Content.Server/PAI/PAISystem.cs
> +        AddComp<GlitchAccentComponent>(uid);
EnsureComp is generally better since AddComp will fail if there's already a component of the same type on the entity.

2025-04-26 01:27 UTC, MilonPL commented on Content.Shared/PAI/PAIComponent.cs
> +    public bool Cracked = false;
You don't need to set bools as false, they are already like that by default.

2025-04-26 01:56 UTC, beck-thompson commented on Content.Shared/PAI/PAIComponent.cs
> +    public bool Cracked = false;
I like it being false

2025-04-26 21:57 UTC, EmoGarbage404 requested changes

2025-04-26 21:57 UTC, EmoGarbage404 commented on Content.Server/PAI/PAISystem.cs
> +        _damageable.TryChangeDamage(uid, new DamageSpecifier(_prototypeManager.Index<DamageTypePrototype>("Heat"), 50));
shouldn't hardcode prototypes in here

2025-04-26 21:57 UTC, EmoGarbage404 commented on Content.Server/PAI/PAISystem.cs
> +        _damageable.TryChangeDamage(uid, new DamageSpecifier(_prototypeManager.Index<DamageTypePrototype>("Blunt"), 150));
here too. you can just add this into the yaml to damage it on thrown.

2025-04-26 21:57 UTC, EmoGarbage404 commented on Content.Server/PAI/PAISystem.cs
> +            comp.Cracked = false;
pretty sure we have a repairable system and component which feels like a better way of handling this. the hardcoded threshold is hurting me

2025-06-05 13:32 UTC, TheShuEd commented
it's been over a month since the review. Do you plan to continue working on this PR?

2025-07-10 08:52 UTC, TheShuEd commented
Given that this PR has been in a “Awaiting Changes” state for over 2 months without any activity, I'm closing it as obsolete

2025-07-10 08:52 UTC, closed without merging