Add some alternate jumpsuit designs which can be toggled
space-wizards/space-station-14 pull request #31213
Opened 2024-08-19 18:18 UTC by Dutch-VanDerLinde

## About the PR

## Why / Balance
cool

## Technical details
uses ``FoldableClothingComponent``, sprites from tg

## Media
![image](https://github.com/user-attachments/assets/19b59081-fda0-492e-84c9-8298e8accae6)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- add: Some jumpsuits may now be folded to give them an alternate look.

2024-08-19 18:40 UTC, ImRenQ commented
COOL

2024-08-19 20:02 UTC, DieselMohawk commented
Very nice

2024-08-19 20:41 UTC, ps3moira commented
![flipped-equipped-INNERCLOTHING](https://github.com/user-attachments/assets/95088583-f195-4d4d-a3aa-67189d218b96)
here's a prisoner thing too

2024-08-19 20:44 UTC, Dutch-VanDerLinde commented
> ![flipped-equipped-INNERCLOTHING](https://private-user-images.githubusercontent.com/113228053/359239283-95088583-f195-4d4d-a3aa-67189d218b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDA1MjksIm5iZiI6MTcyNDEwMDIyOSwicGF0aCI6Ii8xMTMyMjgwNTMvMzU5MjM5MjgzLTk1MDg4NTgzLWYxOTUtNGQ0ZC1hM2FhLTY3MTg5ZDIxOGI5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQyMDQzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjY2ZGRiOWJhMTE1OTg0NDU4NDkwOWM2MjNmNmQ2NmM5YjNmNjM2ZmEzNWJlODhkYmIwMGFlNmI4ZTlkM2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BqhoCBJBvS2xRg1fng8LRkkNOmdRmOMsxMvCOw9uPug) here's a prisoner thing too

too bad prisoner jumpsuits and colored use clothing layers which makes it impossible for foldable clothing to work

2024-08-19 20:45 UTC, ps3moira commented
> > ![flipped-equipped-INNERCLOTHING](https://private-user-images.githubusercontent.com/113228053/359239283-95088583-f195-4d4d-a3aa-67189d218b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDA1MjksIm5iZiI6MTcyNDEwMDIyOSwicGF0aCI6Ii8xMTMyMjgwNTMvMzU5MjM5MjgzLTk1MDg4NTgzLWYxOTUtNGQ0ZC1hM2FhLTY3MTg5ZDIxOGI5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQyMDQzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjY2ZGRiOWJhMTE1OTg0NDU4NDkwOWM2MjNmNmQ2NmM5YjNmNjM2ZmEzNWJlODhkYmIwMGFlNmI4ZTlkM2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BqhoCBJBvS2xRg1fng8LRkkNOmdRmOMsxMvCOw9uPug) here's a prisoner thing too
> 
> too bad prisoner jumpsuits and colored use clothing layers which makes it impossible for foldable clothing to work

a shame. maybe make them not colored? food for thought

2024-08-19 20:47 UTC, Dutch-VanDerLinde commented
> > > ![flipped-equipped-INNERCLOTHING](https://private-user-images.githubusercontent.com/113228053/359239283-95088583-f195-4d4d-a3aa-67189d218b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDA1MjksIm5iZiI6MTcyNDEwMDIyOSwicGF0aCI6Ii8xMTMyMjgwNTMvMzU5MjM5MjgzLTk1MDg4NTgzLWYxOTUtNGQ0ZC1hM2FhLTY3MTg5ZDIxOGI5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQyMDQzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjY2ZGRiOWJhMTE1OTg0NDU4NDkwOWM2MjNmNmQ2NmM5YjNmNjM2ZmEzNWJlODhkYmIwMGFlNmI4ZTlkM2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BqhoCBJBvS2xRg1fng8LRkkNOmdRmOMsxMvCOw9uPug) here's a prisoner thing too
> > 
> > 
> > too bad prisoner jumpsuits and colored use clothing layers which makes it impossible for foldable clothing to work
> 
> a shame. maybe make them not colored? food for thought

#26943

2024-08-19 21:06 UTC, Emisse commented
I think a tanktop or something underneath might be better so its more gender neutral

2024-08-19 21:12 UTC, EmoGarbage404 commented
> I think a tanktop or something underneath might be better so its more gender neutral

Me when i enter fight mode and let the titties hang

2024-08-19 21:12 UTC, Dutch-VanDerLinde commented
im making an underwear pr just gimme a minute

> I think a tanktop or something underneath might be better so its more gender neutral

2024-08-19 21:19 UTC, ElPidor commented
> ## About the PR
> ## Why / Balance
> cool
> 
> ## Technical details
> uses `FoldableClothingComponent`, sprites from tg
> 
> ## Media
> ![image](https://private-user-images.githubusercontent.com/45323883/359202865-19b59081-fda0-492e-84c9-8298e8accae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDE4MjYsIm5iZiI6MTcyNDEwMTUyNiwicGF0aCI6Ii80NTMyMzg4My8zNTkyMDI4NjUtMTliNTkwODEtZmRhMC00OTJlLTg0YzktODI5OGU4YWNjYWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIxMDUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZTc5OGNjMTcyYTc3OGE0MDVmNzRkZTkxZjAzMTg5NzcyMmNhOThlMjVkZGY4MDljODRiN2Y1ZTQ4NmRjNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tRaAlLknc3ygeYqUPfmvAplyHirHf097olZO_4r9Up8)
> 
> ## Requirements
> * [x]  I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
> * [x]  I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> 🆑
> 
> * add: Some jumpsuits may now be folded to give them an alternate look.

![image](https://github.com/user-attachments/assets/ee594200-cb4d-4df9-abca-01688ec6ba66)
DREAM PR

2024-08-19 21:38 UTC, coolsurf6 commented
No more luck of the draw with random colourful clothing. 

Perfect.

2024-08-19 21:43 UTC, lzk228 commented
blessed, but the only reason why i don't like it - forks should make resprites. if it possible (which i think not) would be good to make it with displacement maps

2024-08-19 21:45 UTC, shampunj commented
best pr ever

2024-08-20 01:41 UTC, EmoGarbage404 commented
the sec alt jumpsuit doesn't have the pixels on the sides above the belt which makes him look pudgier than all the rest. it looks like a layer is missing or smth.

2024-08-20 01:47 UTC, Savsj commented
> the sec alt jumpsuit doesn't have the pixels on the sides above the belt which makes him look pudgier than all the rest. it looks like a layer is missing or smth.

So like, yeah thats definitely not intentional but its funny that we have the villiage people and then paul blart mall cop, and i am pro this accident staying for sec.

2024-08-20 02:03 UTC, ps3moira commented
> > the sec alt jumpsuit doesn't have the pixels on the sides above the belt which makes him look pudgier than all the rest. it looks like a layer is missing or smth.
> 
> So like, yeah thats definitely not intentional but its funny that we have the villiage people and then paul blart mall cop, and i am pro this accident staying for sec.
reminds me of this
![image](https://github.com/user-attachments/assets/546b98f5-188b-45e0-b196-8e09025b4bda)

2024-08-20 03:27 UTC, Dutch-VanDerLinde commented
The sec sprite is literally just the sec jumpsuit but just the pants

2024-08-20 03:55 UTC, DieselMohawk commented
> The sec sprite is literally just the sec jumpsuit but just the pants

I see what they mean, the rest of the waist wrapped shirts make the illusion of it going inwards and looking more skinny.

2024-08-20 05:45 UTC, whateverusername0 commented
based, merge now

2024-08-20 09:13 UTC, DaMoggen commented
Amazing, we need this

2024-08-20 19:26 UTC, Dutch-VanDerLinde commented
![image](https://github.com/user-attachments/assets/b8e70b9c-d558-4396-a839-48f80fbb3622)
new security sprite

2024-09-05 03:57 UTC, UbaserB requested changes
After internal maintainer discussion, the consensus is for there to be a gender neutral tanktop/wife beater underneath and for the jumpsuit itself to use rgb similar to the current plain-colour jumpsuits.

2025-01-04 04:33 UTC, Pumkin69 commented
someone needs to remake this.

2025-06-19 21:35 UTC, Entvari commented
Can't this now be merged after the introduction of underclothes markings, i'd absolutely love for this to be introduced

2025-07-10 02:46 UTC, Dutch-VanDerLinde commented
reopening since underwear was added to the game

2025-07-29 04:09 UTC, Dutch-VanDerLinde commented
> Looks good! Bit awkward to take off the whole jumpsuit just to tie off the top but it works. Only two problems I have are with the Atmos and Engineering jumpsuits. The tie around the waist is a bit too solid a color compared to all the others. They look good from every angle but the front, where it becomes pretty blobby when it's all using the outline color.
> 
> <img alt="Engineer Jumpsuit" width="150" height="191" src="https://private-user-images.githubusercontent.com/176858593/471790417-482e552b-7d73-4dab-ad5b-aee86ac23b79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM3NjI0MjMsIm5iZiI6MTc1Mzc2MjEyMywicGF0aCI6Ii8xNzY4NTg1OTMvNDcxNzkwNDE3LTQ4MmU1NTJiLTdkNzMtNGRhYi1hZDViLWFlZTg2YWMyM2I3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyOVQwNDA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWYzNzVjYjcyYzE1Njg0YjZlNWZiNmFmYzI1NDg2YjY2ZTEyZTNhNWU0OWI4Mzg1NDA4NjJjNjA3NWQxYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8uODnXiG82D-g0eVeIZA0z3EAlssywxqd2jBxKLxhrM"> <img alt="Atmos jumpsuit" width="163" height="173" src="https://private-user-images.githubusercontent.com/176858593/471790518-f6ec4c99-6f41-42ee-9452-3ee8b7c372f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM3NjI0MjMsIm5iZiI6MTc1Mzc2MjEyMywicGF0aCI6Ii8xNzY4NTg1OTMvNDcxNzkwNTE4LWY2ZWM0Yzk5LTZmNDEtNDJlZS05NDUyLTNlZThiN2MzNzJmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyOVQwNDA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGM1NzVhYTU3NjQ4MTE3NWQzMDExYTRiZDg2ODJkODVkNzE4OWQwMjYyOGM5ODI5Y2VkMjk3Mjg0ZDNhMjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B1W98lhGY1S4uX3pQ4XnDRcdZzFWHQV9RnX2wR-sTQM">

this is just a bug with the foldable system that should be fixed, you should be able to fold clothes while having them equipped, as for the sprite, ill see what i can do

2025-08-02 17:42 UTC, Entvari commented
Awesome that this PR is being picked up again, it'd be really cool if we got a grey jumpsuit version too though, the attire is super fitting for tider.

2025-08-03 22:11 UTC, Dutch-VanDerLinde commented
> Awesome that this PR is being picked up again, it'd be really cool if we got a grey jumpsuit version too though, the attire is super fitting for tider.

Sadly it's impossible because of sprite layers

2025-08-26 00:19 UTC, TiniestShark commented
<img width="64" height="64" alt="folded-equipped-INNERCLOTHING 2" src="https://github.com/user-attachments/assets/dc2517cc-22e1-4b6e-b8ba-64f8e56a0377" />
<img width="64" height="64" alt="folded-equipped-INNERCLOTHING" src="https://github.com/user-attachments/assets/7436e3e2-1bdd-4a04-adfc-c6f2b8c53453" />
Heya, I wanted to help with getting this PR off the ground so I just went ahead and made the adjustments to the Engi and Atmos jumpsuits myself. Just switch these in and I can give it an official approval.

2025-08-26 03:53 UTC, Dutch-VanDerLinde commented
> <img alt="folded-equipped-INNERCLOTHING 2" width="64" height="64" src="https://private-user-images.githubusercontent.com/176858593/481849860-dc2517cc-22e1-4b6e-b8ba-64f8e56a0377.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxODA2MjEsIm5iZiI6MTc1NjE4MDMyMSwicGF0aCI6Ii8xNzY4NTg1OTMvNDgxODQ5ODYwLWRjMjUxN2NjLTIyZTEtNGI2ZS1iOGJhLTY0ZjhlNTZhMDM3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQwMzUyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2Y1YWVlNjIzZmQ3MjhhYTM4YjhmNWU5OGQ4ZTY4YzI1YzMwMGY3OTc2MDk4OTNhNDRjOTNhMTRmNTc0MTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k8lCyonWCRQcy9n5hP-XjlRBuhjtaklZABW5HJhEzZo"> <img alt="folded-equipped-INNERCLOTHING" width="64" height="64" src="https://private-user-images.githubusercontent.com/176858593/481849865-7436e3e2-1bdd-4a04-adfc-c6f2b8c53453.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxODA2MjEsIm5iZiI6MTc1NjE4MDMyMSwicGF0aCI6Ii8xNzY4NTg1OTMvNDgxODQ5ODY1LTc0MzZlM2UyLTFiZGQtNGEwNC1hZGZjLWM2ZjJiOGM1MzQ1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNlQwMzUyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGI5ZDMwZDdkNjZjZmViYzc5ZmQ3MTYxMTYwNjM3NzNlNzQwMmRhNTBhNWM5NmJiNDQ2MTU3YzJhNDdkYWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5HQe4vBrao06YbNOGhCO0sWqQrMer_TJmcv-gaxvMTs"> Heya, I wanted to help with getting this PR off the ground so I just went ahead and made the adjustments to the Engi and Atmos jumpsuits myself. Just switch these in and I can give it an official approval.

Thanks! Sorry for the inactivity, I was busy with a couple of things. I'll put these in.

2025-08-26 03:59 UTC, Dutch-VanDerLinde commented
Can't download the sprites so im just gonna fix the sec jumpsuit for now

2025-08-26 04:33 UTC, TiniestShark commented
> Can't download the sprites so im just gonna fix the sec jumpsuit for now

That's odd, I can download it just fine myself. Is there another good way I could send these over to you?

2025-08-29 04:52 UTC, Dutch-VanDerLinde commented
> > Can't download the sprites so im just gonna fix the sec jumpsuit for now
> 
> That's odd, I can download it just fine myself. Is there another good way I could send these over to you?

Figured it out, was able to download them , replaced them with your sprties

2025-09-01 16:28 UTC, TiniestShark approved these changes
Gave a once over in-game and everything's working pretty well, plus the variants are all solid.

2025-09-04 23:53 UTC, ScarKy0 requested changes
Brief check. Please make sure to add yourself to all the attributions in .rsi files you modified. Also add a suffix like (Github) or (Discord) f.e "XYZ made by ABC (Github)"

2025-09-04 23:53 UTC, ScarKy0 commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/cargotech.rsi/meta.json
> -  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/c838ba21dae97db345e0113f99596decd1d66039, edited by Flareguy. In hand sprite scaled down by potato1234_x,
Any reason this attribution was removed?

2025-09-06 15:20 UTC, Dutch-VanDerLinde commented
> Brief check. Please make sure to add yourself to all the attributions in .rsi files you modified. Also add a suffix like (Github) or (Discord) f.e "XYZ made by ABC (Github)"

I didn't modify any sprites except the sec one

2025-09-06 15:20 UTC, closed without merging

2025-09-06 15:21 UTC, Dutch-VanDerLinde commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/cargotech.rsi/meta.json
> -  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/c838ba21dae97db345e0113f99596decd1d66039, edited by Flareguy. In hand sprite scaled down by potato1234_x,
accident

2025-09-06 15:22 UTC, ScarKy0 commented
> I didn't modify any sprites except the sec one

In that case youre gonna have to attribute the person who made the other sprites

2025-09-06 15:22 UTC, Dutch-VanDerLinde commented
> > I didn't modify any sprites except the sec one
> 
> In that case youre gonna have to attribute the person who made the other sprites

what other sprites? they're from TG, the same commit that it's originally attributed by

2025-09-06 15:22 UTC, Dutch-VanDerLinde commented
except the sprites by TiniestShark, which i had already attributed her

2025-09-06 15:23 UTC, ScarKy0 commented
> what other sprites? they're from TG, the same commit that it's originally attributed by

Ah in that case all good

2025-09-06 16:27 UTC, Dutch-VanDerLinde commented
> Tested, works, and look absolutely amazing in-game. I hope we get this for more jumpsuits at some point

There's more jumpsuit variants from TG that havent been ported yet, like the detective jumpsuits since we still use those old sprites

I plan to port the rest once this PR is merged

2025-09-06 16:28 UTC, Dutch-VanDerLinde commented
and possibly sprite more.

2025-09-06 17:56 UTC, TiniestShark commented
> except the sprites by TiniestShark, which i had already attributed her

*Him

Glad to have helped, and really looking forward to seeing the other jumpsuit variants. I think this is a great way to get more customization in without just making entirely new clothing.

2025-09-06 19:40 UTC, Entvari commented
YES!!!!!!

2025-09-06 23:11 UTC, Dutch-VanDerLinde commented
After 1 year and 1 month in development, we hope it was worth the wait