Add special microwave board to Combat Bakery Kit
space-wizards/space-station-14 pull request #31239
Opened 2024-08-20 21:03 UTC by themias

## About the PR

This PR adds a special Syndicate microwave board to the Combat Bakery Kit (#31179). Microwaves with this board are able to bake baguette swords and throwing croissants (and normal recipes.) Both the new boards and microwaves are incognito and appear normal.

Baguette Sword Recipe:
Dough x 1
Salt 5u
Pepper 5u
Metal Rod x 1
Cook Time: 15 seconds

Throwing Croissant Recipe:
Raw Croissant x 1
Butter Slice x 1
Glass Shard x 1
Cook Time: 5 seconds

## Why / Balance

The SS13 version had the ability to bake more weapons, so this brings it in line. It adds opportunities to rearm yourself after eating past weapons to hide them, as well as arming other syndies. I increased the TC cost, but let me know if that is a fair price.

## Technical details

The main hurdle was how to allow only some people to cook a recipe. We couldn't just learn it from a book like SS13, since we didn't want to just add a component onto a player entity like that.

I considered an implant, but that was a bit messier, since the implant would have the component rather than the player.

The microwave built with this board has a RecipeProviderComponent, which will add its recipes to the available list when cooking. The two new recipes are marked as SecretRecipe, and do not appear in the normal list.

## Media

This shows how a modified microwave can cook the secret recipe, but a normal one can't:

https://github.com/user-attachments/assets/a0456819-5d87-47d3-aa89-c98bcf97fc24

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: The Combat Bakery Kit now has a special microwave board that allows baking more weapons.
- tweak: The Combat Bakery Kit now costs 6 TC.

2024-08-20 21:28 UTC, themias commented on Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
> +        private List<FoodRecipePrototype> TryGetSecretRecipes(EntityUid uid)
I'm realizing this probably could be an event instead.

2024-08-20 21:57 UTC, Golinth commented
Maybe make the board the special donk co branded ones that the nukies have, and give this functionality to it instead? Its just odd to me to have two different syndicate microwaves

2024-08-20 22:16 UTC, themias commented
> Maybe make the board the special donk co branded ones that the nukies have, and give this functionality to it instead? Its just odd to me to have two different syndicate microwaves

The idea is for it to be sneaky and look like a regular microwave. Those Nukie ones are bright red and would stand out.

2024-08-20 22:38 UTC, SlamBamActionman commented
I think this is an interesting way to make it possible to cook weapons, but I would def make the board itself look sus. That way players can confirm the microwave is tampered with if they disassemble it, and if they do they likely suspect you already.

How will players learn the new recipes? If there is no way to know them outside reading a wiki/code it's bad. Maybe the kit can include a piece of paper listing the recipes (with a cheeky little "burn after reading" at the bottom)?

2024-08-20 23:20 UTC, themias commented
> I think this is an interesting way to make it possible to cook weapons, but I would def make the board itself look sus. That way players can confirm the microwave is tampered with if they disassemble it, and if they do they likely suspect you already.
> 
> How will players learn the new recipes? If there is no way to know them outside reading a wiki/code it's bad. Maybe the kit can include a piece of paper listing the recipes (with a cheeky little "burn after reading" at the bottom)?

These are both good suggestions. I'll update the PR with them.

2024-08-22 14:53 UTC, ElPidor commented
I made it a little cooler, how's it chaaat
![image](https://github.com/user-attachments/assets/dad05b6d-1245-4bff-98cb-7d21295d2c21)
![image](https://github.com/user-attachments/assets/40b32560-8eaa-4981-88f4-521ebd9bf79f)
[Traitor reciept.txt](https://github.com/user-attachments/files/16713579/Traitor.reciept.txt) if you'd like to put it in

2024-08-25 09:10 UTC, Admiral-Obvious-001 commented
I think this would be hilarious, but probably would need to be retuned a fair deal considering how easy it is to get the required materials with little effort.

2024-08-29 01:21 UTC, UbaserB requested changes
After internal discussion, we've decided that the microwave board should be the red donk co version so that nukies can also use it.

EDIT: I misinterpreted something, sorry for that.

2024-09-02 13:49 UTC, merged

2024-09-02 17:19 UTC, Everturning commented
> I made it a little cooler, how's it chaaat ![image](https://private-user-images.githubusercontent.com/49343726/360518272-dad05b6d-1245-4bff-98cb-7d21295d2c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTc3MzcsIm5iZiI6MTcyNTI5NzQzNywicGF0aCI6Ii80OTM0MzcyNi8zNjA1MTgyNzItZGFkMDViNmQtMTI0NS00YmZmLTk4Y2ItN2QyMTI5NWQyYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDE3MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MWVjMjY0NWY2ZjRjNTNhZmFkYjIzZWMxNThhNGEyOTk4Nzk2YWQxMzI1OThiOGM3N2U2YmE4NTk4YTM2ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dkqsT-KSXmIDzq4kjZCI8xjXZAaymvB0Hn0BAdvZs1E) ![image](https://private-user-images.githubusercontent.com/49343726/360516891-40b32560-8eaa-4981-88f4-521ebd9bf79f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTc3MzcsIm5iZiI6MTcyNTI5NzQzNywicGF0aCI6Ii80OTM0MzcyNi8zNjA1MTY4OTEtNDBiMzI1NjAtOGVhYS00OTgxLTg4ZjQtNTIxZWJkOWJmNzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDE3MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZjZmODhiY2I3NTJmZjBjYjBmN2YwMmIwMjdjYjYyZWMzZTAzMWY1NDEzYWRjZGEzMGQzYzdlNzk4NzA4M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xeGkSX-a8muXVRUR0u2iUK_OKW7CpYZt6JFddsngdKo) [Traitor reciept.txt](https://github.com/user-attachments/files/16713579/Traitor.reciept.txt) if you'd like to put it in _I can change some parts if it doesnt fit wizden art style_

This isn't spam yall