PKA Modkits + Rebalance
space-wizards/space-station-14 pull request #31247
Opened 2024-08-21 00:33 UTC by EmoGarbage404

## About the PR

Rebalances the Proto-kinetic Accelertor:
- The range has been decreased to roughly 4 tiles
- The damage has been decreased to 15 blunt and 15 structural.
- Raises the size class to large and increases the inventory size to 2x3

To compensate, adds several modkits that can be used to buff the PKA. All 3 can be installed at once but there can't be duplicates. They are researchable via the "Kinetic Modifications" tech and can also be rarely found in salvage.

The 3 modkits are:
- Damage: Raises damage to 25 blunt and 30 structural
- Range: Raises range from 4 tiles to about 6.5
- Fire Rate: Raises fire rate from 0.5 to 0.8

## Why / Balance

The baseline PKA has really powerful stats that outclass most of its contemporaries. Decent damage, infinite ammo, and high range make it a forgiving and easy choice for salvagers but also make it better than actual guns and higher-level melee weapons in a lot of scenarios. Bringing the stats down a little bit carves out a bit of a niche for the PKA where it's less of an outright gun and more of a mid-range kiting option, which is a lot more interesting of an archetype.

Of course, dangerous monsters make strong ranged options necessary to an extent, so to facilitate this and to encourage collaboration with science, the modkits can serve as ways to make the PKA more viable. This gives the weapon a bit of a progression which makes it a more unique item for salvage while also giving them more of a reason to work with science in order to unlock the tech.

## Media

![image](https://github.com/user-attachments/assets/de12f40f-4490-4577-9ea5-dbd57ba84f02)
![image](https://github.com/user-attachments/assets/e62b41e8-b15b-4d80-b9a0-72cafff4833f)
![image](https://github.com/user-attachments/assets/c1b55d69-e9cd-4cef-9fb1-527e27bc277a)

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added 3 modkits for the proto-kinetic accelerator, granting increased damage, range, and fire rate. They can be researched via the new "Kinetic Modifications" arsenal tech.
- tweak: Reduced damage and range on the proto-kinetic accelerator.

2024-08-21 05:37 UTC, sad2284 commented
By the time the RND studies this, the shift will have time to end

2024-08-21 09:16 UTC, Boaz1111 commented
> By the time the RND studies this, the shift will have time to end. As for me, it is better to move it by 1

Not really, no. This can be researched very fast, most arsenal techs aren’t that expensive, and you’d just need to take enough to unlock arsenal t2, and click it when it comes up

2024-08-21 09:20 UTC, deltanedas commented
nobody gets arsenal techs outside of warops so it would still be one of the last techs unlocked in a round, salv can buy real guns instead of begging sci to get t2 of an entire discipline they didnt touch

2024-08-21 09:23 UTC, Boaz1111 commented
> nobody gets arsenal techs outside of warops so it would still be one of the last techs unlocked in a round, salv can buy real guns instead of begging sci to get t2 of an entire discipline they didnt touch

To unlock a new tier you need 75% of the previous tier researched. Science currently has 8 arsenal T1 techs, so you’d need 6. The cheapest way to do that only costs 38000 points, which is nothing. If it helps salvage get more ores for science, I know for a fact this will be researched at the request of salvage.

2024-08-21 10:33 UTC, Savsj commented
This is a ok nerf with solid changes, i personally dont know how i feel about the range nerf but its aleays something that can be adjusted and this solves every complaint i had about the PKA nerf. Plus this adds the ground floor to start doing some more interesting things with the PKA later.

2024-08-21 14:22 UTC, engineer-pearl commented
I guess there's a bit of "see how it goes" and "skill issue", but I'm worried that the accompanying nerf may make it so there are no ores for anyone.

Can we get something to help less experienced salvs survive on asteroids closer to round start?

2024-08-21 15:21 UTC, Ilya246 commented
yes nobody gets arsenal tech, sci will never actually make the modkits unless they're easy to research (t1)

salv will just end up buying guns and never caring about PKAs, and i think both the baseline and rangekit ranges on the PKA are bad, reminder that ping is a thing and might cause enemies to be able to melee you while you see them as 4 tiles away

2024-08-21 16:51 UTC, sad2284 commented
> > К тому времени, когда RND изучит это, сдвиг успеет закончиться. Как по мне, лучше сдвинуть его на 1
> 
> Не совсем, нет. Это можно исследовать очень быстро, большинство технологий арсенала не так уж и дороги, и вам просто нужно взять достаточно, чтобы разблокировать арсенал t2, и нажать на него, когда он появится

Even if the RND is speedrun, it will be studied in about 40-60 minutes. By that time, the scraps will have time to get hold of larger guns and they will simply not ask the RND for improvements. But knowing the players on the RND, there is a high risk that they will not learn a even in 2 hours of shifting

2024-08-21 18:00 UTC, a-person5660 commented
This needs to either be a t1 tech or be in the industrial tree along with the other salvage technology. I just don't see it bring researched frequently enough if its a t2 sec tech.

2024-08-21 18:55 UTC, Ilya246 commented
the range is likely still too small even with the range modkit, salv *will* just buy lasers, steal a recharger, and blast fish from a distance with them

2024-08-21 18:56 UTC, Emisse commented
thats fine

2024-08-22 06:32 UTC, Ilya246 commented
> thats fine

then we're effectively removing the PKA from the game as it'd be not a viable option outside of very specific circumstances anymore, and even with the modkits it seems only barely viable

additionally, the modkits cost *gold and silver* and they're something you will want many of, so that would add quite a bit more to how rarely they are made

2024-08-22 18:15 UTC, Savsj commented
After playing some salvage myself yesterday, I am inclined towards saying the range nerf is a step too far at all. I believe the damage fine and the rate of fire upgrade will be really fun. But as it stands with no good way to actually get a better hardsuit now because wrecks were anonymized, and that means theres also no reliable way anymore to get a better weapon THAN the PKA anymore, because from a mechanical standpoint yes they can just get lasers and be fine, but from an RP level it will never be allowed unless theres more chamges made to space law to accomadate for this. The cost of the upgrades is also i believe a reasonable concern, because now its 1:1 on ore mining is now even more time consuming and less enjoyable, the cost increase on materials aswell means that ive seen material shortages on stations where all a salvage team is doing is mining, i dont think that needs to be reverted but oulling it back would probably be a decent idea. And i agree that while it isnt that hard to get tier 2 arsenal research, it feels a little strange to me it isnt being bundled with the rest of the cargo stuff in industrial. I think this is a positive step in the right direction over all but given the recent additions of new salvage enemies i think we need tonreadjust scope.

2025-04-05 02:54 UTC, EmoGarbage404 commented
merge conflicts have been resolved. Hopefully a decision can be reached since this PR has been labeled as "in discussion" for the past *squints* 2 1/2 months.

2025-04-06 20:03 UTC, slarticodefast reviewed
Just had a quick look so far.
Might also be worth considering using something like this PR does instead
https://github.com/space-wizards/space-station-14/pull/35539
since it is less hardcoded to gun stats and there is overlap in its use

2025-04-06 20:25 UTC, Pronana commented
I worry about the balancing of this PR. The nerfs to the PKA are pretty significant which isn't too if you're dealing with carp and xenos and does encourage salvagers to use their crusher weapons more. 

However, the VGRoid is a different story, mostly with hivelords. Hivelords are fast and spawn way more enemies than the PKA can deal with. (Spawns them with a firerate of 0.66 while the PKA fires at 0.5) This adds skill to fighting them as you need to kite and target the Hivelord directly, which was fine when they only took three shots to take down. 

However, the nerfs to the PKA mean they will now take five shots to kill, and you have to be within 4 tiles of them which makes them significantly more dangerous in a way that I don't think will end up being fun to play around as it guarantees you'll be taking a lot of bleed and slashing damage if you see one due to them being faster than you, your range now being way smaller, and them taking way more hits to actually put down.

I feel like this doesn't mean that the nerfs to the PKA should be reduced, rather that the VGRoid enemies need to be rebalanced around these changes. People already don't go to the VGRoid because it's a pain to get to with a decent bit of risk and this PR could make that problem worse when we want more salvagers to be going to the VGRoid more often.

2025-04-07 06:06 UTC, walksanatora commented
as a salv player I basically never go to VGRoid. if I have a space capable sh(u/i)ttle. I am going on a exped. where the rocks are softer and the loot is plentiful.

2025-04-10 00:23 UTC, RedBookcase commented
Coming in to give my own two cents on the issues raised.

Overall I like the PR conceptually and I agree outright with a lot of the changes (Nerfing base PKA stats, improving/restoring them by getting modkits, making the PKA a 2x3), all pretty good ideas.

Pronana mentioned the concern about fighting hivelords using the PKA, and personally I don't see that in particular being too much of a problem. I personally prefer to just go in for melee on hivelords, the Crusher Dagger still mops the floor with them and their spawn even with the incoming damage nerf.

I do have three specific concerns, though.

1) Research level. Is this still a level 2 research? If so, I do agree that it should be brought down to level 1. This is a change that could definitely wait until the PR gets merged to gather more info/see how it goes, but I do think that making it level 2 might end up gating it from salvage more often and just generally cause more frustration with the process. Alternatively, it could be kept at level 2, and pka mods could be added on as debris/vgroid loot, in much the same way you can find mineral scanners and handheld mass scanners.

2) I think that a 4 tile range may just be a bit too severe overall. I would certainly need to play with this nerf for a while before saying for certain, but I can definitely think of a number of times on salvage where having a PKA with that small of a range would be, if not life-threatening, exceptionally annoying (thinking about killing carp on debris here, especially). I think that if the range remains this small, the range upgrade is going to become a must-have for pretty much anyone seeking to use the PKA regularly, which makes for less interesting choices when picking out mods and limits player freedom.

3) Does this PR fix the current bug regarding PKA examination? I'm guessing not, given the screenshots. Due to the way the PKA and it's ammo are coded, you can't examine a PKA to see how much damage it does, which has always been a problem but would only become worse if we introduce a damage upgrade into the game. Players having less information and feedback on the tools they're using is always a negative.

2025-04-25 03:04 UTC, ArtisticRoomba requested changes
Code looks cool and good, testing went well. This blocker is here to remind you to implement a popup to show that the user successfully inserted an upgrade.

2025-04-25 17:43 UTC, ArtisticRoomba approved these changes
This PR has been given the seal of approval by the coalition of good salvage players.

2025-04-25 18:18 UTC, merged

2025-04-25 18:36 UTC, kosticia commented
Amen🙏

2025-04-26 19:00 UTC, TytosB commented
bad way to implement modkits, even with a damage and range modkit the pka is only just as good as it was before, so this is effectively just a pka nerf where to get pka thats actually half decent you need sci tech items. the pka did not need a nerf, 25 damage was balanced by its abysmal fire rate.