Moved temperature to shared
space-wizards/space-station-14 pull request #31249
Opened 2024-08-21 04:04 UTC by Jezithyr

## About the PR

Moved Temperature component, ThermalRegulator component and most of the implementation of temperature, thermal regulation and heater systems to Content.Shared. This will allow shared content to interact with TemperatureComponent without requiring a ServerSide implementation. This *does not* implement predicted temperature, it only networks the component states.

## Why / Balance

No visible changes for players. This was done to make working with temperature in shared systems easier.

## Technical details

Simply moved temperature, thermal regulation and heater systems to shared along with their associated components. I also networked the components to make sure that the data is accessible on the client as well. I did not implement prediction since temperature interacts with atmospherics which is a purely server-side system and would make prediction more difficult. Values on temperature related components are calculated on the server and then networked to the clients.

## Media

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Namespace changes:
```
ThermalRegulatorComponent: Content.Server.Body.Systems -> Content.Shared.Body.Systems
ChangeTemperatureOnCollideComponent: Content.Server.Temperature -> Content.Shared.Temperature
ContainerTemperatureDamageThresholdsComponent: Content.Server.Temperature -> Content.Shared.Temperature
EntityHeaterComponent: Content.Server.Temperature -> Content.Shared.Temperature
InternalTemperatureComponent: Content.Server.Temperature -> Content.Shared.Temperature
TemperatureComponent: Content.Server.Temperature -> Content.Shared.Temperature
TemperatureProtectionComponent: Content.Server.Temperature -> Content.Shared.Temperature
```

Obsolete methods:
```
public void ForceChangeTemperature(EntityUid target, float temp, TemperatureComponent? temperature = null)
public float GetHeatCapacity(EntityUid uid, TemperatureComponent? comp = null, PhysicsComponent? physics = null)
public void ChangeHeat(EntityUid uid, float heatAmount, bool ignoreHeatResistance = false, TemperatureComponent? temperature = null)
```
**Changelog**

2024-08-21 09:42 UTC, slarticodefast commented
I think this one is a duplicate of #30511
Not sure if it includes all the same files though.

2024-08-21 12:11 UTC, deltanedas commented
crusher dagger disgustingly op

2024-08-22 03:39 UTC, Jezithyr commented
> I think this one is a duplicate of #30511 Not sure if it includes all the same files though.

I totally forgot about that one 😅 
That said, this implementation puts less networking load on the server (Temperature components aren't being dirtied every tick only when they actually get changed)

2024-08-22 09:57 UTC, metalgearsloth requested changes

2024-08-22 09:57 UTC, metalgearsloth commented on Content.Server/Temperature/Systems/EntityHeaterSystem.cs
> +        Appearance.SetData(heater, EntityHeaterVisuals.Setting, setting);
Sussy null suppression because this can cause nullrefs and isn't guaranteed to exist.

2024-08-22 09:57 UTC, metalgearsloth commented on Content.Shared/Temperature/Components/EntityHeaterComponent.cs
>  public sealed partial class EntityHeaterComponent : Component
Needs NetworkedComponent also it's being dirtied but there's nothing actually being synced.

2024-08-22 09:57 UTC, metalgearsloth commented on Content.Shared/Temperature/Components/InternalTemperatureComponent.cs
>  public sealed partial class InternalTemperatureComponent : Component
Needs NetworkedComponent

2024-08-22 09:57 UTC, metalgearsloth commented on Content.Shared/Temperature/Components/TemperatureComponent.cs
> +    [DataField, ViewVariables(VVAccess.ReadWrite), AutoNetworkedField]
VVRW unnecessary on datafields.

2024-08-22 09:57 UTC, metalgearsloth commented on Content.Shared/Temperature/Systems/SharedTemperatureSystem.cs
> +
Was going to comment this breaks persistence but it was already like this so.

2024-08-22 09:57 UTC, metalgearsloth commented on Content.Shared/Temperature/Systems/SharedTemperatureSystem.cs
> +        var thresholdsQuery = GetEntityQuery<ContainerTemperatureDamageThresholdsComponent>();
Can move these to the system.

2024-10-15 12:20 UTC, Mishics commented
Hey, when will you continue working? Or someone on vacation... Just wondering, nothing more

2024-11-08 03:43 UTC, Mishics commented
> > Я думаю, что это дубликат #30511. Не уверен, что он содержит все те же файлы.
> 
> Я совсем забыл об этом 😅 Тем не менее, такая реализация снижает сетевую нагрузку на сервер (компоненты температуры не обновляются каждый тик, а только при фактическом изменении)

If you think about it, how soon can you temperature refactor ?

2024-12-26 22:26 UTC, Jezithyr commented
Due to various reasons I have decided to no longer directly be involved 
with the development of wizden, and as such I will be closing this PR.

If someone else wishes to take up/re-open this PR and continue developing it, 
they have my permission to do so. 

A more in depth explanation can be found here: https://discord.com/channels/310555209753690112/770682801607278632/1321967056446554174.

2024-12-26 22:26 UTC, closed without merging