Added Space Carp Tooth Arrows and Sharkminnow Spears, buffs sharkminnow teeth.
space-wizards/space-station-14 pull request #31257
Opened 2024-08-21 11:38 UTC by Boaz1111

## About the PR

I added space carp tooth arrows, made from 1 rod, 1 cloth and one space carp tooth. They deal 35 piercing damage. Open to nerf it to 30. I also added a sharkminnow spear, made from 2 rods, 3 lv cables and one sharkminnow tooth. This weapon deals 22 piercing damage when wielded, and 25 piercing damage when thrown. It breaks in the same amount of throws as normal spears. Also, I made the sharkminnow tooth deal 15 damage in melee, as requested by Emo
## Why / Balance

Seeing as salvage weapons are being nerfed, and these teeth were recently added, I figured I'd get started on unique crafting recipes for mob loot. Discussed with Emo and Flare over discord, eventually ended up with these two weapons. I doubt they will be used much on-station, although I do see a potential warops scenario where salvage goes hunting for carp teeth to make cool arrows. Off-station however, I believe they will be rather useful. 
## Technical details

## Media

![weapons](https://github.com/user-attachments/assets/78083bf3-4d9b-4f06-81b7-182e6bbfd352)
![spear](https://github.com/user-attachments/assets/472f3b88-fa06-477b-9049-a06dba1db513)
![arrow](https://github.com/user-attachments/assets/00d12acd-5015-4994-b38b-40ba17a793c2)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added sharkminnow tooth spears and carp tooth arrows. Happy salvaging!
- tweak: Sharkminnow teeth now deal 15 damage instead of 10.

2024-08-21 11:39 UTC, Boaz1111 commented
also, the arrow tails are purple because salvage has purple as one of their colors, I wanted to distinguish the arrows from regular arrows and brown looked ugly

2024-08-21 19:09 UTC, Emisse commented
these are super overtuned but i dont really see people crafting these out the gate if they arent, probably should be taken more in line with other things tho

2024-08-21 21:05 UTC, Boaz1111 commented
> these are super overtuned but i dont really see people crafting these out the gate if they arent, probably should be taken more in line with other things tho

Apart from the throwing the spear is the same as the plasma spear

2025-04-24 00:24 UTC, MilonPL requested changes
\+ EOF newline

2025-04-24 00:24 UTC, MilonPL commented on Resources/Prototypes/Recipes/Construction/Graphs/weapons/spear.yml
> +      entity: SpearSharkMinnow
Remove indent.

2025-04-24 00:24 UTC, MilonPL commented on Resources/Textures/Objects/Weapons/Melee/sharkminnow_spear.rsi/meta.json
4 spaces not 2

2025-04-29 16:24 UTC, EmoGarbage404 commented
Pushed changes and addressed reviews. Will merge once tests pass.

2025-04-29 16:36 UTC, merged