Add loadout names
space-wizards/space-station-14 pull request #31303
Opened 2024-08-22 10:41 UTC by metalgearsloth

From AI branch nothing using it atm but open to suggestions. DB migrations so requires contrib ping (the pgsql one may be breaking).

2024-08-22 11:36 UTC, ilyamikcoder commented
if i understand correctly that this is the pr about allowing to set separate character names in loadouts, then i suggest that clowns, mimes and borgs get this functionality

2024-08-22 11:57 UTC, DogZeroX commented
That's the whole point

2024-08-30 15:39 UTC, Everturning commented
add this to musicians maybe?
they could have like a stage name, like slim shady or something like that

2024-09-05 07:40 UTC, AverageNotDoingAnythingEnjoyer commented
@metalgearsloth , how's the progress?

2024-09-09 00:55 UTC, LaOubliette commented
I fucking beg please

2024-10-02 15:51 UTC, PJB3005 commented on Resources/Locale/en-US/preferences/loadouts.ftl
> +loadout-name-edit-tooltip = 32 characters max. If no name is specified a random one may be chosen for you.
unhardcode

2024-10-02 15:53 UTC, PJB3005 reviewed
I'll fix conflicts and the one nit I guess

2024-10-02 16:24 UTC, PJB3005 requested changes
Diff seems to be missing changes for the DB model, I'm assuming this is in error due to the DB migrations being present

2024-12-24 02:43 UTC, PJB3005 commented
Is this ready for review or can it be made a draft? I don't see the DB side anymore.

2025-02-11 13:02 UTC, metalgearsloth commented on Resources/Prototypes/Loadouts/role_loadouts.yml
> +#  canCustomizeName: true
Borgs use dataset but AI is localized dataset so the choice was either update borgs to use it or make it compatible with both (which seemed skrunkly).

2025-02-11 17:30 UTC, PJB3005 approved these changes

2025-02-11 17:30 UTC, merged

2025-02-14 19:14 UTC, lzk228 commented on Resources/Prototypes/Loadouts/role_loadouts.yml
> +#  canCustomizeName: true
wait, doesn't localized dataset does the same thing as default dataset and in result they are both the same?

2025-02-15 19:16 UTC, VasilisThePikachu commented
In the future please fill out the pr template as i had to dig what this does in the maintainer meeting. Or at least provide some screenshots