Spray painter update
space-wizards/space-station-14 pull request #31328
Opened 2024-08-22 21:33 UTC by Ertanic

## About the PR

Adds the ability for the spray painter to color other things. Plans are in the works to add the ability to paint decals.

## Why / Balance

Maybe someone could use it, particularly engineers.

## Technical details

PaintableAirlockComponent has been renamed to PaintableComponent, like AirlockGroupPrototype to PaintableGroupPrototype and slightly extended to achieve more versatility. 

To add new tabs to the spray painter it is enough to add a PaintableComponent to the prototype and specify the corresponding PaintableGroupPrototype ID. The PaintableGroupPrototype contains a category (tab; I will replace it with prototype a little later) and a dictionary, where the key is the name of the style (it should be common for other groups, if you want to be able to paint different types of objects); the value is the name of the prototype, which will be used for displaying in the UI and then used for repainting.

## Plans

- [ ] Replace category with prototype.
- [ ] Add the usual closets and canisters.
- [ ] Add localization to styles.
- [ ] Add the ability to paint decals.
- [ ] Maybe make saving the tab where the spray painter window was closed.

## Media

https://github.com/user-attachments/assets/e6876044-26cb-4429-9481-5e452c657784

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Spray painter can now paint airlocks, lockers and crates.

2024-08-22 22:48 UTC, lzk228 commented
just a suggestion for localizing without hardcoding
is it possible and will it be good to make prototypes like this
```yaml
stylePaths:
    paintable-group-atmospherics: AirlockAtmospherics
    paintable-group-basic: Airlock
    paintable-group-cargo: AirlockCargo
    paintable-group-command: AirlockCommand
 ```
 and then just use locale in ftl
 ```fluent
 paintable-group-atmospherics = Atmospherics
 paintable-group-basic = Basic
 paintable-group-cargo = Cargo
 paintable-group-command = Command
 ```
 in that case locale isn't hardcoded and loadprototype can be used without any problems

2024-08-23 12:31 UTC, dvir001 commented
Can we also get some new way for detective to scan the entity to know it has paint on it?

2025-03-16 15:20 UTC, Ertanic commented
At heart, I don't know why other systems might have broken down.....

2025-03-17 18:22 UTC, SpeltIncorrectyl commented
Seems like a very good idea.
Only issue I can see is people spray-painting normal lockers to look like sec lookers to try and troll sec.
I can imagine the mime spray-painting their own locker and then dragging it around the station.

2025-03-24 13:37 UTC, Quantum-cross commented
I'm not the biggest fan of the spray painter requiring ammo as I already feel like it's an underutilized item, but I love the other changes.

2025-04-01 05:33 UTC, Djungelskog2 commented
This is gonna be a pretty funny way to inconspicuously steal the captains locker

2025-04-05 01:06 UTC, SpeltIncorrectyl commented
I've thought about it and I don't think this is a good idea anymore.
Spraypainting doors is fine because doors don't move. If the doors leading to the bridge look like maintenance doors, you still know they are command doors from your map knowledge.
But lockers can move. If a locker can be repainted into any other locker, then the painting cannot be trusted and becomes meaningless.

Is that sec locker dragged by the mime actually a sec locker? Or is it just their mime locker repainted? Or maybe it's even the captain's locker repainted as a sec locker. Is the captain locker in captain's room the real locker? It looks like it, but can you really trust that?

Would be fun for the person with the spraycan and hell for sec.

2025-04-07 07:23 UTC, JackTalentedCoder commented
Dude... Im not maintainer nor contributor, but this is must have!!!!

2025-04-15 00:36 UTC, metalgearsloth commented on Content.Client/Atmos/EntitySystems/GasCanisterAppearanceSystem.cs
> +
You can get comp data directly from prototypes.

2025-04-26 20:16 UTC, daevidos commented
I like this PR a lot. I feel like making it so you can only paint unlocked lockers would fix some of the issues mentioned above. Rationale for this being that the locker also has to be painted inside. Repainting captains locker to make it not be suspicious would no longer be a problem as long as the thief doesn't have the access to open it but at that point i think they deserve it.

2025-04-28 01:28 UTC, whatston3 commented on Content.Shared/SprayPainter/PaintedSystem.cs
> +    }
Instead of doing this, couldn't you check the current time vs. when it was painted in the examine?

2025-04-28 14:14 UTC, whatston3 commented on Content.Shared/SprayPainter/PaintedSystem.cs
> +    }
You're only using this currently to say whether or not something was freshly painted in the examine menu.  Why have an Update loop?

You could remove the Update loop and put a check on the current time in your examined event, only push the "freshly painted" message if the paint event happened less than 15 minutes ago.

2025-05-02 20:17 UTC, sowelipililimute requested changes
first go-over

2025-05-03 04:12 UTC, Ertanic commented on Content.Client/Storage/Visualizers/EntityStorageVisualizerSystem.cs
> +                    continue;
Without this, a visual bug occurred.

2025-05-03 04:14 UTC, Ertanic commented on Content.Server/SprayPainter/SprayPainterSystem.cs
> +        Del(dummy);
Some objects break down into a version before painting when broken. This is necessary so that the breakage has the correct appearance.

2025-05-03 04:24 UTC, Ertanic commented on Content.Client/SprayPainter/UI/SprayPainterDecals.xaml
> +            <Button Text="+90°" Name="AddAngleButton" />
Why?

2025-05-03 04:52 UTC, sowelipililimute commented on Content.Client/SprayPainter/UI/SprayPainterDecals.xaml
> +            <Button Text="+90°" Name="AddAngleButton" />
different locales use different numbers

2025-05-03 05:13 UTC, Ertanic commented on Content.Client/SprayPainter/UI/SprayPainterDecals.xaml
> +            <Button Text="+90°" Name="AddAngleButton" />
Let them use what the Arabs invented.

2025-05-03 06:51 UTC, Deserty0 commented on Content.Client/SprayPainter/UI/SprayPainterDecals.xaml
> +            <Button Text="+90°" Name="AddAngleButton" />
> different locales use different numbers

who use rome numbers 😭

2025-05-07 00:55 UTC, sowelipililimute requested changes

2025-05-07 00:55 UTC, sowelipililimute commented on Content.Client/SprayPainter/SprayPainterSystem.cs
>  }
these could be record structs

2025-05-07 00:55 UTC, sowelipililimute commented on Content.Client/Storage/Visualizers/EntityStorageVisualizerSystem.cs
> +                    continue;
can you elaborate on the nature of the bug and maybe fix it/file an issue for later? if not, can you dehardcode this? if none of the above, add a comment explaining exactly why this is here

2025-05-07 00:55 UTC, sowelipililimute commented on Content.Server/SprayPainter/SprayPainterSystem.cs
> +        }
is this needed? this just looks like a copypaste from the crayon system which seems to be the only place in the codebase to do this

2025-05-07 00:55 UTC, sowelipililimute commented on Content.Shared/Atmos/Components/GasCanisterComponent.cs
> +    public sealed partial class GasCanisterComponent : Component, IGasMixtureHolder
doesn't seem resolved?

2025-05-07 00:55 UTC, sowelipililimute commented on Content.Shared/SprayPainter/Components/PaintedComponent.cs
> +    public TimeSpan RemoveTime;
unresolved

2025-05-07 00:55 UTC, sowelipililimute commented on Resources/Locale/en-US/spray-painter/spray-painter.ftl
> +spray-painter-style-airlocks-salvage      = Salvage
not resolved

2025-05-07 00:55 UTC, sowelipililimute commented on Resources/Prototypes/Entities/Structures/Storage/Canisters/canister_groups.yml
> +    frezon:                FrezonCanister
still not resolved

2025-05-07 00:55 UTC, sowelipililimute commented on Content.Client/SprayPainter/UI/SprayPainterDecals.xaml
> +            <Button Text="+90°" Name="AddAngleButton" />
not resolved

2025-05-07 00:55 UTC, sowelipililimute commented on Resources/Prototypes/Entities/Structures/Storage/Closets/lockers_groups.yml
> +    scientist:      LockerScientist
not resolved

2025-05-07 19:27 UTC, slarticodefast commented on Content.Client/SprayPainter/UI/SprayPainterDecals.xaml
> +            <Button Text="+90°" Name="AddAngleButton" />
Please resolve the requested changes or this PR won't be merged. Localization is a requirement for all new code.

2025-05-10 17:26 UTC, sowelipililimute commented on Content.Client/Atmos/UI/GasCanisterBoundUserInterface.cs
> -using Robust.Client.GameObjects;
extraneous change

2025-05-10 17:27 UTC, sowelipililimute commented on Content.Client/Atmos/Piping/Unary/Systems/GasCanisterSystem.cs
>  using Content.Shared.Atmos.Piping.Unary.Systems;
extraneous change

2025-05-10 17:30 UTC, sowelipililimute commented on Content.Client/Doors/DoorSystem.cs
> +        }
once again wondering why we need to overwrite the RSI of every layer individually instead of updating the base RSI of the sprite component

2025-05-10 17:32 UTC, sowelipililimute commented on Content.Client/Storage/Visualizers/EntityStorageVisualizerSystem.cs
> +                    continue;
please stop marking comments as resolved without addressing the feedback

2025-05-10 17:34 UTC, sowelipililimute commented on Content.Server/SprayPainter/SprayPainterSystem.cs
> +        }
i'm assuming that's a yes? again, if i ask a question i would appreciate a reply instead of resolving silently

2025-05-10 17:37 UTC, sowelipililimute commented on Content.Shared/Atmos/Components/GasCanisterComponent.cs
> +    public sealed partial class GasCanisterComponent : Component, IGasMixtureHolder
once again, still not resolved. if you need help or elaboration, feel free to ask here or on the discord

2025-05-10 17:38 UTC, sowelipililimute commented on Content.Shared/SprayPainter/Components/PaintedComponent.cs
> +    public TimeSpan RemoveTime;
please address the requested changes

2025-05-10 17:40 UTC, sowelipililimute commented on Resources/Locale/en-US/spray-painter/spray-painter.ftl
> +spray-painter-style-airlocks-salvage      = Salvage
please address the requested changes

2025-05-10 18:11 UTC, Ertanic commented
Please stop spamming about nothing, some of which I've even fixed already.

2025-05-10 21:24 UTC, slarticodefast commented
@Ertanic 
Since you are not interested in addressing the requested changes I will be closing this PR.
Maybe someone else can pick it up.
Also please stay respectful towards maintainers, we are doing these code reviews in our free time. If you don't want your code reviewed, there are plenty of other contributors who do.

2025-05-10 21:24 UTC, closed without merging