Add pickaxes to Engi-Vend for easier meteor repair
space-wizards/space-station-14 pull request #31325
Opened 2024-08-22 19:09 UTC by AutoOtter

## About the PR
This PR adds 2 pickaxes to the engi-vend inventory to better equip engineers to respond to meteor strikes.
## Why / Balance
The recent frequency of meteor strikes makes it necessary for engineering to find mining tools to remove unwanted rubble, however getting said tools from QM can be iffy and takes time. Providing engineering with a few pickaxes lets them fix holes faster and lets whoever got their work blown up get back to the game.

## Technical details
Added 2 pickaxes to the end of engivend.yml

## Media

https://github.com/user-attachments/assets/5742aeda-7e19-4e59-a8cd-bfbfbc48ec32

## Requirements
Due to influx of PR's we require to ensure that PR's are following the correct guidelines.
- [X ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ X] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**
:cl:
- add: Added Pickaxe to Engi-Vend for meteor repair technicians!

2024-08-22 19:44 UTC, Krovotushka commented
I think science exists for a reason, engineers can even print themselves some pickaxes roundstart

2024-08-22 20:00 UTC, Ilya246 commented
you can use baseball bats to mine in like 2 hits

also the axe

2024-08-22 20:02 UTC, Emisse commented
realistic solution is to make meteor rock break without pickaxe easier

2024-08-22 20:03 UTC, Ilya246 commented
maybe make meteor rock some kind of "brittle rock" which falls apart if you stare at it too hard

2024-08-22 20:05 UTC, Cojoke-dot commented
> I think science exists for a reason, engineers can even print themselves some pickaxes roundstart 

Meh, nobody has roundstart wood so you either have to go maints diving, break stuff people like, or wait for bio to grow stuff. For an event as common as meteors and rock anoms, I think it would be nice.

2024-08-22 20:11 UTC, Krovotushka commented
> > I think science exists for a reason, engineers can even print themselves some pickaxes roundstart
> 
> Meh, nobody has roundstart wood so you either have to go maints diving, break stuff people like, or wait for bio to grow stuff. For an event as common as meteors and rock anoms, I think it would be nice.

This game is about interactions with others, you can ask science to research mining drills, which is super easy to do, ask atmos technician to give you fire axe for a minute, ask salvagers to give you atleast one of their pickaxes, ask cargo to order thar salvage vend restock and there is more and more of ways to obtain something to break meteors with in first 20 minutes of shift

2024-08-23 00:53 UTC, EthanQix commented
> > I think science exists for a reason, engineers can even print themselves some pickaxes roundstart
> 
> Meh, nobody has roundstart wood so you either have to go maints diving, break stuff people like, or wait for bio to grow stuff. For an event as common as meteors and rock anoms, I think it would be nice.

Alternatively, ask botany for some wood at round start so you can print some pickaxes once it's grown. Or ask salvage for a pickaxe as they usually have a couple extra. No department is supposed to be self-sufficient.

2024-08-23 01:13 UTC, AutoOtter commented
> > > I think science exists for a reason, engineers can even print themselves some pickaxes roundstart
> > 
> > 
> > Meh, nobody has roundstart wood so you either have to go maints diving, break stuff people like, or wait for bio to grow stuff. For an event as common as meteors and rock anoms, I think it would be nice.
> 
> This game is about interactions with others, you can ask science to research mining drills, which is super easy to do, ask atmos technician to give you fire axe for a minute, ask salvagers to give you atleast one of their pickaxes, ask cargo to order that salvage vend restock and there is more and more of ways to obtain something to break meteors with in first 20 minutes of shift

I understand where you're coming from, but in my gameplay experience, atmos is busy using the axe for meteors that hit them and salv is gone with most of their equipment. This means both engi and whoever got hit are stuck looking for something that'll help while more meteors hit other places.  Long story short, the quality of life improvements outweigh the RP losses.

2024-08-23 02:19 UTC, thebadman4662 commented
> ask salvagers to give you atleast one of their pickaxes

Same salvagers that steal half of cargo vends leaving nothing behind never to be seen again?

2024-08-23 06:08 UTC, Ilya246 commented
> > ask salvagers to give you atleast one of their pickaxes
> 
> Same salvagers that steal half of cargo infrastructure leaving nothing behind never to be seen again?

remove the reclaimer problem solved

2024-08-25 07:27 UTC, UbaserB requested changes
Instead of adding pickaxes to the Engi-Vend, please make the meteor rock (in _specific_) easier to destroy so that engineers don't need special tools for removing it out of the way.

2024-08-25 20:40 UTC, closed without merging