make tesla brighter
space-wizards/space-station-14 pull request #31357
Opened 2024-08-23 10:34 UTC by qwerltaz

## About the PR

I propose making tesla and small balls lightning brighter.

From testing out, any pop-ins at all due to pvs are very rare and small.

## Why / Balance

Super spooky, good. And it's a giant ball of lightning after all!

## Media

https://github.com/user-attachments/assets/687a0e84-80a7-4ba4-8291-f7e3446f5c9e

tesla and miniballs difference

![before-after](https://github.com/user-attachments/assets/7da24533-8f7e-43d6-a1c8-be30891f0613)

![horror](https://github.com/user-attachments/assets/93dd0438-7cfc-4e32-8341-75f2f25583e3)

made mini ball slightly brighter too

![mini ball](https://github.com/user-attachments/assets/5b336ce2-23ec-4201-9c59-a0d5130b404b)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Made tesla a lot brighter.

2024-08-23 10:41 UTC, Krovotushka commented
Moth players on their way to suicide to tesla ball

2024-08-23 16:16 UTC, mierdapovareshka commented
бля чё это за говно ебаное

2024-08-26 15:00 UTC, UbaserB requested changes
After internal discussion and testing, we've found that the pvs pop-ins are too severe so please lower the radius so it's not higher than the pvs range.

2024-09-04 14:47 UTC, UbaserB approved these changes

2024-09-04 14:47 UTC, merged