Fix matchstick prediction issues
space-wizards/space-station-14 pull request #31418
Opened 2024-08-25 05:30 UTC by beck-thompson

## About the PR

Matchstick was always miss predicting getting inserted into a container. There was an outdated method that I fixed as well.

## Technical details

The only sussy thing I had to do was always make the event handled if a matchstick is used on a matchbox. If you don't do that and check for it being lit and then making it list if its not, it starts misrepresenting on the second round because the match becomes lit and the event wouldn't be handled.

![image](https://github.com/user-attachments/assets/cf811a0c-f273-4a9d-8311-261439fd76c1)
\* This works the first time but the second time it will never trigger so it won't get handled and gets inserted.

## Media

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2024-08-25 05:38 UTC, Winkarst-cpu commented
Oh, I think you need to update yml of matches too...

2024-08-25 05:44 UTC, beck-thompson commented
Your right but I have no idea why its failing... Isn't the default variable name lowercase? It was:
`[DataField("duration")]` but the name was still just `Duration` which should default to the same thing?

2024-08-25 05:46 UTC, Winkarst-cpu commented
Try removing read-only access, I don't know.

2024-08-25 05:48 UTC, Winkarst-cpu commented
Uh... The old one was read-only too...

2024-08-25 06:36 UTC, beck-thompson commented
OK we couldn't figure out why it always fails when the datafield names are removed (Even when the names would still work...). Just leaving them there!

2024-09-20 11:43 UTC, metalgearsloth requested changes

2024-09-20 11:43 UTC, metalgearsloth commented on Content.Server/Light/EntitySystems/MatchstickSystem.cs
>                  return;
Return means this will terminate the entire method if any single match is not on a grid.

2024-09-20 11:43 UTC, metalgearsloth commented on Content.Shared/Lightning/Components/MatchboxComponent.cs
> +}
Needs networking.

2024-09-20 11:43 UTC, metalgearsloth commented on Content.Shared/Lightning/Components/MatchstickComponent.cs
> +
Needs autopausedfield.

2024-09-20 11:43 UTC, metalgearsloth commented on Content.Shared/Lightning/EntitySystems/MatchboxSystem.cs
> +{
file-scoped namespaces.

2025-04-06 14:17 UTC, slarticodefast requested changes

2025-04-06 14:17 UTC, slarticodefast commented on Content.Server/Light/EntitySystems/MatchstickSystem.cs
> +using Content.Shared.Light.EntitySystems;
not in alphabetic order 😢

2025-04-06 14:17 UTC, slarticodefast commented on Content.Server/Light/EntitySystems/MatchstickSystem.cs
> +            var burnoutTime = match.TimeMatchWillBurnOut;
why assign this as a variable if you only use it once?

2025-04-06 14:17 UTC, slarticodefast commented on Content.Server/Light/EntitySystems/MatchstickSystem.cs
> +                match.TimeMatchWillBurnOut = null;
do we have to set it to null?
shouldn't the state check at the beginning already do the same?
Also it might make sense to do the visuals in shared so they are predicted, and only keep the hotspot in the server, but that is not a blocker

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/Components/MatchboxComponent.cs
> +public sealed partial class MatchboxComponent : Component
can you add documentation to the component?

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/Components/MatchstickComponent.cs
> +    [DataField("duration")]
```suggestion
    [DataField, AutoNetworkedField]
```

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/Components/MatchstickComponent.cs
> +    public TimeSpan? TimeMatchWillBurnOut = null;
needs time offset serializer

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/Components/MatchstickComponent.cs
> +    [DataField("igniteSound", required: true)] public SoundSpecifier IgniteSound = default!;
```suggestion
    [DataField]
    public SoundSpecifier? IgniteSound = null;
```
just make it nullable

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/EntitySystems/MatchboxSystem.cs
> +public sealed class SharedMatchboxSystem : EntitySystem
```suggestion
public abstract partial class SharedMatchboxSystem : EntitySystem
```

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/EntitySystems/MatchboxSystem.cs
> +    private void OnInteractUsing(EntityUid uid, MatchboxComponent component, InteractUsingEvent args)
```suggestion
    private void OnInteractUsing(Entity<MatchboxComponent> ent, ref InteractUsingEvent args)
```

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/EntitySystems/MatchboxSystem.cs
> +        if (matchstick.CurrentState == SmokableState.Unlit)
I would move this check into the Ignite function

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/EntitySystems/SharedMatchstickSystem.cs
> +        SubscribeLocalEvent<MatchstickComponent, InteractUsingEvent>(OnInteractUsing);
```suggestion
        base.Initialize();

        SubscribeLocalEvent<MatchstickComponent, InteractUsingEvent>(OnInteractUsing);
```

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/EntitySystems/SharedMatchstickSystem.cs
> +namespace Content.Shared.Light.EntitySystems;
the smoking namespace delta was using in his PR probably makes more sense

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/EntitySystems/SharedMatchstickSystem.cs
> +    private void OnIsHotEvent(EntityUid uid, MatchstickComponent component, IsHotEvent args)
```suggestion
    private void OnIsHot(Entity<MatchstickComponent> ent, ref IsHotEvent args)
```

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/EntitySystems/SharedMatchstickSystem.cs
> +        args.IsHot = component.CurrentState == SmokableState.Lit;
```suggestion
        args.IsHot |= component.CurrentState == SmokableState.Lit;
```
may overwrite another event subscription that already set it to true

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/EntitySystems/SharedMatchstickSystem.cs
> +        _audio.PlayPredicted(matchstick.Comp.IgniteSound, matchstick, user, AudioParams.Default.WithVariation(0.125f).WithVolume(-0.125f));
the params should probably be moved into the sound specifier datafield

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/EntitySystems/SharedMatchstickSystem.cs
> +        matchstick.Comp.TimeMatchWillBurnOut = _timing.CurTime + TimeSpan.FromSeconds(matchstick.Comp.Duration);
needs dirtying in case `Ignite` is called from the server

2025-04-06 14:17 UTC, slarticodefast commented on Content.Shared/Lightning/EntitySystems/SharedMatchstickSystem.cs
> +    protected void SetState(EntityUid uid, MatchstickComponent component, SmokableState value)
same here

2025-04-06 20:00 UTC, beck-thompson commented
OK addressed the review! There were a few other minor cleanup things I did as well. I split it up into two commits, the first one is before the namespace switch so it might be easier to look at that.

2025-04-06 21:43 UTC, slarticodefast requested changes

2025-04-06 21:43 UTC, slarticodefast commented on Content.Server/Matchstick/EntitySystems/MatchstickSystem.cs
> +    }
Ok, I had another look and I think we should just merge https://github.com/space-wizards/space-station-14/pull/36310 first and give matchsticks the `IgnitionSourceComponent` because this code is directly copy pasted from there.
That way we can completely kill the server side system here. All you need to do is use `SetIgnited` in the `IgnitionSourceSystem`.
I think the `IgnitionSource` namespace would also be work for matchsticks!
Sorry for missing this in the previous review and making you change this again

2025-04-07 21:52 UTC, slarticodefast requested changes
One final thing, the rest looks good.

2025-04-07 21:52 UTC, slarticodefast commented on Content.Shared/IgnitionSource/EntitySystems/SharedMatchstickSystem.cs
> +public abstract class SharedMatchstickSystem : EntitySystem
```suggestion
public sealed partial class MatchstickSystem : EntitySystem
```
since they are empty we can just make this non-abstract and remove the server and client systems now

2025-04-07 22:08 UTC, beck-thompson commented on Content.Shared/IgnitionSource/EntitySystems/SharedMatchstickSystem.cs
> +public abstract class SharedMatchstickSystem : EntitySystem
I actually left them like that on purpose so it would be easier for forks to make changes if they wanted (E.g they wouldn't have to make a new class and it would reduce merge conflicts) - we don't really seem to have a policy either way and I'm also unsure if any forks even would have any changes. Let me know what you think!

2025-04-07 22:23 UTC, slarticodefast commented on Content.Shared/IgnitionSource/EntitySystems/SharedMatchstickSystem.cs
> +public abstract class SharedMatchstickSystem : EntitySystem
you can still do that since it is partial

2025-04-07 23:53 UTC, beck-thompson commented on Content.Shared/IgnitionSource/EntitySystems/SharedMatchstickSystem.cs
> +public abstract class SharedMatchstickSystem : EntitySystem
> you can still do that since it is partial

From what I remember (I could be wrong!) it doesn't quite work because the shared class isn't abstract so when you make a child it gets all funky. It doesn't matter much either way though so I'll just remove em! It's usually done that way anyway

2025-04-08 21:00 UTC, slarticodefast approved these changes
Works great! Thanks for the PR!

2025-04-08 21:00 UTC, merged