fix scram, revert #26429
space-wizards/space-station-14 pull request #31482
Opened 2024-08-26 15:29 UTC by Ilya246

## About the PR
fixes #31480

why is this a revert? i believe that #26429 is a de-optimisation, since i presume it would be faster to check the 20 or so tiles the tries20 picks rather than the 31k or so tiles in range; i think tries20 is actually the efficient implementation for this

however, it's possible i am wrong regarding the above, so correct me if i am; in that case, i will make a PR that removes the range sqrt, as opposed to a revert

additionally, tries20 will naturally prioritise larger grids near itself and be less likely to teleport you into space if you're far into the station

## Why / Balance
this is a fix - irrelevant

## Technical details
makes scram use tries20 to find a valid tile

## Media
not tested, **yet**

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- fix: Fixed the syndicate scram implanter incorrectly teleporting you only up to 10 tiles away. The range is now 100 tiles.

2024-08-26 21:58 UTC, whateverusername0 approved these changes
i approve of this

2024-09-09 20:20 UTC, Sadopeer commented
This would be a much needed buff

2024-09-10 01:14 UTC, metalgearsloth requested changes
Change the existing code to do what is preferred rather than leaving in poorly optimised code that teleports arbitrarily.

2024-09-11 03:34 UTC, Ilya246 commented
i believe i should mention this, but from testing, the tries20 method works 20 to 50 times faster than the one i am reverting

2025-03-21 08:44 UTC, TheShuEd commented
What is the status of this PR? Is it ready to be reviewed?

2025-03-21 09:19 UTC, Ilya246 commented
> What is the status of this PR? Is it ready to be reviewed?

yes

2025-04-30 16:49 UTC, EmoGarbage404 commented
Closing this PR.

Re-implementing the suspect prior logic in the name of optimizing the coldest path there ever was isn't necessary. The current logic is perfectly fine. Any additional adjustments to the spawning should be done in a separate PR that maintains the code structure.

Thank you for your contribution.

2025-04-30 16:49 UTC, closed without merging