Extend shuttle dock time if the shuttle doesn't dock at evac.
space-wizards/space-station-14 pull request #31496
Opened 2024-08-26 22:20 UTC by PJB3005

If the shuttle can't dock at evac for *some reason*, it will instead try to dock at another port on the station. And if that fails it goes somewhere random on the station.

Because of the chaos and confusion caused by this, many people will frequently not get to the shuttle in time under these circumstances. This sucks for everybody.

To alleviate this, the shuttle launch timer will now be extended if the station doesn't dock at its ideal spot. The default values (controlled via CVar) are 1.667x and 2x respectively for "wrong dock" and "no dock at all" scenarios.

The code around here was a mess, so I fixed that too. "CallEmergencyShuttle" has been renamed to "DockEmergencyShuttle", the overload that did the actual docking has been renamed to DockSingleEmergencyShuttle. Code has been split into separate dock -> announce methods so we can calculate shuttle delay in between the case of multiple stations.

Also made the "shuttle couldn't find a dock" text announce the time until it launches and fix the shuttle timers not triggering for it.

:cl:
- tweak: The emergency shuttle will now wait at the station longer if it couldn't dock at evac.

2024-08-31 00:23 UTC, UbaserB commented
How many seconds is it in practice?

2024-08-31 01:46 UTC, metalgearsloth approved these changes

2024-09-05 15:33 UTC, PJB3005 commented
5 and 6 minutes respectively.

2024-09-09 17:55 UTC, VasilisThePikachu requested changes

2024-09-09 17:55 UTC, VasilisThePikachu commented on Content.Shared/CCVar/CCVars.cs
> +        /// </summary>
It just can't!

```suggestion
        /// <summary>
        /// If the emergency shuttle can't dock at all, the dock time will be multiplied with this value.
        /// </summary>
```

2024-09-09 18:10 UTC, VasilisThePikachu approved these changes

2024-09-09 18:10 UTC, merged