Redid Singularity Generator Sprite
space-wizards/space-station-14 pull request #31500
Opened 2024-08-27 01:54 UTC by Moomoobeef

## About the PR
Redid the sprite for the singularity generator. Both to fix the issue listed below, but also because it just sucked.

## Why / Balance
Fixes #31295

## Technical details

## Media
![2024-08-26_20-52](https://github.com/user-attachments/assets/18b10e1d-3f05-43ad-b5e6-1807c42f3c25)

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: New sprite for Singularity Generator.

2024-08-27 07:05 UTC, UbaserB commented
its weirdly shiny

2024-08-27 08:51 UTC, Moomoobeef commented
> its weirdly shiny

I can make it less shiny, I just wanted it to have some depth since the original sprite always felt so flat

2024-08-28 00:27 UTC, c4llv07e commented
> its weirdly shiny

But it looks cool, I like it.

Also, it is now easier to see it in the space, because it's not full black.

2024-08-28 15:48 UTC, Moomoobeef commented
that's also a good point. Honestly I think I want to leave it, I don't want to make it less shiny

2024-09-03 12:41 UTC, UbaserB requested changes
After internal maintainer discussion, we've settled on a few things that need to be changed with the sprite.
- Instead of shine, thee ring should be a stronger "outline" on it.
- The neck between the base and and the ring should be removed.
- The rings should be thicker.
- Instead of having a two-pixel center it should be one four probably.

2024-09-03 18:03 UTC, Moomoobeef commented
>     * Instead of having a two-pixel center it should be one four probably.

I don't know what that means :P
otherwise I will work on this

2024-09-07 19:07 UTC, Moomoobeef commented
I forgor :skull: 
Going to work on these changes now

2024-09-08 00:38 UTC, Moomoobeef commented
I made an updated sprite that I think is hideous, but I would like to know which one more people like better
![image](https://github.com/user-attachments/assets/61cb9eff-f62e-4d5d-a516-a2b46de185f3)
Here is an ingame comparison
![image](https://github.com/user-attachments/assets/f8df474c-4feb-4690-906d-40a59f1b4016)

I also made a version of my original sprite with a thicker ring because I actually liked the way the thick ring looked and here is that
![image](https://github.com/user-attachments/assets/87581e27-20ba-4553-9a2a-0e3a9bc15158)
and here is the comparison with the two updated ones
![image](https://github.com/user-attachments/assets/4731866c-3b32-4265-892e-96439f04b593)

which one do you think looks best

2024-09-08 00:42 UTC, Moomoobeef commented
![image](https://github.com/user-attachments/assets/f117814c-91e4-44b5-b745-e11aa4c2185e)
oh and here they are under brighter lighting if that helps tell the difference since they are rather similar

2025-03-21 08:48 UTC, merged