Allow recycler to shred clothing
space-wizards/space-station-14 pull request #31518
Opened 2024-08-27 13:39 UTC by lzk228

## About the PR

## Why / Balance

## Technical details

## Media

## Requirements

- [ ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-08-29 03:03 UTC, UbaserB requested changes
fix the comments, it should be something along the lines of "50% of the amount of cloth you'd obtain upon butchering" or something similar

2024-08-31 13:40 UTC, slarticodefast submitted a review, later dismissed

2024-08-31 13:40 UTC, slarticodefast commented on Resources/Prototypes/Entities/Structures/Machines/recycler.yml
> +      - ClothMade
Add the Recyclable tag to the relevant clothing items instead

2024-09-01 21:39 UTC, slarticodefast commented on Resources/Prototypes/Entities/Clothing/Head/hats.yml
> +        - Recyclable
```suggestion
    - ClothMade
    - Recyclable
```
Test fail real. Fix the intendation here.

2024-09-01 23:23 UTC, slarticodefast reviewed
Ok, right now I'm not completely happy with what can and cannot be recycled. I guess it should be restricted to items that you can butcher? Or do we want all clothing to be recyclable/destroyed, including things like crew medals, pins and magboots, even if they give us no materials?

2024-09-01 23:23 UTC, slarticodefast commented on Resources/Prototypes/Entities/Clothing/Hands/base_clothinghands.yml
> +    - Recyclable
Add it to ClothingHandsButcherable instead. Otherwise it causes some gloves to be recyclable, but have no materialComposition.

2024-09-01 23:23 UTC, slarticodefast commented on Resources/Prototypes/Entities/Clothing/Head/base_clothinghead.yml
> +    - Recyclable
same here

2024-09-01 23:23 UTC, slarticodefast commented on Resources/Prototypes/Entities/Clothing/Neck/base_clothingneck.yml
> +      Cloth: 100
Ok, for some reason the crew medals, pins and headphones inherit this and are butcherable for that reason. There should probably be a ClothingNeckBaseButcherable prototype to fix that, but that is not your fault can be done in another PR

2025-05-15 23:44 UTC, merged