clean up tools lathe recipes
space-wizards/space-station-14 pull request #31521
Opened 2024-08-27 13:50 UTC by deltanedas

## About the PR
clean up hydro and tools files, and changed some times:
- a single cable now takes 0.1s to print instead of 2, literally no reason it was that long with 1 cable in mind
- rcd ammo standardized to 2 seconds from 2.4 nobodys gonna lose sleep over the 400ms saved

requires #31515

## Why / Balance
-diff

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- tweak: Printing cables in an autolathe is now 20 times faster.

2024-09-12 02:59 UTC, slarticodefast requested changes

2024-09-12 02:59 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Lathes/botany.yml
> +  id: MiniHoe
```suggestion
  id: HydroponicsToolMiniHoe
```

2024-09-12 02:59 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Lathes/botany.yml
> -  result: HydroponicsToolScythe
keep result

2024-09-12 02:59 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Lathes/botany.yml
> -  result: HydroponicsToolHatchet
literally 1984

2024-09-12 02:59 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Lathes/cooking.yml
> +  parent: DrinkMug
don't inherit the plate from the mug

2024-09-12 02:59 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Lathes/cooking.yml
> +  parent: FoodPlateTin
you save 2 lines with this but the parenting makes no sense

2024-10-05 01:13 UTC, slarticodefast commented
Are you coming back to this?

2024-10-05 05:40 UTC, deltanedas commented
yes

2024-11-01 09:52 UTC, slarticodefast commented
Looks good to me, thanks for the cleanup.

2024-11-01 09:52 UTC, slarticodefast approved these changes

2024-11-02 13:24 UTC, merged