Default every false instance of ExcludeUserAudio to true
space-wizards/space-station-14 pull request #31532
Opened 2024-08-27 20:25 UTC by ninruB

## About the PR

Fixes: #31433 (?)

Please ELI5 in reviews if possible.

## Technical details

I have no idea if I'm doing this right, client/server compiled on debug and no errors were seen.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A (?)

2024-08-27 21:12 UTC, Hreno commented
Wherever true is explicitly passed, you can remove it. And wherever no argument is passed in, you now need to pass false explicitly.

2024-08-27 22:50 UTC, ninruB commented
> Wherever true is explicitly passed, you can remove it. And wherever no argument is passed in, you now need to pass false explicitly.

I'll figure it out tomorrow.

2024-08-28 20:25 UTC, Hreno requested changes

2024-08-28 20:25 UTC, Hreno commented on Content.Shared/Containers/ItemSlot/ItemSlotsSystem.cs
> +                Insert(uid, slot, args.Used, args.User, excludeUserAudio: default);
`default` will become false here, it's a breaking change. You should just delete the entire `excludeUserAudio` argument here.

Also in other places.

2024-08-28 20:25 UTC, Hreno commented on Content.Shared/Containers/ItemSlot/ItemSlotsSystem.cs
> +            return TryInsert(uid, slot, item, user, excludeUserAudio: default);
You must forward the `excludeUserAudio` as was passed in to this method, cannot override it to `default` (which is false, for boolean).

Also in other places.

2024-08-28 23:50 UTC, ninruB commented
Thanks, I addressed the review, should be good now. Going to re-request a review just to be sure.

2024-08-29 16:14 UTC, Hreno requested changes
Have you searched for usages of every of these methods across the codebase and made sure the wrong value isn't now passed in any more? Remember, functionality during a refactoring must not change.

2024-08-29 16:14 UTC, Hreno commented on Content.Shared/Containers/ItemSlot/ItemSlotsSystem.cs
> +            Eject(uid, slot, item!.Value, user, excludeUserAudio = false);
This shouldn't be done, keep `excludeUserAudio` as is.

2024-08-30 13:24 UTC, Hreno commented
All usages weren't fixed.

Can I suggest you to tackle an easier issue where you'd have a higher confidence in making things work correctly? Not that I have 100% confidence in what I contribute is correct, but I'm reasonably assured.

Changing things blindly and hoping they will be fine is a recipe for failure.

2024-08-30 14:38 UTC, ninruB commented
> Can I suggest you to tackle an easier issue where you'd have a higher confidence in making things work correctly?

The previous issue I tried to tackle marked as beginner friendly and easy ended up actually being a landmine, so I'm not too eager to switch. I'll give this one a way more rigorous look, I'll re-request a review when I'm absolutely certain this changes no functionality.

2024-09-01 15:09 UTC, ninruB commented
I've had my schedule extended by a LOT, closing PR as per lack of free time and or dedication.

2024-09-01 15:09 UTC, closed without merging