Add game preset attribute, unhardcode game presets
space-wizards/space-station-14 pull request #3166
Opened 2021-02-12 13:56 UTC by DrSmugleaf

## About the PR
The death of the game preset switch expression has come.
Now game presets are marked with `[GamePreset(id, aliases...)]`

2021-02-12 15:44 UTC, metalgearsloth requested changes
nullables

2021-02-12 15:44 UTC, metalgearsloth commented on Content.Server/Players/PlayerData.cs
> +        }
I see you sneakin

2021-02-13 08:51 UTC, PaulRitter approved these changes
based based based

2021-02-13 08:51 UTC, PaulRitter commented on Content.Server/Players/PlayerData.cs
> +        }
thistbh, fix dis & get merged

2021-02-13 08:52 UTC, PaulRitter requested changes
wrong button

2021-02-13 12:42 UTC, DrSmugleaf commented on Content.Server/Players/PlayerData.cs
> +        }
Done.

2021-02-13 20:21 UTC, PaulRitter approved these changes

2021-02-14 14:39 UTC, merged