Improve animal cube interactions
space-wizards/space-station-14 pull request #31668
Opened 2024-08-31 01:52 UTC by thetolbean

## About the PR

Firstly, this PR adds the ability to see that an animal cube has had the wrong reagent added to it via examination. Secondly, it allows for animal cubes to be dried out in a microwave by microwaving them for 5 seconds, allowing users to recover animal cubes.

## Why / Balance
If a player accidentally or unknowingly adds the wrong reagent to an animal cube, it softlocks the cube, making it unusable. At  that point, the only thing to do with the cube is throw it into space. In addition, there is no feedback given to the player, leaving many players confused as to why it is not working. I chose this method instead of whitelisting the correct liquids due to my apprehension of limiting player choices due to an "unforeseen force" preventing players from adding incorrect reagents.

## Technical details

1. Adds 12 microwave recipes in a new file to `cube_dehydrate_recipes.yml`, one for each animal cube.
2. Adds an `OnExamine` function to `RehydratableSystem.cs`, with logic to compare the items max volume to it's current volume. If they are equal, it appends a soaked message to the description of the cube. (The volumes can only be equal if the cube did not expand due to the reagent being incorrect)

## Media

![image](https://github.com/user-attachments/assets/6ff3fc53-9f59-457e-879e-284c06d712fa)

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Animal cubes can now be examined to determine if they are soaked in the wrong reagent.
- add: Animal cubes can now be dried in a microwave to remove incorrect reagents.

2024-08-31 02:15 UTC, thebadman4662 commented
This creates way to generate infinite nutriment via repeatedly draining cubes then cooking new ones from themselves.

2024-08-31 02:20 UTC, deltanedas commented
> Adds 12 microwave recipes in a new file to cube_dehydrate_recipes.yml, one for each animal cube.

dont do this, give animal cubes temperature and a component that evaporates the solution when temperature is > 100C (maybe even use atmospheric pressure too for the funny :trollface:)

2024-08-31 02:32 UTC, thetolbean commented
> Does this create way to generate infinite nutriment via repeatedly draining cubes then cooking new ones from themselves?

Yes, it would as it just results in a new cube. This was not something I had considered


> Dont do this, give animal cubes temperature and a component that evaporates the solution when temperature is > 100C

I will have to look into how to accomplish this, but this makes just as much sense as the microwave solution, minus the implications

It seems like the microwave drying out the cubes is **_problematic_**, so I will have to look into alternative methods of drying the cubes out

2024-08-31 02:36 UTC, beck-thompson commented
I'm not quite sure but I think that solution would be fine and actually not too problematic... I'm praying that there is some ChangeTemerpature event or something that you can listen to and if its over a certain amount just delete all the solution inside the cube. Unknown if this is possible but that would be a clean solution

2024-08-31 03:53 UTC, slarticodefast commented
> I'm praying that there is some ChangeTemerpature event or something that you can listen to

You can subscribe to BeingMicrowavedEvent and remove the solution inside the monkey cubes instead of using special microwave recipes.

2024-08-31 08:50 UTC, deltanedas commented
ideally you could grill them or put them in a superheated room too with AtmosExposed, so dont rely solely on microwave

2024-08-31 10:20 UTC, lzk228 commented
fixes https://github.com/space-wizards/space-station-14/issues/29793

2024-08-31 13:12 UTC, thetolbean commented
> Or even better, only allow water to be transferred into them in the first place.

I had originally thought of that, but I dont think it would make sense to have players unable to add liquids other than water. My main concern is that there is no "lore" reason as to why you would only be able to add water. In that case, it would just feel like an invisible wall. Plus, it's funny to have cubes be splashed or accidentally have the incorrect liquid added due to spills or slipping

2024-09-04 05:07 UTC, thetolbean commented
UPDATE:
- Removed microwave recipes
- Cubes now do not respawn when microwaved, but only clear liquids

TO BE ADDED IN FUTURE:
- Exposing cube to heat in order to boil reagents out

2024-09-04 13:00 UTC, EthanQix commented
> TO BE ADDED IN FUTURE:
> 
>     * Exposing cube to heat in order to boil reagents out

Fun times to be had when heating up cube full of CLF3

2024-11-02 17:16 UTC, PursuitInAshes approved these changes

2025-04-22 19:58 UTC, EmoGarbage404 approved these changes

2025-04-30 02:50 UTC, chromiumboy requested changes

2025-04-30 02:50 UTC, chromiumboy commented on Content.Shared/Chemistry/EntitySystems/RehydratableSystem.cs
> +		if(args.Time <= 0)
The rehydratable component should have a field to specify a minimum dry time and use this value here

2025-04-30 02:50 UTC, chromiumboy commented on Content.Shared/Chemistry/EntitySystems/RehydratableSystem.cs
> +        if (solution.Volume == solution.MaxVolume)
If the rehydratable component CatalystMinimum is greater than zero, and the cube has some amount of the wrong chemical on it, is it possible you could run into a situation where you can't add enough of the correct solution to meet the minimum threshold?  If so, the examination should tell you that you need to dry off the cube

2025-09-03 18:25 UTC, SlamBamActionman commented
I think that this PR fixes a bug that should be fixed, but does it in the wrong way. While the PR description argues against having a whitelist I think that it is suitable in this case for a few reasons: 
1) It is bad UX to allow incorrect reagents to be put in the cube in the first place. Why would it let me put milk in it if the result of it is needing to destroy the reagent to "clean" the cube?
2) Would require more work for the player than just stopping it. The goal of pouring reagents into a cube is to activate it, so doing it incorrectly would require several further steps. Nicer to the player to just allow hydrating liquids to work. 
3) We have a precedent with rigged batteries that uses a whitelist for plasma, so it's not unexpected in the game.

2025-09-03 18:27 UTC, closed without merging