Hristov & .60 changes - Hristov Rework, Part 2
space-wizards/space-station-14 pull request #31662
Opened 2024-08-31 00:14 UTC by SlamBamActionman

## About the PR

This PR focuses on a few different changes to Hristov that are intended to rework the weapon into a formidable sniper rifle, including object penetration and damage changes. This is part 2 of a two-part Hristov rework; part 1 #31626 focuses on extending the gun's range.

This PR implements the following:
- The Hristov is now a wield-to-fire weapon.
- While being wielded, the wielder gets a 75% speed penalty.
- The Hristov takes 2.5 seconds to chamber a round; this delay is also applied when first wielding it.
- .60 Anti-Materiel bullets now deal:
  - 75 Piercing Damage
  - 150 Structural Damage
  - 60 Stamina Damage
- .60 Anti-Materiel bullets now have the ability to penetrate structures, up to a threshold of 360 damage.
  - The way this is calculated is that the bullet checks the damage required to break the entity it has hit, and if the bullet has dealt a combined damage under the threshold and the bullet damage itself is enough to break the object, it will continue.
  - If an entity is missing the ability to take Structural damage, the bullet will stop. This keeps the bullet from penetrating mobs (it's far too powerful for that).

## Why / Balance

The Hristov rework is split up in two parts as they implement different features and it would be fairly overwhelming to do both at once. The two parts are also fairly disconnected from each other codewise, so it's easier to implement.

The combined changes in this PR turns the Hristov into a powerful sniper that requires planning to use optimally. The requirement to wield and the long chamber time keeps its DPS down, and it becomes a poor choice for a run-and-gun situation due to the extreme movement speed slowdown. To balance this out the damage rewards landing your shots, and the gun gives you unique tools to let you do that. 

The anti-materiel bullets are tweaked such that they are able to penetrate weak structural objects like windows and grilles, but stop at walls. Since fights in groups in long hallways aren't uncommon and damage dealt by the bullets is high, they've been made to not penetrate mobs, making them more effective at single-target elimination. As an added bonus for any entrepreneuring sniper it also features heavy stamina damage; the 60 stamina damage of the first shot is enough to allow a brief moment of slowdown that the sniper is able to capitalize in for one shot, and if hit again the target will be knocked down. The damage is tweaked such that an officer or Captain is able to take 3 hits before being crit, while an unarmored target takes only 2. While the burst damage is strong, the slow reload causes a Time-To-Crit that is comparable to the high-tier lasers such as the laser cannon or advanced laser pistol.

Please consider these changes in the context of Part 1 of the Hristov Rework as well, since the extended range is key to utilizing the Hristov effectively. 

For comparison, here is how the new Hristov stacks up against the C20-r (20 TC purchase), the Viper (3 TC purchase) and the Python (8 TC purchase):
![image](https://github.com/user-attachments/assets/deb9f2fb-1962-41ab-90df-d2464daf59a1)

## Technical details

There are two main components to this PR:

The first is the new property in `ProjectileComponent`, `PenetrationThreshold`, which is used in `ProjectileSystem` to determine if a bullet should penetrate an entity or not. 

The second is the `SpeedModifiedOnWieldComponent`, which is used in `WieldableSystem` to set the movement speed slowdown.

## Media

[Youtube video link:](https://www.youtube.com/watch?v=uTCpamifReo)
[![Youtube video](https://img.youtube.com/vi/uTCpamifReo/0.jpg)](https://www.youtube.com/watch?v=uTCpamifReo)

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: .60 anti-materiel bullets now deal a lot more damage and are able to penetrate weak structures.
- tweak: Hristov now requires wielding to fire, and slows you down considerably.

2024-08-31 00:15 UTC, UbaserB commented
so based

2024-08-31 00:52 UTC, Everturning commented
Wait c20 is 20tc since when

2024-08-31 01:01 UTC, Boaz1111 commented
It isn’t, just checked

2024-08-31 06:57 UTC, SlamBamActionman commented
> Wait c20 is 20tc since when

Oop, miswrote.

2024-09-17 18:31 UTC, 7-62x54r commented
holy based

2024-12-02 23:35 UTC, KaiserMaus commented
No rework .60 ammo?

2024-12-11 13:23 UTC, KaiserMaus commented
Can we make AP .60 rounds which can penetrate whole station like Immovable Rod or like AP rounds in SS13. That AP bullet must be deleted only if hit Human.

2025-01-30 18:09 UTC, slarticodefast requested changes

2025-01-30 18:09 UTC, slarticodefast commented on Content.Server/Projectiles/ProjectileSystem.cs
> +            damageRequired -= damageableComponent.TotalDamage;
what about `DamageTypeTrigger`, where entities need a certain type of damage to be destroyed?

2025-01-30 18:33 UTC, SlamBamActionman commented on Content.Server/Projectiles/ProjectileSystem.cs
> +            damageRequired -= damageableComponent.TotalDamage;
This will fail safely; any such entity will max out the damage required - at worst it will eat the bullet. 

As per comments in `DestructibleSystem.DestroyedAt`, ideally `DestructibleComponent` should have a total damage destroy value as a component field, but that refactor is outside the scope of this PR.

2025-02-02 00:40 UTC, slarticodefast requested changes

2025-02-02 00:40 UTC, slarticodefast commented on Content.Server/Projectiles/ProjectileSystem.cs
>          var modifiedDamage = _damageableSystem.TryChangeDamage(target, ev.Damage, component.IgnoreResistances, origin: component.Shooter);
```suggestion
        var modifiedDamage = _damageableSystem.TryChangeDamage(target, ev.Damage, component.IgnoreResistances, damageable: damageableComponent, origin: component.Shooter);
```
we can reuse this here so the resolve won't have to get this

2025-02-02 00:40 UTC, slarticodefast commented on Content.Shared/Projectiles/ProjectileComponent.cs
> +    public List<string> PenetrationDamageTypeRequirement = new List<string>();
```suggestion
    public List<string> PenetrationDamageTypeRequirement = new();
```

2025-02-02 00:40 UTC, slarticodefast commented on Content.Server/Projectiles/ProjectileSystem.cs
> +        if (component.DeleteOnCollide && component.DamagedEntity)
![grafik](https://github.com/user-attachments/assets/7c909586-f73f-4e4c-9401-8a8eaee84203)
This datafield description and name is not really accurate anymore.
A bullet that destroys the first wall in its way would this have false as long as it can penetrate further.
Also the logic in which it is used is really convoluted.

2025-02-02 00:40 UTC, slarticodefast commented on Content.Server/Projectiles/ProjectileSystem.cs
> +            if (component.PenetrationDamageTypeRequirement.Count != 0)
I would maybe make this nullable instead of making the datafield an empty list.

2025-02-02 00:40 UTC, slarticodefast commented on Content.Server/Projectiles/ProjectileSystem.cs
> +                if (!component.PenetrationDamageTypeRequirement.Any(x => modifiedDamage.DamageDict.Keys.ToList().Any(y => y == x)))
Combine the two if statements.
Don't use linq if possible (it's slow), otherwise there should be a function which does this directly without nesting `Any`s

2025-02-04 16:49 UTC, slarticodefast approved these changes
Looks good to me!

2025-02-04 20:54 UTC, Boaz1111 approved these changes
Looks good to me, feels REALLY good to use, especially combined with part 1, all works correctly. Can't wait to use it!

2025-02-04 21:55 UTC, merged

2025-02-04 23:38 UTC, Thatonestomf commented
YES!!!
FINALLY I AM SO HAPPY TO SEE THESE PR's GO THROUGH!!