Lite Magnet Rebalancing
space-wizards/space-station-14 pull request #31726
Opened 2024-09-01 19:32 UTC by EmoGarbage404

## About the PR

- Magnet pulls come in a lot closer
- Changed weights for pull types to make wrecks and asteroids more common
- Make equipment spawners give better loot on average
- Make carp spawners weighted more towards single carp than groups or sharks
- carp and sharks are a bit slower
- carps and sharks have slightly less health and do a bit less damage
- plasma and uranium asteroids are more common
- rarer ore groups on asteroid pulls are a bit larger per vein.
- scrap is more common but weighted less towards big scrap

## Why / Balance

It was a bit too punishing overall and not really rewarding enough.

## Media

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Space Carp and Sharkminnows are a bit weaker overall.
- tweak: The magnet now pulls in debris a bit closer.
- tweak: Space debris now has slightly better loot.

2024-09-01 20:14 UTC, Awlod commented
😺👍🎇🎇🎇🎇

2024-09-01 20:34 UTC, Sarahon commented
Thank god.

2024-09-01 23:02 UTC, Anzarot121 commented
Dragon nerf real

2024-09-02 04:36 UTC, merged

2024-09-02 04:39 UTC, deltanedas requested changes

2024-09-02 04:39 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/carp.yml
> +        40: Dead
carp changes should be to the salvage one, this affects dragon traitors etc