Auditlog
space-wizards/space-station-14 pull request #31736
Opened 2024-09-02 02:16 UTC by dffdff2423

## About the PR

Add an audit log as described in https://github.com/space-wizards/space-station-14/issues/19672. It is currently only viewable inside SS14.Admin because I don't think viewing the audit log would be that useful in game.
## Why / Balance

The reasons are outlined in the issue. I am kind of surprised there is no way to audit admin actions in the game yet.

## Technical details

Adds a few new tables/migrations to add audit logs to the database. Adds an entry whenever a user takes one of the actions outlined in the issue. I tried to have the logging at the point closest to the database that was possible to reduce code-duplication. The UI for viewing them will be in the SS14.Admin PR that should link to this one below.

## Media

![audit-log-example](https://github.com/user-attachments/assets/553aacff-fb9e-4a22-ac1a-f0a2234b9b08)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

I don't think there are any.

**Changelog**

:cl: Aquif
ADMIN:
- add: Admin audit logs now exist and can be viewed in SS14.Admin. Audit logs will only exist for *new* actions. Existing actions will not have audit logs.

2024-09-02 02:33 UTC, Geekyhobo commented
This should have a adminflag and permission attached to it, and add that to the ss14admin PR as well

2024-09-02 02:38 UTC, Geekyhobo commented on Content.Server.Database/remove-migration.sh
is this needed

2024-09-02 02:48 UTC, dffdff2423 commented on Content.Server.Database/remove-migration.sh
It is not really needed, but I found it useful to have a counterpart to the add-migration.sh script when I was debugging migrations. I can remove it if you think it is unnecessary.

2024-09-06 04:06 UTC, metalgearsloth commented on Content.Shared.Database/AuditLogType.cs
> +    SeverBan = 7,
Server

2024-09-08 13:28 UTC, dffdff2423 commented
Branch got a little messed up because the submodule script does not work when your ss14 repo is a submodule and I forgot I did not have it installed. I should have fixed it now.

2024-10-11 12:08 UTC, PJB3005 requested changes

2024-10-11 13:03 UTC, dffdff2423 commented on Content.Server.Database/Model.cs
> +    public class AuditLog
I remember there being *some* reason why I did not do that, but this was so long ago I can not remember. I will take another look at it.

2024-10-11 13:05 UTC, dffdff2423 commented on Content.Server/Administration/Commands/BanExemptionCommands.cs
> +        }
I have no idea why I thought this was acceptable.

2024-10-15 23:13 UTC, dffdff2423 commented
I will try to get around to re-vising this some time this weekend, my free-time is significantly lower right now for a few IRL reasons but should clear up soon.

2024-10-16 01:07 UTC, dffdff2423 commented
Discussed on discord with CE here https://discord.com/channels/310555209753690112/770682801607278632/1295911799220342867

2024-11-10 23:49 UTC, dffdff2423 commented
"Recent events" and the fact that I have multiple small and easy to merge PRs that have been open for two and a half months without a review have killed my motivation to make major contributions to wizden. I am going to close this PR so it is not hanging over me while I spend my limited free time working on other projects. I may return to this in a few months, or I may not. Please mark it as derelict. Thank you for understanding. 

Anybody who wishes to pick up this PR and make it into a state that is mergeable, feel free to contact me here or on discord dffdff2423 (551544963201105931) if you have questions. I would strongly recommend reading the above discussion I had with CE.

2024-11-10 23:49 UTC, closed without merging