Secret stash wrench anchoring fix
space-wizards/space-station-14 pull request #31779
Opened 2024-09-03 07:16 UTC by godisdeadLOL

## About the PR

(reopened pr because had some git issues in previous)

- Anchoring has higher priority over stashing
- Verbs for stashing are always shown which allows to stash wrenches

## Why / Balance

fixes #31646 and #31455

## Technical details

## Media

https://github.com/user-attachments/assets/70ac6ff2-d8f1-4a39-a494-603fdb7261b8

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: yuitop
- tweak: now anchoring has higher priority over stashing

2024-10-30 17:28 UTC, slarticodefast requested changes
Keep the HasVerbs datafield, it might be useful to disable them for some kinds of secret stashes that cannot be anchored. Just setting it to true for the potted plants should be enough.

2024-12-11 16:40 UTC, slarticodefast approved these changes

2024-12-11 16:41 UTC, slarticodefast commented
I went ahead and fixed the merge conflict and addressed the review myself.
Thank you for your contribution.

2024-12-13 21:28 UTC, Tayrtahn approved these changes

2024-12-13 23:00 UTC, merged