Gave AI a comms console
space-wizards/space-station-14 pull request #31852
Opened 2024-09-04 23:21 UTC by ScarKy0

## About the PR

Needs https://github.com/space-wizards/space-station-14/pull/31823 to be merged first

Allows AI to use a comms console as an ability.

## Why / Balance

It's just sorta a thing AI should be able to do.

## Technical details

A lot of duplicate code until the previous PR is merged.
Made all shuttles transmit their time at Wireless instead of Private, as well as Screens receiving Wireless as well. Had to be done to allow aghost and AI to use the broadcast feature of Comms Consoles.

## Media

![image](https://github.com/user-attachments/assets/2d98a7af-66a5-4f1d-9184-7594ae131baa)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Made all emergency shuttles transmit ShuttleTimer via Wireless and Screens receive via Wireless.

**Changelog**

:cl:
- add: Station AI now has a comms console ability.
- tweak: Station AI abilities now have a default order.

2024-09-05 13:31 UTC, nymhole commented
just make all PRs depend on eachother so they all get merged, super based. please give the ai the ability to open multiple camera monitors.

2024-09-05 13:32 UTC, ScarKy0 commented
> just make all PRs depend on eachother so they all get merged, super based. please give the ai the ability to open multiple camera monitors.

I did do that apprently i did smth wrong
Also idk how to do that, for now AI cant even use the camera monitor because it breaks the overlay

2024-09-06 04:09 UTC, superjj18 commented
Honestly ai should have most of the important consoles like atmos alert, criminal, power, camera, etc.  let the player uses the action menu to decide which they care about having quick access to.

2024-09-06 10:37 UTC, slarticodefast requested changes

2024-09-06 10:37 UTC, slarticodefast commented on Resources/Prototypes/Actions/station_ai.yml
> +        #- Biological
These are not mentioned in the PR description at all. Make that a separate PR. and don't include commented out code for features that haven't been decided on yet.

2024-09-06 10:40 UTC, slarticodefast commented
Also the changes to Wireless are not part of this PR, but were in another one. Please atomize your PRs better so we don't accidentally merge features that aren't supposed to be part of the PR. Also adjust your PR description.

2024-09-06 10:42 UTC, ScarKy0 commented
> Also the changes to Wireless are not part of this PR, but were in another one. Please atomize your PRs better so we don't accidentally merge features that aren't supposed to be part of the PR. And adjust your PR description.

Yeah I forgot to update the description since I moved all the Wireless changes to my Fixes PR, my bad

2024-09-12 15:27 UTC, slarticodefast approved these changes

2024-09-12 15:28 UTC, merged