Adds salvage magnet board to the circuit imprinter
space-wizards/space-station-14 pull request #31996
Opened 2024-09-09 01:08 UTC by ArtisticRoomba

## About the PR

Adds the salvage magnet board to the circuit imprinter.
## Why / Balance

The salvage magnet board was previously unable to be obtained IC. You either had to admeme it into existence or simply suffer, as the salvage gameplay loop literally cannot be started with the magnet missing.

If your salvage magnet gets emogarbaged (meteored), stolen, or otherwise obliterated it can now be easily repaired. This PR fixes #31994.

I don't think this should be under research, science partially relies on Cargo for their gameplay loop and it would just be a happier situation if this could be made roundstart, it's a pretty integral thing for salvage.

The recipe requires gold for the circuitboard but the RD can easily ransack the vault for some gold if necessary. If this needs to be changed (because RD _somehow_ spent all the station's gold on useless shit) let me know. Same with the technology thing.

_Reminder of the TODO: Make the salvage magnet require HV wire and draw a lot of power when active, to mechanically enforce having the magnet being the "starter" for salvage's gameloop. Would require map changes._

## Technical details

YAML editing lmao.
Adds `SalvageMagnetMachineCircuitboard` to electronics.yml
Adds `SalvageMagnetMachineCircuitboard` to lathe.yml under `staticRecipes` if you're having a _really_ bad day.
Adds the supply sprite component to the circuitboard.

## Media

Media shows changed sprite, components needed, the double salvage magnet situation staying consistent, and the flatpacked version of the magnet.

![Content Client_ebl7ZHmT4s](https://github.com/user-attachments/assets/270e2d8e-ee87-4097-bddc-c0077c3d9406)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: The salvage magnet circuitboard can now be made at a circuit imprinter.

2024-09-09 01:12 UTC, Cojoke-dot commented
Just add it to the qm's closet, else sci salv would be too prevalent. It would just replace the spare reclaimer shuttle board anyways.

2024-09-09 01:12 UTC, ArtisticRoomba commented
Sure.

2024-09-09 01:28 UTC, lzk228 commented
to resolve the issue i would just made salv magnet not completely desctruclible but turned into "broken" version that can be repaired

2024-09-09 01:29 UTC, Cojoke-dot commented
> to resolve the issue i would just made salv magnet not completely desctruclible but turned into "broken" version that can be repaired

meh, meteors would end up just knocking it off the grid into deep space then

2024-09-09 01:32 UTC, ArtisticRoomba commented
yeah, meteors can just knock it out into deep space, and with the magnet being so integral to salv's gameloop, it would be better to have this be on a lathe + in locker

if we feel that it needs to be behind technology then I can add it to a salvage-related tech that makes sense

2024-09-09 01:34 UTC, lzk228 commented
i'm just afraid that salv will abuse two or even three magnets
or it's not possible?

2024-09-09 01:38 UTC, lzk228 commented
that's fine then

2024-09-09 20:16 UTC, ArtisticRoomba commented
What

2024-09-09 21:21 UTC, ArtisticRoomba commented
Oh, #31524 lmao
Now I don't have to worry about random mats pricing

2024-09-09 21:39 UTC, deltanedas requested changes

2024-09-09 21:39 UTC, deltanedas commented on Resources/Prototypes/Recipes/Lathes/electronics.yml
> +  id: SalvageMagnetMachineCircuitboard
no reason for this to take extra steel or be 10 seconds, just inherit the gold electronics recipe

2024-09-10 01:09 UTC, ArtisticRoomba commented
also @deltanedas related issue to your PR #31524 while we're here, the base protos for `BaseGoldCircuitboardRecipe` and `BaseCircuitboardRecipe` show despite `abstract: true` in the lathe
![Content Client_CfAyLjFJid](https://github.com/user-attachments/assets/c5e208d1-90d0-473f-b466-cd748fd0aba8)

2024-09-10 23:23 UTC, beck-thompson commented
Just had a shift where a meteorite exploded our magnet... Not fun we just sat around for the rest of the shift!

2024-09-10 23:25 UTC, Emisse commented
shure

2024-09-10 23:25 UTC, merged