Welding mask update
space-wizards/space-station-14 pull request #31999
Opened 2024-09-09 08:35 UTC by godisdeadLOL

## About the PR
The welding mask is now adjustable. It darkens your vision with an overlay when covering your face. Wearing other eye protecting equipment (like sunglasses) along with the mask will make you temporarily blind.

## Why / Balance
it was in ss13

## Technical details

## Media
![1](https://github.com/user-attachments/assets/b4f3f74b-d813-43cb-a486-3b156b324d21)
![2](https://github.com/user-attachments/assets/4ee32b60-6575-41bf-ad58-0d00e4bb2c0c)
![3](https://github.com/user-attachments/assets/89fb52f5-7063-4d67-b538-3f7b7308dbd0)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl: yuitop
- tweak: the welding mask is now adjustable

2024-09-09 08:43 UTC, Empoleon4444 commented
the darkened vision should be way more potent, like 3 tiles of vision or less

2024-09-09 09:15 UTC, Hrosts commented
The part about darkening your vision should probably be in the CL

2024-09-09 22:28 UTC, Cojoke-dot commented
Add a 1-3 second use delay or something, don't want people invalidating the debuf in combat by toggling it on and off a ton

2024-09-09 22:47 UTC, Golinth commented
Darkness should definitely be stronger, the welding mask is so strong because it invalidates flashes, which is predominantly a melee ranged item anyway

2024-09-10 02:23 UTC, TurboTrackerss14 commented
100% agree with Cojoke. 
This should legitimately nearly blind you 2 tile radius so it stops being a defacto "anti flash"

2024-09-10 08:36 UTC, godisdeadLOL commented
ok

2024-09-10 14:18 UTC, godisdeadLOL commented
I made vision darkening into a component for a piece of clothing. Also added welding goggles. Found some bugs. I'll fix them later.

2024-09-10 14:22 UTC, godisdeadLOL commented
Is that darkening good?

![n1](https://github.com/user-attachments/assets/255692fb-a077-4066-a9bf-c757ecef76af)
![n2](https://github.com/user-attachments/assets/6aca3ac1-5dc1-4907-b43a-209f8fa399d8)

2024-09-10 14:25 UTC, UbaserB commented
fix cl please

2024-09-10 14:27 UTC, Boaz1111 commented
what’s the difference between welding goggles and engineering goggles?

2024-09-10 14:42 UTC, godisdeadLOL commented
Welding goggles are not adjustable and darken screen less. Pretty much customization option.

2024-09-10 21:28 UTC, Everturning commented
well I mean welding goggles give you darkness and engi goggles don't.

2024-09-11 00:02 UTC, yuitop commented
no contraband tag

2024-10-06 10:56 UTC, UncaughtEx commented
This is pretty interesting

2024-12-27 10:04 UTC, Pumkin69 commented
i think this is good personally nerfing welding masks as a super easy to get anti flash but not entirely removing them is really fun and interesting for roundflow and gameplay.

2025-01-16 16:27 UTC, SlamBamActionman requested changes
Thanks for the contribution! I've tested it out ingame and I love the overall feel of it, but I have some notes that I would like to see first.

1. I would forgo the folded-up state entirely when it comes to not being worn. It works fine when you have it on your head, but placing a folded-up mask in your hand or in the world doesn't look right. Instead I would have it revert to its "down" position if you remove the mask (even if it means you have to flip it back up again if you put it up, similar to how coats/masks work). 

2. I think you can avoid `WeldingMaskSystem` entirely and instead build it out of generic components; one for updating the sprite appearance and one for applying the darkened vision when toggled. Now as luck would have it, `MaskSystem` already does all the former, except it is for some reason hardcoded to `Slot.MASK`; were you to [change that](https://github.com/space-wizards/space-station-14/blob/cec5816acf354479a1df0220bd0aaf0f41745a8c/Content.Shared/Clothing/EntitySystems/MaskSystem.cs#L31) into a component property you could use the `MaskComponent` for the visuals instead, and have the `DarkenedVisionSystem` subscribe to the `ItemMaskToggledEvent`.

3. Atomize welding goggles into its own PR, as it's adding a new item when the focus of the PR seems to be on the welding mask feature.

2025-04-14 15:30 UTC, MilonPL commented
Thank you for your contribution! I will be closing this PR as stale, as it has been awaiting changes for 3 months now. Feel free to open another PR if you ever come back to this.

2025-04-14 15:30 UTC, closed without merging