Syndicate business card
space-wizards/space-station-14 pull request #32162
Opened 2024-09-14 17:47 UTC by pofitlo-Git

## About the PR

A new uplink item is added to the game - the syndicate's business card. in general, it is quite useless and is only needed for role play. You can write a message on the back

## Technical details

it costs nothing, but it is limited in purchase. you can only buy 3 of them

## Media

![image](https://github.com/user-attachments/assets/67e0856d-05a4-4d87-87f3-723ca9dc9492)
![image](https://github.com/user-attachments/assets/227cef9c-b807-4063-b9c9-3255cb62c60a)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.
- [ ] I create unique UI for card

## Breaking changes

**Changelog**

2024-09-14 17:53 UTC, lzk228 requested changes

2024-09-14 17:53 UTC, lzk228 commented on Resources/Locale/en-US/paper/syndicate-business-card.ftl
> +syndicate-business-card-base = It's nothing personal, it's just business
```suggestion
syndicate-business-card-base = It's nothing personal, it's just business

```

2024-09-14 17:53 UTC, lzk228 commented on Resources/Locale/en-US/store/uplink-catalog.ftl
> +uplink-business-cadr-name = Syndicate business card
all words start with uppercase, that's called title case in english

2024-09-14 17:53 UTC, lzk228 commented on Resources/Locale/en-US/store/uplink-catalog.ftl
> +uplink-business-cadr-desc = a business card that you can give to someone to demonstrate your involvement in the corporation or leave at the crime scene in order to make fun of the detective. You can
first letter uppercase and dot at the end

2024-09-14 17:53 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Misc/business card.yml
wouldn't be better to put it in paper.yml and set BasePaper as parent?

2024-09-14 17:53 UTC, lzk228 commented on Resources/Textures/Objects/Misc/Business_сard.rsi/Synicate card.png
name should be `syndicate_card.png`

2024-09-14 18:01 UTC, pofitlo-Git commented on Resources/Prototypes/Entities/Objects/Misc/business card.yml
I saw an offer to make more of these cards. for a bar, for example, or for something else, idk. so maybe it would be better to allocate it to a separate file

2024-09-14 18:02 UTC, UbaserB commented
This is so based

2024-09-14 18:46 UTC, Ertanic commented on Resources/Prototypes/Entities/Objects/Misc/business card.yml
> +      state: Synicate card
```suggestion
      state: Synicate_card
```
You forgot to fix the name of the state in the prototype.
![image](https://github.com/user-attachments/assets/b0925491-0540-45d6-b110-2576760e930d)

2024-09-14 23:29 UTC, pofitlo-Git commented
![image](https://github.com/user-attachments/assets/620bc752-989e-4bbf-a3e9-3f8bd8c6a7af)
logo

maybe someone someday draw a normal logo....

2024-09-15 14:29 UTC, eoineoineoin commented on Resources/Textures/Interface/Paper/paper_heading_syndicate_logo.svg
Looks like this file wasn't saved correctly? It's just a resized version of paper_heading_virus.svg?

2024-09-15 14:31 UTC, eoineoineoin commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
> +    canExtinguish: true # Mwahaha! Let the world burn because of one piece of paper!
Is this change intentional? This is just setting to the default value, so can be removed - the change also makes the comment incorrect.

2024-09-15 14:35 UTC, eoineoineoin commented on Resources/Textures/Objects/Misc/Business_card.rsi/meta.json
> +            "name": "Synicate_card"
Typo. Also in the "Synicate_card.png" filename.

2024-09-15 14:40 UTC, eoineoineoin commented on Resources/Textures/Interface/Paper/paper_background_black.svg
This file does not seem to be the same one which generated paper_background_black.svg.96dpi.png?

2024-09-15 18:18 UTC, HenhenIII commented
Based

2024-09-15 20:57 UTC, slarticodefast requested changes

2024-09-15 20:57 UTC, slarticodefast commented on Resources/Locale/en-US/store/uplink-catalog.ftl
> +uplink-business-cadr-desc = A business card that you can give to someone to demonstrate your involvement in the syndicate or leave at the crime scene in order to make fun of the detective. You can bu
```suggestion
uplink-business-card-name = Syndicate business card.
uplink-business-card-desc = A business card that you can give to someone to demonstrate your involvement in the syndicate or leave at the crime scene in order to make fun of the detective. You can buy no more than three of them.
```

2024-09-15 20:57 UTC, slarticodefast commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +  description: uplink-business-cadr-desc
```suggestion
  name: uplink-business-card-name
  description: uplink-business-card-desc
```

2024-09-15 20:57 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Misc/business card.yml
> +- type: entity
Rename the file to business_card.yml

2024-09-15 20:57 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Misc/business card.yml
> +      state: Synicate_card
```suggestion
      state: sydicate_card
```

2024-09-15 20:57 UTC, slarticodefast commented on Resources/Textures/Objects/Misc/Business_card.rsi/meta.json
> +            "name": "Synicate_card"
```suggestion
            "name": "syndicate_card"
```
Same for the file name.
The folder should be renamed to business_card.rsi

2024-09-15 20:57 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Misc/business card.yml
> +  parent: BaseItem
This should just inherit from the Paper entity in paper.yml and only overwrite what needs to be changed.

2024-09-18 21:36 UTC, slarticodefast commented
The default isn't centered at the moment like in the PR image. You can add some whitespace to the ftl string using
`{"           "}`
Also please add an changelog to your PR description to notify players of your addition.

2024-09-18 22:10 UTC, slarticodefast commented
Also a request from one of our art directors for the item sprite:
"make sure the item isnt in 3/4ths, is really all i have to say. goes against the artstyle guidelines im pretty sure.
the sprite could maybe use some rounded edges to make it more card-like, too"

2024-09-22 15:39 UTC, slarticodefast commented
Test fail is real.
Also I will ask the art directors for approval of the new sprite.

2024-09-23 15:36 UTC, pofitlo-Git commented
> Test fail is real. Also I will ask the art directors for approval of the new sprite.

it's because any "paper" sould have "write" state with sprite. And I don't know exactly how resolve this

2024-09-26 11:56 UTC, pofitlo-Git commented
@slarticodefast I think that it can work now

2024-09-26 12:28 UTC, slarticodefast commented
Awesome, I'll give it another in-game test later.
The item sprite might need some more adjustments according to the art directors:
- the sprite should not be in 3/4ths perspective
- "the bottom highlight is what's making it look 3/4ths"
- "the shading on the s is kinda messy"
All I got as a review from them so far, I can ask for more clarification if needed.

2024-09-26 12:29 UTC, Ilya246 commented
maybe you should be able to fax them

2024-09-26 16:37 UTC, eoineoineoin commented
These comments are marked as resolved, but are still outstanding:

https://github.com/space-wizards/space-station-14/pull/32162#discussion_r1760060393
https://github.com/space-wizards/space-station-14/pull/32162#discussion_r1759782733

You've also modified the whitesepace on every single line in Resources/Textures/Objects/Misc/bureaucracy.rsi/meta.json - can you fix that?

2024-09-26 20:42 UTC, pofitlo-Git commented
> These comments are marked as resolved, but are still outstanding:
> 
> [#32162 (comment)](https://github.com/space-wizards/space-station-14/pull/32162#discussion_r1760060393) [#32162 (comment)](https://github.com/space-wizards/space-station-14/pull/32162#discussion_r1759782733)
> 
> You've also modified the whitesepace on every single line in Resources/Textures/Objects/Misc/bureaucracy.rsi/meta.json - can you fix that?

yes It's my mistake but I don't understate what do u mean about modified the whitesepace on every single line. It's look same...

2024-09-26 21:17 UTC, beck-thompson commented
Also I could be wrong but I still think there is a merge conflict?

2024-09-26 22:56 UTC, slarticodefast commented
> Also I could be wrong but I still think there is a merge conflict?

A direct merge conflict should get shown in the github actions.
There can be silent merge conflicts if there are namespace or API changes (that's why we have the breaking changes section).
I usually merge master before doing ingame tests to make sure

2024-09-27 00:38 UTC, cohanna commented
> yes It's my mistake but I don't understand what do u mean about modified the whitesepace on every single line. It's look same...
Resources/Textures/Objects/Misc/bureaucracy.rsi/meta.json
most notably line 10 has a larger indent (which propagates to the lines below)
but just about every line has had at least one extra indent

you can view the diff if you go to the "files changed" tab of this pr.

2024-09-27 14:28 UTC, pofitlo-Git commented
okey now It's done

2024-09-28 10:14 UTC, eoineoineoin commented
@pofitlo-Git I appreciate this has had a lot of back and forth to fix issues - thanks for your patience here, it gets easier, really!

@slarticodefast I'm not sure that pofitlo knows how to resolve merge conflicts, so in the interests of saving everyone a bit more hassle, I've resolved the merge conflict and fixed another typo in https://github.com/eoineoineoin/space-station-14/tree/pofitlo/businesscard -  could you fast-forward their branch to that?

2024-09-28 11:33 UTC, slarticodefast commented
> I'm not sure that pofitlo knows how to resolve merge conflicts, so in the interests of saving everyone a bit more hassle, I've resolved the merge conflict and fixed another typo in https://github.com/eoineoineoin/space-station-14/tree/pofitlo/businesscard - could you fast-forward their branch to that?

Sure, thanks for helping out. I'll give the business card a final code review and in-game test as soon as possible and this should be good to merge then.

2024-09-28 12:17 UTC, pofitlo-Git commented
> @pofitlo-Git I appreciate this has had a lot of back and forth to fix issues - thanks for your patience here, it gets easier, really!
> 
> @slarticodefast I'm not sure that pofitlo knows how to resolve merge conflicts, so in the interests of saving everyone a bit more hassle, I've resolved the merge conflict and fixed another typo in https://github.com/eoineoineoin/space-station-14/tree/pofitlo/businesscard - could you fast-forward their branch to that?

thank you very mach! I really awful for git

2024-09-30 20:27 UTC, slarticodefast commented on Resources/Prototypes/Entities/Objects/Misc/business_card.yml
> +  name: Syndicate business card
```suggestion
  name: syndicate business card
```

2024-09-30 20:28 UTC, slarticodefast approved these changes

2024-09-30 20:44 UTC, merged

2024-09-30 20:45 UTC, slarticodefast commented
Thank you for your contribution and your first PR :)