Added the ability to drink from Beakers
space-wizards/space-station-14 pull request #3216
Opened 2021-02-15 04:01 UTC by Nukeuler123

## About the PR 
It uhh, allows people to drink from a beaker, though you want get hurt if you drink something like... i dunno, liquid hydrogen.

closes #3208

2021-02-15 12:02 UTC, Zumorica requested changes
GlassBeakerComponent is going to be removed soon. Instead of doing this dirty hack, set `isOpen` to true on the `Drink` component in the prototypes.

2021-02-16 07:22 UTC, Nukeuler123 commented
> GlassBeakerComponent is going to be removed soon. Instead of doing this dirty hack, set `isOpen` to true on the `Drink` component in the prototypes.

Ahh,didn't know I could do that with the yaml stuff, I'll get around to it when I have power in my home in a few days

2021-02-19 19:10 UTC, Nukeuler123 commented
All fixed up and using the funny yaml stuff

2021-02-19 19:11 UTC, DrSmugleaf approved these changes

2021-02-23 08:52 UTC, merged