Add generator scrap (Plasma / uranium scrap)
space-wizards/space-station-14 pull request #32198
Opened 2024-09-16 05:04 UTC by beck-thompson

## About the PR

Added 6 new scraps that can be found when doing salvage! All are related to generators. The generators cannot be put in lockers so they have to be dragged back to the station. Because of this, they hold a lot of resources (45 steel, 5 or 30 plasma/uranium, 5 plastic)! These shouldn't be supper common but should appear about once per trip.

## Why / Balance

Right now, its difficult to obtain any reasonable amount of plasma or uranium from salvage scrapping. This adds a few options that will hopefully make it easier. 
## Technical details

## Media

https://github.com/user-attachments/assets/0b584ddd-fe7f-480e-a6fe-12c343f9ef61

**Changelog**

:cl: Beck Thompson
- add: Added some new scrap that contains uranium and plasma that can be found when salvaging!

2024-09-16 05:21 UTC, beck-thompson commented
![image](https://github.com/user-attachments/assets/075dcfad-23e4-421e-9c49-9368db9f2a54)

Forgot the shading!

2024-09-17 15:59 UTC, beck-thompson commented on Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
> +      weight: 0.5
Just wanted them to be less common! I think it would be better for the higher plasma/uranium generators to appear more frequently.

2024-09-18 20:27 UTC, beck-thompson commented on Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
> +      weight: 0.5
Remember this is scrap so being in better condition would make it less common (The two leaking ones are in much worse condition). Secondly, the other two generators are not very good so making them more common wouldn't be that helpful. Having to drag something that big for only 45 metal, 5 plastic, and 5 special is probably not worth it (At least when I'm doing salvage).

2024-09-21 05:56 UTC, beck-thompson commented on Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
> +      weight: 0.5
Sorry forgot reply but yeah that makes sense! Tweaking the values to basically that now

2024-09-23 06:54 UTC, UbaserB requested changes
Can you make it so that the empty frame version has depth? You should be able to see the bottom base of the generator a bit like you know, the sprite is somewhat angled. Also, if you're going to animate the uranium then maybe animate the plasma leakage too.

2024-09-23 16:29 UTC, beck-thompson commented
>Also, if you're going to animate the uranium then maybe animate the plasma leakage too.

I was thinking the plasma was more of a solid... I tried a few ways of animating it like with sparkles but I could never get it to look good :(

2024-10-13 06:41 UTC, UbaserB approved these changes
Sprite and conceptual approval from me, just skimmed over the yaml so someone should check it in more detail

2024-12-08 02:02 UTC, ps3moira commented
why does uranium not emit radiation?

2024-12-08 02:15 UTC, beck-thompson commented
> why does uranium not emit radiation?

I don't know 🤷. I assume for balance reasons (Wasn't the banana ore changed because of that?)!

That reminded me though, I forgot to make the uranium generators release a small amount of radiation.

2024-12-16 12:33 UTC, SlamBamActionman commented
Balance seems fine with how rare they are; it seems a lot on a first glance, but the time cost required to drag it makes it feel fine. Thanks for your contribution!

2024-12-16 12:33 UTC, merged