Skirt of Life resprite + adding it to paramedic loadout
space-wizards/space-station-14 pull request #32227
Opened 2024-09-17 02:45 UTC by KingFroozy

## About the PR

This PR changes the sprite of the Skirt of Life, and adds it to paramedic's loadout with a requirment on it to have 10 hours played with paramedic role. Also adds white shoes to role loadout.
## Why / Balance

There's a different PR, that suggests making skirt of life accesseable via a hacked medidrobe, which I dislike. Medical doctors right now have more than lots of clothings they can put on to show off with, and giving them a skirt of life would be just unfair to paramedics, which don't have a single other option besides their jumpsuit, and it's also quite nonsense it requires the medidrobe to be hacked to get it. Why exactly paramedic? The skirt itself was added, when brigmedic been a thing for a while, but then it got abandoned and became rather gamerloot. Considering it once belonged to brigmedic, it would be pretty logical to give it to Para as a compromise. Also, the sprite was ugly-ish, so I resprited it (@Flareguy said it looks good).
## Technical details

none
## Media

![Снимок экрана 2024-09-17 052356](https://github.com/user-attachments/assets/388a30a6-6082-4216-8c4e-8d63429e73fe)
![Снимок экрана 2024-09-17 054221](https://github.com/user-attachments/assets/0e988a7a-5c0f-4320-a470-ab9d30ac856c)

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Changed sprite for the skirt of life.
- add: Added skirt of life to paramedic's loadout for experienced saviours of lives!
- add: Added white shoes to paramedic's loadout.

2024-09-17 11:39 UTC, foob1 commented
Sprite looks okay but I'm not sure if it makes sense for it to belong to paramedic. I'm not sure what it is a reference to but it looks more like a nurse thing with the heart and pink colors.

2024-09-17 11:48 UTC, Kukutis96513 commented
the skirt of life doesn't really fit the dark blue colours of paramedics much, i think it'd be better as a medical doctor item instead.

2024-09-17 18:10 UTC, foob1 commented
Honestly though I prefer the old sprite for the skirt of life, though the heart on the back is a nice touch

2024-09-21 09:34 UTC, slarticodefast commented
It has been added to the hacked medidrobe, so please remove it from the loadout #32214

2024-09-21 15:26 UTC, KingFroozy commented
> It has been added to the hacked medidrobe, so please remove it from the loadout #32214

Done, though adding white shoes is left here, cause I think it's necessary.

2024-12-20 11:32 UTC, TheShuEd requested changes
remove shoes and mergable

2024-12-20 11:32 UTC, TheShuEd commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - WhiteShoes
Out of Scope, remove

2025-04-13 10:35 UTC, slarticodefast commented
Thank you for your contribution!

2025-04-13 10:35 UTC, merged