tape recorder v3 revival
space-wizards/space-station-14 pull request #32234
Opened 2024-09-17 07:07 UTC by deltanedas

## About the PR
revival of #30089
refactored, microoptimised and addressing reviews
changed the weird dual-state thing to just be mode and thats it

stores the verb used, but the exact string the server picked in SendEntitySpeak can't be saved. presumably this will be possible in chat refactor, then the tape can store the exact message (including whispering, which still isnt stored right)

## Why / Balance
see old pr

## Technical details
Active bool changed to ActiveTapeRecorder so it can be queried for
UI uses RadioOptions instead of making them manually
most of the state is just gotten from the component instead of being sent in every bui state
it also stores the used speech verb now

## Media
Pause | Record | Playback | Rewind
![03:52:14](https://github.com/user-attachments/assets/3e62652d-35b5-420c-a36a-86f5b53de640)

![03:52:19](https://github.com/user-attachments/assets/ceb18a32-ff0e-49a9-94de-b7251f986d59)

![03:52:29](https://github.com/user-attachments/assets/90e4e548-adb0-4904-8ee2-4b4220a4fb9e)

![03:58:55](https://github.com/user-attachments/assets/04a9f22d-d629-45c6-9660-5a9bbd618886)

![03:59:52](https://github.com/user-attachments/assets/d2710495-28e5-4246-8ca7-a75a9999115e)

it will use a random string from the speech verb that was recorded
![04:58:25](https://github.com/user-attachments/assets/a59ef59e-da1b-40f4-9f14-e9267716e8f3)

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl: BombasterDS, deltanedas
- add: Tape recorders and cassettes can now be crafted in autolathes for recording crew speech.

2024-09-17 07:49 UTC, lzk228 commented
he is cooking 🗣️🗣️🗣️

2024-09-17 08:39 UTC, MemesHodachy commented
let him cook dat 🔥

2024-09-17 15:14 UTC, deltanedas commented
the whisper stuff from #17898 needs to be fixed with a chat refactor, right now if i want to have it i would need to copy paste all of its logic to hide identity in the transcript

2024-09-17 16:16 UTC, beck-thompson commented
Fourth times the charm! Good luck 🫡

2024-09-26 17:06 UTC, slarticodefast commented
Will need to be adjusted for #30798

2024-10-27 15:02 UTC, UrPrice commented
@metalgearsloth heyo, is it ready for review or merge? 3rd iteration of tape recorder, we soon start merge for us earlier than it will be merge to upstream

2024-10-28 16:21 UTC, stalengd requested changes
Pretty sure this should be localized

2024-10-28 16:21 UTC, stalengd commented on Content.Shared/TapeRecorder/SharedTapeRecorderSystem.cs
> +        var cassetteName = "Unnamed";
```suggestion
        var cassetteName = Loc.GetString("tape-recorder-menu-cassette-unnamed");
```

2024-10-28 16:21 UTC, stalengd commented on Resources/Locale/en-US/taperecorder/taperecorder.ftl
> +
```suggestion
tape-recorder-menu-no-cassette-label = Cassette tape is not inserted
tape-recorder-menu-cassette-unnamed = Unnamed
```

2024-12-20 17:36 UTC, Strol20 commented
Will this be merged after the chat refactoring?

2024-12-20 22:01 UTC, Strol20 commented
Sorry for my English

2024-12-21 14:18 UTC, deltanedas commented
guess maints dont want it, using it downstream then

2024-12-21 14:18 UTC, closed without merging

2024-12-21 14:33 UTC, Strol20 commented
Please open pr. Sooner or later someone would check and merge.

2024-12-21 14:54 UTC, deltanedas commented
i dont want to deal with merge conflicts for another year when nobody cares

2024-12-24 18:15 UTC, Vonsant commented
I feel so sad right now.

2025-01-03 06:17 UTC, NakataRin commented
With all my heart I wish for this to be implemented. But yet again, no luck

2025-01-03 07:34 UTC, deltanedas commented
notice how nobody begging for it is a maintainer... :trollface:

2025-01-03 18:30 UTC, JIPDawg commented
> notice how nobody begging for it is a maintainer... :trollface:

What if you became that maintainer.

2025-01-22 21:56 UTC, dffdff2423 commented
the day deltanedas creates a discord account is the day the world ends.