Station ai radio sounds
space-wizards/space-station-14 pull request #32246
Opened 2024-09-17 10:56 UTC by Callmore

## About the PR

Adds a sound that is played whenever the station AI talks on their radio. The AI talking on intercoms in unaffected.

## Why / Balance

Makes it easier for the AI to say stuff and get noticed instead of blending into the chat with the rest of the crew.

## Technical details

Added a new event, `RadioModifyMessageEvent`, that can modify a radio message before it is sent. It recives the chat message that was about to be sent, the radio channel and the entity that sent the message.
This event is raised after the chat message is created, but before it is sent to anyone.

The chat message methods now take an audio specifier instead of a sound path and volume. I did this so I could modify the sound varience on the sound for the chat message.

## Media

https://github.com/user-attachments/assets/a942ae5f-4778-43bf-9bbe-5e84306d97fd

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Chat methods have been changed to use sound specifiers instead of accepting a path and volume seperately.

**Changelog**

:cl:
- add: Station AI now makes a sound whenever it speaks over the radio.

2024-09-17 11:00 UTC, Djungelskog2 commented
https://github.com/space-wizards/space-station-14/pull/30780 see here for feedback/similar issues

2024-09-17 11:01 UTC, Callmore commented
FUCK

2024-09-17 11:03 UTC, muburu commented
a better solution to this would be a job icon appearing near their name in chat

2024-09-17 11:59 UTC, ScarKy0 commented
If there is an event that can modify stuff id love for AI to have a job icon visible behind their name when speaking
Since engine supports chat icons now

2024-09-17 12:02 UTC, lzk228 commented
> Since engine supports chat icons now

IT DOES?!

2024-09-17 12:13 UTC, ScarKy0 commented
> IT DOES?!
As of recently https://github.com/space-wizards/RobustToolbox/pull/5428
![image](https://github.com/user-attachments/assets/0d281e2b-7f50-4df6-9034-0e9e589466b9)

2024-09-17 12:26 UTC, UbaserB commented
no way

2024-09-29 14:40 UTC, Callmore commented
oh it just autopushed it ok uhhh
surely it isn't broken right

2024-09-29 15:09 UTC, VasilisThePikachu requested changes

2024-09-29 15:09 UTC, VasilisThePikachu commented on Content.Shared/Chat/MsgChatMessage.cs
> +        /// </summary>
```suggestion
        /// <summary>
        /// Sound that should be played when other people receive this message.
        /// </summary>
```
Minor spelling fail

2024-09-29 15:09 UTC, VasilisThePikachu commented on Content.Server/Radio/EntitySystems/RadioMessageModifierSystem.cs
> +    public readonly SoundSpecifier RadioAiSound = new SoundPathSpecifier("/Audio/Voice/Talk/radio_ai.ogg", AudioParams.Default.WithVariation(0.125f));
Hard coded

2024-09-29 15:09 UTC, VasilisThePikachu commented on Content.Server/Radio/EntitySystems/RadioMessageModifierSystem.cs
> +    }
This should probably be part of the AI code and not on a random event

2024-09-29 15:57 UTC, deltanedas commented
wont this make impersonating the ai impossible

2024-09-29 16:54 UTC, Callmore commented on Content.Shared/Chat/MsgChatMessage.cs
> +        /// </summary>
ok

2025-04-18 15:12 UTC, slarticodefast commented
Closing this since this has to wait for the chat refactor and will likely need to be rewritten afterwards.

2025-04-18 15:12 UTC, closed without merging

2025-04-18 21:21 UTC, walksanatora commented
> a better solution to this would be a job icon appearing near their name in chat

starlight actually has this @muburu and I love it. A because it allows me to pick and choose and weight the opnions of members of radio based on their job (hearing greytide saing singuloose versus the CE saying singuloose are two very diffrent things). and makes it clearer if that name is the AI or a borg.

2025-04-18 23:18 UTC, Callmore commented
it's probably a nice solution, i think some 13 servers do in fact add the job title or icon to your messages, but it would of be out of scope of this pr, and wouldn't really help the issue of the ai getting ignored
plus, hopefully after chatrefactor (assuming it doesn't just disappear), silicons will have monospace text, ai text itself could be made bigger and the clown can speak in bright pink comic sans