Add camera visor
space-wizards/space-station-14 pull request #32254
Opened 2024-09-17 16:59 UTC by ArZarLordOfMango

## About the PR

Added camera visor. These are goggles that allow you to look at the world as an AI (they don't allow you to look through walls, just give you a “noise” effect). You can also turn them on and off by action. They're can researched in the experimental branch.
## Why / Balance

Playing as an AI, sometimes it can be difficult to explain where to put the cameras to get a better field of view. Especially if you don't know the map.
## Technical details

## Media

![Screenshot 2024-09-17 173735](https://github.com/user-attachments/assets/93966bae-8cb2-44ed-8bca-409c5b4e387d)
![Screenshot 2024-09-17 173903](https://github.com/user-attachments/assets/b60261ce-7dcd-4d66-9890-9004899222c8)
![Screenshot 2024-09-17 174019](https://github.com/user-attachments/assets/e5e3f9a4-1d41-4b48-997d-e5461732082b)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: Added camera visor. Goggles that allow you to see as an AI

2024-09-17 17:05 UTC, muburu commented
it'd be funny of the sprite was like a blocky VR headset

2024-09-17 17:12 UTC, Everturning commented
i love this because it both buffs traitors and AI and thats hilarious to me

2024-09-17 20:35 UTC, lzk228 commented
would be neat to make not AI overlay, but like make visionless zone darkened or something

2024-09-19 01:28 UTC, HerCoyote23 commented
I'd recommend you change the item description to to something like:
Advanced visor which displays camera view ranges. Useful for working with the Station AI.

as the current: 
Advanced glasses are designed to look like through cameras. Useful for working with Station AI.

is grammar-wise pretty rough.

2024-09-20 23:01 UTC, slarticodefast commented
Hey, I brought this up for maintainer discussion. Instead of making this its own item, could you add this functionality to the diagnostic HUD instead?

2024-09-22 15:33 UTC, slarticodefast commented
Did some more testing and found a bug:
Take the glasses into your hands, activate them and drop them. You will keep the overlay.

![Screenshot (291)](https://github.com/user-attachments/assets/0918bb21-3b99-443c-a9b5-bebaede4b3d8)

Also the shadows look a little weird sometimes when there is static, but I'm not sure how this could be prevented ecxept by allowing you to look through walls (assuming there is a camera), which would be quite powerful.

![Screenshot (290)](https://github.com/user-attachments/assets/b44ac21e-88bc-4d1a-a07a-db24d6657e4e)
![Screenshot (289)](https://github.com/user-attachments/assets/072fdb8f-b0e5-4831-bee3-6f4a868a5b0d)

2024-11-17 19:25 UTC, ArZarLordOfMango commented
i hate my life and git...

2024-11-17 19:40 UTC, slarticodefast commented
holy hell
![grafik](https://github.com/user-attachments/assets/3d21c623-9fa8-46a9-a6db-9d8eaca5bc10)

2025-01-04 15:08 UTC, SlamBamActionman requested changes

2025-01-04 15:08 UTC, SlamBamActionman commented on Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
> +  name: Toggle camera mod
```suggestion
  name: Toggle Camera Mod
```
Capitalize

2025-01-04 15:08 UTC, SlamBamActionman commented on Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
> +    - type: StationAiOverlay
This won't work because StationAiOverlay also (somehow) handles allowing access to items within view. 

In effect, this means you gain telekinesis because you can grab any item within view of your screen. This would need to be fixed, likely by separating the StationAiOverlay behavior into visual behavior and interaction behavior.

2025-01-04 15:08 UTC, SlamBamActionman commented on Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
> +  description: A heads-up display that scans the humas in view and provides accurate data about their health status.
Erroneously edited description.

2025-01-04 15:08 UTC, SlamBamActionman commented on Resources/Prototypes/Recipes/Lathes/robotics.yml
> +- type: latheRecipe
Add to the CL that you can now print the huds as a research unlock.

2025-01-06 01:34 UTC, deltanedas commented
this lets you toggle doors and stuff which is bad

2025-03-21 08:58 UTC, TheShuEd commented
This PR has been in “Awaiting changes” status for over 3 months now without any visible updates, so I'm closing it as derelict. If you nevertheless plan to continue, please comment it and the PR will be reopened.

If you need help, you can ask questions in discord or in this PR

2025-03-21 08:58 UTC, closed without merging