Ignore intern roles for traitor kill objective
space-wizards/space-station-14 pull request #32288
Opened 2024-09-18 22:28 UTC by lzk228

![image](https://github.com/user-attachments/assets/58d0bd4c-c74b-4917-8aa5-fa6a2d47ab06)

## About the PR

Intern, tech assist and research assist now can't be traitor kill objectives.

## Why / Balance

to resolve #32271 

## Technical details

add new list of jobs in PickRandomPersonComponent
then for pick check if any of humans has the job in list
remove human from list

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Intern, technical assistant and research assistant now can't be traitor kill objectives.

2024-09-18 22:34 UTC, beck-thompson commented
I always skip the objectives if its an intern as well. Really good idea!

2024-09-18 22:48 UTC, Cojoke-dot commented
Service worker needs to be added if that pr to make them an intern job ever gets merged...

2024-09-18 22:59 UTC, Boaz1111 commented
intern should probably be clarified into medical intern in the CL, also, why does this not include cadets? Because they’re sec?

2024-09-18 23:01 UTC, lzk228 commented
> Because they’re sec?

you have to play 15 hours overall to play as cadet
also for me sounds weird that syndicate wouldn't want to kill security guys

2024-09-19 07:36 UTC, pheenty commented
Add heads to this as well, heads should always fall under kill (not maroon) objective

2024-09-19 07:39 UTC, cohanna commented
> Add heads to this as well, heads should always fall under kill (not maroon) objective

I don't see why?

2024-09-19 07:53 UTC, pheenty commented
> > Add heads to this as well, heads should always fall under kill (not maroon) objective
> 
> I don't see why?

Because a couple of months ago antag difficulty has been correctly capped, but still one traitor can get "kill the RD and escape unrestrained" and the other can get something absurd like "kill or maroon the captain, kill or maroon the hos and escape unrestrained", because maroon objectives are considered easier (a maroon objective, say, a bartender, can die on their own and nobody would care, and in general killing a bartender is of course easier then a captain)

2024-09-19 10:34 UTC, Sarahon commented
I don't really see it making much of a difference? If the person teaching the intern is the target, then the same issue persists? It's not like it's impossible to learn just because you're a possible target. The game overall just isn't really that beginner friendly and par for the course honestly. 

Like you can make all intern roles non-targeted, but the person teaching them may be targeted, so teaching halts once again.

2024-09-19 23:59 UTC, deltanedas requested changes

2024-09-19 23:59 UTC, deltanedas commented on Content.Server/Objectives/Components/PickRandomPersonComponent.cs
> +    [DataField, ViewVariables(VVAccess.ReadWrite)]
just [DataField]

2024-09-19 23:59 UTC, deltanedas commented on Content.Server/Objectives/Systems/KillPersonConditionSystem.cs
> +            .ToList();
use RemoveAll instead of linq funny

2024-09-20 15:36 UTC, Everturning commented
> At that point why not just make most, if not all service roles non-target since they're also usually where new players are recommended?

this is a false dichotomy, as even if new players are recommended to do service, that does not mean all service players are new players just because thats recommended.

2024-09-27 00:20 UTC, Sarahon commented
> > At that point why not just make most, if not all service roles non-target since they're also usually where new players are recommended?
> 
> this is a false dichotomy, as even if new players are recommended to do service, that does not mean all service players are new players just because thats recommended.

and not all interns are new either? It's way more likely a new player is gonna be service vs a department intern. Like it's globally recommended people start janitor for their first few times playing I thought?

2024-10-02 14:01 UTC, closed without merging

2024-10-02 14:01 UTC, slarticodefast commented
Hey, we had a maintainer vote and the result was to close this PR for the following reasons:
- Being an intern does not equal being a new player. You could have lots of playtime in other departments or on other servers.
- Being killed by antagonists is part of the game, the story it is telling and not always something negative. It can even be a good thing for newer player to learn that early.
- There are other antagonists where such a safety feature does not exist (nukies, revs, eventually Wizard)

Thank you for your contribution.

2024-10-02 14:02 UTC, lzk228 commented
weh, okay, it was good experience tho