AI now uses the criminal console instead of the station console to view records.
space-wizards/space-station-14 pull request #32307
Opened 2024-09-19 17:02 UTC by ScarKy0

## About the PR

Make the AI Station Records action instead be the Criminal Records console.

## Why / Balance

The station records is useless and just an inferior version of the criminal records console. AI had essentially no use with it anyways. Now you can at least set criminals as wanted when sec asks you to without flying across the map.

## Technical details

Made the CriminalRecordsConsole component networked.
Added a new action for AI to seperate aghost's station records and ai's criminal records. (Since Aghost is supposed to be able to delete the records, which AI couldnt do anyways)

## Media

![image](https://github.com/user-attachments/assets/15fbb929-d439-4ffb-b294-044985cba12f)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: AI now uses a criminal console instead of the station records console.

2024-09-19 17:34 UTC, Dutch-VanDerLinde commented
why? Criminal records give you less information about the person than station records, and AI shouldn't really be setting criminals to wanted, that's the Wardens job

2024-09-19 17:35 UTC, ScarKy0 commented
> why? Criminal records give you less information about the person than station records, and AI shouldn't really be setting criminals to wanted, that's the Wardens job

Ive never seen the station records be used either way.
And security keeps yelling at AI to change wanted status anyways, might as well make it easier whenever possible.

2024-09-19 17:40 UTC, superjj18 commented
> why? Criminal records give you less information about the person than station records, and AI shouldn't really be setting criminals to wanted, that's the Wardens job

1. Robocop law set
2. AI is already perfectly capable of utilizing the criminal records terminals anyways, so this is more QoL than a new functionality/ai powercreep

You are correct though about station records havi no more info, I honestly think ai should have both and the ai player can pick and choose what terminals they want on hand with the actions menu

Other than that it is perfectly reasonable to give ai quick access without needing to scroll around looking for a terminal to jump into

2024-09-19 21:01 UTC, Plykiya commented
As with the mindshield and wanted status vision, I don't really think it's a good idea to push the AI towards security-sided gameplay. Every tool that's given to them is an official "this is what you are expected to do for the station", so having a criminal records computer on demand will make AI players think this is what they should be doing

2024-09-19 21:20 UTC, ScarKy0 commented
> As with the mindshield and wanted status vision, I don't really think it's a good idea to push the AI towards security-sided gameplay. Every tool that's given to them is an official designation of "this is what you are expected to do for the station", so having a criminal records computer on demand will make AI players think this is what they should be doing

You see this is already a thing AI can do by simply flying across the map to security
this simply removes the fly across the map part and still serves essentially the same purpose
its not like letting AI see wanted status to report people instantly, simply means u dont gotta cross the map to do what you already could do
Besides borgs can see mindshield status im still confused why AI shouldnt

2024-09-19 21:52 UTC, 0x6273 commented
> You see this is already a thing AI can do by simply flying across the map to security
this simply removes the fly across the map part and still serves essentially the same purpose

Is this really intended? I think AI being able to view criminal records is good, but changing them should be sec's job.

2024-09-19 21:56 UTC, superjj18 commented
> Besides borgs can see mindshield status im still confused why AI shouldnt

If Borgs see mind-shield/wanted status then that is a bug

2024-09-19 22:01 UTC, ScarKy0 commented
>If Borgs see mind-shield/wanted status then that is a bug

they do in fact see mindshields and ive never seen it be called a bug

2024-09-20 11:53 UTC, superjj18 commented
> >If Borgs see mind-shield/wanted status then that is a bug
> 
> 
> 
> they do in fact see mindshields and ive never seen it be called a bug

This was supposed to be changed #26207, not that im against this pr but yes it is intended for Borgs to not see mind-shields or wanted status for the same reasons why AI can't

2024-09-21 17:34 UTC, Moomoobeef commented
> > why? Criminal records give you less information about the person than station records, and AI shouldn't really be setting criminals to wanted, that's the Wardens job
> 
> Ive never seen the station records be used either way. And security keeps yelling at AI to change wanted status anyways, might as well make it easier whenever possible.

I use station records :(
And security really just needs to learn that that isn't the AI's job.

2024-09-23 03:23 UTC, superjj18 commented
> And security really just needs to learn that that isn't the AI's job.

"AI set x to wanted for y" seems like a perfectly reasonable request for an on-board station ai.  AIs job is whatever the crew deems its job to be.  Hell if someone asks for the AI to mark someone as wanted the AI literally cannot say no under Asimov laws due to law two.

So yes if someone tells the ai to mark someone as wanted it 100% is the ai's job.

2025-04-16 23:43 UTC, EmoGarbage404 requested changes

2025-04-16 23:43 UTC, EmoGarbage404 commented on Content.Shared/CriminalRecords/Components/CriminalRecordsConsoleComponent.cs
> +[RegisterComponent, NetworkedComponent, AutoGenerateComponentState]
It seems like you were trying to do prediction for this component but you never properly dirty any of these values. Is there some part of this that i missed?

2025-04-16 23:51 UTC, EmoGarbage404 commented
Maintainer team have decided to close this PR.

The general sentiment is that the AI should not have blanket inherent access to all powerful station consoles. Additionally, hunting criminals is not the AIs primary job and should not be facilitated to this degree.

Thank you.

2025-04-16 23:51 UTC, closed without merging