Localizable craftmenu
space-wizards/space-station-14 pull request #32339
Opened 2024-09-20 21:56 UTC by Ertanic

## About the PR

The name and description of the target crafting items are now taken directly from the prototypes.

## Why / Balance

## Technical details

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- tweak: The name and description of the target crafting items are now taken directly from the prototypes.

2024-09-20 22:06 UTC, slarticodefast commented
Wouldn't that cause problems with things like secret walls that have a different name?

2024-09-20 22:14 UTC, Ertanic commented
> Wouldn't that cause problems with things like secret walls that have a different name?

Very likely. But exactly the secret door in the prototype itself is referred to as a solid wall. 

![image](https://github.com/user-attachments/assets/5d7b8d57-626a-40e6-a45f-0c47762303fc)

2024-09-20 22:31 UTC, slarticodefast commented
Yeah, that's a problem, you won't know which one is which if you don't know the recipe. Maybe add an optional translation string to the crafting menu entry that overrides the prototype name if necessary.

2024-09-20 22:35 UTC, chavonadelal commented
> Yeah, that's a problem, you won't know which one is which if you don't know the recipe. Maybe add an optional translation string to the crafting menu entry that overrides the prototype name if necessary.

No, I don't think that's an option! So localization could be ruined again... Although, only if it's LocID, then maybe...

2024-09-25 03:10 UTC, Ertanic commented
> Yeah, that's a problem, you won't know which one is which if you don't know the recipe. Maybe add an optional translation string to the crafting menu entry that overrides the prototype name if necessary.

I left the ability to overload prototype craft names manually via fluent keys. Among other things, I added an optional ability to output suffixes. 

At the request of @chavonadelal I made it possible to pull sprites from target prototypes. I didn't bother and just replaced ItemList and TextureRect by ListContainer and EntityPrototypeView. Then I will remove unused icon fields in construction prototypes.

![image](https://github.com/user-attachments/assets/42afcfc8-2f1a-4e50-9d8c-b2cada96b7b9)

![image](https://github.com/user-attachments/assets/09f63881-758f-41c5-b3e7-8ee9d5e94a85)

2024-09-25 05:22 UTC, mirrorcult commented
extremely blessed PR

2024-09-25 06:22 UTC, lzk228 commented
> I left the ability to overload prototype craft names manually via fluent keys. Among other things, I added an optional ability to output suffixes.

pjb once said
![image](https://github.com/user-attachments/assets/57b37e9a-5204-4f1b-bade-7014b8763b2d)

2024-09-26 20:14 UTC, Ertanic commented
Sneaky rider decided to brush up on unused imports.....

2024-09-29 02:24 UTC, metalgearsloth commented
so:
- I got randomly pinged over this PR merge-begging for it when it was only a few days old.
- I look at the engine PR and it's bandaiding a bug and 2 maintainers ask for it to be investigated (whether it's tests or control-related).
- Instead you tell us it's someone else's problem and refuse to fix it and we should prioritise your PR instead as someone else can fix the bug.

If you keep insisting our engine is so bad is the better solution not to investigate the root causes of issues and fix those instead of symptoms?

2025-02-02 20:26 UTC, chavonadelal commented
WOW

2025-04-08 14:26 UTC, cfif126 commented
hi plz merge

2025-04-13 15:30 UTC, chavonadelal requested changes
Use only the LocID fields

2025-04-13 15:30 UTC, chavonadelal commented on Content.Shared/Construction/Prototypes/ConstructionPrototype.cs
> +    public string? Description;
```suggestion
    public LocId? Description;
```

Use only the LocID field so that your work doesn't go down the drain when someone decides to add non-localized text.

2025-04-13 15:30 UTC, chavonadelal commented on Content.Shared/Construction/Prototypes/ConstructionPrototype.cs
> +    public string? Name;
```suggestion
    public LocId? Name;
```
Use only the LocID field so that your work doesn't go down the drain when someone decides to add non-localized text.

2025-05-01 04:59 UTC, EmoGarbage404 approved these changes

2025-05-01 04:59 UTC, EmoGarbage404 commented
there's a small visual issue but it's related to the engine-side UI code. I'll put up a fix shortly.

2025-05-01 05:15 UTC, metalgearsloth approved these changes

2025-05-01 14:16 UTC, ScarKy0 commented
I'll look at it in-game later and merge if its fine
If another maintainer wants to merge before me feel free

2025-05-01 14:21 UTC, merged