Adding intellicard functionality.
space-wizards/space-station-14 pull request #32347
Opened 2024-09-21 11:46 UTC by ScarKy0

## About the PR

Intellicards can now be used to remove/insert the current AI from the core.

## Why / Balance

Killing AI makes sense... I think

## Technical details

The brain slot on intellicards and ai core is unlocked but cannot eject, making intellicards swap the brain between itself and the core.

## Media

https://github.com/user-attachments/assets/b26716e3-1b4d-42b5-a62d-f225da3e43fc

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## TODO
- [ ] Make swapping the brain a doAfter.
- [ ] Fix a bug where actions duplicate on removing and inserting the brain.
- [ ] Update laws on inserting into the core, in case the upload console is used while AI brain is taken out. (Maybe)

## Breaking changes

**Changelog**

:cl:
- add: Added missing intellicard functionality.

2024-09-21 11:47 UTC, ScarKy0 commented
If someone knows how to do anything in the TODO please tell me because I don't 😭

2024-09-21 12:18 UTC, deltanedas commented
> Make swapping the brain a doAfter.

i think ItemSlot has a field for this that rmc added

2024-09-21 12:20 UTC, ScarKy0 commented
> i think ItemSlot has a field for this that rmc added

From what ive seen ItemSlotsComponent doesnt have a field for doAfter, unless im missing something

2024-09-21 21:11 UTC, ScarKy0 commented
God bless fildrance

2024-09-23 03:45 UTC, superjj18 commented
Just need to make ai cores buildable and anchorable and then AI’s can successfully be revived after being disconnected from the station.

2024-09-23 08:35 UTC, AverageNotDoingAnythingEnjoyer commented
Maybe it shouldn't spawn in RD locker for now, as AI still doesn't have ways to protect itself against an antag breaking in and carding them

2024-10-14 03:52 UTC, metalgearsloth commented on Content.Shared/Silicons/StationAi/SharedStationAiSystem.cs
> +        }
Pretty sure actionsystem has a method for this like clearactions.

2024-10-14 03:53 UTC, metalgearsloth requested changes
Remove the PAI stuff for now I reckon.

2024-10-14 09:08 UTC, ScarKy0 commented
Well shit its all on fire

2024-10-22 13:49 UTC, merged

2024-10-22 13:50 UTC, slarticodefast commented
Tested in-game and works as intended.

2024-10-22 14:47 UTC, superjj18 commented
Can we perhaps remove mapped intellicards and instead put one in RD's locker?

2024-10-23 05:31 UTC, ScarKy0 commented
> Make the intelicard require a lenghty do-after like disarming the nuke does. That way someone can't just suicide rush into AI chamber and intelicard them away, and also provides a MALF AI or just regular AI in general the chance to warn crew or fight back before they are completely neutralized. Perhaps even make it tell the AI "hey someone is uploading you into an Intelicard!"

Thats the plan!
I will be trying to do something similiar when I continue working on intellicards after this, for now this serves as a basic way to be able to kill the AI

> Can we perhaps remove mapped intellicards and instead put one in RD's locker?

There is one in RD's locker but I know nothing of mapping to remove the mapped ones