Faxes are colored again
space-wizards/space-station-14 pull request #32353
Opened 2024-09-21 15:30 UTC by AsnDen

## About the PR
I've noticed that faxes lost their colors (blue for centcomm and black for sindye)

Hope I've done everything correctly

## Why / Balance
They had their colors but somehow lost them.

## Technical details
Changed layer for fax. Changed sprites for inserting and printing (removed fax from them).

It looked like that `color` also changes color for paper (it looked strange)

Haven't changed `FaxVisualsSystem` (cause I don't know how and what I should change, so just decreased `Length`).

I have removed unique animations when fax gets message (probably I will try to restore them soon)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- fix: Faxes have their colors again

2024-11-05 17:53 UTC, slarticodefast commented
Could you add some before/after in-game screenshots to your PR description?

2024-11-07 18:43 UTC, AsnDen commented
> Could you add some before/after in-game screenshots to your PR description?

Have added some. Found a bug, will fix it soon

2025-01-04 14:35 UTC, SlamBamActionman requested changes
Something about changing the animation times is causing the animation when printing a sent fax to start on the wrong frame from the second fax onwards. 

See if you can fix that. Otherwise, PR looks good!

2025-03-21 08:59 UTC, TheShuEd commented
This PR has been in “Awaiting changes” status for over 3 months now without any visible updates, so I'm closing it as derelict. If you nevertheless plan to continue, please comment it and the PR will be reopened.

If you need help, you can ask questions in discord or in this PR

2025-03-21 08:59 UTC, closed without merging