Predict dumping
space-wizards/space-station-14 pull request #32394
Opened 2024-09-23 05:21 UTC by metalgearsloth

- This got soaped really fucking hard.
- Dumping is predicted, this required disposals to be predicte.d
- Disposals required mailing (because it's tightly coupled), and a smidge of other content systems.
- I also had to fix a compnetworkgenerator issue at the same time so it wouldn't mispredict.

Breaking namespace changes for a bunch of stuff that got predicted / needed to be in shared, mostly device network + configurator + disposals.

Requires https://github.com/space-wizards/RobustToolbox/pull/5459 so it doesn't mispredict.

2024-09-23 15:57 UTC, notquitehadouken commented
Me when fixing one issue creates a 1500 line PR

2025-02-10 17:07 UTC, slarticodefast requested changes
I don't really understand the power receiver change.
And I haven't done in-game testing yet.

2025-02-10 17:25 UTC, slarticodefast commented
Ok, test result: I am getting debug asserts when tagging a mailing unit with a multitool.
```
An unhandled exception of type 'System.InvalidCastException' occurred in System.Private.CoreLib.dll: 'Unable to cast object of type 'Content.Client.Disposal.Unit.DisposalUnitBoundUserInterface' to type 'Content.Client.Disposal.Mailing.MailingUnitBoundUserInterface'.'
   at Robust.Shared.GameObjects.SharedUserInterfaceSystem.TryGetOpenUi[T](Entity`1 entity, Enum uiKey, T& bui) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedUserInterfaceSystem.cs:line 900
   at Content.Client.Disposal.Mailing.MailingUnitSystem.OnMailingState(Entity`1 ent, AfterAutoHandleStateEvent& args) in D:\Code\SS14\space-station-14\Content.Client\Disposal\Mailing\MailingUnitSystem.cs:line 17
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 678
   at Content.Shared.Disposal.Components.MailingUnitComponent.MailingUnitComponent_AutoNetworkSystem.OnHandleState(EntityUid uid, MailingUnitComponent component, ComponentHandleState& args) in D:\Code\SS14\space-station-14\Content.Shared\Robust.Shared.CompNetworkGenerator\Robust.Shared.CompNetworkGenerator.ComponentNetworkGenerator\MailingUnitComponent_CompNetwork.g.cs:line 53
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass56_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 305
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 678
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(EntityUid uid, NetEntity netEntity, MetaDataComponent meta, IEventBus bus, EntityState curState, EntityState nextState, GameTick lastApplied, GameTick toTick, Boolean enteringPvs) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 1391
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 902
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 741
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 388
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 540
   at Robust.Client.GameController.<StartupContinue>b__60_0(Object sender, FrameEventArgs args) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 229
   at Robust.Shared.Timing.GameLoop.Run() in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass102_0.<Run>b__0() in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 106
```

2025-03-02 03:29 UTC, metalgearsloth commented on Content.Shared/Configurable/ConfigurationComponent.cs
>  namespace Content.Shared.Configurable
I don't really know what it does but I can try figuring it out

2025-04-19 02:25 UTC, metalgearsloth commented on Content.Server/Atmos/Monitor/Systems/FireAlarmSystem.cs
> +using DeviceNetworkComponent = Content.Shared.DeviceNetwork.Components.DeviceNetworkComponent;
I do as rider provides

2025-04-19 02:40 UTC, metalgearsloth commented on Content.Shared/Content.Shared.csproj
> +    <Folder Include="Disposal\Tube\Components\" />
For rider to troll me of course.

2025-04-19 03:24 UTC, metalgearsloth commented on Content.Shared/Disposal/SharedDisposalUnitSystem.cs
> -        }
Should beTM

2025-04-19 06:20 UTC, merged

2025-04-19 10:40 UTC, slarticodefast commented
You didn't even let me re-review 😦