fix powered lights electrocuting you despite having insulated gloves
space-wizards/space-station-14 pull request #32409
Opened 2024-09-23 14:48 UTC by MilonPL

## About the PR

Lights will no longer electrocute you while wearing any gloves with the InsulatedComponent

## Why / Balance

i'm guessing that was always the indented behavior but no one implemented it because of how the AttackedEvent works, considering how it checks for the component when interacting
also needed to fix https://github.com/DeltaV-Station/Delta-v/issues/909 downstream

## Technical details

Checks for InsulatedComponent on the entity (if for whatever reason it has one), if false, moves on to check the gloves, and adjusts the siemens coefficient accordingly, otherwise defaults to 1.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None

**Changelog**

:cl:
- fix: Punching lights while wearing insulated gloves will no longer electrocute you.

2024-09-23 23:37 UTC, metalgearsloth commented on Content.Server/Electrocution/ElectrocutionSystem.cs
> +        DoCommonElectrocution(args.User, uid, component.UnarmedHitShock, component.UnarmedHitStun, false, siemens);
Spelling dude.

Also if there isn't there needs to be a helper method for this.

2024-12-20 11:19 UTC, TheShuEd approved these changes

2025-02-25 13:21 UTC, slarticodefast commented
@MilonPL Can you have another look at this implementation? It looks really hacky to me hardcoding the gloves slot like this.
Like sloth said, this should be either a helper method or a relay event.

2025-04-18 01:33 UTC, metalgearsloth commented
> @MilonPL Can you have another look at this implementation? It looks really hacky to me hardcoding the gloves slot like this. Like sloth said, this should be either a helper method or a relay event.

I mean you could relay it but it's mmm

2025-04-18 08:58 UTC, slarticodefast requested changes

2025-04-18 08:58 UTC, slarticodefast commented on Content.Server/Electrocution/ElectrocutionSystem.cs
> +        DoCommonElectrocution(args.User, uid, component.UnarmedHitShock, component.UnarmedHitStun, false, GetSiemensCoefficient(args.User));
Just replace this with `DoCommonElectrocutionAttempt`, which raises the relay event checking for insulated gloves.
Delete the rest.

2025-04-18 11:52 UTC, metalgearsloth commented
https://discord.com/channels/310555209753690112/900426319433728030/1362714222290534502

2025-04-18 11:52 UTC, closed without merging