Changing the thief's objective to stealing ID cards.
space-wizards/space-station-14 pull request #32411
Opened 2024-09-23 15:32 UTC by kosticia

## About the PR
Currently, the thief has an unreasonably difficult goal, especially during lowpop. This can require stealing a huge number of ID cards, namely 15. Additionally, this goal has an extremely easy difficulty for the game itself. With my change, I am proposing to change the maximum number of required IDs from 15 to 10.

## Why / Balance
This objective may require literally stealing ID cards from every second person during low-pop. This is just so much difficult, given the presence of other objectives of the thief.

## Technical details
The maximum number of required cards has been changed from 15 to 10. The difficulty of the objective itself has been increased from 0.7 to 1.

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- tweak: The maximum number of ID cards required to complete a thief's objective has been changed from 15 to 10.

2024-09-23 15:45 UTC, Cojoke-dot commented
It's not really that difficult in comparison. The figurine one is the same but you can't steal them from people, you just have to get lucky and find them around the station or buy them. With the id you at least know where they are and can still buy more. Top that with objectives like steal 5 stamps or door remotes? Its current balance is pretty on par with other objectives.

2024-09-23 15:53 UTC, deltanedas commented
figurine is literally just buying them, every single round theres no way you can get 18 figurines otherwise

2024-09-23 15:57 UTC, Cojoke-dot commented
> figurine is literally just buying them, every single round theres no way you can get 18 figurines otherwise

You can buy id too. Figurines are just worse because you're not stealing them, you're not being a thief. Stealing is the whole point of the antag, stealing a ton of things(ids) is the whole point.

2024-09-23 16:01 UTC, kosticia commented
> The figurine one is the same but you can't steal them from people, you just have to get lucky and find them around the station or buy them. With the id you at least know where they are and can still buy more.

I think the figures are the problem with the maps. On a conventional Train, this goal is quite fun to accomplish.
>Top that with objectives like steal 5 stamps or door remotes? Its current balance is pretty on par with other objectives.

 I have never seen any problems with stamps and remote remotes from airlocks, there were always enough of them

2024-09-27 19:06 UTC, slarticodefast requested changes

2024-09-27 19:06 UTC, slarticodefast commented on Resources/Prototypes/Objectives/thief.yml
> +    difficulty: 1
```suggestion
    difficulty: 0.7
```
The number reduction is good, but keep the old difficulty, please.

2024-09-30 22:37 UTC, slarticodefast approved these changes

2024-09-30 22:40 UTC, slarticodefast commented
I went ahead and adjusted the objective difficulty for you. Thank you for your contribution.

2024-09-30 22:40 UTC, merged