DSword Replacement - the Hypereutactic Blade
space-wizards/space-station-14 pull request #32414
Opened 2024-09-23 17:03 UTC by keronshb

## About the PR

This adds the Hypereutactic Blade, a gigantic esword that requires 2 hands to wield and has slowdown.

## Why / Balance

Another take on "esword but better" but with actual sidegrade ramification this time.

When in hand, the hilt/blade slows you down significantly.
It takes longer to activate (longer use delay)
Required being wielded to use
Has a longer swing/wideswing (2.0 instead of 1.5)
Slower attack speed (0.8) to compensate for higher attack values
Higher attack values than the esword (except structural)
100% Reflect Chance
16 tc, the original dsword price

The slowdownn & slow use will hopefully find a better balancing place than the high speed and mobility of the dsword. 
While you can still stuff the hilt into your bag or pocket, it's not going to be as good of a ganking tool unless someone is cornered.

## Technical details

It's all YAML.

## Media

![image](https://github.com/user-attachments/assets/74768b9e-b367-44d8-a00e-11b91b1839c2)

https://github.com/user-attachments/assets/08901043-9ff4-431d-beea-c802dc3cb8fd

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-09-23 17:15 UTC, Kadeo64 commented
i see the highlander gamemode came early

2024-09-23 17:18 UTC, Cojoke-dot commented
uuuhhhhhhhh... this is stronger than the desword... 100% reflect is craazzzyyyy. Note:
- needs nukie blacklist
- 100% reflect means its almost impossible for sec to take you down. They need to get close and you kill them faster than you get stunned, top that with 4 spare tc to get armor/stims/noslips and your unstoppable
- the swing looks really fast in the video... idk if you can change that with just yml but it should be a slower speed because big sword

2024-09-23 17:22 UTC, deltanedas commented
nukies using this can just get the batong treatment

2024-09-23 17:23 UTC, ps3moira commented
d-sword could never be replaced

2024-09-23 17:24 UTC, Cojoke-dot commented
> nukies using this can just get the (thrown) batong treatment

You're too fast, TIME TO METH UP!!!!

2024-09-23 17:31 UTC, superjj18 commented
40 dmg swing + 100% reflect seems absolutely insane

2024-09-23 17:34 UTC, Ilya246 commented
maybe lower it to like 80% reflect or increase slowdown so the only real ranged option against the wielder is throwing but they aren't reaching you unless you're cornered

2024-09-23 17:44 UTC, Kadeo64 commented
honestly I think the biggest issue is the price
if this thing was a "major" weapon like the l6/chinalake and thus like 25-30 tc it might be more balanced
16tc is far too low for a weapon this powerful

2024-09-23 19:23 UTC, cohanna commented
100% reflect chance + jug suit my beloved

2024-09-23 21:47 UTC, Plykiya commented
100% reflect? for 16 TC? this should basically be on par with the price of an L6 or a Chinalake

2024-09-23 21:58 UTC, bruhmogus commented
this... should really just be reserved for death squad, they've had syndicate stuff far too long to be honest

2024-09-23 22:21 UTC, UltimateJester commented
I'm with everyone else, 100% deflect quite literally places at the very top for melee, which isn't even that huge considering the crew doesn't have access to melee weapons that could put down a jugsuit wielding something like this.

2024-09-23 22:24 UTC, Kadeo64 commented
to be fair I think two sec officers with batons could stun a hyperblade wielder easily but in nukies they're likely going to have support that can just shoot the officers which makes this a moot point. just remove this from nukies entirely it's too strong, and nerf price to 20-25tc so you need traitor coordination to do a stupid juggernaut meme gimmick

2024-09-23 23:38 UTC, vorkathbruh commented
everyone in here forgetting about just throwing batons lmao, super easy item to counter

2024-09-24 00:58 UTC, keronshb commented
https://github.com/user-attachments/assets/e8735be5-6abb-422f-8512-16786f8b11d5

There's easy counterplay if people look hard enough.

We're discussing the 100% reflect.

2024-09-24 05:43 UTC, Randomplayer2or3 commented
How about making you take stamina damage after each reflect by like 30% of what that hit could have done

2024-09-24 06:00 UTC, Cojoke-dot commented
> There's easy counterplay if people look hard enough.
> 
> We're discussing the 100% reflect.

one nukie whos not moving... I mean... sure... but you aren't accounting for 4 of them and a medic all moving high on stims. A spear or 30% speed reduction is only so effective against someone who takes 50% less damage from most attacks and is unaffected by the main damage source the station outputs.

2024-09-24 08:44 UTC, Plykiya commented
> Content.Client_Oo7N7QDy9G.mp4
> 
> There's easy counterplay if people look hard enough.
> 
> We're discussing the 100% reflect.

arrows not getting reflected is a bug or unintended (how is a bow more effective than a gun)

how many spears are you expecting security to have

yes, bolas and batons do exist, but so do EMP implants and various other stamina-resisting drugs that robust people will 100% use

2024-09-24 09:57 UTC, Cojoke-dot commented
Why is it an argument about the insane reflect, we've done this before. Back when reflections worked on move speed and jugsuits just took 2 eswords to become immortal? People hated that and this is just worse because you don't need a jug to become immortal.

2024-09-24 11:23 UTC, Kadeo64 commented
> There's easy counterplay if people look hard enough.

Do you know how hard it is to land enough spears/arrows to do meaningful damage against a nukie, who has both support and stims?

2024-09-24 13:48 UTC, Everturning commented
merge it, but make it so it only activates for keronshb's account

2024-09-24 14:10 UTC, Kadeo64 commented
> Okay okay okay
> 
> This is not balanced at all. 

when me and alzore agree on something, something is wrong

2024-09-24 15:52 UTC, UbaserB commented
too much ideaguys power

2025-02-03 18:57 UTC, Emisse approved these changes

2025-02-03 19:21 UTC, Errant-4 requested changes
The changelog was not updated with the uplink removal

2025-02-03 20:17 UTC, keronshb commented
> The changelog was not updated with the uplink removal

Removed

2025-02-03 21:22 UTC, Errant-4 approved these changes

2025-02-03 21:22 UTC, merged