ciggie sounds
space-wizards/space-station-14 pull request #32426
Opened 2024-09-24 04:09 UTC by deltanedas

## About the PR
plays a sound when lighting a ciggie or it goes out

## Why / Balance
good

## Technical details
replaced _active hashset with BurningComponent to track actively lit ciggies

## Media
it work

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

2024-09-24 13:06 UTC, baddiePRO commented
gone are the days of me looking like an idiot trying to smoke a cigarette butt

2024-09-24 13:55 UTC, lzk228 commented
no media?

2024-09-24 15:59 UTC, deltanedas commented
trust

2024-10-15 21:20 UTC, Centronias commented on Content.Server/Nutrition/EntitySystems/SmokingSystem.cs
> +                : smokable.SnuffSound;
```suggestion
            var sound = SoundSpecifier?;
            if (state == SmokableState.Lit)
            {
                EnsureComp<BurningComponent>(uid);
                sound = smokable.LightSound;
            }
            else
            {
                RemComp<BurningComponent>(uid);
                sound = smokable.SnuffSound;
            }
```
considering the if and ternary have the same condition.

2024-10-19 19:40 UTC, ps3moira commented
tryna smoke here

2024-12-04 02:08 UTC, metalgearsloth commented on Content.Shared/Smoking/BurningComponent.cs
> +public sealed partial class BurningComponent : Component;
networkedcomp

2024-12-27 10:16 UTC, Pumkin69 commented
media would be nice to hear the sounds

2025-01-02 23:00 UTC, ps3moira commented
here is video showcasing the sounds [ciggie sounds showcase](https://www.youtube.com/watch?v=itnw3-SJDTw)

2025-01-03 05:34 UTC, ps3moira commented
> media would be nice to hear the sounds

here's a video showcasing it [ciggie sounds showcase](https://youtu.be/itnw3-SJDTw)

2025-02-04 04:40 UTC, ps3moira commented
bump

2025-02-11 10:07 UTC, metalgearsloth approved these changes

2025-04-18 12:46 UTC, slarticodefast requested changes

2025-04-18 12:46 UTC, slarticodefast commented on Resources/Audio/Effects/attributions.yml
> +- files: ["cig_light.ogg", "cig_snuff.ogg"]
`cig_snuff` needs to be converted to mono or it will break positional audio

2025-04-18 12:46 UTC, slarticodefast commented on Content.Shared/Nutrition/Components/SmokableComponent.cs
> +        public SoundSpecifier? LightSound = new SoundPathSpecifier("/Audio/Effects/cig_light.ogg");
add documentation

2025-04-18 12:46 UTC, slarticodefast commented on Content.Server/Nutrition/EntitySystems/SmokingSystem.cs
> +                : smokable.SnuffSound;
yeah, I like this more
or even just write `PlayPvs` twice so you can remove the `SoundSpecifier? sound = null;` line

2025-04-18 12:46 UTC, slarticodefast commented on Content.Server/Nutrition/EntitySystems/SmokingSystem.cs
>                  if (!_solutionContainerSystem.TryGetSolution(uid, smokable.Solution, out var soln, out var solution))
should probably be cached with `ResolveSolution`, but not a blocker for this PR if you don't want to do more

2025-04-18 22:01 UTC, slarticodefast approved these changes
Looks good, test fail unrelated.
Thank you for your contribution and sorry for the wait.

2025-04-18 22:01 UTC, merged

2025-04-19 13:12 UTC, cfif126 commented
does this also work with cigars?

2025-04-20 01:38 UTC, deltanedas commented
yes and pipes