Alerts for silicons and ability to pull for supplybot
space-wizards/space-station-14 pull request #32468
Opened 2024-09-26 21:14 UTC by AsnDen

## About the PR
Mainly makes supplybot to pull things.
I've added alerts so supplybot can stup pilling things.

As supplybot got alerts, I thought other silicons also should get them. 

## Why / Balance
Being able to carry things seems pretty useless. 

## Technical details
Adds puller component for supplybot. Adds alerts for honk, jonk, medi, supply bots.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: Supplybot now can pull thigns.
- add: Basic silicons now can see their health and other alerts.

2024-09-26 21:39 UTC, Cojoke-dot commented
> Being able to carry things seems pretty useless.

mmmm... that means they can save people by dragging them away from an antag to med or something, not all that useless. It sounds nice though ignoring how annoying it could be for nukies or something. Paramed Cargobot real

2024-09-26 21:49 UTC, lzk228 commented
i added alerts in #29949
and if this pr will be merged first, as #31471 was merged with feature that was in my pr, i am gonna blow up i swear

2024-09-26 21:50 UTC, lzk228 commented
tho how bots can pull? with what?

2024-09-27 04:45 UTC, AsnDen commented
> > Being able to carry things seems pretty useless.
> 
> mmmm... that means they can save people by dragging them away from an antag to med or something, not all that useless.

I have ment current situation, it can carry things that somebody has put in it

2024-09-27 14:09 UTC, AsnDen commented
> tho how bots can pull? with what?

Same energy as cobra. He just can

https://github.com/user-attachments/assets/f5757b1a-df91-4161-9889-2ea10093ad5a

2024-09-27 15:33 UTC, Plykiya commented
> Being able to carry things seems pretty useless.

I've turned supply bots into mobile armories or medbays. It's not useless at all. It just relies on working with other people.

2024-09-27 17:09 UTC, AsnDen commented
> > Being able to carry things seems pretty useless.
> 
> I've turned supply bots into mobile armories or medbays. It's not useless at all. It just relies on working with other people.

Cool ideas. But it is mainly the **supply**bot and I guess adding him ability to pull will increase his utility.

2025-04-25 00:55 UTC, slarticodefast requested changes
Will need to be adjusted to
https://github.com/space-wizards/space-station-14/pull/29949

2025-05-07 14:53 UTC, AsnDen commented
> Will need to be adjusted to #29949

I guess done

2025-05-07 21:06 UTC, EmoGarbage404 approved these changes

2025-05-13 17:14 UTC, slarticodefast approved these changes

2025-05-13 17:15 UTC, merged