pAI Software Catalog
space-wizards/space-station-14 pull request #32498
Opened 2024-09-28 05:26 UTC by ArchRBX

## About the PR

Adds a Software Catalog to pAI's that lets them install various helpful software.

pAI's start off with 30 'Silicon Memory' to spend on software.

Based loosely on the software available to pAI's on [tgstation](https://tgstation13.org/wiki/Personal_AI).

## Why / Balance

pAI's at the moment are relegated to being Walkmans that can squawk for help when their owner is being crowbarred in maints. A lot of people don't even bother picking them up, and many more don't bother picking the role. This PR gives the role a lot more utility to both the pAI and its owner.

## Technical details

No major changes. Removes the initial actions for pAI's. Adds a store, currency, and corresponding catalog.

## Media

![firefox_2024-09-28_06-22-16](https://github.com/user-attachments/assets/88c735bb-c5e7-4932-a4d4-31af034983d8)

https://github.com/user-attachments/assets/c517d167-02f3-49ff-9439-ab8af16b0d00

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None.

**Changelog**
:cl:
- add: pAI's can now install a variety of useful software through their new Software Catalog.
- tweak: pAI's no longer start with a Station Map or MIDI Player, and must purchase these through the shop.

2024-09-28 05:27 UTC, metalgearsloth commented
Regardless of whether this gets merged power monitoring can't be included here, it's too expensive.

2024-09-28 07:25 UTC, ArcaneOcto commented
This looks really cool! I hope this gets merged. Some ideas:

Tools: remote signaler, gas analyzer, t-ray, flashlight (multiple colors?)
Comms: most channels are probably an instant "no" from maintainers, but Syndicate pAIs buying Syndi Comms would be cool imo
Accents: Buying speech traits for a small amount of memory would be neat for rp
PDA apps: Station News, Notes, Crew Manifest
HUD: Medical, Job Icons

would be cool to be able to choose from this list and be at least _slightly_ useful to whoever is carrying you.

2024-09-28 10:06 UTC, LittleNorthStar commented
Some syndicate specific ideas for PAI to maybe make some people decide to buy them

Voice Mask application letting the PAI speak using anyone's voice (Could lead to some interesting interactions where the a PAI has to speak on behalf of its owner)

Code Word database/detector application let's the syndicate PAI see same highlighted text as agents when someone says a code word

Hidden Compartment application let's the syndicate PAI have a hidden 2 by 2 storage compartment which it can toggle the accessibility of

Chameleon PDA Projector application let's the syndicate PAI disguise any PDA or PAI (including potato)

Chameleon Master Control Program, let's the syndicate PAI control its owners chameleon clothing (probably the hardest to code but would be really cool)

2024-09-28 10:46 UTC, Fildrance commented
If this is core functionality (list of abilities is going to get wider later) this requires ability to uninstall apps. I think i fixed refund feature and have tests for it - it should work here too!

2024-09-28 10:57 UTC, ilyamikcoder commented
> If this is core functionality (list of abilities is going to get wider later) this requires ability to uninstall apps.

in ss13 it is impossible to uninstall these probably because that would make this a bit pointless - you could've just jiggled around your apps and be able to do _everything_

i feel like it would still be nice to implement with some limitation though! perhaps force you to wait like 10 minutes or something before uninstalling an app, or/and require your owner to do it for you instead of letting you do it yourself

regarding the PR itself though - this is really awesome thank you

2024-09-28 17:10 UTC, ArchRBX commented
> Some syndicate specific ideas for PAI to maybe make some people decide to buy them
> 
> Voice Mask application letting the PAI speak using anyone's voice (Could lead to some interesting interactions where the a PAI has to speak on behalf of its owner)
> 
> Code Word database/detector application let's the syndicate PAI see same highlighted text as agents when someone says a code word
> 
> Hidden Compartment application let's the syndicate PAI have a hidden 2 by 2 storage compartment which it can toggle the accessibility of
> 
> Chameleon PDA Projector application let's the syndicate PAI disguise any PDA or PAI (including potato)
> 
> Chameleon Master Control Program, let's the syndicate PAI control its owners chameleon clothing (probably the hardest to code but would be really cool)

These sound a bit too valuable for just 2 TC...

2024-09-28 18:14 UTC, ArcaneOcto commented
> These sound a bit too valuable for just 2 TC...

Agreed. I think the programs should mostly be limited to things that the player holding the pAI could already do on their own. Like taking notes or looking a map.

2024-09-28 21:07 UTC, Rainbeon commented
> These sound a bit too valuable for just 2 TC...

Of these, 2 would work for the pricepoint I think (last 3 are kinda, ehhh...)

Codeword detection seems relatively harmless (I'm kind of surprised it's not base behavior, given it's a Syndie pAI already)

And voice mask pAI seems good because if you're in person you can tell it's a pAI because it has a unique pAI speech noise, to get real use out of it you'd have to have it use Intercoms, which is neat and kinda funny, fun additional interaction/use for Intercoms

2024-10-20 21:38 UTC, Moomoobeef commented
an idea that came up during a conversation in #general is the idea of having more variants of pAIs, such as a salvage pAI and a command pAI, which could have access to programs that others don't; for instance only salvage pAI has access to mass scanner.

This was proposed as a solution to the theoretical problem of power-gamers rushing pAIs roundstart to get things like mass scanner.

An alternative idea is to instead of pAI variants, have pAIs have cartridge slots and add special cartridges with restricted software.

Up to you if you want to use these ideas or not but I thought I'd share them.

2024-10-29 14:50 UTC, Fildrance commented
I would like to add Hologram to pAI, but on a condition that it will be limited by some decision system - this store PR can fit. 

The idea is - hologram should not be 'funny useless decor feature that every pAI gets'. It should be choice of a pAI player - what you want to be, and you should sacrifice a lot for it - for example pAI should not have enough currency to have Host health analyzer AND hologram APP at the same time. Those choices are what makes the game actually game and not just fancy virtual reality where you can hang out with friends and tell jokes.

2024-10-29 15:24 UTC, ScarKy0 commented
> Those choices are what makes the game actually game and not just fancy virtual reality where you can hang out with friends and tell jokes.

pAI is literally a virtual friend you can talk to and tell jokes with... thats literally what they do

2024-10-29 16:25 UTC, Fildrance commented
As was noted on discord discussion - for pAI to have more features, it should not be usual tech, and i agree - as app store would get more useful stuff we SHOULD remove most pre-mapped pAI and lower spawn chances. It is rare and cool companion, which cannot change round too much but will be your personal HELP and not just talking partner that cannot get drunk.

2024-10-29 16:32 UTC, ScarKy0 commented
...I mean if people disliked pAI it wouldnt be played
you wonna lower something people already enjoy to make it more "professional", but people already seem to enjoy pAI surprisingly much

2024-11-19 19:04 UTC, insoPL commented
I kind of feel it overlaps with https://docs.spacestation14.com/en/space-station-14/player-interaction/cartridge-loaders.html
Cartridge programs system. I think it would make more sense to give pai ability to use those. This will also make some programs dept locked by default. Plus maybe a slot for HUD so you can put any HUD on your pai.

2025-01-20 09:57 UTC, MilonPL commented on Content.Shared/PAI/SharedPAISystem.cs
> +    [Dependency] private readonly SharedActionsSystem _actionsSystem = default!;
Just `_actions`.

2025-01-20 09:57 UTC, MilonPL commented on Content.Shared/PAI/SharedPAISystem.cs
> +    private void OnMapInit(EntityUid uid, PAIComponent component, MapInitEvent args)
All of these should use `Entity<T> ent, ref event args`

2025-01-21 20:54 UTC, keronshb requested changes
There should be comments in the catalog saying that some things are excluded either for balance or for performance. And anything that's to be added shouldn't have anything that's round-impacting.

Basically a comment to reinforce that monitoring (Power/Atmos/Crew), Cameras, etc aren't going to be added.

2025-02-20 23:44 UTC, beck-thompson commented
just putting this here so I dont forget! FSP had a good idea for an app: geiger counters! (dont do it in this pr again I'm just putting this here so I remember!)

2025-04-22 23:13 UTC, MilonPL commented
I am going to be closing this PR as Stale. If you ever end up coming back to this, please open a new PR.

2025-04-22 23:13 UTC, closed without merging