Alphabetical sort of chem dispenser
space-wizards/space-station-14 pull request #3253
Opened 2021-02-16 13:53 UTC by Peptide90

closes #3000

Did a sort on reagent dispenser to close out an issue. Should have been resolved by a previous PR.

2021-02-16 13:55 UTC, metalgearsloth commented
TBH the UI should maybe auto-sort in case we ever get the chem names back

2021-02-16 14:15 UTC, Peptide90 commented
> 
> 
> TBH the UI should maybe auto-sort in case we ever get the chem names back

Yeah I couldn't find a way to do a sort within a YAML file so just thought I'd check through them. This commit should cover all the dispensers that have anything over like 2 items in.

Future PR's for dispensables should just be in alphabetical order anyway for good practice.

2021-02-17 10:14 UTC, metalgearsloth commented
I just did it https://github.com/space-wizards/space-station-14/pull/3253

2021-02-17 10:20 UTC, metalgearsloth commented
Also the reason is that if someone wants to just slap translated names onto it and still have the same reaction code they don't need to mess with the yaml.

2021-02-17 10:22 UTC, metalgearsloth requested changes

2021-02-17 10:22 UTC, metalgearsloth commented on Resources/Prototypes/Catalog/VendingMachines/seeds.yml
> +  startingInventory: #maintain in alphabetical order
Seems silly to leave the comment on only the one so I'd just delete it.

2021-02-17 12:38 UTC, Peptide90 commented
closing in favour of #3275 due to my github repo mess.

2021-02-17 12:38 UTC, closed without merging