Add HSeparator SeparatorColor property
space-wizards/space-station-14 pull request #32548
Opened 2024-09-30 16:25 UTC by GreaseMonk

## About the PR

Added the optional `SeparatorColor` for the `HSeparator` UI element that accepts a hex color code

## Why / Balance

Now you can set a color for your separators.

## Technical details

A typical usage example would be:
`<cc:HSeparator SeparatorColor="#A3875A"/>`

## Media

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added ability to set the color of a UI separator element

2024-11-30 20:20 UTC, VlaDOS1408 commented
🤮
One more step closer to the shitcode

Now imagine the faces of people who change the standard UI style in their build. I'm already against dirty-skinned colors, and you're still adjusting the possibilities.

2024-11-30 22:07 UTC, PJB3005 requested changes
This needs to be a style property

2024-12-02 23:56 UTC, GreaseMonk commented
> 🤮 One more step closer to the shitcode
> 
> Now imagine the faces of people who change the standard UI style in their build. I'm already against dirty-skinned colors, and you're still adjusting the possibilities.

I know you think you are helping , but you're not. I'd like some constructive criticism like PJB gave, preferably.

2024-12-03 00:09 UTC, GreaseMonk commented
> This needs to be a style property

Sorry, I didn't know any better, updating it soonish!

2024-12-03 08:35 UTC, VlaDOS1408 commented
> > 🤮 One more step closer to the shitcode
> > 
> > Now imagine the faces of people who change the standard UI style in their build. I'm already against dirty-skinned colors, and you're still adjusting the possibilities.
> 
> I know you think you are helping , but you're not. I'd like some constructive criticism like PJB (somewhat) gave, preferably.

Well, PJB said everything, all colors should be done through styles, you can't hardcode colors.

2024-12-03 09:21 UTC, GreaseMonk commented
@VlaDOS1408 Is this correct how it's coded right now? 

Currently it compiles all fine, im not getting it to compile when i use this:
```<customControls:HSeparator Color="#A3875A"/>```

Is the word Color a reserved namespace perhaps ? there is something i'm not doing correctly..

2025-09-03 20:08 UTC, juliangiebel approved these changes

2025-09-03 21:30 UTC, PJB3005 requested changes
This should take a `StyleBox` instead.

2025-09-04 18:35 UTC, sowelipililimute requested changes
can you elaborate more on your usecase? we prefer to have this stuff be based off of styles & stylesheets, rather than per-control hardcoded colours overrides. if you're wanting this to be used for e.g. alternate subtler or stronger variants this is the wrong way to be going about that

2025-09-06 09:15 UTC, GreaseMonk commented
I just wanted to change the color of the separator - if i can wrap it in a style block to change the color, i would love to know how this is done if you have a code reference i would appreiciate it.

In this case, we can close the PR

2026-07-29 06:26 UTC, AJCM-git commented
Contrib seems inactive

2026-07-29 06:26 UTC, closed without merging