Substation Maintenance (take 3)
space-wizards/space-station-14 pull request #32550
Opened 2024-09-30 18:05 UTC by AwareFoxy

## About the PR
Based on  [Peptide90](https://github.com/Peptide90) pull request (https://github.com/space-wizards/space-station-14/pull/25191)
## Why / Balance
You can see 2 previous PR's to details.

## Technical details
I want to do what Peptide90 wanted to do in the last PR, more precisely:

- [ ]  Change the substation screen icons to be more accessibility friendly. They should be legible charts or distinct icon changes, not just colours. The red one also needs rotated.
- [ ]  Decrease decay rate.
- [ ]  Fix whatever is causing the verb to show up for ejecting the nitrogen booster even when the maintenance door is shut.
- [ ]  Figure out why they and don't seem to decay their integrity.
- [ ]  Make sure there's a non decaying version of the substation for mappers. Change it's sprite to be obviously different e.g. yellow plating to symbolise engineering.

## Media
coming soon :3

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-09-30 21:00 UTC, AwareFoxy commented
going to work on this tommorow, sleep time now 🛏️

2024-10-01 12:09 UTC, AwareFoxy reviewed
uh

2024-10-14 17:29 UTC, AwareFoxy commented
Ok I think its ready for review now(not for merge obviously)

2024-10-14 19:08 UTC, 0x6273 requested changes

2024-10-14 19:08 UTC, 0x6273 commented on Content.Shared/Power/SubstationComponent.cs
> +    public float SubstationLightBlinkInterval = 1f;
This should be a `TimeSpan`, and either a datafield or a constant.

2024-10-14 19:08 UTC, 0x6273 commented on Content.Shared/Power/SubstationComponent.cs
> +    public float SubstationLightBlinkTimer = 1f;
As mentioned earlier, replace this with a `TimeSpan` that represents the next game time that the light should blink.

2024-10-14 19:08 UTC, 0x6273 commented on Content.Server/Power/EntitySystems/SubstationSystem.cs
> +            return;
Combine ifs when possible, when the conditional code is the same.

2024-10-14 19:37 UTC, 0x6273 commented on Resources/Textures/Structures/Power/substation.rsi/meta.json
> +    "copyright": "Created by EmoGarbage404 (github), screen sprites created by joshepvodka (github) and updated by AwareFoxy(github)",
Have you asked joshepvodka if they were the one that created the screen sprites, and that they are okay with relicensing to CC0? (In their PR they are licensed as CC-BY-SA)

2024-10-15 19:39 UTC, Krovotushka commented
Based PR, merge now🦖

2025-04-18 15:14 UTC, slarticodefast commented
Are you coming back to this?

2025-04-21 14:06 UTC, AwareFoxy commented
> Are you coming back to this?

Nah, left from SS14 coding community


If anyone wanna take it - you're welcome

2025-04-21 14:06 UTC, AwareFoxy commented
> Are you coming back to this?

Nah, left from SS14 coding community


If anyone wanna take it - you're welcome

2025-04-21 14:46 UTC, closed without merging