Give AI a Sound Cue when an Antimov board is inserted
space-wizards/space-station-14 pull request #32625
Opened 2024-10-03 20:54 UTC by poklj

## About the PR

Added the ability to give a lawboard an Upload sound that gets played for the AI player

## Why / Balance

At the moment Subverted AI are only given a Notification via the Chat that their laws have been changed, Something that can be easily missed during highly active comms and might not immediately cause a player to check their laws.

Causing a very recognizable "You are now evil" sound makes it far more likely a player does not miss that their core directive has changed.

## Technical details

Added a SoundSpecifier DataField to SiliconLawProviderComponent 

Added a check OnUpdaterInsert to check the SiliconLawUpdaterComponent for a defined Sound (in this case it'll just be Antimov) and play it to the associated player

Added a sound to Antimov's law board

## Media

https://github.com/user-attachments/assets/574854b8-2ced-4162-bc93-f70f90febd4a

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

## TODO
- [ ] find/make a more appropriate Antimov sound cue 

**Changelog**

:cl: Kickguy223
- add: As an AI, Having an Antimov Lawboard inserted into your AI Upload Computer will now Play a sound cue

2024-10-03 20:58 UTC, muburu commented
a little sound for when your laws are changed in general (regardless of evilness) would be much more useful than a sound specifically playing for when you're going into evil mode

2024-10-03 21:12 UTC, poklj commented
> a little sound for when your laws are changed in general (regardless of evilness) would be much more useful than a sound specifically playing for when you're going into evil mode

If one was available, it could be placed as the default for the LawUploadSound (this was pointed out to me on discord, and i shifted to make the Noise playing not based on how "subversive" the lawset actually is). 
It will play a sound so long as there's a Sound associated to the inserted board at the moment, and the default is left empty, but mostly out of a lack of sound rather than a choice to leave it silent.

2024-10-03 21:19 UTC, ArtisticRoomba commented
A squirrel sound for when Nutimov is inserted lmao

I think that you should just have the sound from SS13 when AI's laws are changed, remember that this needs to work for Freeform laws.

2024-10-03 21:28 UTC, ScarKy0 commented
This should affect anything that has silicon laws and any time the laws are changed(updated, ion storms, etc)

2024-10-03 21:56 UTC, Everturning commented
Make it the malf ai sound from 13

2024-10-03 23:07 UTC, slarticodefast requested changes
I agree with the others that there should be a sound effect for every law change. Maybe someone can find a cool one from SS13. The emag law change sound does not really fit here since no emag is used and the "death to NT" has nothing to do with antimov

2024-10-03 23:07 UTC, slarticodefast commented on Content.Shared/Silicons/Laws/Components/SiliconLawProviderComponent.cs
> +    [DataField, ViewVariables(VVAccess.ReadWrite)]
```suggestion
    [DataField]
```
DataField already includes ReadWrite access nowadays. Old files still do this manually though.

2024-10-03 23:07 UTC, slarticodefast commented on Content.Server/Silicons/Laws/SiliconLawSystem.cs
> +            }
```suggestion
            if (provider.LawUploadSound != null && _mind.TryGetMind(update, out var mindId, out _) )
                _roles.MindPlaySound(mindId, provider.LawUploadSound);
```
you can combine the two if conditions

2024-10-03 23:17 UTC, Doru991 commented
> Make it the malf ai sound from 13

I'd prefer if the Malf sound was reserved for malf

2024-10-03 23:41 UTC, Stewie523 commented
I'm all for this but it doesn't fit with the law change. It doesn't use an emag (atleast directly) it should have its own unique sound.

2024-10-04 01:30 UTC, IProduceWidgets commented
You can find sounds on Freesound.org you just may want to clip them, and convert to .ogg. Make sure to attribute them. Maybe this one that sounds like the public broadcast alarm sound? idk. 
https://freesound.org/people/BoulderDamStudios/sounds/181326/

2024-10-04 02:37 UTC, poklj commented
https://github.com/user-attachments/assets/46d0263d-2e96-4375-9903-e3e7258aaae3

Grabbed the noise TG uses for Law uploads as well as Did some cutting around the problem emag bits.
@ps3moira has mentioned that they might try to make a more antimov themed subversion cue, but i'd rather not pressure someone into doing something out of nowhere so hopefully this suffices for the "you're evil now" side of the coin

2024-10-04 03:01 UTC, ps3moira commented
> Generic-and-relevant.mp4 
> Grabbed the noise TG uses for Law uploads as well as Did some cutting around the problem emag bits. @ps3moira has mentioned that they might try to make a more antimov themed subversion cue, but i'd rather not pressure someone into doing something out of nowhere so hopefully this suffices for the "you're evil now" side of the coin

Yeah I can make something just gimme some time and put this in draft. Once it's done I'll send it

2024-10-04 03:08 UTC, poklj commented
> > Generic-and-relevant.mp4
> > Grabbed the noise TG uses for Law uploads as well as Did some cutting around the problem emag bits. @ps3moira has mentioned that they might try to make a more antimov themed subversion cue, but i'd rather not pressure someone into doing something out of nowhere so hopefully this suffices for the "you're evil now" side of the coin
> 
> Yeah I can make something just gimme some time and put this in draft. Once it's done I'll send it

Solid, I was unsure if this PR should be a draft or not, I'll remove the bad placeholder once you're done

2024-10-06 17:50 UTC, TytosB commented
this is a good change but as others said it doesnt go far enough, there needs to be some obvious unmissable indicator when every any borg or ais laws are changed at all rather it be from emag, law boards, or ion storms. the single line of text is not enough in any case.

2024-10-08 19:51 UTC, poklj commented
https://github.com/user-attachments/assets/17ebd49a-f5a1-4aaa-8af6-658410b4673b

Bespoke antimov sound (Thank you @ps3moira)

2024-10-08 21:01 UTC, poklj commented
Re-ran the Integration tests locally and asked about it in \#development, May need a re-run due to integration test failure being stochastic with this one, local integration tests ran fine

2024-10-08 23:00 UTC, slarticodefast approved these changes
Tested everything in-game and it works as intended.
The new sound effect is amazing.
It would probably be a good idea to have `cryo_warning.ogg` also play when a borg gets ion stormed, but that can be done in a separate PR.
Thank you for your first contribution :)

2024-10-17 03:41 UTC, chromiumboy commented
Thank you for your contribution @poklj and @ps3moira! The new sounds are great, and it's just overall a good QOL change. Tested in-game just fine

2024-10-17 03:41 UTC, merged