Rerotate aspid
space-wizards/space-station-14 pull request #32727
Opened 2024-10-10 00:57 UTC by Golinth

## About the PR

## Why / Balance

## Technical details

## Media

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-10-10 04:13 UTC, thebadman4662 commented
Does cargo have bounty console now?

2024-10-10 04:22 UTC, Golinth commented
> Does cargo have bounty console now?

Yes. I think it was added prior to me updating the map though, as I didn't place it.

2024-10-10 04:42 UTC, Djungelskog2 commented
shouldnt science have two artifact chambers?

2024-10-10 08:31 UTC, tutoumi commented
give arti chamber plasma windows since its exposed to the hallway

2024-10-10 08:47 UTC, lzk228 commented
![Aspid-0](https://github.com/user-attachments/assets/ac4eaa99-f3de-4d4b-a8f7-b8dbb25b139c)

- please no cryosleep in medbay, at least one issue with it - it's hard to steal thing from cryoed person
- weird decals in arti room
![image](https://github.com/user-attachments/assets/76f4c2b5-b311-4c47-8fbb-f723041bab31)
- cargo breakroom is gone😭😭
- afaik lattice right at dock can't be cutted 
![image](https://github.com/user-attachments/assets/d2d7f9ff-4287-46af-a34e-4a0dcf002ea8)
> Removed round-start cryo spawn.

why?

2024-10-10 11:24 UTC, Kadeo64 commented
oh no

2024-10-10 14:11 UTC, Everturning commented
Will there be 4 salv slots for the 4 lockers?

2024-10-10 14:30 UTC, Golinth commented
> Will there be 4 salv slots for the 4 lockers?

There are 3 slots round start and a fourth can join mid-round

2024-10-10 14:30 UTC, lzk228 commented
please not 4 salv, i played on server where on aspid was 4 roundstart salvagers and it was terrible, even when they could split to expeditions, magnet and wrecks/asteroids
and now when it's only magnet and wrecks/asteroids it will be even more terrible

2024-10-10 14:33 UTC, Golinth commented
> please no cryosleep in medbay

Most other maps have cryo in med, I assumed it was standard?

> weird decals

huh, they were fine in the editor. I’ll remake em.

> cargo break room

I know! But it originally never existed, and I needed somewhere to put salv (it’s in a more logical spot now than the original imo)

> lattice uncuttable

I’ll remove it

2024-10-10 14:41 UTC, Golinth commented
> please not 4 salv, i played on server where on aspid was 4 roundstart salvagers and it was terrible, even when they could split to expeditions, magnet and wrecks/asteroids
> and now when it's only magnet and wrecks/asteroids it will be even more terrible
> maybe would be better to remove one late-join salv

It’s not 4 roundstart, just 3, and I gave a fourth locker as it was alway an issue for the fourth latejoin salvage to have to either steal the QM’s suit, take an EVA suit, or just work as a cargo tech. IMO 4 salv is fine, but if other people share your opinion I’ll reduce it to 3

2024-10-10 14:46 UTC, lzk228 commented
> I assumed it was standard?

better to ask emisse

2024-10-10 16:17 UTC, EthanQix commented
> Most other maps have cryo in med, I assumed it was standard?

Honestly there's no reason for cryobeds to be in med since they're not used for anything medical-related, AND it means that anyone choosing a cryo spawn is stuck in there until a medic lets them out. Cryobed should be in dorms.

> please no 4 salv

what's the matter with 4 salvagers ?

2024-10-10 16:20 UTC, Golinth commented
> AND it means that anyone choosing a cryo spawn is stuck in there until a medic lets them out.

they are not the late join spawn variants of cryosleep. Everyone all late joins will spawn in dorms. These are just for med to throw SSD people they revive into, instead of either leaving them out front, or taking the time to slowly drag them to dorms

2024-10-10 16:34 UTC, EthanQix commented
> > AND it means that anyone choosing a cryo spawn is stuck in there until a medic lets them out.
> 
> they are not the late join spawn variants of cryosleep. Everyone with cryo late joins will spawn in dorms. These are just for med to throw SSD people they revive into, instead of either leaving them out front, or taking the time to slowly drag them to dorms.
> 
> I’ll ask Emisse and see what she wants me to do with them.

oh, I didn't notice the cryobeds in dorms, my bad.

Speaking of dorms, if you could squeeze a bathroom in there, that would be swell - or at least delete the washroom sign that leads to nowhere ^^

2024-10-10 16:37 UTC, Golinth commented
> oh, I didn't notice the cryobeds in dorms, my bad.
> 
> Speaking of dorms, if you could squeeze a bathroom in there, that would be swell - or at least delete the washroom sign that leads to nowhere ^^

I think I’m going to try to rework that entire area. I’m not very happy with it. Cryo feels too closed in, the dorm rooms aren’t standard, and there is no bathroom.

2024-10-10 17:00 UTC, lzk228 commented
> Can you explain in further detail the problems of 4 salvagers over 3

most of the time some of salvagers took over the work of others and others did not like it, this led to frequent quarrels and insults

2024-10-10 22:45 UTC, thebadman4662 commented
> Honestly there's no reason for cryobeds to be in med since they're not used for anything medical-related, AND it means that anyone choosing a cryo spawn is stuck in there until a medic lets them out. Cryobed should be in dorms.

They are used to store catatonic/long ssd players without gibbing them or stockpiling whole load of them while people get blocked from taking their roles otherwise.

2024-10-11 05:44 UTC, Golinth commented
> Speaking of dorms, if you could squeeze a bathroom in there, that would be swell - or at least delete the washroom sign that leads to nowhere ^^

How is this? 
![image](https://github.com/user-attachments/assets/cd68a090-ec1d-49ab-963d-bac8529cf90a)

2024-10-11 06:20 UTC, Golinth commented
> weird decals in arti room

So I remade them in the same style, and they still look odd in the renderer. In-game they look completely fine.

2024-11-21 09:13 UTC, ScarKy0 requested changes
Personally I don't think intellicards should be mapped.
They already appear in RD locker and letting any walking by nukie to card the AI is probably bad.

2024-12-27 11:06 UTC, Pumkin69 commented
Also need to go through and remove any gamer loot like the cultist dagger for example. Ask emisse about this as she can specify what should and shouldn't be removed.

2025-01-04 21:26 UTC, ArtisticRoomba requested changes
This map's power needs to be balanced, as discussed in the review thread.

Generally, your main station SMES bank need to be at:
- 40-30% at 5 minutes, with no AME assistance. At 5 minutes, the AME is turned on.
- 20% or above at 10 minutes with AME assistance. At this time, all solars are assumed to be aligned.
- Around 15% at 20 minutes with solars and AME assistance. This is when the station's main engine is assumed to be started.

You can increase the battery runtime before the AME by adding more SMESes. We have advanced SMESes now, so that can help if you don't have enough space.

For increasing runtime after the AME is started, add more AME cores.
For increasing runtime after the solars are aligned, add more solars, although this wasn't necessary on all maps I balanced. You might need to make changes though.

2025-04-18 16:44 UTC, slarticodefast commented
Are you coming back to this?

2025-04-23 14:59 UTC, ArtisticRoomba commented
@Golinth please address the changes I requested and I'll be happy to do a proper review pass of Aspid.

2025-05-30 13:49 UTC, spanky-spanky commented
Closing this as derelict as discussed on Discord. @Golinth I’ll see that your contributions are credited if/when this is revived by someone else, which is also in the works.

2025-05-30 13:49 UTC, closed without merging