Cardboard Box Capacity 4 -> 5
space-wizards/space-station-14 pull request #32743
Opened 2024-10-11 03:44 UTC by Scribbles0

## About the PR

Cardboard boxes can now fit 5 entities instead of 4.

## Why / Balance

This is mainly intended for stealth boxes, which are rarely seen in Nukeops. This change will allow an entire team of nukeops to fit inside of a stealth box, instead of having to leave one member out.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

- tweak: Cardboard boxes can now fit 5 entities instead of 4.

2024-10-11 03:48 UTC, JIPDawg commented
I agree with this, but right now the boxes are easily exploitable unfortunately and I feel like it should be fixed first. #29886

2024-10-11 07:15 UTC, Plykiya commented
> I agree with this, but right now the boxes are easily exploitable unfortunately and I feel like it should be fixed first. #29886

basically just means implementing vehicle code

2024-10-28 00:25 UTC, slarticodefast commented
> I agree with this, but right now the boxes are easily exploitable unfortunately and I feel like it should be fixed first. https://github.com/space-wizards/space-station-14/issues/29886

Yeah, I've even seen parameds use them to transport injured people because it's faster than pulling a roller bed.
Not easy to do, but we need proper vehicle code.

2024-11-02 15:39 UTC, SlamBamActionman requested changes
The PR is conceptually sound and while there are issues with the cardboard movement, I doubt adding an additional slot will cause any meaningful uptick in that specific issue. Just fix the comment and I can approve it.

2024-11-02 15:39 UTC, SlamBamActionman commented on Resources/Prototypes/Entities/Structures/Storage/Closets/big_boxes.yml
> +      capacity: 5 #4 Entities seems like a nice comfy fit for a cardboard box.
Update the comment to describe why it's set to 5.

2024-11-02 16:14 UTC, slarticodefast commented
I guess it's fine. Thanks for the PR.

2024-11-02 16:14 UTC, slarticodefast approved these changes

2024-11-02 16:21 UTC, SlamBamActionman approved these changes

2024-11-02 16:21 UTC, merged