Add Diona rooting
space-wizards/space-station-14 pull request #32782
Opened 2024-10-13 14:08 UTC by SlamBamActionman

## About the PR

This PR adds a new species-unique feature to the Diona that allows them to get a built-in toggleable "magboots", at the cost of absorbing liquids on the ground and a slowdown. This feature is called "Rooting", simulating the diona steadying themselves using their root-like leg appendages.

## Why / Balance

The Diona have long been seen as a sub-optimal species due to their main downside: not being able to wear shoes. This downside is interesting but due to how many mechanics of the game are centered around shoes it has made the Diona adifficult species to justify for certain jobs and scenarios. Among these include Janitorial, Salvage and Nukies, as these are roles that rely on footwear-specific items. 

Giving Diona built-in magboots have been suggested before in #24596, however this was an always-on feature and it was suggested the Diona would have a slower base speed as result. 

Instead this PR implements this as a toggle in the form of the "Rooting" action and status effect. While rooted, Diona move at 80% speed (same as magboots) and have a similar effect of preventing slipping and floating in no-grav. The one exception is slipping caused by injuring items on the ground, such as glass shards and D4s. This is due to the rooting not being equivalent to wearing shoes, and to prevent a diona walking over a stack of multiple glass shards and immediately dying from burst damage.

While rooted, the affected entity will also attempt to transfer reagents from puddles to the entity's chemstream. This happens at a rate of 0.75u per second. In effect, this means that a diona can passively "drink" from puddles. This is largely meant as a downside; while some chemicals on the floor may be neutral or even helpful, being rooted over e.g. welding fuel would make the diona take damage over time.

## Technical details

Most of the absorption code in `RootableSystem` is set up in a similar way to how `SmokeSystem` handles it, though centered from the rootable entity. The no-slip and no-grav code is fairly boilerplate event handling.

`SlipAttemptEvent` has been given an optional entity property that includes the entity causing the slip (used to determine if it has `DamageUserOnTriggerComponent`). 

## Media

https://github.com/user-attachments/assets/65a1ea7d-1e75-4a79-bc15-92c31cbda4c6

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Diona can now root, keeping them from slipping but absorbing fluids from the ground.

2024-10-13 14:31 UTC, Boaz1111 commented
hoili moili

2024-10-13 14:41 UTC, BramvanZijp commented
I feel like there should be a do-after bar for toggling this on or off to make it so you CAN be punished for rooting and then walking on harmfull liquids (or having a poison container thrown at you by an antag who sees you are rooted) Also there should be some indicator like a sprite change or smth if thats doable

2024-10-13 21:09 UTC, DieselMohawk commented
> I feel like there should be a do-after bar for toggling this on or off to make it so you CAN be punished for rooting and then walking on harmfull liquids (or having a poison container thrown at you by an antag who sees you are rooted) Also there should be some indicator like a sprite change or smth if thats doable

Could be an audio indicator, could change from the smack of shoeless feet to a sort of heavy thump.

2024-10-13 22:28 UTC, FungiFellow commented
On my way to make a space lube and poison mix to screw over Diona.

2024-10-15 08:29 UTC, TheShuEd submitted a review, later dismissed

2024-10-15 08:29 UTC, TheShuEd commented on Content.Server/Rootable/RootableSystem.cs
> +            rooted.NextSecond += TimeSpan.FromSeconds(1);
hardcoded number! Move to RootableComponent, as "SuctionFrequency" or something

2024-10-15 08:29 UTC, TheShuEd commented on Content.Server/Rootable/RootableSystem.cs
> +    [Dependency] private readonly SharedSolutionContainerSystem _solutionContainerSystem = default!;
```suggestion
    [Dependency] private readonly SharedSolutionContainerSystem _solutionContainer = default!;
```

2024-10-15 08:29 UTC, TheShuEd commented on Content.Server/Rootable/RootableSystem.cs
> +        if (!TryComp<BloodstreamComponent>(entity, out var bloodstream))
TryComp every second. it's better to do a _bloodstreamQuery, or move to arguments

2024-10-15 08:29 UTC, TheShuEd commented on Content.Server/Rootable/RootableSystem.cs
> +        foreach (var reagentQuantity in transferSolution.Contents.ToArray())
I'm not sure, but can't the whole solution be put into the entity at once, rather than doing it in a loop for each reagent?

2024-10-15 08:29 UTC, TheShuEd commented on Content.Shared/Rootable/SharedRootableSystem.cs
> +    [Dependency] private readonly SharedAudioSystem _audioSystem = default!;
```suggestion
    [Dependency] private readonly SharedAudioSystem _audio = default!;
```

2024-10-22 21:34 UTC, HyperB1 commented
I'd really increase the slowdown (because how else is it "rooting" then?) and decrease the absorption rate to 0.5 a second for balance purposes.

2024-12-27 10:49 UTC, Pumkin69 commented
I would love to see this because slipping as a diona constantly is hell tbh.

2025-03-04 12:08 UTC, slarticodefast requested changes
You need to initialize NextSecond on map init or if a diona spawns on a puddle they will get an update every tick until the time has caught up with the server time. See the slarti guide for an example.

2025-03-04 12:08 UTC, slarticodefast commented on Content.Shared/Rootable/RootableComponent.cs
> +    public TimeSpan NextSecond;
rename to NextUpdate

2025-03-04 12:08 UTC, slarticodefast commented on Content.Shared/Rootable/SharedRootableSystem.cs
> +            entity.Comp.NextSecond = _timing.CurTime + TimeSpan.FromSeconds(1);
dehardcode the timespan

2025-03-04 17:10 UTC, SlamBamActionman commented on Content.Server/Rootable/RootableSystem.cs
> +        foreach (var reagentQuantity in transferSolution.Contents.ToArray())
Turns out there's a ReactiveSystem function takes the whole solution... but then it just loops over the reagents anyways. I've changed over to that function though since it makes the code look cleaner.

2025-03-04 18:07 UTC, ScarKy0 requested changes
Tiny thing

2025-03-04 18:25 UTC, ScarKy0 approved these changes
Tested and works all fine!

2025-03-04 20:19 UTC, slarticodefast requested changes
NextUpdate will need to be intialized on MapInit or a diona spawning will get updates every single tick until it has caught up to server time.

2025-03-09 11:15 UTC, DieselMohawk approved these changes
Good stuff

2025-04-10 11:16 UTC, slarticodefast requested changes

2025-04-10 11:16 UTC, slarticodefast commented on Content.Server/Rootable/RootableSystem.cs
> +            rooted.NextUpdate += TimeSpan.FromSeconds(rooted.TransferFrequency);
just directly make the datafield a timespan instead of converting it

2025-04-10 11:16 UTC, slarticodefast commented on Content.Server/Rootable/RootableSystem.cs
> +    private void PuddleReact(EntityUid entity, EntityUid puddleUid, RootableComponent? rootableComponent = null, PuddleComponent? puddleComponent = null, BloodstreamComponent? bloodstreamComponent =
use `Entity<Component>` pattern

2025-04-10 11:16 UTC, slarticodefast commented on Content.Server/Rootable/RootableSystem.cs
> +    private void ReactWithEntity(EntityUid entity, EntityUid puddleUid, Solution solution, RootableComponent? rootableComponent = null, PuddleComponent? puddleComponent = null, BloodstreamComponent?
same

2025-04-10 11:16 UTC, slarticodefast commented on Content.Shared/Rootable/RootableComponent.cs
> +    public EntProtoId Action = "ActionToggleRootable";
add documentation
same below

2025-04-10 11:16 UTC, slarticodefast commented on Content.Shared/Rootable/RootableComponent.cs
> +    /// The max rate at which chemicals are transferred from the puddle to the rooted entity.
is it in units per second? Or the total amount for each transfer step?
maybe mention that

2025-04-10 11:16 UTC, slarticodefast commented on Content.Shared/Rootable/SharedRootableSystem.cs
> +    public bool TryToggleRooting(EntityUid uid, RootableComponent? rooted = null)
`Entity<Component>`

2025-04-10 11:16 UTC, slarticodefast commented on Content.Shared/Rootable/SharedRootableSystem.cs
> +        if (!TryComp<PhysicsComponent>(entity, out var body))
maybe use a query here as well because this will be a lot of trycomps

2025-04-10 11:16 UTC, slarticodefast commented on Content.Shared/Rootable/SharedRootableSystem.cs
> +        if (!_entityManager.HasComponent<PuddleComponent>(args.OtherEntity))
use the existing query

2025-04-10 14:26 UTC, slarticodefast requested changes
I don't have time to test this in-game before the staging cutoff.
Maybe someone else can. Do you think we need a maint discussion thread for this for conceptual approval since it is a rather big combat balance change? Personally I like it though

2025-04-10 14:26 UTC, slarticodefast commented on Content.Shared/Rootable/RootableComponent.cs
> +    /// The max rate (in reagent units per TransferFrequency) at which chemicals are transferred from the puddle to the rooted entity.
total nitpick, but this hurts
a frequency has the unit of 1/s
so u per frequency would have the physical unit of u*s
maybe make it "reagent units per transfer"

2025-04-10 14:26 UTC, slarticodefast commented on Content.Shared/Rootable/SharedRootableSystem.cs
> +    public bool TryToggleRooting(Entity<RootableComponent> entity)
keep the resolve here, since it is a public api
that way you can call it either with only the uid or with the tuple
use an `Entity<RootableComponent?> for that`

2025-04-14 10:14 UTC, SlamBamActionman commented
> I don't have time to test this in-game before the staging cutoff. Maybe someone else can. Do you think we need a maint discussion thread for this for conceptual approval since it is a rather big combat balance change? Personally I like it though

Review addressed; I don't think a maintainer discussion is necessary since there hasn't been any pushback when raised internally.

2025-04-16 15:19 UTC, slarticodefast submitted a review, later dismissed

2025-04-16 15:19 UTC, slarticodefast commented on Content.Shared/Rootable/RootableComponent.cs
> +    [DataField]
```suggestion
    [DataField, AutoNetworkedField]
```
I think this one has to be networked as well

2025-04-16 15:19 UTC, slarticodefast commented on Content.Shared/Rootable/RootableComponent.cs
> +    [DataField]
```suggestion
    [DataField, AutoNetworkedField]
```

2025-04-16 15:19 UTC, slarticodefast commented on Content.Shared/Rootable/RootableComponent.cs
> +    [DataField(customTypeSerializer: typeof(TimeOffsetSerializer))]
```suggestion
    [DataField(customTypeSerializer: typeof(TimeOffsetSerializer)), AutoNetworkedField]
```

2025-04-16 15:19 UTC, slarticodefast commented on Content.Shared/Rootable/RootableComponent.cs
> +    public SoundSpecifier RootSound = new SoundPathSpecifier("/Audio/Voice/Diona/diona_salute.ogg");
```suggestion
    [DataField]
    public SoundSpecifier RootSound = new SoundPathSpecifier("/Audio/Voice/Diona/diona_salute.ogg");
```

2025-04-16 15:19 UTC, slarticodefast commented on Content.Server/Rootable/RootableSystem.cs
> +            if (!rooted.Rooted || rooted.PuddleEntity == null || curTime < rooted.NextUpdate || !PuddleQuery.TryComp(rooted.PuddleEntity, out var puddleComp))
I think you need to update the `NextUpdate` time even if rooted is disabled.
If you reset it every time you toggle it then you could repeatedly toggle it to either instantly absorb a large amount of reagents, or to avoid doing so (depending on if there is a delay to the first absorbtion or not).
Also the funny kudzu bug in the case where you activate rooting while standing on a puddle. The loop would update every tick until it catches up.

2025-04-16 15:19 UTC, slarticodefast commented on Content.Shared/Rootable/SharedRootableSystem.cs
> +        if (entity.Comp.NextUpdate < _timing.CurTime) // To prevent constantly moving to new puddles resetting the timer
isn't this condition always true and thus exactly doing what the comment says it should prevent?

2025-04-17 11:59 UTC, SlamBamActionman commented on Content.Server/Rootable/RootableSystem.cs
> +            if (!rooted.Rooted || rooted.PuddleEntity == null || curTime < rooted.NextUpdate || !PuddleQuery.TryComp(rooted.PuddleEntity, out var puddleComp))
It's correct that the code had an issue, though not this part specifically. If you stood in the same puddle and toggled rooting off, you'd do a large transfer whenever you turned it on again.

It's necessary to do `+=` to account for lag e.g. when the time between ticks is longer than 2+ `TransferFrequency`. So to solve the bug (while avoiding needlessly updating `NextUpdate` when unrooted), I am instead setting the `NextUpdate` to `CurTime` whenever it is toggled on *if* the `NextUpdate` is behind `CurTime`. 

This ensures that the transfer doesn't do any "catch-up" to absorb large amounts, but ensures you can't repeatedly toggle to prevent transfer. 

The action has a 1 second delay but I tested without just to be sure.

2025-04-17 12:17 UTC, SlamBamActionman commented on Content.Shared/Rootable/SharedRootableSystem.cs
> +        if (entity.Comp.NextUpdate < _timing.CurTime) // To prevent constantly moving to new puddles resetting the timer
This condition isn't true if you exit and enter a new puddle entity (puddle entities are per tile, so this is a common occurence) between updates. It will be true if you leave a puddle, stand outside for a bit, and then enter one again. `NextUpdate` must be updated here or else you get false "catch-up".

2025-05-11 23:19 UTC, walksanatora commented
is this another PR in limbo. please this would make diona even more interesting (I am going to flood the station with mutagen to coutner nukie dionas >:) )

2025-05-26 06:08 UTC, DieselMohawk approved these changes

2025-05-28 20:18 UTC, superjj18 commented
Can we also make them immune to slipping due to stepping on glass?

They are a freakin tree they should break the glass, the glass shouldn't break them

2025-05-29 02:41 UTC, Whatahooda commented
I would love this PR so much. [Cu1r](https://github.com/space-wizards/space-station-14/pull/32782#issuecomment-2449829461) already made a pretty good argument for why this would be a nice change. Why do Diona not wear shoes? I always imagined it was because their feet are too crazy. With this they have a reason for being crazy. Also I really want to drink liquids through my feet. That just sounds awesome.

2025-05-30 02:55 UTC, superjj18 commented
> Please don't make diona boring.

Implying that arbitrarily and unavoidably tripping on glass is what makes Diona exciting

2025-06-04 10:32 UTC, ScarKy0 commented on Content.Client/Rootable/RootableSystem.cs
> +}
```suggestion
public sealed class RootableSystem : SharedRootableSystem;
```

2025-06-04 10:33 UTC, ScarKy0 commented on Content.Server/Rootable/RootableSystem.cs
> +    [Dependency] private readonly ISharedAdminLogManager _logger = default!;
```suggestion
public sealed class RootableSystem : SharedRootableSystem
{
    [Dependency] private readonly ISharedAdminLogManager _logger = default!;
```

2025-06-04 10:34 UTC, ScarKy0 commented on Content.Server/Rootable/RootableSystem.cs
> +using Robust.Shared.Timing;
```suggestion
﻿using Content.Server.Body.Components;
using Content.Server.Body.Systems;
using Content.Shared.Administration.Logs;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Components;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Database;
using Content.Shared.FixedPoint;
using Content.Shared.Fluids.Components;
using Content.Shared.Rootable;
using Robust.Shared.Timing;
```
Unused

2025-06-04 10:53 UTC, merged

2025-06-04 10:54 UTC, K-Dynamic commented
self merg

2025-06-04 10:55 UTC, VasilisThePikachu commented
It had the proper approvals so it's ok

2025-06-04 19:43 UTC, ArcaneOcto commented
Legendary. Time to make a silly little tree person