Fixes some cable sprite issues
space-wizards/space-station-14 pull request #32822
Opened 2024-10-14 20:14 UTC by Moomoobeef

## About the PR
Moved LV and MV a bit so that both cables are visible underneath catwalks.
Fixed cable terminals to line up with HV cables.

## Why / Balance
Fixes #32731, also fixes the cable terminals not lining up with HV cables.

## Media
![2024-10-14_15-10](https://github.com/user-attachments/assets/ca914d62-9073-4c42-8a51-ab310e44b153)
![2024-10-14_15-11](https://github.com/user-attachments/assets/ea188666-d357-4e22-975a-c67a263bfa48)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None, probably

**Changelog**
nah

2024-10-14 20:19 UTC, Moomoobeef commented
![image](https://github.com/user-attachments/assets/9f870f4d-1933-49d4-a501-bbf1d5799e3c)
oops

2024-10-15 08:18 UTC, TheShuEd approved these changes
CC BY-SA 3.0
requires the license to reflect all changes applied.

2024-10-15 14:00 UTC, qwerltaz commented
This causes MV to obscure pipes again, especially under catwalk, which is what I wanted to prevent too when offsetting them.

![image](https://github.com/user-attachments/assets/5ec826ea-da9c-4f82-9a9d-e6038892402e)

A possible fix is to move LV and MV next to each other so half of each is visible through the hole which currently reveals LV. If that doesn't work or if it looks bad, I'm currently making a pr to show subfloor entities above catwalk, which will make all wires and pipes clearly visible when using t-rays, even with the current offsets.

2024-10-15 19:25 UTC, Moomoobeef commented
I can only offset them so far because the junction sprites take up so much space. I think what I'll do is put mv on the opposite side instead

2024-10-20 18:26 UTC, Moomoobeef commented
> I think what I'll do is put mv on the opposite side instead

I forgot to actually do thing. Will do thing now

2024-10-20 18:41 UTC, Moomoobeef commented
> A possible fix is to move LV and MV next to each other so half of each is visible through the hole which currently reveals LV.

On second thought I actually liked this idea better, but there is a problem I discovered. LV and MV cables have the same drawdepth, and will draw over each-other depending on which is placed first
![image](https://github.com/user-attachments/assets/154026db-063c-47d0-94a5-b65adb262ee9)
![image](https://github.com/user-attachments/assets/a5dfca67-6549-45ed-a77d-ef817b8ae56f)
To fix this LV would have to be at a higher depth than MV, so I'll put LV at ThinPipe depth. It's weird, but LV and pipes don't generally overlap so I *think* it's fine? It shouldn't break anything at the very least, but it IS weird.

2024-10-20 18:44 UTC, Moomoobeef commented
![image](https://github.com/user-attachments/assets/b7d6a7b2-c43e-4af1-83cc-5053c3ca8638)
Great success

2024-10-20 18:45 UTC, Moomoobeef commented
> CC BY-SA 3.0 requires the license to reflect all changes applied.

2024-10-20 18:45 UTC, Moomoobeef commented
fuck I hit the wrong button

2024-10-20 18:46 UTC, Moomoobeef commented
> > CC BY-SA 3.0 requires the license to reflect all changes applied.

now to fix this accordingly and then commit :P

2024-10-20 18:58 UTC, Moomoobeef commented
![cables](https://github.com/user-attachments/assets/41dd506c-7d17-4daa-9d74-953d3d42a4a7)
graphic I made illustrating the changes

2024-12-27 11:21 UTC, Pumkin69 commented
thank you very much i really hated catwalks as an engineer player and frequently cut them up.

2025-04-18 18:05 UTC, MilonPL requested changes
With the recent MV changes I feel like only the LV cable needs to be moved up by a pixel or two up. Everything else is recognizable.
![image](https://github.com/user-attachments/assets/fba9ca71-febb-408b-8ce9-b4ca8648c1ea)

2025-04-29 00:13 UTC, EmoGarbage404 commented
Ping to reopen if you come back to this.

2025-04-29 00:13 UTC, closed without merging

2025-09-03 09:19 UTC, Moomoobeef commented
I completely forgot about this PR. I don't even know if the relevant problem still exists or not but the issue is still open. I'll have to check next time I'm in game.