Altered map playercount restrictions
space-wizards/space-station-14 pull request #32836
Opened 2024-10-15 23:20 UTC by DuckManZach

## About the PR

Altered the range of players needed for certain maps to appear. More specifically, The max player cap for smaller maps is increased, and the minimum amount of players needed for larger maps is also increased.
## Why / Balance

This allows for smaller maps to appear at higher player counts. When playing towards the minimum player count for larger maps, the station often feels understaffed and desolate. This PR fixes this by allowing for smaller stations to be rolled at a higher player count. It's a better experience when a station has most of its roles filled by crew, rather than barely having what it needs to function. 
## Technical details

some simple changes in the map yml files
## Media

Not nessessary
## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Smaller maps can now appear at higher play counts.

2024-10-15 23:33 UTC, muburu commented
reach should remain unchanged it's really like a below 10 pop map

2024-10-16 00:46 UTC, luckyshotpictures requested changes
The upper limit of Saltern does not support 50 players. 
Similarly, Reach also is not made for 10+ players.

 Omega and Packed are low pop player maps, I really do not suggest upping the minPlayers for those maps.

2024-10-23 05:46 UTC, luckyshotpictures approved these changes
These changes are good now.

2025-01-19 08:22 UTC, Emisse commented
its fine just needs to fix goncflicts

2025-01-19 08:23 UTC, Emisse approved these changes

2025-04-14 23:24 UTC, MilonPL commented
@DuckManZach please fix merge conflicts and remove the submodule changes from the PR.

2025-04-18 13:16 UTC, MilonPL commented
Thank you for your contribution! We've decided to close it due to inactivity. If you ever come back to it, feel free to open a new PR.

2025-04-18 13:16 UTC, closed without merging