hivelord resprite
space-wizards/space-station-14 pull request #32840
Opened 2024-10-16 06:09 UTC by muburu

## About the PR
gives hivelord cool new sprites i made from scratch.
also gives the hivelord remains aka "rorocore" inhand sprites because why not

## Why / Balance
hivelord looked stanky and was hard to see in the dark

## Technical details
just png additions and meta json things. 
also removed seemingly redundant sprites in the hivelord rsi, the "nocore" and "active" sprites, if these are used in-game somewhere let me know (i'll have alot more work to do if so :)).

## Media
![hivelord](https://github.com/user-attachments/assets/2a52707a-53c5-4db3-b212-b150b4795c08)
hivelord
![hivelordbrood](https://github.com/user-attachments/assets/85b1270b-9efb-4bc9-a12d-f89e1a98f150)
little tentacle clone things
![hivelord-dead](https://github.com/user-attachments/assets/26f70da8-ceba-4bc9-aba5-59ae0a012e60)
dead

- frame duration of these gifs are the same ones i have set in game
- scream at me if you want something here changed

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
no changeylog

2024-10-16 22:48 UTC, Flareguy requested changes
This needs ingame screenshots, preferably in the setting they tend to actually spawn (the mining asteroid.)

2024-10-17 00:20 UTC, muburu commented
added epic gif of hivelord destruction in mockup mining asteroid so you can see it animated in game

2024-11-06 06:17 UTC, muburu commented
shnooo mimimimimi (i would like an update on this thanks)

2025-01-07 05:46 UTC, Stewie523 commented
holy slop the current sprite is good.

2025-01-07 18:16 UTC, closed without merging

2025-01-07 18:17 UTC, muburu commented
closing because no art lead approval and don't really wanna work on it