Make medkits and boxes occupy less space
space-wizards/space-station-14 pull request #32862
Opened 2024-10-17 12:24 UTC by NoElkaTheGod

## About the PR
All medkits and boxes (e.g. survival box) are now 2x2 in inventory. The amount of space inside is unchanged.

## Why / Balance
Medkits and boxes were useless to carry in your backpack, because they take just as much space as their contents would. Now they aren't useless, providing more inventory space, but making your backpack harder to manage.

## Technical details
Minor YAML changes.

## Media
![Funny](https://github.com/user-attachments/assets/0a397a6b-66a2-4fb1-8e04-fe9ce1cd0de5)
Some examples.

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- tweak: Various boxes and medkits are now 2x2 items.

2024-10-17 12:30 UTC, deltanedas commented
tardis good
also for medkits this is irrelevant as youve always been able to make combat medkits for 3 plastic which are 2x2 right now

2024-10-17 12:36 UTC, NoElkaTheGod commented
> also for medkits this is irrelevant as youve always been able to make combat medkits for 3 plastic which are 2x2 right now

I know, but i think it doesn't really make sense. Why is combat medkit small, but all the others aren't?

2024-10-17 12:41 UTC, thebadman4662 commented
> > tardis good also for medkits this is irrelevant as youve always been able to make combat medkits for 3 plastic which are 2x2 right now
> 
> Why they cost the same, but occupy different amount of space? Sounds strange...

Black makes you slimmer, duh!

2024-10-17 12:41 UTC, Kadeo64 commented
>youve always been able to make combat medkits for 3 plastic which are 2x2 right now

wtf

2024-10-17 12:45 UTC, thebadman4662 commented
> > youve always been able to make combat medkits for 3 plastic which are 2x2 right now
> 
> wtf i thought black medkit was syndie contraband and that's why it could get away with tardis shenanigans

Like every single CMO room have combat medkits, some are even in normal doctor areas 😆

2024-10-17 12:48 UTC, Kadeo64 commented
> Like every single CMO room have combat medkits, some are even in normal doctor areas 😆

i have 600 hours in science not 600 hours in medical

2024-10-17 13:10 UTC, NoElkaTheGod commented
I just tested, and yes, combat medkit is craftable in medical techfab with 3 plastic, just like any other medkit, but for some reason is smaller.

On the other hand, i have no clue how did i manage to break something with just 7 lines of YAML. Any ideas on that failing test?

2024-10-17 13:59 UTC, lexaSvarshik commented
Medkits should be 3*2 because we already have a combat medkit with its unique feature of being 2*2 size. Or make the combat medkit bigger inside because of this change.

2024-10-17 14:09 UTC, TurboTrackerss14 commented
Just make the combat medkit more expensive than a normal medkit so its not just a "better" carbon copy than the other medkits.. 

Inventory tetris/tardis mechanics are dumb and pushing it even further is just gunna make inventory management even more tedious than it is now. 

Why take a dufflebag with a clear 10% speed reduction when you can print medkits and be 100% speed..

2024-10-17 14:20 UTC, UncaughtEx commented
Tetris is an inherent trait of grid inv in its current state sadly
Especially with side arms being Ls

2024-10-17 14:50 UTC, NoElkaTheGod commented
> Just make the combat medkit more expensive than a normal medkit so its not just a "better" carbon copy than the other medkits..

It's still a better copy of the other medkits, because the other medkits are useless.

> Inventory tetris/tardis mechanics are dumb and pushing it even further is just gunna make inventory management even more tedious than it is now.

I don't see how making an item actually useful would make inventory management more tedious. Quite the opposite, now you don't have to take every item out of your survival box every round, because survival box takes up less space than it's contents. Yes, you can fill the entire backpack with cardboard boxes, but that would be really inconvenient, so you probably won't do that.

> Why take a dufflebag with a clear 10% speed reduction when you can print medkits and be 100% speed..

Because with a duffelbag you don't have to check all 100500 medkits in your backpack to find that one stack of gauze. Duffelbag gives more space at the cost of movement speed, boxes (and medkits) will give space at the cost of convenience.

2024-10-17 14:59 UTC, Aisu9 commented
aren't medkits also following a white list? to prevent the so call tardi-meta

2024-10-17 15:11 UTC, SlamBamActionman commented
Medkits doesn't need to be smaller than their containers to be useful. They're perfectly fine for carrying and aren't used as a powergamer tool where some tider has an inventory full of medkits.

If anything it sounds like combat medkits shouldn't be craftable in the medfab.

2024-10-17 15:21 UTC, Aisu9 commented
> Medkits doesn't need to be smaller than their containers to be useful. They're perfectly fine for carrying and aren't used as a powergamer tool where some tider has an inventory full of medkits.
> 
> If anything it sounds like combat medkits shouldn't be craftable in the medfab.

i'm not sure CMO need another exclusive equipement, just triple their cost

2024-10-17 15:22 UTC, NoElkaTheGod commented
Reverted all changes involving medkits, because some people were upset. Would probably make another PR after proper discussion in discord.

2024-10-17 15:42 UTC, superjj18 commented
This change will result in a meta shift of keeping emergency kits due to increased inventory space.  Not an objection but there are pretty sizable gameplay implications here

2024-10-17 16:12 UTC, ArtisticRoomba commented
As long as the relevant kits are all properly whitelisted I don't mind the change too bad. I'm of the opinion that certain boxes are "display" boxes and a 3x3 is warranted (donk pockets for example), while things like emergency kits are supposed to be kept on your person and not used until there's an actual emergency.

Right now it's just inherently better to ditch your kit box and gridinv your stuff better, because you can squeeze a 3x3 into a 2x4.

If whitelisted, the description should be partially changed to communicate that it's explicitly designed to be a compact kit. I don't like whitelists all that much because it's just not communicated to the player but a hinting explanation is fine.

Also I think the base civilian medikit should potentially stay the same. It decreases the attractiveness of the combat medikit (which a doctor can make at the lathe if they really want it).

2024-10-17 16:17 UTC, UncaughtEx commented
I will always be in the mindset that the survival boxes are awful to deal with

2024-10-17 16:46 UTC, NoElkaTheGod commented
> As long as the relevant kits are all properly whitelisted I don't mind the change too bad. I'm of the opinion that certain boxes are "display" boxes and a 3x3 is warranted (donk pockets for example), while things like emergency kits are supposed to be kept on your person and not used until there's an actual emergency.

Most (if not all) boxes inherit CardboardBox, including donk pockets and everything else, so yes, all of them are 2x2 now. I don't think that this is a problem, because you don't have much reason to carry "display" boxes with you anyways.

> Also I think the base civilian medikit should potentially stay the same. It decreases the attractiveness of the combat medikit (which a doctor can make at the lathe if they really want it).

Medkit changes were reverted, now this PR only changes boxes.

2024-10-17 21:06 UTC, YotaXP commented
Gonna be harder to fulfill the "cardboard boxes" cargo bounty if everyone's keeping theirs, but that can be adjusted separately.

3x3 to 2x2 is a 56% reduction in area. Seems pretty drastic. Have you considered 3x2? (For medkits as well.)

2024-10-17 21:06 UTC, IProduceWidgets commented
I don't want tardis inventory while we still have singleton ui. Its unpleasant to deal with.

2024-10-17 21:52 UTC, YotaXP commented
Did some napkin math, so numbers may not be accurate. This will more than double potential storage capacity, which seems a bit... excessive.

| **3x3 Boxes (Current)** | Backpack | Satchel | Duffel Bag |
|---|:---:|:---:|:---:|
| How many boxes fit inside | 2 | 1 | 2 |
| Potential number of slots | 28 (+0%) | 32 (+0%) | 40 (+0%) |

| **3x2 Boxes** | Backpack | Satchel | Duffel Bag |
|---|:---:|:---:|:---:|
| How many boxes fit inside | 4 | 4 | 6 |
| Potential number of slots | 40 (+42.9%) | 44 (+37.5%) | 58 (+45%) |

| **2x2 Boxes (This PR)** | Backpack | Satchel | Duffel Bag |
|---|:---:|:---:|:---:|
| How many boxes fit inside | 6 | 8 | 8 |
| Potential number of slots | 58 (+107.1%) | 72 (+125%) | 80 (+100%) |

2024-10-18 03:17 UTC, deltanedas commented
because you can only have 1 storage open at a time the tradeoff for tardis is having much more tedious inventory management

2024-10-18 03:31 UTC, thebadman4662 commented
> Gonna be harder to fulfill the "cardboard boxes" cargo bounty if everyone's keeping theirs, but that can be adjusted separately.
> 
> 3x3 to 2x2 is a 56% reduction in area. Seems pretty drastic. Have you considered 3x2? (For medkits as well.)

Just buy some pizza.

Cargo gets bounty.
Rat King gets to eat.
Chemlab gets omnizine for ambuzol+ and necrozol.

2024-10-18 06:09 UTC, NoElkaTheGod commented
> 3x3 to 2x2 is a 56% reduction in area. Seems pretty drastic. Have you considered 3x2? (For medkits as well.)

While filling your inventory with boxes does give you a lot more space, you have to be insane to manage that amount of inventories. Making boxes 3x2 would make that option even less attractive, because not only do you have to manage a mildly annoying amount of boxes, but this doesn't even give you 50% more space.

Also, comparing inventory space that way is not very correct, because some items aren't 1x1, so you can't put, for example, 2 stacks of steel in one box. If anything, a backpack full of boxes is more of a satchel on crack than a direct upgrade.

2024-10-18 06:47 UTC, thebadman4662 commented
Stack of steel won't fit into a box because of item siza anyways, no? If boxes turn 2x2 that makes them medium so only 1x1 and 1x2/L items are allowed.

2024-10-18 13:43 UTC, TurboTrackerss14 commented
> Stack of steel won't fit into a box because of item siza anyways, no? If boxes turn 2x2 that makes them medium so only 1x1 and 1x2/L items are allowed.

No. Because its still tagged as Large...

2024-10-18 14:17 UTC, NoElkaTheGod commented
maxItemSize on all boxes is still set to "small", so you can't put a stack of steel in a box, because a stack of steel is "Normal". Boxes themselves are tagged as "Large" on purpose, because some boxes allow "Medium" items, and we don't want players to put a box in a box.

2024-10-18 15:10 UTC, thebadman4662 commented
> maxItemSize on all boxes is still set to "small", so you can't put a stack of steel in a box, because a stack of steel is "Normal". Boxes themselves are tagged as "Large" on purpose, because some boxes allow "Medium" items, and we don't want players to put a box in a box.

Yeah, there are some items that are like 3x4 and still can't accept anything bigger than 1x2 or 1x1 in some cases. When you make 0TC bombs recipes you really find out how some of containers suck. 😆

2025-03-12 13:38 UTC, cfif126 commented
Should have been merged already

2025-03-12 14:18 UTC, NoElkaTheGod commented
Maintainers seem to be very indecisive about this one, so i guess we'll have to wait a couple more years

2025-03-12 14:19 UTC, NoElkaTheGod commented
Woops, sorry, butterfingers

2025-04-13 05:21 UTC, beck-thompson requested changes

2025-04-13 05:21 UTC, beck-thompson commented on Resources/Prototypes/Entities/Objects/Specific/Medical/medkits.yml
> +
don't touch this

2025-04-13 05:23 UTC, beck-thompson commented on Resources/Prototypes/Entities/Objects/Specific/Medical/medkits.yml
> +
hey also just realized this is under discussion! Started a vote, dont bother making changes until I get the result! Sorry for the long wait :)

2025-04-13 05:57 UTC, IProduceWidgets commented on Resources/Prototypes/Entities/Objects/Specific/Medical/medkits.yml
> +
> don't touch this

Lol, funny way to phrase.
You probably need to remove a newline or blank spaces from the PR in that file so it doesn't pollute the edit history.

2025-04-13 08:42 UTC, NoElkaTheGod commented on Resources/Prototypes/Entities/Objects/Specific/Medical/medkits.yml
> +
I had bothered to make changes before you got the result

2025-04-14 05:27 UTC, closed without merging

2025-04-14 05:27 UTC, beck-thompson commented
Thanks for your PR! I looked at the old thread and did a vote and it was chosen to close this PR. The main reason mostly just being to avoid "tetras" powergaming where you stack up lots of boxes in your inventory to hold a bunch of stuff.

Again, sorry for requesting changes - I didn't realize there was a vote on it :cry:

2025-04-14 05:34 UTC, NoElkaTheGod commented
Well it's not like changing 1 line was hard lr anything. Gotta make all the boxes 1x1 for the next april fools update :trollface:

2025-04-14 09:05 UTC, lzk228 commented
> Thanks for your PR! I looked at the old thread and did a vote and it was chosen to close this PR. The main reason mostly just being to avoid "tetras" powergaming where you stack up lots of boxes in your inventory to hold a bunch of stuff.
> 
> Again, sorry for requesting changes - I didn't realize there was a vote on it 😢

well you can do it now with most of outer clothing (coats, jackets), maybe we could resize boxes to 3x2?

2025-04-14 15:32 UTC, NoElkaTheGod commented
> I should point out in the time I've looted bodies, I haven't ever seen anyone carry like 6 different winter jackets for nested storage.

That's exactly my point. You can only open one inventory at a time, so using a lot of winter jackets is very inconvenient. Same applies to boxes (i've played a server where boxes are 2x2, haven't seen anybody carrying more than 2).