HOTFIX Traitor activation fix for missing PDA (#30359)
space-wizards/space-station-14 pull request #32880
Opened 2024-10-18 13:06 UTC by Errant-4

## About the PR
Deploy #30359 to Stable

Traitors who "activate" without a PDA will now correctly get the codewords, the audio notification, and get an installed Uplink Implant. The cost is taken from their starting TC. This is objectively a worse situation than actually having purchased this implant from a normal uplink, but is still far better than missing out on all your TC and not knowing the code words

**Changelog**

:cl: Errant
- fix: Players becoming Traitor without a PDA now correctly get the text and audio notifications, and the code words. They are also given an Uplink Implant, with the price taken from their starting TC.

2024-10-18 16:47 UTC, keronshb requested changes
Not a hotfix, this is a bandaid. Should go through the usual process instead of merge to stable.

2024-10-18 16:57 UTC, VasilisThePikachu commented
> Not a hotfix, this is a bandaid. Should go through the usual process instead of merge to stable.

May I ask what you would consider a fix?

2024-10-18 17:26 UTC, thebadman4662 commented
> > Not a hotfix, this is a bandaid. Should go through the usual process instead of merge to stable.
> 
> May I ask what you would consider a fix?

Legacy PDAs getting the uplink? 🤔 

There are legacy IDs(changing them changes manifest) so doing something similiar but with PDA would be logical step, maybe part of it is already implemented as PDA have data like who the original owner is and that could be used for when it should get uplink?

2024-10-19 04:55 UTC, WhiteGorila commented
Adding headset uplink also could be a fix/workaround as headset uplinks are in 13

2024-10-21 08:02 UTC, Errant-4 commented
Hotfix has been contested so the PR will go through regular review instead

2024-10-21 08:02 UTC, closed without merging