Mutetoxin buff
space-wizards/space-station-14 pull request #32915
Opened 2024-10-19 22:17 UTC by Thatonestomf

## About the PR

Made Mute toxin still mute you even after its metabolized, similar to glue
## Why / Balance

Mute toxin is heavily underpowered for its cost, and its expensive and still worse then glue at muting targets
## Technical details

i just added mute time to mute toxin
## Media

none needed
## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None i hope
**Changelog**

:cl:
- tweak: Mute toxin now mutes even after is metabolized, similar to glue

2024-10-19 22:20 UTC, slarticodefast commented
Looks like you branched off from the wrong branch. Your smile raffle change is in here.

2024-10-19 22:23 UTC, TurboTrackerss14 commented
It should add way more than 5s. 
Considering glue does the exact same timer, and is used to make mutetoxin.

2024-10-19 22:26 UTC, slarticodefast commented
Or keep both at 5s and make glue not accumulate.

2024-10-19 23:45 UTC, Thatonestomf commented
I wanted to avoid nerfing glue so ill just go ahead and buff Mute even more, although it may be a bit unfun to get hit by

2024-10-20 00:09 UTC, Thatonestomf commented
alright i buffed it to 10 seconds of mute per tick and....
![image](https://github.com/user-attachments/assets/705cd5fa-b1a2-438e-bc40-210d277506f3)
![image](https://github.com/user-attachments/assets/f58998d8-5c82-4e57-ba4f-93a3e33233dd)

its a bit busted, but imma be real mute toxin is still too expensive, it may need a new recipe

2024-10-20 00:17 UTC, slarticodefast commented
I guess it has to be pretty powerful to justify its cost, even if it means your target will have to play as a mime for a while 😆

2024-10-20 00:19 UTC, slarticodefast requested changes

2024-10-20 00:19 UTC, slarticodefast commented on Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
> +    raffle: null
```suggestion
```
this is from another PR

2024-10-20 00:33 UTC, Thatonestomf commented on Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
> +    raffle: null
thanks for getting that

2024-10-20 00:40 UTC, slarticodefast approved these changes
Tested it and while this is quite strong it feels reasonable considering how expensive mute toxin is to make (needing vestine and uranium). Could you adjust the changlog to include the strength increase?

2024-10-20 00:41 UTC, slarticodefast commented
Fixes #32910

2024-10-20 00:44 UTC, Thatonestomf commented
change log updated, 2 PRs done in 3 days, im feeling good

2024-10-20 03:24 UTC, Coolsurf6 commented
Even with this buff, I think it might be justified and could even be made stronger in the future. When things like PDA Messaging becomes a thing, people could just message about what occured using their PDA. I think this being an upgrade for glue seems justified imo.

2024-10-21 03:43 UTC, chromiumboy commented
Let's give it a shot. If it ends up being too oppressive, it's not hard to change/revert

2024-10-21 03:43 UTC, merged