make emergency lights (de)constructable
space-wizards/space-station-14 pull request #32945
Opened 2024-10-22 01:46 UTC by Boolean-Buckeye

* add an emergency light node to the LightFixture construction graph
* add a recipe entry to the construction menu for emergency light
* make emergency light entity at the emergency light node on the graph

## About the PR

I made emergency lights constructible and deconstructible.

## Why / Balance

When I was playing the game, I right clicked an emergency light and there was an option to "Begin Deconstructing". which I clicked, and then I examined the emergency light and it said to use a screwdriver next. But when I went to do that, nothing happened. It turns out this examine shows up I think because the parent of the emergency light entity has it at the light tube point on the light fixture construction graph by default. So, being annoyed, I went and looked up how to code for ss14 to fix this. The recipe is one steel and one glass, and I figure since the emergency light looks almost exactly like the empty light fixture, just adding glass to the recipe would be fine. It's a pretty simple (and very small) looking structure with not much use so I think it would be overkill to require using a lathe to print an emergency light like with the other wall lights like bulbs and tubes. 

## Technical details

I fixed it by adding a new node on the light fixture graph for emergency lights. This only required changing the yamls to:
* add a construction node for emergency lights in light fixture graph
* add the recipe to the construction menu
* emergency light entity construction component set to this new node

## Requirements

- [x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x ] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Emergency lights can be constructed and deconstructed

2024-10-22 02:57 UTC, slarticodefast commented
The test fail is real.
EmergencyLight inherits this from AlwaysPoweredWallLight, meaning if you destroy it by force, you will get 2 steel sheets, while constructing it only needs 1.
![grafik](https://github.com/user-attachments/assets/b7806056-74d8-4d04-a020-d234f28eafeb)

2024-10-22 03:16 UTC, Boolean-Buckeye commented
> The test fail is real. EmergencyLight inherits this from AlwaysPoweredWallLight, meaning if you destroy it by force, you will get 2 steel sheets, while constructing it only needs 1. ![grafik](https://private-user-images.githubusercontent.com/161409025/378662790-b7806056-74d8-4d04-a020-d234f28eafeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjYzNTYsIm5iZiI6MTcyOTU2NjA1NiwicGF0aCI6Ii8xNjE0MDkwMjUvMzc4NjYyNzkwLWI3ODA2MDU2LTc0ZDgtNGQwNC1hMDIwLWQyMzRmMjhlYWZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwMzAwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Yzc4NzBjNDMwZjAxYjk5YmZmYTkyZDJjOGYwMzBkY2I2ODVjMmJmMTIxMWI2NGUzNTRmNGIxZjg4NDJhZjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5DI-qxmnEbXRoYpCN6ANfkQuo8gZTt72Fi-mUWHcRwg)

Hi, thanks for the explanation, I am impressed by this testing, this is my first time trying to do coding , I updated the PR so that the emergency light is destroyed into 1 steel and 1 glass shard

2024-10-22 08:05 UTC, Cojoke-dot commented
mmmm... it says they have an internal battery, maybe they should need a battery?

2024-10-22 09:09 UTC, slarticodefast commented
> mmmm... it says they have an internal battery, maybe they should need a battery?

All the other lights are really cheap to build as well, so I think it's fine without for consistency reasons.

2024-10-22 16:01 UTC, deltanedas commented
if anything it should be a capacitor not battery, that would be really annoying

2024-10-23 00:50 UTC, Boolean-Buckeye commented
@slarticodefast is it still awaiting changes ?

2024-11-01 03:22 UTC, deathride58 requested changes
PR looks good, but there's one little nitpick

2024-11-01 03:22 UTC, deathride58 commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +    - !type:TileNotBlocked
Comment is an unnecessary copypaste
```suggestion
  conditions:
    - !type:TileNotBlocked
```

2024-11-03 23:11 UTC, deathride58 approved these changes

2024-11-04 03:24 UTC, chromiumboy commented
Thank you for your first contribution!

The code looks good and it all tested fine in-game

2024-11-04 03:24 UTC, merged