Removed bola stam damage
space-wizards/space-station-14 pull request #32989
Opened 2024-10-24 23:44 UTC by ARMOKS

Bola stam damage consistently allows for a 0.5 second stun, this can be done in 5 or 6 ways with different items, its bad for combat.

## About the PR
Removed bola stam damage

## Why / Balance
Bola + Baton / prod throw (wall bounce) = 0.5 second stun
Bola + Prod throw = 1 second stun
Bola + Boxing gloves = 2-3 second stun
Bola + Rigged gloves = ~1 second stun
There are several other combos that are absolutely disgusting, this on top of the fact that you can bind remove from backpack and throw to the same key to insta launch bolas without warning makes them a mess. A solution that would also be fine is giving them some sort of slowdown from taking from bag to throwing. IIRC they do not even have an in-hand sprite.

**Changelog**
:cl: remove bola stam damage

2024-10-24 23:56 UTC, ARMOKS commented
If anyone is concerned about this I can record a few of the bola interactions and post them here to show what I mean

2024-10-25 02:42 UTC, Futuristic-OK commented
Make stun bola for secfab, before makeshift bolas nerf.

2024-10-25 02:52 UTC, ARMOKS commented
> Make stun bola for secfab, before makeshift bolas nerf.

half the issue is as sec I can bola someone then disabler them for a near instant unstoppable stun

2024-10-25 03:02 UTC, ArtisticRoomba commented
a bola should restrain my movement as it wraps around my legs, I should not all of a sudden become physically exhausted and be one/two disabler shot(s) from collapsing onto the floor

this balance change is completely fine, IMO

2024-10-25 04:58 UTC, ninruB commented
I think this essentially puts bolas out of commission like they were before they got stamina damage, but having 55 on-demand instant stamina damage on a makeshift item is ridiculous and shouldn't be a thing, especially considering that the stamina slow from taking 50 stamina damage will stack with whatever the bola itself applies.

Bolas should probably get a greater slowdown with this change.

2024-10-25 05:54 UTC, thebadman4662 commented
You forgor:

Bola + DBS = ~0.2 second stun.

2024-10-25 15:55 UTC, ARMOKS commented
> I think this essentially puts bolas out of commission like they were before they got stamina damage, but having 55 on-demand instant stamina damage on a makeshift item is ridiculous and shouldn't be a thing, especially considering that the stamina slow from taking 50 stamina damage will stack with whatever the bola itself applies.
> 
> Bolas should probably get a greater slowdown with this change.

It absolutely does not, sec has a big issue with tiders running and slipping them and whatnot. Throwing a bola instantly ends this as they can no longer run and sec can VERY easily stun them. Even without stam damage a massive slowdown is a game changing thing in combat

2024-10-25 15:56 UTC, ARMOKS commented
> Add Lazer bolas that cut people's legs off

I’ll PR this the second newmed drops

2024-10-25 16:25 UTC, thebadman4662 commented
> > I think this essentially puts bolas out of commission like they were before they got stamina damage, but having 55 on-demand instant stamina damage on a makeshift item is ridiculous and shouldn't be a thing, especially considering that the stamina slow from taking 50 stamina damage will stack with whatever the bola itself applies.
> > Bolas should probably get a greater slowdown with this change.
> 
> It absolutely does not, sec has a big issue with tiders running and slipping them and whatnot. Throwing a bola instantly ends this as they can no longer run and sec can VERY easily stun them. Even without stam damage a massive slowdown is a game changing thing in combat

Bola is more of ambush/defense tool than chase one, throws are too slow to catch tiders unless there is already warrant on them and they can't just weldmask it like flash/flashbang/clusterflash, provided there isn't someone, even dead in the way to block it when they stand still.

2024-10-25 23:08 UTC, SlamBamActionman commented
Instead of removing it, why not lower it to something like 20? That way you get some decent combo behavior with the stun baton/disabler without making the stun happen super fast.

Stamina slowdown happens at 50 stam damage. Stun baton deals 35 (2 hits = 70, 3 hits 105), Disabler deals 30 (2 hits = 60, 4 hits 120). 

A bola throw at 20 means the first stun baton hit deals stamina slowdown, but you still need 3 baton hits to stun. This makes the bola + baton combo slower than just using the baton, but you still get a lot of benefit for using the bola. 

For disabler, you also get a stun on the first hit *and* you get a stun after 3 hits instead of 4, which feels appropriate for doing a more complex set of actions with bola + 3 disabler shots compared to just shooting with the disabler 4 times.

2024-10-26 19:12 UTC, keronshb commented
> Instead of removing it, why not lower it to something like 20? That way you get some decent combo behavior with the stun baton/disabler without making the stun happen super fast.
> 
> Stamina slowdown happens at 50 stam damage. Stun baton deals 35 (2 hits = 70, 3 hits 105), Disabler deals 30 (2 hits = 60, 4 hits 120).
> 
> A bola throw at 20 means the first stun baton hit deals stamina slowdown, but you still need 3 baton hits to stun (20 > 55 > 90 > 125). This makes the bola + baton combo slower than just using the baton, but you still get a lot of benefit for using the bola.
> 
> For disabler, you also get a stun on the first hit _and_ you get a stun after 3 hits instead of 4 (20 > 50 > 80 > 110), which feels appropriate for doing a more complex set of actions with a bola + 3 shots combo, compared to just shooting with the disabler 4 times.

Alt to this -
Change the slowdown to mimic what it is now with the stam loss.

2024-10-26 19:21 UTC, Iamgoofball commented
Why don't you guys just make the bola work as originally designed; a flat slowdown until it's removed, no need to make it do any stamina damage. This is solved design.

2024-10-27 05:18 UTC, keronshb commented
> Why don't you guys just make the bola work as originally designed; a flat slowdown until it's removed, no need to make it do any stamina damage. This is solved design. No need to reinvent the wheel here.

That's exactly what I suggested.

2024-10-27 16:05 UTC, ARMOKS commented
> Why don't you guys just make the bola work as originally designed; a flat slowdown until it's removed, no need to make it do any stamina damage. This is solved design. No need to reinvent the wheel here.

this is exactly what im doing, im gonna edit it a bit later because I realize I left out the makeshift bola

2024-10-27 17:16 UTC, WhiteGorila commented
> Why don't you guys just make the bola work as originally designed; a flat slowdown until it's removed, no need to make it do any stamina damage. This is solved design. No need to reinvent the wheel here.

Dude this is literally my response to 90 percent of the PRS on this game. This shit has already been done to death and figured out before literally all anyone has to do is copy from 13 it ain't that hard!!

2024-10-27 23:19 UTC, SlamBamActionman commented
> > Why don't you guys just make the bola work as originally designed; a flat slowdown until it's removed, no need to make it do any stamina damage. This is solved design. No need to reinvent the wheel here.
> 
> Dude this is literally my response to 90 percent of the PRS on this game. This shit has already been done to death and figured out before literally all anyone has to do is copy from 13 it ain't that hard!!

SS13 is a great resource to start from, but since SS14 is quite different when it comes to combat (with its movement especially!) it's definitely worth taking the time to evaluate changes in the context of SS14. Rote copying of SS13 without examining how it acts in SS14 risks introducing its own errors.

There's also a good chance that while SS13 has found something that works, there might be other stuff that works too! And in some cases those stuff might work even better!

And in some it might not. But if 90% of PRs aren't allowed to be exploratory, there's not gonna be much room for innovation, and I see no point in resting on SS13's laurels.

2024-10-28 04:08 UTC, deltanedas commented
being able to instantly no-counter stun someone with a macro or good keybinds is not a good thing regardless of ss13/ss14

2024-10-28 22:55 UTC, metalgearsloth approved these changes

2024-10-29 05:35 UTC, keronshb requested changes

2024-11-10 03:27 UTC, keronshb approved these changes
lg2m

2024-11-10 03:32 UTC, merged

2024-11-10 07:06 UTC, MilenVolf commented
CL was not set right

2024-11-11 19:30 UTC, TermoNemo commented
sounds like _someone_ has **skill issues**

2024-11-11 19:45 UTC, sweekyl commented
pizda