CCVars that controls suicide and ghost
space-wizards/space-station-14 pull request #33040
Opened 2024-10-28 19:01 UTC by TokenStyle

## About the PR
Add CVar `cvar ic.enable_ghost <bool>` and `cvar ic.enable_suicide <bool>` that controls suicide or ghost.

## Why / Balance
Convenient, and having more parameters is good.

## Technical details
ic.enable_suicide - disables/enables SuicideSystem.Suicide method at all, that used only in SuicideCommand though.
ic.enable_suicide - disables/enables ghosting in GhostCommand.cs.

## Media
Changes are self explaining.
Thanks @QuietlyWhisper for implementation.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
ADMIN:
- add: CVar ic.enable_ghost <bool> now controls ghost command ability for all (including admins).
- add: CVar ic.enable_suicide <bool> now controls suicide command ability for all (including admins).

2024-10-30 01:37 UTC, PJB3005 requested changes

2024-10-30 01:37 UTC, PJB3005 commented on Content.Server/Ghost/GhostCommand.cs
> +                !_cfg.GetCVar(CCVars.ICEnableGhost)))
This really isn't the right place to put this check:

1. The denial message is "You cannot ghost right now.", which really does not clearly indicate that this is a server config thing.
2. This blocks using `ghost` while already dead, which is weird and actually breaks some mechanics that manually invoke the `ghost` command.

2024-10-30 01:42 UTC, Simyon264 commented
Unrelated, but why am I mentioned in the co-author section of the commit? I don't remember anything regarding this... lol?

This isn't anything bad, just strange.

2024-11-08 10:44 UTC, TokenStyle commented
Dunno `GhostCommand.cs` to disable only to Client and always available for server's side to use ghostCommand. Tried `IConsoleShell shell.IsClient` but it's works as expected and always `false` for `GhostCommand` (because it's located in Content.Server). Apparently, my skill issue to fix it, closing it. Feel free to use it in any way you would like to!

2024-11-08 10:44 UTC, closed without merging