Added the ability for pAIs and station maps to be stored in engineering belts
space-wizards/space-station-14 pull request #33048
Opened 2024-10-29 05:07 UTC by august-sun

## About the PR
Added the ability for pAIs and station maps to be stored in utility and CE belts.

## Why / Balance
This is primarily aimed at improving navigation throughout the station, as stations can sometimes be disparate in signage or provided maps. In particular, for engineers, it improves responsiveness to damage or other emergencies. For pAIs, the most pertinent benefit is simply having additional storage space (which is accurate for the pAI's size.)

## Technical details
Added the StationMapComponent to engineering belt whitelists.

## Media
![image](https://github.com/user-attachments/assets/ea2a6d26-9ee0-490e-99b4-c9d54c126ab2)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Utility and CE belts can now hold the pAI and the handheld station map.

2024-10-29 10:33 UTC, slarticodefast commented
you can already store the pAI in your PDA

2024-10-29 13:41 UTC, thetolbean commented
> you can already store the pAI in your PDA

Maybe you want to carry 8 pAIs + the one in your pda

2024-10-29 19:03 UTC, august-sun commented
> > you can already store the pAI in your PDA
> 
> Maybe you want to carry 8 pAIs + the one in your pda

Collects-the-pAIs, is that you?

2024-11-19 11:32 UTC, HyperB1 commented
Now, hear me out, what about the remote signallers? Can you add these as well?

2025-01-27 17:19 UTC, Simyon264 requested changes
The PR says it added the ability to store them in your belt, but the YAML changes do not reflect this.
Either: 
A: You intended to not include that feature (in which case, please change the title of the PR)
B: You DID want to do this (in which case, please change the YAML)

2025-01-27 18:47 UTC, Simyon264 approved these changes

2025-01-27 18:48 UTC, merged