Engineering guidebook improvements v2
space-wizards/space-station-14 pull request #33062
Opened 2024-10-30 00:53 UTC by ArtisticRoomba

## About the PR
Significantly updates the Engineering guidebook (more explicitly the Atmos section) to have a lot more relevant and useful information.

## Why / Balance
Right now engineering has been getting update after update with no real change to the relevant guidebook entry. This has lead to a lot of out of date information and bad practices being prevalent in the guidebook, something that pains me to read.

As a terminal CE main I feel like I am at least partially qualified to revise the guidebook to decent standards, and I don't mind keeping it up to date with new changes. Just give me a second to get it up to date though, there's a lot to add and clarify.

This PR is a draft. I am not done with this yet, but I've made enough progress to warrant putting this up as a draft to accept ideas and criticism. Ideally, all of the sections will be redone, the relevant atmos devices will have tooltip-links to the guidebook, all that jazz.

The end goal is to have a wikipedia-esque browsing experience; everything links to each other and people can follow links in the guidebook to learn more about certain topics they don't understand.

Keep in mind I am respecting the guidebook entries guidelines as best I can, explicitly this one:

> Refrain from including specific advice and “meta” strategies. The guide should be an impartial source of information.

This PR closes #32622.

This PR is a reopening of #32894 because I accidentally synced my fork and merged like a month's worth of commits into my branch. HAHAHAHAHAHAHAHAHA. You can laugh at me for this one. Gotta learn somehow. Sorry for spamming the repo, maints.

## Media
Preview of all the other pages that are fleshed out. I have yet to work on the rest of the engineering section.

![Content Client_hMpFalUSi1](https://github.com/user-attachments/assets/4366918e-cd1c-46ad-98a9-de487df5f0dc)

I'm leaving the media dry right now as I'm still working on this, nothing is final.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: The Engineering Guidebook has been significantly expanded and should be up to date.
- add: Most atmospherics and engineering-related devices and equipment now have a link to their relevant guidebook entry upon examine.

2024-11-01 07:12 UTC, ArtisticRoomba commented on Resources/ServerInfo/Guidebook/Engineering/Thermomachines.xml
> +  Thermomachines also have an efficiency coefficient, which determines how much work they can do per unit of power consumed.
freezer thermomachines do not appear to be thermodynamically sound as per

            float dQ = thermoMachine.HeatCapacity * thermoMachine.Cp * args.dt;

with the "Cp" variable being the Coefficient of Performance, which is -3.9 lmfao, so I might just omit this, not sure how I feel about it.

I *do want* people to do nerd atmos math to find cool solutions to problems though...

2024-12-05 17:43 UTC, Admiral-Obvious-001 commented on Resources/ServerInfo/Guidebook/Engineering/AirVent.xml
> +  For example, this means that an air vent will be unable to pump to 101.3kPa if the gas inside the vest goes below half that (50.65kPa).
Vest/vent

2024-12-05 19:04 UTC, Admiral-Obvious-001 approved these changes
That's it. Very, very good, way better than what we have now.

2024-12-05 21:52 UTC, Admiral-Obvious-001 commented on Resources/ServerInfo/Guidebook/Engineering/SingularityEngine.xml
> +  - Turn on the Radiation Collectors.
Forgot to add that the collectors need plasma gas canisters in this step. Probably more important to note it first than later down in the same section.

2024-12-06 01:27 UTC, ArtisticRoomba commented
> That's it. Very, very good, way better than what we have now.

thanks a bunch!

2024-12-12 13:33 UTC, Potion2112 approved these changes

2024-12-12 13:36 UTC, Potion2112 approved these changes

2024-12-17 16:57 UTC, ArtisticRoomba commented
By royal decree I declare this PR open for review. I'd say it's in a good state to merge, content-wise. I've included some media so you can see what it looks like in-game.

And thanks in advance to whoever fully reviews this poor PR.

2024-12-17 16:59 UTC, ScarKy0 commented
newguide is real

2024-12-17 17:04 UTC, ArtisticRoomba commented
> newguide is real

Merge just a week away
I dare you to review it

2024-12-17 17:38 UTC, ScarKy0 commented
> Merge just a week away
I dare you to review it

Bold of you to assume I know anything of engineering to make sure the info is accurate

2024-12-21 10:25 UTC, Pumkin69 commented
amazing pr

2024-12-28 01:01 UTC, cohanna commented
with the addition of the advanced SMES, the SMES section needs a small adjustment to clarify the difference, and the utility, of the advanced smes

2024-12-28 01:45 UTC, ArtisticRoomba commented
> with the addition of the advanced SMES, the power storage section needs a small adjustment to clarify the difference, and the utility, of the advanced smes

Yeah, I guess I gotta do that now... goddammit...

2024-12-28 01:48 UTC, cohanna commented
> Yeah, I guess I gotta do that now... goddammit...

An up to date guide book really is sisyphusian in nature huh lol

2024-12-29 10:03 UTC, ArtisticRoomba commented
> > Yeah, I guess I gotta do that now... goddammit...
> 
> An up to date guide book really is sisyphusian in nature huh lol

You win.

![image](https://github.com/user-attachments/assets/88e6ae26-c209-4c49-8c56-ed01c64fc18c)

2024-12-30 00:22 UTC, cohanna commented
Quick get a maintainer to merge it before they add something else lol

2025-01-14 20:07 UTC, southbridge-fur commented on Resources/ServerInfo/Guidebook/Engineering/Radiators.xml
> +  To increase the efficiency of radiation, you can build radiators on scaffolding, which will allow the radiator to radiate more heat, compared to being directly attached to hull tile.
I also constantly call it "scaffolding" instead of "lattice"

2025-01-14 20:11 UTC, southbridge-fur commented on Resources/ServerInfo/Guidebook/Engineering/Shuttlecraft.xml
> +  This platform is considered a different grid from the station, and thus will not have any gravity or be static — it can move around freely.
Could change the static wording here to say something like "this new grid has no gravity, nor is it held in place by a station anchor"

2025-01-14 20:25 UTC, southbridge-fur commented on Resources/ServerInfo/Guidebook/Engineering/SolarPanels.xml
> +  Solar powers generate [color=orange]HV power[/color], and as such require an [color=orange]HV wire[/color] running underneath them to connect to the station's power grid.
Typo "Solar powers"

2025-01-14 20:39 UTC, southbridge-fur commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
>    - Heat-Exchanger: Basically, just a bunch of heat-exchanger pipes in space. Not much to say, besides the fact that it cools down the gas inside it. Make sure the heat-exchangers are [color=#a4885c]
Up to you if yu want to replace all the usage of the term "heat exchanger" with "radiator'

2025-01-14 20:48 UTC, southbridge-fur commented on Resources/ServerInfo/Guidebook/Engineering/VoltageNetworks.xml
> +  [color=green]Low Voltage[/color] wire doesn't have to be directly run to every machine, as it can power multiple machines as long as the wire is close enough to the machine.
Might want to specify that "close enough" is within two tiles radially, and three tiles in each cardinal direction

2025-01-15 12:39 UTC, ArtisticRoomba commented on Resources/ServerInfo/Guidebook/Engineering/FireAndGasControl.xml
> +  - The temperature between the two sides of the firelock is different by 330 K (57°C) or more.
Are you sure? In FirelockCompoent it's defined as:

```csharp
/// <summary>
        /// Maximum temperature difference before the firelock will refuse to open, in k.
        /// </summary>
        [DataField("temperatureThreshold"), ViewVariables(VVAccess.ReadWrite)]
        public float TemperatureThreshold = 330;
```

2025-01-15 12:44 UTC, ArtisticRoomba commented on Resources/ServerInfo/Guidebook/Engineering/FireAndGasControl.xml
> +  Firelocks will drop if the air alarm reaches a [color=red]Danger[/color] alert state. Firelocks will remain dropped until the air alarm returns to a [color=green]Green[/color] alert state.
Firelocks drop on a danger signal recieved, not a warning. Just tested it to check my sanity. I will clear up that inconsistency though, thanks.

2025-01-15 19:23 UTC, southbridge-fur commented on Resources/ServerInfo/Guidebook/Engineering/Radiators.xml
> +  To increase the efficiency of radiation, you can build radiators on scaffolding, which will allow the radiator to radiate more heat, compared to being directly attached to hull tile.
Up to you. I also agree that it should be called scaffolding

2025-01-15 19:24 UTC, southbridge-fur commented on Resources/ServerInfo/Guidebook/Engineering/FireAndGasControl.xml
> +  - The temperature between the two sides of the firelock is different by 330 K (57°C) or more.
Lel then that's a problem with the code too

2025-01-15 19:56 UTC, ArtisticRoomba commented on Resources/ServerInfo/Guidebook/Engineering/FireAndGasControl.xml
> +  - The temperature between the two sides of the firelock is different by 330 K (57°C) or more.
I'll have to look at this later, because there is a difference between dropping and a firelock lockout.

2025-01-16 00:43 UTC, ArtisticRoomba commented on Resources/ServerInfo/Guidebook/Engineering/FireAndGasControl.xml
> +  - The temperature between the two sides of the firelock is different by 330 K (57°C) or more.
I looked at the code a bit further and did some testing. In practice, temp lockout Works:tm: (when it does) however the intended firelock drop doesn't occur.

The heating is handled by Monstermos and the air just heats right past the firelock and it doesn't drop because the both sides are equal. If you want the locks to drop, you'd have to have a big rush of hot air hit the firelock, but it would have to be handled just right as right now Monstermos screws over firelocks barring specific circumstances.

Even then, usually massive bursts of heat are followed by huge pressures, so either:
- The firelocks will win (yay!) and drop, protecting the fire/heat from spreading.
- The firelocks get dunked on by Monstermos being Monstermos and it just runs right past

I tested this with the temp threshold set to 57 K and it didn't make a difference. However you're free to do your own testing as mine was probably flawed somehow.

2025-01-17 18:40 UTC, ScarKy0 commented
I'm never getting this time back :godo:

2025-01-17 18:41 UTC, ArtisticRoomba commented
> I'm never getting this time back :godo:

now get me another maintainer to review this and newguide will be real :godo:

2025-01-23 16:18 UTC, slarticodefast requested changes
I only had a quick look so far, but you seem to have hardcoded a bunch of numbers into the guidebook, for example wattage and pressure.
Could you use the values directly from the prototypes instead so they are automaticallly kept up to date? See https://github.com/space-wizards/space-station-14/pull/27570

2025-01-25 05:25 UTC, ArtisticRoomba commented
I've went ahead and un-hardcoded a lot of references. As far as I know, everything else are constants and won't change anytime soon. Let me know if I've missed anything, and thanks for the first review.

2025-01-25 05:44 UTC, Partmedia commented
Thank you for your work on the guidebook. I think once @slarticodefast confirms that their reviews comments were addressed, you'll have the two approvals needed to merge.

2025-01-25 05:44 UTC, Partmedia approved these changes

2025-01-26 17:25 UTC, nighoggDatatype commented on Resources/ServerInfo/Guidebook/Engineering/AirVent.xml
> +  For example, this means that an air vent will be unable to pump to 101.3 kPa if the gas inside the vent goes below half that.
Uh, not a maintainer, but can't help but notice that 101.3 kPa is still hard coded here. You may want to use `[color=orange][protodata="GasVentPump" comp="GasVentPump" member="DefaultExternalBound"/] kPa[/color]` as you did above, since that will likely be what default station pressure would be synced to.

2025-01-26 17:53 UTC, ArtisticRoomba commented on Resources/ServerInfo/Guidebook/Engineering/AirVent.xml
> +  For example, this means that an air vent will be unable to pump to 101.3 kPa if the gas inside the vent goes below half that.
Intentionally hardcoded. These numbers don't relate to the actual performant values of an air vent, they demonstrate an example that was previously mentioned using important numbers.

The point is that if your distro pressure falls below ~50 kPa, you'll be unable to pressurize the station to standard atmospheric, which is a huge issue and it's important to communicate that mechanic to a new player.

2025-01-27 19:41 UTC, Partmedia commented
I made a best effort to get @slarticodefast to confirm that review concerns were addressed. I believe these concerns have been addressed, and given the potential for merge more conflicts and that we already have the required number of maintainer approvals, I'm going to go ahead and merge this now. Thank you very much for this work.

2025-01-27 19:42 UTC, merged

2025-01-27 20:03 UTC, ArtisticRoomba commented
Slart had cosmetic concerns that would be good if addressed, these will be committed in a seperate PR. Thanks for merging.

2025-01-27 22:12 UTC, slarticodefast reviewed
Looks like this got merged while I was reviewing it, but I got some more change requests.
First, as far as I know using an Oxford comma is not allowed when listing only two items, see
https://writing-center.phsc.edu/grammar/punctuation/commas/items-series
or
https://en.wikipedia.org/wiki/Serial_comma
I marked some other cases, too, but I'm not completely certain, so you might want to double check.

Otherwise there is the accidental setting change that was done in `sensor.yml` which is important for air alarms and should be reverted as soon as possible.

And I got some nitpicks regarding the yaml indentation convention.

Thanks for all the effort you put into this guide!

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/FireAndGasControl.xml
> +  If the conditions between the two sides of the firelock return to within acceptable differences, the firelock will disable lockout mode, and can be opened by anyone.
```suggestion
  If the conditions between the two sides of the firelock return to within acceptable differences, the firelock will disable lockout mode and can be opened by anyone.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/FireAndGasControl.xml
> +  This can be used to quickly drop firelocks in a room manually, or to raise them after an upset has been resolved.
```suggestion
  This can be used to quickly drop firelocks in a room manually or to raise them after an upset has been resolved.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  The TEG generates power by exchanging heat between hot and cold gases.
```suggestion
  The TEG generates power by exchanging heat between hot and cold gasses.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  The circulators take in either a hot or cold gas, and pass it through the machine to exchange heat.
```suggestion
  The circulators take in either a hot or cold gas and pass it through the machine to exchange heat.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  Most (if not all) stations have the burn chamber separated from the main atmospherics block by a 1-wide spaced grid, to prevent the flow of scalding hot gas to Atmos if there was a breach. The cham
```suggestion
  Most (if not all) stations have the burn chamber separated from the main atmospherics block by a 1-wide spaced grid to prevent the flow of scalding hot gas to Atmos if there was a breach. The chambers consist of 3 important parts:
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  Either should be supplemented with a pump before it, to keep pressures high.
```suggestion
  Either should be supplemented with a pump before it to keep pressures high.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  Open this occasionally to keep the pressure under control, or to space excess input gas.
```suggestion
  Open this occasionally to keep the pressure under control or to space excess input gas.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  Instead, use a network configurator to connect all the [textlink="scrubbers" link="AirScrubber"] to a nearby air alarm, and set the air alarm's [textlink="scrubber" link="AirScrubber"] settings to
```suggestion
  Instead, use a network configurator to connect all the [textlink="scrubbers" link="AirScrubber"] to a nearby air alarm, and set the air alarm's [textlink="scrubber" link="AirScrubber"] settings to scrub everything except Oxygen and Plasma and to siphon air as well.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  A gas pump at max pressure should be placed after, and a volumetric pump before the heat-exchangers.
```suggestion
  A gas pump at max pressure should be placed after and a volumetric pump before the heat-exchangers.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  Remember, Atmospherics is a science, and as such, it is always evolving.
```suggestion
  Remember, Atmospherics is a science and as such, it is always evolving.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  The setups above are just the tip of the iceberg; there are many ways to setup the TEG, and many ways to improve upon the setups above.
```suggestion
  The setups above are just the tip of the iceberg; there are many ways to setup the TEG and many ways to improve upon the setups above.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  Always seek to improve upon the designs you see, and always seek to improve upon the designs you make.
```suggestion
  Always seek to improve upon the designs you see and always seek to improve upon the designs you make.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  The TEG is a powerful tool, and with great power comes great responsibility.
```suggestion
  The TEG is a powerful tool and with great power comes great responsibility.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  Make sure to use it wisely, and make sure to use it well.
```suggestion
  Make sure to use it wisely and make sure to use it well.
```

2025-01-27 22:12 UTC, slarticodefast commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  Space Station 14 atmospherics is a complex system, and the TEG is just one part of it.
```suggestion
  Space Station 14 atmospherics is a complex system and the TEG is just one part of it.
```

2025-01-27 22:16 UTC, ArtisticRoomba commented
I'll make those urgent air alarm changes and gloss over the guidebook again when I get home, thanks for reviewing.