Fix: Examine Damage now specifies no damage
space-wizards/space-station-14 pull request #33064
Opened 2024-10-30 03:32 UTC by thetolbean

## About the PR
When you examine an item that is a weapon, but has no damage, IE a plushie, it now specifies that it does no damage.

## Why / Balance
Shows that the examined item is a weapon but does no damage.
Fix #33052 (Second try)

## Technical details
Checks the items damage dictionary to check if there is only one damage type and if that damage is 0.
Returns specific "no damage" message

## Media
![{35C8CA65-FA1E-4592-9019-5508252996CC}](https://github.com/user-attachments/assets/63e5485f-99c1-4fee-b0ba-d282b3058448)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- fix: Items with a damage of 0 now have correct damage examination text.

2024-11-02 17:12 UTC, PursuitInAshes approved these changes

2024-11-10 05:01 UTC, chromiumboy requested changes

2024-11-10 05:42 UTC, thetolbean commented on Content.Shared/Damage/Systems/DamageExamineSystem.cs
> +                if(damageSpecifier.DamageDict.Values.GetEnumerator().Current == FixedPoint2.Zero)
Ah, you're right. That is technically a possibility. That's what i get for assuming people would be smart about their damage types :godo:

But i did not realize that damageSpecifier had those methods. I'll go see if that works!

2024-11-10 06:46 UTC, thetolbean commented on Content.Shared/Damage/Systems/DamageExamineSystem.cs
> +                if(damageSpecifier.DamageDict.Values.GetEnumerator().Current == FixedPoint2.Zero)
> This doesn't account for the possibility that someone might assign more than one damage types set to zero. Try

Got this resolved with your recommendation!

2024-11-11 02:52 UTC, chromiumboy commented
Looks good, tested in game fine. Thanks for the fix

2024-11-11 02:53 UTC, chromiumboy approved these changes

2024-11-20 02:05 UTC, merged