Delay NukeOps round end by 10 seconds after the nuke explodes.
space-wizards/space-station-14 pull request #33072
Opened 2024-10-30 19:22 UTC by Callmore

Delays round end from when the nuke explodes during NukeOps by 10 seconds.

The round end in this case is when the window pops up after the nuke would usually explode.

This delay should only occur if the nuke explodes on the right station, on the wrong station it will just cut to the end of round like before.

Note that this PR does not actually add any checks to see if the nukies survived.

## Why / Balance

This allows for time for the nuke to actually destory the station, and potentionally kill the NukeOps if they stay near it. This would then allow for their win to be downgraded in future from a major to a minor if they are all dead, with an extra line on the end of round window stating they all died.

It also allows for the nuke to explode the station a little before everything ends and the window gets in the way.

## Technical details

Added an `Update` method to `NukeopsRuleSystem`, that will check to see if the round should end after the nuke explodes. I am not sure of a better way of doing this, or if this is the "correct" way. I've avoided using `Timer` since it has the issue of not being well tied to the game, and hard to cancel, leading to bugs.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: During NukeOps, the round will no longer end immeidately after the nuke explodes, and will instead be delayed by a short time.

2024-10-31 00:19 UTC, Cojoke-dot commented
> This allows for time for the nuke to actually destory the station, and potentionally kill the NukeOps if they stay near it. This would then allow for their win to be downgraded in future from a major to a minor if they are all dead, with an extra line on the end of round window stating they all died.

Aren't they meant to kill themselves on the nuke as a part of the mission? Why would they loose the major win for dying to it?

2024-10-31 00:39 UTC, EthanQix commented
> Aren't they meant to kill themselves on the nuke as a part of the mission? Why would they lose the major win for dying to it? As I understood it it was meant to be an elite agent suicide mission.

I don't think they need to suicide, just nuke the station.

As a side note, I think it would better to have a custom message when the nukie team *survives* the nuke, for an extra major victory ^^

2024-10-31 01:31 UTC, Sadie-silly commented
> > This allows for time for the nuke to actually destory the station, and potentionally kill the NukeOps if they stay near it. This would then allow for their win to be downgraded in future from a major to a minor if they are all dead, with an extra line on the end of round window stating they all died.
> 
> Aren't they meant to kill themselves on the nuke as a part of the mission? Why would they lose the major win for dying to it? As I understood it it was meant to be an elite agent suicide mission.

Doesn't the nukie intro literally state "Get out while the payload detonates"?

2024-10-31 12:55 UTC, SlamBamActionman commented
> Doesn't the nukie intro literally state "Get out while the payload detonates"?

Flavortext might say it, but to my understanding the Nukies should not need to worry about needing to survive the Nuke to declare a victory, gameplay-wise. Keeping survival as a purely player-driven optional goal is better and makes it a "nice to have" than making the Nukies have less of a victory just because they decided to stick with the Nuke and actually engage with the station instead of covering it in 3 layers of reinforced walls.

2024-10-31 22:25 UTC, deltanedas commented
shouldnt lose major but should say how many nukies lived on roundend and give a special text if they all lived

2024-11-04 10:24 UTC, Graded5 commented
Im fairly sure Nukies need to survive for a major in SS13. I dont see any issue for downgrading to a minor for dying to the nuke, it makes sense because why would the Syndicate tell perfectly capable operatives to just give up their life in the event they actually win.

However I do think if nukies need to escape there needs to be a 'point of no return' for the nuke countdown where it can no longer be disarmed. (We already kind of do with the very long disarm timer but a more official one accompanied by an announcement would allow newkies to know when to bail)

Also having Nukies need to live might make them actually not treat the nukie shuttle like a throw away hunk  of junk. Overall I think it wouldnt subtract anything and would be a good change.

2025-01-19 11:08 UTC, Callmore commented on Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
> +    public TimeSpan? NukeExplodedTime;
fuck i left this just like this for two months?

2025-01-19 19:06 UTC, Tayrtahn requested changes

2025-01-19 19:06 UTC, Tayrtahn commented on Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
> +    public TimeSpan? NukeExplodedTime;
The usual pattern is to save the final time on the component, so you'd want to store the explosion time plus the delay. You can then add autopause to the field too.

2025-01-20 09:09 UTC, Hrosts commented
> However I do think if nukies need to escape there needs to be a 'point of no return' for the nuke countdown where it can no longer be disarmed. (We already kind of do with the very long disarm timer but a more official one accompanied by an announcement would allow newkies to know when to bail)

This kinda ruins an opportunity for the crew to do a last-second defuse, which is extremely cool when it happens.

2025-04-19 12:51 UTC, MilonPL commented
Please address the review.

2025-04-22 23:13 UTC, MilonPL commented
I am going to be closing this PR as Stale. If you ever end up coming back to this, please open a new PR.

2025-04-22 23:13 UTC, closed without merging