move lathe recipes into packs (easier for forks and maintaining)
space-wizards/space-station-14 pull request #33095
Opened 2024-10-31 22:00 UTC by deltanedas

## About the PR
packs are shared between lathes to:
- dedupe things like emag recipes and ammofab which even had mistakes from their copy pasta
- make forks editing these much much simpler since you dont have to worry about it being in 4 different places
- if downstreams want to make department techfabs like engifab its much much much easier, just select the engi related packs and its done (assuming future prs dont add random shit to wrong packs :trollface:)
- avoid conflicts downstream by using parenting to have a single changed line, or add your own pack to a specific lathe also a single line. makes mainting forks recipes 100x easier
- because themed recipes are mostly in their own files there will be less conflicts between prs (unless they add to the same pack of course)

ingame changes are below

## Why / Balance
- emagged autolathe can print flash and batong for ease of implementation, gives traitors more options especially for kidnapping :trollface:
- ammofab can no longer print tranq shells, theyre a researched item and ammofab was otherwise purely roundstart ammo
- ammofab can now make wt550 and drozd mags to be consistent, balance wise you can just refill them from .35 auto boxes anyway
- secfab can now make chemical payloads, for emp bombs and such
- made tech disk terminal, node scanner, anomaly scanner roundstart recipes since theyre roundstart and in all sci lockers
- fixes some roundstart recipes like beakers being in dynamic in the protolathe instead of static (surgery tools pack is commented out since its just bloat atm)
- removed rollerbeds from autolathe, it doesnt make any sense to be there when the medfab has it.
  can readd as a rollerbeds pack for them to share if its desired

## Technical details
- made GetAvailableRecipes use a cached hashset for performance
- lathes without TechnologyDatabase can now have static emag recipes, changed order of a check

## Media
roundstart circuit printer
![09:55:03](https://github.com/user-attachments/assets/5cee8ae6-ffcf-4f1b-a460-48311670d91d)

roundstart protolathe, has sci tools and more chem stuff
![09:56:30](https://github.com/user-attachments/assets/573a42c7-6578-448f-a003-17648d20ae89)

autolathe is still random shit
![09:57:23](https://github.com/user-attachments/assets/b959efc7-d0c6-4f46-a242-0d44f4d3d04a)
and has batong :trollface:
![09:57:52](https://github.com/user-attachments/assets/de6c6be9-d863-48cb-9746-e2fa3f5c9a87)

valid uniform printer still prints centcomm and syndie clothes (which can now trivially be made normal recipes for a special centcomm or syndie printer prototype :trollface:)
![09:55:23](https://github.com/user-attachments/assets/3123c7ed-ff9f-4061-a05b-e1643ef90308)

i would show research but funny interaction debug assert trolling

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
LatheComponent and EmagLatheComponent static/dynamic recipes have been replaced with a list of pack ids.

if you are adding things to them instead of adding recipes to upstream packs make your own pack and either make an upstream pack inherit it, or add it to an upstream lathe's pack list

example below
```yml
# define a recipe pack
- type: latheRecipePack
  id: SecurityWeaponsFork
  recipes:
  - # list the forks gun recipes for the secfab/emagged protolathe here

# and either make it a parent of an upstream recipe pack so it gets added to whatever lathes it is used by
- type: latheRecipePack
  parent: SecurityWeaponsFork # Fork: add it to any usage of SecurityWeapons, this is futureproof
  id: SecurityWeapons
  ...

# or add it to 1 (or more) lathes
- type: Lathe
  dynamicRecipes:
  ...
  - SecurityWeapons
  - SecurityWeaponsFork # Fork: example to add the pack to a specific lathe
```

**Changelog**
ingame changes are too minor for cl

2024-11-15 03:51 UTC, SaphireLattice commented
Really think the roundstart/balance changes need to be split off from this. I love the technical details of the PR and would instantly approve it, but the fact that there's balancing changes make it a bit more difficult to review. That and having to go through the list sucks on its own already.

2024-11-15 11:56 UTC, deltanedas commented
some of the changes like for ammofab would mean a lot of duplication
prs already been waiting for ages another month to discuss the balance for these wont change anything

2025-01-23 17:11 UTC, sowelipililimute reviewed
some minor nits

2025-01-23 17:11 UTC, sowelipililimute commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +    #- SurgeryStatic # Disabled until surgery matters
these are already in the lathe pre-refactoring, i don't think these need to be commented out
```suggestion
    - SurgeryStatic
```

2025-01-30 08:18 UTC, deltanedas commented
dead chat xd

2025-01-30 08:25 UTC, ArtisticRoomba commented
bumping it in the review channel

2025-02-05 03:08 UTC, MilonPL requested changes
Code looks mostly good, minor nitpicks, will probably need to be updated after the emag refactor.

2025-02-05 03:08 UTC, MilonPL commented on Content.Server/Lathe/LatheSystem.cs
> +            AddRecipesFromPacks(args.Recipes, component.EmagStaticPacks);
Shouldn't emagging also update the UI so you don't have to reopen it?

2025-02-05 03:08 UTC, MilonPL commented on Content.Shared/Lathe/Prototypes/LatheRecipePackPrototype.cs
> +using Robust.Shared.Serialization;
Unused.

2025-02-05 03:08 UTC, MilonPL commented on Content.Shared/Lathe/SharedLatheSystem.cs
> +            var pack = _proto.Index<LatheRecipePackPrototype>(id);
Don't need to specify the type.

2025-02-05 07:44 UTC, deltanedas commented on Content.Server/Lathe/LatheSystem.cs
> +            AddRecipesFromPacks(args.Recipes, component.EmagStaticPacks);
ui shitcode is in server not shared and not relevant to this pr

2025-02-07 17:47 UTC, MilonPL approved these changes

2025-02-07 18:22 UTC, Simyon264 approved these changes
sloggers (this merge is a bribe for you to upstream traitor rep /s)

2025-02-07 18:22 UTC, merged

2025-02-07 18:23 UTC, deltanedas commented
erm the design doc isnt merged so cant do that :)

2025-02-07 18:25 UTC, ArtisticRoomba commented
What are ddocs again (godo)

2025-02-08 13:26 UTC, deltanedas commented
you had all of 3 months to read the description...