Added Popup for the Ligneous plant mutation when using hands.
space-wizards/space-station-14 pull request #33136
Opened 2024-11-03 09:11 UTC by Tr1bute

## About the PR

Added a popup when attempting to harvest a plant with the ligneous mutation with bare hands.

## Why / Balance

There was some confusion for players with the Ligneous mutation which makes the plant harvest-able only with sharp tools. Adding a popup with the message "The plant is too tough." to give them a hint to use something other than just their hands.

I decided to only put the message when attempting to harvest using hands, as the intent is clear that the player just wanted to harvest, but wasn't able to. Using any other tools like a crowbar or a screwdriver will not trigger the popup.

## Technical details

Just one line of code and a text entry that creates a popup when the player attempts to harvest a plant with the Ligneous plant mutation, and they aren't a using a tool with the SharpComponent.

## Media

![image](https://github.com/user-attachments/assets/61f0f7e2-9b92-47e8-9d02-9e3bb8c6c579)

https://github.com/user-attachments/assets/245cc0b6-6d25-4982-9f71-4a8f1077c4c5

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: A popup now appears when attempting to harvest mutated plants that require sharp tools.

2024-11-03 10:28 UTC, slarticodefast approved these changes
Very good QOL addtion. No idea why that wasn't a thing yet.
Thank you for your contribution!

2024-11-03 11:29 UTC, SlamBamActionman requested changes

2024-11-03 11:29 UTC, SlamBamActionman commented on Resources/Locale/en-US/botany/components/plant-holder-component.ftl
> +plant-holder-component-ligneous-cant-harvest-message = The plant is too tough.
I think the PR is great QOL, but I would probably make the description hint just a bit more towards the solution.
```suggestion
plant-holder-component-ligneous-cant-harvest-message = The plant is too tough to harvest with your bare hands.
```

2024-11-04 00:56 UTC, SlamBamActionman approved these changes

2024-11-04 00:56 UTC, merged