make kill objectives only target players with jobs
space-wizards/space-station-14 pull request #33135
Opened 2024-11-03 09:09 UTC by deltanedas

## About the PR
title

## Why / Balance
so you dont get objective to kill ert or some admin testing area urist or a nukie

## Technical details
- added MindHasMatchingRole to SharedRoleSystem for looking for roles matching a whitelist
- added RoleWhitelist and RoleBlacklist fields to PickRandomPersonComponent
- made kill objective have a JobRole whitelist

## Media
![image](https://c.tenor.com/1ybdLgfamD0AAAAd/tenor.gif)

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- fix: Fixed non-crew being picked for traitor kill objectives.

2024-11-03 10:38 UTC, Errant-4 commented
ERT, CBURN and Death Squad are now jobs, and will still be targeted

2024-11-03 10:56 UTC, slarticodefast commented
Rarely getting a kill objective for nukies, ninjas, ert and so on is totally a feature in my opinion.

2024-11-03 13:04 UTC, deltanedas commented
> ERT, CBURN and Death Squad are now jobs, and will probably still be targeted

would checking the job can be readied up for work for these edge cases?

2024-11-03 16:01 UTC, Errant-4 commented
> > ERT, CBURN and Death Squad are now jobs, and will probably still be targeted
> 
> would checking the job can be readied up for work for these edge cases?

Not sure from the top of my head how you would do that/what that would entail

2024-11-03 19:02 UTC, NoElkaTheGod commented
> ERT, CBURN and Death Squad are now jobs, and will probably still be targeted

Well, at least they are on station for some time, so it is possible to kill them (although pretty damn hard). Still better than having to kill a ninja, which can stun with one click and outrun anything.

2024-11-04 17:49 UTC, IProduceWidgets commented
Maybe pull from the crew manifest list?

2024-11-04 18:17 UTC, deltanedas commented
SetPreference is what im going to use but maybe theres some weird edge cases from that

2025-01-25 19:56 UTC, deltanedas commented
> high priority
> nothing after 3 months

2025-01-25 20:16 UTC, ArtisticRoomba commented
I bumped it in the review channel

2025-01-25 20:55 UTC, beck-thompson requested changes
pro

2025-01-25 20:55 UTC, beck-thompson commented on Content.Server/Objectives/Components/PickRandomPersonComponent.cs
> +    /// If non-null a target must have a job with SetPreference set to true.
Can't be null change it to true or something

2025-01-26 00:17 UTC, slarticodefast commented on Content.Server/Objectives/Systems/KillPersonConditionSystem.cs
> +                _proto.Index(jobId).SetPreference));
Wouldn't this mean if you get a custom job assigned by HOP you would no longer be an eligible kill target?

2025-01-26 00:18 UTC, deltanedas commented on Content.Server/Objectives/Systems/KillPersonConditionSystem.cs
> +                _proto.Index(jobId).SetPreference));
id cards have nothing to do with mind roles

2025-03-13 08:30 UTC, closed without merging