Cigarette pack can only store cigarette now
space-wizards/space-station-14 pull request #33148
Opened 2024-11-03 21:55 UTC by Vonsant

## About the PR
Made cigarette packs only able to store cigarette.

## Why / Balance

The same as https://github.com/space-wizards/space-station-14/pull/33074
Cigarette packs has 2 slots, each one can store a bottle.

## Technical details

## Media

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-11-03 22:45 UTC, thebadman4662 commented
Well, at least match boxes got spared.

2024-11-04 00:21 UTC, keronshb requested changes
Probably not going to merge this. Leaving my comments here.
Cig packs, like pill bottles, are meant to store smaller items.
Cig packs are, by design, to also store:
lighters, matches, bullets, the disk, money, and like-sized things.

2024-11-04 08:41 UTC, Golinth commented
NOOO I hate this! I store my dead mice in cigarette packages, and offer them as smokes to my fellow lizards. Wouldn’t be able to do that with this change

2024-11-04 08:57 UTC, thebadman4662 commented
> NOOO I hate this! I store my dead mice in cigarette packages, and offer them as smokes to my fellow lizards. Wouldn’t be able to do that with this change

Those damn IEM haters. 💢

2025-04-15 01:31 UTC, beck-thompson commented
Thanks for the pr! The vote concluded and we decided to close this pr, mainly because adding whitelists isn't fun and not super inventive - they should only be used when extremely necessary!

2025-04-15 01:31 UTC, closed without merging