Adds gorilla gauntlet storage sprite and updates hit sound
space-wizards/space-station-14 pull request #33167
Opened 2024-11-04 21:01 UTC by RiceMar1244

## About the PR

Adds an old sprite I made for the gorilla gauntlet when it was first added as the storage sprite since we didnt use it for the icon. Also, I replace the gauntlet's hit sound with the same intense blast that the crusher uses when hitting a marked target.

## Why / Balance

I wanna get more storage sprites in the game with better fits for their inventory footprints. Also, while im touching up the gauntlet's presentation, I wanted to give it a beefy punch sound. It previously used a weak tapping sound.

## Technical details

## Media

![storage gauntlet](https://github.com/user-attachments/assets/94072928-29a9-44f2-90b5-6a4e10f2f976)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

No CL because of minor visual and audio changes.

2024-11-06 07:25 UTC, TheShuEd approved these changes

2024-11-09 06:04 UTC, UbaserB requested changes
I have a few issues with the sprite. The thumb feels a little bit too low, the pink stripes are a little bit too thick (should probably be 1 pixel for consistency?), there are missing outlines in a couple of places (more noticeably the "back" of the sprite), and the part where the glove is raised upwards at the back should be far less jarring.

2024-11-09 09:39 UTC, SpaceRox1244 commented
I made the striping on the gauntlet's assets more consistent with eachother. As the gauntlet's original designer, I think modifying the icon sprite to have thicker stripes brings it more in line with the other two major assets.

2024-11-12 23:42 UTC, UbaserB approved these changes
I guess the sprite's fine.

2024-11-15 22:48 UTC, merged