contraband system for reagents
space-wizards/space-station-14 pull request #33184
Opened 2024-11-05 20:19 UTC by Ian321

## About the PR

This PR adds the ability to classify reagents and their contraband status with the help of forensic pads.

Fixes #31383 
Fixes #32218

(there where more issues, but i can't find them)

## Why / Balance

It was previously not possible to mark a reagent as contraband.

## Technical details

- Modified the ForensicPadSystem to "scan" drainable/drawable containers (puddles, beakers, syringes, ...).
- Added a new datafield "Contraband" to reagents. (I would of loved to re-use the other system, but reagents can't have components.)
- Expanded the guidebook entry for forensics.
- Expanded the guidebook for chemicals.

## Media

https://github.com/user-attachments/assets/76ef7cd5-b2d7-4d18-ad2e-8a531c90f433

https://github.com/user-attachments/assets/3dbaa561-bd72-4fb4-af01-8a579980355d

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None.

**Changelog**

:cl:
- add: Forensic pads can now also be used to identify and classify chemicals.
- add: Chemical pads can be used to identify chemicals.
ADMIN:
- add: Chemicals can now be contraband.

2024-11-05 20:42 UTC, Ian321 commented
Could in theory also encode the "GrandTheft" severity. Could make for an interesting objective: "Steal 10u of liquid youth from the command bar/vault.".

2024-11-05 20:57 UTC, YotaXP commented
Not in the scope of this PR, but perhaps there should be a new contraband category for prescription drugs that doctors are allowed to grant permission to possess.

2024-11-06 05:34 UTC, Djungelskog2 commented
holy guacamole a reason to use forensic pads

2024-11-07 15:29 UTC, slarticodefast requested changes
Very useful feature in my opinion. I found a few nitpicks that need to be corrected. I will check with the other maintainers and admins if this implementation is a good approach since the contraband system is quite connected to our server rules.

2024-11-07 15:29 UTC, slarticodefast commented on Content.Server/Forensics/Systems/ForensicPadSystem.cs
>          [Dependency] private readonly MetaDataSystem _metaData = default!;
```suggestion
```
remove this unused dependency while you are at it

2024-11-07 16:38 UTC, Ian321 commented on Content.Server/Forensics/Systems/ForensicPadSystem.cs
> +                            _ => null
Should I expand the existing `ContrabandSeverityPrototype` with a field named `color`? Should the strings in `contraband-severity.ftl` be modified to reused that new field? Should I change the color in the text to (example: cyan) for restricted items (like I did for reagents)?

2024-11-07 17:29 UTC, slarticodefast commented on Content.Server/Forensics/Systems/ForensicPadSystem.cs
> +                            _ => null
> Should I expand the existing ContrabandSeverityPrototype with a field named color? Should the strings in contraband-severity.ftl be modified to reused that new field?

That sounds like a good approach to me. Best keep the colors the current severity prototypes use (yellow, red, crimson) and use them for the forensic pad as well for consistency.

2024-11-07 18:38 UTC, Ian321 commented
The failed test `DeleteAllThenGhost` is unrelated and passed on my machine.

2024-11-21 16:12 UTC, Ian321 commented
Why the hell is there a conflict? Nothing changed in `contraband-severity.ftl`.

2024-11-23 16:09 UTC, Ian321 commented
I'm starting to have some mixed feeling about this PR after having played some more botany and getting mutations that added would-be-contraband reagents multiple time. For example: Should I have to toss my ambrosia-dues, just because it also contains Stimulants/Hyperzine?

I'm assuming that's also why its still under maintainer discussion. Maybe this needs #33385 and a general free-pass for botany and chem?

2024-11-23 16:32 UTC, slarticodefast commented
> I'm assuming that's also why its still under maintainer discussion. Maybe this needs https://github.com/space-wizards/space-station-14/pull/33385 and/or a general free-pass for botany and chem?

Yeah, that's one of the points, but the discussion has stalled a little, I'll give it a bump. Some points we got so far:
- Lead should likely not be contraband, even if it is a strong poison and only available for nukies, since it is also a common material in real life and it being prohibited does not really make much sense. Long term a lot of chemicals will have to be rebalanced anyways, but probably after newmed and the chem refactor.
- Like you mentioned, a lot of discussion will be needed for other reagents, for example uranium, mutagen, plasma and so on. They all can be dangerous and could be considered contraband, but would need to be classified if that is something we want to have for reagents.
- In combination with the linked PR some reagents might only be allowed for certain jobs.

In any case, I think having the functionality for this in the game should be a good thing, no matter the exact classifications we come up with. For the start we can stick to the obvious highly prohibitied traitor only reagents that are syndicate contraband and maybe add minor categries later.

I will give the PR another review when I find the time.

2024-11-25 13:40 UTC, Ian321 commented
@slarticodefast I have a suggestion:

1. i'll wait for #33385
2. rebase
3. add fields to specify allowed departments and jobs
4. remove the fields already assigned (so no reagent is contraband)

This way we could merge this and have another (multiple?) PR decide what is considered contraband.

2024-11-25 13:45 UTC, slarticodefast commented
Sounds like a good plan to me 👍

2025-01-15 06:15 UTC, IProduceWidgets commented
I think this should be its own component. It doesn't really make any sense to tie it to fingerprinting and DNA at all.

2025-01-21 19:55 UTC, Ian321 commented
now waiting on #34559 to continue

2025-09-10 13:21 UTC, slarticodefast commented
I merged #37113 which add the same feature, but has a nicer implementation.
I'll keep this PR open in case you still want to add the forensics pad feature.
Adjust the PR to the other PR if you do.

2025-09-10 15:27 UTC, closed without merging