Make button frames constructable and destructible
space-wizards/space-station-14 pull request #33195
Opened 2024-11-06 12:52 UTC by Boolean-Buckeye

## About the PR

* Make button frames constructable and deconstructable
* Make button frames desctuctible

## Why / Balance

Some people on discord were complaining that button frames were invincible and that it was annoying

## Technical details

* Add construction graph for button frames
* Add button frames to construction menu
* Make button frames desctructible

## Requirements

- [ x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
 - add: Button Frames can be constructed, deconstructed, and destroyed

2024-11-06 13:30 UTC, SlamBamActionman requested changes
Great PR conceptually, just needs to have the names made lowercase to be merged. Ideally they wouldn't be separate construction graphs and instead be part of some sort of painting system, but since we don't have one that fits this works well for now.

2024-11-06 13:30 UTC, SlamBamActionman commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +  name: Gray Button Frame
Should use lowercase for construction names

2024-11-06 13:30 UTC, SlamBamActionman commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +  name: Caution Button Frame
Ditto

2024-11-06 13:30 UTC, SlamBamActionman commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +  name: CautionSecurity Button Frame
Ditto (Also maybe just "security button frame" is enough)

2024-11-06 13:30 UTC, SlamBamActionman commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +  name: Exit Button Frame
Ditto

2024-11-06 13:30 UTC, SlamBamActionman commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +  name: Janitor Button Frame
Ditto

2025-03-21 09:11 UTC, TheShuEd commented
This PR has been in “Awaiting changes” status for over 3 months now without any visible updates, so I'm closing it as derelict. If you nevertheless plan to continue, please comment it and the PR will be reopened.

If you need help, you can ask questions in discord or in this PR

2025-03-21 09:11 UTC, closed without merging