Ethereal Jaunt Spell for Wizard & Jaunt ECS
space-wizards/space-station-14 pull request #33201
Opened 2024-11-07 01:49 UTC by keronshb

## About the PR

Added an Ethereal Jaunt Spell for Wizard and a Jaunt ECS to go with it.

Jaunt, on the backend, is just polymorph. The user gets put into an invisible ghost like body for very few seconds so they can make an escape. They can even go through walls and walk on space! Just be careful since it has a long cooldown and a very short duration, even with upgrades!

Polymorph was also given support to play a sound when morphing and reverting.

## Why / Balance

It's a classic Wizard spell from SS13. Like all Wizard spells it's powerful, and allows the wizard to make a hasty escape as needed. Giving it more movement tech other than just teleporting or turning into a rod. You could consider this a non-lethal version of a rod.

## Technical details

Only code changed was in Polymorph.
Polymorph configs now have SoundSpecifiers for polymorphing and reverting.
If not null, we play on polymorph and/or play on revert.

## Media

https://github.com/user-attachments/assets/780403ec-2f76-4d9a-a46f-5ef71f533516

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Jaunt Component and Jaunt System added to Content.Shared
Polymorph Prototype = added PolymorphSound and ExitPolymorphSound fields.
Polymorph System = Adds a check if Polymorph Sound is null for Polymorph method. Adds same check for Exit Polymorph Sound to Revert method. Uses Audio Play PVS.

**Changelog**

:cl:
- add: Added Ethereal Jaunt! A Wizard Spell that turns you invisible and into a ghost-like creature for escaping!

2024-11-07 01:57 UTC, slarticodefast commented
Very cool spell. Maybe give the player a ghostly sprite that is invisible to non-ghosts, so you have better visual feedback of your current location and ghosts can observe where you are going?

2024-11-07 03:46 UTC, keronshb commented
> Very cool spell. Maybe give the player a ghostly sprite that is invisible to non-ghosts, so you have better visual feedback of your current location and ghosts can observe where you are going?

Ideally an effect would play when polymorphing as well. Might be doing that next in another PR. But I could see the benefit of just turning them into a blue ghost or something.

2024-11-07 04:17 UTC, Ilya246 commented
doesn't need a CL i think

2024-11-07 04:32 UTC, keronshb commented
> doesn't need a CL i think

It does, all of it is adding up to Wizard. Even though it's not player facing now, it will be eventually.

2024-11-07 04:37 UTC, Ilya246 commented
> > doesn't need a CL i think
> 
> It does, all of it is adding up to Wizard. Even though it's not player facing now, it will be eventually.

so it's essentially a CL for development progress?

2024-11-07 05:25 UTC, keronshb commented
> > > doesn't need a CL i think
> > 
> > 
> > It does, all of it is adding up to Wizard. Even though it's not player facing now, it will be eventually.
> 
> so it's essentially a CL for development progress?

Sorta. Admins are still free to spawn the Grimoire. It's not like it's just a pure code change, which players wouldn't need to know about.

2024-11-07 17:45 UTC, Everturning commented
Is there support for placing it in the action bar?

2024-11-07 18:04 UTC, keronshb commented
> > > Is there support for placing it in the action bar?
> > 
> > 
> > What do you mean?
> 
> oh wait I looked at the video closer lol. I thought it was a book.
> 
> Mainly i'm thinking about nightmares. while we don't really have support for darkness and light level mechanics afaik, jaunts are a big step forward to getting nightmares in the game

Yep. That may either require the action system rework. Which would include an optional requirements whitelist/blacklist for an action to require some sort of entity to use - like blood or darkness. Or it might be doable in the jaunt system itself in the future.

2024-11-08 00:30 UTC, keronshb commented
> Very cool spell. Maybe give the player a ghostly sprite that is invisible to non-ghosts, so you have better visual feedback of your current location and ghosts can observe where you are going?

https://github.com/user-attachments/assets/791ee860-fc5e-4a2b-9a31-51477ed57ef6

2024-11-08 10:40 UTC, Graded5 commented
The UI completely disappearing feels a bit weird, but I'm assuming that'd be a hard fix. Overall, I like it!

2024-11-10 03:31 UTC, keronshb commented
> The UI completely disappearing feels a bit weird, but I'm assuming that'd be a hard fix. Overall, I like it!

Mostly done on purpose at this point. It's polymorphing into a body that doesn't have an inventory system, etc (inventory transfers so we just don't lose everything). So items and actions can't be used in jaunt. Ideally at some point it would be nice to have like a "disable hud" component or something which would just disable all action and hud interaction.

2024-11-12 22:09 UTC, slarticodefast requested changes
The in-game test went well, but I found some minor things that need a cleanup.
One suggestion I would have is maybe to add a "Urist McHands vanished into thin air!" popup when jaunting so it does seem like a more intended action to viewers instead of them simply disappearing, which could be interpreted as a bug or lag.

2024-11-12 22:09 UTC, slarticodefast commented on Resources/Prototypes/Entities/Mobs/Player/jaunt_mobs.yml
> +    - HideContextMenu
This will also mean admins won't be able to interact with it via right clicking.
Since you can spawn the jaunt as a mob, I would maybe remove this.

2024-11-12 23:21 UTC, keronshb commented on Resources/Maps/meta.yml
> +          - 0
yeah idk how it got here, probably when i merged master

2024-11-13 21:20 UTC, slarticodefast requested changes

2024-11-13 21:20 UTC, slarticodefast commented on Content.Shared/Jaunt/JauntComponent.cs
> +//  Can be used in-place of giving a jaunt-action directly
```suggestion
/// <summary>
///     Used to control various aspects of a Jaunt.
///     Can be used in place of giving a jaunt-action directly.
/// </summary>
```

2024-11-13 21:20 UTC, slarticodefast commented on Content.Shared/Jaunt/JauntComponent.cs
> +    // Which Jaunt Action the component should grant
```suggestion
    /// <summary>
    ///     Which Jaunt Action the component should grant.
    /// </summary>
```

2024-11-13 21:20 UTC, slarticodefast commented on Content.Shared/Jaunt/JauntComponent.cs
> +    // The jaunt action itself
```suggestion
    /// <summary>
    ///     The jaunt action itself.
    /// </summary>
```

2024-11-13 21:25 UTC, slarticodefast approved these changes
Did some minor cleanup with the missing summary tags.
Code looks good and in-game test went well.
If you get art director approval for the sprites this is good to merge!

2024-11-13 22:46 UTC, keronshb commented
> Did some minor cleanup with the missing summary tags. Code looks good and in-game test went well. If you get art director approval for the sprites this is good to merge!

For the popup, I think it's a good idea but that's also the idea behind the sound effect. So I wanna see how people find that, and if too many think it might be unintended then we'll add one.

2024-11-13 23:34 UTC, Flareguy approved these changes

2024-11-13 23:36 UTC, merged