Delete HOS headset from warden's locker
space-wizards/space-station-14 pull request #33234
Opened 2024-11-09 19:47 UTC by kosticia

## About the PR
Removes Hos headset from warden locker

## Why / Balance
Warden isn't command staff 

## Technical details
Watch the code

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- delete: Removed HOS headset from warden locker

2024-11-10 11:37 UTC, Emisse commented
looks good just need you to update the copyright field of the headsets meta.json at the top

2024-11-10 11:37 UTC, Emisse approved these changes

2024-11-10 12:11 UTC, kosticia commented
> looks good just need you to update the copyright field of the headsets meta.json at the top

Done

2024-11-10 16:25 UTC, slarticodefast requested changes

2024-11-10 16:25 UTC, slarticodefast commented on Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
> +  parent: [ClothingHeadset, BaseCommandContraband]
```suggestion
  parent: [ClothingHeadset, BaseRestrictedContraband]
```
The warden is not command, so it being command restriced shows up as contraband for them
![grafik](https://github.com/user-attachments/assets/eef4956a-47a2-42e1-b589-26332a8bee13)
For the same reason they should probably not have a command encryption key either.

2024-11-10 16:25 UTC, slarticodefast commented on Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
> +  parent: [ClothingHeadsetAlt, BaseCommandContraband]
```suggestion
  parent: [ClothingHeadsetAlt, BaseRestrictedContraband]
```

2024-11-10 18:04 UTC, slarticodefast commented
Thanks for fixing it. I opened a maintainer discussion about if the warden is supposed to have a command encryption key. I will come back to you once we have a conclusion.

2024-11-23 15:39 UTC, slarticodefast commented
Hey, we had a maintainer vote and came to the conclusion that the warden should not have a command encryption key since they are not command staff themselves. As such they no longer need a special headset, but can be given a normal security headset instead. Could you adjust your PR for that?

2024-11-24 11:43 UTC, kosticia commented
> Hey, we had a maintainer vote and came to the conclusion that the warden should not have a command encryption key since they are not command staff themselves. As such they no longer need a special headset, but can be given a normal security headset instead. Could you adjust your PR for that?

Done.

2024-11-24 11:44 UTC, kosticia commented
All these likes... :trollface:

2024-11-25 00:46 UTC, slarticodefast approved these changes
Yeah, sorry that your sprite did not make it.
But the warden should not have a command headset in the first place.
Anyways, thank you for your contribution.

2024-11-25 00:46 UTC, merged