Add Reagent gold and silver solification with frost oil
space-wizards/space-station-14 pull request #33239
Opened 2024-11-10 04:29 UTC by Minty642

## About the PR

Add 2 reagent recipe to create gold and silver with frost oil

## Why / Balance

this will allow botany to make a solid gold from golden apple and chilly plant. requested by RedBookcase(Buck Clark)

## Technical details

yml changes

## Media

## Requirements

- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] it does not require an ingame showcase.

## Breaking changes

**Changelog**

🆑 
- add: Added Gold and Silver Solidification, just mix with frost oil.

2024-11-10 08:46 UTC, NoElkaTheGod commented
Finally, a proper use for chilly (and golden apples too)

2024-11-10 14:03 UTC, thebadman4662 commented
Finally cargo can buy gold and iron for cheap and salvagets not mining won't matter. ✊

2024-11-15 17:05 UTC, slarticodefast commented
Cool addition, it was always weird how botany was able to obtain gold and silver, but not use it in any way since it is in reagent form. I looked at the [tg wiki](https://tgstation13.org/wiki/Guide_to_chemistry)https://tgstation13.org/wiki/Guide_to_chemistry) and it looks like they got similar solification recipes for plasma and uranium as well. Balance-wise I think the amount of frost oil needed can even be reduced a little. I'm thinking of 10u of gold/silver/plasma/uranium and 5u of frost oil. But I'm open for feedback on that.

2024-11-15 18:10 UTC, RedBookcase commented
_Oh shit I forgot to post my comment-_

Nice, glad to see this PR out there. Looking forwards to seeing Botany able to help Science, which afaik is a department they rarely interact with currently outside of begging for a chemmaster.

2024-12-11 15:34 UTC, slarticodefast commented
Are you coming back to this?

2024-12-12 01:02 UTC, Minty642 commented
> Are you coming back to this?

yeah soon, sorry i been neglecting this one, been busy with other stuff. give me 2 day to take a look at this one

2024-12-12 01:42 UTC, slarticodefast commented
All good, just wanted to check if this PR is still active.

2024-12-14 07:09 UTC, Minty642 commented
> Cool addition, it was always weird how botany was able to obtain gold and silver, but not use it in any way since it is in reagent form. I looked at the [tg wiki](https://tgstation13.org/wiki/Guide_to_chemistry) and it looks like they got similar solification recipes for plasma and uranium as well. Balance-wise I think the amount of frost oil needed can even be reduced a little. I'm thinking of 10u of gold/silver/plasma/uranium and 5u of frost oil. But I'm open for feedback on that.

so, after some calculation. i choose not to make the frost recipe to 5u. cargo could use it for profit investment, this is how. 
Chemical Crate (D), contains 200u of gold reagent= 750 spesos
Condiment restock crate, contains 5 coldsauce packet equals to 50u of coldsauce reagent, 300 spesos x 4 = 1200 spesos
total investment = 1200 + 750 = 1950 spesos

200 Gold reagent = 20 gold piece
1 Gold = 75 spesos
20 Golds = 1500 spesos

Net worth : 1500 - 1950 = -450 spesos. money loss on investment

but if coldsauce reagent reduced to 5u, then investment for condiment stuff is cut by half, equals to 600 spesos.
therefore, total investment only 600 + 750 = 1350.
Net worth : 1500 - 1350 = 150 spesos profit on investment.

2024-12-14 10:21 UTC, NoElkaTheGod commented
> but if coldsauce reagent reduced to 5u, then investment for condiment stuff is cut by half, equals to 600 spesos. therefore, total investment only 600 + 750 = 1350. Net worth : 1500 - 1350 = 150 spesos profit on investment.

Doing all of that for just 150 spesos is kinda not really worth it?...

2024-12-14 18:06 UTC, Thatonestomf commented
And not cargo tech is going to sell the gold anyway for that little, they are just going to give it to sci since its more valuable that way
but I'm not opposed to either

2025-01-06 23:34 UTC, slarticodefast requested changes

2025-01-06 23:34 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Reactions/fun.yml
> +      entity: IngotGold1
```suggestion
  effects:
  - !type:CreateEntityReactionEffect
    entity: IngotGold1
```

2025-01-06 23:34 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Reactions/fun.yml
> +      entity: IngotSilver1
```suggestion
  effects:
  - !type:CreateEntityReactionEffect
    entity: IngotSilver1
```

2025-01-06 23:38 UTC, slarticodefast approved these changes
The math makes sense, we should not introduce any more cargo exploits.
There should probably also be an integration test for that.
I made a small change to fix the intendation according to our conventions.
I think the recipe is a good addition, but maybe we will have to remove gold and silver from the chemistry crate in the future if cargo can simply buy gold and silver that way. On the other hand it is probably to expensive the be worth it outside of an emergency.
Thank you for your contribution!

2025-01-15 23:40 UTC, slarticodefast commented
Looks like the other PR linked above solves the potential cargo exploit problem. If we merge that first we can reduce the amount needed for the reaction to 5u after all.

2025-01-15 23:46 UTC, Minty642 commented
> Looks like the other PR linked above solves the potential cargo exploit problem. If we merge that first we can reduce the amount needed for the reaction to 5u after all.

alright sounds good, give me a day to change it

2025-01-18 14:31 UTC, slarticodefast approved these changes
Looks good to me.
To be merged after https://github.com/space-wizards/space-station-14/pull/34458

2025-02-01 15:24 UTC, Boaz1111 requested changes
Frost

2025-02-01 15:24 UTC, Boaz1111 commented on Resources/Prototypes/Recipes/Reactions/fun.yml
> +    Frostoil:
Needs to be changed to FrostOil, #34458 changed the ID

2025-02-01 15:24 UTC, Boaz1111 commented on Resources/Prototypes/Recipes/Reactions/fun.yml
> +    Frostoil:
same here

2025-02-01 21:18 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Reactions/fun.yml
> +    Frostoil:
```suggestion
    FrostOil:
```
Time for a web edit :godo:

2025-02-01 21:18 UTC, slarticodefast commented on Resources/Prototypes/Recipes/Reactions/fun.yml
> +    Frostoil:
```suggestion
    FrostOil:
```

2025-02-01 21:20 UTC, slarticodefast commented
@Boaz1111 should be good to merge.

2025-02-02 00:59 UTC, Boaz1111 approved these changes

2025-02-02 01:00 UTC, Boaz1111 commented
Thank you for the PR!

2025-02-02 01:00 UTC, merged