Prevent pulling when teleporting
space-wizards/space-station-14 pull request #33252
Opened 2024-11-11 06:39 UTC by thetolbean

## About the PR
If a user attempts to teleport, either through the space ninja's katana or a scram implant, they will drop said item before teleporting

## Why / Balance
Fix #33243 and prevent teleports from being extended to pulled objects

## Technical details
Adds a check to both `OnScramImplant` & `OnDash` that check if the user is pulling an item, and if so, attempt to cancel the pull before the teleport

## Media

https://github.com/user-attachments/assets/ed8b0c71-0beb-4b37-abca-9c88b9c691e4

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: Teleporting or dashing now causes you to stop pulling objects.

2024-11-11 13:16 UTC, slarticodefast approved these changes

2024-11-11 13:17 UTC, slarticodefast commented
Tested and works as intended, thanks for the PR!

> I did say the issue was present with scram implants, but I also heard it was funny to scram into space with a secoff that was dragging you earlier, so it might be worth leaving that in considering its unpredictability

While I agree with you that it would be funnier to keep, this has too many potential edge cases where it could cause bugs with pulling.

2024-11-11 13:23 UTC, MilenVolf commented
Does it also prevent pulling if user or targes is being teleported? For example, by bluespace anomaly

2024-11-11 13:43 UTC, slarticodefast commented
> Does it also prevent pulling if user or target is being teleported? For example, by bluespace anomaly

The bluespace anomaly is a separate system, but it likely has the same problem.

2024-11-11 14:39 UTC, thetolbean commented
> Does it also prevent pulling if user or target is being teleported? For example, by bluespace anomaly

Yes, as Slarti said the bluespace system is separate
With being pulled however, the scram implant already had a check in place to escape from being pulled. The dash does not, so I will be adding that shortly

2024-11-11 17:29 UTC, NoElkaTheGod commented
It was kinda funny though. But removing this is probably for the better.

2024-11-11 17:35 UTC, slarticodefast requested changes

2024-11-11 17:35 UTC, slarticodefast commented on Content.Shared/Ninja/Systems/DashAbilitySystem.cs
> +        if (TryComp(user, out PullerComponent? puller) && TryComp(puller.Pulling, out PullableComponent? pullable))
```suggestion
        if (TryComp<PullerComponent>(user, out var puller) && TryComp<PullableComponent>(puller.Pulling, out var pullable))
```
maybe make it a little more consistent for better readability

2024-11-11 17:35 UTC, slarticodefast commented on Content.Server/Implants/SubdermalImplantSystem.cs
> +        if (TryComp(ent, out PullerComponent? puller) && TryComp(puller.Pulling, out PullableComponent? pullable))
```suggestion
        if (TryComp<PullerComponent>(ent, out var puller) && TryComp<PullableComponent>(puller.Pulling, out var pullable))
```

2024-11-11 20:04 UTC, slarticodefast approved these changes

2024-11-11 20:04 UTC, slarticodefast commented
Thanks!

2024-11-11 20:04 UTC, thetolbean commented
And I did perform testing on the bluespace scenarios, both the linked lockers and bluespace anom.
Both cancel your pulls if you are dragging something.
The items come along in the locker if they are also closed in, but you are not pulling them when you leave the other locker

2024-11-12 00:26 UTC, thetolbean commented
> It was kinda funny though. But removing this is probably for the better.

Yeah, I agree. There's nothing like stealing an entire computer (or person) in the blink of an eye
Although it definitely needs to be removed for balancing

2024-11-12 05:28 UTC, chromiumboy commented
My thoughts are that the pulling system should listen for when a puller's transform get updated, and if the displacement is outside a certain tolerance, the pull is canceled. That way all teleport cases would be covered

2024-12-16 14:09 UTC, merged