Fixed issue where entities in containers would be deleted when the construction process advances to another node
space-wizards/space-station-14 pull request #33267
Opened 2024-11-12 01:43 UTC by kbarkevich

## About the PR
The `Content.Server/Construction/ConstructionSystem.Graph.cs` file was changed to allow entities inside containers to persist during construction as the entity is changed from node to node.

## Why / Balance
The development docs (specifically https://docs.spacestation14.com/en/space-station-14/core-tech/construction.html#containers) state that "When the entity changes due to reaching a node with a different entity prototype, all those containers *will be transferred to the new entity*. " I discovered this bug when creating a new entity that involved a multi-node/multi-entity construction process, and also necessitated that the specific entities stored within the construct are available to be edited and retrieved in order to function. I found that when the construction involves more than one step, the entities stored within the containers are deleted/not carried over to the next entity.

## Technical details
Within the previously mentioned file, the `ChangeEntity` method was altered. This alteration is within the "Container transferring" section of the method. The alteration iterates over all containers in the previous construction entity and ensures that they are transferred along to the next entity.

## Media
N/A, unless requested

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
N/A

2024-11-13 01:00 UTC, cohanna commented
oh hey will this fix #32590

2024-11-13 07:44 UTC, kbarkevich commented
> oh hey will this fix #32590

This does in fact fix #32590 

(Before fix) at cog's externally facing sec intercom: 
![image](https://github.com/user-attachments/assets/6d071b2a-a7c5-48a6-b47e-cd87dbd427e2)

(After fix) at cog's externally facing sec intercom: 
![image](https://github.com/user-attachments/assets/d7c7eb91-c041-41cb-85f0-99f52e70b487)

2024-12-30 21:12 UTC, cohanna commented
i would request a review from a maintainer 
(I want to steal sec keys again :godo:)

2025-01-29 01:37 UTC, beck-thompson requested changes

2025-01-29 01:37 UTC, beck-thompson commented on Content.Server/Construction/ConstructionSystem.Graph.cs
> +				var oldContainerManager = EntityManager.EnsureComponent<ContainerManagerComponent>(uid);
OK this looks like it'll work! However, I think you could probably combine it with the loop below it! Let me know if it works or if I'm wrong 🫡

2025-01-31 06:35 UTC, beck-thompson requested changes
Also ensure you remove all situations where the electronic boards get duplicated. You might want to wait on that though until you get someone else to look at this. I'm still not fully convinced this is the correct solution :thinking:

2025-02-06 00:26 UTC, Booblesnoot42 commented
To make sure I understand correctly: this pr changes the way the construction component transfers containers from only transferring those specified in the component to transferring all of them? Could you provide an example where this is necessary?

2025-03-05 21:28 UTC, slarticodefast requested changes

2025-03-05 21:28 UTC, slarticodefast commented on Content.Server/Construction/ConstructionSystem.Graph.cs
> +                var oldContainerManager = EntityManager.EnsureComponent<ContainerManagerComponent>(uid);
we already know this one from the `containerManager` variable

2025-03-05 21:28 UTC, slarticodefast commented on Content.Server/Construction/ConstructionSystem.Graph.cs
> +                // Transfer all containers owned by the previous entity to the new one.
I'm pretty sure transferring all containers will cause bugs and unintended behaviour.
Solutions are containers.
Actions are stored in containers.
Some items have containers that store virtual items.
And so on.
The containers to be transferred should be specificly chosen in the construction graph.

2025-03-05 21:28 UTC, slarticodefast commented on Content.Shared/Containers/ContainerFillComponent.cs
> +    public bool FillEmptyContainersOnly = true;
This feels hacky.

2025-03-05 21:29 UTC, beck-thompson approved these changes
I've tested this a lot, I'm still unsure about construction code and this does have some weird anomalies (E.g containers will always get transferred even if it doesn't quite make sense.). However, it does fix the issue and makes enough sense so I think its good!

Also fix this comment to indicate that it isn't just "containers handled by construction" now
![Screenshot from 2025-03-05 13-15-43](https://github.com/user-attachments/assets/69209a9b-9b9e-4bd8-87bc-bdfa8363c703)

2025-03-05 21:29 UTC, beck-thompson commented on Content.Shared/Containers/ContainerFillComponent.cs
> +    [DataField("fillEmptyContainersOnly")]
get rid of the name override!

2025-03-05 21:29 UTC, beck-thompson commented on Content.Server/Construction/ConstructionSystem.Graph.cs
> +                foreach (string container in oldContainerManager.Containers.Keys)
use var instead of string

2025-03-05 21:33 UTC, slarticodefast commented
Is this PR even needed? It look like you can already whitelist the containers that should be preserved.
See https://github.com/space-wizards/space-station-14/pull/34911 for an example.

2025-06-27 00:42 UTC, slarticodefast commented
Since the issue got fixed by https://github.com/space-wizards/space-station-14/pull/34911 it turns out the construction system is working as intended. The containers to be transferred need to be whitelisted like done in that PR. Transferring all containers will create a whole range of bugs, as actions, solutions etc would be transferred with them.

To be fair, the ConstructionComponent could really use some documentation for this.

2025-06-27 00:42 UTC, closed without merging