Add Sprite changes to Logic Gates to show the input/output state
space-wizards/space-station-14 pull request #33277
Opened 2024-11-12 13:53 UTC by 0tito

## About the PR
Gates now show the state of their inputs and outputs on the sprite

## Why / Balance
Its easier to use them if you can see the states

## Media
https://github.com/user-attachments/assets/c305a2b9-adcb-420f-8a2e-f5ad60a11166

## Requirements

- [ x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

2024-11-12 21:49 UTC, deltanedas commented
use separate layers for a/b/output and none of the evil stuff is needed

2024-11-14 02:51 UTC, 0tito commented
Is this better? im not exactly the best coder :godo:

2024-11-19 00:47 UTC, Aeshus requested changes
Thanks for the PR!

There's some small code style issues, and a bug where the code accidentally sets InputA instead of InputB.

Other than that, I like the change and the rest of the visualizer/layering stuff looks good (I don't have personal experience with any of it).

Also, I'm not a maintainer, so this is just a peer review. I may have made some mistakes in my review, or have missed things, so take this review with a grain of salt.

2024-11-20 18:42 UTC, deltanedas requested changes

2024-11-20 18:42 UTC, deltanedas commented on Content.Shared/DeviceLinking/SharedLogicGate.cs
> +public enum LogicGateState : byte
copy paste of SignalState

2024-11-26 04:10 UTC, Aeshus approved these changes
LGTM! Thanks for applying the changes/feedback.

I think the only thing now is that you could add yourself to the `meta.json`'s copyright to say that you created the sprites for the light-up states.

Also, make sure to click "resolve" for comments/requested changes once you address it. Otherwise, maintainers may have the false impression that it is still a work-in-progress or ongoing issue.

2024-11-27 16:08 UTC, slarticodefast requested changes
Cool idea. Needs a little more cleanup before it can be merged.
Thanks to Aeshus and delta for doing the previous reviews.

2024-11-27 16:08 UTC, slarticodefast commented on Content.Server/DeviceLinking/Systems/LogicGateSystem.cs
> +            _appearance.SetData(uid, LogicGateVisuals.InputA, state == SignalState.High ? "High" : "Low");
Instead of using the strings "High" and "Low" you can simply make it a boolean

2024-11-27 16:08 UTC, slarticodefast commented on Resources/Prototypes/Entities/Structures/gates.yml
> +    - state: empty
instead of using an empty sprite just toggle the layers on or off

2024-12-03 17:48 UTC, slarticodefast commented
Quick question: What changes did you make to logic.png? I don't see any difference yet somehow it still doubled in size.

2024-12-03 17:59 UTC, 0tito commented
I used it as base when i was making the other sprites, and i think i changed its sprite when  i was learning how to change sprites but then instead of reverting it i painted it back to a similar color :godo: i used krita, maybe when i saved i changed something on it?

2024-12-03 18:06 UTC, slarticodefast commented
If it is not changed leave it as it was to preserve the git history and attributions.
And I gave the PR a quick in-game test and the sprites for gates other than the or gate seem to be wrong now when spawning them.
![grafik](https://github.com/user-attachments/assets/9beb7f25-e09d-4266-b8fb-8d4a789c25c1)

2024-12-03 18:18 UTC, 0tito commented
This happens in normal wizden too, iirc oasis has some gates like that, but if you craft them and  switch through them normally they work. I can try to change it tho, also how do i "revert" the change to logic.png, would just replacing the sprite with upstream logic.png fix it? or do i have to do something else

2024-12-03 18:58 UTC, slarticodefast commented
Just copying the original sprite back is probably the easiest way. There should be a git command, too, but no idea which one.
Thanks for fixing the other gates! I'll give it another test later.

2024-12-04 12:09 UTC, slarticodefast approved these changes
I tested this and it works as intended for non-pulsed signals. With signal buttons there seems to be some weird behaviour for gates, but that is not the fault of this PR and happening on master as well. I opened an issue for that #33716.
Thank you for your first contribution!

2024-12-06 15:35 UTC, merged