Six new food crates for the ATS
space-wizards/space-station-14 pull request #33286
Opened 2024-11-13 02:10 UTC by AgentSmithRadio

## About the PR
I've added six new food crates available for purchase from the ATS. A brief summary:
**Getmore Bakemore Crate** - A slimmed down kitchen supplies crate with 6 of each Getmore baking ingredient (raisins/chocolate/pistachios).
**Black Market Meats Freezer** - Freezer containing 4 human meat, 2 lizard meat and 2 plant meat.
**Moth Pizza Delivery** - 4 cotton pizzas for stations that want to accommodate moths, otherwise identical to a normal pizza delivery crate. They spawn properly in pizza boxes with plastic knives.
**Personnel Surprise Crate** - High-end meal hamburger and fries meal with cake, water cup party hat and mystery figure box, a way to reward/celebrate/cheer up a crew member. Not made for sharing.
**Ice Cream Delivery** - 16 pieces of assorted ice cream food items, probably going to be very popular if implemented.
**Snowcone Delivery** - 16 assorted snowcones for _slightly less_ than the ice cream delivery, because they deserve representation too.

## Why / Balance
The food category that cargo has access to is rather limited, with the most exciting things on there being the pizza delivery crates. My basic reasoning is as follows:

The Getmore Bakemore crate is to provide an answer for making things like Raisin Cookies, Baklava and Chocolate Cake without having to raid vending machines as a chef, or necessarily make chocolate. I view the Getmore items inside as candy/junk food, and this is a fun way to combine these specific items which have recipes into a kit that encourages chefs to actually make these sorts of foods. I'm not sure if it's necessarily competitive with a kitchen supplies crate in the current meta, but I could see it being of about equal appeal with a ChefVend restock.

Black Market Meats is a way to get cannibal meats onto the station in a marginally less (or more?) morally questionable way. Some people like exploring this topic, and I see no real reason not to enable it. NanoTransen isn't exactly portrayed as that moral of a corporation. It's also a way to get an extra Freezer, which isn't usually a thing that's in demand, but it's a thing.

The Moth Pizza Delivery is a way to give something edible to moth players, who are often unfed by chefs (even with the new cotton bread and cotton pizza recipes), and they have to resort to eating clothing. This seems like a fun thing for a group of moths to order together from Cargo, or for Cargo to buy in an attempt to support their moth crewmates. Otherwise, it follows the same logic as the other pizza deliveries.

Personnel Surprise Crate contains some high-end food. Crazy Hamburger, Cheesy Fries, Slice of Birthday Cake, Bottle of Space Cola, it's an absolute feast. The mystery figure box and the water cup party hat are a bonus so the recipient has visible keepsakes of getting this crate. None of these items are actually powerful or impact the round in any real way, but they're not the most common foods while being very appealing to receive. This is rife with some fun roleplaying opportunities, and I'd argue that getting one of this has the same appeal as getting a medal from the Captain.

Ice Cream Delivery and Snowcone Delivery are functionally identical, 16 appealing treat-type items to spoil the crew with, or for a few crewmembers to gorge on. I expect the ice cream one in particular to become very popular, and any vanity item being requested from Cargo instead of required/meta/grand lottery is a win in my book.

## Technical details
Edits to box.yml, cargo_food.yml and food.yml. Box.yml was to get the cotton pizzas to spawn in their own dedicated pizza boxes, cargo_food.yml and food.yml was to actually get the crates into the cargo menu as spawnable entities. I only added content, nothing was removed.

## Media
[Here's a YouTube video showcasing the crates, and showing them on the Cargo request console.](https://www.youtube.com/watch?v=Ci9jTEiO7i0)

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
I don't forsee any issues with this beyond possible merge conflicts. All of these crates worked when tested.

**Changelog**
:cl:
- add: New food crates are now available at the Automated Trade Station!

2024-11-13 02:35 UTC, lucioghosty commented
It would be great if there was a personnel surprise crate for moths too, otherwise you'll just gift your moff fren a crate and they'll say "thanks but I can't eat any of this."

Just a personal suggestion!

2024-11-13 02:50 UTC, AgentSmithRadio commented
> It would be great if there was a personnel surprise crate for moths too, otherwise you'll just gift your moff fren a crate and they'll say "thanks but I can't eat any of this."
> 
> Just a personal suggestion!

I was trying to brainstorm this one and... I'm not sure if it works quite the same? I'd add one if I had a decent concept for it.

Your real choices for the moth crate are cotton pizza, which I'm adding here already, cotton bread, which is generally seen as a food downgrade, and fancy clothing. What do you think this type of crate should look like, I'm not against adding it to my PR if there's something there.

2024-11-13 07:56 UTC, RedBookcase commented
Looks like a fun expansion for cargo vanity buys, i'm in favor of it. Kind of weird that the ice cream doesn't come in a freezer though, no? But I guess it doesn't rot, so doesn't really matter.

2024-11-13 14:28 UTC, AgentSmithRadio commented
> Looks like a fun expansion for cargo vanity buys, i'm in favor of it. Kind of weird that the ice cream doesn't come in a freezer though, no? But I guess it doesn't rot, so doesn't really matter.

Yeah, I admit that I have no idea what adding a freezer to the things cargo can buy will do to... anything? It was a necessary evil for the black market meats "crate" because otherwise the meat is basically guaranteed to rot before it gets delivered to kitchen under normal cargo conditions. If there's no real issue to putting ice cream or snowcones into a freezer, it's a very easy change to make, I just haven't considered the actual consequences of making freezers even more accessible in that way, aside from just how bulky they are from being structures.

2024-11-14 15:42 UTC, AgentSmithRadio commented
I have now learned that Plant Meat doesn't actually have a cooking recipe. I'm not sure if this needs to prompt a change or not, I'll come back to this.

2024-11-14 22:36 UTC, AgentSmithRadio commented
Plant Meat itself is edible by itself, and seems to function like other raw meat. There doesn't appear to be a cooked plant meat sprite from SS13 or one worth repurposing in the searching I've done. I think that it can exist as it is, Reptilians can eat it without penalty and letting cannibals do weird cannibal things is definitely on-brand for that behaviour.

Hopefully someone will make a cooked plant meat recipe, but I don't think that this PR requires one as it is.

2024-12-07 19:39 UTC, TiniestShark commented
I really enjoy the idea of just buying your employees the Five Guys equivalent of a Happy Meal. These are all pretty great ideas and I always enjoy seeing cargo get more interesting things to buy. 

The Black Market Meats crate is the only one I'm a little iffy on, makes cannibalism a bit too "easy" if that makes any sense rather than needing to be a thing actively and willfully committed. NT's pretty morally questionable but casual cannibalism feels a bit far even if it's a "Black Market" crate, especially given it would stand in pretty stark contrast to most everything else. Corporate branding would be something closer to "a new, bold initiative on waste management" and then introducing soylent green.

2024-12-08 01:14 UTC, AgentSmithRadio commented
> The Black Market Meats crate is the only one I'm a little iffy on, makes cannibalism a bit too "easy" if that makes any sense rather than needing to be a thing actively and willfully committed. NT's pretty morally questionable but casual cannibalism feels a bit far even if it's a "Black Market" crate, especially given it would stand in pretty stark contrast to most everything else. Corporate branding would be something closer to "a new, bold initiative on waste management" and then introducing soylent green.

I'm of a split mind on this.

On one hand, NanoTrasen presents itself as a reliable, nominally safe and dare I say family-friendly organization, almost like a cost-cutting capitalist Federation from Star Trek. They're generally humane, and try to provide creature comforts to an almost Fallout level of decadence that they actually deliver on, with branded products, bar/kitchen/hydroponics/janitorial staff and paid musicians. They also have a family-friendly face to their branding with the plushie lineups and Safety Moth posters, and their deliberate attempts to combat speciesism, and a thriving tourism business.

On the other hand, they cut so many corners, do not give the staffing, training or resources required to actually run their stations, and their morality is demonstrably loose at best. They're not a good corporation, with a safety-third approach to their designs with minimal redundancies, leaving their stations susceptible to disaster. They do active dangerous scientific research on their stations despite their civilian populations, and stations like Core haven't even received a new coat of paint after a prior zombie infestation. They're monopolistic to the point of having an entire syndicate of corporations forming against them, despite not even being a direct competitor to many of these corporations. Salvage teams barely have anything resembling safety equipment despite the high risk of their jobs, even when we see what NanoTrasen death squads are capable of. 

Salvage wrecks continue to tell the story. So many derelict space station chunks are just drifting in space, littered with corpses and proof of NT's failures. Admeme events such as the Phoenix (classified moth hybrid research experiment gone rogue). The illegal fighting pits found within the depths of maintenance on stations, and the scars of greytide revolutions. The human burgers that can spawn on stations at round-start. Despite NT's nice vaneer, they're not _okay_.

I could see NT, through its extensive genetics testing, station reclamation projects, black ops and salvage operations just having a lot of corpses, and looking to cut a profit from it through scrupulous/unaware quartermasters. Perhaps the Black Market Meats are sold from Syndicate corporations, or NT is looking for ways to supply this type of meat to their stations knowing the... eccentric natures of their crews and the predilections of different species (Reptilians and Arachnids especially) in order to prevent internal cannibalism from occurring. 

Or maybe it's a branding issue and just needs to be renamed/branded, or just needs to be removed. I'd love to hear more on this.

2024-12-08 08:30 UTC, TiniestShark commented
> I could see NT, through its extensive genetics testing, station reclamation projects, black ops and salvage operations just having a lot of corpses, and looking to cut a profit from it through scrupulous/unaware quartermasters.

I 100% agree with this view on NT honestly. There's a lot of good creature comforts to help keep their crews relatively and decently comfortable, but it does always very much run up against the general corporate idea of providing enough pleasantries to get people to ignore the cut corners and inhumane experiments. I mean this is a corporation with a Deathsquad just on hand to call in during the most extreme examples of crew revolution. They're always most interested in protecting their own assets and profits above all else.

Though we've already got ways of biomass reclamation through the requisite science machinery, and cloning pods technically which makes it a bit difficult to justify the black market meats IMO. The human burgers and such could be remnants from previous shifts or left there by other actors since all the stations have signs of previous life or usage. That's kind of why I make the soylent green comparison, this is a company that would absolutely 100% in a heartbeat mulch those leftover bodies to get whatever materials they can from them, but it's the marketing angle that's important to remember. You don't want the population to know they're eating people after all.

Most of the sparefaring species are always going to balk at the idea of cannibalism so it needs to be more sneakily presented and done. Something like "Biomass Burgers", some sort of non-indicative name that brings more the idea of the "mcdonald's pink sludge nuggets" than directly cannibalism. Honestly just calling it Soylent in some form would work as a nice classic sci fi reference. Especially since when surgery becomes a thing and a better way of fulfilling things like organ bounties, there's a lot of leftover materials there still to recycle. NT wouldn't even need to profit off of it, it could just be a straight up cheaper alternative to ordering live animals or dehydrated monkeys/kobolds. Why have cargo waste valuable money on those things, when they could purchase the leftovers you're already got instead?


The Syndicate would absolutely just sell meat to cannibals but then that would beg the question of why you can casually order it from the cargo console.

2024-12-08 09:01 UTC, Djungelskog2 commented
I disagree with most of these for the fact that food bloat is very real, vending machines are publicly accessible and food supply crates are already somewhat common. rare cannibal meats shouldnt be able to be gotten any way outside of actually butchering someone, the moth crate shouldnt exist because cotton foods should just appear in the already existing crates and the personal would be a good idea if we had a proper mailing system or "Mailman" cargo tech archetype or personal lock on the crate with a note saying who it goes to, otherwise its directionless and unlikely to be noticed or cared about.

2024-12-08 16:57 UTC, AgentSmithRadio commented
> I disagree with most of these for the fact that food bloat is very real, vending machines are publicly accessible and food supply crates are already somewhat common. 

Right now food is in a spot of "eat your ration and maybe one more time a shift to avoid the debuff", and starvation isn't a current actual concern for play. I can't even think of a time that it's happened to me, even as a Reptilian player where my food choices are often quite limited. This leaves it, in my mind, as a roleplaying tool, and these crates are opportunities for roleplay, on top of GetMore BakeMore, which is just a cool new toy for chef players who want to mess with the vending machine recipes.

> rare cannibal meats shouldnt be able to be gotten any way outside of actually butchering someone,

I don't see why it should be rare, at least not much more than exotic animal meat (ie. penguin), see my discussion with TiniestShark, but I've decided that I'm going to be removing this one purely for flavour reasons. It doesn't make sense for NT to be selling this with how they brand themselves, or for the ATS to be carrying this, no matter how evil NT may be. 

> the moth crate shouldnt exist because cotton foods should just appear in the already existing crates 

It's a probability problem. Cotton pizza is the only pizza that moths can eat, and it's currently spawning in pizza boxes at a 10% rate. With the emergency pizza delivery (4 pizzas), there is a ~34% chance of a cotton pizza appearing. For disaster pizza delivery (16 pizzas), there's ~18.5% chance that a cotton pizza won't spawn, that's roughly 1 in 5. Moths get screwed over on these pizza deliveries daily, this is a way to mitigate that with a proportion that likely covers the average station's moth populations (even moth-heavy servers like Salamander).

> and the personal would be a good idea if we had a proper mailing system or "Mailman" cargo tech archetype or personal lock on the crate with a note saying who it goes to, otherwise its directionless and unlikely to be noticed or cared about.

The Personnel Surprise Crate is a single-person rehash of the Party Crate in-game, being a deluxe hamburger meal, hat and toy, rather than a birthday cake, a whole bunch of party hats and glowsticks and some cups of grape juice. Party Crate does see some use in my experience, at least in MRP, about as much as a department-specific pizza party request happens. This is a way to personalize that experience, or for cargo to really spoil themselves.

Cargo in any given round can be all over the place. It can be completely incompetent and refuse to do anything (revolutionaries), to delivering every major requested item (bulk resources for science, Solid Plasma for science, ChemVend Restock for Chemistry, Kitchen Supplies Crate for Kitchen, Exotic Seeds for Botany, etc.) without being asked, before getting on to getting fun stuff like Light Implants or Clown Toybox or vending machine restocks or what have you because the department is just that effective. Struggling with cargo is a part of the game, but when cargo can flex, I want them to have every opportunity to flex with vanity purchases and personalized deliveries. Sometimes, they succeed. Sometimes, somebody has to steal a cargo ID off a corpse, approve the order, get it off the telepad, and deliver it themselves, despite whatever disaster is going on, because they have an encounter they want to roleplay. We shouldn't deny things because players suck and the game encourages antagonists and a constant sense of paranoia, but enable players to do fun things that they aren't doing to win the game, but to experience it.

2024-12-08 17:04 UTC, AgentSmithRadio commented
> That's kind of why I make the soylent green comparison, this is a company that would absolutely 100% in a heartbeat mulch those leftover bodies to get whatever materials they can from them, but it's the marketing angle that's important to remember. You don't want the population to know they're eating people after all.

Your whole response is well argued, and short of me creating an actual soylent entity (out of my skillset, and the ones actually made from soy don't count), there isn't really a way to explore this. The best ideas I had to replace this includes "exotic animal meats", such as penguin, but that feels like it should be even more rare than cannibalism is given how expensive animals are, even on stations like Cog (where, to be fair, Kitchen is neglected to all hell because of the dead Bar placement at the end of the main horseshoe highway, and the hidden Kitchen). That leaves me with creating something like jugs of raw animal proteins and fats, sort of a "make your own meat kit", which might be an idea worth pursuing, but I feel like I'm going down a whole rabbit hole because fundamentally I had a bad idea. I can check that idea out some other day, perhaps with the whole Science lipid extractor tech that nobody ever uses.

I'll be removing Black Market Meats from my PR when I get a moment, thanks for helping me see the light.

2024-12-08 18:08 UTC, TiniestShark commented
> Your whole response is well argued, and short of me creating an actual soylent entity (out of my skillset, and the ones actually made from soy don't count), there isn't really a way to explore this.

Yeah, this is one of those situations where I'd want to put my money where my mouth is but my coding skills are still pretty basic at the moment as is. I'm still barely figuring out how to do inhands lol.

>  but I feel like I'm going down a whole rabbit hole because fundamentally I had a bad idea. 

I wouldn't call it a fundamentally bad idea, it's definitely worth exploring to some degree. I mean the whole angle of trying to put together an idea for how NT would handle the vast amount of bodies it no doubt ends up with in its attempts to recycle and re-use them is a great avenue to pursue. It's more that the specific presentation needed some refinement.

> That leaves me with creating something like jugs of raw animal proteins and fats, sort of a "make your own meat kit", which might be an idea worth pursuing

If you ever do, I'd love to see what you come up with! More reasons for people to use the Lipid machinery would be great outside of just wanting to make 500 mothroaches to unleash at once or something.

2024-12-29 16:07 UTC, AgentSmithRadio commented
https://github.com/space-wizards/space-station-14/pull/33997 means that my my Moth Pizza Delivery crate is no longer required, and is frankly a better solution to the problem than this crate was. I'll get it removed from this PR shortly.

2025-02-10 07:05 UTC, beck-thompson requested changes
I like the ideas!

2025-02-10 07:05 UTC, beck-thompson commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +    - id: FoodBurgerCrazy
Could you do a normal burger (The big bite probably would be good!)? Allowing difficult to create recipes like this to be purchased easily makes them less unique and fun!

2025-02-10 07:05 UTC, beck-thompson commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +  parent: CratePlastic
This is just a VERY powerful crate. Could you tune it down a small bit? I'd cut each snack to 3 each and reduce everything else by one at least.

2025-02-10 14:23 UTC, AgentSmithRadio commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +  parent: CratePlastic
I've been meaning to restructure this PR, it's been needing a rework and I've let it fall by the wayside.

First, I want to give you the two most apt comparisons. The first is a Getmore Restock, which currently restocks 3 of each of the following in any snack.yml machine, 6 if you use both boxes on the same machine: 
![image](https://github.com/user-attachments/assets/fdce2729-e662-44ee-8d76-003a4c179f21)

Effectively this crate as it is is a focused version of that restock box (which comes in 2 per crate, which costs 600), going for the same total (minus the contraband), just in the actual baking ingredients. It is then merged with the "optimal" baking crate which is Kitchen Supplies, which comes with the following:
![image](https://github.com/user-attachments/assets/ec2114f9-27b4-4747-9e3e-e997c6d4dad6)

Same concept, but a cut inventory, being less "generally" good, and being hyper-focused on baking. And yes, the Kitchen Supplies crate is in fact that good, and I think it's that way because they're an absolute pain to get from cargo, especially if you want more than one, they'd rather just give you ChefVends due to their ease of delivery.

With 3 of each snack, we're getting ~300 in value from the snacks, with a cut kitchen supplies inventory, and then you're wondering why you're ever ordering this. 3 of a reagent to cook with kind of sucks. For instance, with one such crate you can make:

Pistachios: 3 Baklava (only recipe, has the advantage of being a pie for the sake of clown/bounty)
4no Rasins: 3 Raisin Cookies (only recipe, unless you count Cak, which this crate does not cover)
Chocolate: This gets even more sad: 
![image](https://github.com/user-attachments/assets/bdc403aa-faa0-4579-81b9-1e5a44f978c2)

In order for this crate to be worth getting, I think you need to go heavy on the candy. It's a pantry crate for when Botany is refusing to grow crops for you because they have other focuses (a common issue on servers like Salamander), allowing you to still cook foods that require effort and "uncommon" ingredients through working with cargo, and without having to raid all of the snack machines on the station.

If we're going to nerf the ingredients, the worst I'd like to see is 4 on the 3 candies, or cutting pistachios and raisins and boosting the chocolate. If this crate is to exist, it has to have a reason to be taken over Kitchen Supplies and ChefVend, otherwise it'll just be bloat in the Cargo menu that will be ignored.

2025-02-10 14:27 UTC, AgentSmithRadio commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +    - id: FoodBurgerCrazy
When I conceived of this crate, I was going for spectacle, and crazy burger felt like spectacle at the time. I then had the crate compared to a trip to 5 Guys for Cargo, and yeah, I get how it loses it's specialness from that, even with its relative expense.

I could see going for a Big Bite Burger as well. It's fancy, while not intricate like Crazy or the Super Big Bite, it's in that delicious middle ground.

I'm also wondering if I should get the crate to instead create a box which then has a fill with all these items, so that it's more like being given a meal box, instead of having to haul a crate all the way across the station to surprise someone. And if I'm going to that point, maybe this just needs to become a hamburger meal for 1 concept.

I'll need to think on this one a bit.

2025-02-11 04:58 UTC, beck-thompson commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +    - id: FoodBurgerCrazy
Up to you! I think either is fine

2025-02-11 05:00 UTC, beck-thompson commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +  parent: CratePlastic
I trust your judgement I didn't realize how powerful the other crates where. Maybe just slightly reduce some of the candy then?

2025-02-11 05:01 UTC, beck-thompson commented
Request a review when your done making the changes you want!

2025-02-11 15:43 UTC, AgentSmithRadio commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +  parent: CratePlastic
I'm stuck in the office today, but thinking about what changes to make.

I can see cutting pistachios and raisins to 4 to still see inherent value in ordering this crate over Kitchen Supplies. If forced to cut more, it'd be to get pistachios down to 2-3, given how much relative food Baklava gives as a pie item, but I don't see what real abuse can come from having it at 4. It makes for an easy pie for clown to throw, it's another efficient way to do the pie bounty (ChefVend just does it with meat pie instead), but it doesn't break anything or shake up the meta at all beyond allowing easier no-Botany Chef play.

That said, I'm thinking about the FoodBoxCloth that's now been added to Kitchen Supplies. I think that I need to add it to this crate. Not just for moth inclusiveness and the inherent baking theme to the crate, but because I can see in 6 months time if I don't add it, a new contributor is going to see it missing from this crate and think that it's an omission and PR to get one added to it. I may as well jump ahead and add one.

2025-02-12 05:01 UTC, AgentSmithRadio commented
I made sweeping changes and revisions. Ice Cream and Snowcones now come in freezers to fit their theming. Getmore Bakemore now gets one of the new cloth boxes for moth cooking, and had its raisins and pistachios cut down to 4. Added Happy Honk Meal Delivery to replace Personnel Surprise Crate, which generates with a random Happy Honk toy (crayon box excluded, due to size). I also capitalized Sweetie's Pistachios, following how other branded products are now being treated as proper nouns. New video in description.

2025-02-22 00:20 UTC, beck-thompson approved these changes
seems good besides that! Not the best at balance stuff though but worse case we revert some of it

2025-04-23 05:22 UTC, ArtisticRoomba approved these changes

2025-04-23 05:22 UTC, ArtisticRoomba commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/box.yml
> +        orGroup: GiftPool
All of this should be refactored to use entitytables in the future.

2025-04-23 05:22 UTC, ArtisticRoomba commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
> +  name: Sweetie's Pistachios
```suggestion
  name: Sweetie's pistachios
```

2025-04-23 05:37 UTC, merged