You can't see while you're in a crate
space-wizards/space-station-14 pull request #33317
Opened 2024-11-14 18:37 UTC by TheShuEd

## About the PR
Containers can now block vision for entities that sit within it.

## Why / Balance
Logic

## Media
https://github.com/user-attachments/assets/6d8e3e46-da18-4193-b6a0-6f770c81a9d6

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- tweak: Containers can now block vision for entities that sit within it.

2024-11-14 19:37 UTC, Stewie523 commented
Not everything needs to be logical. This is just annoying.

2024-11-14 20:08 UTC, thebadman4662 commented
> Not everything needs to be logical. This is just annoying.

At least nukies might not need to gun down every disposal bin/locker if they do not want instant stunkill or something 🤔 

Not taking damage when you are hiding in container is weird too but thats another issue I guess.

2024-11-15 00:07 UTC, keronshb commented
I feel the vision blocking is a bit too harsh. It either should have a wider radius or  it should gradually get worse.
Close = see, further = fuzzy, furthest = blind

2024-11-15 00:10 UTC, Kadeo64 commented
lockers have the eye slits

you should be able to see out of them

2024-11-15 00:53 UTC, KaiserMaus commented
Maybe add the same block vision when player travel in disposal tube?

2024-11-15 00:55 UTC, Shaddap1 commented
> lockers have the eye slits
> 
> you should be able to see out of them

I hate being that guy but ackshually not all lockers have slits.

2024-11-15 06:07 UTC, NoElkaTheGod commented
> lockers have the eye slits

Yet somehow they are completely airtight

2024-11-16 03:19 UTC, BombasterDS commented
Can you add float BlockIntensity into component (if that possible with current shader)? It'll have to make lockers with real eye slits. Also i'm think that colorful shader instead of gray one will work better.

2024-11-28 13:40 UTC, metalgearsloth requested changes

2024-11-28 13:40 UTC, metalgearsloth commented on Content.Shared/Eye/Blinding/Components/ChildBlockVisionComponent.cs
> +}
Needs networking.

2024-11-28 13:40 UTC, metalgearsloth commented on Content.Shared/Eye/Blinding/Systems/ChildBlockVisionSystem.cs
> +}
This shouldn't be subscribing to directed events for engine components as this can very easily break in the future when the engine needs it.

2024-11-28 13:40 UTC, metalgearsloth commented on Content.Shared/Eye/Blinding/Systems/ChildBlockVisionSystem.cs
> +    }
You're resolving the transformcomponent twice, once unnecessarily.

Remove the transformqueryhascomp.

2024-12-06 11:34 UTC, TheShuEd commented
Keron is against this kind of implementation of these mechanics, and proper implementation means working with shaders, which I'm not ready for.

2024-12-06 11:34 UTC, closed without merging