[Part of #32893] Localize ai names
space-wizards/space-station-14 pull request #33352
Opened 2024-11-16 14:37 UTC by MilenVolf

## About the PR
Required for #32893

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-11-16 16:55 UTC, SaphireLattice requested changes
Comments probably should be moved to their respective entries in the localization file

And yay moving strings out of the yaml. Honestly this should be a lint some day, that there’s enough Fluent entries for some prefix thing.

2024-11-16 19:05 UTC, deltanedas commented on Resources/Locale/en-US/datasets/names/ai.ftl
> +names-ai-dataset-43 = ENIAC #famous early computer
fake comment

2024-11-16 21:42 UTC, MilenVolf commented on Resources/Locale/en-US/datasets/names/ai.ftl
> +names-ai-dataset-43 = ENIAC #famous early computer
Thanks, missed this

2024-11-16 21:42 UTC, MilenVolf commented
> Comments probably should be moved to their respective entries in the localization file
> 
> And yay moving strings out of the yaml. Honestly this should be a lint some day, that there’s enough Fluent entries for some prefix thing.

Got it

2024-11-16 22:01 UTC, MilenVolf commented
> Comments probably should be moved to their respective entries in the localization file
> 
> And yay moving strings out of the yaml. Honestly this should be a lint some day, that there’s enough Fluent entries for some prefix thing.

Do you mean by that, that you want it to look like this?
## Before:
```
names-ai-dataset-1 = 16-20
names-ai-dataset-2 = 512k
names-ai-dataset-3 = 640k
names-ai-dataset-4 = "790"

## Comments on names
# 640k              - ought to be enough for anybody
```
## After:
```
names-ai-dataset-1 = 16-20
names-ai-dataset-2 = 512k

# Ought to be enough for anybody
names-ai-dataset-3 = 640k

names-ai-dataset-4 = "790"
```

2024-11-16 22:15 UTC, SaphireLattice commented
Yup! Otherwise the comments are just difficult to look through.

2024-11-18 08:02 UTC, TheShuEd approved these changes

2025-02-17 13:10 UTC, Tayrtahn approved these changes

2025-03-08 16:54 UTC, slarticodefast approved these changes
Do not merge before the other required PRs are reviewed.
1/9

2025-03-08 19:02 UTC, merged