Predict vending machine UI
space-wizards/space-station-14 pull request #33412
Opened 2024-11-19 05:24 UTC by metalgearsloth

At least the sound + amount. Not the entity itself. Draft because working on disabling the UI while it's on cooldown.

Resolves https://github.com/space-wizards/space-station-14/issues/31363

:cl:
- tweak: Predict vending machine UI and have the buttons reflect whether the UI is useable.

2024-12-05 02:34 UTC, slarticodefast requested changes
Found some bugs while testing:
- The last item in the inventory list seems to be always missing
- In some cases you cannot scroll to the bottom of the list without resizing the window
![grafik](https://github.com/user-attachments/assets/7b0239e0-58e5-4a01-9cab-e5f7bde98d04)
![grafik](https://github.com/user-attachments/assets/1e1184cc-296a-4e07-a77d-896cab88e12b)

2024-12-05 02:34 UTC, slarticodefast commented on Content.Shared/VendingMachines/SharedVendingMachineSystem.cs
> +        Popup.PopupClient(Loc.GetString("vending-machine-component-try-eject-access-denied"), uid);
```suggestion
        Popup.PopupEntity(Loc.GetString("vending-machine-component-try-eject-access-denied"), uid);
```
The popup currently does not show up. For `PopupClient` the second parameter is the recipient, not the entity the popup is shown above. Maybe `PopupPredicted` works here as well and should be used instead, not sure.

2025-01-20 09:24 UTC, MilonPL reviewed
Mostly covered by the other review, minor nitpicks. 
Edit: add the PublicAPI attribute to public methods!

2025-01-20 09:24 UTC, MilonPL commented on Content.Client/Advertise/Systems/SpeakOnUIClosedSystem.cs
> +public sealed class SpeakOnUIClosedSystem : SharedSpeakOnUIClosedSystem
Just put a semicolon at the end of this line, doesn't need a body declared.

2025-01-20 09:24 UTC, MilonPL commented on Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
> +using Robust.Shared.Timing;
Unused.

2025-01-20 09:24 UTC, MilonPL commented on Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
>              if (data is not VendorItemsListData { ItemProtoID: var protoID, ItemText: var text })
Might want to rename it to `protoId` if you're touching this.

2025-01-20 09:24 UTC, MilonPL commented on Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
> +            foreach (var (proto, uid) in _dummies)
`uid` is never being used.

2025-01-20 09:24 UTC, MilonPL commented on Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
> +public record VendorItemsListData(EntProtoId ItemProtoID, int ItemIndex) : ListData
Since we're not using a file scoped namespace in this file (the curse of old code), this will not be namespaced properly. Might want to move it up.

2025-01-20 09:24 UTC, MilonPL commented on Content.Client/UserInterface/Controls/ListContainer.cs
> +    public ListContainerButton(ListData data, int index) : base()
Is there any reason to call `base()` here?

2025-01-20 09:24 UTC, MilonPL commented on Content.Client/VendingMachines/VendingMachineSystem.cs
> +    private void OnVendingHandleState(EntityUid uid, VendingMachineComponent component, ref ComponentHandleState args)
Can this use `Entity<T>` instead?

2025-01-20 09:24 UTC, MilonPL commented on Content.Shared/VendingMachines/SharedVendingMachineSystem.cs
> +    private void OnVendingGetState(EntityUid uid, VendingMachineComponent component, ref ComponentGetState args)
This doesn't have any overrides so should be fine to just use `Entity<T>`.

2025-01-20 09:24 UTC, MilonPL commented on Content.Shared/VendingMachines/SharedVendingMachineSystem.cs
> +    private void OnInventoryEjectMessage(EntityUid uid, VendingMachineComponent component, VendingMachineEjectMessage args)
Above.

2025-01-20 09:24 UTC, MilonPL commented on Content.Shared/VendingMachines/VendingMachineComponent.cs
> +        public TimeSpan? EjectEnd;
These are runtime-modified, is there a reason to not using a TimeOffsetSerializer?

2025-02-18 13:12 UTC, metalgearsloth commented on Content.Shared/VendingMachines/SharedVendingMachineSystem.cs
> +        Dirty(entity);
Dirty just flags the component for PVS which runs entirely out of band after all systems have run (via servergamestatemanager or via clientgamestatemanager due to funny prediction reasons).

2025-02-18 13:19 UTC, metalgearsloth commented on Content.Shared/VendingMachines/VendingMachineComponent.cs
> +    public sealed class VendingMachineComponentState : ComponentState
Dictionaries aren't copied properly so when the client re-runs states it mutates the componentstate and causes bad times (I have an engine PR but have been lazy on finishing it).

2025-02-23 22:15 UTC, slarticodefast commented
Still can't grab the last item without resizing the window. This will need to be fixed first.
![example](https://github.com/user-attachments/assets/1b27710a-2712-4f6a-ac34-ebb93a6c3fe4)

2025-03-02 02:47 UTC, merged