Derelictn'tn't Borg!
space-wizards/space-station-14 pull request #33433
Opened 2024-11-20 16:20 UTC by ScarKy0

## About the PR

Revival of #32499 due to some github mess. It apparently got merged but not really since it was instantly reverted. This PR is basically the same as that one but also cleaned up.

## Why / Balance

Read in the original PR.

## Technical details

Read in the original PR.

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: ScarKy0, GoldenCan
- add: The Derelict Cyborg - a broken cyborg with altered laws due to year of exposure to ion storms - can now appear as a ghost role through a new midround event.

2024-11-21 00:21 UTC, slarticodefast requested changes

2024-11-21 00:21 UTC, slarticodefast commented on Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
> +    removeChance: 0.1
```suggestion
```
Keep it at the default or we will end up with way too many laws.

2024-12-03 20:04 UTC, slarticodefast approved these changes
The amount of laws this generates is still a little high.
But I asked the admins for feedback again and they said the players can probably handle it and to ship it and see where it goes, so let's give it a try.

2024-12-06 06:22 UTC, chromiumboy commented
The code looks fine and I tested it in-game. The randomization of the laws is a bit extreme. I had one borg with a single ion law and no core laws, and another with 2 ion storm laws and 10 core laws (i.e., the 10 commandments). But I saw the admin approval, so let's try it and see what happens

2024-12-06 06:22 UTC, merged