Ripley Resprite
space-wizards/space-station-14 pull request #33452
Opened 2024-11-21 21:50 UTC by Conflee

## About the PR
All sprites for the Ripley Mech, including recoloring most of the mech arms.

## Why / Balance
The old Ripley sprites were very old, and no longer fit in with the rest of the mechs in the game. Specifically, their shading and outline style was dramatically different to the point of distraction in my opinion. However, the overall design was nice, so I kept that mostly. The mech arms and tools were also not colored the same as the Ripley, even before I reshaded it, so I amended that where needed.

## Technical details
N/A, Sprite Work

## Media
![a84c246e6c54666b7a14d563ea3c1697](https://github.com/user-attachments/assets/964db879-d401-4b80-9eb4-1b01d2bc55ff)
Old on the left, new on the right. Included the MKII as well

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A, Sprite Work

**Changelog**

:cl:
- tweak: All Ripley sprites. Including base Ripley, MKII, Broken, Old, etc
- tweak: Several mech arms and tools, to make it so the yellow parts of them actually match the yellow of the Ripley (They didn't even before I changed Ripley)

2024-11-21 22:07 UTC, Aeshus requested changes
Thanks for the PR!

The new sprites look great (though I'm not really in any position to judge as a code contributor), but there's some minor stuff you'll need to fix in your PR to get this ready to be merged.

1. Make sure to edit the [`meta.json`](https://docs.spacestation14.com/en/specifications/robust-station-image.html) file in the RSI directories that you're modifying to properly credit yourself! You should probably credit yourself at the end of the existing copyright information for modifying/respriting them. (e.g.) https://github.com/space-wizards/space-station-14/blob/de59d537f02ec754e5e8a3017a8a848f13233b0f/Resources/Textures/Objects/Specific/Mech/mecha.rsi/meta.json#L1-L4
2. "Minor respriting" (what they would call fixing/cleaning up current sprites) generally aren't given changelog entries, so you'll need to remove it from your pr description. There's more information in the [Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html#changelog). They usually only want changelog entries for things that are major and likely to affect player experience (e.g. no longer recognizable from its original).
   > Log only changes with significant in-game impact. This may include new features or changes or tweaks to existing features that affect balance. Minor changes to object appearances and descriptions typically do not affect how you would play the game. Changelog entries for major sprite updates are appropriate.

2024-11-21 22:18 UTC, Conflee commented
Edited change log. I probably won't bother crediting myself on this one (partially because figuring out how might be another hour but mostly because all I did was some shading and linework tweaks. Wasn't actually much) I'll do it in the future though!

2024-11-21 23:00 UTC, Aeshus commented
I'd like to insist that you credit yourself! 

(Plus I think the maintainers may block merging because of it, as we're trying to get a lot better with asset provenance/copyright verification right now.)

All you need to do is edit these 3 files to credit yourself (just append your name to the copyright text that's already in those files).

1. https://github.com/space-wizards/space-station-14/blob/de59d537f02ec754e5e8a3017a8a848f13233b0f/Resources/Textures/Objects/Specific/Mech/mecha.rsi/meta.json#L2
   
   (e.g.)
   ```json
     "copyright" : "Taken from https://github.com/tgstation/tgstation at at https://github.com/tgstation/tgstation/commit/40d89d11ea4a5cb81d61dc1018b46f4e7d32c62a, hamtr made by brainfood1183 (github), ripley sprites modified by Conflee (github)",
   ```

2. https://github.com/space-wizards/space-station-14/blob/de59d537f02ec754e5e8a3017a8a848f13233b0f/Resources/Textures/Objects/Specific/Mech/mecha_equipment.rsi/meta.json#L2
   
   (e.g., not totally sure I like how I've phrased it)
   ```json
     "copyright" : "Taken from https://github.com/tgstation/tgstation at at https://github.com/tgstation/tgstation/commit/40d89d11ea4a5cb81d61dc1018b46f4e7d32c62a, many mecha modules modified by Conflee (github)",
   ```

3. https://github.com/space-wizards/space-station-14/blob/de59d537f02ec754e5e8a3017a8a848f13233b0f/Resources/Textures/Objects/Specific/Mech/ripley_construction.rsi/meta.json#L2

   
   (e.g.)
   ```json
     "copyright" : "Taken from https://github.com/tgstation/tgstation at at https://github.com/tgstation/tgstation/commit/40d89d11ea4a5cb81d61dc1018b46f4e7d32c62a, ripley sprite modified by Conflee (github)",
   ```

2024-11-21 23:19 UTC, Conflee commented
> I'd like to insist that you credit yourself!
> 
> (Plus I think the maintainers may block merging because of it, as we're trying to get a lot better with asset provenance/copyright verification right now.)
> 
> All you need to do is edit these 3 files to credit yourself (just append your name to the copyright text that's already in those files).
> 
> 1. https://github.com/space-wizards/space-station-14/blob/de59d537f02ec754e5e8a3017a8a848f13233b0f/Resources/Textures/Objects/Specific/Mech/mecha.rsi/meta.json#L2
>    
>    (e.g.)
>    ```json
>      "copyright" : "Taken from https://github.com/tgstation/tgstation at at https://github.com/tgstation/tgstation/commit/40d89d11ea4a5cb81d61dc1018b46f4e7d32c62a, hamtr made by brainfood1183 (github), ripley sprites modified by Conflee (github)",
>    ```
> 2. https://github.com/space-wizards/space-station-14/blob/de59d537f02ec754e5e8a3017a8a848f13233b0f/Resources/Textures/Objects/Specific/Mech/mecha_equipment.rsi/meta.json#L2
>    
>    (e.g., not totally sure I like how I've phrased it)
>    ```json
>      "copyright" : "Taken from https://github.com/tgstation/tgstation at at https://github.com/tgstation/tgstation/commit/40d89d11ea4a5cb81d61dc1018b46f4e7d32c62a, many mecha modules modified by Conflee (github)",
>    ```
> 3. https://github.com/space-wizards/space-station-14/blob/de59d537f02ec754e5e8a3017a8a848f13233b0f/Resources/Textures/Objects/Specific/Mech/ripley_construction.rsi/meta.json#L2
>    
>    (e.g.)
>    ```json
>      "copyright" : "Taken from https://github.com/tgstation/tgstation at at https://github.com/tgstation/tgstation/commit/40d89d11ea4a5cb81d61dc1018b46f4e7d32c62a, ripley sprite modified by Conflee (github)",
>    ```

Alrighty done.

2024-11-21 23:21 UTC, Aeshus approved these changes
Looks good to me!

2024-11-21 23:22 UTC, Aeshus commented
Ignore the failed labels test...

2024-11-22 01:56 UTC, ps3moira commented
I don't like the four orange lights on the back

2024-11-22 02:13 UTC, Conflee commented
> I don't like the four orange lights on the back, it doesn't make much sense design wise. Could swap it out for a control panel look.

They're meant to be indicator lights for if the machine is on or off. The unpiloted version has the lights turned off so it's easier to tell if it's occupied or not from behind.

2025-01-02 17:33 UTC, closed without merging