Safari hat In-hand Sprites
space-wizards/space-station-14 pull request #33464
Opened 2024-11-22 19:32 UTC by onesch

## About the PR
Adds in-hand sprites to the safari hat.

## Why / Balance
Currently it has no in-hands, so this is adding one.

## Media

<img src="https://github.com/user-attachments/assets/1b853c11-3b4f-4d21-99f5-c0533d50331e" alt="inhand-left" width="250"/>
<img src="https://github.com/user-attachments/assets/991824a7-40b8-4097-8b14-223ee5257c82" alt="inhand-right" width="250"/>

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Adds in-hand sprites to the safari hat.

2024-12-11 23:24 UTC, slarticodefast requested changes

2024-12-11 23:24 UTC, slarticodefast commented on Resources/Textures/Clothing/Head/Hats/safarihat.rsi/meta.json
> +  }
Please keep the indentation as it was before at two spaces per level.
Also make sure the closing curly brackets line up correctly.
I'll ask an art director for approval for the sprite.

2024-12-12 00:51 UTC, slarticodefast commented
Also a small visual change like this does not need a changelog entry, could you remove that from your PR description?
You will ofc course still be mentioned in the game's credits for contributing.

2024-12-12 01:31 UTC, Emisse approved these changes

2024-12-12 09:07 UTC, onesch commented
> Also a small visual change like this does not need a changelog entry, could you remove that from your PR description?
> You will of course still be mentioned in the game's credits for contributing.

I deleted the changelog.

Is the problem with indents solved? Is the fact that I approved your changes regarding indents already in the branch as a commited?

2024-12-12 12:11 UTC, slarticodefast commented
It seems like you did not push the changes to your branch correctly, the indentation hasn't been fixed yet.

2024-12-12 13:11 UTC, onesch reviewed
Correct?

2024-12-12 17:09 UTC, slarticodefast approved these changes
Looks good to me, thank you for your contribution!

2024-12-12 17:09 UTC, merged