Minor shotgun changes and comments for future changes
space-wizards/space-station-14 pull request #33512
Opened 2024-11-24 08:32 UTC by K-Dynamic

## About the PR

- Increased Kammerer ammo count from 4 to 7, reduced firerate from 2 to 1.
- Double-Barrel shotgun and sawn-off version now share the same fire rate (previous 2 and 4 respectively, now 3).
- Added yml comments to multiple shotguns to describe intended behaviour and future changes.
- Changed descriptions of the Kammerer, Enforcer and Bulldog.

## Why / Balance

The Kammerer only having 4 shells for its length makes awkward to use in combat, as it's essentially a quad shotgun that requires frequent reloading. I've also never heard of a four-shell shotgun unless it's compact or shortened. 7 shells is much more sustainable, while having a slower firerate differentiates it from the semi-auto Enforcer (until we add pump-actions again).

The Double-Barreled shotgun and sawn-off had different firerates despite being effectively the same firearm. I've made their firerates both 3 as a compromise.

I also considered increasing the capacity of the Enforcer from 7 to 9 and the capacity of the Bulldog's drum magazine from 8 to 13. This likely would upset the current balance however, where shotguns are already powerful enough in close-quarters combat. I've instead added yml comments suggesting what they _should_ be, as long as their associated issue with shell spread is fixed (#33509).

I've changed the descriptions of the Kammerer, Enforcer and Bulldog to better its stats, typos, etc.

## Technical details

yml changes only

- `Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml`

## Media

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] ~~I have added media to this PR or~~ it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: The Kammerer now holds 7 shells but now fires slightly slower than other shotguns.
- tweak: The Double-Barreled Shotgun and its sawn-off counterpart now share the same firerate.
- tweak: Changed descriptions of the Kammerer, Enforcer and Bulldog.

2024-11-24 08:38 UTC, thebadman4662 commented
Oooh, I like sound of 7 ammo kammerer, even if you only use it as suit slot weapon because you are using satchel its beginning to sound like proper alternative to laser.

2024-11-24 09:12 UTC, Pumkin69 commented
kammerer is always usually the last gun to get grabbed because its magazine capacity and i fucking love shotguns so i think this is overall good.

2024-11-24 09:20 UTC, thebadman4662 commented
> kammerer is always usually the last gun to get grabbed because its magazine capacity and i fucking love shotguns so i think this is overall good.

Make it 1x4 or 2x4 after drozd nerf and its going to be taken like hot potatoes. 😆

2024-11-24 12:18 UTC, Aeshus requested changes
Thanks for the PR!

I just have some thoughts on the description for the weapons.

2024-11-24 12:18 UTC, Aeshus commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
> +  description: And old design yet a faithful favourite weapon of security forces throughout many worlds. Uses .50 shotgun shells.
The original phrasing is a little weird. Plus you misspelled some stuff. 

It kinda feels weird to change the lore from it being the reliable "irregular forces gun" (like the AK-47) to just being another "favorite weapon of security."

```suggestion
  description: An old yet faithful design, and a favorite weapon among irregular forces throughout many worlds. Uses .50 shotgun shells.
```

2024-11-24 12:18 UTC, Aeshus commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
> +  description: A premium semi-auto combat shotgun used by modern security forces. Uses .50 shotgun shells.
I prefer auto being expanded to automatic (more consistency). Also, what are "_modern_ security forces""

```suggestion
  description: A premium semi-automatic combat shotgun, which is the pride of all security forces. Uses .50 shotgun shells.
```

2024-11-25 05:23 UTC, MissKay1994 commented
I believe the Kammerer was intended to be like the riot shotguns used in prisons. The thing I always was bothered by is if that's the case it should be a 4+1 shotgun. I could argue making the capacities more similar to real shotguns along the lines of:
Kammerer (M870) = 4+1
Enforcer (M1014) = 7+1
Bulldog (IDK) = 12+1 or something that would be balanced

If you do do this, you may or may not need to buff the shotgun ammo box to make it still viable and useful. Making the drum 12-13 rounds would mean people would have 24-26 rounds instead of the 16 in the box. Perhaps make the shotgun ammo boxes hold 30 rounds? Now.... I could see the Kammerer be 7+1 with a slower fire rate, but 4+1 is what the M1870 version it's based on holds.

2024-11-25 06:59 UTC, ps3moira commented
Why has no one fixed the Kammerer to be a pump-action shotgun?

2024-11-25 10:15 UTC, thebadman4662 commented
4+1 as in L shotgun or?

2024-11-25 10:18 UTC, KaiserMaus commented
At the moment, we have the ability to saw off a double-barreled shotgun, but what if we had the option to cut down Kammer with a saw?

2024-12-01 05:43 UTC, Aeshus submitted a review, later dismissed
Looks good, just has some eisentests that need to be reran.

2025-01-22 22:01 UTC, Emisse approved these changes

2025-01-30 17:36 UTC, beck-thompson approved these changes
Tested in game and it seems fine! The new descriptions are more fun :)

2025-01-30 17:36 UTC, merged