HealingSystem: check blood restoration, staunching
space-wizards/space-station-14 pull request #33526
Opened 2024-11-24 19:40 UTC by whatston3

## About the PR

Healing objects now check for possible blood restoration or bleeding reduction when checking whether or not to allow or repeat healing.

## Why / Balance

Fixes #28831.

Porting https://github.com/new-frontiers-14/frontier-station-14/pull/2457.

## Technical details

The conditions of HasDamage now check bleeding reduction and target bleeding, and blood restoration and target blood loss.

## Media

A video reproducing the steps for #28831 in the test map.  The moth is struck with a 200 dmg bang stick, and gauze is applied, stopping the moth's bleeding despite the moth having no pierce or slash damage.  The bloodpack is then applied, and repeats successfully, despite the moth having no bloodloss damage.

https://github.com/user-attachments/assets/79e5deb8-b8ea-4436-8f38-4c301a23c45d

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Healing items that reduce bleeding can now be applied to undamaged mobs.

2024-11-25 03:00 UTC, Plykiya commented
does this stop repeated healing with gauze for pierce damage if they happened to be bleeding?

2024-11-25 14:29 UTC, whatston3 commented
> does this stop repeated healing with gauze for pierce damage if they happened to be bleeding?

No.  I think you'll need extra state for that - bleeding reduction, blood restoration, and damage healing are all treated as equally important in all cases.

2024-11-25 21:01 UTC, KashRas2 commented
Frontier is licensed for AGPL3. Does it means that this pr will change licence?

2024-11-25 23:48 UTC, whatston3 commented
I wrote this, I am making this contribution to this repo under the MIT license.

2025-01-20 08:50 UTC, MilonPL commented on Content.Server/Medical/HealingSystem.cs
> +    private bool HasDamage(EntityUid target, DamageableComponent component, HealingComponent healing)
Wouldn't this be better with a `Entity<T1, T2>` signature?

2025-01-20 08:50 UTC, MilonPL commented on Content.Server/Medical/HealingSystem.cs
> +        if(TryComp<BloodstreamComponent>(target, out var bloodstream))
Space after `if`.

2025-01-20 08:50 UTC, MilonPL commented on Content.Server/Medical/HealingSystem.cs
> +                && _solutionContainerSystem.ResolveSolution(target, bloodstream!.BloodSolutionName, ref bloodstream.BloodSolution, out var bloodSolution)
Nullable warning suppression isn't needed here, the if statement above means that bloodstream can never be null.

2025-01-20 08:50 UTC, MilonPL commented on Content.Server/Medical/HealingSystem.cs
> +                && bloodstream!.BleedAmount > 0)
Above.

2025-01-20 18:44 UTC, whatston3 commented
Thanks for the review, I'll make the changes in a bit.

2025-01-20 19:06 UTC, whatston3 commented
Suggestions made where appropriate.

2025-01-21 00:38 UTC, beck-thompson requested changes
Minor style changes rest looks good :+1:

The double popup thing is annoying but I think that's kind of out of scope for this PR

2025-01-21 00:38 UTC, beck-thompson commented on Content.Server/Medical/HealingSystem.cs
> +            if (healing.BloodlossModifier < 0
Just make these one line!

2025-01-21 00:38 UTC, beck-thompson commented on Content.Server/Medical/HealingSystem.cs
> +        if (TryComp<BloodstreamComponent>(ent, out var bloodstream))
I think adding one comment here explaining what this entire section is for would be nice!

2025-01-21 02:52 UTC, whatston3 commented on Content.Server/Medical/HealingSystem.cs
> +        if (TryComp<BloodstreamComponent>(ent, out var bloodstream))
Righto.

2025-01-21 02:58 UTC, whatston3 commented on Content.Server/Medical/HealingSystem.cs
> +        if (TryComp<BloodstreamComponent>(ent, out var bloodstream))
Should be done, let me know if the comments need work.

2025-01-21 03:40 UTC, beck-thompson approved these changes
Looks great! :+1:

2025-02-05 03:23 UTC, MilonPL approved these changes

2025-02-05 03:23 UTC, merged