Cleanup vape and allow it to use any reagent
space-wizards/space-station-14 pull request #33530
Opened 2024-11-24 23:01 UTC by Winkarst-cpu

## About the PR
Title.

## Why / Balance
Resolves #15978. 

## Technical details

## Media

https://github.com/user-attachments/assets/208db0a8-8cee-4d89-a70e-df2c95a1a546

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Now you can vape some reagents without vape exploding.
- fix: Now you can vape by using vape in your hands.

2024-11-26 16:07 UTC, slarticodefast requested changes
This does not address all the points in the issue, in particular prediction. But it is a good start and the rest can be done in another PR

2024-11-26 16:07 UTC, slarticodefast commented on Content.Server/Nutrition/EntitySystems/SmokingSystem.Vape.cs
> +    private void TryVape(EntityUid uid, VapeComponent vape, EntityUid user, EntityUid target)
```suggestion
    private void TryVape(Entity<VapeComponent> vape, EntityUid user, EntityUid target)
```

2024-11-26 17:43 UTC, 7-62x54r commented
Is that water in the first beaker in video showcase? Why does water vapor deal _all 4 of burn damage types?_
There are cigarettes and literal CIGARS which deal zero damage, there are soaked ciggs as well which affect the user only because of the reagent which they were soaked with, now why does water deal damage? It makes zero sense to me.

2024-11-26 19:36 UTC, Aisu9 commented
> > Is that water in the first beaker in video showcase? Why does water vapor deal _all 4 of burn damage types?_ There are cigarettes and literal CIGARS which deal zero damage, there are soaked ciggs as well which affect the user only because of the reagent which they were soaked with, now why does water deal damage? It makes zero sense to me.
> 
> Vapes always dealed damage. They should do it to lungs, but at the moment we don't have proper organs system.

cigarette never dealed damage and yet they deal lung damage in SS13. also lack of clarity in the main post what chems can be used.

2024-11-26 19:37 UTC, Winkarst-cpu commented
> cigarette never dealed damage and yet they deal lung damage in SS13. also lack of clarity in the main post what chems can be used.

Ask the original author 🤷

2024-11-26 19:39 UTC, Aisu9 commented
> > Is that water in the first beaker in video showcase? Why does water vapor deal _all 4 of burn damage types?_ There are cigarettes and literal CIGARS which deal zero damage, there are soaked ciggs as well which affect the user only because of the reagent which they were soaked with, now why does water deal damage? It makes zero sense to me.
> 
> Vapes always dealed damage. They should do it to lungs, but at the moment we don't have proper organs system.

you are the author of this PR, follow guidelines and provide clarity in the PR you write.

2024-11-26 19:40 UTC, Winkarst-cpu commented
> you are the author of this PR, follow guidelines and provide clarity in the PR you write.

There are was damage BEFORE my PR, I didn't touch vape damage to lungs.

2024-11-26 19:57 UTC, Aisu9 commented
> > you are the author of this PR, follow guidelines and provide clarity in the PR you write.
> 
> There are was damage BEFORE my PR, I didn't touch vape damage to lungs.

for this post specifically i meant the chemicals vapes will be able to use.

2024-11-26 19:59 UTC, Winkarst-cpu commented
> for this post specifically i meant the chemicals vapes will be able to use.

Oh, addressed this. Sorry.

2024-11-26 23:54 UTC, slarticodefast requested changes
Emagging the vape works, but gives absolutely no feedback that something happened. Could you play a zap sound maybe like for other devices? There is also supposed to be a popup from the emag, but that does not show up because it calls PopupClient from the server in EmagSystem, which is in shared.

RiggableSystem throws an error if you put the rigged vape into a microwave because it has no battery. Could you add a `false` to the `Resolve` in the `Explode` function so it just cancels normally?

2024-11-26 23:54 UTC, slarticodefast commented on Content.Server/Nutrition/EntitySystems/SmokingSystem.Vape.cs
> +            _adminLogger.Add(LogType.Ingestion, LogImpact.Low, $"{ToPrettyString(target):target} is vape {ToPrettyString(uid)} {SharedSolutionContainerSystem.ToPrettyString(solution)}");
```suggestion
            _adminLogger.Add(LogType.Ingestion, LogImpact.Low, $"{ToPrettyString(target):target} is vaping {SharedSolutionContainerSystem.ToPrettyString(solution)} using {ToPrettyString(uid)}");
```

2024-11-26 23:54 UTC, slarticodefast commented on Content.Server/Nutrition/EntitySystems/SmokingSystem.Vape.cs
> +            _adminLogger.Add(LogType.ForceFeed, LogImpact.Medium, $"{ToPrettyString(user):user} is forcing {ToPrettyString(target):target} to vape {ToPrettyString(uid)} {SharedSolutionContainerSystem
```suggestion
            _adminLogger.Add(LogType.ForceFeed, LogImpact.Medium, $"{ToPrettyString(user):user} is forcing {ToPrettyString(target):target} to vape {SharedSolutionContainerSystem.ToPrettyString(solution)} using {ToPrettyString(uid)}");
```

2024-11-26 23:54 UTC, slarticodefast commented on Content.Server/Nutrition/EntitySystems/SmokingSystem.Vape.cs
> +                target.Value);
```suggestion
                user);
```
you show both popups to the target

2024-11-27 08:51 UTC, Winkarst-cpu commented
> Emagging the vape works, but gives absolutely no feedback that something happened. Could you play a zap sound maybe like for other devices? There is also supposed to be a popup from the emag, but that does not show up because it calls PopupClient from the server in EmagSystem, which is in shared.
GotEmaggedEvent gets cancelled by some other system, but I don't know which.

2024-11-27 08:56 UTC, Winkarst-cpu commented
Also I need to cleanup some system since they create zap sound on emag themselves.

2024-12-18 17:18 UTC, slarticodefast requested changes

2024-12-18 17:18 UTC, slarticodefast commented on Content.Shared/Emag/Components/EmaggedComponent.cs
> +    public SoundSpecifier Sound = new SoundCollectionSpecifier("sparks");
I would keep these on each component being emagged so they can still be customized for each device.

2025-02-12 08:06 UTC, closed without merging