Store/Uplink uses mind entityuid instead of body entityuid
space-wizards/space-station-14 pull request #33553
Opened 2024-11-25 21:02 UTC by ActiveMammmoth

## About the PR

Title says it all really.
## Why / Balance

Originally a part of my Mind Swap PR, I was asked to split this off as a separate PR by Keron. This is necessary to make Mind Swap function correctly; without this the grimoire would be owned by the person who the wizard swaps with, allowing them to not only purchase spells but even refund the spells from the original wizard. Effectively Mind Swap would be just giving up your wiz role to someone else entirely, which obviously is not the intention.

2024-11-26 02:44 UTC, slarticodefast submitted a review, later dismissed
You will need to adjust all the store conditions for this.
For example `BuyerAntagCondition` which gets the mind from the buyer entity, which is now the mind itself.
![grafik](https://github.com/user-attachments/assets/e24aeafa-37c6-46ce-957f-628ae9f63f2c)
Or `BuyerSpeciesCondition` which now checks for `HumanoidAppearanceComponent` on the mind entity instead of the player.

2025-01-10 01:48 UTC, keronshb requested changes
One potential change that I need another maint to sanity check for me. Ran tests in game with wizard and revenant, ran into no issues.

2025-01-10 01:48 UTC, keronshb commented on Content.Server/Store/Systems/StoreSystem.cs
> +        component.AccountOwner ??= new Entity<MindComponent?>(mind, mindComp);
```suggestion
        component.AccountOwner ??= (mind, mindComp);
```

You dont need to make a new Entity, you can just make a tuple.
Might need another maint to sanity check me on this.

2025-01-10 01:52 UTC, metalgearsloth commented on Content.Server/Store/Systems/StoreSystem.cs
> +        component.AccountOwner ??= new Entity<MindComponent?>(mind, mindComp);
The tuple gets cast to entity anyway so entity is probably better.

2025-01-10 01:53 UTC, metalgearsloth commented on Content.Shared/Store/Components/StoreComponent.cs
> +    public Entity<MindComponent?>? AccountOwner = null;
This looks like it should be a datafield and in turn an entityuid, I'm not really sure why it isn't a datafield.

2025-01-16 00:39 UTC, keronshb approved these changes
lg2m

2025-01-29 21:08 UTC, ScarKy0 requested changes
Not fully familiar with this code but get reviewed.

2025-01-29 21:08 UTC, ScarKy0 commented on Content.Shared/Store/ListingCondition.cs
>  using Robust.Shared.Serialization;
Accidental import?

2025-01-29 21:08 UTC, ScarKy0 commented on Content.Shared/Store/Components/StoreComponent.cs
>  using Robust.Shared.Audio;
Accidental import?

2025-01-29 21:08 UTC, ScarKy0 commented on Content.Server/Traitor/Uplink/UplinkSystem.cs
> +
The integration test should be updated instead, this is just weird looking code.

2025-01-29 21:08 UTC, ScarKy0 commented on Content.Server/Store/Systems/StoreSystem.Listings.cs
>  using Content.Shared.Store;
Accidental import?

2025-01-29 21:08 UTC, ScarKy0 commented on Content.Server/Store/Conditions/BuyerDepartmentCondition.cs
Get rid of ent and just use TryComp<T>, way cleaner that way and I don't think theres a differance

2025-01-29 21:08 UTC, ScarKy0 commented on Content.Server/Store/Conditions/BuyerAntagCondition.cs
> +        var roles = roleSystem.MindGetAllRoleInfo(args.Buyer);
Get rid of ent and just do HasComp<T>, cleaner but im unsure if theres a differance here

2025-01-29 21:08 UTC, ScarKy0 commented on Content.Server/Store/Conditions/BuyerJobCondition.cs
> +        jobs.MindTryGetJob(args.Buyer, out var job);
No ent, do TryComp<T>

2025-01-29 21:08 UTC, ScarKy0 commented on Content.Server/Store/Conditions/BuyerSpeciesCondition.cs
> +        if (!ent.TryGetComponent<HumanoidAppearanceComponent>(mind.OwnedEntity, out var appearance))
TryComp<T>

2025-01-29 21:15 UTC, slarticodefast commented
@ScarKy0 The shorthands `TryComp` and `GetComp` are only available inside entity systems.

2025-01-29 21:24 UTC, ScarKy0 commented
> @ScarKy0 The shorthands TryComp and HasComp are only available inside entity systems.

Very good to know for the future, thanks

2025-02-04 16:25 UTC, ScarKy0 approved these changes
Wizard, just a week away

2025-02-04 16:25 UTC, merged