Make shuttle airlocks not snapcardinals
space-wizards/space-station-14 pull request #33557
Opened 2024-11-25 22:33 UTC by Winkarst-cpu

## About the PR
Title.

## Why / Balance
Fixes #33478.

## Technical details

## Media

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-11-25 22:56 UTC, Winkarst-cpu commented
Unrelated failed check?

2024-11-25 23:58 UTC, slarticodefast requested changes

2024-11-25 23:58 UTC, slarticodefast commented on Resources/Prototypes/Entities/Structures/Doors/Airlocks/shuttle.yml
> +    snapCardinals: false
```suggestion
```
inherited from AirlockShuttle

2024-11-25 23:58 UTC, slarticodefast commented on Resources/Prototypes/Entities/Structures/Doors/Airlocks/shuttle.yml
> +    snapCardinals: false
```suggestion
```
inherited

2024-11-26 00:29 UTC, slarticodefast approved these changes
Tested and works as intended.
Thanks for the fix!

2024-11-26 13:51 UTC, merged