Slime plushie now squishes
space-wizards/space-station-14 pull request #33554
Opened 2024-11-25 21:10 UTC by Minemoder5000

## About the PR

The slime plushie now makes the slime squish sounds
## Why / Balance

Parity with other plushies
## Technical details

Added a few .yml lines
## Media

https://github.com/user-attachments/assets/11fe3528-ac73-4981-8b4b-44fe7a8c380c

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Minemoder
- tweak: Slime plushie now squishes.

2024-11-25 21:41 UTC, Minemoder5000 commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +      path: /Audio/Voice/Slime/slime_squish.ogg
Oops

2024-11-26 00:06 UTC, slarticodefast commented
Would this maybe cause problems for players with misophonia? I think some people mentioned they really dislike the squish sound.
You can of course already spam it using the emote as a slime, but this makes it even more common.

2024-11-26 00:23 UTC, Winkarst-cpu commented
> Would this maybe cause problems for players with misophonia? I think some people mentioned they really dislike the squish sound.
> You can of course already spam it using the emote as a slime, but this makes it even more common.

Personally I think that this is should be done as an accessibility setting somehow since most people doesn't mind it.

2024-11-26 00:23 UTC, Minemoder5000 commented
> Would this maybe cause problems for players with misophonia?

It probably would, as well as being easier to spam since it isn't an emote that floods chat.

2024-12-21 04:06 UTC, Thinbug0 commented
this should be like P1 top priority :33

2025-02-05 10:51 UTC, DuckManZach commented
I think if you add the hit sound might as well keep the usesound.
Either way excellent feature!

2025-02-10 06:32 UTC, beck-thompson requested changes
I think it might be better if you add a `EmitSoundOnCollide` for the slime squish as well. Having it beep only when it hits the wall feels weird :thinking:

2025-02-10 06:43 UTC, Minemoder5000 commented
> I think it might be better if you add a `EmitSoundOnCollide` for the slime squish as well. Having it beep only when it hits the wall feels weird 🤔

The lizard plush doesn't weh on collide, nor does the shark. Errant brought up the same issue in #33540. I could fix it for the slime plush specifically, fix it for all of them, or do nothing.

2025-02-10 07:06 UTC, beck-thompson approved these changes

2025-02-13 07:54 UTC, MilonPL approved these changes

2025-02-13 07:55 UTC, merged