Elf Ears
space-wizards/space-station-14 pull request #33572
Opened 2024-11-26 09:42 UTC by Farrellka-dev

## About the PR

I hate those ears - https://github.com/space-wizards/space-station-14/pull/30490.
They have a disgusting yellowish tint that makes you want to vomit. So I added different variations of long (elf) ears.

## Why / Balance

It's simple, I hate these ears in this PR - https://github.com/space-wizards/space-station-14/pull/30490. 
These ears look like a yellow crop of something, but not ears in any way, so I added 6 variations of long ears. Oh, and I also love elves very much, if I may, I can make them, with their own characteristics, like dwarves.

## Technical details

I just added more variations of long ears that don't look like a yellow crop of something. Just pictures, just meta, just prototypes and translations. Nothing special.

## Media

It was before me:
![image](https://github.com/user-attachments/assets/8b7297bf-d24a-42cf-8cb2-fe0a28e7989e)
An example of one of my ears:
![image](https://github.com/user-attachments/assets/1a817d79-0d64-4382-ba44-9e453f9f3319)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-11-26 21:00 UTC, ps3moira commented
Just replace the original since the original doesn't look too good

2024-11-27 08:29 UTC, Farrellka-dev commented
Random error, lmao.

2025-02-04 17:59 UTC, beck-thompson requested changes
Needs art approval I'll ask about that :saluting_face:

2025-02-04 17:59 UTC, beck-thompson commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/ears.yml
> +  id: LongEarsStandard
Keep the id the same so there wont be any issues with people whos characters already have it!

2025-02-04 17:59 UTC, beck-thompson commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/ears.yml
> -  speciesRestriction: [Human, Dwarf]
Same as above, still allow dwarves to have them! Why not have elf dwarves sounds fun :laughing:

2025-02-04 21:13 UTC, Emisse approved these changes

2025-02-04 21:13 UTC, Emisse commented
art approval

2025-02-05 08:08 UTC, Farrellka-dev commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/ears.yml
> -  speciesRestriction: [Human, Dwarf]
Maybe, but only for short ears, so that there is no dissonance.
I'm a little upset about Aegi, but at least they FINALLY reviewed my PR.

2025-02-05 08:23 UTC, beck-thompson commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/ears.yml
> -  speciesRestriction: [Human, Dwarf]
> Maybe, but only for short ears, so that there is no dissonance.
> I'm a little upset about Aegi, but at least they FINALLY reviewed my PR.

After displacement maps become better you should check in again. I'm pretty sure that was the biggest reason for them getting denied :thinking:

2025-02-05 16:48 UTC, beck-thompson approved these changes
We ball... If people end thinking some look weird for humans we can always revert those specific ones. I really can't make any judgement calls but I think they are all mostly fine :laughing:

2025-02-05 16:49 UTC, merged

2025-02-18 03:40 UTC, Sarahon commented
Hate the original all you want, I had to fight tooth and nail to even get humans any level of this customisation.

2025-02-21 16:01 UTC, Farrellka-dev commented
> Hate the original all you want, I had to fight tooth and nail to even get humans any level of this customisation.

Thanks for this one <3