Added New Cocktails and new fill level sprites to existing drinks.
space-wizards/space-station-14 pull request #33570
Opened 2024-11-26 06:43 UTC by RedBookcase

## About the PR
There are just too few cocktails in the game right now, and the fact that we had absolutely none that used absinthe or champagne seemed criminal. So I made some new sprites, added some new drinks, got distracted and added sprites/fill levels for a bunch of drinks that lacked them previously, and got them all finished here.

New drinks include the Caipirinha, Daiquiri, Death In The Afternoon, Empress 75, Espresso Martini, Mayojito, Mimeosa, Mimosa, Moscow Mule, The Sun Also Rises, and the Whiskey Sour.

Old Drinks that now have new sprites or proper fill levels include the Arnold Palmer, Blue Hawaiian, Coconut Rum, Cosmopolitan, Blue Curacao, Emeraldine Melon, Fourteen Loko, Milkshake (Unused Currently), Painkiller, Pina Colada, Red Mead, Rewriter, Roy Rogers, Sake, Shirley Temple, Sol Dry, and Vodka Tonic.

## Why / Balance
Balance should be largely unchanged. A few of the drinks have very minor effects (Moscow Mule contains small amounts of copper, Mayojito causes vomiting and some poison damage, Mimeosa causes mute condition) but none of them are going to be game-breakingly powerful.

## Technical details
Includes lots of changes to files in Textures/Objects/Consumables/Drinks, both in adding new folders for the new drinks and modifying old drinks to add new sprites. Files in Consumable/Drink and Recipies/Reactions were tweaked for the same reason, as were drinks.yml, flavors.yml, alcohol.ftl, and flavor-profiles.ftl.

## Media

![image](https://github.com/user-attachments/assets/ec45b173-15e1-4b15-8103-09b2a7b94310)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added about a dozen new cocktails for the Bartender to mix up, and polished some of the sprites for older drinks.

2024-11-26 06:57 UTC, DieselMohawk requested changes

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/royrogers.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/rewriter.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/red_meadglass.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/pinacolada.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/painkiller.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/milkshake.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/fourteen_loko_glass.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/emeraldglass.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/curacaoglass.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/cosmopolitan.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/coconutrum.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/bluehawaiian.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Textures/Objects/Consumable/Drinks/arnoldpalmer.rsi/meta.json
This meta.json fill is improperly written. Rather than erasing all of the prior credit, simply add that you made fill sprites for it after the initial credit.

2024-11-26 06:57 UTC, DieselMohawk commented on Resources/Prototypes/Recipes/Reactions/drinks.yml
Mojito recipes often times require shaking them, did you intend to remove this recipe step?

2024-11-26 06:58 UTC, DieselMohawk commented
I wish there was an easier way to do that.

2024-11-26 07:56 UTC, RedBookcase commented on Resources/Prototypes/Recipes/Reactions/drinks.yml
Could be considered something of a band-aid solution currently. The recipes added for the Daiquiri and Caipirinha were conflicting with the mojito's recipe. I'll update it to re-add the old mojito recipe and change the Daiquiri/Caipirinha in a way that fixes the conflict.

2024-11-26 18:30 UTC, Everturning commented
add a beret to the mimeosa glass kinda like a lime or umbrella :trollface:

2024-11-26 23:10 UTC, RedBookcase commented on Resources/Textures/Objects/Consumable/Drinks/arnoldpalmer.rsi/meta.json
All meta.json files have been updated with proper credit. Resolving similar conversations.

2024-11-26 23:11 UTC, RedBookcase commented on Resources/Prototypes/Recipes/Reactions/drinks.yml
Has been updated, Mojito once again requires shaking to be made and the Caipirinha recipe now requires Ice to prevent conflicts between the recipes for the two drinks.

2025-02-28 06:20 UTC, DieselMohawk approved these changes
I'm no maintainer, but this looks good to me

2025-03-10 20:14 UTC, Emisse approved these changes

2025-03-10 23:07 UTC, Tayrtahn approved these changes
I would really like it if the drinks that are just a flat color or simple fade had their fill level sprites converted to grayscale so they support being tinted when mixed with other reagents. 
But this PR has sat idle for quite a while and I'm a fan of more bartender content, so I'll leave that as an exercise for the future.

2025-03-10 23:08 UTC, merged

2025-03-11 00:18 UTC, RedBookcase commented
> I would really like it if the drinks that are just a flat color or simple fade had their fill level sprites converted to grayscale so they support being tinted when mixed with other reagents. But this PR has sat idle for quite a while and I'm a fan of more bartender content, so I'll leave that as an exercise for the future.

ITS YOU

![image](https://github.com/user-attachments/assets/8a744d3f-7e5c-427c-91b8-a426303fbb5f)

2025-03-11 02:11 UTC, Tayrtahn commented
Uh oh, caught! 

I may have kinda forgotten about that one...