Fix default view top bar
space-wizards/space-station-14 pull request #33576
Opened 2024-11-26 13:02 UTC by metalgearsloth

CL is weird coz players never saw it but can add.

2024-11-26 14:16 UTC, slarticodefast requested changes
The spacing is a little off.
deadmin:
![grafik](https://github.com/user-attachments/assets/71dcefba-b713-448f-830c-d90c2c1a2913)
readmin:
![grafik](https://github.com/user-attachments/assets/2197f2c0-9559-48eb-bed8-85190fca59fc)

2024-11-29 09:41 UTC, metalgearsloth commented
Turns out it's a gridcontainer bug.

2025-03-21 09:14 UTC, TheShuEd commented
Engine PR was merged over 3 month ago
What the status?

2025-03-21 10:16 UTC, slarticodefast commented
I think this was a fix for another PR that we reverted.
So not sure if this is needed anymore

2025-04-18 21:45 UTC, closed without merging