Localize ai dataset names
space-wizards/space-station-14 pull request #33608
Opened 2024-11-27 19:59 UTC by MilenVolf

## About the PR
This PR is NOT part of #32893 and can be merged freely

## Why / Balance
Localization is good

## Technical details
Type of variable NameDataset in `RoleLoadoutPrototype.cs` was changed from DatasetPrototype to LocalizedDatasetPrototype

## Media

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
AI names now use a localized dataset instead of a dataset
The dataset's ID has been changed from names_ai to NamesAi to fit naming conventions

2024-11-27 20:58 UTC, slarticodefast requested changes

2024-11-27 20:58 UTC, slarticodefast commented on Resources/Prototypes/Loadouts/role_loadouts.yml
> +  nameDataset: NamesAi
```suggestion
  nameDataset: NamesAI
```

2024-11-27 20:58 UTC, slarticodefast commented on Resources/Prototypes/Datasets/Names/ai.yml
> +  id: NamesAi
```suggestion
  id: NamesAI
```

2024-11-27 22:06 UTC, slarticodefast approved these changes

2024-11-27 22:06 UTC, slarticodefast commented
Localization good 👍

2024-12-06 15:37 UTC, VasilisThePikachu approved these changes

2024-12-06 15:38 UTC, merged