Fix BuckleSystem always marking InteractHandEvent as Handled
space-wizards/space-station-14 pull request #33602
Opened 2024-11-27 13:51 UTC by MilenVolf

## About the PR
Title

## Why / Balance
Fixes #33263

## Technical details
This PR adds check for a successful unbuckling before marking InteractHandEvent as Handled

## Media

https://github.com/user-attachments/assets/e497f9ca-3743-46f3-99aa-6cf7c4b5009b
## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Mouses, mothroaches, cockroaches and etc can be picked up once again.

2024-11-27 14:15 UTC, slarticodefast requested changes

2024-11-27 14:15 UTC, slarticodefast commented on Content.Shared/Buckle/SharedBuckleSystem.Interaction.cs
> +            canUnbuckle = TryUnbuckle(ent!, args.User, popup: true);
```suggestion
            args. Handled = TryUnbuckle(ent!, args.User, popup: true);
```
just do it like this and remove canUnbuckle

2024-11-27 14:20 UTC, slarticodefast approved these changes
Tested and works as intended. Thanks for fixing it!

2024-12-01 12:40 UTC, SaphireLattice approved these changes
Unconditional "handled" is bad, yeah

Works fine, does not seem to break things from *very* brief testing

2024-12-01 22:09 UTC, merged