Popup when being pulled shows who is pulling you
space-wizards/space-station-14 pull request #33612
Opened 2024-11-27 21:54 UTC by Plykiya

## About the PR

Adds a popup that indicates the identity of who is pulling you

## Why / Balance

Too often people will attempt to drag people out of the evac shuttle or into emagged recyclers because there is no way OOC to know who is actually dragging you, despite it being information you would 100% be aware of IC

## Technical details

Shows a popup to the entity being pulled with the visible identity name in the popup message

## Media

https://github.com/user-attachments/assets/5393021a-46de-45d2-a183-a28543ffaa4f

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: You are now notified of who is pulling you when being pulled.

2024-11-27 22:11 UTC, MilenVolf requested changes
Good PR, just one nitpick

2024-11-27 22:11 UTC, MilenVolf commented on Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
> +            Loc.GetString("getting-pulled-popup", ("pulling", Identity.Entity(pullerUid, EntityManager)));
```suggestion
            Loc.GetString("getting-pulled-popup", ("puller", Identity.Entity(pullerUid, EntityManager)));
```

2024-11-27 22:11 UTC, MilenVolf commented on Resources/Locale/en-US/movement/pulling.ftl
> +﻿getting-pulled-popup = { CAPITALIZE(THE($pulling)) } begins pulling you.
```suggestion
﻿getting-pulled-popup = { CAPITALIZE(THE($puller)) } begins pulling you.
```

2024-11-27 22:27 UTC, lzk228 approved these changes
nice, as i can tell

2024-11-28 06:35 UTC, MilenVolf approved these changes

2024-11-29 22:36 UTC, lzk228 commented
> Does this show the persons true name or their visible identity?

it uses identity

2024-11-30 03:12 UTC, slarticodefast approved these changes
Good QOL improvement 👍 
Tested and works as intended.

2024-12-09 03:51 UTC, chromiumboy commented
Nice. Test in-game and it works as advertised

2024-12-09 03:51 UTC, merged