Don't show warnings when Serializer isn't from YAML
space-wizards/space-station-14 pull request #3362
Opened 2021-02-21 16:24 UTC by Ygg01

There was an issue that when DefaultSerializer was accessing the entity, it
wasn't setting `countTag` so the component would report a pointless warning. 

Closes #3287

2021-02-23 02:04 UTC, metalgearsloth commented
Would this work if you checked if the serializer was reading instead?

2021-02-26 23:56 UTC, Ygg01 commented
> Would this work if you checked if the serializer was reading instead?

Apparently not
![rider64_oRzST2UVtG](https://user-images.githubusercontent.com/1146204/109367566-ae527880-7896-11eb-8064-d91c06ca5eae.png)

2021-02-27 09:29 UTC, PaulRitter commented
all defaultserializer does is just use the defaultvalues, this isnt a problem with the defaultserializer but with the storagecountercomponent. the warning does make sense tho imo

2021-02-27 09:48 UTC, PaulRitter requested changes
please investigate where the defaultserializer is being used to call this. this workaround isn't valid as this should warn when using it w/ a defaultserializer

2021-02-27 10:59 UTC, closed without merging