great organs reparenting take 2
space-wizards/space-station-14 pull request #33629
Opened 2024-11-28 20:10 UTC by lzk228

reopened #32300

reparented all organs

before

<details>
  <summary>graph in text</summary>

```
digraph {
BaseItem -> BaseAnimalOrganUnGibbable ;
BaseAnimalOrganUnGibbable -> BaseAnimalOrgan ;
BaseAnimalOrgan -> OrganAnimalLungs ;
BaseAnimalOrgan -> OrganAnimalStomach ;
OrganAnimalStomach -> OrganMouseStomach ;
BaseAnimalOrgan -> OrganAnimalLiver ;
BaseAnimalOrgan -> OrganAnimalHeart ;
BaseAnimalOrgan -> OrganAnimalKidneys ;
OrganAnimalStomach -> OrganBloodsuckerStomach ;
OrganAnimalLiver -> OrganBloodsuckerLiver ;
OrganAnimalHeart -> OrganBloodsuckerHeart ;
OrganAnimalStomach -> OrganAnimalRuminantStomach ;
BaseItem -> SentientSlimesCore ;
OrganHumanBrain -> SentientSlimesCore ;
BaseHumanOrgan -> OrganSlimesLungs ;
BaseItem -> BaseArachnidOrgan ;
OrganAnimalStomach -> OrganArachnidStomach ;
BaseArachnidOrgan -> OrganArachnidLungs ;
BaseArachnidOrgan -> OrganArachnidHeart ;
BaseHumanOrgan -> OrganArachnidLiver ;
BaseHumanOrgan -> OrganArachnidKidneys ;
BaseArachnidOrgan -> OrganArachnidEyes ;
BaseArachnidOrgan -> OrganArachnidTongue ;
BaseItem -> BaseDionaOrgan ;
BaseDionaOrgan -> OrganDionaBrain ;
OrganHumanBrain -> OrganDionaBrain ;
BaseDionaOrgan -> OrganDionaEyes ;
BaseDionaOrgan -> OrganDionaStomach ;
BaseDionaOrgan -> OrganDionaLungs ;
OrganDionaBrain -> OrganDionaBrainNymph ;
OrganDionaStomach -> OrganDionaStomachNymph ;
OrganDionaLungs -> OrganDionaLungsNymph ;
MobDionaNymph -> OrganDionaNymphBrain ;
MobDionaNymphAccent -> OrganDionaNymphStomach ;
MobDionaNymphAccent -> OrganDionaNymphLungs ;
OrganHumanHeart -> OrganDwarfHeart ;
OrganHumanLiver -> OrganDwarfLiver ;
OrganHumanStomach -> OrganDwarfStomach ;
BaseItem -> BaseHumanOrganUnGibbable ;
BaseHumanOrganUnGibbable -> BaseHumanOrgan ;
BaseHumanOrganUnGibbable -> OrganHumanBrain ;
BaseHumanOrgan -> OrganHumanEyes ;
BaseHumanOrgan -> OrganHumanTongue ;
BaseHumanOrgan -> OrganHumanAppendix ;
BaseHumanOrgan -> OrganHumanEars ;
BaseHumanOrgan -> OrganHumanLungs ;
BaseHumanOrgan -> OrganHumanHeart ;
BaseHumanOrgan -> OrganHumanStomach ;
BaseHumanOrgan -> OrganHumanLiver ;
BaseHumanOrgan -> OrganHumanKidneys ;
OrganAnimalStomach -> OrganMothStomach ;
OrganHumanStomach -> OrganMothStomach ;
OrganHumanLungs -> OrganRatLungs ;
OrganAnimalStomach -> OrganRatStomach ;
OrganAnimalStomach -> OrganReptilianStomach ;
BaseItem -> SentientSlimeCore ;
OrganHumanBrain -> SentientSlimeCore ;
BaseHumanOrgan -> OrganSlimeLungs ;
OrganHumanLungs -> OrganVoxLungs ;
}
```

</details>

![out](https://github.com/user-attachments/assets/ae998520-8dc0-463f-9fcc-78d1029f6397)

after
<details>
  <summary>graph in text</summary>

```
digraph {
OrganAnimalStomach -> OrganMouseStomach ;
OrganAnimalStomach -> OrganBloodsuckerStomach ;
OrganAnimalLiver -> OrganBloodsuckerLiver ;
OrganAnimalHeart -> OrganBloodsuckerHeart ;
OrganAnimalStomach -> OrganAnimalRuminantStomach ;
SentientSlimeCore -> SentientSlimesCore ;
OrganSlimeLungs -> OrganSlimesLungs ;
OrganAnimalStomach -> OrganArachnidStomach ;
BaseArachnidOrgan -> OrganArachnidStomach ;
BaseOrganLungs -> OrganArachnidLungs ;
BaseArachnidOrgan -> OrganArachnidLungs ;
BaseOrganHeart -> OrganArachnidHeart ;
BaseArachnidOrgan -> OrganArachnidHeart ;
BaseHumanOrgan -> OrganArachnidLiver ;
OrganAnimalLiver -> OrganArachnidLiver ;
BaseArachnidOrgan -> OrganArachnidLiver ;
BaseHumanOrgan -> OrganArachnidKidneys ;
OrganAnimalKidneys -> OrganArachnidKidneys ;
BaseArachnidOrgan -> OrganArachnidKidneys ;
BaseOrganEyes -> OrganArachnidEyes ;
BaseArachnidOrgan -> OrganArachnidEyes ;
BaseOrganTongue -> OrganArachnidTongue ;
BaseArachnidOrgan -> OrganArachnidTongue ;
BaseItem -> BaseBaseOrgan ;
BaseBaseOrgan -> BaseOrgan ;
BaseBaseOrgan -> BaseOrganBrain ;
BaseOrgan -> BaseOrganEyes ;
BaseOrgan -> BaseOrganTongue ;
BaseOrgan -> BaseOrganAppendix ;
BaseOrgan -> BaseOrganEars ;
BaseOrgan -> BaseOrganLungs ;
BaseOrgan -> BaseOrganHeart ;
BaseOrgan -> BaseOrganStomach ;
BaseOrgan -> BaseOrganLiver ;
BaseOrgan -> BaseOrganKidneys ;
BaseOrganLungs -> OrganAnimalLungs ;
BaseAnimalOrgan -> OrganAnimalLungs ;
BaseOrganStomach -> OrganAnimalStomach ;
BaseAnimalOrgan -> OrganAnimalStomach ;
BaseOrganLiver -> OrganAnimalLiver ;
BaseAnimalOrgan -> OrganAnimalLiver ;
BaseOrganHeart -> OrganAnimalHeart ;
BaseAnimalOrgan -> OrganAnimalHeart ;
BaseOrganKidneys -> OrganAnimalKidneys ;
BaseAnimalOrgan -> OrganAnimalKidneys ;
BaseOrganBrain -> OrganDionaBrain ;
BaseDionaOrgan -> OrganDionaBrain ;
BaseOrganEyes -> OrganDionaEyes ;
BaseDionaOrgan -> OrganDionaEyes ;
BaseOrganStomach -> OrganDionaStomach ;
BaseDionaOrgan -> OrganDionaStomach ;
BaseOrganLungs -> OrganDionaLungs ;
BaseDionaOrgan -> OrganDionaLungs ;
OrganDionaBrain -> OrganDionaBrainNymph ;
OrganDionaStomach -> OrganDionaStomachNymph ;
OrganDionaLungs -> OrganDionaLungsNymph ;
MobDionaNymph -> OrganDionaNymphBrain ;
MobDionaNymphAccent -> OrganDionaNymphStomach ;
MobDionaNymphAccent -> OrganDionaNymphLungs ;
OrganHumanHeart -> OrganDwarfHeart ;
OrganHumanLiver -> OrganDwarfLiver ;
OrganHumanStomach -> OrganDwarfStomach ;
BaseOrganBrain -> OrganHumanBrain ;
BaseHumanOrgan -> OrganHumanBrain ;
BaseOrganEyes -> OrganHumanEyes ;
BaseHumanOrgan -> OrganHumanEyes ;
BaseOrganTongue -> OrganHumanTongue ;
BaseHumanOrgan -> OrganHumanTongue ;
BaseOrganAppendix -> OrganHumanAppendix ;
BaseHumanOrgan -> OrganHumanAppendix ;
BaseOrganEars -> OrganHumanEars ;
BaseHumanOrgan -> OrganHumanEars ;
BaseOrganLungs -> OrganHumanLungs ;
BaseHumanOrgan -> OrganHumanLungs ;
BaseOrganHeart -> OrganHumanHeart ;
BaseHumanOrgan -> OrganHumanHeart ;
BaseOrganStomach -> OrganHumanStomach ;
BaseHumanOrgan -> OrganHumanStomach ;
BaseOrganLiver -> OrganHumanLiver ;
BaseHumanOrgan -> OrganHumanLiver ;
BaseOrganKidneys -> OrganHumanKidneys ;
BaseHumanOrgan -> OrganHumanKidneys ;
BaseOrganStomach -> OrganMothStomach ;
OrganAnimalLungs -> OrganRatLungs ;
OrganAnimalStomach -> OrganRatStomach ;
OrganAnimalStomach -> OrganReptilianStomach ;
BaseSlimeOrgan -> SentientSlimeCore ;
BaseOrganStomach -> SentientSlimeCore ;
BaseOrganBrain -> SentientSlimeCore ;
BaseSlimeOrgan -> OrganSlimeLungs ;
BaseOrganLungs -> OrganSlimeLungs ;
OrganHumanLungs -> OrganVoxLungs ;
}
```

</details>

![out](https://github.com/user-attachments/assets/a17c9df7-9756-4f8e-bfd6-8769a2dcdb7b)

2025-05-02 09:00 UTC, Errant-4 requested changes

2025-05-02 09:00 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/arachnid.yml
> +  parent: [OrganAnimalStomach, BaseArachnidOrgan]
All inline lists should have spaces inside the brackets, like you did with the previous ones

2025-05-02 09:00 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/Animal/animal.yml
>    - type: Item
I think ItemComponent is already inherited with these exact values, so this is redundant

2025-05-02 09:00 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/arachnid.yml
>    abstract: true
I saw that you consistently paid attention to put parent before id, thank you. But all abstract definitions should also go before parent and id, the full sequence is `type > abstract > parent > id > categories > name > suffix > description > components.`

2025-05-02 09:00 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/arachnid.yml
> +  parent: [OrganAnimalStomach, BaseArachnidOrgan]
I don't think we should ever inherit from the animal organs on the roundstart species (and in some other cases, like rat king). There is a pricing difference, some other minor details that we either forget about, or have to manually change back anyway (such as the comparatively big block of redefining the entire SolutionContainerManager just to restore the stomach volume.
It would probably be cleaner and shorter to start from the BaseOrgan<Organ> prototypes and add what few values change compared to that

2025-05-02 09:00 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/arachnid.yml
>      sprite: Mobs/Species/Arachnid/organs.rsi
this is already inherited from BaseArachnidOrgan

2025-05-02 09:00 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/arachnid.yml
> +  description: Two was already too many.
Check the arachnid inheritances, something is broken and they get the human sprites. Is it maybe not predictable/deterministic which sprite will be used if both parents specify one? 
![image](https://github.com/user-attachments/assets/ef695ff5-aae6-4867-9227-26492d175a77)

On my branch I specified the sprite on Base((Species))Organ and the state on the BaseOrgan((Organ)) so there was never a possible conflict, but that does require setting up Base((Species))Organ for all the species even if we just use the human sprites

2025-05-02 09:00 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/arachnid.yml
> +  parent: [BaseHumanOrgan, OrganAnimalLiver, BaseArachnidOrgan] #TODO: sprite arachnid liver and change parent from BaseHumanOrgan to BaseArachnidOrgan
Not gonna lie, I... really dislike these triple inheritances. We don't even need anything from BaseArachnidOrgan. I think it would be better to just go with BaseHumanOrgan and BaseOrganLiver, and switch BaseHumanOrgan to BaseArachnidOrgan once there is an arachnid sprite?

2025-05-02 09:00 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/dwarf.yml
>    name: dwarf heart
I'm thinking we should probably just remove the dwarf name designators, since no other species' organs uses distinct names unless the sprite is something very exotic, like slime gas sacs

2025-05-02 09:00 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/rat.yml
> +  suffix: rat
Would arguably be cleaner to just inherit baseorganstomach and give it Animal metabolism

2025-05-02 09:52 UTC, Errant-4 reviewed
Also, all brains from anyone, and diona-nymph's lungs are not showing their descriptions

2025-05-02 09:57 UTC, FairlySadPanda commented on Resources/Prototypes/Body/Organs/dwarf.yml
>    name: dwarf heart
We'll need to resolve if Dwarfs are a human subspecies or not:

yes - should use the same organs
no - should use their own organs outright

2025-05-02 09:58 UTC, FairlySadPanda commented on Resources/Prototypes/Body/Organs/arachnid.yml
> +  parent: [BaseHumanOrgan, OrganAnimalLiver, BaseArachnidOrgan] #TODO: sprite arachnid liver and change parent from BaseHumanOrgan to BaseArachnidOrgan
We shouldn't be importing "base species organ" to another species at all.

2025-05-02 10:01 UTC, FairlySadPanda commented
Can't really make decisions long-term without the strike team but:

Would prefer to group "base" concepts behind _type_ of species not specific species.

E.g:

"BaseHumanoidHeart"
"BaseInsectoidExoskeleton"
"BaseNitrogenBreatherLungs"

Or whatever in the future.

If we make a species that is a "humanoid insectoid nitrogen breather" their organs should inherit from appropriate bases, not random other similar species.

2025-05-02 10:02 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/dwarf.yml
>    name: dwarf heart
This is an irrelevant distinction because Reptilians, Mothpeople and Voxes all just use an identical heart, for example. dwarves are the outlier in this
(Now that I think about it, mothpeople should _definitely_ have custom eyes, but that's a separate issue since we need a sprite)

2025-05-02 10:06 UTC, FairlySadPanda commented on Resources/Prototypes/Body/Organs/dwarf.yml
>    name: dwarf heart
See comment below, we're on the same page.

For the time being we could treat "common" organs as "humanlike" just so we have a good word to describe them that isn't just "human".

2025-05-02 10:21 UTC, Errant-4 commented
I don't see the point in grouping them by categories that are essentially arbitrary. Slime and vox are currently the two nitrogen breathing species, but their lungs have essentially nothing in common. They use different sprites and they have different metabolizers. Insectoid is also not particularly applicable when you consider that not only are MothPeople and Arachnids not _really_ insects, earth spiders are also not insects at all to begin with.
I think the current system of the parents being defined purely functionally is fine:
BaseOrgan prototypes define the components that the organ commonly does, so the specific organ protos only need to make minor adjustments, and designate the sprite state
BaseSpeciesOrgan specifies the sprite to be used (so honestly, right now most species would just use or inherit from BaseHumanOrgan) and any species-specific thing that deviate from "standard" organs, such as Diona not being made of meat

2025-05-02 13:22 UTC, FairlySadPanda commented
Right, but you're saying "base human organ is the template for this diona organ" when it would make more sense to say "base _humanoid_ organ is the template for this diona organ".

Organs are not explicitly tied to a particular species. If I define "mechanical heart" and allow a roboticist to swap out someone's vox heart for it, does that mechanical heart also derive from "base human heart"? That just feels wrong.

2025-05-02 14:48 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/dwarf.yml
>    name: dwarf heart
This note is about the name. We don't _actually_ describe any organ as "human" at any point, in a place that is player visible. All we need to do is simply not name them "dwarf organ", just "organ".

2025-05-02 14:56 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/arachnid.yml
> +  parent: [BaseHumanOrgan, OrganAnimalLiver, BaseArachnidOrgan] #TODO: sprite arachnid liver and change parent from BaseHumanOrgan to BaseArachnidOrgan
While we could certainly just rename the current BaseHumanOrgans to BaseOrgan, to be used as the parent for the other species, and then "derive" a new (completely identical) BaseHumanOrgan off of BaseOrgan. 
I don't know if there would be any point to do so, if BaseOrgan would still use, be historical necessity because of how the sprites are located, a reference to Human/organs.rsi ? I suppose it would mean that there is no _direct_ reference to human organs on every species, so for that reason it might be worth it even if it's just a naming convention

2025-05-02 17:14 UTC, Errant-4 commented
Uuuuuuh, Houston, we have a problem :godo: (I forgot about this one, too)
![image](https://github.com/user-attachments/assets/84151766-0b2e-463c-aaee-3c50d70079ac)

2025-05-02 20:09 UTC, deltanedas commented on Resources/Prototypes/Body/Organs/arachnid.yml
> +  description: Two was already too many.
you have to flip the parents

2025-05-04 21:24 UTC, Errant-4 commented
I will still approve, if someone disagrees they can object.

2025-05-07 19:52 UTC, Errant-4 commented on Resources/Prototypes/Body/Organs/arachnid.yml
> +  description: Two was already too many.
(The other way to fix this and also avoid it ever happening again on organs would be if the parents were always strictly: sprite from one parent, state from the other, as discussed below)

2025-05-18 10:46 UTC, Errant-4 commented
@lzk228 Hi are you coming back to this?

2025-05-18 14:23 UTC, lzk228 commented
yes

2025-05-22 20:30 UTC, closed without merging