Recipes for curtains and tables using carpets now respect stacks.
space-wizards/space-station-14 pull request #33721
Opened 2024-12-04 22:07 UTC by whatston3

## About the PR

Swapped construction graphs using CarpetX tags to use FloorCarpetX materials instead.  Same fix as #31966.

Ports definitions from https://github.com/new-frontiers-14/frontier-station-14/pull/2507 where appropriate.

## Why / Balance

Fixes #27136.  Fixes #25687.

## Technical details

Changes construction graphs for tables to use materials where appropriate.

## Media

The video below shows the construction of 8 separate table types using 8 different colours of carpet.  Each is constructed with a stack of two in the user's hands, and after construction, the user has a stack of one in their hands.

https://github.com/user-attachments/assets/59888e82-e7d7-4a04-b710-1c68066f3c77

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Recipes for coloured curtains and tables now respect stacks.

2024-12-04 22:45 UTC, beck-thompson commented
- 54 diff for an important bugfix? Great pr!!

2025-02-02 21:06 UTC, Plykiya approved these changes
I found no issues with the changes after testing. While the sky blue carpet does exist, it does not have a printable recipe, nor recipes to turn into curtains or tablecloths, so it's not a relevant issue.

2025-02-24 04:31 UTC, Centronias approved these changes

2025-03-30 01:27 UTC, Boaz1111 approved these changes
Looks good to me, thanks for the bugfix! All works in game!

2025-03-30 10:05 UTC, Boaz1111 requested changes
Actually, one thing I missed, the CarpetX tags seem to no longer be used now, and can be deleted.

2025-03-31 02:06 UTC, whatston3 commented
Requested changes made; tests pass.

2025-04-03 10:28 UTC, Boaz1111 approved these changes
LGTM, works in game

2025-04-03 14:45 UTC, merged