Replace obsolete GetAnchoredEntities
space-wizards/space-station-14 pull request #33734
Opened 2024-12-05 12:43 UTC by MilenVolf

## About the PR

For #33279

## Why / Balance

## Technical details

## Media

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-12-05 15:28 UTC, TheShuEd approved these changes

2024-12-07 06:23 UTC, chromiumboy requested changes
Thanks for tidying this up. Just a few things from me

2024-12-07 06:23 UTC, chromiumboy commented on Content.Server/NodeContainer/Nodes/AdjacentNode.cs
>              var gridIndex = grid.TileIndicesFor(xform.Coordinates);
This method is obsolete too, could you do that as well?

2024-12-07 06:23 UTC, chromiumboy commented on Content.Server/NodeContainer/Nodes/NodeHelpers.cs
> +            foreach (var entityUid in mapSys.GetAnchoredEntities(xform.GridUid!.Value, grid, coords))
Null-suppression is best avoided

2024-12-07 06:23 UTC, chromiumboy commented on Content.Server/NodeContainer/Nodes/NodeHelpers.cs
> +            var mapSys = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SharedMapSystem>();
I understand that you can't do a normal dependency injection on a static class, but resolving the entity system each time the function gets called is likely to be problematic. You should get Sloth's input on this

2024-12-07 06:23 UTC, chromiumboy commented on Content.Server/NodeContainer/Nodes/NodeHelpers.cs
> +            var mapSys = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SharedMapSystem>();
See my above comment

2024-12-07 06:23 UTC, chromiumboy commented on Content.Server/NodeContainer/Nodes/PipeNode.cs
> +            var mapSys = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SharedMapSystem>();
Use dependency injection to handle this

2024-12-07 06:23 UTC, chromiumboy commented on Content.Server/NodeContainer/Nodes/PipeNode.cs
> +            var mapSys = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SharedMapSystem>();
See above

2024-12-07 06:23 UTC, chromiumboy commented on Content.Shared/Construction/EntitySystems/AnchorableSystem.cs
> +
```suggestion
```

2025-04-18 07:47 UTC, metalgearsloth commented on Content.Server/NodeContainer/EntitySystems/NodeGroupSystem.cs
> +
System dependency please.

2025-04-18 07:47 UTC, metalgearsloth commented on Content.Server/NodeContainer/Nodes/AdjacentNode.cs
>                  yield break;
Kinda suss it's taking in the xform's griduid and the grid, just use Entity<Grid> for it and have the callers adjust.

2026-06-29 10:47 UTC, metalgearsloth commented
Died to conflict hell.

2026-06-29 10:47 UTC, closed without merging