Christmas Nuke Song
space-wizards/space-station-14 pull request #33752
Opened 2024-12-06 22:29 UTC by Piras314

## About the PR

Adds nukemass by Mrjajkes to the nuke songs for Christmas.

## Why / Balance

## Technical details

## Media

https://www.youtube.com/watch?v=gLSyt7AaqQM

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added Nukemass by Mrjajkes to the nuke songs for christmas!

2024-12-06 22:31 UTC, he1acdvv commented
![image](https://github.com/user-attachments/assets/de3e209a-1b6b-4d55-92ab-14072517775b)

this btw.

2024-12-06 22:32 UTC, Piras314 commented
@Geekyhobo :godo:

2024-12-06 22:48 UTC, ScarKy0 commented
Yes please this is so peak

2024-12-06 23:13 UTC, slarticodefast requested changes

2024-12-06 23:13 UTC, slarticodefast commented on Resources/Audio/StationEvents/attributions.yml
> +  copyright: "Created by Mrjajkes"
```suggestion
  copyright: "Created by mrjajkes"
```
I asked mrjajkes for confirmation that this is the correct licence. But could you fix the name in the attribution like they requested?
![grafik](https://github.com/user-attachments/assets/71a654f3-e07c-4e31-80c8-ab0edbe161d2)

2024-12-07 01:11 UTC, slarticodefast approved these changes

2024-12-07 02:37 UTC, slarticodefast commented
@Geekyhobo Fulfill your promise 😄

2024-12-07 02:39 UTC, Geekyhobo commented
Hi hi hi merry Christmas I approve this pr

2024-12-07 05:58 UTC, chromiumboy commented
Oh yes, this is awesome

2024-12-07 05:58 UTC, merged