Added more ATV names to atv.yml
space-wizards/space-station-14 pull request #33756
Opened 2024-12-07 03:01 UTC by hoganzc

## About the PR
Added additional names to the atv dataset. Took inspiration from other PRs which expanded name data sets. I did not test as I just added additional strings.

## Why / Balance
Many of the other name datasets are much longer. Currently there are only 19. I added 17 more, for 36 total.

## Technical details
Just added additional strings the dataset

## Media

## Requirements
- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-12-07 15:39 UTC, slarticodefast commented
Are these even used anywhere in the game?

2024-12-07 20:34 UTC, ArtisticRoomba commented
probably for downstream

2024-12-07 20:35 UTC, ArtisticRoomba requested changes
there is one name that isn't an ATV name

2024-12-07 20:35 UTC, ArtisticRoomba commented on Resources/Prototypes/Datasets/Names/atv.yml
> +  - Arch-Nemesis Takedown.
this is an ANT name not an ATV name

2024-12-08 05:14 UTC, whatston3 commented
Further suggestions:
- Anti-Tank Vestibule
- Aged Terran Vestige
- Armored Transport Voyager
- Assess This Vroom
- Agile Through Velocity
- All Things Vanish
- Avast The Vapors

2025-04-19 20:14 UTC, slarticodefast commented
Closing this since
- The names aren't even used anywhere
- They are not localized

Thank you for your contribution.

2025-04-19 20:14 UTC, closed without merging