Fixes some mobs not being able to honk/weh
space-wizards/space-station-14 pull request #33777
Opened 2024-12-08 03:17 UTC by ArtisticRoomba

## About the PR
Some mobs can now honk or weh if forced to by reagents.

Vox can now Honk and Weh.
Arachnids can now Honk.
Moths can now Honk.

Keep in mind that they obviously can't do these emotes by default. It's a prohibited emote that is only allowed if a reagent forces them to (like Juice that makes you Weh or Honk).

## Why / Balance
They were missing relevant sounds in the emote sounds YML. Previously, they were unable to honk or weh if forced to by a reagent. They would play the emote, but not the sound.

This change makes it so that they can!

## Technical details
A few YML changes in `speech_emote_sounds.yml`
## Media
![Content Client_uvObiPLDNQ](https://github.com/user-attachments/assets/29c8eac2-2836-4ca1-bbce-d0ccedb904ce)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- fix: Voxes can now honk and weh if forced to by a reagent.
- fix: Arachnids and Moths can now honk if forced to by a reagent.

2024-12-08 19:39 UTC, Aeshus approved these changes
LGTM, though minor nitpick is that the order that you put Honk and Weh seems to be for them...

Also, who doesn't like style changes in another part of the same file :)

2024-12-18 20:01 UTC, ArtisticRoomba commented
conflicts cleared

2025-01-20 00:01 UTC, ScarKy0 requested changes
Everything is almost good, just one missing detail.

2025-01-20 00:01 UTC, ScarKy0 commented on Resources/Prototypes/Voice/speech_emote_sounds.yml
> +      collection: Weh
Please also add Hew to Voxes!

2025-01-20 00:10 UTC, ScarKy0 approved these changes
Hew!
Looks all good and tested in game! Thank you for your contribution!

2025-01-20 00:12 UTC, ScarKy0 commented
Staring at the test in progress, waiting...

2025-01-20 00:13 UTC, ArtisticRoomba commented
running tests on my machine right now because I know this is going to heisentest

2025-01-20 00:21 UTC, merged