Predict gas valves
space-wizards/space-station-14 pull request #33836
Opened 2024-12-12 08:03 UTC by metalgearsloth

## Breaking changes
GasValve shared you know the drill

**Changelog**
:cl:
- tweak: Predict gas valves.

2025-05-13 12:23 UTC, slarticodefast requested changes
got some nitpicks

2025-05-13 12:23 UTC, slarticodefast commented on Content.Client/Atmos/Piping/Binary/Systems/GasValveSystem.cs
> +public sealed class GasValveSystem : SharedGasValveSystem
```suggestion
public sealed partial class GasValveSystem : SharedGasValveSystem
```
makes it easier for forks to add things in separate files

2025-05-13 12:23 UTC, slarticodefast commented on Content.Shared/Atmos/Piping/Binary/Components/GasValveComponent.cs
> +public sealed partial class GasValveComponent : Component
I know it wasn't there before, but please add documentation to the component and datafields

2025-05-13 12:23 UTC, slarticodefast commented on Content.Shared/Atmos/Piping/Binary/Systems/SharedGasValveSystem.cs
> +public abstract class SharedGasValveSystem : EntitySystem
```suggestion
public abstract partial class SharedGasValveSystem : EntitySystem
```

2025-05-13 12:23 UTC, slarticodefast commented on Content.Shared/Atmos/Piping/Binary/Systems/SharedGasValveSystem.cs
> +
```suggestion
```

2025-05-13 12:23 UTC, slarticodefast commented on Content.Server/Atmos/Piping/Binary/EntitySystems/GasValveSystem.cs
> +public sealed class GasValveSystem : SharedGasValveSystem
```suggestion
public sealed partial class GasValveSystem : SharedGasValveSystem
```

2025-05-13 12:23 UTC, slarticodefast commented on Content.Shared/Atmos/Piping/Binary/Systems/SharedGasValveSystem.cs
> +    private void OnInit(EntityUid uid, GasValveComponent component, ComponentStartup args)
```suggestion
    private void OnStartup(Entity<GasValveComponent> ent, ref ComponentStartup args)
```
naming convention, OnInit is for MapInitEvent

2025-05-13 12:23 UTC, slarticodefast commented on Content.Shared/Atmos/Piping/Binary/Systems/SharedGasValveSystem.cs
> +    private void OnActivate(EntityUid uid, GasValveComponent component, ActivateInWorldEvent args)
```suggestion
    private void OnActivate(Entity<GasValveComponent> ent, ref ActivateInWorldEvent args)
```

2025-05-13 12:23 UTC, slarticodefast commented on Content.Shared/Atmos/Piping/Binary/Systems/SharedGasValveSystem.cs
> +        if (!Transform(ent).Anchored)
why did you remove the `IsInDetailsRange` check?

2025-05-13 13:00 UTC, MilonPL requested changes

2025-05-13 13:00 UTC, MilonPL commented on Content.Shared/Atmos/Piping/Binary/Components/GasValveComponent.cs
> +    public bool Open = true;
This needs to either be ReadOnly for VV or we subscribe to AfterAutoHandleState to set appearance correctly because otherwise we have no way of knowing it changed

2025-05-13 14:39 UTC, slarticodefast commented on Content.Client/Atmos/Piping/Binary/Systems/GasValveSystem.cs
> +public sealed class GasValveSystem : SharedGasValveSystem
I was wrong

2025-05-14 14:16 UTC, metalgearsloth commented on Content.Shared/Atmos/Piping/Binary/Systems/SharedGasValveSystem.cs
> +        if (!Transform(ent).Anchored)
It's pretty annoying and you can already visually tell if it's open or not, hiding it from examine didn't really make sense to me as it just punishes newbies.

2025-05-14 15:53 UTC, MilonPL approved these changes

2025-05-14 18:06 UTC, slarticodefast approved these changes
Good stuff 👍

2025-05-14 18:06 UTC, merged