Flora clean up
space-wizards/space-station-14 pull request #33839
Opened 2024-12-12 12:09 UTC by TheShuEd

## About the PR

All tree and rock prototypes are compressed from 3-6 variants into 1, using RandomSprite

## Why / Balance

Reducing the size of prototypes. It just didn't make sense, so I fixed it.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

2024-12-12 17:58 UTC, dvir001 commented
Holy based

2024-12-16 17:10 UTC, slarticodefast requested changes
got a minor nitpick

2024-12-16 17:10 UTC, slarticodefast commented on Resources/migration.yml
> +# 2024-12-16
```suggestion
# 2024-12-01
```
You changed the date here. You should also keep them in chronological order, so move the flora changes below the dungeon master board change.

2024-12-16 19:20 UTC, slarticodefast approved these changes

2024-12-16 19:20 UTC, merged

2025-01-08 10:13 UTC, rosieposieeee commented
this made it impossible to manually map all of these variants...