Other colour of the binary channel
space-wizards/space-station-14 pull request #33841
Opened 2024-12-12 16:40 UTC by Nimfar11

## About the PR
Changes the colour of the binary channel, making it visually different from the medical channel.

## Why / Balance
The binary and medecine channel have virtually the same colour, which is visually indistinguishable. This presents difficulties for AI, cyborg medics and sometimes syndicates. Now the binary channel will have a different tone of blue that will visually distinguish it from the others.

## Technical details

## Media
Before
![изображение](https://github.com/user-attachments/assets/0cc0f061-7053-4c13-ba86-53fe2865e813)
After
![изображение](https://github.com/user-attachments/assets/80839120-ac10-49e4-9a78-868bfd97e4a7)

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

:cl:

- tweak: Changes the colour of the Borg binary channel to a different shade of blue.

2024-12-12 18:02 UTC, SlimmSlamm commented
This is extremely unnecessary considering it says the channel at the start of the message and not a ton of people are even going to be seeing Binary and Medical. Not a good PR imo.

2024-12-12 18:12 UTC, slarticodefast commented
The darker color seems a little harder to read against the background in my opinion.

2024-12-12 18:14 UTC, ArtisticRoomba commented
> This is extremely unnecessary considering it says the channel at the start of the message and not a ton of people are even going to be seeing Binary and Medical. Not a good PR imo.


I disagree, medical borgs interacting with both binary and medical channels is not absolutely unheard of. In fact, I'd say it's a bit common.

Just because it says the name of the channel at the start of the message doesn't mean that we don't need to color the channels. It's quick and intuitive for people to know which channel is which by color alone.

2024-12-12 21:51 UTC, thetolbean commented
> The darker color seems a little harder to read against the background in my opinion.

I agree. I think it should be changed for clarity and ease of use, but the showcased tone doesn't stand out clearly on the background

2024-12-13 02:41 UTC, UbaserB commented
too dark

2024-12-13 02:43 UTC, slarticodefast commented
Ideally we would have icons for the channels anyways in order to help colorblind players.

2024-12-13 06:55 UTC, BigfootBravo commented
I do like this new color, actually! And like others have said, would let borgs and AI tell medical and binary apart a bit easier!

2024-12-13 07:58 UTC, NoElkaTheGod commented
I would really like the binary channel to look like this, but unfortunately green is already reserved for common channel (and the background isn't quite black).
![изображение](https://github.com/user-attachments/assets/c4219782-15db-43b6-9247-797a7e1783eb)

2024-12-13 11:23 UTC, Nimfar11 commented
Made the colour brighter and a little into the green shade.

2024-12-13 11:37 UTC, ScarKy0 requested changes
Could you also change the color of the Station AI Announcement to reflect the new binary color?

2024-12-13 18:14 UTC, ScarKy0 approved these changes

2024-12-14 03:13 UTC, slarticodefast requested changes
The new color looks good to me.
One small thing: The beacon for the AI uses the binary chat color as well, could you update that to the new color?
![grafik](https://github.com/user-attachments/assets/0f39a2a0-3659-4cc0-8e53-858ef8a4958a)

2024-12-14 11:21 UTC, slarticodefast approved these changes
Thank you for your contribution!

2024-12-14 16:03 UTC, merged