Add basic discord client integration with ooc and admin chat support
space-wizards/space-station-14 pull request #33840
Opened 2024-12-12 12:54 UTC by Simyon264

## About the PR

This PR adds an integrated discord client into the game and also adds support for an OOC and admin chat relay.
## Why / Balance

Setting up MoMMi is bad and the source code is outdated and it barely runs and having to rely on more outside services to host sucks. Ideally everything should be integrated with the game.

## Technical details

There are two components that make this work. Theres `DiscordLink` which handles the discord connection and contains the needed proxy methods. Then there is `DiscordChatLink` which subscribes to message events on the discord client and contains the methods to send a message to the discord channel that gets called in `ChatManger`.

## Media

![image](https://github.com/user-attachments/assets/ee099997-b67f-444b-a840-80b6d390689b)
![image](https://github.com/user-attachments/assets/cd5a3b3f-ac06-461f-87ba-3830ce123fd3)
![image](https://github.com/user-attachments/assets/91769a1d-bb06-4b89-897b-cb866f538066)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

`MoMMILink` and the corresponding CVars have been removed. To setup a new relay, change the following cvars:

```toml
[discord]
token = "<token>"
guild_id = 000000000000000000

[ooc]
discord_channel_id = 000000000000000000

```

For the new admin chat relay add the following line:
```toml
[admin]
chat_discord_channel_id = 000000000000000000
```

2024-12-14 16:00 UTC, PJB3005 commented
Linking previous PR: #23458

2024-12-15 23:26 UTC, PJB3005 requested changes
Mostly looks pretty good.

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +public sealed class DiscordLink : IPostInjectInit
Need doc comments.

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +    public void PostInject()
```suggestion
    void IPostInjectInit.PostInject()
```

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +        if (_configuration.GetCVar(CCVars.DiscordGuildId) == string.Empty || _configuration.GetCVar(CCVars.DiscordPrefix) == string.Empty)
Access these CVars through the fields you store for them.

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +            _client = null;
You should check this before creating `_client`, so that you don't have to throw it away later.

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +            _client.StopAsync();
You probably need to await these.

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +            _client.Log -= Log;
You probably shouldn't be unregistering this so that log messages during shutdown aren't eaten.

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +        return msg.Exception is null ? $"{msg.Source}: {msg.Message}" : $"{msg.Source}: {msg.Exception}\n{msg.Message}";
Should you not be printing the exception after the message in this case?

You'd get:
```
foobar: IndexOutOfRangeException
At stacktrace
At stacktrace
At stacktrace
At stacktrace
Error while doing X
```
which doesn't make much sense.

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +            Arguments = split.Skip(1).ToArray(),
```suggestion
            Arguments = split[1..],
```

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordChatLink.cs
> +    [Dependency] private IConfigurationManager _configurationManager = default!;
```suggestion
    [Dependency] private readonly DiscordLink _discordLink = default!;
    [Dependency] private readonly IConfigurationManager _configurationManager = default!;
```

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordChatLink.cs
> +            }
You should filter for channels outside the `RunOnMainThread()`, so that you're not bothering the main thread for every message in the Discord server.

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordChatLink.cs
> +        _ = _discordLink.SendMessageAsync(channelId.Value, $"**{channel.ToString().ToUpper()}**: `{author}`: {message}");
You need to await this in an async void at least so any possible exceptions aren't discarded.

2024-12-15 23:26 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordChatLink.cs
> +        _ = _discordLink.SendMessageAsync(channelId.Value, $"**{channel.ToString().ToUpper()}**: `{author}`: {message}");
Also do not use `channel.ToString().ToUpper()`, you're using an identifier as a user-presented value here.

2025-03-21 09:18 UTC, TheShuEd commented
This PR has been in “Awaiting changes” status for over 3 months now without any visible updates, so I'm closing it as derelict. If you nevertheless plan to continue, please comment it and the PR will be reopened.

If you need help, you can ask questions in discord or in this PR

(i am very sad closing this) 😢

2025-05-15 07:48 UTC, Simyon264 commented
I am picking this up again.

2025-05-23 21:00 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +        var split = content[BotPrefix.Length..].Split(' ', StringSplitOptions.RemoveEmptyEntries);
Doing argument splitting in such a simplistic manner makes it impossible to pass arguments that contain spaces. It seems like a bad limitation to have.

2025-05-23 21:01 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +            _sawmill.Error("Tried to send a message to Discord but the channel was not found.");
Log which channel.

2025-05-23 22:06 UTC, Simyon264 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +        var split = content[BotPrefix.Length..].Split(' ', StringSplitOptions.RemoveEmptyEntries);
The arguments array is just meant to make simple commands easier. Anything more complicated can call upon the message object to get the raw message. I think this is fine to keep.

2025-05-24 18:21 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +        var split = content[BotPrefix.Length..].Split(' ', StringSplitOptions.RemoveEmptyEntries);
I would recommend having the same system as console commands in that case, where everything *after* the command prefix is given. So commands don't have to do the work of stripping the prefix themselves.

2025-05-24 18:21 UTC, PJB3005 commented on Content.Server/Discord/DiscordLink/DiscordLink.cs
> +            _client = null;
This isn't necessary anymore given the client hasn't been created in this case.

2025-05-24 18:49 UTC, merged

2025-05-24 18:51 UTC, Simyon264 commented
after all these years, finally discord bot in content