Show battery level for selected devices in Power Monitoring Console
space-wizards/space-station-14 pull request #33854
Opened 2024-12-14 11:58 UTC by ArtisticRoomba

## About the PR
Adds a charge percentage and charge bar to applicable devices in the Power Monitoring Console.

This is a revival of derelict PR #26793, originally coded by Crotalus. I've tried to make it look decent, this is my first PR touching any drop of C#.

## Why / Balance
Extremely needed QOL feature. This tells engineers battery levels across the station and can prove EXTREMELY USEFUL to know. Really gives you a good idea as to where power is moving around in the station, and how the grid behaves as a whole.

## Technical details
* Added battery level indicators to the `PowerMonitoringButton` class, including a progress bar and percentage label for visual representation of battery levels.

* Refactored `GetPrimaryPowerValues` into `PowerStats` class to encapsulate power statistics.

* Updated the `PowerMonitoringConsoleEntry` struct to include a nullable `BatteryLevel` property to store battery level information. (`Content.Shared/Power/SharedPowerMonitoringConsoleComponent.cs`)

## Media
![Content Client_lXdI8RzX5P](https://github.com/user-attachments/assets/18559c26-be27-425d-a95c-c2bee6867510)

![Content Client_It40NkmUXX](https://github.com/user-attachments/assets/c4e216a1-215e-40c4-b655-1cb7d26cf604)

![Content Client_zA0560SVIF](https://github.com/user-attachments/assets/4278db12-6648-4ad0-a6ff-22a355a0321d)

## Small Note
Heya. It's the idiot that doesn't know how to code.

There's a bug that I need help fixing. The PR is fine right now, but it could be better.

When you click on a main entry in the power monitoring console, a bunch of *child* entries open up. These entries are supposed to be drawn with the battery percentages and progress bar as well, however this doesn't actually show in-game.

I did some debugging and saw that the `PowerMonitoringConsoleEntry[]` struct list doesn't have a BatteryValue float, while `PowerMonitoringConsoleEntry` does when applicable. I think this is boiled down to it not being recorded somewhere in `PowerMonitoringConsoleSystem`, however I don't have experience nor the time right now to go further than what I've already done.

If anyone could give me some pointers that would be nice.

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Shouldn't be any.

**Changelog**
:cl: Crotalus, ArtisticRoomba
- add: Battery levels of applicable devices are now shown in the Power Monitoring Console.

2024-12-14 15:16 UTC, PJB3005 requested changes
> I did some debugging and saw that the PowerMonitoringConsoleEntry[] struct list never has a BatteryLevel float (null), while PowerMonitoringConsoleEntry does when applicable. Because the value is always null, the battery info is never drawn.
> 
> I think this is boiled down to it not being recorded somewhere in PowerMonitoringConsoleSystem, however I don't have experience nor the time right now to go further than what I've already done.

There are other places in the system code where these `PowerMonitoringConsoleEntry` values are being made, you should update them too.

2024-12-14 15:16 UTC, PJB3005 commented on Resources/Locale/en-US/components/power-monitoring-component.ftl
> +power-monitoring-window-battery-level = {$percentage}%
This isn't used.

2024-12-14 15:16 UTC, PJB3005 commented on Content.Client/Power/PowerMonitoringWindow.xaml.Widgets.cs
> +            var color = Color.FromHsv(new Vector4((batteryPercentage / 100f) * 0.33f, 1, 1, 1));
Why not use `entry.BatteryLevel.Value` directly? You're dividing and then multiplying by 100 here.

2024-12-14 15:16 UTC, PJB3005 commented on Content.Client/Power/PowerMonitoringWindow.xaml.Widgets.cs
> +            button.BatteryPercentage.Text = $"{batteryPercentage}%";
You should use `.ToString("P0")` instead so this localizes properly.

2024-12-14 15:16 UTC, PJB3005 commented on Content.Client/Power/PowerMonitoringWindow.xaml.Widgets.cs
> +            Value = 0,
You're just setting all of these to the default, there's no point to.

Also set `MaxValue` to 1 so you can avoid multiplying by 100 when setting the value.

2024-12-14 15:16 UTC, PJB3005 commented on Content.Client/Power/PowerMonitoringWindow.xaml.Widgets.cs
> +            SetWidth = 45f,
You should probably set a MinWidth instead so the layout doesn't break when we get the ability for users to select custom fonts.

2024-12-14 15:16 UTC, PJB3005 commented on Content.Client/Power/PowerMonitoringWindow.xaml.Widgets.cs
> +            HorizontalAlignment = HAlignment.Right,
This doesn't do anything.

2024-12-14 15:16 UTC, PJB3005 commented on Content.Client/Power/PowerMonitoringWindow.xaml.Widgets.cs
> +            HorizontalAlignment = HAlignment.Right,
This doesn't do anything.

2024-12-14 15:16 UTC, PJB3005 commented on Content.Server/Power/EntitySystems/PowerMonitoringConsoleSystem.cs
> +    private sealed class PowerStats
This should be a struct.

2024-12-15 03:33 UTC, ArtisticRoomba commented
> There are other places in the system code where these `PowerMonitoringConsoleEntry` values are being made, you should update them too.

I addressed your review, however I admittedly don't know where exactly these values are being made, after I spent some time searching in the relevant system. I'll look around some more. Sorry.

2024-12-15 03:56 UTC, ArtisticRoomba commented
NEVERMIND
![image](https://github.com/user-attachments/assets/423c928f-c2c4-4cdb-bc74-121d896fb1fd)

2024-12-18 17:39 UTC, PJB3005 approved these changes

2024-12-19 00:46 UTC, slarticodefast approved these changes
Blessed PR.
Tested and works as intended.

2024-12-19 00:46 UTC, merged

2025-07-26 00:09 UTC, superjj18 commented
I just want to say, I know this change took place on the 12/18/24, but I would still nominate this for best change of 2025 because holy fuck this change revolutionized engineering.  The technical issues you can diagnose just by looking at the console are amazing.  I dont think any other engi PR has changed engineering so drastically with so small a change.  Genuinely bravo