[Christmas] Y'all want a Smite Cranberry?
space-wizards/space-station-14 pull request #33922
Opened 2024-12-18 02:06 UTC by FairlySadPanda

## About the PR

![image](https://github.com/user-attachments/assets/951dbe9c-d16a-4675-998f-a0748767f7d8)

## Why / Balance

![image](https://github.com/user-attachments/assets/5f7e8472-648d-432a-ae14-a83bbed82e82)

(Mostly a thank-you to the mods and admins 

## Technical details

1. Added Smite Cranberry, including both the can and the re-agent.
2. Renamed Lemon-Lime to Smite to match; there's no other changes.

## Media

![image](https://github.com/user-attachments/assets/04b6b8fa-15ae-453c-af3f-170e1a1cebe5)

Sprite by @august-sun 

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Smite Cranberry is now available wherever lemon-lime soda is sold, just for the holidays.

2024-12-18 02:07 UTC, FairlySadPanda commented
Immediate suggestion from @IProduceWidgets - an alcoholic variant to put in the booze-o-mat.

2024-12-18 02:09 UTC, FairlySadPanda commented
It would be good to have some way of marking up items and vending machine contents as seasonal, and being able to hang these features off of a seasonal cvar setting.

2024-12-18 02:11 UTC, FairlySadPanda commented
Other name suggestions

1. Slips/Slips Cranberry @august-sun 
2. Smite/Cranberry Smite @Plykiya

2024-12-18 02:12 UTC, FairlySadPanda commented
I should like to point out that after my extended break and vow to only review stuff on here for a long while, this stupid meme has brought me back

curse you all

2024-12-18 02:15 UTC, FairlySadPanda commented on Resources/Prototypes/Recipes/Reactions/drinks.yml
> +    ZombieCocktail: 4
This added newline is so minor I really don't want to have to faff removing it...

2024-12-18 02:26 UTC, beck-thompson commented
(High because it needs to be added before christmas!)

2024-12-18 02:50 UTC, august-sun commented
> I should like to point out that after my extended break and vow to only review stuff on here for a long while, this stupid meme has brought me back
> 
> curse you all

that's why we do this 😎

2024-12-18 04:49 UTC, Emisse commented
arbitrage fail

2024-12-18 11:27 UTC, TeenSarlacc commented
it's the thirst thirstiest time

2024-12-18 23:12 UTC, FairlySadPanda commented
OK y'all I may have slightly more to this PR

2024-12-18 23:24 UTC, FairlySadPanda commented
https://github.com/user-attachments/assets/e453f898-27e7-4098-baee-4c6bb924b946

2024-12-18 23:32 UTC, Emisse approved these changes

2024-12-18 23:42 UTC, slarticodefast requested changes

2024-12-18 23:42 UTC, slarticodefast commented on Resources/Locale/en-US/reagents/meta/consumable/drink/soda.ftl
> +reagent-desc-lemon-lime-cranberry = tart cranberry, Christmas, and a hint of lemon and lime
```suggestion
reagent-desc-lemon-lime-cranberry = Tart cranberry, Christmas, and a hint of lemon and lime.
```

2024-12-18 23:42 UTC, slarticodefast commented on Resources/Textures/Objects/Consumable/Drinks/lemon-lime-cranberry.rsi/meta.json
> +      "delays": [
Why do the inhands have delays?

2024-12-18 23:48 UTC, FairlySadPanda commented on Resources/Textures/Objects/Consumable/Drinks/lemon-lime-cranberry.rsi/meta.json
> +      "delays": [
Parity with lemon-lime.rsi

2024-12-18 23:48 UTC, FairlySadPanda commented on Resources/Textures/Objects/Consumable/Drinks/lemon-lime-cranberry.rsi/meta.json
> +      "delays": [
(they'll never know I copy-pasta'd)

2024-12-19 00:11 UTC, slarticodefast approved these changes

2024-12-19 00:11 UTC, merged