Action charges refactor
space-wizards/space-station-14 pull request #33993
Opened 2024-12-21 23:04 UTC by metalgearsloth

- Fixes the slight godmoding of baseactioncomponent.
- Gets back 1ms of server time.<

## Breaking changes
Charges got moved to ActionCharges + ResetChargesComponents.

2024-12-22 10:54 UTC, deltanedas commented
kid named LimitedChargesComponent

2025-01-07 00:43 UTC, metalgearsloth commented
> kid named LimitedChargesComponent

LimitedCharges needs reworking...

2025-02-04 22:08 UTC, keronshb commented
DNM until Wizard is released and action plan post-launch is finalized.

2025-03-05 05:00 UTC, iaada reviewed
I hope you don't mind some random contributer nitpicking...

2025-03-22 02:28 UTC, metalgearsloth commented on Content.Shared/Charges/Systems/ChargesSystem.cs
> +        if (GetCurrentCharges((uid, comp, null)) == comp.MaxCharges)
There was some reason I didn't but it's probably not relevant anymore.

2025-03-29 17:23 UTC, keronshb requested changes

2025-03-29 17:23 UTC, keronshb commented on Resources/Prototypes/Magic/projectile_spells.yml
> -    renewCharges: true
I forgot to remove renew charges from here. The use delay should still be intact.

From discord, @ActiveMammmoth said that "also when used for the first time, the sprite becomes greyed out forever, even after cooldown finishes"

2025-03-29 17:23 UTC, keronshb commented on Resources/Prototypes/Magic/projectile_spells.yml
> -      renewCharges: true
I forgot to remove renew charges from here. The use delay should still be intact.

2025-03-29 17:25 UTC, keronshb commented
@ActiveMammmoth had this feedback from discord:

- ActionOnInteract staves don't work correctly
- Spell upgrades don't work correctly

2025-03-29 17:39 UTC, ActiveMammmoth commented
Apologies if I'm reiterating anything that Keron has mentioned.
- ActionOnInteract staves currently don't recognize their charge count and allow for infinite usage with zero delay (Staff of Animation, RGB Wand)
- Action sprites appear to be greyed out despite being available for use
- Action cooldown and action charge cooldown seem to be two separate things which causes issues. Example being Fireball lvl 3 which has a charge cooldown of 8 seconds as intended but a regular cooldown of 15 seconds which prevents it from being usable despite being recharged.

2025-03-29 17:43 UTC, keronshb commented on Content.Client/Actions/ActionsSystem.cs
> +            action.IconColor = _charges.GetCurrentCharges(actionId.Value) < 1 ? action.DisabledIconColor : action.OriginalIconColor;
If something doesn't have a limited charges component, like Scream or Combat Mode, this makes those actions start greyed out.

2025-03-29 17:52 UTC, keronshb commented on Content.Shared/Actions/SharedActionsSystem.cs
> -
This makes an unintended huge nerf.
If you have something with 2 charges and a use delay, the action fires off, so does the use delay, and then you're unable to use an action _until_ the use delay is up. 

The behavior should be:
If an action still has charges remaining, use delay should not trigger until the charges are used up.

2025-04-06 12:53 UTC, metalgearsloth commented on Content.Shared/Actions/SharedActionsSystem.cs
> -
Charges didn't work before and I'm not super interested in design changes to it in the same PR, I'm mainly worried about the big performance issues charges are causing atm. This is effectively a selective revert without having to completely remove everything.

2025-04-06 17:34 UTC, keronshb commented on Content.Shared/Actions/SharedActionsSystem.cs
> -
We need some sort of information to the player that a charge is recharging. Even if it's just a timer on the examine text.

And logic should be:
Use delay is never longer/equal to the recharge timer.

2025-04-07 04:06 UTC, metalgearsloth commented
> Apologies if I'm reiterating anything that Keron has mentioned.
> 
>     * Action cooldown and action charge cooldown seem to be two separate things which causes issues. Example being Fireball lvl 3 which has a charge cooldown of 8 seconds as intended but a regular cooldown of 15 seconds which prevents it from being usable despite being recharged.

This was already existing with the charges PR.

I think we need to prioritise fixing the performance problems and should either just revert charges entirely if this pr is insufficient or leave it for now. Content shouldn't take priority over 1ms of server time being wasted. I pointed out this could happen in the original PR but let it slide and then it did anyway so there's precedent that it was known in advance it would need reverting.

2025-04-07 04:13 UTC, keronshb commented
> > Apologies if I'm reiterating anything that Keron has mentioned.
> > ```
> > * Action cooldown and action charge cooldown seem to be two separate things which causes issues. Example being Fireball lvl 3 which has a charge cooldown of 8 seconds as intended but a regular cooldown of 15 seconds which prevents it from being usable despite being recharged.
> > ```
> 
> This was already existing with the charges PR.
> 
> I think we need to prioritise fixing the performance problems and should either just revert charges entirely if this pr is insufficient or leave it for now. Content shouldn't take priority over 1ms of server time being wasted. I pointed out this could happen in the original PR but let it slide and then it did anyway so there's precedent that it was known in advance it would need reverting.

Previously the UseDelay also conveyed Charges. We didn't have support (at the time) to do individual charges recharging, so instead I intentionally had all charges recharge at once with the usedelay.

Now that the Use Delay and Recharge Timer are independent of each other, we now have a scenerio where Use Delay times could be larger than or equal to the Recharge Timer.

So we 100% need to convey this to the player somehow or this will look unfinished.

If doing an animation is out of scope, I'm asking for you to just convey the time on the examine screen (like how remaining / charges are). And I'm asking to do another pass to see which Use Delays are longer or equal to the Recharge Times and to reduce the Use Delays significantly so the Charges recharge properly.

2025-04-12 22:17 UTC, keronshb submitted a review, later dismissed
New changes requested.
Staff of Animation still has an issue and me and Mammmoth are looking into it.

2025-04-12 22:17 UTC, keronshb commented on Content.Shared/Charges/Systems/SharedChargesSystem.cs
> +    private TimeSpan GetNextRechargeTime(Entity<LimitedChargesComponent?, AutoRechargeComponent?> entity)
```suggestion
    public TimeSpan GetNextRechargeTime(Entity<LimitedChargesComponent?, AutoRechargeComponent?> entity)
```

public for where this will be used.

2025-04-12 22:17 UTC, keronshb commented on Content.Client/UserInterface/Systems/Actions/Controls/ActionButton.cs
> +            return new ActionAlertTooltip(name, decr, charges: chargesText);
```suggestion
            var charges = _sharedChargesSys.GetCurrentCharges((ActionId.Value, actionCharges, null));
            var chargesText = FormattedMessage.FromMarkupPermissive(Loc.GetString($"Charges: {charges.ToString()}/{actionCharges.MaxCharges}"));

            if (_entities.TryGetComponent(ActionId, out AutoRechargeComponent? autoRecharge))
            {
                var chargeTimeRemaining = _sharedChargesSys.GetNextRechargeTime((ActionId.Value, actionCharges, autoRecharge));
                chargesText.AddText(Loc.GetString($"{Environment.NewLine}Time Til Recharge: {chargeTimeRemaining}"));
            }

            return new ActionAlertTooltip(name, decr, charges: chargesText);
```

This way we relay the info back to the user how long the next charge will be.

![image](https://github.com/user-attachments/assets/3c07286e-7cd7-49c0-a409-c08b6422eb4b)

![image](https://github.com/user-attachments/assets/3aa09cc5-1f4b-4c6d-8d88-f3a5e4c37112)

2025-04-12 22:17 UTC, keronshb commented on Content.Shared/Charges/Systems/SharedChargesSystem.cs
>      }
What happens right now is if this is called, it gets the charge time right?
But if another charge is used, this is reset.

So if you had limited charge to 3/3 and auto charge to 20 seconds and you used an action, the action goes to 2/3 and the timer starts. Works as expected.
If you fire off another charge while the timer is active, the timer will reset. So the action goes to 1/3 and the timer goes back to 20 seconds. The first charge still doesn't continue counting down and instead you need to wait another full 20 for the charge to recharge.

I don't think this is breaking enough for me to want to hold up the PR, but please put a TODO: with the bug information in this method so someone can look at it in the future.

2025-04-14 08:42 UTC, metalgearsloth commented on Content.Client/UserInterface/Systems/Actions/Controls/ActionButton.cs
> +            return new ActionAlertTooltip(name, decr, charges: chargesText);
This shouldn't even be hardcoded in here to begin with?

2025-04-14 13:37 UTC, keronshb commented on Content.Client/UserInterface/Systems/Actions/Controls/ActionButton.cs
> +            return new ActionAlertTooltip(name, decr, charges: chargesText);
Can you explain more why you think this is hardcoded here?
This wouldn't be changed in the action refactor I have planned unless I had someone to work on an actual animation for charges & recharge time on the refactor.

What really is the issue of showing people the information they need instead of keeping it hidden? I do not want recharge time to _not_ be conveyed to the user.

2025-04-18 02:07 UTC, metalgearsloth commented on Content.Client/UserInterface/Systems/Actions/Controls/ActionButton.cs
> +            return new ActionAlertTooltip(name, decr, charges: chargesText);
For future archaeologists tl;dr is that any number of systems may want to modify tooltips like itemstatus, alerts, or actual tooltips, but for now it's just being slapped in.

2025-04-18 03:45 UTC, merged