Changeling devour transform
space-wizards/space-station-14 pull request #34002
Opened 2024-12-22 02:48 UTC by poklj

## About the PR

Adds Changelings Devour and Transform Componentry and Systems to Achieve what is set out in The [Changeling Doc ](https://docs.spacestation14.com/en/space-station-14/round-flow/proposals/changeling.html)

With the new components and Systems a Player is able to Consume Other humanoids for their Identities to later Assume their visage, speaking and all things that make up them.
## Why / Balance

Followed https://docs.spacestation14.com/en/space-station-14/round-flow/proposals/changeling.html directly.

Assumptions made not defined within the doc:
Devour can be used on a living being
Devour does 25 damage per second after windup (10/10/5 slash/pierce/blunt)

Double pressing the transform button will transform into the last Identity Consumed

Fingerprints are the Tell for changelings, While everything from their Gender, DNA, TypingBubble, voice descriptor are changed, their Fingerprints will always be the original Identities prints

## Technical details

Added ChangelingTransformComponent and System for controlling Transformation
Added ChangelingDevourComponent and System for managing the action of Consuming people
Added ChangelingIdentityComponent and System for Storing references to Consumed Identities and managing aspects that require additional functionality for devouring and Consuming (like spawning clone's of victims into nullspace as well as assisting with Pvs)

Identities when consumed are stored in nullspace via the HumanoidAppearanceComponent's Clone appearance function, and are paused. These entities will be Forced Into the PVS of the changeling so that later when the Transform Ui is utilized, these entities can be used to show the sprites of the identity.

During transform all information is transferred from these nullspace entities onto the acting entity.

## Media

https://github.com/user-attachments/assets/86e76e95-fd3f-482c-adc2-a2a5801ba350

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Moved DNA into Shared
Moved HumanoidAppearanceComponent::CloneAppearance into Shared

**Changelog**

No CL No Fun (yet)

2025-01-28 04:47 UTC, keronshb submitted a review, later dismissed

2025-01-28 04:47 UTC, keronshb commented on Content.Shared/Armor/SharedArmorSystem.cs
> +
I know this is still in draft but anything ling related shouldn't be in the armor system. What are you trying to do?

2025-01-28 05:03 UTC, poklj commented on Content.Shared/Armor/SharedArmorSystem.cs
> +
This was brought up in Developer and is being changed to be a query of some form for the coefficents. 

Was caused as a failure to understand what InventoryRelays do and how to make one, and has been clarified (will be the next commit i do)

2025-02-17 20:23 UTC, poklj commented
Waiting on Active Devour and Transform sounds. but good for review

2025-02-17 21:01 UTC, poklj commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        CopyComp<SpeechComponent>(targetIdentity, ent, out _);
Use CopyComps (once it's complete) rather than CopyComp

2025-02-17 22:14 UTC, ScarKy0 requested changes
Something something shitcode
Just kidding

Mostly a syntax review and stuff, you ate a lot of whitespaces and added too many in some places. I'll do a more in-depth review for things in a week(tm)

2025-02-17 22:14 UTC, ScarKy0 commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +}
```suggestion
[Serializable, NetSerializable]
public sealed class ChangelingTransformIdentitySelectMessage : BoundUserInterfaceMessage
{
    public readonly NetEntity TargetIdentity;

    public ChangelingTransformIdentitySelectMessage(NetEntity targetIdentity)
    {
        TargetIdentity = targetIdentity;
    }
}

[Serializable, NetSerializable]
public sealed class ChangelingIdentityData
{
    public readonly NetEntity Identity;
    public string Name;

    public ChangelingIdentityData(NetEntity identity, string name)
    {
        Identity = identity;
        Name = name;
    }
}

[Serializable, NetSerializable]
public sealed class ChangelingTransformBoundUserInterfaceState : BoundUserInterfaceState
{
    public readonly List<ChangelingIdentityData> Identites;
    public ChangelingTransformBoundUserInterfaceState(List<ChangelingIdentityData> identities)
    {
        Identites = identities;
    }
}

[Serializable, NetSerializable]
public enum TransformUi : byte
{
    Key,
}
```
Github sucks at showing this diff so... whitespaces between stuffs

2025-02-17 22:14 UTC, ScarKy0 commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +}
```suggestion
public sealed partial class ChangelingTransformActionEvent : InstantActionEvent;
```

2025-02-17 22:14 UTC, ScarKy0 commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +
```suggestion
    public readonly NetEntity Identity;
    public string Name;

```

You overall needs to fix up whitespaces around this part of the file

2025-02-17 22:14 UTC, ScarKy0 commented on Content.Shared/Humanoid/SharedHumanoidAppearanceSystem.cs
> +        }
```suggestion
        if (!Resolve(source, ref sourceHumanoid) || !Resolve(target, ref targetHumanoid))
            return;
```

2025-02-17 22:14 UTC, ScarKy0 commented on Content.Shared/Humanoid/SharedHumanoidAppearanceSystem.cs
> +        }
```suggestion
        if (TryComp<GrammarComponent>(target, out var grammar))
            grammar.Gender = sourceHumanoid.Gender;
```

2025-02-17 22:14 UTC, ScarKy0 commented on Resources/Locale/en-US/changeling/changeling.ftl
> +changeling-unidentified-husked-corpse = Mangled Corpse
```suggestion

changeling-defibrillator-failure = This patient is too internally mangled to be revived
changeling-unidentified-husked-corpse = Mangled Corpse
```

2025-02-17 22:14 UTC, ScarKy0 commented on Resources/Prototypes/Antag/changeling.yml
> +  description: Consume the essence of your victims and subsume their identity and mind into your own
```suggestion
  description: Consume the essence of your victims and subsume their identity and mind into your own.
```

2025-02-17 22:14 UTC, ScarKy0 commented on Resources/Prototypes/Antag/changeling.yml
> +  description: Transform and assume the identities of those you have devoured
```suggestion
  description: Transform and assume the identities of those you have devoured.
```

2025-02-17 22:14 UTC, ScarKy0 commented on Resources/Prototypes/Body/Organs/Antag/changeling.yml
> +          Quantity: 5
Not needed yet, can be removed

2025-02-17 22:14 UTC, ScarKy0 commented on Resources/Prototypes/GameRules/roundstart.yml
> +  - type: AntagSelection
```suggestion
  - type: GameRule
    minPlayers: 1 # Totally should be playable :)
  - type: AntagSelection
```

I want to play ling so bad... (Not an actual review)

2025-02-19 22:58 UTC, poklj commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        CopyComp<SpeechComponent>(targetIdentity, ent, out _);
ostensibly usable now... even though copycomps isn't merged

2025-03-03 12:29 UTC, UbaserB approved these changes
art approval or something

2025-04-19 19:30 UTC, poklj commented on Resources/Audio/Effects/Changeling/devour_consume.ogg
@ScarKy0 states that Consume is a little loud, agreed first suggested fix is to lower it a little using the playsound properties

2025-04-19 20:22 UTC, poklj commented
tests appear to be pulling earlier required Engine branch rather than head.

2025-04-30 20:45 UTC, slarticodefast requested changes
Quick first pass review.
I will still need to do in-game testing and look into how we should best do the cloning and identity storage.

2025-04-30 20:45 UTC, slarticodefast commented on Content.Server/Changeling/Devour/ChangelingDevourSystem.cs
> +public sealed class ChangelingDevourSystem : SharedChangelingDevourSystem
all of this needs to be in shared and predicted

2025-04-30 20:45 UTC, slarticodefast commented on Content.Server/Changeling/Devour/ChangelingDevourSystem.cs
> +    }
why even make this a function?
PlayPVS already does the null check
and you should be using playprediced in shared

2025-04-30 20:45 UTC, slarticodefast commented on Content.Server/Changeling/Devour/ChangelingDevourSystem.cs
> +    protected override void RipClothing(EntityUid uid, EntityUid item,  ButcherableComponent butcher)
always use the Entity<Component> pattern for parameters
see https://hackmd.io/@Slart/S1hsoGFm1l for an explanation

2025-04-30 20:45 UTC, slarticodefast commented on Content.Server/Changeling/Transform/ChangelingTransformSystem.cs
> +    }
this should not be in this system at all
the misprediction is a bug that needs to be fixed
the rest should be turned into an API function in GrammarSystem or something

2025-04-30 20:45 UTC, slarticodefast commented on Content.Server/GameTicking/Rules/Components/ChangelingRuleComponent.cs
> +public sealed partial class ChangelingRuleComponent : Component;
documentation

2025-04-30 20:45 UTC, slarticodefast commented on Content.Server/Speech/EntitySystems/VocalSystem.cs
> +        component.ScreamActionEntity = null;
What is this for?
this should already be null
![grafik](https://github.com/user-attachments/assets/0cc8b508-87b6-478a-868f-4d7813ffc31c)
Also constants should be directly set in the component, not on map init

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentityComponent.cs
> +public sealed partial class ChangelingIdentityComponent : Component
documentation

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingRoleComponent.cs
> +public sealed partial class ChangelingRoleComponent : BaseMindRoleComponent;
same

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +public sealed partial class ChangelingDevourComponent : Component
same

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    [DataField(customTypeSerializer: typeof(PrototypeIdSerializer<EntityPrototype>))]
`PrototypeIdSerializer` is deprecated, use `EntProtoId`
see my guide for more info
in general prototype IDs should never be strings

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    public EntityUid? CurrentDevourSound;
this looks sus

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    [DataField, AutoNetworkedField]
needs timeoffsetserializer

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingHuskedCorpseComponent.cs
> +public sealed partial class ChangelingHuskedCorpseComponent : Component;
documentation

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingHuskedCorpseSystem.cs
> +        _humanoidSystem.CloneAppearance(huskedBodyAppearance, ent);
spawning a whole body only to clone the appearance and delete it again is a little sus
can't we directly apply the data from the species prototype?

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/SharedChangelingDevourSystem.cs
> +public sealed partial class ChangelingDevourConsumeDoAfterEvent : SimpleDoAfterEvent;
best move these into a separate file for better bookkeeping
also add documentation

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/SharedChangelingDevourSystem.cs
> +        if (damage.DamagePerGroup.TryGetValue("Brute", out var val) && val < comp.DevourConsumeDamageCap)
don't hardcode this

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/SharedChangelingDevourSystem.cs
> +        var pierce = ev.DamageModifiers.Coefficients.ContainsKey("Piercing") && ev.DamageModifiers.Coefficients["Piercing"] < 1f - ent.Comp.DevourPreventionPercentageThreshold;
don't hardcode the damage categories

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/SharedChangelingDevourSystem.cs
> +        return  slash || blunt || pierce;
*aaaaaah*

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/SharedChangelingDevourSystem.cs
> +                         || !HasComp<DamageableComponent>(args.Target))
what is the reason for the `DamageableComponent` check?

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/SharedChangelingDevourSystem.cs
> +        ent.Comp.NextTick = curTime + TimeSpan.FromSeconds(1);
don't hardcode the timespan

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/SharedChangelingDevourSystem.cs
> +        StartSound(ent, new SoundPathSpecifier(_audio.GetSound(ent.Comp.ConsumeNoise!)));
this should be directly played here with PlayPredicted

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/SharedChangelingIdentitySystem.cs
> +    public void CloneToNullspace(Entity<ChangelingIdentityComponent> ent, EntityUid target)
add documetation for all public API functions
the cloning part should be independent of the pvs override
we should also just be reusing the new cloningsystem here instead of manually copying dna etc
we might have to move some of it to shared
on the other hand full entity spawning cannot be predicted yet
doing this in shared will spawn two copies, one on the client, one on the server

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/SharedChangelingIdentitySystem.cs
> +    /// Simple helper to add a PVS override to a
end of sentence?

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/SharedChangelingIdentitySystem.cs
> +        _pvsOverrideSystem.AddSessionOverride(target, actor.PlayerSession);
these should be removed again when the component shuts down

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/ChangelingTransformComponent.cs
> +public sealed partial class ChangelingTransformComponent : Component
documentation

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/ChangelingTransformComponent.cs
> +    [DataField(customTypeSerializer: typeof(PrototypeIdSerializer<EntityPrototype>))]
deprecated

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        base.Initialize();
```suggestion
        base.Initialize();

```

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        if(!ent.Comp.ChangelingTransformActionEntity.HasValue)
why the null check?

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        var userInterfaceComp = EnsureComp<UserInterfaceComponent>(ent);
pretty sure the integration tests will complain about this if ever used in a prototype

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        Dirty(ent, userIdentity);
why? nothing changed in that component

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +            var x = userIdentity.ConsumedIdentities.Select(x =>
don't use linq
it's slow

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +            return;
oh god, so many trycomps 💀 
there has to be a better way than hardcoding all of these here
otherwise we will have to add more and more here over time
this should be done in yaml
or just be part of the existing cloning system

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        }
stuff like this is what I mean
this will completely break for any species added in forks

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +            EnsureComp<TypingIndicatorComponent>(targetIdentity);
what?

2025-04-30 20:45 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +}
move the BUI stuff and messages into their own file for better bookkeeping

2025-04-30 20:45 UTC, slarticodefast commented on Resources/Prototypes/Antag/changeling.yml
> +  name: Urist McLing
perfect name :)

2025-04-30 20:45 UTC, slarticodefast commented on Resources/Prototypes/GameRules/roundstart.yml
> +    minPlayers: 999 # TODO: make this reasonable once Changeling is out of WIP
you can give this a proper value
it should not roll unless part of a preset

2025-04-30 21:55 UTC, poklj commented on Content.Server/Speech/EntitySystems/VocalSystem.cs
> +        component.ScreamActionEntity = null;
This is because copycomps will pull across the actionEntity of the target comp, causing a disjointed EntityUid pointing to the action on the victim, not the changeling, setting it to null stops it from pointing to that and allows the component to get a new entity

2025-04-30 22:00 UTC, poklj commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +            EnsureComp<TypingIndicatorComponent>(targetIdentity);
Any spawned Humans will not have a typing Indicator on them unless a mind is put into the body, this is the case for anything that uses the default typing indicator.

2025-04-30 22:38 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +            EnsureComp<TypingIndicatorComponent>(targetIdentity);
this should just be part of a general cloning component whitelist

2025-05-03 12:12 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        TransformGrammarSet(ent, targetConsumedHumanoid.Gender);
```suggestion
```
This isn't needed anymore and is handled by `CloneAppearance`
See https://github.com/space-wizards/space-station-14/pull/37130

2025-05-28 22:35 UTC, poklj commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        var userInterfaceComp = EnsureComp<UserInterfaceComponent>(ent);
Keeping for now, pending if we are making Changling it's own prototype vs A direct antag creation. 
For a prototype this would cause IntegrationTests to complain, however it is remedied by moving the UserInterfaceComponent to the prototype itself

2025-06-15 19:05 UTC, Fildrance commented on Content.Client/Changeling/ChangelingIdentitySystem.cs
> +public sealed partial class ChangelingIdentitySystem : SharedChangelingIdentitySystem;
if only shared have logic - make it hte only one system and not abstract.

2025-06-15 19:05 UTC, Fildrance commented on Content.Client/Changeling/Devour/ChangelingDevourSystem.cs
> +public sealed partial class ChangelingDevourSystem : SharedChangelingDevourSystem;
inherit doc

2025-06-15 19:07 UTC, Fildrance commented on Content.Client/Changeling/Transform/ChangelingTransformMenu.xaml
> +﻿<ui:RadialMenu
remove xaml/xaml.cs and use code such as https://github.com/space-wizards/space-station-14/pull/36378 in BUI - create models for buttons and put them into SimpleRadialMenu
Also this way you can highlight currently selected person in menu

2025-06-15 19:08 UTC, Fildrance commented on Content.Client/Changeling/Transform/ChangelingTransformBoundUserInterface.cs
> +    public ChangelingTransformBoundUserInterface(EntityUid owner, Enum uiKey) : base(owner, uiKey) { }
use primary c-tor

2025-06-15 19:08 UTC, Fildrance commented on Content.Client/Changeling/Transform/ChangelingTransformBoundUserInterface.cs
> +        base.Open();
empty line after calling base would be nice

2025-06-15 19:12 UTC, Fildrance commented on Content.Server/GameTicking/Rules/ChangelingRuleSystem.cs
> +        base.Initialize();
empty line after calling base pls :3

2025-06-15 19:13 UTC, Fildrance commented on Content.Server/GameTicking/Rules/ChangelingRuleSystem.cs
> +public sealed class ChangelingRuleSystem : GameRuleSystem<ChangelingRuleComponent>
xml-doc this pls

2025-06-15 19:13 UTC, Fildrance commented on Content.Server/GameTicking/Rules/Components/ChangelingRuleComponent.cs
> +
excessive empty line

2025-06-15 19:17 UTC, Fildrance commented on Content.Server/Administration/Systems/AdminVerbSystem.Antags.cs
> +
excessive empty line

2025-06-15 19:19 UTC, Fildrance commented on Content.Server/Changeling/Devour/ChangelingDevourSystem.cs
> +public sealed partial class ChangelingDevourSystem : SharedChangelingDevourSystem
inherit doc

2025-06-15 19:19 UTC, Fildrance commented on Content.Server/Changeling/Devour/ChangelingDevourSystem.cs
> +    [Dependency] private readonly SharedAudioSystem _audioSystem = default!;
remove unused systems and usings

2025-06-15 19:21 UTC, Fildrance commented on Content.Server/Changeling/Devour/ChangelingDevourSystem.cs
> +    protected override void RipClothing(EntityUid victim, Entity<ButcherableComponent> item)
i am fairly certain this all can be predicted? and made in shared

2025-06-15 19:22 UTC, Fildrance commented on Content.Server/Changeling/Transform/ChangelingTransformSystem.cs
> +            return;
empty line after if block is required :godo:
also remove unused dependencies and usings

2025-06-15 21:19 UTC, poklj commented on Content.Client/Changeling/Devour/ChangelingDevourSystem.cs
> +public sealed partial class ChangelingDevourSystem : SharedChangelingDevourSystem;
made irrelevant due to RipClothes becoming shared, eliminating the need for Client/server specific code and thus removing the need for this file

2025-06-15 21:20 UTC, poklj commented on Content.Server/Changeling/Devour/ChangelingDevourSystem.cs
> +public sealed partial class ChangelingDevourSystem : SharedChangelingDevourSystem
made irrelevant due to RipClothes becoming shared, eliminating the need for Client/server specific code and thus removing the need for this file

2025-06-15 21:42 UTC, ScarKy0 requested changes
Few bugs spotted while testing:
- Displacement maps do not function, leading to vox with human-shaped suits for example
- Few species specific traits misbehave (Dwarves arent short, slime storage doesnt work, diona can wear shoes)

2025-06-15 22:29 UTC, poklj commented on Content.Client/Changeling/Transform/ChangelingTransformMenu.xaml
> +﻿<ui:RadialMenu
Turns out this Ui isn't simple enough for SimpleRadials, Discussions in discord have revealed that use of Spriteview for viewing the individual identities complicates the radial out of reach of it and thus we cannot convert it

2025-06-16 03:58 UTC, ArcaneOcto commented
Could it be? It's really happening? I never thought I'd see the day...

2025-06-16 13:02 UTC, ScarKy0 commented
> Could it be? It's really happening? I never thought I'd see the day...

Youd be surprised how much work is happening behind the scenes

2025-06-16 13:57 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +        }
You'll need to add a total damage check or similiar. With husking disabled you're able to endlessly eat one body and gain the identity several times.

![image](https://github.com/user-attachments/assets/7d544ecf-5ea0-4e6d-9956-7cdc4c6f7015)

2025-07-23 18:32 UTC, ScarKy0 requested changes
I woke up today and chose violence, so have a 26 extreme nitpicks
(I'll likely handle them myself later)

2025-07-23 18:32 UTC, ScarKy0 commented on Resources/Audio/Effects/Changeling/attributions.yml
> +  source: "https://1.1.1.1" # TODO: FIX THIS
Should probably fix this before release

2025-07-23 18:32 UTC, ScarKy0 commented on Resources/Locale/en-US/administration/antag.ftl
> +admin-verb-make-changeling = Make the target into a Changeling
```suggestion
admin-verb-make-changeling = Make the target into a Changeling.
```
dot

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +
Get rid of extra newlines

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Transform/ChangelingTransformComponent.cs
> +/// The component containing information about Changelings Transformation action
```suggestion

namespace Content.Shared.Changeling.Transform;

/// <summary>
/// The component containing information about Changelings Transformation action
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +    [Dependency] private readonly INetManager _net = default!;
```suggestion
using Robust.Shared.Prototypes;

namespace Content.Shared.Changeling.Transform;

public abstract partial class SharedChangelingTransformSystem : EntitySystem
{
    [Dependency] private readonly INetManager _net = default!;
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingHuskedCorpseSystem.cs
> +        if(!TryComp<BodyComponent>(ent.Owner, out var body))
```suggestion
        unrevivable.ReasonMessage = "changeling-defibrillator-failure";

        if(!TryComp<BodyComponent>(ent.Owner, out var body))
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +        var spawnEntities = EntitySpawnCollection.GetSpawns(item.Comp.SpawnedEntities, _robustRandom);
```suggestion
        Dirty(ent);
    }
    
    private void RipClothing(EntityUid victim, Entity<ButcherableComponent> item)
    {
        var spawnEntities = EntitySpawnCollection.GetSpawns(item.Comp.SpawnedEntities, _robustRandom);
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +        if(EntityManager.EntityExists(ent.Comp.CurrentDevourSound))
```suggestion
        if (EntityManager.EntityExists(ent.Comp.CurrentDevourSound))
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +        if(!EntityManager.EntityExists(ent.Comp.CurrentDevourSound))
```suggestion
        if (!EntityManager.EntityExists(ent.Comp.CurrentDevourSound))
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +        if(target == ent.Owner)
```suggestion
        if (target == ent.Owner)
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +}
```suggestion
    public float DevourPreventionPercentageThreshold = 0.1f;
}
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    public TimeSpan DamageTimeBetweenTicks = TimeSpan.FromSeconds(1);
Datafield and autonetworked

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    public EntityUid? CurrentDevourSound;
network for admeme bullshittery

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    public bool Husking = false;
Network to allow admemes to mess with it

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +
```suggestion
    }
}

```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +    /// </summary>
```suggestion
            _pvsOverrideSystem.RemoveSessionOverride(identity.Value, actor.PlayerSession);
        }
    }

    /// <summary>
    /// Inform another Session of the entities stored for Transformation
    /// </summary>
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +    /// </summary>
```suggestion
        HandlePvsOverride(ent, mob);
    }

    /// <summary>
    /// Simple helper to add a PVS override to a Nullspace Identity
    /// </summary>
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +    ///
```suggestion
        }
    }
    
    /// <summary>
    /// Clone a target humanoid into nullspace and add it to the Changelings list of identities.
    ///
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +        CleanupPvsOverride(ent, ent.Owner);
```suggestion
    {
        CloneToNullspace(ent, ent.Owner);
    }
    
    private void OnShutdown(Entity<ChangelingIdentityComponent> ent, ref ComponentShutdown args)
    {
        CleanupPvsOverride(ent, ent.Owner);
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/ChangelingIdentityComponent.cs
> +}
```suggestion
    public EntityUid? LastConsumedEntityUid;
}
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/ChangelingIdentityComponent.cs
> +    /// <summary>
I think just move this to the bottom of the component, thats how it was in the other files dunno

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    /// The Action for devouring
Bottom of the file

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Server/Storage/EntitySystems/StorageSystem.cs
> +    [Dependency] private readonly UserInterfaceSystem _userInterface = default!;
```suggestion
    [Dependency] private readonly UserInterfaceSystem _userInterface = default!;
    
```
needs a newline after

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Server/Storage/EntitySystems/StorageSystem.cs
> +    }
```suggestion
        SubscribeLocalEvent<StorageFillComponent, MapInitEvent>(OnStorageFillMapInit);
    }
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Server/GameTicking/Rules/ChangelingRuleSystem.cs
> +}
```suggestion
    }
}
```

2025-07-23 18:32 UTC, ScarKy0 commented on Content.Server/Speech/EntitySystems/VocalSystem.cs
> +        var v = EnsureComp<VocalComponent>(args.CloneUid);
Why remove VocalComponent if you ensure it right afterwards?

2025-07-23 21:55 UTC, ScarKy0 commented
Addressed my reviews, just need the sources for sounds

2025-07-23 23:43 UTC, ScarKy0 approved these changes
What can I say except peak

2025-07-24 00:36 UTC, slarticodefast commented on Content.Client/Changeling/Transform/ChangelingTransformBoundUserInterface.cs
> +    protected override void UpdateState(BoundUserInterfaceState state)
```suggestion

    protected override void UpdateState(BoundUserInterfaceState state)
```

2025-07-24 00:38 UTC, slarticodefast commented on Content.Client/Changeling/Transform/ChangelingTransformBoundUserInterface.cs
> +
```suggestion

```
caught webediting

2025-07-24 00:44 UTC, slarticodefast commented on Content.Server/Administration/Systems/AdminVerbSystem.Antags.cs
> +        Verb changeling = new()
```suggestion

        Verb changeling = new()
```

2025-07-24 00:45 UTC, slarticodefast commented on Content.Server/Administration/Systems/AdminVerbSystem.Antags.cs
> +            Message = Loc.GetString("admin-verb-make-changeling"),
follow the same pattern as the other verbs

2025-07-24 00:48 UTC, slarticodefast commented on Content.Server/Changeling/Transform/ChangelingTransformSystem.cs
> +        if (!_prototype.TryIndex(settingsId, out var settings))
use `Resolve`
see https://github.com/space-wizards/space-station-14/pull/39124

2025-07-24 00:51 UTC, slarticodefast commented on Content.Server/Emoting/Systems/BodyEmotesSystem.cs
> +        component.Sounds = null;
What is this doing?
It should already be null.

2025-07-24 00:55 UTC, slarticodefast commented on Content.Client/Changeling/Transform/ChangelingTransformMenu.xaml.cs
> +        foreach (var identity in state.Identites)
Your current identity is showing in the radial and you can transfrom into yourself.
Showing it is probably fine since it makes it easier to keep track of identities and they stay in the same position.
But the button should be disabled.
<img width="289" height="317" alt="grafik" src="https://github.com/user-attachments/assets/155ffbd8-f883-490f-8ce1-bba93e3d784e" />

2025-07-24 01:05 UTC, slarticodefast commented on Content.Server/GameTicking/Rules/Components/ChangelingRuleComponent.cs
> +/// The rule for Changeling antags
```suggestion
/// Gamerule component for handling a changeling antagonist.
```
Come on, that part was already in the name.

2025-07-24 01:12 UTC, slarticodefast commented on Content.Server/Speech/EntitySystems/VocalSystem.cs
> +        RemComp<VocalComponent>(args.CloneUid);
Is there a reason why you are removing it first?
The only thing done on init is add the action, which the clone should either already have or will get with the EnsureComp.

2025-07-24 01:13 UTC, slarticodefast commented on Content.Server/Speech/EntitySystems/VocalSystem.cs
> +        v.Sounds = ent.Comp.Sounds;
You are shallow copying here.
Best just call LoadSounds.

2025-07-24 01:16 UTC, slarticodefast commented on Content.Server/Storage/EntitySystems/StorageSystem.cs
> +    private void OnClone(Entity<StorageComponent> ent, ref CloningEvent args)
We got a problem here.
Med code namespaces like cloning should not be a dependency for more groundlaying systems like storage code.
Same problem with `VocalSystem`.
I would probably add a public API method for cloning the component to another entity, and then call that in CloningSystem.Subscriptions as a workaround. Not pretty either, but a compromise.
Then in the cloning system add a code comment why we need to do this (for slimes+changelings).

Also this should be in shared, even if the cloning isn't yet.

2025-07-24 01:24 UTC, slarticodefast commented on Content.Server/Storage/EntitySystems/StorageSystem.cs
> +        cloneStorageComponent.Grid = ent.Comp.Grid;
deep copy
And copy all the other datafields as well. While slimes are not using them, maybe downstream does.

2025-07-24 01:25 UTC, slarticodefast commented on Content.Server/Storage/EntitySystems/StorageSystem.cs
> +        _userInterface.SetUi((args.CloneUid, cloneUserInterfaceComponent), StorageComponent.StorageUiKey.Key, new InterfaceData("StorageBoundUserInterface"));
We shouldn't put a magic string here.
Where is that string coming from in other places? Is it always the same as the BUI class name?

2025-07-24 01:27 UTC, slarticodefast commented on Content.Server/Wagging/WaggingSystem.cs
> +    private void OnCloning(Entity<WaggingComponent> ent, ref CloningEvent args)
this one can probably stay here
for having tail wagging depend on med code should be fine

2025-07-24 01:28 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentityComponent.cs
> +/// The storage component for Changelings, it handles the link between a changeling and it's consumed identities that
```suggestion
/// The storage component for Changelings, it handles the link between a changeling and its consumed identities that
```

2025-07-24 01:28 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentityComponent.cs
> +    public Dictionary<EntityUid,EntityUid> ConsumedIdentities = [];
```suggestion
    public Dictionary<EntityUid, EntityUid> ConsumedIdentities = [];
```

2025-07-24 01:35 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +        var mob = Spawn(speciesPrototype.Prototype, MapCoordinates.Nullspace);
This shouldn't be nullspace, but a separate paused map.
Look at `PolymorphSystem` and `SharedCryostorageSystem` for an example.

2025-07-24 01:36 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +    private void OnMindSwapVictim(Entity<ChangelingIdentityComponent> ent, ref MindRemovedMessage args)
```suggestion
    private void OnMindRemoved(Entity<ChangelingIdentityComponent> ent, ref MindRemovedMessage args)
```

2025-07-24 01:36 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +    private void OnMindSwapSpell(Entity<ChangelingIdentityComponent> ent, ref MindAddedMessage args)
```suggestion
    private void OnMindAdded(Entity<ChangelingIdentityComponent> ent, ref MindAddedMessage args)
```

2025-07-24 01:37 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +            return;
```suggestion
        if (!TryComp<ActorComponent>(args.Container.Owner, out var actor))
            return;

```

2025-07-24 01:38 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +            QueueDel(consumedIdentity.Value);
```suggestion
            PredictedQueueDel(consumedIdentity.Value);
```

2025-07-24 01:41 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +        if(ent.Comp.ConsumedIdentities.ContainsKey(target))
```suggestion
        if (ent.Comp.ConsumedIdentities.ContainsKey(target))
```

2025-07-24 01:43 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +            || !TryComp<DnaComponent>(target, out var targetDna))
Cloning code already handles this

2025-07-24 01:43 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +        mobDna.DNA = targetDna.DNA;
remove

2025-07-24 01:44 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +        SetPaused(mob, true);
If we have a paused map then the entity will be auto paused when spawned there.

2025-07-24 01:46 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentitySystem.cs
> +        _metaSystem.SetEntityName(mob, Name(target));
Use `NameModifierSystem.GetBaseName` or you will make any modifiers permanent.

2025-07-24 01:50 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.Events.cs
> +public sealed partial class ChangelingDevourWindupDoAfterEvent : SimpleDoAfterEvent;
Why is github not coloring this correctly?
<img width="747" height="199" alt="grafik" src="https://github.com/user-attachments/assets/a6aaccd9-7404-4c08-b34b-023fa9c9ce2b" />

2025-07-24 01:52 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingHuskedCorpseSystem.cs
> +public sealed class ChangelingHuskedCorpseSystem : EntitySystem
Move Husking into a separate PR.
This is a major game design decision, and I still see it as very problematic.
The rest of the design in this PR is basic changeling stuff, so no design problems there.

2025-07-24 02:00 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/ChangelingTransformComponent.cs
> +    public override bool SendOnlyToOwner => true;
move to bottom of the component

2025-07-24 02:00 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/ChangelingTransformComponent.cs
> +
```suggestion
```

2025-07-24 02:05 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.events.cs
> +    public ChangelingTransformWindupDoAfterEvent(NetEntity targetIdentity)
use primary constructor

2025-07-24 02:05 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.events.cs
> +public sealed partial class ChangelingTransformWindupDoAfterEvent : SimpleDoAfterEvent
documentation
same for the TargetIdentity

2025-07-24 02:06 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.events.cs
Rename the file, this is not part of the system.

2025-07-24 02:10 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.ui.cs
Same.

2025-07-24 02:10 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.ui.cs
> +public sealed class ChangelingTransformIdentitySelectMessage : BoundUserInterfaceMessage
documentation
same for the others

2025-07-24 02:15 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.events.cs
> +    public NetEntity TargetIdentity;
DoAfterEvents shouldn't store data, or it will break persistence
<img width="765" height="153" alt="grafik" src="https://github.com/user-attachments/assets/8d065fb6-78e4-4e87-8277-e9eb17eecb8c" />

2025-07-24 02:16 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.ui.cs
> +public enum TransformUi : byte
```suggestion
public enum TransformUI : byte
```

2025-07-24 02:16 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.ui.cs
> +    public ChangelingTransformIdentitySelectMessage(NetEntity targetIdentity)
primary constructor
same for the others

2025-07-24 02:17 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.ui.cs
> +    public string Name;
Why do we need to send the name?
You can just use `NameModifierSystem.GetBaseName` on the client.

2025-07-24 02:18 UTC, slarticodefast commented on Content.Shared/Humanoid/SharedHumanoidAppearanceSystem.cs
> +    public void SetGender(Entity<HumanoidAppearanceComponent> ent, Gender gender)
documentation
also make this nullable and add a resolve

2025-07-24 02:19 UTC, slarticodefast commented on Content.Shared/Inventory/InventorySystem.Slots.cs
> +    private void OnCloned(Entity<InventoryComponent> ent, ref CloningEvent args)
this should not be here
see my comments above

2025-07-24 02:21 UTC, slarticodefast commented on Content.Shared/Rootable/SharedRootableSystem.cs
> +        EnsureComp<RootableComponent>(args.CloneUid);
copy `TransferRate`, `TransferFrequency`, and `SpeedModifier` in case they are ever changed in yaml

2025-07-24 02:22 UTC, slarticodefast commented on Resources/Audio/Effects/Changeling/attributions.yml
> +  copyright: "Made by @DarkIcedCoffee on Discord for SS14, utilizing sounds from Caitlin_100, jedg and EricsSoundschmiede on freesound"
link the sounds used from freesound as well
same below

2025-07-24 02:25 UTC, slarticodefast commented on Resources/Prototypes/Antag/changeling.yml
> +
```suggestion
```

2025-07-24 02:26 UTC, slarticodefast commented on Resources/Prototypes/Antag/changeling.yml
> +  - type: ChangelingDevour
they are missing the armblade and ChangeLingIdentity

2025-07-24 02:27 UTC, slarticodefast commented on Resources/Prototypes/Antag/changeling.yml
> +  id: MobLing
add a suffix mentioning that they are not a traitor
or add AutoTraitorComponent so they get that on spawn (that component is cursed though, make sure to test it with mind swap)

2025-07-24 02:28 UTC, slarticodefast commented on Resources/Prototypes/Antag/changeling.yml
> +
```suggestion
```

2025-07-24 02:29 UTC, slarticodefast commented on Resources/Prototypes/Antag/changeling.yml
> +  id: ChangelingCloningSettings
The component datafields in `CloningSettingsPrototype` have `AlwaysPushInheritance`, so these are merged when inheriting.
So use inheritance to avoid having to copy paste everything. You might need to split up the default cloning prototype, because we don't want stuff like BibleUser

2025-07-24 02:32 UTC, slarticodefast commented on Resources/Prototypes/Roles/MindRoles/mind_roles.yml
> +    - type: MindRole
fix indentation

2025-07-24 02:35 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +/// Component responsible for Changelings Devour attack. including the amount of damage, if a successful devour husks
```suggestion
/// Component responsible for Changelings Devour attack. Including the amount of damage, if a successful devour husks
```

2025-07-24 02:38 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    public EntityUid? CurrentDevourSound;
Networking this will likely cause PVS errors when the auido entity is deleted and the reference is dirtied.
The jukebox does the same and currently spams 10000+ errors each day.
This either needs to be not networked, WeakEntityReference or https://github.com/space-wizards/RobustToolbox/pull/6056

2025-07-24 02:39 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    [DataField(customTypeSerializer: typeof(TimeOffsetSerializer)), AutoNetworkedField]
AutoPausedField

2025-07-24 02:40 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +    [Dependency] private readonly EntityManager _entityManager = default!;
unused

2025-07-24 02:43 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +    private void OnConsumeAttemptTick(Entity<ChangelingDevourComponent> ent,
AttemptEvents shouldn't be doing state changes.
I would probably just add some fixed damage for each devour stage, similar to the doafter topicals have, just with damage instead of healing. Or add a proper tick update for doafters.

2025-07-24 02:44 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +        ent.Comp.NextTick += ent.Comp.DamageTimeBetweenTicks; //TODO: Add this to the component
needs dirtying
also the TODO is resolved

2025-07-24 02:44 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +            ent.Comp.CurrentDevourSound = _audio.PlayPvs(ent.Comp.DevourWindupNoise!, ent,  new AudioParams())!.Value.Entity;
```suggestion
            ent.Comp.CurrentDevourSound = _audio.PlayPvs(ent.Comp.DevourWindupNoise!, ent, new AudioParams())!.Value.Entity;
```

2025-07-24 02:44 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +            ent.Comp.CurrentDevourSound = _audio.PlayPvs(ent.Comp.ConsumeNoise!, ent,  new AudioParams())!.Value.Entity;
```suggestion
            ent.Comp.CurrentDevourSound = _audio.PlayPvs(ent.Comp.ConsumeNoise!, ent, new AudioParams())!.Value.Entity;
```

2025-07-24 02:45 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +            _popupSystem.PopupClient(Loc.GetString("changeling-devour-consume-failed-not-dead"), args.User,  args.User, PopupType.Medium);
```suggestion
            _popupSystem.PopupClient(Loc.GetString("changeling-devour-consume-failed-not-dead"), args.User, args.User, PopupType.Medium);
```

2025-07-24 02:46 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +    private bool TargetIsProtected(EntityUid target, Entity<ChangelingDevourComponent> ent)
```suggestion
    private bool IsTargetProtected(EntityUid target, Entity<ChangelingDevourComponent> ent)
```
and add a code comment what this is doing exactly

2025-07-24 02:48 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +        RaiseLocalEvent(target, ev, true);
any reason for broadcasting this?

2025-07-24 02:55 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +        QueueDel(item);
```suggestion
        PredictedQueueDel(item);
```

2025-07-24 02:58 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +           ent.Comp.CurrentTransformSound = _audio.PlayPvs(ent.Comp.TransformAttemptNoise, ent, new AudioParams())!.Value.Entity;
```suggestion
            ent.Comp.CurrentTransformSound = _audio.PlayPvs(ent.Comp.TransformAttemptNoise, ent, new AudioParams())!.Value.Entity;
```

2025-07-24 02:58 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        if(EntityManager.EntityExists(ent.Comp.CurrentTransformSound))
```suggestion
        if (EntityManager.EntityExists(ent.Comp.CurrentTransformSound))
```

2025-07-24 03:00 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        _uiSystem.SetUi((ent, userInterfaceComp), TransformUi.Key, new InterfaceData("ChangelingTransformBoundUserInterface"));
same problem as above, hardcoded string

2025-07-24 03:02 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        if (!HasComp<UserInterfaceComponent>(ent))
make this a TryComp and pass it into the UI API methods so that we only have to get it a single time

2025-07-24 03:02 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        else // if the UI is already opened and the command action is done again, transform into the last consumed identity
cool idea
but maybe add a tooltip for this so the players will know

2025-07-24 03:05 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +        //TODO: While it would be splendid to be able to provide the original owning player who was playing the targetIdentity, it's not exactly feasible to do
You could add a component to the stored identities that contains the original player's session/and uid (although you have to be careful because they might no longer exist).
Not a blocker for this PR though.

2025-07-24 03:05 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.cs
> +    protected virtual void ApplyComponentChanges(EntityUid ent, EntityUid target, ProtoId<CloningSettingsPrototype> settingsId) { }
documentation

2025-07-24 09:56 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    public EntityUid? CurrentDevourSound;
Damn was hoping we could network this to make changing the sound as admeme easier

2025-07-24 09:56 UTC, ScarKy0 commented
> Also you should add a check to prevent making someone a changeling multiple times.

2025-07-24 09:56 UTC, closed without merging

2025-07-24 09:56 UTC, ScarKy0 commented
My keyboard just shit itself let's not talk about that

2025-07-24 09:57 UTC, ScarKy0 commented
> Also you should add a check to prevent making someone a changeling multiple times.

Don't all antags lack a check like that?

2025-07-24 10:08 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    public EntityUid? CurrentDevourSound;
That is not the sound file, but the sound entity.

2025-07-24 10:08 UTC, ScarKy0 commented on Content.Shared/Changeling/Devour/ChangelingDevourComponent.cs
> +    public EntityUid? CurrentDevourSound;
Oh oops

2025-07-24 10:09 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +            ent.Comp.CurrentDevourSound = _audio.PlayPvs(ent.Comp.DevourWindupNoise!, ent,  new AudioParams())!.Value.Entity;
oh, and don't do that null forgiveness and `AudioParams` thing
same below

2025-07-24 10:10 UTC, slarticodefast commented
> Don't all antags lack a check like that?

Yes, but no need to copy that bug.

2025-07-25 00:50 UTC, poklj commented on Content.Client/Changeling/Transform/ChangelingTransformBoundUserInterface.cs
> +
Incorrect, i did not webedit _this_ part :godo:
~~it was a oneline keep both merge conflict in AdminVerbs~~

2025-07-27 23:46 UTC, slarticodefast commented on Content.Shared/Changeling/Devour/ChangelingDevourSystem.cs
> +    private void OnConsumeAttemptTick(Entity<ChangelingDevourComponent> ent,
Discussed on discord, will be refactored later.

2025-07-28 00:26 UTC, slarticodefast requested changes
I fixed most of my above review comments.
We are getting really close!
Another bug I found while testing is that the `rooted` alert won't disappear when you transform from a diona to another species while rooted.

2025-07-28 00:26 UTC, slarticodefast commented on Content.Shared/Changeling/ChangelingIdentityComponent.cs
> +    public Dictionary<EntityUid, EntityUid> ConsumedIdentities = [];
This will cause major PVS issues when the original entity is somehow deleted.

2025-07-28 00:26 UTC, slarticodefast commented on Content.Shared/Changeling/Transform/SharedChangelingTransformSystem.events.cs
> +/// Fix before merging! - Slarti
see code comment

2025-07-28 00:38 UTC, slarticodefast commented
And it seems like I broke a test 😅 
<img width="617" height="163" alt="grafik" src="https://github.com/user-attachments/assets/4ff53922-4dc7-4af2-9113-df9501ff0574" />

2025-07-28 01:42 UTC, ScarKy0 commented on Content.Shared/Changeling/ChangelingIdentityComponent.cs
> +    public Dictionary<EntityUid, EntityUid> ConsumedIdentities = [];
Pushed a temporary fix. Will need WeakEntityReference though

2025-08-06 19:50 UTC, slarticodefast approved these changes
Finally ready, all bugs squished.