Character eye customization, scroll bar in appearance tab character setup. Fixes #2946
space-wizards/space-station-14 pull request #3403
Opened 2021-02-24 16:14 UTC by Rember

## About the PR 
Requires space-wizards/RobustToolbox#1595
Fixes #2946
This adds a set of color bars in the character customization screen that lets you adjust the eye colors of your character. It also adds a scroll bar for the appearance tab on the character setup screen, since the colors bars could not fit on the UI otherwise.

**Screenshots**

![image](https://user-images.githubusercontent.com/5190810/109029700-63343c00-76c3-11eb-9db8-7731a1ca1103.png)

2021-02-25 10:58 UTC, PJB3005 requested changes

2021-02-25 10:58 UTC, PJB3005 commented on Content.Client/GameObjects/Components/MagicMirrorBoundUserInterface.cs
> +        private sealed class ColorSlider : Control
Move `ColorSlider` out of `MagicMirrorBoundUserInterface.cs` and use the same instance instead of copy pasting it like this, please.

2021-03-07 19:10 UTC, SweptWasTaken commented
Reviews applied, this should be mergeable?

2021-03-07 19:46 UTC, DrSmugleaf approved these changes

2021-03-07 19:48 UTC, merged