Add standard, wallmount and improvised N2 closets, Revived
space-wizards/space-station-14 pull request #34042
Opened 2024-12-23 19:07 UTC by IamVelcroboy

## About the PR
Reopens [#27383](https://github.com/space-wizards/space-station-14/pull/27383) and updates to use entity tables.

## Why / Balance
fixes [#27194](https://github.com/space-wizards/space-station-14/issues/27194)

## Technical details
n/a

## Media
![image](https://github.com/user-attachments/assets/a896b727-2cf4-47a0-b566-76735a571a97)

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an in-game showcase.

## Breaking changes
n/a

**Changelog**
n/a

2024-12-23 19:21 UTC, IamVelcroboy commented
*fake test fail*

2024-12-28 01:35 UTC, cohanna commented
Iirc the improvised sprite was removed because space racism bad, though having it for a mappable option isn't the worst imo

2024-12-29 03:20 UTC, IamVelcroboy commented
> Iirc the improvised sprite was removed because space racism bad, though having it for a mappable option isn't the worst imo

I can take it or leave it. I really just want the wallmounted ones.

2025-02-26 01:39 UTC, MilonPL requested changes
Make sure all of your entity prototypes follow the order defined in our [yaml covnentions](https://docs.spacestation14.com/en/general-development/codebase-info/conventions.html#yaml-conventions).

2025-02-26 01:40 UTC, IamVelcroboy commented
> Make sure all of your entity prototypes follow the order defined in our [yaml covnentions](https://docs.spacestation14.com/en/general-development/codebase-info/conventions.html#yaml-conventions).

![image](https://github.com/user-attachments/assets/05f8c6de-0a0f-44af-b743-dbcf29933516)

2025-02-26 03:36 UTC, IamVelcroboy commented
Aiight is just wallmount locker now

2025-02-28 16:00 UTC, MilonPL requested changes

2025-02-28 16:00 UTC, MilonPL commented on Resources/Textures/Structures/Storage/closet.rsi/n2_door.png
After asking art directors, we don't feel like the regular N2 locker needs respriting, so just undo that change. Everything else looks fine and the wallmount lockers are good too!

2025-03-03 05:39 UTC, MilonPL approved these changes

2025-03-12 22:42 UTC, merged