Hi-viz vest now actually hi-viz
space-wizards/space-station-14 pull request #34087
Opened 2024-12-27 16:54 UTC by kosticia

## About the PR
Now hi-viz vest glows in the dark

## Why / Balance
Makes hi-viz vest a little bit more usefull
Also it was in SS13

## Media
![Безымянный2](https://github.com/user-attachments/assets/7cd34045-e0ef-456e-ad2b-11f70173c070)
![Безымянный3](https://github.com/user-attachments/assets/efb66bee-4d5a-4f33-9a61-20a824757df3)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

2024-12-27 17:02 UTC, beck-thompson commented
Love the idea!

2024-12-28 05:18 UTC, Aeshus requested changes

2024-12-28 05:18 UTC, Aeshus commented on Resources/Textures/Clothing/OuterClothing/Vests/hazard.rsi/meta.json
As you've made modifications to the sprites, you'll need to credit yourself for the modifications in the copyright section of this `meta.json` file.

As an example: (You don't need to use this specific version if you don't want to)

```json
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/c838ba21dae97db345e0113f99596decd1d66039. Vox state made by Flareguy for Space Station 14. Modified/split into UNSHADED and regular sprites by kosticia (GitHub).",
```

https://docs.spacestation14.com/en/space-station-14/art.html#licensing

2024-12-28 11:31 UTC, kosticia commented on Resources/Textures/Clothing/OuterClothing/Vests/hazard.rsi/meta.json
Added

2025-01-18 18:01 UTC, beck-thompson approved these changes
Tested and looks good! I don't think it needs art approval?

2025-01-18 18:03 UTC, Aeshus reviewed
Thanks for the PR!

This'll get merged once an art director comes around.

2025-01-27 09:06 UTC, Emisse approved these changes

2025-01-27 09:06 UTC, Emisse commented
art approval

2025-01-27 09:08 UTC, merged