Warnings/sprite component
space-wizards/space-station-14 pull request #34088
Opened 2024-12-27 18:33 UTC by BarryNorfolk

## About the PR
Removes approx 26 warnings from `Content.Server\Explosion\EntitySystems\ExplosionSystem.TileFill.cs`.

## Why / Balance
Warnings are bad. Warnings delenda est.

## Technical details
Swapping away from obsolete functions/code to ones.
One instance of breaking up a logic bomb into a separate function that's a tad easier to read.

I've tested in game with a china lake to see if the explosion system still works, which it does. Can provide video if needed.

## Media
N/A.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
- None

**Changelog**
N/A

2025-01-10 15:05 UTC, metalgearsloth requested changes

2025-01-10 15:05 UTC, metalgearsloth commented on Content.Server/Explosion/EntitySystems/ExplosionSystem.TileFill.cs
>          }
Use the overload that does both at the same time please, much faster (each one needs to go up the transform hierarchy individually instead of at the same time).

2025-01-10 15:05 UTC, metalgearsloth commented on Content.Server/Explosion/EntitySystems/ExplosionSystem.TileFill.cs
> +
This looks like it should be an engine method on SharedMapSystem if anything?

Also doesn't TryFindGridAt fail if the tile is empty? is the return at 273 even possible?

2025-01-10 15:05 UTC, metalgearsloth commented on Content.Server/Explosion/EntitySystems/ExplosionSystem.TileFill.cs
> +        foreach (var grid in mapGrids)
This warning is around the fact you should be storing the list on the system and clearing + re-using it instead of allocating it every time.

2025-03-21 09:27 UTC, TheShuEd commented
This PR has been in “Awaiting changes” status for over 2 months now without any visible updates, so I'm closing it as derelict. If you nevertheless plan to continue, please comment it and the PR will be reopened.

If you need help, you can ask questions in discord or in this PR

2025-03-21 09:27 UTC, closed without merging