NanoTask
space-wizards/space-station-14 pull request #34095
Opened 2024-12-28 04:12 UTC by pontaoski

## About the PR
This introduces an app called NanoTask which allows people to keep a todo list of tasks by priority, and to print those tasks onto cards for easy insertion into PDAs.

## Why / Balance
This doesn't have any particular balance concerns, besides another source of infinite paper being added to the game.

The functionality of the app itself is mostly just a nice in-game in-character way to keep a todo list, which doesn't confer a huge mechanical advantage for using it.

## Technical details
NanoTask is relatively self-contained, living in its own new cartridge component and system, as well as a new UI.
NanoTaskItemControl and ItemPopup are widgets used in the construction of a NanoTaskUiFragment used in the construction of a NanoTaskUi.

The NanoTaskUi is structured in a React-ish manner, where state goes down and actions come up.

```mermaid
graph TB
	NanoTaskCartridgeSystem--sends UI state-->NanoTaskUi
	NanoTaskUi--sends messages-->NanoTaskCartridgeSystem

    NanoTaskUi--instantiates-->NanoTaskUiFragment
    NanoTaskUiFragment--sends messages-->NanoTaskUi

    NanoTaskUi--instantiates-->NanoTaskItemPopup
    NanoTaskItemPopup--sends messages-->NanoTaskUi

    NanoTaskUiFragment--instantiates-->NanoTaskItemControl
    NanoTaskItemControl--sends messages-->NanoTaskUiFragment
```

From there, the client top-level `NanoTaskUi` sends messages to the server `NanoTaskCartridgeSystem` which validates and takes actions as decided by the client UI. This part is fairly straightforward.

Printed NanoTask items get a `NanoTaskPrintedComponent`, similar to the bounty manifest component, which allows the item to be inserted into your PDA's NanoTask.

The main interaction between the NanoTask additions and changed code is adding new prototypes for the NanoTask cartridges, printed items, and PDAs.

## Media
![grafik](https://github.com/user-attachments/assets/132f32ee-e05a-4d80-aa9c-e150c2b453b0)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added NanoTask

2025-01-02 15:55 UTC, ilovehans10 commented
I adore this idea! I can't wait to see this implemented, and here are some ideas for how to expand this in future PRs in such a way as to fill planning/coordination holes I normally find in gameplay.

It would be neat to add a way to import tasks so if I am a botanist and get 4 bounties from cargo I can just click each bounty to the PDA and have them added as tasks.

Another neat feature would be to have a task feed that you could subscribe to. Tasks could be shared as a department, between syndicate agents, to plan a birthday party for the captain, to cordinate as revs, or to make a tider shittle. For feeds it could be neat if the person who makes the feed prints off a "feed card" from their PDA which others then click on their PDA with to connect to the feed. This implementation would make it so that the person who lives in disposals could find a feed card that was flushed by a syndicate agent and now know who their targets are.  The one issue I can see with this would be that feeds would have to operate based on some sort of range-based system; otherwise they could be used as a primitive communication system in the case of a comms outage.

Yet another feature that could play nicely with this is timed tasks, where the task either counts down or up when created. This would be great for both Sec and Engi as a way to keep track of prisoners and tesla/singulo. This would pair nicely with the "task feeds" idea in that Engi could have a feed that lets them all know that tesla has to have repairs done in 10 minutes.

2025-02-11 10:12 UTC, metalgearsloth requested changes

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Client/CartridgeLoader/Cartridges/NanoTaskUi.cs
> +
Use SendPredictedMessage and make it predicted please.

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Client/CartridgeLoader/Cartridges/NanoTaskUi.cs
> +    }
Should be using compstates not UI states.

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskCartridgeComponent.cs
> +{
Please document your code it's not clear what this even is.

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskCartridgeComponent.cs
> +
Is this supposed to be a required field?

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskCartridgeSystem.cs
> +
Use nullable for this not NaN checks.

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskCartridgeSystem.cs
> +        base.Initialize();
Documentation please.

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskCartridgeSystem.cs
> +    [Dependency] private readonly AudioSystem _audio = default!;
This code also needs to be in shared, all new code needs to be predicted.

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskCartridgeSystem.cs
> +
Is this supposed to use pushmarkup?

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskPrintedComponent.cs
> +}
As above please document.

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Shared/CartridgeLoader/Cartridges/NanoTaskUiMessageEvent.cs
> +}
As above please document.

2025-02-11 10:12 UTC, metalgearsloth commented on Content.Shared/CartridgeLoader/Cartridges/NanoTaskUiState.cs
> +
```suggestion

[Serializable, NetSerializable]
public enum NanoTaskPriority : byte
{
    High,
    Medium,
    Low,
};

```

2025-02-11 18:07 UTC, sowelipililimute commented on Content.Client/CartridgeLoader/Cartridges/NanoTaskUi.cs
> +    }
i have 0 idea what you're talking about

2025-02-11 18:08 UTC, sowelipililimute commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskCartridgeComponent.cs
> +
no

2025-02-11 18:09 UTC, sowelipililimute commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskCartridgeSystem.cs
> +    [Dependency] private readonly AudioSystem _audio = default!;
pretty much all of the cartridge system code lives in server, what i could move to shared is essentially just a skeleton

2025-02-11 18:09 UTC, sowelipililimute commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskCartridgeSystem.cs
> +
not really

2025-02-11 18:10 UTC, sowelipililimute commented
i'm not going to be able to move the bulk of nanotask into shared w/ the current state of the cartridge loader system having nearly all of the actual methods in server and not in the SharedCartridgeLoaderSystem

2025-03-15 06:08 UTC, metalgearsloth approved these changes

2025-03-15 06:45 UTC, beck-thompson requested changes
I think it would be nice of the "Done" button changed to like "Undo" or something!
![image](https://github.com/user-attachments/assets/ab7e8954-0ea7-43ea-8e34-1758dd6370bf)

Also if you could add comments to all your new classes and stuff that would be good! I got confused sometimes what exactly each thing did at a glace

2025-03-15 06:45 UTC, beck-thompson commented on Content.Client/CartridgeLoader/Cartridges/NanoTaskItemControl.xaml.cs
> +}
add a newline!

2025-03-15 06:45 UTC, beck-thompson commented on Content.Client/CartridgeLoader/Cartridges/NanoTaskItemPopup.xaml
> +</DefaultWindow>
newline!

2025-03-15 06:45 UTC, beck-thompson commented on Content.Client/CartridgeLoader/Cartridges/NanoTaskItemPopup.xaml
> +            <BoxContainer Orientation="Horizontal"
Could you add comments to each of these sections with like a quick comment on what they are (E.g like "option buttons" or "severity buttons" etc...)? Same with the other XML document as well!

2025-03-15 06:45 UTC, beck-thompson commented on Content.Shared/CartridgeLoader/Cartridges/NanoTaskCartridgeComponent.cs
> +    public float? PrintDelayRemaining = null;
Use a timespan

2025-03-15 06:45 UTC, beck-thompson commented on Content.Shared/CartridgeLoader/Cartridges/NanoTaskCartridgeComponent.cs
> +    public float PrintDelay = 5.0f;
Use a timspan

2025-03-15 06:45 UTC, beck-thompson commented on Content.Client/CartridgeLoader/Cartridges/NanoTaskItemPopup.xaml
> +               MinSize="300 200">
Change the minsize so it wont compress the buttons when you shrink it!
![image](https://github.com/user-attachments/assets/d5de7b50-9857-49c7-ab8f-6149a643bf8c)

2025-03-15 06:45 UTC, beck-thompson commented on Content.Client/CartridgeLoader/Cartridges/NanoTaskItemPopup.xaml.cs
> +        if (id is null)
Try:
`DeleteButton.Visible = id != null`;

2025-03-15 06:45 UTC, beck-thompson commented on Content.Server/CartridgeLoader/Cartridges/NanoTaskCartridgeSystem.cs
> +                {
A lot of these could be a lot shorter if you just did:
```
if (!task.Item.Validate())
   return;
```
I personally like that more, but its up to you :saluting_face:

2025-03-15 16:24 UTC, merged