Add microwave recipes to the guidebook
space-wizards/space-station-14 pull request #34105
Opened 2024-12-28 20:56 UTC by pontaoski

## About the PR
Microwave recipes are now automatically listed in the guidebook.

## Why / Balance
This makes discovering microwave recipes for new chefs actually possible.

## Technical details
- add GuideMicrowaveGroupEmbed and GuideMicrowaveEmbed widgets for automatically listing and displaying recipes in the guidebook
- add Group data field to the microwave recipe prototype
- add groups to microwave recipe prototypes
- add new guidebook documents for the new microwave recipe groups

## Media
![grafik](https://github.com/user-attachments/assets/88fff5a5-d66c-47ed-9636-b982df1df80a)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added microwave cooking recipes to the guidebook

2024-12-28 21:05 UTC, lzk228 commented
dear god thank you🙏

2024-12-29 00:04 UTC, Aeshus requested changes
Thanks! We've really been needing this...

I didn't really have much time to look into it much/give in depth feedback, but here are my initial thoughts after looking through everything.

2025-01-01 17:39 UTC, pontaoski commented on Content.Client/Guidebook/Controls/GuideMicrowaveEmbed.xaml
> +    <PanelContainer HorizontalExpand="True">
`PanelContainer` can't be the root of a XAML file, only the `BoxContainer` or the type itself

2025-01-01 17:48 UTC, Aeshus commented on Content.Client/Guidebook/Controls/GuideMicrowaveEmbed.xaml
> +    <PanelContainer HorizontalExpand="True">
Anything deriving from `Control` can be the root of a XAML file. The reason here that it's `BoxContainer` is because the `GuideMicrowaveEmbed` class derives from `BoxContainer`. 

If you instead derive from `PanelContainer`, you can now put the type as `PanelContainer`.

Note that you'd then need to change the `StyleBoxFlat` to add `Padding="5"` to replicate the same behavior as the margins of the parent `BoxContainer`.

2025-01-01 17:51 UTC, pontaoski commented on Content.Client/Guidebook/Controls/GuideMicrowaveGroupEmbed.xaml
> +</BoxContainer>
XAML files seem to be required by the build
```cs
/home/jblackquill/GitHub/space-station-14/Content.Client/Guidebook/Controls/GuideMicrowaveGroupEmbed.cs(17,29): error RXN0001: Unable to discover the relevant Robust XAML file expected at GuideMicrowaveGroupEmbed.xaml [/home/jblackquill/GitHub/space-station-14/Content.Client/Content.Client.csproj]
```

2025-01-01 17:54 UTC, Aeshus commented on Content.Client/Guidebook/Controls/GuideMicrowaveGroupEmbed.xaml
> +</BoxContainer>
That's because you're using a partial `GuideMicrowaveGroupEmbed.xaml.cs` file.

You can just delete `GuideMicrowaveGroupEmbed.xaml`, rename `GuideMicrowaveGroupEmbed.xaml.cs` to `GuideMicrowaveGroupEmbed.cs`, and then remove the `partial` and `GenerateTypedNameReferences` and it should be fine.

An an example, see: https://github.com/space-wizards/space-station-14/blob/master/Content.Client/Stack/StackStatusControl.cs

2025-01-01 17:55 UTC, pontaoski commented on Content.Client/Guidebook/Controls/GuideMicrowaveEmbed.xaml
a divider where exactly

2025-01-01 17:57 UTC, Aeshus commented on Content.Client/Guidebook/Controls/GuideMicrowaveEmbed.xaml
Right below the name.

![image](https://github.com/user-attachments/assets/8b414567-6b94-494d-8d70-d325f518832a)

Similar to how the reagents have a colored background to differentiate it.

![image](https://github.com/user-attachments/assets/4b9e7946-4300-4dec-a2e4-a4a137f6770a)

2025-01-10 02:31 UTC, Alpaccalypse commented
Thanks, from the title, I didn't realise just what great work you had done. This look like it should resolve #34342 I just posted.

2025-01-10 17:03 UTC, pontaoski commented
this only lists microwave recipes, so e.g. construction graph recipes like the custom burgers and tacos aren't listed here

2025-01-10 21:44 UTC, Alpaccalypse commented
Now I think of it, they would need a hand-crafted entry anyway, as they are so open-ended. (Accidental double pun)

2025-02-05 05:30 UTC, Aeshus commented
I'll do a code review of this by this weekend.

2025-02-15 00:22 UTC, beck-thompson approved these changes
Just a few minor things! Looks good besides that :+1:

2025-02-15 00:22 UTC, beck-thompson commented on Content.Client/Guidebook/Controls/GuideMicrowaveGroupEmbed.cs
> +using Content.Client.Guidebook.Richtext;
Sort all your imports alphabetically and also remove the unused ones!

2025-02-15 00:22 UTC, beck-thompson commented on Content.Client/Guidebook/Controls/GuideMicrowaveGroupEmbed.cs
> +        var prototypes = _prototype.EnumeratePrototypes<FoodRecipePrototype>()
Could you combine this stuff with the one in `TryParseTag`?

2025-02-15 18:32 UTC, Aeshus requested changes

2025-02-15 18:32 UTC, Aeshus commented on Content.Client/Guidebook/Controls/GuideMicrowaveEmbed.xaml
**nitpick:** I think there's gonna need to be some more UI design stuff for this to be merged.

In my opinion, it looks close enough to the reagents that it looks off to not have the colored header and for everything to be positioned slightly differently. Feel free to use the Discord to iterate on it or complain to me if you'd like.

2025-02-15 18:32 UTC, Aeshus commented on Content.Client/Guidebook/Controls/GuideMicrowaveEmbed.xaml.cs
> +using System.Linq;
**nitpick:** System imports always come first, ignoring the regular ordering.

2025-02-15 18:32 UTC, Aeshus commented on Resources/Locale/en-US/guidebook/cooking.ftl
> +guidebook-microwave-reagent-quantity-display = × {$amount}u
**note:** I think I remember hearing something from Julian about not putting richtext bbcode inside of fluent strings, though I can't really remember right now.

Probably just something to be aware of, or have another maint look more into.

2025-02-17 16:20 UTC, themias commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
> +  group: Breads
Since this can only be cooked in the DonkCo microwave, it might be worth putting this in a special group or something. Players might be confused why they can't cook it otherwise.

2025-02-17 16:20 UTC, themias commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
> +  group: Dessert
Same here.

2025-02-21 20:58 UTC, Aeshus approved these changes
Looks good to me in-game, though there is a weird visual bug at some aspect ratios, but may not be directly related to this and may just be a normal UI code thing.

![image](https://github.com/user-attachments/assets/585a6edf-9321-4146-94f0-d2d8dbe831f0)

2025-02-22 00:57 UTC, sowelipililimute commented
oh yeah I've seen drawing weirdness at different aspect ratios it's probably just that considering these are normal controls w/o any custom drawing

2025-02-23 14:49 UTC, slarticodefast requested changes

2025-02-23 14:49 UTC, slarticodefast commented on Content.Client/Guidebook/Controls/GuideMicrowaveEmbed.xaml.cs
> +            Logger.Error("Recipe embed tag is missing recipe prototype argument");
Obsolete, use sawmill.

2025-02-23 14:49 UTC, slarticodefast commented on Content.Shared/Kitchen/MicrowaveMealRecipePrototype.cs
> +        public string Group { get; private set; } = "Other";
```suggestion
        public string Group = "Other";
```
not needed

2025-02-23 15:23 UTC, slarticodefast approved these changes

2025-02-23 15:24 UTC, slarticodefast commented
Absolutely based PR!
Thank you for your contribution!

2025-02-23 15:24 UTC, merged