Anchored pipe sprite layers, to distinguish from unanchored pipes.
space-wizards/space-station-14 pull request #34129
Opened 2024-12-30 11:13 UTC by Alpaccalypse

## About the PR
Draft PR to showcase anchored pipe sprites, while I work out how to actually get them to function as intended. Made for issue #33495. If someone codes the functionality for this before me, they are welcome to use these sprites if they would like.

## Why / Balance
Visual feedback for anchored vs. unanchored sprites. Unanchored pipes are almost identical to anchored; when in place, it can be very hard to tell if individual pipe sections are unanchored, in a pipe chain. This should make it much more obvious to the player, while maintaining a minimalist aesthetic to the pipe sprites.

## Technical details
Allows a single brace and rivet decal lair to be overlayed onto each anchored pipe type.

## Media
Anchored pipe appearance:
![pipeBendAnchoredDemo](https://github.com/user-attachments/assets/6a11780d-9ff3-41f5-84ee-54fad8a7f43a)
![pipeFourwayAnchoredDemo](https://github.com/user-attachments/assets/08508a1f-b4d3-4791-86f1-c87d18c04111)
![pipeHalfAnchoredDemo](https://github.com/user-attachments/assets/34163f04-7940-4b4f-9c12-3ca334de7590)
![pipeTJunctionAnchoredDemo](https://github.com/user-attachments/assets/6964bcdc-5e65-426a-a645-96f3a8f854fb)
![pipeStraightAnchoredDemo](https://github.com/user-attachments/assets/76834cc9-e7ba-48cb-90c0-d8e85f8d3ab1)

## Requirements
- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
Cosmetic, though relatively significant for atmos gameplay. Presumably no changelog needed.

2024-12-30 11:20 UTC, Alpaccalypse commented
It is annoying that a different sprite/alignment is needed for some pipes, or this could just be added to the pipeConnector.png and I assume would just work, without needing any extra code.

Right now I'm tacking down how that actually works, as I assume using a similar method would be the best way to implement the anchoring functionality for these layers, into the game. I assume a Visualizer component for related entities in pipes.yml would also work, though so far, I've struggled to get this working using anchoring as a state.

2024-12-30 13:53 UTC, Alpaccalypse commented
> You can simply use a GenericVisualizer to get the sprite change working, no C# needed. See #33810

Thanks so much, that was exactly what I was looking and couldn't work out for myself. You saved me a lot of head scratching.

2024-12-30 18:24 UTC, Alpaccalypse commented
Well I uploaded a working version of the pipe.yml, but not sure it is quite right.

I was hoping I could get `visible: true` working, as with the gas cannisters, but it wouldn't work, just displayed the anchored version for all states. It seems to me like the uploaded version is putting down a second layer of the default pipe sprite when unanchored, but I may be misinterpreting how Visualizer layers work. It certainly seems to WAI in the game at least.

2024-12-30 20:00 UTC, Alpaccalypse commented
It appears the zfighting bug I identified is unique to the test environment. Opon map loading, or anchoring/constructing a new pipe, the game correctly picks one pipe and bolt as the top layer.

2025-01-10 15:00 UTC, UbaserB requested changes
I like the concept a lot, but there's a couple small issues. 
Firstly, the 'screws' (as in, individual bordered pixels on the sides) should be less separated from the sheet of metal wrapping over the pipe *in terms of contrast*, not position. Also make sure it's not to the point of fully looking like a part of the sheet. 

Second issue is during 3-4 way pipe intersections. The contrast is way too intense as compared to the 1-2 way ones, and it's simply jarring to see. Takes up too much attention on the screen and it should be similar to the others.

2025-01-10 16:57 UTC, Alpaccalypse commented
Thank for the feedback, both seem like fair points to me. I'll do a revision to address this and post an update.

2025-01-10 20:12 UTC, Emisse commented
feels visually messy to me

2025-01-10 20:13 UTC, Emisse commented
brackets should probably stick out from the sides of the pipe less

2025-01-11 11:58 UTC, Alpaccalypse commented
I was on the fence about how much they should stick out. I think if I follow Ubasers advice about contrast, it will allow them to be pulled back in without merging too much with the pipe outline.

2025-01-11 21:57 UTC, Alpaccalypse commented
Updated pipes to pull focus less, and blend in better. Have also shortened brackets slightly for straight and corner pipes, without losing too much fidelity I think.

![image](https://github.com/user-attachments/assets/93c36ac4-b70b-4707-8b19-240f8ebb556e)
![image](https://github.com/user-attachments/assets/299fc742-f543-4970-a380-451c57daae23)

2025-01-11 22:07 UTC, Alpaccalypse commented
Before
![2024-12-30_18 08 41](https://github.com/user-attachments/assets/0b6f3e53-fd84-4615-9c85-207a89090623)

2025-01-11 22:07 UTC, Alpaccalypse commented
After (too subtle?)
![2025-1-11_22 03 28](https://github.com/user-attachments/assets/cf328d3e-ba0a-4fff-af45-e53342365af4)

2025-01-12 05:26 UTC, Alpaccalypse commented
Had a go at trying to make the Fourway/TJunction brackets less dominating. Problem is, reducing the width leaves very little room for any filler, it's all outline needed for definition. Stil, might be of interest. Am basically pre-empting queries. 
![pipeFourwayAnchoredv2](https://github.com/user-attachments/assets/9ae0ccaa-8a19-4a3d-be5b-59419accc89f)

2025-01-30 20:19 UTC, Emisse commented
sticks out too far on the sides and interrupting the color every tile makes it feel very visually messy. Not sure how I would go about this.

2025-04-19 14:04 UTC, closed without merging