Make foods reflect their ingredients better
space-wizards/space-station-14 pull request #34138
Opened 2024-12-30 20:48 UTC by Stop-Signs

## About the PR
This PR changes the internal reagents that control hunger to better reflect the ingredients that went in them
soups have all been standardized to 55u of max volume, regardless of whats in them, salads have much more vitamin since they are healthier and many more changes. These amounts should better reflect the amount of effort chefs put into food. There are many examples where the microwave would just takes your 30+ nutriment worth of ingredients and reduce it to 12.

## Why / Balance
This needed to be done eventually, a lot of the food protos hadn't been updated since 2021 and many recipes called for several ingredients only for their end result to be lackluster

## Technical details
all of this is YML and almost every bit of it is just reagents.

## Media
There is no good way to display these changes through media

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: Meals now better reflect the amount of ingredients put into them.

2024-12-31 20:19 UTC, Alpaccalypse commented
Looks well thought out and logical to me, only gripe would be that soylent burger has been nerfed too harshly; Assuming soy beans are an ingredient, they actually have a pretty high protein content and should have at least some vitamins.

2024-12-31 21:13 UTC, Stop-Signs commented
> Looks well thought out and logical to me, only gripe would be that soylent burger has been nerfed too harshly; Assuming soy beans are an ingredient, they actually have a pretty high protein content and should have at least some vitamins.

yeah I had a lot of debate with myself doing that particular one. on one hand I was trying to stick to the "produce recipes get vitamin based on the veggie while meat recipes get protein." mentality, and on the other hand it was "this is essentailly a burger made out of fillers". 

Thanks for pointing this out though as i didnt get the chance to completely review everything I did, I'll go ahead and push a commit to rectify this injustice.

2024-12-31 23:15 UTC, Alpaccalypse approved these changes
For the record, I am not a soy enthusiast, just a pedant. I also read the PR guidelines, and it says my review could be valuable, apparently.

Having looked through this in detail, I don't see any obvious errors and all changes seem well reasoned within the bounds of the PR description, and general game balance, so this gets my approval.

2025-01-18 16:22 UTC, Alpaccalypse commented
Out of interest, what made you increase the volume of Clown's Tears soup over the previous one, Wing Fan Chu, for example, which you kept at maxVol 40?

2025-02-06 04:27 UTC, Stop-Signs commented
> Out of interest, what made you increase the volume of Clown's Tears soup over the previous one, Wing Fan Chu, for example, which you kept at maxVol 40?

just seeing this now, I dont quite remember but it may have had soemthing to do with the water in the recipe. When i started this PR I didn't have a standardized plan and was just adding the reagent amounts of ingredients. That's mostly what the rest of the PR is but with stuff like soups and cakes i tried to standardize it.

2025-05-11 04:24 UTC, sowelipililimute requested changes
ran through with calculations, the values here seem more or less appropriate, except for pies, which are still undervalued by the logic stated in the PR description

2025-05-11 04:24 UTC, sowelipililimute commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +          Quantity: 10
taking berries as an example,

source berries:
- nutriment: 5 * 3 = 15
- vitamin: 4 * 3 = 12
- total: 27u

source batter:
- 15u flour, 12u egg, 5u sugar, 5u milk: willing to call this as the other substantial half of this setup

checks out

2025-05-11 04:24 UTC, sowelipililimute commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +          Quantity: 10
similar logic to above but milk

2025-05-11 04:24 UTC, sowelipililimute commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +          Quantity: 2
similar to above but chocolate

2025-05-11 04:24 UTC, sowelipililimute commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +          Quantity: 15
appropriate given pumpkin's more reagents

2025-05-11 04:24 UTC, sowelipililimute commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +          Quantity: 30
yeah that works out with similar scaling to the mundane cakes & incorporating the source 30u of sugar

2025-05-11 04:24 UTC, sowelipililimute commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/pie.yml
>            Quantity: 5
again taking berries as an example, that's 15u/12u source reagent becoming 15u/5u, not counting the stuff in the pie dough. this needs to be a buff to meet the stated goals of the PR.

2025-05-11 04:24 UTC, sowelipililimute commented on Resources/Prototypes/Entities/Objects/Consumable/Food/burger.yml
> +        maxVol: 45
math checks out for the burgers, gains a few nutriments over the source ingredients

2025-05-11 16:21 UTC, Stop-Signs commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/pie.yml
>            Quantity: 5
Thanks for your review I appreciate it a ton, ill push a commit to resolve this ASAP!

2025-05-11 16:29 UTC, Stop-Signs commented
I've buffed pies and added sugar since most pie fillings are sweet, the pie slices are exactly 1/4th the reagents of the full pie since you get 4 slices

2025-05-13 16:31 UTC, sowelipililimute approved these changes
definitely an improvement to a lot of foods vs where we stand today

2025-05-25 18:01 UTC, beck-thompson approved these changes
There are a few minor issues but its so much better than before lets send it

2025-05-25 18:02 UTC, merged

2025-05-25 18:59 UTC, beck-thompson commented
> Could you list them out or open an issue for people to fix

Just more of the issues this PR was fixing. Not all the recipes make sense and sometimes the extra fill space is the "wrong" amount