Id console fix
space-wizards/space-station-14 pull request #34142
Opened 2024-12-31 00:20 UTC by Pequemax

## About the PR

Fixed a bug where if the priviliged id card had missing accesses compared to the id card to be modified it would not change the resulting accesses.

## Why / Balance

## Technical details

Fixed the way the difference is calculated, wich caused the issue.

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-12-31 11:10 UTC, PJB3005 requested changes
This still doesn't seem to work properly. From testing, trying to modify an ID card with centcomm access causes that access level to be removed silently.

2024-12-31 13:20 UTC, Pequemax commented
Is there a place where all the "protected" access are saved?(Like syndicate, centcomm, etc) My main issue are with these ones

2024-12-31 15:57 UTC, PJB3005 commented
> Is there a place where all the "hidden" access are saved?(Like syndicate, centcomm, etc) My main issue are with these ones

I feel like any solution that requires knowing all hidden accesses (instead of simply solely working off the ones available to the ID console) is fundamentally flawed?

2024-12-31 16:44 UTC, Pequemax commented
I was planning to do a datafield with all the access that are unknown to the user of the computer, its less than an ideal solution since they would need to be updated everytime a new traitor role is added

2024-12-31 16:47 UTC, Pequemax commented
I got 2 ideas to fix the issue about the missing hidden access, the first one is add them to the id console as normal access, but they will stick out like a sore thumb(though the computer user would not be able to see if they have it or not), and the other one is to add them to the console component as hidden access, but that would have the problem outlined in the previous comment, plus the fact that i am not too proficient with the codebase

2024-12-31 19:37 UTC, Pequemax commented
All right, I think I managed to get it working, I tested HoP removing Cap access, Centcom and Syndies keeping their hidden access, and HoP trying to remove access they dont have, but i think I overcorrected something since the UI/UX label popped. I had to add a list of all hidden access to make it work tho, so it might not be good to pull

2024-12-31 20:09 UTC, PJB3005 requested changes
Adding a list of unknown accesses is not a proper way to do this. Just make the console not remove access levels on the ID card that the console can't give out.

2024-12-31 22:11 UTC, Pequemax commented
Apologies for the back and forth, fixed without the use of a list for the hidden access, checked with:

- HoP removing Cap access, both permited and prohibited
- Hop giving syndies access, and keeping Nuke Ops access
- Hop giving centcomm access, and keeping Centcomm access

2025-01-01 18:23 UTC, PJB3005 requested changes

2025-01-01 18:23 UTC, PJB3005 commented on Content.Server/Access/Systems/IdCardConsoleSystem.cs
> +        var hiddenAccess = difference.Except(visibleDifference).ToList();
It makes more sense to calculate this as `difference.Except(ableToModify)` instead.

2025-01-01 18:23 UTC, PJB3005 commented on Content.Server/Access/Systems/IdCardConsoleSystem.cs
> +        var difference = addedTags.Union(removedTags).ToHashSet();
`.ToHashSet()` is needlessly expensive.

2025-01-01 18:23 UTC, PJB3005 commented on Content.Server/Access/Systems/IdCardConsoleSystem.cs
> +        _access.TrySetTags(targetId, newAccessList.Union(hiddenAccess));
The way this code works is extremely non-obvious, and I had to check your code out in a debugger to even understand it. You are implicitly relying on `hiddenAccess` only ever containing negative differences due to removal of these tags by the UI, which works, but is extremely unclear.

Please either restructure this code to make the behavior more obvious, or make it heavily commented.

2025-01-01 18:23 UTC, PJB3005 commented on Content.Server/Access/Systems/IdCardConsoleSystem.cs
> +            $"{ToPrettyString(player):player} has modified {ToPrettyString(targetId):entity} with the following accesses: [{string.Join(", ", changes)}] [{string.Join(", ", newAccessList)}]");
This doesn't correctly log the resulting access list, as `newAccessList` won't show hidden accesses.

2026-06-21 23:48 UTC, whatston3 commented
Should be closed, superceded [by] #44016.  Cheers for the bugfix!

2026-06-22 07:45 UTC, closed without merging