removes ambience from the lobby
space-wizards/space-station-14 pull request #3428
Opened 2021-02-26 08:25 UTC by tmtmtl30

![image](https://user-images.githubusercontent.com/53132901/109275079-1b97d800-77c9-11eb-8b07-aa9edd931bcf.png)
ok

2021-02-27 17:39 UTC, PaulRitter approved these changes

2021-02-27 17:40 UTC, PaulRitter requested changes
small nitpick, otherwise good job :+1:

2021-02-27 17:40 UTC, PaulRitter commented on Content.Client/GameObjects/EntitySystems/AmbienceSystem.cs
> +        }
i'd call endambience before creating a new stream here, just to make sure :^)

2021-03-01 07:17 UTC, tmtmtl30 commented
handled.

2021-03-03 03:46 UTC, metalgearsloth approved these changes

2021-03-03 03:47 UTC, merged