Water vapor now makes puddles under 100ºC above 1 moles
space-wizards/space-station-14 pull request #3489
Opened 2021-03-03 15:06 UTC by Zumorica

## About the PR 
Water vapor under 100ºC will create puddles if the gas amount is greater than 1 mole.
For now, 1 mole = 1 reagent unit. Very simple stuff. Gas reactions can now take a maximum temperature, which defaults to `float.MaxValue`.

**Screenshots**
![Peek 2021-03-03 16-04](https://user-images.githubusercontent.com/6766154/109825574-3e4b4600-7c3a-11eb-8250-1ca10ba4e833.gif)

**Changelog**
:cl:
- add: Water vapor now make puddles if they're under 100ºC.

2021-03-04 03:43 UTC, metalgearsloth approved these changes

2021-03-05 13:31 UTC, PaulRitter commented
pls update to use serv3 c:

2021-03-05 16:25 UTC, Clyybber commented on Content.Server/Atmos/Reactions/GasReactionPrototype.cs
> +		[DataField("maximumTemperature")]
```suggestion
		  [DataField("maximumTemperature")]
```

2021-03-05 21:13 UTC, PaulRitter requested changes
god those immutable prototype datafields make me happy.
fix what clybber mentioned & get merged

2021-03-05 21:15 UTC, merged