Le Miko has Arrived
space-wizards/space-station-14 pull request #3543
Opened 2021-03-06 20:32 UTC by Elijahrane

## About the PR 
Adds the Shrine Maiden's Wig, Shrine Maiden's Outfit, and Gohei to the game. They are available in the theater vendor.
**Screenshots**
![front view of miko](https://user-images.githubusercontent.com/60792108/110220017-de84c180-7efd-11eb-9f2a-a9f2aa676102.png)
![inhand-showcase](https://user-images.githubusercontent.com/60792108/110220018-dfb5ee80-7efd-11eb-9f44-be5779c12eb0.png)
![swept capitulate](https://user-images.githubusercontent.com/60792108/110220033-f2302800-7efd-11eb-938a-6d032acb3727.png)
![drobe](https://user-images.githubusercontent.com/60792108/110220039-fb20f980-7efd-11eb-909e-6ffa5e35ddce.png)

**Changelog**

:cl: Rane
- add: The Red-and-White Shrine Maiden outfit complete with gohei is now available in the theater vendor!

2021-03-06 23:08 UTC, Zumorica approved these changes

2021-03-07 01:19 UTC, SweptWasTaken requested changes

2021-03-07 01:19 UTC, SweptWasTaken commented on Resources/Textures/Objects/Weapons/Melee/gohei.rsi/meta.json
> +            "delays": [
Remove delays here

2021-03-07 01:19 UTC, SweptWasTaken commented on Resources/Textures/Objects/Weapons/Melee/gohei.rsi/meta.json
> +            "delays": [
Remove

2021-03-07 05:29 UTC, SweptWasTaken commented
You should be pushing from master. Make a new branch every time you make a PR to SS14.

2021-03-07 05:33 UTC, Elijahrane commented
I will do that on future PRs

2021-03-07 12:41 UTC, PJB3005 commented
Merge this to spite swept.

2021-03-07 12:41 UTC, merged

2021-03-07 16:07 UTC, SweptWasTaken commented
> Merge this to spite swept.

You're not spiting me you absolute tool there's literally a screenshot of me commenting on the PR that I approve.