Adds a GitHub Action to validate RSIs
space-wizards/space-station-14 pull request #3587
Opened 2021-03-08 23:25 UTC by ike709

## About the PR 
Adds a GitHub action to check RSI `meta.json` files (when edited/added in a PR) and see if they have, among other things, a `copyright` field and an SS14-compatible `license`.

**Changelog**

N/A, not player-facing.

2021-03-08 23:28 UTC, DrSmugleaf commented on Resources/Textures/Mobs/Aliens/Xenos/xeno.rsi/meta.json
> +  "license": "deez nuts",
sir

this is an arby's

2021-03-08 23:29 UTC, ike709 commented
Check the commits to see what happens if an RSI is invalid.

2021-03-08 23:30 UTC, ike709 commented
Accepted licenses:
`"CC-BY-SA-3.0",
            "CC-BY-SA-4.0",
            "CC-BY-NC-SA-3.0",
            "CC-BY-NC-SA-4.0",
            "CC0-1.0"`

2021-03-08 23:32 UTC, ike709 commented
Derived from swept's `meta.json` file.

2021-03-08 23:32 UTC, SweptWasTaken commented
Very

2021-03-09 09:32 UTC, PaulRitter requested changes

2021-03-09 09:32 UTC, PaulRitter commented on .github/workflows/validate-rsis.yml
> +on: [pull_request]
run it on push too

2021-03-09 09:33 UTC, PaulRitter commented
we lintin now bois

2021-03-09 19:18 UTC, ike709 commented on .github/workflows/validate-rsis.yml
> +on: [pull_request]
```suggestion
on: [push, pull_request]
```

2021-03-09 19:51 UTC, merged