Adds lobby music
space-wizards/space-station-14 pull request #3620
Opened 2021-03-11 22:14 UTC by ike709

## About the PR 
Adds lobby music. Can be toggled in the settings or directly via cvar. Also fixes ambient hum so it actually stops when you disconnect.

TODO:
- [ ] Add a couple more songs
- [ ] Consider renaming AmbienceSystem?
- [ ] Finalize the audio params. I'm currently testing with terrible earbuds.

**Screenshots**

https://streamable.com/v9yeg9

**Changelog**

:cl:
- add: Added lobby music. It can be disabled in the audio settings.
- fix: Fixed the ambience continuing to play after you disconnect.

2021-03-11 22:37 UTC, GraniteSidewalk commented on Content.Client/GameObjects/EntitySystems/AmbienceSystem.cs
> +            else if (_stateManager.CurrentState is LobbyState)
You forgot the case where musicEnabled && !_stateManager.CurrentState is LobbyState - might want to call EndLobbyMusic() in that case just to be safe

2021-03-11 22:42 UTC, GraniteSidewalk commented
Pretty simple PR, don't see really anything wrong with it but I do think you should rename AmbienceSystem to something better.

2021-03-11 23:47 UTC, ike709 commented
I can't test the audio params super well so I'll wait for codejannie feedback.

2021-03-12 00:29 UTC, ike709 commented on Content.Client/GameObjects/EntitySystems/BackgroundAudioSystem.cs
> +            if (file == null) // Just in case we fail to get a song from the server, play one at random.
For some reason we're failing to get the server's song and we're falling back on a randomized one.

2021-03-12 00:32 UTC, ike709 commented on Content.Client/GameObjects/EntitySystems/BackgroundAudioSystem.cs
> +            if (file == null) // Just in case we fail to get a song from the server, play one at random.
If I disconnect and then reconnect, all connections after the first work fine.

2021-03-12 01:02 UTC, ike709 commented on Content.Client/GameObjects/EntitySystems/BackgroundAudioSystem.cs
> +            if (file == null) // Just in case we fail to get a song from the server, play one at random.
The StateChanged code seems to fire before the client actually receives the net message. Not sure what to do about that.

2021-03-12 01:06 UTC, ike709 commented
Code should be good to go, I think?

2021-03-12 01:09 UTC, ike709 commented
Should be good to go?

2021-03-12 01:23 UTC, ike709 commented
One bug: Latejoins don't get lobby music.

2021-03-12 01:45 UTC, ike709 commented
I have no idea why latejoins don't get music.

2021-03-12 02:49 UTC, ike709 commented
When latejoining (and _only_ when latejoining, somehow), `MsgTickerLobbyStatus` is sent containing the correct value but when it is received the song string is null.

2021-03-12 03:08 UTC, ike709 commented
Latejoin music fixed, this should be fully good to go.

2021-03-12 10:25 UTC, metalgearsloth requested changes
Seems okay if it works ingame.

2021-03-12 10:25 UTC, metalgearsloth commented on Content.Shared/GameTicking/SharedGameTicker.cs
> +
Just for readability sake probably good to have property order in buffer order.

2021-03-12 10:25 UTC, metalgearsloth commented on Content.Client/GameObjects/EntitySystems/BackgroundAudioSystem.cs
> +            _lobbyStream.Stop();
```suggestion
            _lobbyStream?.Stop();
```

2021-03-12 10:25 UTC, metalgearsloth commented on Content.Client/GameObjects/EntitySystems/BackgroundAudioSystem.cs
> +            _ambientStream.Stop();
```suggestion
            _ambientStream?.Stop();
```

2021-03-12 22:40 UTC, DrSmugleaf approved these changes

2021-03-12 22:40 UTC, merged