Adds more surgery tools and resprites existing
space-wizards/space-station-14 pull request #3631
Opened 2021-03-12 22:30 UTC by SweptWasTaken

## About the PR 

The bone saws look a little strange, but IRL bone saws for surgery look lame as fuck, and this makes me think the upgraded ones will be for like cutting carapace or chitin or something. They all have cool inhands too.

**Screenshots**

![Content Client_2021-03-12_14-11-37](https://user-images.githubusercontent.com/49448379/111004514-1b7b0900-8381-11eb-948a-d39ce3318124.png)
**Changelog**

:cl: Swept
- add: Resprites surgery tools
- add: More advanced/unadvanced surgery tools

2021-03-13 08:16 UTC, metalgearsloth requested changes

2021-03-13 08:16 UTC, metalgearsloth commented on Resources/Textures/Objects/Specific/Medical/Surgery/scalpel.rsi/desktop.ini
> +shiv.png=@shiv.png,0
what

2021-03-13 08:16 UTC, metalgearsloth commented on Resources/Textures/Objects/Specific/Medical/Surgery/desktop.ini
> +hemostat.png=@hemostat.png,0
what

2021-03-13 08:18 UTC, SweptWasTaken commented on Resources/Textures/Objects/Specific/Medical/Surgery/scalpel.rsi/desktop.ini
> +shiv.png=@shiv.png,0
What the fuck

2021-03-16 07:48 UTC, PaulRitter approved these changes

2021-03-16 07:48 UTC, merged