Hudthemes
space-wizards/space-station-14 pull request #3774
Opened 2021-04-01 01:21 UTC by ike709

## About the PR 

Branched from https://github.com/space-wizards/space-station-14/pull/3718.

Adds theme presets to the HUD, so people can no longer bikeshed about icons.

**Screenshots**

https://streamable.com/ff7zex

**Changelog**

:cl:
- add: You can now set your HUD's theme in the settings.

2021-04-01 04:50 UTC, SweptWasTaken commented
Did you really just branch my PR without telling me or nuthin??

2021-04-01 22:08 UTC, ike709 commented
I clicked the wrong button in git, will fix later.

2021-04-02 01:44 UTC, ike709 commented
Git unbroken.

2021-04-02 02:05 UTC, SweptWasTaken commented
What's the default theme with this PR?

2021-04-02 02:16 UTC, ike709 commented
Yours.

2021-04-02 02:21 UTC, SweptWasTaken commented
> 
> 
> Yours.

Coo'

It's nothing personal against your pixel one I just think this one fits the theme better for first timers.

2021-04-02 22:25 UTC, ike709 commented
This is ready for review btw.

2021-04-11 14:53 UTC, Zumorica requested changes
Just a few nitpicks, overall looks good to me

2021-04-11 14:53 UTC, Zumorica commented on Content.Client/GameObjects/Components/HUD/Inventory/HumanInventoryInterfaceController.cs
> +        public void UpdateHudTheme(int _)
Why take in an int if you're gonna discard it?

2021-04-11 14:53 UTC, Zumorica commented on Content.Client/UserInterface/HandsGui.cs
> +        private void UpdateHudTheme(int _)
Why take in an int if you're gonna discard it?

2021-04-11 14:53 UTC, Zumorica commented on Content.Client/UserInterface/OptionsMenu.Graphics.cs
> +                _hudThemeOption.AddItem(Loc.GetString("ui-options-hud-theme-classic"));
instead of hardcoding the theme options, enumerate the HUD theme prototypes using `IPrototypeManager.EnumeratePrototypes<T>`

2021-04-11 15:03 UTC, Zumorica requested changes

2021-04-11 15:03 UTC, Zumorica commented on Content.Client/UserInterface/GameHud.cs
> +        }
This shouldn't really be here, have your HUD manager subscribe to `IConfigurationManager.OnValueChanged` and correct the value if it's ever changed to something incorrect. This also has the advantage of `invokeImmediately`, which lets you correct the value when the game starts, if it's incorrect!

2021-04-11 15:03 UTC, Zumorica commented on Content.Client/UserInterface/HandsGui.cs
> +            _configManager.OnValueChanged(CCVars.HudTheme, UpdateHudTheme, invokeImmediately: true);
Read my review above, you should correct the value if it's incorrect in `UpdateHudTheme`

2021-04-11 19:16 UTC, Zumorica requested changes

2021-04-11 19:16 UTC, Zumorica commented on Content.Client/UserInterface/GameHud.cs
> +            return _resourceCache.GetTexture($"/Textures/Interface/Inventory/{dir}/{path}");
Don't do this... Use `ResourcePath` instead.

2021-04-11 21:51 UTC, Zumorica commented on Content.Client/UserInterface/GameHud.cs
> +                throw new ArgumentOutOfRangeException();
what you can do here is reverse the operator, something like this:
```csharp
if (!_prototypeManager.TryIndex(...))
{
    throw new ArgumentOutOfRangeException();
}

// do thingies here, prototype will never be null from here onwards!

2021-04-11 22:25 UTC, ike709 commented on Content.Client/UserInterface/GameHud.cs
> +            }
```suggestion
            if (!_prototypeManager.TryIndex(id.ToString(), out HudThemePrototype? proto))
            {
                throw new ArgumentOutOfRangeException();
            }
            dir = proto.Path;
```

2021-04-11 22:43 UTC, merged