Nukes any mention of CollisionGroup.Clickable
space-wizards/space-station-14 pull request #3782
Opened 2021-04-01 05:17 UTC by SweptWasTaken

## About the PR 

Just removes it from everything that had it.

2021-04-01 05:43 UTC, mirrorcult commented on Resources/Prototypes/Entities/Constructible/Specific/traitordm.yml
> -      mass: 1
intended?

2021-04-01 07:30 UTC, metalgearsloth requested changes
Stuff with no mask or layer shouldn't exist so those physics components will need removing.

2021-04-01 07:30 UTC, metalgearsloth commented on Content.Shared/Physics/CollisionGroup.cs
> +        Passable        = 1 <<  7, // 256 Things that are passable
You didn't update the integer references

2021-04-03 23:55 UTC, SweptWasTaken commented
Reviews applied, I moved stuff like the chargers and the morgue stuff over to Constructible while I was at it.

2021-04-08 11:23 UTC, metalgearsloth approved these changes

2021-04-08 11:44 UTC, merged