Moves Hands to shared, some prediction
space-wizards/space-station-14 pull request #3829
Opened 2021-04-11 22:48 UTC by collinlunn

Moves a majority of hand code to shared, makes held item sprites be handled by a visualizer, implements prediction for swapping hands and dropping items.

A lot of stuff is WIP still but I want to consolidate what I've done so far, since PR size is piling up.

2021-04-12 15:10 UTC, ike709 commented
There's some sus changes in here, might want to test that this doesn't break HUD themes.

2021-04-13 10:31 UTC, metalgearsloth commented on Content.Client/GameObjects/EntitySystems/HandsSystem.cs
> +        }
We have directed versions of the eventbus for this now so you don't need to TryGet it, buckle uses it from memory.

2021-05-25 23:03 UTC, collinlunn commented
Fixed what issues I could find with the changes. Hand code still needs work for further cleanup of obsolete methods, general code quality improvement, and to implement the rest of prediction.

2021-06-05 16:04 UTC, metalgearsloth requested changes
I'm not gonna be anal on ECS as this was done before it.

Personally I'd prefer that hands get refactored entirely in one go rather than piecemealed over PRs but this is fine for now once the reviews are done.

2021-06-13 21:59 UTC, collinlunn commented on Content.Shared/GameObjects/EntitySystems/SharedHandsSystem.cs
> +        }
Client now specifies which hand it is dropping from, the prevent any desyncs from preventing the player form dropping from their intended hand.

2021-06-13 22:00 UTC, collinlunn commented on Content.Shared/GameObjects/EntitySystems/SharedHandsSystem.cs
> +        }
Fixed the same way to the dropping event.

2021-06-13 22:55 UTC, collinlunn commented on Content.Client/GameObjects/Components/Items/HeldItemsVisualizer.cs
> +            }
Not sure how I'd go about that, I think I'll call that out of scope.

2021-06-13 23:25 UTC, collinlunn commented on Content.Server/GameObjects/Components/GUI/HandsComponent.cs
> +            var initialPosition = outermostEntity.Transform.Coordinates;
I'm fairly sure the 0,0 lerp is fixed. WorldPosition would be cleaner that looping to find the outermost container, but I would need to to change the animation or make another coordinate conversion helper, which I am calling out of scope, putting a TODO on it.

2021-06-13 23:42 UTC, collinlunn commented on Content.Client/GameObjects/Components/Items/HandsComponent.cs
>          }
I've cleaned the gui handling to hopefully be more clear that the subscriptions are handled right.

2021-06-14 00:36 UTC, collinlunn commented on Content.Shared/GameObjects/EntitySystems/SharedHandsSystem.cs
> +            SubscribeNetworkEvent<DropMessage>(HandleDrop);
I'm not sure I fully understand what you are asking about.

Currently, the client issues a SwapHands event by `RaisePredictiveEvent` which raises both a local and networked version of the event. The local event triggers the predicted hand swap, and the networked event causes the server to run the hand swap and send back the updated state.

2021-06-16 14:47 UTC, metalgearsloth approved these changes

2021-06-16 14:47 UTC, metalgearsloth commented
Fix conflict (Probably needs the namespace update too).

2021-06-17 22:20 UTC, collinlunn commented
Went through and made sure everything is in the new appropriate folders and namespaces,

2021-06-21 09:21 UTC, merged