Add cvar thresholds to gas overlays
space-wizards/space-station-14 pull request #3835
Opened 2021-04-12 13:08 UTC by metalgearsloth

Rather than having 256 thresholds it can now be reduced to whatever you want.

:cl:
- add: Add cvar to specify discrete gas overlay thresholds

2021-05-20 21:29 UTC, ShadowCommander approved these changes

2021-06-06 05:10 UTC, metalgearsloth commented
@Zumorica I logged how many tiles get sent with plasmaflooding 10,000 units:

Master:
![image](https://user-images.githubusercontent.com/31366439/120913256-1e17a100-c6d9-11eb-9b2f-e968d6ae0326.png)

PR:
![image](https://user-images.githubusercontent.com/31366439/120913260-28399f80-c6d9-11eb-8a93-4c25b9828b42.png)

2021-06-15 06:39 UTC, Zumorica requested changes
Good PR, just needs some cleanup regarding CVars and it's good to merge

2021-06-15 06:39 UTC, Zumorica commented on Content.Server/GameObjects/EntitySystems/Atmos/GasTileOverlaySystem.cs
> +            configManager.OnValueChanged(CVars.NetMaxUpdateRange, value => _updateRange = value + RangeOffset);
The configuration manager's `OnValueChanged` has a parameter to invoke the lambda immediately so you don't need to duplicate the code and manually get the tick rate, range, etc

2021-06-21 07:08 UTC, merged