Trash bags tweaks
space-wizards/space-station-14 pull request #3866
Opened 2021-04-16 21:14 UTC by Macoron

## About the PR 
Check changelog.

Add new storage fill visualizer. It will receive appearance data from `ServerStorageComponent` and change sprite depending on filled volume. Because security and performance reasons, `ServerStorageComponent` will send volume data only if `showFillLevel` is true.

**Changelog**

:cl:
- tweak: Trash bags now change sprite when you add junk inside.
- tweak: You can dump all trash into disposal from trash bag.

2021-04-28 07:04 UTC, metalgearsloth requested changes

2021-04-28 07:04 UTC, metalgearsloth commented on Content.Client/GameObjects/Components/Storage/StorageFillVisualizer.cs
> +            var closestFillSprite = (int) Math.Round(fillPercent * _maxFillLevels);
There's 2 ContentHelpers.RoundToLevels but people complain it doesn't round the way they want so ¯\\\_(ツ)\_/¯

2021-04-28 07:04 UTC, metalgearsloth commented on Content.Server/GameObjects/Components/Disposal/DisposalUnitComponent.cs
> +            }
IMO better off making it a new component and dumping the logic onto a system given it'll make any future changes much easier e.g. if someone wanted to be able to empty one trash bag into another or something.

2021-04-28 14:01 UTC, Macoron commented on Content.Server/GameObjects/Components/Items/Storage/ServerStorageComponent.cs
> +            }
Not sure if I understand. What the difference between `ComponentDependency` and `TryGetComponent`?

2021-05-01 19:22 UTC, metalgearsloth commented on Content.Server/GameObjects/Components/Items/Storage/ServerStorageComponent.cs
> +            }
ComponentDependency has the field vs resolving it when needed. Depends how often it gets called as to whether it matters.

2021-06-05 16:06 UTC, metalgearsloth commented
You coming back to this Macoron or busy_irl?

2021-06-14 20:53 UTC, Macoron commented
Well, I'll better close this for now. If anyone willing to return. feel free to do so.

2021-06-14 20:53 UTC, closed without merging