Implement fluent for some Menu files
space-wizards/space-station-14 pull request #3893
Opened 2021-04-26 14:32 UTC by Visne

Implement fluent for

BlockGameMenu
SpaceVillainArcadeMenu
CommunicationsConsoleMenu
ConstructionMenuPresenter
ConfigurationMenu
WiresMenu
LatheQueueMenu

2021-04-26 14:55 UTC, RemieRichards commented on Content.Client/Construction/ConstructionMenuPresenter.cs
> +            uniqueCategories.Add(Loc.GetString("construction-presenter-all"));
`construction-presenter-category-all`?

2021-04-26 14:56 UTC, RemieRichards commented on Content.Client/GameObjects/Components/Configuration/ConfigurationMenu.cs
> +            Title = Loc.GetString("configuration-device");
I like the `-title` suffix you had for some of the other menus, it'd be nice if that was used consistently!

2021-04-26 14:56 UTC, RemieRichards commented on Content.Client/GameObjects/Components/Wires/WiresMenu.cs
> +                        Text = Loc.GetString("wires-wires"),
You know what's wrong with this

2021-04-26 14:57 UTC, RemieRichards commented on Content.Client/GameObjects/Components/Wires/WiresMenu.cs
> +                        Text = Loc.GetString("wires-dead-beef"),
this is a tricky one, `DEAD-BEEF` is hexadecimal, it's not *really* in english at all.
I probably wouldn't translate this at all.

2021-04-26 14:58 UTC, RemieRichards commented
In general good, but left some points to go over

2021-04-27 07:42 UTC, RemieRichards commented on Content.Client/Arcade/BlockGameMenu.cs
> +                Text = Loc.GetString("blockgame-new-game"),
Sorry, didn't mention this yesterday but, maybe make these `blockgame-button-new-game`, `blocgkame-button-scoreboard` etc.

Just in general try to include a *little* bit more context

2021-04-27 07:42 UTC, RemieRichards commented on Content.Client/Arcade/BlockGameMenu.cs
> +            gameOverMenuContainer.AddChild(new Label{Text = Loc.GetString("blockgame-game-over"),Align = Label.AlignMode.Center});
`blockgame-msg-game-over` maybe?

2021-04-27 07:42 UTC, RemieRichards commented on Content.Client/Arcade/BlockGameMenu.cs
> +            menuContainer.AddChild(new Label{Text = Loc.GetString("blockgame-highscores")});
labels get `-label-` in their message Ids?

2021-04-27 07:44 UTC, RemieRichards commented on Content.Client/Command/CommunicationsConsoleMenu.cs
> +                PlaceHolder = Loc.GetString("communications-console-announcement"),
`communications-console-announcement-placeholder`?

2021-04-27 07:47 UTC, RemieRichards requested changes
Sorry I didn't really consider any of these yesterday.

Also thinking maybe these all need `menu` in them somewhere? mainly for the case where an item has a menu, it could get confusing whether a message refers to the item (i.e. an interaction) or the item's menu.
@PJB3005 ^ ?

2021-05-21 13:00 UTC, Visne commented
Oh god it's been three weeks
Ready for review again

2021-05-21 13:03 UTC, PaulRitter approved these changes

2021-05-21 13:03 UTC, PaulRitter commented
gtm with @RemieRichards approval

2021-05-21 13:08 UTC, RemieRichards commented
PJ's clearly not listening so, implement the last thing I said above and I'll sign off on it.

2021-05-21 13:26 UTC, Visne commented
> 
> 
> PJ's clearly not listening so, implement the last thing I said above and I'll sign off on it.

@RemieRichards Done.

2021-05-21 13:30 UTC, RemieRichards approved these changes

2021-05-21 13:39 UTC, merged