Surgery
space-wizards/space-station-14 pull request #3939
Opened 2021-05-07 02:17 UTC by DrSmugleaf

## About the PR 
[WIP hackmd doc](https://hackmd.io/@ss14/surgery)

This PR refactors all of surgery. It was previously the last part of body system that had not been touched since [this PR](https://github.com/space-wizards/space-station-14/pull/1544).

Surgeries are now defined in YAML and their effects are short snippets of code written in C#. This follows the same pattern as DestructibleComponent, where a surgery tool has a behavior, an operation has a list of required steps, and once those steps are fulfilled its effect executes.

This is meant to be able to be flexible enough to implement whatever surgery operations are wanted in the future. I have based the system in this PR around the surgeries on the [baystation wiki](https://wiki.baystation12.net/Surgery). This is not an explicit design choice, I just work here.

At the moment surgeries that are underway can be canceled with drapes if no steps have been done yet or with a cautery otherwise.

Thanks to @ike709 for the help with moving surgeries from the wiki to yaml prototypes and localization.

TODO:
- [ ] The entity that you are operating on shows up on the operation selection list.
- [ ] The part list in the operation selector shows the part sprites.
- [ ] All of it is ECS.
- [ ] SurgeonComponent has data about what surgeries an entity can perform.
- [ ] Performing surgery on ~a grape~ dismembered limbs. 
- [ ] Allow one surgeon to perform multiple surgeries at once.
- [ ] Allow multiple surgeons to perform surgery on a single target at once.
- [ ] Remove surgery drapes component in favor of surgery tool component.

TODO Effects:
- [x] Amputation.
- [x] Cauterization.
- [ ] Organ extraction.
- [ ] Artery repair.
- [ ] Autopsy.
- [ ] Bone repair.
- [ ] Facial reconstruction.
- [ ] Limb replacement.
- [ ] Object insertion.
- [ ] Object removal.
- [ ] Organ repair.

**Screenshots**
Menu that opens up when you use surgery drapes.
![image](https://user-images.githubusercontent.com/10968691/117357881-c5749e80-aeb5-11eb-8d11-6f5ca1615042.png)

**Changelog**
:cl:
- fix: Fixed surgery being broken.
- add: Added amputation and cauterization.

2021-05-07 06:34 UTC, metalgearsloth commented
![image](https://user-images.githubusercontent.com/31366439/117407560-120db780-af52-11eb-8d7d-e9e92d73efc2.png)

2021-09-14 12:37 UTC, DrSmugleaf commented
Ready for review.
[Docs](https://docs.spacestation14.io/en/content/surgery)

2021-09-17 09:11 UTC, metalgearsloth approved these changes
lgtm

2021-09-17 09:12 UTC, metalgearsloth approved these changes

2021-09-17 09:12 UTC, metalgearsloth approved these changes

2021-09-17 09:56 UTC, metalgearsloth commented
of all the things why the fark is projectile conflicting

2021-09-18 10:39 UTC, metalgearsloth approved these changes

2021-09-21 03:31 UTC, metalgearsloth requested changes
Should drapes apply to the person or out of scope? As it just remains in your hands.

Also it would be useful to have something like construction where it tells you what the steps are because I got NFI. I get some is supposed to be hidden but wasn't sure where the visible parts should be.

After I started a surgery I didn't seem to be able to stop it. I tried using drapes on the target again and on a new target and nothing happened. On the new target it brought up the window but after I selected a surgery it wouldn't start.

Another maintainer should probably suss it out like mirrorcult or vera.

2021-09-21 03:31 UTC, metalgearsloth commented on Content.Server/Body/Surgery/SurgerySystem.cs
> +                surgeon.Target != null &&
If AfterInteract is raised on the user then use ComponentManager.TryGetComponent instead and use the supplied uid.

2021-09-21 03:31 UTC, metalgearsloth commented on Content.Server/Body/Surgery/SurgerySystem.cs
> +                !target.TryGetComponent(out SharedBodyComponent? body))
Same here, target's probably a bit trickier if AfterInteract doesn't already have the target entityuid.

2021-09-21 03:31 UTC, metalgearsloth commented on Content.Server/Body/Surgery/SurgerySystem.cs
> +        private async void OnToolAfterInteract(EntityUid uid, SurgeryToolComponent tool, AfterInteractEvent args)
Vera added events for do_after @Zumorica so you should be able to ECS it a bit.

2021-09-21 03:31 UTC, metalgearsloth commented on Content.Server/Body/Surgery/SurgerySystem.cs
> +                }
I can't read these in-game as they get pushed out at once and look like elven text from lotr.

![image](https://user-images.githubusercontent.com/31366439/134105970-7cfb9c27-37a5-4cfd-87f0-d767a37a6703.png)

2021-09-21 03:31 UTC, metalgearsloth commented on Content.Server/Body/Surgery/SurgerySystem.cs
> +        }
I removed drapes from a target and got this 
![image](https://user-images.githubusercontent.com/31366439/134106001-c089c23c-a822-412a-aa89-cb17a9f178e8.png)

2021-09-21 03:31 UTC, metalgearsloth commented on Content.Server/Notification/NotifyExtensions.cs
> +            params IEntity[] except)
This is kinda dirty and it should really use filters but I'm fine with it for now I guess.

2021-09-21 03:31 UTC, metalgearsloth commented on Content.Shared/Body/Surgery/SharedSurgerySystem.cs
> +            args.Target.Surgeon = EntityManager.GetEntity(uid).GetComponent<SurgeonComponent>();
Use ComponentManager instead of EntityManager and cut out the middle man.

2021-09-21 03:31 UTC, metalgearsloth commented on Content.Shared/Body/Surgery/Surgeon/SurgeonComponent.cs
> +        }
Sir this is an ECS codebase.

Also use ComponentManager.

2021-09-21 03:31 UTC, metalgearsloth commented on Content.Shared/Body/Surgery/Target/SurgeryTargetComponent.cs
> +        }
As per other thingie.

2021-09-21 03:31 UTC, metalgearsloth commented on Resources/Prototypes/Surgery/Operations/organ_repair.yml
> +  - BoneGel
https://youtu.be/B3uk5bJcyM8?t=24

2021-11-07 00:32 UTC, AJCM-git commented
Re-open once you come back to it. Anybody else can pick this up if they want 
![image](https://user-images.githubusercontent.com/60196617/140627898-bf49d4e2-0baf-4ce1-8ff4-811e192342ae.png)

2023-03-27 14:31 UTC, deltanedas commented
i am currently working on reviving this

*god damn* its evil

2023-03-27 15:05 UTC, moonheart08 commented
More importantly: **do not use the code here jfc**

2023-03-27 19:28 UTC, deltanedas commented
ok so yes this code here is complete ass and i was basically fully rewriting it

2023-04-01 20:09 UTC, DrSmugleaf commented
Finally got around to finishing surgery

2023-04-01 20:11 UTC, ElectroJr approved these changes
lgtm

2023-04-01 20:11 UTC, merged

2023-04-01 22:04 UTC, PixelTheKermit commented
It's been one week.

2023-04-04 10:07 UTC, S1ss3l commented
![image](https://user-images.githubusercontent.com/45254902/229759315-135bbdf1-afb0-4d90-a177-9567a0da3394.png)

2023-04-04 13:44 UTC, deltanedas commented
so @DrSmugleaf are you gonna revive this for non bossfight(?)

2023-04-04 16:56 UTC, DrSmugleaf commented
> so @DrSmugleaf are you gonna revive this for non bossfight(?)

Not before wounds