Adds more splat and tweaks PuddleComponent.cs
space-wizards/space-station-14 pull request #3942
Opened 2021-05-08 07:49 UTC by SweptWasTaken

## About the PR 

PuddleComponent.cs had hard-coded sprite states that was supplied by the RSI file name? Was sus so I fixed it and updated all the puddle components in yaml.

I also added flour and tomato splatting.

**Screenshots**

![image](https://user-images.githubusercontent.com/49448379/117531392-cef32900-afd1-11eb-9194-58e6a6a556be.png)

**Changelog**

:cl: Swept
- add: You can splat bags of flour and tomatoes.

2021-05-09 06:01 UTC, mirrorcult commented on Content.Server/GameObjects/Components/Fluids/PuddleComponent.cs
> +                _spriteComponent.LayerSetState(0, $"{_spriteState}-{randomVariant}"); // TODO: Remove hardcode
do you need the comment still?

2021-05-15 09:23 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Fluids/PuddleComponent.cs
> +                _spriteComponent.LayerSetState(0, $"{_spriteState}-{randomVariant}"); // TODO: Remove hardcode
no

2021-05-15 09:26 UTC, PaulRitter requested changes
looks good

2021-05-15 09:26 UTC, PaulRitter commented on Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
> +          # Wow double-yolk you're so lucky!
```suggestion
```

2021-05-15 09:26 UTC, PaulRitter commented on Content.Server/GameObjects/Components/Fluids/PuddleComponent.cs
> +                _spriteComponent.LayerSetState(0, $"{_spriteState}-{randomVariant}"); // TODO: Remove hardcode
```suggestion
                _spriteComponent.LayerSetState(0, $"{_spriteState}-{randomVariant}");
```

2021-05-19 16:06 UTC, SweptWasTaken commented
Just direct-applied the reviews Paul left, will self-merge if I come back from breakfast and the tests are passing.

2021-05-21 00:19 UTC, merged