Fix clicking a locker while inside of said locker
space-wizards/space-station-14 pull request #3965
Opened 2021-05-11 09:01 UTC by ShadowCommander

Fixes #1535 the right way.

## About the PR 

**Changelog**

:cl:
- fix: Fixed clicking a locker when the player is inside of said locker.

2021-05-15 16:00 UTC, PaulRitter requested changes

2021-05-16 07:28 UTC, ShadowCommander commented
Added a test, but I needed to change UserInteraction and DoAttack to public. If this is a problem I can probably make a new method that calls each.

2021-05-17 07:56 UTC, PaulRitter requested changes

2021-05-17 07:56 UTC, PaulRitter commented on Content.IntegrationTests/Tests/Interaction/Click/InteractionSystemTests.cs
> +            MapCoordinates mapCoordinates = default;
these three get assigned an are then never used.

2021-05-17 08:31 UTC, PaulRitter approved these changes

2021-05-17 09:31 UTC, merged