Lower data usage
space-wizards/space-station-14 pull request #4005
Opened 2021-05-15 10:59 UTC by ShadowCommander

## About the PR 

Adds some checks to prevent Dirty being called when nothing changed.

2021-05-15 11:05 UTC, DrSmugleaf requested changes

2021-05-15 11:05 UTC, DrSmugleaf commented on Content.Server/GameObjects/Components/Metabolism/MetabolismComponent.cs
> +                && alertsComponent.IsShowingAlert(AlertType.LowOxygen))
Isn't this already handled by ServerAlertsComponent?
https://github.com/space-wizards/space-station-14/blob/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Content.Shared/GameObjects/Components/Mobs/SharedAlertsComponent.cs#L140-L143

2021-05-15 11:05 UTC, DrSmugleaf commented on Content.Server/GameObjects/Components/Body/Behavior/StomachBehavior.cs
> +                bloodstream.TryTransferSolution(transferSolution);
This should be checked in the TryTransferSolution method instead.

2021-05-16 20:37 UTC, PaulRitter approved these changes

2021-05-16 20:37 UTC, merged