Add pasta
space-wizards/space-station-14 pull request #4018
Opened 2021-05-18 12:14 UTC by Ygg01

This is a behind the scene update, it replaces Fluent.Net with Linguini (the Code Pasta ;) ) 

Keep in mind, Linguini is much stricter with regards to Fluent compatibility, so it will yell if you try to pass files that used to work before. 

That said, I checked the files by CnP on Fluent playground (https://projectfluent.org/play/) so the errors reported are actual errors and not false positives.

2021-05-18 12:58 UTC, moonheart08 commented
You *must* add a funny blue rat to merge this PR, sorry.

2021-05-18 12:59 UTC, DrSmugleaf requested changes
Where's the rat

2021-05-18 13:10 UTC, Zumorica requested changes
No rat, no approval from me.

2021-05-18 13:33 UTC, Ygg01 commented
Does this count:

https://i.pinimg.com/originals/e8/01/49/e801493d8099d44b98089ff9c668409a.jpg

2021-05-18 13:34 UTC, DrSmugleaf approved these changes

2021-05-20 08:39 UTC, PaulRitter requested changes
better not have the submodule update in this pr

2021-05-22 14:42 UTC, Ygg01 commented
@PaulRitter Agreed, removed the Toolbox.

2021-05-27 10:49 UTC, Zumorica approved these changes

2021-05-27 10:49 UTC, merged