Makes the singularity engine actually work stably.
space-wizards/space-station-14 pull request #4068
Opened 2021-05-25 01:58 UTC by 20kdc

## About the PR

The singularity engine can now be entered into a stable state where it produces enough power to power the station and does not escape without external intervention.

Primarily this PR consists of correcting parts of `startsingularityengine`, and fixing bugs in various parts due to other system changes breaking them or the parts in general being... bad.

A GNU Octave script has been provided in `Tools` to simulate Singularity energy growth.

TODO:

- [x] Feasibly possible for Engineering to use Singularity Engine
- [ ] Correct the shader issues
- [ ] Map in an unfinished PA
- [ ] Balancing

**Screenshots**

![image](https://user-images.githubusercontent.com/22304167/119428229-6e1f5c80-bd04-11eb-9fb5-ba2926d9966b.png)

**Changelog**

:cl:
- fix: startsingularityengine starts the radiation emitters and no longer sets the PA into an unsafe mode.
- fix: Radiation collectors do not produce infinite energy when subjected to radiation.
- fix: Two singularities no longer instantly annihilate each other

2021-05-25 02:05 UTC, TimrodDX commented
Out of curiosity, does this fix the singularity killing people through walls? I know at one point I remember being in a sandbox game where there were people setting up a PA and I was a ghost and spawned a singularity on the generator to simulate the PA working and I remember it killing them via radiation damage through the station's walls.

2021-05-25 02:06 UTC, 20kdc commented
Nope, will still kill them straight through walls. Doesn't change how singularity radiation acts, which, for reference, is basically "anything in this radius gets radiation"

2021-05-25 02:15 UTC, ShadowCommander commented
To fix the radiation, hardsuits probably need radiation resistance, which is a separate thing from the Singularity.

2021-05-25 14:12 UTC, 20kdc commented
Right, as far as I can tell, this PR is as close to ready as it's going to get without further input from someone who isn't me.

2021-05-25 21:39 UTC, mirrorcult approved these changes

2021-05-25 23:30 UTC, mirrorcult commented
can the unfinished PA actually be built? i remember there being an issue with the PA not working properly when spawned from the unfinished versions because their prototype was fucked up

2021-05-26 09:07 UTC, PaulRitter requested changes
looks very good 👍 can't comment on the shader-scripts as i never touched that, but otherwise good job

2021-05-26 11:24 UTC, 20kdc commented
@mirrorcult I made sure to specifically test using the unfinished PA. It works.
If there's an issue, probably best to figure that out later once things *can* work

2021-05-26 11:25 UTC, 20kdc commented on Content.Client/Graphics/Overlays/SingularityOverlay.cs
> +                _singularities.Clear();
This is acting as a replacement for the situation where the "null eye" would be provided by EyeManager. Such an eye can see no singularities anywhere. Therefore, clear & return.

2021-05-26 11:27 UTC, 20kdc commented on Content.Server/Physics/Controllers/SingularityController.cs
>              if (singularity.Level <= 1) return;
A level 1 singularity may be pulled by another singularity.

2021-05-26 11:28 UTC, 20kdc commented on Resources/Prototypes/Entities/Constructible/Power/Engines/PA/particles.yml
> +      energy: 1
I won't commit this exact suggestion because I think it's important to note the dynamic elements here. I'll remove the value, but not the comment.

2021-05-26 11:29 UTC, 20kdc commented on Content.Server/GameObjects/Components/Power/PowerNetComponents/RadiationCollectorComponent.cs
> +                _enabled = value;
Done.

2021-05-27 00:14 UTC, TimrodDX commented
One thing I should add that might be beyond the scope of this PR (but since you're already re-mapping anyway) is that if the singulo eats containment, the emitters will all hit the station and be basically unstoppable killing machines due to the radiation.

2021-05-27 00:18 UTC, 20kdc commented
@TimrodDX That is not possible without sticking the singularity engine basically in the metaphorical middle of nowhere. As it is, it's unlikely that the singularity will eat containment in such a way that you won't have other problems.

2021-05-27 00:27 UTC, 20kdc commented
Some advice for future players if the emitters are in fact for some reason firing at a station *and* the singularity has not evaporated or left (the singularity is the radiation risk): Cut the MV wires that lead to the emitters, unwrench the emitter left and right substations, cut the wire bridge that leads to the PA room (though this requires waiting for those substations to discharge), or if all else fails, evacuate Engineering, as this is the only department that will be hit by the emitters.

2021-05-27 00:29 UTC, TimrodDX commented
> 
> 
> Some advice for future players if the emitters are in fact for some reason firing at a station _and_ the singularity has not evaporated or left (the singularity is the radiation risk): Cut the MV wires that lead to the emitters, unwrench the emitter left and right substations, cut the wire bridge that leads to the PA room (though this requires waiting for those substations to discharge), or if all else fails, evacuate Engineering, as this is the only department that will be hit by the emitters.

What happened when I tried setting it up just now (which admittedly is without this commit) is that the singularity went south and the emitters wound up hitting the library and penetrating right through to science.

2021-05-27 00:31 UTC, 20kdc commented
Ah. I appear to have misjudged how far down that area goes.
In that event, my advice remains: Cut the MV wires that lead to the emitters. Doing this should almost instantly kill emitter power.

2021-05-27 06:35 UTC, ShadowCommander commented
> 
> What happened when I tried setting it up just now (which admittedly is without this commit) is that the singularity went south and the emitters wound up hitting the library and penetrating right through to science.

I don't think emitters are supposed to be able to break through reinforced walls. That's a separate issue from the singulo stuff I think.

2021-05-28 09:43 UTC, PaulRitter approved these changes

2021-05-28 09:44 UTC, merged