Slims down disposal unit ui and fixes collisions
space-wizards/space-station-14 pull request #4122
Opened 2021-05-31 21:19 UTC by SweptWasTaken

## About the PR 

I cleaned up the disposal ui window and localized it. I also fixed it's physics to collide with items again meaning you can throw stuff into disposal units again.

After looking at the mess that is disposal mailing unit ui and realizing it's broken in game i've commented out the yaml for it as it's busted currently.

Closes #3875.
 

**Screenshots**

UI before
![image](https://user-images.githubusercontent.com/49448379/120242683-05c90180-c255-11eb-9c52-e031a5aed20e.png)

UI after
![image](https://user-images.githubusercontent.com/49448379/120242737-2abd7480-c255-11eb-9017-a672644bfe4a.png)

**Changelog**

:cl:
- fix: Throwing entities into disposal units now work
- tweak: Slims down disposal unit UI
- remove: Disposal mailing units for now

2021-05-31 21:20 UTC, mirrorcult commented on Content.Client/VendingMachines/VendingMachineMenu.cs
> +            SetSize = (Math.Clamp((longestEntry.Length + 8) * 12, 300, 400),
?

2021-05-31 21:21 UTC, SweptWasTaken commented on Content.Client/VendingMachines/VendingMachineMenu.cs
> +            SetSize = (Math.Clamp((longestEntry.Length + 8) * 12, 300, 400),
Idiot moment, was testing your PR kek.

2021-06-01 00:51 UTC, ShadowCommander requested changes

2021-06-02 18:43 UTC, SweptWasTaken commented on Content.Client/GameObjects/Components/Disposal/DisposalUnitWindow.cs
>              Contents.AddChild(new VBoxContainer
Sure but i'll do it in another PR.

2021-06-03 07:51 UTC, ShadowCommander requested changes

2021-06-03 07:51 UTC, ShadowCommander commented on Content.Client/GameObjects/Components/Disposal/DisposalUnitWindow.cs
> +            MinSize = SetSize = (300, 140);
Set Resizable to false maybe?

2021-06-03 07:51 UTC, ShadowCommander commented on Content.Client/GameObjects/Components/Disposal/DisposalUnitWindow.cs
> +                            new Control {MinSize = (4, 0)},
Can probably replace this with `HBoxContainer.SeparationOverride = 4` on the above HBoxContainer.

2021-06-03 07:51 UTC, ShadowCommander commented on Content.Client/GameObjects/Components/Disposal/DisposalUnitWindow.cs
> +                            new Control {MinSize = (4, 0)},
Same as above.

2021-06-03 07:51 UTC, ShadowCommander commented on Resources/Prototypes/Entities/Constructible/Piping/Disposal/units.yml
> +  parent: BaseConstructible
Can you use BaseMachinePowered or is this too different?

2021-06-04 00:17 UTC, SweptWasTaken commented
Reviews applied.

2021-06-04 00:25 UTC, ShadowCommander approved these changes

2021-06-04 00:26 UTC, merged