Plasma grinding
space-wizards/space-station-14 pull request #4161
Opened 2021-06-08 22:02 UTC by SethLafuente

## About the PR 
Made plasma grindable
**Screenshots**

![image](https://user-images.githubusercontent.com/84478872/121263393-6a461b00-c86a-11eb-9e57-701cb1150a20.png)

**Changelog**

:cl: Seth
- add: Added Grindable Plasma

2021-06-12 13:14 UTC, Zumorica commented
Related bug: https://github.com/space-wizards/space-station-14/issues/4179

2021-06-16 03:47 UTC, metalgearsloth requested changes

2021-06-16 03:47 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Materials/Sheets/other.yml
> +    - Grindable
Should be juiceable instead of grindable (ignore the name).

2021-06-17 23:21 UTC, SweptWasTaken commented
Looks like Seth deleted his remote-branch so I can't direct-edit this and merge it, so i'm going to close and direct commit it since it's such a small change.

2021-06-17 23:21 UTC, closed without merging