#3898 open sprite field for drink comp
space-wizards/space-station-14 pull request #4235
Opened 2021-06-27 12:25 UTC by GalacticChimp

## About the PR 

Fixes https://github.com/space-wizards/space-station-14/issues/3898

Drink cans now display differently based on their Opened state

![image](https://user-images.githubusercontent.com/63882831/123544351-29e40980-d753-11eb-92c1-447266327456.png)

Remaining issues:
- on swapping an opened can to another hand, the sprite will revert to a closed one, even though DrinkComponent.Opened == true
- same issue if an opened can is dropped/thrown

discusion on Discord:  https://discord.com/channels/310555209753690112/560845886263918612/858666750665293824

2021-06-27 12:26 UTC, GalacticChimp commented
Calling @SweptWasTaken and @metalgearsloth since they participated in the issue

2021-07-03 02:28 UTC, SweptWasTaken approved these changes

2021-07-03 02:29 UTC, SweptWasTaken commented
Code looks fine to me, @metalgearsloth .

2021-07-03 02:34 UTC, metalgearsloth requested changes
Bugs would also need fixing obv and I'd need to check it in-game.

2021-07-03 02:34 UTC, metalgearsloth commented on Content.Server/Nutrition/Components/DrinkComponent.cs
> +            if(Owner.TryGetComponent(out AppearanceComponent? appearance))
```suggestion
            if (Owner.TryGetComponent(out AppearanceComponent? appearance))
```

2021-07-03 02:34 UTC, metalgearsloth commented on Content.Shared/Nutrition/Components/SharedDrinkFoodContainerComponent.cs
> +    public enum DrinkCanStateVisuals
```suggestion
    public enum DrinkCanStateVisuals : byte
```

2021-07-03 02:34 UTC, metalgearsloth commented on Content.Client/Nutrition/Visualizers/DrinkCanVisualizer.cs
> +        [DataField("state_closed")]
Style guide is camelCase for yaml nodes.

2021-07-03 02:34 UTC, metalgearsloth commented on Content.Client/Nutrition/Visualizers/DrinkCanVisualizer.cs
> +            var sprite = component.Owner.GetComponent<ISpriteComponent>();
TryGet plz

2021-07-03 02:34 UTC, metalgearsloth commented on Content.Client/Nutrition/Visualizers/DrinkCanVisualizer.cs
> +                sprite.LayerSetState(0, $"{_stateOpen}");
I prefer being explicit about layers as it can avoid conflicting visualizers interfering.

2021-08-22 00:54 UTC, SweptWasTaken commented
Are you gonna come back to this @GalacticChimp?

2021-08-23 15:23 UTC, GalacticChimp commented
@GalacticChimp yes, I plan to finish all my PRs by end of this week

2021-09-22 11:05 UTC, metalgearsloth approved these changes
Fix conflicts

2021-09-28 17:07 UTC, GalacticChimp commented
> Fix conflicts

done.

2021-10-01 19:37 UTC, DrSmugleaf requested changes

2021-10-01 19:37 UTC, DrSmugleaf commented on Content.Server/Nutrition/EntitySystems/DrinkSystem.cs
> +        // TODO move to DrinkSystem
```suggestion
```

2021-10-03 04:56 UTC, merged