#4219 emit sound system add single sound support
space-wizards/space-station-14 pull request #4237
Opened 2021-06-27 19:57 UTC by GalacticChimp

Fixes #4219

2021-06-27 20:07 UTC, GalacticChimp commented
Calling @SweptWasTaken and @RemieRichards  since they opened the issue

2021-06-28 03:59 UTC, metalgearsloth approved these changes
Also check it doesn't give log errors in-game too.

2021-06-28 03:59 UTC, metalgearsloth commented
Ultimately this should be replaced with SoundSpecifier whenever we get that some day (like SpriteSpecifier... but for sounds).

2021-06-28 14:13 UTC, metalgearsloth commented
Okay so zumzum is now working on it so maybe revisit after #4239 is merged if you want the ideal version.

2021-06-30 18:23 UTC, GalacticChimp commented
@metalgearsloth ok, I'll wait a bit and do a proper full version, so we won't have to get back to this

2021-07-10 10:31 UTC, GalacticChimp commented
Don't merge yet, I'll add SoundSpecifier in other parts of the code as well

2021-07-10 10:32 UTC, Zumorica commented
Wouldn't it be better if you did multiple PRs? They'd be easier to review

2021-07-10 11:27 UTC, GalacticChimp commented
> Wouldn't it be better if you did multiple PRs? They'd be easier to review

on second thought, yes, this is a good idea

2021-07-12 08:10 UTC, Zumorica requested changes

2021-07-12 08:10 UTC, Zumorica commented on Content.Server/Sound/EmitSoundSystem.cs
> +            SubscribeLocalEvent<EmitSoundOnActivateComponent, ActivateInWorldEvent>((eUI, comp, args) => HandleEmitSoundOn(comp));
This is a bad idea, just make your methods take in the three arguments, even if two of them go unused.

2021-07-12 11:54 UTC, GalacticChimp commented on Content.Server/Sound/EmitSoundSystem.cs
> +            if (!string.IsNullOrWhiteSpace(component.Sound.GetSound()))
I'll add a TryGetSound() in a separate PR

2021-07-25 11:37 UTC, merged