Add more flexibility to BuckleComponent. Replaced ComponentMessage with ECS in BuckleComponent and ClimbComponent
space-wizards/space-station-14 pull request #4284
Opened 2021-07-18 10:09 UTC by Jackrost

## About the PR 

**Add more flexibility to BuckleComponent**
For TryBuckle:
*) Default Argument "check _range" - Now you can setting up if you want check range between Buckled Entity and Entity with StrapComponent. If "check_range" is false - range check will be ignored
*) Default Argument "range" - Buckle range can be setting up. By default it's as previous range now.
*)Add BuckleAttempt and UnbuckleAttempt Events. Now you can handle buckle Events. UnbuckleAttempt Event is only raises if TryUnbuckle was not forced("force" is false)

**Replaced ComponentMessage with ECS in BuckleComponent and ClimbComponent**

:cl:
- add: Add Climbing EntitySystem for Shared and Client
- add: Add "check_range" and "range" defaulft arguments to TryBuckle method
- add: Add cancellable BuckleAttemptEvent and UnbuckleAttemptEvent
- remove: Remove ActionBlocker from SharedBuckleComponent
- remove: Remove HandleMessage method from ClimbingComponent

2021-07-18 10:24 UTC, Jackrost commented
Link it with issue #4265, please

2021-07-20 13:10 UTC, metalgearsloth requested changes

2021-07-20 13:10 UTC, metalgearsloth commented on Content.Shared/Buckle/SharedBuckleSystem.cs
> +        }
Would be better to probably have a separate "Buckled" component and then use the directed event for it, that way this stuff isn't being called for every single movement / rotation.

Downside is that RemoveComponent is currently bugged via networking so would need to check if it has a client version that runs too.

2021-07-20 13:10 UTC, metalgearsloth commented on Content.Shared/Climbing/SharedClimbingSystem.cs
> +        }
Same as above. Also climbing checking IsTransitioning will be removed someday so not much point having this tbh.

2021-07-21 13:28 UTC, metalgearsloth commented on Content.Shared/Climbing/SharedClimbingSystem.cs
> +        }
Actually just slap a TODO on this and we'll deal with it later.

2021-07-21 19:15 UTC, Jackrost commented on Content.Client/Buckle/BuckleComponent.cs
> +        public override bool TryBuckle(IEntity? user, IEntity to, bool check_range, float? range)
Like I have discussed about this earlier in discord, it was for optimisation. In Kitchen Spike I use range check (InRangeUnobstructed method) after success result of "do_after" to be sure. After that TryBuckle proccess happend and doing the same thing again. Also default buckle range is very small. For chair it's ok, but Kitchen Spike is solid and placed in corner, so you need pulling body  very close, and moving something with mouse click just too long procces for this.

2021-07-27 14:00 UTC, metalgearsloth commented on Content.Client/Buckle/BuckleComponent.cs
> +        public override bool TryBuckle(IEntity? user, IEntity to, bool check_range, float? range)
You're better off always doing the check in buckle and not kitchenspike then, no?

2021-07-27 14:01 UTC, metalgearsloth commented
Changelog should also be player-friendly. In this case I don't think they'd know what a refactor is so I'd probably delete it.

2021-08-18 11:06 UTC, metalgearsloth commented
You coming back to this Jack?

2021-08-18 12:48 UTC, Jackrost commented
> You coming back to this Jack?
Yeah,, but I still busy, so I complete it later

2021-10-03 04:52 UTC, metalgearsloth commented
Been over 6 weeks so if you get time just get it re-opened.

2021-10-03 04:52 UTC, closed without merging