grindable/juiceable stacks
space-wizards/space-station-14 pull request #4391
Opened 2021-07-29 15:29 UTC by plinyvic

reagent grinder now takes stacks into account
added ScaleSolution that allows scaling of solution contents

## About the PR 

**Screenshots**

**Changelog**

:cl: plinyvic

2021-07-29 15:51 UTC, Zumorica requested changes
This needs to be made more [ECS](https://hackmd.io/@ss14/ecs) instead of coupling StackComponent and JuiceableComponent like this

The way to improve this is the following:
1. Create and raise a directed event for scaling the solution of an item being juiced.
2. Subscribe to this event, directed to StackComponent. Multiply the event instance multiplier by stack count.
3. Use multiplier from raised event to scale the solution.

Now, I do think that Juiceable/Grindable need a very big refactor, but that's out of scope.

2021-07-29 15:52 UTC, Zumorica commented
The changelog in the PR's description is broken, either fix it or remove it

2021-07-29 20:32 UTC, plinyvic commented
should be fixed

2021-07-29 23:20 UTC, mirrorcult commented on Content.Server/Kitchen/EntitySystems/ReagentGrinderSystem.cs
> +                            }
you don't need to do the HasComponent check; the effect args just won't be modified if there isn't a stackcomp

also, make sure that you're raising the event directed by passing in false for the third arg
```suggestion
                            RaiseLocalEvent<JuiceableScalingEvent>(item.Uid, juiceEvent, false);
```

2021-07-30 22:20 UTC, Zumorica requested changes

2021-07-30 22:20 UTC, Zumorica commented on Content.Server/Kitchen/EntitySystems/ReagentGrinderSystem.cs
> +            args.Scalar = component.Count; // set scalar to amount of items in stack
```suggestion
            args.Scalar *= component.Count; // multiply scalar by amount of items in stack
```

2021-07-31 12:06 UTC, merged