Owner Transform to Owner
space-wizards/space-station-14 pull request #4460
Opened 2021-08-12 07:25 UTC by ColdAutumnRain

**Changelog**
Issue #4451

- changed: Owner.Transform.Coordinates changed to Owner

PS. Sorry for previous PR, for some reason I had file BUILD_TEST inside commit. I wanted to be sure if there are no other file like this.

2021-08-12 07:34 UTC, Zumorica requested changes

2021-08-12 07:34 UTC, Zumorica commented on Content.Server/Atmos/Components/GasTankComponent.cs
> -                    SoundSystem.Play(Filter.Pvs(Owner), _ruptureSound.GetSound(), Owner.Transform.Coordinates, AudioHelpers.WithVariation(0.125f));
Given the entity is deleted in the next frame, it makes no sense to play this sound on the owner. Revert the change

2021-08-12 07:34 UTC, Zumorica commented on Content.Server/Body/BodyComponent.cs
> -            SoundSystem.Play(Filter.Pvs(Owner), _gibSound.GetSound(), Owner.Transform.Coordinates, AudioHelpers.WithVariation(0.025f));
Given this entity is deleted in the next frame, it makes no sense to play this sound on the owner. Revert the change

2021-08-12 07:34 UTC, Zumorica commented on Content.Server/Movement/Components/FootstepModifierComponent.cs
> -            SoundSystem.Play(Filter.Pvs(Owner), SoundCollection.GetSound(), Owner.Transform.Coordinates, AudioParams.Default.WithVolume(-2f));
Honestly, I don't think it makes sense at all that footstep sounds follow an entity. Revert the change

2021-08-12 07:34 UTC, Zumorica commented on Content.Server/Nutrition/Components/SliceableFoodComponent.cs
> -            SoundSystem.Play(Filter.Pvs(Owner), _sound.GetSound(), Owner.Transform.Coordinates,
Play this sound on `eventArgs.User` instead as this entity might be deleted after this.

2021-08-12 07:38 UTC, metalgearsloth commented on Content.Server/Singularity/Components/ServerSingularityComponent.cs
> +            SoundSystem.Play(Filter.Pvs(Owner), _singularityCollapsingSound.GetSound(), Owner);
In this case the singulo is probably being deleted so probably not suitable to use the entity.

2021-08-12 08:34 UTC, Zumorica commented
Two things, just so you know... We don't put technical changes like this in the changelog, users don't care. And your changelog is formatted incorrectly, it needs to follow this format:
```
:cl:
- add: Added fun!
- remove: Removed fun!
- fix:
```

2021-08-18 21:29 UTC, ShadowCommander approved these changes

2021-08-18 21:36 UTC, PaulRitter approved these changes

2021-08-18 21:36 UTC, merged