Adds the ability to assign equip sounds in ClothingComponent
space-wizards/space-station-14 pull request #4485
Opened 2021-08-18 05:54 UTC by SweptWasTaken

## About the PR 

Tin.

2021-08-19 02:06 UTC, SweptWasTaken commented
Fuck ClothingComponent i'm abandoning this.

2021-08-20 01:37 UTC, mirrorcult requested changes

2021-08-20 01:37 UTC, mirrorcult commented on Content.Server/Clothing/Components/ClothingComponent.cs
> +            if (EquipSound != null)
equipsound isnt marked as nullable (should be `SoundSpecifier?`) so either do that or remove this check and add `required: true`

2021-08-20 04:05 UTC, SweptWasTaken commented
Done.

2021-08-20 04:22 UTC, merged