Cigarette ecs
space-wizards/space-station-14 pull request #4495
Opened 2021-08-19 22:10 UTC by Ygg01

Removes old Component-based `StorageCounter` replaces it with Systems. 

Also renames old `ItemCounterComponent` into `ItemMapperComponent` to distinguish between these two.
When making the Belt tool visualizer I intended to unify them, but on @mirrorcult suggestion, I'll keep them separated.

Not interesting for players, so no changelog.

2021-08-20 05:47 UTC, mirrorcult requested changes

2021-08-20 05:47 UTC, mirrorcult commented on Content.Server/Storage/EntitySystems/ItemCounterSystem.cs
> +        protected override bool TryGetCount(ContainerModifiedMessage msg, ItemCounterComponent itemCounter,
why bother with an out param, i would just return 0 if theres no server storage or no items

2021-08-20 05:47 UTC, mirrorcult commented
if you want to unity itemmapper/itemcounter and you think that would lead to cleaner code, go for it, my opinion on that isn't final

2021-08-23 06:03 UTC, mirrorcult commented
some yaml still has some removed components

2021-08-23 09:49 UTC, Ygg01 commented
> some yaml still has some removed components

I ran the YAML Linter and it showed no errors, if that's what you mean.

2021-08-23 11:33 UTC, PaulRitter commented
> > some yaml still has some removed components
> 
> I ran the YAML Linter and it showed no errors, if that's what you mean.

Linter says no
![image](https://user-images.githubusercontent.com/16618384/130440532-8527e948-f1f8-43c1-8fd6-da3be108102a.png)

2021-08-23 13:28 UTC, Ygg01 commented
> Linter says no
> ![image](https://user-images.githubusercontent.com/16618384/130440532-8527e948-f1f8-43c1-8fd6-da3be108102a.png)

Are you just parroting the Linter or did you actually check it?

2021-08-23 13:34 UTC, metalgearsloth requested changes
> 
> 
> > Linter says no
> > ![image](https://user-images.githubusercontent.com/16618384/130440532-8527e948-f1f8-43c1-8fd6-da3be108102a.png)
> 
> Are you just parroting the Linter or did you actually check it?
> 
> EDIT: Those lines don't exist on my branch

You need to merge in master my man.

2021-08-23 13:38 UTC, Ygg01 commented
> You need to merge in master my man.

This is a helpful comment. Saying fix isn't as much.

2021-09-03 05:24 UTC, mirrorcult approved these changes

2021-09-04 17:42 UTC, merged