Fix bounds ordering
space-wizards/space-station-14 pull request #4514
Opened 2021-08-23 06:41 UTC by metalgearsloth

Requires https://github.com/space-wizards/RobustToolbox/pull/1966
https://github.com/space-wizards/RobustToolbox/pull/1958 fails tests if there's any invalid bounds.

2021-08-23 10:42 UTC, metalgearsloth commented
I have no idea how clickable is failing now

2021-08-24 08:31 UTC, merged

2021-08-24 08:33 UTC, PaulRitter requested changes
why did i decide to review this
![image](https://user-images.githubusercontent.com/16618384/130584578-75b874d9-131b-4248-a593-9d1c33fcd60f.png)

2021-08-24 08:33 UTC, PaulRitter commented on Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
> +          bounds: "-0.49,-0.49,0.49,0.49" # don't want this colliding with walls or they won't close
```suggestion
          bounds: "-0.49,-0.2,0.49,-0.49" # don't want this colliding with walls or they won't close
```

2021-08-24 08:33 UTC, PaulRitter commented on Resources/Prototypes/Entities/Structures/Doors/Windoors/assembly.yml
> +        bounds: "-0.49,-0.49,0.49,-0.2"
wait what, shouldnt it be:
```suggestion
        bounds: "-0.49,-0.2,0.49,-0.49"
```

2021-08-24 08:33 UTC, PaulRitter commented on Resources/Prototypes/Entities/Structures/Doors/Windoors/base.yml
> +        bounds: "-0.49,-0.49,0.49,-0.2"
same question as above
```suggestion
        bounds: "-0.49,-0.2,0.49,-0.49"
```

2021-08-24 08:34 UTC, PaulRitter commented
ooop, merge during review. powerful