Fix throwable solution
space-wizards/space-station-14 pull request #4590
Opened 2021-09-11 11:03 UTC by Ygg01

## About the PR 
This PR addresses issues introduced by changes done in solution refactor

Closes #4583 

**Screenshots**
![Broken beer botles](https://user-images.githubusercontent.com/1146204/132945486-e19183b4-aaa2-4467-9763-889b7431a2fd.png)

**Changelog**
Like so: :cl: Ygg01

Spill behavior was changed so on break all solutions in SolutionContainer will be spillt.

:cl:
- fix: bottles filled with drinks now spill as expected

2021-09-12 06:15 UTC, metalgearsloth requested changes
I fixed the changelog as it was a bit mangled.

2021-09-12 06:15 UTC, metalgearsloth commented on Content.Server/Destructible/Thresholds/Behaviors/SpillBehavior.cs
>                  return;
Would this EntitySystem ever fail?

2021-09-14 10:48 UTC, Ygg01 commented on Content.Server/Destructible/Thresholds/Behaviors/SpillBehavior.cs
>                  return;
Defensive coding, I've removed it.

2021-09-15 10:46 UTC, metalgearsloth approved these changes

2021-09-15 10:46 UTC, merged