Basic AHelp Panel, Ported & Fixed
space-wizards/space-station-14 pull request #4776
Opened 2021-10-05 23:06 UTC by 20kdc

## About the PR

Continuation of https://github.com/space-wizards/space-station-14/pull/3049

*But this time it works!*

Full explaination:

Each player has an AHelp channel, which they can always receive messages on, and they can always send messages on.
All admins receive and can send messages on all ahelp channels.

When an ahelp message is received, if a window does not exist or is hidden for that channel, it is created/shown.

To be absolutely clear, this PR is not intended to be some sort of full ticketing system. Frankly I suspect such a thing would be such a big PR that it would be a nightmare to keep it up to date with the way things change around here.

It is meant to be an admin/player semi-private chat system, since that's simple to implement and is what is needed (see: OOC being misused for this)

**Screenshots**
![image](https://user-images.githubusercontent.com/22304167/136112929-27f3a11d-4f63-4d9f-aba1-ffd3fe5dea65.png)

**Changelog**

:cl:
- add: 'AHelp' next to the options menu.

2021-10-05 23:11 UTC, 20kdc commented
there's already a players tab, and if that allowed selection it seems like these should really go there, but, well, it doesn't, they don't
Player Actions Panel, maybe?

2021-10-05 23:13 UTC, mirrorcult commented
yeah that seems fine

2021-10-05 23:13 UTC, ike709 commented
> To be absolutely clear, this PR is not intended to be some sort of full ticketing system. Frankly I suspect such a thing would be such a big PR that it would be a nightmare to keep it up to date with the way things change around here.

Here you go: https://github.com/space-wizards/space-station-14/pull/3881

2021-10-05 23:14 UTC, mirrorcult commented
this PR probably needs a lot of discussion from maintainers considering anim tooling is a focus + we still want to potentially reuse ike/PJB's ticketing PR and we'd have to integrate that with this

2021-10-05 23:14 UTC, mirrorcult commented
speak of the devil

2021-10-05 23:17 UTC, SweptWasTaken commented
Seems p ok for now

2021-10-05 23:17 UTC, SweptWasTaken approved these changes

2021-10-06 01:02 UTC, mirrorcult commented
personally im fine w/ this being merged especially since we've been getting players recently and moony requested it

2021-10-06 02:20 UTC, moonheart08 commented
yea honestly even in a barebones state we need ahelp asap

2021-10-06 02:24 UTC, ShadowCommander commented
If the code is fine, then it'd be good to have something, even if we have to replace it later. I'll review this PR later in the week unless someone else gets to it first.

2021-10-06 11:16 UTC, Zumorica requested changes
This isn't getting merged until it has the classic `bwoink` sound.

2021-10-06 11:26 UTC, Zumorica commented on Content.Client/Administration/BwoinkSystem.cs
> +        protected override void OnBwoinkTextMessage(BwoinkTextMessage message, EntitySessionEventArgs eventArgs)
I looked into this, this is a problem with many windows in the codebase right now...

2021-10-06 11:33 UTC, Zumorica commented on Content.Client/Administration/BwoinkSystem.cs
> +        protected override void OnBwoinkTextMessage(BwoinkTextMessage message, EntitySessionEventArgs eventArgs)
On closer inspection, it seems the GC correctly handles cleaning closed windows up, so it should be fine.

2021-10-06 15:25 UTC, merged