Adds gamer flare to the game.
space-wizards/space-station-14 pull request #4998
Opened 2021-10-24 00:19 UTC by moonheart08

Introduces the RgbLightController component, an adjustable-rate oscillator that cycles through various hues.

**Screenshots**
![Screenshot from 2021-10-23 19-13-46](https://user-images.githubusercontent.com/7806367/138575180-b36bb599-7dab-4b29-bcbb-37aa540146ef.png)

2021-10-30 04:02 UTC, metalgearsloth requested changes

2021-10-30 04:02 UTC, metalgearsloth commented on Content.Shared/Light/Component/SharedRgbLightControllerComponent.cs
> +    public class SharedRgbLightControllerComponent : Robust.Shared.GameObjects.Component
yuck.

Also don't need share prefix if it's not being inherited.

2021-10-30 04:02 UTC, metalgearsloth commented on Content.Shared/Light/SharedRgbLightControllerSystem.cs
> +        }
Still server-states going out?

2021-11-30 08:41 UTC, metalgearsloth approved these changes

2021-11-30 08:41 UTC, metalgearsloth commented on Content.Client/Light/RgbLightControllerSystem.cs
> +                (float) (((gameTiming.CurTime.TotalSeconds - offset.TotalSeconds) / rgb.CycleRate + Math.Abs(rgb.Owner.Uid.GetHashCode() * 0.1)) % 1),
Should pass in currenttime as CurTime is a property that needs to be re-calculated every time (and it does show up in the profiler from time to time).

2021-11-30 13:43 UTC, PaulRitter approved these changes

2021-11-30 13:44 UTC, PaulRitter requested changes
change what sloth noted & this should be good to merge

2021-11-30 14:54 UTC, merged