New Guns (hopefully no conflicts this time)
space-wizards/space-station-14 pull request #5105
Opened 2021-10-30 16:17 UTC by TaralGit

![new_guns](https://user-images.githubusercontent.com/76408146/139540961-4aa7ca8c-5daa-4b4e-9ad5-08bccb59e8fe.png)
*makeshift gun, STAR laser pistol, COG laser carbine, new c20r sprite and new Predator revolver (all thanks to cev-eris)

🆑

add: makeshift laser gun
add: STAR laser pistol
add: COG laser carbine
add: Predator revolver and bundle
add: firecost for most battery guns
fix: Inspector has been replaced with the Predator in the uplink
fix: Inspector had it's ammo capacity reduced from 7 to 6
fix: replaced old c20r cev eris sprite with a newer one from the same source
remove: laser gun

2021-10-30 17:03 UTC, TaralGit commented
I'm not touching the old laser gun. That thing is cursed.

2021-11-02 05:57 UTC, metalgearsloth commented
Changelog sentence should be readable on its own, the "add" is for the icon.

2021-11-04 19:44 UTC, TaralGit commented
> Changelog sentence should be readable on its own, the "add" is for the icon.

Should I delete the changelog?

2021-11-06 19:12 UTC, SweptWasTaken commented
Are you pulling these sprites from CEV-Eris master?

For the star pistol you've put the source as "obrez_retro.rsi" which looks like this...

![image](https://user-images.githubusercontent.com/49448379/140620921-18ef6c98-7140-4465-b28f-7c0ebf4382ed.png)

For the cog.rsi you've put the source as "energy.rsi" which looks like this...

![image](https://user-images.githubusercontent.com/49448379/140620988-d3d73d78-f6ca-4c41-aa1f-96007291aa76.png)

Where are you pulling the pistol sprite from? It looks really awful. If you're looking for a good looking energy pistol sprite you should use the [PDW from Cev-Eris](https://github.com/discordia-space/CEV-Eris/blob/master/icons/obj/guns/energy/pdw.dmi).

![image](https://user-images.githubusercontent.com/49448379/140621145-af5c99ba-f988-4166-8f75-bb97292bf038.png)

2021-11-06 19:16 UTC, SweptWasTaken commented
> 
> 
> > Changelog sentence should be readable on its own, the "add" is for the icon.
> 
> Should I delete the changelog?

Just shrink it down maybe, doesn't have to be so verbose. Say like "Added more energy weapons". Shrinking the Inspector's ammo should be a tweak.

2021-11-06 20:55 UTC, TaralGit commented
> Are you pulling these sprites from CEV-Eris master?
> 
> For the star pistol you've put the source as "obrez_retro.rsi" which looks like this...
> 
> ![image](https://user-images.githubusercontent.com/49448379/140620921-18ef6c98-7140-4465-b28f-7c0ebf4382ed.png)
> 
> For the cog.rsi you've put the source as "energy.rsi" which looks like this...
> 
> ![image](https://user-images.githubusercontent.com/49448379/140620988-d3d73d78-f6ca-4c41-aa1f-96007291aa76.png)
> 
> Where are you pulling the pistol sprite from? It looks really awful. If you're looking for a good looking energy pistol sprite you should use the [PDW from Cev-Eris](https://github.com/discordia-space/CEV-Eris/blob/master/icons/obj/guns/energy/pdw.dmi).
> 
> ![image](https://user-images.githubusercontent.com/49448379/140621145-af5c99ba-f988-4166-8f75-bb97292bf038.png)

Think I'm just going to get rid of the laser pistol, since it's kinda pointless. It's a modified Obrez but I got the wrong link for the meta.json.
Yeah. At first I thought that I should get the PDW in but the problem is that this gun is supposed to also have a Stun setting and I don't know how to code that in.

2021-11-07 01:08 UTC, SweptWasTaken commented
> 
> 
> > Are you pulling these sprites from CEV-Eris master?
> > For the star pistol you've put the source as "obrez_retro.rsi" which looks like this...
> > ![image](https://user-images.githubusercontent.com/49448379/140620921-18ef6c98-7140-4465-b28f-7c0ebf4382ed.png)
> > For the cog.rsi you've put the source as "energy.rsi" which looks like this...
> > ![image](https://user-images.githubusercontent.com/49448379/140620988-d3d73d78-f6ca-4c41-aa1f-96007291aa76.png)
> > Where are you pulling the pistol sprite from? It looks really awful. If you're looking for a good looking energy pistol sprite you should use the [PDW from Cev-Eris](https://github.com/discordia-space/CEV-Eris/blob/master/icons/obj/guns/energy/pdw.dmi?rgh-link-date=2021-11-06T20%3A55%3A29Z).
> > ![image](https://user-images.githubusercontent.com/49448379/140621145-af5c99ba-f988-4166-8f75-bb97292bf038.png)
> 
> Think I'm just going to get rid of that laser pistol and replace it with another one I just saw. It's a modified Obrez, as for the COG I got the wrong link for the meta.json but that was fixed.
> 
> At first I thought that I should get the PDW in but the problem is that this gun is supposed to also have a Stun setting and I don't know how to code that in.

I mean it should be very easy looking at the existing weapons. If you can't code it in then don't add it?

2021-11-07 01:20 UTC, PaulRitter commented
> I mean it should be very easy looking at the existing weapons. If you can't code it in then don't add it?

I'd like you to stop being mean to people and start being constructive.

For Taral: If you are unsure how to code something, feel free to reach out to us on [discord](https://discord.gg/ss14), namely the #howdoicode channel.

2021-11-07 21:54 UTC, TaralGit commented
Well, I'm done with this PR.

2021-11-23 23:36 UTC, mirrorcult requested changes

2021-11-23 23:36 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  name: Makeshift Laser Gun
lowercase the name

2021-11-23 23:36 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  name: Svalinn Laser Pistol
lowercase name

2021-11-23 23:36 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  name: COG Laser Carbine
lowercase--ok you get the idea

2021-11-25 22:37 UTC, merged