Adds a UI for gas mixers
space-wizards/space-station-14 pull request #5165
Opened 2021-11-05 00:36 UTC by ike709

## About the PR 
See #4203

Adds a UI for mixers.

**Screenshots**

![image](https://user-images.githubusercontent.com/5714543/140439089-045a0f73-2a9e-4d04-9d7e-d4cce3ab1ec9.png)

**Changelog**

:cl:
- add: Gas mixers now have a UI

2021-11-05 08:32 UTC, PaulRitter requested changes
lgtm, just two things:
- do not open the window if the mixer isnt anchored
- I'd rather have "{Dir} Node" than the numbers, seems more clear

2021-11-05 15:24 UTC, ike709 commented
CBA to do node directions but I did improve it. It's more immediately clear than using dirs anyways.

2021-11-08 13:32 UTC, Efruit commented on Resources/Locale/en-US/components/gas-mixer-component.ftl
> +comp-gas-mixer-ui-mixer-node-side = Side Node:
While technically correct, I don't think "Node" is the best thing to call them.

```suggestion
comp-gas-mixer-ui-mixer-node-primary = Primary Port:
comp-gas-mixer-ui-mixer-node-side = Side Port:
```

2021-11-08 19:26 UTC, PaulRitter requested changes
please update your variables in code too to be consistent with "Primary/Side Node"

fix the nitpicks and i merge

2021-11-11 20:17 UTC, ike709 commented on Resources/Locale/en-US/components/gas-pump-component.ftl
> +comp-gas-pump-ui-needs-anchor = Anchor the pump first!
```suggestion
comp-gas-pump-ui-needs-anchor = Anchor it first!
```

2021-11-11 20:18 UTC, ike709 commented on Resources/Locale/en-US/components/gas-mixer-component.ftl
> +comp-gas-mixer-ui-needs-anchor = Anchor the mixer first!
```suggestion
comp-gas-mixer-ui-needs-anchor = Anchor it first!
```

2021-11-11 20:18 UTC, ike709 commented on Resources/Locale/en-US/components/gas-filter-component.ftl
> +comp-gas-filter-ui-needs-anchor = Anchor the filter first!
```suggestion
comp-gas-filter-ui-needs-anchor = Anchor it first!
```

2021-11-11 20:19 UTC, ike709 commented
The variable names are consistent with the actual nodes in the code being node one & two. Primary/side is just to make it clearer for players.

2021-11-11 20:23 UTC, ike709 commented
Linter failure is unrelated to the PR.

2021-11-11 22:10 UTC, merged