Soft player cap that lets in only admins.
space-wizards/space-station-14 pull request #5227
Opened 2021-11-08 22:51 UTC by moonheart08

## About the PR
The PR is too powerful! Only admins can merge.

**Screenshots**
![Screenshot from 2021-11-08 16-46-46](https://user-images.githubusercontent.com/7806367/140830819-c15a15d3-3f75-4d52-8006-77b80992f9c2.png)

2021-11-08 22:52 UTC, moonheart08 commented
Note the maximum is set to 30 by default. @PJB3005 will need to set it in our server configs appropriately, though I think the default is good.

2021-11-08 23:02 UTC, moonheart08 commented
(Also note afaik the exception doesn't happen now, the screenshot predates me adding a `return` i forgot.)

2021-11-08 23:06 UTC, PaulRitter requested changes
didn't you say you were gonna take a break? :eyEs:

2021-11-08 23:06 UTC, PaulRitter commented on Content.Server/Connection/ConnectionManager.cs
> +                e.Deny("The server is too full! Only admins can join.");
no need to flex smh
```suggestion
                e.Deny("The server is too full!");
```

2021-11-08 23:06 UTC, moonheart08 commented
> didn't you say you were gonna take a break? :eyEs:

this is what happens when I find 30 minutes of freetime

2021-11-08 23:08 UTC, PaulRitter commented
> 
> 
> > didn't you say you were gonna take a break? :eyEs:
> 
> this is what happens when I find 30 minutes of freetime

dont make me repoban you

2021-11-08 23:09 UTC, PaulRitter approved these changes

2021-11-08 23:11 UTC, ike709 commented
If you want to be based you can also let donors bypass the cap.

2021-11-08 23:11 UTC, moonheart08 commented
> If you want to be based you can also let donors bypass the cap.

I mentioned this, I could do it but didn't feel like it.

2021-11-09 09:38 UTC, PaulRitter commented
> 
> 
> If you want to be based you can also let donors bypass the cap.

no

2021-11-09 09:39 UTC, PaulRitter commented on Content.Server/Connection/ConnectionManager.cs
> +                e.Deny("The server is too full!");
```suggestion
                e.Deny("The server is full!");
```

2021-11-09 09:44 UTC, merged