latex gloves allow medical consumables to be more effective
space-wizards/space-station-14 pull request #5275
Opened 2021-11-11 23:19 UTC by xRiriq

## Latex gloves allow medical consumables to be more effective 

Right now latex gloves are kind of a dud item aside from RP purposes. Instead it makes sense to me that if you are using the latex gloves in a medical context your medical outcome should be more effective. This doesn't touch any of the other kinds of gloves in this PR but it makes sense that someone wearing some other kinds of gloves instead of even bare hands should be less effective. In theory this also could be used eventually to make the gloves 'dirty' and less effective so there would be need to dispose of them and get fresh ones from cargo over the course of a round.

This mirrors the currently existing `HeatResistanceComponent` in adding itself as a potential data field of a `ClothingComponent`, and the actual value comes into play during the `HealingComponent`'s application of effects. After all of the existing checks we look at the source entity, check to see if it has gloves on its hands and then applies the scaling value accordingly.

Right now the `HealingComponent` is only used by brutepacks, ointments, and gauze so there should be no side effects beyond that.

**Screenshots**

![starting](https://user-images.githubusercontent.com/94037592/141381740-cd51dc9b-fcf0-477a-a948-77f8c223c790.png)
![healing without gloves](https://user-images.githubusercontent.com/94037592/141381749-840a9d1c-b580-48b1-b20e-5f1235c93551.png)
![healing with gloves](https://user-images.githubusercontent.com/94037592/141381751-54dace59-631c-4000-ab23-3de290eff2a2.png)

**Changelog**

:cl:
- add: latex gloves now double the effectiveness of brutepacks and ointments

2021-11-11 23:23 UTC, xRiriq commented
Fixing some autoformatter woes. I thought it was more standardized.

2021-11-11 23:26 UTC, xRiriq commented
Unnecessary formatting changes have been removed, should be ready for review.

2021-11-11 23:26 UTC, mirrorcult requested changes

2021-11-11 23:26 UTC, mirrorcult commented on Content.Server/Medical/Components/SterileComponent.cs
> +
no whitespace between attributes and class

2021-11-11 23:26 UTC, mirrorcult commented on Content.Server/Clothing/Components/ClothingComponent.cs
> +        [DataField("Sterile")]
datafields should be `camelCase`, the rest of the component doesn't really follow this but uhhhhh

2021-11-11 23:26 UTC, mirrorcult commented on Content.Server/Clothing/Components/ClothingComponent.cs
> +        [DataField("Sterile")]
also this should really be its own component, not just slapped onto clothing?

2021-11-11 23:26 UTC, mirrorcult commented on Content.Server/Medical/Components/HealingComponent.cs
> +            if (eventArgs.User.GetComponent<InventoryComponent>().TryGetSlotItem(EquipmentSlotDefines.Slots.GLOVES, out ClothingComponent? gloves))
don't assume the user has an inventory

2021-11-11 23:26 UTC, mirrorcult commented on Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
> +    Sterile: 2 # mutliplier for healing consumables like BrutePacks
multiplier

2021-11-11 23:26 UTC, mirrorcult commented on Content.Server/Clothing/Components/ClothingComponent.cs
> +        [DataField("Sterile")]
you already made another component for this so just put it in there

2021-11-11 23:26 UTC, mirrorcult commented
this will definitely require some discussion for balance/design reasons

2021-11-11 23:30 UTC, xRiriq commented
Thanks for the feedback. I followed what the heat resistance property for clothing was mostly but I agree that it probably wasn't the right way.

2021-11-11 23:31 UTC, metalgearsloth commented
I'm not a huge fan; if it were for like a surgery I'd be okay with it but not for basic med applications.

It looks like on tg it can confer faster med application and on vg it confers surgery benefits.

2021-11-11 23:33 UTC, mirrorcult commented
i'd support making the application faster (is it even a doafter in ss14? it should be, anyway) but not healing more

2021-11-11 23:37 UTC, metalgearsloth commented
Maybe like; 2s if latex gloves on, 5s if not, and then longer if it's a self-application?

2021-11-11 23:37 UTC, xRiriq commented
> 
> 
> I'm not a huge fan; if it were for like a surgery I'd be okay with it but not for basic med applications.
> 
> It looks like on tg it can confer faster med application and on vg it confers surgery benefits which don't seem bad.

Yes, I was considering making brute packs and stuff take a second as a separate idea and with gloves it could go faster as a separate idea. Right now in most shifts I'm just running out because they only heal 5 and I often need to heal 40+ to get back to 'full' with a bicaridine jab/dosing.

Also for me it was the interaction part too, where sure you can have the supplies wherever but taking the time to have the extra tool will make it more effective.

2021-11-12 00:00 UTC, metalgearsloth commented
I'm not a fan of "X item makes Y more do more" in general because then you get people swapping out gloves before healing or dropping items for a medic instead of just applying right away (barotrauma has this gameplay and it kinda sucks).

Once we have more chems it should be easier to heal people up and I think mirror is doing a pass on them. Ointment + bruise is really only for minor stuff anyway.

2021-11-12 00:04 UTC, xRiriq commented
Fair enough. I'm fine closing this PR and working on other things (like maybe making packs be a time thing).

2021-11-12 00:04 UTC, closed without merging

2021-11-12 00:16 UTC, metalgearsloth commented
Some other food for thought: We don't have the trauma packs around the station plus medical probably needs more mapped in (via smart fridge or otherwise) which contributes to the scarcity.