Carp crit\dead
space-wizards/space-station-14 pull request #5503
Opened 2021-11-24 13:19 UTC by FoLoKe

## About the PR 

Fixes #5485 
If this okay I'm gonna adjust sprites for all other animals without crit or dead textures
(Yes - Holocarp has crit\dead sprite and texture)

**Screenshots**

![image](https://user-images.githubusercontent.com/36813380/143244115-30e496df-4a84-4430-9623-47ac9649236f.png)

**Changelog**

:cl:
- add: Added space carps dead sprite

2021-11-24 15:02 UTC, cheesePizza2 commented
why not flip dead one upside down? like how dead fish float belly up

2021-11-24 16:09 UTC, FoLoKe commented
> why not flip dead one upside down? like how dead fish float belly up

They already flipped, there just was no "dead\crit" differences 
![image](https://user-images.githubusercontent.com/36813380/143273393-72ed9ad0-2c56-41ad-8cf1-058d0d41139b.png)
(first two are original for alive and dead)

2021-11-25 02:12 UTC, metalgearsloth requested changes

2021-11-25 02:12 UTC, metalgearsloth commented on Resources/Textures/Mobs/Aliens/Carps/space.rsi/meta.json
> +      ]
Don't need delay

2021-11-25 02:12 UTC, metalgearsloth commented on Resources/Textures/Mobs/Aliens/Carps/magic.rsi/meta.json
> +      ]
Don't need delay

2021-11-30 10:12 UTC, merged