owo
space-wizards/space-station-14 pull request #5510
Opened 2021-11-25 07:23 UTC by moonheart08

## About the PR 

**Screenshots**
![Screenshot from 2021-11-25 01-20-09](https://user-images.githubusercontent.com/7806367/143397361-56298db4-3802-4b2d-9c87-eeb65b97d088.png)

2021-11-25 09:32 UTC, ShadowCommander approved these changes

2021-11-25 10:22 UTC, Zumorica reviewed
I'm not a fan of static methods

2021-11-25 14:09 UTC, PaulRitter commented
> I'm not a fan of static methods

gotta be a bit more constructive like that, seems kinda the best way in this case afaict. how'd you propose to change it?

2021-11-25 14:10 UTC, Zumorica commented
> > I'm not a fan of static methods
> 
> gotta be a bit more constructive like that, seems kinda the best way in this case afaict. how'd you propose to change it?

Literally just `EntitySystem.Get<OwOAccentSystem>().Accentuate(yourTextHere)`, no need for static

2021-11-25 14:11 UTC, PJB3005 reviewed
Pro-static gang

2021-11-25 14:16 UTC, PaulRitter commented
> > > I'm not a fan of static methods
> > 
> > 
> > gotta be a bit more constructive like that, seems kinda the best way in this case afaict. how'd you propose to change it?
> 
> Literally just `EntitySystem.Get<OwOAccentSystem>().Accentuate(yourTextHere)`, no need for static

![image](https://user-images.githubusercontent.com/16618384/143456883-c0b0a275-77c7-4bec-ae76-a8b235d97d9f.png)

yeah no sorry im with the pro-static gang on this one.

if there might be a future possiblity for which you'd want this in a system, say because you may want to introduce some way to globally change behaviour over cvars or smth i'd understand it, but this is literally just a very simple text formatting algo, i dont see this being changed ever.

2021-11-25 14:16 UTC, metalgearsloth commented
If you're gonna static at least get rid of the field with the dependency.

2021-11-25 14:17 UTC, PaulRitter commented
> If you're gonna static at least get rid of the field with the dependency.

that field still gets used tho

2021-11-25 14:18 UTC, metalgearsloth commented
If it weren't a static it would also get used in both methods

2021-11-25 14:19 UTC, PaulRitter commented on Content.Server/Speech/EntitySystems/OwOAccentSystem.cs
> +            args.Message = Accentuate(args.Message, _random);
@metalgearsloth it still does. what?

2021-11-25 14:20 UTC, PaulRitter commented
for the component, there is literally 0 change in how much it uses the dependency

2021-11-25 14:21 UTC, metalgearsloth commented on Content.Server/Speech/EntitySystems/OwOAccentSystem.cs
> +            args.Message = Accentuate(args.Message, _random);
It gets used 50% less.

2021-11-25 14:30 UTC, PaulRitter requested changes
im wrong do what the funny woman said

EntitySystem.Get<OwOAccentSystem>().Accentuate(yourTextHere)

2021-11-25 15:10 UTC, PaulRitter commented
reposting @Clyybber's meme for preservation
![image](https://user-images.githubusercontent.com/16618384/143465421-bc5552fa-a1e5-45bc-a5c8-ba808317cc7b.png)

2021-11-27 01:31 UTC, ShadowCommander approved these changes

2021-11-27 05:59 UTC, mirrorcult approved these changes

2021-11-27 06:43 UTC, merged