Implement moving pointing arrow.
space-wizards/space-station-14 pull request #5595
Opened 2021-11-28 12:20 UTC by pointer-to-null

## About the PR 

The pointing arrow now fly from the pointer (player) to the pointed location. This makes intentions more clear.

The speed at which the arrow moves depends on the distance. The further it goes, the faster.

The flying part can be completely disabled if `_isFlying` variable is set to false before `PointingArrowComponent` startup.

**Screenshots**

https://user-images.githubusercontent.com/91910481/143766401-b6040c17-a50d-47bf-92d3-b7da1eccbc28.mp4

**Changelog**

:cl:
- add: Now the pointing arrow actualy moves from the player to the pointed location.

2021-11-28 12:22 UTC, metalgearsloth commented
I've seen unitystation's version of this and I wasn't a fan, IMO.

2021-11-28 12:56 UTC, pointer-to-null commented
This helps determine who is pointing where, alot. Especially when there are several people hanging around.

2021-11-28 17:57 UTC, moonheart08 commented
@metalgearsloth this seems like a good thing to make an option in the options menu

2021-11-28 18:03 UTC, PaulRitter commented
a clientside-option for this should suffice, yeah

2021-11-28 19:56 UTC, mirrorcult commented
personally i'm fine with this

2021-11-28 20:00 UTC, mirrorcult requested changes

2021-11-28 20:00 UTC, mirrorcult commented on Content.Server/Pointing/EntitySystems/PointingSystem.cs
> +        private MapCoordinates playerCoordinates;
this being on the serverside system means you can't have more than one person pointing at the same time

2021-11-28 20:07 UTC, Zumorica commented
My only issue with this is that pointing arrows are entirely server-side right now, wasting a lot of bandwidth for no good reason...
But refactoring them to be client-side only is honestly out of scope for this PR. I like that animation, personally

2021-11-28 20:08 UTC, DogZeroX commented
Could probably have a limit of how many arrows you can "shoot"

2021-11-29 00:35 UTC, metalgearsloth commented
> a clientside-option for this should suffice, yeah

Should be server-side and replicated because people with it off are at an inherent disadvantage.

2021-11-29 00:39 UTC, metalgearsloth requested changes

2021-11-29 00:39 UTC, metalgearsloth commented on Content.Server/Pointing/EntitySystems/PointingSystem.cs
> +                EntityManager.GetEntity(uid).Transform.WorldPosition = playerCoordinates.Position;
Don't use GetEntity, just use GetComponent

2021-11-29 00:39 UTC, metalgearsloth commented on Content.Server/Pointing/EntitySystems/PointingSystem.cs
> +                    component.Owner.Transform.WorldPosition += directionStep * frameTime * component._flyingSpeed;
Don't use the transform property and as mirror said don't use mapcoordinates.

2021-12-01 08:52 UTC, pointer-to-null commented
All code reviewers comments and serverside option are noted.

> My only issue with this is that pointing arrows are entirely server-side right now, wasting a lot of bandwidth for no good reason... But refactoring them to be client-side only is honestly out of scope for this PR. I like that animation, personally

This is good point actually. So, I think the best decision would be to hold this PR for now. And implement this feature later.

In this regard, I have a question. Should I convert this PR to draft or close it?

2021-12-24 12:29 UTC, closed without merging