More tiles and some cleanup
space-wizards/space-station-14 pull request #5608
Opened 2021-11-29 02:39 UTC by AJCM-git

## About the PR 
-  Add useful tiles for mapping (bar, laundry, mime, clown, chapel, kitchen, snow and grass)
- Added tile item entities for every tile and carpet with their respective sprite and inhands
- Reorganized tiles prototypes and tile item entities prototypes
- Fixed weird joke with the pink carpet
- Fixed case of tiles display names

**Screenshots**
![image](https://user-images.githubusercontent.com/60196617/143800148-66be00b9-ae17-4d8c-8717-0ac45dac8e74.png)

2021-11-29 02:39 UTC, mirrorcult commented
GRASS

2021-11-29 02:41 UTC, DogZeroX commented
GRASS

2021-11-29 02:57 UTC, AJCM-git commented
Marked as a draft by accident, oops (also fixed the linter, hopefully)

2021-11-29 03:04 UTC, moonheart08 commented
GRASS

2021-12-05 03:21 UTC, metalgearsloth requested changes
Can't see licences / copyright on new tiles?

2021-12-07 15:07 UTC, AJCM-git commented
@metalgearsloth new tile items are either handmade or taken from the same source the meta.json already points to. Didn't add copyright to the tiles before because the only one that has it is the steel tile (and they need to use RSIs anyways) so now i only added it to the ones i added/made

2021-12-09 23:41 UTC, metalgearsloth commented on Resources/Textures/Tiles/copyright.txt
> +bar.png, laundry.png, mime.png, clown.png and kitchen.png are under CC-BY-SA-3.0
Which codebase are these from? It's grouped with the tg ones but doesn't have a commit.

2021-12-11 23:08 UTC, mirrorcult approved these changes

2021-12-11 23:08 UTC, merged