Paimusic
space-wizards/space-station-14 pull request #5614
Opened 2021-11-29 23:07 UTC by hubismal

## About the PR 
PAIs can play MIDIs on their own nokia-esque synths accessible through the action menu.
The spacestation14.sf2 soundfont has a new program on bank 1 called "paiSynth" that uses a cell phone beep sample, as there wasn't a consistently chiptuney midi instrument, at least in my default soundfont.
The pAI prototype now has an instrument that isn't accessible through interaction, and is instead opened up by the PAIMidi action that PAIs start out with.
Instruments now can also accept players that are the instrument owner itself.
In the future I'd like to reduce the range on these instruments, but I've been advised by Vera that to do this right now with the midi system would be somewhat complicated.

This is my first PR. Prepare for some facepalming code wise.

**Screenshots**
The only visual embellishment is the icon for the action.
![image](https://user-images.githubusercontent.com/47284081/143955316-724bd5b7-37ae-4b9b-ac59-f2e896385eac.png)

**Changelog**
:cl:
- add: pAIs have been outfitted with cheap ringtone synthesizers to play their own music.

2021-11-29 23:19 UTC, 20kdc commented on BuildChecker/BuildChecker.csproj
> +		<!--
uuuuuuh

2021-11-29 23:20 UTC, 20kdc commented on Resources/Prototypes/Actions/actions.yml
> +    radius: 3
This is an instant action, so it doesn't have these three fields, I think?

2021-11-29 23:21 UTC, 20kdc commented on Resources/Prototypes/Entities/Objects/Fun/vehicle.yml
> +- type: entity
Not sure what this is doing here

2021-11-29 23:24 UTC, 20kdc commented
would like to mention that you left the `paiSynth` sample (unused) in the SS14 soundfont file

2021-11-29 23:27 UTC, hubismal commented
Okay somehow this got mangled with an old, entirely separate branch i haven't touched for months. Let me remove all of this garbage.

2021-11-30 00:04 UTC, mirrorcult requested changes

2021-11-30 00:04 UTC, mirrorcult commented on Content.Server/Actions/Actions/PAIMidi.cs
> +
whitespace is fucked up here

2021-11-30 00:04 UTC, mirrorcult commented on Content.Server/PAI/PAISystem.cs
> +			bui.Close(actor.PlayerSession);
whitespace again

2021-12-01 01:13 UTC, mirrorcult commented on Content.Server/PAI/PAISystem.cs
> +            bui.Close(actor.PlayerSession);
why is there just no indentation here

2021-12-01 01:19 UTC, hubismal commented on Content.Server/PAI/PAISystem.cs
> +            bui.Close(actor.PlayerSession);
editor indentation settings apparently

2021-12-01 18:14 UTC, mirrorcult approved these changes

2021-12-02 18:49 UTC, merged