Partial hand ECS
space-wizards/space-station-14 pull request #5634
Opened 2021-12-01 02:20 UTC by ElectroJr

## About this PR

This PR moves a small amount of hands component logic into the hands systems. The main reason for doing this is in order to get hands predicted. 

There's not much point to getting interactions predicted if hand-swapping, picking up, dropping, and pickup-animations are all initiated server-side. Now they should feel a lot better for laggy clients. To try that aspect out, if you launch the game, and run `cvar net.fakelagmin 0.5` you should find that swap hands using 'X' or by clicking on the hands GUI shouldn't have a delay, and neither should dropping items. Because pick-up interactions are all initiated server side, picking up items will still feel laggy.

This is the first time I've properly messed around with trying to do this sort of thing, and is the second actual use of `RaisePredictiveEvent`, so I didn't have much code to use as a reference. I think I understand how predictions work, but maybe I've don't something silly somewhere. I for one, could do with a 101. I haven't tested out the other net options yet.

## Issues / Comments

For pickup animations, currently the server just tells all clients to play the animation. If you have predicted interactions you can get a situation where the user plays the pickup animation locally, and then plays it again when the server sends it to all clients. If all pickup interactions were predicted & client-initiated, then you could just never send the animation to the user that initiated that interaction. But initially there will eb a mix (e.g., predicted verbs, non-predicted standard interactions). So for now I've just added a `animateUser` bool that determines whether the pickup-animation is sent to the user that initiated the pickup.

I'm not sure why, but when an item is dropped while walking, there is a delay before the item is nudged in the direction the user was walking. I'm guessing that whatever applies that force is sever-side somewhere?

## Video

Video with a laggy client on the right (`net.fakelagmin 0.5`). Picking items up is delayed, but swaping hands & dropping isn't

https://user-images.githubusercontent.com/60421075/144159565-29e94847-980f-41a4-9c0f-724a78e64ea3.mp4

2021-12-01 02:27 UTC, ElectroJr commented on Content.Server/Weapon/Ranged/ServerRangedWeaponComponent.cs
> -        }
I still have to replace this, so DNM until fixed

2021-12-19 04:47 UTC, ShadowCommander approved these changes
Tested in game and doesn't seem to be anything obvious that broke.

2021-12-29 21:08 UTC, ShadowCommander requested changes

2021-12-29 21:08 UTC, ShadowCommander commented on Content.Shared/Item/SharedItemComponent.cs
> +            EntitySystem.Get<SharedHandsSystem>().UpdateHandVisualizer(Owner, hands);
```suggestion
            if (!Owner.TryGetContainer(out var container)
                || !_entMan.TryGetComponent(container.Owner, out SharedHandsComponent hands))
                return;

            EntitySystem.Get<SharedHandsSystem>().UpdateHandVisualizer(container.Owner, hands);
```

2021-12-29 23:22 UTC, PaulRitter reviewed
partial review i never submitted

2021-12-31 04:27 UTC, ElectroJr commented on Content.Client/Items/Managers/ItemSlotManager.cs
> +            if (entity == null || entity == default)
because it was brushing up on inventory stuff that was using default and I wanted to avoid touching that. will remove now

2021-12-31 05:25 UTC, ElectroJr commented
Need to fix several issues after inventory refactor, DNM.

2022-01-01 08:45 UTC, ElectroJr commented
> Need to fix several issues after inventory refactor, DNM.

Looks like they were mostly just general inv-refactor problems, not hands specific, and they've since been fixed. So seems fine to merge again.

2022-01-04 07:49 UTC, ShadowCommander approved these changes
Haven't tested it yet, but code looks fine.

2022-01-04 07:49 UTC, ShadowCommander commented on Content.Client/Hands/Systems/HandsSystem.cs
> +        }
```suggestion
        }

```

2022-01-04 07:49 UTC, ShadowCommander commented on Content.Client/Hands/Systems/HandsSystem.cs
> +
```suggestion
```

2022-01-05 04:53 UTC, merged