Removes smilies from existence. (kinda)
space-wizards/space-station-14 pull request #5649
Opened 2021-12-01 22:31 UTC by moonheart08

## About the PR 
No more smilies.
```
[INFO] CON: > say "Hello! :)"
[DEBG] chat: Local: Hello!
[DEBG] chat: Emotes: smiles
```

:cl: moony
- add: In-game chat now has a sanitizer that removes smilies. You can now put :) or similar at the end of your message to emote automatically.

2021-12-01 22:34 UTC, DogZeroX commented
Should do lmao for laughs and kek for giggles

2021-12-01 22:35 UTC, moonheart08 commented
> Should do lmao for laughs and kek for giggles

specific to smilies. I'll figure out a good solution for things that might go midsentence later.

2021-12-02 22:44 UTC, DrSmugleaf requested changes

2021-12-02 22:44 UTC, DrSmugleaf commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> +    private static readonly Dictionary<string, string> SmilelyToEmote = new()
Smilely > smiley

2021-12-02 23:35 UTC, moonheart08 commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> +    private static readonly Dictionary<string, string> SmilelyToEmote = new()
i knew i was getting it wrong

2021-12-03 00:10 UTC, PaulRitter requested changes
nitpicks, otherwise lgtm

2021-12-03 00:10 UTC, PaulRitter commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> +        }
just do
```csharp
        foreach (var (smiley, replacement) in SmileyToEmote)
```
to avoid the extra dict lookup

2021-12-03 00:10 UTC, PaulRitter commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> +        if (!_configurationManager.GetCVar(CCVars.ChatSanitizerEnabled))
cache this

2021-12-03 00:34 UTC, PaulRitter requested changes

2021-12-03 00:34 UTC, PaulRitter commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> +        _configurationManager.OnValueChanged(CCVars.ChatSanitizerEnabled, x => doSanitize = x, true);
you'll wanna u subscribe in shutdown

2021-12-03 00:34 UTC, PaulRitter commented on Content.Server/Entry/EntryPoint.cs
> +            IoCManager.Resolve<IChatSanitizationManager>().Initialize();
initialize before chatmanager IMO

2021-12-03 00:49 UTC, merged