Adds posters (for mapping)
space-wizards/space-station-14 pull request #5812
Opened 2021-12-18 00:22 UTC by AJCM-git

## About the PR
Adds poster entities and spawners for mapping, functionality of rolled posters will be done in a future PR.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/60196617/146621767-eed9f2ae-a5c5-4bbe-bb64-9a299b69d2a6.png)

2021-12-18 00:51 UTC, TimrodDX commented
If you wouldn't mind, there's the "SPACE" poster that gets put near external airlocks which I don't think is in the game. Could you add that? I know there's at least a few of those on the original Packed and I'd be happy to put them on SS14 Packed.

2021-12-18 00:53 UTC, AJCM-git commented
If you can find it and post the link sure

2021-12-20 18:14 UTC, AJCM-git commented
Tests pass now and ready for a merge (couldn't find the poster Timrod was referring to). Thanks to @wrexbe for a solution to the MapInit issues

2021-12-21 18:22 UTC, PaulRitter requested changes
lgtm besides my comment

2021-12-21 18:22 UTC, PaulRitter commented on Resources/Prototypes/Entities/Objects/Decoration/posters.yml
> +    state: rolled_legit
afaict these are just placebo posters, which you cant actually place on walls. we decided on not adding non-functional items into the game, so these would either need to be removed or coded to actually be placeable

2021-12-21 19:06 UTC, PaulRitter requested changes
otherwise lgtm

2021-12-21 19:06 UTC, PaulRitter commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
> +    state: poster34_contraband
remove this one & its image

2021-12-21 19:06 UTC, PaulRitter commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
> +    state: poster34_legit
remove this one and its image

2021-12-21 20:43 UTC, PaulRitter commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
> +    state: poster34_legit
scratch that, just tone down the description

2021-12-21 21:00 UTC, AJCM-git commented
Reviews addressed

2021-12-22 22:46 UTC, PaulRitter approved these changes

2021-12-29 09:24 UTC, merged