Adds temperature to solutions
space-wizards/space-station-14 pull request #5834
Opened 2021-12-19 13:52 UTC by TemporalOroboros

Gives solutions a temperature and some basic backend to manipulate it.

**Changelog**

:cl:
- add: Added temperature handling to solutions. Nothing actually uses it yet, but it exists.

2021-12-19 13:59 UTC, TemporalOroboros commented
The tests are exploding because they run before `IPrototypeManager` is registered to `IoCManager`. How do I fix this?

2021-12-19 15:15 UTC, TemporalOroboros commented on Content.Shared/Chemistry/Components/Solution.cs
> +            if (!IoCManager.Resolve<IPrototypeManager>().TryIndex(reagentId, out ReagentPrototype? proto))
This line specifically is what is blowing up.

2021-12-19 16:15 UTC, TemporalOroboros commented on Content.Shared/Chemistry/Components/Solution.cs
> +            if (!IoCManager.Resolve<IPrototypeManager>().TryIndex(reagentId, out ReagentPrototype? proto))
Paul has given me advice on how to fix this.

2021-12-19 16:21 UTC, TemporalOroboros commented on Content.Shared/Chemistry/Components/Solution.cs
> +            if (!IoCManager.Resolve<IPrototypeManager>().TryIndex(reagentId, out ReagentPrototype? proto))
It looks like it's fixed.

2021-12-19 16:52 UTC, TemporalOroboros commented on Content.Shared/Chemistry/Components/Solution.cs
> +            if (!IoCManager.Resolve<IPrototypeManager>().TryIndex(reagentId, out ReagentPrototype? proto))
It looks like it's fixed.

2021-12-19 23:14 UTC, mirrorcult requested changes
fantastic PR

having them be doubles is meh, I'd prefer if they were the same as atmos' temperature for consistency (float)

2021-12-19 23:14 UTC, mirrorcult commented on Content.Server/Chemistry/ReagentEffectConditions/SolutionThermalEnergy.cs
> +    ///     Requires the solution to be above or below a certain temperature.
incorrect xmldoc

2021-12-19 23:14 UTC, mirrorcult commented on Resources/Locale/en-US/administration/ui/manage-solutions/manage-solutions.ftl
> +admin-solutions-window-thermal-energy-label = Thermal Energy (J):
might want to look into the generic unit formatting in localization for some of the SI units here, but not strictly necessary

2021-12-20 03:19 UTC, TemporalOroboros commented on Content.Server/Chemistry/ReagentEffectConditions/SolutionThermalEnergy.cs
> +    ///     Requires the solution to be above or below a certain temperature.
It has been corrected.

2021-12-20 03:20 UTC, TemporalOroboros commented
They've been converted back to floats.

2021-12-20 03:21 UTC, mirrorcult approved these changes

2021-12-24 09:22 UTC, merged