Saltern Salvage Tweak
space-wizards/space-station-14 pull request #5878
Opened 2021-12-23 14:28 UTC by Pangogie

Gives Saltern a catwalk so salvage crews can get closer to the wrecks.

Also adds prototype for salvage equipment crates to the cargo catalog.

![image](https://user-images.githubusercontent.com/7548248/147253722-0543849d-78bc-4dfc-b402-4bcdf4021050.png)

2021-12-24 12:13 UTC, PaulRitter approved these changes

2021-12-24 17:31 UTC, moonheart08 requested changes
The bridge cuts it a bit close to the salvage spawn area, I think the last section should be removed.

2021-12-24 22:58 UTC, Efruit commented
Does this mean we're not planning to use that area for a cargo shuttle dock?

2021-12-25 05:37 UTC, Pangogie commented
Shortened the catwalk.
I see this as a temporary solution while salvage is in early stages so people can experiment with it. Can be changed to fit cargo shuttles when the time arises.
![image](https://user-images.githubusercontent.com/7548248/147378194-c93cd096-c4ab-4b58-86c1-29582250970e.png)

2021-12-26 04:06 UTC, merged