Light Cigars when interacting with hot stuff
space-wizards/space-station-14 pull request #5879
Opened 2021-12-23 16:36 UTC by JustinTether

Subscribed to IsHotEvent in ThrusterSystem, added AfterInteractEvent to SmokingSystem.Cigar which will set SmokableState to Lit if IsHotEvent returns true

This should mean that cigs/Cigars should light when interacting with anything hot, which should fix issue 5429

## About the PR 

**Screenshots**

**Changelog**

:cl: JustinTime
- tweak: Subscribed to IsHotEvent in ThrusterSystem
- tweak: Added AfterInteractEvent in SmokingSystem.Cigar to raise IsHotEvent and set Smokablestate to Lit if the item was hot

2021-12-23 16:38 UTC, DogZeroX commented
You should make the changelog more user-friendly. "You can now light the cigar by clicking it on a thruster."

2021-12-23 16:39 UTC, JustinTether commented
Yea that makes sense, especially if it's going to be public facing

2021-12-23 17:06 UTC, metalgearsloth requested changes

2021-12-23 17:06 UTC, metalgearsloth commented on Content.Server/Shuttles/EntitySystems/ThrusterSystem.cs
> +        }
Gyros shouldn't be hot IMO, for now just check if it's an angular thruster.

2021-12-23 17:09 UTC, metalgearsloth commented on Content.Server/Nutrition/EntitySystems/SmokingSystem.Cigar.cs
> +            RaiseLocalEvent(targetEntity.Uid, isHotEvent);
Your branch is very old and needs updating hence the error.

2021-12-24 06:02 UTC, JustinTether commented
I think 99cb6a0 should address the issues brought up by metalgearsloth

2021-12-24 11:39 UTC, metalgearsloth approved these changes
I made some changes:
- Check IsOn not Enabled (as that is the toggle not whether the thruster is lit)
- Check if smokable already lit up front to avoid the eventbus event.

2021-12-24 11:59 UTC, merged