Adds a lobby final countdown.
space-wizards/space-station-14 pull request #5945
Opened 2021-12-29 17:17 UTC by pointer-to-null

## About the PR 

Setting a round start time to 10 seconds when all players in the lobby pressed the "Ready Up" button.

I was thinking about adding a CVar for this. But I don’t know if it’s needed.

https://user-images.githubusercontent.com/91910481/147684742-ea1a4be2-e0a5-420e-9515-2a3856069aab.mp4

**Changelog**

:cl:
- add: Added a 10 seconds final countdown in the lobby when all players are ready.

2021-12-31 02:25 UTC, mirrorcult requested changes

2021-12-31 02:25 UTC, mirrorcult commented on Content.Server/GameTicking/GameTicker.Lobby.cs
> +        private readonly TimeSpan _finalCountdownTime = new TimeSpan(0, 0, 10);
should be a cvar imo

2021-12-31 09:15 UTC, pointer-to-null commented on Content.Server/GameTicking/GameTicker.Lobby.cs
> +        private readonly TimeSpan _finalCountdownTime = new TimeSpan(0, 0, 10);
Done.

2022-01-01 11:17 UTC, Zumorica commented
I don't like this, honestly. The round start timer is long on purpose so people can join the server during it and ready up.

2022-01-01 16:26 UTC, pointer-to-null commented
> I don't like this, honestly. The round start timer is long on purpose so people can join the server during it and ready up.

In some cases admin can control this by using delay/pause. But yea, if there is no admin then this not going to work.

So, there are two options here: 
1. Scrap this PR. 
2. I can make this feature toggleable through CVar. And it will be off by default.

Both are fine with me.

2022-01-01 17:00 UTC, PaulRitter commented
ngl, i agree with vera & pjb. i dont see the need

2022-01-05 05:48 UTC, metalgearsloth commented
If a fork ever asks for it we'll have a reference PR.

2022-01-05 05:48 UTC, closed without merging