Add SMES Recipe
space-wizards/space-station-14 pull request #5967
Opened 2021-12-31 09:21 UTC by DubiousDoggo

- Added a crafting recipe for SMES.
- Uses the machine frame with a SMES machine board.
- SMES machine board unlocked with Electromagnetic Theory, made at lathe.
- Requires 5 MV cable, 5 HV cable and 10 capacitor, can be tweaked if need be.

**Changelog**
:cl:
- add: Added SMES construction - no more easy power crippling :)

2021-12-31 09:24 UTC, DubiousDoggo commented
fixes part of #5515

2022-01-02 05:30 UTC, mirrorcult requested changes

2022-01-02 05:30 UTC, mirrorcult commented on Resources/Prototypes/Entities/Structures/Power/smes.yml
> +      LayoutId: SMES
does this layout ID even do anything, i dont think the SMES wire layout exists? if it doesnt just remove this for now

2022-01-09 07:10 UTC, mirrorcult approved these changes

2022-01-09 07:31 UTC, merged