Removed more copyright materials
space-wizards/space-station-14 pull request #5984
Opened 2022-01-01 14:31 UTC by Peptide90

Removed wretchedhive bar sign and altered LV426 to a spider.

If anyone can spot or think of anything else copyright related let me know and I can bundle it in with this PR.

![lv426](https://user-images.githubusercontent.com/78795277/147852839-5739a639-de46-4f26-a738-c2a7dbf38f7f.png)

2022-01-01 17:09 UTC, PaulRitter approved these changes

2022-01-01 17:10 UTC, PaulRitter requested changes
you gotta adjust the barsign.rsi/meta.json to reflect the deleted state

2022-01-02 19:41 UTC, Peptide90 commented
> you gotta adjust the barsign.rsi/meta.json to reflect the deleted state

My bad, forgot about that. Fixed now and corrected some other issues and copyright in posters.

2022-01-02 22:18 UTC, Phantom-Lily commented
"Richard" item probably falls under this.

2022-01-03 00:56 UTC, PaulRitter approved these changes

2022-01-04 13:56 UTC, merged