Singulo/Radiation Tweaks
space-wizards/space-station-14 pull request #6045
Opened 2022-01-06 07:52 UTC by Pangogie

This is mostly intended as a temporary fix so the singularity will stop vaporizing people. Please adjust as necessary.

Added RadPerSecondBase so the singularity can change rads per level correctly based on the defined dps.
Added items to fill rad suit closets.
Renamed radiation suit/hood.
Radiation is now applied per 1s instead of 0.5s. (I think.)
Nerfed radiation storm damage to be less obnoxious. 8 --> 5

:cl: Pancake
- fix: The singularity will no longer vaporize engineers in 2 seconds.
- fix: Radiation suit closets are now filled.

2022-01-06 08:13 UTC, ElectroJr reviewed
The fills are gonna conflict with #6006

2022-01-06 11:48 UTC, Pangogie commented
> The fills are gonna conflict with #6006

Fixed.

2022-01-07 04:13 UTC, ElectroJr commented on Content.Shared/Radiation/SharedRadiationStorm.cs
> +        public virtual float RadsPerSecondBase { get; set; }
I don't think the client makes use of `RadsPerSecondBase`, so you can just leave that server-side?

2022-01-07 04:14 UTC, ElectroJr commented on Content.Shared/Radiation/SharedRadiationStorm.cs
> +        public readonly float RadsPerSecondBase;
```suggestion
```

2022-01-07 04:17 UTC, ElectroJr commented on Content.Server/Radiation/RadiationPulseComponent.cs
> +        }
Both `RadsPerSecondBase` and `RadsPerSecond` are backed by the same value (`_radsPerSecond`). Is there supposed to be a `_radsPerSecondBase`?

2022-01-07 04:19 UTC, ElectroJr commented on Content.Shared/Radiation/SharedRadiationStorm.cs
>          public readonly float RadsPerSecond;
Just adding this in here is not sufficient to make sure that this variable is networked.

You also need to add it to the constructor (see how `RadsPerSecond` is set a few lines below this), and you also need to then make use of it in `HandleComponentState()` in the client's `RadiationPulseComponent`.

Alternatively, if it just doesn't need to be networked (which seems to be the case, given that its only used to set `RadsPerSecond` which is networked), then you can just remove it from the state.

2022-01-07 04:21 UTC, ElectroJr commented on Content.Shared/Radiation/SharedRadiationStorm.cs
>          public readonly float RadsPerSecond;
And also remove the dirtying when setting.

I.e., the code from before:
```cs
public override float RadsPerSecondBase
{
    get => _radsPerSecond;
    set
    {
        _radsPerSecond = value;
        Dirty();
    }
}
```
could just be
```cs
public override float RadsPerSecondBase { get; set; }
```

2022-01-07 04:27 UTC, ElectroJr requested changes
Need to fix or remove the networking/component state stuff. and conflicts.

2022-01-09 11:22 UTC, Pangogie commented
I just heckin' hardcoded in the radiation values for now. I'm not competent enough to do the proper C# necessary for the other methods. Again, this is just intended as a fix so the singulo stops doing 30+ dps and vaporizing engineers the second it starts.

2022-01-10 04:53 UTC, ElectroJr reviewed
Even if radiation needs to be re-done eventually, it should still be in yaml. Also instead of just deleting the changes, you deleted `engineer.yml` altogether.

If you just want to get singulo fixed quickly, mind if I add commits to this branch?

2022-01-10 04:58 UTC, Pangogie commented
> Even if radiation needs to be re-done eventually, it should still be in yaml. Also instead of just deleting the changes, you deleted `engineer.yml` altogether.
> 
> If you just want to get singulo fixed quickly, mind if I add commits to this branch?

I did?! Gosh dang it. I thought I was just deleting the change when I did it through Github.

Ya go right for it, man. I'm not the best at C#.

2022-01-10 05:36 UTC, ElectroJr approved these changes
This isn't so much count as an "approve" as it is just a  "no longer request changes", given I made those changes, somone else should approve this.

2022-01-11 06:30 UTC, merged