Change LogImpact for laser/hitscan weapons.
space-wizards/space-station-14 pull request #6139
Opened 2022-01-12 12:24 UTC by Pangogie

Adds high impact for laser/hitscan weapons and extreme impact for over 15 damage.

This will make finding laser weapon usage much easier in logs.

2022-01-13 04:20 UTC, ElectroJr commented
> This will make finding laser weapon usage much easier in logs.

Wouldn't just filtering by `LogType.HitScanHit` be sufficient for that?

Also I don't know if there is actually any standard for what counts as `Extreme` vs `High`, but at the moment explosions are only `High`. So if this is bumped up, they should definitely also be. But even with that change, 15 seems too low to be extreme. IMO extreme events should have the capacity to outright crit/kill one or more people.

2022-01-15 08:50 UTC, ShadowCommander requested changes

2022-01-15 08:50 UTC, ShadowCommander commented on Content.Server/Weapon/Ranged/Barrels/Components/ServerRangedBarrelComponent.cs
> +                        logImpact = LogImpact.Extreme;
```suggestion
                    logImpact = dmg.Total > 15 ? LogImpact.Extreme : LogImpact.High;
```

2022-01-15 08:50 UTC, ShadowCommander commented on Content.Server/Weapon/Ranged/Barrels/Components/ServerRangedBarrelComponent.cs
> +
```suggestion
```
Unnecessary line break.

2022-01-21 06:38 UTC, closed without merging