Disposal Pipe Crafting
space-wizards/space-station-14 pull request #6188
Opened 2022-01-16 05:05 UTC by DubiousDoggo

what it says on the tin

:cl:
- add: Added construction for disposal pipes

2022-01-16 11:30 UTC, Peptide90 commented
lgtm, not sure on 1 steel sheet per pipe but that's a simple thing to balance later. RPD would be something to look at in future for straight building them like an RCD.

Not sure how broken pipes are currently handled RE removing them but could be something to consider. In regards to my above comment, if broken pipes give you 1 metal sheet we don't want them to be infinitely rebuildable.

2022-01-17 19:26 UTC, mirrorcult requested changes
not sure if we want this even as a stopgap, since RPDs would be better. maybe a topic for the meeting

2022-01-17 20:51 UTC, moonheart08 approved these changes
This seems fine to me, and construction is certainly better than a pipe dispenser.

2022-01-18 22:16 UTC, mirrorcult approved these changes
i have decided that it is fine

2022-01-18 23:18 UTC, Peptide90 commented
> i have decided that it is fine

We happy with it only taking 1 metal sheet per pipe? In which case a destroyed pipe being removed should return no scrap.

2022-01-19 15:44 UTC, metalgearsloth reviewed
do_afters should be at least 1s IMO.

I say this because I have 350ms ping to EU and the bar essentially disappears as soon as it starts if it's 0.5s

2022-01-19 20:23 UTC, Peptide90 requested changes
Pretty much main point is PascalCase for graph IDs (I have a PR coming for everything else in recipes). Plus the APC naming change.

2022-01-19 20:23 UTC, Peptide90 commented on Resources/Prototypes/Entities/Structures/Piping/Disposal/pipes.yml
> +    graph: disposalPipe
All graph IDs should be PascalCase now: DisposalPipe

2022-01-19 20:23 UTC, Peptide90 commented on Resources/Prototypes/Entities/Structures/Piping/Disposal/pipes.yml
> +    graph: disposalPipe
DisposalPipe

2022-01-19 20:23 UTC, Peptide90 commented on Resources/Prototypes/Entities/Structures/Piping/Disposal/pipes.yml
> +    graph: disposalPipe
DisposalPipe

2022-01-19 20:23 UTC, Peptide90 commented on Resources/Prototypes/Entities/Structures/Piping/Disposal/pipes.yml
> +    graph: disposalPipe
DisposalPipe

2022-01-19 20:23 UTC, Peptide90 commented on Resources/Prototypes/Entities/Structures/Piping/Disposal/pipes.yml
> +    graph: disposalPipe
DisposalPipe

2022-01-19 20:23 UTC, Peptide90 commented on Resources/Prototypes/Entities/Structures/Piping/Disposal/pipes.yml
> +    graph: disposalPipe
DisposalPipe

2022-01-19 20:23 UTC, Peptide90 commented on Resources/Prototypes/Entities/Structures/Piping/Disposal/pipes.yml
> +    graph: disposalPipe
DisposalPipe

2022-01-19 20:23 UTC, Peptide90 commented on Resources/Prototypes/Recipes/Construction/Graphs/utilities/disposal_pipes.yml
> +  id: disposalPipe
DisposalPipe

2022-01-19 20:23 UTC, Peptide90 commented on Resources/Prototypes/Recipes/Construction/utilities.yml
> +  name: apc
Acronym names to remain upper case: APC

2022-01-19 20:23 UTC, Peptide90 commented on Resources/Prototypes/Recipes/Construction/utilities.yml
> +  graph: disposalPipe
DisposalPipe - won't tag it for every instance in this file.

2022-01-22 12:54 UTC, merged