Disabled "die" and "stay alive" objectived, reduced max difficulty to compensate
space-wizards/space-station-14 pull request #6247
Opened 2022-01-20 01:34 UTC by Elijahrane

## About the PR 
Discussed the reasoning a bit in Discord, but with the current way rounds end these are kind of bad and really mess up the difficulty balance. Most objectives imply 'stay alive' and 'die' is easily cheesed by /suiciding 3 seconds before the round ends. These can be revisited after there's an actual evac shuttle and round end I think.

**Changelog**

:cl: Rane
- remove: Removed objectives to die or stay alive.
- tweak: Lowered max objective difficulty.

2022-01-20 01:50 UTC, moonheart08 requested changes
Yea no, I want a p good argument for why these objectives should go. This needs discussed before merging.

2022-01-20 02:11 UTC, Elijahrane commented
To summarize the arguments in Discord so far:
1. Most objectives basically imply "stay alive", so it's basically free difficulty knocked off if you get it because there's a 95% chance you redtext anyway if you die.
2. Die is very cheesable but it's a classic and usually gets more leeway on murderboning once servers start approaching MRP, so it should probably remain but be way rarer than it is now.

2022-01-30 13:58 UTC, metalgearsloth commented
Don't see any arguments on github so gonna merge when CI passes.

2022-01-30 14:06 UTC, metalgearsloth commented on Resources/Prototypes/Objectives/traitorObjectives..yml
> +  difficultyOverride: 1.75
```suggestion
  difficultyOverride: 2.75
```

2022-01-30 14:19 UTC, merged