Fix wallmount rotation
space-wizards/space-station-14 pull request #6272
Opened 2022-01-22 18:53 UTC by Charlese2

## About the PR 
Fixes: #6271 
This adds the rotation of the grid that the construction ghost is being placed on as an offset to the direction check in WallmountCondition.
**Screenshots**

**Changelog**

2022-01-22 18:56 UTC, Charlese2 commented
Is there a better way to get the rotation of the grid you are trying to build on?

2022-01-22 19:19 UTC, Acruid commented
No, that is the best way.

2022-01-23 12:04 UTC, metalgearsloth requested changes

2022-01-23 12:04 UTC, metalgearsloth commented on Content.Shared/Construction/Conditions/WallmountCondition.cs
> +            var gridRotation = IoCManager.Resolve<IEntityManager>().GetComponent<TransformComponent>(location.EntityId).WorldRotation;
All of the IEntityManager resolves in this method can be replaced with the entManager that is already resolved above.

2022-01-25 09:29 UTC, merged