Shutter construction
space-wizards/space-station-14 pull request #6427
Opened 2022-02-01 09:16 UTC by Peptide90

## About the PR 
Adds construction for shutters, window shutters (2x glass before finishing) and radiation shutters (2x steel before finishing).

Construction steps pretty much follow the same as firelocks but use door electronics instead of firelock. See gifs below.

PRing for now as complete however will need to check how this works with mapper shutters as not sure they can be deconstructed due to having many IDs for shutters - will investigate when I have more time soon.
**Screenshots**

![shutter (2)](https://user-images.githubusercontent.com/78795277/151941677-38c4bc3a-384a-4ca2-96fa-11597ef6c52e.gif)
Glass
![shutter glass](https://user-images.githubusercontent.com/78795277/151941692-29fe8261-959e-41c2-97d7-8fd7eeb151b6.gif)
Radiation
![radiation](https://user-images.githubusercontent.com/78795277/151941725-d0f3f94c-20c7-4a48-8e4a-a9a8854d068f.gif)

**Changelog**

:cl:
- add: Shutters can now be constructed from the construction menu (G)! Add glass before final step for windowed, or steel for radiation shutters.

2022-02-02 23:15 UTC, metalgearsloth requested changes

2022-02-03 15:19 UTC, Peptide90 commented on Resources/Prototypes/Entities/Structures/Doors/Shutter/shutters.yml
> +      - SmallImpassable
Copied from firelock frame, I'll scrap it for Opaque.

2022-02-03 15:19 UTC, Peptide90 commented on Resources/Prototypes/Entities/Structures/Doors/Shutter/shutters.yml
> +      - VaultImpassable
As other comment, was copied from firelock frame. Main difference being this is an overhead shutter so should be passable, will remove.

2022-02-07 19:39 UTC, mirrorcult approved these changes

2022-02-08 10:49 UTC, merged