Bored apes can now scream
space-wizards/space-station-14 pull request #6497
Opened 2022-02-06 08:37 UTC by hubismal

## About the PR 
Monkeys can now scream using the classic goonstation sound effect. There is a new action MonkeyScream, similar to VoxScream. The ScreamAction also now accepts datafields for volume and variation, and falls back to male voices if mobs don't have a defined sex.

If anyone has any high quality free monkey screaming sound effects from the internet, please tell me. I had trouble finding anything on the quality/energy of the original goon sound.

**Changelog**

:cl:
- add: Monkeys can scream now via their action bar (next to combat mode).

2022-02-13 11:33 UTC, metalgearsloth requested changes
Use snake casing instead (monkey_scream). Can't push to your repo or I would've just done it.

2022-02-19 19:34 UTC, mirrorcult approved these changes

2022-02-19 19:34 UTC, mirrorcult commented
still working on this? just a minor review

2022-02-28 14:12 UTC, metalgearsloth commented
we can re-open when you get a chance to work on it.

2022-02-28 14:12 UTC, closed without merging