Fires burn bright
space-wizards/space-station-14 pull request #6516
Opened 2022-02-07 00:16 UTC by hubismal

## About the PR 
Fires now visibly burn brightly (which is to say they're unshaded) whether they're a mob/entity on fire, or a hallway on fire.
This should also make the explosion rework (if that's still a thing) look nicer.

Specifically: 
- The fire overlay on a human is now unshaded.

- The fire-recoloring logic in GasTileOverlaySystem is moved into a new function that a new overlay, FireTileOverlay, uses. FireTileOverlay is essentially GasTileOverlay but with the unshaded shader (and it obviously only draws fire).

**Screenshots**
![image](https://user-images.githubusercontent.com/47284081/152707295-3cec41a9-1ccf-4b74-b3f7-ea8497a5b539.png)
![image](https://user-images.githubusercontent.com/47284081/152707305-7ec32e01-7484-4008-9adb-7d32363cde3b.png)

**Changelog**

:cl:
- tweak: Fires now burn brightly, meaning fires and people affected by fire are much more noticeable.

2022-02-07 00:19 UTC, mirrorcult commented
doesnt gastileoverlay still draw the fire stuff

2022-02-07 00:26 UTC, hubismal commented
> doesnt gastileoverlay still draw the fire stuff

it only draws gas now because the method in gastileoverlaysystem it uses used to account for fires and send the appropriate colors. now it doesn't, the code for coloring fires was moved into MoveNextFire.


(i think)

2022-02-07 00:55 UTC, hubismal commented
To prove my point, here's what it looks like when FireTileOverlay is commented out from being added.

https://user-images.githubusercontent.com/47284081/152709467-dfe9e80b-3e90-42f6-9c00-febb72527a21.mp4

2022-02-07 01:05 UTC, metalgearsloth requested changes

2022-02-07 01:05 UTC, metalgearsloth commented on Content.Client/Atmos/Overlays/FireTileOverlay.cs
> +            IoCManager.InjectDependencies(this);
So nice it's injected twice.

2022-02-07 01:05 UTC, metalgearsloth commented on Content.Client/Atmos/EntitySystems/GasTileOverlaySystem.cs
> +            {
You should split this to 2 separate struct enumerators.

2022-02-07 01:20 UTC, mirrorcult commented
> To prove my point, here's what it looks like when FireTileOverlay is commented out from being added.
> 
> 

all good then

2022-02-08 10:34 UTC, Pangogie commented
> I feel like people on fire should have a pointlight to actually glow. Makes for some scary maint chases.

They'd likely have to write some sort of edge finding code so the light is only on the edges for performance reasons.

2022-02-08 10:36 UTC, metalgearsloth commented
> > I feel like people on fire should have a pointlight to actually glow. Makes for some scary maint chases.
> 
> They'd likely have to write some sort of edge finding code so the light is only on the edges for performance reasons.

Think they meant for people on fire and not the gas itself.

2022-02-08 10:43 UTC, merged

2022-02-08 21:19 UTC, Matz05 commented
As I understand the tiny, non-shadow-casting point lights are now able to be used extremely freely with minimal performance impact, and only a risk of 'not all of them drawing' in cases of overuse, so as long as you stick to those and not the shadow-casting kind, I _think_ light from fire tiles and burning entities should be OK?

2022-02-08 22:04 UTC, hubismal commented
> As I understand the tiny, non-shadow-casting point lights are now able to be used extremely freely with minimal performance impact, and only a risk of 'not all of them drawing' in cases of overuse, so as long as you stick to those and not the shadow-casting kind, I _think_ light from fire tiles and burning entities should be OK?

If you just want a non-shadow casting glow effect from fire it would be functionally identical and probably less convoluted to make a new shader for fire that has a bloom effect on it.

2022-02-08 23:16 UTC, Matz05 commented
That's probably a better solution for fire tiles, yeah. Burning entities can probably get away with tiny point lights and the unshaded layer?