Added text for petting Holoparasites
space-wizards/space-station-14 pull request #6728
Opened 2022-02-15 17:52 UTC by MaxNox7

I sure do hope this works...

**Changelog**
Added text for both succeeding and failing at petting a Holoparasite

2022-02-15 17:58 UTC, Willhelm53 requested changes

2022-02-15 17:58 UTC, Willhelm53 commented on Resources/Locale/en-US/interaction/interaction-popup-component.ftl
Change "it's" to {POSS-ADJ($target)} and you should be good. Also maybe close this PR and make this change in your first branch

2022-02-15 18:06 UTC, Peptide90 commented
Should probably be apart of #6727

2022-02-15 18:12 UTC, Zymem commented
Just a warning, there's a typo in the text. 
"it's" should be "its".

2022-02-15 18:21 UTC, Willhelm53 commented
> Just a warning, there's a typo in the text. "it's" should be "its".

Changing that to {POSS-ADJ($target)} will take care of this for you. Good work though!

2022-02-19 19:29 UTC, mirrorcult requested changes
add the complementary component to the holopara

2022-02-19 20:26 UTC, Willhelm53 commented on Resources/Locale/en-US/interaction/interaction-popup-component.ftl
>Also maybe close this PR and make this change in your first branch

Ignore this part now.

2022-02-19 20:27 UTC, Willhelm53 requested changes

2022-02-19 20:27 UTC, Willhelm53 commented on Resources/Locale/en-US/interaction/interaction-popup-component.ftl
> +petting-failure-holo = You reach out to pet {THE($target)}, but {POSS-ADJ($target) spikes almost impale your hand!
Missing a }

2022-02-20 10:40 UTC, CrudeWax commented
Now this is what my PR has been lacking all along

2022-02-20 11:03 UTC, metalgearsloth commented
changelog text won't show up ingame if that's what you want, needs to follow the formatting in the PR template.

2022-02-28 15:36 UTC, merged