Medical items sound support + sounds
space-wizards/space-station-14 pull request #6871
Opened 2022-02-23 14:07 UTC by elthundercloud

## About the PR 
Fix:  #6786
Medical items have  sounds:
- Medical items have `healingBeginSound` and `healingEndSound` data  fields
- Ointment, brutepack and gauze now have basic sounds I stole from various places

2022-02-23 14:10 UTC, metalgearsloth requested changes
Licensing for audio?

2022-02-23 14:10 UTC, metalgearsloth commented on Content.Server/Medical/HealingSystem.cs
> +    [Dependency] private readonly ActionBlockerSystem _blocker = default!;
?

2022-02-23 14:10 UTC, metalgearsloth commented on Content.Server/Medical/HealingSystem.cs
> +            SoundSystem.Play(Filter.Pvs(uid), args.Component.HealingEndSound.GetSound(), uid, AudioHelpers.WithVariation(0.125f).WithVolume(-5f));
Pass in EntityManager to the Pvs static methods.

2022-02-23 14:19 UTC, elthundercloud commented
>Licensing for audio?
Freesound.org and I slapped it together in Reaper

2022-02-23 14:23 UTC, Willhelm53 commented
Good work! You'll need to include a quick licenses.txt, see Resources/Audio/Animals for an example.

2022-02-27 04:48 UTC, mirrorcult approved these changes

2022-02-27 07:02 UTC, merged