Guardians Ignore bullets
space-wizards/space-station-14 pull request #7035
Opened 2022-03-08 12:38 UTC by CrudeWax

## About the PR 
Fixes the unintentional design issue of holoparasites not being immune to bullets. 
Now bullets pass through holoparasites and other forms of guardians, with the intention being that security will have to either mix up their arsenal with lasers, or shoot the owner, hence introducing more counter-play than "Rush with lethal gun"

**Screenshots**

**Changelog**

:cl: CrudeWax
- fix: Bullets now fly through Guardians in accordance with the Cybersun handbook. Better aim for the owner!
- tweak: Stun bolts also pass through guardians. Laser beams however don't.

2022-03-08 12:39 UTC, CrudeWax commented
Why are pipes haunting my PRs

2022-03-08 15:08 UTC, moonheart08 commented
We are not giving miners/salvagers holoparasites.

2022-03-08 23:48 UTC, mirrorcult commented
just gut it from the PR for now

2022-03-09 22:03 UTC, CrudeWax commented
Removed

2022-03-09 22:48 UTC, mirrorcult commented
fix conflicts and good to merge

2022-03-10 09:02 UTC, metalgearsloth requested changes
Most of the sprite fields are dupe with the base one.

2022-03-11 19:05 UTC, CrudeWax commented
Ready for merge

2022-03-13 16:46 UTC, metalgearsloth requested changes
Bunch of duplicate datafields and also spelling.

2022-03-13 16:46 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/guardian_activators.yml
> +  description: I guess the wizard federation had to cut costs after the jhin merchandise scandal
League reference?

2022-03-13 16:46 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Mobs/Player/guardian.yml
> +      - VaultImpassable
Are these correct?

2022-03-13 16:46 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/guardian_activators.yml
> +        visible: false
?

2022-03-13 21:27 UTC, CrudeWax commented on Resources/Prototypes/Entities/Mobs/Player/guardian.yml
> +      - VaultImpassable
Yes.

2022-03-15 17:15 UTC, CrudeWax commented on Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/guardian_activators.yml
> +        visible: false
As intended.

2022-03-15 19:25 UTC, Mith-randalf commented
Out of curiosity, can you run me through the reason for holoparas being immune to bullets?

2022-03-17 18:44 UTC, mirrorcult commented
> Out of curiosity, can you run me through the reason for holoparas being immune to bullets?

lets them fill a more interesting niche, gives them a bit more utility since they're underpowered now, and makes combat with holopara users more fun

2022-03-17 18:45 UTC, mirrorcult approved these changes

2022-03-17 18:46 UTC, merged