Agent ID Cards
space-wizards/space-station-14 pull request #7041
Opened 2022-03-08 23:45 UTC by Elijahrane

## About the PR 
Classic traitor item that will go well with identity.
**Screenshots**

https://user-images.githubusercontent.com/60792108/157344795-6a4f406e-8c88-4bee-a696-fb57af68bd04.mp4

**Changelog**

:cl: Rane
- add: Added Agent ID cards to the uplink, a traitor item that allows you to copy accesses from other cards and change the name and job title to whatever you want.

2022-03-15 17:08 UTC, CrudeWax commented
Does the trim also change depending on the job?

2022-03-15 22:47 UTC, Elijahrane commented
No

On Tue, Mar 15, 2022, 1:09 PM CrudeWax ***@***.***> wrote:

> Does the trim also change depending on the job?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/space-wizards/space-station-14/pull/7041#issuecomment-1068237242>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOPZ2LASFUNV2LCEJRBU3I3VAC72RANCNFSM5QH5PCYQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-28 04:02 UTC, mirrorcult requested changes

2022-03-28 04:02 UTC, mirrorcult commented on Content.Server/Access/Systems/AgentIDCardSystem.cs
> +            _cardSystem.TryChangeFullName(uid, args.Name);
pass in the id card comp into the function

2022-03-28 04:02 UTC, mirrorcult commented on Content.Server/Access/Systems/AgentIDCardSystem.cs
> +            _cardSystem.TryChangeJobTitle(uid, args.Job);
pass in the id card comp

2022-03-28 04:02 UTC, mirrorcult commented on Content.Client/Access/UI/AgentIDCardWindow.xaml
> +            Title="Agent ID Card">
loc

2022-04-15 21:15 UTC, mirrorcult approved these changes

2022-04-15 21:15 UTC, merged