ID and Emag retexture + Uplink message bugfix
space-wizards/space-station-14 pull request #7102
Opened 2022-03-13 11:39 UTC by CrudeWax

## About the PR 
Minor visual fix-ups for IDs, notably removing the non-transparent white space.
Updates emag to look more like the in-game ID cards
Updates emag's flavortext to mention the cooldown.
Fixes a visual bug when inserting telecrystals into the uplink popping up a un-decoded translation string.

**Screenshots**

![image](https://user-images.githubusercontent.com/75271456/158057574-bb5cdf08-6d08-4096-90a1-21f6086775e7.png)

**Changelog**

:cl: CrudeWax
- fix: Fixed the popup for inserting TC into the uplink
- tweak: updated emag to look more like the rest of the ID cards

2022-03-13 13:05 UTC, metalgearsloth commented
Dupe https://github.com/space-wizards/space-station-14/pull/7084 ?

2022-03-13 13:22 UTC, CrudeWax commented
Old one had issues with github. This one has more content and only the needed changes.

2022-03-13 22:36 UTC, mirrorcult requested changes

2022-03-13 22:36 UTC, mirrorcult commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +  listingName: Eletromagnetic Card
why did the listing name have to be changed at all. its also misspelled

2022-03-13 22:36 UTC, mirrorcult commented on Resources/Locale/en-US/traitor/uplink/telecrystal-component.ftl
> +telecrystal-component-sucs-inserted = You slot the telecrystals into the uplink
this is the incorrect way to fix this, pass in the args properly when this is called and then do something like this

```suggestion
telecrystal-component-sucs-inserted = You slot {THE($source)} into {THE($target)}.
```

2022-03-13 22:36 UTC, mirrorcult commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +  description: The business card of the syndicate, this sequencer is able to break open airlocks and tamper with a variety of station devices. Moderate cooldown between usages.
i dont think this is even true, it just has a recharge so if you use them all up  you have to wait a bit

2022-03-13 22:36 UTC, mirrorcult commented
sprites look fine

2022-03-17 18:46 UTC, mirrorcult commented
id prefer if the listing name was not changed

2022-03-20 21:59 UTC, mirrorcult approved these changes

2022-03-20 21:59 UTC, merged