Trees and flora
space-wizards/space-station-14 pull request #7281
Opened 2022-03-25 21:09 UTC by Delete69

## About the PR 
Adds tree entities and flora decals. This is my first meaty PR, so any feedback on how I did things is welcome. I tried to understand and tweak as much as I could before I pushed it. As they stand, the trees are not constructible, indestructible, and only really intended for mapping usage to add flavor.

**Screenshots**

![decals](https://user-images.githubusercontent.com/95458399/160200884-ba94ce41-7222-4f5e-8595-07ff2ca15c85.jpg)
![trees](https://user-images.githubusercontent.com/95458399/160200891-d6e6348b-75d9-4180-8df5-8fb06ca92cf4.jpg)

**Changelog**

:cl: Delete
- add: Added trees and flora for mappers.

2022-03-26 06:02 UTC, Delete69 commented
yeah idk what a ClickTestRotatingCornerVisible is

2022-03-26 06:08 UTC, metalgearsloth commented
> yeah idk what a ClickTestRotatingCornerVisible is

You used the wrong separators

2022-03-26 06:09 UTC, metalgearsloth requested changes

2022-03-26 06:09 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Decoration/flora.yml
> +      - Impassable
Bunch duplicated with BaseTree?

2022-03-26 06:09 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Decoration/flora.yml
> +          bounds: "-0.35,-1.3,0.35,-0.5"
These should really be circle.

2022-03-26 06:09 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Decoration/flora.yml
> +    sprite: Objects\Decoration\Flora\flora_trees.rsi
Should have a placementmode to default to tile centre even if it's not anchored.

2022-03-26 19:18 UTC, Delete69 commented
> > yeah idk what a ClickTestRotatingCornerVisible is
> 
> You used the wrong separators

I really don't see where anything is wrong, I can't decipher the errors and my eye is untrained.

> Bunch duplicated with BaseTree?

I guess I'll solve this with parenting a parent?

> These should really be circle.

I started out with a circle but it wasn't as good as. Using a rectangle allowed the player sprite to get up close to the trunk, while still being able to hide behind the foliage and not have their head get covered by the trunk of the trees. Each type of tree sprite required a different shape bounds. Is a circle really something you require here?

![image](https://user-images.githubusercontent.com/95458399/160253945-12c8d7bc-4598-4e34-9bb0-4913bc0774f2.png)

> Should have a placementmode to default to tile centre even if it's not anchored.

I've used these trees in mapping for 2 weeks now, and 9 times out of 10 I wanted to PlaceFree so I removed SnapgridCenter from my yaml. Is this really required as well?

2022-03-27 06:51 UTC, metalgearsloth commented
> I really don't see where anything is wrong, I can't decipher the errors and my eye is untrained.

You used \ instead of /

> Each type of tree sprite required a different shape bounds. Is a circle really something you require here?

The bounds look like they should be wider than they are tall to me if you want to make hiding behind them more of a thing.

> I've used these trees in mapping for 2 weeks now, and 9 times out of 10 I wanted to PlaceFree so I removed SnapgridCenter from my yaml. Is this really required as well?

It's not a huge deal but as long as the tree sprite is offset then the center should be the base.

2022-03-27 21:06 UTC, Delete69 commented
I fixed up the separators, tidied up the parents. I left the bounds like they are because they are tweaked to perfection and work really keen. Theres a fine line between being able to hide behind the tree due to drawdepth and not having you're head disappear under the trunk when you stand below it. I also left out the SnapgridCenter because I believe its the right way to go for mappers.

2022-03-28 20:52 UTC, mirrorcult approved these changes
we really need decal placement sorting by tags now tbh

2022-03-28 20:53 UTC, merged