Brass Instruments
space-wizards/space-station-14 pull request #7291
Opened 2022-03-26 22:56 UTC by EmoGarbage404

## About the PR 
Added new brass instruments into the game and retextured 2 old ones.

**Screenshots**

**Changelog**

:cl: EmoGarbage
- add: Added 3 new brass instruments: the French Horn, the Euphonium, and the Tuba
- add: Added the Brass Instrument Ensemble Crate, a crate containing an assortment of brass instruments for your band to play.
- tweak: Adjusted the sprites for the Trumpet and Trombone.

2022-03-28 03:55 UTC, mirrorcult requested changes
why was the soundfont file modified?

2022-03-28 04:39 UTC, moonheart08 commented
> why was the soundfont file modified?

some of the instruments are nonstandard and do not have standard midi equivalents, namely the euphonium

2022-03-28 12:01 UTC, EmoGarbage404 commented
> why was the soundfont file modified?

What moony said. I used default midi whenever i could, just to reduce bloat, but there wasn't a default midi for euph.8

2022-04-08 21:12 UTC, mirrorcult approved these changes

2022-04-08 21:12 UTC, merged