Group ahelp relayed messages by round id
space-wizards/space-station-14 pull request #7399
Opened 2022-04-03 00:45 UTC by wrexbe

Changes the username in the ahelp relay to have the round id, and clears the cached messages when the round id changes.
R: 1234| N: UserNameHere

In theory this will make it easier to see all the messages from the same round grouped together, and should help push older messages into the past.

2022-04-03 09:17 UTC, PaulRitter requested changes

2022-04-03 09:17 UTC, PaulRitter commented on Content.Server/Administration/BwoinkSystem.cs
> +            _relayMessages.Clear();
no. why? no.

2022-04-03 09:17 UTC, PaulRitter commented on Content.Server/Administration/BwoinkSystem.cs
> +            _relayMessages.Clear();
this'll drop all unsent messages at the end of the round. why?

2022-04-03 09:19 UTC, PaulRitter requested changes
also you'd wanna add the roundid with the message to _relayMessages. rn its sending the roundid of when the message was sent to discord, not when it was sent ingame

2022-04-06 04:17 UTC, wrexbe commented
![Capture](https://user-images.githubusercontent.com/81056464/161894692-655b198c-7ea1-4be9-9118-903968d8f019.PNG)
But it works Paul, I just tried it

2022-04-13 22:30 UTC, PaulRitter commented
nvm

2022-04-13 22:31 UTC, PaulRitter approved these changes

2022-04-13 22:32 UTC, merged