Rejuvenate cures all diseases
space-wizards/space-station-14 pull request #7495
Opened 2022-04-10 23:07 UTC by Elijahrane

## About the PR 
Closes https://github.com/space-wizards/space-station-14/issues/7485

2022-04-10 23:27 UTC, Zumorica requested changes

2022-04-10 23:27 UTC, Zumorica commented on Content.Server/Disease/DiseaseSystem.cs
> +        public void CureAllDiseases(DiseaseCarrierComponent carrier)
Should follow the [conventions for public APIs in Entity Systems](https://docs.spacestation14.io/en/getting-started/conventions#public-api-method-signature).

2022-04-10 23:34 UTC, Elijahrane commented
one sec I forgot to stop bisecting

2022-04-10 23:38 UTC, Elijahrane commented
okay this is fucked now

2022-04-10 23:41 UTC, Elijahrane commented
okay now I think

2022-04-10 23:41 UTC, Zumorica requested changes

2022-04-10 23:41 UTC, Zumorica commented on Content.Server/Administration/Commands/RejuvenateCommand.cs
> +                EntitySystem.Get<DiseaseSystem>().CureAllDiseases(target);
Honestly, just keep the `TryGetComponent` and pass the result to the method. That's what resolves were intended for.

2022-04-11 10:46 UTC, Zumorica approved these changes

2022-04-11 10:46 UTC, merged