[Draft] Allows animals to resist out of inventory
space-wizards/space-station-14 pull request #7545
Opened 2022-04-13 23:24 UTC by keronshb

## About the PR 

Draft PR.  This will allow animals to resist out of inventory by moving, instead of being stuck in one forever.

**Screenshots**

**Changelog**

:cl:
- add: Animals can now escape inventory by moving

2022-04-16 04:38 UTC, ShadowCommander commented
Oh yeah. The hands thing is a hack so that we could test. The actual fix needs canMove to be blocked when a mob is inside a container, so this probably needs engine changes.

2022-04-18 10:23 UTC, ElectroJr requested changes
Other than a couple of small things the PR is generally good, But there is one significant issue: the escape system is completely agnostic about the type of container that the mouse/animal is escaping from. It should probably be restricted to containers that are either hands, inventory, or storage (i.e. backpacks and the like) related.

This issue is noticeable when you try to escape from a locked locker, because it triggers both the normal locker escape and the inventory-escape. Because the inventory escape is much faster it completes first. Maybe its fine for mice to have an easier time getting out of a locker, but its still weird that it does the double do-after. 

Another possible issue is disposals, because while moving through disposal tubes you are inside of a container. Again maybe mice should be able to escape from where, but just having no restrictions on the container is very likely going to add weird bugs at some point.

2022-04-18 20:48 UTC, keronshb commented on Content.Server/Resist/EscapeInventorySystem.cs
> +        }
What should I do in this situation then?  I'm not sure how to use a finished event without making another class and such.

2022-04-18 20:49 UTC, keronshb commented
> Other than a couple of small things the PR is generally good, But there is one significant issue: the escape system is completely agnostic about the type of container that the mouse/animal is escaping from. It should probably be restricted to containers that are either hands, inventory, or storage (i.e. backpacks and the like) related.
> 
> This issue is noticeable when you try to escape from a locked locker, because it triggers both the normal locker escape and the inventory-escape. Because the inventory escape is much faster it completes first. Maybe its fine for mice to have an easier time getting out of a locker, but its still weird that it does the double do-after.
> 
> Another possible issue is disposals, because while moving through disposal tubes you are inside of a container. Again maybe mice should be able to escape from where, but just having no restrictions on the container is very likely going to add weird bugs at some point.

How do I specify if they're in certain containers?

2022-04-18 20:49 UTC, keronshb commented on Content.Server/Resist/EscapeInventorySystem.cs
> +    }
Like the above, how do I go about it without making another class if I don't need to put the user in there?

2022-04-18 20:52 UTC, keronshb commented on Content.Server/Resist/EscapeInventorySystem.cs
> +            {
Done

2022-04-18 21:15 UTC, keronshb commented on Resources/Locale/en-US/resist/components/escape-inventory-component.ftl
> +escape-inventory-component-start-resisting = You start struggling to escape!
I made an attempt but I'm not sure if it works.

2022-04-18 21:22 UTC, keronshb commented on Content.Server/Resist/EscapeInventorySystem.cs
> +    }
I put a cancellation event in, but I'm not sure how to do it another way.

2022-04-20 06:17 UTC, ElectroJr commented on Resources/Locale/en-US/resist/components/escape-inventory-component.ftl
> +escape-inventory-component-start-resisting = You start struggling to escape!
You need to also add a `escape-inventory-component-start-resisting-target` entry to the .ftl file

2022-04-20 06:20 UTC, ElectroJr commented on Content.Server/Resist/EscapeInventorySystem.cs
> +    }
You just need a separate class for each event. But neither event needs the user. I.e., just:
```cs
 private sealed class EscapeDoAfterComplete : EntityEventArgs { }
 private sealed class EscapeDoAfterCancel : EntityEventArgs { }
```
would work.

2022-04-20 06:20 UTC, ElectroJr commented on Content.Server/Resist/EscapeInventorySystem.cs
> +        }
you still need the class, you just don't need the event to take in a user.

2022-04-20 06:30 UTC, ElectroJr commented
> How do I specify if they're in certain containers?

The rigorous way of doing that would be to make sure that each system provides a function to check if a given entity is contained within one of the containers that belong to some component.

But the easier solution is to just fudge it and assume that if the parent/container entity has either a `SharedStorageComponent`, `InventoryComponent`, or `SharedHandsComponent`, then the mouse is **probably** in one of those containers. So I guess just adding some HasComp<> checks to look for those components on the container entity before escaping should probably be good enough.

2022-04-20 19:20 UTC, keronshb commented on Resources/Locale/en-US/resist/components/escape-inventory-component.ftl
> +escape-inventory-component-start-resisting = You start struggling to escape!
Oops for some reason I thought I had already done this.  Should be on this push.

2022-04-20 19:21 UTC, keronshb commented on Content.Server/Resist/EscapeInventorySystem.cs
> +    }
Thanks!  Should be changed now.

2022-04-20 19:21 UTC, keronshb commented on Content.Server/Resist/EscapeInventorySystem.cs
> +        }
I got it now.  Should be fixed.  Just so I know, what would be a scenario where I would need to pass stuff into a class like that?

2022-04-21 10:01 UTC, ShadowCommander reviewed
Just minor formatting things left. Looks good otherwise!

2022-04-21 15:25 UTC, keronshb commented on Content.Client/Entry/IgnoredComponents.cs
> +            "CanEscapeInventory"
Fixed

2022-04-21 15:25 UTC, keronshb commented on Content.Server/Resist/EscapeInventorySystem.cs
> +            if(HasComp<SharedStorageComponent>(container.Owner) || HasComp<InventoryComponent>(container.Owner) || HasComp<SharedHandsComponent>(container.Owner))
Fixed but since this was also combined I guess it's moot.

2022-04-21 15:25 UTC, keronshb commented on Content.Server/Resist/EscapeInventorySystem.cs
> +    }
I think I did this right, I tested and it works.

2022-04-21 16:19 UTC, ShadowCommander approved these changes

2022-05-09 01:33 UTC, keronshb commented
Is there anything else I need to do for this?

2022-05-11 07:14 UTC, ShadowCommander commented
Was this only for mouse? It's only on the mouse right now. Other than that it should be good to merge.

2022-05-12 07:58 UTC, merged