Adds suppermatter
space-wizards/space-station-14 pull request #7633
Opened 2022-04-18 15:29 UTC by PJB3005

:cl:
- add: Added suppermatter. Goes great with a glass of syndicate bomb!
- remove: Removed fun!

![image](https://user-images.githubusercontent.com/8107459/163831657-b26af202-4e80-4adc-af38-5a78cb082982.png)

Original item from /vg/, but I made the sprites myself by cutting up the TG's SM sprite because the /vg/ one is pretty awful.

2022-04-18 15:31 UTC, PJB3005 commented
I spent like 20 minutes debugging why the microwave wouldn't work just to make this.

2022-04-18 15:38 UTC, PJB3005 commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +    trash: ""
Yaml linter is broken and says this line is bad but it's totally fine.

2022-04-19 03:12 UTC, Mirino97 commented
I read this as you adding the SM engine.

DAM YOU PJB, YA'VE BLUE BALL'D ME!!

2022-04-19 13:58 UTC, moonheart08 requested changes

2022-04-24 00:38 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +    energy: 1.4
consider that its funny

2022-04-24 01:07 UTC, moonheart08 commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +    energy: 1.4
> consider that its funny

rn due to robust being weird, exceeding the light limit causes nasty artifacting that's really hard on people's eyes.

2022-05-12 08:50 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
> +    energy: 1.4
pjb issue.

2022-05-12 09:44 UTC, merged