Familiars respawn
space-wizards/space-station-14 pull request #7640
Opened 2022-04-18 22:01 UTC by Elijahrane

## About the PR 
As suggested during the discussion yesterday about people griefing the chaplain, familiars respawn now, which makes random deaths to atmos or griefers a bit less devastating to their round. 3 minutes for Remilia, 5 minutes for Cerberus.

**Changelog**

:cl: Rane
- add: The chaplain's familiars can be resummoned now after they die. 3 minutes for Remilia, 5 minutes for Cerberus.

2022-04-19 06:04 UTC, metalgearsloth requested changes

2022-04-19 06:04 UTC, metalgearsloth commented on Content.Server/Bible/BibleSystem.cs
> +            foreach (var (summonableComp, respawning) in EntityQuery<SummonableComponent, SummonableRespawningComponent>())
Least common component first.

2022-04-19 06:04 UTC, metalgearsloth commented on Content.Server/Bible/BibleSystem.cs
> +                RemComp<SummonableRespawningComponent>(summonableComp.Owner);
Isn't this going to have collection modified issues doing it in the loop.

2022-04-19 06:04 UTC, metalgearsloth commented on Content.Server/Bible/Components/SummonableComponent.cs
> +        public float Accumulator = 0f;
Needs to be a datafield to be serialized correctly.

2022-04-19 06:04 UTC, metalgearsloth commented on Content.Server/Bible/BibleSystem.cs
> +                AddComp<SummonableRespawningComponent>(summonable.Owner);
Should this be EnsureComp instead.

2022-04-19 14:33 UTC, Elijahrane commented
Very slightly out of scope but I made all the other accumulators in components datafields too while I was at it

2022-04-24 00:39 UTC, mirrorcult approved these changes

2022-04-24 00:39 UTC, mirrorcult commented on Content.Server/Bible/BibleSystem.cs
> +                var familiarComp = AddComp<FamiliarComponent>(familiar);
```suggestion
                var familiarComp = EnsureComp<FamiliarComponent>(familiar);
```

2022-04-24 01:44 UTC, Elijahrane commented
Reviews addressed

2022-04-24 02:27 UTC, merged