Add a syndicate stamp
space-wizards/space-station-14 pull request #7649
Opened 2022-04-19 14:34 UTC by Veritius

## About the PR 
Adds a syndicate stamp that can be bought from the uplink. Useful for making sure Command knows that the ransom letter is not a prank.

**Changelog**

:cl:
- add: Add a Syndicate Stamp to the uplink

2022-04-19 15:33 UTC, Fishfish458 commented
I can try to throw together something for a custom stamp, a red S or something

2022-04-20 01:30 UTC, moonheart08 commented
Should have a unique icon.

2022-04-20 08:01 UTC, Veritius commented
stamp probably needs a unique texture to differentiate it from the nanotrasen-issued ones but I am not a good artist so
when you draw it

2022-04-23 23:55 UTC, mirrorcult approved these changes

2022-04-23 23:55 UTC, mirrorcult requested changes

2022-04-23 23:55 UTC, mirrorcult commented on Resources/Textures/Objects/Misc/bureaucracy.rsi/note.txt
> +TODO: Someone needs to split this up at some point. This RSI is a mess.
just make a github issue dont add random txt files

2022-04-24 00:00 UTC, mirrorcult approved these changes

2022-04-24 00:00 UTC, merged