Added a chemical that makes an entity sentient and a ghost role
space-wizards/space-station-14 pull request #7666
Opened 2022-04-20 11:34 UTC by areitpog

## About the PR
Adds a chemical which makes an entity sentient; it also has a very complicated recipe

**Screenshots**
https://user-images.githubusercontent.com/77842470/164220889-bcec129c-d72d-4dde-bc5f-14a71a5f08c1.mp4

**Changelog**

:cl: areit
- add: Added a chemical which is able to turn an entity sentient!

2022-04-24 00:25 UTC, mirrorcult requested changes

2022-04-24 00:25 UTC, mirrorcult commented on Resources/Prototypes/Recipes/Reactions/medicine.yml
> +      amount: 1
this need to be harder to make in the sense that its ingredients are hard to acquire, preferably requiring some chemicals that can only be acquired in salvage (or nocturine?), not just by having a lot of ingredients

2022-04-24 00:25 UTC, mirrorcult commented on Resources/Prototypes/Recipes/Reactions/medicine.yml
> +      amount: 1
if you dont want to do that in this PR then imo the recipe should be removed until that can be added

2022-04-25 14:56 UTC, UKNOWH commented
looks good , maybe some round I can use it to field a massive monkey army.

2022-05-12 08:52 UTC, metalgearsloth commented
Ping for re-open when you get a chance to work on it.

2022-05-12 08:52 UTC, closed without merging