Drains
space-wizards/space-station-14 pull request #7678
Opened 2022-04-20 20:38 UTC by Elijahrane

## About the PR 
Closes https://github.com/space-wizards/space-station-14/issues/6814.
Currently placable by mappers only, the obstruction check is a bit too CBT until collision group rework.
**Screenshots**

https://user-images.githubusercontent.com/60792108/164318676-d7edf090-280f-4b83-b9b2-63e1381f1ed4.mp4

**Changelog**

:cl: Rane
- add: Drains will soon be added to stations, making the jobs of Janitors, Chefs, and Chemists much easier.

2022-04-21 09:52 UTC, Peptide90 commented
Presumably you can empty drains with a bucket to collect all those sweet sweet reagents?

2022-04-21 10:41 UTC, UKNOWH commented
will you be able to left click the drain to get rid of chems? That will be so useful

2022-04-22 01:41 UTC, Elijahrane commented
> Presumably you can empty drains with a bucket to collect all those sweet sweet reagents? Gives Janitor something to do going round unblocking drains.

You empty buckets into drains not the other way around

> will you be able to left click the drain to get rid of chems? That will be so useful

It goes into the abyss at a rate of 3u / second (until we get plumbing???)

2022-04-22 12:19 UTC, Peptide90 commented
> > Presumably you can empty drains with a bucket to collect all those sweet sweet reagents? Gives Janitor something to do going round unblocking drains.
> 
> You empty buckets into drains not the other way around
> 
> > will you be able to left click the drain to get rid of chems? That will be so useful
> 
> It goes into the abyss at a rate of 3u / second (until we get plumbing???)

I get the logic but seems counter. Until we get plumbing perhaps it should function as a bucket in the floor that needs periodically emptied (I don't see plumbing coming on the horizon and would be a good way to harvest chems I guess).

2022-04-22 14:00 UTC, ShadowCommander commented
> I get the logic but seems counter. Until we get plumbing perhaps it should function as a bucket in the floor that needs periodically emptied (I don't see plumbing coming on the horizon and would be a good way to harvest chems I guess).

Isn't the point of the drain to delete reagents?

2022-04-22 14:03 UTC, Peptide90 commented
> > I get the logic but seems counter. Until we get plumbing perhaps it should function as a bucket in the floor that needs periodically emptied (I don't see plumbing coming on the horizon and would be a good way to harvest chems I guess).
> 
> 
> 
> Isn't the point of the drain to delete reagents?
> 
> 
> 
> Otherwise we need a super drain so that the janitor can dump reagents into that to delete them.

I thought it was to get rid of puddles of reagents? I mean go for it as is if deleting is what y'all want. I can see it working either way.

2022-04-24 00:43 UTC, mirrorcult commented
i don't super like that it deletes reagents but i get why it exists, might need to be made slower though

2022-04-24 00:47 UTC, mirrorcult requested changes
is it easy to make mop buckets spillable in this same PR?

2022-04-24 00:47 UTC, mirrorcult commented on Content.Server/Fluids/Components/DrainComponent.cs
> +        public float UnitsDestroyedPerSecond = 3f;
datafield? also i think this should be 1 or 2u

2022-04-24 00:47 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
> +    - type: Drain
this should have a drainable solution so people can pull out of it with syringes or buckets or smth

2022-04-24 00:47 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
> +    mode: SnapgridCenter
this should be parented to basestructure or smth right? if not, needs to be transform anchored

2022-04-24 00:47 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
> +      volume: -10
not sure how it works in game but i'd be fine with it being a little loud since its a drain

2022-04-24 01:03 UTC, Elijahrane commented
Reviews addressed

2022-04-24 01:04 UTC, mirrorcult commented on Content.Server/Fluids/Components/DrainComponent.cs
> +        [DataField("UnitsDestroyedPerSecond")]
```suggestion
        [DataField("unitsDestroyedPerSecond")]
```

2022-04-24 01:04 UTC, mirrorcult approved these changes

2022-04-24 01:04 UTC, merged