Adds the clown bomb
space-wizards/space-station-14 pull request #7683
Opened 2022-04-21 07:27 UTC by Veritius

## About the PR
Adds the clown bomb, a bomb that spawns 50 clowns on detonation. All clowns are hostile, but do 0 damage and make the honk noise when they attack. This is an admeme item, for obvious reasons.

**Screenshots**
![image](https://user-images.githubusercontent.com/45957058/164398873-711ca30e-29cf-43ee-a25d-a8af70ba074f.png)

**Changelog**

:cl:
- add: Adds the Clown Bomb, an admeme item.

2022-04-25 12:24 UTC, metalgearsloth commented
> Every single clown that ClusterBombSystem tries to spawn gives a warning (as you can't throw a KinematicController.) As an admeme item, this is tolerable, but if it's ever going to be made user accessible in normal rounds, that'll have to be fixed.

Need to do what atmos does and overwrite it temporarily (wyci).

2022-05-05 02:58 UTC, metalgearsloth requested changes

2022-05-05 02:58 UTC, metalgearsloth commented on Resources/Prototypes/Entities/Objects/Weapons/Throwable/grenades.yml
> +      maxGrenadesCount: 20
this is WAY too many clowns, this is like 300 ents getting spawned in. 5 max.

2022-05-05 02:58 UTC, metalgearsloth commented on Content.Server/Explosion/Components/ClusterGrenadeComponent.cs
> +        public bool UsePhysics = false;
Property doesn't seem to do anything as they don't get launched anyway. Better off just having them actually throw? Just use a timer on the system to accumulate when to stop making them dynamic bodytypes and make them KC again.

2022-05-12 10:14 UTC, metalgearsloth requested changes
Still lagging my game real hard and not yeeting when I just tried it.

2022-05-12 23:10 UTC, Veritius commented
Yeah I dunno why the yeeting isn't working. I was a bit busy on making the flavor text pr so I wasn't working on this. I'll just mark it as draft until I fix that.

2022-06-01 23:08 UTC, Veritius commented
kinda given up on this one, just tag it with Derelict or smth

2022-06-01 23:08 UTC, closed without merging