Fixes thirst not applying speed debuffs properly , Makes Thirst a server-side component only
space-wizards/space-station-14 pull request #7767
Opened 2022-04-25 00:14 UTC by MLGTASTICa

## About the PR 
All logic functionality removed from ThirstComponent and moved to ThirstSystem
Thirst damage no longer scales with frametime, since frames are calculated by the second
Removed client-side and shared ThirstComponents , since they provided no functionality(and there was no reason to send network updates for thirst anyway)

**Screenshots**

**Changelog**

:cl: SPCR
- fix : Fixed being extremly thirsty not applying its slowdown properly

2022-04-26 15:03 UTC, metalgearsloth requested changes
All of the systems need caching as dependencies, same with logger sawmill.

2022-04-26 15:03 UTC, metalgearsloth commented on Content.Server/Nutrition/EntitySystems/ThirstSystem.cs
> +            float mod = component.CurrentThirstThreshold == ThirstThreshold.Parched ? 0.75f : 1.0f;
Should also check for dead.

2022-04-26 16:41 UTC, MLGTASTICa commented on Content.Server/Nutrition/EntitySystems/ThirstSystem.cs
> +        [Dependency] private readonly IEntityManager _entMan = default!;
Fixed

2022-04-28 12:26 UTC, metalgearsloth commented on Content.Server/Nutrition/EntitySystems/ThirstSystem.cs
> +            float mod = component.CurrentThirstThreshold == ThirstThreshold.Parched ? 0.75f : 1.0f;
I meant the threshold

2022-04-28 12:43 UTC, metalgearsloth commented on Content.Server/Nutrition/Components/ThirstComponent.cs
> +        OverHydrated = 1 << 3,
Mainly so rider doesn't yell at me when I (A | B)

2022-05-09 05:50 UTC, merged