Fix decals (finally)
space-wizards/space-station-14 pull request #7771
Opened 2022-04-25 11:29 UTC by metalgearsloth

:cl:
- fix: Decals (e.g. tile paint) should now be removed correctly.

@PaulRitter 

Originally I had it as separate messages but the subscriptions seemed to be done out of order so this way just guarantees the decals get cleaned up for the overlay.

2022-04-25 14:47 UTC, moonheart08 approved these changes

2022-04-26 17:11 UTC, PaulRitter requested changes
quickly read, small notes, i gotta pull apart this code someday

2022-04-26 17:11 UTC, PaulRitter commented on Content.Server/Decals/DecalSystem.cs
> +                DirtyChunk(gridId, chunkIndices);
removedecal already dirties the chunk

2022-04-26 17:11 UTC, PaulRitter commented on Content.Client/Decals/DecalSystem.cs
> +            ChunkIndex[gridId].Remove(uid);
this is already done through removedecalinternal which should be called as opposed to this but ig it should be fine?

2022-04-28 10:23 UTC, merged