Rainbow crayon + color-selectable crayons
space-wizards/space-station-14 pull request #7786
Opened 2022-04-25 23:23 UTC by vulppine

## About the PR 

Adds the rainbow crayon - which, in turn, adds the ability to have color selectable crayons. The rainbow crayon comes with 30 charges, instead of the regular 5 found in regular crayons.

**Screenshots**

![image](https://user-images.githubusercontent.com/76629141/165190234-1a63cd22-d1a1-4316-99b3-ac1dde9ac292.png)

**Changelog**

:cl:
- add: Adds the rainbow crayon. Honk!

2022-04-27 07:40 UTC, PaulRitter requested changes
empty file on client `Content.Client/Crayon/CrayonDecalVisualizer.cs`

god the colorfield on crayoncomp should just be typed color, suppose i'll go fix that soon

2022-04-27 07:40 UTC, PaulRitter commented on Content.Server/Crayon/CrayonSystem.cs
>          Dirty(component);
only dirty if you actually change the color

2022-04-27 23:39 UTC, vulppine commented
> empty file on client `Content.Client/Crayon/CrayonDecalVisualizer.cs`
> 
> god the colorfield on crayoncomp should just be typed color, suppose i'll go fix that soon

already deleted in this PR, and yeah, i was wondering why the color field on crayons was a string

2022-04-28 07:58 UTC, PaulRitter commented
> already deleted in this PR

its still there

> yeah, i was wondering why the color field on crayons was a string

previous crimes against humanity

2022-04-28 07:59 UTC, vulppine commented
> > already deleted in this PR
> 
> its still there
> 
> > yeah, i was wondering why the color field on crayons was a string
> 
> previous crimes against humanity

![image](https://user-images.githubusercontent.com/76629141/165705710-9faf5687-4670-45ce-bfb1-7a7dadadfd0d.png)

buh

2022-04-28 12:23 UTC, merged