Dumpable component to use a doafter to empty storage into a disposal unit, placeable surface, or the ground
space-wizards/space-station-14 pull request #7792
Opened 2022-04-26 02:34 UTC by Elijahrane

## About the PR 
Janitors and botanists rejoice.

**Changelog**

:cl: Rane
- add: The trash bag and plant bag can now be directly emptied into disposal units, onto tables, or on the ground with an alternative verb.

2022-04-26 02:43 UTC, mirrorcult commented
the 'into a disposal unit/surface' part can probably use a utility verb. in fact i thought a utility verb already existed for this

2022-04-26 03:28 UTC, Elijahrane commented
Added utility verbs

2022-05-04 02:46 UTC, mirrorcult requested changes

2022-05-04 02:46 UTC, mirrorcult commented on Content.Server/Storage/EntitySystems/DumpableSystem.cs
> +            public DumpableComponent Dumpable { get; }
dont store components on these events, idk if its even used

2022-05-04 02:53 UTC, Elijahrane commented
Fixed conflicts and addressed review

2022-05-04 02:54 UTC, mirrorcult commented
you have added a 30 thousand line [mono_crash.2536d94da2.0.json](https://github.com/space-wizards/space-station-14/pull/7792/commits/94b8cac12012e1d27b175aecff1c41300f9262b5#diff-a9182f7b0d3ddfc558e81cc8d20fe6b6599235c68d9797940a27ceed5639866a)

2022-05-04 02:55 UTC, Elijahrane commented
gotta get my loc metrics up

2022-05-04 03:00 UTC, mirrorcult approved these changes

2022-05-04 03:00 UTC, merged