Adds the pressure medipen and adds the emergency suit to emergency lockers
space-wizards/space-station-14 pull request #7880
Opened 2022-04-30 12:06 UTC by juliangiebel

## About the PR 
This PR adds a new medicine: barozine, the pressure medipen and it adds the emergency suit to emergency lockers with a probability of 50% (I testet it, probabilities are scuffed. Flare guns, which are 5%, are sometimes more common than the suit).

Barozine prevents pressure damage but causes jittering, screaming, stuttering and a bit of poison damage. Overdosing on it causes more poison damage. There is no recipe for it rn. This should probably be found on salvage wrecks imo.

Leporazine also got buffed as the values it had did **nothing** to prevent your body temperature from plummeting below the damage threshold.

The pressure medipen got added to survival boxes. It contains 10u of leporazine and 10u of barozine.

Without injecting yourself with either barozine or leporazine you still crit in 12 seconds when spaced.
If you inject yourself with the pressure medipen you crit in roughly 30 second which gets significantly less the longer you take to inject yourself.

If you manage to find an emergency suit before your dose of leporazine runs out you're safe for a few minutes. (The suit has only weak temperature protection).

If your body temperature dropped below the damage threshold before you manage to get into **any** suit you die anyway without injecting yourself with leporazine as it can't rise fast enough.

All in all this gives players a chance to survive depressurization without making it significantly less deadly.
**Changelog**
:cl:
- add: Added a new medipen variant to survival boxes that buys you some time when you get spaced.
- tweak: Some emergency lockers now contain an emergency suit.

2022-05-02 22:39 UTC, mirrorcult commented
conflicts

2022-05-02 22:41 UTC, mirrorcult requested changes
all good in concept, just nitpicks

2022-05-02 22:41 UTC, mirrorcult commented on Content.Server/Atmos/EntitySystems/BarotraumaSystem.cs
> +        }
this should probably alsao have a flat modifier in case the pressure is 0

2022-05-02 22:41 UTC, mirrorcult commented on Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml
> +  name: pressure medipen
should maybe be something like 'space medipen' since it also has leporazine?

2022-05-05 22:03 UTC, juliangiebel commented
This should be ready to be merged now

2022-05-06 21:43 UTC, mirrorcult approved these changes

2022-05-06 21:44 UTC, merged