New Medium Salvage Map- Cultist Vault
space-wizards/space-station-14 pull request #7967
Opened 2022-05-06 04:31 UTC by 5150Con

## About the PR 
This is my attempt at contributing a new salvage map to the community, I wanted to add some more themed salvages to the list, and this it it.

The salvage contains;

Persistent items:
1x Uranium Gen
1x Substation
1x Space drugs
1x Devil's Kiss drink
1x RGB plushie
1x Nar 'Sie plushie
Various floor cables
Various Cultist clothing

Spawners:
2x Salvage Mob 
1x Space Tick 
1x Space Bear 
1x Alien artifact
2x Salvage Material crate

I think this would be great because there isn't a similar salvage like it, and it has some power gen options for Salvage/Engi/Cargo. I tried to make it so that Salvage will need to construct a button/lever to open the vault, so it should involve a little more then loot and leave.

**Screenshots**
![20220505220421_1](https://user-images.githubusercontent.com/104950325/167066881-5aea09e7-e282-4d4e-9dae-ba539ca10ab3.jpg)

![20220505223109_1](https://user-images.githubusercontent.com/104950325/167067385-4224ad35-f8df-4e66-89d2-526dc6dcf3ce.jpg)

:cl:
- add: New Medium Salvage Map

2022-05-13 19:03 UTC, mirrorcult requested changes

2022-05-13 19:03 UTC, mirrorcult commented on Content.MapRenderer/Program.cs
> +        private const string MapsAddedEnvKey = MyStation.yml ;
revert this change

2022-05-13 19:03 UTC, mirrorcult commented
i believe the actual size here is 6.5? not 10.5

2022-05-13 19:03 UTC, mirrorcult commented
or its 8, actually, cant count

2022-05-13 19:09 UTC, mirrorcult commented
actual salvage is good btw

2022-05-13 19:47 UTC, 5150Con commented on Content.MapRenderer/Program.cs
> +        private const string MapsAddedEnvKey = MyStation.yml ;
I  have done so.

2022-05-13 19:50 UTC, 5150Con commented
> or its 8, actually, cant count

I switched it to 8, I am not 100% sure on how to measure, as I just did furthest tile in one direction and put that

2022-05-17 18:08 UTC, mirrorcult requested changes

2022-05-17 18:08 UTC, mirrorcult commented on Resources/Prototypes/Maps/salvage.yml
> +  mapPath: /Maps/Salvage/medium-cult-vault.yml
this isnt the correct path? you have it as `Med-Cult-Vault.yml`

2022-06-05 00:17 UTC, closed without merging