Various Entities make sounds when speaking
space-wizards/space-station-14 pull request #7980
Opened 2022-05-07 02:54 UTC by hubismal

## About the PR 
Functionality has been added for entities to make noises when talking, a la Goonstation and some other branches of SS13. A few creatures (including players) have been given this feature as a proof of concept.

The sounds used for humans are from goonstation. Mice now play their squeak sound when talking as well. Vending machines also play a little four note jingle I whipped up because it seemed lame to have them be quiet. Drones, monkeys, and other mobs still need sounds, but this should be very straightforward to do and I'd rather not unnecessarily bloat this PR.

SharedSpeechComponent, which previously had one job and failed to do it (all entities can speak regardless of whether they had one, fixing this is outside the scope of this PR) now also has the ability to play sounds from a SpeechSoundsPrototype that it caches. SpeechSoundsPrototype is a 3 SoundSpecifiers for saying, asking, and exclaiming. SpeechNoiseSystem plays one of these sounds when players talk depending on what punctuation character a message ends with.

Players cannot yet choose what voice/speechsounds they have although the prototypes are there. I will save this for a future PR.

This is my largest PR, and I experimented with some things, so there may be some oddities.
**Screenshots**

https://user-images.githubusercontent.com/47284081/167234909-30e39811-8d9e-40cc-a72c-79c7907a842a.mp4

**Changelog**

:cl:
- add: Humans, mice, and vending machines make noise when they talk.

2022-05-07 03:15 UTC, EmoGarbage404 commented
Very cool pr, am eagerly waiting for review.

2022-05-07 03:54 UTC, moonheart08 requested changes
NOT A FULL REVIEW, but **all** added sounds need license information. Add a LICENSE file in their respective folder(s) with a link to the commit you obtained it from if any + the asset's license, with credit to the author.

2022-05-07 04:16 UTC, metalgearsloth requested changes
Please don't mix tabs and spaces; in your IDE it may look okay but it looks bad elsewhere. t-stalker also mentioned that stuff like mice that spam might blast your eardrums so there should be some kind of minimum cooldown for it, e.g. 0.5s

You also committed RobustToolbox.

I didn't review the code but it looked a bit sussy.

2022-05-07 04:36 UTC, hubismal commented
> NOT A FULL REVIEW, but **all** added sounds need license information. Add a LICENSE file in their respective folder(s) with a link to the commit you obtained it from if any + the asset's license, with credit to the author.
What's missing a license file here? is license.txt in the voices folder inadequate somehow?

2022-05-07 04:37 UTC, metalgearsloth commented
> > NOT A FULL REVIEW, but **all** added sounds need license information. Add a LICENSE file in their respective folder(s) with a link to the commit you obtained it from if any + the asset's license, with credit to the author.
> 
> What's missing a license file here? is license.txt in the voices folder inadequate somehow?

Goon assets are NC which isn't specified; it just has the copyright but not the license.

2022-05-08 09:33 UTC, metalgearsloth commented
Where'd you get vending_jingle.ogg from? I already fixed the rest.

2022-05-08 09:34 UTC, Emisse commented
i want to sound like an animal crossing character

2022-05-08 09:37 UTC, metalgearsloth commented
> i want to sound like an animal crossing character

Might get annoying with lots of people on server but not hard to do; afaik they just play a sound for each letter very quickly.

2022-05-08 09:38 UTC, metalgearsloth commented
@hubismal also you have maintainer pushes off so Im gonna have to leave a bunch of comments for cleanup.

2022-05-08 13:05 UTC, hubismal commented
> Where'd you get vending_jingle.ogg from? I already fixed the rest.

I made a subsynth in zynaddsubfx with a decent amount of release and  then overdrove it and filter curved it in audacity. I couldn't find a vending machine jingle from any other branch of SS13

2022-05-08 13:23 UTC, merged