Syndie Commander and Syndie Elite Armors
space-wizards/space-station-14 pull request #8003
Opened 2022-05-08 02:16 UTC by Emisse

syndie commander is needed for nukies; syndie elite is being added to uplink at a greater cost than the normal blood red. features similar stats to 13

![image](https://user-images.githubusercontent.com/99158783/167278864-b3edd0b8-adba-4ca6-b6cd-91852831099f.png)

2022-05-08 07:46 UTC, mirrorcult requested changes
should add starting gear for these so they can actually be spawned in later

2022-05-08 07:46 UTC, mirrorcult commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +
shouldn't be in the uplink IMO

2022-05-08 09:28 UTC, Emisse commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +
will do

2022-05-12 12:09 UTC, metalgearsloth commented on Resources/Textures/Clothing/Head/Hardsuits/syndiecommander.rsi/meta.json
> +  "copyright": "Taken from vg at commithttps://github.com/vgstation-coders/vgstation13/commit/a16e41020a93479e9a7e2af343b1b74f7f2a61bd",
```suggestion
  "copyright": "Taken from vg at commit https://github.com/vgstation-coders/vgstation13/commit/a16e41020a93479e9a7e2af343b1b74f7f2a61bd",

```

2022-05-12 12:10 UTC, metalgearsloth commented on Resources/Textures/Clothing/Head/Hardsuits/syndieelite.rsi/meta.json
> +  "copyright": "Taken from vg at commithttps://github.com/vgstation-coders/vgstation13/commit/a16e41020a93479e9a7e2af343b1b74f7f2a61bd",
```suggestion
  "copyright": "Taken from vg at commit https://github.com/vgstation-coders/vgstation13/commit/a16e41020a93479e9a7e2af343b1b74f7f2a61bd",

```

2022-05-12 12:37 UTC, merged