Flavor text
space-wizards/space-station-14 pull request #8070
Opened 2022-05-10 05:39 UTC by Veritius

## About the PR 
Adds Flavor Text / Character Descriptions. Now you can describe every wrinkle in your character's face... as long as you stay within 512 characters, that is. Flavor text is visible in-game as an examine verb.

For #7809

**Screenshots**

![image](https://user-images.githubusercontent.com/45957058/167551993-bada75a7-4bfc-4758-9512-aea350d1dec5.png)
![image](https://user-images.githubusercontent.com/45957058/167552489-95b122bd-0c94-4c31-a0b5-3ba0ac790f38.png)
Admins can also add formatting in VV
![image](https://user-images.githubusercontent.com/45957058/167554570-51e3b766-b7ac-46c4-8bbe-1f65699f4bea.png)

**Changelog**

:cl:
- add: Added character descriptions.

2022-05-10 07:17 UTC, UKNOWH commented
pog

2022-05-10 20:33 UTC, ike709 commented
This needs to be a config option. A lot of MRP SS13 servers think flavortext adds more cringe than value, and for good reason.

2022-05-11 08:10 UTC, Veritius commented
Oh, probably should have mentioned. It's a CVar now.

2022-05-12 22:44 UTC, Veritius commented on Content.Server.Database/Migrations/Sqlite/SqliteServerDbContextModelSnapshot.cs
> +                    b.Property<byte[]>("Markings")
Yeah, I dunno what this was about. It's kinda suspicious, but it's auto-generated by dotnet migrations, so I'm terrified of touching it.

2022-05-12 22:48 UTC, Veritius commented on Content.Server.Database/Migrations/Sqlite/SqliteServerDbContextModelSnapshot.cs
> +                    b.Property<byte[]>("Markings")
@vulppine Since you're the author of the Markings pr, mind having a look at this?

2022-05-12 23:57 UTC, metalgearsloth commented on Content.Server.Database/Migrations/Sqlite/SqliteServerDbContextModelSnapshot.cs
> +                    b.Property<byte[]>("Markings")
I pinged him on discord and there's probably something sussy that happened when they were fixing up markings PR so just revert this for now.

2022-05-13 06:52 UTC, mirrorcult requested changes

2022-05-13 06:52 UTC, mirrorcult commented on Content.Client/FlavorText/FlavorText.xaml.cs
> +        public LineEdit FlavorTextInput => CFlavorTextInput;
you can set access in XAML

```xaml
    <LineEdit Name="FlavorTextInput" Access="Public" MinSize="220 0" HorizontalExpand="True" />
```

then access it normally

2022-05-13 06:52 UTC, mirrorcult commented on Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
> +            if (_configurationManager.GetCVar<bool>("ic.flavor_text"))
```suggestion
            if (_configurationManager.GetCVar(CCVars.FlavorText))
```

dont access them by name

2022-05-13 06:52 UTC, mirrorcult commented on Content.Server/FlavorText/FlavorTextComponent.cs
> +    public sealed class FlavorTextComponent : Component
this is mostly a semantics thing but i think this should be something like `DetailedDescriptionComponent` so we can use it for other stuff that isnt necessarily flavor text

2022-05-13 07:19 UTC, Veritius commented on Content.Server/FlavorText/FlavorTextSystem.cs
> +    public sealed class DetailedExaminableSystem : EntitySystem
woops that wasn't supposed to get in yet

2022-05-13 19:00 UTC, mirrorcult commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("ic.flavor_text", true, CVar.SERVER | CVar.REPLICATED);
we should default this to off IMHO. not sure we want this on LRP, when we get a MRP server we can turn it on

2022-05-13 22:58 UTC, mirrorcult approved these changes

2022-05-13 22:58 UTC, merged