Maid outfit for janidrobe
space-wizards/space-station-14 pull request #8071
Opened 2022-05-10 08:23 UTC by Emisse

look me in the eyes and tell me you dont want this
![image](https://user-images.githubusercontent.com/99158783/167583414-ee8ad5b3-b966-460d-a924-5f1c921d40e8.png)

2022-05-10 08:23 UTC, vulppine commented
just add an entire maid uniform and stuff it into contraband 😎

2022-05-10 08:24 UTC, Emisse commented
based idea

2022-05-10 11:52 UTC, Snowyypanda commented
the tg maid outfit looks much better imo

2022-05-10 23:33 UTC, Elijahrane commented
> the tg maid outfit looks much better imo

this literally is the /tg/ janitor maid outfit

2022-05-12 23:50 UTC, mirrorcult requested changes

2022-05-12 23:50 UTC, mirrorcult commented on Resources/Prototypes/Entities/Clothing/Shoes/specific.yml
> +    enabled: false
not enabled?

2022-05-13 00:13 UTC, Emisse commented on Resources/Prototypes/Entities/Clothing/Shoes/specific.yml
> +    enabled: false
it sit absoneobfeon efroer renanbled

2022-05-23 11:19 UTC, merged