Adds space ambience
space-wizards/space-station-14 pull request #8096
Opened 2022-05-11 02:46 UTC by ike709

## About the PR 
Adds space ambience. It's like station ambience but not an annoying perpetual humming sound. The two songs are from the BeeStation OST and can be found here (credit to qwerty for both):
- Starlight: https://www.youtube.com/watch?v=XTfPEFfmhrA
- Constellations: https://www.youtube.com/watch?v=ufwRj1LI3aw

**Screenshots**

https://user-images.githubusercontent.com/5714543/167758479-8d098184-45eb-4af8-bf54-63c80058e1b4.mp4

**Changelog**

:cl:
- add: Added space ambience, with two songs. Go throw yourself out into space a few times.
- add: Added audio settings to disable station ambience and/or space ambience.

2022-05-11 02:54 UTC, moonheart08 approved these changes

2022-05-18 03:16 UTC, wrexbe requested changes

2022-05-18 03:16 UTC, wrexbe commented on Content.Client/Audio/BackgroundAudioSystem.cs
> +        private readonly CancellationTokenSource _timerCancelTokenSource = new();
```suggestion
        private CancellationTokenSource _timerCancelTokenSource = new();
```

2022-05-18 03:16 UTC, wrexbe commented on Content.Client/Audio/BackgroundAudioSystem.cs
> +            Timer.Spawn(1500, StartAmbience);
```suggestion
            _timerCancelTokenSource.Cancel();
            _timerCancelTokenSource = new();
            Timer.Spawn(1500, StartAmbience, _timerCancelTokenSource.Token);
```

2022-05-18 03:22 UTC, wrexbe approved these changes

2022-05-18 04:21 UTC, merged