Make shift laser gun
space-wizards/space-station-14 pull request #8125
Opened 2022-05-13 00:28 UTC by UKNOWH

## About the PR 
Adds the construction graph for makeshift laser
**Screenshots**

**Changelog**

:cl:
- add: Added makeshift laser gun!

2022-05-13 01:02 UTC, Veritius commented
The techfab circuit board should be mentioned in the PR description and changelog.

2022-05-13 01:05 UTC, Veritius requested changes

2022-05-13 01:05 UTC, Veritius commented on Resources/Prototypes/Recipes/Construction/Graphs/weapons/makeshift laser gun.yml
> +              name: refined diamond
The refined diamond prototype should be defined with everything else, for the sake of organisation and potential re-use in later recipes.

2022-05-13 01:14 UTC, Veritius commented
I made a dumbass suggestion and removed it. Apparently GitHub still keeps the little thingy. Oops.

2022-05-14 04:06 UTC, Laus4Deus commented
👀 what's up with those files changed

2022-05-14 04:11 UTC, EmoGarbage404 commented
i believe there might be a forking issue, causing files from your previous pr to be on this one. They should be removed before this is merged.

2022-06-04 06:30 UTC, merged

2022-06-04 06:38 UTC, mirrorcult commented
does this even work anymore now that laser cells arent ejectable

2022-06-04 06:38 UTC, mirrorcult commented
i dont really think this should be in regardless design wise

2022-06-04 07:31 UTC, wrexbe commented
Do you have a different recipe in mind, or just remove the makeshift laser?

2022-06-04 07:32 UTC, Peptide90 commented
> Do you have a different recipe in mind, or just remove the makeshift laser?

I think mirror doesn’t want mining mains mass producing laser guns. 

Imo if it stays maybe require a battery, actual laser and some metal as the graph doesn’t make a ton of sense right now. Then salvage will have to get lucky on a ship (don’t think any have lasers) or cooperate with science.