Add a redial button
space-wizards/space-station-14 pull request #8140
Opened 2022-05-13 18:17 UTC by 20kdc

## About the PR

Adds a redial button. Name subject to change, and it might even be an idea to just use this as the reconnect button depending on the disconnect reason.
(It very much depends on if RT can be made to divine if a disconnect is "redial-worthy" like a server shutdown or a key failure... Or if it doesn't matter.)

**Screenshots**
![image](https://user-images.githubusercontent.com/22304167/168343188-a7516051-77ce-4440-afd4-b09167022917.png)

**Changelog**

:cl:
- add: "Redial" button to cause a reconnect-from-launcher without you having to go to the launcher yourself.

2022-05-13 23:06 UTC, ike709 commented
`Reconnect` and `Relaunch` together is probably pretty ambiguous for most players.

2022-05-13 23:10 UTC, 20kdc commented
> `Reconnect` and `Relaunch` together is probably pretty ambiguous for most players.

ok, so, do I just make Reconnect redial, or...

2022-05-14 00:38 UTC, moonheart08 commented
`Reload Game` maybe?

2022-05-14 01:07 UTC, ike709 commented
Maybe `Instant Reconnect` and `Full Relaunch`?

2022-05-14 02:27 UTC, wrexbe commented
I think since 99% of the time you see this is going to be because the server rebooted, maybe it should just get rid of the reconnect button

2022-05-14 09:23 UTC, 20kdc commented
> I think since 99% of the time you see this is going to be because the server rebooted, maybe it should just get rid of the reconnect button

I wish it were that simple
Unless you're saying just get rid of the reconnect button *always*, in which case sure?

Dear goodness this PR is going into bikeshedding territory

2022-05-14 15:06 UTC, wrexbe commented
Yeah, I am saying get rid of the reconnect button entirely. The number one reason the player is going to see this screen is because the server rebooted. Which means what you have is a "Reconnect" button, that may be faster in rare cases, but is much more likely to just to always fail (it has never helped me personally, and disappointed me the first time I tried it). It's less confusing to only have one button that while slightly slower, will always work. You probably need someone else to ok this idea.

2022-05-15 23:03 UTC, PJB3005 requested changes
The engine should properly report disconnect reasons to content so that content can properly show a *single* button, which picks reconnect/redial whenever appropriate. This is just confusing.

2022-05-16 08:10 UTC, 20kdc commented
Closing because this PR essentially needs to be bulldozed for required changes anyway - expect possible engine PR in future?

2022-05-16 08:10 UTC, closed without merging