adds water and fuel tanks back to cargo
space-wizards/space-station-14 pull request #8168
Opened 2022-05-14 18:47 UTC by Peptide90

## About the PR 
Title. Botany can stop crying.
**Screenshots**

**Changelog**

:cl:
- add: Added the water tank and fuel tank back to cargo ordering. It's expensive so use as a last resort.

2022-05-15 02:06 UTC, mirrorcult requested changes

2022-05-15 02:06 UTC, mirrorcult commented on Resources/Prototypes/Catalog/Cargo/cargo_materials.yml
> +  cost: 5000
5000 is a wee bit high for just one, maybe 2000 instead?

2022-05-15 22:47 UTC, youarereadingthis commented
Good PR. I was surprised they weren't in already.

5000 points seems too harsh though. I think it would very rarely be ordered by cargo even if you begged for it unless there was a massive surplus of points(15k+).

Also, the oil tank definitely needs to be in a crate that requires engineering access or that's going to be a new common source of griefing.

2022-05-19 08:42 UTC, Peptide90 commented
> Good PR. I was surprised they weren't in already.
> 
> 
> 
> 5000 points seems too harsh though. I think it would very rarely be ordered by cargo even if you begged for it unless there was a massive surplus of points(15k+).
> 
> 
> 
> Also, the oil tank definitely needs to be in a crate that requires engineering access or that's going to be a new common source of griefing. Cargo gets spaced often enough already unfortunately.

I'll lower the points but the idea was to disincentivise people buying it. I refuse to believe people are running out of water tanks that are mapped and are just lazy. Also sounds like people need to do proper COSHH storage for their welding fuel.

2022-05-20 20:18 UTC, mirrorcult approved these changes

2022-05-20 20:18 UTC, merged