Polymorphs and Transformation
space-wizards/space-station-14 pull request #8185
Opened 2022-05-15 02:05 UTC by EmoGarbage404

## What is it? 
This is a general purpose system meant to handle all forms of one entity turning into another. It is based on prototypes and is wide enough in scope to cover both innate transformations and polymorph spells. This pr lacks content itself, but this system can be widely used in the future for a variety of magical and supernatural actions.

**What's left?**

- [ ] Finish various visual design things (dynamic icons and popups)
- [ ] Retool the system to use a paused map rather than containers
- [ ] Add in several more customizable options for polymorph prototypes
- [ ] Add a system to transfer damage between entities

**Changelog**

:cl:
- add: Polymorphing! Your local spacemen might find themselves turning into a variety of different things.

2022-05-15 14:45 UTC, UKNOWH commented
pog , new TF system

2022-05-16 00:31 UTC, EmoGarbage404 commented
This seems to fail on build, and i have no clue why. If anyone could tell me what's happening, it'd be very much appreciated.

2022-05-16 02:53 UTC, EmoGarbage404 commented
ready for review

2022-05-16 03:35 UTC, metalgearsloth commented
Screenies?

2022-05-16 04:26 UTC, EmoGarbage404 commented
screenies are in. There's a popup but it was broke when screenies were made.

2022-05-16 07:30 UTC, Peptide90 commented
Mimic prop hunt :)

2022-05-18 01:17 UTC, metalgearsloth requested changes
More comments please.

2022-05-18 01:17 UTC, metalgearsloth commented on Content.Server/Administration/Commands/AddPolymorphActionCommand.cs
> +    [Dependency] private IPrototypeManager _proto = default!;
Unneeded.

2022-05-18 01:17 UTC, metalgearsloth commented on Content.Server/Administration/Commands/AddPolymorphActionCommand.cs
> +        var polySys = EntitySystem.Get<PolymorphableSystem>();
entitysystem.get<T> is going the way of the dodo so just resolve it manually.

2022-05-18 01:17 UTC, metalgearsloth commented on Content.Server/Administration/Commands/AddPolymorphActionCommand.cs
> +        entityUid.EnsureComponent<PolymorphableComponent>();
use the entitymanager ensurecomp

2022-05-18 01:17 UTC, metalgearsloth commented on Content.Server/Polymorph/Components/PolymorphableComponent.cs
> +        public Dictionary<string, InstantAction> PolymorphActions = new();
Not sure if this should be on a new component or not. At least make it nullable.

2022-05-18 01:17 UTC, metalgearsloth commented on Content.Server/Polymorph/Systems/PolymorphableSystem.Map.cs
> +        }
Update the MapId to an EntityUid and also use Dirty(mapComp) instead.

2022-05-18 01:17 UTC, metalgearsloth commented on Content.Server/Polymorph/Systems/PolymorphableSystem.cs
> +        [Dependency] private readonly IEntityManager _entity = default!;
This is already on entity systems.

2022-05-18 01:17 UTC, metalgearsloth commented on Content.Server/Polymorph/Systems/PolymorphableSystem.cs
> +                return;
Should just Index given linter should catch it. At a minimum if TryIndex was left it would need an error log.

2022-05-18 01:17 UTC, metalgearsloth commented on Content.Server/Polymorph/Systems/PolymorphableSystem.cs
> +            var child = Spawn(proto.Entity, Transform(target).Coordinates);
Transform for the target is being resolved twice, just cache it as a local variable and reuse it.

2022-05-18 01:17 UTC, metalgearsloth commented on Content.Server/Polymorph/Systems/PolymorphableSystem.cs
> +                return;
Log error for the former, latter should be caught by yaml linter.

2022-05-18 04:05 UTC, merged

2022-05-18 04:09 UTC, EmoGarbage404 commented
Guess i'm doing prop hunt now.