Typing indicator (typing chat bubble)
space-wizards/space-station-14 pull request #8215
Opened 2022-05-16 18:51 UTC by Macoron

## About the PR 
Fix #4915
Continues #5173

**Screenshots**

https://user-images.githubusercontent.com/6161335/168661075-db1f52f3-eeca-4b92-bfbc-36417e008f8b.mp4

**Changelog**

:cl:
- add: Added chat typing indicator.

2022-05-16 21:16 UTC, mirrorcult requested changes
looks good, a couple requests:

- people have expressed desire for a client cvar that makes it so they don't show typing indicators, doesnt seem like that would be too hard to do?
- the solution of making it a layer on the entity that gets added and the data is synced with appearance data is good to me, but want a second opinion
- how does it look for mobs stacked on the same tile (or pAIs on the same tile as someone else)?

2022-05-17 07:12 UTC, Macoron commented on Content.Server/Chat/TypingIndicator/TypingIndicatorSystem.cs
> +    }
```
    /// <summary>
    ///     Component required for entities to be able to speak. (TODO: Entities can speak fine without this, this only forbids them speak if they have it and enabled is false.)
    ///     Contains the option to let entities make noise when speaking, datafields for the sounds in question, and relevant AudioParams.
    /// </summary>
    [RegisterComponent]
    public sealed class SharedSpeechComponent : Component
```

I'm not sure about it. Check TODO comment. Also see typing crowbars and other ghost roles is kinda cool.

2022-05-17 07:42 UTC, Macoron commented
> people have expressed desire for a client cvar that makes it so they don't send typing indicators, doesnt seem like that would be too hard to do?

Done. In future PR this will need UI element in chat window, but for now you can disable it on a client by `cvar chat.show_typing_indicator false`. You will still see others typing indicators though.

> how does it look for mobs stacked on the same tile (or pAIs on the same tile as someone else)?

Sprite sorting looks good when entities really close to each other (just tested it). If pAIs or mouse placed inside mobs inventory, typing indicator won't be shown.

2022-05-17 09:53 UTC, mirrorcult commented on Content.Server/Chat/TypingIndicator/TypingIndicatorSystem.cs
> +    }
sure, thats fine for now then

2022-05-17 09:54 UTC, mirrorcult approved these changes

2022-05-17 09:55 UTC, merged