Fix popups appearing at 0,0
space-wizards/space-station-14 pull request #8221
Opened 2022-05-16 23:12 UTC by ElectroJr

Problem was probably just because of entities leaving PVS and being sent to 0,0 in null-space. Should fix #7749 but I haven't really tested thoroughly.

2022-05-17 11:02 UTC, PaulRitter requested changes

2022-05-17 11:02 UTC, PaulRitter commented on Content.Client/Popups/PopupSystem.cs
> +            if (_eyeManager.CurrentMap != mapCoords.MapId)
the client can already see multiple maps at once using viewsubscriptions. i dont have time to figure out how you can check which maps are seen atm but i know this is wrong

2022-05-17 11:02 UTC, PaulRitter commented on Content.Client/Popups/PopupSystem.cs
> +            if (_eyeManager.CurrentMap != transform.MapID)
see above

2022-05-17 11:02 UTC, PaulRitter commented on Content.Client/Popups/PopupSystem.cs
> +                if (Entity == null && InitialPos.MapId == _eyeManager.CurrentMap)
see above

2022-05-17 11:02 UTC, PaulRitter commented on Content.Client/Popups/PopupSystem.cs
> +                else if (_entityManager.TryGetComponent(Entity, out TransformComponent xform) && xform.MapID == _eyeManager.CurrentMap)
see above

2022-05-18 02:33 UTC, metalgearsloth commented
@PaulRitter A whole bunch of stuff is broken for cameras / multi-viewports which needs fixing anyway, see https://github.com/space-wizards/space-station-14/issues/8154

2022-05-18 09:43 UTC, PaulRitter commented
> @PaulRitter A whole bunch of stuff is broken for cameras / multi-viewports which needs fixing anyway, see #8154

![image](https://user-images.githubusercontent.com/16618384/169010087-4adf0d40-f5ed-4ad5-a8c7-421e722245d0.png)

2022-05-18 22:01 UTC, metalgearsloth commented
Merging coz I wanna stop getting pinged on it and I'm too lazy to revert the log.

2022-05-18 22:12 UTC, merged