Gromit mug
space-wizards/space-station-14 pull request #8224
Opened 2022-05-17 01:42 UTC by ZeroDayDaemon

## About the PR 
gromit mug. a stylized mug ported from Unitystation.
**Screenshots**

![image](https://user-images.githubusercontent.com/60460608/168710626-1803e45a-3150-41fe-abe1-e4b8f34c7495.png)

**Changelog**

:cl: Daemon
- add: Added wacky zany funny humorous dog mug reagent container

2022-05-17 01:43 UTC, EmoGarbage404 commented
This is clearly the straw that breaks the camel's back. I hope you get repo banned. /s

2022-05-17 01:44 UTC, ZeroDayDaemon commented
Up next, porting unity's locker sprites /s

2022-05-17 07:46 UTC, Macoron commented
Finally some decent content PRs

2022-05-17 08:25 UTC, metalgearsloth commented
> Finally some decent content PRs

https://github.com/unitystation/unitystation/pull/4905

hmm

2022-05-17 09:06 UTC, Zumorica requested changes

2022-05-17 09:06 UTC, Zumorica commented on Resources/Textures/Objects/Consumable/Drinks/mug_gromit.rsi/meta.json
> +    "copyright": "https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Textures/items/drinks/mug_gromit.asset",
> [unitystation/unitystation#4905](https://github.com/unitystation/unitystation/pull/4905)

Given the original PR specifies the spriter, you should include them here too.

2022-05-18 18:20 UTC, mirrorcult approved these changes
funny dog mug

2022-05-18 18:21 UTC, merged