Redial Button II - Now with magic!
space-wizards/space-station-14 pull request #8237
Opened 2022-05-17 14:58 UTC by 20kdc

## About the PR

Brought to you by the Redial API.

**Screenshots**

![image](https://user-images.githubusercontent.com/22304167/168842487-166b8748-69a8-4e32-851d-ad6d99a84a8d.png)

![image](https://user-images.githubusercontent.com/22304167/168842765-236ae5c4-bac9-48ef-94ab-f32c09f15edf.png)

**Changelog**

:cl:
- tweak: When the server shuts down or you fail to connect because of a key error, the button shown will say `Relaunch` rather than `Reconnect` and will restart the client for you.

2022-05-17 22:18 UTC, wrexbe approved these changes

2022-05-17 22:24 UTC, moonheart08 requested changes
This should definitely prompt the user to wait 15-30 seconds to reconnect in the case of updates. Otherwise they'll try and connect before the server's even online.

2022-05-18 01:59 UTC, wrexbe commented
How about if the button is grayed out, and says "Please Wait", for 15 seconds?

2022-05-18 10:19 UTC, 20kdc commented
> How about if the button is grayed out, and says "Please Wait", for 15 seconds? @moonheart08

I have now just implemented this.

2022-05-22 01:56 UTC, merged