Waystation: The Station That Will Succeed Packed's Legacy
space-wizards/space-station-14 pull request #8398
Opened 2022-05-24 02:21 UTC by TimrodDX

## About the PR 

This PR adds Waystation, the map that was largely the successor to Packed on /vg/. It is a small/mid-pop map that is slightly bigger than Packed and also re-uses some room layouts from it. I have ported the map 1:1, except for the Atmos department (which was more than a little odd) and some mapping bugs that still exist in the current /vg/ master which I have fixed. The atmos piping is mostly a 1:1 copy and the original map had pipes through walls.

I also did not put in the AI satellite or telecomms room - both of those were kinda Ass Blast USA, and when we get silicons and telecomms I will be adding my own AI area that isn't a satellite. In the same vein, there were some minor changes to the exterior of the station in order to accommodate moving shuttles, and I edited the arrivals shuttle due to the diagonal shuttle wall bug. 

This map will be replacing Packed - I will eventually update Packed and make it playable again, but it will be a low-pop map with the same restrictions as Saltern or Moose. 
 
My hope is that the testing I've done ahead of time makes the launch of this map go significantly smoother than Packed or Delta did. 

**Screenshots**

![image](https://user-images.githubusercontent.com/7907891/169935396-b797d6eb-4464-463f-a034-e7745692c08e.png)

![image](https://user-images.githubusercontent.com/7907891/169935420-26109538-cadd-48ef-a11c-b0c1ccfdf7b7.png)

![image](https://user-images.githubusercontent.com/7907891/169935447-f24a3fc7-ec17-4d04-9e5e-1450a47c860f.png)

![image](https://user-images.githubusercontent.com/7907891/169935492-179d5084-e615-4297-9182-a3beba511de7.png)

![image](https://user-images.githubusercontent.com/7907891/169935523-a1237943-e3b0-4eda-a71c-46fea8a31a42.png)

![image](https://user-images.githubusercontent.com/7907891/169935567-50106334-9ee4-4d21-864c-d742eed255d7.png)

![image](https://user-images.githubusercontent.com/7907891/169935600-50f32a07-431d-45c5-bda5-fb5e14db0770.png)

**Changelog**

:cl:
- add: Waystation has been faithfully ported to SS14, and will succeed Packed Station's role as a low to midpop map.

2022-05-24 04:46 UTC, Emisse commented
looks awesome

2022-05-25 20:55 UTC, mirrorcult requested changes
overall looks pretty good. didnt comment on anything that would entail significant changes from canon way

review notes:

- this fireplace in the caps bedroom is stuck in the wall here, and you can see it through the other side of the wall
![image](https://user-images.githubusercontent.com/19853115/170362267-af05bb7a-fc4b-4626-844b-ed3dee7fd705.png)

- prison lockdown button (left one) in sec doesn't properly lock down this top blast door

![image](https://user-images.githubusercontent.com/19853115/170364207-f9c0a3d3-9927-453b-8425-bf168fbb0488.png)

- this signal button isnt linked to these blast doors (should they be shutters?) in the kitchen
![image](https://user-images.githubusercontent.com/19853115/170364803-4dca6784-cec7-4dcc-85e1-71d5fb2f6c1e.png)

- these are computer frames? (maybe just replace with tables and have windoors?)
![image](https://user-images.githubusercontent.com/19853115/170362618-1aa7c2d2-0e47-4375-80d9-47a04043b040.png)

- microreactor cell probably shouldnt be mapped, at least not in such an easily accessible location
![image](https://user-images.githubusercontent.com/19853115/170362806-8abf9128-c11b-4137-a1cd-93dadc9f5f24.png)

- not sure how i feel about cargo starting with an ATV?

- what is this room, exactly
![image](https://user-images.githubusercontent.com/19853115/170363111-1632d9ba-7579-440f-b9d6-a99edb6d2d7b.png)

- chem is oversupplied with grenade materials, needs to at least have less chem payloads
- power monitoring console in the bridge doesnt actually do anything since its not hooked up to HV

- this signal button in RND isnt linked to anything. same with the one in robotics
![image](https://user-images.githubusercontent.com/19853115/170365347-3a2e31b2-8d90-4c8b-b787-e2c1187ef29c.png)

2022-05-25 22:45 UTC, TimrodDX commented
Yeah, some of those definitely need explaining. I split them into three categories: things that are non-map bugs, things that simply aren't in SS14 yet, and things that can/will be changed.

**Non-Map Bugs**

- The microreactor cell is there because there's a loot spawner on that table, and I think the microreactor cells are included in the loot table for that particular spawner due to them being tagged as a power cell. Peptide was the one who merged those, so that's going to be a problem on any map that uses those, including Delta.

- The prison lockdown button in the Warden's office doesn't close that blast door because it's outside of the standard 30-tile radius in which machine linking works. There was a PR up for this, but I don't know if it was merged or not.

- The fireplace in the captain's bedroom is I think either a wall-mount or offset in /vg/. In mapping mode, it's actually in the correct position, it just gets kicked out of the correct position due to physics.

![image](https://user-images.githubusercontent.com/7907891/170373374-07becd20-6c31-4851-bc9d-af12a25dece9.png)

![image](https://user-images.githubusercontent.com/7907891/170373389-bab97a09-b96a-4ecc-a5fb-f6f4a06abc72.png)

** Things That Aren't in SS14 Yet**

- The empty room with the T-shape is the Thermoelectric Generator room, which is a thing on /vg/ but isn't yet in SS14. The SS13 map has a Supermatter, the TEG, and the AME as a backup.

![image](https://user-images.githubusercontent.com/7907891/170371685-da2e25d6-7041-41f5-adc1-d389ff1245aa.png)

- The two computer frames in Security are there as placeholders, because on the original map there is a camera computer and I think a Beepsky control computer there. I can replace it with a desk until those things are in. Note that the reason the buttons aren't there is because buttons on tables are currently broken.

![image](https://user-images.githubusercontent.com/7907891/170371979-e7bdac6e-5fff-4cde-9055-06d8ba633d53.png)

This is what it looks like replaced.

![image](https://user-images.githubusercontent.com/7907891/170373050-16411caf-9183-4bc4-8816-ee486fa380ec.png)


** Things That Can / Will Be Fixed**

- The blast doors on the kitchen windows are, oddly enough, blast doors on the original map. I believe this is because on /vg/, blast doors can close over windows/doors but shutters cannot. I have those working, but the main reason they didn't is because at the time I started the map, blast doors over windows did not work.

![image](https://user-images.githubusercontent.com/7907891/170372392-c7010d25-c1d4-4c90-881c-47ac86c078f4.png)

- The monitoring console on the bridge now has HV power. This probably should also be a "Things That Aren't in SS14 Yet" because I don't think they even need to be directly wired in SS13.

- Chemistry's grenade supply has been lowered to 2.

![image](https://user-images.githubusercontent.com/7907891/170374026-249c30b3-31c1-415a-948f-e60415a7198e.png)

- The buttons in R&D and Robotics don't do anything

Those were for blast doors that have since been nuked, reason being that they're supposed to be controlled by a button in the RD's office, but buttons on tables don't work right at the moment. They've been removed.

2022-05-26 14:48 UTC, moonheart08 approved these changes

2022-05-29 16:18 UTC, merged