Fix StepTrigger error
space-wizards/space-station-14 pull request #8480
Opened 2022-05-27 11:25 UTC by wrexbe

Saw a ton of these errors earlier on lizard

```
Caught exception in entsys
System.Collections.Generic.KeyNotFoundException: Entity 51786 does not have a component of type Robust.Shared.GameObjects.TransformComponent
   at Robust.Shared.GameObjects.EntityQuery`1.GetComponent(EntityUid uid) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 1101
   at Content.Shared.StepTrigger.StepTriggerSystem.Update(StepTriggerComponent component) in /home/runner/work/space-station-14/space-station-14/Content.Shared/StepTrigger/StepTriggerSystem.cs:line 47
   at Content.Shared.StepTrigger.StepTriggerSystem.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Shared/StepTrigger/StepTriggerSystem.cs:line 23
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 317
 Catcher=entsys Sawmill=runtime
```

I added checks for a transform component to the guard at the beginning, and one to the remove check.

2022-05-27 11:29 UTC, metalgearsloth commented on Content.Shared/StepTrigger/StepTriggerSystem.cs
> +            if (!otherUid.IsValid() || !TryComp<TransformComponent>(otherUid, out var otherTransform))
Checking for transform is a bandaid IMO; if you use mousetraps you can replicate the problem.

2022-05-27 11:30 UTC, PJB3005 requested changes
The first problem here is that we shouldn't even getting entities without transform in an entity query here, since those would be deleted. So I'd prefer we fix that instead.

Also put `Transform` in the entity query instead.

2022-05-28 04:46 UTC, metalgearsloth requested changes

2022-05-28 04:46 UTC, metalgearsloth commented on Content.Shared/StepTrigger/StepTriggerSystem.cs
> +        if (component.Deleted ||
You can remove this Deleted check because the component is ensured to exist.

2022-05-28 04:46 UTC, metalgearsloth commented on Content.Shared/StepTrigger/StepTriggerSystem.cs
> +        if (!otherUid.IsValid() ||
This IsValid check is pointless and should only be used for debugging.

2022-05-28 04:46 UTC, metalgearsloth commented on Content.Shared/StepTrigger/StepTriggerSystem.cs
> +        component.Dirty();
```suggestion
        Dirty(component);
```

2022-05-28 04:46 UTC, metalgearsloth commented on Content.Shared/StepTrigger/StepTriggerSystem.cs
> +            component.Dirty();
```suggestion
            Dirty(component);
```

2022-05-28 04:46 UTC, metalgearsloth commented on Content.Shared/StepTrigger/StepTriggerSystem.cs
> +            !TryComp(otherUid, out PhysicsComponent? otherPhysics))
If the cause is steptrigger leading to other colliding entities being deleted then I'm fine with this here I guess.

2022-05-28 05:39 UTC, merged