Event Music & Nuke Countdown Song
space-wizards/space-station-14 pull request #8597
Opened 2022-06-02 18:41 UTC by ike709

## About the PR 

Modifies AdminSoundSystem to be a more generic system for playing sounds globally to players, with the only restrictions being if they've disabled the sound via cvar or (optionally) if they're not on the same grid.

Also as an example usage, adds [Countdown](https://www.youtube.com/watch?v=G2gVAPKlgqA) from the BeeStation OST to when the nuke is armed. It's our second most-popular song by views.

I eventually intend to add support to everything Bee has songs for, like xeno infestation and war ops.

**Screenshots**
Note: I had to do a fresh install of OBS so the resolution is wonky but you're just here for the audio anyways.

It starts when armed, stops when disarmed, and will start again if rearmed.

https://user-images.githubusercontent.com/5714543/171702349-d0eb251c-2e1f-4786-ba66-18d7fba58a46.mp4

**Changelog**

:cl:
- add: A song now plays during the nuke countdown. It can be disabled with the Event Music audio setting.

2022-06-02 19:37 UTC, DogZeroX commented
Also, the song ends 67 seconds before the nuke explodes, so we will have to lower the nuke time until it explodes or have an awkward period of silence before detonation.

2022-06-02 19:49 UTC, ike709 commented
It's timed for SS13's default of 90 seconds. Don't really know what to do about SS14 using 180 seconds.

2022-06-02 23:00 UTC, metalgearsloth requested changes

2022-06-02 23:01 UTC, metalgearsloth commented on Content.Server/Nuke/NukeSystem.cs
>              SoundSystem.Play(Filter.Broadcast(), component.ArmSound.GetSound());
This is also broadcast.

2022-06-05 03:37 UTC, wrexbe commented
Are you still working on this?

2022-06-05 07:44 UTC, ike709 commented
Yes.

2022-06-05 07:46 UTC, ike709 commented
> Are you still working on this?

\> leave as draft for 2 days
\> asked if derelict
\> forensics has been waiting for a review for 10 days

>:^(

2022-06-05 07:51 UTC, mirrorcult commented
thank you for making me realize i never submitted my review on forensics

2022-07-04 05:51 UTC, metalgearsloth commented
Ideally we wouldn't have like 3 different content audio systems + engine but can fix that later.

2022-07-04 06:29 UTC, metalgearsloth approved these changes

2022-07-04 06:29 UTC, merged