LOOC has a prefix now
space-wizards/space-station-14 pull request #8834
Opened 2022-06-14 06:50 UTC by Just-a-Unity-Dev

## About the PR 
resolves #8833, the LOOC prefix is `|`

**Screenshots**

https://user-images.githubusercontent.com/67359748/173511365-70fe0068-4047-4f3e-89de-3d9545b849bd.mp4

**Changelog**

:cl: eclips_e
- add: Added a prefix for LOOC

2022-06-16 09:37 UTC, metalgearsloth requested changes
Swap it with admin chat as it barely gets used and makes much more sense.

2022-06-28 10:16 UTC, metalgearsloth requested changes

2022-06-28 14:48 UTC, Just-a-Unity-Dev commented on Content.Client/Chat/UI/ChatBox.xaml.cs
> +        public const char AliasLOOC = ']';
i have commited a sin. a webedit + mobile. reviews addressed

2022-06-28 14:52 UTC, metalgearsloth commented
This might conflict with hud refactor considering they refactored chat so gonna sit until that's merged.

2022-07-21 20:32 UTC, wrexbe commented
I looked at the UI refactor a bit, this code isn't going to be compatible. It looks like LOOC will have a prefix of '(' when it's done.

2022-07-21 20:32 UTC, closed without merging