Disarm 1984
space-wizards/space-station-14 pull request #8872
Opened 2022-06-16 02:20 UTC by Elijahrane

## About the PR 
Disarm fail chance is now modified by relative health, relative mass, and whether either party has the "slowed down" component.

**Screenshots**

**Changelog**

:cl: Rane
- add: Disarm chance now scales with relative health, relative mass, and status effects. It's now a much, much worse tool to instantly win a fight you're losing.

2022-06-16 12:28 UTC, mirrorcult requested changes
approve the concept entirely

2022-06-16 12:28 UTC, mirrorcult commented on Content.Server/CombatMode/CombatModeSystem.cs
> +            && !hands.ActiveHand.IsEmpty)
```suggestion
            if (TryComp<HandsComponent>(args.Performer, out var hands)
                && hands.ActiveHand != null
                && !hands.ActiveHand.IsEmpty)
```

2022-06-16 12:28 UTC, mirrorcult commented on Content.Server/CombatMode/CombatModeSystem.cs
> +            Logger.Error("Chance is:" + chance);
a

2022-06-16 12:28 UTC, mirrorcult commented on Content.Server/CombatMode/CombatModeSystem.cs
> +            Logger.Error("inTargetHand is: " + inTargetHand);
a

2022-06-16 12:28 UTC, mirrorcult commented on Content.Server/CombatMode/CombatModeSystem.cs
> +               healthMod = 0; // If some of them can't take damage, no effect from this.
you're already setting it to 0 before this, just invert this and put the else code here

2022-06-16 12:28 UTC, mirrorcult commented on Content.Server/CombatMode/CombatModeSystem.cs
> +                }
use `PhysicsComponent.FixturesMass` instead of calculating it manually

2022-06-16 12:28 UTC, mirrorcult commented on Content.Server/CombatMode/CombatModeSystem.cs
> +            return chance;
```suggestion
            return Math.Clamp(chance, 0f, 1f);
```

2022-06-16 12:28 UTC, mirrorcult commented on Content.Server/CombatMode/Disarm/DisarmMalusComponent.cs
> +    /// </summary>
```suggestion
    /// <summary>
    /// Applies a malus to disarm attempts against this item.
    /// </summary>
    [RegisterComponent]
```

2022-06-16 12:28 UTC, mirrorcult commented on Content.Server/CombatMode/Disarm/DisarmMalusComponent.cs
> +        public float Malus = 0.3f;
add comments for what this value represents, not obvious that it's -= chance

2022-06-17 05:33 UTC, Elijahrane commented
Reviews addressed

2022-06-17 05:36 UTC, mirrorcult approved these changes

2022-06-17 05:37 UTC, merged

2022-07-21 15:44 UTC, CaptainSqrBeard commented
Is massMod work as intended? I tried get it inside my head and got wrong values.

Values from example:
Disarmer Mass: 120
Disarm Victim: 70

70/120 = 0.58~
0.58-1 = -0.42
-0.42/2 = -0.21

So basically disarmer gets extra 21% chance for disarm instead of 29% that was in example

And it also can be harder to disarm someone that slightly heavier that you. Like if you vice-versa masses from example, you will get 35% chance decrease instead of 21%

Line 122:
```csharp
massMod = (((disarmedPhysics.FixturesMass / disarmerPhysics.FixturesMass - 1 ) / 2)); // Ex, you weigh 120, they weight 70, you get a 29% bonus 
```