Obfuscates pocket slots from the Strip Menu
space-wizards/space-station-14 pull request #8948
Opened 2022-06-18 23:33 UTC by keronshb

## About the PR 

Hides pocket items from strip menu changes.

It is a bit hardcoded right now and the only other example of this in code hardcodes it something similar. I'd like to try to not hardcode it, but I'm having issues getting to that point.

**Screenshots**

![image](https://user-images.githubusercontent.com/54602815/174460121-6669c3a2-ce97-4c39-8e48-3d5745fa83ed.png)

**Changelog**

:cl:
- add: Adds obfuscation to pocket items so players can't check the strip menu to see what they have.

2022-06-18 23:49 UTC, mirrorcult requested changes

2022-06-18 23:49 UTC, mirrorcult commented on Content.Client/Inventory/StrippableBoundUserInterface.cs
> +        public string Occupied { get; } = "Occupied";
localize

2022-06-18 23:50 UTC, mirrorcult commented
you could maybe have a datafield bool on the slot for whether it should be 'hidden'? and then check that instead of pocket1/pocket2

2022-06-19 00:11 UTC, keronshb commented
> you could maybe have a datafield bool on the slot for whether it should be 'hidden'? and then check that instead of pocket1/pocket2

Oh that's a good idea, but in this instance how would I check for that? I know I can throw it on the slot like how it's done for the strip delay, but here it's seemingly not going through the inventory system the same way it would on the strip delay PR if that makes sense?

Like I tried to understand how it grabs inventory, but following in breakpoints or in code hasn't exactly been helpful on trying to figure out how it's grabbed.

For example if I made it I can't just do slot.IsHidden because even if I added it to the inventory template, it's not grabbing it from that.

I would add a bool to the dictionary so then it would have 3 variables? But again even if I followed up to the files that I know it's in (StrippableBounderUserInterface, SharedStrippableComponent) I just don't understand how it exactly grabs the data and how to work that in.

2022-06-19 09:48 UTC, PaulRitter requested changes
this should definitely be a bool. you'd need to network that bool using the strippingboundinterfacestate

2022-06-19 15:30 UTC, keronshb commented
> this should definitely be a bool. you'd need to network that bool using the strippingboundinterfacestate

I do not understand how this works. If you can give me an example I could try, but I do not know what to add here or how to grab the information.

2022-06-19 20:10 UTC, ElectroJr commented on Content.Client/Inventory/StrippableBoundUserInterface.cs
> +        public string Occupied { get; } = Loc.GetString("strippable-bound-user-interface-stripping-menu-obfuscate");
`static`

2022-06-19 20:27 UTC, ElectroJr commented
It looks like the easiest way to do this would be to just update the server's `StrippableSystem.SendUpdate()`, which is where it gets the slot & the name of the item. Just check if `slot.StripHidden` or whatever the bool will be called there and obfuscate the name of the item if needed

2022-06-20 00:43 UTC, keronshb commented
> It looks like the easiest way to do this would be to just update the server's `StrippableSystem.SendUpdate()`, which is where it gets the slot & the name of the item. Just check if `slot.StripHidden` or whatever the bool will be called there and obfuscate the name of the item if needed

Got it. This latest push should fix it.

2022-06-20 00:57 UTC, merged