Cloner Console Part 2 Part 2
space-wizards/space-station-14 pull request #8972
Opened 2022-06-20 15:03 UTC by Elijahrane

## About the PR 
Yeah I revived the old fishfish pr, draft because I still have a lot of cleanup and I can't merge upstream because it crashes with a weightless bug.

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

2022-06-20 17:38 UTC, Elijahrane commented
What do you want me to do about body reassemble since it's already pretty broken and incompatible with this

2022-06-20 17:51 UTC, EmoGarbage404 commented
> What do you want me to do about body reassemble since it's already pretty broken and incompatible with this

Um you can probably leave it commented out and then i can fix it after the pr is merged. On thing of note, im not sure the species field in humanoid appearance is properly updated and tracked.

2022-06-21 23:16 UTC, EmoGarbage404 commented
Ive made fixes to skeletons in a new pr, so i suggest removing all unnecessary changes in your code lest you may run into a lot of conflicts.

2022-06-22 10:50 UTC, Elijahrane commented
I'll just fix it after that's merged because this isn't gonna build if I uncomment that

2022-07-15 03:06 UTC, mirrorcult requested changes
will need another review + i need to test ingame as well

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Body/Components/BodyReassembleComponent.cs
> +// }
has this been discussed with emogarbage at all as for whether this is getting fixed soon, cause ideally this is uncommented before merge

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Cloning/CloningConsoleSystem.cs
> +            Logger.Error("args.Receiver is: " + args.Receiver);
```suggestion
```

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Cloning/CloningConsoleSystem.cs
> +                Logger.Error("Adding scanner...");
```suggestion
```

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Cloning/CloningConsoleSystem.cs
> +                Logger.Error("Adding pod...");
```suggestion
```

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Cloning/CloningConsoleSystem.cs
> +                consoleComp.CloningPodInRange = podDistance <= consoleComp.MaxDistance;
```suggestion
                Transform(scanner.Value).Coordinates.TryDistance(EntityManager, Transform((console)).Coordinates, out float scannerDistance);
                consoleComp.GeneticScannerInRange = scannerDistance <= consoleComp.MaxDistance;
            }
            if (cloningPod != null)
            {
                Transform(cloningPod.Value).Coordinates.TryDistance(EntityManager, Transform((console)).Coordinates, out float podDistance);
                consoleComp.CloningPodInRange = podDistance <= consoleComp.MaxDistance;
```

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Cloning/CloningConsoleSystem.cs
> +            string scanBodyInfo = "Unknown";
localize

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Cloning/CloningConsoleSystem.cs
> +            if (args.Port == "CloningPodSender")
these should be static strings/consts somewhere

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Cloning/CloningConsoleSystem.cs
> +            var cloneBodyInfo = "Unknown";
loc

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Cloning/CloningConsoleSystem.cs
> +            && Transform((EntityUid) consoleComponent.CloningPod).Anchored)
```suggestion
            && Transform(consoleComponent.CloningPod.Value).Anchored)
```
etc for all other cases of that

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Cloning/CloningSystem.cs
> +                {
this should really use an `ActiveCloningPodComponent` for perf

2022-07-15 03:06 UTC, mirrorcult commented on Content.Server/Cloning/Components/CloningConsoleComponent.cs
> +        public bool Powered = false;
this doesnt need to be stateful

2022-07-15 03:06 UTC, mirrorcult commented on Content.Shared/Cloning/SharedCloningConsole.cs
> +            public readonly string? ClonerBodyInfo;
entire file is indented one too many

2022-07-17 01:21 UTC, Elijahrane commented
![image](https://user-images.githubusercontent.com/60792108/179380008-8936200a-da24-4e61-af96-ac80e8eb4d6d.png)

2022-08-04 04:04 UTC, mirrorcult approved these changes

2022-08-04 04:05 UTC, merged