Solution spiking
space-wizards/space-station-14 pull request #8984
Opened 2022-06-20 22:14 UTC by vulppine

## About the PR 

Adds solution spiking to the game. This allows pills to dissolve into beakers and other entities that use `RefillableSolutionComponent`, and eggs to be cracked into bowls, or anything that uses the previously mentioned component. If a solution container overflows while it's being spiked, however, it will raise an event - currently used by SpillableSystem to create puddles on the ground when the container overflows.

**Changelog**

:cl:
- add: Pills can now be dissolved into beakers. And, you can crack eggs into bowls now! The future is now!

2022-06-21 01:57 UTC, mirrorcult requested changes

2022-06-21 03:15 UTC, vulppine commented on Content.Server/Chemistry/EntitySystems/SolutionSpikableSystem.cs
> +            _triggerSystem.Trigger(source);
spawning items being something like cracking an egg, and you get eggshells

2022-06-24 02:26 UTC, mirrorcult commented on Content.Server/Chemistry/EntitySystems/SolutionSpikableSystem.cs
> +            _triggerSystem.Trigger(source);
yeah i guess why not

2022-06-24 02:26 UTC, mirrorcult approved these changes

2022-06-24 02:26 UTC, merged