Skeleton Fixes
space-wizards/space-station-14 pull request #9008
Opened 2022-06-21 20:30 UTC by EmoGarbage404

## About the PR 
q: if the solution was this simple, why did this take so long
a: uhhu hhhh ummm uhh heahahe

Fixes #8182
Fixes #8463 
**Screenshots**

**Changelog**

:cl:
- fix: Skeleton reassembly now works properly for ghost roles.
- fix: Skulls now have the correct scream sound effects.
- fix: Skeleton reassembly now cancels correctly.

2022-07-12 04:39 UTC, metalgearsloth requested changes

2022-07-12 04:39 UTC, metalgearsloth commented on Content.Server/Body/Systems/BodyReassembleSystem.cs
> +            foundPart = null;
This is dirty as, please don't add the entitylookup back in and especially don't compare prototype IDs.

2022-07-15 19:13 UTC, ElectroJr commented on Content.Server/Body/Systems/BodyReassembleSystem.cs
this shouldn't depend on entity prototypes.
It should probably just look for specific body parts with some sort of limb reassembly component

2022-07-17 00:19 UTC, EmoGarbage404 commented
closing this because skeletons are generally pretty awful. Their balance is wack and pretty un-fun in general. When i made this iteration, i had a shittier idea of game balance and general, and all of the systems for skeletons are pretty hacky and poorly done. I'll be retooling them at a later point to work more akin to an antag for events, then one proper body system is in, further tooling them to be interesting to play. For the time being, i'm closing this.

2022-07-17 00:19 UTC, closed without merging