Adds a tool for importing .netset files into the ban DB.
space-wizards/space-station-14 pull request #9016
Opened 2022-06-22 06:06 UTC by moonheart08

## About the PR
.netset is a stupidly simple format (each line is either a comment, or an IP) so I wrote a tool to import these files into the ban database.

2022-06-24 03:59 UTC, wrexbe commented on Content.Server/Administration/Commands/ImportNetsetCommand.cs
> +                new NetUserId(new Guid("a17aa146-807c-48bb-8573-65e3cb05119d")),
If this is MoMMI's user, maybe this should be a CCVar, or a constant with a name.

2022-06-24 04:00 UTC, wrexbe requested changes
I feel like this command could be abused to anonymously ban people. Maybe force add who did it to the reason, or at log when someone uses this command.

2022-06-24 06:19 UTC, moonheart08 commented
> I feel like this command could be abused to anonymously ban people. Maybe force add the person who uses it to the ban reason, or log when someone uses this command.

This is an issue on the administrative side, there's a reason this tool is +HOST.

2022-06-24 06:21 UTC, moonheart08 commented on Content.Server/Administration/Commands/ImportNetsetCommand.cs
> +                new NetUserId(new Guid("a17aa146-807c-48bb-8573-65e3cb05119d")),
I don't think this needs to be modifiable.

2022-06-24 06:27 UTC, moonheart08 commented on Content.Server/Administration/Commands/ImportNetsetCommand.cs
> +                new NetUserId(new Guid("a17aa146-807c-48bb-8573-65e3cb05119d")),
I've made it clearer what it is, however I want the user to remain consistent, ideally between servers, for automation purposes.

2022-06-25 17:50 UTC, wrexbe approved these changes

2022-06-25 17:52 UTC, merged