Disease Stages But Epic
space-wizards/space-station-14 pull request #9043
Opened 2022-06-23 01:17 UTC by EmoGarbage404

## About the PR 
Stages are now defined as a dictionary of thresholds corresponding to numerically ordered stages starting at 0. Effects and cures can be applied to a stage through the `Stages` datafield, which is simply a list of integer stages.
**Screenshots**

**Changelog**

:cl:
- add: Diseases can now have different stages.

2022-06-23 04:59 UTC, metalgearsloth requested changes

2022-06-23 04:59 UTC, metalgearsloth commented on Content.Server/Disease/DiseaseSystem.cs
> +                    }
```suggestion
                    float lastThreshold = 0;
                    foreach (var threshold in disease.Stages)
                    {
                        if (disease.TotalAccumulator >= threshold.Value &&
                            threshold.Value > lastTreshold)
                        {
                            lastThreshold = threshold.Value;
                            stage = threshold.Key;
                        }
                    }
```

Also should the thresholds just be an array?

2022-06-28 13:49 UTC, metalgearsloth commented on Content.Server/Disease/DiseaseSystem.cs
> +
Still has tresholds

2022-06-28 13:58 UTC, metalgearsloth requested changes
This needs some sort of validation that the yml is correct.

2022-06-28 13:58 UTC, metalgearsloth commented on Content.Shared/Disease/DiseasePrototype.cs
> +        [DataField("Stages", serverOnly: true)]
```suggestion
        [DataField("stages", serverOnly: true)]
```

2022-06-28 13:58 UTC, metalgearsloth commented on Content.Shared/Disease/DiseaseCure.cs
> +        public readonly List<int> Stages = new() { 0 };
Any reason it can't be an array?

2022-06-28 22:17 UTC, EmoGarbage404 commented
I really wasn't sure what to do for testing, but everything else is addressed.

2022-07-08 03:44 UTC, metalgearsloth approved these changes

2022-07-08 03:44 UTC, merged