Add paper planes
space-wizards/space-station-14 pull request #9134
Opened 2022-06-24 23:56 UTC by themias

## About the PR 

- Adds an alt-verb to fold paper into a plane, and unfold the plane back to paper
- Saves the writing/stamp for *super discreet* communication
- Updated sprite to be directional so it looks correct when thrown
- Nyooom

**Screenshots**

<video src="https://user-images.githubusercontent.com/89101928/175749521-ca87cb07-692c-41fd-aaa3-1b789904a8c9.mp4"></video>

**Changelog**

:cl:
- add: Paper planes

2022-06-25 02:10 UTC, ike709 commented
They seem kind of... excessively bouncy.

2022-06-25 02:13 UTC, themias commented
> They seem kind of... excessively bouncy.

Yea I reduced the friction so they could go far, but not sure how to make them stop on collision. We could increase the friction to reduce the bouncy, but then no yeeting down the whole hallway.

2022-06-25 02:51 UTC, moonheart08 commented
> They seem kind of... excessively bouncy.

It's prolly fine and I think it'll lead to people doing funny things with them.

2022-06-25 05:24 UTC, themias commented
Fixed the bouncing by just killing the momentum on collision.

2022-06-25 20:14 UTC, DogZeroX commented
Use OBS nerd.

2022-06-27 15:28 UTC, themias commented
> Creating another entity and putting the paper inside of that seems unnecessary when you could just modify the paper?

My original thought was that this would be good to prevent writing/stamping the plane, avoid alt-verb priority stuff, and handle the sprite change automatically.

Although thinking more on it now, I'd imagine you could accomplish it by just adding the PaperPlaneComponent and checking for its presence/absence when determining the verbs/sprites/etc.

I can look into changing it to be that way if we think that's the way to go.

2022-06-27 15:28 UTC, metalgearsloth commented
sounds good to me

2022-06-28 17:44 UTC, themias commented
> sounds good to me

As part of updating this I *think* I've also fixed the issue with the NoSpinOnThrow not aligning properly, but not sure how the local vs world rotation works for stuff like shuttles, etc.

2022-07-03 02:23 UTC, mirrorcult requested changes

2022-07-03 02:23 UTC, mirrorcult commented on Content.Server/Paper/PaperSystem.cs
> +
feel like this should go after all the other examined stuff

2022-07-03 02:23 UTC, mirrorcult commented on Content.Server/Paper/Plane/PaperPlaneComponent.cs
> +        public string[] Tags = { "NoSpinOnThrow", "Trash" };
datafield this

2022-07-03 02:23 UTC, mirrorcult commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +        public sealed class FoldPlanceCancelledEvent : EntityEventArgs
```suggestion
        public sealed class FoldPlaneCancelledEvent : EntityEventArgs
```

2022-07-03 02:23 UTC, mirrorcult commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +            SubscribeLocalEvent<UnfoldPlaneCancelledEvent>(OnUnfoldPlaneCancel);
you can make the cancelled events directed too

2022-07-14 12:22 UTC, metalgearsloth requested changes

2022-07-14 12:22 UTC, metalgearsloth commented on Content.Client/Paper/UI/PaperSystem.cs
> +            args.Sprite.LayerSetVisible(PaperVisualLayers.Plane, writingStatus == PaperStatus.Plane);
Can't you just set the state of the paper layer?

2022-07-14 12:22 UTC, metalgearsloth commented on Content.Client/Paper/UI/PaperSystem.cs
> +    Plane
See above

2022-07-14 12:22 UTC, metalgearsloth commented on Content.Server/Paper/PaperComponent.cs
> +        public float FoldDelay = 1.0f;
Datafield + VV, also comment that it's for paper planes.

2022-07-14 12:22 UTC, metalgearsloth commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +        [Dependency] private readonly IEntityManager _entityManager = default!;
This is already a dependency on entitysystem so please remove.

2022-07-15 03:06 UTC, mirrorcult commented
needs reviews addressed

2022-07-15 22:20 UTC, themias commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +            }
The restitution helped cut down the bounce, thanks for pointing me to that. However, it still slides around quite a bit after collision if I don't set it back on the ground, so I'd like to still include that one line. That way it acts much more like you'd expect it to.

Thanks for all the reviews you've given me btw, I appreciate them.

2022-07-15 22:20 UTC, themias commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +            }
The restitution helped cut down the bounce, thanks for pointing me to that. However, it still slides around quite a bit after collision if I don't set it back on the ground, so I'd like to still include that one line. That way it acts much more like you'd expect it to.

Thanks for all the reviews you've given me btw, I appreciate them.

2022-07-24 04:12 UTC, metalgearsloth commented on Content.Server/Paper/Plane/PaperPlaneComponent.cs
> +        public string[] Tags = { "NoSpinOnThrow", "Trash" };
Also needs a customtypeserializer

2022-07-24 04:22 UTC, metalgearsloth requested changes

2022-07-24 04:22 UTC, metalgearsloth commented on Content.Server/Paper/Plane/PaperPlaneComponent.cs
> +        public readonly CollisionGroup CollisionMask = CollisionGroup.ItemMask;
Should this be overwriting thrown?

2022-07-24 04:22 UTC, metalgearsloth commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +        }
PaperComponent is unnecessary because you already have component.

Also these can probably just be struct events done by ref.

2022-07-24 04:22 UTC, metalgearsloth commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +                return;
Don't thrown items inherently ignore mobs?

2022-07-24 04:22 UTC, metalgearsloth commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +            paper.CancelToken = new CancellationTokenSource();
PaperPlaneComponent check should be done under TryFoldPlane.

2022-07-24 04:22 UTC, metalgearsloth commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +            EntityManager.RemoveComponent<PaperPlaneComponent>(plane.Owner);
Use the proxy methods for these + elsewhere, i.e. RemComp<T>

2022-07-24 04:22 UTC, metalgearsloth commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +        [Dependency] private DoAfterSystem _doAfterSystem = default!;
```suggestion
        [Dependency] private readonly DoAfterSystem _doAfterSystem = default!;
```

2022-07-24 04:26 UTC, AJCM-git requested changes
`PaperPlaneSystem` needs some formatting and some cleanup, there is a lot of repeated code that can be condensed because `PaperPlaneComponent` will always have `PaperComponent` and you can make checks with this in mind (see the verb example below). However, these component checks are a little redundant and more expensive booleans because you could merge the plane system and component with `PaperSystem` and add a folded/plane bool datafield to `PaperComponent` and simplify things a lot. So i recommend that you do that

2022-07-24 04:34 UTC, AJCM-git commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +        public override void Initialize()
Organize the handlers in the same order as the events are initialized in this method, also move all other methods below the handlers, makes reading the code easier

2022-07-24 04:35 UTC, AJCM-git commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +        private void OnAltVerbPlane(EntityUid uid, PaperPlaneComponent plane, GetVerbsEvent<AlternativeVerb> args)
Merge this with the other verb
```suggestion

```

2022-07-24 04:36 UTC, AJCM-git commented on Content.Server/Paper/Plane/PaperPlaneSystem.cs
> +        private void OnAltVerbPaper(EntityUid uid, PaperComponent paper, GetVerbsEvent<AlternativeVerb> args)
```suggestion
        private void OnAltVerbPlane(EntityUid uid, PaperComponent paper, GetVerbsEvent<AlternativeVerb> args)
        {
            if (!args.CanAccess || !args.CanInteract)
                return;

            if (TryComp<PaperPlaneComponent>(uid, out var plane))
            {
                AlternativeVerb unfoldVerb = new()
                {
                    Act = () => TryUnfoldPlane(plane.Owner, plane, args),
                    Text = Loc.GetString("paper-component-verb-unfold-plane"),
                    IconTexture = "/Textures/Interface/VerbIcons/fold.svg.192dpi.png",
                };

                args.Verbs.Add(unfoldVerb);
                return;
            }

            AlternativeVerb foldVerb = new()
            {
                Act = () => TryFoldPlane(paper.Owner, paper, args),
                Text = Loc.GetString("paper-component-verb-fold-plane"),
                IconTexture = "/Textures/Interface/VerbIcons/fold.svg.192dpi.png",
            };
            args.Verbs.Add(foldVerb);
        }
```

2022-08-05 10:49 UTC, closed without merging