Added missing drawdepth "WallTops" to directional windows.
space-wizards/space-station-14 pull request #9308
Opened 2022-06-30 17:59 UTC by BismarckShuffle

## Bugfix for #9095

They are no longer on default 0 Z-layer.

🆑 

- Gave appropriate drawdepth to computer frame, broken computer frame, and directional window sprites (all variations)

2022-06-30 18:43 UTC, mirrorcult requested changes

2022-06-30 18:43 UTC, mirrorcult commented on Resources/Prototypes/Entities/Structures/Windows/plasma.yml
> +    drawdepth: WallTops
instead of giving it to all the children, just give it to the parent `WindowDirectional`

2022-06-30 18:43 UTC, mirrorcult commented on Resources/Prototypes/Entities/Structures/Windows/plasma.yml
> +    drawdepth: WallTops
same applies to the ot her 2

2022-07-03 02:26 UTC, mirrorcult approved these changes

2022-07-03 02:26 UTC, merged

2022-07-03 02:31 UTC, Delete69 commented
Why would we lower the level by -1? There was a conversation about thindows not too long ago, and we figured they should be bumped up to 4 or 5, or ideal creat a 4.5 for them so they sit on top of things like tables.

2022-07-07 23:43 UTC, BismarckShuffle commented
closes #9095