Rotting fixes
space-wizards/space-station-14 pull request #9338
Opened 2022-07-01 21:50 UTC by Elijahrane

## About the PR 
Whoops, can't believe no one noticed some of this stuff didn't work for a week... Maybe that means miasma isn't even that bad?

Anyway, fixes:
1. Stuff can now be preserved before it rots.
2. AntiRottingContainers work again.

**Changelog**

:cl:
- fix: Morgues and body bags should behave much more reliably for stopping rotting.
- fix: You can preserve bodies so they never rot.

2022-07-01 23:03 UTC, EmoGarbage404 approved these changes

2022-07-03 02:15 UTC, mirrorcult requested changes

2022-07-03 02:15 UTC, mirrorcult commented on Content.Server/Atmos/Miasma/MiasmaSystem.cs
> +
this should probably ensure the bodypreserved so its not the job of the caller

2022-07-03 02:44 UTC, Elijahrane commented
Review addressed + tested in game

2022-07-03 02:46 UTC, mirrorcult approved these changes

2022-07-03 02:46 UTC, merged