Adds Research, Virology, Glass Maint Airlocks
space-wizards/space-station-14 pull request #9350
Opened 2022-07-02 11:01 UTC by 13spacemen

I tried out SS14 after SS13, went to my favorite department science, and noticed the airlocks were ugly as hell
Then I realized SS14 was using the old "science airlocks" instead of TG's nice purple "research airlocks"
The green virology airlocks were also missing

So I added those airlocks and a glass maint airlock too

Only map I edited so far is atlas.yml, never coded for SS14 before; replaced science airlocks with research ones, and replaced the virology room medical airlocks with virology ones

Ideally all or most of the science airlocks should be replaced by the research airlocks which look a lot better

:cl:
- add: Added purple research airlocks, green virology airlocks, and mapped them in

2022-07-02 11:16 UTC, Emisse requested changes
Remove the atlas.yml change otherwise it will mess up ongoing mapping PRs. Otherwise looks fine

2022-07-02 11:20 UTC, 13spacemen commented
@Emisse done

2022-07-02 11:21 UTC, Emisse approved these changes

2022-07-02 17:00 UTC, Peptide90 commented
The green on virology is pretty muted compared to our colour schemes I feel.

The sprites are decent but make sure they’re not out of place. Also glass maint kind of defeats the purpose of maint being dark but it’s not a bad idea for some variety if used sparingly, it’ll have its place.

2022-07-02 17:05 UTC, EmoGarbage404 commented
All the sprites seem to have assembly states that don't match the art style.

2022-07-02 17:06 UTC, Emisse commented
the assembly states are what all of our airlocks use already

2022-07-02 17:12 UTC, 13spacemen commented
@Peptide90 these sprites are all from TG, the virology green airlocks are the old r4407 medical airlocks, they used to be green before TG made them blue
As for glass maint, it's just a variant

@EmoGarbage404 yeah I noticed that was the case for all the other airlocks, so I just used the same assembly state as them

2022-07-03 02:44 UTC, mirrorcult requested changes

2022-07-03 02:44 UTC, mirrorcult commented on Resources/Prototypes/Entities/Structures/Doors/Airlocks/access.yml
> +
i think if we're going to add the darker purple research airlocks they should really just be sprite changes on the old sci airlocks, I don't see any reason to have both

2022-07-03 04:56 UTC, metalgearsloth commented
Do we have virology as a dept even?

2022-07-03 04:59 UTC, mirrorcult commented
no but they're fine to have as flavor since we do have disease ward sections of med

2022-07-15 02:15 UTC, mirrorcult commented
needs merging the research and sci airlocks as outlined then good to merge

2022-07-16 22:35 UTC, mirrorcult approved these changes

2022-07-16 22:35 UTC, merged