Add and replace alert sounds
space-wizards/space-station-14 pull request #9360
Opened 2022-07-02 21:21 UTC by DogZeroX

## About the PR 

**Screenshots**

**Changelog**

:cl:
- add: Blue alert now has its own alarm.
- add: Red alert alarm sounds more alarming.

2022-07-02 22:56 UTC, Mirino97 approved these changes

2022-07-03 02:42 UTC, mirrorcult requested changes

2022-07-03 02:42 UTC, mirrorcult commented on Resources/Audio/Misc/license.txt
> +bluealert.ogg was taken from: https://github.com/Skyrat-SS13/Skyrat13/commits/master/modular_skyrat/sound/misc/notice1.ogg
specify commit and not master

2022-07-03 03:52 UTC, mirrorcult approved these changes

2022-07-03 03:52 UTC, merged