Job-specific traitor items
space-wizards/space-station-14 pull request #9601
Opened 2022-07-10 17:02 UTC by EmoGarbage404

## About the PR 
Adds support for job-specific traitor items using a whitelist. The items available are tied to the PDA, so if you steal a T chaplains pda you could purchase T chaplain items.

Added the necronomicon as a test item, but more should be added soon.
**Screenshots**

**Changelog**

:cl:
- tweak: The Necronomicon can now be purchased by Traitor Chaplains in the uplink.

2022-07-14 14:40 UTC, metalgearsloth requested changes

2022-07-14 14:40 UTC, metalgearsloth commented on Content.Client/Traitor/Uplink/UplinkMenu.xaml.cs
> +            }
You shouldn't send these in the first place.

2022-07-14 14:40 UTC, metalgearsloth commented on Content.Server/Traitor/Uplink/UplinkSystem.cs
> +                }
the roles shitcode continues :despair:

2022-07-14 14:40 UTC, metalgearsloth commented on Content.Server/Traitor/Uplink/UplinkComponent.cs
> +        [ViewVariables] public HashSet<JobPrototype>? JobWhitelist = null;
Just use a string + typeserializer for it then you don't need jobprototype to be serializable. Also this doesn't have a datafield.

2022-07-14 14:57 UTC, EmoGarbage404 commented on Content.Server/Traitor/Uplink/UplinkSystem.cs
> +                }
you know it, baby

2022-07-15 04:26 UTC, metalgearsloth approved these changes

2022-07-15 04:26 UTC, merged