Gas tile overlay rejig
space-wizards/space-station-14 pull request #9619
Opened 2022-07-11 08:31 UTC by ElectroJr

- Merges `FireTileOverlay` into `GasTileOverlay`
- Generally rejigs how the gas data is sent to clients
  - Data is now sent via a single message per user, instead of a message per chunk per user.
  - Does some hashset & dictionary pooling now.
- Changes may or may not fix #9294. 
  - The changes are significant enough that it might just be fixed after this PR ~, with many new bugs in its place~.
  - But I don't know what the cause is/was or how to reproduce it, so can't be sure.
- Removes temperature data.
  - Was unused, with plans to have it eventually affect fire colour.
  - But until that gets added it just takes up data. 
  - Also it would either need to have temperature levels or some other way of ensuring that a 0.01 kelvin difference does not dirty a whole chunk.
- De-duplicates some PVS-related code in gas tiles & decals
  - There is now a `ChunkingSystem` that currently just exists so both systems can use the same `GetChunksForSession()`.
  - The functions were basically just copied over from the grid decal system.
  - There's still a lot of code duplication between the decal & gas chunking, a lot of the chunking stuff can probably be generalized, But this PR will already conflict with #9608 & I don't want to make that worse.

2022-07-14 04:24 UTC, AJCM-git requested changes

2022-07-24 03:52 UTC, mirrorcult commented
https://user-images.githubusercontent.com/19853115/180631361-e427c77f-e3c5-44b6-9c79-ba1ee2e238e1.mp4

old bug where the gas tile overlay becomes unshaded when effects are drawn has regressed in this PR

file overlay also just seems.. wrong? i cant tell if its like it on master, but start a plasma fire in saltern arrivals and just pay attention to the end when the fire dissipates from lack of oxygen, feels like its disappearing by chunk

2022-07-25 01:43 UTC, ElectroJr commented
> old bug where the gas tile overlay becomes unshaded when effects are drawn has regressed in this PR

Actually it looks like that's a separate bug (but also introduced by me), where overlays with the `WorldSpaceEntities` OverlaySpace can get drawn more than once, effectively leading to higher opacity gases for a few frames. I'll fix that in a separate engine PR

> feels like its disappearing by chunk

There was a bug, where a `LastUpdate == curTick` should have been `LastUpdate != curTick`.
Basically, the overlay was only updating whenever the chunk had not changed in the most recent tick, AFAICT it seems fine now, and appears to behave as it does on master.

2022-07-25 02:09 UTC, mirrorcult approved these changes

2022-07-25 02:10 UTC, merged