Donut-Vend add
space-wizards/space-station-14 pull request #9703
Opened 2022-07-14 05:32 UTC by Deahaka

## About the PR 
Add donut-vend for heavy roleplay officers. There are not many regular donuts in the build that would be worth inserting into the machine, so there are not enough of them now.
by [Theta Station](https://github.com/ThetaStation/ThetaStation).
**Screenshots**

![010101](https://user-images.githubusercontent.com/96499407/178906313-036191de-c1be-478a-96e1-55ecaacc8f02.png)

**Changelog**

:cl:
- add: Added donut-vend.

2022-07-14 05:35 UTC, Deahaka commented
![0000](https://user-images.githubusercontent.com/96499407/178907291-0a0fd1b8-86f9-45af-8dc4-2c552e0b1833.png)

![image](https://user-images.githubusercontent.com/96499407/178907117-dc64ad79-2746-49cb-b4a4-16878ed946b5.png)

2022-07-14 05:59 UTC, moonheart08 commented
> ![0000](https://user-images.githubusercontent.com/96499407/178907291-0a0fd1b8-86f9-45af-8dc4-2c552e0b1833.png)
> 
> ![image](https://user-images.githubusercontent.com/96499407/178907117-dc64ad79-2746-49cb-b4a4-16878ed946b5.png)

Excuse me?

2022-07-14 06:03 UTC, Deahaka commented
> Excuse me? Is there an issue here.

no, i'm just wondering why it works like this?

2022-07-14 06:05 UTC, moonheart08 commented
> > Excuse me? Is there an issue here.
> 
> no, i'm just wondering why it works like this?

Remie is a codeowner on something you added, so she gets added to the reviewer list.

2022-07-14 14:34 UTC, EmoGarbage404 commented on Resources/Locale/en-US/advertisements/vending/donut.ftl
> +﻿advertisement-donut-1 = Homer Simpson approves!
this probably doesn't matter that much but generally we want to stay copyright safe and avoid references to intellectual properties.

2022-07-14 14:36 UTC, EmoGarbage404 commented on Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
> +
maybe give it a point light like the other vendors?

2022-07-14 18:39 UTC, Deahaka commented
**Done**

2022-07-15 02:49 UTC, mirrorcult requested changes
looks great outside of that, will probably have to be mapped sparsely though

2022-07-15 02:49 UTC, mirrorcult commented on Resources/Prototypes/Catalog/VendingMachines/Advertisements/donut.yml
> +    - advertisement-donut-4
```suggestion
```

2022-07-15 02:49 UTC, mirrorcult commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/donut.yml
> +    FoodDonutBungo: 5
should look something like this for inventory imo, chocolate are the most common

```suggestion
    FoodDonutChocolate: 5
    FoodDonutApple: 3
    FoodDonutPink: 3
    FoodDonutBungo: 3
```

2022-07-17 07:51 UTC, Deahaka commented
Fixed as requested in review

2022-07-20 07:48 UTC, Partmedia commented
Presently, you can hack security vending machines to dispense donuts. If donut dispensers become more commonplace, should donuts be removed from the hacked security vendor list?

2022-07-20 08:26 UTC, Deahaka commented
Maybe, I just thought that it would be necessary to give donuts with cyanide for a hacked donut-vend

2022-07-28 10:37 UTC, Deahaka commented
> Presently, you can hack security vending machines to dispense donuts. If donut dispensers become more commonplace, should donuts be removed from the hacked security vendor list?

I looked, it contains a reference and for some reason boxes of donuts. I can remove the boxes, but I think the reference should be left there.

2022-07-31 02:58 UTC, merged