Add gas recyclers (WIP, sprite needed)
space-wizards/space-station-14 pull request #9934
Opened 2022-07-20 23:15 UTC by Partmedia

## About the PR 
Gas recyclers catalyze the conversion of carbon dioxide into oxygen. The gas recycler component takes gas from the input net, converts carbon dioxide to oxygen, and releases the result into the output net.

To make things more fun, the input net must be pressurized to 3 MPa and heated to at least 300 C; otherwise, no reaction will occur.

Game-mechanic wise, gas recyclers contain the catalyst for the conversion reaction, and therefore, requires no external power. However, the external pumps and heaters required to make the reaction happen still do.

This PR is WIP because it is missing a new sprite. (Help needed!)

**Screenshots**
Setting up the gas recycler requires an external pump to bring the pressure up to 3 MPa, and an external heater to bring the temperature up to 500 C:
![gas-recycler-setup](https://user-images.githubusercontent.com/3229565/180098038-03119437-b0b2-425f-a31e-3f39280d5521.png)

At which point the examine text shows:
![gas-recycler-examine](https://user-images.githubusercontent.com/3229565/180098052-c641fb70-4718-457a-a1c3-b947d12b783f.png)

If either the temperature or pressure is not enough to make the reaction happen:
![gas-recycler-examine-off](https://user-images.githubusercontent.com/3229565/180098072-29e21a12-5231-47ba-9e3e-79826e6aa729.png)

**Changelog**
:cl: notafet
- add: Gas recyclers convert waste carbon dioxide into breathable oxygen.

2022-07-20 23:37 UTC, ike709 commented
Would be nice if it required another gas like tritium.

2022-08-09 09:33 UTC, juliangiebel commented
Maybe it should require you to replace the catalyst once in a while and each conversion takes a different catalyst.

2022-08-09 11:14 UTC, juliangiebel reviewed
Good PR :smile:
I only found that you named the parameter for component in your event handlers `c` and single letter variables should be avoided imo.
Otherwise the code looks good. :+1:
I still have to check the PR out in game when I get home.

2022-08-09 17:31 UTC, Partmedia commented on Content.Server/Atmos/Piping/Binary/EntitySystems/GasRecyclerSystem.cs
> +        private void OnExamined(EntityUid uid, GasRecyclerComponent c, ExaminedEvent args)
I'll make the change.

2022-08-09 17:42 UTC, Partmedia commented on Content.Server/Atmos/Piping/Binary/EntitySystems/GasRecyclerSystem.cs
> +                inlet.Air.AdjustMoles(Gas.Nitrogen, nN2O);
The original intent of this was to convert only the fraction of gas that passes through the device. That bit of calculation is in my passive gate PR (not yet merged when I wrote this) and I didn't want to duplicate code.

I would need to move some common code from PassiveGateSystem to AtmosphereSystem and use it here. Would you be willing to review that in this PR or a separate one?

2022-08-09 18:15 UTC, Partmedia commented
> Maybe it should require you to replace the catalyst once in a while.

Catalysts [aren't generally consumed](https://en.wikipedia.org/wiki/Catalytic_converter). But it would be fun to damage them if someone tries to flow toxic gases through the recycler.

I don't want to make using recyclers too hard right now, though, especially since we have gas miners on all stations.

2022-08-09 18:18 UTC, juliangiebel commented
> > Maybe it should require you to replace the catalyst once in a while.
> 
> Catalysts [aren't generally consumed](https://en.wikipedia.org/wiki/Catalytic_converter). But it would be fun to damage them if someone tries to flow toxic gases through the recycler.
> 
> I don't want to make using recyclers too hard right now, though, especially since we have gas miners on all stations.

You're right. We can change things later on when gas miners get replaced / removed.

2022-08-09 18:22 UTC, juliangiebel commented on Content.Server/Atmos/Piping/Binary/EntitySystems/GasRecyclerSystem.cs
> +                inlet.Air.AdjustMoles(Gas.Nitrogen, nN2O);
It might be better to do that in a separate PR so this one doesn't have to wait on your passive gate PR.

2022-08-09 22:47 UTC, juliangiebel approved these changes

2022-09-01 02:47 UTC, mirrorcult requested changes
concept looks good to me. with this i'd be in favor of removing miners entirely from all maps and making the tanks simply decently pressurized at roundstart

2022-09-01 02:47 UTC, mirrorcult commented on Content.Server/Atmos/Piping/Binary/EntitySystems/GasRecyclerSystem.cs
> +            }
this is kind of a weird pattern, most everywhere else in the codebase would just do this

```suggestion
            if (comp.Reacting)
            {
                args.PushMarkup(Loc.GetString("gas-recycler-reacting"));
            }
```

etc for the others

2022-09-01 02:47 UTC, mirrorcult commented on Content.Server/Atmos/Piping/Binary/EntitySystems/GasRecyclerSystem.cs
> +        }
shouldnt this be on `AtmosDeviceEnabledEvent` rather than init (also as a counterpart to the disabled event being handled)

2022-09-01 02:47 UTC, mirrorcult commented on Content.Server/Atmos/Piping/Binary/EntitySystems/GasRecyclerSystem.cs
> +        private const float minPressure = 3000;  // 3 MPa
```suggestion
        private const float MinTemp = 300 + Atmospherics.T0C; // 300 C
        private const float MinPressure = 30 * Atmospherics.OneAtmosphere;  // 3 MPa
```

c# convention + define this in terms of other atmos constants

2022-09-01 02:49 UTC, mirrorcult commented
passive gate PR is also merged now so might want to integrate the gradual change in here?

2022-09-01 21:17 UTC, Partmedia commented
Sorry for the rebase/force-push; I needed to resync with upstream master.

Changes:

- Addressed reviewer feedback
- Implement gradual gas conversion. I ended up not using code from the passive gate to make it "feel" better in game. This involved adding a `RemoveVolume()` method, which is a separate change in a separate commit that should probably be left separate (i.e. rebase only, instead of squash-then-rebase).

I was able to convert atmos on a mid-sized map to work without miners and set up the gas recycler so that it would convert waste gases. Before removing miners anywhere though, I'd suggest having a bit of a transition period so I can write up what mappers need to add on the wiki, and see if any of the constants need some tweaking.

Also taking a look at the failing build right now.

2022-09-02 01:16 UTC, Partmedia commented
Fixed integration tests; fixed construction recipe.

2022-09-10 11:12 UTC, Peptide90 commented
Very odd that tests are failing due to a map file that isn't touched. Probably fine to merge.

2022-09-11 23:02 UTC, merged

2022-09-11 23:10 UTC, Partmedia commented
Thanks! For those following space exploration in the real world:

> MOXIE can reliably convert carbon dioxide into a small tree’s worth of oxygen... MOXIE works its magic by sucking in air, filtering out dust, and compressing and heating the gases to 800 degrees Celsius. The heated air flows through a solid oxide electrolysis instrument that splits carbon dioxide... into oxygen and carbon monoxide... then separates out the oxygen and expels the carbon monoxide, alongside other gases, as exhaust.

_Source: [NASA Can Now Reliably Produce a Tree’s Worth of Oxygen on Mars](https://singularityhub.com/2022/09/04/nasa-says-it-can-now-reliably-produce-a-trees-worth-of-oxygen-on-mars/), Sept. 4, 2022_