Zombie Fixes and Tweaks
space-wizards/space-station-14 pull request #9940
Opened 2022-07-21 01:27 UTC by EmoGarbage404

## About the PR 
some housecleaning

Closes #9930 

**Screenshots**

**Changelog**

:cl:
- tweak: Zombies now move slower than normal people.
- tweak: Zombies now do a bit of structure damage.
- tweak: Zombies now do further decreased damage to other zombies.
- fix: Zombies that were cuffed before turning now behave properly after being uncuffed.
- fix: Zombies no longer take damage over time from rotting.

2022-07-25 05:51 UTC, metalgearsloth requested changes

2022-07-25 05:51 UTC, metalgearsloth commented on Content.Server/Zombies/ZombieComponent.cs
> +        [ViewVariables]
readwrite

2022-07-26 14:00 UTC, mirrorcult requested changes

2022-07-26 14:00 UTC, mirrorcult commented on Content.Server/Zombies/ZombieSystem.cs
>          }
believe you also need to refresh movespeed modifiers when you zombify someone

2022-07-27 00:35 UTC, mirrorcult approved these changes

2022-07-27 00:35 UTC, merged