Update dat_fukken_disk.yml
space-wizards/space-station-14 pull request #9959
Opened 2022-07-22 12:40 UTC by GoodWheatley

Changed nuke disk and fake disk size to 5, because I don’t think it makes sense that a laser gun takes up less space than a floppy disk

## About the PR 

**Screenshots**

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

2022-07-22 14:04 UTC, Peptide90 approved these changes
Looks good to me.

2022-07-22 14:05 UTC, Peptide90 commented
Scratch that. You can actually just remove the item component all together and it’ll inherit size 5 from the parent.

2022-07-22 14:10 UTC, GoodWheatley commented
Ok, how do I do that?

2022-07-22 18:29 UTC, GoodWheatley commented
Alright after failing to figure this out, merging it in the current state it’s in won’t cause any problems, right?

2022-07-22 20:27 UTC, Peptide90 requested changes
Pointed out the bits I’d say to remove.

Otherwise if that’s not ideal then just remove the line that has size, that way it inherits size from the parent but the item component is still specifying the item sprite (this is in sprite component too so not sure it’s necessary)

2022-07-22 20:27 UTC, Peptide90 commented on Resources/Prototypes/Entities/Objects/Misc/dat_fukken_disk.yml
> -    size: 12
So lines 12 to 15 here are your item component. Delete them (everything up to the next component defined with the -)

2022-07-22 20:27 UTC, Peptide90 commented on Resources/Prototypes/Entities/Objects/Misc/dat_fukken_disk.yml
> -    size: 12
Same here, lines 30 to 33 delete.

2022-07-28 00:12 UTC, GoodWheatley commented
sorry, this is my first time using github, is there any way to accept the changes you've suggested?

2022-07-28 00:19 UTC, ElectroJr commented
You can just make the changes to your local branch, and then push them to your github. the PR will automatically update

2022-07-28 12:41 UTC, GoodWheatley commented
This is way more stressful than I thought it would be

2022-07-31 02:58 UTC, mirrorcult approved these changes

2022-07-31 02:58 UTC, merged