Zombie SFX
space-wizards/space-station-14 pull request #9976
Opened 2022-07-23 04:12 UTC by EmoGarbage404

## About the PR 
bout time i did some soundwork
**Screenshots**

**Changelog**

:cl:
- add: Zombies now have proper groaning sounds when they scream.
- add: Zombies will occasionally audibly groan or say a voice line.
- add: Zombies now groan when they are hit.

2022-07-23 04:13 UTC, EmoGarbage404 commented
Closes #9969

2022-07-24 11:23 UTC, metalgearsloth requested changes

2022-07-24 11:23 UTC, metalgearsloth commented on Content.Server/Zombies/ZombieComponent.cs
> +        [DataField("skinColor")]
Why remove VV?

2022-07-24 11:23 UTC, metalgearsloth commented on Content.Server/Zombies/ZombieSystem.cs
> +                _chat.TrySendInGameICMessage(uid, "generic automated groan", InGameICChatType.Speak, false);
Is this message intended?

2022-07-24 11:23 UTC, metalgearsloth commented on Content.Server/Zombies/ZombieSystem.cs
> +            {
You should have some kind of "ActiveZombieComponent" that gets tracked instead as it's just for the groan timer. Right now it's going to iterate every zombie every tick, dead or alive, so will lead to unnecessary iteration.

2022-07-24 11:23 UTC, metalgearsloth commented on Content.Server/Zombies/ZombieSystem.cs
> +                if (zombiecomp.Accumulator < 5) //generic number
Should use a const or datafield for these kinds of magic numbers.

2022-07-24 11:23 UTC, metalgearsloth commented on Content.Server/Zombies/ZombieSystem.cs
> +                    _vocal.TryScream(zombiecomp.Owner);
Should just make this its own method given it's the same code as above.

2022-07-24 11:23 UTC, metalgearsloth commented on Content.Server/Zombies/ZombieComponent.cs
> +        public float GroanChance = 0.1f;
comment i.e. reflecting it's from the groan accumulator OR from damage.

2022-07-27 21:37 UTC, mirrorcult commented on Content.Server/Zombies/ZombieComponent.cs
> +        [DataField("skinColor")]
datafield already implies viewvariables

2022-07-28 16:46 UTC, EmoGarbage404 commented
i am going to kill robusttoolbox

2022-08-08 03:16 UTC, metalgearsloth approved these changes

2022-08-08 03:16 UTC, merged